### ISSUE TITLE
Adding page number

### ISSUE THREAD

**Issue by navin11** [bpampuch/pdfmake#1000]
Hi, this plugin is really awesome. but I have one query, how to add page number for each page???

var pdfContent = {
                content: [
                    {
                        image: pdfIconsConfig.logo.svg,
                        alignment: 'center',
                        width:150
                    },
                    '\n', <data>,'\n',{
                        table: {
                            headerRows: 1,
                            widths: [ '6%','9%','8%','6%','9%','8%','6%','9%','8%','6%','9%','8%' ],
                            body: <data>
                        }
                    }, <data>
                ],footer:{
                    margin:10,
                    columns: [
                        {
                            fontSize: 9,
                            text:[
                                {
                                    text: '--------------------------------------------------------------------------' +
                                    '\n',
                                    margin: [0, 20]
                                },
                                {
                                    text: '© xyz pvt., ltd.'
                                }
                            ],
                            alignment: 'center'
                        }
                    ]
                },
                defaultStyle:{
                    italics: true,
                    font: 'openSans'
                }
            };

I'm generating pdf for dynamic data. each an every the count will be differ. so how can I add page number based on the data range??? thanks in advance...

**Comment by liborm85** [comment]
see https://github.com/bpampuch/pdfmake#headers-and-footers :

> ```
> var docDefinition = {
>  footer: function(currentPage, pageCount) { return currentPage.toString() + ' of ' + pageCount; },
>  header: function(currentPage, pageCount, pageSize) {
>    // you can apply any logic and return any valid pdfmake element
>
>    return [
>      { text: 'simple text', alignment: (currentPage % 2) ? 'left' : 'right' },
>      { canvas: [ { type: 'rect', x: 170, y: 32, w: pageSize.width - 170, h: 40 } ] }
>    ]
>  },
>  (...)
>};
>```

**Comment by navin11** [comment]
Before tried this, that time it wasn't working. Now I fixed thanks, I'll close this issue

**Comment by navin11** [comment]
hi @liborm85 I can't keep after company name in the footer???

**Comment by liborm85** [comment]
Yes, no problem, simple example:
```js
    footer: function(currentPage, pageCount) {
        return {
            margin:10,
            columns: [
            {
                fontSize: 9,
                text:[
                {
                text: '--------------------------------------------------------------------------' +
                '\n',
                margin: [0, 20]
                },
                {
                text: '© xyz pvt., ltd. ' + currentPage.toString() + ' of ' + pageCount,
                }
                ],
                alignment: 'center'
            }
            ]
        };
  
    },
```

**Comment by navin11** [comment]
Not working!!! it was giving the as "Uncaught ReferenceError: currentPage is not defined"...

**Comment by navin11** [comment]
Thanks!!! its working.

**Comment by bandham** [comment]
Hi, I started using this plugin few days back, is there a way where I can use the page numbers inside the content of the document definition, I tried using the same function which we use in header or footer but this doesn't work. instead its printing the function:
I tried something like below:
{text: function(currentPage, pageCount){return currentPage.toString()}, style:'alignCenter'},

Thanks is Advance

**Comment by India0** [comment]
I have same problem....
I far as I know you can access currentPage and pageCount from the header and footer section, and currentPage from the background section....

**Comment by liborm85** [comment]
`currentPage` is available from background-layer, see https://github.com/bpampuch/pdfmake#background-layer.

**Comment by India0** [comment]
I have tried this, but I want to display additional information only on the
last page. If I can get totalPages in background section to, it will
work..,.
"if (currentPage == totalPages) { I am on the last page }"

Is it possible to add totalPages parameter to the background section?

Thx your help!

2017-05-31 13:43 GMT+02:00 Libor M. <notifications@github.com>:

**Comment by blunatic** [comment]
+1, having pageCount in background layer section (like header and footer) would be very useful.

**Comment by India0** [comment]
Great! Thank you very much!

2017. okt. 19. 19:00 ezt írta ("Brendan" <notifications@github.com>):

**Comment by gabimoncha** [comment]
I am not sure if I understood correctly.
I am doing something like the example bellow, but the browser return this message: 

> Uncaught ReferenceError: footer is not defined

```
var docDefinition = {
 footer: function(currentPage) { return currentPage.toString()},
 content: [
      'some text',
      'some other text',
      ' maybe 2 or 3 iterations',
      footer
 ]
};
```

**Comment by ivansaldivar** [comment]
Variation to example of liborm85, this way not print number in first page:

```
	footer: function(currentPage, pageCount) {
	   if (currentPage!=1) {
	        return {
	            margin:5,
	            columns: [
	            {
	                fontSize: 9,
	                text:[
	                {
	                text: '_______________________________________________________________________________________________________________________' +
	                '\n',
	                margin: [0, 40]
	                },
	                {
	                text: 'CORPORACIÓN COGNOX LIMITADA © 2018 - ' + currentPage.toString() + ' / ' + pageCount,
	                }
	                ],
	                alignment: 'center'
	            }
	            ]
	        };
	   }
    },
```

**Comment by elyohan14** [comment]
> Yes, no problem, simple example:
> 
> ```js
>     footer: function(currentPage, pageCount) {
>         return {
>             margin:10,
>             columns: [
>             {
>                 fontSize: 9,
>                 text:[
>                 {
>                 text: '--------------------------------------------------------------------------' +
>                 '\n',
>                 margin: [0, 20]
>                 },
>                 {
>                 text: '© xyz pvt., ltd. ' + currentPage.toString() + ' of ' + pageCount,
>                 }
>                 ],
>                 alignment: 'center'
>             }
>             ]
>         };
>   
>     },
> ```

Thank you so much, maybe this is not related but how can I bind the this.variable inside the function?
```js
footer: function(currentPage, pageCount) {
        var vm = this
        return {
          columns: [
            vm.img2,
            {text: 'Dpto. Técnico\n', bold: true, alignment: 'left', fontSize: 12, margin: [-25, 13, 0, 0] },
            {text: 'Division Acuacultura\n', alignment: 'left', fontSize: 10, margin: [-147, 25, 0, 0]},
            {text: 'Guayaquil - Ecuador', bold: true, alignment: 'left', fontSize: 12, margin: [-269, 36, 0, 0] },
            {text: `_______________________\n${name}\n${pathologyAnalysis.user.technical_advisor.full_name ? pathologyAnalysis.user.technical_advisor.full_name : ''}\n`,bold:true, alignment: 'center', fontSize: 10, margin: [-70, 15, 0, 0] }
          ]
        }
      }
```
