### ISSUE TITLE
Opening  Generated PDF in the Same Tab/Page

### ISSUE THREAD

**Issue by thincmedia** [bpampuch/pdfmake#1003]
Thanks again for this great PDF generation compilation.

Is there any way of opening the generated pdf in the same tab/page based on the function:

pdfMake.createPdf(docDefinition).open();

Any help would be appreciated.

Kindest regards

**Comment by liborm85** [comment]
It is not supported.

duplicate: https://github.com/bpampuch/pdfmake/issues/631

**Comment by karunkhurana** [comment]
it use for open in same page 
   pdfMake.createPdf(docDefinition).open({}, window);

**Comment by quasi635** [comment]
Worked for me @karunkhurana!
