### ISSUE TITLE
A document definition generator

### ISSUE THREAD

**Issue by unluckynelson** [bpampuch/pdfmake#1004]
Hi Bartek

I really like your pdfmake library and have started a side-project to basically generate the document definitions from HTML for your library. Please check it out: http://powerprop.co.za/pdfmake-generator/
 I am busy writing the code to parse the HTML to JSON and am looking for solutions out there. Otherwise I would be writing the code myself. Let me know if you are interested in collaborating

Cheers
johan

**Comment by Wabbala** [comment]
👍
