### ISSUE TITLE
Zero-width space

### ISSUE THREAD

**Issue by alexisab** [bpampuch/pdfmake#1007]
Hi everyone,

I try to allow PDFMake to cut a word by inserting a Zero-width space character. It works but it prints strange character : 
![capture du 2017-05-22 15-33-28](https://cloud.githubusercontent.com/assets/11648546/26314502/770be1a6-3f0e-11e7-846f-53c9bcca7aee.png)

I use Source sans pro font. Do you have an idea on how to fix this ?

**Comment by liborm85** [comment]
Source Sans Pro not supported zero width character, see issue https://github.com/adobe-fonts/source-sans-pro/issues/58

**Comment by liborm85** [comment]
In new pdfmake release will be solved wrapping long words, see https://github.com/bpampuch/pdfmake/issues/204#issuecomment-302877081 And will not need to be used zero width hack.

**Comment by Ekkapap** [comment]
I Need Zero-width space too
my probrem is text alignment justify that show in picture
![image](https://user-images.githubusercontent.com/19544110/121460831-da25e400-c9d7-11eb-8b39-2deff28e7cc7.png)
