### ISSUE TITLE
Chinese characters - dots missing in numbers

### ISSUE THREAD

**Issue by qerad** [bpampuch/pdfmake#1008]
Hi,
I tried to use Chinese font. The Chinese characters works fine. I have a problem with numbers. The dots are missing. Example: Instead of "54.22" it shows "54 22".
I added a base64 font to vfs_fonts.js and then set new font in code.
I tried with SourceHanSansTC and NotoSansCJKtc.

<a href="http://pl.tinypic.com?ref=21dml2p" target="_blank"><img src="http://i66.tinypic.com/21dml2p.png" border="0" alt="Image and video hosting by TinyPic"></a>

Can you recommend other font or other solution?

**Comment by liborm85** [comment]
Test with SourceHanSansSC font:
![pdf-screen](https://user-images.githubusercontent.com/1298652/27011519-618d0530-4ebd-11e7-809f-06db1ea58683.png)

All is ok.

**Comment by qerad** [comment]
The simple text test went ok. The problem occurs when content is from ui grid.

**Comment by liborm85** [comment]
Then look for a problem in ui grid.
