### ISSUE TITLE
How to Use Standard Fonts

### ISSUE THREAD

**Issue by Mikolaytis** [bpampuch/pdfmake#101]
How to use standard fonts? 
Found them in source code
PDFFont.prototype._standardFonts = ["Courier", "Courier-Bold", "Courier-Oblique", "Courier-BoldOblique", "Helvetica", "Helvetica-Bold", "Helvetica-Oblique", "Helvetica-BoldOblique", "Times-Roman", "Times-Bold", "Times-Italic", "Times-BoldItalic", "Symbol", "ZapfDingbats"];

I have tried to use that font names instead of font file names in VFS. But i got a exception: Uncaught TypeError: Cannot read property 'widthOfString' of null

**Comment by loverdrive** [comment]
Any news about it?

**Comment by liborm85** [comment]
It will not be implemented.

**Comment by imhansi** [comment]
Hi,

I'm currently evaluating moving to this framework from PDFKit. The lack of using named standard fonts like in PDFKit is the main issue for me. 

A few quick questions:
1) Why would adding support for this increase the size of the library? Wouldn't it just be passing the font name through to PDFKit? If I understand correctly, the result PDF will simply use the named font on the system that opened it and the font won't actually need to be embedded into the PDF.

2) If there is no planned support for this feature I'll most likely try to implement it myself and open an PR. Any suggestions on how I can get started?

Thanks!

**Comment by liborm85** [comment]
Standard 14 fonts are supported by pdfmake on server-side by default.
I'm implemented command for building with standard fonts for client-side by commit https://github.com/bpampuch/pdfmake/commit/903f767a255725f70e2fc962eea512522f571753.

How to use standard 14 fonts in pdfmake are described in [wiki page](https://github.com/bpampuch/pdfmake/wiki/Standard-14-fonts).
