### ISSUE TITLE
Canvas line moving down and right on repeated prints

### ISSUE THREAD

**Issue by jeremymauro** [bpampuch/pdfmake#1010]
I have a line on a page that moves down and right when I call `pdfMake.createPdf(dd).download()` a second time. Every call moves it more. I am using `v0.1.28`.

```
{  canvas: [
        { type: 'line', x1: 0, y1: 3, x2: 492, y2: 3, lineWidth: 0.5 },
      ]
 }
...
pageMargins:[20,20,20,20]
...
```
I added some console.logs to the src code and `resetXYs()` is fired many times on the first `pdfMake.createPdf(dd).download()`, but it doesn't fire at all on additional calls.

The first print renders the line `x1: 0` `y1: 3` ` x2: 492` `y2: 3`

The second print renders the line `x1: 20` `y1: 76.71875` ` x2: 512`  `y2: 76.71875`

..third `x1: 40`  `y1: 150.4375`  `x2: 532`  `y2: 150.4375`

**Comment by liborm85** [comment]
It's a strange calling multiple times generating same docDefinition for pdf.

**Comment by liborm85** [comment]
You can't use same docDefinition variable for multiple pdfmake calls. If necessary, you need to clone  variable.
