### ISSUE TITLE
JS-Graphic to pdf

### ISSUE THREAD

**Issue by hyllos7** [bpampuch/pdfmake#1011]
Hi,
I've created a js-graphic in a canvas and transfer it via getDataUrl as a PNG and safe it as a js-variable (eg. var img). How can I include this "img" as an image to the pdf? 
{      image: 'img',    } doesn't work.

best, Martin.

**Comment by liborm85** [comment]
Simple example of usage canvas and image element:
```js
function createCanvas() {
    var canvas = document.createElement('canvas');
    
    var ctx = canvas.getContext("2d");
    ctx.moveTo(0,0);
    ctx.lineTo(200,100);
    ctx.stroke();
    
    return canvas.toDataURL();
}

var canvasImage = createCanvas();

var dd = {
	content: [
		'Image from canvas:',
		{image: canvasImage}
	]
}
```

**Comment by hyllos7** [comment]
many thanks for your answer, I tried to apply your advise, but it still doesn't work. Here is my code. 

```
var img = new Image();
img.setAttribute('crossOrigin', 'anonymous');
img.src = myChart.getDataURL({
    type:"png",
    pixelRatio: 2,
    backgroundColor: '#fff',
    excludeComponents:['toolbox']
});

 var docDefinition =
	 {content: [{
      'Image from mychart:',
		{image: img}
		}
	],
	 };
```

**Comment by liborm85** [comment]
Then something like this:

```js
var base64Image = myChart.getDataURL({
    type:"png",
    pixelRatio: 2,
    backgroundColor: '#fff',
    excludeComponents:['toolbox']
});

var dd = {
	content: [
		'Image from mychart:',
		{
			image: base64Image
			width: 200
		}
	]
}
```

**Comment by hyllos7** [comment]
many thanks again, this works perfectly with jspdf, but unfornutaly I
cannot make it work with the better pdfmake. the automatic line break would
save me tons of time.
best, Martin.


2017-05-24 10:45 GMT+02:00 Libor M. <notifications@github.com>:

**Comment by liborm85** [comment]
`myChart` is ECharts - https://ecomfe.github.io/echarts/index-en.html - library?

I'm test it with ECharts and it works ok. Only the problem is if the image of chart is very large, then it is not displayed in PDF. Need to define `width` or/and `height` property in image (as shown above post).

**Comment by hyllos7** [comment]
yes, that's the library - I'm probably just not experienced enough with js.
I now created 2 versions, the first with jspdf (works), the second with
pdfmake (doesn't work). Could you have a look at the code with the google
developer tool?

http://www.scaoo.com/cei/balken/balken3.php


http://www.scaoo.com/cei/balken/balken4.php


thank you very much for your support!


2017-05-24 12:03 GMT+02:00 Libor M. <notifications@github.com>:

**Comment by liborm85** [comment]
I fixed it.
Download, unpack and run this: [balken4.html.gz](https://github.com/bpampuch/pdfmake/files/1025290/balken4.html.gz)
Works ok, try it.

**Comment by hyllos7** [comment]
fantastic! apparently, it's what you had written before, I don't know what
I did wrong.
You made my day, thanks a million!!!



2017-05-24 13:16 GMT+02:00 Libor M. <notifications@github.com>:

**Comment by EthicalHackingCOP** [comment]
> , {image: canvasImage}

hi man ! 
i'm trying to show a chart !

but i got a error on base64 hash

I got this hash
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAASwAAACWCAYAAABkW7XSAAAGiElEQVR4Xu3aTXIQORBEYXEz5mYcDU4GMROGGDts3L/qytLHxhu1lPWy/MILvowxvo8xfo4xvo0xfgz/EEAAgaIEvrzk+voiLOIqWpRYCCAwxm9h/WZBXLYCAQTKEngrLOIqW5VgCCDwkbCIy24ggEA5Ap8Ji7jKVSYQAusS2Cos4lp3R0yOQBkCe4VFXGWqEwSB9QgcFRZxrbcrJkbgcQJnhUVcj1coAALrELhKWMS1zs6YFIHHCFwtLOJ6rEoPI9CfwF3CIq7+u2NCBKYTuFtYxDW9Ug8i0JfALGERV98dMhkC0wjMFhZxTavWQwj0I/CUsIir3y6ZCIHbCTwtLOK6vWIPINCHQBVhEVefnTIJArcRqCYs4rqtahcjkE+gqrCIK3+3TIDA5QSqC4u4Lq/chQjkEkgRFnHl7pjkCFxGIE1YxHVZ9S5CII9AqrCIK2/XJEbgNIF0YRHX6RVwAQI5BLoIi7hydk5SBA4T6CYs4jq8Cj5EoD6BrsIirvq7JyECuwl0FxZx7V4JHyBQl8AqwiKuujsoGQKbCawmLOLavBoOIlCPwKrCIq56uygRAp8SWF1YxPXpijiAQB0ChPW6i69jjG9jjJ8vP3/UqUoSBBAgrPd3gLj8biBQkABh/b0U4iq4tCKtS4CwtnVPXNs4OYXArQQIax9e4trHy2kELiVAWMdwEtcxbr5C4BQBwjqFbxDXOX6+RmAXAcLahevDw8R1DUe3IPBXAoR17YIQ17U83YbAKwKEdc9CENc9XN26OAHCuncBiOtevm5fjABhzSmcuOZw9kpzAoQ1t2Dimsvba80IENYzhRLXM9y9Gk6AsJ4tkLie5e/1MAKEVaMw4qrRgxTFCRBWrYKIq1Yf0hQjQFjFCnmJQ1w1e5HqYQKE9XABnzxPXLX7kW4yAcKaDPzgc8R1EJzPehEgrKw+iSurL2kvJkBYFwOddB1xTQLtmVoECKtWH3vTENdeYs5HEyCs6Pr+hCeuHj2a4hMChNVrRYirV5+meUOAsHquBHH17HX5qQir9woQV+9+l5uOsNaonLjW6Ln9lITVvuJXAxLXWn23m5aw2lW6aSDi2oTJoWoECKtaI3PzENdc3l47SYCwTgJs8jlxNSmy+xiE1b3hffMR1z5eTk8mQFiTgYc8R1whRa0Wk7BWa3zfvMS1j5fTNxMgrJsBN7meuJoUmT4GYaU3ODc/cc3l7bU3BAjLShwhQFxHqPnmNAHCOo1w6QuIa+n65w9PWPOZd3yRuDq2WnAmwipYSnAk4gouLyE6YSW0lJeRuPI6i0hMWBE1xYYkrtjqagYnrJq9dEtFXN0afWgewnoI/KLPEteixV81NmFdRdI9ewgQ1x5azv4hQFiW4UkCxPUk/cC3CSuwtIaRiathqXeMRFh3UHXnUQLEdZTcIt8R1iJFh41JXGGFzYpLWLNIe+cIAeI6Qq3xN4TVuNxGoxFXozLPjEJYZ+j5djYB4ppNvNh7hFWsEHE2ESCuTZj6HSKsfp2uNBFxrdT2GIOwFiu86bjE1bTYt2MR1iJFLzImcTUvmrCaF7zoeMTVtHjCalqssf4jQFzNFoGwmhVqnHcJEFeTxSCsJkUaYxMB4tqEqe4hwqrbjWT3ESCu+9jeejNh3YrX5cUJEFfxgvy3hrCCxJ1CgLimYD7/iL+wzjN0Qx8CxFW8S8IqXpB4jxD4v7j+eSSBR98lQFgWA4GPCfwrru8A1SFAWHW6kAQBBD4hQFhWBAEEYggQVkxVgiKAAGHZAQQQiCFAWDFVCYoAAoRlBxBAIIYAYcVUJSgCCBCWHUAAgRgChBVTlaAIIEBYdgABBGIIEFZMVYIigABh2QEEEIghQFgxVQmKAAKEZQcQQCCGAGHFVCUoAggQlh1AAIEYAoQVU5WgCCBAWHYAAQRiCBBWTFWCIoAAYdkBBBCIIUBYMVUJigAChGUHEEAghgBhxVQlKAIIEJYdQACBGAKEFVOVoAggQFh2AAEEYggQVkxVgiKAAGHZAQQQiCFAWDFVCYoAAoRlBxBAIIYAYcVUJSgCCBCWHUAAgRgChBVTlaAIIEBYdgABBGIIEFZMVYIigABh2QEEEIghQFgxVQmKAAKEZQcQQCCGAGHFVCUoAggQlh1AAIEYAoQVU5WgCCBAWHYAAQRiCBBWTFWCIoAAYdkBBBCIIUBYMVUJigAChGUHEEAghgBhxVQlKAIIEJYdQACBGAKEFVOVoAgg8AvQryymYqgkPQAAAABJRU5ErkJggg==

but, when i put it in the img tag , it say me that !
Uncaught RangeError: Source is too large

any hint ?
