### ISSUE TITLE
Getting blank window

### ISSUE THREAD

**Issue by bennyAG** [bpampuch/pdfmake#1014]
Just before the file download dialog box appears i get an open empty window that i can close.
There is also an error coming from the library:

Uncaught TypeError: Cannot create property 'href' on string 'about:blank'
pdfmake.min.js:2 

Some has a clue?

**Comment by bennyAG** [comment]
It also happens with minimal code see:
docDefinition.content = [];
        docDefinition.styles = {
            smallText: {
                fontSize: 7,
            },
            filter:{
                fontSize:12,
                color:'red',
            }
        };
 pdfMake.createPdf(docDefinition).open();
        pdfMake.createPdf(docDefinition).download('search.pdf');

**Comment by bennyAG** [comment]
Os: ubuntu,
browser:chrome

**Comment by liborm85** [comment]
You have to use `open()` or `download()`, both do not work at the same time.
And `download()` works on all browsers, `open()` not. See supported browsers: https://github.com/bpampuch/pdfmake/issues/800. In Chrome works only with disabled AdBlock.

**Comment by bennyAG** [comment]
Not sure it was clear from the instructions.
But thank you for the fast response.
