### ISSUE TITLE
Cannot add line

### ISSUE THREAD

**Issue by bennyAG** [bpampuch/pdfmake#1017]
Getting : angular.js:13920 Unrecognized document structure: {"type":"line","x1":40,"y1":60,"x2":260,"y2":60,"lineWidth":3,"_margin":null}

the code is:
docDefinition.content.push({
                    type: 'line',
                    x1: 40, y1: 60,
                    x2: 260, y2: 60,
                    lineWidth: 3
                });

**Comment by Wabbala** [comment]
@bennyAG,

What did you do to fix this issue? Just as a reference for others in case
they run into the same issue.

**Comment by bennyAG** [comment]
My error here that it should be added to a canvas element ,
anyway there was another bug and I just gave up on this feature.
the quickest fix.
