### ISSUE TITLE
Download PDF in the ionic app

### ISSUE THREAD

**Issue by sergiosanabria** [bpampuch/pdfmake#1019]
I am using pdfmake to create a PDF file with IONIC 2. In the browser, running IONIC SERVE works for me without problems.
The problem is when I build the app for android. In the cell phone does not download the file, as if it does in the browser.

Any help or advice about it, thanks

**Comment by machadoapoena** [comment]
For running in mobile you need to use cordova api.
tips

`
var pdfDocument = $window.pdfMake.createPdf(obj);
pdfDocument.getBuffer(function(dataURL) {
    var ConabCordovaFileFactory = $injector.get('ConabCordovaFileFactory');
    ConabCordovaFileFactory.exportFile(tempName, dataURL, 'application/pdf');
});

exportFile: function(fileName, dataURL, type) {
				var utf8 = new Uint8Array(dataURL);
				var binaryArray = utf8.buffer;
				$cordovaFile.writeFile(cordova.file.externalDataDirectory, fileName, binaryArray, true).then(function (success) {
					$cordovaFileOpener2.open(cordova.file.externalDataDirectory+fileName,type).then(function() {
						$log.debug(CONAB_CORDOVA_FACTORY_CONSTANTS.MSG_ARQUIVO_GERADO_SUCESSO);
					}, function(err) {});
				}, function (error) {
					$log.debug(CONAB_CORDOVA_FACTORY_CONSTANTS.MSG_ERROR_GERAR_ARQUIVO);
				});
			}
`
