### ISSUE TITLE
Table migration

### ISSUE THREAD

**Issue by AndreyZavarin** [bpampuch/pdfmake#1020]
### There was a problem with moving the table to a new page.
Code sample:
` {
      table: {
        headerRows: 2,
        widths: [30, 150,'*'],

        body: [
          [{text: 'HELLO WORLD =)' ,fontSize: 10, bold: true, colSpan:3}, '', ''],
          [{text: '№\nп/п', alignment: 'center'}, {text:'Условие',alignment: 'center'}, {text: 'Содержание условия',alignment: 'center'}],
          ['1.', '...', '...'],
          ['2.', '...', '...'],
          ...
        ]
      },
      fontSize: 10,
      margin: [0, 10, 0, 0],
      layout: {
        paddingLeft: function(i, node) { return 2; },
        paddingRight: function(i, node) { return 2; },
        paddingTop: function(i, node) { return 2; },
        paddingBottom: function(i, node) { return 2; }
      },
    },`
1 page:
![table migration](https://cloud.githubusercontent.com/assets/15002874/26484879/37f71f20-41fd-11e7-9917-563158844cba.png)

2 page
![table migration](https://cloud.githubusercontent.com/assets/15002874/26484636/edd16352-41fb-11e7-9454-95199e876f6b.png)

**Comment by liborm85** [comment]
It's known bug (see https://github.com/bpampuch/pdfmake/issues/247). For fix use `dontBreakRows: true` in `table` element.

**Comment by AndreyZavarin** [comment]
Thanks!
