### ISSUE TITLE
how can i merge two pdf ..?? 

### ISSUE THREAD

**Issue by Ashvin9490** [bpampuch/pdfmake#1022]
I am having a structure where i have some attachments as images which i am adding into pdf ... that is working fine..!!
but i have some attachments in pdf format , how can i attach this pdfs to the pdf generated by pdfmake ..??

**Comment by liborm85** [comment]
Attach pdf files into pdf are not possible.

**Comment by Ashvin9490** [comment]
any other solution..?? where i can merger two pdf ..??

**Comment by liborm85** [comment]
This library does not edit or merge pdf files. Library is only for generating pdf.

**Comment by Ashvin9490** [comment]
ok ...!! thanks for your valuable time..!!

**Comment by nuxwin** [comment]
@liborm85 

Good evening

Even though, that issue has been closed, I think that it could be really aswome if such a feature could be implemented in a near future. For my compagny, I've writen a UI that make possible to build some PDFs using your library. That UI make it possible to select content from many datasource, then build a PDF for each of them. Right now, we build and store each PDF as data URL in our database and finally, we make an XHR request to get back those PDFs in a single PDF which is opened in another window to make the end user able to view or print it. On the server side, we make use of the PHP FPDI library to merge the PDFs... That process, on the server side is sometime, depending on number of PDFs to merge, a long running process. We would really prefer have your library make all that job. Would it be so difficult for you to add a function which would add a PDF in another ?

Thank you for your time. You works is much appreciated. Your library is really great and from my point of view , really better than it jspdf alternative.

**Comment by liborm85** [comment]
Merging PDF documents is out of pdfmake scope.
