### ISSUE TITLE
save pdf on server

### ISSUE THREAD

**Issue by Ashvin9490** [bpampuch/pdfmake#1026]
How can I save pdf on server folder instead of downloading it ..??

**Comment by liborm85** [comment]
See this example: https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js

**Comment by Ashvin9490** [comment]
I saw above link... i am generating pdf in javascript which is getting downloaded but i want to store it on server ... how can i do it with get request ..??

**Comment by Ashvin9490** [comment]
want to use both code javascript as well as server side ... how can i pass docDefination to server and save pdf there in server ..??

**Comment by Ashvin9490** [comment]
front end //
var parameters = { docDef: docDefinition };
$.get('/relatedJsonData/mergePdf',parameters, function(data) {
       console.log(data);
});

back end//  API

exports.mergePdf = function(req, res){
var pdfd = pdfMake.createPdfKitDocument(req.query.docDef);
    pdfd.pipe(fs.createWriteStream('../final.pdf'));
    pdfd.end();
};

**Comment by liborm85** [comment]
That code does not work? Looks probably it is correct. Is throwed any error?

**Comment by Ashvin9490** [comment]
PdfPrinter.createPdf is not a function

**Comment by liborm85** [comment]
It depends how you have installed pdfmake. Important is right `require`.
If you use `npm install pdfmake`, so then this:
```js
var PdfPrinter = require('pdfmake');
var printer = new PdfPrinter(fonts);

var pdfDoc = printer.createPdfKitDocument(docDefinition);
```

**Comment by Ashvin9490** [comment]
Cannot read property 'length' of undefined
when posting buffer to server ... if i get succeed in passing buffer to server, it will also be really helpful
pdfDocGenerator.getBuffer(function(buffer){
 console.log(buffer);
$.post('/relatedJsonData/mergePdf',buffer , function(data) {
	                           
});
});

**Comment by liborm85** [comment]
What line does this error? Is it in pdfmake? Maybe `docDefinition` is in wrong format. Is `req.query.docDef` a valid object?

**Comment by Ashvin9490** [comment]
Yes it is not giving me correct format... so now i am sending pdf buffer but it is not hitting endpoint,
when 
pdfDocGenerator.getBuffer(function(buffer){
bytesArray = new Uint8Array(buffer);
console.log(bytesArray);
$.post('/relatedJsonData/mergePdf',bytesArray , function(data) {
	console.log(data);
 });
});

and when i post base64 or dataURL it hit endpoint
pdfDocGenerator.getBase64(function(encodedString) {
data = encodedString;
console.log(data);
console.log(data.length);
$.post('/relatedJsonData/mergePdf', data, function(data) {
 console.log(data);
 });
});

**Comment by Ashvin9490** [comment]
please help me out to save this client side generated pdf  in sserver side

**Comment by liborm85** [comment]
from [readme](https://github.com/bpampuch/pdfmake#get-the-pdf-as-buffer):

```js
var docDefinition = { .... };

var pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBuffer((buffer) => {
	// here you have generated pdf buffer
	// here you can do what you want
});
```

or getBuffer in [readme](https://github.com/bpampuch/pdfmake#get-the-pdf-as-base64-data).

In callback you can send data to the server (eg. ajax) and then return the file to the user (pdfmake using [FileSaver.js library](https://github.com/eligrey/FileSaver.js/).  The specific way of realization depends on js framework you use.
