### ISSUE TITLE
Issue with dynamic pageBreakBefore since v0.1.29

### ISSUE THREAD

**Issue by wbrekel** [bpampuch/pdfmake#1028]
This function: 
`pageBreakBefore: function(currentNode) {return currentNode.startPosition.top >= 300;},`
causes an issue since 0.1.29 in some (but not all) situations, whereas it worked consistently in 0.1.28.

PDF does not render, the console error is
`pdfmake.min.js:5 Uncaught Unrecognized document structure: {"_span":true,"_minWidth":0,"_maxWidth":0}`

To reproduce the error, add the function to the TABLES example in the [playground](http://pdfmake.org/playground.html):

from line 437:
`
...

	],
	pageBreakBefore: function(currentNode) {return currentNode.startPosition.top >= 300;},
	styles: {
		header: {
			fontSize: 18,
			bold: true,
			margin: [0, 0, 0, 10]
		},

...
`
This will throw an error. Doing the same in the STYLES1 example (insert on line 28, just before styles attribute) works fine though.

**Comment by liborm85** [comment]
Tonight will be a new version with a bugfix.

**Comment by wbrekel** [comment]
Would be great, thanks in advance!

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/51c237abc000d9b652f9c580633de896aba06225.

Version 0.1.30 released.

**Comment by timwb** [comment]
@wbrekel test notification
