### ISSUE TITLE
Rendering issue

### ISSUE THREAD

**Issue by Mikolaytis** [bpampuch/pdfmake#103]
After long cyrillic text all english chars rendering breaks.
Check this out in playground:

var dd = {
  content: [
    'Космона́вт (астрона́вт), — человек, проводящий испытания и эксплуатацию космической техники в космическом полёте[1]. Понятие космического полёта в разных странах различно. Согласно классификации Международной федерации аэронавтики (ФАИ), космическим считается полёт, высота которого превышает 100 км. Согласно классификации Военно-воздушных сил США (ВВС США, United State Air Forces, USAF), космическим полётом считается полёт, высота которого превышает 50 миль (80 км 467 м). В России же космическим полётом называется орбитальный полёт, — то есть аппарат должен сделать хотя бы один виток вокруг Земли. Именно поэтому общее количество космонавтов отличается от источника к источнику. Содержание  [убрать]  1 Статистика 2 Этимология и использование терминов 2.1 Этимология 2.2 Происхождение и история термина «космонавт» 2.3 Происхождение термина «астронавт» 2.4 Международные синонимы слова «космонавт» 2.5 Использование термина 3 Исторические факты 4 Подготовка космонавтов 5 Международный космос 6 Погибшие космонавты 7 См. также 8 Литература 9 Ссылки 10 Источники Статистика[править | править вики-текст] На 30 сентября 2014 года насчитывается 552 человека, совершивших орбитальный космический полёт; 7 человек[2][3][4][5], совершивших космический полёт по баллистической траектории высотой более 100 км (классификация ФАИ); 6 человек, совершивших космический полёт по баллистической траектории высотой более 50 миль, но ниже 100 км (классификация ВВС США). Среди космонавтов 56 женщин. По данным на 1 мая 2009 года, космонавты планеты провели за пределами Земли свыше 10 000 человеко-дней[6], включая более 100 человеко-дней выходов в открытый космос. Представители 35 ныне существующих государств побывали на орбите Земли (См. Первые полёты космонавтов различных стран мира). Этимология и использование терминов[править | править вики-текст] Этимология[править | править вики-текст] В словарях указывают, что слово «космонавт» образовано от греческих слов «космос» (греч. κόσμος), обозначающего «упорядоченность», «строение», «мир», «вселенную», «мироздание», и «наута» (греч. ναυτα): «мореход», «моряк», «мореплаватель», «спутник». Но стоит отметить, что термин «космонавтика» (как и «астронавтика») произошёл раньше, и разбирать этимологию корректнее от этого слова — от «космос» (греч. κόσμος) и «наутика» (греч. ναυτικη, которое в греческом языке всё же вторично от греч. ναυτα — «моряк») — «искусство мореплавания», «кораблевождение». ',
    'paragraph 2',
    'Some Eng Text'
  ]
}

**Comment by jthoenes** [comment]
Dublicate of #165
