### ISSUE TITLE
caching pages/layout calculations

### ISSUE THREAD

**Issue by Vadi** [bpampuch/pdfmake#1034]
Not sure if this feature is in pipeline. The pdfs that has 100s of pages most of them are static and does not required to regenerate every time. Is there an approach to implement caching? For example, save the layout generation and re-use or keep the page stream in memory and reuse it. Any headway is greatly appreciated. I can provide a PR in case this is useful to others.

**Comment by liborm85** [comment]
Version 0.1.29 contains fonts caching, which dramatically increased performance.  Caching of full pdf documents will not be supported. It has to solve the application that implements pdfmake library.
