### ISSUE TITLE
how to define docDefinition to have all the data of a <div>

### ISSUE THREAD

**Issue by BRAEIKMiled** [bpampuch/pdfmake#1038]
Hi, 

I'm developping an app with `cordova `and `Angularjs `and I want to generate pdf file from my html page but I don't know how to define the `docDefinition `to point to all the data in my page.

Kind regards

**Comment by liborm85** [comment]
Samples for `docDefinition` they are described in [playground](http://pdfmake.org/playground.html).

`docDefinition` is not html format (see https://github.com/bpampuch/pdfmake/issues/205).
