### ISSUE TITLE
Problem with the resolution of the pdf

### ISSUE THREAD

**Issue by MiDDiO** [bpampuch/pdfmake#1041]
Hi guys,
i'm programming in javascript the project is print a pdf of 20 pages the problem is that i'm in the third page and my resolution of the pdf is a mess.. someone can help me? 
I will show the code of the page and if it possible the pdf.
               
```
var fisio={
         fontSize:10,
	table:{
	widths:['40%','10%','25%','25%'],
	body:[
	[{text:' 3. ANAMNESI FISIOLOGICA',style:'header'},'','',''],
	]
	},
	layout: 'noBorders'
}

	var reg='';
	var sti='';
	var alt='';
	var dia='';
	var tro='';

		if(data.carcli.alvreg){

			reg='Regolare';

		}
		if(data.carcli.alvsti){

		         sti='Stipsi';

		}
		if(data.carcli.alvalt){

			alt='Alterno';

		}
		if(data.carcli.alvdia){

			dia='Diarroico';

		}
	       if(data.carcli.alvtro){

		tro='Altro: '+data.carcli.alvtronot;

		}

	      fisio.table.body.push(
	     [{text:'Alvo '+reg+' '+sti},{text:alt},{text:dia},{text:tro}],
	);
```

I get some data form an application if these data are true o false if it's true I set a variable and in the end print all in a row of the table. I will try to explain how is the pdf...

**Practically the pdf should be wrote like this:**
3 Anamnesi Fisiologica
Alvo Regolare Stipsi Alterno Diarroico Altro:....
**But the file that I have is** 
3 Anamnesi 
Fisiologica 
Alvo Regolare Stipsi Alterno Diarroico Altro:....

In the first moment i was thinking that was the widths of the first column for this reason I set up the % at 40 but still the problem. 
If someone can help me I will be really greatfull.

**Comment by liborm85** [comment]
Attach a sample of docDefinition with data to reproduce problem and pdf output file. Above mentioned can not simply run.

**Comment by MiDDiO** [comment]
Problem solved, was a pagebreak putted in a wrong place my error
