### ISSUE TITLE
How to use system font in NodeJS?

### ISSUE THREAD

**Issue by red010182** [bpampuch/pdfmake#1044]
I'm using pdfmake in Nodejs and I don't have Roboto font and don't want to setup it nor build a custom font. 

How can I just use system font, like Times New Roman, Helvetica, or else?

ps. I'm on OSX

**Comment by NevilDabre** [comment]
First, you need to convert your fonts to base64 format and copy it into vfs_fonts.js file.

To use any custom font, need to create an object of your available fonts as follows : 

`pdfMake.fonts = {
    OpenSans: {
        normal: 'OpenSans-Regular.ttf',
        bold: 'OpenSans-Bold.ttf',
        italics: 'OpenSans-Italic.ttf',
        bolditalics: 'OpenSans-BoldItalic.ttf'
    },
    TimesRoman: {
        normal: 'TimesRoman-Regular.ttf',
        bold: 'TimesRoman-Bold.ttf',
        italics: 'TimesRoman-Italic.tt',
        bolditalics: 'TimesRoman-BoldItalic.ttf'
    },
    Roboto: {
        normal: 'Roboto-Regular.ttf',
        bold: 'Roboto-Medium.ttf',
        italics: 'Roboto-Italic.ttf',
        bolditalics: 'Roboto-MediumItalic.ttf'
    }
};`


Use it in var dd 

`            defaultStyle: {
                font: 'TimesRoman'
            },`

good luck.

**Comment by NevilDabre** [comment]
Use base64 Encoder
https://www.giftofspeed.com/base64-encoder/

**Comment by red010182** [comment]
Thank you for reply. 

That's even more complicated than to use Roboto. Is there any way to get start quickly and run some code with pdfmake in Nodejs without get involved into font problem? 

Or, perhaps the default font could bundled into npm package?

**Comment by red010182** [comment]
Found the answer. Just copy fonts folder from example and `examples/basics.js` works fine.
