### ISSUE TITLE
Please consider adding font sets for different languages.

### ISSUE THREAD

**Issue by red010182** [bpampuch/pdfmake#1045]
The default font Roboto obviously cannot display non-English characters like Chinese, Japanese, Arabian... etc. It's so frustrated to see a such wonderful package that cannot display my language. And the process to build font is also painful.

Do you consider let people commit the translated font that could display their language? For example, let people upload the base64 font to `fonts/zh-TW` for traditional Chinese, `fonts/zh-CN` for simplified Chinese and so on.

So that people could just download their fonts instead of building them.

**Comment by skillguru** [comment]
We also have a requirement to support the Chinese characters. We are using fireflysung.ttf  and this is packaged with the vfs_fonts.js file and delivered to client browser along with pdfmake library. The challenge  is that fireflysung.ttf size is about 15 MB, so the vfs_fonts.js became 20MB. The original file size with Roboto font only is 933 KB.
Now user will have to wait for the vfs_fonts.js file download before the customer starts exporting. We can defer this download at the end of the page load but still it is a pretty big size.
Is this the only way to support font for different language?

**Comment by Wabbala** [comment]
I think the easiest way is to set-up a nodeJS server, such that you can
have the heavy duty work done on a server, where you have much more control
over things like the fonts. Also the only way to support fonts of a
different language is to use the vfs_fonts.js file.

**Comment by skillguru** [comment]
Not sure how node.js is gonna help in this case much different than tomcat. We still have to package the font in  vfs_fonts.js file.

**Comment by Srinivasakarthikeyan** [comment]
Solution given in pdfmake documentation: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/

**Comment by liborm85** [comment]
Downloading via url protocol can be used, [see documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/).
