### ISSUE TITLE
Server side rendering of otf fonts doesn't work

### ISSUE THREAD

**Issue by Stacey-Gammon** [bpampuch/pdfmake#1048]
Server side rendering of all the ttf fonts I've tried works like a charm, but any time I use an otf font, it does not look as expected.  Since the default font Roboto doesn't support Chinese or Japanese characters I need a custom font, and I'd like to use Google Noto, but without otf support, I can't seem to achieve this.

**Comment by liborm85** [comment]
What exactly does not work?

**Comment by Stacey-Gammon** [comment]
It either picks some default font that is not the one I chose, or it comes out looking garbled.

Using version `0.1.31`, here is what [NotoSerifCJKjp-Bold.otf](https://noto-website.storage.googleapis.com/pkgs/NotoSerifCJKjp-hinted.zip) (downloaded from [here](https://www.google.com/get/noto/help/cjk/)) comes out looking like, which is clearly not NotoSerifCJKjp-Bold.
![screen shot 2017-06-18 at 7 14 56 am](https://user-images.githubusercontent.com/16563603/27260265-dc1ea8ca-53f5-11e7-9d36-043ff816477c.png)

So then I tried [Steelworks](http://www.fontspace.com/burntilldead/steelworks-vintage-demo) which comes with both an otf and ttf version. The ttf version came out looking fine, the otf version looks like this:
![screen shot 2017-06-18 at 7 19 32 am](https://user-images.githubusercontent.com/16563603/27260292-81e8beb2-53f6-11e7-89fc-900e9521e987.png)

I tried a few additional otf fonts as well, but you get the point. For some reason, I have no trouble with ttf, but otf doesn't look right, which leads me to believe it's a problem specifically with otf.

**Comment by gilphilbert** [comment]
I noticed something similar when using OTF files and couldn't work out why TTFs worked fine. It turns out that the PDF reader I was using (the one built into Chrome) seems to handle TTFs but not OTFs - I was seeing exactly what you're seeing. The OTF versions worked fine in Acrobat.

I've moved to TTFs to support a wider range of PDF readers. You can convert OTF files to TTF online for free if needed (just make sure the font's license allows it).

**Comment by liborm85** [comment]
OTF fonts are problematic - https://github.com/bpampuch/pdfmake/issues/1168

Pdfmake using [pdfkit library](https://github.com/devongovett/pdfkit) for rendering PDF files, please create issue [there](https://github.com/devongovett/pdfkit). Thanks.
