### ISSUE TITLE
Hide specific item bullets in lists

### ISSUE THREAD

**Issue by FinnStutzenstein** [bpampuch/pdfmake#1049]
Hi,

I have a feature request: In our project [OpenSlides](https://github.com/OpenSlides/OpenSlides) we need to hide specific bullet points in a list. An option like `liststyletype` (see the matching css style) would be nice, so that item2 do not get an "item marker":
```
ul: [
    'item 1',
    {text: 'item 2', liststyletype: false}, // or 'none'
    'item 3'
]
```
Also for ordered lists this would be helpful. The expected behavior is that the item with `liststlyetype: false` does not get any number and the counter doesn't count up, so this would be the output:
```
ol: [
    'item 1',
    {text: 'item without any number', liststyletype: false},
    'item 2'
]
```
Thanks!

**Comment by liborm85** [comment]
Implemented own list items type by  commit https://github.com/bpampuch/pdfmake/commit/69e4264f9a111d73d63f2fb3e266e7e399526706.

Examples:
```js
{
	ol: [
		'item 1',
		{text: 'item 2', listType: 'none'},
		{text: 'item 3', listType: 'upper-roman'}
	]
},
```
```js
{
	ul: [
		'item 1',
		{text: 'item 2', listType: 'none'},
		{text: 'item 3', listType: 'circle'}
	]
},
```
