### ISSUE TITLE
Print option opens in new window

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#1051]
In the latest version the option `  pdfMake.createPdf(pdfDoc).print();` will open in a new window/tab where as in old versions it was in same window. 
![screenshot](https://user-images.githubusercontent.com/9914694/27670746-88f7ed5e-5cac-11e7-98d6-a27f26b511cf.png)

How to make open the printable dialogue in the same window in latest version?

**Comment by GerritK** [comment]
You can easily set the window to current window.
`pdfmake.createPdf(pdfDoc).print({}, window);`

**Comment by mpsbhat** [comment]
@GerritK, But this method rewrites the URL...!!!

**Comment by liborm85** [comment]
Will overwrite the url because you get to another url...

Answered.

**Comment by mpsbhat** [comment]
Didn't get you @liborm85
