### ISSUE TITLE
Heavy use of memory

### ISSUE THREAD

**Issue by alexisab** [bpampuch/pdfmake#1052]
Hi,
For my webapp I must generate PDF on server-side. These PDF have a lot of heavy pictures embeded and sometimes it result in a crash of my app. I must reduce the memory usage. Do you have an idea on how I can do it ?

I would like to create my PDF step by step with stream for example (instead of construct the entire doc definition).

Thank you for your help and for this amazing library !

**Comment by liborm85** [comment]
Relevant pdfkit issue: https://github.com/devongovett/pdfkit/issues/728

**Comment by atiertant** [comment]
@alexisab you can try

`npm install Atlantis-software/pdfmake#atlantis`

it's a modified version of pdfmake with performance optimizations (image size, qrcode, progress callback, ...) that use a modified version of pdfkit reducing memory usage.

but we got an other bug you should have too : `createPdfKitDocument` function break javascript event loop as it is a long processing synchronous function, while generating PDF, javascript can't do anything else and asynchronous function called in progress callback are done after `createPdfKitDocument` end.

**Comment by fredlemieux** [comment]
I'm having a similar problem with the images, I've been taking note of the time taken to create a pdf with certain number of pictures: 15x pictures = 4:40, 18 = 5:30, 20 = 06:00, 23 pictures the app terminates with "Terminated due to memory issue" warning in the debugger.  This is a real shame as pdfMake is such a good library but this is a big problem.  I'll give the Atlantic-software version a go and see if it sorts out the photo issue.

I've other apps in the past with Pdfmake that have not had too much problem creating a pdf with lots of photos (40+), that app was using version ^0.1.26, so I might try to revert back to that version.  I'm not sure why the latest version 0.1.34 would be so much worse?

**Comment by soohan92** [comment]
npm install Atlantis-software/pdfmake#atlantis
This library doesn't seems exist? npm install but nothing installed.

**Comment by atiertant** [comment]
@soohan92 try using it in your package.json

**Comment by Jbegley1995** [comment]
@atiertant Hey, I'm trying to use the atlantis pdfmake and I got it to work and the memory usage is great, exactly what I was looking for. Although it seems the speed is way way slower, it seems to be coming from the measure document function, I was wondering if you have encountered this? If not is there anything you can say to point me in the right direction?

**Comment by atiertant** [comment]
@Jbegley1995 there are many problems:
- all pdfkit and pdfmake methods are synchronous (should return promise to avoid breaking changes)
- pdfkit streams does not respect backpressure
- node zlib has memory leaks (https://github.com/nodejs/node/issues/8871) we used synchronous deflate to avoid this problem but this is slower

**Comment by Jbegley1995** [comment]
@atiertant I see, thanks for the response and sharing the work, I wonder if I can find a sort of compromise between the speed and the memory? My requirements don't exactly need the PDF generation to be as fast as it is on the master branch and I can take on more memory than the current build on the Atlantis branch. Also props to you guys, I seen all the work you've put into it

**Comment by liborm85** [comment]
In new version 0.1.50 is solved heavy use of memory (upgraded pdfkit to 0.9.0).

**Comment by NUllrich22** [comment]
Hey @Jbegley1995 can you please introduce how to implement the Atlantis-software/pdfmake#atlantis library in the package.json. I cannot find the Module. 

Kind regards
Niklas
