### ISSUE TITLE
Remove vLines in specific row

### ISSUE THREAD

**Issue by adamka93** [bpampuch/pdfmake#1053]
Hi!
Is there a proper way to remove vertical lines from only one row?
I have a table: 
![kep](https://user-images.githubusercontent.com/10884684/27538772-e78bd798-5a79-11e7-82b2-21a8dfc70ed2.png)
and I want to remove the vertical lines between box 1- box 2, box 2 - box 3, box3- box4 (box 1-5 are nested table, lines cames from upper table)
Found some function:
`vLineColor: function (i, node) { if( i >0 && i<4){ return "#fff";} }`
but this function remove all vertical lines, form other rows too

the full code in file:

[table_vlines.TXT](https://github.com/bpampuch/pdfmake/files/1102029/table_vlines.TXT)

**Comment by alexisab** [comment]
For each cells you can define which borders you want to print with `border: [true, true, true, true]`. You have an example in the playground.
