### ISSUE TITLE
Default vfs_fonts.js should not include sampleImage.jpg

### ISSUE THREAD

**Issue by BobVul** [bpampuch/pdfmake#1057]
This image unnecessarily bloats the default font file by ~85 kB. It is only useful for testing and maybe on the playground, but now ends up getting served on every request.

It should probably be removed from the built/minified sources.

**Comment by liborm85** [comment]
https://github.com/bpampuch/pdfmake/commit/b359056905a264c46e64ce2eba4e83c262366654
