### ISSUE TITLE
How to setup pdfmake into Angular 4(cli)?

### ISSUE THREAD

**Issue by brunork26** [bpampuch/pdfmake#1058]
Well i tried something and didn't succeeded, I installed like the readme said. Into my component i tried importing it in two different ways, one like this:

`import * as pdfmake from 'pdfmake';`

and got me this error: 

`Uncaught TypeError: fs.readFileSync is not a function`

the second way i did this:

`import * as pdfmake from '/Users/<yeah_thats_me>/Documents/<my_team>/Angular4/TestProject/node_modules/pdfmake/build/pdfmake.min.js';`

for some reason i couldn't use the relative path, and i got a different error this time:

`ERROR Error: File 'Roboto-Regular.ttf' not found in virtual file system`

Well I did set the index.html with the scripts, but when i did i got this error:

`GET http://localhost:4200/build/pdfmake.min.js 
GET http://localhost:4200/build/vfs_fonts.js 404 (Not Found)`

Since i'm still learning javascript/typescript/angular, i'm probably doing something dumb.

**Comment by liborm85** [comment]
You also need to import a fonts file `pdfmake/build/vfs_fonts.js` as say [documentation](https://github.com/bpampuch/pdfmake#getting-started).
