### ISSUE TITLE
View Problem

### ISSUE THREAD

**Issue by Hkarimi561** [bpampuch/pdfmake#1059]
How can i manage the view in the Other Languages
<img width="819" alt="screen shot 2017-07-09 at 2 56 01 pm" src="https://user-images.githubusercontent.com/16588927/27993061-2bdca28c-64b7-11e7-9c19-04aab1b71e6f.png">
Please Help me

**Comment by Hkarimi561** [comment]
i make this with table

**Comment by PeterLazar** [comment]
I too would like to know if there is a way to know some content (most likely the table) is too wide to fit on the page.

**Comment by liborm85** [comment]
Is likely to be associated with: https://github.com/bpampuch/pdfmake/issues/441

**Comment by Hkarimi561** [comment]
@liborm85 

I want to be like div in html that mean it's at the end of the line go to next line

**Comment by liborm85** [comment]
It is not supported now.  Requires implementation of this issue: https://github.com/bpampuch/pdfmake/issues/358
