### ISSUE TITLE
fillColor based on column index

### ISSUE THREAD

**Issue by NickStemerdink** [bpampuch/pdfmake#1060]
I noticed it is currently not possible to set the `fillColor` based on the column index, only the rowIndex is available. Is there a special reason for not also providing the column index?

If not I would be happy to implement this myself and create a PR for this change.

Example:
```js
fillColor: function (rowIndex, columnIndex, node) {
    return columnIndex === 0 ? 'grey' : 'white';
}
```

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/9e49c786b0cd9adb02815d0cca6b20812fbdebe4.

Syntax:
```js
fillColor: function (rowIndex, node, colIndex) {
//
}
```
