### ISSUE TITLE
Multilevel list numbers

### ISSUE THREAD

**Issue by regisaih** [bpampuch/pdfmake#1067]
Is there a way to get this kind of multilevel list numbers?
```
1. First level header
   1.1 First sub level header
   1.2 Second sub level header
      1.2.1 First third level heaer
2. Second first level header
```

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/959

**Comment by polmatambunan** [comment]
There is a bug in multilevel list numbers 

`counter: 1.10` become 1.1
