### ISSUE TITLE
context-sensitive header/footer

### ISSUE THREAD

**Issue by jampy** [bpampuch/pdfmake#1068]
In a multi-page document I'd like to print the title of the current section in the `header`.

The content is dynamic and I can't predict how many pages a specific section will contain (ie. the page number alone won't tell me the section I'm in).

The `header`, `footer` or `background` callbacks seem the way to go for such dynamic header/footers, but how do these handlers know which section I'm in?

Since **each section starts on a new page** (`pageBreak: "before"`), I tried to override the `header` property like so:

```javascript
    dd.content.push({
      pageBreak: "before",
      pageSize: "A4",
      pageOrientation: "landscape",
      style: "heading2",
      text: "New section",

      header: (currentPage, pageCount, pageSize) => {

        return [
          {
            text: "In a new section",
            absolutePosition: { x: 80, y: 33 }
          }
        ];

      },
    });

```
...but apparently that's not supported.

Any way to archive this?

**Comment by liborm85** [comment]
It is not possible now.

Feature request: https://github.com/bpampuch/pdfmake/issues/283
