### ISSUE TITLE
Add new page while generating pdf with dynamic content

### ISSUE THREAD

**Issue by NikhilRadadiya** [bpampuch/pdfmake#1070]
I'm trying to generate pdf with dynamic content from html.
Issues is pdf generating successfully but only one page and rest of the content get cut. After hours of digging I found that I need to use `pageBreakBefore` but I don't have any idea how to use it with dynamic content. 
used `pageBreak:'after'` also but it only adds page not remaining content 
Here is my code, I'm using it with angular 2

```
createPdf(): void {
     var main = $('.main');
    html2canvas(this.el.nativeElement, {
            onrendered: function (canvas) {
                var data = canvas.toDataURL();                       
                var a4  =[ 595.28,  841.89];
                var docDefinition = {
                    pageSize: 'A4',
                    content: [{
                        image: data,
                        width: 500,
                        pageBreak:'after'
                    }],
                     pageBreakBefore: function(currentNode, followingNodesOnPage,
                      nodesOnNextPage, previousNodesOnPage) {                      
                       return currentNode.headlineLevel === 1 && followingNodesOnPage.length === 0;
                    }
                };
                pdfMake.createPdf(docDefinition).download("test.pdf");
            },
            imageTimeout:2000,
            removeContainer:true
        },
        );
    }
```

Please help me here.
How to use `pageBreakBefore` with dynamic content?

**Comment by osaatcioglu** [comment]
This is the code that I developed more than two years ago. But, it seems still relevant and it looks like it is similar to what you did. 

https://gist.github.com/osaatcioglu/98c8ce73ea2551f1bbd15b3ebb309c78

May be, you need to specify the image to fit correctly to the page before inserting the pagebreak. 

I hope it helps. Good luck!
