### ISSUE TITLE
Performance of PDF download

### ISSUE THREAD

**Issue by dmatesic** [bpampuch/pdfmake#1072]
It takes a long time to download PDFs, even for a basic 6KB PDF with text only.

Steps to reproduce (Chrome Version 59.0.3071.115 (Official Build) (64-bit) / macOS Sierra Version 10.12.5):

1. Go to the [pdf make playground](http://pdfmake.org/playground.html)
2. Select "BASICS"
3. Click "DOWNLOAD"
4. Wait ~5 seconds for PDF to download.

Any ideas? The "IMAGES" example (which produces a 200KB PDF file) takes about the same amount of time to download. In my own project, a much larger file (1.3 MB) also takes ~5 or 6 seconds to download.

**Comment by liborm85** [comment]
I try it with Chrome (Windows 7 and 10) and time for generate is <1 second.
Did you try it on another computer?

**Comment by dmatesic** [comment]
I tried it on a few other computers and apparently I'm the only one with the issue. If I find out what's causing it I'll leave a comment here, thanks!
