### ISSUE TITLE
How to make a page break for the table with 20+ columns?

### ISSUE THREAD

**Issue by afrankiv** [bpampuch/pdfmake#1074]
My document is a huge table with 20+ columns and I would like to split the table into two A4 pages. Expected behavior is similar as MS Excel do during printing. Is it possible to do so somehow with pagebreak for the table?

**Comment by liborm85** [comment]
Not currently. It works just like MS Word - the wide tables there are out of the page too.

Feature request is here: https://github.com/bpampuch/pdfmake/issues/441

**Comment by akhiljain1611** [comment]
any progress @liborm85 @adulaisow
