### ISSUE TITLE
Canvas does not work in header/footer

### ISSUE THREAD

**Issue by dj-hedgehog** [bpampuch/pdfmake#1078]
I have been trying to insert a canvas in a header and footer for the last two hours but it is just ignored. There is no error. It is just never rendered.

Here is a minimal example that illustrates my problem in the playground:

    var dd = {
        header: function() {
            return [
                {
                    table: {
                        widths: [ '*'],
                        body: [[ 
    						{
    							border: [false, false, false, false],
    							fillColor: '#eeeeee',
    							text: '-'
    
    						},
                        ]]
                    },
                },
                { canvas: [ { type: 'rect', x: 170, y: 32, w: 170, h: 40 } ] }
    
            ]
        },
    	content: [
    		{text: 'Optional border', fontSize: 14, bold: true, margin: [0, 0, 0, 8]},
    		'Text',
    	]
    }

**Comment by liborm85** [comment]
You have canvas outside the header area.

For example this works:
```js
var dd = {
    header: function() {
        return [
            {
                table: {
                    widths: [ '*'],
                    body: [[ 
						{
							border: [false, false, false, false],
							fillColor: '#eeeeee',
							text: '-'

						},
                    ]]
                },
            },
            { canvas: [ { type: 'rect', x: 170, y: 0, w: 170, h: 10 } ] }

        ]
    },
	content: [
		{text: 'Optional border', fontSize: 14, bold: true, margin: [0, 0, 0, 8]},
		'Text',
	]
}
```
