### ISSUE TITLE
Fails in rowSpan, text in rows exceeds table edges

### ISSUE THREAD

**Issue by juliandavidmr** [bpampuch/pdfmake#1079]
Hello, I have this code:

```js
{
	style: 'tableExample',
	color: '#444',
	table: {
		widths: ['*', '*', '*'],
		headerRows: 2,
		// keepWithHeaderRows: 1,
		body: [
			[
			    {text: 'Header 1', style: 'tableHeader', alignment: 'center'}, 
			    {text: 'Header 2', style: 'tableHeader', alignment: 'center'}, 
			    {text: 'Header 3', style: 'tableHeader', alignment: 'center'}],
			[{
			    rowSpan: 3,
			    text: 'rowSpan set to 3'
			}, 'Sample value 2', 'Sample value 3'],
			['', 'Sample value 2', 'Sample value 3'],
                        ['', 'Sample value XY', 'Sample value 3']
		]
	}
},
```

The contents of the last row exceeds the border of the table edges. That is, `['', 'Sample value XY', 'Sample value 3']` is displayed incorrectly.

This code has been tested in [pdfmake.org/playground](http://pdfmake.org/playground.html) and matches my explanation.

Thank you for creating this library.

**Comment by liborm85** [comment]
You have a wrongly defined table - `headerRows: 2`.
With `headerRows: 1` or `headerRows: 4` works ok.
