### ISSUE TITLE
PDF-Links based on Anchors

### ISSUE THREAD

**Issue by clemenskroell** [bpampuch/pdfmake#1081]
It would be great if we could include "anchors" on pages and link to them from e.g. the first page.

Example: We generate a multi page pdf, where different content-categories are on many pages. Now we want to link to these category-pages from the first page. At the moment this is not possible, as we don't know on which page a category is. Or do we miss an existing feature in pdfMake?

Thanks

**Comment by liborm85** [comment]
Not possible now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/897
