### ISSUE TITLE
wordpress compatibility ?

### ISSUE THREAD

**Issue by eelaapcc** [bpampuch/pdfmake#1082]
Hello there,

I was looking for a way to generate pdf from a webpage and after trying many solutions, pdfmake seemed the perfect one. But, whereas it works perfectly as a php solo page, when I paste the code on my wordpress custom page, it doesn't work anymore. I can click as much as I want, it doesn't trigger the pdf as it should. Any idea ?

Here's what I tried already : 
- simplifying the pdfmake code to the basics in case I had made a mistake customizing it
- removing any other code from my custom WP page
- adding the code to a basic WP post 
None of that worked. What surprises me, is that JsPDF works but its customization is not as interesting. And I have a javascript button to get back to the top of the page, so JS doesn't seem to be incompatible.

Here is my WP customization : 
- added ACF and CPT UI plugins to customize fields
- made a custom php page which calls all the custom fields and is used for any post with the assigned type (and I wanted to add the pdfmake function there to edit a pdf for every post generated)

Being a beginner in coding, my only guess as to why it doesn't work would be WP since it is the only variable which makes it stop working. 
In case I made a mistake, here is the code I wrote (mostly taken from pdfmake library) : 
`<script  src='myfolder/pdfmake.min.js'></script>`
`<script src='myfolder/vfs_fonts.js'></script>`
`<script type="text/javascript">`
`function test(){`
 `   var docDefinition = {`
 ` pageSize: 'A4',`
 ` pageOrientation: 'portrait',`
  `pageMargins: [ 20, 20, 20, 20 ],`
`};`
   ` var docDefinition = { content: [`
    ` { text: 'blah', style: 'titre' },`
    ` { text: 'blah', style: 'texte' },`
    ` { text: 'blah', style: 'focus' },`
`   ],`
   ` styles: {`
   `  titre: {`
  `     fontSize: 14,`
    `   bold: true,`
    `   alignment: 'center'`
  `   },`
   `  focus: {`
     `  fontSize: 9,`
     `  bold: true,`
      ` alignment: 'center'`
 `    },`
   ` texte: {`
     `  fontSize: 9,`
    `   alignment: 'center'`
   `  }`
  ` }`
 `};`
 `pdfMake.createPdf(docDefinition).open();`
 `pdfMake.createPdf(docDefinition).download('blah.pdf');`
 `   }`
    `</script>`
   ` <button onclick="test()">Télécharger</button>`

Thanks for any help, I appreciate !

**Comment by liborm85** [comment]
Is there any error in the browser javascript console?

**Comment by eelaapcc** [comment]
ha yes there is ! thank you, you're the best ! 
here is what happened : on my solo page, the `<script src='myfolder/pdfmake.min.js'></script>` indeed went where I wanted it to. but on my custom WP page, it redirected using the custom url (I guess because of the CPT UI plugin) and so could not find the two .js files. Stupid mistake ! I forced the path writing the full url and now, it works like a charm !
big thank you 👍 

(btw, if someone wonders, pdfmake works perfectly to add the ACF custom fields content to the pdf).
Thank you for this wonderful tool ! you have no idea how easier you just made my work ;)
