### ISSUE TITLE
nested text array 

### ISSUE THREAD

**Issue by blairjo** [bpampuch/pdfmake#1084]
Hi,

If I create the following on the pdfmake playground:

```javascript  
var dd = {
	content: [
		{
		    text : [ 
		        "this ",
		        "that ",
		        { text : ["the ", "other"]}
		    ]
		}
	]
}
```

The text will come out as "**this that the ,other**" i.e with a comma between "the" and "other".
I'd have expected a nested text array to behave the same as the top level text array simply concatenate the text to "**this that the other**" 

If the nested array itself contains an object with a text component it shows as "object", from a toString()
e.g
```javascript
var dd = {
	content: [
		{
		    text : [ 
		        "this ",
		        "that ",
		        { 
		            text : [
		                "the ", 
		                {text : "other", bold : true}
		            ]
		        }
		    ]
		}
	]
}
```
So this shows as "**this that the ,[object Object]**"

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1033
