### ISSUE TITLE
Cover page?

### ISSUE THREAD

**Issue by Herudea** [bpampuch/pdfmake#1086]
I wasn't sure if this was a good place to reach out about a feature - I hope it's ok.

It would be nice to be able to define a "cover page" that happens only once, and and any defined repeating headers or footers start _after_ that if it exists.

This may be currently possible, and I just have not sorted it out yet.

Thanks - incredible work!

**Comment by davidvictor** [comment]
you can do something like this to not render the header or footer on the first page.

```
const header = function (currentPage, pageCount) {
  if (currentPage != 1) {
    return {
      columns: [
        {
          text: 'Employee Handbook',
          style: ['vsmall', 'gray'],
          margin: [40, 26, 0, 0]
        }, {
          image: 'companyLogo',
          width: w,
          alignment: 'center',
          margin: [0, 18, 0, 0]
        }, {
          text: `${user.company.name}`,
          alignment: 'right',
          style: ['vsmall', 'gray'],
          margin: [0, 26, 40, 0]
        }
      ],
    }
  }
  else {
    return {}
  }
};
```

**Comment by liborm85** [comment]
Answered.

Connected with #368, #283.

**Comment by reworx-ux** [comment]
Where exactly should I insert this. Pasting it right after _const documentDefinition = this.getDocumentDefinition();_  doesn't work. The header gets ignored in the PDF.

**Pasting in after getDocumentDefinition() {return {pageSize: 'A4'pageMargins: [ 50, 80, 40, 100 ]}** looks like the code below, but I get ERROR:  _Type Error Cannot read property 'offer' of undefined:_

 header: function(currentPage, pageCount) {
          if (currentPage != 1) {
            return {
              columns: [
                {
                  text: 'Employee Handbook',
                  style: ['vsmall', 'gray'],
                  margin: [40, 26, 0, 0]
                }, {
                  image: 'companyLogo',
                  width: '100',
                  alignment: 'center',
                  margin: [0, 18, 0, 0]
                }, {
                  text: this.offer.place.address.street,
                  alignment: 'right',
                  style: ['vsmall', 'gray'],
                  margin: [0, 26, 40, 0]
                }
              ],
            }
        }
          else {
            return {}
          
        }
    
      
      },
