### ISSUE TITLE
TypeError: pdfMake.createPdf is not a function

### ISSUE THREAD

**Issue by leonardoEbert** [bpampuch/pdfmake#1091]
Hello, I'm having this problem when I try to create the file, I've tried everything and nothing has worked. I'm using the server side and I do not know what to do, I searched extensively in several communities and even here in GitHub and I did not find the answer to the problem. Please help me...

`let pdfMake = require('pdfmake');`
`let docDefinition = { content: 'This is an sample PDF printed with pdfMake' };`
`pdfMake.createPdf(docDefinition).open();`
`pdfMake.end();`

The same problem occurs with the source code of my application and with the documentation examples
And when I make a request in Postman it returns the following error:
TypeError: pdfMake.createPdf is not a function

Could you show me a example of a source code that is working 100%??

**Comment by liborm85** [comment]
See Getting Started in readme - https://github.com/bpampuch/pdfmake#getting-started , how to using pdfmake in client-side with require.

**Comment by leonardoEbert** [comment]
It is a requirement that the pdfs be created on the server...

**Comment by liborm85** [comment]
You use `createPdf(docDefinition).open()` and this is client-side function. But you writes about the server now. For server-side examples see this section in readme - https://github.com/bpampuch/pdfmake#server-side

**Comment by leonardoEbert** [comment]
Make senses now... 
Now, pdfMake requests the "fs" library, and I have already requested access to it in support of npmjs.com
Thanks for your help.

**Comment by leonardoEbert** [comment]
The pdfMkake library requests "fs" library on the client-side, but fs is exclusive from nodeJS, how to solve this??

**Comment by RaghuVarmaPinnelli** [comment]
what is the proper way to use `pdfMake.createPdf(docDefinition).download()` on server side. I'm seeing 

> pdfMake.createPdf is not a function

error

**Comment by AdamBCo** [comment]
Has anyone solved this issue?

**Comment by chalangr12** [comment]
What I did to actually generate the file is call the getBuffer Function that returns a callback see below.
`var generatedDoc = pdfMake.createPdf(data);
generatedDoc.getBuffer((buffer)=>{
fs.writeFileSync('file.pdf',buffer)
})`

**Comment by benquan** [comment]
Client side Documentation says:
	`pdfMake.addVirtualFileSystem(pdfFonts);`

But what actually works is:
	`pdfMake.vfs = pdfFonts.pdfMake.vfs;`

I got this from other examples
