### ISSUE TITLE
Is it possible to assign styles to table of contents?

### ISSUE THREAD

**Issue by sashakirichek** [bpampuch/pdfmake#1097]
Is it possible to assign style to toc items? Something like:

{toc: {title: {text: 'Table of content', style: 'h1', **styles: {tocH1: {}}**}}, pageBreak: 'before'},
{text: 'References', style: 'h1', pageBreak: 'before', tocItem: true, **tocStyle: 'tocH1'**},

**Comment by liborm85** [comment]
Assign styles is implemented by PR https://github.com/bpampuch/pdfmake/pull/1108.

**Comment by nerdess** [comment]
These are the TOC styles I found in the source code:

```
toc: {
  id: `toc-${i}`,
  title: {text: 'Some title', style: 'tocGroupTitle'},
  textStyle: 'foo',
  textMargin: [16, 0, 0, 0],
  numberStyle: 'baz'
},
```
