### ISSUE TITLE
Document title not used on open()

### ISSUE THREAD

**Issue by risoldi** [bpampuch/pdfmake#1098]
Hello,

I am creating a document definition that has the title defined:
```
var docDefinition = {
			info : {
				title : "The title of my document",
				author : "The author",
			},
			content : [
                        // my content here
                       ]
}
```
Then I open the PDF in another window by doing:
`pdfMake.createPdf(docDefinition).open();`
From what I read in the docs and on here, I would expect the PDF file to be called "The title of my document", but instead in the new window I get a URL reading like:
`blob:http://localhost:8080/2c7dc6a4-6cdc-4b67-a70b-ac97482d639a`
(the number changes every time)
and when I save the PDF the file is named "2c7dc6a4-6cdc-4b67-a70b-ac97482d639a.pdf".
The tab's title nonetheless reflects the title property.

This is on Chrome on Windows.
Note that if I use download() instead, the title is correctly used as a filename, but I really do want it opened in a new window instead. Is there a way I can get the PDF in a new window and have the correct filename?
Thanks

**Comment by liborm85** [comment]
When using `open()` is not supported file name, only title. This is the property of browsers.

**Comment by moffsugita** [comment]
@liborm85 Really?
How bad browser is. Google doesn't have tech skills. are there no hacks?

**Comment by liborm85** [comment]
@moffsugita Really.
