### ISSUE TITLE
Embed link in paragraph

### ISSUE THREAD

**Issue by r0fls** [bpampuch/pdfmake#1101]
Is it possible to embed a link into a paragraph? I don't think it is, but it would be a nice feature. I know you can add a link as a separate element:

```javascript
var dd = {
	content: [
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines',
		{text: "hyperlink", link: 'http://google.com', decoration:"underline", fontSize:15}
	]
}
```

However it would be nice to render the link within the paragraph.

**Comment by liborm85** [comment]
Mixing text styles/properties in one paragraph is described in playground on list STYLES2.
