### ISSUE TITLE
Pdf open stop working after chrome update

### ISSUE THREAD

**Issue by hiago-b-oliveira** [bpampuch/pdfmake#1105]
![screenshot_2017-08-16_12-34-28-2](https://user-images.githubusercontent.com/18020705/29372556-e11802ee-8281-11e7-8fa2-8ec23e4a3362.png)

After update my chrome to Version 60.0.3112.101 (Official Build) (64-bit), the open pdf function stop working. 

Debugging the code, I saw that the problem is in the line: 
```
win.location.href = pdfUrl;
```
The pdfUrl is correct. It is possible to open the pdf in other tab copying / pasting the value, but assign the href looks like have no effect. Maybe it's a chrome bug... 

Sorry my english!

**Comment by uebbi** [comment]
Dá uma lida [aqui](https://github.com/bpampuch/pdfmake/issues/800#issuecomment-313741653) e [aqui](https://jsfiddle.net/5ntw24qc/3/).

Lembrando que você deve usar a versão mais recente do pdfmake, atualmente a 0.1.32.

**Comment by hiago-b-oliveira** [comment]
@uebbi, no meu caso o problema era o Adblock. Só achei estranho o problema não acontecer antes com uma versão mais antiga da lib e do chrome. 

Muito obrigado pelos links!

**Comment by hiago-b-oliveira** [comment]
Issue resolved by disabling Adblock. Thanks for your help @uebbi
