### ISSUE TITLE
Add Text on Image - Is this possible or a feature that could be implemented?

### ISSUE THREAD

**Issue by AlexanderFalk** [bpampuch/pdfmake#1107]
Is there any way to add text to an image? I got a picture in the bottom of my page, which has lowered opacity. I want some contact information on the image, but I can't find any ways to do this?

I tried these things: 
https://stackoverflow.com/questions/29518377/embedding-a-background-image-in-pdfmake?rq=1
https://github.com/bpampuch/pdfmake/issues/802
https://github.com/bpampuch/pdfmake/issues/358

None have worked as needed. 

The first link, where you add the background to the text, seems legit. But it didn't work out. 

Hope anyone can help or suggest an idea. If it is not possible, then I will do it photoshop and just let it be a picture. Just wanted it a bit more dynamically. 

Regards

**Comment by liborm85** [comment]
Example with absolute position:
```js
var dd = {
	content: [
		{
			image: 'sampleImage.jpg',
			width: 200
		},
		{
			text: 'Text over image',
			absolutePosition: {x: 100, y: 50}
		}		
	]
}
```
