### ISSUE TITLE
Open serverside created pdf in new tab

### ISSUE THREAD

**Issue by yrojha4ever** [bpampuch/pdfmake#111]
I have created pdf server side like ex:
Suppose this value i have in js variable.
var pdfData = "data:application/pdf;base64,JVBERi0xLjMKJf////8KOCAwIG9iago8PAovVHlwZSAvRXh0R1N0YXRlCi9jYSAxCj4+CmVuZG9iago5IDAgb2JqCjw8Ci9UeXBlIC9FeHRHU3RhdGUKL0NBI+CnN0YXJ0eHJlZgozODE3NAolJUVPRgo="

Now I just want to open this pdf in new tab using pdfmake.js
How to do that?
Thanks

**Comment by CgarciaTC** [comment]
yrojha4ever, crees que puedas decirme como lo hicistes, trabajo con un proyecto igual y necesito descargar un pdf en base 64 con pdf-make. Te lo agradeceria
