### ISSUE TITLE
Chrome (iOS) Print not working

### ISSUE THREAD

**Issue by Vigneshjana** [bpampuch/pdfmake#1110]
Using PDFmake , Updated Chrome version print is not working for iOS

**Comment by liborm85** [comment]
Do you use [latest](https://github.com/bpampuch/pdfmake/releases/latest) version of pdfmake?
Are you [disabled adblock](https://github.com/bpampuch/pdfmake/issues/800)?

**Comment by liborm85** [comment]
What exactly does it mean "print is not working"? What is doing? Any error in console?
