### ISSUE TITLE
Edit text node on repeatable headerRows

### ISSUE THREAD

**Issue by lbonatti** [bpampuch/pdfmake#1111]
Hi.
I need to edit the text of the repeteable haderRows (only in repeteable). Add "Continued" text.
The first row of a table header is a  Table Title, and if the table is repited (the headers) need concatenate the continued text in this title. Is there any posibility of that?

Thanks for the grat library. And i'm sorry by my bad english.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/531
