### ISSUE TITLE
Problem with the vertical line of a table 

### ISSUE THREAD

**Issue by MiDDiO** [bpampuch/pdfmake#1112]
Hi guys,
I have a problem that is really strange when i print a file with few data there isn't problem but when I print a data link 300 rows in the last page the vertical line of the table continue for all the length of the page... and don't stop on the end of the data... someone has my problem ? I will wait some reply

**Comment by liborm85** [comment]
It is known issue. Fix is not yet available.
duplicate: https://github.com/bpampuch/pdfmake/issues/928
