### ISSUE TITLE
Text wrapping after parenthesis

### ISSUE THREAD

**Issue by julien-hadleyjack** [bpampuch/pdfmake#1114]
In the example, I want to have some bold text in parentheses. The parenthesis shouldn't be bold. Depending on the length of text before a parenthesis, it can appear as the last character on a line. I expected it to be on the next line with the remaining text (which happens when the text is not wrapped in another text object).

I can manually fix it by inserting more spaces before the parenthesis but I would like to avoid it because it would probably break again if I make some changes to the text before it.

I also don't want to wrap the parenthesis and its included text content in noWrap because in some places in the real document it is longer than one line.

**Example Code:**
```javascript
var dd = {
  content: [ {
      text: [
          "placeholder placeholder placeholder placeholder placeholder placeholder placeholder placehol (",
              {"bold": true, "text": "“placeholder”"},
              ")"
          ]
  } ]
}
```

**Example Result:**
![Result](https://user-images.githubusercontent.com/7487613/29553817-31677834-871d-11e7-9db1-44dde8a2b833.png)

**Comment by liborm85** [comment]
It's known issue - https://github.com/bpampuch/pdfmake/issues/975
Currently, I don't know how to simple fix it yet.
