### ISSUE TITLE
label-pageref feature

### ISSUE THREAD

**Issue by FinnStutzenstein** [bpampuch/pdfmake#1116]
Hi,

I saw that PdfMake supports a TOC and can put page numbers after rendering (or whenever the document location for text is determinated to get the page number) into the document. This feature is nice, but for complex TOCs it would be great to have a label and pageref functionality:

If there is an peace of text, e.g. an header I would like to give this header a label like 'header_obj_1'. This should be the same syntax as for the `tocItem: true`. Im my custom TOC then I have text like 'This is my Header ....... ' and then the pagenumber pasted in by PdfMake like the `toc` definition: `{ pageRef: {label: 'header_obj_1'} }`.

It would be very nice, if you can implement this great feature.

Thanks!

**Comment by emanuelschuetze** [comment]
@liborm85 Can you give us your priority for this feature request? We need this feature for OpenSildes to make nice TOCs. Is it possible to get this in the next pdfmake release? Thanks in advance!

**Comment by liborm85** [comment]
@emanuelschuetze Yes I'll do it.

**Comment by liborm85** [comment]
Implemented `pageReference` feature and `textReference` feature by commit https://github.com/bpampuch/pdfmake/commit/ebf046ad7c791a36a772ebda823d30e7a28b363d and https://github.com/bpampuch/pdfmake/commit/c983402ed3adb677f04dc0ab55cc298a874d75c2.

Examples is available here: [examples/pageReference.js](https://github.com/bpampuch/pdfmake/blob/master/examples/pageReference.js)

**Comment by liborm85** [comment]
New version released.
