### ISSUE TITLE
Chrome Intent to Deprecate and Remove: Top-frame navigations to data URLs

### ISSUE THREAD

**Issue by smockensturm** [bpampuch/pdfmake#1117]
Hi. Anything to report on how to handle this development?

https://groups.google.com/a/chromium.org/forum/#!topic/blink-dev/GbVcuwg_QjM

Kinda' renders this useless in Chrome:

`pdfMake.createPdf(docDefinition).open();`

**Comment by liborm85** [comment]
Pdfmake doesn't use `data:` which was blocked, but `blob:` which works.

**Comment by smockensturm** [comment]
You sure about that? Console error starts out thusly:

`Not allowed to navigate top frame to data URL: data:application/pdf;base64...`

pdfmake v0.1.32

**Comment by liborm85** [comment]
On [playground](http://pdfmake.org/playground.html) OPEN button works ok.

**Comment by webedge** [comment]
I am getting the same behavior in Chrome, Firefox and IE

**Comment by smockensturm** [comment]
It's true. The playground OPEN button works OK.

Help us understand then, why this most simple of examples (per the documentation) is using `data:` and yielding the error first mentioned in this thread.

Is there something we should be doing differently? Why does the playground OPEN work OK, and this does not?

```
<!doctype html>
<html lang="en">

<head>
   <meta charset="utf-8">
   <title>PDF Make</title>
   <script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
   <script type="text/javascript" src="pdfmake.min.js"></script>
   <script type="text/javascript" src="vfs_fonts.js"></script>
</head>

<body>
   <button id="go">GO</button>
</body>

</html>

<script type="text/javascript">

   var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };

   $('#go').click(function(){
      pdfMake.createPdf(docDefinition).open();
   });

</script>

```

**Comment by liborm85** [comment]
Your example works ok with version 0.1.32.
If this does not work for you, update pdfmake to latest (0.1.32) version.

**Comment by smockensturm** [comment]
No it does not. Not in Chrome

**Comment by smockensturm** [comment]
Wrong. My bad. Looks good. Thank you.

**Comment by TheKojuEffect** [comment]
The playground OPEN button opens a new tab and closes it immediately in chrome, but it works in firefox.

**Comment by Wabbala** [comment]
Two options:
- pop-up blockage by chrome;
- adblockr: ​disable ad-blocker and retry

**Comment by TheKojuEffect** [comment]
@Wabbala Thank you. uBlock was the problem.
