### ISSUE TITLE
PDF size, DPI and pixels

### ISSUE THREAD

**Issue by CrackerakiUA** [bpampuch/pdfmake#1118]
Lets say we are working mostly with images, what i need to have in result is good DPI, same as given image and specific size for printing. By setting pageSize to some values, i am getting the size i want to have as result, but DPI is horrible. I am adding images with to content with huge points value, but still result is same, DPI looks to be 72 or worse. I am using dataUrl, can that be my mistake?
When i am adding huge pageSize, i get pixels i would like to have but size of the pdf is wrong.

**Comment by liborm85** [comment]
Pdfmake for render PDF using pdfkit library, see relevant issue: https://github.com/devongovett/pdfkit/issues/268
