### ISSUE TITLE
Text transform uppercase

### ISSUE THREAD

**Issue by davidyeiser** [bpampuch/pdfmake#1119]
Is there a way to transform text to uppercase? 

e.g.

    {
      text: 'Hello World',
      uppercase: true
    }

`HELLO WORLD`

**Comment by davidyeiser** [comment]
Well, as soon as I posted this I realized I could just use `.toUpperCase()` to transform the string before passing it to `pdfmake`.

**Comment by nikolnikov** [comment]
Is text-transform: uppercase/lowercase an option with PDFMake? I've tried a few different methods on the PDFMake playground, but nothing worked. It would be a nice feature!

**Comment by kioidun** [comment]
Any update if PDFMake accepts text-transform:uppercase/lowercase?

**Comment by craragon77** [comment]
any updates? this would be a v handy feature...

**Comment by whawker** [comment]
I was able to workaround this by using `fontFeatures` with small caps (assuming the font supports it), you do need to increase the font size a little to negate the "small" caps.

```
fontFeatures: ['c2sc', 'smcp'], // Small caps
```

Reference: https://developer.mozilla.org/en-US/docs/Web/CSS/font-feature-settings

However, adding support for `uppercase: true` would be preferred!
