### ISSUE TITLE
border radius / rounded corners

### ISSUE THREAD

**Issue by ts-de** [bpampuch/pdfmake#1120]
Is there a way to create rounded corners (border-radius) for tables or other elements?

**Comment by mashit** [comment]
+1

**Comment by liborm85** [comment]
duplicate feature request: https://github.com/bpampuch/pdfmake/issues/385

**Comment by elainebyrne** [comment]
#385 is a border around and image. NOT border-radius. Has there been any update on this?

**Comment by GO-gyan** [comment]
+1

**Comment by thilinaucsc** [comment]
any update?

**Comment by Ovi** [comment]
nothing yet?

**Comment by balasubrahmanyams** [comment]
Any updates about it

**Comment by bluesky777** [comment]
please, any update on this?

**Comment by Roman-Vala** [comment]
{canvas: [
				{
					type: 'rect',
					x: 0,
					y: 0,
					w: 285,
					h: 23,
					r: 3,
					lineColor: '#ccc',
				},
			]},

and then position text absolutely

**Comment by Chandru1495** [comment]
@Roman-Vala , Hi All, How to make the rounded corner (border - radius) dynamically for a table content using this canvas element?
