### ISSUE TITLE
Content appearing behind header when content naturally flows over a page break

### ISSUE THREAD

**Issue by n397772** [bpampuch/pdfmake#1121]
As the title suggests, content is appearing behind the specified header when content naturally flows from one page to another.

`header: {
			columns: [
				{
					margin: [8, 8, 0, 50],
					image: path.join(__dirname, '../../test_logo.png'),
					width: 120
				},
				{
					margin: [0, 8, 8, 50],
					text: 'Form: ' + survey.title +
						'\nCreated by: ' + surveyResponse.createdBy,
					color: 'grey',
					alignment: 'right'
				}
			]
		}`

![image](https://user-images.githubusercontent.com/31733547/30165004-5cec7df4-93d6-11e7-87f7-e1b84ceb885b.png)

I have a workaround for this when specifying a page break, I can just add a margin above my page header;

`// survey header
	definition.content.push({
		pageBreak: 'before',
		text: survey.title,
		style: 'header',
		margin: [0, 50, 0, 0],
		tocItem: true
	});`
Is there something like this I can do for regular page content when it overflows? As the content is programmatically generated and I have no way of knowing when content will flow from one page to the next therefore I can't add the same workaround to regular content. Is there an attribute on the header object which stops content appearing behind it that I'm missing?

Thanks.

**Comment by liborm85** [comment]
Must be set page margins adjust the size of the header.

```js
var docDefinition = {
  // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
  pageMargins: [ 40, 60, 40, 60 ],
};
```
