### ISSUE TITLE
Is it possible to suppress or switch headers and footers on some pages?

### ISSUE THREAD

**Issue by JimSangwine** [bpampuch/pdfmake#1126]
Thanks for a great library!

**Comment by liborm85** [comment]
This is not possible now. Some workaround is here: https://github.com/bpampuch/pdfmake/issues/178#issuecomment-274005757

(feature request is here: https://github.com/bpampuch/pdfmake/issues/178)

**Comment by JimSangwine** [comment]
Thanks!
