### ISSUE TITLE
Table exports to PDF without images

### ISSUE THREAD

**Issue by martszu** [bpampuch/pdfmake#1127]
Hi!
I have a problem with exporting my table to PDF - I have one column only with images and in PDF document it is empty. How can I solve this problem?

![example](https://user-images.githubusercontent.com/18463038/30326970-b1c1468c-97ca-11e7-895a-a2b45876f20f.jpg)

**Comment by wsw70** [comment]
@martszu sorry to piggyback - as a side question: how did you style your table to have a dark background?

**Comment by liborm85** [comment]
Please attach simple example of docDefinition for reproduce your problem (executable on http://pdfmake.org/playground.html).
