### ISSUE TITLE
What are the available styles?

### ISSUE THREAD

**Issue by wsw70** [bpampuch/pdfmake#1128]
Hello

Is there a list of styles which are available? I tried to use the camelCase version of CSS styles but they were not recognized.

Thank you

**Comment by liborm85** [comment]
CSS is not supported.
See examples on [the playground](http://pdfmake.org/playground.html) and in [examples folder](https://github.com/bpampuch/pdfmake/tree/master/examples).

**Comment by MuffinMan82** [comment]
that's very complicated, why don't you adopt css? are you expecting devs to learn a whole new styling syntax just for a one library??
