### ISSUE TITLE
table width error

### ISSUE THREAD

**Issue by bilzhere** [bpampuch/pdfmake#1129]
var dd = {
	content: [   
	     {
	       table: {
	           widths: ['*','100'],
	           body:[
	               ['','']
	               ]
	       }  
	     }
	]
}
Whenever I try to put widths as ['*','100'], it is not coming. can someone please help me out

**Comment by liborm85** [comment]
You have to define the width correctly. Example:

```js
var dd = {
  content: [
  {
    table: {
    widths: ['*', 100],
      body:[
        ['','']
      ]
    }
  }
  ]
}
```
