### ISSUE TITLE
Resource interpreted as Document but transferred with MIME type application/pdf

### ISSUE THREAD

**Issue by JohannesHoppe** [bpampuch/pdfmake#1130]
Open http://pdfmake.org/playground.html and check the Chrome Console (Version 61.0.3163.79 (Official Build) (64-bit)

![image](https://user-images.githubusercontent.com/640639/30400067-08ba8bd6-98d6-11e7-8dd2-41e73be753fd.png)

**Comment by staminna** [comment]
I'm also experiencing this when trying to display a Image from html2canvas. How can I specify to render a image into pdfmake?

**Comment by michelsouzafigueiredo** [comment]
any help on this, please ?

**Comment by liborm85** [comment]
Chrome version 83 no longer displays this warning.
