### ISSUE TITLE
Trouble uploading file to server

### ISSUE THREAD

**Issue by robbiemilejczak** [bpampuch/pdfmake#1132]
I'm using PDFmake in browser to generate invoices and I need to store them on a remote server. My backend is coldfusion.

I'm currently using the .getBuffer method, passing the buffer to a file object, and declaring the type of that file to be "application/pdf". After a lot of trial and error, this is the ONLY way coldfusion will accept it as a file and upload it to the server.

The problem is, its getting passed as an octet-stream instead of a pdf, which is pretty frustrating. I know this probably isn't technically an "issue" but I thought I could get some help here. Heres to hoping!

**Comment by liborm85** [comment]
Issue is not related to pdfmake. Try to ask ColdFusion support.

**Comment by robbiemilejczak** [comment]
Just wanna add for anyone who ends up here through google, I did solve this.

Instead of using the .getBuffer() method, I used the .getBase64() method and then converted that to a bytearray and then passed that to the File constructor (if you're using node you can use the function b64toBlob, blobs work just as well I have tested and confirmed. If you're not using node, or prefer to use the File constructor, modify the code found here: https://stackoverflow.com/questions/16245767/creating-a-blob-from-a-base64-string-in-javascript)

From there, it's just a matter of sending that Blob/File to your server or wherever you need it to go. If it doesn't get there as a pdf you can still open it as a pdf, just be sure to add the ".pdf" extension when you name the file at upload time.

**Comment by pniewerth** [comment]
@rmilejcz Thank you, that way worked for me too.

**Comment by awinograd** [comment]
Ran into the same issue but I think I found a slightly cleaner solution:

```js
pdf.getBlob(blob => {
    const file = new File([blob], `output.pdf`, { type: blob.type })
})
```
