### ISSUE TITLE
Table with 3 or more colspan results _minwidth of undefined

### ISSUE THREAD

**Issue by Paskalouis** [bpampuch/pdfmake#1135]
Hello !
Thanks for this great library.

I am encountering the error regarding table colspan, I am getting the example from playground

		[
			{text: 'Header with Colspan = 2', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 2', style: 'tableHeader', colSpan: 2}, 
			{}
		],
		[
			{text: 'Header 1', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 2', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 3', style: 'tableHeader', alignment: 'center'},
		],

This piece of code results right : 
![image](https://user-images.githubusercontent.com/5112688/30635948-2fa6b218-9e1e-11e7-9424-484f7ab50ef1.png)

But when I change the code to be like this : 

               [
			{text: 'Header with Colspan = 2', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 2', style: 'tableHeader', colSpan: 3}, 
			{},
                    {}
		],
		[
			{text: 'Header 1', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 2', style: 'tableHeader', alignment: 'center'}, 
			{text: 'Header 3', style: 'tableHeader', alignment: 'center'},
                    {text: 'Header 4', style: 'tableHeader', alignment: 'center'},
		],

It shows error : 
![image](https://user-images.githubusercontent.com/5112688/30636051-8b92812e-9e1e-11e7-9c39-e2ab11ae4dd5.png)

I don't know if this is error caused of wrong format, but looking at the code, this should be work.
Is this currently a bug ?

Thank you for help !

**Comment by liborm85** [comment]
Is necessary add widths.

Change from:
`widths: [200, 'auto', 'auto'],`

To:
`widths: [200, 'auto', 'auto', 'auto'],`

**Comment by Paskalouis** [comment]
@liborm85 Hello , This is working now.
I just added one more span and add more param on width, it works.

Thanks !
