### ISSUE TITLE
pdfmake adds _margin":[0,0,0,0] to the json 

### ISSUE THREAD

**Issue by flexpeace** [bpampuch/pdfmake#1138]
This json {image: this.center_url ,width: 100, style: 'image',margin: [0,0, 0, 0],  alignment: 'left'} 

produces this:

pdfmake.min.js:10 Uncaught Unrecognized document structure: {"width":100,"style":"image","margin":[0,0,0,0],"alignment":"left","_margin":[0,0,0,0]}

I don't know where this _margin":[0,0,0,0] is coming from.

Can someone help me out?

**Comment by liborm85** [comment]
This works correct on playground:
```js
var dd = {
	content: [
		{image: 'sampleImage.jpg', width: 100, style: 'image',margin: [0,0, 0, 0], alignment: 'left'},
	]
}
```

What's the value in `this.center_url`?
