### ISSUE TITLE
Hyperlink image need to navigate

### ISSUE THREAD

**Issue by jitui2i** [bpampuch/pdfmake#114]
Hi,
 I am using pdfmake it was awesome tool, But i am finding typical to implement hyperlink on image , that is , on click on image need to navigate to url .

Could any one please help me out of this .... :)

**Comment by uanthwal** [comment]
How to add link to a text?? 
 {
text: 'Text',
bold: true,
url:'http://www.google.com'
}

Not able to link the text to hyperlink. Please help me out.

**Comment by liborm85** [comment]
Implemented. https://github.com/bpampuch/pdfmake/commit/a82db5de572af9c7bae79d3f0f32435dd6adfddd

**Comment by vixalien** [comment]
@liborm85 @bpampuch You also ought to support images on QR codes.
