### ISSUE TITLE
Question about the pages

### ISSUE THREAD

**Issue by MiDDiO** [bpampuch/pdfmake#1140]
HI, 
I'm a programmer and I need for my work to insert some information in the content in same page and another content if is the last page. it's possible ??? Another question i need to print the number of my page in the content it is possible?? I need this solution form the request of my client If someone knows the solution also if it's hard to implement let me know... thanks

**Comment by dorothythurston** [comment]
Hi.  You should be able to access the page number via the background layer https://github.com/bpampuch/pdfmake#background-layer or add it in a footer or header https://github.com/bpampuch/pdfmake#headers-and-footers. Also, one way to make sure content ends up on the last page of your document is to specify it as final page break element to your content... for example `content: [
			{ 
			text: 'This will be on the first page', 
		},
		{
			text: 'This will be on the last page because i have not added any other content declarations after it and I have specified that the page break should come before it with pageBreak',
			pageBreak: 'before'
		},
	]`
