### ISSUE TITLE
Please consider adding font stacks.

### ISSUE THREAD

**Issue by geon** [bpampuch/pdfmake#1142]
CSS has the concept of font stacks, where another font will be used a fallback in case the selected one is missing.

If I want to use mixed English and Japanese text, I must currently merge font files for each font I use, which is a huge pain.

I would rather have the rendering fall back on a Japanese font in the places where Japanese characters are missing in the selected font.

Is that even possible?

**Comment by liborm85** [comment]
In pdfmake it is not possible.
But pdfmake internally using [pdfkit library](https://github.com/devongovett/pdfkit) for rendering pdf, you can try to ask there - [pdfkit](https://github.com/devongovett/pdfkit).

**Comment by wrobe0709** [comment]
@geon - I have this same issue with English and Japanese text. Which fonts do you merge to get English and Japanese working and what tool do you use to merge? Thanks!

**Comment by r0the** [comment]
I recommend using the [Google Noto fonts](https://www.google.com/get/noto/) for a wide coverage of languages.

**Comment by Avital-Kapiloff** [comment]
@geon how did you merge the font files?

**Comment by geon** [comment]
I don't think I ever did. It was too much of a hassle.

**Comment by stefan-kolb** [comment]
See https://github.com/foliojs/pdfkit/issues/201

**Comment by linhcub** [comment]
Hi there
I have the same issue. Currently, I am working on a project using **IPAMincho** font for displaying Japanese. It works perfectly except for Emoji. Hope it can be done with PDFmake. Any workaround by now?
