### ISSUE TITLE
invalid image, images dictionary should contain dataURL entries

### ISSUE THREAD

**Issue by navexor** [bpampuch/pdfmake#1143]
Hi.
I'm trying to insert one base64 encoded image to pdf document.
Here is an example that can be reproduced on [playground:](http://pdfmake.org/playground.html)

`
var dd = {
	content: [
		'blablabla',
		{
			image: 'data:image/png;base64,R0lGODdh9AH0AZAAAAAAACUAACH5BAgAAAAALAAAAAD0AfQBhgAAAAEAAgAAAWgAm4kAwogAwGYAmYoAw2gAnAEAAQIAAwMABIcAv4kAwY4AyYgAwREAGmkAnZMA0IsAxJEAzHMAoowAxoIAuBcAIAcAClUAd2cAm2oAnmQAjXAAqTQATpUA00UAYQUACJEAzmIAk5MAz20Ao2sAoVcAgooAwksAcY4AyIsAxY0AxzwAVnsArhkAJAsAEA8AFioAO4QAuwMABXYAp1wAgy8AQx4AKyYANkcAZkwAbAgADFcAfDgAT2cAkkIAXRQAHG8AnYEAtiIAMWAAiH4AsjMASFAAcWIAi3EAoGwAmVIAdW0An2oAlmQAl2YzmWYzzGYz/2ZmAGZmM2ZmZmZmmWZmzGZm/2aZAGaZM2aZZmaZmWaZzGaZ/2bMAGbMM2bMZmbMmWbMzGbM/2b/AGb/M2b/Zmb/mWb/zGb//5kAAJkAM5kAZpkAmZkAzJkA/5kzAJkzM5kzZpkzmZkzzJkz/5lmAJlmM5lmZplmmZlmzJlm/5mZAJmZMwf/gACCg4SFhoeIiYqLjI2Oj5CRkpOUlZaXmJmam5ydnp+goaKjpKWmp6ipqqusra6vsLGys7S1tre4ubq7vL2+v8DBwsPExcbHyMnKy8zNzs/Q0dLT1NXW19jZ2tvc3d7f4OHi4+Tl5ufo6err7O3u7/Dx8vP09fb3+Pn6+/z9/v8AAwocSLCgwYMIEypcyLChw4cQI0qcSLGixYsYM2rcyLGjx48gQ4ocSbKkyZMoU6pcybKly5cwY8qcSbOmzZs4c+rcybOnz59AgwodSrSo0aNIkypdyrSp06dQo0qdSrWq1atYs2rdyrWr169gw4odS7as2bNo06pdy7at27dw/+PKnUu3rt27ePPq3cu3r9+/gAMLHky4sOHDiBMrXsy4sePHkCNLnky5suXLmDNr3sy5s+fPoEOLHk26tOnTqFOrXs26tevXsGPLnk27tu3buHPr3s27t+/fwIMLH068uPHjyJMrX868ufPn0KNLn069uvXr2LNr3869u/fv4MOLH0++vPnz6NOrX8++vfv38OPLn0+/vv37+PPr38+/v///AAYo4IAEFmjggQgmqOCCDDbo4IMQRijhhPUIYOGFGGao4YYcdohhMB6GKOKIJJZoooc8nagih7QEkIAsAQTAiwIClCOAjK4kgKMrO0ZzowKt9NjKiwDUsMCRSCap5P+STDbpJJJAAiAkLUQC8OSVWGap5ZZcOlmDIFWqQmQACpRp5plopqnmmmwuUE2UgnQpJ5NfxvIiBkZUoOeefPbp55+ABsrnEBrAIOUtRH7QgaCMNuroo5BGKigQOAwJQA9B+IDCppx26umnoIYqKgpNzBBNAi8uMEMSHSwh6at/PvGDLECA0IIDuOaq66689urrr7pKcEClU75SYwA3SEABsMw26+yz0Eb76woUlPDBoajUWIMPHpzg7bfghivuuOSW+60H14aZTJRIVOCAstLG2yu1IASBrSo1LlCBBQU04O+/AAcs8MAEFwwwAy08gMG9sci4AwgMFECAwRRXbPH/xRhnTDABDDhgg5s1niKjDiZAscHJKKes8sost+zyyQZwQEIPAISMTAJAxnDDCA40UMADGgc9MMcWEEGzuiIDkEQJBRzg9NNQRy311FRXHTUDEuwAAJyw1CjCCxY0YPXYZJdt9tloj00ACxccjQqQH3hgAAJ012333XjnrffedA+AgAEQAID0MDjO8ALTYqetuNUETMDAwoOXImMOFhCw+OVjN+DAEpGzMvIKlmMu+uikk02ABRdkIPjbAMQ9N9+wxy77ABEAvvoxQAbAgwMrNF266I0/fnsrQ1DwwO+jp3DABDkw7AqQSUjgO/KipxA69Zef3vbwpcAtt+zgh383/+22d96LiwDAMEQJE2OfveOQtwKkC0y7f3kBEoSw9Sw12NCz/YtTXuUAmDbtue0U3nud+BYYO/IFzny7iJILGECB6RHwbMGLHyteBAEaTOB6FyTbAyjAhFnIqAgtIIDyQli2FHyQCANkodpQd0BTJJCBOOSbA7n3C5wBQGcjYIEFZag2+PEwFTIywgiGSESpNa4BhipWKoDEA+k1MXMO+MECnmC8K07NgEcUxQ1zSMbx1e6BwijcC5YIQi9SLYNhRCAAcECBxLlRagUogb241ooF+M+Od3waAVZggy81wYqBdBoYIdiJMZbxkTtkZC1yt7veJZJxRpRkKGrUgxek8P+STxvhExoGgByw4AArBGUeeSAIDdTvkotkneseSctI/gJ96mMfIEEZNThqMhTQQyQogyeEONoQADsQ5iVXaCgAaECZd4ylHGdJyzLashcSpCATeQk1X75icjHkZQFG4IL95WgJ/+OlKA/1zG1eUZrHpGY1c3hNXfgQiELkJiaF98tRFO946qQAEGoWpFJOAJXcHGc5v9TOYdLQmJ9w5DwZWE9cqJGN+tynBp8HAPq504vEhKgYARACaAZybReQwf4aCsuH9hMTEp2o+CpqC0ry7qMZVWQmYcFBD7YxkOOcFR9TwYQuirMEN5CSjFiaSHh2r3XfkylFzyjSIL0ol+3/y6lGqyo5ACgRp00sAAWUwFVPyAgGDfggNzVnKgUs1aQgdaksoyrVmVL1pcfsqDa1arqdwgJIdNzlSVlAA5XiFaYACMIrQak5G4hAcG8FKwudSoqY1rWBd63FPXeWT74WkZ+x4KQnf3rHoJpTFUUFqCqztr/IOnR7h62EZS+rw8yaUBCGw6hnP7vRVwRTsjIcpxHKuokXCYEBagWl8ggQRXbC9Z1ynSZdaYvZ8s3CppbcbV9BS0pTpiCVTS1aDIibifktkZsjHOggXNtS2M5VgdSFHU03eNX1ZVW7vCVvKVKLXgog4bSnAIJRVTkCoQqCveF1r3ThG9+9zVdMgphg/wXxazZvymJ+i73kOJMa20kYF7mkBSkLiGDYAzvzuU2k7Chm22AzWjdHABDBDUrQWQpvt7eveJEMaMCCEEOXCOPtcCQwDFwW5tEH90LwSaMbz+m2OG8PVoUSIOZjG/fSrzACwM6KHELNVWqooHiREs7LSwI4wFQ7UnI0mfxUeT4ZyrZlBdxKwADwWnmrQvYEYOuY0BIgWYqd0DGPq0zExj7WZmp2o4pH6uY3uxiNrxAwl61sYVl47QWgK3MLjlBDYALgB2Rerda4lui4KrjJDHZ03aJcihpl4AjhvHN+86xnAFRx0gT0MoDDDAAlTFi5B2Auw0oN3VO32cmq7lucIf/cgwvEWtZVq3SWc3BQO5dWAhpwnideFIML9Dig6i0EsVPM5spCNdXJZjUpXpQBZxMa2sHGci34O8wVvODQI0XCgDVc4F2Pm4iL9nSjk40AdY/iRc1+NrydKO8LdzTDTXWADrTNiRdtucwjLjEh/i3DgIOCxY42uCgQ7u6F49kWgv72aptAcU1wG4bvNrKftc3xyZZ7xecm+KP1W/FLldzkb2x4li9e7xd8yWaNBIC+VQvLM9P8xLh2n8cjmnOdr3rZqSC5woGuU+5Oco581nQRWo4JGfkAxU00NEHFDfXXdtrcA0831lGh9ZjLWtqzuHSmV8tKMGMC4Uf4pCpLMOr/Q9Q8hFOvddxVLfJQ1J3rXxS6w2/Ny8YevdY4SCcsD6Awih/+golP+uJDPvdTPB7yV/Z6LSZXbeWmwAJjB3QlzA7xO6Z37Yb4PAFDzwmQv7nxvE643e+Md1vQW8Os9XslXB344RPQtH7XPQB5vwnfPxn4nzg96gUpeYd7tPKbkz0lPuf86Ys3jtK3H/U1Yf0WY3/bPt8614s/Cx17u/zuUx7zyD4JGR0y6u5zZGSXflJ3c4yGbHL3YqugfdsXb6pnCzIyYwCIPfhTeJqgd/gndSswcYBGgNizfuVVdVZXcKVnCgy4ffR3XQAwA2F3SZozBJ0wMg6QgdjTWG6iCB5I/z0giFij93slWAoniHopaGkxZgN711QT8ADNFYLRM4HUU4G7xnZMtWTGBncIyHg/uG7xR4O7NYSTV3tuhD97tAn9M4PDxHlLiAg5iDw7eAnt12DvF2hb2IDc94AQmD5OY21eNEIlpAkn1ALfBUq3h3SG13bt9XY414PXl4UHN4d06IA4lgtcxHTRlIQLI36NQEVoR0TQtwhr+DttaAlvGF9x2HPC94iQyHOqYF5OiDwKFYWToADuIlhxBWQi9YmlE4qyJYJWV4rF5Yh06IWyYH8ql0iDeAmTk4eD92eMgIuko4uUMIrU5YsuB4wNKIxDB4bv5DjFJGRAkkytCIobyP9/JjaFa1aFiXiFpKeAzPZzwdh9X8eCtOhFr6h8jhAA6DSPaecxN9iMhphgiHiA6IaF7Jh11oiC8EgLXmOEXPg7YkVWHcZ6CIV8FuiJ/0iFASlw6uiDBUl3BymECUkLVKSNKUZYGicJQBIEm8hCLlQAl9gIzjg60BiLvKhz1JgJQQh52JhlMKCM/GZglXB8QEUBHVBWMQk8BqiRA7mOkLaAH6mTIWkLk6hKY6WKZ5VWenhFI/Rf9rhxF3mOGflxNUlwN/l3Tzl/UamCLhBqg3UBQYaSiUWSAGcBR/CWMPmVipaUYqmI7seII3eWQLeTwwgAMnB/guhfsNgIU6lhJZD/bZi4XnhpamFJdXwJhxEABU3ZjvIXmGl5WxJIYBwWCR+WXE01jo9ZjiuJeA/lIqjSmq75mrAZm7Lpml/iAht5fQgQAQuzALPZm775m60pI83GAg1AAMZ5nMiZnMp5nDklmA43A5q3ZLbYT6zIWA5QAV2Ze5FZbHWSCjGgBBywASNYNxtgAloDCzVAAw7AAhbQnu75nvAZn+55X8PUmUQoAn/EWBTwZZBQIwJGiWFYAvqTnV5pjopGWDAgAxCwoAzaoA76oBAaoQ6qAzdwAuI5nuR5AjsAAxLaoR76oQ0qAzBwBDRwASZ6oiiaoiqKoisQnUhohxGETKl5QQJ4mqtz/1ykeUct+ZKPcJSjUwADAAUGMKREWqRGeqRImqRFCgXecqEYSp4mwAFCqqRUWqVWSqRQAAM10ANc2qVe+qVgyqUZEAMzUAEt+KKRuAtnZTlZCXCbNpmEACSgFo6kI1ZF+VI+KjoPwAG5GQF++qeAGqiCOqiECqgn86R4I56FuqiM2qh/igAcYAAqpQkyMFr1CaO74J/7dke6RqCr42t0OjpbmZiJkKeYs6fiOQCquqqs2qqu+qqwyqqI6mCxWqu2equqKp6YKSXAOZsCkABfwgMQc6lpGqNzulrMyAgp15DPSJd22aPbuYfhOavUapN+yQhuEgLDCkv2WX+ESQTFGP9NLfACqkOIhyCnbFlajUmOhWigtjet1RqvHJmZlJCt24qmqggLtBeqwGOaytprv1aaHCgJpno5qCqvCGuZHSkJ9soAxJqv37SCZoh8LCd+L7eZMqQ52Dl+0aqV8JqwICtVZRknJHWvJ9WteVeELgpS9lauigAkSzd4A9p/HdtEBxuyODtPI2slJeuw3IqpMyKj/Io5gzSwiWBx6QpSE+CS7NquMxpCN5uzUktGO9uwD0trnpM+bIp8fXe0PwRzlzRCd8qx7upGUTu1aGtXCxsJVvuzxdoLmgqgV2R5Lwt2+khEo+qp2lm20uqkafu31UWvk9C2+Iq1cvZpSXtF1gP/ey23r7D0pvlasItztoBbuXC2tpBAuCcLtLygY+DKrD8qAV1rCIAneEAlARU7ezWLtx9rua5rN1Xbs1drDI6bSJqzBFIEWCsLUi0Qe6rLtx7rt6/7urGrrT5buLQrsaBbPcvTPFNidk9rP7dro2q4ujJEucNrucVrspXIubywkLsbVslXCK5mqYmUR2P4u9FLQNibvYC7vce7uW/rC9+4vjUYftqpA0fYvd1oCZKrOO3rvmkLv7ObvDBgOcubPcGWhofyfxpWlXn2v2kTwAI8tQTsthDrrf/JmOlLUBmAaQlssIipt9ULvDbbuhX8txeMvLiDuEM7uSTEdvobwotD/wCQG8HWy0IUnMI4u8Lym8GDGQNgG0guBEXYookvrDj4k7rImMNQi8I8bMHXugia273ze0sA4ANyaWQS0MFleLeT1btNa5EmzLrCG8VS68NWDMRZNsNhK1CQWQSV06YsNL1+6MQXtMNojLBqrGgoqwt+FL4dx42Cg8QcTKqQIMFoo8d7HK99rLTe+wv1m8RpU49Sko8v2r9lh8fsC8WNDLKPvI2R7AtndTw0PMFwLJF0HEIPycaoScmT68mfzMdTrAhV7Mej7Atx21SEFThC+8ZcecdlfL2yPMuOXMuJcMuQfMXAgK6wfDamhY+CHMYvAKfQOsw6XMzGTK2hnGJ/nP8LF3vKi0wBo6QDFjB4STDGd4nNT3zG23zMmPsIyizKzAwMtbtkL2CYRHw6vivM9ms/jPzO49nNAPfNuUB+9RaubvSChguZ7JzH2izQGErQg5zLwBDIYDxZ4lzJeoTIBMvJABTQEm2t8ewI8+zNFk2/v4yKitM4NKDJ/vzMExzRI92LyIwIJ13QKX0+6WPKLF3JFDBcDf3K6EXTNU2WN30IOV3R9QwiALDBP302I8SfnKDIUm3UR02QgsuwsovBQ+1wxxrVZWPD1ezKBfrP7iPSWT2vbLzUk2XQ9vRDsLbRVpZH6Uy99wjSAI3Va72IJd0Ibo14cK0LS7XFYr24/Vz/1Xqd1nzd1wq71Wzb1SzcDAgt1lbD0KBg1Waj1o5NikltCIENeoMdQbNo2VWDvh5NtmiNPZzd2bRF0W+905JMUobN0i4N04r90J3szq6t1W0t2T/81beFAQUwAavM0mIl1Jm92Kzd2L1dV7At2LLdQwDQAQFr2qG0n6mt2jK9yM793DIV3aI93Sods9gtSONqzdxd1LwN3n3519gK3Gss3N4aA3N93k5j1+r80bod0t/t3tUk3rs32mrqTLXdgK/nvKGg2WXT2gAe4J9dCKE94ORNygDgxuc9QjA4CgwuQv/94NYU4YQw4dNH4DNS2tidR+VEwvy92tTzABGwAbg6/+MzDso0fuMzrqvPWgkkrn4mrgtAEgIHjpY0ANkxjV4nwAFKvuRM3uRO/uRQ7uQI0N4juAEREOVYnuVazuQeYC9Y2+NS9+MHDQDEbdymLVz7TbP97T5LCwUk8OZwHudyPud0XudzHgEWGq8lY+d83ud+DudG8AMyYq6DK9+43NTG8CLW3d2Vp90s3uKMbjqoEwM1IAKWfumYnumavumcnukY0AQmQOXJxgEuEAOdfuqonuqXXieEXujGW8DSALObiopkTTOtvgkdHm2o81iqIGN5jqHlWU7fdOtc/epeTQ3cdt9RjT/p/OiQ7naCsyLSXiRjmW5TXkxAIu3afiGeAP/mHyjmhM3cFHY6Cs7h4p6LekmZt9mXu0rfrODtOgjuY64DpouKGp40a66D6a546/7YZh0L8M6G8k7YmIzcJbDiXZXvbLjvotfvng3fvhDwoDjwuJCSQ058E1Dk/46D596s6CiQEy3itiDxuUjxiAIAOErXQDUCyp3wLo7uH6+UIQ/xvUDyz2jyJw+qqNgAjm4Kuf5GDN971e7b7r4KNi+TOF9TSjfr85feuGfuCg+KQV99Q8+UG/8KRw88Sa9Zl9J8dMjs233kh3j1iyCNry3ytZD1RLv1qwcADrx938UC5e7ykT5DMb+XDj+NaE8Lav8+FU44AIBCKq+VMYxEHS//k1PPflXP1kWvCn1fw2wPgQUPeSoe9mIPkGRft5X58EYuDI/f0pEvknFZ96BnkplfqoePlHev7kvJ+Mvw+QUU+t6a8pQ/AkmF15sc9TCv3lS/+XpP87wA+2jjnMsgZte9cDxP1fj+8h7P+4rv+2cP/Lsg/Bgk+ypo3iY3SPf29HQP7Y1vCGZ/WTs7C9RfYdY/mD3g9SaHP6OLCj//RYkfgtAv/ntP/oa+zKdf4G8Pb/o398sPCAUHg4SFhoeIiYqDBBYXPQAJAJOUlZaXmJmVCgAfHgYIoaKjpKWmp6ihAxEGEJGasLGys7SXCwAhIAyLvL2+BwQTDBivtcbHyMmW/wEARS0Ev9HS04YPFEzK2ZXMGhKC1OCKjY/F2sacnqCp6+ztq63l5vLzt7m74fiGwcPx8/7/sQIscdAgn0F8BUq4AMAJIC1u3g4aHAdJkkNY6D6128iR1DtXFi+KlFVPl8R8+4iFHMlSHqcgEU/K5EWABQ0Z/VpuA9Dt28xpFHO2zKiuo1F2H4XqZFny3k9pKZUunRpLkhAaE6A93TqowIgbAJhRXcYzJldfQVcuJXq0baqkaseKbHr2V9S4cvNekmSEgs+6MhtQwMFQ7ySIfwEnSiuXrdvHHlmBNDySruJFdylr3gQAB4UHl08SWPFCBAABlBGHFueoYuNOGiHLRv8Ad7NDy6sPZbatWVKPF89y5ysggUfh1GUTCwfWWqpIx7Mf1+btD/dyRsJUUtfMLEkJ5dd7pTgwIUdY7snDE2I8Fnr0ttO3m7N+fbf8vMyKWCAwXv0va9jYppp/7FHl3ntGxXefMvQtZ9+CciUwBEH+/eLVQg0h11OFBU51IIIcKQjhMQ0K9+CIawEQxHcV9lLTBTjhNdaA6nWYYjogwieZcyhqUmJuJ/bIklVYadViIgmBJRZ6GxLYnIwjfZgjUjtCKWQmP64W5JUi8eXXkYoINsNxTJoVno06STnlW1VyWUuWoW3pJkCceAYamLqtYINpqG1G45lPvobjmiG2OSf/SbiYRGB2PB6qjW/AGYlnVyUYl2GZ4AEZaHuwFUUolfBY6SgAcF4m56jydMfipIP0B8N5AqbnJDmiOqTmp6WIiGolpSp26q7Z5Ldff5Na84R8f9a3qYGd4uqOocBa0itgv0arjIQUsnohmX7ytGqNy3rYrLPr6BrttHVVa+0xL30L5osxUpesg+HeGBu5qJgLLLpnqbtuLURmNWmSsPI2r4n1pjkuvqfouyu/XPn7Ly1eZhqemNx22yS4tAp6L8O5QvsvxFtJPLEsdX6G52h7nrbdwZp2zOmgIIcc6smkJurUmYzWirMskAZ3ZEKWIisrx67N/HHNojiMKslPmfyz/yacJGGmeq4WbPDRgMrMLM1MNy3yulD/JPXUmDCTw35HGgshzFomPNTCYasytrVlz3Q22pkMoXKFCWF4H9xxys3SrQw7PWreMu3NN2cuuFsfCzA2KhfhphoeJd11K+4o46L1/Hg2kkBQpH8J+aC1vFwr67W4YHd+97k6cyj66MowY8QIFpvqwJhLvtw6va/b66nsN58MukSO416YZwVd7EDLfRq9cddJf7102J4fuvxBzeOO2m9CL0fcDhmzfr3r2cO+PdPdz/n9RLc7j0zVV4c2HgGvBi/8+sRrn/HqNor4uWl+KKmf/YyhNrYtxxpAcNnbhoew4iksdtyb3b5qt/8ofvhsgX37W2688oP0qS9/FRTgBd9XMwNyCYH4CJ/zOOEC3pmIBUSI1wQ1IDniZcBy/0AcvlYBhckoj4M1UiAIKQYACDBAYKthQAlQsDrr9fCGNFDh3DBYt+RNDIbhGE8BtLPEY3QHBAUowAPWyMY2uvGNcIzjGhmwAhaYx3/yoaEu1CjHPvrxj2xkAAUq8EGA5McEBjDABhbJyEY68pGQjKQkNwCFEyihBhKcWJ0kwAA+AvKToJwjafhUxmP0yQcUKAEFVsnKVrrylbCM5SolQAPC4FE+ksjAEEAgy1768peulEALgGeYBPDAAyZIpjKXycxmOvOZ0FwmMacWgA7/8BKY2MxmK0swgg9UsZRAm8QMfNCBcprznOhMpzrX2QEj7AAnt7yPb0KgBHba8574PKcPigBEh6AmADhQgUAHStCCGvSgCE2oQENgHr5JogZBMEI+J0rRc95gTNUDpzESUMh/xHNBHdXJR5eSUduE9FAnHZJGgzXSfyRAASmlzEtLip+WTiUANL2cTa0lAJj6aacrDapQh0rUohr1qEhNqlKXytSmOvWpUI2qVKdK1apa9apYzapWt8rVrnr1q2ANq1jHStaymvWsaE2rWtfK1ra69a1wjatc50rXutr1rnjNq173yte++vWvgA2sYAdL2MIa9rCITaxiF8vYxjr2/7GQjaxkJ0vZylr2spjNrGY3y9nOevazoA2taEdL2tKa9rSoTa1qV8va1rr2tbCNrWxnS9va2va2uM2tbnfL29769rfADa5wh0vc4hr3uMhNrnKXy9zmOve50I2udKdL3epa97rYza52t8vd7nr3u+ANr3jHS97ymve86E2vetfL3va6973wja9850vf+tr3vvjNr373y9/++ve/AA6wgAdM4AIb+MAITrCCF8zgBjv4wRCOsIQnTOEKW/jCGM6whjfM4Q57+MMgDrGIR0ziEpv4xChOsYpXzOIWu/jFMI6xjGdM4xrb+MY4zrGOd8zjHvv4x0AOspCHTOQiG/nISFNOspKXzOQmO/nJUI6ylKdM5Spb+cpYzrKWt8zlLnv5y2AOs5jHTOYym/nMaE6zmtfM5ja7+c1wjrOc50znOtv5znjOs573zOc++/nPgA60oBscCAA7',
			fit: [500, 500]
		},
	]
}`

What is wrong with this image? This base64 URL is absolutely working and I can open it in the browser.

**Comment by liborm85** [comment]
Image is not PNG, but probably GIF.
