### ISSUE TITLE
Small font size in latest chrome when printing with Epson FX-2175

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#1147]
We are printing some receipts generated in pdfmake using Epson FX-2175 dot matrix printer. It is working fine in chrome browser with version less than 50. The latest version of chrome prints the font with small size even though we setup the font-size in doc definition to extremely large.

Is it the problem of printer drivers or pdfmake core files?

**Comment by liborm85** [comment]
In pdf file is font size correct?

**Comment by mpsbhat** [comment]
Yes @liborm85, Might be its chrome browser's issue isn't it?

**Comment by liborm85** [comment]
Then there is no problem in pdfmake, but in Chrome and print capability or in printer drivers.
