### ISSUE TITLE
Two large images in header, only the first overflows

### ISSUE THREAD

**Issue by FelipeMicali** [bpampuch/pdfmake#1152]
Hello.

First off all, I'd like to thanks for this awesome library, it's really helping me a lot in my projects!

Right now I'm facing a problem. I'm trying to add two images in my header, in the first page, something like this:

```js
var dd = {
        pageSize: 'A4',
        pageOrientation: 'landscape',
        pageMargins: [40,60,40,40],
        header: {
            columns: [
                {
                    absolutePosition: {x: 0, y: 0},
                    image: 'sampleImage.jpg',
                    width: 300,
                    alignment: 'left'
                },
                {
                    absolutePosition: {x: 0, y: 0},
                    image: 'sampleImage.jpg',
                    width: 130,
                    alignment: 'right'
                }
            ]
        },
    content: [
        'Here goes your content',
    ]
}
```

I need one image in the left side and one in the right side, and both of them must have heights that exceeds the top margin of 60.

The problem is that only the first image (in the first column) is kept in the document when I set the width to a value that scales the height to over 60 (the top margin value). In the second column, if I set the image width to 200, for example, it's height scales to over 60 and the image is not visible.

Is there any way to correct this problem? I need to scale all images in header heights to over 60 and keep them all in the document flow. I can't understand why this works only for the first image. This is not working for vectors also.

Thank you!

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/ed485a88a6558db033b5149fd5a8db49568ef1e8.
