### ISSUE TITLE
`printer.createPdfKitDocument` does not allow working with the PDFKit page buffer and `switchToPage`

### ISSUE THREAD

**Issue by nblumoe** [bpampuch/pdfmake#1153]
I would like to be able to use `switchToPage` with the PDFKit document that is being returned from the printer. To do so, the PDFKit constructor needs to be called with the option `bufferPages: true` here:

https://github.com/bpampuch/pdfmake/blob/69a38a04973e978790b18f8078f31f9cf11fced7/src/printer.js#L88

At the moment there seems to be no way of passing that into the printer method.

**Comment by andrewckor** [comment]
I created a pull request with the same code, I hope they merge it as soon as possible.

**Comment by liborm85** [comment]
Added by PR https://github.com/bpampuch/pdfmake/pull/1268.
