### ISSUE TITLE
Jump to page number that TOC generates

### ISSUE THREAD

**Issue by karanbhavsar007** [bpampuch/pdfmake#1154]
TOC puts page numbers after rendering the document. Is there any feature where I can jump to that pageNumber when I click the TOC Item?

**Comment by dorothythurston** [comment]
This was just implemented... Now you should be able to click on the number in the TOC and it should go to that page... see https://github.com/bpampuch/pdfmake/commit/3749a25186bc5348585b3f66c9c367355e9aed47

**Comment by karanbhavsar007** [comment]
Thank you so much for looking into this.
Somehow, it still doesn't work for me. I am using latest version of pdfmake cdn

**Comment by dorothythurston** [comment]
Yes the version has not been bumped to the version that includes this commit. If you use npm to pdfmake regularly you with have to wait for the version to be updated

**Comment by dorothythurston** [comment]
Or you could point your npm to the master branch if you didn't want to wait https://docs.npmjs.com/files/package.json#git-urls-as-dependencies
