### ISSUE TITLE
Images or Canvas Vectors with same height as page

### ISSUE THREAD

**Issue by FelipeMicali** [bpampuch/pdfmake#1157]
Hello!

My question is exclusivelly about pdfmake.js

I'm currently building documents that have margins of 40 on left, right and bottom, and 60 on top.

I'm trying to add an image or canvas vector with absolute positions that will have the same height as an A4 landscaped page that's going to work as a background image.

The problem is that it seems the margins are not allowing me to put these elements in the whole page. When the element height is higher than (pageHeight - marginBottom), I think it understands that this is higher than the available vertical space of (pageHeight - marginBottom - marginTop) and the element disappears.

Does anyone know any trick to add images or canvas vectors with the same height as the page when using pages with margins?

Thank you!

**Comment by liborm85** [comment]
This should reproduce your request:
```js
var dd = {
	pageSize: {
		width: 595.28,  
		height: 841.89
	},
	content: [
		{
			image: 'sampleImage.jpg',
			width: 595.28,
			height: 841.89,
			absolutePosition: {x: 0, y: 0}
		}
	]
}
```

I tried it on playground and it works ok. Where is your problem?

**Comment by FelipeMicali** [comment]
Hi!

Thank you very much for answering!

I tried your code in the playground and it worked, even for pages with margins. I don't know what I did wrong for the first time for images.

But the problem persists for canvas. Try the following dd in the playground:

var dd = {
	pageSize: {
		width: 595.28,  
		height: 841.89
	},
	pageMargins: [50,50,50,50],
	content: [
	    {
	        absolutePosition: {x: 0, y: 0},
			canvas: [
				{
					type: 'polyline',
					lineWidth: 3,
					closePath: true,
					points: [{x: 0, y: 0}, {x: 0, y: 791.89}, {x: 100, y: 791.89}]
				}
			]
		}
	]
}

It works fine as it is, but if you use y: 792.89 for the polyline points, the element breaks the page. Is it possible to ahieve canvas elements with same height as page?

Thanks again!

**Comment by FelipeMicali** [comment]
I've tried everything but I couldn't find a way to put absolute positioned canvas elements near page bottom... please, help me solve this problem, I'm really in the need of this solution!

This is what I'm trying to do:

`var dd = {
    pageSize: {width: 841.89, height: 595.28},
    pageOrientation: 'landscape',
	content: [
		{
            absolutePosition: {x: 0, y: 0},
            canvas: [
              {
                type: 'polyline',
                lineWidth: 0,
                closePath: true,
                color: '#fce5d4',
                points: [{x: 530, y: 0}, {x: 650, y: 0}, {x: 841.89, y: 50}, {x: 841.89, y: 270}]
              },
              {
                type: 'polyline',
                lineWidth: 0,
                closePath: true,
                color: '#fce5d4',
                points: [{x: 0, y: 400}, {x: 300, y: 555.28}, {x: 200, y: 555.28}, {x: 0, y: 500}]
              }
            ]
          }
	]
}`

when y variable is higher than 555.28, it breaks the page... somehow pdfmake won't let me put absolute positioned elements near page bottom.

Is there any trick to make it work?? Why this works in page top, left and right and not in bottom? I need y values the same as page height (595.28) instead of 555.28.

Thank you very much!

**Comment by liborm85** [comment]
Fixed by commit: https://github.com/bpampuch/pdfmake/commit/35ab3c00dfb014c3f91adb4141f640ede8205557

**Comment by FelipeMicali** [comment]
Hello!

Is this bug corrected already? I saw that a new commit was made today. When is it going to be available in the main minified browser file?? Or how could I add it manually?

Thanks!

@liborm85

**Comment by liborm85** [comment]
You can build it from sources, see: https://github.com/bpampuch/pdfmake#building-from-sources.

**Comment by FelipeMicali** [comment]
OK, I'll try to do it!

Thank you very much!

**Comment by FelipeMicali** [comment]
This fix is working perfectly!

Thank you very very much, @liborm85 ! You saved my life! =D

**Comment by FelipeMicali** [comment]
@liborm85 , now I'm facing another problem with absolute positioned images.

Try to reproduce this dd in the playground:

var dd = {
	pageSize: {
		width: 841.89,  
		height: 595.28
	},
	pageMargins: [50,50,50,50],
	content: [
	    {
			image: 'sampleImage.jpg',
			width: 80,
			absolutePosition: {x: 50, y: 500}
		},
		{
			image: 'sampleImage.jpg',
			width: 80,
			absolutePosition: {x: 250, y: 500}
		},
		{
			image: 'sampleImage.jpg',
			width: 80,
			absolutePosition: {x: 450, y: 520}
		}
	]
}

You can see that when there are more than one image, the ones near page bottom breaks into next page. If only there is only a single image near bottom, it works fine. This problem also exists when an absolute positioned canvas is used after two or more images, like in this dd:

var dd = {
	pageSize: {
		width: 841.89,  
		height: 595.28
	},
	pageMargins: [50,50,50,50],
	content: [
		{
			image: 'sampleImage.jpg',
			width: 80,
			absolutePosition: {x: 250, y: 550}
		},
		{
			image: 'sampleImage.jpg',
			width: 80,
			absolutePosition: {x: 450, y: 550}
		},
        {
            absolutePosition: {x: 0, y: 0},
            canvas: [
              {
                type: 'polyline',
                lineWidth: 0,
                closePath: true,
                color: '#fce5d4',
                points: [{x: 530, y: 0}, {x: 650, y: 0}, {x: 841.89, y: 50}, {x: 841.89, y: 270}]
              },
              {
                type: 'polyline',
                lineWidth: 0,
                closePath: true,
                color: '#aaaaaa',
                points: [{x: 10, y: 0}, {x: 30, y: 0}, {x: 600, y: 500}, {x: 400, y: 500}]
              }
            ]
        }
	]
}

Could you help me fix this problem??

Also, I'm willing to contribute whith this amazing library, as I'm using it in my projects, and I'd like to learn how it works and help maintaining it. It's a really powerful resource and there are a lot of missing features that I need in my projects and are absolutely possible to create.

Thanks again!

**Comment by liborm85** [comment]
same as https://github.com/bpampuch/pdfmake/issues/1152
Fixed by commit https://github.com/bpampuch/pdfmake/commit/ed485a88a6558db033b5149fd5a8db49568ef1e8.

**Comment by FelipeMicali** [comment]
You are a true life saver!

Thank you very very much, @liborm85 !
