### ISSUE TITLE
[REQUEST] Change filename of downloadable PDF

### ISSUE THREAD

**Issue by CaptainMack** [bpampuch/pdfmake#116]
Hi!

I've looked through the docs and simply can't seem to find a configuration option/parameter, where I can state the filename of the pdf-file that is being generated. I simply want to dynamically change <filename>.pdf

I guess this might not be possible as the filename is hardcoded as far as I can see: 

d.prototype.download=function(a){a=a||"file.pdf" and so on.

Thanks in advance,

Chris

**Comment by erdemlal** [comment]
is it possible to give a custom default name to the pdf while the user opens the document in a new tab with the
pdfMake.createPdf(docDefinition).open() method and then uses the save as option?

**Comment by moffsugita** [comment]
@erdemlal Yes. I hope it. now it is random Hexadecimal name.

@bpampuch is it impossible?

**Comment by moffsugita** [comment]
I thought I should do like `.open('hoge.pdf');`

but error...
```
TypeError: Cannot create property 'autoPrint' on string 'hoge.pdf'
```

**Comment by swadhinranjan** [comment]
Is it possible to make pdf name dynamic, instead of this download('myFileName.pdf'), I used download(this.pdfFileName) , I am using a variable, but it is getting undefined here. Any possibility here to make pdf name as a variable.
