### ISSUE TITLE
Create multiple pdfs and merge them in the end

### ISSUE THREAD

**Issue by FelipeMicali** [bpampuch/pdfmake#1160]
Hello!

I'm building a report that's going to have different attachments, each one having a specific styling and content for hraders, footers and pageMargins.

I'm currently struggling with header and footer functions to create different elements for each attachment, and I haven't find any solution for different pageMargins for each attachment.

Is it possible to create multiple pdfs from different docDefinition and merge them all together in the end?? How could I achieve this?

Thank you!

**Comment by dorothythurston** [comment]
This question has been asked before of the underlying library pdfkit which does the conversion to pdf... but it doesn't do merging multiple pdfs once they are converted to pdf. There are libraries out there that do that though that you could google for
