### ISSUE TITLE
Conditional Statement in content

### ISSUE THREAD

**Issue by MyQuestion123** [bpampuch/pdfmake#1165]
I would like to include a conditional if/then statement in the **content** part of my PDFMake code but haven't been able to get anything to work yet. I can get it to work with header/footer commands but not in the content area.

So something like, if page # = 1 then { text: 'Text on page one only' } else { text: 'Text on other pages' }.

Thanks in advance for any advice on getting this to work.

**Comment by dorothythurston** [comment]
I don't think this is possible to do what you described as the content area does not have access to the page number like the header and footer do.

However you can order your document in such a way that you know that the text is on the first page by using page breaks:

`var dd = {
	content: [
		{ text: "text on my first page", pageBreak: "after"},
		{ text: "text on my second page" }
	]
}`

**Comment by liborm85** [comment]
Answered, No reaction.
