### ISSUE TITLE
How can I rotate an image 90 degrees?

### ISSUE THREAD

**Issue by rdhb17** [bpampuch/pdfmake#1166]
Hello everyone,

I need to rotate an image 90 degrees. This image is generated automatically vertically and I need to strain it horizontally in the report I need to generate.

Please, I'll thank you for helping me.

**Comment by liborm85** [comment]
Is not related to pdfmake. For editing images use google.

**Comment by hbaldwinRPT** [comment]
As a note, I needed to flip images and this can be done with negative fit or width height integers along with positive margins to reflect or rotate 180
