### ISSUE TITLE
Background of page

### ISSUE THREAD

**Issue by j8** [bpampuch/pdfmake#1167]
I need to create different background for each page? What is the way to do that?

**Comment by liborm85** [comment]
Example:
```js
var dd = {
    background: function(currentPage) {
        return 'simple background text on page ' + currentPage;
    },

    content: [
        {text: 'text', pageBreak: 'after'},
        {text: 'text', pageBreak: 'after'},
        {text: 'text', pageBreak: 'after'},
    ]
};
```

You can return different backgrounds for different pages in `background` function.

**Comment by j8** [comment]
Thank you, but I mean background color?

**Comment by liborm85** [comment]
Not supported now, here is feature request: https://github.com/bpampuch/pdfmake/issues/861

**Comment by j8** [comment]
OK, thanks!
