### ISSUE TITLE
custom fonts problem in angular 

### ISSUE THREAD

**Issue by sutineeangs** [bpampuch/pdfmake#1169]
Hi
i installed pdfmake by using npm install pdfmake --save ,
i create report service file for generate pdf and custom fonts in vfs_fonts.js file.

this is my vfs_fonts
`this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {
"THSarabunNew": ".......",
.....
}`

in my report service
`import * as pdfMake from 'pdfmake/build/pdfmake.js';
import * as pdfFonts from 'pdfmake/build/vfs_fonts.js';
pdfMake.vfs = pdfFonts.pdfMake.vfs;
pdfMake.fonts = {
  'Roboto': {
    normal: 'Roboto-Regular.ttf',
    bold: 'Roboto-Medium.ttf',
    italics: 'Roboto-Italic.ttf',
    bolditalics: 'Roboto-Italic.ttf'
  },
  'THSarabunNew': {
    normal: 'THSarabunNew.ttf'
  },
  'code128': {
    normal: 'code128.ttf'
  }
}`

in docDefinition code, i defined defaultStyle
```
var docDefinition = {
content:[...],
defaultStyle: {
  font: 'THSarabuNew'
}
}
```

when i generated pdf , i got error msg -> Error: Font 'THSarabuNew' in style 'normal' is not defined in the font section of the document definition.

**Comment by sutineeangs** [comment]
i try print console.log
![f1](https://user-images.githubusercontent.com/29113665/32361067-f5fedcc8-c08e-11e7-92b7-14bca4630c38.png)
i found pdfmake object it's not custom fonts

**Comment by sutineeangs** [comment]
my fonts config
```
pdfMake.fonts = {
  'Roboto': {
    normal: 'Roboto-Regular.ttf',
    bold: 'Roboto-Medium.ttf',
    italics: 'Roboto-Italic.ttf',
    bolditalics: 'Roboto-Italic.ttf'
  },
  'THSarabunNew': {
    normal: 'THSarabunNew.ttf'
  },
  'code128': {
    normal: 'code128.ttf'
  }
}
```

**Comment by cur3n4** [comment]
Did you find out what was the reason for the error?

**Comment by lory-lu** [comment]
I met the same question in my project. How did you fix it ?

**Comment by cmargulhano** [comment]
Hi guys, any update on this?
