### ISSUE TITLE
Issue with Arabic Characters

### ISSUE THREAD

**Issue by vipulj03** [bpampuch/pdfmake#1170]
I am able to create PDF in SharePoint Document Library, however its not showing Arabic characters.
I also tried in http://pdfmake.org/playground.html, its having the same issue with Arabic characters.

Any support or way for it ?
![arabic](https://user-images.githubusercontent.com/30520703/32369275-9c0a52cc-c0ae-11e7-801a-b20181f25aa9.png)

**Comment by dorothythurston** [comment]
You may have to import a specific font that supports Arabic characters

**Comment by liborm85** [comment]
Roboto font in playground not support Arabic characters, you have to use another font as it writes @dorothythurston. But now pdfmake not supported RTL, see issue: https://github.com/bpampuch/pdfmake/issues/315
