### ISSUE TITLE
How To Grouping In pdfmake?

### ISSUE THREAD

**Issue by PrabuGovindan** [bpampuch/pdfmake#1172]
How To Grouping In pdfmake?

**Comment by liborm85** [comment]
Please stop spamming!
What do you mean by the Grouping?

**Comment by PrabuGovindan** [comment]
sorry to spam. 
below is the sample code
**CODE:**
      { name: 'Bartek', age: 34 ,type:'aa'},
      { name: 'John', age: 27 ,type:'aa'},
      { name: 'Elizabeth', age: 30 ,type:'aa'},
      { name: 'Johny', age: 27 ,type:'aab'},
      { name: 'Eliza', age: 30 ,type:'aab'},
      { name: 'Johnes', age: 27 ,type:'aaf'},
      { name: 'Elizabetha', age: 30 ,type:'aai'},

How to load the list in group wise based on type ?

**Comment by liborm85** [comment]
Pdfmake not support aggregation functions. Grouping create by for loop in javascript and then add result to docDefinition pdfmake.
