### ISSUE TITLE
How To Grouping In pdfmake???????????????????????????

### ISSUE THREAD

**Issue by PrabuGovindan** [bpampuch/pdfmake#1173]
How To Grouping In pdfmake???????????????????????????

**Comment by liborm85** [comment]
Please stop spamming!
duplicate: https://github.com/bpampuch/pdfmake/issues/1172

**Comment by PrabuGovindan** [comment]
var body = [];
var itemsCount = 1;

for (let i = 0; i <= itemsCount; i += 1) {
                var row = [
                                {
                                //            image: base64Image,
                                text:"test",colSpan:2,
                                                width: 300
                                },
                                ''
                                
                ];
                body.push(row);
}
itemsCount = 20;
for (let i = 0; i <= itemsCount; i += 1) {
                var row1 = [
                                'Row ' + i,
                                {
                                //            image: base64Image,
                                text:"test",
                                                width: 300
                                },
                ];
                body.push(row1);
}

var dd2 = {
                                pageSize: 'LETTER',
                                pageOrientation: 'portrait',
                                pageMargins: [80, 55],
                                content: [{
                                                                width: 'auto',
                                                                height: 'auto',
                                                                alignment: 'center',
                                                                table: {
                                                                                //widths: widths,
                                                                                body: body
                                                                },
                                                                //layout: border
                                }]
};

pdfMake.createPdf(dd2).download();
