### ISSUE TITLE
I want to look like this, any sample code there?

### ISSUE THREAD

**Issue by PrabuGovindan** [bpampuch/pdfmake#1175]
I want to look like this, any sample code there?

![capture](https://user-images.githubusercontent.com/27006716/32597561-151e2320-c55d-11e7-9512-f7def2985b6f.JPG)

**Comment by liborm85** [comment]
See examples in [playground](http://pdfmake.org/playground.html) > "TABLES".

**Comment by PrabuGovindan** [comment]
var body = [];
var itemsCount = 1;

for (let i = 0; i <= itemsCount; i += 1) {
                var row = [
                                {
                                //            image: base64Image,
                                text:"test",colSpan:2,
                                                width: 300
                                },
                                ''
                                
                ];
                body.push(row);
}
itemsCount = 20;
for (let i = 0; i <= itemsCount; i += 1) {
                var row1 = [
                                'Row ' + i,
                                {
                                //            image: base64Image,
                                text:"test",
                                                width: 300
                                },
                ];
                body.push(row1);
}

var dd2 = {
                                pageSize: 'LETTER',
                                pageOrientation: 'portrait',
                                pageMargins: [80, 55],
                                content: [{
                                                                width: 'auto',
                                                                height: 'auto',
                                                                alignment: 'center',
                                                                table: {
                                                                                //widths: widths,
                                                                                body: body
                                                                },
                                                                //layout: border
                                }]
};

pdfMake.createPdf(dd2).download();
