### ISSUE TITLE
What is the correct way to cater for multiple languages/characters?

### ISSUE THREAD

**Issue by nelsonra** [bpampuch/pdfmake#1176]
Hi,

We are using pdfMake and we would like to be able to support multiple languages (characters) in the output.

It is not clear to me the correct way to get all the characters working for various languages. I've played around with generating my own fonts file (vfs_fonts.js). I tried using Arial and Noto Sans (https://www.google.com/get/noto/#sans-lgc) but I don't seem to get all the characters I was expecting to see.

If it is down to the font is there a better way to load up the font than having to manually generate the fonts used (https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side).

Any guidance is appreciated.

Thanks
Nelson

**Comment by liborm85** [comment]
You have to use a font that supports all the characters you need. Pdfmake does not allow "font merging" to one font file. If you need characters from different fonts use this manual https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side and special characters are described here https://github.com/bpampuch/pdfmake/wiki/Icons.
