### ISSUE TITLE
Using multiple tabs in results in a bogus character being displayed instead of the tabs.

### ISSUE THREAD

**Issue by nelsonra** [bpampuch/pdfmake#1177]
I noticed some weird character replacing the tabs in my text content.

![pdfmake_playground_example](https://user-images.githubusercontent.com/7580950/32610950-2ab3448c-c55c-11e7-8d71-bbbef87ba163.png)

You can reproduce the issue in the playground
```
var dd = {
	content: [
		'text\ttext\ttext\t',

		'text\ttext\u0900text\u0900',

		'text\u0900text\u0900text\u0900',
		]
}
```

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/aead2d5cc39c0eeb04ae0e8fb895c9ae95a36743.
