### ISSUE TITLE
How do you enable font feature settings?

### ISSUE THREAD

**Issue by meltingice** [bpampuch/pdfmake#1180]
We're using the [Portrait](https://commercialtype.com/catalog/portrait) font, which has a font feature setting that changes how numbers are shown (it moves them so they all live on the baseline). In CSS, we do `font-feature-settings: "lnum";` to enable this feature.

Is there any way to do so in pdfmake? From looking at FontKit, it seems like it _may_ be possible, but I'm having a hard time following how to actually enable it. Any help would be appreciated, thanks!

**Comment by liborm85** [comment]
Feature implemented by commit https://github.com/bpampuch/pdfmake/commit/1f6537b61ff1f0738bbfe79c896e6eed22f34231.

```js
{text: 'Hello World 1234567890', fontFeatures: ['smcp']},
{text: 'Hello World 1234567890', fontFeatures: ['c2sc']},
{text: 'Hello World 1234567890', fontFeatures: ['onum']},
{text: 'Hello World 1234567890', fontFeatures: ['onum', 'c2sc']}
```

A specific feature must be suppored by font.
