### ISSUE TITLE
pdfmake makes my bundle size huge

### ISSUE THREAD

**Issue by anoopbaabte** [bpampuch/pdfmake#1181]
I am using pdfmake in my angular 4 app and it really helps me in making nice pdf docs on the client side. But I am a little concerned when I look into the bundle-report after an aot build. It adds a considerable amount of weight to my chunk. Is there any way to reduce this, like importing only the needed parts/services/modules or so? Right now I am importing it as below

import { createPdf } from 'pdfmake/build/pdfmake';

![screenshot from 2017-10-29 23 27 15](https://user-images.githubusercontent.com/4527082/32686186-a05eb232-c6c6-11e7-9e7f-c4839afd3363.png)

**Comment by liborm85** [comment]
New version 0.1.34 a little reduces size of pdfmake.js and pdfmake.min.js files because lodash dependency was removed. Currently minified version has 950 kB.
Generating pdf files is too complex, so pdfmake is big, it can not be changed.

**Comment by kchiragowni** [comment]
@anoopbaabte would you mind sharing working sample for Angular 4 component?

**Comment by railsstudent** [comment]
Same situation here. Bundle size is huge in Angular 6. Size of node_modules is 2.96 mb and 2.13 mb of it comes from pdfmake

**Comment by klis87** [comment]
Try code splitting, with webpack for instance, so at least this big pdf bundle will be only loaded when needed

**Comment by nimatullah** [comment]
Guys, I have the same issue any idea?

**Comment by blikblum** [comment]
You can try https://www.npmjs.com/package/pdfmake-lite loading fonts and assets with https://www.npmjs.com/package/pdfmake-utils

It does not support IE, arabic fonts and woff2 fonts

**Comment by Tiberriver256** [comment]
I cut my bundle size in half by changing my import from:
```js
import * as pdfMake from 'pdfmake/build/pdfmake';
```

to
```js
import * as pdfMake from 'pdfmake/build/pdfmake.min';
```

**Comment by anthonyballugjr** [comment]
> I cut my bundle size in half by changing my import from:
> 
> ```js
> import * as pdfMake from 'pdfmake/build/pdfmake';
> ```
> 
> to
> 
> ```js
> import * as pdfMake from 'pdfmake/build/pdfmake.min';
> ```

This produce an error on production build

**Comment by shayc** [comment]
@anthonyballugjr thank you for this, I'm dynamically importing the module, the minified version is considerably smaller!

**Comment by Recursero** [comment]
> @anthonyballugjr thank you for this, I'm dynamically importing the module, the minified version is considerably smaller!

Hi Shayc. Can you show how import de minified version. I've dynamically importing the module but the buddle size is 3mb. Thanks in advance

**Comment by Recursero** [comment]
@shayc 
Hi Shayc. Can you show how import de minified version. I've dynamically importing the module but the buddle size is 3mb. Thanks in advance
