### ISSUE TITLE
Print without changing URL

### ISSUE THREAD

**Issue by niallmactaggart** [bpampuch/pdfmake#1184]
Is there any way to have print functionality on the same tab/window that will open the print preview, without going to the blob URL aswell?

Any help would be appreciated

Cheers,
Niall

**Comment by liborm85** [comment]
No, open without changing url is not supported/allowed by browsers.

**Comment by mgoku** [comment]
To @niallmactaggart and anyone in the future who probably had the same problem, I solve this by following this answer from Stackoverflow

https://stackoverflow.com/a/54674592/1995640
