### ISSUE TITLE
Generated Pdfs cause some readers use 100% of machine memory

### ISSUE THREAD

**Issue by Requium** [bpampuch/pdfmake#1186]
Some functions put on generated pdfs (for example the vector.pdf from examples folder) by PdfMake can cause some readers (PDFNitro) make a memory loop  to the machine(Reaching to 100% and make the machine crash), its something that i can do to not trigger this behaviour on this pdf Readers?, i think is something to do with quantity of rows in a table, or cuantity of vectors in a pdf but i cant find the solution because on chrome works fine, but on some windows  pdfreaders cause 100% Memory usage.

Thanks and sorry for my english.

**Comment by liborm85** [comment]
I tried some pdf readers and everything was fine. Pdf files are generated valid, so there is nothing to change. Try disable compression (see https://github.com/bpampuch/pdfmake#compression).

**Comment by Requium** [comment]
Totally right, Thank you!!, i disabled compression and the Nitro PDf works with the pdf,  it may be something in that reader, Thank you again!!!.
