### ISSUE TITLE
setting different cell border color on table

### ISSUE THREAD

**Issue by m3Lvs** [bpampuch/pdfmake#1189]
Hello, is it possible to set different border color per cell ? like { text: 'cell text', border:[true,true,true,true],borderColor:'red']}

i would like to create 
![image](https://user-images.githubusercontent.com/5618660/32869077-14ee2e92-cab0-11e7-931c-0da8dc1081e9.png)

currently I only have this
![image](https://user-images.githubusercontent.com/5618660/32869107-33c8ee1a-cab0-11e7-8c86-a1d9c172f823.png)

thank you for answering, by the way, your library is awesome , very fast ! 

have a good day ahead!

**Comment by liborm85** [comment]
Yes, it is possible. Example of table cell:
```js
{text: 'cell text', border: [true, true, true, true], fillColor: 'red'}
```

**Comment by liborm85** [comment]
Simple example:
```js
var dd = {
	content: [
		{
			table: {
				headerRows: 1,
				body: [
					[{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}, {text: 'Header 3', style: 'tableHeader'}],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
				]
			},
			layout: {
				hLineColor: function (i, node) {
					return (i === 0 || i === node.table.body.length) ? 'red' : 'blue';
				},
				vLineColor: function (i, node) {
					return (i === 0 || i === node.table.widths.length) ? 'red' : 'blue';
				},
			}
		},
	]
}
```

`hLineColor` and `vLineColor` edit as you need it

**Comment by m3Lvs** [comment]
nah, as you can see on the image I posted above "the small one" you see I already made a calendar using pdfmake.. I have used "layout" to change the color of the border right? now I am asking HOW DO **I SET SPECIFIC CELL** to other **COLORS** not the whole borders on the table..  

eg. on html/css perspective, 

```
<table>
<tr ><td class='red-border'>sample text</td><td>sample text</td><td>sample text</td></tr>
<tr><td>sample text</td><td>sample text</td><td>sample text</td></tr>
<tr><td>sample text</td><td>sample text</td><td>sample text</td></tr>
</table>
```


`<style>
td{border:1px solid #000;}
 .red-border{border:2px solid red !important;}
</style>`

is this possible?

![image](https://user-images.githubusercontent.com/5618660/32959823-d193db3e-cbfd-11e7-9f97-8be979e27c4e.png)


see all the borders are dark blue and only 2 of them has "light blue" border..

**Comment by liborm85** [comment]
Then **NO**, `borderColor` property is not supported for table cell.

**Comment by m3Lvs** [comment]
Ahh I see.. as I thought so. anyways Thanks for clarifying this..

**Comment by FelipeMicali** [comment]
I think it's better for you to render your html/css calendar in a canvas element and convert it to an image, than use it in pdfmake. Use html2canvas to achieve this: https://github.com/niklasvh/html2canvas

**Comment by JiaXueYan** [comment]
e  this is not borderColor？

**Comment by dorothythurston** [comment]
For anyone finding this later I believe it is supported now https://github.com/bpampuch/pdfmake/commit/9e25e22e5cd0b66d9179aca6269ddc3a0bbdb557

**Comment by thiagodevsilva** [comment]
It is work for me, thank you!
I have one question about border width, i need change but this form not working for me:

borderWidth: [3, 3, 3, 3] or borderWidth: 3.

Can you help me?



> As @dorothythurston pointed out it's [now possible](https://github.com/bpampuch/pdfmake/issues/1189#issuecomment-529971357).
> 
> **EXAMPLE:**
> 
> ```
> table: {
>   body: [
>     [{
>         text: 'Cell 1',
>         borderColor: ['#ff00ff', '#00ffff', '#ff00ff', '#00ffff'],
>       },
>       {
>         image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
>         borderColor: ['#ff00ff', '#00ffff', '#ff00ff', '#00ffff']
>       },
>       'Cell 3'
>     ]
>   ]
> }
> ```

**Comment by nicolacardi** [comment]
I have the same problem. borderColor can be set with an array, but border widths apparently cannot 
I tried borderWidth: [1,2,3,4] or borderWidths : [1,2,3,4] and it's not working.
hlineWidth and vLineWidth doesn't solve as this is only for "internal" vertical and horizontal lines and not for all of the four sides of a single cell
