### ISSUE TITLE
Weird issue when doing Array.push

### ISSUE THREAD

**Issue by rosshwalker** [bpampuch/pdfmake#1190]
Hi all,

Love PDFMake.  Great tool.  Got an issue and i cant make any sense of it.  I have some code I am using to build the rows in a table i am using with PDFMake.  When i comment out anything to do with PDFMake the resulting array is normal, however, when I uncomment the PDFMake code weird things happen to my array.  Does PDFMake override Array.push or something like that.  Here is a sample of my code;

 var quoteData = [];

                            dt.rows().every( function ( rowIdx, tableLoop, rowLoop ) {

                                var dataRow = this.data();
                                quoteData.push([ rowNo++, dataRow.type, dataRow.quantity, dataRow.brand, dataRow.cat_number, '', dataRow.sell_per_unit, dataRow.total_excl_gst ]);

                            });

with the PDFMake code commented, the resulting array is as expected. However, when i uncomment the code, I get errors in PDFMake and the output to console of the above array quoteData, looks like this;

![image](https://user-images.githubusercontent.com/2472023/32889141-ca02d946-cb1d-11e7-9f44-79c692da2dae.png)

And when i comment out the PDFMake stuff, the array looks like this;

![image](https://user-images.githubusercontent.com/2472023/32889205-0ab58358-cb1e-11e7-9e4a-0f50656ab7b9.png)

I am relatively new to JS and so figuring this out has been tough for me.  Any ideas please let me know .

Cheers,

Ross.

**Comment by FelipeMicali** [comment]
Hey Ross!

What you are facing is probably an async problem.

Take a look at that "i" icon in the end of your console logged array. That indicates that the array was updated after some change was made to that array after it was first console logged. So, in your first image, your array has some properties created by pdfmake, and when pdfmake is not triggered, your original array is logged.

Even if you log your array before pdfmake run, it will show the updated array anyway, before pdfmake modifies it in sequence, and your logged array is updated too.

Pdfmake modifies your array, so it can insert and position all it's elements in the correct page by creating references in each object. Javascript is an object oriented language, and should be built by that way to accomplish better results.

Why is this being a problem to you? Try to explain us what you are trying to achieve, and maybe we can guide you better!

Bye!

**Comment by rosshwalker** [comment]
Thats awesome! you are right. I fixed the array and then it worked. Ive
encountered this before..getting my head around these differences has been
difficult. But worth it. Starting to love JS. Thanks again.

**Comment by JoelNietoTec** [comment]
I've been having the exact same problem and I had spend almost 3 days trying to figure out what is going on. How can I prevent pdfmake to modify my array? When i try to pass it as table rows, this happen
![error](https://user-images.githubusercontent.com/6298693/36642136-bb938182-1a08-11e8-9ad0-468588dc4741.PNG)
