### ISSUE TITLE
Roll paper print 

### ISSUE THREAD

**Issue by inromualdo** [bpampuch/pdfmake#1194]
Hi.
How can i print with roll paper? ex: Point of sale printer
![31w3f-lldol _sy355_](https://user-images.githubusercontent.com/12269482/33065466-35276cc6-cea9-11e7-84f4-299695d16316.jpg)

Thank you.

**Comment by liborm85** [comment]
Yes, it's possible with auto height size feature:
```js
var dd = {
	pageSize: {
		width: 595.28,
		height: 'auto'
	},
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```
