### ISSUE TITLE
Table custom cell suddivision

### ISSUE THREAD

**Issue by pianetarosso** [bpampuch/pdfmake#1195]
Hi, I need to subdivide a cell in two or more columns, but this bahaviour should be applied only to some cells.

Currently I'm doing this using a table inside a table, but I cannot calculate margins properly, so the result is like this:

![schermata del 2017-11-21 13-31-08](https://user-images.githubusercontent.com/814397/33072669-bc526ce8-cec0-11e7-88b4-18b1e10b5116.png)

or like this, when a cell in the same row is bigger than another:

![schermata del 2017-11-21 13-35-26](https://user-images.githubusercontent.com/814397/33072794-20f532c0-cec1-11e7-9f6d-9e279f7e7ad5.png)

Is there a better method, or a way to get the final cell's size and apply this to the others?

Thank you

**Comment by pianetarosso** [comment]
The only working solution I found is to duplicate the number of columns and use colSpan accordingly if I have a particular element type or not.

This is the result:

![schermata del 2017-11-22 12-12-53](https://user-images.githubusercontent.com/814397/33124875-d10d3820-cf7e-11e7-92df-2854dd768d87.png)

**Comment by liborm85** [comment]
Use `rowSpan` and `colSpan` property.
I do not know what the table should look like, but this simple example should help:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					[
						{text: 'text'},
						{text: 'text'},
						{text: 'text'}
					],
					[
						{rowSpan: 3, text: 'text'},
						{text: 'text'},
						{text: 'text'}
					],
					[
						'',
						{colSpan: 2, text: 'text'},
						''
					],
					[
						'',
						{text: 'text'},
						{text: 'text'}
					]
				]
			}
		}
	]
}
```

And see http://pdfmake.org/playground.html on button TABLES.
