### ISSUE TITLE
Open PDF in IE 11 - permission denied

### ISSUE THREAD

**Issue by FlorianLeitgeb** [bpampuch/pdfmake#1197]
When I try the openPDF method in IE11, I get this exception:  `SCRIPT70: Permission denied`
And the code that fails is this line from pdfmake `win.location.href = pdfUrl;`.

To be more clear about the failing code:

```
	Document.prototype._openPdf = function (options, win) {
		if (!win) {
			win = this._openWindow();
		}
		try {
			this.getBlob(function (result) {
				var urlCreator = global.URL || global.webkitURL;
				var pdfUrl = urlCreator.createObjectURL(result);
				win.location.href = pdfUrl;
			}, options);
		} catch (e) {
			win.close();
			throw e;
		}
	};
```

But as I can remember, the PDF creation already worked. After the permission denied exception, I get a second exception: SCRIPT5043: `Accessing the 'caller' property of a function or arguments object is not allowed in strict mode. File: init.debug.js, Line: 1351, Column: 5`

**Comment by liborm85** [comment]
see supported browsers: https://github.com/bpampuch/pdfmake/issues/800

duplicate with: https://github.com/bpampuch/pdfmake/issues/230
