### ISSUE TITLE
pdf text not rendering with fonts object empty

### ISSUE THREAD

**Issue by dovalin** [bpampuch/pdfmake#120]
In previous versions this configuration worked fine:

var fonts = {}

In 0.1.13, with this configuration all texts in generated pdf are not rendered (but i can see horizontal lines in tables). When I  add the roboto fonts in server-side and configuring the fonts variable like examples all works fine.

¿Is this an issue/bug?

**Comment by liborm85** [comment]
The font that will be written in pdf is necessary.
