### ISSUE TITLE
Line at bottom of page when using tables

### ISSUE THREAD

**Issue by Patrick-Sachs** [bpampuch/pdfmake#1200]
Hello,

I am currently running into a few issues with tables. Before we start, here is a screenshot visualizing my problem: [https://image.prntscr.com/image/9xkP4MbqRh64pLWD8Txbog.png](https://image.prntscr.com/image/9xkP4MbqRh64pLWD8Txbog.png)

As you can see pdfmake seems to append a few pixels of the top line of a table whenever there is still space left. Is this a bug? If not, how can I prevent it from doing so? A possible solution might be so set the border color to transparent, but I'd like to avoid that if possible.

Furthermore I'd like to keep a table on one page. In my screenshot there is a table that is split between page two and three. I have already tried using `dontBreakRows: true` in the `table` property, to no avail(The table is not only split between the header and body rows, it can be between any given row within the table).

My table style:
```
styles: {
    biTable: {
        margin: [0, 5, 0, 15],
        width: 500
    },
    biTableHeader: {
        bold: true,
        fontSize: 13,
        color: "black"
    }
}
```

The table itself:
```
style: "biTable",
table: {
    widths: ["*"],
    body: body,
    dontBreakRows: true
},
layout: {
    fillColor: function (i, node) {
        if (i === 0) return "#4fc4c6";
        return ((i + 2) % 2 === 0) ? "#CCCCCC" : null;
    }
}
```

Thank you for your time.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/995
