### ISSUE TITLE
Header/Footer functions not called running playground locally

### ISSUE THREAD

**Issue by Zyzle** [bpampuch/pdfmake#1202]
As the title says, when running the dev-playground locally it seems that header/footer functions are never actually called and so they add no content to the page.

I have confirmed that the functions I'm using work trying them in the hosted playground and static text headers and footers work as expected in local dev-playground

Browsers tested: Chrome 62, Firefox 57

**Comment by pstoll** [comment]
I confirm this. It is that the function definitions are not getting passed into the server.js call createPdfBinary function. i.e. when inspecting req.body, the definition of either a footer or header function are simply not there. It seems related to the use eval client side.

**Comment by blikblum** [comment]
Got the same issue. https://github.com/bpampuch/pdfmake/pull/1350 should fix
