### ISSUE TITLE
Dynamic data from a <select>

### ISSUE THREAD

**Issue by etiks3** [bpampuch/pdfmake#1203]
HI there,
thanks for the great library. I'm trying to insert data from a <select> option value in a PDF generate dynamically. I don't find any help with this. Could you please give a hand on this?
 here's my code
`var e = document.getElementById('cares').value;
var data = [];
data.push(e);

var docDefinition = {
            content: [{
                    table: {
                        body: data
                    }
                }
`

I'm trying here to push my value in an array in order to inject it to PDF through data...
Well, i'm a bit lost with that.

Thanks for your help

**Comment by liborm85** [comment]
see http://pdfmake.org/playground.html on TABLES.

This is definition for table:
```js
		{
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		},
```

You do this, and that's a mistake:
```
		{
			table: {
				body: [
					'value'
				]
			}
		},
```

**Comment by etiks3** [comment]
Hi liborm85,

thanks for your answer. I'll try that
