### ISSUE TITLE
Is there a way to keep print empty row until the end of page?

### ISSUE THREAD

**Issue by psutinrerk** [bpampuch/pdfmake#1206]
Hello,

I tried to print empty row until the end of page as show in picture
is there any way I can do this using pdf make?  Thank you very much :)

![screenshot 2017-11-30 23 35 15](https://user-images.githubusercontent.com/4808913/33442626-2c7afd1e-d628-11e7-9618-4baabb99aa85.png)

**Comment by dorothythurston** [comment]
Hmmm well if you are not planning to change your page size you could set the row height such that it ends around the bottom of the page? i.e. `{
			style: 'tableExample',
			table: {
				heights: 800,
				body: [
					['row 1', 'column B'],
					['row 2', 'column B'],
					['row 3', 'column B']
				]
			}
		}`

**Comment by psutinrerk** [comment]
Thank you very much I will try that :)
