### ISSUE TITLE
CHnage background color of a table cell based on its data value

### ISSUE THREAD

**Issue by dheemandutta** [bpampuch/pdfmake#1207]
I want to modify table cell color values based on the data that it contains. Can that be done currently ?

**Comment by FelipeMicali** [comment]
Hello!

Pdfmake's content is a array that accepts any kind of data, including values returned by functions. So it's up to you and only you to build the necessary logic for your business.

**Comment by liborm85** [comment]
Simple example:
```
var dd = {
	content: [
		{
			
			table: {
				body: [
					[{text: 'Column 1', fillColor: 'yellow'}, 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		},
	]
}
```
