### ISSUE TITLE
Changelog

### ISSUE THREAD

**Issue by VitalyChe** [bpampuch/pdfmake#1209]
Thank you for the product!
I keep an eye on changes but it would be nice to have a changelog.
Thans!

**Comment by ThisWillDoIt** [comment]
There is one at: https://github.com/bpampuch/pdfmake/releases

But a separat changelog.md file would be nice in order to see changes on a local repo.

**Comment by VitalyChe** [comment]
@ThisWillDoIt Yeah, thanks! I am building locally so changelog.md is what I look for in general
