### ISSUE TITLE
svg support

### ISSUE THREAD

**Issue by jakubsadura** [bpampuch/pdfmake#121]
Is there a plan to add support for svg elements?
It would be nice to be able to generate pdfs also from svg

**Comment by MurWade** [comment]
for now you can convert svg to png quite easy client side / server side and use that in your pdf.

**Comment by natcohen** [comment]
Well with png, you lose the advantage of svg

**Comment by jthoenes** [comment]
well, with svg pdfmake needs to implement an svg parser - which is non trivial as you can imagine. So don't hope for it any time soon.

**Comment by natcohen** [comment]
Yes I know... But generating PDFs from svg opens so many applications! It would be the beginning of doc converters in pure JavaScript (docx to svg to pdf)

**Comment by jthoenes** [comment]
Happy to accept pull requests ;-)
Am 05.05.2015 18:35 schrieb "natcohen" <notifications@github.com>:

**Comment by natcohen** [comment]
Is it possible to draw objects (lines, text, etc...) based on coordinates of the page? with this I could start working on svg...

**Comment by jthoenes** [comment]
Look here for object drawing: https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js 

For text you can use the normal ``text`` - maybe in combination with this #222

**Comment by bpampuch** [comment]
I guess it's time to introduce extensibility, I'll add another Issue with a proposal for PluginAPI

**Comment by natcohen** [comment]
Plugins would definitely open to new features!
@jthoenes I get it for text and vectors but how can I define the size of a page in pixels?

**Comment by jthoenes** [comment]
@bpampuch I was thinking along the same lines recently.

@natcohen page sizes in pixels don'r make sense. The easiest way would be, to define a transformation, e.g. ``1px = 0.75 points``

**Comment by MurWade** [comment]
https://github.com/CBiX/svgToPdf.js/ something to look at . it is a plugin for jspdf

**Comment by natcohen** [comment]
Any chance we can implement this on pdfmake?

**Comment by nottinhill** [comment]
+1 for this feature, we would need it too.

**Comment by viklele** [comment]
+1 useful to get scalable lightweight symbols in PDF

**Comment by michaelzoidl** [comment]
+1

**Comment by skibulk** [comment]
+1

**Comment by speciose** [comment]
+1

**Comment by christomitov** [comment]
+1

**Comment by liborm85** [comment]
Relevant pdfkit issue https://github.com/devongovett/pdfkit/issues/270.

Will not be included in pdfkit, is in new libraray: https://github.com/devongovett/svgkit.

**Comment by marer** [comment]
+1

**Comment by afbruno** [comment]
+1

**Comment by AlexanderTserkovniy** [comment]
Any updates?

**Comment by josepfdc** [comment]
any update ? ...it would be important to import images in format svg

**Comment by zxlin** [comment]
https://github.com/alafr/SVG-to-PDFKit

This seems like a working solution specifically compatible with PDFKit and the API seems pretty simple.

**Comment by NiPfi** [comment]
> 
> 
> https://github.com/alafr/SVG-to-PDFKit
> 
> This seems like a working solution specifically compatible with PDFKit and the API is pretty straight forward.

How would I use this client-side? All code examples seem to rely on Node.js using the printer which requires 'fs'.

**Comment by JustynaKK** [comment]
> @zxlin How do you integrate https://github.com/alafr/SVG-to-PDFKit into the document definition of pdfmake?

+1

**Comment by saleswon** [comment]
> > @zxlin How do you integrate https://github.com/alafr/SVG-to-PDFKit into the document definition of pdfmake?
> 
> +1

+1

**Comment by Quixomatic** [comment]
> > @zxlin How do you integrate https://github.com/alafr/SVG-to-PDFKit into the document definition of pdfmake?
> 
> +1

+1

@liborm85 any updates on this?

**Comment by cvhooser** [comment]
+1

**Comment by mpsbhat** [comment]
+1

**Comment by ackvf** [comment]
`canvg` is a decent SVG parser.

**Comment by zxlin** [comment]
I'm not sure how to integrate `SVGtoPDFKit` into this particular package, but I use it directly in `pdfkit` without issue. 

@liborm85 @bpampuch If there's a way to expose the pdfkit doc object to the user, it could be hacked for now at least until a good solution is integrated into the lib.

**Comment by cyrixmorten** [comment]
I have created a fork that adds svg support in the document definition.

It works similar to images except you cannot use the images library or file paths.

Example usage:

```
npm install https://github.com/cyrixmorten/pdfmake.git#0.1 --save
```

```
content: [
    {
        svg: '<svg viewBox="0 0 500 500"><circle cx="250" cy="250" r="100" stroke="black" stroke-width="3" fill="red" /></svg>',
        width: 100
    },
    {
        svg: '<svg viewBox="0 0 500 500"><circle cx="250" cy="250" r="100" stroke="black" stroke-width="3" fill="red" /></svg>',
        fit: [500, 250]
    }
]
```

It uses `SVGtoPDFKit` under the hood and it should be possible to pass options to it in the document definition (untested though as I did not need it)

```
    {
        svg: '<svg>...</svg>',
        options: { ... SVGtoPDFKit options ... }
    }
```

See https://github.com/alafr/SVG-to-PDFKit#parameters for available options

**Comment by manu-st** [comment]
@cyrixmorten Any reason you did not submit a PR for it?

**Comment by cyrixmorten** [comment]
@manu-st thought it would require a bit more work before it could be accepted but that discussion might as well happen in a PR. Have created a PR here: https://github.com/bpampuch/pdfmake/pull/1682

**Comment by Dylanlan** [comment]
Thanks so much @cyrixmorten, this helps me a ton! I was struggling to use `SVGtoPDFKit` with pdfmake, since it seemed like we needed to specify the pdf page number and x, y coordinates to properly place the image in between pdfmake content, which was quickly becoming a pain. Your PR seems to be exactly what I needed

**Comment by bgold0** [comment]
Any idea on how to get this to work? Added the PR but still getting 
> Unrecognized document structure: {"svg":....

**Comment by cyrixmorten** [comment]
Hi Bryan. Am not sure that there has been a new release to npm that the
includes svg nodes yet.

tir. 16. jul. 2019 02.12 skrev Bryan <notifications@github.com>:

**Comment by thompsondave** [comment]
Hi @cyrixmorten, any idea when this will be released?

**Comment by cyrixmorten** [comment]
@thompsondave I do not know, is up to the owner of this project

**Comment by liborm85** [comment]
Experimental SVG support added in version 0.1.58+ via [SVG-to-PDFKit library](https://github.com/alafr/SVG-to-PDFKit).
