### ISSUE TITLE
save pdf document back to server

### ISSUE THREAD

**Issue by balajikarthiq** [bpampuch/pdfmake#1213]
This is not an issue, i don't know where have to ask the requirement. i searched in internet, but didn't find the solution for this. Is this possible to save generated document back to server in 'pdfmake'?

**Comment by Wabbala** [comment]
Well, you have the base64 encoded pdf probably at some point after
rendering right? Can't you make a upload request to the server? Who will
handle this upload request and save it?

**Comment by balajikarthiq** [comment]
will check it on that.
