### ISSUE TITLE
need to display emoji

### ISSUE THREAD

**Issue by rameezfsitix** [bpampuch/pdfmake#1214]
Hi, i want to add emoji in pdf how i can do this

**Comment by Wabbala** [comment]
Nope not possible due to PDFkit limitations. [link](https://github.com/devongovett/pdfkit/issues/575)

**Comment by rameezfsitix** [comment]
when i am trying to use A ( \u0041 ) uni code in pdfmake it convert into A char . meanwhile when i am trying to use "\uD83D\uDE00" it cant display emoji.

**Comment by Wabbala** [comment]
Your font must support these unicode characters. [link](https://superuser.com/questions/1094188/how-do-i-display-the-latest-unicode-characters-esp-emoji-in-windows-browsers)

**Comment by rameezfsitix** [comment]
include OpenSansEmoji and seguiemj font but not yet victory

**Comment by liborm85** [comment]
Tested with [OpenSansEmoji font](https://github.com/MorbZ/OpenSansEmoji/blob/master/OpenSansEmoji.ttf) and emoji works correctly.

Doc definition example:
```js
var dd = {
	content: [	
		'\uD83D\uDE00\uD83D\uDE08',
		'\uD83C\uDF00\uD83C\uDF50'
	]
};
```

and output:
![issue-1214](https://user-images.githubusercontent.com/1298652/33804259-5645e552-dda1-11e7-886f-a129cb7a8097.png)

**Comment by rameezfsitix** [comment]
@liborm85 thanks for your response. if you have any example code please share it. Thanks in advance

**Comment by liborm85** [comment]
Simple code example is above.

Instructions:
Download [OpenSansEmoji font](https://github.com/MorbZ/OpenSansEmoji/blob/master/OpenSansEmoji.ttf), create own vfs file with that font - using 
[wiki instructions](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side)  for create a configure font.
And then you can use something like this (same as above example):
```js
var dd = {
	content: [	
		{text: '\uD83D\uDE00\uD83D\uDE08', font: 'OpenSansEmoji'},
		{text: '\uD83C\uDF00\uD83C\uDF50', font: 'OpenSansEmoji'}
	]
};
```

**Comment by kievsash** [comment]
It would be great to use specific font for text and OpenSansEmoji for inline emojies only
