### ISSUE TITLE
Support Buffer for images

### ISSUE THREAD

**Issue by coyotte508** [bpampuch/pdfmake#1216]
Please allow providing images directly as buffers.

Pdfkit supports using buffer directly for images, instead of filepaths.

Pdfmake doesn't support buffers, and even at some point converts buffers in the document to:

```js
{
    type: "Buffer",
    data: [...]
}
```

The best way to implement image support would be to prevent buffers from being converted to that, and then there's no roadblocks.

The images in the image dictionary work fine.

**Comment by liborm85** [comment]
What buffers do you mean?

For example this works in nodejs:
```js
var docDefinition = {
	content: [
		{
			image: new Buffer('/9j/4RC...//Z', 'base64')
		}
	]
};
```

What is to be added?

**Comment by coyotte508** [comment]
After more testing, I realize that the issue only occurs in the footer.

This sample code reproduces it (place inside the "examples" folder"):

```js
var fonts = {
	Roboto: {
		normal: 'fonts/Roboto-Regular.ttf',
		bold: 'fonts/Roboto-Medium.ttf',
		italics: 'fonts/Roboto-Italic.ttf',
		bolditalics: 'fonts/Roboto-MediumItalic.ttf'
	}
};

var PdfPrinter = require('../src/printer');
var printer = new PdfPrinter(fonts);
var fs = require('fs');

var docDefinition = {
	content: [
		{
			text: "Does image buffer footer load?"
		}
	],
	footer: {
		image: fs.readFileSync("fonts/sampleImage.jpg"),
		// image: "fonts/sampleImage.jpg",
		height: 100,
		width: 100,
	},
	pageMargins: [50,50,50,150],
};



var now = new Date();
var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('pdfs/images.pdf'));
pdfDoc.on("error", err => console.error(err));
pdfDoc.end();
console.log(new Date() - now);
```

I experienced other problems with the footer like the border color for tablecells not being taken into account.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/8d5ce80bca6490ee37e7db25ff167b5feb3748aa.
