### ISSUE TITLE
Error when image has a width of '*'

### ISSUE THREAD

**Issue by coyotte508** [bpampuch/pdfmake#1217]
```js
doc = {
  content: {
    columns: [{
      image: "...",
      width: "*"
    }, "hello"]
  }
}
```

This causes an error with dimensions of `NaN`. But the star is valid here, it describes the width behavior of the column. I don't know what would be the preferred way to handle this, I think maybe pdfmake should act as if the image didn't get a width argument.

**Comment by liborm85** [comment]
This is right definition:

```js
var dd = {
	content: [
		{
			columns: [
				{
				    stack: [
				        {
				            image: '...',
				        }
				    ],
				    width: '*'
				},
				{
					text: 'hello'
				}
			]
		}
	]
}
```
