### ISSUE TITLE
IE8 doesn't like "class" property name

### ISSUE THREAD

**Issue by Worthy7** [bpampuch/pdfmake#1219]
//#########################
	// Class Definition Table #
	//#########################
	var ClassRangeRecord = new r.Struct({
	  start: r.uint16,
	  end: r.uint16,
	  class: r.uint16
	});

This code doesn't work in IE8 because you called the property `class`.
Please rename it and all instances for the next version :)

**Comment by liborm85** [comment]
IE8 is not supported.

These browsers are supported: see https://github.com/bpampuch/pdfmake#supported-browsers

**Comment by Worthy7** [comment]
Hmm, since Datatables does support IE8, I was expecting this to work. But thanks anyway for responding.
