### ISSUE TITLE
it doesn't work when i use multiple fonts in one pdf

### ISSUE THREAD

**Issue by outNapGnaw** [bpampuch/pdfmake#1220]
this is my fonts setting
<pre>
window.pdfMake.fonts = {
                'UserNameFont':{
                    normal: 'userNameFont.ttf',
                    bold: 'userNameFont.ttf',
                    italics: 'userNameFont.ttf',
                    bolditalics: 'userNameFont.ttf'
                },
                'Roboto': {
                    normal: '微软雅黑.ttf',
                    bold: '微软雅黑.ttf',
                    italics: '微软雅黑.ttf',
                    bolditalics: '微软雅黑.ttf'
                },
            };
</pre>
when i use like this 
<pre>
    const test  = {
        stack : [
            { 
               text : 'this is user name font text',
               font:'UserNameFont',
               italic : true
            }, { 
            text : 'this is roboto text',
            font:'Roboto',
            bold : true
         } , 
       ]
     }
</pre>
all of the  pdf will be created with UserNameFont font
but, when i use like this 
<pre>
    const test  = {
        stack : [ 
        { 
            text : 'this is roboto text',
            font:'Roboto',
            bold : true
         } ,  { 
               text : 'this is user name font text',
               font:'UserNameFont',
               italic : true
            },
       ]
     }
</pre>
all of the  pdf will be created with Roboto font

it just like the pdf will be created with the font witch is the first used in my content

so,how should i do to make it work with two kinds of font?

**Comment by liborm85** [comment]
Can not be simulated, everything works correctly.

See test scripts:
[pdfmake-issue-1220.zip](https://github.com/bpampuch/pdfmake/files/1545421/pdfmake-issue-1220.zip)
