### ISSUE TITLE
Multiple images support

### ISSUE THREAD

**Issue by pinal-r** [bpampuch/pdfmake#1221]
I want to include multiple images in one pdf , how it can be done ?

**Comment by liborm85** [comment]
Simply. For example:

```js
var dd = {
	content: [
		{
			image: 'image1.png',
		},
		{
			image: 'image2.png',
		},
		{
			image: 'image3.png',
		}		
	]
}
```

**Comment by cfoxy17** [comment]
Or even better:

say you had the following canvas IDs in your .html file:
`<canvas id="myCanvasOne" width="650" height="280"></canvas>
<canvas id="myCanvasTwo" width="650" height="280"></canvas>
<canvas id="myCanvasThree" width="650" height="280"></canvas>`

You can create a list of these in your .ts file:
`
let elementIdsOfCanvases = ['myCanvasOne','myCanvasTwo','myCanvasThree'];
`
Then call a function that takes the elementIds as an argument:
`
exportMultipleImagesToPDF(elementIdsOfCanvases: string[]) {
    let myImageObjects: any[] = [];

    for(let i = 0; i < elementIdsOfCanvases.length; i++) {
        let canvas = document.getElementById(elementIdsOfCanvases[i]) as HTMLCanvasElement;
        let dataURL = canvas.toDataURL('image/jpg');
        let myElement = document.createElement('a');
        myElement.href = dataURL;
        myImageObjects.push({image:myElement.href,height: 175,width: 325});
    }

    let docDefinition = {
        content: myImageObjects
    };
    
    var generatedDoc = PDFmake.createPdf(docDefinition);
    generatedDoc.getBuffer((buffer)=>{
        let blob = new Blob([buffer]);
        FileSaver.saveAs(blob,'myFilename.pdf')
    })
}   
`
