### ISSUE TITLE
Add content after pages creation

### ISSUE THREAD

**Issue by FelipeMicali** [bpampuch/pdfmake#1224]
I need to insert some absolute positioned content in specific pages after pages are created. Those contents won't be bigger than the available space on each page.

I've tries doing it with the "header" function but the header content is limited to page's top margin.

Is there any way to achieve this?

Thanks in advance!

**Comment by FelipeMicali** [comment]
Could someone give me some tip to achieve this, please??

I need to implement this as soon as possible.

Thanks!

**Comment by liborm85** [comment]
When space is available on page, it would be possible to use [background layer function](https://github.com/bpampuch/pdfmake#background-layer).

**Comment by FelipeMicali** [comment]
@liborm85 you are a true life saver!

Thanks again!
