### ISSUE TITLE
Push to next page

### ISSUE THREAD

**Issue by ajbrown444** [bpampuch/pdfmake#1227]
It would be great to have a feature that pushes a "group" of content to a new page if the entire group doesn't fit on the current page. For example, if I have a little paragraph of text and a table of data that goes with it, I'd like it to all stay together on the same page.

**Comment by var-bin** [comment]
Hi there,

I suppose you should manage this case by yourself. There a lot of obstacles, e.g. what do you mean **"a little paragraph"**? How many words should it contain before to push it to the next page?

Best regards,
Vitalii

**Comment by liborm85** [comment]
No reaction.
