### ISSUE TITLE
Making a large table with header rows and columns

### ISSUE THREAD

**Issue by EricG-Personal** [bpampuch/pdfmake#1229]
I am using [react-table](http://react-table.js.org) to generate a rather large table that I need to be able to print nicely. What does "nicely" mean?  I do not want the contents of a cell to be clipped, split between pages, or auto-scaled to be smaller. Each page should have the appropriate header rows and each page should have the appropriate header column (the ID column).

I have a sample project:

https://github.com/EricG-Personal/table_print

To see the print result I would like to see, you can check out:

https://github.com/EricG-Personal/table_print/blob/master/table.png
(It isn't pixel perfect, but representative of what I am hoping to achieve.)

My best option appears to be to take my data and create my own PDF which, as closely as is reasonable, matches what is rendered by a browser.

What I am not sure is if your declarative syntax can handle how I need my table to be printed.

What may make it difficult is the need to repeat a column on every page.

So, this issue may ultimately be a feature request or enhancement.

**Comment by dorothythurston** [comment]
Pdfmake lets you set it so the header row does repeat on every page. Also you can set column widths and heights, or you can let it auto calculate how large the height should be based on the contents. Please play around with the http://pdfmake.org/playground.html (select the table tab) and see examples. I think you should be able to achieve what you desire with this library?

**Comment by EricG-Personal** [comment]
Yes, I do see how to make a header row repeat on every page.

However, I do not see a way to have a header column repeat on every page, but perhaps I have missed something.

**Comment by dorothythurston** [comment]
Ah I see. I don't think there is a way to make a "header column" repeat on each page. You would have to write some sort of looping logic across your data.

**Comment by EricG-Personal** [comment]
Indeed. Hence the feature request. :-)

**Comment by liborm85** [comment]
Currently not possible. It works just like MS Word - the wide tables there are out of the page too.

Feature request for implementation is here: https://github.com/bpampuch/pdfmake/issues/441
