### ISSUE TITLE
Create Dinamically tables does not  allow's more than four columns?

### ISSUE THREAD

**Issue by cristianchaparroa** [bpampuch/pdfmake#123]
Hi, I'm try to build a tables dynamically, but not works,  My first attempt was the following

```javascript
   var body = [];
   for (key in peajes) 
   {
	 if (peajes.hasOwnProperty(key))
	{
		var peaje = peajes[key];
		var fila = new Array();
		fila.push( peaje.peaje.toString() );
		fila.push( peaje.ruta.toString()  );
		fila.push( peaje.fechaCruce.toString() );
		fila.push( peaje.hora.toString()  );
		//fila.push( peaje.valor.toString() );
		body.push(fila);
        }
   }
   var docDefinition = {
		content: [{
		  table: {
			 headerRows: 1,
			 widths: [ '*', 'auto', 100, '*' ],
			body: body
		   }
	}
    ]};//end docDefinition
    pdfMake.createPdf(docDefinition).open();
```
But If I add more than four columns, I can't see the pdf generated , 

what am I doing wrong?

**Comment by IrfanMurtaza93** [comment]
Nope, there is no issue with '100', but the number of items in width array. That's where you define the width of each of your column. if you don't define the width, it would not work any way. you must have to specify the width of each column.
