### ISSUE TITLE
Reverse table columns

### ISSUE THREAD

**Issue by jafar-rezaei** [bpampuch/pdfmake#1230]
Is it a fast and reliable way to reserve `table` columns OR `columns` grids ?
or we should parse recursive json to reverse it.

**Comment by liborm85** [comment]
What do you mean by "reverse table" ?

You can specify order of rows and columns of table when you create `docDefinition`.

**Comment by jafar-rezaei** [comment]
@liborm85 thanks for your response .
In persian and all(RTL languages) we need to add columns from right to left.
if we reverse every table columns we can have RTL tables .

**Comment by liborm85** [comment]
RTL is not supported now.
Feature request issue: https://github.com/bpampuch/pdfmake/issues/184
