### ISSUE TITLE
open pdfmake blob in pdf.js

### ISSUE THREAD

**Issue by jafar-rezaei** [bpampuch/pdfmake#1231]
I want to display my generated pdf in `pdf.js` page , which I added to my project .
I use blob url of generated pdf to display it . but it has some troubles with `IE` .

can I have a better way to do that ?
I mean using some thing like this Data : 
```

# option 1
var data;
pdfMake.createPdf(docDefinition).getDataUrl(function(dataURL) {
    data = dataURL;
});

# option 2 
var data;
pdfMake.createPdf(docDefinition).getBase64(function(encodedString) {
    data = encodedString;
});

# option 3
var data;
pdfMake.createPdf(docDefinition).getBuffer(function(buffer) {
    // turn buffer into blob
    data = buffer;
});

```

**Comment by liborm85** [comment]
You can use any of methods:
- [`getDataUrl`](https://github.com/bpampuch/pdfmake#put-the-pdf-into-your-own-page-as-url-data)
- [`getBase64`](https://github.com/bpampuch/pdfmake#get-the-pdf-as-base64-data)
- [`getBuffer`](https://github.com/bpampuch/pdfmake#get-the-pdf-as-buffer)
- [`getBlob`](https://github.com/bpampuch/pdfmake#get-the-pdf-as-blob)

Depends on type that requires pdf.js.

**Comment by jafar-rezaei** [comment]
we have `getDocument` function in pdf.js which has `src` input : 
```
function getDocument(src) {
  var task = new PDFDocumentLoadingTask();
  var source;
  if (typeof src === 'string') {
    source = { url: src };
  } else if ((0, _util.isArrayBuffer)(src)) {
    source = { data: src };
  } else if (src instanceof PDFDataRangeTransport) {
    source = { range: src };
  } else {
    if ((typeof src === 'undefined' ? 'undefined' : _typeof(src)) !== 'object') {
      throw new Error('Invalid parameter in getDocument, ' + 'need either Uint8Array, string or a parameter object');
    }
    if (!src.url && !src.data && !src.range) {
      throw new Error('Invalid parameter object: need either .data, .range or .url');
    }
    source = src;
  }
...
}
```

I think we can use `getBuffer` method with `getDocument` and it will be do the job

**Comment by liborm85** [comment]
I don't know. Is not related to pdfmake. Look at pdf.js documentation or ask pdf.js support.
