### ISSUE TITLE
Page Count variable only usable in header/footer?

### ISSUE THREAD

**Issue by erisontavares** [bpampuch/pdfmake#1235]
Hi there, 

I'm trying to create a report with pdfMake, but on my last page, I need to add a paragraph for signature with the number of pages of the report. I tried creating a function like the one from footer, using as parameter the pageCount variable, but apparently, this variable is only accessible in the footer of header elements. Is there any way to accomplish this, to use the pageCount in any other element of the document?

**Comment by liborm85** [comment]
No, this is not possible.
