### ISSUE TITLE
global.open is not a function/error failed to load pdf document

### ISSUE THREAD

**Issue by JBoshart** [bpampuch/pdfmake#1242]
Hello, 

I am at my wit's end, and I am hoping someone can assist me. I'm building an express.js app. In the controller where I intend to call pdfmake I have required the following: 

`var pdfMake = require('pdfmake/build/pdfmake');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;`

I call pdfmake as follows:

`var docDefinition = {content: 'This is an sample PDF printed with pdfMake'};
      pdfMake.createPdf(docDefinition).open();`

And receive the folloing error/stacktrace in the browser: 
global.open is not a function
TypeError: global.open is not a function
    at Document._openWindow (/<path to my project>/node_modules/pdfmake/build/pdfmake.js:153:20)
    at Document._openPdf (/<path to my project>/node_modules/pdfmake/build/pdfmake.js:163:15)
    at Document.open (/<path to my project>/node_modules/pdfmake/build/pdfmake.js:182:8)
    at printInvoice (/<path to my project>/controllers/invoices.js:64:52)

I've spent time reading the [readme](https://github.com/bpampuch/pdfmake), as well as issues [1091](https://github.com/bpampuch/pdfmake/issues/1091), [522](https://github.com/bpampuch/pdfmake/issues/522), and [150](https://github.com/bpampuch/pdfmake/issues/150). 

I have tried to use the playground server.js code as a template in my server.js file doing the following:
```
var pdfMakePrinter = require('pdfmake/src/printer');

function createPdfBinary(pdfDoc, callback) {
  var fontDescriptors = {
    Roboto: {
      normal: path.join(__dirname, 'public/fonts/Roboto-Regular.ttf'),
      bold: path.join(__dirname, 'public/fonts/Roboto-Medium.ttf'),
      italics: path.join(__dirname, 'public/fonts/Roboto-Italic.ttf'),
      bolditalics: path.join(__dirname, 'public/fonts/Roboto-MediumItalic.ttf'),
    }
  };

  var printer = new pdfMakePrinter(fontDescriptors);
  var doc = printer.createPdfKitDocument(pdfDoc);

  var chunks = [];
  var result;
  
  doc.on('data', function (chunk) {
     chunks.push(chunk);
   });
  doc.on('end', function () {
     result = Buffer.concat(chunks);
     callback('data:application/pdf;base64,' + result.toString('base64'));
   });
  doc.end();
}

 app.get('<my url>', function (req, res) {
   var docDefinition = {content: 'This is an sample PDF printed with pdfMake'};

   createPdfBinary(docDefinition, function(binary) {
     res.contentType('application/pdf');
     res.send(binary);
   }, function(error) {
     res.send('ERROR:' + error);
   });
 });
```

This results in the grey pdf screen to appear with an error pop-up: "error failed to load pdf document"

If anyone has any insight I would sincerely appreciate it.

**Comment by liborm85** [comment]
Error `global.open is not a function` probably is fixed in this: [pdfmake.zip](https://github.com/bpampuch/pdfmake/files/1609632/pdfmake.zip).
Please try it.

**Comment by liborm85** [comment]
No reaction.

**Comment by gloriousglory** [comment]
@JBoshart, did you ever resolve this? I'm facing the same problem.

**Comment by liborm85** [comment]
@gloriousglory Please try edited pdfmake.js from https://github.com/bpampuch/pdfmake/issues/1242#issuecomment-355811174. Thanks.

**Comment by gloriousglory** [comment]
@liborm85 Thank you. Solved.

**Comment by liborm85** [comment]
Fixed in master by commit https://github.com/bpampuch/pdfmake/commit/816e9f49d67c2272436ecddf875ff2ff6ea820be.

**Comment by JBoshart** [comment]
@gloriousglory - Thanks for bringing my attention back to this. I moved on in my project because we needed to launch. Now I'm back to this, and would really like to use PDF make. 

@liborm85 - Thanks for the ping to the other issue, and I apologize for not responding to your previous comments. I appreciate your work.

**Comment by jinuem** [comment]
any update on this issue?
