### ISSUE TITLE
view pdf not working in UC browser(Android)

### ISSUE THREAD

**Issue by chandanch** [bpampuch/pdfmake#1244]
I have created a simple pdf document 

````javascript

let pdfContent = {content: 'Cars of 2017'};

function viewFile() {
   pdfMake.createPdf(pdfContent).open();
}

````

view.html

````html
....
<button onclick="viewFile()">
````

This works in Chrome(android), Safari(iOS) but on UC browser it shows the following error:
`error(404): File not found`

**Comment by liborm85** [comment]
UC browser has not been tested. See supported browser https://github.com/bpampuch/pdfmake/issues/800.
