### ISSUE TITLE
Second Page  has no text 

### ISSUE THREAD

**Issue by sandercage** [bpampuch/pdfmake#1249]
##  Second page has no text after I push 'copyData' into 'tableData'

> detail code in 'test1.txt'

`

    var tableData = []
    var copyData = [{content_item_obj}]
    tableData.push(...copyData);
    tableData.push(...copyData);
    var docDefinition = {
	    content: tableData,
    }
    var showBox = document.querySelector('.pdf_show')
    var pdfDocGenerator = pdfMake.createPdf(docDefinition);
    pdfDocGenerator.getDataUrl(function (dataUrl) {
	    showBox.src = dataUrl;
    })
`

Please help.Sir
![wechatimg23](https://user-images.githubusercontent.com/30860970/34868398-9dd52d38-f7be-11e7-8097-1374b3c3add3.png)

[test1.txt](https://github.com/bpampuch/pdfmake/files/1625546/test1.txt)

**Comment by liborm85** [comment]
Multiple references to same object are problematic, see isue: https://github.com/bpampuch/pdfmake/issues/465

Rewrite `copyData` as function, see example:
```js
var tableData = []

function getCopyData() {
    return [{
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		}];
}


tableData.push(...getCopyData());
tableData.push(...getCopyData());

var dd = {
    content: tableData,
}
```

**Comment by sandercage** [comment]
Solve it! thank you very much

send from yangchuan by spark
