### ISSUE TITLE
Number of papers is not equal to num of Pages

### ISSUE THREAD

**Issue by sandercage** [bpampuch/pdfmake#1250]
When I previewed the print, I found inconsistencies between the number of papers and the number of pages, which was the same after printing
Please help.
![1515757580581](https://user-images.githubusercontent.com/30860970/34873912-d5cb19c4-f7d1-11e7-8030-eac06b919c7d.jpg)

**Comment by liborm85** [comment]
Number of papers and number of pages are different variables.
1 paper can have 2 pages or only 1 page.

Is not related to pdfmake.
