### ISSUE TITLE
[Questions] Maximizing the image in PDF format and storing as an object

### ISSUE THREAD

**Issue by luckyvs1** [bpampuch/pdfmake#1256]
I have an image which has been converted to pdf, but I want to maximize the image on the page and have been unsuccessful. This will be a dynamic process, so I won't be able to adjust the properties manually of pageSize or pageOrientation, but have access to the image's width and height. 

What would be the best approach to go about this using the settings available? 

Also, is it possible to store the pdf converted image as an object instead of downloading, printing, or opening?

**Comment by liborm85** [comment]
For detection image size you can use some other library and then only set required `width` and `height` of image to pdfmake.

Attaching objects is not supported.

**Comment by luckyvs1** [comment]
I tried the method mentioned above by setting width and height only; however, the image was not maximized.

Using the following code, where my variables are checked and passed correctly for `width` and `height`.

          // PDFMake documentation at:
          // https://github.com/bpampuch/pdfmake
          let docDefinition = {
            content: [
              {
                image: imageString,
                width: width,
                height: height,
              }
            ]
          };
          pdfMake.createPdf(docDefinition).download(modifiedName);

The image converted should be in landscape format; however, the image appears as a portrait with a portion of the image truncated and not maximizing the page. Is there anything else I am missing in order to maximize the image on the page with proper layout and paper size in a dynamic manner?


[a-print-certificate-sample-2016 (1).pdf](https://github.com/bpampuch/pdfmake/files/1650047/a-print-certificate-sample-2016.1.pdf)

**Comment by liborm85** [comment]
Change page orientation to landscape and set page margins to 0, see example:
```js
var dd = {
	pageOrientation: 'landscape',
	pageMargins: [0, 0, 0, 0],
	content: [
		'insert image here'
	]
}
```

Then image will be visible correctly on page.

**Comment by luckyvs1** [comment]
If I include the code above, then the following happens I get two landscape pages that are both white.

`// PDFMake documentation at:
      // https://github.com/bpampuch/pdfmake
      let docDefinition = {
        pageOrientation: 'landscape',
	pageMargins: [0, 0, 0, 0],
        content: [
          {
            image: imageString,
            width: width,
            height: height,
          }
        ]
      };
      pdfMake.createPdf(docDefinition).download(modifiedName);`

**Comment by liborm85** [comment]
Hmmm, tested on [playground](http://pdfmake.org/playground.html) and all works correctly:

```js
var dd = {
	pageOrientation: 'landscape',
	pageMargins: [0, 0, 0, 0],
	content: [
		{
			image: 'sampleImage.jpg',
			width: 841.89,
			height: 595.28
		}
	]
}
```

**Comment by luckyvs1** [comment]
That works perfectly! The width and height, are not what I expected what are the units of the width and height? I was passing in `width`: 790 and `height`: 608.
