### ISSUE TITLE
Contents of the book (TOC)

### ISSUE THREAD

**Issue by greensleeves** [bpampuch/pdfmake#126]
Good day.Tell me please, how to make a table of contents?

**Comment by jthoenes** [comment]
This is not supported yet. Noted as a feature request.

**Comment by andrea-vega** [comment]
+1

**Comment by plaufer** [comment]
+1

**Comment by Diferno** [comment]
+10 :)

**Comment by liborm85** [comment]
I started implementing a TOC.

For details, check commits and:
Readme: https://github.com/bpampuch/pdfmake#table-of-contents
Example: https://github.com/bpampuch/pdfmake/blob/master/examples/toc.js

**Comment by liborm85** [comment]
New version with first implementation TOC was released.
