### ISSUE TITLE
Adding Images ClientSide

### ISSUE THREAD

**Issue by MentalGear** [bpampuch/pdfmake#1260]
I'm wondering what's the correct way to add images to a .pdf clientside (e.g. from a browser, not node). Apparently, I can't just add links. Is a data base64 format my only option ? (quality is not the best with base64)

PS: Great library, and awesome that it allows automatic text floating.

**Comment by liborm85** [comment]
On client-side only base64 can be used for image.
Image in base64 doesn't affects image quality.
