### ISSUE TITLE
Security properties addition needed in the doc definition

### ISSUE THREAD

**Issue by BaelishLord** [bpampuch/pdfmake#1262]
Is there anyway to add security properties of the pdf before download of the same.

for example. content copying, printing, page extraction, etc

**Comment by liborm85** [comment]
Marked as feature request.
Requires implementation in the library pdfkit, issue: https://github.com/devongovett/pdfkit/issues/16.

**Comment by julie-ng** [comment]
FYI - encryption is coming soon to pdfkit, there's a Pull Request here https://github.com/devongovett/pdfkit/issues/16

**Comment by petrgazarov** [comment]
Here is the link to PR: https://github.com/foliojs/pdfkit/pull/820

**Comment by MobileAppVault** [comment]
Hi, can you give an ETA when this feature will be available in pdfmake?

**Comment by liborm85** [comment]
Created PR for implements security from pdfkit - https://github.com/bpampuch/pdfmake/pull/1591
Status: **_waiting for new version of pdfkit_**

**Comment by liborm85** [comment]
Released in 0.1.50.
