### ISSUE TITLE
Download of PDF takes very long time to start

### ISSUE THREAD

**Issue by leFroxx** [bpampuch/pdfmake#1263]
I'm using v0.1.35 of pdfmake.
I'm trying to start the download of a pdf file of 8 pages, each one including a "full screen" image.
The way I was tracking time was like this:
```
const start = Date.now();
pdf.download('file.pdf', () => {
  console.log("downloaded after " + (Date.now() - start) + "ms");
});
```
In Chrome v63 it takes about 2600ms to start downloading the pdf.
In Chrome v63 on my mobile device (OnePlus 5 running on Android 8.0.0) it takes about 23500ms.

Taking more than 20s for a pdf file of 8 pages to start a download (not even create) is way longer than it should.
Increasing the size of the pdf's content also increases the time of the download to start.

If you need more code please let me know.

**Comment by liborm85** [comment]
You are measuring total time - including generating pdf document, not only time to start download.
Generally mobile devices are slower therefore it takes longer.

**Comment by leFroxx** [comment]
I see, so `download()` does not only prepare the download, but also builds the pdf file? I thought that'd be done by `pdfMake.createPdf(docDefinition)`.

Well, I figured out that in my case the generation takes so long because of the big images (750px*1060px aka a full DIN A4 page with a high enough resolution) I put inside it. When I remove them and only put in some texts, it gets loaded pretty much instantly.

But using `pdfmake` the way I do (generating images from a part of my DOM with `html2canvas` and build a pdf with those images consuming space of a full pdf page each) is a way that's used quite often as I figured out, so I wouldn't have expected it to take so long. Imagine generating a bigger file of let's say 100 of those pages. That would take a huge amount of time – even on desktops, what'd make it pretty much unusable like this.

Is there a way you can recommend achieving what I want to do? So taking a part of my DOM and generate a multipaged pdf file out of it including CSS styles?
