### ISSUE TITLE
Making a blob using pdfMake

### ISSUE THREAD

**Issue by luckyvs1** [bpampuch/pdfmake#1264]
I read the documentation available and tried the following:

`const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBlob((blob) => {
	// ...
});`

However, i was given the following error `Uncaught TypeError: pdfDocGenerator.getBlob is not a function`.  Is there any further documentation that highlights how to convert the resulting pdfMake into a blob or something else as an intermediate step before converting to a file object (or even directly)?

**Comment by liborm85** [comment]
I tested and method `getBlob` works. What version of pdfmake you have?

**Comment by luckyvs1** [comment]
Just checked the version of pdf make is `1.0.38`

**Comment by liborm85** [comment]
This version number doesn't exist. You aren't using official version.

**Comment by luckyvs1** [comment]
Thanks for the information, we ended up updating the package to use the NPM version of pdfMake. I think there was some confusion with the following package from Atmospherejs: (https://atmospherejs.com/nilsdannemann/pdfmake).
