### ISSUE TITLE
Line between columns

### ISSUE THREAD

**Issue by elard28** [bpampuch/pdfmake#1267]
I want to add a line between columns in a paragraph. I can't fin the option that works.

**Comment by liborm85** [comment]
You can draw line with vector (see https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js).

**Comment by Jeremias-Nater** [comment]
I dont think this is working without making it absolute, and especially not over multiple pages. In my case the columns start mid-page and cover multiple pages, how would i add a line between them in this case?
