### ISSUE TITLE
Broken columns with spaces

### ISSUE THREAD

**Issue by edjayks** [bpampuch/pdfmake#1269]
A simple columns with 2 text as below, will result in the 2nd text be rendered in first column.
If i insert any visible character such as '_' in the second text, then it will is correct, which it will display right next to first text.

columns: [
          {text: 'Date of Collection :', width: 'auto'},
          {text: padEnd('                                           '), width: 'auto', style: 'underlineItem'}
        ]
styles: {
        underlineItem: {fontSize: 9, decoration: 'underline'}
    }

**Comment by liborm85** [comment]
Please attach example for reproduce your question executable on [playground](http://pdfmake.org/playground.html).
