### ISSUE TITLE
about vertical-align question

### ISSUE THREAD

**Issue by chenyuechuan** [bpampuch/pdfmake#1273]
when some td's content is too much ,the same of row's td space will be opened, I want to the opened td can located in the vertical center , can author have some good idea to fixed this question? thanks,very much!!!

![image](https://user-images.githubusercontent.com/16483031/35668966-7f43b438-076e-11e8-9a92-25151ca3b7c2.png)

**Comment by liborm85** [comment]
Is not supported now. Here is feature request: https://github.com/bpampuch/pdfmake/issues/74

**Comment by IsmaellHV** [comment]
and now?

**Comment by MrOttimista** [comment]
Still not supported 
but there are some work arounds you can use

**Comment by dinhtrongthong** [comment]
and now?

**Comment by hoangntm** [comment]
> Still not supported but there are some work arounds you can use

which work?

**Comment by MrOttimista** [comment]
Adding margin-top and bottom to all items and keep the height constant 

> > Still not supported but there are some work arounds you can use
> 
> which work?

**Comment by hoangntm** [comment]
> Adding margin-top and bottom to all items and keep the height constant
> 
> > > Still not supported but there are some work arounds you can use
> > 
> > 
> > which work?

In my case, the height is not fixed.

**Comment by dinhtrongthong** [comment]
> Adding margin-top and bottom to all items and keep the height constant
> 
> > > Still not supported but there are some work arounds you can use
> > 
> > 
> > which work?

it's too easy for the case of "the height constant".
in my case, the height not fixed and use a combination of rowspan, colspan and breakpage

**Comment by muhammadAliAmin89** [comment]
Is vertical alignment is supported now for table columns ? in 2024

**Comment by rohankm** [comment]
waiting for the same

**Comment by MeesterZee** [comment]
Would love this feature--still no updates? Hoping to see this in 0.3.x

**Comment by stvndelucis** [comment]
Still not update ?
