### ISSUE TITLE
Dynamic header - write over header-area

### ISSUE THREAD

**Issue by stuwi** [bpampuch/pdfmake#1274]
Actually, I would need **different pagemargins per page**... but because this is not yet possible I try to help myself with dynamic header-height.

I need a **higher header on the first page** (250px) than on all **following pages** (120px).
So I set the pageMargins to [20,120,20,20] and the title of the first page with a margin of [0,130,0,8].

As we/you know the header-content ist only writen to the **header-area** (120height in this case)

in LayoutBuilder.prototype.addDynamicRepeatable

`this.writer.beginUnbreakableBlock(sizes.width, sizes.height);`

So I changed this line to:

`this.writer.beginUnbreakableBlock(sizes.width, this.pageMargins[3]);`

*--> not ok for the footer - I know ;-)*

I'd like to have a option like "unlimited-header-height"

**Comment by liborm85** [comment]
https://github.com/bpampuch/pdfmake/issues/368
