### ISSUE TITLE
line opacity

### ISSUE THREAD

**Issue by Azimuth67** [bpampuch/pdfmake#1275]
Is it possible to add opacity to a single line or circle line?

Best regards

**Comment by Azimuth67** [comment]
Where can I find strokeOpacity in examples?
Examples doesn't cover everything.
Where can I find other stuff in pdfmake without having to ask?

Best regards

**Comment by liborm85** [comment]
`strokeOpacity` works much like `fillOpacity`.
Yes in examples is not everything. New documentation is needed, see issue: https://github.com/bpampuch/pdfmake/issues/1238.
