### ISSUE TITLE
require('pdfmake') loads the PdfPrinter function, not createPdf

### ISSUE THREAD

**Issue by andrei-pmbcn** [bpampuch/pdfmake#1276]
The docs say:

> for server-side use require('pdfmake');
> for client-side use require('pdfmake/build/pdfmake.js'); and require('pdfmake/build/vfs_fonts.js');

However, running var x = require('pdfmake') loads the PdfPrinter function into x, whereas running var x = require('pdfmake/build/pdfmake.js') loads the createPdf function into x. Indeed, the "main" field in the project's package.json points to "src/printer.js". This is a problem because PdfPrinter is more limited in scope than createPdf.

**Comment by liborm85** [comment]
There is not much to do on the server like in a browser. Therefore, the interfaces are different, as is written in documentation.

**Comment by zjr** [comment]
@liborm85 where is this in documentation? I don't see anything about needing to load this differently in your docs. As @andrei-pmbcn said, your docs say "for server-side use require('pdfmake');".

I don't see anything in your documentation about needing to run `new PdfPrinter` nor its font arguments, nor it's main function `createPdfKitDocument` which differs from the client side version, nor that the server side version is different from the client side version.

I don't think having a link to some code is the same as documenting that the client and server versions of this library work so differently and it certainly seems the documentation could be improved in this regard. The implication is that the server side version of this library is going to work just like the client side version.

**Comment by liborm85** [comment]
@zjr see https://github.com/bpampuch/pdfmake#server-side

It is true that better documentation is needed, issue for new nice documentation is created: https://github.com/bpampuch/pdfmake/issues/1238

**Comment by zjr** [comment]
thank you @liborm85
