### ISSUE TITLE
what CSS is supported?

### ISSUE THREAD

**Issue by FrancescoMussi** [bpampuch/pdfmake#1277]
Hello, great component.
One question:

How can I know the exact css classes that I can use?

In my use case I need this css to be applied to my text:

```
border-bottom:  1px dotted #000,
text-decoration:  none,
```

It seems it is not supported, right?
There is any way to force that style somehow?

Thanks

**EDIT:**

I found this while searching the examples:

`decoration: 'underline', decorationStyle: 'dotted'`

I think it can be awesome to have a clear reference to all the style possibility to make easier how to style the pdf.

**Comment by liborm85** [comment]
CSS is not supported, this is not a HTML.

Examples are available on [playground](http://pdfmake.org/playground.html) and in [examples folder](https://github.com/bpampuch/pdfmake/tree/master/examples). Documentation is not complete, but I have a issue for create new nice documentation https://github.com/bpampuch/pdfmake/issues/1238.

**Comment by FrancescoMussi** [comment]
Yes I totally agree on the need  of a new documentation.

What I meant is to have all the possible styling options listed one by one. 

So who wants to user this component can easily find what he need without having to rummage between examples.
