### ISSUE TITLE
Support for variables

### ISSUE THREAD

**Issue by chandanch** [bpampuch/pdfmake#1280]
Assume that we have specify the same value for multiple elements and also for multiple properties  for example we have color property: `color: red`.  Instead of specifying red for all elements  we can create a variable 

```sass 
$color: red
header: {
   color: $color
}
table-element: {
   color: $color
}
```

In this way we can reuse the same variable and we can specify color for multiple elements

**Comment by liborm85** [comment]
Yes, docDefinition is Javascript, you can program it as you need it.
