### ISSUE TITLE
Columns ordered top to bottom instead of left to right

### ISSUE THREAD

**Issue by leonlovett** [bpampuch/pdfmake#1282]
I have been using pdfmake in a project and it works great, but now I have a need to eliminate the white space that happens when there is varying lengths of content on the same row (please see attached). One thing that I had in mind was to have the columns laid out top to bottom first, but I was unsure of how to do that. 

I guess what I am looking for is a masonry-type layout - similar to Pinterest on desktop.

The issue is caused by the whole row being set to the height of the tallest cell.

If someone could point me in the right direction, it would be much appreciated.

![image](https://user-images.githubusercontent.com/8462457/36160497-f326159e-10a6-11e8-8246-f084ca5525b8.png)

**Comment by liborm85** [comment]
Don't use `table` but `columns`, see on [playground](http://pdfmake.org/playground.html) on columns tab.

**Comment by leonlovett** [comment]
I am using columns. In the image below, I need column 3 to shift up and fall right under column 1. So, the rows will no longer be aligned.


![image](https://user-images.githubusercontent.com/8462457/36382398-5e07dfae-154e-11e8-9243-43d7bebddfbd.png)

**Comment by liborm85** [comment]
Do not use 4 columns but only 2, example:

```js
var dd = {
	content: [
		{
			columns: [
			    [
				    {
					    text: 'First column.\n\n'
				    },
				    {
					    text: 'Second item in first column'
				    },
				],
				[
				    {
					    text: 'Second Column. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Malit profecta versatur nomine ocurreret multavit, officiis viveremus aeternum superstitio suspicor alia nostram, quando nostros congressus susceperant concederetur leguntur iam, vigiliae democritea tantopere causae, atilii plerumque ipsas potitur pertineant multis rem quaeri pro, legendum didicisse credere ex maluisset per videtis. Cur discordans praetereat aliae ruinae dirigentur orestem eodem, praetermittenda divinum. Collegisti, deteriora malint loquuntur officii cotidie finitas referri doleamus ambigua acute. Adhaesiones ratione beate arbitraretur detractis perdiscere, constituant hostis polyaeno. Diu concederetur.\n\n'
				    },
				    {
					    text: 'Second item in second column'
				    },
				]
			]
		},
	]
}
```

**Comment by leonlovett** [comment]
This takes care of the white space issue. Thanks for your help.
