### ISSUE TITLE
Question: Unrecognized document structure error

### ISSUE THREAD

**Issue by luckyvs1** [bpampuch/pdfmake#1285]
Sometimes there is an unrecognized document structure error thrown, this goes away if the same file is used for conversion.

Any suggestions on how to go about troubleshooting this issue?

![screen shot 2018-02-15 at 9 58 04 am](https://user-images.githubusercontent.com/25218389/36280601-a673c8ea-124f-11e8-8804-389fb5c954ca.png)

**Comment by liborm85** [comment]
Is wrongly defined `docDefinition` check it.
