### ISSUE TITLE
Rendering issue of grayscale+transparent (alpha channel) .PNG

### ISSUE THREAD

**Issue by oleksiy-nesterov** [bpampuch/pdfmake#1286]
For the .pdf templating the grayscale images (with alpha channel) are used very often, but here is a issue. See my screen.

Issue screen:
![Issue screen](https://content.screencast.com/users/Oleksiy/folders/Jing/media/716b7994-df92-4975-9713-781213150e89/2018-02-16_1108.png)

Original image:
![Original image](https://res.cloudinary.com/stuzodev/image/upload/w_112,h_112,c_thumb,g_face,a_exif,r_max,e_make_transparent:0,f_png/v1518770541/ahjxal8omy95st9uah3o.jpg)

Base 64 image:
```data:image/png;base64,/9j/4AAQSkZJRgABAQAAYABgAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/wAALCACCAIIBASIA/8QAHAAAAQUBAQEAAAAAAAAAAAAABQECAwQGAAcI/8QAPhAAAgECBQIEBAMHAgQHAAAAAQIDBBEABRIhMUFRBhMiYRQycYEHQpEjM1JioaKxFSQ1coLBQ2NzksLR4f/aAAgBAQAAPwD6LkAKAk/e2Ig6ow1g/YYswtu19vbEiuL98NLsxBIt7YeRb64S1jfDxKsalpGAUbknawwErfEHnLoypFcHb4mW4j/6Ry/2sPfAeknrK/MJY6vMqg08a6XEGmJTId9iBqAAtyT8w32xPWNPlqF6aurPNLrHDFJKJRMxtYHUCV3vcg7AE40VVmlPRxxR1coNQy30RoWZu5Ci5tiPLs3pq+rmp4PPE0ShmDwugAPG5Fr+3OC6g9bXxIBjgMLbGejaYsV1eknpthrwu7ixG3fFnUyIFvc2te2+JadTpJIwpPrGJipYenFbMJ4qOleepfTGvYXJPQAckk7ADnGHzietzFomrf2NK0gEVJybAFtUp4J2+UbD3NiIKyokdlRSbk2OL3huAnLIWBsHLS3ve+piwB+xA+2CMx8/N4aeHT50MRdNQuFLXXX76QGFuusfXEhpoMvEkKSrHKy+bU1kjAsF41Mx6ngDgWPQWw9szkoYYosqyzzNZPlRzTGOSY9XtpY233Z7HvyL6qFyVBIsbbjtiXHYX74xuW5ys1W1JVwCmrSLqA+pJQOqNYXt1BAI7WscFZQQAVO/YYmhUNZpDdhidSCeDhAp18C2Kmd5tS5LRmepbk6URRdnboAO+MxleY1Gb5lUyV+kGKNHhgX5YdRcE+7WFr/W1rm7s9pxDSU87m5Sdf63X/5DEFPCDKWZTfm2LXhhR/pRiYnXBNJGQewYlf7Sp++CdNDFHUyToP2rgKW6kC9h/U4oSRiGorc1zVv9tC+uGHoSoADHuf4RwLk8na5kNTSxB6qvm/3lRYySMjLGg6Rq5FrC/Q7m56408ZuAVN1IvccYkBvh3TCXx5rUQLVMY5HZGBDJInKMOGU9/wD9B2OC3h/MpasS0leVFfTWD2FhIvR19j26H7XNINL2vv2xbVSBgfnuc0uS5e1XVte3pSMfNIx4Ue/+Nz0x5lLV5jmmY5hPmcdpldVjUNtChRW0gdOdzycOy3OYMtzXVCz1krIY5o4BqsRuLn5RbfYkH1e2C2YZpU11Oy1pgpKdyBoT9rITfYA2te9rAA723xfo/DkNVEkmbF5ibHyXbUB9el/+Ww+vOCsXh/LE/cUdPEwFg0aBG/UWOGS0FTSamoapj18qoYyKfubsP1t7HFCvq8xqqciCjaBachptVmkfuIjwTbhj9LA3scybKsqrKGOojaSqSUXEssrM3632IO1trYOZbQxZfSrT05fyVJKh3LEXN7XO9t8WedhhduMdbHjKLNS+uhPw5H/hMLxMP+X8v1W253BwRgr3qtFXTL5OYUd2eJjs6nlb9Va2x7gdiMa+gzGnr4qeqo5BJDKupWHUYu1+Yw0FHJU1TCOKMXY8/YDqTwB1x5oc4lzbNvjo6f4yYHTTxF7QUy+77hnPJ0g2ItfYHCNRNmFJVZxmkqTPIVp6eGNSkTDVpDMoN2FyTuTdQDt0WOlpsvoI4KdVVLbdz7nF3w7SCvzd6p/VT0PojvwZSNz/ANKn+49RjcxJqTcWGF0lPtvvhki3I+a+O0aSL8Yo+HtWXeIcxorEU1Qq1kAPAb5ZFHsCEb6ucadZCzWtYYmBt0xwBF747Hj8FJkVSxjyivjp5uLUsykX90NwfuMUsxhdHrvijFNTUEDSyPGCgmJFxEy9tgWF9/T0JGKdPU1+S1TPllSWfyjNURVA1RkKAC5FwVYkjg252NsG5KWr8RZrTpnE6zJHBLOlPECkGoWVdSknUbuTc7ekWA3uMgqfIyBXpLoVotUQHQhPTjUeJoEocrymlgUKEmEQHQAQyW/S2B0gp0hMspIjiBdj7AXP+Mafw9SNQZFSQSi0+nzJv/UY6n/uJx02btHmfwNOrs0aB5NKFjY/cAfU89AbGxWCqjqYtSagL2IZSpB+hxMoAGrp0xWrJvKhLrFJK1wAkYF9z77AYBU0tVD40yumqxJd4JtJdg1xZSxU2FxdVuLCxI6EY3YAHAw8HbDhhPtjwh63LKuIxN5VVJexjQeaQe+lQSMEfCtBDXeH66CNDH8RNKpUqVP8I2O42A5wuR5e2ax59BIRHVy0cVPLb8kg81T+jA/0wV8Lnzs2pZgNJmoHOi/ykOmpfqCbYx2aK1FRVNKNhSF4yODpXv8AVQD98b/xXSmbKoqgneGeNvpqOgn7BicZvRrpmhZtpSsLfRmCn/JxvbMWNhffa+OybLnp4pGnYNUzuZJXHFztYewFgPpiy8LK9/y4WRy/fDo4ySp4GIKhY5fEuVEg+bFDPIre37NSP7h+mNAhxJxjhhMeco0EMi00EfmS2usEKjUBxe3AHubDDsqc5ZWzxVlI1OtVMGgdmVlLFQChtwbgkd77b4KwUsNJW1NRFCqzVOkyuv59IsL/AGxRo8nNNn0tdT1FqZ1kPklN0dypaxvwSt7W5J36AJ43y74WeSu0f7Gpj0VDWv5bAadRPYrt2Gkd8FcjEmY+EqRKrUwqKRVkvsWugBxm6JahYBDVeqpiqo43NgLsJE9X0NwR7EY9KpiHCsRgbWZ6i5jLRUcbTTxAa7OqKpO+m5623sO4va4xYoM0WeUxSrJFIgtJFKBqW42O1wRsdwSOexxYklhiWSaRtEEal2Y7AAbk4zmUeLaLNPiXy2roqp4BrlpYn1TIg5NwbEjtbna/XGhpdMviGSQEN5dHHYjs7ve310D9MHTwCMLyLDHRhgDqIO/Tph1/bGWyqhhy2nKQgln3eRzdnPcnDqyhTMoJKepXVC46Gx7gg9CDYg9xihk1VMwlo69tdfRt5chIA81fySW/mHNttQYdME5AZWUWtix6TTMJSBpF2JNtsN8tI4izEKqgkk9Bgc9DR1MsNd5Ks4UGOQrY2O4/z9rnBKAXuO2PiPxL4jzNvGmc1seZ1MbpXTPEEkICjzDY244AH0x9Q+Es8k8RZf4VzZ1UT1dPPHNo4JQgFvpqX+7Fr8Ymmi/DDxA1K0iT/Delk+YHUOMfLX4HVeYZb+IeW1NKryxJFMrDgSL5TkKR7sB97e2PsHL5o8mzKKlrpV8x8ugRG6yNGzh7Dk/OvHfF9/EKqdMFFVTX6lVjH95B/piVc6qNFxlzn285L/5x0Wfxq1qykqqVeS5TWg9yy3A+9sGI54pI1eORGRgGVlYEEHqMCY0LXDcDtixGtkuvTGV8YEZdUU+fQox+GHlVYUX1QE7n6ofV7DV3wdpyXVZEKsrbgjqDwcZrxxmJakbLaOUfE1BEUpH5EIuR9SAdu1/a49cwzLN6iOmrFggoPOSN4oJC5mNixVmIFlsBdQN77m1wd2oDxA4pVtPKXVoaqantz5YU3/8Acpx5Xn34F5DW01ZPl9dWxZhLqdGmZGjLE3OoBQbH2O2Nf4JyFMqyygpYllihy2k+EiMgAZnYhpWtvtdVt9+RYm9J4ajzenkgzmpneGYFXp4ZGVCp/KWPrPvYgHsMSUn4f+F6QAQ5JRXUBQzJqa2xtqO/IBxV8ReEcuFNRy06tTmKoRAinUjCRghujXX8wPHQYor4Oghr/IqoKCV5ATCxpxEJbfkultLfUNcccHEjeGo4tUNHNW0FQi6jCZ3ZLd1s1yPe/wBRiFKnOstmSN6uTWxsPMQSRtt0Isf1IPthzVAdi8uQZO8jG7MwsWPUn0H/ACcbmM2X089scutvm+XDa+qoaCjeXMJI46c+ljIRY36e5PbrjE01ZPRZfLCJnocmja0Esq2nZDwiqfl7C41W20jY4BiTzGkqpoWgpV9MMIuzkMeT1Mjm3O/A5vjReG6O8xEgW9N6nK8ec43A76Est/c42SOqxC+2K9XVRQR6pUkk1nSiRrdmP+Oh3NhjD5f+IeX5tmTZbldJUitPyLWFYUJ7XBY39rXxs6RJvhkFSVMgA1FRYX9gemL0caqovzh0s6xqbnYcnGfgq5M+zCJ4f+FU0msSdKiQcaf5FO9+pAtsDcj4iB+Bga5Eq1cHltyQxkVf8Ej74J5jSirhCxkJUx+qN/4W9+4PBHbGdqZMtqKRo6yrpqWR1v5csqq8LjuCeQR/TAanbNZII3WjdgyghhESDtze2NgpYA2w3MK6Kgy2oq5QWWGNpCoO7WF7YyFTJJ8Rq8qKszOxD1cl/Jpj1RB7dlsTb1G+BlXTxwaqqsqGlZFLPNIdlHXQOB223PUnDqOOerq4lVFjqEXXFCwDfCobjzZB/Gdwq/XfnGzoaJKKiSGFTpFySTckk3JJ6kkknFlidKgqcSaXcaQfvj5D/FtqjK/xAzPL1jZUScSFwSLKw1rb7NbBPKPxD8TQLT0uW5hWCWVlSOJmWZSTawPmAkCxvtj2nKajP80eKm/1upDogaodIIQEv2uh3PQff66SLwzHVf8AFaytzAdY55bRn6ogVW+hBxpYoVgjVEUKqiwA4GKlEwzeuSoQXoaViImt+9lsQWH8ouQO5JPQEnY0tuRh5VWIuoNu4w6w7YE6FCE8Yy/jSoMOSvEh9NTLHTM/OhXYKT9bE297YFUUxTTBFHop09IXAqeZ87rY5MvRGjWTyaOJvkqJV3aY/wDlpY26E+4GNVQ+HoI6cKZJEr7l2rEsJGfqT0I2AsbiwA6Ytpmj0JWDPESIH0pWRgiF+17/ALs+zG3YngGJkIQEDnFczKrBda+YBq033t3tjEZ54RyvxXVeJqOvp42q5RFNBUDaSLVFoBVuQLxnbg4y9T+GmT+FqnLM5oaeqMmkQfCSSayJXAClT320W49V9rY9UyXL48qoYaclTUlRJMyj5mPJ/wCw9h7YvV2YUlBEslVMkeo2RfmZz2VRux9gCcVHirs8XRUI9Dlp+aO/7adext8insCWI/h3B0VNEIokjjVURAFVFFgAOABixvbcY6+H74CsQzEFjbFXMsthrqSSCVQ0cgswvz/9YzNZ4XqpI2p/j5RSvs5jjUSkdRq4H2W/33wWyPKqXK7SxKTIEEQd7elP4VA2UcbADjB9UjmW/wArYY9KLMrgEMLEHgj3wLbKKugs2RVCRxDmiqLmG38tt4/oPT/LgRmy520sFQMoRamB7hoatXV0PzIdQU2I425CnpiZUllrYM5yZopBNAIZY5roHUMSu4BKspZxYjqQbWwlesNFozvxBUiaWn9NNBEp0Ru3pAReXkN9IPO9gBc3nyjLM4qkkqMwq1pZagh2jhQM8S29Metrg2HNl5JI5wey3J6WhdpI49UzbPNIS8jfVjvb24HTBGyr8owqbnD9xhR3w6+AM3pfbE0EgsA25w9wrH0m3/bFd0Ky2IBXE8ezDa2LBuUHW364SNhe2J2RXH1wElyFVqZJ6GompHlOqRUsUc9ypBF/cWv1wkHh6Ja5KyqlkrKmMHy2ltaK/OlQAAT35tte2DOoIAFtirDmHnyHy4wsPmNCJHcAu63B0r1AIPNuDtbfFxD6SbjT3vinWZlFTQGaMLMhDWZXFrqCSD2NgfuLbYhkzF6irkoV/Yz+SWsQSbnZSCPy7Hf3HB2xTyTNZ6moMC008Y1aj5riTylAAKswY2bVfY9PpjR3wIlUMd+BiCNR5we+w2wQRNVj0wsqenpiEFjYbA4sQPYWY4fIu11wiMwG+HM3pucRi77EbHDzZV2GM/SZbJBDC0USM3w5TVCVH7Zvncn/AARc7ttvixHltRHX/FRR00dofKMKuQjm4Oo+na1gODcHfgYgp6KghoEomqzUSKx80U41M/q1AMBe3QXNvriwuUz1dQ80zy0ylFjUh7TBASdN1Nhcnc3N9tgRfBijpIaOBYaeNUjXoOp6k9yTuSecTeWD1OA78HFeoNlW23qA/rgony/bDxxipJsxtiaPnFr8uEGIpemJI/3Zw4c4pZpDEYmkMSGT+LSL/ripldDSVEKvUUsEr/xPGGP9cG40VECooVQLAAWAxIOuEb5Tjsf/2Q==```

**Comment by dmytro-kerest** [comment]
doh! I have the same issue!

**Comment by Savenets** [comment]
seems like I have the same issue

**Comment by bellgetlinks** [comment]
I have the same issue :(

**Comment by peterver** [comment]
@bellgetlinks @Savenets @dmytro-kerest @oleksiy-nesterov this is actually due to an issue in pdfkit ( https://github.com/foliojs/pdfkit/issues/339 ), please voice your concerns there as well :D. As a temporary solution to anyone who encounters this, you can either save the image as PNG 24 ( photoshop ) or save the image with 8bpc RGBA setting in Gimp.

**Comment by liborm85** [comment]
Fixed in version 0.1.50.
