### ISSUE TITLE
Combine multiple document definition objects

### ISSUE THREAD

**Issue by vivek1729** [bpampuch/pdfmake#129]
In a question posted on [stackoverflow](http://stackoverflow.com/questions/26731494/pdfmake-how-to-create-multiple-page-pdf-with-different-orientation),  an issue was brought up to have an option to set individual page orientation.

I suggested creating multiple document definition objects and combining them with the `append` flag like so:

       pdf1.pipe(fs.createWriteStream('foo.pdf'));
       pdf2.pipe(fs.createWriteStream('foo.pdf',{flags:'a'}));
       pdf3.pipe(fs.createWriteStream('foo.pdf',{flags:'a'}));

But it is not working. Related [gist](https://gist.github.com/ismile/3db044e5d557a8912b22). Is there a simpler way of addressing this problem? If not, how do I go about combining multiple doc definitions in `pdfmake`.

**Comment by jthoenes** [comment]
Different page orientations is no allowed with #202. Closing the issue
