### ISSUE TITLE
Having trouble with a value, it won't fill the cell

### ISSUE THREAD

**Issue by RicMBM** [bpampuch/pdfmake#1293]
Good Morning,Afternoon,Nigth, depending on your local time.

I did a Call for information, but it just wont fill the cell.

**Here im using the pdfmake playground:**

![github1](https://user-images.githubusercontent.com/36857095/36683024-24f225f0-1ae2-11e8-97db-53829613f3ac.PNG)
all well done, size, widths,heights, etc.
but after creating the PDF it looks like this:

![github1-5](https://user-images.githubusercontent.com/36857095/36683025-251476b4-1ae2-11e8-9ec5-15996747080d.PNG)
somehow it makes a (\n) but in the playground looks ok.

**Heres how it looks the data after the call:**
![github3](https://user-images.githubusercontent.com/36857095/36683339-ed9c9fb2-1ae2-11e8-9fed-12f5324e1e76.PNG)
also tried removing those white spaces, leave a white espace after the first word then comma then white space and second word, still no results.

**Heres another example but now im just leaving an empty space:**

![github2](https://user-images.githubusercontent.com/36857095/36683027-252aea20-1ae2-11e8-80dc-37cbe5125d3d.PNG)
_**that white space the one above this**_
still wont respect the empty space i did, and it downloads like this:

![github2-5](https://user-images.githubusercontent.com/36857095/36683477-498ae536-1ae3-11e8-9db3-767422b7128c.PNG)
**_that white space the one above this, got removed._**

Any help, tip will be apreciated, if more information is needed please let me know.

Thanks.

**Comment by liborm85** [comment]
If it works only on playground you're using outdated version, update pdfmake to latest version.

**Comment by RicMBM** [comment]
The white space needed, got fixed updating the pdfmake.min file but the problem with the Text persist, any suggestion?

![github4](https://user-images.githubusercontent.com/36857095/36739436-8328ebf4-1ba5-11e8-9958-707cde6fedc6.PNG)

**Comment by RicMBM** [comment]
Found the problem with the text, somehow the database from the company I'm working keeps getting a '\r' while getting the information so in the API im getting Reynosa\r,Tamaulipas\r thats the reason.

Applying a **_.replace('\r','')_** fixed the problem.

Thanks for the support. Problem Solved
