### ISSUE TITLE
Dowload pdf file

### ISSUE THREAD

**Issue by Legends** [bpampuch/pdfmake#1295]
I have a pdf file encoded a base64 string, that I get from my serverside ASP.NET application.
like: `var pdf = "<this is my base64 string>" // my pdf file`

I saw this example, but have no clue how it works?!

```
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
	alert(data);
});
```

What is `docDefinition` here, it's not described in conjunction with base64 string.
How do I have to configure it?
What do I have to return in the arrow function below?

**Comment by liborm85** [comment]
In `docDefinition` is content which will be converted into a pdf file, see [styling and further](https://github.com/bpampuch/pdfmake#styling).
Method `getBase64` return pdf file in base64.

**Comment by Legends** [comment]
I already have the pdf as `base64` string (from the server).
I want the user to click on a button/link to download it?

Is this possible with pdfmake.js?

**Comment by liborm85** [comment]
Pdfmake library is for generating pdf files. Can not loading pdf files.

**Comment by Legends** [comment]
Thank you for the info.
