### ISSUE TITLE
Watermark only works as string, not as an object

### ISSUE THREAD

**Issue by hillelcoren** [bpampuch/pdfmake#1302]
With earlier versions of the library the following code worked:

```
        dd.watermark = {
            text: 'preview',
            color: 'black',
            opacity: 0.04,
        };
```
After updating to v0.1.36 only the following works:

`dd.watermark = 'preview';`

Thanks for your help and amazing project!

**Comment by liborm85** [comment]
I tested on playground (with version 0.1.36) this:
```
var dd = {
	content: [
		'Test page of watermark.',
	]
}

dd.watermark = {
    text: 'preview',
    color: 'black',
    opacity: 0.04,
};
```

And all works ok.

**Comment by hillelcoren** [comment]
Thanks for the quick response, it must be something specific to my code.
