### ISSUE TITLE
Get Base64 from PDF

### ISSUE THREAD

**Issue by RicMBM** [bpampuch/pdfmake#1303]
Good Morning,Afternoon,Night depending on your local time.

What im trying to do is to create the base64 from the created pdf what im trying is:

```
const pdfDocGenerator = pdfMake.createPdf(
            {
                info: {
                    title: 'awesome Document',
                },
                pageMargins: [8.5, 8.5, 8.5, 8.5],
                content: Content
            }
        );
        var Base64PDF = pdfDocGenerator.getBase64((data) => {alert(data);});
```
but no success the example above i got it from: 

https://github.com/bpampuch/pdfmake

title: **Get the PDF as base64 data**

is the closest one to work but only through : **_alert(data)_** 
im able to see the base64 and im not capable of sending that value to the variable Base64PDF.

The second example i saw (without sucess) is from #198  tried:

> If you want to have only the base64 encoded string do:
```
var data;
pdfMake.createPdf(docDefinition).getBase64(function(encodedString) {
    data = encodedString;
});
```

Any help,tips,guidance will be appreciated.

Thanks

**Comment by liborm85** [comment]
Method `getBase64` have a callback function because it is **asynchronous** operation. In this callback do all what you need with base64 string.

**Comment by RicMBM** [comment]
Done, working 100% thanks and in case someone is interested here it is:

    //CREATION OF THE DOCUMENT
    const pdfDocGenerator = pdfMake.createPdf(
    {
    info: {
    title: KardexData["0"].FullName,
    },
    pageMargins: [8.5, 8.5, 8.5, 8.5],
    content: Content
    }
    );

    //NOT NECESARY ONLY USEFUL FOR ME IN CASE YOU ARE WORKING WITH SENCHA
    /* var form = this.getView();
    var cont = form.down('#docContainer'),
    width = cont.getWidth(),
    height = cont.getHeight();*/
        
    //GETTING THE BASE64 AND SETTING IT TO A CONTAINER FOR PREVIEW
    pdfDocGenerator.getBase64((data) => { 
        form.down('#docContainer').setHtml('<object width="' + 
        width + '" height="' + height + '" data="data:application/pdf;base64,' + data + '"></object>');
    });

    [data="data:application/pdf;base64,] =  specifies data type Base64
