### ISSUE TITLE
When saving the PDF how to set the name

### ISSUE THREAD

**Issue by RicMBM** [bpampuch/pdfmake#1304]
Good Morning,Afternoon,Night depending your local time

The title might be confusing but i'm actually looking a way about how to name the PDF, like we do with:

    var PDF = pdfMake.createPdf({
    pageMargins: [8.5, 8.5, 8.5, 8.5],
    content: Content
    }).download('Test.pdf');

but now using:

     .open( [Name Here] )

i did use:

    pdfMake.createPdf({
                    info: {
                             title: 'awesome Document',
                             },
                             pageMargins: [8.5, 8.5, 8.5, 8.5],
                             content: Content
                        }).open();

but when downloading the file it gets a random name with numbers and letters I read # 501 and saw that it got tagged with Feature Request, Did the update realized?

Any help,tip,guidance will be appreciated

Thanks

**Comment by liborm85** [comment]
This is not supported by browsers. Only `title` can be used (see https://github.com/bpampuch/pdfmake/issues/501#issuecomment-292787563).

**Comment by RicMBM** [comment]
Yes,but the title that got from:     
    
    title

 can be used for the downloaded document?

**Comment by liborm85** [comment]
Yes, it can be used. `title` will be used in pdf viewer for display document title (how exactly, depends on viewer).

**Comment by RicMBM** [comment]
but when i download the PDF it creates a random name for Save, looks like a base64 kind of, with random numbers and letters

**Comment by liborm85** [comment]
This is a "feature" of browsers while using `open`. For nice file name you must use `download` method.

**Comment by moffsugita** [comment]
@RicMBM  finally did you give up?
