### ISSUE TITLE
Border-Radius for images?

### ISSUE THREAD

**Issue by elainebyrne** [bpampuch/pdfmake#1305]
Hi,

I understand someone at #385 has already asked but that's a border around an image. I'm looking to set a "border-radius" on the image. Huge difference so please don't close this thread.

I'm generating a resume using PDFMake and need the image to have about 'border-radius: 4px'. Some hack or solution would be appreciated.

**Comment by liborm85** [comment]
Duplicate with feature request for implement border style in issue https://github.com/bpampuch/pdfmake/issues/385.

**Comment by elainebyrne** [comment]
This is NOT a duplicate request. You are just closing without even reading it. #385 is EXTREMELY different than what I'm looking at. 

Or you don't know how to resolve the issue and closing threads!! Shameful.

**Comment by liborm85** [comment]
This is **NOT** CSS but pdfmake which has a completely **DIFFERENT** definition. Pdfmake **NOT** support CSS.
Yes in CSS exists [`border`](https://www.w3schools.com/css/css_border.asp) and property [`border-radius`](https://www.w3schools.com/cssref/css3_pr_border-radius.asp), but both is **style border for element**, so from the point of view pdfmake are **SAME**!

No issues was only closed, all were redirected to feature request issue https://github.com/bpampuch/pdfmake/issues/385 because there is no need to have 100 issues, for **SAME** thing, only written differently.

I keep the project in my spare time without any money. So it is not possible to assume that everything will be done immediately.

You can implement this request a create pull request, it is welcome.

**Comment by elainebyrne** [comment]
Thank you for the clarifications. I understand you are contributing in your spare time and we can't thank you enough.

I was upset that there's no feature request and yet it was closed without allowing anybody else to comment on it or give a solution (hack) to get this done. Anyways, I have used Python to generate from the backend with html/css template. Wishing this plugin achieve great success in the coming days. 

Thank you once again for your contribution. People like you are the ones who are truly making our lives easier and better.

**Comment by NadeemShadan** [comment]
> Hi,
> 
> I understand someone at #385 has already asked but that's a border around an image. I'm looking to set a "border-radius" on the image. Huge difference so please don't close this thread.
> 
> I'm generating a resume using PDFMake and need the image to have about 'border-radius: 4px'. Some hack or solution would be appreciated.

One of colleague actually used an image with hole in it and the through the hole the image below would. The image was placed over the other one using `absolutePosition`

**Comment by animoffa** [comment]
hope it's helpful. works for me
`{svg: "<svg width="80" height="80">
				<defs>
					<clipPath id="circleView">
						<rect id="rect"  width="100%" height="100%" rx="10"/>
					</clipPath>
				</defs>
				<image 
				  width="80" 
				  height="80" 
				  xlink:href="${imgAvatar}" 
				  clip-path="url(#circleView)"
				/>
			 </svg>",
				width: 80,
			},`

**Comment by therbta** [comment]
This worked for me. Thanks @animoffa for the base code.

```
<svg width="80" height="80"> 
      <defs>
	  <clipPath id="halfCircleClip"> 
                     <circle cx="40" cy="40" r="40"/>
	   </clipPath>
	</defs>
	<image width="80" height="80" xlink:href="data:image/jpeg;base64,${image}" clip-path="url(#halfCircleClip)" />

```

**Comment by DanisKhasanov** [comment]
```
const roundImageWithCanvas = (images, width, height, radius) => {
  return new Promise((resolve, reject) => {
    const img = new Image();
    img.src = images;
    img.onload = () => {
      const canvas = document.createElement("canvas");
      canvas.width = width;
      canvas.height = height;
      const ctx = canvas.getContext("2d");

      ctx.clearRect(0, 0, width, height);
      ctx.beginPath();
      ctx.moveTo(radius, 0);
      ctx.arcTo(width, 0, width, height, radius);
      ctx.arcTo(width, height, 0, height, radius);
      ctx.arcTo(0, height, 0, 0, radius);
      ctx.arcTo(0, 0, width, 0, radius);
      ctx.closePath();
      ctx.clip();

      ctx.drawImage(img, 0, 0, width, height);

      resolve(canvas.toDataURL("image/png"));
    };
    img.onerror = reject;
  });
};
```


```
  const roundedImage = await roundImageWithCanvas(images, 80, 80, 10); // radius = 10
```


```
  {
      image: roundedImage,
    },
```



Hello everyone, I found this solution!
Pass base64 to Canvas and trim there and get back base 64 with the necessary styles. Then display it in content
