### ISSUE TITLE
How to concatenate text styles within the cell of a table?

### ISSUE THREAD

**Issue by Adrek** [bpampuch/pdfmake#1306]
Hello everyone,
Please, I would like you to help me.
I want to know what is the correct way to concatenate text with independent styles within a cell.

The code is the following:

```
 {
            table: {
                widths: ['*','auto',150,'*'],
                body: [
                    ['Nro','Nombre','Apellidos','Dni'],
                    ['001','Pepe','Suarez','7041654'],
                    ['002','Miguel','Sanchez','8787997'],
                    ['003','Juan', ['Suarez',{text:'Benites',bold:true}],'8787997']
                ],
                headerRows: 1
            }
        }

```
And the current result is:
![firefox_2018-03-11_01-15-42](https://user-images.githubusercontent.com/12045258/37250439-9e095f8e-24ca-11e8-93d4-6f091a0547ed.png)

The result I need is:
![needed](https://user-images.githubusercontent.com/12045258/37250441-a523833a-24ca-11e8-858b-19c49c85dca5.png)

I do not know why it makes a line break.

Thank you very much.

**Comment by liborm85** [comment]
See https://github.com/bpampuch/pdfmake#styling, texts must be in one `text` element.

Example:
```js
	 {
            table: {
                widths: ['*','auto',150,'*'],
                body: [
                    ['Nro','Nombre','Apellidos','Dni'],
                    ['001','Pepe','Suarez','7041654'],
                    ['002','Miguel','Sanchez','8787997'],
                    ['003','Juan', [ {text: ['Suarez ', {text:'Benites',bold:true}]} ],'8787997']
                ],
                headerRows: 1
            }
        }
```

**Comment by Adrek** [comment]
Thank you very much. It works perfect
