### ISSUE TITLE
Set table row height to fit all remaining page

### ISSUE THREAD

**Issue by jlameiro87** [bpampuch/pdfmake#1308]
Hi, I'm generating a table with dinamic content, and I want to set last row height to fill all remaining page size, there is a way to know remaining page height until footer? The rows can have differents heights according to his content
![tables](https://user-images.githubusercontent.com/31218194/37313813-364e17dc-2627-11e8-8e54-30c1f120a67e.png)

**Comment by liborm85** [comment]
feature request: https://github.com/bpampuch/pdfmake/issues/1427
