### ISSUE TITLE
Set title in the download option

### ISSUE THREAD

**Issue by Maikel-mg** [bpampuch/pdfmake#1309]
It is posible to set the title of the document in the download method?

**Comment by liborm85** [comment]
Title can be set over `info` metadata:
```js
var dd = {
  info: {
	title: 'awesome Document',
  },
  ...
}
```

see https://github.com/bpampuch/pdfmake#document-metadata for more information

**Comment by RicMBM** [comment]
By download method i think you are asking for:

    var PDF = pdfMake.createPdf({
            pageMargins: [8.5, 8.5, 8.5, 8.5],
            content: Content
        }).download('TEST.pdf');
