### ISSUE TITLE
Error: [BrotliDecompress] invalid distance

### ISSUE THREAD

**Issue by pedro3900** [bpampuch/pdfmake#1310]
I started get this problem today, Error: [BrotliDecompress] invalid distance, I can only reproduce it in ios but some users has this problem with my app in chrome in apple devices and normal PCs.

This maybe is cause by any update because the software works fine the days before but today appear this error.

**Comment by liborm85** [comment]
Currently only on some iOS devices is this error throwed, see https://github.com/bpampuch/pdfmake/issues/935.

Is repored in brotli.js - https://github.com/devongovett/brotli.js/issues/18.
