### ISSUE TITLE
Not able to set background color for a text full page width

### ISSUE THREAD

**Issue by sankarmahadevan** [bpampuch/pdfmake#1315]
I tried to generate pdf file from a div without table implementation.  Attached a sample 
![300dpi](https://user-images.githubusercontent.com/3656739/37447032-fe284a8c-2845-11e8-970e-017bca306334.jpg)
image.  I want to generate the pdf how it looks in html view.  Data may contain images also.

`var content = [];
		var today = moment().format('lll');
		var docDefinition = {
		   content: content,
			styles: {
				header: {
					background: '#5f5f5f',
					color:'#fff',
					fontSize:16,
					bold: true,
					margin:[5,35,0,0],
					width:'100%',
				},
				questionStyle: {
					width: '100%',
					fontSize: 13,
					bold: true,
					margin:[5,20,20,0],
				},
				answerStyle: {
					width: '100%',
					fontSize: 13,
					margin:[20,10,0,0],
					color:'#57585a'
				},
				date: {
					color:'#57585a'
				}
			}
		 };
		 
		
			
		
		content.push({text: today,style: 'date',regular: true,fontSize: 10,margin:[0,-20,0,0],alignment: 'right'})		
		content.push({ text: temptitle, style: 'header' })
		
		
		for(var i = 0; i < questions.length; i++){
			var index = i + 1
			content.push({ text: index+'. '+questions[i].question, style: 'questionStyle' })
			if(questions[i].answers){
				for(var j = 0; j < questions[i].answers.length; j++){
					content.push([{ text: questions[i].answers[j].answer, style: 'answerStyle' }])
				}
			}else if(questions[i].answer){
				content.push({ text: questions[i].answer, style: 'answerStyle' })
			}else if(questions[i].files && questions[i].files.length > 0){			
				for(var k = 0; k < questions[i].files.length; k++){
					//content.push({image:$scope.img,width:300,height:200,margin:[20,10,0,0],alignment: 'left'})
					content.push({ text: questions[i].files[k].caption, style: 'answerStyle' })					
				}
			}
			if(questions[i].subQuestion){
				content.push({ text: index+'. '+questions[i].subQuestion.question, style: 'questionStyle',	margin:[15,20,20,0]})
				if(questions[i].subQuestion.answers){
					for(var j = 0; j < questions[i].answers.length; j++){
						content.push([{ text: questions[i].subQuestion.answers[j].answer, style: 'answerStyle',	margin:[30,20,20,0]}])
					}
				}else if(questions[i].answer){
					content.push({ text: questions[i].subQuestion.answer, style: 'answerStyle',	margin:[30,10,20,0]})
				}
			}
			
		}
	//	pdfMake.createPdf(docDefinition).open();	   
		pdfMake.createPdf(docDefinition).download(temptitle+".pdf");//Create PDF		
	}`

**Comment by liborm85** [comment]
There is no other way than to use `table` now.
