### ISSUE TITLE
Is there a row height minimum ?

### ISSUE THREAD

**Issue by FrancescoMussi** [bpampuch/pdfmake#1317]
Hello. Great library.

I need to make a table with very short height, something like 6 or 8.

```
table: {
       heights: 8,
       body: [...]
}
```

But it seems that it doesn't make it shorter than 10.
Is there is a minimum of 10 in place for table rows?
Would be possible to override it?

Thanks!

**Comment by liborm85** [comment]
Try set table padding to zero:
```js
			layout: {
				paddingLeft: function(i, node) { return 0; },
				paddingRight: function(i, node) { return 0; },
				paddingTop: function(i, node) { return 0; },
				paddingBottom: function(i, node) { return 0; },
			}
```
and smallest `fontSize` to texts.

**Comment by FrancescoMussi** [comment]
I am sorry, somehow I have missed your reply.

Thanks! It works perfectly!

**Comment by myUsernamesTaken** [comment]
Hey!
Is it possible to use this in combination with layout: 'noBorder' ? 
Many tries, but don't get that working.

**Comment by sanathpathiraja** [comment]
@myUsernamesTaken 
try this,
```
layout: {
	        hLineWidth: function hLineWidth(i) {return 0;},
                vLineWidth: function vLineWidth(i) { return 0;},
		paddingLeft: function(i, node) { return 0; },
		paddingRight: function(i, node) { return 0; },
		paddingTop: function(i, node) { return 0; },
		paddingBottom: function(i, node) { return 0; }
	}
```
