### ISSUE TITLE
GC Error when generating a big file

### ISSUE THREAD

**Issue by longweiquan** [bpampuch/pdfmake#1319]
Hello,

When I try to generate a big file with 10000 lines in a table, PDFMake fail with GC error. Do you have Idea on how to fix this problem, I would help if you can tell me the right direction. 

Thank you in advance. 

<--- Last few GCs --->

[2258:0x102802400]    64733 ms: Mark-sweep 1404.5 (1467.5) -> 1404.5 (1467.5) MB, 3929.5 / 0.0 ms  allocation failure GC in old space requested
[2258:0x102802400]    68235 ms: Mark-sweep 1404.5 (1467.5) -> 1404.5 (1445.0) MB, 3501.7 / 0.0 ms  last resort 
[2258:0x102802400]    72313 ms: Mark-sweep 1404.5 (1445.0) -> 1404.5 (1445.0) MB, 4077.8 / 0.0 ms  last resort 

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0xbb3c771cef1 <JSObject>
    2: /* anonymous */ [/node_modules/pdfkit/js/mixins/text.js:166] [bytecode=0x2bac2e02d9b1 offset=51](this=0x94114509dc1 <JSGlobal Object>)
    4: _initOptions /node_modules/pdfkit/js/mixins/text.js:169] [bytecode=0x2bac2e02dae9 offset=57](this=0x84591eddae9 <PDFDocument map = 0x322cf62159c9>,x=0x1d1893...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 4: v8::internal::Factory::NewTransitionArray(int) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 5: v8::internal::TransitionArray::Insert(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Map>, v8::internal::SimpleTransitionFlag) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 6: v8::internal::Map::CopyReplaceDescriptors(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Handle<v8::internal::LayoutDescriptor>, v8::internal::TransitionFlag, v8::internal::MaybeHandle<v8::internal::Name>, char const*, v8::internal::SimpleTransitionFlag) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 7: v8::internal::Map::CopyAddDescriptor(v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 8: v8::internal::Map::CopyWithField(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
 9: v8::internal::Map::TransitionToDataProperty(v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Object::StoreFromKeyed) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
10: v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::Object::StoreFromKeyed) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
11: v8::internal::StoreIC::LookupForWrite(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
12: v8::internal::StoreIC::UpdateCaches(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
13: v8::internal::StoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::Object::StoreFromKeyed) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
14: v8::internal::KeyedStoreIC::Store(v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
15: v8::internal::Runtime_KeyedStoreIC_Miss(int, v8::internal::Object**, v8::internal::Isolate*) [/Users/longweiquan/.nvm/versions/node/v8.4.0/bin/node]
16: 0x1dbeaca840dd
17: 0x1dbeacb6c786
18: 0x1dbeaca92f12
19: 0x1dbeacb73fa1
20: 0x1dbeaca92f12

Process finished with exit code 134 (interrupted by signal 6: SIGABRT)

**Comment by ssbunny** [comment]
I've come across the same issue.

**Comment by apeter10** [comment]
I've the same issue

**Comment by liborm85** [comment]
Solved in new version see https://github.com/bpampuch/pdfmake/issues/1052#issuecomment-459941689.
