### ISSUE TITLE
Problem with pdf generation with Safari Browser

### ISSUE THREAD

**Issue by jitui2i** [bpampuch/pdfmake#132]
Hi all,

Could any one please help me to resolve this error regard download the pdf in safari browser ...

The error is here :+1: 

"'[object BlobConstructor]' is not a constructor (evaluating 'new Blob([result, {type: 'application/pdf'}, null])')"

Please help me regard this ...

**Comment by jthoenes** [comment]
I don't have any issue with current Safari on Mac. Can you post your code?

**Comment by bpampuch** [comment]
@jitui2i - which version? I can't reproduce this issue

Maybe this will solve this?
http://stackoverflow.com/questions/14347534/blob-constructor-not-working-in-safari-opera
