### ISSUE TITLE
Website down

### ISSUE THREAD

**Issue by ThisWillDoIt** [bpampuch/pdfmake#1321]
The connection to pdfmake.org times out since 18.3. (?).

**Comment by lerasah** [comment]
I'm running the [dev-playground](https://github.com/bpampuch/pdfmake/tree/master/dev-playground) on my local until the website is up.

**Comment by liborm85** [comment]
@bpampuch Site http://pdfmake.org/ doesn't work, receiving ERR_CONNECTION_TIMED_OUT message. Can you solve it?

**Comment by paulverkooijen** [comment]
Hi @bpampuch website is still down?

**Comment by AishS** [comment]
Hi , any updates on this??

**Comment by lerasah** [comment]
# [Temporary Playground](https://tinyurl.com/pdfmake-temp)
Hi folks, my work this week is heavily depends on this library, so I made a clone of the playground which is for the purpose of testing your document definitions. Enjoy!

**Comment by KerimG** [comment]
Does someone have an API reference?

**Comment by liborm85** [comment]
Full website cloned to temporary mirror: http://liborm85.github.io/pdfmake

Information was added to readme.

**Comment by liborm85** [comment]
@bpampuch You need to restore pdfmake.org domain. Can you hear me? :)

**Comment by liborm85** [comment]
Site pdfmake.org is back.
