### ISSUE TITLE
Google Chrome 65, PDFMake Compatibility Issues

### ISSUE THREAD

**Issue by visaolive** [bpampuch/pdfmake#1323]
Hello

- In our project
- We're using version v0.1.26 of pdfmake.js
- When users upgrade to Chrome version 65
- When users attempt to export a report, they receive the following error
- Refused to frame blob: because if violates the Following Content Security Policy directive, "frame-src https: mailto:"
- Error on pdfmake.min.js Line: 2 (mostly due to being minified)
- What is the proper version of PDFMake works with Chrome Version 65, or is this still pending?

**Comment by liborm85** [comment]
Tested on Chrome 65 with pdfmake 0.1.36. Update to the latest version.

**Comment by deverlex** [comment]
I have same issue with pdfmake 0.1.36 and Chrome 65.0.3325.181
