### ISSUE TITLE
How to set table to next new page if not enough space available for it on current page.

### ISSUE THREAD

**Issue by anknegi** [bpampuch/pdfmake#1326]
I am generating a pdf containing tables of products with products category and subcategory as its header and body as products listing.  What I want that if product listing of one category and subcategory is finished and their is not enough space left for showing next category and subcategory products ,then they should appear on next page rather than on a current page. Is there any way to do this ? Please help.
This is how my current code is : 

  var docDefinition = {
			    pageSize: 'LETTER',
          pageMargins: [0, 20, 0, 30],
          header: function(page, pages) {
            margin: [0,0]
  			 },

          footer: function(currentPage, pageCount) {
			      return {
			        //text: 'Page : ' + currentPage.toString() + ' - ' + pageCount.toString(),
              text: 'Page: '+currentPage.toString(),
			        alignment: 'right',
              margin: [ 10, 0, 12, 0],
            }

			    },
          //pageMargins: [ 0, 0, 20, 40 ],
					content: <?= json_encode($data); ?>,
			    styles: {
			      navBar: {
			        fontSize: 28,
			        bold: true,
			        fillColor: '#0a2958',
			        color: '#fff',
              margin: [ 0, 20],
			        alignment: 'center'
			      },
			      bannerSide: {
			        fillColor: '#2c77b8',
               //margin: [ 0, -20, 0, 0],
			      },
            header_section:{
              margin: [ 0, -20, 0, 0],
            },
            mainCategory: {
              margin: [ 10, 0, 10, 0],
            },
            subCategoryName: {
              margin: [ 10, 0, 10, 0],
            },
            bannerImage: {
              margin: [0, 0, 0,0],
            },
            footer_section: {
              fillColor: '#2669BB',
              margin: [0, 125, 0,0],
            },
            tabledata: {
             margin: [ 10, 0, 10, 0],
             alignment: 'left',
            }
			    },
			    defaultStyle: {
			      fontSize: 8,
			      alignment: 'justify'
			    }

			  };
			  pdfMake.createPdf(docDefinition).download();
			}());

**Comment by superlbr** [comment]
+1

**Comment by superlbr** [comment]
I just got an idea. It could be calculated that height remain in a page and height for a table

**Comment by liborm85** [comment]
Set property `unbreakable: true` to `table`.
Example:
```js
{
	unbreakable: true,
	table: {
		body: [
			...
		]
	}
},
```

**Comment by wadouk** [comment]
awesome ! would be great to have it in doc !
