### ISSUE TITLE
dashed line

### ISSUE THREAD

**Issue by Rodrigo54** [bpampuch/pdfmake#1327]
how to make a dashed line?
dashed line is supported in pdfkit.
In this [link ](http://pdfkit.org/docs/vector.html)I see that dashed line is supported in pdfkit
in pdfkit api I could do something with this
```js
doc.moveTo(0, 280)
   .lineTo(700, 280)
   .dash(5, { space: 10 })
   .stroke();
```

I know how to make a separator line thanks to issue #2 

```js
{ canvas: [{ type: 'line', x1: 0, y1: 5, x2: 595 - 2 * 40, y2: 5, lineWidth: 0.5 }] }
```

but since the documentation is not complete #1238, 
I wanted someone to explain how I make a dashed line

**Comment by liborm85** [comment]
```js
var dd = {
	content: [
		{
			canvas: [
				{ type: 'line', x1: 0, y1: 280, x2: 700, y2: 280, dash: {length: 5, space: 10} }
			]
		}
	]	
}
```

And examples with vectors is here: https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js

**Comment by cesc1802** [comment]
How i can make a text beofore dash line. Somethings line this blablabla..............

**Comment by SanjidHaque** [comment]
HI @cesc1802, we can achieve that with table/columns
