### ISSUE TITLE
pdfmake playground is not working

### ISSUE THREAD

**Issue by chiragparmar17** [bpampuch/pdfmake#1328]
PDFMake Playground Link - http://pdfmake.org/playground.html  is not working since last few days.

![image](https://user-images.githubusercontent.com/15837363/37696381-201590a4-2cfc-11e8-9db4-d39ae40b713f.png)

**Comment by lerasah** [comment]
Duplicate of [#1321](https://github.com/bpampuch/pdfmake/issues/1321)
