### ISSUE TITLE
How to get currentPage in the content array?

### ISSUE THREAD

**Issue by dudusotero** [bpampuch/pdfmake#1330]
Is possible to get the currentPage in the content array like in background function?
I need to set different margins on all pages or some way to change the absolutePosition of continuation of text, but I can't find a way to do this.

Does anyone have any ideas?
Thanks!

`background: function (currentPage) {
    return currentPage % 2 === 0 ? oneImg : otherImg;
},`
`content: [
    {
        text: 'Some loooooong text....'
    }
]`

**Comment by liborm85** [comment]
No, it is not possible, only by `background`, `header` or `footer`.

**Comment by superlbr** [comment]
@liborm85 since [pdfkit](https://github.com/devongovett/pdfkit) could use addPage(), why not pdfmake

**Comment by liborm85** [comment]
@superlbr Because in pdfkit is necessary to write use methods `writeText`, `moveDown`, etc., but pdfmake generate pdf dynamically by `docDefinition`.

**Comment by superlbr** [comment]
why not just define a convert rule, like [{ addPage: true }]

**Comment by liborm85** [comment]
Of course that internally pdfmake uses pdfkit methods, when it's built on pdfkit.

If you mean directly only `addPage` and your question is not related to this issue, then of course it goes:
```js
{text: 'Text break after this text', pageBreak: 'after'}
```
or
```js
{text: 'Text break before this text', pageBreak: 'before'}
```

**Comment by superlbr** [comment]
@liborm85 yeah, you're right. should be #1326
