### ISSUE TITLE
Including images in header or footer?

### ISSUE THREAD

**Issue by zopyx** [bpampuch/pdfmake#1336]
We use pdfmake as part of its DataTables.net integration through the `customize()` callback.

Is it possible to include an image as part of the header or footer?

**Comment by liborm85** [comment]
Yes, you can add image into header and footer, simple example of `docDefinition`:
```js
var dd = {
    header: function(currentPage, pageCount, pageSize) {
        return [
            { image: 'sampleImage.jpg', height: 30, width: 100 }
        ]
    },
    footer: function(currentPage, pageCount, pageSize) {
        return [
            { image: 'sampleImage.jpg', height: 30, width: 100 }
        ]
    },    
    content: [
        'text'
    ]
}
```

**Comment by zopyx** [comment]
Is it possible to pass in an arbitrary URL?

**Comment by liborm85** [comment]
No, ony local file (in browser from virtual file system storage) or base64, see https://github.com/bpampuch/pdfmake#images.

**Comment by torresdaniel11** [comment]
@zopyx  i use another library called html2canvas, what i do is pass the image inside a html element, i set 'useCORS', and then i receive a data element, i can pass that element to pdfmake to print in the file
