### ISSUE TITLE
Display the PDF as an svg or png/jpg?

### ISSUE THREAD

**Issue by Sondro** [bpampuch/pdfmake#1345]
I have no problem loading a pdf preview into an iframe or div using getBuffer() or getBase64(), but how about as an image?

Simply changing the type or data source causes an error or leaves the page blank.

Do I need another lib for this?

**Comment by liborm85** [comment]
pdfmake allows only generate pdf files. If you want transform to image use any third-party library.

**Comment by Sondro** [comment]
Thanks, btw do you have any recommendations for such a lib other than jsPDF?

I'm not very familiar with the PDF via JavaScript ecosystem.

**Comment by liborm85** [comment]
you can try:
* http://usefulangle.com/post/24/pdf-to-jpeg-png-with-pdfjs
* https://gist.github.com/ichord/9808444
* https://gist.github.com/jdeng/cbfad9cb21e452127c81
* or next results via google

**Comment by MentalGear** [comment]
Hey @Sondro, did you get this working? Would you mind sharing your implementation with the community? :)

**Comment by Sondro** [comment]
I didn't get around to adding this feature because of the styling limitations in PDF Make. Instead I decided to go with a refactor of html to canvas/png to pdf workflow.

This should be failry trivial to add if you use js pdf.
