### ISSUE TITLE
Wrong Barcode Base64 decoding

### ISSUE THREAD

**Issue by thejoe8495** [bpampuch/pdfmake#1346]
Hello,

i have problem to generate a PDF with generated Barcode.
The barcode who pdfmake decode is wrong. I hope anyone can help me and give me a workaround or an fix for it.
The Base64 converter http://freeonlinetools24.com/base64-image convert the image perfekt

**Function to generate the barcode:**
https://github.com/milon/barcode/blob/2a17de5f20ea9c23eb9924c00c74861a044886ef/src/Milon/Barcode/DNS1D.php#L170

**Orginal:**
![image](https://user-images.githubusercontent.com/15785677/38620703-748c4584-3d9f-11e8-9c29-f8bdc399cd55.png)

**Broken Image pdfmake:**
![image](https://user-images.githubusercontent.com/15785677/38621051-548c3d74-3da0-11e8-8e61-62c49e777439.png)

**pdfmake Playground:**
var dd = {	content: [		{			image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAA/AQMAAABtkYKcAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAL5JREFUKJGF0M0JwzAMBWDdeks2SBYxZK300hQ6SFdxFmjGyNWgSwzBr5IdsPNTqtMHz7ZkEbC6ukOgS/CkcGTYGqoyGIYng4+C6t+gI4A/kBZh2HolyBjAbp4zpFxNqRIwSgT3iBj38GCvcP3t5fHsM7B0kAqKMMwyTwmNBFZfeJfAdqsZIpYLSLGltoD+y5qEho4IssO4efmOqzJ0UZNGglauH+DXhOa+aqMCMgWHhPkEjbSFHO4zdL0xOuEL+QtWeoVDRCYAAAAASUVORK5CYII=',
		},			],	}

**Base64:**
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAD8AAAA/AQMAAABtkYKcAAAABlBMVEX///8AAABVwtN+AAAAAXRSTlMAQObYZgAAAL5JREFUKJGF0M0JwzAMBWDdeks2SBYxZK300hQ6SFdxFmjGyNWgSwzBr5IdsPNTqtMHz7ZkEbC6ukOgS/CkcGTYGqoyGIYng4+C6t+gI4A/kBZh2HolyBjAbp4zpFxNqRIwSgT3iBj38GCvcP3t5fHsM7B0kAqKMMwyTwmNBFZfeJfAdqsZIpYLSLGltoD+y5qEho4IssO4efmOqzJ0UZNGglauH+DXhOa+aqMCMgWHhPkEjbSFHO4zdL0xOuEL+QtWeoVDRCYAAAAASUVORK5CYII=

**Comment by liborm85** [comment]
Probably this png format is not supported, try re-save image.

**Comment by thejoe8495** [comment]
With a resave in Paint.net the picture is shown. But what can i do to save a working picture in php?

**Comment by liborm85** [comment]
Try some php library to work with images.
