### ISSUE TITLE
Linking to a section in PDF

### ISSUE THREAD

**Issue by nomad1072** [bpampuch/pdfmake#1347]
Is there a way to use the PageReference attribute and also use a custom text for a table row. For Example:
`[{text: 'some sample text', pageReference: {"id"}}]`

Presently, the pageReference overrides the text attribute and places the page number in the field. 
Alternatively, could the pageReference be used with the linkToPage attribute to directly link to a page.

**Comment by nomad1072** [comment]
Is this intended behaviour? I kinda have a PR ready for this bug to show both the text provided by the text field and the pageNumber added by the pageReference attribute.

**Comment by nomad1072** [comment]
Sure, thanks a lot. This is exactly what I wanted. Will close the PR.

**Comment by liborm85** [comment]
New version released.

**Comment by Ravindhart** [comment]
Is there any way I can show the text, but when clicked on that text it will navigate to the corresponding page number?
for example in the above example, it will show just "some sample text" but on clicking this text, it will take us to page no:2?
Thank you.

**Comment by nomad1072** [comment]
Please check these issues #897 #1237. This is probably what you are looking for.
