### ISSUE TITLE
Zoom of view

### ISSUE THREAD

**Issue by wvinim** [bpampuch/pdfmake#1351]
How can i set the default zoom onload?

**Comment by liborm85** [comment]
Default zoom set in your pdf viewer.

**Comment by Wabbala** [comment]
It is possible, but it is a manual action, see:
https://forums.adobe.com/thread/488335
It can be done automatically using indesign when exporting a document to
pdf. But how to do that using pdfmake/pdfkit, you can ask the pdfkit
community!

**Comment by liborm85** [comment]
I didn't find any documentation how to add pdf file anywhere of this "zoom" feature in pdf standards.

**Comment by wvinim** [comment]
Thank y'all
