### ISSUE TITLE
Possible to add special page cut commands to Thermal printers? (e.g. Epson)

### ISSUE THREAD

**Issue by afilp** [bpampuch/pdfmake#1352]
I create a single PDF, that has many different "tickets", 1 per page (I use a page break after each).

I then use the `print()` command to print this PDF in a Thermal printer (Epson).

This printer also has a **cut paper** functionality.

This is a achieved by adding special characters to the output, as shown here:
https://reference.epson-biz.com/modules/ref_escpos/index.php?content_id=87

I tried to add them to the footer of each ticket, so that each ticket is automatically **cut**:

```
          // footerText += "&#x1b;@&#x1d;V0";
          footerText += "\x1B@\x1DV0";
```

But this just shows weird chars in the PDF (which is reasonable).

![image](https://user-images.githubusercontent.com/7850073/38779160-2641b644-40cd-11e8-95a3-952ac9e3d03b.png)

My question is: Is there a solution to this? Is this possible somehow?

Thanks!

**Comment by liborm85** [comment]
Printer requires these special characters for cut, so it must be in pdf, so what do you want to solve? This probably has no solution, or use a small font or white font color (if is paper white).

**Comment by afilp** [comment]
Unfortunately, these special characters cannot work with the PDF. I found that the printer can cut the paper on page break through settings in their device driver, so I am OK now.

Thanks for the feedback, now closing this issue.

**Comment by jasminder** [comment]
What page size to use for thermal print ?
