### ISSUE TITLE
Unsupported Number Error

### ISSUE THREAD

**Issue by shardool-freightwalla** [bpampuch/pdfmake#1358]
I am seeing the below error when I add the attached doc definition.
[error_doc_definition.txt](https://github.com/bpampuch/pdfmake/files/1942336/error_doc_definition.txt)

```
pdfmake.js:3180 Uncaught Error: unsupported number: 57.0625*210
    at o.number (pdfmake.js:3180)
    at c.lineTo (pdfmake.js:24913)
    at w (pdfmake.js:13555)
    at pdfmake.js:13409
    at g.createPdfKitDocument (pdfmake.js:13197)
    at l._createDoc (pdfmake.js:12709)
    at l.getBuffer (pdfmake.js:12847)
    at l.getDataUrl (pdfmake.js:12827)
    at generate (playground.html:124)
    at playground.html:114
```
![screen shot 2018-04-24 at 4 06 25 pm](https://user-images.githubusercontent.com/17472264/39182275-fe49fb92-47d9-11e8-9664-807b134d4569.png)

Some of my findings are : 
1. When I remove the newline "\n" from line 11 text , the pdf is rendered properly.
2. Also when I remove a table from the definition it works fine.

I am unable to find if there is maximum size that I am overflowing by adding new lines or any other issue. In my application, I have data which contains many paragraphs with new lines and I keep hitting this error when my data size grows.
Appreciate your help in this.

**Comment by liborm85** [comment]
`heights` does not support `*`, instead of `heights: ['*', 100],` use `heights: ['auto', 100],`.
