### ISSUE TITLE
Could not open file because its either not supported or damaged

### ISSUE THREAD

**Issue by NikhilNanjappa** [bpampuch/pdfmake#1359]
I'm trying to generate a PDF as per the code below server(NodeJS) code. The issues I'm facing are:

1. While making the call to the API from postman, it prompts me to download the file but **no PDF file extension is seen after download**.
2. The PDF download when opened will always give the error `Adobe Acrobat Reader could not open the xxx because it is either not a supported file type or because the file has been damaged (for example, it was send as an email attachment and wasn't correctly decoded)`

```
const pdfMake = require("pdfmake/src/printer");

generatePdf = (dd, callback) => {
  const printer = new pdfMake(fontDescriptors); // fonts loaded
  const doc = printer.createPdfKitDocument(dd);

  let chunks = [];

  doc.on('data', (chunk) => {
    chunks.push(chunk);
  });

  doc.on('end', () => {
    let result = Buffer.concat(chunks);
    callback('data:application/pdf;base64,' + result.toString('base64'));
    // callback('data:application/pdf;base64,' + Buffer.from(result.toString('base64'), 'base64')); <<-- this somehow works as data appears 
  });

  doc.end();
};
```
and calling the 'generatePdf' function as below:
```
  generatePdf(docDefinition, (binary) => {
      res.contentType('application/pdf');
      res.send(binary);
    }, (error) => {
      res.send('ERROR:' + error);
    });
```

This is exactly as mentioned in the [example](https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js), so why does this not work as expected? Please help.

**Comment by melistik** [comment]
Hi,
I also try to get server running. For me it also doesn't work. 
Try to run the application as described within readme. 

My post example via postman (content-type: application/json):
``` json
{"content": "var dd = { content: 'First paragraph' }"}
```
The pdf is broken. 

Any idea what I do wrong?

**Comment by liborm85** [comment]
That's issue is related to postman.

**Comment by NikhilNanjappa** [comment]
If anyone still looking for solutions, check out [my blog on how to generate & properly serve a PDF](https://medium.com/@kainikhil/nodejs-how-to-generate-and-properly-serve-pdf-6835737d118e) using NodeJS (implementing `pdfmake` package).
