### ISSUE TITLE
chinese charaters can't show normally?

### ISSUE THREAD

**Issue by dianyitongxiao** [bpampuch/pdfmake#136]
Hi, my content contains chinese charaters, however when I download the pdf, it's blank. don't support it?

**Comment by jthoenes** [comment]
There are two possible reasons for this:

* Your font does not support Chinese characters. See here to use a custom font with Chinese characters: https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
* You have more than 95 different characters in your document. There is a but about this. See #165
