### ISSUE TITLE
In "pdfmake/build/vfs_fonts.js" this.pdfmake is undefined in webpack.

### ISSUE THREAD

**Issue by bspatil0001** [bpampuch/pdfmake#1364]
While generating vendor.js this.pdfmake in "pdfmake/build/vfs_fonts.js" "this" keyword is undefined.

**Comment by liborm85** [comment]
How does it relate to pdfmake? I do not know what you have in the `vendor.js` file.

How to use pdfmake is described in [readme](https://github.com/bpampuch/pdfmake#getting-started).
