### ISSUE TITLE
Table title - Adjust text on headers after page break

### ISSUE THREAD

**Issue by jgking2** [bpampuch/pdfmake#1365]
What I'm trying to do is adjust a table elements header row, if it's been rendered again on any subsequent pages.  For example, if you have a table with a header as such.
```
Table Title
Data In body
Data in body
--page break within table--
Table Title (contd...) 
Data In body
Data in body
```
I've looked into pageBreakBefore, and at the tableProcessor.js, but it appears the header portion of the table node is just cloned to repeat, with no hook to adjust the data.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/531
