### ISSUE TITLE
Using images stored in variable

### ISSUE THREAD

**Issue by myUsernamesTaken** [bpampuch/pdfmake#1366]
Hey there,

i let the user choose which background image shall be printed via radio buttons. The images are stored in another js file as dataUrls in a variable. 
I can print the images, when i set the variable in the document definition. 
When i use the radio buttons values (they are identical to the image variables names) store them in a variable, and put this variable into the document definiton, i get this error message: `pdfmake.js:12777 Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)`

Don't know what to do... :(

**Comment by liborm85** [comment]
Create simple example runnable on [playground](http://pdfmake.org/playground.html) or [jsfiddle.net](https://jsfiddle.net/) for reproduce problem.

**Comment by gwhi94** [comment]
Did you find any solution?
