### ISSUE TITLE
Uncaught TypeError: Cannot read property 'pageSize' of undefined

### ISSUE THREAD

**Issue by r2222** [bpampuch/pdfmake#1367]
even though after adding page size the same error is coming

 var docDefinition = { content: 'This is an sample PDF printed with pdfMake' , pageOrientation: 'portrait',pageSize:'A4'};
  pdfMake.createPdf(this.docDefinition).download('optionalName.pdf');

**Comment by liborm85** [comment]
Tested on playground and in script and works ok. It will not be a problem in pdfmake, but something else affects it.

**Comment by knnhcn** [comment]
I came across the same problem with no fix yet. When I log pdfMake I can't see any enums and I can't use them.

Service I used for pdfMake instance:

`import { Injectable } from '@angular/core';
import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

@Injectable()
export class PdfExportService {
  private _pdfMake: typeof pdfMake;

  constructor() {
    this._pdfMake = pdfMake;
    console.log(this._pdfMake);
    this._pdfMake.vfs = pdfFonts.pdfMake.vfs;
  }

  get pdfMakeInstance() {
    return this._pdfMake;
  }

}`

Creating pdf -> TypeError: Cannot read property 'A4' of undefined:

`      const dd = {
        content: [
          {
            image: img,
            width: 800
          }
        ],
        pageSize: null,
        pageOrientation: null,
      };
      dd.pageSize = this.pdfExportService.pdfMakeInstance.PageSize.A4;
      dd.pageOrientation = this.pdfExportService.pdfMakeInstance.PageOrientation.LANDSCAPE;
      this.pdfExportService.pdfMakeInstance.createPdf(dd).download();`
