### ISSUE TITLE
Extra space added after Hyphen or minus sign causing spacing issues in words with hyphen

### ISSUE THREAD

**Issue by hobbsi** [bpampuch/pdfmake#1368]
Extra spaces are added sometimes after Hyphen or minus sign. Seems to be related to big words in a line, because most times it works good. This is a problem when there are some long words in the line, giving output results like "language-_______ dependent" ( _______ = spacing).
 
For example the following text with -(mimus) or even ‐(hyphen) gets an extra space after "language-":

Input:
"The details are complex and language-dependent, and can interact with other orthographic and typesetting practices. Hyphenation algorithms, when employed in concert with dictionaries, are sufficient for all but the most formal texts. See also justification."

Output in PDF:
"The details are complex and language- dependent(...)"

[example.pdf](https://github.com/bpampuch/pdfmake/files/1987791/example.pdf)

**Comment by hobbsi** [comment]
I could recreate it in the playground with this:

`var dd = {
    pageSize: 'A5',
	content: [
		{
			text: 'This is a header (whole paragraph uses the same header style)\n\n',
			style: 'header'
		},
		{
			text: [
				'The details are complex and language-dependent, longwordtosimulatetheeffect orthographic and typesetting practices. Hyphenation algorithms, when employed in concert with dictionaries, are sufficient for all but the most formal texts. See also justification.\n'
			]
		}
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true
		},
		bigger: {
			fontSize: 15,
			italics: true
		}
	},
    defaultStyle: {
      alignment: 'justify',
      fontSize: 10.5
    }
}`

**Comment by hobbsi** [comment]
I found a solution this by adding

`if (word[word.length-1] === '-') continue;`

 at function splitWords(text, noWrap)

But this might break end of line hyphenation...

**Comment by liborm85** [comment]
Minus and hyphen is breakable character, this is the correct behavior.
For nonbreaking character you can use [NON-BREAKING HYPHEN](https://www.fileformat.info/info/unicode/char/2011/index.htm), example:

```js
var dd = {
    pageSize: 'A5',
	content: [
		{
			text: 'This is a header (whole paragraph uses the same header style)\n\n',
			style: 'header'
		},
		{
			text: [
				'The details are complex and language\u2011dependent, longwordtosimulatetheeffect orthographic and typesetting practices. Hyphenation algorithms, when employed in concert with dictionaries, are sufficient for all but the most formal texts. See also justification.\n'
			]
		}
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true
		},
		bigger: {
			fontSize: 15,
			italics: true
		}
	},
    defaultStyle: {
      alignment: 'justify',
      fontSize: 10.5
    }
}
```

**Comment by hobbsi** [comment]
I see, I didn't know that. Sorry for the mistake. Thanks.

**Comment by mLuby** [comment]
Hyphen is a *line*-breakable character, but the inserting-of- a-space around it is **not correct**.
>Spaces **are not placed between a hyphen and either of the elements it connects** except when using a suspended or "hanging" hyphen that stands in for a repeated word (e.g., nineteenth- and twentieth-century writers). [-Wikipedia, 3rd sentence](https://en.wikipedia.org/wiki/Hyphen#Use_in_English)

Here's my repro—similar to above.
```js
var dd = {
	content: [{columns: [
		'hypen-ated blah blah blah nextline',
		'spacer text',
		'comment out to see correct',
	]}],
	defaultStyle: {columnGap: 20, alignment: 'justify'},
}
```
><img width="825" alt="Screen Shot 2019-06-24 at 6 29 38 PM" src="https://user-images.githubusercontent.com/2483420/60058479-26be6a80-96ae-11e9-9be9-38451608b359.png">
When the third column is commented out, it's correct:
><img width="833" alt="Screen Shot 2019-06-24 at 6 29 54 PM" src="https://user-images.githubusercontent.com/2483420/60058502-3473f000-96ae-11e9-99e9-6ffd6ad90dd1.png">

P.S. @liborm85 thanks for the non-breaking hyphen `‑` workaround.
