### ISSUE TITLE
Blocked a frame with origin "X" from accessing a cross-origin frame.

### ISSUE THREAD

**Issue by abhibly** [bpampuch/pdfmake#1373]
Hello. I have an ionic3 app which contains a iframe to display the pdf. 
I have an iframe in my html file like this
`<iframe id="loyaltyBadge" width="100%" height="200" name="loyaltyBadge"></iframe>`
I use the following code to display my pdf in iframe
```js
OpenPDF() {
    var dd = {
      content: [
        'First paragraph',
        'Another paragraph'
      ]
    }
    const pdfDocGenerator = pdfMake.createPdf(dd);
    pdfDocGenerator.getDataUrl((dataUrl) => {
      const targetElement: any = document.getElementById('loyaltyBadge');
      targetElement.src = dataUrl;
    });
  }
```

The pdf is display in iframe correctly.I need to print the content in iframe by opening a dialog in same window.For that i have the following code like this,
```js
PrintPDF() {
    window.frames['loyaltyBadge'].focus();
    window.frames['loyaltyBadge'].print();
}
```
When the event is fired i am getting an error like this `Blocked a frame with origin "x" from accessing a cross-origin frame.` 
I have made a demo here which demonstrates the example here https://stackblitz.com/edit/ionic-flhhwm?file=pages%2Fhome%2Fhome.html.
Steps to replicate the issue:
1.Click on Load Pdf Button
2.Click on Print Pdf Button
Can somebody please tell me how can print the content in my iframe.

**Comment by liborm85** [comment]
This issue is not related to pdfmake.
It's more about how to print frame in ionic3, try ask on ionic support/forum.

pdfmake library have `download`, `open` and `print` for relevant actions.
