### ISSUE TITLE
scroll does not uppear when noWrap:true if there are more columns i.e 20 

### ISSUE THREAD

**Issue by jayeshsheta** [bpampuch/pdfmake#1379]
scroll does not uppear when noWrap:true if there are more columns i.e 20 

{
			style: 'tableExample',
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22'],
					['One value goes here', 'Another one here', 'OK?','4','5','6','7','8','9','10','11','12','13','14','15','16','17','18','19','20','21','22']
				]
			}
		},

**Comment by liborm85** [comment]
What do you mean "scroll"?

**Comment by jayeshsheta** [comment]
horizontal scroll in pdf document

**Comment by liborm85** [comment]
Pdf document is printable document on paper, scrolling is not supported.
