### ISSUE TITLE
Insert docDefinition into DDBB

### ISSUE THREAD

**Issue by onbermejo** [bpampuch/pdfmake#138]
I need to insert a docDefinition in a field of a DDBB.
How could I convert a docDefinition to a string?

i am doing a JSON.stringify(docDefinition); in Javascript but when I do it, I lose header and layout.
I attach docDefinition and table:
table: http://textuploader.com/onco
docDefinition: http://textuploader.com/onc4

Thanks!

**Comment by jthoenes** [comment]
Functions cannot be printed using ``JSON.stringify``. That's not a pdfmake issue.
