### ISSUE TITLE
Webpack 4 issue ? 

### ISSUE THREAD

**Issue by no-more** [bpampuch/pdfmake#1380]
Hello,

I'm not sure if it's related but since I switched to webpack 4 I can't make mademake to work anymore.

It looks like #910 but I have already tested all suggested solutions with no luck (it was working before with those same solutions)

Does anyone have the same issue or any clue on how to solve this please ? 

Thanks a lot.

**Comment by no-more** [comment]
Quite strangely I found a workaround.

In previous version I used to import pdfmake and the font file in the vendor file and then import pdfmake where I use it without having to reimport the fonts.
With webpack 4 I have to import font every time I import pdfmake to fix this issue.

I'll mark this as closed but the behavior is still quite strange.

**Comment by CarlosAzocar** [comment]
@no-more Your solution: example please. I have same problem!

**Comment by no-more** [comment]
In the end the issue was a bad configuration of the webpack config file (in my case at least).
With webpack 4 previous chunk plugin is integrated and requires a new configuration to work correctly. If not correctly done each chunk file contains all the code and imports are not shared any more which explain why my pdfmake configuration done in my vendor.js file is not working in my main.js file.

I don't know if you have the same issue but I hope that could help.
