### ISSUE TITLE
Custom bold font doesn't work

### ISSUE THREAD

**Issue by oursonvie** [bpampuch/pdfmake#1387]
I followed the instruction on making my own vfs_fonts.js file
I added two Chinese font one for normal another one for bold

`pdfMake.fonts = {
     msyh: {
          normal: 'msyh.ttf',
          bold: 'msyh_bold.ttf',
          italics: 'msyh.ttf',
          bolditalics: 'msyh.ttf'
        }
    }`

It seems I set the fonts currently

defaultStyle is set as following

`defaultStyle: {
      font: 'msyh',
      fontSize: 10
    },`

The wired thing is when I put bold:true in defaultStyle, it works
but when I put it in my content the bold options seems never work
So Im pretty sure the font is loaded however the inline bold just refuse to work, any idea?

**Comment by Wabbala** [comment]
Tonny, please provide minimal doc definition that works on the playground.

**Comment by remotealex** [comment]
I'm experiencing this exact issue! @oursonvie did you figure it out?

**Comment by oallouch** [comment]
+1

**Comment by jaranin-b** [comment]
++
