### ISSUE TITLE
glup buildFonts 

### ISSUE THREAD

**Issue by sajid9** [bpampuch/pdfmake#1391]
glup buildFonts  this command does not work

**Comment by sajid9** [comment]
i am using mean.js in which i use pdfMake to generate pdf it workes fine i know i wanna use custom font i make example/fonts folder and i type this command buildFonts but its not work

**Comment by liborm85** [comment]
You probably do not have `gulp` installed. You can install by command `npm install`  in pdfmake folder. ([see](https://github.com/bpampuch/pdfmake#building-from-sources))
