### ISSUE TITLE
Table cell padding and layout: noBorders

### ISSUE THREAD

**Issue by myUsernamesTaken** [bpampuch/pdfmake#1394]
Hey, 
is it possible to have a combination of `layout: 'noBorders'` and `              layout: {
                paddingTop: function(i, node) { return 0; },
                paddingBottom: function(i, node) { return 0; },
              }  `? 
Padding set to zero works fine and layout without borders, too. But no padding and no borders together not.

**Comment by myUsernamesTaken** [comment]
Ok, with borders: [false, false, false, false] i can disable the borders. Would be nice to set this in the styles zone to generally disable them.

**Comment by ArulRozario** [comment]
layout: {
        defaultBorder:false,
        paddingLeft: function (i, node) { return 1; },
        paddingRight: function (i, node) { return 1; },
        paddingTop: function (i, node) { return 5; },
        paddingBottom: function (i, node) { return 5; },
      }
works for me
