### ISSUE TITLE
Customization of table borders

### ISSUE THREAD

**Issue by meghnad-globalids** [bpampuch/pdfmake#1396]
Is there anyway to set table border colour and opacity?

**Comment by stefanomozart** [comment]
Use custom hLineColor & vLineColor functions in the layout definition. There is an example in the "Tables" tab in the [playground](http://pdfmake.org/playground.html):
`
{
	table {
		(table definition)
	}, 
	layout: {
		fillColor: function (i, node) {
			return (i % 2 === 0)) ? '#fafafe' : null;
		},
		hLineColor: function (i, node) {
			return (i === 0 || i === node.table.body.length) ? null : '#cdcddd';
		},
		vLineColor: function(i, node) {
			return '#ff1f1fe';
		}
	}
}
`
