### ISSUE TITLE
Words are broken when text is wrapped around the boundary of table

### ISSUE THREAD

**Issue by OwaisQureshi** [bpampuch/pdfmake#1397]
Words are broken when text is wrapped around the boundary of table.

![image](https://user-images.githubusercontent.com/6282079/41381300-4fd22d40-6f35-11e8-8899-5022215822ef.png)

Code:
`body: [
  [
    { text: 'Academic Status:',  bold: true  },
    { text: jQuery('#dtLTREQ_ACC_LOAD_INTENT_OCONV').val(),  alignment: 'center' },
    { text: 'Minimum Hours of Instruction Per Week:', bold: true },
    { text: '15 hours', alignment: 'center' },
    { text: 'Level of Study:', bold: true },
    { text: "Bachelor's Degree", alignment: 'center' },
    { text: 'Type of Training Program:', bold: true },
    { text: 'Academic', alignment: 'center' },
    { text: 'Exchange Program:', bold: true },
    { text: 'No', alignment: 'center' }
  ],
  [
    { text: 'Estimated Tuition Fee for the First Academic Year:',  bold: true,colSpan: 2  },
    {  },
    { text: getTextObjectWithLinks('', EstTuitionFee, ''), colSpan: 8 },{}, {}, {}, {}, {}, {}, {}
  ],
]`

**Comment by liborm85** [comment]
I do not know how to reproduce, because this example works on playground ok:
```js
var dd = {
	content: [
		{
			table: {
            body: [
		        [
		            { text: 'Academic Status:', bold: true }, 
		            { text: 'XXX Text XXX', alignment: 'center' },
		            { text: 'Minimum Hours of Instruction Per Week:', bold: true },
		            { text: '15 hours', alignment: 'center' },
		            { text: 'Level of Study:', bold: true },
		            { text: "Bachelor's Degree", alignment: 'center' },
		            { text: 'Type of Training Program:', bold: true },
		            { text: 'Academic', alignment: 'center' },
		            { text: 'Exchange Program:', bold: true },
		            { text: 'No', alignment: 'center' }
		          ], 
		          [ 
		              { text: 'Estimated Tuition Fee for the First Academic Year:', bold: true,colSpan: 2 },
		              { },
		              { text: 'XXX Text XXX', colSpan: 8 },
		              {},
		              {},
		              {},
		              {},
		              {},
		              {},
		              {}
		              ],
		          ]
			}
		},
	]
	
}
```

**Comment by OwaisQureshi** [comment]
It's really weird its working fine on my machine, but the words are broken when they are wrapped that happens on the page when the page is served through server, although I'm using js and its's executed in the browser, the results should be consistent !
I'm trying to duplicate the issue on my local machine.

**Comment by OwaisQureshi** [comment]
I removed the protoype.js as it was no longer needed in the project and it started working just fine, if anyone has similar issue also try to update prototype.js
