### ISSUE TITLE
Header does not accept multiple lines/paragraphs

### ISSUE THREAD

**Issue by stefanomozart** [bpampuch/pdfmake#1399]
Hi,

I am trying to create simple report. I need the name of the organization, the name of the system and the name of the report printed in each page header.

I am using the following code, but the result is that only the first line/paragraph (with "Company Name") is printed:

	header: {
		columns: [
			{
				image: 'logo',
				fit: [80, 70],
				width: 90,
			},
			{
				stack: [
					{
						text: "Company Name",
						fontSize: 18
					},
					'System X'
					'Report Y'
				],
				width: '*'
			}
		],
		margin: [15, 15]
	}

I don't know if this is a bug (and headers are supposed to print multiple lines) or a feature request. But certainly, This functionality would be greatly appreciated.

**Comment by liborm85** [comment]
Increase values in `pageMargins`, see [readme](https://github.com/bpampuch/pdfmake#page-dimensions-orientation-and-margins).

**Comment by stefanomozart** [comment]
Works like a charm! Thanks

**Comment by ArulRozario** [comment]
Yes. Adjusting margin works like a charm
