### ISSUE TITLE
Create pdf can't use open method 

### ISSUE THREAD

**Issue by chayakornwc** [bpampuch/pdfmake#1403]
When i use open method was new blank page, then this page was closed

**Comment by Wabbala** [comment]
Have you checked the ad-block options?

**Comment by chayakornwc** [comment]
yes i do.

**Comment by liborm85** [comment]
Which browser do you use? See [supported browsers](https://github.com/bpampuch/pdfmake/issues/800).

**Comment by chayakornwc** [comment]
Thanks, this case is my browser  do not supported
