### ISSUE TITLE
Font not found after update from 0.1.33 to 0.1.36

### ISSUE THREAD

**Issue by FlorianLeitgeb** [bpampuch/pdfmake#1404]
I made an update today and since then, my fonts are not found anymore by the browser. My app however, still compiles fine.

So I changed in my package.json from "^0.1.33" to "^0.1.36" and made a npm i.
Everything compiled just fine.
Now when I start my export, I get this error:
`pdfmake.min.js:2 Uncaught File 'Arial-Bold.ttf' not found in virtual file system`

I am using a custom font, which I compiled with your tutorial into a `vfs_fonts.js` and included it in my project. This was working fine for a couple of weeks/months now.

First I make my imports:
`import * as pdfMake from "pdfmake/build/pdfmake.min.js";
import * as pdfFonts from "pdfmake/build/vfs_fonts.js";`

Then I set my variables in my `PdfExporter` class:
`    pdfMake.fonts = {
      Arial: {
        normal: "Arial-Regular.ttf",
        bold: "Arial-Bold.ttf",
      },
    };`

I am not using any italics, so this is fine for me.

Then I set the variable for pdfMake:
`pdfMake.vfs = pdfFonts.pdfMake.vfs;`

And here is an example of my usage in code for default styling:
`  private static createDefaultStyles(): object {
    return {
      fontSize: 8,
      bold: false,
      color: "black",
      font: "Arial",
    };
  }`

Do you have any idea what is causing the bug? Maybe it is not about the version update, but this is the only big thing that changed today.

**Comment by Binghammer** [comment]
I just started using the project today, and `^0.1.36` is the version I started with. I am seeing this problem also.

**Comment by Binghammer** [comment]
This solved my issue for me: https://github.com/bpampuch/pdfmake/issues/1312

**Comment by liborm85** [comment]
What is returned from: `console.log(pdfMake.vfs);` ? Array object where is one of key `Arial-Bold.ttf` ?

And from `console.log(pdfMake.vfs["Arial-Bold.ttf"]);` is returned some base64 text, or `undefined`?

**Comment by FlorianLeitgeb** [comment]
Sorry, but I was on vacation. Had to copy back the custom font file into my node_module folder from pdfmake. Totally forgot that I have to do this. It would be great to have a config object, that I can pass to pdfmake when generating a pdf from object. where I can specify the location for my fonts.
