### ISSUE TITLE
I need a row with 2 columns

### ISSUE THREAD

**Issue by misterflorescu** [bpampuch/pdfmake#1405]
I use pdfMake to generate CV-s from a database. I have multiple field that i classified with 2 classes titleStyle (the style of the title: job, adress, etc.) and anotherStyle (the style for the value of fields: Engineer, NY str.., etc). I'll show you the code here and i hope that somebody can help. I don't understand how to create a pdf where the titleStyle will be in left and anotherStyle in right. Anyone have an ideea ? 

`styles:
                            {
                        titleField: {
                            alignment: 'left',
                            width: '40%',
                            fontSize: 15,
                            bold: true,
                            backgroundColor: '#dfe4ea',

                        },
                        anotherStyle: {
                            width: '40%',
                            alignment: 'right',
                            italic: true,
                            paddingBottom: 5,
                            backgroundColor: '#f1f2f6',
                        },
                        imageStylePdf: {
                          textAlign: 'center',
                          marginTop: 5,
                          marginBottom: 10,
                        },
                    },`

**Comment by liborm85** [comment]
You can use `table`, see [playground](http://pdfmake.org/playground.html) > _TABLES_
