### ISSUE TITLE
Get page content before generation of new page 

### ISSUE THREAD

**Issue by ArpitKumar2092** [bpampuch/pdfmake#1409]
I am designing an application specific code that uses header  footer and table 
Now the problem is i have to print row count and sum of integer values  columns  in footer 
I can not determine the height of row as it depends upon content for example 

I have 4 columns where first three are integer and last one is a text which is so long that it increases height of that row equivalent to three rows

I there any way to print sum , number of rows , or  get the content of page before it transfers content to next page ....So that i could update footer values

**Comment by BrunoAderaldo** [comment]
I find this in README.md, its help?

> **Dynamically control page breaks, for instance to avoid orphan children**
> 
> A pageBreakBefore function can be specified, which can determine if a page break should be inserted before a node...

```
pageBreakBefore: function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
     return currentNode.headlineLevel === 1 && followingNodesOnPage.length === 0;
  }
```

> If pageBreakBefore returns true, a page break will be added before the currentNode. Current node has the following information attached:

```
{
   id: '<as specified in doc definition>',
   headlineLevel: '<as specified in doc definition>',
   text: '<as specified in doc definition>',
   ul: '<as specified in doc definition>',
   ol: '<as specified in doc definition>',
   table: '<as specified in doc definition>',
   image: '<as specified in doc definition>',
   qr: '<as specified in doc definition>',
   canvas: '<as specified in doc definition>',
   columns: '<as specified in doc definition>',
   style: '<as specified in doc definition>',
   pageOrientation '<as specified in doc definition>',
   pageNumbers: [2, 3], // The pages this element is visible on (e.g. multi-line text could be on more than one page)
   pages: 6, // the total number of pages of this document
   stack: false, // if this is an element which encapsulates multiple sub-objects
   startPosition: {
     pageNumber: 2, // the page this node starts on
     pageOrientation: 'landscape', // the orientation of this page
     left: 60, // the left position
     right: 60, // the right position
     verticalRatio: 0.2, // the ratio of space used vertically in this document (excluding margins)
     horizontalRatio: 0.0  // the ratio of space used horizontally in this document (excluding margins)
   }
}
```
