### ISSUE TITLE
too large data for the Qr format

### ISSUE THREAD

**Issue by mvndr** [bpampuch/pdfmake#1412]
Getting qr code text in dynamic way,
**Example:** 
var longText = $scope.dynmicValue, (DynamicValue like: 1105)
qr: longText, fit: 150, alignment: 'right'

![image](https://user-images.githubusercontent.com/24519082/41837100-6491ac26-7811-11e8-969a-6e956913723d.png)
Any help will be appreciated

**Comment by Wabbala** [comment]
please produce a minimal example that can be used on the playground for
testing purposes. Your example is too short to work with

**Comment by liborm85** [comment]
Your text is too large. QR codes have limited storage capacity, for example alphanumeric string is limited to 4 296 characters (see [wikipedia.org](https://en.wikipedia.org/wiki/QR_code#Storage)).

**Comment by mvndr** [comment]
After struggling for one hour got the solution. Thank @liborm85  for the link, your link help me to reach the root cause. I am posting the solution may help other, who are facing same issue.
**//I had converted the value into string and it work.**
var longText = $scope.dynmicValue.toString();

**Comment by sandesh-bhoir** [comment]
> After struggling for one hour got the solution. Thank @liborm85 for the link, your link help me to reach the root cause. I am posting the solution may help other, who are facing same issue. **//I had converted the value into string and it work.** var longText = $scope.dynmicValue.toString();

I was facing the same issue, but converting it to string didn't worked.
I also checked the length of my string and its 4192 which should work as per @liborm85 
Can you assist here..
