### ISSUE TITLE
Removing border around pdf

### ISSUE THREAD

**Issue by Sujatha-yuvraj** [bpampuch/pdfmake#1415]
Am generating pdf by using pdfmake. PDF generating properly the problem here is it is generating border around the content. i tried to remove them by using layout"'noBorders' and other ways also. but no luck , can anyone sort out this issue. here is my code sample

                   html2canvas(document.getElementById('div2'), {
                    onrendered: function (canvas2) {
                        var data2 = canvas2.toDataURL();
                        var docDefinition2 = {

                            content: [{  
                                layout: 'noBorders',
                                image: data2, alignment: 'center',
                                fit: [700, 700], margin: [40, 0, 0, 0], 
                                pageBreak: 'after'
                            }]
                        };                         
                        pdfMake.createPdf(docDefinition2).download('batch5df885f0-6e16-453e-83cb-b09d2e990bad.pdf');    }
                });

**Comment by liborm85** [comment]
You have no borders in docDefinition, probably border is from canvas. Remove border in canvas.

**Comment by Sujatha-yuvraj** [comment]
Can you please tell me how to remove the border in canvas

**Comment by liborm85** [comment]
Try change css styles in `div2` element by javascript. But this issue has no connection to pdfmake library, try to ask on https://stackoverflow.com.
