### ISSUE TITLE
Custom font rendered differently across browsers

### ISSUE THREAD

**Issue by dionisisZyg** [bpampuch/pdfmake#1417]
Hello,

Firstly i would like to thank you for the awesome project.

I came across with the following issue. I added my custom font as described in the documentation, but the font is not rendered correctly in google chrome. The IE, firefox and Microsoft edge are rendering the font as expected. Is there something that can be done about it? Is it possible to somehow use a fallback font? Or maybe do I have to detect the browser through JavaScript to handle the case accordingly? 

Thanks.

**Comment by liborm85** [comment]
Pdf should be generated in all browsers the same.
Some example for reproduce issue? aAd can you attach these different pdf files?

**Comment by liborm85** [comment]
Yes, the generated pdf file is the same across all browsers. The problem will be in viewers, that Google Chrome is only simplified viewer probably renders pdf incorrectly.
pdfmake uses [pdfkit library](https://github.com/devongovett/pdfkit) for generating pdf, you can try ask  [there](https://github.com/devongovett/pdfkit/issues) whether is possible solve this Google Chrome bug in generating pdf by pdfkit.
