### ISSUE TITLE
Underline in a justified text

### ISSUE THREAD

**Issue by Beryllo** [bpampuch/pdfmake#1418]
When using underline in a text with the 'justify' alignment, some of the text is not correctly underlined, as if the underline property only recognize the original left alignment, as show in the image below.
![tela](https://user-images.githubusercontent.com/40700741/42107910-5e8fe6b6-7baf-11e8-95e6-e06069f4c860.png)

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/92e511f818f78c5dd9c58bfccc5ce48ec8be2ddc.
