### ISSUE TITLE
Draw unicode characters 

### ISSUE THREAD

**Issue by webDeveloperAle** [bpampuch/pdfmake#142]
I need insert in to a column unicode characters like Ʉ or Ӂ, but are not drawing in PDF. For exmpler if I want to print  "Ʉ  թ✖✖✖✖✖✖✖✖✖✖✖" into the pdf, spaces for those chareacters are occupied but the characters can not display.  Any idea?

Thanks

**Comment by jthoenes** [comment]
You need to use a font that supports these unicode characters.

See https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
