### ISSUE TITLE
Send pdf data to iOS device using nodejs

### ISSUE THREAD

**Issue by chriseenberg** [bpampuch/pdfmake#1420]
Hi guys.

I've recently picked up this library, and it's going well!

There is - however - a slight issue, in which, after i've created a pdf, i want to send it to the client. I've tried the buffer and base64 method, but the app expects a pdf binary format - which is why it does not render on the device.

How might i achieve this through nodejs ( firebase functions ) ?

I'm far from an expert in data types, so i'm having difficulties imagining what may work. I've searched the internet thoroughly but without luck.

Can anyone help here?

Kind regards Chris.

**Comment by chriseenberg** [comment]
I've fixed it by adding this line for anyone else searching this answer:
`response.send(new Buffer(doc, 'binary'))`

**Comment by aachman** [comment]
I want to do it in server side , please refer my issue #1419.
