### ISSUE TITLE
Passing a string array to ul modifies data

### ISSUE THREAD

**Issue by BeatriceThalo** [bpampuch/pdfmake#1423]
I am passing a string array to an unordered list element in a definition. The array is unexpectedly getting modified by pdfmake, when no modifications would be expected.
The first way to reproduce is to use the same array twice in the definition, which only shows the first ul correctly in the pdf.

```javascript
var arr = ['hi', 'there'];
var arr2 = ['hi2', 'there2'];
var dd = {
  content: [
    {
      style: 'tableExample',
        table: {
          body: [
            ['Column 1'],

            [
              {
                stack: [
                  'Let\'s try an unordered list',
                  {
                    ul: arr
                  }
                ]
              },
              {
                stack: [
                  'Let\'s try an unordered list',
                  {
                    ul: arr // arr2 displays correctly but not arr
                  }
                ]
              }
            ]

          ]
        }
      }
    ],
    styles: {
      tableExample: {
        margin: [0, 5, 0, 15]
      }
    }	
}
console.log(arr) // prints ["hi", "there"]
```
A second way which sporadically reproduces in the playground tables definition and seems to reliably reproduce in my project's data records, is when the console shows pdf-schema-looking objects instead of the original strings:
```javascript
Array(2)
0: {text: "hi", _margin: null, _inlines: Array(0), _minWidth: 9.521484375, _maxWidth: 9.521484375, …}
1: {text: "there", _margin: null, _inlines: Array(0), _minWidth: 27.193359375, _maxWidth: 27.193359375, …}
length: 2
__proto__: Array(0)
```

**Comment by liborm85** [comment]
Can not be multiple references to same object/variable (see issue: https://github.com/bpampuch/pdfmake/issues/465).

Yes, pdfmake modifies docDefinition data during generating PDF file.

**Comment by BeatriceThalo** [comment]
Ah, thank you. I didn't see the differently worded dup issue already.
