### ISSUE TITLE
How to dynamically inject list in the pdf

### ISSUE THREAD

**Issue by postmeback** [bpampuch/pdfmake#1424]
Hi,

I have a bunch of question and answers, which i want to print in my excel file. In the pdf file it looks like something the below:

![q a_1](https://user-images.githubusercontent.com/14862687/42316818-bc6b065e-8018-11e8-9a5d-5e43a9d8a6da.PNG)

Now, whenever the user says **no** to Q.1 , a dependent question appears. If it is **yes**, then the question will not appear. In this way i want to dynamically inject question and answers depending on user's preference.

The backend content looks something like this :

     `{
      text: '\n1)' + this.questionService.questions.Questions['sub-section'][0].questions[0].details['question- 
      alt-description'] + '\n', 
      bold: true
            },

            {
              style: 'tableExample',
              table: {
                style: 'table1',
                widths: ['*'],
                body: [
               [{ text :
                    this.questionService.qanda.find(x => x.ActId == 647).ActVal == '' ?
                     '\n' : this.questionService.qanda.find(x => x.ActId == 647).ActVal === 'No' ? 
                   'This should print the dependent question' : 'This should not print the dependent question' ,
                 }]
                ]
              }
          },
          {
            text:
                    '\n2)' + this.questionService.questions.Questions['sub-section'] 
                     [0].questions[0].details.MoreActionFalse[0]['question-description'],

                     bold: true, alignment: 'justify'
                     },
                    {
                     style: 'tableExample',
                     table: {
                     style: 'table1',
                   widths: ['*'],
                    body: [
                   [{ text :
                     this.questionService.questions.Questions['sub-section'] 
                    [0].questions[0].details.MoreActionFalse[0].answer
                      == '' ? '\n' : this.questionService.questions.Questions['sub-section'] 
                    [0].questions[0].details.MoreActionFalse[0].answer, 

                    bold: true}]
                      ]
                      }
                    },`

I want to inject the second question dynamically, when 1st question's response is **No**.

What i have tried is below :+1: 

                   `function builddependentquestion_1() {
                     const body = [];
                     body.push([{
                             text : '2nd question',
                            rowSpan: 1,
                           fillColor: '#ffffff',
                           bold: true,
                          border: [false, false, false, false]}
                        }
                     ]);

                   return body;
                 }

                  function tabledependentquestion_1() {
                  return {
                       table: {
                           body: builddependentquestion_1()
                            }
                          };
                      }`

Then i have called the function in the ternary operator above. But, it didn't work. 

Can anybody help here ?

If more clarity is required, please let me know, thanks in advance :)

**Comment by liborm85** [comment]
Simple example for dynamically creating questions with anwsers:
```js
function addQuestion(questionText, answers) {
    contentData.push({text: questionText});
    
    var bodyData = [];
    answers.forEach(function(answer) {
        bodyData.push([{text: answer}]);
    });
    
    contentData.push({table: {body: bodyData}});
    contentData.push({text: ' '});
}

var contentData = [];

addQuestion('Question 1', ['Answer 1A', 'Answer 1B', 'Answer 1C']);
addQuestion('Question 2', ['Answer 2A', 'Answer 2B', 'Answer 2C']);

var dd = {
	content: contentData
};
```

Variables for questions and answers for `addQuestion` function  you can fill from you data storage.

**Comment by postmeback** [comment]
Using ternary operator i have fixed the issue. Anyway thanks for the help.
