### ISSUE TITLE
<br> tag & ponctuation mark

### ISSUE THREAD

**Issue by eelaapcc** [bpampuch/pdfmake#1426]
Hello,
I am using PDFMake to create a pdf in my wordpress website, where I use ACF to provide custom fields. My trouble is PDFMake doesn't support the ponctuation mark ' (apostrophe) nor the <br> tag (ACF automatically converts a line break into the <br> tag when you use the enter key inside the field).
My question, therefore, is how can I work around this limitation ? since I really need to be able to write ' and line breaks inside my fields.
Clarification : I do not write the text in the pdfmake code, I call the fields dynamically. For instance : `{text: '<?php the_field('ACF1', $ID1); ?>', style: 'texte'}`
Thank you !

**Comment by eelaapcc** [comment]
sorry if I was not clear, English is not my first language ;)
I do not write the text in the content part of the code, like you did. instead, I call the text from the ACF field using php code only (ex: `{text: '<?php the_field('ACF1', $ID1); ?>', style: 'texte'}`).
Therefore, when I type on the wordpress admin interface and use an apostrophe or when I use the enter key to make a line break, it somehow messes up with PDFmake which doesn't work anymore. So far, it only works when I delete all the apostrophes and linebreaks from the text I write in the ACF field which is useless because the text becomes unclear.

**Comment by liborm85** [comment]
I am also not a native speaker ;-)

It doesn't relate to pdfmake but to escaping in php.
Use [addslashes](http://php.net/manual/en/function.addslashes.php) for escape text:
`{text: '<?php addslashes(the_field('ACF1', $ID1)); ?>', style: 'texte'}`

And for new line [str_replace](http://php.net/manual/en/function.str-replace.php) to replace new line to character \n, something like:
 `$replacedText = str_replace("\n", "\\n", $sourceText);`

Or try google for other escape solutions in php.

**Comment by eelaapcc** [comment]
thank you for your help ! I did not know about escaping in php, sorry...
the solution offered does not work for now, I am reading about it and trying to find a solution. maybe on ACF end ?
anyways, thanks a lot !
