### ISSUE TITLE
Tables and columns create excess empty space at page bottom if page height is set to 'auto'

### ISSUE THREAD

**Issue by toschwa** [bpampuch/pdfmake#1428]
I noticed that if you set the page height to 'auto' and fill content with columns or tables, the page will have excess empty space at the bottom.
You can test this in the PDFMake playground using:
```
var dd = {
    pageSize: {height: 'auto', width: 562},
	content: [
			{
			table: {
				body: [
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor'],
					['Lorem', 'Ipsum', 'Dolor']
				]
			}
		},
	],
}
```
and adding or removing entries from the table.

**Comment by toschwa** [comment]
I'm guessing the bug comes from the 'item.item.getHeight()' function, which is called in the 'printer.js' @ line 165:
```
[...]
function calculatePageHeight(pages, margins) {
	function getItemHeight(item) {
		if (isFunction(item.item.getHeight)) {
			return item.item.getHeight();
[...]
```
This returns the same height for every item, no matter how much text is inside the item.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/8924fb55a285d760bb311714746351f289fcde5f.
