### ISSUE TITLE
Add loading of SVG image

### ISSUE THREAD

**Issue by marcusy3k** [bpampuch/pdfmake#1429]
Hi,
Possible to add a feature to allow loading svg images when creating pdf file? really hope it is supported because we want to include barcode(s) in pdf file, Normally, barcode is generated as SVG image by external function at runtime (e.g. JsBarcode -- https://github.com/lindell/JsBarcode ).

Perhaps I mis-understand SVG things... JsBarcode could write to HTML as:

`<img id="bcimg" src="data:image/png;base64,......">`

or

`<svg id="barcode" width="288px" height="59px" x="0px" y="0px" viewBox="0 0 288 59" xmlns="http://www.w3.org/2000/svg" version="1.1" style="transform: translate(0,0)"><rect x="0" y="0" width="288" height="59" style="fill:#ffffff;"></rect><g transform="translate(10, 5)" style="fill:#000000;"><rect x="0" y="0" width="4" height="30"></rect><rect x="6" y="0" width="2" height="30"></rect> ... <text style="font: 12px monospace" text-anchor="middle" x="134" y="44">AAA1234567890</text></g></svg>`

The barcode could be shown on web page, but how could I add it to PDF ?

I could not use toDataURL() because the output barcode image would be blur (too low resolutions), it is not suitable for printing.

I know we could use Path as below, but it seems it do Stroke instead of Fill, so it is not suitable for barcode too... (and I don't know how to convert svg image to Path string.)
` {
       canvas : [
          { type: 'path', d: 'M 10 10 l 100 0 l 0 100 l -100 0 Z' }
        ]
   }
 `

As an alternative, I know pdfmake could generate qr code, if it could also generate Code128 barcode, it could help.

**Comment by liborm85** [comment]
JsBarcode output extract as image (you can use this: https://stackoverflow.com/questions/35637298/generate-barcode-from-text-and-convert-it-to-base64/35703395#35703395) and in pdfmake insert as image.

**Comment by marcusy3k** [comment]
Thanks, I could not use toDataURL() because it output image as 96dpi only, it is not suitable for printing.

So far, I use another way to draw the png with higher resolution, and thanks again for telling me how to use Path with Fill instead of Stroke, I guess using Path could have much better result, I will try it if I have time. ^_^
