### ISSUE TITLE
playground font embedding

### ISSUE THREAD

**Issue by lastlink** [bpampuch/pdfmake#1430]
How do we change which fonts are available when running the playground locally on our own machines?

**Comment by liborm85** [comment]
Which fonts are availabe is defined here: https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js#L19-L26

**Comment by lastlink** [comment]
In `build/pdfmake.js`

There is this variable
```js
STANDARD_FONTS = {
      "Courier": function() {
        return fs.readFileSync(__dirname + "/../font/data/Courier.afm", 'utf8');
...
  }
```

However, we can't use `Courier` in the playground

```js
 defaultStyle:{
        font: 'Courier'
    },  
```

In web console
**Uncaught Error: Font '' in style 'normal' is not defined in the font section of the document definition.**

**Comment by liborm85** [comment]
Use real font from font file.
