### ISSUE TITLE
Generate PDF from SVG with embedded custom @Fontface don't render text on first download.

### ISSUE THREAD

**Issue by danyfu** [bpampuch/pdfmake#1431]
Hi,

I'm trying to generate a pdf from SVG, the SVG has html content contained in foreignObject element.
To generate the pdf I convert the SVG to a canvas and embed that image as a base64 png dataURI.

To use a custom font I embed a ttf font converted to an base64 data called [Cabin](https://fonts.google.com/specimen/Cabin) inside my SVG, generate the pdf in Chrome, Opera, Firefox and Edge Browser has no problems but in Safari for strange reason the first time I download doesn't render the text, but in the second download it render the text.
Here's a jsfiddle link that represents this behavior: https://jsfiddle.net/4fyctdr5/4/

Also if I don't embed a custom font it works fine, but it sets the Times New Roman by default.

Result:
![screen shot 2018-07-11 at 1 33 41 pm](https://user-images.githubusercontent.com/9112457/42597888-3f3b938c-850f-11e8-8d06-dba669f76fba.png)

Expected:
<img width="1247" alt="screen shot 2018-07-11 at 1 36 12 pm" src="https://user-images.githubusercontent.com/9112457/42597942-7182bea6-850f-11e8-87d2-d2b22f1a8691.png">

Tested on Safari Version 11.1.1 (12605.2.8)

**Comment by liborm85** [comment]
How does it relate to pdfmake?
You only from canvas pass png image to pdfmake. Others are some canvas generating that is not related to pdfmake.
