### ISSUE TITLE
QR codes don't add any additional page height if page height is set to 'auto'

### ISSUE THREAD

**Issue by toschwa** [bpampuch/pdfmake#1435]
The calculation for 'auto' page height seems to be broken for QR Codes aswell.
QR codes seem to have an item height of 0, so no space will be added for them at all.
You can test this in the PDFMake playground using:
```
var dd = {
    pageSize: { width: 562, height: 'auto' },
	content: [
        {qr: 'text', alignment: 'center'}
	]
}
```
If you remove the QR code the page will still have the same height.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/8924fb55a285d760bb311714746351f289fcde5f.
