### ISSUE TITLE
How to Fill SVG Path instead of Stroke?

### ISSUE THREAD

**Issue by marcusy3k** [bpampuch/pdfmake#1436]
Hi,
I have tried to use SVG Path as below, but it seems it do Stroke instead of Fill, how can I set it to Fill ?

{ canvas : [ { type: 'path', d: 'M 10 10 l 100 0 l 0 100 l -100 0 Z' } ] }

Thanks.

**Comment by liborm85** [comment]
Fill can you apply like this:
```
{ canvas : [ { type: 'path', d: 'M 10 10 l 100 0 l 0 100 l -100 0 Z', color: 'red'} ] }
```

**Comment by marcusy3k** [comment]
Thanks, it works!  I've tried 'Color' instead of 'color'...
