### ISSUE TITLE
Multiple levels in ToC?

### ISSUE THREAD

**Issue by karatekaneen** [bpampuch/pdfmake#1437]
Is it possible somehow to get header and subheaders on different levels in the table of contents?
Something like:

Table of contents:
Introduction
    - Background
    - About the project
    - About the authors
Abstract
...

Been looking around and trying with the code but can't get it to work.

**Comment by naxmefy** [comment]
i hope i understand you...

if your headers make use of a specific style you can iterate over the contents and just grep them together to create a ToC

**Comment by karatekaneen** [comment]
Sorry but I now see I wasn't very clear. 
I'm generating reports and I've got some major headers things like introduction and summary and so on. And within these major headers i've got subheaders so I want that the subheaders get indented one level. Attaching pic from word to show how I mean.
![ahr0cdovl3d3dy5syxb0b3btywcuy29tl2ltywdlcy93cc9wdxjjac1hcgkvaw5jb250zw50lziwmtuvmtevdg9wlxdvcmqtdgfibgutb2yty29udgvudhmtmjuwedexnc5wbmc](https://user-images.githubusercontent.com/41196840/43313905-a2da0e12-9191-11e8-9964-db1cf048df7e.jpg)

**Comment by liborm85** [comment]
You can use `tocMargin` for indentation. Is also possible to use `tocStyle`.

Example:
```js
var dd = {
	content: [
		{
			toc: {
				title: {text: 'INDEX'},
			}
		},
		{
			text: 'Introduction',
			tocItem: true,
			tocStyle: {bold: true},
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet...',

		{
			text: 'Background',
			tocItem: true,
			tocMargin: [20, 0, 0, 0],
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet...',

		{
			text: 'About the project',
			tocItem: true,
			tocMargin: [20, 0, 0, 0],
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet...',

		{
			text: 'About the authors',
			tocItem: true,
			tocMargin: [20, 0, 0, 0],
			pageBreak: 'before'
		},
		'Lorem ipsum dolor sit amet...',

		{
			text: 'Abstract',
			tocItem: true,
			tocStyle: {bold: true},
			pageBreak: 'before'
		},
	]
}
```

And see [/examples/toc.js](https://github.com/bpampuch/pdfmake/blob/master/examples/toc.js)

**Comment by xuananpham93** [comment]
I want to add the dot in TOC. How can I do that? @karatekaneen

**Comment by cesc1802** [comment]
i also want to add the dot in TOC. anyone can help me ?

**Comment by Padi2312** [comment]
@liborm85  this issue isn't really resolved  ... it only changes the style of the ToC but it hasn't multiple levels like in the image from @karatekaneen .

Also i am looking for the Dot function like @xuananpham93

**Comment by flynnhammonds** [comment]
I have the same requests for more styling options for the TOC.
I ended up using a table cell with the bottom cell displaying a dash underline & utilising 'pageReference' and 'textReference' from the id of the content item.

`
            {
            id: "referenceName1", // custom name 
            text: title, 
            }
`
`customToc(["referenceName1",{id:"referenceName1",childCount: 1}])
`
Here is the custom TOC you can use for a temporary solution

```
export const customToc = (references) => {
  const TocsPerColumn = 10; // Define the maximum number of references per column.
  //const TocsPerColumn = null; //(to display a single column).
  let columns = [];
  if (TocsPerColumn) {
    const columnCount = Math.ceil(references.length / TocsPerColumn);
    for (let i = 0; i < columnCount; i++) {
      columns.push({
        width: "*",
        stack: references
          .slice(i * TocsPerColumn, (i + 1) * TocsPerColumn)
          .map((reference) => {
            return `CustomTocLine(reference);`
          }),
      });
    }
  } else {
    columns = [
      {
        width: "*",
        stack: references.map((reference) => {
          return CustomTocLine(reference);
        }),
      },
    ];
  }
  return columns;
};

const CustomTocLine = (reference) => {
  let childCount = 0;
  if (typeof reference === "object") {
    childCount = reference.childCount || 0;
    reference = reference.id;
  }
  return {
    width: "*",
    margin: [childCount * 10, 0, 0, 0], // Adjust the margin based on the child count.
    table: {
      widths: ["auto", "*", "auto"],
      body: [
        [
          {
            border: [false, false, false, false], // Disable borders.
            textReference: reference, // Use the reference for a page link.
            margin: [0, 0, 0, -5], // Adjust the bottom margin for alignment with TOC dashes.
          },
          {
            border: [false, false, false, true], // Disable all but the bottom border.
            text: "", // Leave the second column blank for the TOC dashes.
            margin: [0, 0, 0, -5], // Adjust the bottom margin for alignment with TOC dashes.
          },
          {
            border: [false, false, false, false], // Disable borders.
            pageReference: reference, // Use the reference for to display page number.
            margin: [-15, 0, -15, -5], //Margins for the pageReference and the bottom margin for alignment with TOC dashes.
          },
        ],
      ],
    },
    //Customised Dashed / Dotted Line for the TOC.
    layout: {
      hLineWidth: function (i, node) {
        return 2; // Set the line width.
      },
      hLineColor: function (i, node) {
        return "white"; // Set the line color.
      },
      hLineStyle: function (i, node) {
        return { dash: { length: 2 } }; // Define a dashed line style for the line.
      },
    },
  };
};

```

**Comment by adamzwasserman** [comment]
@flynnhammonds I would like to use your workaround but am not completely sure how.

Am I going to not use built-in TOC at all, but rather building a stack to use in the content: object?
Also, am I building an array of elements I want in the toc, and the looping through the array, calling customToc on each element in my array, or am I passing the array to the function?
The function parameters `customToc(["referenceName1",{id:"referenceName1",childCount: 1}])` are confusing me. Why does "referenceName1" appear twice? Why is the array made out of a text type followed by an object type?

If these are dumb questions I apologize in advance.

Thank you for any help you can give me.
