### ISSUE TITLE
open() and print() methods no longer working in Chrome or Edge?

### ISSUE THREAD

**Issue by 185driver** [bpampuch/pdfmake#1439]
Within the last few days I've noticed that I can no longer use the `.open()` or `.print()` methods with pdfmake in Chrome or Edge. When executed, a new blank browser tab opens for a moment, then disappears. However, these methods do work when using Firefox. They also don't seem to be working in the pdfmake [playground](http://pdfmake.org/playground.html). Is anyone else noticing this new behavior?

The `.download()` method continues to work normally, however.

**Comment by liborm85** [comment]
You must disable adblock in Chrome, and see [supported browsers](https://github.com/bpampuch/pdfmake/issues/800).

**Comment by Ananyag** [comment]
no its not working in firefox also and, I am using .download() method only but its returning empty Pages

**Comment by 185driver** [comment]
@liborm85 My apologies, I saw your response right away and then forgot to come back and close this issue. You are right, of course, about it being an adblock issue in Chrome and a supported browser issue with Edge. I already knew of the adblock thing and had handled it earlier, but when it cropped up again it didn't occur to me that's what it was again.  All okay now. It's interesting that Edge doesn't play nice with the `open()` and `print()` methods.  That's unfortunate, but I really like using pdfmake. Such a capable plugin for my needs. Wow. Cheers.

**Comment by bvsbharat** [comment]
Getting below error even ad_block was not enabled. 
Not allowed to navigate top frame to data URL:

**Comment by Irfan995** [comment]
Getting same error even if the ad_blocked is disabled
