### ISSUE TITLE
create pdf and then store file in cordova

### ISSUE THREAD

**Issue by padampaddy** [bpampuch/pdfmake#144]
So, I wanted to generate a pdf in my phonegap/cordova application. every thing is fine and i generate and the pdf is created. however when i open it. the text appears as symbols (?,* etc.). Rest the margins and footer and colors are all perfect only the problem is with the text. 

What problem can it be?
Probably the font?

Awesome library by the way. have coded so much in it just to find that it breaks in cordova.. very sad.

**Comment by tjacquin** [comment]
Hey guys, I'm having the exact same issue here. No solution yet?

**Comment by tjacquin** [comment]
So I looked into the issue a bit more and managed to resolve the problem.
I figured that the encoding was the cause of the problem.
At first, I was using the function getBase64 and calling atob() on the callback result which ended up creating a pdf but the encoding of the font was wrong.
Then I used getBuffer(),  converted the buffer to Uint8Array and converted the array to a binary array.
Writing this binary array to the persistent file in Cordova produced a readable PDF.

Here's the code I'm using (I'm using angular):

```javascript
var binaryArray = null;
var currentfileEntry = null;

$scope.docDefinition = {"Put your scope definition here"};

function fail(error) {
	console.log(error.code);
};

function gotFS(fileSystem) {
	var fileName = "your-file.pdf";
	fileSystem.root.getFile(fileName, {
	  create: true,
	  exclusive: false
	}, gotFileEntry, fail);
}

function gotFileEntry(fileEntry) {
	currentfileEntry = fileEntry;
	fileEntry.createWriter(gotFileWriter, fail);
}

function gotFileWriter(writer) {
    writer.onwrite = function (evt) {
      $scope.downloading = false;
      alert("The file was written successfully");
      window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, gotFSforRead, fail);
    }
    writer.write(binaryArray);
}

$scope.download = function () {
    if (!window.cordova) {
      pdfMake.createPdf($scope.docDefinition).open();
    } else {
      pdfMake.createPdf($scope.docDefinition).getBuffer(function (buffer) {
        var utf8 = new Uint8Array(buffer); // Convert to UTF-8...                
        binaryArray = utf8.buffer; // Convert to Binary...
        window.requestFileSystem(LocalFileSystem.PERSISTENT, 0, gotFS, fail);
      });
    }
}
```
I hope this will be helpful to other developers facing the same issue.

**Comment by inceptivetech** [comment]
@tjacquin , Do I require to specify any dependancy for writing pdf file in filesystem.

regards,
Suhas

**Comment by tjacquin** [comment]
As you can see in the $scope.download function, the behavior is different whether you are using this code within a browser or a Cordova app.

In a browser, the open() function will pop a base64 encoded PDF in a new tab. You don't need to add any dependency.

In a Cordova app, you need to write the PDF to the file system. As of Cordova 3.0, you need to include the file plugin:
`cordova plugin add org.apache.cordova.file`

Here's the reference on how to use the file API: http://docs.phonegap.com/en/edge/cordova_file_file.md.html

Hope that helps,
Thomas

**Comment by nantoka69** [comment]
@tjacquin,

thanks a lot for this hint. Converting the input parameter of getBuffer() via  Uint8Array to a binary array turned a strange looking into a correct PDF for me as well. I tried a lot of other things with no success. 

Btw. I tested it with Cordova 4.3.0 under Android with Android SDK 22.

**Comment by shallsaur** [comment]
@tjacquin 

Thanks for the help. Managed to get it to work perfectly.

**Comment by vikassaxena** [comment]
hello friends i am using this code but i got  error  Reference Error : **pdfMake is not defined**

anyone can help

**Comment by tjacquin** [comment]
@vikassaxena 
Did you reference the javascript file in the <head> section of your html page?
<script src='build/pdfmake.min.js'></script>

**Comment by vinitbhu06** [comment]
Thanks @tjacquin for the code.

**Comment by zurieelrdz** [comment]
@shallsaur 

Hello

Just a question. I'm using your code to generate the file, but it don't work, It only put on console App Directory Initialized and that's all. Can you help me? heres my code.

var folder = "downloads";
        var appDirectory;
            window.requestFileSystem(LocalFileSystem.PERSISTENT, 1, function(fileSys){
                      fileSys.root.getDirectory(folder, { create: true, exclusive: false }, function (directory) {
                        appDirectory = directory;
                        console.log("App directory initialized.");
                      }, fail);
                    }, fail);

        function fail(error) {
                      console.log("App directory Error: " + error.code);
                    }

        pdfMake.createPdf(docDefinition).getBuffer(function (buffer) {
                var utf8 = new Uint8Array(buffer); // Convert to UTF-8...
                binaryArray = utf8.buffer; // Convert to Binary...
                save(binaryArray,"Test.pdf")
        });

        function save(data,savefile){
          var html = savefile;
            appDirectory.getFile(html, {create: true, exclusive: false}, function(fileEntry){
                      fileEntry.createWriter(win, fail);
                    }, fail);

            function win(writer) {
                      writer.onwriteend = function (evt) {
                        if (writer.length === 0) {
                          writer.write(data);
                        } else { }
                      };
                    writer.truncate(0);
                console.log("Write success");
                alert("Saving is successful.")
            };

            function fail(error) {
                      console.log("Writer Error: " + error.code);
            }
        }

**Comment by matiasmicheletto** [comment]
A working example:

`
var fileName = "myPDFFile";
var pdfFile = pdfMake.createPdf(document); // Create the document
window.resolveLocalFileSystemURL(cordova.file.externalDataDirectory, // Open public dir
            function (directoryEntry){
                directoryEntry.getFile(fileName+".pdf", { create: true, exclusive: false }, 
                    function(fileEntry){
                       fileEntry.createWriter(function(fileWriter) {
                            fileWriter.onwriteend = function() {    
                                console.log("Done!");// Success!
                            };
                            fileWriter.onerror = function (e) {
                                console.log(e);
                            };
                            pdfFile.getBuffer(function (buffer) {
                                var utf8 = new Uint8Array(buffer);
                                binaryArray = utf8.buffer;
                                fileWriter.write(binaryArray);    
                            });
                   }, 
                   function(error){
                        console.log(error);
                   });
            }, function(error){
                console.log(error);
            });
        });`
