### ISSUE TITLE
Understanding syntax

### ISSUE THREAD

**Issue by francescverdu** [bpampuch/pdfmake#1442]
Hi, I can't reach to understand the syntax rules, that is, I can't understand when to use {} and when to use [], resulting really confusing to construct the data structure. There is a logical rule we can follow?
For instance, in playground, styles1 we have:
	content: [
		{
and then we have
	styles: {
		{
Why these differences...? Where can I find a complete syntax specification?

Francesc

**Comment by liborm85** [comment]
pdfmake for `docDefinition` uses JavaScript Object Notation (JSON). Simply said `[ ]` is definition for array and `{ }` for "object" definition. See [wikipedia.org](https://en.wikipedia.org/wiki/JSON) and [w3schools.com](https://www.w3schools.com/js/js_json_intro.asp).
