### ISSUE TITLE
[bug] createPdf() runs into infinity

### ISSUE THREAD

**Issue by ZoXlike** [bpampuch/pdfmake#1447]
In some cases does the while in the LayoutBuilder.prototype.layoutDocument (line 13997 in pdfmake.js) runs into infinity. 
Its caused of a problem with page break. The Programm tries to calculate when to break to next page and if the input isn't clear enough it stuck at this point. This while there need to have and error handling.

**Comment by liborm85** [comment]
Attach example for reproduce problem runnable on [playground](http://pdfmake.org/playground.html).
