### ISSUE TITLE
pdf export base64, post to a server and save in it problem

### ISSUE THREAD

**Issue by vatpc** [bpampuch/pdfmake#1449]
Good morning, I have developed in angular 5 an app that uses pdfmake to generate an invoice, and it is correct, but now I want to save it in the server, for this I export the pdf to a string with pdfDocGenerator.getBase64 and send it by POST to the server.
The php server collects the string, makes a base64_decode and stores it in a file. This file doesn't work, it's a little smaller than the original. Could you please tell me what I'm doing wrong or some other option  can I try?
Angular------------------
component--------------------
const pdfDocGenerator = pdfMake.createPdf( this.dd);
pdfDocGenerator.getBase64((data) => {
let datos={'data':data};
 this.sser.upload(JSON.stringify(datos)).subscribe();
}
Angular service----------------
    let headers = new HttpHeaders().set('Content-Type','application/x-www-form-urlencoded');
    return this.httpClient.post(this.global.SERVIDOR_URL , 'datos=' + (datos), {headers: headers});

PHP -----------------------------
if (!empty($_POST['datos'])) {
        $sesion=$_POST['datos'];
        $data  = $character->{'data'};
        $data = base64_decode($data);
	file_put_contents($fichero, $data);

thanks

**Comment by liborm85** [comment]
Maybe PDF document have big size and POST limit on server is small and data is cropped by server.

**Comment by vatpc** [comment]
Thanks for your answer, but I'm talking about 25k files I haven't tried yet with larger files.

**Comment by vatpc** [comment]
I found my mistake, instead of using the getBase64(data) method
using the getDataUrl((dataUrl) method, everything fits together.
