### ISSUE TITLE
Is it possible to save created file to server?

### ISSUE THREAD

**Issue by amigo9876** [bpampuch/pdfmake#1453]
This code making download to client
`pdfMake.createPdf(docInfo).download('name.pdf');`

Can i save generated pdf to server?

**Comment by liborm85** [comment]
Yes, it is possible. Use [`getBuffer`](https://github.com/bpampuch/pdfmake#get-the-pdf-as-buffer) or [`getBase64`](https://github.com/bpampuch/pdfmake#get-the-pdf-as-base64-data) and output you can send to server via ajax (or any other option you prefer).
