### ISSUE TITLE
Vulnerability was found by nsp

### ISSUE THREAD

**Issue by bananna0** [bpampuch/pdfmake#1454]
Nsp finded following vulnerability in dependencies:
pdfmake@0.1.37 > pdfkit@0.8.3 > fontkit@1.7.7 > brfs@1.6.1 > static-module@1.5.0 > static-eval@0.2.4 
https://nodesecurity.io/advisories/548
Could you do something about it?

**Comment by liborm85** [comment]
It is not in pdfmake but in fontkit.
