### ISSUE TITLE
How to display a waiting info when a large or long pdfdocument created?

### ISSUE THREAD

**Issue by qdhunter** [bpampuch/pdfmake#1455]
when it create a large pdfdocument , the opened window is emty for a long time. I want to display a waiting info,how to do it? thank you.....

**Comment by liborm85** [comment]
Before running the document generation in pdfmake, show a waiting loader. And then in pdfmake method `download` use second callback parameter to hide waiting loader.

Simple example:
```js
var dd = {
  //...
};

var callbackFunction = function() {
  // Here implement function for hide waiting loader
}

// Here implement function for show waiting loader


pdfMake.createPdf(docDefinition).download('filename.pdf', callbackFunction);
```

**Comment by qdhunter** [comment]
When you download a pdf,you can display a message in your own html page. I use open-method,and the new pdf window is already opened,but it shows only a blank page at first,and wait a moment,it shows the content i want to see.

**Comment by liborm85** [comment]
For `open` you can create own new window (variable `win`) and implement waiting loader in `waiting.html` file, example:
```js
var dd = {
  //...
};

var win = window.open('waiting.html', '_blank');

pdfMake.createPdf(dd).open({}, win);   
```
