### ISSUE TITLE
Internet Explorer Prints Boxes With "X"s in them when rendering a Date String mm/dd/yyyy

### ISSUE THREAD

**Issue by billycomic** [bpampuch/pdfmake#1457]
This only happens in Internet Explorer and Edge. I pass in the date "12/12/2018" and at the beginning and end of each date field when render pdf has a BOX with an X inside it. 
􀀀12􀀀/􀀀12􀀀/􀀀2018􀀀

In chrome and firefox it prints as normal 12/12/2018

any way around this in IE?

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by billycomic** [comment]
Go to [playground](http://pdfmake.org/playground.html) and use the setup below. In Chrome and FireFox it works fine, but in Internet Explorer it renders boxes with x's inside them for the date variable.

`      var date = new Date("05/13/1976").toLocaleString();
      var dd = {
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines',
		date
	]
}`

**Comment by liborm85** [comment]
Yes... you not pass text with date, but use formating to locale. Maybe IE inserting some unbreakable characters to date, and Roboto font not support this characters. Use other font, or remove this characters from text.
