### ISSUE TITLE
RTL languages are not supported

### ISSUE THREAD

**Issue by mohamedkassemofficial** [bpampuch/pdfmake#1463]
I installed a font that support Arabic letters and the pdf was successfully generated but the text is flipped instead of being right-to-left it floats word-by-word from left-to-right.
Can u consider solving this.

**Comment by mohamedkassemofficial** [comment]
I installed a font that support Arabic letters and the pdf was successfully generated but the text is flipped instead of being right-to-left it floats word-by-word from left-to-right.
Can u consider solving this.

**Comment by liborm85** [comment]
RTL is not supported now.
Feature request: https://github.com/bpampuch/pdfmake/issues/184
