### ISSUE TITLE
convert PDF object into HTML or String

### ISSUE THREAD

**Issue by KishanIos007** [bpampuch/pdfmake#1464]
I am using PDF make for making my pdf from predefined document definition. works fine but now i am trying to print the created PDF. I am using ionic framework and using native printer plugin (https://ionicframework.com/docs/native/printer/) for printing but now problem is the printer plugin only takes the HTML/String as an input. 

so do we have any kind of method that can convert PDF object into HTML/string. I have checked all the method that are written in PDFmake js file, but couldn't figure it out.

Here is my code for reference.

```
let printer_ = this.printer;
    var dd = this.createDocumentDefinition();
    var pdf = pdfMake.createPdf(dd);
      printer_.print(_encodedString, options).then((msg)=>{
        console.log("Success",msg);
      },(error)  => {
        console.log("Error", error);
      });
```

**Comment by KishanIos007** [comment]
@liborm85 can u please reply here also.

**Comment by liborm85** [comment]
Output from pdfmake can be base64, buffer (array of chars) or blob, see examples below. But this outputs are data for pdf file. HTML or string (mean as text which is in document) is not possible.

Example with `getBase64`:
```js
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
	// ...
});
```

Example with `getBuffer`:
```js
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBuffer((buffer) => {
	// ...
});
```

Example with `getBlob`:
```js
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBlob((blob) => {
	// ...
});
```

**Comment by KishanIos007** [comment]
Thanks @liborm85 for your help. Do you have any plans to make this features available in the library ??

**Comment by liborm85** [comment]
pdfmake library is for generate pdf files; not for html or other, for this use different library.

**Comment by KishanIos007** [comment]
yaah but ionic official plugin printer ( https://ionicframework.com/docs/native/printer/ ) only takes String and HTML as an input so that's why i get stuck here.

**Comment by liborm85** [comment]
Then use [`print()` from pdfmake](https://github.com/bpampuch/pdfmake#print-the-pdf).

**Comment by KishanIos007** [comment]
Okays.. Does it supports in both iOS and Android ??

**Comment by liborm85** [comment]
Supported browsers is available [here](https://github.com/bpampuch/pdfmake/issues/800).

Pdfmake for `print` method requires client side environment in browser, for example open new window:
```js
win = window.open('', '_blank');
win.location.href = ...;
```
But this probably not work in Ionic, because is runned on server-side and no simply available browser environment?
I have no experience with Ionic framework, I don't know how to help.

**Comment by KishanIos007** [comment]
No actually ionic opens up the InAppBrowser(the browser with in the app) when print method calls. Ionic is totally based on webviews only so that might not be the issue.

**Comment by liborm85** [comment]
Source code that opens window in pdfmake is here [/src/browser-extensions/pdfMake.js#L98-L110](https://github.com/bpampuch/pdfmake/blob/master/src/browser-extensions/pdfMake.js#L98-L110) and it is not probably supported in ionic.

Here is simple code for open print window with pdf in pure javascript:
```js
var dd = ...;

var pdf = pdfMake.createPdf(dd);

var win = window.open('', '_blank'); // TODO: Change to ionic code for open blank window open  

pdf.getBlob(function (result) {
  // In result is Blob object to open in browser
   
  // TODO: Change following two lines to ionic code for create URL object
  var urlCreator = window.URL || window.webkitURL;  
  var pdfUrl = urlCreator.createObjectURL(result);
    
  win.location.href = pdfUrl; // TODO: Change to ionic code for set Blob window object to opened window
}, {autoPrint: true}); // This is important to raise printing in pdf document
```

You can modify TODOs lines from pure javascript to ionic code/objects and it should start working.

**Comment by SStasL** [comment]
How can i take base64 string and save it to variable?
like this...
`const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
        var b64; //in this variable must be data in base64 string format
	return b64;
});`
