### ISSUE TITLE
PDF accessibility

### ISSUE THREAD

**Issue by achecht** [bpampuch/pdfmake#1469]
I posted this to: https://github.com/bpampuch/pdfmake/issues/942, but it appears that issue is closed.
------
In response to GuanQiuQiao who said:
  You can refer to here  http://pdfmake.org/playground.html
------
I referred to the Playground and specifically the styles and images sections. There is nothing there about Tagging for screen reader compatibility or setting Alt Text for images. The PDF spec has handling of both tagging and alt text. Is it possible that PDFMake might have this capabiity in the future? If you think it has it now, just give me a simple example of how to add a navigation tag to a text element declaration and how to add alt text for an image element. Much appreciated!

**Comment by liborm85** [comment]
Issue https://github.com/bpampuch/pdfmake/issues/942 marked as feature request.
