### ISSUE TITLE
Page Specific margins (was: Footer Height)

### ISSUE THREAD

**Issue by smoresch** [bpampuch/pdfmake#147]
Hi, i need to have a different footer content for my multiple pages doc. In the first page footer is 1/8 of the height page, in the last page is 1/4 with different text. How i can do it?

**Comment by jthoenes** [comment]
I renamed the issue to make to make it clearer. What you want is, different page margins on different pages.

**Comment by liborm85** [comment]
Same as https://github.com/bpampuch/pdfmake/issues/325.
