### ISSUE TITLE
Arabic text line order

### ISSUE THREAD

**Issue by Bumbleboss** [bpampuch/pdfmake#1474]
While there's no full support (afaik) for the Arabic words here, is there a way to 
be able to make the lines at the last become at the top? Maybe there's something Idk of?

Code:
```text.split(" ").reverse().join(" ").split("\n").reverse().join("\n")``` 

Preview:
![unknown](https://user-images.githubusercontent.com/22979938/44622774-85695b00-a8c8-11e8-9846-22b4eafa16ea.png)

**Comment by liborm85** [comment]
duplicate with https://github.com/bpampuch/pdfmake/issues/184 and https://github.com/bpampuch/pdfmake/issues/315.
