### ISSUE TITLE
Building font file via shell script

### ISSUE THREAD

**Issue by abtx** [bpampuch/pdfmake#1480]
I've tried running the script from within the (custom) project directory, but the generated font file is empty. What font extension do I need to use and is there a way to specify the path for fonts directory?

**Comment by liborm85** [comment]
Run the script as:
```sh
script.sh font1.ttf font2.ttf font3.ttf
```

**Comment by abtx** [comment]
For anyone getting `base64: invalid option -- w`, change line 17 in `generateFonts.sh` to `echo -n "$(base64 -b 0 $file)"`

**Comment by liborm85** [comment]
[This](https://github.com/bpampuch/pdfmake/wiki/Building-font-file-via-shell-script) page on wiki was added by @HoffmannP, maybe he can help.

"Official" solution is this [wiki](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side).

**Comment by HoffmannP** [comment]
The base64-binary I use is part of `GNU coreutils 8.28` and the flag disables line wrapping. I can't comment on `-b 0` as a replacement. Where is your base64 from?

**Comment by abtx** [comment]
I've not changed the base64, and you're right, removing `--w` will cause line wrapping, and I'd like to know how to prevent the error. The solution proposed was found on StackOverflow.

**Comment by HoffmannP** [comment]
Could you do `base64 -v` or otherwise give me the version of your base64-binary?

**Comment by abtx** [comment]
Doing `base64 -v` throws `invalid option -- v`, the help doesn't list an option to find out the version, how else can I find out the version of my base64-binary on a mac?

**Comment by HoffmannP** [comment]
Allright, I can't get my hands of a manual of Apple's version of `base64` so I assume you have to just trust StackOverflow 😭. The `-b`-flag is not supported in the GNU version of `base64` so the script needs to be changed for different base64-versions.

**Comment by abtx** [comment]
Ok, no problem at all. I couldn't find more info about how to get the base64 version on a mac, but if/when I do I'll make sure to comment back here. Cheers!
