### ISSUE TITLE
Pagesize and rotation

### ISSUE THREAD

**Issue by zfranco55** [bpampuch/pdfmake#1482]
How can I add a page format like DL (Italian envelope format) or custom page, and how can I rotate the page 90 degrees?

**Comment by liborm85** [comment]
According to dimensions from source http://dlsize.com.au/DL-paper-size.php is definition for DL this:
```js
var dd = {
	pageSize: {
		width: 280,
		height: 595
	},
	content: [
		'Text'
	]
}
```

Page orientation can be changed by using `pageOrientation` (see [readme](https://github.com/bpampuch/pdfmake#page-dimensions-orientation-and-margins)).

**Comment by zfranco55** [comment]
THANKS.

Il giorno ven 7 set 2018 alle ore 13:58 Libor M. <notifications@github.com>
ha scritto:
