### ISSUE TITLE
Cannot read property '_calcWidth' of undefined

### ISSUE THREAD

**Issue by vinay4484** [bpampuch/pdfmake#1483]
this.makePDF = function(){

   this.rowContent = [];
   this.tableheaders = [];
   this.tableContent = [];

    for(var i = 0;i<this.values1.length;i++){
         this.tableheaders[i] = {text: this.values[i].name,  bold: true, alignment: 'center'}
    }

    this.tableContent.push(this.tableheaders);

    for(var j = 0;j<this.variable.length;j++){

        this.rowContent.push("","");
    }

    this.tableContent.push(this.rowContent);
    this.rowContent = [];

    var docDefinition = {

           header: 'simple text',
           content: [
             {
               table: {
                 headerRows: 1,
                 widths: [ '*', '*' ],

                 body:this.tableContent
               }
             }

           ]
         };

    pdfMake.createPdf(docDefinition).open();
}

Hi I am getting the above mentioned error while trying to generate a pdf from a HTML table . The table headers are the names of two objects and each of these objects have two arrays which are displayed in the rows. 

Below is the attached image of the error

![error](https://user-images.githubusercontent.com/37010582/45219597-6f20af00-b279-11e8-9dd2-58096f5db60f.PNG)

**Comment by liborm85** [comment]
Attach example runnable on [playground](http://pdfmake.org/playground.html).

**Comment by vinay4484** [comment]
I am sorry i did not understood what you have said, you want to me execute this function on playground?

**Comment by liborm85** [comment]
I need somehow to simulate this issue error.

**Comment by vinay4484** [comment]
// playground requires you to assign document definition to a variable called dd

var headerContent = ["Col1", 'Col2', 'Col3'];

var tableBody = [];
var wantedBody = ['Col1 Row', 'Col2 Row', 'Col3 Row'];

for(var i = 0; i < 5; i++){
    var row = [];
    for(var j = 0; j < wantedBody.length; j++){
        row[j] = wantedBody[j] + i;
        
 
    }
    tableBody.push(row);
    row = [];
}
console.log(tableBody);

var dd = {
                content: [
                {
                                                style: 'tableExample',
                                                table: {
                                                                body: [
                                                                    headerContent,
                                                        tableBody
                                                                ]
                                                }
                                }
                ]
                
}

**Comment by liborm85** [comment]
You have 5 columns in `tableBody`, but in header variable (`headerContent`) only 3 columns.
It works with this modification:
```
var headerContent = ["Col1", 'Col2', 'Col3', '4', '5'];
```

**Comment by vinay4484** [comment]
Thanks it worked
