### ISSUE TITLE
Different pageSize on every page?

### ISSUE THREAD

**Issue by jachui** [bpampuch/pdfmake#1485]
I'm trying to generate a PDF with one image per page, and I'd like each page to have the same size as the image's original size. How can I set a different pageSize on every page?

**Comment by xuchao008** [comment]
@jachui how to resolve  issue ?

**Comment by jachui** [comment]
Add the ability to add page with different pageSize in a single document?

**Comment by xuchao008** [comment]
@jachui excuse , How to do ? or other the ways of resolve.

**Comment by jachui** [comment]
I don't know how to resolve it myself. If it's not possible to do it already, then I guess it will be a feature request. You can label this as 'feature request' and get back to it later.

**Comment by xuchao008** [comment]
@jachui ok，thank u.

**Comment by liborm85** [comment]
Feature request: https://github.com/bpampuch/pdfmake/issues/325
