### ISSUE TITLE
Placement of content to bottom

### ISSUE THREAD

**Issue by victor192** [bpampuch/pdfmake#1487]
I have some table in the `content`. I want table placed at the bottom of the page. Is it possible to implement it somehow? I tried to put a table in the `footer`, but unfortunately it has a limited height

**Comment by liborm85** [comment]
If you want increase height for footer can increase `pageMargins`, see [readme](https://github.com/bpampuch/pdfmake#page-dimensions-orientation-and-margins).
Vertical alignment of page is not supported (feature request: https://github.com/bpampuch/pdfmake/issues/899).
