### ISSUE TITLE
Styling nested text arrays

### ISSUE THREAD

**Issue by jmholzinger** [bpampuch/pdfmake#1488]
Styling applied to text arrays nested in another text array are not properly applied to the text array.

```
var dd = {
	content: [
	    // Static text
	    {text: 'Coloring static text', color: 'green', italics: true},
	    
	    // Text array
	    {text: ['Coloring', ' ', 'text', ' ', 'array'], color: 'blue', bold: true},
	    
	    // Nested static text
	    {
	        text: [
	            {text: 'Coloring nested static text', color: 'red', italics: true, bold: true}
	       ]
	    },
	    
	    // Nested text array
	    {
	        text: [
	            {text: ['Coloring', ' ', 'nested', ' ', 'text', ' ', 'array'], color: 'pink', bold: true}
	       ]
	    }
	]
}
```

While it is possible to concatenate the string first, my use case requires a different font to be used as part of the nested text so I cannot take that approach. Currently the only approach that works when various fonts and styles are needed is to apply the styles to the individual text elements, rather than the parent text element. This approach is a bit cumbersome, but it works. 

I'm not sure if this limitation is intentional or a mere oversight, but I can take a look at the source and potentially provide a fix if there is interest.

**Comment by jmholzinger** [comment]
The styling is overridden by defaults here:
https://github.com/bpampuch/pdfmake/blob/master/src/textTools.js#L287

Still need to investigate why the correct styling is not found on the "styleContextStack"

**Comment by liborm85** [comment]
Is not supported now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/1174

**Comment by nikzanda** [comment]
Any updates?
