### ISSUE TITLE
Download doesn't seems to work on IOS

### ISSUE THREAD

**Issue by NeevShah** [bpampuch/pdfmake#149]
I have tested it on ipad and iphone with chrome and safari browsers. Please help me to make it work.

**Comment by albertohm** [comment]
Same problem here.

Maybe is related to https://github.com/eligrey/FileSaver.js/issues/12

I'm also trying to add a new method of preview using https://github.com/mozilla/pdf.js maybe it works...

**Comment by jthoenes** [comment]
I'm on a Mac, and I down own iOS devices, so I cannot investigate the problem. I'm happy to help, when you want to create a pull request.

**Comment by DrMantisT** [comment]
Hey guys I just ran into this problem and saw this conversation was pretty fresh. Can't seem to get the .pdf to launch from iphone chrome but iphone safari worked. any recent discoveries on this bug?

**Comment by sganeshkumar** [comment]
Hey guys pdfmake download option not working in Iphone and Ipad - chrome browser. Print option working perfect. Plz help me.
pdfMake.createPdf(docDefinition).download('Final Agreement');

**Comment by davsha77** [comment]
I am having an issue as well. I can see the pdf, but I have no way to print, export, or save the file.

**Comment by girish-fuluskar** [comment]
Hi,
I am working on assignment where it require to generate PDF on devices (iOS, Android, Windows). I am using PDFMake library for the same, were I am able to generate the PDF on chrome but when I am running the same solution on any device. It doesn't work.
Any advice?

**Comment by liborm85** [comment]
reference: https://github.com/bpampuch/pdfmake/issues/800

**Comment by liborm85** [comment]
In files-saver was previously fixed, see https://github.com/eligrey/FileSaver.js/issues/12
