### ISSUE TITLE
pdfmake async

### ISSUE THREAD

**Issue by kaushikpathak** [bpampuch/pdfmake#1490]
I need promisify code of pdfmake. Since I have to handle scalability with combined multiple pdf pages(more than 30), which is currently very tough.
I mean to say I am trying to generate 1 pdf with more than 30 pages but I need to maintain scalability with a fast output. So can you please provide a promisify code of PDFmake?

**Comment by liborm85** [comment]
In pdfmake you can use callbacks (on client-side) and events (on server-side).
For impementation promises, is available feature request: https://github.com/bpampuch/pdfmake/issues/866
