### ISSUE TITLE
pdfmake */auto column sizing?

### ISSUE THREAD

**Issue by takuter** [bpampuch/pdfmake#1491]
We need to convert an html table (created by bootstrap datatable) into a PDF. This needs to work for a variety of columns and widths. We are using default columns so that data and header sizes will auto-fit (none of the widths have been specified).

Is there a way to figure out the column width for a table directly from pdfmake? This would allow us to determine when the columns will overflow. We could then kick those excess columns to a second, third, etc. page.

If this is not possible, is there a good workaround?

**Comment by takuter** [comment]
I have found the method to get columns widths, buildColumnWidths, however both that method as well as other parts of PDFmake are inaccessible.  Is there a way to access methods and objects/vars in PDFmake.js from another js file on the same page? 

If not is there a workaround or just insert a function in the pdfmake js file to call that function separately?

**Comment by liborm85** [comment]
There is no solution for the wide tables now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/441
