### ISSUE TITLE
multiple fonts in one text to display non ascii characters

### ISSUE THREAD

**Issue by Akta3d** [bpampuch/pdfmake#1497]
I use an Americane font on my website and use it to generate the pdf.
All is good with "normal" characters.

If all character are present in the used font I haven't problem.
But some users need use unicode characters not present in Americane/Roboto fonts

If I inspect these DOM element in chrome, I see that multiple font are used to render the text : 
![image](https://user-images.githubusercontent.com/6841666/45928506-16be0280-bf45-11e8-910e-13c4b1ef6c1f.png)

Is there a way to add multiple font, the goal will be to use the default font (American in my case) when it's possible, else secondary fonts on the same text

**Comment by liborm85** [comment]
See [Getting Started](https://github.com/bpampuch/pdfmake#getting-started) and [Custom Fonts](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side) for using own fonts.

**Comment by Akta3d** [comment]
I already read this article and I know how to use custom font.

I use Americane font instead Roboto font.

I want know if there is a way to use 2 font for a same text in the case where the text has special characters.

Exemple with the text : 
"Fingerspitzengefühl is a German term.\nIt’s pronounced as follows: [ˈfɪŋɐˌʃpɪtsənɡəˌfyːl]"
Is it possible to use a default font for all ascii characters present in the default font, and use a secondary font in case of a character is not present in the default font.

I want use Americane as default font and DejaVu font as secondary font. DejaVu has unicode characters

**Comment by liborm85** [comment]
No, it not possible. Must be defined one font for one "text part".
Use multiple fonts, example:
```
{
    text : [
        {text:'Fingerspitzengefühl is a German term.\nIt’s pronounced as follows:'},
        {text:'[ˈfɪŋɐˌʃpɪtsənɡəˌfyːl]', font: 'AlternativeFont'}
    ]    
}
```

**Comment by Akta3d** [comment]
that's what I thought, but I preferred to ask

**Comment by cyrixmorten** [comment]
@Akta3d Not sure this will help in your case but faced the same issue with partially translated reports. Meaning that some text entries would be in English and other in Chinese.

My current solution is to iterate the document object model just before printing to PDF:

`PdfMakeAutodetectFont.apply(report);`

With the current code detecting text nodes and applying font:

```
import * as _ from 'lodash';
import { Fonts } from '../fonts/fonts';

export class PdfMakeAutodetectFont {
    /**
     * Auto detect font for text nodes
     *
     * Note: This modifies the document definition object by adding a font property on all text nodes
     *
     * @param input
     * @param key
     * @param object
     */
    public static apply(input: any, key?: string, object?) {

        const isNode = _.isObject(input);
        const isArray = _.isArray(input);
        const isText = _.isString(input);

        if (!(isNode || isArray || isText)) {
            return;
        }

        if (_.includes(PdfMakeAutodetectFont.excludedKeys, key)) {
            return;
        }

        const isTextNode = isNode && _.isString(input.text);

        if (isText || isTextNode) {
            if (isText) {
                // convert to text node and apply font
                object[key] = {
                    text: input,
                    font: Fonts.detectFont(input),
                };
            } else {
                input.font = Fonts.detectFont(input.text);
            }
            return;
        }

        if (isArray) {
            return _.forEach(input, PdfMakeAutodetectFont.apply);
        }

        if (isNode) {
            return  _.forOwn(input, PdfMakeAutodetectFont.apply);
        }
    }

    private static excludedKeys = ['style', 'styles', 'layout', 'margin', 'alignment', 'widths', 'pageMargins', 'pageOrientation', 'defaultStyle'];
}
```

Where `Fonts.detectFont` detects Non-english characters:

```
    public static detectFont(text: string): Font {
        if (!_.isString(text)) {
            return Font.ROBOTO;
        }

        // https://stackoverflow.com/a/15034560/1501613
        const containsCJK = text.match(/[\u3000-\u303f\u3040-\u309f\u30a0-\u30ff\uff00-\uff9f\u4e00-\u9faf\u3400-\u4dbf]/);

        return containsCJK ? Font.NotoCJK : Font.ROBOTO;
    }
```
