### ISSUE TITLE
Use JSON objects and print inside the PDF

### ISSUE THREAD

**Issue by A-Pradeep** [bpampuch/pdfmake#1498]
Hi , i'm very much interested using this PDFmake , its awesome.
In my case , i'm getting a JSON response from the server , whenever i click the submit button.
```
{"owner":null,"roles":[],"_id":"5ba89e0ed2f64e379c2f0f0d","data": 
{"page1Text":"Hello","page2Text2":"Hola","page2Text":"Hi","page3Text":"Thank You"},"access":[],"metadata":
{"timezone":"Asia/Calcutta","offset":330,"referrer":"http://localhost/caas/
form/","browserName":"Netscape","userAgent":"Mozilla/5.0 (Linux; Android 6.0; Nexus 5 Build/
MRA58N) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Mobile
Safari/537.36","pathName":"/caas/
form/","onLine":true},"form":"5b98a42d92147e1664a146ce","externalIds":
[],"created":"2018-09-24T08:19:26.689Z","modifed":"2018-09-24T08:19:26.690Z","saved":true}
```

I want specifically the data should be printed inside the PDF
like for example   
content :First Message ={{page1.Text}}
(inside pdf) `First Message =Hello`
i want to be printed inside the pdf like this , how can i achieve this ??

**Comment by liborm85** [comment]
JSON response from server you can convert to  [document definition content](https://github.com/bpampuch/pdfmake#document-definition-object). This is a normal javascript, you can use any function from js for creating content.

**Comment by A-Pradeep** [comment]
how can i use the CSS in this ? 
any ways i can align , do changes to the appearance ?

content: [
                                { text: 'Welcome', style: 'header' },
                                { text:'----------------------X--------------------------'},
                                { text: 'First  Message: '+submission.data.page1Text, style: 'anotherStyle' },
                                { text: 'Second Message: '+submission.data.page2Text, style: 'anotherStyle' },
                                { text: 'Second Message: '+submission.data.page3Text, style: 'anotherStyle' }
                            ],

![image](https://user-images.githubusercontent.com/37439293/45946499-b1cedf00-c00e-11e8-8bec-da3015bf4489.png)

its coming like this , how can i edit and playaround with the css / design how the pdf should print ?

**Comment by liborm85** [comment]
Object name? What do you mean? Add some example.
