### ISSUE TITLE
table rowspan border

### ISSUE THREAD

**Issue by Cajami** [bpampuch/pdfmake#1499]
hello good day, I have a table with rowspan in the body not in the header, but when you go to another page has no border in the cell with rowspan.

how can I solve that?

![error_pdfmake](https://user-images.githubusercontent.com/25354307/46020379-e04ac980-c0a3-11e8-936b-574ca62f00ba.png)

**Comment by pcbimon** [comment]
Need Help pls. I found same with you.

**Comment by liborm85** [comment]
feature request: https://github.com/bpampuch/pdfmake/issues/2270

**Comment by mojidul-dev-pwd** [comment]
Is this issue resolved?
