### ISSUE TITLE
Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)

### ISSUE THREAD

**Issue by Masber** [bpampuch/pdfmake#1501]
Hi,

I am getting an error when trying to print a transparent image.

```
this.label_logo = 'R0lGODlhAQABAAD/ACwAAAAAAQABAAACADs=';
var pdfContent = {	
            content: [
              {image: 'data:image/gif;base64,' + this.label_logo, alignment: 'left', width: 150},
              {text: '\n'}
                ]};
pdfMake.createPdf(pdfContent).download(data.rma + '.pdf');
```
any advice?

**Comment by liborm85** [comment]
For this image is internally returned error: `Unknown image format`.

Maybe in image is unsupported format, try image re-save.

**Comment by Guigeek973** [comment]
So is it really limited to 10KB ?

**Comment by Mr3richardgomes** [comment]
ony JPEG and PNG formats are supported, your format informed is GIF, not supported.
[imagesPfdMaker](https://pdfmake.github.io/docs/0.1/document-definition-object/images/)

**Comment by prabhatpal77** [comment]
Images do not support in the PDFmake library. They don't have proper documentation on their website. It is totally bull shit.

**Comment by marwajomaa** [comment]
> Images do not support in the PDFmake library. They don't have proper documentation on their website. It is totally bull shit. I am working on it for 10 days I got totally frustrated with it.

@prabhatpal77  did you find a way to work with images I am facing the same issue on the client side?

**Comment by capvalen** [comment]
I resolved like that:
I passed the image to base64. It returns a long character string. I put it in a variable after that y called in the content.
`let testImage = 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAm0AAACk ...'`
`content: [`
`  { image: testImage, width: 300, margin: [100, 0, 0, 0], },`
`]`

**Comment by andrewhamili** [comment]
![image](https://github.com/user-attachments/assets/77038062-213a-4bf4-aca6-9702845fa006)

#[https://github.com/andrewhamili/nestjs-pdfmake](url)

Reopening this issue.
