### ISSUE TITLE
 How do I open a PDF file on the file system

### ISSUE THREAD

**Issue by lhuangjs** [bpampuch/pdfmake#1503]
I want open a PDF file on the file system, can I implement the  operation using pdfmake?

**Comment by liborm85** [comment]
After generate PDF file by pdfmake, you can open file by `open()` method.
Example:
```js
pdfMake.createPdf(docDefinition).open();
```
(see [readme](https://github.com/bpampuch/pdfmake#open-the-pdf-in-a-new-window))
