### ISSUE TITLE
If cell is continuing from previous page, add text like "continuing.."

### ISSUE THREAD

**Issue by phzbox** [bpampuch/pdfmake#1504]
Hi, I'm wondering if it's possible to add some text in a cell if it's continuing from a previous page in a table?

I.e.
(Page 1)-------------
| Header1 | Header 2 |
[ Cell....... | Cell ...... ]
[ Cell (1).. | Cell (2). ]

(Page 2)--------------
[ Cell (1).. | Cell (2..).]

If Cell (1) is short and Cell (2) is very long, Cell (1) becomes empty on the 2nd page. I'd like to add a place holder such that it says (continuing..) in Cell (1) on page 2.

I spent some time going through the code but I'm not sure where I could add such feature? The API could be something like this:

```
 {
  text: '..',
  emptyCellPageBreakText: 'continuing..'
 }
```

Happy to try to code it but I would need some direction as to where to get started.

Thanks!

**Comment by liborm85** [comment]
Not supported now, feaure request is here: https://github.com/bpampuch/pdfmake/issues/531
