### ISSUE TITLE
Unkown font format

### ISSUE THREAD

**Issue by ps-coder** [bpampuch/pdfmake#1507]
I'm following [server.js](https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js) and have copied fonts from [here](https://github.com/bpampuch/pdfmake/tree/master/examples/fonts). But whenever I try to run the application, I'm getting 'Unkown font format' with following trace:

`Error: Unknown font format
  at Object.fontkit.create (/node_modules/fontkit/src/base.js:53:9)
  at Object.create [as openSync] (/node_modules/fontkit/src/base.js:16:18)
  at Function.PDFFont.open (/node_modules/pdfkit/js/font.js:14:24)
  at PDFDocument.font (/node_modules/pdfkit/js/mixins/fonts.js:39:28)
  at FontProvider.provideFont (/node_modules/pdfmake/src/fontProvider.js:49:58)
  at /node_modules/pdfmake/src/textTools.js:299:27
  at Array.forEach (<anonymous>)
  at measure (/node_modules/pdfmake/src/textTools.js:281:13) ......`

pdfmake version is latest ie 0.1.38. **What could be the reason for this error?** I tried running it by downloading roboto fonts from official Google repo but same error

**Comment by liborm85** [comment]
I tried run dev-playground, and works ok.
Did you follow [these instructions](https://github.com/bpampuch/pdfmake/blob/master/dev-playground/README.md) to run server?

There is no need to copy font files anywhere. Maybe you're copyed wrong font files?

**Comment by ps-coder** [comment]
I'm working on serverless so wasn't exactly following the code. But used this instead and it's perfectly:
```
var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

Thanks for such a great library!

**Comment by liborm85** [comment]
From first post is pdfmake runned in server-side, but in your second post is runned as client-side.
Examples how to use pdfmake on server-side is [here](https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js) and for client-side is [here](https://github.com/bpampuch/pdfmake#getting-started).

If the error persists, you pass a wrong font file. Attach example of your code.

**Comment by MustakimKhalifa** [comment]
i want to use unicode font and i have embed font file (ttf) but still given me this error : pdfmake.js:52523 Uncaught (in promise) Error: Unknown font format
