### ISSUE TITLE
scollable div

### ISSUE THREAD

**Issue by sunithajanapareddy** [bpampuch/pdfmake#1508]
hello 

i have div with vertical and horizontal scroll iam not able to download all the data and iam able to download only seen data

**Comment by liborm85** [comment]
What? Pdfmake not supported scrollable elements. All texts in docdefinition are printed to pdf document.

**Comment by sunithajanapareddy** [comment]
> What? Pdfmake not supported scrollable elements. All texts in docdefinition are printed to pdf document.

hey hi
can i give inner html data in the content in docdefination if yes how we need to give

**Comment by liborm85** [comment]
For load inner text data from element and pass to pdf document, you can use for example this:
```js
var dd = {
	content: [
		{text: document.getElementById("example-element").innerHTML},
	]	
}
```


Full transformation from HTML to PDF if too complicated and feature request is here: https://github.com/bpampuch/pdfmake/issues/205

**Comment by sunithajanapareddy** [comment]
> For load inner text data from element and pass to pdf document, you can use for example this:
> 
> ```js
> var dd = {
> 	content: [
> 		{text: document.getElementById("example-element").innerHTML},
> 	]	
> }
> ```
> 
> Full transformation from HTML to PDF if too complicated and feature request is here: #205

but it is displaying as text but not as html page design we need to get html design

**Comment by liborm85** [comment]
Not supported now, feature request is here: https://github.com/bpampuch/pdfmake/issues/205
