### ISSUE TITLE
Cannot convert div content to pdf  

### ISSUE THREAD

**Issue by nsgawli** [bpampuch/pdfmake#151]
i have a predefined div, how to convert it to the pdf....??? 
As per your given examples you mentioned data statically but how to assign dynamic content to pdf...???

**Comment by jthoenes** [comment]
pdfmake does not support converting HTML into PDF native. I know that some people have been doing this, but I'm unsure if there is a good way to integrate it into the library.

Don't expect it to be in the library soon.

**Comment by jthoenes** [comment]
Look to #205
