### ISSUE TITLE
fillOpacity changes following images

### ISSUE THREAD

**Issue by zreptil** [bpampuch/pdfmake#1510]
when defining fillOpacity on a canvas object, then the following objects are also drawn with this opacity. The objects itself don't have fillOpacity for their rendering, so it is not possible to reset the fillOpacity for the objects, unless you define a canvas object with the wanted opacity. 

Can be seen in the image-example on the playground. just add the following as first object in the content:
		{
		    canvas:[{type:"rect", x:0, y:0, w:100, h:100, color: "red", fillOpacity: 0.5}]
		},

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/da275776b1a92c83e6c5d942dd0eab35bbecbd0a.
