### ISSUE TITLE
Table Row Height not working

### ISSUE THREAD

**Issue by nebulaware** [bpampuch/pdfmake#1512]
I built a document and one of the rows needs a set height. If I use the pdfmake playground, the height rule is followed, on my site it ignores all height values. I even copied the playground table example over to my site and even that doesn't work.

**Comment by liborm85** [comment]
What version number do you use? Try use latest version.

**Comment by nebulaware** [comment]
Yes, I've updated to the latest version: v0.1.38

**Comment by liborm85** [comment]
Yes on playground is 0.1.38 and it works.

**Comment by nebulaware** [comment]
Yes, but as i mentioned if i copy my code to the playground the heights work. But on the site they do not. Even copying the playground example with heights doesnt work and i did try the new code and no luck. Could there be any other reason or another way to control the height

**Comment by liborm85** [comment]
If docdefinition on playground works ok, then must work on your server. If not work, you probably do not have the latest version.
