### ISSUE TITLE
Is't possible to use with Vue.JS?

### ISSUE THREAD

**Issue by biapar** [bpampuch/pdfmake#1518]
Is't possible to use with Vue.JS?

**Comment by knakamatsu** [comment]
Hi.
I made a simple implementation.
https://github.com/knakamatsu/vue-pdf/blob/master/src/components/PDFgen.vue

Thanks.

**Comment by biapar** [comment]
Thank. But I don't understand how to pass a <div> content ( dynamic content ).

var docDefinition = { content: 'This is an sample PDF printed with pdfMake' }

**Comment by liborm85** [comment]
Above is example how to use pdfmake in Vue.JS framework. For preparing content you can use javascript/framework ability (eg. append array item/variable, etc.). If you do not know how, use google or Vue.JS support.

**Comment by EDMONDGIHOZO** [comment]
@knakamatsu  thank you so much,

**Comment by lschmidt7** [comment]
I used this file in my VueJS project, but i get this error: 
'Cannot set property 'render' of undefined'
I tried different approachs but i can't resolve

**Comment by lartheon** [comment]
> I used this file in my VueJS project, but i get this error:
> 'Cannot set property 'render' of undefined'
> I tried different approachs but i can't resolve

I found an example online that used the following as an import, hopefully it helps
```import pdfMake from "pdfmake/build/pdfmake";```

**Comment by ClaudioVigliarolo** [comment]
And of course this holds true for the fonts 
`import pdfMake from "pdfmake/build/pdfmake";`
