### ISSUE TITLE
Multiple dynamic images of diferent width and height

### ISSUE THREAD

**Issue by DenWoas** [bpampuch/pdfmake#1521]
Hi, I am trying to insert some images in colums,  i want to insert 12 images for each pdf page(3*4). I am trying this for the first column, but it doesn´t do anything:  

```
      var col = [];
       for(let i = 0; images.length > i; i++) {

          if(i < 3){
           col.push(['image: '+images[i], ' width: ' + 110,' height: ' + 110]);
         }

       }


    let docDefinition = {
      content: [

      {
        columns: col
      },


      ]
      },


    ],
```

I would like the images to be able to put them in the pdf in three columns and 4 rows per page.

How can I do it?

Thanks

**Comment by liborm85** [comment]
For create grid can be used `table` node with `layout: 'noBorders'` (see how to use `table` on [playground example](http://pdfmake.org/playground.html) > _TABLES_). Columns can be used of course, but the table is probably more appropriate.

Example how to insert `image`s is on [playground example](http://pdfmake.org/playground.html) > _IMAGES_.

I recommend read [readme](https://github.com/bpampuch/pdfmake/blob/master/README.md).
