### ISSUE TITLE
Something similar to border-width property in css

### ISSUE THREAD

**Issue by Quixomatic** [bpampuch/pdfmake#1527]
Are there currently any plans to add border-width functionality to tables? Currently the borders are quite bulky, looks like 2px to 3px in width to me. Being able to control the widths of the borders would be extremely useful.

**Comment by liborm85** [comment]
This is supported, you can use `hLineWidth` and `vLineWidth` functions, see [playground](http://pdfmake.org/playground.html) > _TABLES_ and [readme](https://github.com/bpampuch/pdfmake#tables).

**Comment by Quixomatic** [comment]
@liborm85 thank you for the quick response, I didn't realize what that was for. Is there a numeric value translation that maps to `1px border widths`? It seems like `returning 0.1 - 0.25` for `hLineWidth` and `vLineWidth` looks closest to `1px`.

**Comment by liborm85** [comment]
Unit is points (pt).

**Comment by blikblum** [comment]
I am also looking into this issue.

With @liborm85 info and this [conversor](https://www.ninjaunits.com/converters/pixels/pixels-points/) i found that 1 pixel === 0.75 points.

But when setting line width to 0.75 sometimes draws a sharp line sometimes a fuzzy one. 

See how this def is draw in playground:
```javascript
 {
	table: {
		headerRows: 1,
		body: [
			[{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}, {text: 'Header 3', style: 'tableHeader'}],
			['Sample value 1', 'Sample value 2', 'Sample value 3'],
			['Sample value 1', 'Sample value 2', 'Sample value 3'],
			['Sample value 1', 'Sample value 2', 'Sample value 3'],
			['Sample value 1', 'Sample value 2', 'Sample value 3'],
			['Sample value 1', 'Sample value 2', 'Sample value 3'],
		]
	},
	layout: {
		hLineWidth: function (i, node) {
			return 0.75;
		},
		vLineWidth: function (i, node) {
			return 0.75;
		}
	}
}
```
![image](https://user-images.githubusercontent.com/3047126/47223593-05bfb000-d390-11e8-90f3-5eccd4d5d7c5.png)

Second and fourth vertical lines and fourth horizontal line are sharp, while others are fuzzy

I bet is something related how vector graphics are draw. There's some info about this when using cairo, a vector drawing with a PostScript and PDF inspired api:
https://www.cairographics.org/FAQ/#sharp_lines
http://stevehanov.ca/blog/index.php?id=28

In fact, changing margin left and top changes how lines are draw

**Comment by Quixomatic** [comment]
@blikblum I noticed that as well, sometimes the lines are sharp/fuzzy depending on the value you set for `hLineWidth` and `vLineWidth`, since my project doesn't require the values to change I found that 0.25 provides the sharpest lines (at least so far).

@liborm85 thank you for letting me know the unit of measure is in `pt`, very helpful

**Comment by Quixomatic** [comment]
@liborm85 is there anything on the books to add borders to regular `text` content blocks?

**Comment by liborm85** [comment]
Borders is not supported with `text`.

**Comment by nicolacardi** [comment]
vLine and hLine seem to affect only internal borders width. I have single cells tables, and I need to set all of the four sides widths. f I use hLineWidth and vlineWidth I get a border of the specified thickness only on the right and bottom.
The strange fact is that border can be easily set in the body as an array like

```
body: [[{
              text: "my text",
              fillColor: "#FF0000,
              border: [true, false, true, false ],
              borderColor: ['#00FF00','#00FF00','#00FF00','#00FF00'], // imposta il bordo della cella
             }]]
```
but borderWidth is not a possible array I can set in the same way
