### ISSUE TITLE
Width of string

### ISSUE THREAD

**Issue by teawithfruit** [bpampuch/pdfmake#1529]
Hello,

First thanks for this great module!
I've read, that pdfmake is based on pdfkit.
Is it possible to use functions from pdfkit in my workflow with pdfmake?

In this case, I mean specifically the ```widthOfString``` function from pdfkit. I would like to use this function in my pdf creation workflow to dynamically resize the font size of a given string to fit in a box with a defined width an height.

Or are there any other ways to solve this problem with an existing pdfmake function? Maybe with an anonymous fontSize function?

If not, is it possible to implement something like this?
```js
{
  text: 'This paragraph will have a bigger font',
  width: 200,
  fontSize: function(node, text, size) {
    if(this.widthOfString(text) > node.width) {
      return size - 1
    } else {
      return 10
    }
  }
}
```

Thanks.

**Comment by liborm85** [comment]
feature request: https://github.com/bpampuch/pdfmake/issues/937

**Comment by shov** [comment]
Is it solved of denied? I'm interested in the functionality

**Comment by mowolf** [comment]
> Is it solved of denied? I'm interested in the functionality

would be interested as well

**Comment by zullo91** [comment]
I can get the maxWidth and other parameter as well. 
And the magic happen! 
Shakala booom ;)

```
console.log(
        this.getTextMaxWidth({
          absolutePosition: { x: offsetX, y: offsetY },
          columns: [
            {
              text: productEntry.product.name,
              fontSize: 10
            }
          ]
        })
      )
```
```
  private getTextMaxWidth(content: {}) {
    const temp = [];
    temp.push(content);
    const pdf = pdfMake.createPdf({ content: temp });
    pdf.getStream({});
    return pdf.docDefinition.content[0]._maxWidth;
  }
```
