### ISSUE TITLE
Duplicates data when starting a new page

### ISSUE THREAD

**Issue by JorgelGtzGtz** [bpampuch/pdfmake#1531]
**I have a problem generating a PDF when I continue with duplicate records in the new page.**
![duplicate](https://user-images.githubusercontent.com/37045031/47471283-d6ada200-d7c6-11e8-8199-c080859f97f1.PNG)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by JorgelGtzGtz** [comment]
I attach a file for the example you can run in playground and in the third page in the end of page and the start page can you see the duplicate record .

[ReportJson.txt](https://github.com/bpampuch/pdfmake/files/2517451/ReportJson.txt)

**Comment by liborm85** [comment]
In breaked table is defined `"headerRows": 1,` changes to `"headerRows": 0,` (or remove this line).
