### ISSUE TITLE
Characters not rendered properly

### ISSUE THREAD

**Issue by manu-st** [bpampuch/pdfmake#1535]
When using the following document description:
```
var dd = {
    content: [
        {text: '10⁻⁰⁵'},
        ]
}
```
the generated PDF replaces the Unicode characters for  superscript -,0 and 5 as squares. The same text using the same default font renders fine in a webpage.

Is there a reason why those characters are not properly rendered.

**Comment by liborm85** [comment]
Because characters are not available on used font (suppose Roboto font). Use other font which supports this characters.
