### ISSUE TITLE
Position of header and footer

### ISSUE THREAD

**Issue by manu-st** [bpampuch/pdfmake#1537]
Hi,

I'm trying to understand how the headers and footers and positioned and found this inconsistency. Using the following document description:

```
// playground requires you to assign document definition to a variable called dd

var dd = {
    content: [
		{
			table: {
				widths: ["*"],
				body: [
					[
						{text: 'Confidential fds fdsf fsd dsf fds dfsdfds fdsfdsf sdfds fds'},
					]
				]
			},
		},
	],
	pageMargins: [10, 50, 10, 50],
	header: function (currentPage, pageCount) {
		return {
			table: {
				widths: ['auto', "*", "auto"],
				body: [
					[
						{text: 'Confidential', alignment: 'left'},
						{text: 'Page ' + pageCount, alignment: 'center'},
						{text: 'Page ' + pageCount, alignment: 'right'}
					]
				]
			},
		};
	},
	footer: function (currentPage, pageCount) {
		return {
			table: {
				widths: ['auto', "*", "auto"],
				body: [
					[
						{text: 'Confidential', alignment: 'left'},
						{text: 'Page ' + pageCount, alignment: 'center'},
						{text: 'Page ' + pageCount, alignment: 'right'}
					]
				]
			},
		};
	},
}
```

You will see that the header starts at the very top of the page, ignoring the top margin. However, the footer always starts after the bottom margin. Note that header/footer ignore completely the left/right of the pageMargins, so this seems inconsistent.

What is the relationship between pageMargins and header/footer?

Ideally, I'd like to be able to set my header/footer areas position (x, y, width, height) with a constraint that the area does not overlap the inside of the pageMargins. Is that possible?

**Comment by liborm85** [comment]
`header` starting on coord Y = 0 and ending on Y = `pageMargins`.top. Width (X) is `pageSize`.width.
`footer` starting on coord Y = `pageSize`.height - `pageMargins`.bottom and ending on Y = `pageSize`.height. Width (X) is `pageSize`.width.

**Comment by zahrafali** [comment]
Can we change the values? I want my header to have some padding/margin
