### ISSUE TITLE
Table with row headers

### ISSUE THREAD

**Issue by manu-st** [bpampuch/pdfmake#1538]
Hi,

I generate tables where `headerRows` is specified. I sometime end up with a table at the end of the page with the header but no content, the content is on the next page with the header. How can I prevent this situation?

Thanks!

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by manu-st** [comment]
Cannot reproduce this anymore. It might have been an error on my end.
