### ISSUE TITLE
Referencing fonts from .asar archive - pdfmake with electron

### ISSUE THREAD

**Issue by lokixxvii** [bpampuch/pdfmake#1540]
I am creating an electron app that generates a pdf file using pdfmake.
When in development, I can specify the correct path of fonts, i.e. the root directory of my project.
But when I packaged the app, the path for the fonts cannot be found. It is wrong, since the resources are already inside the asar archive for electron.

Can you help me please? Thanks!

**Comment by liborm85** [comment]
I don't know what is asar archive in electron. Try to ask on electron support.

**Comment by manu-st** [comment]
What I've done is include the fonts I need in a directory where the .EXE is generated. Someone might know how to get them from the ASAR file but it is easy enough to have the installer put the fonts there.

**Comment by lokixxvii** [comment]
@manu-st that is also what I ended up doing. Thanks!
