### ISSUE TITLE
how can I configure pdfmake so that it unescapes  &amp;

### ISSUE THREAD

**Issue by aruprakshit** [bpampuch/pdfmake#1542]
I have some texts from API as `&` escaped as  `&amp;`. But pdfmake don't unescape them in pdf while rendering. Is there any settings to fix this from this lib?

I tried the below sample in the [playground](http://pdfmake.org/playground.html), and saw the same result.

```js
var dd = {
	content: [
		'First paragraph, test &amp; test',
	]
	
}
```

**Comment by Jikok** [comment]
You have to escape it with the backslash like bellow 

`text: 'First paragraph, test \& test',`

It output : First paragraph, test & test

**Comment by aruprakshit** [comment]
@Jikok I didn't get what you meant here. I am getting actual string as `'First paragraph, test &amp; test',`.

**Comment by liborm85** [comment]
In pdfmake docdefinition escape not needed, insert text without escaped character.
Use some "unescape" function and then use plaintext text in docdefinition.
