### ISSUE TITLE
support for unicode charackters (Arabic and Persian langyages)

### ISSUE THREAD

**Issue by am2222** [bpampuch/pdfmake#1547]
Hi,
It seems this library does not support Arabic and Farsi characters. is there any solutions for this issue?

**Comment by liborm85** [comment]
Characters are supported, but use a font that supports Arabic characters. (Default Roboto font does not have these characters.)
But not supported RTL (feature request: https://github.com/bpampuch/pdfmake/issues/315)

**Comment by am2222** [comment]
@liborm85 thanks very much
