### ISSUE TITLE
Nested tables overflow from the page (rows overflow not the columns)

### ISSUE THREAD

**Issue by vinuhegdesit** [bpampuch/pdfmake#1550]
I need to iterate the title content(not header) of the table to the next page , if the table spans over to the next page. Seems like the nested table was the only solution for it, as we can use "headerRows" property to iterate any content onto the next page during the table spanning over to the next page. But after using the nested table approach, the rows of the table are just being overflowed in the same page and the rows are getting lost from the bottom of the page. I tried many combinations by applying many of the table related properties.. none of them worked as expected.
Properties tried are: dontBreakRows, keepWithHeaderRows, pageBreak
Tried all sorts of combinations for both outer and inner tables, none worked as expected.
For better understanding of the problem: Please try to implement yourself with some 30 number of rows - 3 sets of data (30x3) with each set having its own respective title to be displayed at the top of its table. As each set has more number of rows(ex:30), then the table for each set surely spans over to the next page, hence the same previous table title has to be displayed on top of the continued table(set) on the next page. Surely you will find problem in either displaying the table title / handling the overflow of the table. Please suggest.

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).
