### ISSUE TITLE
Generate pdfs in bulk

### ISSUE THREAD

**Issue by sohilfynd** [bpampuch/pdfmake#1551]
Thanks for writing such a light weight library on client and server.
I am using this library on client side and i want to generate around 5000 pages pdf. This will not be possible in single run as memory will go out of chrome. How can i implement this in batches like 500 pdfs per file and then release its memory and generate next 500 pdfs and so on for like 10 iterations. whenever i passed callback function to download, pdfs are downloaded at end of all iteration and not one by one.

**Comment by Sibabalwe-Qamata** [comment]
@sohilfynd  i kind have the same task. Did you manage to solve this?

**Comment by liborm85** [comment]
In version 0.1.55+ you can disable cache via fontLayoutCache option.
Example:
`printer.createPdfKitDocument(docDefinition, { fontLayoutCache: false });` on server-side and `pdfMake.createPdf(docDefinition).download('document.pdf', null, { fontLayoutCache: false });` on client-side

[link to documentation](https://pdfmake.github.io/docs/options/)
