### ISSUE TITLE
error view

### ISSUE THREAD

**Issue by Cajami** [bpampuch/pdfmake#1553]
Hi,
How can I solve this error? Thanks for the help

![error_pdfmake](https://user-images.githubusercontent.com/25354307/48015344-f1511680-e0f6-11e8-99cb-94b08ec596c1.png)

**Comment by liborm85** [comment]
Duplicate with: https://github.com/bpampuch/pdfmake/issues/371, https://github.com/bpampuch/pdfmake/issues/921
