### ISSUE TITLE
Fixed margins in table cells

### ISSUE THREAD

**Issue by zreptil** [bpampuch/pdfmake#1554]
Is there a possibility to remove the fixed margins in tablecells and the fixed linewidths for the borderlines?

I tried to scale the output to the pdf so that everything scales to 10 percent of the output, for having previews of the rendered pages on one page. It works for everything except for tables, since these seem to have a fixed borderwidth and a fixed margin inside the cells that cannot be removed, even if i set a style- or margin-attribute in every single cell.

**Comment by liborm85** [comment]
Cell padding in table you can set via layout properties: `paddingLeft`, `paddingRight`, `paddingTop`, `paddingBottom` and line width via `hLineWidth`, `vLineWidth`.

Simple example:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
				]
			},
			layout: {
				hLineWidth: function (i, node) { return 0; },
				vLineWidth: function (i, node) { return 0; },
				paddingLeft: function(i, node) { return 0; },
				paddingRight: function(i, node) { return 0; },
				paddingTop: function(i, node) { return 0; },
				paddingBottom: function(i, node) { return 0; },
			}
		}
	]
}
```

**Comment by zreptil** [comment]
Unfortunately these settings require Javascript for the settings. Is there a possibility to define the paddings with pure JSON? I understand, that the functions make this more flexible, but in my case i create the formdefinition as JSON, send it to a server and let the server do the job of creating the pdf. And i was not able to define the functions in JSON so that they can be interpreted by the server. The function definition arrives at the server as a string, not as a function.

So for me it would be better to have the possibility to define the layout simply as JSON. Is there such a possibility?

**Comment by liborm85** [comment]
No, it is not possible.

**Comment by zreptil** [comment]
I am sorry to hear this. Then i have to dig a little deeper to see, what i can do by myself about this issue. Thanks for the quick answers :)
