### ISSUE TITLE
src/imageMeasure.js detected as virus

### ISSUE THREAD

**Issue by Bazze** [bpampuch/pdfmake#1556]
When downloading latest version of pdfmake from this repo, my antivirus (ESET Endpoint Protection) quickly reacts to the file `src/imageMeasure.js` and deletes it. It's detected as: `a variant of Generik.FKIWGBY`. I'm guessing it's a false positive? Just wanted to let you know..

https://www.virustotal.com/#/file/fa26ed559d1a56238cb6520c0d868a66ec2b0bdcacd9882c5b40b90af30eb563/details

**Comment by liborm85** [comment]
Repo is virus free.

Check your computer for viruses.

**Comment by Bazze** [comment]
I don't doubt that, this is probably a false positive. Just wanted to let you know!

**Comment by Rotzbua** [comment]
The zip gives 4 detections. The pure `imageMeasure.js` (LF line endings) gives only 2 detections:
https://www.virustotal.com/de/file/4ca1dab18f8b4f1690656687a327dc70a43204f7c20d6158bcc9064975f74b90/analysis/1542148812/

With line endings CR+LF and CR there is no detection:
https://www.virustotal.com/de/file/dc0f7af170e7a22ccc8135d45f78da914f66dc131f0edbfebc4d656ef23b68e6/analysis/1542148845/
https://www.virustotal.com/de/file/6ab68b60174b0978226606eee80138be0007d70540121f1e9e4ba8f3bad9bce9/analysis/1542149096/

Interesting how this antivirus programs work :)

I think a simple minify for productive deployment will obfuscate the file enough so the antivirus would not detect them. For develop whitelist them..
