### ISSUE TITLE
Uncaught SyntaxError: Unexpected token <

### ISSUE THREAD

**Issue by sponeill** [bpampuch/pdfmake#1559]
Hello, I'm looking forward to utilizing pdfmake. However, after retrieving the required files from github (pdfmake.min.js & vfs_fonts.js) and including them in my project I am receiving "Uncaught Syntax Error: Unexpected token > (pdfmake.min.js:7 & vfs_fonts.js:7).  I'd appreciate it if you could point me in the right direction. Many thanks.

**Comment by liborm85** [comment]
Do you have correct javascript files for pdfmake? Because this error is throw when is invalid javascript file included by <script> or invalid path.

**Comment by rob101** [comment]
Make sure you download the raw file from Github and not "save as.." on the directory link, as you will get an HTML file that will through this error but pdfmake will still run.
