### ISSUE TITLE
Question about examples

### ISSUE THREAD

**Issue by chiester** [bpampuch/pdfmake#1563]
Why do the examples show a local dependency (../src/printer) that is not shown in the formal documentation anywhere? 

Do I have to manually download and install your /src directory to get something to work the way it works in the example?

**Comment by liborm85** [comment]
Examples are intended for building from source (see [readme](https://github.com/bpampuch/pdfmake#building-from-sources)).
When you have a pdfmake installed as a dependency replace `'../src/printer'` to `'pdfmake'`.
