### ISSUE TITLE
gif support ?

### ISSUE THREAD

**Issue by JRainey72** [bpampuch/pdfmake#1564]
Documented image support currently lists jpeg and png formats.  Will gif images not work?
thank you

**Comment by sukima** [comment]
I tried this using a data URI in the playground and got an error. I would conclude that GIF is **not** supported. I wish the docs and error message were more clear about this.

**Comment by liborm85** [comment]
Supported formats are described in [documentation](https://pdfmake.github.io/docs/document-definition-object/images/).

**Comment by LabN36** [comment]
is there a way to somehow display gif(only static image) in the pdf ?
