### ISSUE TITLE
unable to preserve trailing white space of a simple text or also in a table contents (text)

### ISSUE THREAD

**Issue by vinuhegdesit** [bpampuch/pdfmake#1566]
Can you please add a keyword that can apply for whole pdf to preserve the leading or trailing whitespace. I know there is one property "preserveLeadingSpaces", it only works for simple "text", it doesnt work for table contents. I am actually in a requirement to preserve trailing white spaces for a table contents.

**Comment by liborm85** [comment]
I tried it and it works in table too. Some example for reprocedure your problem runnable on [playground](http://pdfmake.org/playground.html)?

**Comment by vinuhegdesit** [comment]
Sorry I am unable to provide you the example, but surely it doesn't work. I have tried it many times. Can you please tell me the property that you have used to retain the trailing  whitespace for a string content in a table or outside the table ?

**Comment by liborm85** [comment]
How to set `preserveLeadingSpaces` to texts is described here: https://github.com/bpampuch/pdfmake/blob/41ed75396d19d4a80e759282362d7c617e8d351d/examples/styling_properties.js#L29-L33

And `text` element you can use in `table` cell (how to create table is described in [readme](https://github.com/bpampuch/pdfmake#tables)).
Of course is possible set it to style dictionary (see [readme](https://github.com/bpampuch/pdfmake/blob/master/README.md#style-dictionaries)) or to `defaultStyle` (see [readme](https://github.com/bpampuch/pdfmake/blob/master/README.md#default-style)).
