### ISSUE TITLE
Horizontally spread table over multiple pages

### ISSUE THREAD

**Issue by webdevbe** [bpampuch/pdfmake#1568]
Hi,

Is it possible to horizontally spread a table over multiple pages, so a user can put those pages next to each other to create a full table view? Just to be clear, I'm not talking about a lot of rows, it's when having a lot of columns, so it's no longer readable when fitting on one page.

Thanks

**Comment by liborm85** [comment]
It is not possible now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/441
