### ISSUE TITLE
pdfmake + Angular universal

### ISSUE THREAD

**Issue by mgutbor** [bpampuch/pdfmake#1569]
I have this excellent addon working on my angular 6 project, but when I tried to run it in angular universal:

- npm run build:universal
- npm run generate:prerender

Shows me this error:

-----------------------------------------------------------------------------------
_node prerender.js

webpack:///./dist-server/main.c2dc411c687e969813ab.js?:1 !function(e,a){for(var i in a)e[i]=a[i]}(exports,function(modules){var installedModules={};function webpack_require(moduleId){if(installedModules[moduleId])return installedModules[moduleId].exports;var module=installedModules[moduleId]={i:moduleId,l:!1,exports:{}};return modules[moduleId].call(module.exports,module,module.exports,webpack_require),module.l=!0,module.exports}return_webpack_require__.m=modules,webpack_require.c=installedModules,webpack_require.d=function(exports,name,getter){webpack_require.o(exports,name)||Object.defineProperty(exports,name,{configurable:!1,enumerable:!0,get:getter})},webpack_require.r=function(exports){Object.defineProperty(exports,"esModule",{value:!0})},__webpack_require.n=function(module){var getter=module&&module.esModule?function(){return module.default}:function(){return module};return_webpack_require.d(getter,"a",getter),getter},webpack_require.o=function(object,property){

ReferenceError: navigator is not defined_
-----------------------------------------------------------------------------------

Cpuld anyone helps me to solve it??? Will be possible to solve generating pdf on the server???

Thanks in advance.

**Comment by liborm85** [comment]
Try ask on angular support.

**Comment by mgutbor** [comment]
hi @liborm85,

and thanks for your answer. You mean about ask at stackoverflow or on this github there is a part for angular support???

**Comment by liborm85** [comment]
I do not use angular. And I do not know where have angular support.
Here is pdfmake forum/support.
