### ISSUE TITLE
getBuffer() Does Not Fire On iOS

### ISSUE THREAD

**Issue by Rysm** [bpampuch/pdfmake#1570]
Hi everyone,

I am trying to run this piece of code on iOS in my Ionic 2/3 application. When the code reaches this part, no errors are thrown, and no PDF is displayed.

I am clueless as to what the issue is or where it may lie. I would like to reach out for guidance in the right direction.

```
      if (this.plt.is('cordova'))
      {
        this.pdfObj.getBuffer((buffer) => {
          var blob = new Blob([buffer], { type: 'application/pdf' });

          // Save the PDF to the data Directory of our App
          this.file.writeFile(this.file.dataDirectory, 'mydoc.pdf', blob, { replace: true }).then(fileEntry => {

            // Open the PDf with cordova file opener
            this.fileOpener.open(this.file.dataDirectory + 'mydoc.pdf', 'application/pdf')
                .then(() => console.log('File is opened'))
                .catch(e => console.log('Error opening file', e));

          })
        });

      }
```

**Comment by liborm85** [comment]
In `buffer` variable is returned data/array?

**Comment by Rysm** [comment]
I'm not sure; when I try to console.log() inside of :

`this.pdfObj.getBuffer((buffer) => {})`

It never fires

**Comment by liborm85** [comment]
I do not see use pdfmake anywhere in your code. 
So I do not know when is call `this.pdfObj.getBuffer`.

Simple example how it works:
```js
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

var docDefinition = {
  // ... definition for document
};
var pdfDoc = pdfMake.createPdf(docDefinition);
pdfDoc.getBuffer((buffer) => {
  console.log(buffer); // buffer pdf file output 
});
```

**Comment by Rysm** [comment]
That's weird; I only posted the snippet above, so everything else is there @_@

Is there a way to way for the doc definition to actually be created, or do you know why getBuffer() is not being called?

**Comment by liborm85** [comment]
If something fails in method `getBuffer` exception would be thrown.
Code is really executed? Is condition `(this.plt.is('cordova'))` true?

**Comment by Rysm** [comment]
Yeah, the platform check fires true, but getBuffer() does not return or throw an exception
