### ISSUE TITLE
Access class properties in dynamic footer

### ISSUE THREAD

**Issue by roddharris** [bpampuch/pdfmake#1573]
I've wrapped pdfMake in a class that I use for printing reports.  The class basically takes care of the basic layout of the report for my app.

In my footer, I need to display the date/time that the report is being created, the name of the application with its version number and the page number.  The problem is that the name of the application is defined in an appSettings class that is being injected into my reportwrapper class and `this` within the footer dynamic function call is not referencing my reportwrapper class.

```
export class ReportMakerPDF{
   static inject = [AppConfig] //Injection of class object handled by Aurelia Framework
   constructor(config){
       pdfMake.vfs = pdfFont.pdfMake.vfs
       this.settings = config  //This contains the company name and version of the running application
       this.init()
    }

    init(){
        this.reportLayout = {
            footer: this.generateFooter,
            ....
        }
    }

    generateFooter(currentPage, totalPages){
        let columns = []
        columns.push(moment().format("MMM DD, YYYY"))
        
        //This is where I need help!
        //I want to do the following
        //text: `${this.config.appCompanyName} ${this.config.appVersion}`, alignment: "center"
        columns.push({text: "", alignment: "center"})

        columns.push({text: `Page ${currentPage} of ${totalPages}`, alignment: "right"})

        return {style: 'pFooter', columns: columns}
    }
    savePDF(reportName){
        pdfMake.createPdf(this.reportLayout).download(`${reportName}.pdf`, () => {
            ...
        }
    }
```
You can see in `generateFooter` that `this` no longer references my report maker wrapper class so my config object is not available.  Is there a way to somehow pass that data into my `generateFooter` routine or else access that data from within `generateFooter`?

**Comment by adrienblot** [comment]
It seems like you have an error in your code. You are trying to access `this.config.appCompanyName`, but `this.config` doesn't exist, it should be `this.settings`. 

`constructor(config){
       pdfMake.vfs = pdfFont.pdfMake.vfs;
       this.settings = config;
       this.init();
    }`

**Comment by roddharris** [comment]
Thanks, yes -- that was a typo.  You are correct that it should've been `this.settings` -- however, either way, you get the same result.  I'm unable to use `this` within `generateFooter` to access `settings` because the scope of `this` does not refer back to the `ReportMakerPDF` class.

**Comment by adrienblot** [comment]
The class keyword is just syntax sugar but does not change how prototyping and context generation works in javascript. The function context is defined when you execute it, not when you define it (except for arrow functions).

For example when you do this: 
`this.reportLayout = { footer: this.generateFooter }`
`this.reportLayout.footer();`

`this` in the footer function will be `reportLayout`.

Moreover pdfmake separate the header and footer function from the original docDefinition object and call them in directly, so in strict mode `this` will be undefined.

If you want to keep your ReportMakerPDF object context, you can use `bind`:

`this.reportLayout = { footer: this.generateFooter.bind(this) }`

**Comment by roddharris** [comment]
This is exactly what I needed!  Thanks so much -- worked like a charm.
