### ISSUE TITLE
pdfmake memory leak

### ISSUE THREAD

**Issue by szaim** [bpampuch/pdfmake#1574]
hey Guys,

am using pdfmake on jquery datatable, the issue am facing here is that the browser crash when i try to download about 90k of rows, when i was debugging this issue i found out that this was crashing when it try to create about 100 pages (not sure but something around this number) is there a fix for that please i wanna give it a shot before trying to do it on a backend, thanks for help

**Comment by atiertant** [comment]
@szaim there are memory leaks in pdfkit (a lib used by pdfmake), we are waitting for a new release that fix it. 
and there is another problem in both pdfkit and pdkmake to generate big documents: they aren't asynchronous... it lock the event loop and there's no back pressure possible.

**Comment by liborm85** [comment]
Solved in new version see https://github.com/bpampuch/pdfmake/issues/1052#issuecomment-459941689.
