### ISSUE TITLE
Nested relativePosition is not working

### ISSUE THREAD

**Issue by ackvf** [bpampuch/pdfmake#1575]
I am trying to draw a legend under a graph, for that I am rendering a combination of canvas lines with precisely positioned texts (as was advised [here#896](https://github.com/bpampuch/pdfmake/issues/896#issuecomment-285931194)), however, nesting `relativePosition` does not work as one would expect.

```
{
  canvas: [
    {
      type: 'line',
      x1: 70,
      y1: 60,
      x2: 90,
      y2: 60,
      lineWidth: 7,
      color: 'blue',
    },
    {
      type: 'line',
      x1: 190,
      y1: 60,
      x2: 210,
      y2: 60,
      lineWidth: 7,
      color: 'green',
    },
    {
      type: 'line',
      x1: 310,
      y1: 60,
      x2: 330,
      y2: 60,
      lineWidth: 7,
      color: 'red',
    },
  ],
},
{
  relativePosition: { y: -8 },
  text: [
    { text: 'Amount Received', relativePosition: { x: 100 } },
    { text: 'Dept', relativePosition: { x: 220 } },
    { text: 'Property Value', relativePosition: { x: 340 } },
  ],
},
```

result:
![image](https://user-images.githubusercontent.com/2313018/49167772-66022400-f336-11e8-8d66-45ae625604b7.png)

**Comment by adrienblot** [comment]
The text array defines one paragraph with a different styling for each element so you can't change the positioning. Try to use a stack instead: 

`{
  relativePosition: { y: -8 },
  stack: [
    { text: 'Amount Received', relativePosition: { x: 100 } },
    { text: 'Dept', relativePosition: { x: 220 } },
    { text: 'Property Value', relativePosition: { x: 340 } },
  ],
}`

<img width="664" alt="screen shot 2018-11-30 at 9 02 22 am" src="https://user-images.githubusercontent.com/12889063/49248422-89d08180-f47e-11e8-8353-110fd589d76c.png">

**Comment by ackvf** [comment]
Great, thanks!

**Comment by jeremyml** [comment]
It should be noted that `color` causes `lineWidth` not to work, so use `lineColor` instead.  https://github.com/bpampuch/pdfmake/issues/477

**Comment by jeremyml** [comment]
It should be noted that `color` causes `lineWidth` not to work, so use `lineColor` instead.  https://github.com/bpampuch/pdfmake/issues/477
