### ISSUE TITLE
Print and open not working with Firefox ~63

### ISSUE THREAD

**Issue by no-more** [bpampuch/pdfmake#1577]
Hello,

I don't know since how long, but `print` and `open` are not working anymore with latest version of FF.
I have also tested with the playground and have the same issue.
I'm almost sure it used to work so I don't know if the change is on FF side or pdfmake, but would be great to have it working again.
There's no error message.

Works fine with Chrome.

Thanks.

**Comment by no-more** [comment]
You're right. Adblock seems to stop it.
Isn't there any way to prevent this ? I don't understand why adblock is interfering here.

Thanks.

**Comment by liborm85** [comment]
It is blocked in easylist by commit https://github.com/easylist/easylist/commit/e3276b6ff9611e821d0e8ba7ac4dc336a4e3b765 (source https://github.com/bpampuch/pdfmake/issues/800#issuecomment-353878055).
There is no way to solve it...

**Comment by no-more** [comment]
Thanks for your help.
