### ISSUE TITLE
PDF preview with custom font

### ISSUE THREAD

**Issue by keiron77** [bpampuch/pdfmake#1578]
I have added a custom font to the PDF using:

`NeueHaas: {
            normal: 'fonts/Linotype - Neue Haas Unica Pro.otf',
            bold: 'fonts/Linotype - Neue Haas Unica Pro Bold.otf',
        }`

This is working when viewing the PDF, but the preview show scrabbled characters. I am applying the font using `defaultStyle` so it should be applied to all instances. Any ideas how to fix this?

**Comment by liborm85** [comment]
Probably same issue https://github.com/bpampuch/pdfmake/issues/1168.
