### ISSUE TITLE
image watermark is not working.

### ISSUE THREAD

**Issue by dina1610** [bpampuch/pdfmake#1580]
How can i fix the image watermark.

**Comment by dina1610** [comment]
Hi,
 Same method I tried but it's showing dark background picture. Watermark
should be light color ryt. For that also I tried with opacity it's getting
light color but after that whole paragraph contents also getng light. For
that any example

**Comment by liborm85** [comment]
Image opacity you can set by `opacity` property, see [playground](http://pdfmake.org/playground.html) > _tab IMAGES_.

**Comment by dina1610** [comment]
yeah its there. i have already referred. give some content after opacity image check the output what its happening. FYR please check the attachment
[download.pdf](https://github.com/bpampuch/pdfmake/files/2662388/download.pdf)

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/b1df1d0ffd14ccc11b2acaf5fc3117ef7daf1f85.

**Comment by liborm85** [comment]
New version released.

**Comment by dina1610** [comment]
Tnq so much

**Comment by josevenezuelapadron** [comment]
how can i use watermark property but with a image instead a text

**Comment by NathBabs** [comment]
Hello @josevenezuelapadron how did you accomplish it ? I'm trying to do same

**Comment by GoulartNogueira** [comment]
You can simply use `background` instead of `watermark`:

```js
background: {
      "image":"data:image/png;base64,(...)",
      //optional:
      opacity: 0.1,
      absolutePosition: {x: -100, y: 150},
      width: 500,
      },
```
