### ISSUE TITLE
PDFMake slow downoad

### ISSUE THREAD

**Issue by squaredsquared1996** [bpampuch/pdfmake#1582]
Hi, it's been three years after this issue was solved.

But still, I have this issue. **Downloading PDF takes like more than a minute**.

I use **pdfmake v0.1.32**. I want to apply the solution given above but it seems like the code mention is different from my pdfmake.js.

I attached the file because  I can't seem to find the line  25,900. Can anyone help with this? Thank you.
[pdfmake.txt](https://github.com/bpampuch/pdfmake/files/2652041/pdfmake.txt)

_Originally posted by @squaredsquared1996 in https://github.com/bpampuch/pdfmake/issues/280#issuecomment-444771527_

**Comment by jfoclpf** [comment]
is function `download` still available? I don't see it on new documentation: https://pdfmake.github.io/docs/getting-started/client-side/methods/
