### ISSUE TITLE
just use image via Browser

### ISSUE THREAD

**Issue by moffsugita** [bpampuch/pdfmake#1583]
Should I use base64 string (data URI) when I use png via web browser like Chrome?

it is path.
```
const imagePath = './img/myimage.png';
```

also I tried.
```
const imagePath = require('./img/myimage.png');
```

Document
```
            {
              image: imagePath,
            },
```

Error
```
Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)
```

**Comment by liborm85** [comment]
If this is on client-side (browser) you can use data uri format. See [readme](https://github.com/bpampuch/pdfmake#images).

**Comment by liborm85** [comment]
For practices of conversing to URI you can use google.
