### ISSUE TITLE
Table heights extends far beyond when on second page

### ISSUE THREAD

**Issue by ricardosaracino** [bpampuch/pdfmake#1584]
Am i missing something ... when the content spans a second page (getBody) the table just overflows with some height far beyond the one specified.
       
       return {

            pageSize: 'LEGAL',

            pageMargins: [20, 20, 20, 70],

            styles: {
                default: {
                    fontSize: 10,
                },
            },

            content: [
                {
                    style: 'default',
                    margin: [0, 0, 0, 0],
                    table: {
                        widths: '100%',
                        heights: 710, // THIS WORKS WHEN THERE IS 1 Page
                        body: [
                            [
                                {
                                    margin: [0, 0, 0, 0],
                                    border: [1, 1, 1, 1],
                                    table: {
                                        widths: ['100%'],
                                        body: [
                                            [ObservationStatementPdfService.getHeader(user, observationStatement)],
                                            [ObservationStatementPdfService.getBody(observationStatement)],
                                        ]
                                    }
                                }
                            ],
                        ],
                    },
                },

![image](https://user-images.githubusercontent.com/759253/49755254-64b1ef00-fc86-11e8-8c3c-db96496a8483.png)

![image](https://user-images.githubusercontent.com/759253/49755272-71364780-fc86-11e8-97c1-3288e34a5565.png)

**Comment by liborm85** [comment]
Attach example for reproduce problem runnable on [playground](http://pdfmake.org/playground.html).

**Comment by liborm85** [comment]
No reaction.
