### ISSUE TITLE
Prevent content copying from pdf

### ISSUE THREAD

**Issue by dina1610** [bpampuch/pdfmake#1586]
How can I prevent copying the content from PDF. Because of security concerns.

**Comment by liborm85** [comment]
Not possible now, feature request is here: https://github.com/bpampuch/pdfmake/issues/1262

**Comment by kumarandena** [comment]
@dina1610 Security - encryption, access privileges addition was released in 0.1.50.

https://github.com/bpampuch/pdfmake/issues/1262#issuecomment-459942946

Reference :
* https://github.com/foliojs/pdfkit/blob/master/docs/getting_started.md#encryption-and-access-privileges
* https://pdfmake.github.io/docs/document-definition-object/security/
