### ISSUE TITLE
Document not written after page break in iOS 8

### ISSUE THREAD

**Issue by tctruckscience** [bpampuch/pdfmake#159]
Hi, I've come across a problem when trying to use pdfMake to generate a PDF on an iPad (iOS 8.1.2).  Whenever I try to do a page break, the data before the break is written but anything afterwards is not.  It works on desktop browsers but not on Safari on the iPad.  I've tested it using Chrome and it does work using that browser under iOS 8.1.2.  I've also tested it in Safari on an iPad using iOS 7 and the PDF is generated with all its pages.

I tried copying and pasting the document definition from the tables example in the playground but the rest of the document does not appear after page 1.  Is there any way to do this?

**Comment by liborm85** [comment]
Without any sample.
