### ISSUE TITLE
Pdfmake increase header size on all page not working

### ISSUE THREAD

**Issue by Fra996** [bpampuch/pdfmake#1590]
I've this problem, I can't increase header size in pdfmake download. I've tried all, margin, pageMargin but not working? Someone helps me, please? Thanks!

**This is the result**
![qmm0f](https://user-images.githubusercontent.com/45269224/50279242-785d1280-0449-11e9-9601-1e9dfd60a72a.png)

**This is my code:**
                   customize: function ( doc ) {

            var tblBody = doc.content[1].table.body;

            doc.content[1].layout = {

                hLineWidth: function(i, node) {
                    return (i === 0 || i === node.table.body.length) ? 1 : 1;},
                vLineWidth: function(i, node) {
                    return (i === 0 || i === node.table.widths.length) ? 1 : 1;},
                hLineColor: function(i, node) {
                    return (i === 0 || i === node.table.body.length) ? '#ccc' : '#ccc';},
                vLineColor: function(i, node) {
                    return (i === 0 || i === node.table.widths.length) ? '#ccc' : '#ccc';},

            };
            doc.header = function(currentPage,pageCount){
                var headerObj = {
                    columns: [
                        {
                            table: {
                                headerRows: 1,
                                body: []

                            },
                            stack: [         
                                {

                                    image: 'image',
                                    fit:[200,200],
                                    alignment:'right',
                                    margin:[20,20],

                                }
                            ],

                        },

                    ],

                };
                return headerObj;
            }

            doc['styles'] = {

                tableHeader: {
                    bold: !0,
                    fontSize: 11,
                    color: 'white',
                    fillColor: '#8abc33',
                    alignment: 'center',
                },

                title: {
                    fontSize: 20,
                    alignment:'left',
                    marginBottom:50,
                },

            };
        },    
        download: "download"
    };
    return n.Buttons
});

**Comment by Fra996** [comment]
i've just tried, but only title and table was influenced by it.

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by liborm85** [comment]
No reaction.
