### ISSUE TITLE
option to change datatables pdf direction

### ISSUE THREAD

**Issue by sajasbana** [bpampuch/pdfmake#1592]
Dear sir,

Thank you for your tools, I'm using datatables plugins and it is use pdf make to create pdf file output

I wonder if there is any option that i can change pdf direction from right to left or left to right?

Thanks

**Comment by liborm85** [comment]
Text direction is supported only left to right (LTR).
Right to left (RTL) is not supported (feature request: https://github.com/bpampuch/pdfmake/issues/184).
