### ISSUE TITLE
rowSpan and colSpan not working as expected

### ISSUE THREAD

**Issue by Zoomelectrico** [bpampuch/pdfmake#1593]
Hello! Thank you for the library and for reading this issue!
To be short I wanna a make a table with the following layout:

![example](https://raw.githubusercontent.com/Zoomelectrico/image-repo/master/Screenshot%20from%202018-12-23%2015-38-30.png)

I wrote a little example of what is happening in my current structure. 

```js
// Ready to ctrl+c ctrl+v into http://pdfmake.org/playground.html
var dd = {
	content: [
	    {
			style: 'tableExample',
			color: '#444',
			headerRows: 2,
			table: {
				widths: [100, 100, 100, 100],
				headerRows: 1,
				body: [
					[
					    { text: 'Header 1', rowSpan: 2 }, 
					    { text: 'Header 2', rowSpan: 2 }, 
					    { text: 'Header with Subheader', colSpan: 2 }, 
					    {}
					],
					["", "", "A", "B"],
					["data 1", "data 2", "data 3", "data 4"]
				]
			}
		}
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true,
			margin: [0, 0, 0, 10]
		}
	    
	}
};
```
But I getting this
![current pdf document](https://raw.githubusercontent.com/Zoomelectrico/image-repo/master/Screenshot%20from%202018-12-23%2015-46-44.png)

I really would love if someone can help with this, because I don't what else to do.

**Comment by adrienblot** [comment]
Hi! If you change headerRows from 1 to 2, you should get what you want (the headerRows property outside the table property is useless). Cheers.

![screen shot 2018-12-24 at 9 56 30 am](https://user-images.githubusercontent.com/12889063/50387472-f3803a80-0761-11e9-8b22-9c777c34800b.png)

**Comment by Zoomelectrico** [comment]
@adrienblot It works, thank you very much!!

**Comment by DevExploreDot** [comment]
buenas tardes a todos, me podrian ayudar, quiero hacer lo mismo del header with subheader y que debajo este el A, B, este es mi código donde el saldo inicial este en la misma posicion que el header, y que el A sea el deudor y la B sea el acreedor   private generateDetailTable() {
        let columns: string[] = ['AccountAccountingCode', 'Description', 'InitialBalance', 'Debit', 'Credit', 'Debtor', 'Creditor'];
        if (this.isNewSums) {
            columns = ['AccountAccountingCode', 'Description', 'BalanceDebit', 'BalanceCredit', 'Debit', 'Credit', 'Debtor', 'Creditor'];
        }
        let headers: any[] = [
            { text: 'CUENTA', style: 'text_header' },
            { text: 'DESCRIPCIÓN DE CUENTA', style: 'text_header' },
            { text: 'SALDO_INICIAL', style: 'text_header' },
            { text: 'DEBE', style: 'text_header' },
            { text: 'HABER', style: 'text_header' },
            { text: 'DEUDOR', style: 'text_header' },
            { text: 'ACREEDOR', style: 'text_header' }
        ];
        if (this.isNewSums) {
            headers = [
                { text: 'CUENTA', style: 'text_header', alignment: 'center',  margin: [0, 15, 0, 15] },
                { text: 'DESCRIPCIÓN DE CUENTA', style: 'text_header', margin: [0, 15, 0, 15]  },
                { text: 'Saldo_inicial:DEUDOR 2', style: 'text_header',margin: [0, 15, 0, 15]  },
                { text: 'Saldo_inicial:ACREEDOR', style: 'text_header',margin: [0, 15, 0, 15]  },
                { text: 'DEBE', style: 'text_header', margin: [0, 15, 0, 15]  },
                { text: 'HABER', style: 'text_header', margin: [0, 15, 0, 15]  },
                { text: 'DEUDOR', style: 'text_header' , margin: [0, 15, 0, 15] },
                { text: 'ACREEDOR', style: 'text_header', margin: [0, 15, 0, 15]  }
            ];
        }
        let _widths: string[] = ['auto', '*', 'auto', 'auto', 'auto', 'auto', 'auto'];
        if (this.isNewSums) {
            _widths = ['auto', '*', 'auto', 'auto', 'auto', 'auto', 'auto', 'auto'];
        }
        return {
            table: {
                widths: _widths,
                headerRows: 1,
                body: this.buildTableBody(columns, headers)
            }
        };
    }
estaba trabando de seguir los ejemplo de https://pdfmake.github.io/ pero no me sale, gracias de antemano.
