### ISSUE TITLE
Cannot set fontsize for watermark text.

### ISSUE THREAD

**Issue by VimalNathan** [bpampuch/pdfmake#1594]
I have added watermark having more than 30 words. The text shrinks too small. I need a way to set font size for water mark text.

**Comment by liborm85** [comment]
Implemented by [commit](https://github.com/bpampuch/pdfmake/commit/adf6526a30e2e6b1bb3a5bae4b283acb4c5ff076) (in brach 0.1) and [PR](https://github.com/bpampuch/pdfmake/pull/1780) (in master).
