### ISSUE TITLE
Can we share a list of table styles?

### ISSUE THREAD

**Issue by vini-brito** [bpampuch/pdfmake#1595]
Can we have a shared list of table styles? It would make it easier to have more previously made options along the ones already made and shared in the examples. 

Maybe they can have a space in the wiki by the table element explanation.

**Comment by liborm85** [comment]
see [documentation](https://pdfmake.github.io/docs/document-definition-object/tables/#table-layouts)

**Comment by vini-brito** [comment]
Yes I've seen it and I do know how to make it work, I'm talking about we sharing the custom table layouts we individually made, apart of the ones already there. Add more layouts in the examples list.

**Comment by liborm85** [comment]
Wiki is freely available on page creation.
