### ISSUE TITLE
Open, print and download PDF not working with chrome v71.0.3578.89 on iOS v11.1.2

### ISSUE THREAD

**Issue by shakthihcue** [bpampuch/pdfmake#1599]
System:  macbookpro's ipad
OS: iOS v11.1.2
Chrome: v71.0.3578.89

Unable to open, print and download PDF not working with above mentioned configurations. Would be great if someone could throw us some light on how to fix it.

**Comment by achyutgp** [comment]
@shakthihcue , I see kinda similar issue with `download('SamplePDF.pdf')` PDF on all the browsers. However, `open()` and `print()` works fine for me.
System: Windows 10 Pro
Chrome v71.0.3578.98
Firefox Quantum 64.0
Microsoft Edge 41.16299.820.0

**Comment by roemhildtg** [comment]
Same issue here.

**Comment by lin03951** [comment]
Same issue too. Unable to download :(

**Comment by liborm85** [comment]
There are not many changes between version 0.1.39 and 0.1.40 (see https://github.com/bpampuch/pdfmake/compare/0.1.39...0.1.40). And there was nothing changed in `open` action.
Most problems are due to add-ons used in browser, primarily AdBlock (see https://github.com/bpampuch/pdfmake/issues/800), try disable add-ons.

**Comment by roemhildtg** [comment]
I'm assuming the issue came from updating the file saver package. 
https://github.com/bpampuch/pdfmake/commit/59873964f6f9801bd0bce74b0968450d2128cefc

**Comment by Sean-Yi** [comment]
We are also facing the same issue. When download function gets called, it doesn't do anything

**Comment by Ruffio** [comment]
If using FilerSaver.js, then it must be called by FileSaver.SaveAs as stated in the README: https://github.com/eligrey/FileSaver.js

![image](https://user-images.githubusercontent.com/1877612/51500377-07a17100-1dce-11e9-99b8-ed1e105a2b80.png)

**Comment by liborm85** [comment]
@shakthihcue Can you try `download` action on iPad in pdfmake version 0.1.39 and in 0.1.40 ? Because was updated filesaver library from version 1.3.8 to 2.0.0.

**Comment by talamatur** [comment]
The same happens to me with Angular 7 on Windows and Firefox/IE 11/Chrome

**Comment by liborm85** [comment]
Upgraded file-saver to 2.0.1.

New version 0.1.53 released.
