### ISSUE TITLE
split oversized images

### ISSUE THREAD

**Issue by benjkn** [bpampuch/pdfmake#1602]
I am using pdfmake after html2canvas.  I am turning a big chunk of html to image (canvas) and then this into pdf (because of very complicated styling in this html)

In case the canvas is longer than 1 page, I wish to show as much as I can on the 1st page, then on the 2nd to continue from where I stopped and etc. etc.

I used the playground to do some tests.
I was thinking of something like this:

```
var dd = {
	content: [
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, 0, 0, 0]
		},
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, -820, 0, 0]
		}
	]
}
```

But it doesn't work... No error, just wrong result.

Surprisingly when I tried:

```
var dd = {
	content: [
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, -820, 0, 0]
		},
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, 0, 0, 0]
		}
	]
}
```

(different order only) it seems to do what it should fine, but in the wrong order!!! Trying AFTER to change the order, has the same result as the 1st try...

Any help???

**Comment by liborm85** [comment]
Force page breaks is needed, use `pageBreak: 'after'` in image

Example:
```js
var dd = {
	content: [
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, 0, 0, 0],
			pageBreak: 'after'
		},
		{
			image: 'sampleImage.jpg',
			height: 1500,
			width: 500,
			margin: [0, -800, 0, 0]
		},
	]
}
```
