### ISSUE TITLE
If / for statements

### ISSUE THREAD

**Issue by thierryler** [bpampuch/pdfmake#1605]
Hello,

Is it possible to use if ou for statements in content?

Thx.
Th.

**Comment by liborm85** [comment]
Yes, docDefinition is JSON and you can build in javascript with standard javascript commands.

**Comment by thierryler** [comment]
For example, can I skip a full paragraf based on a if ? can you give an example how to do it, pls?

**Comment by liborm85** [comment]
docDefinition is array and you can dynamically create array. To how to write `if` / `for` / array in javascript you can use google.
