### ISSUE TITLE
Table of Content skip the cover page number ( cover page doesn't have number but TOC counts it )

### ISSUE THREAD

**Issue by kavin404** [bpampuch/pdfmake#1607]
I want to make a table of content page for a PDF book which has

- Cover Page
- Table Of Content Page
- Other pages ( **Page Numbering starts from here**) 

Currently it seems that Table of content ( TOC ) counts from the cover page.  Is this a unavailable feature or is there a way to do it?

**Comment by liborm85** [comment]
For change page number is need implement page grouping with reset pagination - issue https://github.com/bpampuch/pdfmake/issues/1270.
