### ISSUE TITLE
vLineColor not getting called

### ISSUE THREAD

**Issue by gabucito** [bpampuch/pdfmake#161]
Hi, I was testing pdfmake and found that in version 0.1.15 the last example of the tables.js the line:
<pre>
vLineColor: function(i, node) {
   return (i === 0 || i === node.table.widths.length) ? 'black' : 'gray';
}
</pre>
does not get called.  

On the other hand, in version 0.1.13 it seems to be working correctly.

**Comment by jthoenes** [comment]
Opened a pull request to fix the issue.
