### ISSUE TITLE
Add link in TOC items (not only page number)

### ISSUE THREAD

**Issue by filippomuscolino** [bpampuch/pdfmake#1610]
Hello, first of all thanks for your great library!

Actually pdfmake generates the TOC with links on page numbers. 
Have you considered having links also on TOC items?

(P.S. I looked at the code and seems not so difficult to implement, I can work on it and open a PR if you're interested!)

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/61f5a49c1690b7703d0066d86b3a18754c619ff6 (in master) and https://github.com/bpampuch/pdfmake/commit/0ab7a35aa4b6a92066df5602b5f7114f1aa3ae28 (in 0.1 branch).

Release pending to https://github.com/bpampuch/pdfmake/issues/897#issuecomment-484776044.
