### ISSUE TITLE
From: Blob URL Display (mobile)

### ISSUE THREAD

**Issue by smockensturm** [bpampuch/pdfmake#1615]
Hey there.

Is there any way to change this display where it says "from: blob"

Client doesn't like it. The word is "very obvious and has negative connotations". ¯\_(ツ)_/¯

![2ffa8746-20ac-11e9-8188-96ccaae6637b](https://user-images.githubusercontent.com/6586518/51752179-d4d4d280-2084-11e9-8563-110f2ad84801.png)

**Comment by liborm85** [comment]
What is displayed in download dialog depends on browser (not on pdfmake library).
