### ISSUE TITLE
Cannot turn bold off

### ISSUE THREAD

**Issue by ninja-** [bpampuch/pdfmake#162]
There seems to be a bug.
I can't turn bold back off after using it once.

Example doc:
```
docDefinition = {
	content: [
		[{ 
			text: 'hello1', 
			alignment: 'center', fontSize: 14, bold: true
		}],
		{ 
			text: "hello2", 
			alignment: 'center', fontSize: 12, bold: false
		}, 'asasdd',
]}
```

In that case both are rendered bold. If I set bold to false in first one, none of them are bold.

EDIT: problem can be fixed by downgrading pdfmake by a lot. I'll try to find the commit that causes the problem

**Comment by SteffiPeTaffy** [comment]
The same behaviour with the italics property.

**Comment by giangdm** [comment]
I founded the problem in debug file line 15156 
change from:

cacheKey = family || src; 

to:
cacheKey = src || family;

**Comment by jthoenes** [comment]
Thanks @giangdm - helped me track it down. The pull request should fix it.

**Comment by bpampuch** [comment]
I'm still experiencing this issue
