### ISSUE TITLE
Open / Download PDF on safari web-app

### ISSUE THREAD

**Issue by Akta3d** [bpampuch/pdfmake#1620]
All work if app is opened in safari)
But if I open my app in web-app mode (standalone) I can't use pdf.open() or pdf.download() either I have a white page either I have nothing.

I have tried to get the buffer then save the buffer with saveAs module, but don't work.

Any ideas to open the pdf generated in browser and open it in safari standalone mode ?

**Comment by moffsugita** [comment]
Yes... Safari can `open()` method.
However, PDFViewer of safari doesn't work download and preview buttons on the bottom.

![2019-02-07 11 56 48](https://user-images.githubusercontent.com/35673132/52387931-7ae5fb00-2acf-11e9-84a1-cf7539b286d6.png)

**Comment by Akta3d** [comment]
On standalone mode, Safari don't open the pdf.

I have remove the standalone mode to open my app in a real safari and not in a approximative safari which cannot open new tab or pdf.

**Comment by Wabbala** [comment]
Popup blocker? Ad-block?

**Comment by Akta3d** [comment]
No,
On **standalone** mode, safari don't display the address bar and cannot open new tab.
When we dowload a pdf, safari try to open a new tab, but can't, the pdf is not displayed and not dowloaded.

To avoid this, I remove the manifest.json if user-agent is safari
`<link rel="manifest" href="/manifest.json" id="manifest-json">`

Now user who add my app on their desktop, they can open my app in a real Safari (with address bar), and can open tab and display pdf.

I don't understand why safari make effort to don't doing as other browsers. They don't want PWA since many time, adn now they don't implement PWA as other browsers. Safari is the new IE.

Sorry I'm pissed by their PWA implementation since many years.

We can close this issue, it's not a pdfmake problem
