### ISSUE TITLE
How can we add border above footer in pdf using datatable

### ISSUE THREAD

**Issue by nilakshibhosale** [bpampuch/pdfmake#1621]

**Comment by nilakshibhosale** [comment]
My code is like this, I have added canvas to it but not working,
`$(document).ready(function() {
    $('#example').DataTable({
        "dom": 'Bfirtlp',
        buttons: [{
            extend: 'pdfHtml5',
            exportOptions: {
                columns: [0, 1, 2],
            },
            customize: function(doc) {
                var now = new Date();
                var jsDate = now.toGMTString();
                doc['footer'] = (function(page, pages) {
                        return {
                            columns: [{
                                    alignment: 'left',
                                    fontSize: '7',
                                    text: ['Version: 1.0']
                                }, {
                                    alignment: 'center',
                                    fontSize: '7',
                                    text: ['page ', {
                                        text: page.toString()
                                    }]
                                }
                                margin: 20
                            }
                        });
                }
            }
        }]
    });
});`

**Comment by nilakshibhosale** [comment]
My code is like this,
`$(document).ready(function() {
    $('#example').DataTable({
        "dom": 'Bfirtlp',
        buttons: [{
            extend: 'pdfHtml5',
            exportOptions: {
                columns: [0, 1, 2],
            },
            customize: function(doc) {
                var now = new Date();
                var jsDate = now.toGMTString();
                doc['footer'] = (function(page, pages) {
                        return {
                            columns: [{
                                    alignment: 'left',
                                    fontSize: '7',
                                    text: ['Version: 1.0']
                                }, {
                                    alignment: 'center',
                                    fontSize: '7',
                                    text: ['page ', {
                                        text: page.toString()
                                    }]
                                }
                                margin: 20
                            }
                        });
                }
            }
        }]
    });
});`

**Comment by nilakshibhosale** [comment]
Thank you @liborm85 , its working fine

**Comment by nilakshibhosale** [comment]
Hi @liborm85 
How can we add pageborder to pdf?

**Comment by liborm85** [comment]
see https://pdfmake.github.io/docs/document-definition-object/background-layer/
