### ISSUE TITLE
Table: dontBreakRows in rowSpan with fillColor leads to visible Border

### ISSUE THREAD

**Issue by kunizial** [bpampuch/pdfmake#1622]
When combining rowSpan with fillColor it works as expected, the two or more Cells visually merge together. When using dontBreakRows, a seperating line appears between the two original cells visible as white.
Using borders on those cells doesnt seem to affect the line, as the cell with a border property is correctly taking the whole space, not just it's original.

```
  var dd = {
    "content": {
      "table": {
        "dontBreakRows": true,
        "body": [
          [
            {
              "bold": true,
              "fillColor": "red",
              "text": "Test",
              "rowSpan": 2,
              "border": [true,true,true,true]
            },
            {
              "text": "Test"
            }
          ],
          [
            "",
            "Test"
          ]
        ],
        "widths": [
          "*",
          "*"
        ]
      }
    }
  }
```

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/5f0295bc1077d0314811cac96bdd322c4e22330b (in master) and https://github.com/bpampuch/pdfmake/commit/ecf05d04bc7227a521364ad2500239f3c80ed3c2 (in branch 0.1)

**Comment by liborm85** [comment]
New version released.
