### ISSUE TITLE
Cant get the page size for printing to change to legal... i would assume its the "size" attr

### ISSUE THREAD

**Issue by ricardosaracino** [bpampuch/pdfmake#1623]
I'm not sure if this is not possible but i am trying to specify the page size when the pdf is printed.

I referred to the guide

> You can also set some options for the page, such as its size and orientation.
> The layout property can be either portrait (the default) or landscape. The size property
> can be either an array specifying [width, height] in PDF points (72 per inch), or a string
> specifying a predefined size. A list of the predefined paper sizes can be seen here. The default
> is letter.
as well as 
> https://github.com/foliojs/pdfkit/wiki/Changing-the-Document-size
to no avail. 

I just put size: "legal"  in a ton of place just trying to get it work

   ```
 const printer = new PdfPrinter({...ObservationStatementPdfService.fonts, ...{size:'legal'}});

    const pdf = printer.createPdfKitDocument({...ObservationStatementPdfService.DOC_INFO,  ...{size:'legal'}, ...ObservationStatementPdfService.getDocContent(user, observationStatement)});

```

  ```
  private static getDocContent(user, observationStatement) {
        return {
            size: 'legal',

            /* right margin is larger than the left on the sample */
            pageMargins: [17, 15, 17, 70],

            defaultStyle: {
                size: 'legal',
                fontSize: 10,
                font: 'Arial'
            },

            content: [


```

**Comment by liborm85** [comment]
How is related pdfkit guide to pdfmake?
pdfmake documentation is [here](https://pdfmake.github.io/docs/document-definition-object/page/).

**Comment by ricardosaracino** [comment]
https://github.com/bpampuch/pdfmake/issues/1623

https://pdfmake.github.io/docs/document-definition-object/page/

Ricardo Saracino

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐
