### ISSUE TITLE
Can't use custom fonts in client-side pdf generation for the bower package

### ISSUE THREAD

**Issue by pfrance99** [bpampuch/pdfmake#1625]
Hi, 
First let me thank you for your lib which was time-saver for the last 3 weeks ! 
For now i'm trying to implement a custom font in my client-side pdf generation, i read the doc and i perceive that i need to use gulp but, for the pdfmake bower package, no gulpfile is included, i got the package v0.1.5 and i currently don't understand why i don't have all necessary files present in the repository ?
Any help would be appreciated,
Paul

**Comment by liborm85** [comment]
Full code with gulp is needed only for creating own vfs files. Otherwise (in production or development) it isn't necessary.
