### ISSUE TITLE
Margin not registering on elements

### ISSUE THREAD

**Issue by shanzilla** [bpampuch/pdfmake#1627]
Margin styles aren't registering for me on certain elements and I'm not sure why. I have a custom font style defined as below.

    var styles = {
        myFont: {
            font: 'myFont',
            fontSize: 20,
            alignment: 'right',
            margin: [0, 100, 0, 0]
        }
    };

I use the style as follows:

    {
        text: "My string",
        style: ['myFont']
    }

In the resulting PDF the font, font size, and alignment are all recognized but there's no margin on the text element at all, even though margin is recognized elsewhere in the PDF using the same syntax. I also tried the following options but nothing seems to work.

    {
        text: "My string",
        style: [{margin: [0, 100, 0, 0]}]
    }
 
    {
        text: "My string",
        margin: [0, 100, 0, 0]
    }

**Comment by liborm85** [comment]
All your valid definitions tested and all is correct:

```js
var dd = {
	content: [
		{text:'First paragraph', style: ['myFont']},
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines',
		{
			text: "My string",
			margin: [0, 100, 0, 0]
		},
	],
	styles: {
		myFont: {
			font: 'Roboto',
			fontSize: 20,
			alignment: 'right',
			margin: [0, 100, 0, 0]
		},
	}
}
```

**Comment by shanzilla** [comment]
And yet I still see no margins when using that definition. Is there any other reason why it wouldn't work?

**Comment by liborm85** [comment]
On [playground](http://pdfmake.org/playground.html) works ok. See: [sample.pdf](https://github.com/bpampuch/pdfmake/files/2855740/sample.pdf)

**Comment by shanzilla** [comment]
I know it works in the playground, I tried it there myself when creating the styles. Is there anything that would interfere with margin working in my project?

**Comment by liborm85** [comment]
I don't know what's wrong with your project. Check docDefinition.

**Comment by sergable** [comment]
@shanzilla if you are working with Typescript, make sure that your docDefinition has a TDocumentDefinitions type assigned.

const docDefinition: TDocumentDefinitions = {
      content: [...]

**Comment by maganap** [comment]
@shanzilla There's a case in the [Playground -> Margins](http://pdfmake.org/playground.html) where they explicitly say inline margins do now work. Maybe that's your case:

```js
{
	stack: [
		'I\'m not sure yet if this is the desired behavior. I find it a better approach however. One thing to be considered in the future is an explicit layout property called inheritMargin which could opt-in the inheritance.\n\n',
		{
			fontSize: 15,
			text: [
				'Currently margins for ',
				/* the following margin definition doesn't change anything */
				{ text: 'inlines', margin: 20 },
				' are ignored\n\n'
			],
		},
		'Lorem ipsum dolor sit amet.\n',
		'Lorem ipsum dolor sit amet.\n',
		'Lorem ipsum dolor sit amet.\n',
		'Lorem ipsum dolor sit amet.\n',
		'Lorem ipsum dolor sit amet.\n',
	],
	margin: [0, 20, 0, 0],
	alignment: 'justify'
}		
```
