### ISSUE TITLE
 d.toFixed is not a function when using custom width and height auto for pageSize

### ISSUE THREAD

**Issue by jasminder** [bpampuch/pdfmake#1630]
Hello, 
I am using this
`pageSize: {
		width: 500.28, height: 'auto'
	}`
It throws an error :  d.toFixed is not a function

**Comment by liborm85** [comment]
This works ok:
```js
var dd = {
    pageSize: { width: 500.28, height: 'auto' },
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```

Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by jasminder** [comment]
Hello, Thanks for checking.
Yes, It works fine with playground . It gets fixed when i replace height with some static integer value. Please try below code at your local pdfmake integration . 
`var dd = {
     pageSize: {
		width: 500.28, height: 'auto'
	},
   
	content: [
	    {
	        text: 'DART',
	        style: 'header'
	        
	    },
	    '\n',
	    {
	        columns:
	        [
	            {
	        text: 'Origin: KTP',
	        style: 'subheader'
	            },
	            {
	        text: 'COD Amount: 1102',
	        style: 'subheader'
	            }
	        ]
	        },
	        {
	            text: 'Cust Code: 900480',
	            style:'subheader'
	        },
	        {
	            text: 'Cust Name:  Computers',
	            style:'subheader'
	        },
	        '\n',
	        
	        {
	            text: 'AWB: 545454545',
	            style:'subheader1'
	        },
	        '\n',
	        {
	            text: 'Address: ',
	            style:'subheader'
	        },
	        '\n',
	        {
	        columns: [
	                {
	            text: 'Weight: 0.5',
	            style:'subheader'
	                },
	                {
	            text: 'Product Type: Printer Parts',
	            style:'subheader'
	                }
	            ]
	        },
	        '\n',
	        {
	            text: 'For more shopping visit: gargcomputers.com'
	        }
	        ],
	        styles: {
	            header : {
	                fontSize : '25',
	                bold:'true'
	            },
	            subheader : {
	                fontSize : '14',
	            },
	            subheader1 : {
	                fontSize : '18',
	            }
	        }
	    
	
	
}

pdfMake.createPdf(dd).download();`

**Comment by liborm85** [comment]
Works ok local and on playground.
