### ISSUE TITLE
pdfmake conflict with file-saver

### ISSUE THREAD

**Issue by nickolas1** [bpampuch/pdfmake#1634]
In my app I am importing pdfMake and downloading a pdf like so:
```
import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake.vfs;

//create document definition here

pdfMake.createPdf(docDefinition).download(`${docTitle}.pdf`);
```
This works fine. However, after this I added a dependency to the same file-saver version used by pdfMake (^2.0.0). As soon as I 
```
import { saveAs } from 'file-saver';
```
elsewhere in my code, pdfMake silently fails downloading. Depending on an earlier version of file-saver (e.g. 1.3.8) resolves the issue, but this is not a great solution.

**Comment by talamatur** [comment]
happens to me too.
Using PDFMake 0.1.40 or 0.1.51 and file-saver 2.0.0
downgrading file-saver to 1.3.1 works for me 
duplicate/ related of #1599

**Comment by liborm85** [comment]
Is some error throwed?

**Comment by nickolas1** [comment]
@liborm85 no error, it fails silently

this does seem related to that other ticket, @talamatur. Just to be very clear on what I've found when using pdfmake ^0.1.50

- If my app does not have filemaker as a dependency, download works as expected.
- If my app depends on the same version of file-saver that pdfmake was built with, download fails. Other file-saver actions in my app still work.
- If I downgrade my app's file-saver dependency, download works. Other file-saver actions in my app work.

**Comment by tcsaddul** [comment]
Ssme here. I guess the problem is in Filesaver 2.0.0 being used twice by our app and pdfmake itself.

**Comment by nickolas1** [comment]
looking at the issues in the file-saver repo I suspect the way that package is bundled (specifically https://github.com/eligrey/FileSaver.js/issues/498) is the root cause, not an issue with pdfmake

**Comment by alexmller** [comment]
I can confirm that building pdfMake 1.5.2 (or 1.4.0) with FileSaver.js 1.3.8 make the download-function work again while building it with 2.0.0 breaks it.

There is no test setup in the FileSaver.js repository to ensure proper regression, leaving it in the dark where exactly the root cause is of this issue is.

As a workaround, I suggest to release pdfMake with 1.3.8 FileSaver.js unless there is a real need for the changes that subsequent releases incorporate.

**Comment by liborm85** [comment]
Upgraded file-saver to 2.0.1.

New version 0.1.53 released.
