### ISSUE TITLE
Getting forbidden errror while trying to make django api call from aurelia

### ISSUE THREAD

**Issue by nilakshibhosale** [bpampuch/pdfmake#1636]
I have integrated aurelia js in django project, from aurelia I am trying to hit django api but CSRF issue is coming and I am not able to get results.

My code is,

`import {inject,DOM, autoinject} from 'aurelia-framework';
import {HttpClient, json} from 'aurelia-fetch-client';

let httpClient = new HttpClient();
let tableHeading;
export class App {
  attached(){
    httpClient.fetch('/demographs/', {
      method: "POST",
      headers: {
        "X-CSRF-Token": this.getCookie("csrftoken"),
        "Accept": "application/json",
        'Cache': 'no-cache',
        "Content-Type": "application/json",
        'Cookie': 'csrftoken='+this.getCookie("csrftoken")
    },
    credentials: 'include'
    })
   .then(response => response.json())
   .then(data => {
      if(data && data.table && data.table.length) {
        tableHeading = data.table[0];
        console.log("table data",tableHeading);
      }
   });
  }
  getCookie(name) {
    let cookieValue = null;
    if (document.cookie && document.cookie != '') {
        let cookies = document.cookie.split(';');
        for (let i = 0; i < cookies.length; i++) {
            let cookie = cookies[i].trim();
            // Does this cookie string begin with the name we want?
            if (cookie.substring(0, name.length + 1) == (name + '=')) {
                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                break;
            }
        }
    }
    return cookieValue;
} 
 
}
`

Thanks

**Comment by liborm85** [comment]
How does it relate to pdfmake? I don't see use of pdfmake.

**Comment by nilakshibhosale** [comment]
Hi @liborm85 
Sorry It supposed to be in different issue but it posted here.
