### ISSUE TITLE
Build error in Angular CLI 6.

### ISSUE THREAD

**Issue by cchetan1993** [bpampuch/pdfmake#1637]
I am trying to use the snippet code- from examples (Table) 

-------------------

```
	{text: [
                       'Inlines can be ',
			{text: 'styled\n', italics: true},
			{text: 'easily as everywhere else', fontSize: 10}]
	}
```

------------------

and below is my code.

```
data_arrival['table']['body'].push(
          [{text:[
            {text:element_party+':',decoration:'underline',italics:true,fontSize:14,color:'#0c0c0c',bold:true},
            {text:' lv '+row,fontSize:10,color:'#00b050',bold:true},
            {text:'\n'+guest_count+'\n',fontSize:8,bold:false},
            {text:guest_data,fontSize:14,bold:true},
            {text:'\nLodging Notes:',fontSize:10,bold:true,color:'#C00000'}
            ],colSpan:5},{text:''},
          {text:''},{text:''},{text:''}]
        );
```

-------------------------
where i am getting following error.
![1](https://user-images.githubusercontent.com/47570684/52653542-2353ef00-2f16-11e9-977b-fa5ac418e312.jpg)

what i observed is it is referencing  italics and bold from angular core library file - resources\app\extensions\node_modules\typescript\lib\lib.es2015.core.d.ts.
![2](https://user-images.githubusercontent.com/47570684/52653539-2353ef00-2f16-11e9-8cd5-d0b28988505e.jpg)

and when i remove bold and italic from code still it don't compile the code.
![3](https://user-images.githubusercontent.com/47570684/52653794-bbea6f00-2f16-11e9-8a14-5a86c342ac27.jpg)

let me know if i am doing any thing wrong in this.

**Comment by liborm85** [comment]
You are probably wrong TypeScript definition for pdfmake. 
Here is informations about creating TS definition: https://github.com/bpampuch/pdfmake/issues/525
