### ISSUE TITLE
qr fit inside table incorrect

### ISSUE THREAD

**Issue by MeneDev** [bpampuch/pdfmake#1638]
The size of the qr code cannot be controlled precisely when used inside tables.

In this example the size "jumps" between 63 and 62.
```
var dd = {
    content: [{
        "table": {
            "widths": [
                "20%",
                "20%",
                "*"
            ],
            "body": [[
                "a\nb\nc\nd", "b",
                { "qr": "Some Text",
                    "eccLevel": "M", fit: 62 }
            ]]
        }
    }]
}

```

**Comment by liborm85** [comment]
Following example have qr inside table and not inside table. And and both are same. Where is problem?

```js
var dd = {
    content: [{
        "table": {
            "widths": [
                "20%",
                "20%",
                "*"
            ],
            "body": [[
                "a\nb\nc\nd", "b",
                { "qr": "Some Text",
                    "eccLevel": "M", fit: 62 }
            ]]
        }
    },
    ' ',
    { "qr": "Some Text",
                    "eccLevel": "M", fit: 62 }
    ]
}
```

**Comment by AnuradhaSharma000111** [comment]
var dd = {
    content: [{
        "table": {
            "widths": [
                "20%",
                "20%",
                "*"
            ],
            "body": [[
                "a\nb\nc\nd", "b",
                { "qr": "Some Text",
                    "eccLevel": "M", fit: 68 }
            ]]
        }
    }]
}

//Hi MeneDev,
//only you need to maximize the fit size.

**Comment by MeneDev** [comment]
My mistake. I expected a slight increase when using 63 rather than 62, but it seems it always "jumps".
What I wanted was to make the QR as big as the four lines of text. But I can only make it slightly bigger or smaller.

**Comment by liborm85** [comment]
Sizes are adjusted to "qr grid size".
