### ISSUE TITLE
Dependency Vulnerability for static-eval

### ISSUE THREAD

**Issue by jpldevpub** [bpampuch/pdfmake#1639]
The dependency **static-eval** has been flag with a security warning on [snyk](https://snyk.io/?utm_campaign=brand&utm_medium=search&utm_source=google&gclid=CjwKCAiAwJTjBRBhEiwA56V7q9w9azLzYX_jyC1_ZYOCs7fhwa5gZN6MvgSDcebgsOQP_9jqXl2x0hoCu_8QAvD_BwE)

**An issue has been raised on the [static-eval](https://github.com/substack/static-eval/issues/20) repo**
Thanks @pocesar

[**MODERATE Sandbox Breakout / Arbitrary Code Execution Vulnerability**](https://npmjs.com/advisories/758)

**Advisory Published** - Feb 14th, 2019

**Reported** - Jan 3rd, 2019

**Question**
Is this package essential?
Is there an Alternative?

**p.s Love pdfmake! Keep up the good work.**

**Comment by liborm85** [comment]
static-eval is used in brfs. brfs in pdfmake is used only in development for building pdfmake.
In production pdfmake is not brfs and static-eval used.

**Comment by riyazpanarwala** [comment]
Can you not remove it in development too ?  Just curious

**Comment by liborm85** [comment]
No, it is not possible. brfs library is needed.

**Comment by mclark-newvistas** [comment]
`npm` isn't warning us about the dev dependency, but the production dependency on `linebreak` which itself depends on `brfs` which depends on `static-module` which depends on `static-eval`. I've opened an issue in foliojs/linebreak#12.
