### ISSUE TITLE
Having problem to dowload multiple files

### ISSUE THREAD

**Issue by rahulpanteon** [bpampuch/pdfmake#1640]
Try to download multiple PDF but it has different behavior on all browsers. Look at the below fiddle It should download  50 files but sometimes it downloads 10, sometimes 15.
https://jsfiddle.net/6e43njmg/1/

**Comment by liborm85** [comment]
Normally it is not possible, you can try this hack: https://github.com/bpampuch/pdfmake/issues/410#issuecomment-269641001
