### ISSUE TITLE
Custom Table of Contents

### ISSUE THREAD

**Issue by kavin404** [bpampuch/pdfmake#1642]
I want to build a Table of content as shown below. How can I do it?
![custom toc](https://user-images.githubusercontent.com/26364290/52991251-e914b100-3431-11e9-8509-5710b9795e1a.PNG)

**Comment by liborm85** [comment]
You can create only manually with `textReference` and `pageReference`, see example: https://github.com/bpampuch/pdfmake/blob/0.1/examples/pageReference.js
