### ISSUE TITLE
Dropdown filters are coming into pdf

### ISSUE THREAD

**Issue by nilakshibhosale** [bpampuch/pdfmake#1645]
How to remove dropdown filter select values from header while export to excel and pdf.

I am using this custom code,
`initComplete: function () { this.api().columns().every( function () { var column = this; var eachHeader = $(column.header())[0]; var headingVal = eachHeader.getAttribute("value"); var select = $('<select><option value="">'+ headingVal +'</option></select>') .appendTo( $(column.header()).empty() ) .on( 'change', function () { var val = $.fn.dataTable.util.escapeRegex( $(this).val()); column .search( val ? '^'+val+'$' : '', true, false ) .draw(); } ); column.data().unique().sort().each( function ( d, j ) { select.append( '<option value="'+d+'">'+d+'</option>' ) } ); } ); }`

**Comment by nilakshibhosale** [comment]
Hello @bpampuch 

Can you help me on this issue?

**Comment by liborm85** [comment]
How does issue relate to pdfmake?

**Comment by nilakshibhosale** [comment]
While generating pdf it includes all the options of dropdown

[https://jsfiddle.net/nilakshibhosale/4skdq2r3/6/](url)

**Comment by liborm85** [comment]
Is not related to pdfmake, use DataTable support.

**Comment by nilakshibhosale** [comment]
Ok Thanks

**Comment by kulshrestha97** [comment]
Hi @nilakshibhosale I am having the same problem, did you find anything on it?
