### ISSUE TITLE
How to align Table in pdf center

### ISSUE THREAD

**Issue by nilakshibhosale** [bpampuch/pdfmake#1646]
How can I align table in center

**Comment by liborm85** [comment]
see https://github.com/bpampuch/pdfmake/issues/72#issuecomment-52410869

**Comment by nilakshibhosale** [comment]
Where to add this code,

My code is like:

`$('#example').DataTable( {
        "dom": 'Bfirtlp',
        buttons: [

                {
                extend: 'excelHtml5',
                exportOptions: {
                    columns: ':visible'
                }
                },
            {
                extend: 'pdfHtml5',
                orientation: 'landscape',
                pageSize: 'A3',
                exportOptions: {
                    columns: [ 0, 1, 2,3,4,5,6,7,8],

                },
            customize: function (doc) {
            var tblBody = doc.content[1].table.body;
                for(var i=0;i<tblBody[0].length;i++){
                  tblBody[0][i].fillColor = '#FFFFFF';
                  tblBody[0][i].color = 'black';
                }
                   var now = new Date();
		    var jsDate = now.toGMTString();
		    doc['footer']=(function(page, pages) {
							return [
							{canvas: [ { type: 'line', x1: 10, y1: 15, x2: 1190-10, y2: 15, lineWidth: 
                    1,color:'black' } ]},
							{
							columns: [

									 {
										alignment: 'left',
										fontSize:'7',
										text: ['Version: 1.0'],
									},
									{
										alignment: 'center',
										fontSize:'7',
										text: ['page ', { text: page.toString() }]
									},
									{
										alignment: 'right',
										fontSize:'7',
					 					text: ['Generated on: ', { text: jsDate}]
									},

								],
								margin:10

							},
							]
						});

						var objLayout = {};
						objLayout['hLineWidth'] = function(i) { return .5; };
						objLayout['vLineWidth'] = function(i) { return .5; };
						objLayout['hLineColor'] = function(i) { return '#aaa'; };
						objLayout['vLineColor'] = function(i) { return '#aaa'; };
						objLayout['paddingLeft'] = function(i) { return 4; };
						objLayout['paddingRight'] = function(i) { return 4; };
						doc.content[1].layout = objLayout;
                                                doc.content[1].margin = [ 5, 0, 5, 5 ];
            }
            }
        ],
        }
    } );`

**Comment by liborm85** [comment]
That's some DataTable library use DataTable support.

**Comment by ontheterra** [comment]
Just use '*' instead of int in widths option, and you are good to go

**Comment by namik7** [comment]
BTW you can always use margins to push your table to center or whichever corner you need.
And i think this is the easiest way to do that.
