### ISSUE TITLE
Pdfmake issue after build using Pkg

### ISSUE THREAD

**Issue by enikshepa** [bpampuch/pdfmake#1647]
I have installed pdfmake for my project and its working fine. After build the project using pkg(https://github.com/zeit/pkg), i am getting the below error.

**\node_modules\unicode-properties\data.trie' was not included into executable at compilation stage. Please recompile add**

**Comment by liborm85** [comment]
Libraries `fontkit`, `unicode-properties`, `linebreak` use external files which probably pkg not included to package.

Pdfmake using `brfs` for including this external files (see [webpack config](https://github.com/bpampuch/pdfmake/blob/6258bd20d7bcfa58fa087f03e64d02a5bf6e09b6/webpack.config.js#L112-L114)). Probably is necessary something like that do in pkg.

**Comment by enikshepa** [comment]
Thank you. Started working after including the above mentioned libraries.

**Comment by kamleshkarwande** [comment]
can you share how you mentioned the libraries and where?

**Comment by enikshepa** [comment]
Excluded the above mentioned libraries in pkg section.
