### ISSUE TITLE
Very long loading time in IE 11

### ISSUE THREAD

**Issue by helix0r** [bpampuch/pdfmake#1649]
Hello! 

After updating from 0.1.37 to 0.1.53 we are experiencing very long loading times and high CPU usages in Internet Explorer 11. It is nearly impossible to work with the system when the pdfmake file is included on a page. I made two performance trackings with the devtools to find the problem:

Loading with version 0.1.53:

![screenshot-2](https://user-images.githubusercontent.com/12292568/53162905-4729cb80-35cd-11e9-8f12-7c5cb3d54e9a.png)

Loading after going back to 0.1.37:

![screenshot-1](https://user-images.githubusercontent.com/12292568/53162893-43964480-35cd-11e9-8f1c-4d62ecedb129.png)

Do you have any idea what might have happened in between?

Thanks in advance, best regards
Tobias

**Comment by blikblum** [comment]
Maybe https://github.com/foliojs/pdfkit/issues/929 ?

**Comment by DonNicoJs** [comment]
We reverted to 1.40 and now it seems fine, for us it was crashing the page altogether.

**Comment by liborm85** [comment]
Attach simple example for reproduce performance issue.

**Comment by DonNicoJs** [comment]
@liborm85 I am not near my IE 11 pc but this should do the trick, just open it with IE 11 / edge
https://mqrnqpo339.codesandbox.io/
I can post a better example in the evening

**Comment by liborm85** [comment]
@DonNicoJs Your example throw syntax error in IE 11. And in Chrome is displayed Generate button that do nothing... and source codes cannot be easily obtained.

I need some example of pdfmake docDefinition runnable ideally on [playground](http://pdfmake.org/playground.html) (eventually on [jsfiddle](https://jsfiddle.net/)).

**Comment by DonNicoJs** [comment]
@liborm85 https://codesandbox.io/s/mqrnqpo339 it's a codesandbox so the source code is available on the link. there is no need for a docDefinition in ie11 with the latest version just importing pdfMake in a complex page is enough to freeze it

**Comment by liborm85** [comment]
Tested with IE 11 on Windows 10:

0.1.37 (duration 254 ms):
![screen-pdfmake-0 1 37](https://user-images.githubusercontent.com/1298652/55679303-670d1880-5909-11e9-9e08-ab03ada043bd.png)

0.1.54 (duration 206 ms):
![screen-pdfmake-0 1 54](https://user-images.githubusercontent.com/1298652/55679306-72604400-5909-11e9-8d47-5aa5660938a1.png)

Loading time with 0.1.37 is 254 milliseconds and with 0.1.54 is 206 milliseconds.
Time and workload is similar (respectively 0.1.54 is faster). I don't see any slowdown.
