### ISSUE TITLE
Image with fixed width depends on browser window size

### ISSUE THREAD

**Issue by Askirkela** [bpampuch/pdfmake#1650]
I'm trying to generate a PDF, got the format I want but cannot figure out why **this**
``
{
    image: dataurl,
    alignment: 'center',
    width: 375.0
}
``
**or**
``
{
    image: dataurl,
    alignment: 'center',
    width: 375,
    height: 450
}
``
**or even**
``
{
    image: dataurl,
    alignment: 'center',
    fit: [375, 450]
}
``
doesn't fix the size of the image in my PDF.

When resizing the browser window between PDF generations, the image is of different sizes

Any hints?

**Comment by liborm85** [comment]
Set zoom 100% in pdf viewer. Usually page is adapts to window.

**Comment by Askirkela** [comment]
Thanks for the reply, but I may have phrased it badly.

As I understand it, the unit used in pdfmake is the point, which is a fixed unit.
The other parts of my template **does not depend on the size** of the window when generating my pdf, but **the image size does**.

I can't post images right now to illustrate, but this may help visualize my issue :
Generating the pdf it gives a layout like this
```
-------------------------
|         this is fixed |
|                       |
|that too               |
|                       |
|          ____         |
|         |    |  image |
|         |____|        |
|                       |
|_______________________|
```
When changing **only** the size of the browser window (calling the same `generate` function again), the image becomes larger
```
-------------------------
|         this is fixed |
|                       |
|that too               |
|                       |
|          ____         |
|         |    |  image |
|         |    |        |
|         |____|        |
|_______________________|
```

I don't understand the behavior since all the other parts of my template are fixed.

Sorry if I explained poorly before.

**Comment by liborm85** [comment]
Attach example runnable on [playground](http://pdfmake.org/playground.html) or [jsfiddle](https://jsfiddle.net/) for reproduce issue.

**Comment by Askirkela** [comment]
Well... Shame on me...
After hours trying to recreate the issue, turns out my problem comes from me misusing html2canvas...

At least I can say that pdfMake works as intended in this case.
Thanks anyway.

**Comment by bgb0349** [comment]
I'm using html2canvas with pdfMake to export html to pdf, how can I zoom the image to 100%, I want that when i open the pdf,
i will open in all the screen.

**Comment by bgb0349** [comment]
I'm using html2canvas with pdfMake to export html to pdf, how can I zoom out the image to 100%?
What I mean is that when I open the pdf in any browser or Acrobat reader, it will open widely.
