### ISSUE TITLE
Dealing with very large data sets (5000+ pages)

### ISSUE THREAD

**Issue by janteque** [bpampuch/pdfmake#1652]
I need to print server side a pdf with a dataset that can be very large (+70.000 items) Beyond the futility of creating such a PDF, we still need to deal with the requirement

. I've made a test but I get a "heap out of memory" error when dealing with more than 10.000 items (being the size of the PDF around 30Mb). 

Is there any way of dealing with this kind of datasets?

I attach the test file. With these results on my machine:
[perf-test.zip](https://github.com/bpampuch/pdfmake/files/2900965/perf-test.zip)

```

2000 Items: 29523.849ms
Final memory read_only_space available size : 480400
Final memory new_space available size : 14854880
Final memory old_space available size : 66693896
Final memory code_space available size : 180320
Final memory map_space available size : 1358312
Final memory large_object_space available size : 1110449664

4000 Items: 65955.951ms
Final memory read_only_space available size : 480400
Final memory new_space available size : 9461368
Final memory old_space available size : 133466648
Final memory code_space available size : 194720
Final memory map_space available size : 1370456
Final memory large_object_space available size : 778509824

8000 Items: 129494.327ms (4000 pages, 17.4 Mb)
Final memory read_only_space available size : 480400
Final memory new_space available size : 12845336
Final memory old_space available size : 135523072
Final memory code_space available size : 132544
Final memory map_space available size : 1372392
Final memory large_object_space available size : 248978944

10000 Items: 245324.167ms (5000 pages, 21.7 Mb)
Final memory read_only_space available size : 480400
Final memory new_space available size : 6610888
Final memory old_space available size : 101554736
Final memory code_space available size : 581632
Final memory map_space available size : 854256
Final memory large_object_space available size : 22552064

12000 Items -> FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
```

**Comment by janteque** [comment]
I just saw this merge request that might be perfect for solving my issue: 

[https://github.com/bpampuch/pdfmake/pull/1362](https://github.com/bpampuch/pdfmake/pull/1362)

Any idea if this feature could be finally implemented?

**Comment by liborm85** [comment]
In version 0.1.55+ you can disable cache via `fontLayoutCache` option.
Example:
`printer.createPdfKitDocument(docDefinition, { fontLayoutCache: false });` on server-side and `pdfMake.createPdf(docDefinition).download('document.pdf', null, { fontLayoutCache: false });` on client-side

[link to documentation](https://pdfmake.github.io/docs/options/)
