### ISSUE TITLE
Importing pdfmake breaks the IE developer console

### ISSUE THREAD

**Issue by JamesSeymour** [bpampuch/pdfmake#1653]
It seems if I import the pdfmake library into my project it subtly breaks the IE developer console. I am using the latest version 0.1.53 with Internet Explorer 11.

I import the library into my code as follows:

`import pdfMake from "pdfmake/build/pdfmake";`

After this has been imported, it is impossible for me to get correct output from the IE developer console. 

For example, prior to the import, I can just type `document`, and the document is returned:

![pdfmake_not_imported](https://user-images.githubusercontent.com/3268617/53348505-102c2080-3913-11e9-9929-5650f8fbb65b.png)

After I import I do exactly the same in the console, but the return is undefined:

![pdfmake_imported](https://user-images.githubusercontent.com/3268617/53348555-2934d180-3913-11e9-88a3-97294ac6499a.png)

Other browsers I have tested seem to be fine, but IE11 really does not like this.

**Comment by JamesSeymour** [comment]
This can even be reproduced on your playground site (http://pdfmake.org/playground.html)

This really seems to cause a problem to the browser. I think it actually breaks the developer console, as once you navigate to other sites after this has occurred it still happens. It isn't fixed until you restart the browser.

**Comment by supernes** [comment]
We're seeing the same issue, had to revert to version 1.40, which was the last confirmed compatible with our IE11 build.

It's not just that the developer console breaks and things like `window` are undefined - we're having issues with event handlers not firing and other invisible ways in which our application breaks.

The defects started appearing after updating from 1.40 to 1.51. Our setup is basically CRA + babel + react-app-polyfill

```
@babel/core: 7.3.3
@babel/plugin-transform-runtime: 7.2.0
@babel/preset-env: 7.3.1
@babel/runtime-corejs2: 7.3.1
babel-preset-react-app: 7.0.1
react-scripts: 2.1.5
react-app-polyfill: 0.2.1
```

**Comment by liborm85** [comment]
@supernes Only developer console is breaks in IE11. `window` works correctly in app scripts, including `console.log(window);`. If you have other problems it is necessary create new issue and describe them (including some functional demos).

**Comment by supernes** [comment]
Thank you for the reply.

Since this seems to be a fringe case and an incompatibility within our dependency tree, we've decided it would be best to migrate to another solution for generating PDF files.

**Comment by liborm85** [comment]
I didn't find reason why console stops working in IE.

**Comment by liborm85** [comment]
Tested with latest (0.1.69) pdfmake version and I don't know why, but works ok now:
![image](https://user-images.githubusercontent.com/1298652/103289352-44793800-49e7-11eb-9687-ae05ea13b9a4.png)
