### ISSUE TITLE
Two tables inline with gap/whitespace in between

### ISSUE THREAD

**Issue by matthew2564** [bpampuch/pdfmake#1660]
Hi,

I am new to using pdfmake and although this is not an issue, I was hoping someone could help me with my dilemma. I am basically trying to replicate a table that looks like this?

Thank for any help!

![screenshot 2019-03-01 at 4 46 36 pm](https://user-images.githubusercontent.com/33056264/53652829-b2b11000-3c41-11e9-85a4-7c0f8a80ec11.png)

**Comment by liborm85** [comment]
You can make two columns and into each column add table.

Examples for columns is here: [playground](http://pdfmake.org/playground.html) > tab _COLUMNS_
Examples for tables is here: [playground](http://pdfmake.org/playground.html) > tab _TABLES_
