### ISSUE TITLE
Uncaught RangeError: Source is too large

### ISSUE THREAD

**Issue by asveloper** [bpampuch/pdfmake#1661]
version 0.1.53

**Comment by liborm85** [comment]
Provide details...

**Comment by asveloper** [comment]
i am passing it base64 image and getting this error, what other details do you want?

**Comment by liborm85** [comment]
Some description of issue... Especially example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html) or [jsfiddle](https://jsfiddle.net/).
