### ISSUE TITLE
TOC links are wrong using dontBreakRows in table

### ISSUE THREAD

**Issue by filippomuscolino** [bpampuch/pdfmake#1662]
Hi,
try this: 
- create a table with dontBreakRows:true
- add a long content inside a cell, and set tocItem: true to this content
If the row containing that cell goes to new page, the page reference in toc is wrong.

Seems that the page reference is calculated not taking in account dontBreakRows (maybe it should be calculated after the table is rendered?)

Is there any solution?
Thanks!

**Comment by liborm85** [comment]
duplicate with: https://github.com/bpampuch/pdfmake/issues/1288

Fixed here: https://github.com/bpampuch/pdfmake/issues/1288#issuecomment-471032577
