### ISSUE TITLE
JS error loading in IE9

### ISSUE THREAD

**Issue by DataTables** [bpampuch/pdfmake#1663]
I know pdfmake doesn't support IE9, but if it is included on the page at all, it throws a JS error:

> Uint16Array is undefined

Would it be possible to do a quick feature check for more modern APIs before attempting to run the code? #453 did that for `Object.keys`. Can that be expanded to also check for `window.Uint16Array`?

**Comment by liborm85** [comment]
Implemented lazy loading for printer and added check for support Uint16Array by https://github.com/bpampuch/pdfmake/commit/d20f9ec1153bcdc7c857dd40b8b786f8ff571edc for browser.

**Comment by liborm85** [comment]
Released in 0.1.54.
