### ISSUE TITLE
Can't find variable: HTMLAnchorElement

### ISSUE THREAD

**Issue by dancomanlive** [bpampuch/pdfmake#1664]
https://snack.expo.io/@dancoman/cGRmbW

**Comment by PatrickCavalcanti** [comment]
Any solution?

**Comment by liborm85** [comment]
`HTMLAnchorElement` uses FileSaver, see [FileSaver.js/src/FileSaver.js#L74](https://github.com/eligrey/FileSaver.js/blob/4a73fd7a2dcdc6ce2947433af3d3fbad56a019fa/src/FileSaver.js#L74).
Must be fixed in [FileSaver](https://github.com/eligrey/FileSaver.js).

**Comment by liborm85** [comment]
Temporary fixed in pdfmake by commit https://github.com/bpampuch/pdfmake/commit/d3cf46ad635bf02b35a05d85ea18491a8ccd5547 (in master) and https://github.com/bpampuch/pdfmake/commit/5ca04b8959c11e96fb79684aaa9844ce9214db93 (in 0.1 branch).

**Comment by liborm85** [comment]
Created PR for FileSaver.js: https://github.com/eligrey/FileSaver.js/pull/533

**Comment by liborm85** [comment]
Released with temporary bugfix in 0.1.54.
