### ISSUE TITLE
Show Chinese fonts in pdfMake

### ISSUE THREAD

**Issue by suhasbhattu** [bpampuch/pdfmake#1666]
I want to use Chinese fonts in the pdfMake. I have used Google Noto font `NotoSansCJKsc-Regular.ttf` but this is not working.

```
pdfMake.fonts = {
      NotoSansCJKscRegular: {
            normal: "NotoSansCJKsc-Regular.ttf"
      }
};

var docDefinition: {
    content: [
        {
            text: "通用规范汉字表",
            font: "NotoSansCJKscRegular"
        }  
    ]
};

pdfMake.createPdf(docDefinition).download();
```
It somehow looks like this:
![untitled](https://user-images.githubusercontent.com/25226718/53950664-af5ece00-40f2-11e9-99d4-7dda8adb5fe5.png)

What is the reason? I have added the base64 of font in the `vfs_fonts.js` too.

**Comment by liborm85** [comment]
I'm tested your use case and output is:
![chinese](https://user-images.githubusercontent.com/1298652/54070472-ac81eb80-4260-11e9-807b-3a03d2bf423a.png)

You have a mistake somewhere.
Instructions are here: https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/

What version of pdfmake are you using?

**Comment by sanshuiwang** [comment]
> I'm tested your use case and output is:
> ![chinese](https://user-images.githubusercontent.com/1298652/54070472-ac81eb80-4260-11e9-807b-3a03d2bf423a.png)
> 
> You have a mistake somewhere.
> Instructions are here: https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/
> 
> What version of pdfmake are you using?

Please show your odfmake version，I used "pdfmake": "^0.1.54"
