### ISSUE TITLE
Downloading the created PDF changes positioning of shapes.

### ISSUE THREAD

**Issue by Janooba** [bpampuch/pdfmake#1669]
I've tested this with both lines and rects. Once you download the pdf, the positioning of these shapes gets distorted.

You can reproduce this in the playground using the following code:

```javascript
var dd = {
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines',
		{
          canvas: [
            {
              type: 'line',
              x1: 0, y1: 5,
              x2: 520, y2: 5,
              lineColor: '#8CC63E'
            }
          ]
        }
	]
	
};
```

Adding the following code to the end changes the positioning of the line significantly:
`pdfMake.createPdf(dd).download();`

I've reproduced this using Firefox, Chrome, and IE

**Comment by liborm85** [comment]
`docDefinition` can be used only once. If you need to generate multiple times is need clone/copy original `docDefinition` and it pass into pdfmake. See https://github.com/bpampuch/pdfmake/issues/1576
