### ISSUE TITLE
[Propose] Missing styles

### ISSUE THREAD

**Issue by lvarayut** [bpampuch/pdfmake#167]
There are `bold`, `fontSize`, and `alignment`. However, there are a lot of important styles missing here, such as, `underline`, `border`, `draw rectangular`, `draw a single line`, and etc.

**Comment by jthoenes** [comment]
We have currently no capacity to work on this. But I can point you to the places you would need to touch, to create a pull request.

Want to give it a try?

**Comment by YidingW** [comment]
@jthoenes  I want to add a single line style, similar to <hr/> does. Can you point the place for the style? 

Thanks

**Comment by jthoenes** [comment]
Sure:

you will need to add methods to ``docMeasure`` and ``layoutBuilder`` - these methods need to be wired up in the ``processNode`` methods of both. 

Don't forget to write test and run the existing one's, so we know everything is still working.

**Comment by liborm85** [comment]
Text decorations are available, see [example](https://github.com/bpampuch/pdfmake/blob/master/examples/textDecorations.js).
