### ISSUE TITLE
Auto-replacement of text to columns

### ISSUE THREAD

**Issue by ninbit** [bpampuch/pdfmake#1674]
In pdfMake, there is a static option for adding texts to columns. For example, you put your text with the definition of a column. Is it possible to just say pdfMake that 'I want to have two columns on the page, you just distribute the text accordingly'? 

As for now, if the text added to a column exceeds the page, it continues from the next page. But I want it to continue from the second column of the same page.

Any solutions?

**Comment by liborm85** [comment]
Feature request is here: https://github.com/bpampuch/pdfmake/issues/604
