### ISSUE TITLE
Setting custom size will change the page orientation.

### ISSUE THREAD

**Issue by zer09** [bpampuch/pdfmake#1675]
I am trying to create pdf that half of the letter size paper, but when setting the width to 612 and the height the to 396 it will cause the page orientation to become in landscape mode. And this will cause invalid result when printed to paper.
![Screenshot from 2019-03-18 13-28-23](https://user-images.githubusercontent.com/780780/54509298-15194880-4984-11e9-9d5f-079ebc85fa65.png)

Now when I tried to specify the page orientation to portrait, it does automatically swap the values of height and width, as seen on the image below.
![Screenshot from 2019-03-18 13-29-28](https://user-images.githubusercontent.com/780780/54509395-5f9ac500-4984-11e9-8f2a-3eded952eb52.png)

Now I tried to swap the value of the height and width on the code, to see if it will make difference, but still the result is not expected.
![Screenshot from 2019-03-18 13-32-42](https://user-images.githubusercontent.com/780780/54509495-b30d1300-4984-11e9-96d3-3ec6e30fdc62.png)

Am I missing something here?
It look like that the page orientation will change based on paper size, but if you explicitly set the page orientation it will also swap the values of the height and width based on page orientation. I think this should not happen.

**Comment by liborm85** [comment]
I found a nice description of difference between landspace and portrait in [this article](http://www.differencebetween.info/difference-between-landscape-and-portrait), citation:

> **_Landscape_**
> A picture or photo of a piece of land
> A document that is **wider than it is taller**

> **_Portrait_**
> A picture or photo of a person
> A document that is **taller than it is wider**

If value is specified in element `pageOrientation`, pages are automatically rotated to this value (`landspace` or `portrait`) according to sizes in `pageSize`.
If you don't want automatic page rotation rotation, do not enter element `pageOrientation`.

**Comment by zer09** [comment]
> If you don't want automatic page rotation rotation, do not enter element `pageOrientation`.

Yes, that was the case on the first image, I didn't set the ```pageOrientation``` so I was expecting it to be in portrait, but it was automatically rotated to landscape.

**Comment by liborm85** [comment]
In first image is width 612.4 and height 396.9 which means - page is wider than it is taller, which is landspace.
If you want a portrait must page taller than it is wider, must be set width 396.9 and height 612.4.

**Comment by zer09** [comment]
Thanks for the advice, I found a way to do it using the standard ```letter``` paper size
