### ISSUE TITLE
download method not working, while open and print are working fine

### ISSUE THREAD

**Issue by brunompbarbosa** [bpampuch/pdfmake#1676]
Hello all,

i've used pdfmake before on a similar project, and was able to have it working sucessfully.

However, i now have an issue which i cannot understand - i'm able to use the open() and print() methods without a problem, but am unable to get it to work with the download method.

When i run it, nothing happens, and the only output i have on the console is:

"[Violation] 'setTimeout' handler took ***ms"

if i console.log the document definition on the console after running one of those methods, it runs it returns the object as expected, but with the download method nothing happens suggesting that the script stops at the method, but there are no errors (other than the violation mentioned above).

Can anyone point me in the right direction as to what could be different between the methods that can be causing this behaviour?

Unfortunately i very much need the download method to be working on this project because of adblockers :|

Best regards,
Bruno

**Comment by liborm85** [comment]
Is "download" on [playground](http://pdfmake.org/playground.html) working?

And add these informations:
- pdfmake version
- browser name and version
- os name and version

**Comment by brunompbarbosa** [comment]
Download is working on playground.

It happened on Chrome, Firefox, and Safari

was using pdfmake version 0.1.50, and updated to 0.1.54.

It seems to be working now, but i'm not sure if it was because of the update or any minor change i may have made in testing.

Most likely it was an issue with my code.

Thanks anyway!
