### ISSUE TITLE
Rows colorizing in header`s color in IE11

### ISSUE THREAD

**Issue by SkripalBoris** [bpampuch/pdfmake#1677]
In the case when the line height exceeds the tables bodys height, when making a transfer, the subsequent parts of the line are painted in the color of the tables header (only in IE 11. Version to reproducing: 0.1.54)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [plaground](https://github.com/bpampuch/pdfmake).

**Comment by SkripalBoris** [comment]
Unfortunately, local example dont reproducing into playground. Maybe real reason is in fonts (OpenSans used or anything else).
