### ISSUE TITLE
Stack fill colour overrides nested table fill colour 

### ISSUE THREAD

**Issue by jonathanchrisp** [bpampuch/pdfmake#1678]
## Overview 
If you have a nested table within a stack the fillColor property of the stack overrides the table's fill colour. Is this a bug or expected behaviour?

## Steps to replicate 
Use the following definition in the playground: 

```
// playground requires you to assign document definition to a variable called dd

var dd = {
	content: [{
			table: {
				body: [
					['Column 1'],
					[
						{
						    fillColor: 'blue',
							stack: [
								'Should the table be blue or green??',
								{
    							    layout: {
    							      fillColor: () => 'green',
    							    },
    								table: {
    									body: [
    										['Col1', 'Col2', 'Col3'],
    										['1', '2', '3'],
    										['1', '2', '3']
    									]
    								},
    							}
							]
						}
					]
				]
			}
		}
	]
}
```

![Screen Shot 2019-03-21 at 11 20 55 am](https://user-images.githubusercontent.com/406799/54727354-72530b00-4bcb-11e9-9cf2-b262567b8494.png)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1223
