### ISSUE TITLE
Footer does't display when pageSize property set to custom width and height

### ISSUE THREAD

**Issue by BMNTeam** [bpampuch/pdfmake#1679]
I come across with problem where I want to add footer to a page with custom size, and then footer doesn't display.

```
...
        footer: {
          columns: [
            'Left part',
            { text: 'Right part', alignment: 'right' }
          ]
        },
        pageSize: {
          width: 54 / 0.35277,
          height: 40 / 0.35277
        },

        defaultStyle: {
          fontSize: 9
        },
        pageMargins: [2, 2 , 2 , 2]
...
```
But if I use default pageSize and pageMargins everything works perfectly.

**Comment by liborm85** [comment]
In your definition is height 2 points to footer. Increase bottom value in `pageMargins` (it is last number).
