### ISSUE TITLE
Problem generating fonts with GUNT from .ttf to export PDF with HTML icons

### ISSUE THREAD

**Issue by greatnews** [bpampuch/pdfmake#1680]
Hi, everyone. I'm working in an ASP .NET Project where we use JQuery Datatables. We implemented the export to PDF function. It's working fine.
The problem I'm facing now is I cannot export HTML icons to PDF. 
I'm following the steps described here https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/#1-create-a-new-vfs-fonts-js-containing-your-font-files
I run
`npm install`
but I'm having problems when I want to execute 
`gulp buildFonts`
I don't get if I do have to define the 'buildFonts' task myself. It says clearly 'you can update gulpfile.js to change the base directory path or to add an alternative config for the buildFonts task'. 
I've tried the two scenarios. Defining my own 'buildFonts' task following https://www.npmjs.com/package/gulp-font like

```
var gulp = require('gulp');
var gulpFonts = require('gulp-font');

gulp.task('buildFonts', function(){
    return gulp.src('examples/fonts/fontawesome/**/*.ttf') //also tried /*.{ttf, otf, worff}
        .pipe(gulpFonts({
            ext: '.css',
            fontface: 'examples/fonts/fontawesome/**', //here I tried lots of variants
            relative: '/assets/fonts/fontawesome/**', //here I tried lots of variants
            dest: 'dist/',
            embed: ['woff'],
            collate: false
        }))
        .pipe(gulp.dest('dist/'))
});
```

and not defining it

```
var gulp = require('gulp');
var gulpFonts = require('gulp-font');

gulp.task('buildFonts', function(){
    return gulp.src('examples/fonts/fontawesome/**/*.ttf') //also tried /*.{ttf, otf, worff}
        .pipe(gulpFonts())
        .pipe(gulp.dest('dist/'))
});
```
When I execute both of them with 'gulp buildFonts' it prints out:
```
[08:05:04] Using gulpfile ~\Documents\Proyectos-test\gulp\gulpfile.js
[08:05:04] Starting 'buildFonts'...
[08:05:04] Finished 'buildFonts' after 163 ms
```
I go to the dist folder but there's no JS file (actually, it's empty).

**Comment by liborm85** [comment]
All necessary steps are described in [documentation](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/), there is no need to create anything else.

When you run on the cloned repository `npm install` and `gulp buildFonts` so does/write what? Any error? Describe what happens.
