### ISSUE TITLE
require('pdfmake') takes longer than usual

### ISSUE THREAD

**Issue by dfloresgonz** [bpampuch/pdfmake#1684]
**Problem:**
Creating the pdf is fast
requiring the module takes more than 3 seconds.

var pdfDoc  = require('pdfmake');// <---------- this lines takes more than expected

**Notes:**
1. In my local PC it works as expected
2. When I upload my code to AWS Lambda it takes more than 3 seconds.
3. I lowered to 2 seconds by increasing my Lambda memory to 900MBs
4. Version is: 0.1.54

**Comment by blikblum** [comment]
I bet is related to encryption support in pdfkit. I would test the versions just before and after the upgrade to pdfkit 0.9

**Comment by liborm85** [comment]
If pdfmake works in your local pc as expected, then there will be performance problem in Amazon. You can try to explore it.

**Comment by PatrickCavalcanti** [comment]
This is very slow in my project in ReactNative,
from 10 to 30 seconds depending on the device. But creating the pdf is fast
