### ISSUE TITLE
Printing PDF in --kioskmode should keep the same html page on the browser

### ISSUE THREAD

**Issue by afilp** [bpampuch/pdfmake#1686]
I want to print in `kiosk mode` so that no modal Dialogs appear when pressing the `print` button for the a PDF to be printed.

This is how the kiosk mode is done:
https://stackoverflow.com/questions/21073959/print-without-confirmation-on-google-chrome

The problem in `pdfmake` is that I did not find a way for the created `blob` not to open and take the place of my html page when using the `window` param?

`pdfMake.createPdf(docDefinition).print({}, window);`

The user cannot go back, I would like to happen automatically.

What is a solution to this?

**Comment by afilp** [comment]
I think I a solution like this works:

```
    const win = window.open('', "tempWinForPdf");
    pdfMake.createPdf(docDefinition).print({}, win);
    win.close();
```

Do you find any problems with this solution? 

I tested it and seems to have printed the PDF while also closing the extra window (tab).

**Comment by liborm85** [comment]
If it works so it is ok.

**Comment by Sonny13** [comment]
had to add a 1 sec delay otherwise the printer would not start to print

this will show the preview of the pdf briefly. 
```
     const win = window.open('', "tempWinForPdf");
     pdfMake.createPdf(docDefinition).print({}, win);
     setTimeout(function() {
           win.close();
     }, 1000);
```

Tested with Chrome Kiosk mode (--kisok) and Kiosk printing (--kiosk-printing) enabled
