### ISSUE TITLE
Pdfmake taking a lot of time to generate pdf with angular

### ISSUE THREAD

**Issue by srajan96** [bpampuch/pdfmake#1687]
@liborm85 @bpampuch 
I referred to #798 where this issues was said to be resolved in 0.1.29. But now in 0.1.54, the issue seems to be back. I am generating text (includes hindi and english)+ some tables +1 image, totaling to 10 pages,using pdfmake, and it takes 1 minute to generate the pdf on chrome. Is there a way out to solve this?

**Comment by srajan96** [comment]
Another observation : I think even by cutting down page content from 10 pages to only 0.25 pages, the library still takes 10 seconds. Does slowness occur due to usage of fonts other than english?

**Comment by blikblum** [comment]
An example would be helpful. The issue can be in pdfmake, or its dependencies (pdfkit, fontkit)

**Comment by srajan96** [comment]
@blikblum I am sort of newbie into this. Can you please guide what I can give that would help you in debugging the issue?

**Comment by srajan96** [comment]
@blikblum I have tried to create a mini version of this error [here](https://angular-zvld71.stackblitz.io). Check in console, I have logged the time taken. I guess using custom vfs is causing this problem.

**Comment by srajan96** [comment]
I am also using pdfmake in another project which uses plain javascript. I have used the same set of fonts there also. However, it takes just 3-4 seconds to generate 5 pages (using english +hindi+images). But the angular project takes about 11s to generate .25 page pdf as can be seen in the demo code.

**Comment by blikblum** [comment]
> I have tried to create a mini version of this error here.

Is not loading: message "connecting to dev server"

**Comment by srajan96** [comment]
Please try [here]( https://stackblitz.com/edit/angular-zvld71)

**Comment by teejt** [comment]
I also have a similar problem.
I was testing using the PdfMake playground at http://pdfmake.org/playground.html

I used the code below for testing with time to display pdf shown
When isTextWrap is false I tried the following:
numRows = 5000 - generated in about 6 seconds and displayed in about 8 seconds
numRows = 8000 -  generated in about 10 seconds and displayed in about 13 seconds
numRows = 10000 - generated in about 11 seconds but display was more than 3 minutes (I gave up waiting for it)

When isTextWrap is true I tried the following:
numRows = 1000 - generated in about 6 seconds and displayed in about 9 seconds
numRows = 3000 - generated in about 16 seconds but display was more than 3 minutes (I gave up waiting for it)


`
var numRows = 400;
var isTextWrap = false;

var data = [];
data.push(
	[{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}, {text: 'Header 3', style: 'tableHeader'}, {text: 'Header 4', style: 'tableHeader'}, {text: 'Header 5', style: 'tableHeader'}, {text: 'Header 6', style: 'tableHeader'}, {text: 'Header 7', style: 'tableHeader'}, {text: 'Header 8', style: 'tableHeader'}, {text: 'Header 9', style: 'tableHeader'}]
);

for (var i=0; i<numRows; i++) {
	var j = i + 1;
	var mlist;
	var longText = "This is a very long text to cause text wrap"
	if (isTextWrap) {
	    mlist = [j, longText, longText, longText, longText, longText, longText, longText, longText]
	}
	else {
            mlist = [j, j+2, j*4, j+3, j*3, j+8, j*8, j+15, j*10]
	}
	data.push (
		//
		mlist
	);
}

var dd = {
    pageMargins: [50, 70, 50, 60],
    footer: function (currentPage, pageCount) {
        return currentPage.toString() + ' of ' + pageCount;
    },    
	content: [
		{text: 'A simple table', style: 'subheader'},
		'The following table has nothing more than a body array and a header row',
		{
			style: 'tableExample',
			table: {
			    headerRows: 1,
				body: data,
			}
		},
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true,
			margin: [0, 0, 0, 10]
		},
		subheader: {
			fontSize: 16,
			bold: true,
			margin: [0, 10, 0, 5]
		},
		tableExample: {
			margin: [0, 5, 0, 15]
		},
		tableHeader: {
			bold: true,
			fontSize: 13,
			color: 'black'
		}
	},
	defaultStyle: {
		// alignment: 'justify'
	}
	
}
`

**Comment by srajan96** [comment]
Okay, so I had been able to reduce time taken from 1 min to 10s. I was using custom fonts. I replaced them with much lighter webfonts and that did the trick.

But still, I guess using pdfmake as a service in angular is going to take some load time.
Anyways, whosoever comes here facing the same issue, try light webfonts, preferably `woff` format to speed up things.
