### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by Bert-de-Jong** [bpampuch/pdfmake#1696]
What is this?

![what is this](https://i.giphy.com/media/pPhyAv5t9V8djyRFJH/giphy.webp)

The [main page](https://github.com/bpampuch/pdfmake) says this, twice:

> Client/server side PDF printing in pure JavaScript

First of all, that sentence is missing a comma.
Its output is not JavaScript; it's not "printing in pure JavaScript".
It's "PDF printing", "in pure JavaScript".

Next, let's look at those two, starting with "in pure JavaScript".
What is it doing in JavaScript; it's _coded_ in vanilla JavaScript.
More precise, it does not require/rely on external libraries or frameworks.
And "PDF printing".
Printing is primarily associated with using a (laser or inkjet) printer.
It's one of the things end-users do with PDF documents: they print them.
This library is not automating (or otherwise helping in) this process.
The word "printing" is misleading.

This leaves us with "client/server side". If you visit [https://en.wikipedia.org/wiki/Client–server](https://en.wikipedia.org/wiki/Client–server) or [https://en.wikipedia.org/wiki/Client/server](https://en.wikipedia.org/wiki/Client/server), you'll see that both redirect to the article about the "client–server model". Therefore "client/server" seems to imply end-users of this library must have some kind of specific client running on their machine. I'm guessing "client/server side" is just a convoluted way to state that this library can output to web browsers.

The starting page of the documentation, on both the [official website](https://pdfmake.github.io/docs/) and [on GitHub](https://github.com/bpampuch/pdfmake/blob/master/README.md), does not explain what this is either. It just lists features. It also does not say what kind of input this tool accepts. Does it accept HTML input? I have to look at the [examples](https://github.com/bpampuch/pdfmake/tree/0.1/examples) to figure this out.

Here's my best guess at what this actually is:

> A JavaScript library to generate PDF files from JavaScript input.
> The library does not require/rely on external libraries or frameworks.

Well, that's not what I'm looking for.
So, I'm off; time to look at other GitHub projects.

**Comment by tcsaddul** [comment]
But this is really a GREAT library! One of my favorites! Just stay a little longer if you want to discover its wonders!

**Comment by pw182162** [comment]
I also do struggle with the documentation. The only example for the client side is this: `<!doctype html>
<html lang='en'><head><meta charset='utf-8'><title>my first pdfmake example</title><script src='build/pdfmake.min.js'></script><script src='build/vfs_fonts.js'></script></head><body>`
It's not working and none of the examples I can execute in the Browser. We don’t have node.js and we don’t plan to use it.
Is it possible to create an example in jsfiddle?

**Comment by liborm85** [comment]
@Bert-de-Jong

hehe... Your issue amused me, thanks.

> Next, let's look at those two, starting with "in pure JavaScript".
> What is it doing in JavaScript; it's _coded_ in vanilla JavaScript.
> More precise, it does not require/rely on external libraries or frameworks.

Vanilla is only slang word.


> This leaves us with "client/server side". If you visit [https://en.wikipedia.org/wiki/Client–server](https://en.wikipedia.org/wiki/Client–server) or [https://en.wikipedia.org/wiki/Client/server](https://en.wikipedia.org/wiki/Client/server), you'll see that both redirect to the article about the "client–server model". Therefore "client/server" seems to imply end-users of this library must have some kind of specific client running on their machine. I'm guessing "client/server side" is just a convoluted way to state that this library can output to web browsers.

Client-side is not same as client/side. I don't know why this redirection mistake is on wikipedia.
I will clarify the text a little.


> And "PDF printing".
> Printing is primarily associated with using a (laser or inkjet) printer.
> It's one of the things end-users do with PDF documents: they print them.
> This library is not automating (or otherwise helping in) this process.
> The word "printing" is misleading.

Printing is not associated only with laser and inkjet printer.


> The starting page of the documentation, on both the [official website](https://pdfmake.github.io/docs/) and [on GitHub](https://github.com/bpampuch/pdfmake/blob/master/README.md), does not explain what this is either. It just lists features. It also does not say what kind of input this tool accepts. Does it accept HTML input? I have to look at the [examples](https://github.com/bpampuch/pdfmake/tree/0.1/examples) to figure this out.

Documentation is not only one page, try use "Next" button.


> Here's my best guess at what this actually is:
>
> > A JavaScript library to generate PDF files from JavaScript input.
> > The library does not require/rely on external libraries or frameworks.

Linguistically it will probably be correct sentence. But technically it is very misleading and over-combined.

---

I modified the library description in readme and documentation a little bit.
For improve documentation is issue here: https://github.com/bpampuch/pdfmake/issues/1238 PRs with improvement documentation is welcome.
