### ISSUE TITLE
PDFMake is displaying some JPEG images incorrectly

### ISSUE THREAD

**Issue by roemhildtg** [bpampuch/pdfmake#1699]
I previously reported an issue dealing with JPEG's and I mentioned that some of them are being colorized weirdly. Here's an example of such JPEG. The file, if opened using a normal picture viewer works well. I'm generating a data uri using the code at the bottom. 

https://pastebin.com/B8khaJsZ

data uri code: 

```javascript
                const reader = new FileReader();
                reader.addEventListener('load', function() {
                    resolve({
                        name: attachment.name,
                        data: reader.result,
                    });
                });
                reader.readAsDataURL(blob.data);
```

**Comment by roemhildtg** [comment]
I have found another example of this occuring:

https://drive.google.com/open?id=1ExUvTqJcXoFoCxNBSGjNu9wSzCv2lVqQ

![image](https://user-images.githubusercontent.com/5471079/55915086-6517b380-5bae-11e9-8c65-139a0b9ca69e.png)


Is this a result of my images possibly? Or a bug with pdfmake? I'd really love to hear suggestions.

**Comment by liborm85** [comment]
No image can be displayed properly in image viewer. Images are wrong, not related to pdfmake.
