### ISSUE TITLE
How to run on client-side?

### ISSUE THREAD

**Issue by Harshil-Modi** [bpampuch/pdfmake#1700]
Can anyone explain me how I can run the server.js on client-side. Like I have index.html page and I've a button in it and I want to generate PDF on button click event. I've literally no idea about node.js. Any kind of help is appreciated. Sorry if the issue is duplicate.

**Comment by toderesa97** [comment]
That's not an issue mate.

**Comment by Wabbala** [comment]
May be you need to figure out first how nodejs works. You can also look at
the source code of the playground. Otherwise I would suggest to have gain
some basic knowledge on JavaScript and other webdesign basics...

**Comment by liborm85** [comment]
How to use pdfmake on client-side is described in [documentation](https://pdfmake.github.io/docs/getting-started/client-side/).
For server.js and node.js use another support (google/stackoverflow/etc.).
