### ISSUE TITLE
Options might be dropped

### ISSUE THREAD

**Issue by iamstiil** [bpampuch/pdfmake#1702]
I have been going through the code and might have spotted a bug.

https://github.com/bpampuch/pdfmake/blob/0.1.54/src/browser-extensions/pdfMake.js#L139

This line is overwriting the `cb` with `defaultFileName` if it is a function. This means if no name is provided the first argument will be the callback. But that implicates that the second argument, in this case `cb` might be actually the options, which are currently dropped.

Am I right?

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/2deb1f6a1151141ec48fad233fc57d18e2773dbc.

**Comment by liborm85** [comment]
New version released.
