### ISSUE TITLE
How to convert HTML to PDF with multiple pages

### ISSUE THREAD

**Issue by virja** [bpampuch/pdfmake#1703]
I am trying to convert HTML div element’s content to PDF using PDFmake() with html2canvas. It is not working for mutliple page generation. Below is an example using PDFmake() with html2canvas plugin.

> The below code generates pdf with single page. When content exceeds, the data from the page is being cropped. I want the data to be continued on next page.

htmlcanvaspdf(){

      console.log('testhtmlcanvas');
      let elem = this.exportthis.nativeElement.innerHTML;
      console.log('exportthiselem'+elem);

        html2canvas(document.querySelector("#exportthis")).then(canvas => {
          console.log('canvass'+canvas);
          var data = canvas.toDataURL();
          var docDefinition = {
              content: [{
                  image: data,
                  width: 500,
                  height: 800,

              }]
          };
          console.log('doccdeff'+docDefinition);
          this.pdfObj = pdfMake.createPdf(docDefinition);
          if(this.pdfObj){

          this.downloadPdf();

          }
      });
    } 

    downloadPdf() {
      console.log('downloadPdf');
      if (this.platform.is('cordova')) {

        this.pdfObj.getBuffer((buffer) => {

          var blob = new Blob([buffer], { type: 'application/pdf' });
          var today= new Date();
          var dd =  today.getTime();
          // Save the PDF to the data Directory of our App
          this.file.writeFile(this.file.dataDirectory, 'whatappoffer'+dd+'.pdf', blob, { replace: true }).then(fileEntry => {
            // Open the PDf with the correct OS tools
            console.log('fileentry'+fileEntry);
            let filenames=this.file.dataDirectory+'whatappoffer'+dd+'.pdf';
            console.log('filearraydownloadPdf'+this.filearray+'filenames'+filenames);
            this.fileOpener.open(this.file.dataDirectory + 'whatappoffer.pdf', 'application/pdf');
          })
        });
      } else {
        // On a browser simply use download!
        this.pdfObj.download();
      }
    }

**Comment by liborm85** [comment]
You can split to more images or use automatic page height, see [documentation](https://pdfmake.github.io/docs/document-definition-object/page/).
