### ISSUE TITLE
Style changed after second download

### ISSUE THREAD

**Issue by toniojst** [bpampuch/pdfmake#1705]
Once the web page is loaded and the first time you click on the button, the print job creates fine pdf, and when you click on the button for the second time, the image where the logo is changed to sign the image and canvas line are change position. So you need to refresh each page for each.

Below is a link to a code where you can see what's wrong https://jsfiddle.net/dnt0fyp6/2/

**Comment by liborm85** [comment]
It is ok, because https://github.com/bpampuch/pdfmake/issues/1669#issuecomment-471893464

**Comment by toniojst** [comment]
Yes i saw this but i dont know how to do this. Can you help me with some example code?

**Comment by liborm85** [comment]
Generate docDefinition always again before calling `download()` method is better.

The second option is use copy of docDefinition object, see https://medium.com/@Farzad_YZ/3-ways-to-clone-objects-in-javascript-f752d148054d (or google).
