### ISSUE TITLE
npm WARN deprecated gulp-util@3.0.8: gulp-util is deprecated 

### ISSUE THREAD

**Issue by Sandgrouse** [bpampuch/pdfmake#1706]
gulp-util is deprecated - replace it, following the guidelines at https://medium.com/gulpjs/gulp-util-ca3b1f9f9ac5

**Comment by liborm85** [comment]
`npm ls gulp-util`

```
pdfmake@0.1.54
`-- gulp-file-contents-to-json@0.2.2
  `-- gulp-util@3.0.8
```

Not related to pdfmake, because pdfmake does not use `gulp-util` library.
Library `gulp-util` is installed via `gulp-file-contents-to-json` library.
