### ISSUE TITLE
Multi-page PDF with Dynamic Data Styling Error

### ISSUE THREAD

**Issue by 5cotts** [bpampuch/pdfmake#1707]
We are using the PDFMake in order to create dynamic PDFs that can be automatically populated with data from a database. We originally outsourced this project to a programmer. They were able to use PDFMake to create a connection to our database and output dynamic PDFs. However, they didn’t stylize the PDFs in a great way. Thus, we modified the JavaScript code they provided and made some style modifications ourselves. 

This is where we are having issues. We removed all of the original programmer’s styling from the source JavaScript. However, upon testing our modified code, the updated styling fails under certain situations. When we use our code to output a dynamic PDF from a data source that is small, and all the data can fit on one page, the code executes flawlessly. However, when we output a PDF created with dynamic data that extends beyond one page, our code fails, and all the new styling code we entered doesn’t work and the output PDF is styled in the old manner that the original programmer created. 

We believe the error may lie in the `docDefinition` variable, as this variable is central to the creation of the output PDF in the PDFMake library.

``` 
const docDefinition = {
    content: [headerContent, bizScopeContent, col_mang, col_shareholders, col_investments],
    styles: styles,
    pageSize: 'A4',
    footer: footer,
    background: background,
  };
```
Each component in `docDefinition` (except for `pageSize: 'A4'`) refers to another variable and/or JavaScript file we have created that contributes to the style or input of the overall output PDF (see below for an example).

<img width="158" alt="Screen Shot 2019-04-24 at 12 31 06 PM" src="https://user-images.githubusercontent.com/34784469/56677595-d9faeb00-668e-11e9-9bf3-309d1198361b.png">

However, it could be the case that the error does not lie within `docDefinition`. 

Has anybody else had a similar issue with styling? Is there some sort of `globalStyling` argument that I am missing? We essentially have a background and a footer and some custom fonts that we wish to replicate on every page necessary (i.e., replicate on every page for as long as our dynamic tables generate). Any advice would be appreciated. Thank you!

I've looked at similar threads (#24 & #1046), but neither seem to exactly match our problem.

**Comment by liborm85** [comment]
We probably removed more than needed. There is nothing to comment, because there are no example.
Example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html) is necessary.

**Comment by 5cotts** [comment]
Hello all, 

This was a server issue on our end and ended up having nothing to do with PDFMake. After a few days of debugging, we fixed it. We can now generate multi-page PDFs with dynamic data beautifully! Thanks to the creators of PDFMake for such a nice tool.
