### ISSUE TITLE
Problem with english and greek characters

### ISSUE THREAD

**Issue by vagdamis** [bpampuch/pdfmake#171]
I am making a webpage that creates cv's  and I use your code to generate the pdf file. There is an issue when using english and greek characters and some of them are not displayed correctly. This is an example I tried in the playground

var dd = {
        content: [
            'EMAIL: v@something.com',
            'ΟΙΚΟΓΕΝΕΙΑΚΗ ΚΑΤΑΣΤΑΣΗ: whatever',
            'ΕΚΠΑΙΔΕΥΣΗ',
            '2007 - 2009  λυκειο',
            'ΓΝΩΣΕΙΣ Η/Υ',
            'Καλή χρήση MS Office, γλώσσες προγραμματισμού C, C++, Java (και Android), PHP, Javascript, HTML,',
            'HTML5, MySql...',
            'ΕΠΑΓΓΕΛΜΑΤΙΚΗ ΕΜΠΕΙΡΙΑ',
            '2014 Πληροφορικός Καταστευή ιστοσελίδων, android εφαρμογών',
            'ΞΕΝΕΣ ΓΛΩΣΣΕΣ',
            'Αγγλικά Michigan , Edexcel  ( Πολύ Καλά )',
            'Γερμανικά Whatever German Diploma. ( Μέτρια )'
        ]
}

see the difference in the last line and then put a G at the start of the first line ( 'GEMAIL: v@something.com') and then that letter will be displayed correctly.

I hope you can help

**Comment by jthoenes** [comment]
This is a dublicate of #165
