### ISSUE TITLE
Use RTL language inside table

### ISSUE THREAD

**Issue by manaryousry9** [bpampuch/pdfmake#1710]
Hi , I know that pdfmake doesn't support rtl so I tried a solution to write the text words in reverse but it doesn't work well 
this the code 
[table with RTL language.txt](https://github.com/bpampuch/pdfmake/files/3122938/table.with.RTL.language.txt)

the text should be displayed exactly like this "الفتره الثانيه لمكتب الاستشاري الخاص" 
but if the text will be divided to more than one line it should be split but from the right to left 
but as we know rtl not supported so I inserted the text in reverse to be like this 
"الخاص الاستشاري لمكتب الثانية الفترة" so if the text splits , it will write from the left to write 
as you could see i did this in the fifth column of the table but the output is not as i expected 
the words are written in right order but the lines is reversed like this pic
![image](https://user-images.githubusercontent.com/45942703/56833409-b55d6980-686e-11e9-8ca5-3feca9305c4a.png)

I need help with this issue , thanks in advance

**Comment by liborm85** [comment]
RTL is not supported now.
Feature request: https://github.com/bpampuch/pdfmake/issues/184
