### ISSUE TITLE
Cannot read property 'toc' of undefined

### ISSUE THREAD

**Issue by simpsojo** [bpampuch/pdfmake#1712]
Hi,

I've been using PDFMake (within an Angular application) for over a year and I regularly upgrade.  With release 0.1.55 I started to get the following fatal error:

	Error: Uncaught (in promise): TypeError: Cannot read property 'toc' of undefined

The culprit appears to be in the following:

	if (!node.id) {
		node.id = 'toc-' + tocItemId + '-' + this.tocs[tocItemId].toc._items.length;
	}

Any idea what changed in 0.1.55 that could have introduced this?  

Could it be that my doc definition is in some way incorrect and that it just hasn't surfaced until now?  

I'd provide a docDefinition but it's huge and complex and I haven't got as far as trying to provide a reproducible test case.  I wanted to raise awareness of a potential issue quickly.  Reverting back to 0.1.54 everything works fine.

Thanks for the great product!

Best wishes,
Joe

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/4c20878f3cdf1a3dedc6c2a40285d3ee6737a629 (in master) and https://github.com/bpampuch/pdfmake/commit/1aab12a35cb7514f409d85078ee3413846be445c (in 0.1 branch).

**Comment by liborm85** [comment]
New version released.

**Comment by simpsojo** [comment]
Upgraded to 0.1.56, all good!  Thanks!
