### ISSUE TITLE
change pdfVersion from 1.3 to 1.7

### ISSUE THREAD

**Issue by Ribx99** [bpampuch/pdfmake#1716]
Hello,
I try to save the pdf-file with the Version 1.7ext3 to use the aes-encrytption but every created pdf-file has version 1.3.

var docDefinition = {
  pdfVersion: '1.7ext3',
  compress: true,
  // permissions
  userPassword: ****
  ...

Can someone please point me in the right direction? 
Best Regards,
Ribx

**Comment by liborm85** [comment]
There was mistake in documentation, correct parameter is `version`.

Documentation fixed: https://pdfmake.github.io/docs/document-definition-object/security/

**Comment by Ribx99** [comment]
works, thank you very much!
