### ISSUE TITLE
Stream page when page is finished

### ISSUE THREAD

**Issue by Llorx** [bpampuch/pdfmake#1717]
Is there any way of receiving the page buffers one by one each time a page is finished?

I mean, when a page cannot have new content and a new page is created, is there any way to stream that page to the output?

I'm creating a very large file with a very large table, and the server hangs while creating the file, and I would like to stream the file on-the-fly while is being created.

Right now `createPdfKitDocument` hangs while calculating the layout and I receive a final stream instantly just after `createPdfKitDocument` hangs about 1 minute or so. If `createPdfKitDocument` could `setImmediate` and output the page while calculating the layout, that would be awesome.

**Comment by kevinbror** [comment]
+1

**Comment by danosaure** [comment]
I think it would be hard because things like table of contents are also created on the fly and could change your page number. So even if the streaming is being done, it would still have to wait about 90%-95% of your "lag" time. I've just started using it, but it's my supposition.

**Comment by Llorx** [comment]
Yes, that's why I said to stream a page when has finished with it. No need to know the total page numbers or wait for the entire file to load, just send out the bytes of each already generated page. Just like Microsoft Reporting Services do.

I guess that something can be done with [linearized PDFs](https://docs.oracle.com/cd/E73729_01/TSG/FAQ/What%20are%20linearized%20PDF%20files_.html):

> Linearized PDF files contains information that allow a byte-streaming server to download the PDF file one page at a time

**Comment by liborm85** [comment]
No, it is not possible. Node position is calculated together for the whole document.

**Comment by ssipos90** [comment]
I guess there's no plan in implementing this?
