### ISSUE TITLE
pdf filename gets incorrect if double quotes are added in it in edge

### ISSUE THREAD

**Issue by suhasbhattu** [bpampuch/pdfmake#1719]
I have a use case where pdf filename may contain special characters including single quote or double quotes. In that case, when I download the file, some random string gets applied to downloaded pdf file. It occurs in MS Edge, and in case of Chrome and Firefox, double quotes gets replaced with underscore(__). How to handle such cases?

```
pdfMake.createPdf(docDefinition).download('"sample".pdf');
```
In such case, Edge browser downloads the PDF file with some random string (6c94f320-8f12-4722-8f44-23da34d663c1.pdf) and in case of Chrome and firefox it downloads with \_sample\_.pdf, is it a problem with browsers and how to fix this issue?

**Comment by liborm85** [comment]
This behavior depends on browser.
