### ISSUE TITLE
Save locally

### ISSUE THREAD

**Issue by User199011** [bpampuch/pdfmake#172]
Hello,

I'm trying to use pdfmake but I have one question about its utilisation. Can I just save my pdf file on my server without downloading it ?

I want my page to generate the pdf file and save it automatically in the folder "upload" of my server. Is it possible ?

Thank you

**Comment by jthoenes** [comment]
You can get an ArrayBuffer from pdfmake. This you can turn into a blob and post it to your server via HTTP.

    pdfMake.createPdf(docDefinition).getBuffer(function(buffer) {
       // turn buffer into blob
       // send it to server via post
    });

**Comment by wahono77** [comment]
I can do it/save locally but I got broken in UTF-8 string. How to fix buffer data to UTF-8?

Thanks

**Comment by jthoenes** [comment]
I don't really understand your issue. Can you provide some example code and the exact error message?

**Comment by wahono77** [comment]
I use it in node-webkit (NodeJS) : 

pdfMake.createPdf(docDefinition).getBuffer(function(result) {
  fs.writeFile('sample.pdf', result, function (err) {
              if (err) throw err;
              gui.Shell.openItem(afile);
            });
}

The result is : all layout and fonts are OK, but string is broken.

**Comment by wahono77** [comment]
![error](https://cloud.githubusercontent.com/assets/3787240/7363899/ff330c54-ed34-11e4-9b17-6e7534e2a877.png)
Here is the screenshot (wrong and OK result)

Thanks

**Comment by jthoenes** [comment]
Hm, I don't see a problem in the picture ^^^

No seriously. I don't think using the browser-extension in node is the right way to do it. I have never used pdfmake on node, so I might have to look into it more closely. But my gut feeling would be to use something similar to https://github.com/bpampuch/pdfmake/blob/master/src/browser-extensions/pdfMake.js#L25 and follow the pdfkit api to actually store the file.

Like (untested ... so you might have to improve it):

````
var printer = new PdfPrinter(this.fonts);
var doc = printer.createPdfKitDocument(this.docDefinition, options);
doc.pipe(fs.createWriteStream('sample.pdf'));
doc.end();
````

BTW: the issue is probably not UTF-8. There is something wrong in binary conversion in node-webkit.

**Comment by wahono77** [comment]
Thanks for your respond. But I got error in var printer = new PdfPrinter(this.fonts);

How to call PdfPrinter from pdfmake.js? I read in https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js.

var PdfPrinter = require('../src/printer');

But it call from split source, how to call it from concatenated source?

thanks

**Comment by wahono77** [comment]
You said : BTW: the issue is probably not UTF-8. There is something wrong in binary conversion in node-webkit.

But I get normal pdf in some doc using pdfMake.createPdf(docDefinition).download('currency.pdf',

I think it is not from node-webkit

**Comment by seansbox** [comment]
I'm having the same problem when using Electron. pdfMake.createPdf(docDefinition).download('foo.pdf') works great but "download" interface is weird for a Electron app. When I try to write the stream to file instead though, the .pdf file's text is all wrong (looks very wrong-encoding to me).

// works!
pdfMake.createPdf(dd).download('foo.pdf');

// does not work :-(
pdfMake.createPdf(dd).getBuffer(function(buffer) {
  fs.writeFileSync('foo.pdf', buffer);
});

**Comment by seansbox** [comment]
I found this works as a workaround:

        fs.writeFileSync('foo.pdf', new Buffer(new Uint8Array(buffer)));

**Comment by plinkplink** [comment]
Thank you @seansbox. I was having this same issue and you saved me headaches with your writeFileSync workaround.
