### ISSUE TITLE
Cannot create property 'href' on string

### ISSUE THREAD

**Issue by simplepry-s** [bpampuch/pdfmake#1721]
Hello Plese help me i got the error

pdfmake.js:17911 Uncaught TypeError: Cannot create property 'href' on string 'about:blank'
    
pdfmake.js:17911 Uncaught TypeError: Cannot create property 'href' on string ''
 

this is my code

printPDF(){

  var docDefinition = {
    content: [
      { text: ' reat pdf demo ', fontSize: 15 },
    ],
  };
  pdfMake.createPdf(docDefinition).open()

}
when i run this function i got the blank window and error

 os : windows10
 work on : reactron

**Comment by liborm85** [comment]
reactron probably not support opening new window in browser.
