### ISSUE TITLE
How to correclty handle server side errors ?

### ISSUE THREAD

**Issue by popod** [bpampuch/pdfmake#1722]
```
let doc = printer.createPdfKitDocument(pdfContent);

let chunks = [];
let result;

doc.on('data', function (chunk) {
  chunks.push(chunk);
});
doc.on('end', function () {
  result = Buffer.concat(chunks)

  res.attachment('facture.pdf')
  res.send(result);
});
doc.end()
```

But I got an `uncaughtException: Unhandled error. (Malformed table row, a cell is undefined.)`

How to catch this properly ?

**Comment by MikeThuchchai** [comment]
could you try to put `try catch` on `let doc = printer.createPdfKitDocument(pdfContent);`

```
let doc;
try {
  doc = printer.createPdfKitDocument(pdfContent);
} catch (error) {
  console.log(error)
}
```

**Comment by liborm85** [comment]
Error checking behavior will be improved in version 0.2.

https://github.com/bpampuch/pdfmake/issues/2066
