### ISSUE TITLE
Browser duplicate the link when writing link: something

### ISSUE THREAD

**Issue by romanula** [bpampuch/pdfmake#1725]
try playground with {text: 'https://www.codejig.com', link: 'https://www.codejig.com/en'} and move mouse on link
and look at link - bottom left 
when mouse is directly on text it is - link: 'https://www.codejig.com/en
when above or below text - text: 'https://www.codejig.com

**Comment by liborm85** [comment]
Chrome pdf viewer interprets text as link, therefore redirects to wrong page. It works correctly in Adobe Reader.
Bug is in Google Chrome, no way how to fix it in pdfmake.
