### ISSUE TITLE
missing dot from "i" in combination "fi"

### ISSUE THREAD

**Issue by romanula** [bpampuch/pdfmake#1726]
Something is wrong with font due to absence dot on i in combination fi, standart Roboto is used
![image](https://user-images.githubusercontent.com/22663355/57853395-53997b00-77ee-11e9-9514-c8a9f4d848fc.png).
So the link became wrong. Related issue -https://github.com/bpampuch/pdfmake/issues/1670#issue-419816412

I have managed to add **fontFeatures: 'dist'** - it helps me

also I noticed that even `characterSpacing` wont help, all char have spacing but 'fi' is always 
close together
![image](https://user-images.githubusercontent.com/22663355/57856200-28fef080-77f5-11e9-8861-ed2bd18d7e57.png)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by romanula** [comment]
```
{text: ['Link to ', { text: 'www.imgo.fi', link: 'http://imgo.fi', decoration: 'underline' }	]	},
```
You can't see dot on i, so the Chrome interprets text as link and it makes link to http://imgo.f, try to move mouse below or above text, I think because Chrome can't recognise i without dot
maybe pdfmake can move 'i' little from 'f' as it is done by `fontFeatures: 'dist',`

**Comment by liborm85** [comment]
This issue is not realated with https://github.com/bpampuch/pdfmake/issues/1670

**Comment by liborm85** [comment]
Font tested on https://fonts.google.com/specimen/Roboto :
![roboto-test-1726](https://user-images.githubusercontent.com/1298652/57910074-a1f95900-7884-11e9-8be1-de7c96ee4b91.png)

Here it is exactly same, it is font behavior.
