### ISSUE TITLE
Please give advice how to insert HTML symbols

### ISSUE THREAD

**Issue by romanula** [bpampuch/pdfmake#1728]
Please give advice how to insert HTML symbols, such as here https://www.w3schools.com/charsets/ref_utf_dingbats.asp,
If it can be done be adding custom font, please advise font, or maybe in future such font can be included to library as optional

**Comment by liborm85** [comment]
Is needed font with support this characters. For example [Code2000](https://fonts2u.com/code2000.font?ptext=%E2%9C%82%E2%9C%83%E2%9C%8E%E2%9C%91%E2%9C%99%E2%9D%A7).
How to add font in client-side (browser) is described in [documentation](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/).
