### ISSUE TITLE
dynamic table two columns per page

### ISSUE THREAD

**Issue by riux** [bpampuch/pdfmake#1729]
dynamic table two columns per page
how can I create dynamic table that the pageBreak advances to the next column and then to the next page, like this image.
![pdfmake](https://user-images.githubusercontent.com/9002215/57971739-7a26f580-7957-11e9-9efe-2cce89072e03.png)

**Comment by liborm85** [comment]
You can use `pageBreak` property,

Example:
```js
var dd = {
	content: [
		{text: 'Page 1', pageBreak: 'after'},
		{text: 'Page 2', pageBreak: 'after'},
	]	
}
```

**Comment by riux** [comment]
The question is, what do I want to create a dynamic table that starts at the same time as the sheet, to the left, until it reaches the end of the page, then continues on the right side of the page and when it reaches the end of the page? Residence sheet advance to the next page as in the image

**Comment by liborm85** [comment]
Not supported. Feature request is here: https://github.com/bpampuch/pdfmake/issues/604
