### ISSUE TITLE
internet explorer does not show preview and print.

### ISSUE THREAD

**Issue by oguzAtes** [bpampuch/pdfmake#173]
internet explorer does not show preview and print. but download is working
but chorme and firefox are working with all option.

Can you check it pls.

Internet explorer version 11.0.9600.17501IS
Update Version:11.0.15
![pdfmake](https://cloud.githubusercontent.com/assets/6254684/5789831/610b2746-9e83-11e4-962b-8d2321d1cce2.jpg)

**Comment by oguzAtes** [comment]
Check your demo web side.
open function display blank page, print function do nothing.
There is no exception code behind and debuging my project.
Thank you.

**Comment by robertmadsen** [comment]
I am having the same issue.

pdfMake.createPdf(docDefinition).open 

works in FireFox, Chrome and Safari, but not Internet Explorer.  In IE, a new window opens, but the document never appears.

**Comment by jthoenes** [comment]
I'm on a Mac, so I cannot investigate the problem. I'm happy to help, when you want to create a pull request.

**Comment by robertmadsen** [comment]
I'm new at GitHub.  Please explain what I do to create a pull request. R

**Comment by YidingW** [comment]
+1

**Comment by jthoenes** [comment]
You essentially create a fork of this repository and develop your bugfix/feature in a branch. Then you submit this code for inclusion by opening a pull request. 

Here is a description in more detail: https://help.github.com/articles/using-pull-requests/

**Comment by nkyordy** [comment]
Internet Explorer doesn't support data URIs for this purpose as listed [here] (https://msdn.microsoft.com/en-us/library/cc848897(v=vs.85).aspx). Because of this you won't be able to use .open() in IE.

As you mentioned, .download() is working fine in IE. The solution I used was to write a function similar to [this one](http://stackoverflow.com/questions/19999388/check-if-user-is-using-ie-with-jquery), and then download the PDF if the check for IE returns true.

**Comment by tlk** [comment]
I guess a workaround would be to use pdf.js from Mozilla as mentioned in #519

Any objections on doing this for the playground/demo?

**Comment by skendrot** [comment]
Any updates on getting  the preview to work in IE?

**Comment by robertmadsen** [comment]
Sorry…never had a  chance to pursue it.

Robert Madsen
Studio Director, SynaptixGames
http://SynaptixGames.com<http://synaptixgames.com/>
760 Horizon Drive, Suite 200, Grand Junction, CO 81506
(970) 281-5805<tel:(970)%20281-5805>
[id:image001.png@01D2936F.047B0630]

**Comment by liborm85** [comment]
Problem is in Internet Explorer and is not expected fix by Microsoft, if is IE in clinic death.
In https://github.com/bpampuch/pdfmake/issues/800 marked as unsupported.
