### ISSUE TITLE
How to get text width ?

### ISSUE THREAD

**Issue by CharlyPoppins** [bpampuch/pdfmake#1733]
Hello,

is there a way to calculate text width from its definition ?
```{ text: 'My text`, fontSize: 24 }```

or to define the width ?
```{ text: 'My text`, fontSize: 24, width: 200, alignment: 'left', background: 'blue' }```

(so my text will be center in a 200px block)

**Comment by liborm85** [comment]
> is there a way to calculate text width from its definition ?
> `` { text: 'My text`, fontSize: 24 } ``

No, it is not possible.

> or to define the width ?
> `` { text: 'My text`, fontSize: 24, width: 200, alignment: 'left', background: 'blue' } ``
> 
> (so my text will be center in a 200px block)

Block containter not supported now (feature request: #15), but as workarround can be used table, see example:
```js
var dd = {
	content: [
		{
			table: {
				widths: [200],
				body: [
					[{text: 'My text', fontSize: 24, alignment: 'center', fillColor: 'blue' }],
				],
			},
			layout: 'noBorders'
		}
	]
}
```

**Comment by zullo91** [comment]
I can get the maxWidth and other parameter as well.
And the magic happen!
Shakala booom ;)

console.log(
        this.getTextMaxWidth({
          absolutePosition: { x: offsetX, y: offsetY },
          columns: [
            {
              text: productEntry.product.name,
              fontSize: 10
            }
          ]
        })
      )
  private getTextMaxWidth(content: {}) {
    const temp = [];
    temp.push(content);
    const pdf = pdfMake.createPdf({ content: temp });
    pdf.getStream({});
    return pdf.docDefinition.content[0]._maxWidth;
  }

**Comment by ifndefdeadmau5** [comment]
@zullo91 man this works like a charm, thanks

**Comment by zamb3zi** [comment]
Awesome, thanks @zullo91 . Here's my version based on your idea.
Note that `noWrap: true` is needed to measure long strings without wrapping.
```ts
import pdfmake from 'pdfmake';
import {TDocumentDefinitions, Content} from 'pdfmake/interfaces';

const printer = new pdfmake({
    // fonts, etc
});


const textMaxWidth = (content: Content) =>
    printer.createPdfKitDocument({content: [{text: content, noWrap: true}]}).x;
```

The main way I'm using this is to truncate a string so that it does not exceed a given width. If truncated, it appends ellipses. It uses [Brent's method](https://en.wikipedia.org/wiki/Brent%27s_method) to minimize the number of width evaluations.
```ts
/**
 * Truncate the given text string to fit within the given width.
 * 
 * See: https://en.wikipedia.org/wiki/Brent%27s_method
 */
const truncateText = (text: string, options: TruncateTextOptions) => {
    const {maxWidth, fontSize} = options;
    const {length} = text;
    let b = length;
    const trunc = (len: number) => {
        len = Math.max(round(len, 0), 1);
        return len < length ? `${text.slice(0, len - 1)}…` : text;
    };
    const f = (len: number) =>
        textMaxWidth({
            text: trunc(len),
            fontSize,
        }) - maxWidth;
    let bx = f(b);
    if(bx > 0) {
        let a = 0, ax = f(0);
        if(ax >= 0)
            return '…';
        if(Math.abs(ax) < Math.abs(bx))
            ([a, ax, b, bx] = [b, bx, a, ax]);
        const xTol = 1;
        let c = a, cx = ax, mflag = true, d: number, maxIter = 20;
        while(maxIter-- && Math.abs(b - a) > xTol) {
            const acx = ax - cx;
            const bcx = bx - cx;
            const abx = ax - bx;
            let s = Math.abs(acx) > Number.EPSILON && Math.abs(bcx) > Number.EPSILON ?
                a*bx*cx/(abx*acx) + b*ax*cx/(-abx*bcx) + c*ax*bx/(acx*bcx) :
                b - bx*(b - a)/(bx - ax);
            if(s < (3*a + b)/4 || s > b || (
                mflag ?
                    (Math.abs(s - b) >= Math.abs(b - c)/2 || Math.abs(b - c) < Math.abs(2 * Number.EPSILON * Math.abs(b))) :
                    (Math.abs(s - b) >= Math.abs(c - d)/2 || Math.abs(c - d) < Math.abs(2 * Number.EPSILON * Math.abs(b)))
            )) {
                s = (a + b)/2;
                mflag = true;
            } else {
                mflag = false;
            }
            const sx = f(s);
            ([d, c, cx] = [c, b, bx]);
            if(ax*sx < 0)
                ([b, bx] = [s, sx]);
            else
                ([a, ax] = [s, sx]);
            if(Math.abs(ax) < Math.abs(bx))
                ([a, ax, b, bx] = [b, bx, a, ax]);
        }
        if(ax > bx)
            ([a, ax, b, bx] = [b, bx, a, ax]);
        return trunc(a);
    }
    return text;
};

type TruncateTextOptions = {
    maxWidth: number;
    fontSize: number;
};
```
