### ISSUE TITLE
hide tables if the value is null?

### ISSUE THREAD

**Issue by andreimcua** [bpampuch/pdfmake#1734]
Hello everyone! I am new to PDFMake so please bear with me.

I would like to know how to hide table if the value is null? 

[{text: 'Worker Id'}, {text: this.helper.id}]

thanks in advance!

**Comment by liborm85** [comment]
I can't see any table in your example.

You can hide element using condition:
```js
var dd = {
	content: []
};

if (/*condition for add to pdf*/) {
    dd.content.push({text: 'example text'});
}
```

**Comment by andreimcua** [comment]
Oh sorry. 

{
		            headerAlign: 30,
		            style: 'tableExample',
		            color: 'black',
		            table: {
		              widths: ['*', 'auto'],
		              headerRows: 2,
		              // keepWithHeaderRows: 1,
		              body: [
		                [{text: 'DOMESTIC WORK EXPERIENCE AND ABILITY 工作經驗及能力', colSpan: 2, style: 'filledHeader'}, {}],
		                [{text: 'Country 國家'}, {text: this.helper.workingExperienceList[0]['country']}],
		                [{text: 'Duration 工作時間'}, this.helper.workingExperienceList[0]['start_date'] + ' ' + this.helper.workingExperienceList[0]['end_date']],
		                [{text: 'Salary 薪金'}, this.helper.workingExperienceList[0]['wage_currency']],
		                [{text: 'Holiday 假期'}, this.helper.workingExperienceList[0]['holiday_arrangement']],
		                [{text: 'House Area 房間大小'}, this.helper.workingExperienceList[0]['house_area'] + ' ' + this.helper.workingExperienceList[0]['house_area_uom']],
		                [{text: 'No. of Family Member'}, this.helper.workingExperienceList[0]['num_of_family_member']],
		                [{text: 'No. of Elder'}, this.helper.workingExperienceList[0]['num_of_elderly']],
		                [{text: 'No. of Disabled'}, this.helper.workingExperienceList[0]['num_of_disable']],
		                [{text: 'No. of Child'}, this.helper.workingExperienceList[0]['num_of_children']],
		                [{text: 'No. of Baby'}, this.helper.workingExperienceList[0]['num_of_babies']],
		                [{text: 'No. of Pet'}, this.helper.workingExperienceList[0]['num_of_pet']],
		                [{text: 'Job Duties'}, this.helper.workingExperienceList[0]['job_duties']],
		                [{text: 'Reason For Leaving'}, this.helper.workingExperienceList[0]['leave_reason']],
		                
		                
		              ]
		            }
		          },
