### ISSUE TITLE
Exported PDF gets printed wrong

### ISSUE THREAD

**Issue by myUsernamesTaken** [bpampuch/pdfmake#1736]
I'm encountering an issue where a exported pdf gets printed with errors. 

Screenshot from PDF: https://ibb.co/VDBBmC3
Scan from printed page: https://ibb.co/VmXKfch

Maybe could give me a hint, what causes this error, since im pretty clueless right now.

**Comment by liborm85** [comment]
Attach docDefinition example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html) or [jsfiddle](https://jsfiddle.net/).

**Comment by myUsernamesTaken** [comment]
Hey, here's the fiddle. Theres an error in it, which i can't fix... 
Uncaught File 'data/Times-Roman.afm' not found in virtual file system

https://jsfiddle.net/tb1e4yLn/

**Comment by liborm85** [comment]
I do not see any problem, pdf document is generated correctly.
Problem will be in the printer or their drivers. Not related to pdfmake.
