### ISSUE TITLE
changing the value does not render? 

### ISSUE THREAD

**Issue by andreimcua** [bpampuch/pdfmake#1737]
I have this column in my table. 

['Address:', this.helper.city + ' ' + this.helper.district + ' ' + this.helper.country],

I am changing the value using ? ""  : "" 

['Address:', this.helper.city?this.helper.city:"" + ' ' + this.helper.district?this.helper.district:"" + ' ' + this.helper.country?this.helper.country:""],

The problem is it only renders the first object and the others disappears. 

I would like to know why is this happening and is there a work around to show all of the objects? Many thanks!

**Comment by liborm85** [comment]
[Here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Conditional_Operator) is described how to use ternary operator in JavaScript. For separate condition in one text you can use brackets.
Not related with pdfmake. It is for programming knowledge. For help with basics in programming you can use [stackoverflow.com](https://stackoverflow.com).
