### ISSUE TITLE
PdfMake - Absolute positionning not working after pageBreak

### ISSUE THREAD

**Issue by Eva-R** [bpampuch/pdfmake#1738]
Hello there,

Keep having this weird issue but I can't find any similar one online.

I am working on a dynamic data project. Every time that I export a pdf the 'absolutePosition' works pretty well when I need to export a one page report but once their is more than 1 page, any extra content overlay on top of the second page. 

Here is an exemple of what I mean:

![test](https://user-images.githubusercontent.com/22544930/58797962-3be93180-85f9-11e9-91a7-ee57f00ab36d.png)

is anyone could help please?

**Comment by liborm85** [comment]
Attach simple example for reproduce issue on [playground](http://pdfmake.org/playground.html).

**Comment by Eva-R** [comment]
Hello @liborm85 ,

Thank you for your reply. 

Here is my code below:

`var dd = {
    content: [

      {
        stack: [
          {
            fontSize: '20',
            color: '#73879c',
            text: 'Pdf Test'
          }
        ],
        absolutePosition: {
          x: 10.098958333333332,
          y: 28.098958333333332
        }
      },
      {
        stack: [

          {
            image: 'https://bit.ly/2WmKbot',
            fit: [
              278.5130208333333,
              89.86979166666667
            ]
          }

        ],
        absolutePosition: {
          x: 301.7109375,
          y: 28.098958333333332
        }
      },
      {
        stack: [
          {
            table: {
              widths: [
                268.515625
              ],
              body: [
                [
                  {
                    color: '#ffffff',
                    text: 'ASP Value Week On Week - Formats',
                    style: 'header'
                  }
                ]
              ],
              fillColor: '#454545'
            }
          },

          {
            style: table,
            table: {
              headerRows: 1,
              widths: [
                69.77864583333334,
                69.77864583333334,
                69.77864583333334,
                69.77864583333334
              ],
              body: [
                [
                  {
                    color: '#73879c',
                    bold: true,
                    text: 'Format'
                  },
                  {
                    color: '#73879c',
                    bold: true,
                    text: 'Last Week'
                  },
                  {
                    color: '#73879c',
                    bold: true,
                    text: 'This Week'
                  },
                  {
                    color: '#73879c',
                    bold: true,
                    text: '% Var'.
                  }
                ],
                [
                  {
                    color: '#73879c',
                    text: 'Val 1'
                  },
                  {
                    color: '#73879c',
                    text: '€2'
                  },
                  {
                    color: '#73879c',
                    text: '€0'
                  },
                  {
                    color: '#73879c',
                    text: '-100%'
                  }
                ],
                [
                  {
                    color: '#73879c',
                    text: 'Val 2'
                  },
                  {
                    color: '#73879c',
                    text: '€4'
                  },
                  {
                    color: '#73879c',
                    text: '€2'
                  },
                  {
                    color: '#73879c',
                    text: '-100%'
                  }
                ],
                [
                  {
                    color: '#73879c',
                    text: 'Val 3'
                  },
                  {
                    color: '#73879c',
                    text: '€5'
                  },
                  {
                    color: '#73879c',
                    text: '€1'
                  },
                  {
                    color: '#73879c',
                    text: '-100%'
                  }
                ]
              ]
            },
            layout: {}
          }

      }
    ],
    absolutePosition: {
      x: 10.098958333333332,
      y: 121.06770833333333
    }
  },
  {
    stack: [

      {
        table: {
          widths: [
            268.515625
          ],
          body: [
            [
              {
                color: '#ffffff',
                text: 'ASP Value Week On Week - Formats',
                style: 'header'
              }
            ]
          ],
          fillColor: '#454545'
        }
      },
      {
        style: table,
        table: {
          headerRows: 1,
          widths: [
            69.77864583333334,
            69.77864583333334,
            69.77864583333334,
            69.77864583333334
          ],
          body: [
            [
              {
                color: '#73879c',
                bold: true,
                text: 'Format'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'Last Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'This Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: '% Var'.
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 1'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '€0'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 2'
              },
              {
                color: '#73879c',
                text: '€4'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 3'
              },
              {
                color: #73879c,
              text: '€5'
              },
              {
                color: '#73879c',
                text: '€1'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ]
          ]
        },
        layout: {}
      }

    ],
    absolutePosition: {
      x: 301.7109375,
      y: 121.06770833333333
    }
  },
  {
    stack: [

      {
        table: {
          widths: [
            268.515625
          ],
          body: [
            [
              {
                color: '#ffffff',
                text: 'ASP Value Week On Week - Formats',
                style: 'header'
              }
            ]
          ],
          fillColor: '#454545'
        }
      },
      {
        style: table,
        table: {
          headerRows: 1,
          widths: [
            69.77864583333334,
            69.77864583333334,
            69.77864583333334,
            69.77864583333334
          ],
          body: [
            [
              {
                color: '#73879c',
                bold: true,
                text: 'Format'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'Last Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'This Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: '% Var.'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 1'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '€0'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 2'
              },
              {
                color: '#73879c',
                text: '€4'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 3'
              },
              {
                color: '#73879c',
                text: '€5'
              },
              {
                color: '#73879c',
                text: '€1'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ]
          ]
        },
        layout: {}
      }

    ],
    absolutePosition: {
      x: 10.098958333333332,
      y: 214.03645833333331
    }
  },
  {
    stack: [

      {
        image: https:'//bit.ly/2WmKbot',
      fit: [
        278.5130208333333,
        89.86979166666667
      ]
      }

    ],
    absolutePosition: {
      x: 301.7109375,
      y: 214.03645833333331
    }
  },
  {
    stack: [

      {
        table: {
          widths: [
            268.515625
          ],
          body: [
            [
              {
                color: '#ffffff',
                text: 'ASP Value Week On Week - Formats',
                style: 'header'
              }
            ]
          ],
          fillColor: '#454545'
        }
      },
      {
        style: table,
        table: {
          headerRows: 1,
          widths: [
            69.77864583333334,
            69.77864583333334,
            69.77864583333334,
            69.77864583333334
          ],
          body: [
            [
              {
                color: '#73879c',
                bold: true,
                text: 'Format'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'Last Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'This Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: '% Var.'
              }
            ],
            [
              {
                color: '#73879c',
                text: Val 1
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '€0'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 2'
              },
              {
                color: '#73879c',
                text: '€4'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 3'
              },
              {
                color: '#73879c',
                text: '€5'
              },
              {
                color: '#73879c',
                text: '€1'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ]
          ]
        },
        layout: {}
      }

    ],
    absolutePosition: {
      x: 10.098958333333332,
      y: 307.0052083333333
    }
  },
  {
    stack: [

      {
        table: {
          widths: [
            268.515625
          ],
          body: [
            [
              {
                color: '#ffffff',
                text: 'ASP Value Week On Week - Formats',
                style: 'header'
              }
            ]
          ],
          fillColor: '#454545'
        }
      },
      {
        style: table,
        table: {
          headerRows: 1,
          widths: [
            69.77864583333334,
            69.77864583333334,
            69.77864583333334,
            69.77864583333334
          ],
          body: [
            [
              {
                color: '#73879c',
                bold: true,
                text: 'Format'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'Last Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: 'This Week'
              },
              {
                color: '#73879c',
                bold: true,
                text: '% Var.'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 1'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '€0'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 2'
              },
              {
                color: '#73879c',
                text: '€4'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 3'
              },
              {
                color: '#73879c',
                text: '€5'
              },
              {
                color: '#73879c',
                text: '€1'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ]
          ]
        },
        layout: {}
      }

    ],
    absolutePosition: {
      x: 301.7109375,
      y: 307.0052083333333
    }
  },
  {
    stack: [

      {
        table: {
          widths: [
            268.515625
          ],
          body: [
            [
              {
                color: '#ffffff',
                text: 'ASP Value Week On Week - Formats',
                style: 'header'
              }
            ]
          ],
          fillColor: '#454545'
        }
      },
      {
        style: 'table',
        table: {
          headerRows: 1,
          widths: [
            69.77864583333334,
            69.77864583333334,
            69.77864583333334,
            69.77864583333334
          ],
          body: [
            [
              {
                color: '#73879c',
                bold: 'true',
                text: 'Format'
              },
              {
                color: '#73879c',
                bold: 'true',
                text: 'Last Week'
              },
              {
                color:'#73879c',
                bold: 'true',
                text: 'This Week'
              },
              {
                color: '#73879c',
                bold: 'true',
                text: '% Var.'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 1'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '€0'
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 2'
              },
              {
                color: '#73879c',
                text: '€4'
              },
              {
                color: '#73879c',
                text: '€2'
              },
              {
                color: '#73879c',
                text: '-10%'
              }
            ],
            [
              {
                color: '#73879c',
                text: 'Val 3'
              },
              {
                color: '#73879c',
                text: €5
              },
              {
                color: '#73879c',
                text: €1
              },
              {
                color: '#73879c',
                text: '-100%'
              }
            ]
          ]
        },
        layout: {}
      }

    ],
    absolutePosition: {
      x: 10.098958333333332,
      y: 399.9739583333333
    }

  }]
}`

I can't make it work on the playground... but can't identify what is the issue. It might be related..

**Comment by Eva-R** [comment]
Hiya,

Thank you for your quick reply.

Here is a simple exemple:
https://jsfiddle.net/aveIom/s2nLbp91/42/

**Comment by liborm85** [comment]
Screenshot in first post contains two images and talking about some overlay. In example isn't images or repeating nodes.

What is the expected result in pdf document? Clarify your question.

**Comment by tapornanan** [comment]
I have quite the same problems. 

In my case I create pdf act like input forms (called template) and I use absolutePosition to add data inside each one of the field inside template. And I have 2 pages of template and I cannot use absolutePosition to add data into page 2

Any solution or work around ? 

I attached generated version to make my explanation more clear 
[pp01 (2).pdf](https://github.com/bpampuch/pdfmake/files/3284947/pp01.2.pdf)

**Comment by Eva-R** [comment]
@liborm85 I didn't add the pictures to simplify the code. The nature of the component doesn't really matter, What am trying to show in that exemple is absolute position breaksafter a page break.

If you look at the y position of each element here:

![image](https://user-images.githubusercontent.com/22544930/59420161-49a27200-8dc4-11e9-8c96-a51b57572709.png)

Top element are taking the right place but the block called "Block Overlay" should appear at
1007.0052083333333 px on the y-axis. Instead its stock on top of the second page.

**Comment by liborm85** [comment]
Node with text "Block Overlay" have Y position 1007.0052083333333, but page have height only 841.89. Node position is out of page, therefore, text was broken to next page on top position. It is correct.

If you want nodes on next page with absolute position, you have to use page break (see [documentation](https://pdfmake.github.io/docs/document-definition-object/page/)).
Simple example of usage:
```js
var dd = {
  content: [
    {
      text: 'First page',
      absolutePosition: {
        x: 40,
        y: 100
      }
    },
    {
      pageBreak: 'before',
      text: 'Second page',
      absolutePosition: {
        x: 40,
        y: 100
      }
    },
  ]
}
```

On second and next pages, Y stats from 0.

**Comment by Eva-R** [comment]
Page break missing!
Ok I see now. I need also to re-initialize dinamically  the value of Y to make it fit into a 841.89px page. 
Thank you for your help.
