### ISSUE TITLE
Mistake in function markSpans

### ISSUE THREAD

**Issue by hilook** [bpampuch/pdfmake#1743]
When we have cols with spans and cols without spans after them we miss cols which follows after spanned cols.  

May be my opinion is wrong and some misunderstanding there, but:

```
rowData[col + i] = {
				_span: true,
				_minWidth: 0,
				_maxWidth: 0,
				rowSpan: rowData[col].rowSpan
			};
```

This code just rewrite cols and we mess them.

Please check and modify as in my variant: 

```
function markSpans(rowData, col, span) {
		for (var i = 1; i < span; i++) {
			rowData.splice(col + i, 0, {
				_span: true,
				_minWidth: 0,
				_maxWidth: 0,
				rowSpan: rowData[col].rowSpan
			});
			/*rowData[col + i] = {
				_span: true,
				_minWidth: 0,
				_maxWidth: 0,
				rowSpan: rowData[col].rowSpan
			};*/
		}
	}
```

https://github.com/bpampuch/pdfmake/blob/master/src/DocMeasure.js

**Comment by liborm85** [comment]
Attach example runnable on [playground](http://pdfmake.org/playground.html) where this causes some error/problem.

**Comment by hilook** [comment]
I find what I do like not as desined:
In exemples row with spaned cols defines as following:
[{text: 'Header with Colspan = 2', style: 'tableHeader', colSpan: 2, alignment: 'center'}, {}, {text: 'Header 3', style: 'tableHeader', alignment: 'center'}],
I define it without empy col. Like this:
[{text: 'col1-col2', colSpan: 2}, {text: 'col3', colSpan: 1}]

In my cace I change DocMeasure.js and rebuld. As I generate tables from html DOM it's closely to use row sructure as html table row structure.
