### ISSUE TITLE
download() not working for Sharepoint webpart with React js(only in IE11)

### ISSUE THREAD

**Issue by suryarsp** [bpampuch/pdfmake#1744]
The download `download( 'filename', () => { alert('pdf downloaded')})`
is not working specifically in IE. Works fine in Chrome, Edge & Firefox.
I am trying to use download and it's **not working in IE11**.

**Comment by liborm85** [comment]
IE11 doesn't support arrow functions. See https://caniuse.com/#feat=arrow-functions

Not related with pdfmake.

**Comment by suryarsp** [comment]
Even if I use **download('fileName')** it's not working in IE11.

**Comment by suryarsp** [comment]
> IE11 doesn't support arrow functions. See https://caniuse.com/#feat=arrow-functions
> 
> Not related with pdfmake.

Even if I use download('fileName') it's not working in IE11.

**Comment by liborm85** [comment]
Tested on [playground](http://pdfmake.org/playground.html) -> _DOWNLOAD_ button in IE11 and all works correctly.

Is any error in console?

**Comment by suryarsp** [comment]
Nope. Any code after the download() method is not getting executed. The document object to create pdf is also correct. I am not sure why this happens in IE.
I am using pdfMake version **"^0.1.56"**

**Comment by suryarsp** [comment]
> Tested on [playground](http://pdfmake.org/playground.html) -> _DOWNLOAD_ button in IE11 and all works correctly.
> 
> Is any error in console?

No errors on the console. Any code after the download() method is not getting executed. The document object to create pdf is also correct. I am not sure why this happens in IE.
I am using pdfMake version "^0.1.56"

**Comment by suryarsp** [comment]
I don't know how it works in the playground in IE11. But i have used this react js as well as SharePoint webpart. In that case i can't figure out what's the real issue . Do i need to include polyfills.js or some js make it work on the IE11.

**Comment by liborm85** [comment]
In playground it works simply as decribed in [documentation](https://pdfmake.github.io/docs/getting-started/client-side/), see:
> ```html
> <!doctype html>
> <html lang='en'>
> <head>
>   <meta charset='utf-8'>
>   <title>my first pdfmake example</title>
>   <script src='build/pdfmake.min.js'></script>
>   <script src='build/vfs_fonts.js'></script>
> </head>
> <body>
> ...
> ```

I have no idea how you are set up to build a react application, it will probably break something. Try to ask on React support.

**Comment by n00el** [comment]
Same. Not working in IE11 under Sharepoint 2013 and Ract 16. The just loading a lot, then minutes after the browser crash
