### ISSUE TITLE
How to dynamically create a canvas without knowing the page width?

### ISSUE THREAD

**Issue by danosaure** [bpampuch/pdfmake#1748]
How do i get the pageSize in my DD? I see it's a param for header and footer, but what about the rest of the document?

I want to have a line of text, and create a canvas below it the with the the page minus 2 * my custom margin.

The system is pretty much dynamic and I am able to do that in the header and footer, but I cannot figure it out for the rest of the DD. This would also allow me to compute an image's `fit` property (say I want images to fit into 80% of width by 60% of width).

**Comment by liborm85** [comment]
Use defined page size to calculate canvas size.
