### ISSUE TITLE
server-side custom font infinite loop

### ISSUE THREAD

**Issue by danosaure** [bpampuch/pdfmake#1751]
I'm really confused how to add custom fonts in **server-side**.

I have the following `FONTS`:

```
const FONTS = {
    // https://github.com/vernnobile/MuliFont/tree/master/version-2.0
    Muli: {
        normal: path.join(baseFontDir, 'Muli'),
        bold: path.join(baseFontDir, 'Muli-Bold.ttf'),
        italics: path.join(baseFontDir, 'Muli-Italic.ttf'),
        bolditalics: path.join(baseFontDir, 'Muli-BoldItalic.ttf')
    },

    // https://github.com/vernnobile/OswaldFont/tree/master/3.0
    Oswald: {
        normal: path.join(baseFontDir, 'Oswald-Regular.ttf'),
        bold: path.join(baseFontDir, 'Oswald-Bold.ttf'),
        italics: path.join(baseFontDir, 'Oswald-Regular.ttf'),
        bolditalics: path.join(baseFontDir, 'Oswald-Bold.ttf')
    },

    // Standard 14 fonts
    Courier: {
        normal: 'Courier',
        bold: 'Courier-Bold',
        italics: 'Courier-Oblique',
        bolditalics: 'Courier-BoldOblique'
    },
    Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique'
    },
    Times: {
        normal: 'Times-Roman',
        bold: 'Times-Bold',
        italics: 'Times-Italic',
        bolditalics: 'Times-BoldItalic'
    },
    Symbol: {
        normal: 'Symbol'
    },
    ZapfDingbats: {
        normal: 'ZapfDingbats'
    },

    // https://github.com/bpampuch/pdfmake/tree/master/examples/fonts
    Roboto: {
        normal: path.join(baseFontDir, 'Roboto-Regular.ttf'),
        bold: path.join(baseFontDir, 'Roboto-Medium.ttf'),
        italics: path.join(baseFontDir, 'Roboto-Italic.ttf'),
        bolditalics: path.join(baseFontDir, 'Roboto-MediumItalic.ttf')
    }
};
```
(all the files are put in the same folder).

When I set the following `defaultStyle: { font }` to either `Oswald` or `Muli`, and trying to generate my document, it goes into what seems like an infinite loop. If I try any system font or even `Roboto`, the PDF generates without an issue.

The feeling of the infinite loop is because I modified the following file `node_modules/pdfmake/src/docMeasure.js` with the following:

```
let counter = 0;
DocMeasure.prototype.measureLeaf = function (node) {
    console.log(`@@@ DocMeasure.measureLeaf()...`, ++counter);
```

and normally, with most fonts, it's called up to 700 times with my content, but when using either `Muli` or `Oswald`, I have left it run up to 200k, and it was not done, so that's why I am thinking there is something wrong with the font files.

Is there something wrong with the fonts I am using? I'm no export on fonts and are just required to use those specific fonts. I am using version `pdfmake@0.1.57` (latest).

Very much appreciate any help here, i've been trying to figure this one out all day.

Thanks everyone.

**Comment by danosaure** [comment]
After changing the content a lot, it is now apparently working and I no longer get the infinite loop. I am unable to figure out why it was not working and suddenly starting to work (I "mistakenly" assign a custom font in a style and have "Courier" as `defaultStyle.font` and realized that it did not break.)

Closing the issue since I cannot reproduce it.

**Comment by danosaure** [comment]
Actually, I am able to reproduce this again. Let me know how I can send you the docDefinition.

**Comment by liborm85** [comment]
You can docDefinition paste here to post.

**Comment by danosaure** [comment]
Hi, sorry, I was on vacations... Just got back. How do I provide the font here?
