### ISSUE TITLE
Large bundle size with webpack

### ISSUE THREAD

**Issue by Turan91** [bpampuch/pdfmake#1752]
Adding this library to a React project increases bundle size by 40mb.

**Comment by Karankang007** [comment]
Noticing the same behavior with the Angular project as well.
On closer look, it seems PDFMake is inlining all fonts and images.

**Comment by blikblum** [comment]
>  it seems PDFMake is inlining all fonts and images.

Probably.

You can try https://github.com/blikblum/pdfmake-utils to load fonts and images as binary and on demand

**Comment by liborm85** [comment]
40 MB is a lot, I assume you used a font with a big file. There is no satisfactory solution, because pdfmake needs a font file in the browser..
