### ISSUE TITLE
PDF is not printable if generated in 1.7 version

### ISSUE THREAD

**Issue by Akta3d** [bpampuch/pdfmake#1759]
Is it normal that pdf are not printable when set these permission ?

```
version: '1.7ext3',
// userPassword: '123',
ownerPassword: '******',
permissions: {
  printing: 'highResolution', 
  modifying: false,
  copying: false,
  annotating: false,
  fillingForms: false,
  contentAccessibility: true,
  documentAssembly: false
},   
content : [...]
```

**Comment by blikblum** [comment]
What version are you using?

Also what happens If you do not set password?

**Comment by Akta3d** [comment]
I use last version of pdfmake, updated yesterday

If I comment owner password the pdf is printable.

Le ven. 28 juin 2019 à 22:51, Luiz Américo <notifications@github.com> a
écrit :

**Comment by Akta3d** [comment]
I have made new tests.

If I set a password all permissions are allways setted to false, permissions properties has no effect.
If I don't set password all is possible and permissions property has no effect.

I verify file permissions with Acrobat Reader

**Comment by blikblum** [comment]
What happens if you set version to 1.4, 1.5 or 1.6 keeping the password?

**Comment by Akta3d** [comment]
All works if I change
`version: '1.7ext3'`
to
`version: '1.7',`

**Comment by liborm85** [comment]
Fixed by https://github.com/foliojs/pdfkit/pull/1126
