### ISSUE TITLE
Ordered List counter value trims trailing zeros (1.10 becomes 1.1)

### ISSUE THREAD

**Issue by Quixomatic** [bpampuch/pdfmake#1760]
When trying to use decimal on the counter value in an ordered list, the decimal value trims trailing 0's making the value something like `10.1` instead of the desired `10.10`

```
var dd = {
	content: [
		{text: '\n\nOrdered list with float start value', style: 'header'},
		{
			ol: [
				{text: 'item 1', counter: 10.10},
				{text: 'item 2', counter: 10.11},
				{text: 'item 3', counter: 10.12},
				{text: 'item 4 without own value'}
			]
		},
	]
}
```

yields a list that looks like this:
```
Ordered list with foat start value
10.1. item 1
10.11. item 2
10.12. item 3
4. item 4 without own value
```

**Comment by liborm85** [comment]
`counter` is numeric format and value entered as `10.1000000000` is still only `10.1`.
Feature request for nested list numbers is here: https://github.com/bpampuch/pdfmake/issues/959

**Comment by Quixomatic** [comment]
@liborm85, I really don't think this should be lumped in with the other enhancement request. Is there no way to allow the counter to take a string value instead of a float?

`counter: '10.10'` would be a simple work around, but since it is expecting a numeric value it is removing unneeded zeros.

If you could point me in the right direction to where this is parsed within the library I'd be happy to make the change myself, I'm just not familiar with your project's structure.

**Comment by gopusrikanth04** [comment]
for : 1.1.1

    ol: [
		{text: 'item 2', counter: 1.1.1},
	]

It showing NaN.

how to solve this problem
