### ISSUE TITLE
TOC not displayable in bookmarks panel

### ISSUE THREAD

**Issue by 1Apar** [bpampuch/pdfmake#1761]
Is it possible to make the TOC appear in the bookmarks panel of the browser/viewing program, as displayed in screenshot ?

![bookmarksPanel](https://user-images.githubusercontent.com/49903337/60954099-142b6e80-a307-11e9-9e64-5e9cdcfd4e55.png)

**Comment by liborm85** [comment]
Feature request for bookmarks is here: https://github.com/bpampuch/pdfmake/issues/427
