### ISSUE TITLE
Changing text color and fillColor in table causes text to be invisible

### ISSUE THREAD

**Issue by Th3OnlyN00b** [bpampuch/pdfmake#1762]
This: 
```
table: {
   body: [
      {
         text: "hello",
         color: 'FFFFFF',
         fillColor: "FF0000"
      }
   ]
}
```
shows up as a blank cell

**Comment by liborm85** [comment]
How to create table in pdfmake is described in [documentation](https://pdfmake.github.io/docs/document-definition-object/tables/) or you can look on [playground](http://pdfmake.org/playground.html) > _TABLES_ tab.

**Comment by Th3OnlyN00b** [comment]
Yes, I've attempted the operation on both my local machine and in the
playground. What I'm attempting to do is not covered in their the
documentation or the playground, and I've tested it extensively.

**Comment by liborm85** [comment]
Correct table definition is needed (is described in documentation).
Simple example of table definition:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					[{text: 'Column 1', color: '#FF0000', fillColor: '#00FF00'}, 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		}
	]
}
```

**Comment by Th3OnlyN00b** [comment]
I realize the sample code I posted was incorrect but the code I had been testing with was correct. Sorry. Fixed anyways tho!
