### ISSUE TITLE
addWatermark getSize not returning good values for short text

### ISSUE THREAD

**Issue by dibell** [bpampuch/pdfmake#1764]
Watermarks with short strings do not render optimally. Draft would be a common watermark text.  Below is an example definition for the playground (and screenshot attached).

For longer text the rendering is much better.

![watermark](https://user-images.githubusercontent.com/467510/61387299-c9cd6300-a8ad-11e9-9e44-a8e22642a370.png)

```
var dd = {
    "watermark": "Draft",
    "content": [
        {
            "table": {
                "widths": ["100%"],
                "body": [
                    ["test"]
                ]
            }
        }
    ]
}
```

**Comment by dibell** [comment]
Added PR #1766 as an attempt to fix this.

**Comment by liborm85** [comment]
Fixed by [commit](https://github.com/bpampuch/pdfmake/commit/adf6526a30e2e6b1bb3a5bae4b283acb4c5ff076) (in brach 0.1) and [in PR](https://github.com/bpampuch/pdfmake/pull/1780) (in master).
