### ISSUE TITLE
Cannot assign to 'vfs' because it is a constant or a read-only property.

### ISSUE THREAD

**Issue by KamayaniT** [bpampuch/pdfmake#1769]
Hi,

I am using Ionic 4  and as instructed, this is what I am doing with the latest version of plugin (0.1.57)
After running npm install pdfmake

in my page.ts :
```
import * as pdfMake from 'pdfmake/build/pdfmake'
import * as pdfFonts from 'pdfmake/build/vfs_fonts'
pdfMake.vfs = pdfFonts.pdfMake.vfs;

```

the last line returns error saying it cannot be assigned as it is constant ? Do I have to do any other changes as well ?

**Comment by blikblum** [comment]
import  pdfMake from 'pdfmake/build/pdfmake'
import  pdfFonts from ...

**Comment by KamayaniT** [comment]
The above syntax gives error.

**Comment by blikblum** [comment]
OK. Good luck.

**Comment by KamayaniT** [comment]
Do u have any idea what can be the issue ? I even tried to downgrade but still had the same error.

**Comment by Lukeozade** [comment]
@KamayaniT Add code like this

`import pdfMake from 'pdfmake/build/pdfmake';`
`import pdfFonts from 'pdfmake/build/vfs_fonts';`

instead of your original imports. 

Credit to @blikblum for saying this. I just did this and it worked for me. 
Thank you!

All the best :)

**Comment by liborm85** [comment]
All is in [documenation](https://pdfmake.github.io/docs/getting-started/client-side/).

**Comment by zmharker** [comment]
This [example from SO](https://stackoverflow.com/a/56535907/6119323) helped me (Angular 7)

**Comment by DraviaVemal** [comment]
Add the font files in createPDF

```
pdfMake.createPdf(
      this.docDefinition,
      {},
      {
        // Default font should still be available
        Roboto: {
          normal: 'Roboto-Regular.ttf',
          bold: 'Roboto-Medium.ttf',
          italics: 'Roboto-Italic.ttf',
          bolditalics: 'Roboto-Italic.ttf'
        },
        // Make sure you define all 4 components - normal, bold, italics, bolditalics - (even if they all point to the same font file)
        TimesNewRoman: {
          normal: 'Times-New-Roman-Regular.ttf',
          bold: 'Times-New-Roman-Bold.ttf',
          italics: 'Times-New-Roman-Italics.ttf',
          bolditalics: 'Times-New-Roman-Italics.ttf'
        }
      },
      pdfFonts.pdfMake.vfs);
```
