### ISSUE TITLE
QR Code Can't be fit

### ISSUE THREAD

**Issue by Karthik-Pandiyan** [bpampuch/pdfmake#1777]
I am using 113 characters length of string for QR code, whether I try to fix the size using fit "80" qr code size getting very small or using fit "90" qr code size getting bigger. I want to fit the size between small and big but I can't. could you please help me to fix it out.

Eg QR string length: "https://localhost:4444/abcdefghijk/lmnopq/x?AlSC=1235454SG45560SASDH5SADEF4ASD5A6SDASD1A6SD54DAS2DD456ASDAS2DIIII"

**Comment by liborm85** [comment]
QR code cannot take all values, it must be adapted to "QR grid".
