### ISSUE TITLE
Two equals tables doesn't work together 

### ISSUE THREAD

**Issue by jonasaraujo96** [bpampuch/pdfmake#1778]
One table works, but two quals tables doesn't work.

Only Table 1
![image](https://user-images.githubusercontent.com/36088468/61906960-d92e5b00-af02-11e9-8880-c8c35fa4fc61.png)

Only Table 1
![image](https://user-images.githubusercontent.com/36088468/61906902-b7cd6f00-af02-11e9-87f0-e05c6a38d220.png)

Only Table 2
![image](https://user-images.githubusercontent.com/36088468/61907004-f2cfa280-af02-11e9-9600-186bc88f9349.png)

Only Table 2
![image](https://user-images.githubusercontent.com/36088468/61907053-0aa72680-af03-11e9-8ae0-885b55f36133.png)

Table 1 and Table 2
![image](https://user-images.githubusercontent.com/36088468/61907085-1f83ba00-af03-11e9-8ffa-22c1d99c34ba.png)

Table 1 and Table 2
![image](https://user-images.githubusercontent.com/36088468/61907116-34604d80-af03-11e9-89c4-7f1be5d0dfb5.png)

**Comment by dorothythurston** [comment]
🤔 It might be that pdfmake is modifying what you pass in as body so passing the same object twice leads to weirdness. Maybe try doing like `body: [...reportData.perguntasRespostas]`

**Comment by davidgatti** [comment]
Make a copy of the object: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/assign, and see if that helps, if it does, then something is happening with the original object.

**Comment by MegaJerk** [comment]
I've recently run into this problem as well. It's not just identical tables, but can also be identical rows or cell objects. Making a copy of the object using Object.assign() is helpful for the initial row of data, but interestingly doesn't work if the same row is reused! 

Using the following code: 
`var columnData_Text = ["Test Text"];
var columnData_Object = [{text: "Test Text"}];

var textRow = [columnData_Text[0], columnData_Text[0]];
var objectRow = [columnData_Object[0], columnData_Object[0]];
var objectAssignRow = [Object.assign({}, columnData_Object[0]), Object.assign({}, columnData_Object[0])];

var testTable_Text = {table: {body: [textRow, textRow]}};
var testTable_Object = {table: {body: [objectRow, objectRow]}};
var testTable_ObjectAssign = {table: {body: [objectAssignRow, objectAssignRow]}};

var dd = {
  content: [
      "Text Table",
      "\n", 
      testTable_Text,
      "Object Table",
      "\n", 
      testTable_Object, 
      "Object Assign Table",
      "\n", 
      testTable_ObjectAssign
  ]  
};`

you get the following results:
![image](https://user-images.githubusercontent.com/1424749/69569086-e4fe5c80-0f8a-11ea-871d-7b56743f2bfa.png)

**Comment by gerardosocias29** [comment]
I used this one to duplicate the data from table 1 to table 2 and it works :)

[#1775](https://github.com/bpampuch/pdfmake/issues/1775#issuecomment-540823497)

![Screenshot from 2024-02-15 20-56-43](https://github.com/bpampuch/pdfmake/assets/30705811/2338a83e-73b8-4aff-9e04-9684ec002068)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/465
