### ISSUE TITLE
Browser crashes for very large data

### ISSUE THREAD

**Issue by jasonejavier** [bpampuch/pdfmake#1787]
We're trying to create a 7000+ data (about 300 pages of pdf) for inventory reports and the web tab stops responding and then crashes. I don't know why because the data are already preloaded. Does this library support this large amount of data? Thank you for any answers

**Comment by damianmalinowski** [comment]
There are various ways to show or download Pdf. 
In my case, I have a report even about 1500 pages.
Only one way handles such a big report by creating ObjectURL. 

Here is an example:
`
        const pdfDocGenerator = pdfMake.createPdf(definition);
        pdfDocGenerator.getBlob((blob: Blob) => {
          const pdfObjectUrl = URL.createObjectURL(blob);
          resolve(pdfObjectUrl);
        });
`

**Comment by dorothythurston** [comment]
I have been able to generate very large pdfs but once I had trouble and I found out it was not pdfmake's fault it was how I was assembling the pdf definition when injecting the data that was very memory intensive. Try seeing if there is any memory intensive operations you are doing with your data?
