### ISSUE TITLE
SVG rendering craches if width or height has decimal 

### ISSUE THREAD

**Issue by flip-it** [bpampuch/pdfmake#1788]
If the svg content is:
 ```
<svg width="217.82" height="46.15" viewBox="0 0 217.82 46.15">…</svg>
```
it fails to render and throws: `Error: unsupported number: NaN`. Removing the decimal part of width and height solves it (viewBox doesn’t matter). Decimals should be valid though =/

Otherwise I love the svg support!

**Comment by liborm85** [comment]
cc @cyrixmorten

**Comment by cyrixmorten** [comment]
Thank you for reporting this, should be fixed with https://github.com/bpampuch/pdfmake/pull/1790
