### ISSUE TITLE
TS Definitions out of date/inaccurate

### ISSUE THREAD

**Issue by mweiczorek** [bpampuch/pdfmake#1789]
The TypeScrpit definition files at https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/pdfmake/index.d.ts seem to be out of date, as I get all kinds of compile errors when trying to use it.

It seems this may have been written by a third party, but wouldn't it make sense to curate your own definitions, given the breadth of this library?

**Comment by liborm85** [comment]
PR is welcomed.

Feature request is here: https://github.com/bpampuch/pdfmake/issues/525
