### ISSUE TITLE
SVG-to-pdfkit not included

### ISSUE THREAD

**Issue by jhung0108** [bpampuch/pdfmake#1791]
Hello,

Wondering when the new build to support svg-to-pdfkit will be created? #1781

**Comment by liborm85** [comment]
see [documentation](https://pdfmake.github.io/docs/document-definition-object/svgs/)

**Comment by paw-leitwert** [comment]
@liborm85 I have installed `svg-to-pdfkit` and `pdfmake@0.1.58`, however I still get the error `Please install svg-to-pdfkit to enable svg nodes`. The workaround described [here](https://github.com/bpampuch/pdfmake/issues/1781#issuecomment-517712668) works, but is not a good solution (e.g. when you wipe and reinstall packages, also doesn't work on CI runner).
Any chance you could make a new release with this build already included?

Thanks for your great work!
