### ISSUE TITLE
Hebrew support

### ISSUE THREAD

**Issue by omrivm** [bpampuch/pdfmake#1792]
I was playing with the playground and entered Hebrew chars. In the preview, all I can see are boxes with X in it. Dose pdfmake supports Hebrew?

For exmaple:
var dd = {
	content: [
		'First paragraph',
		'עברית',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
	
}

Thanks!

**Comment by dorothythurston** [comment]
You should be able to add a new set of font ttfs that include hebrew characters to your project and set those as the font for your document. I do not think any of the fonts that ship with pdfmake itself out of the box have character support for hebrew. I have used google noto in a project I have used pdfmake in https://www.google.com/get/noto/ and I believe it supports hebrew characters
