### ISSUE TITLE
Client-side SVG build includes webpack error

### ISSUE THREAD

**Issue by jkoudys** [bpampuch/pdfmake#1794]
1.38, in the `build/pdfmake.js`, I see:

```
var getSvgToPDF = function () {
        try {
                // optional dependency to support svg nodes
                return __webpack_require__(!(function webpackMissingModule() { var e = new Error("Cannot find module 'svg-to-pdfkit'"); e.code = 'MODULE_NOT_FOUND'; throw e; }()));
        } catch (e) {
                throw new Error('Please install svg-to-pdfkit to enable svg nodes');
        }
};
```
So it's always failing when I try to render an SVG node. Would be nice if I could inject the `svg-to-pdfkit` myself, especially since these libs are huge so I always async `import()` them to code split them away.

**Comment by kwkelly** [comment]
This looks like it's related to https://github.com/bpampuch/pdfmake/issues/1791 and https://github.com/bpampuch/pdfmake/issues/1781 

There is a workaround, but something needs to be done to fix the build process.
