### ISSUE TITLE
Unable to use SVG inside header and footer

### ISSUE THREAD

**Issue by d3xtr0** [bpampuch/pdfmake#1797]
Using any SVG inside the header or footer will display nothing without errors.  
I also tried with wrapping columns and giving it a width/height.  
Tested in Playground and locally (v0.1.58)

```
header: (currentPage, pageCount, pageSize) => {
    return [{
        svg: '<svg viewBox="0 0 24 24">...</svg>'
    }]
},
```

Possible fix:  
```
// elementWriter.js:290
case "svg":
    var img = pack(item.item);

    img.x = (img.x || 0) + (useBlockXOffset ? block.xOffset || 0 : ctx.x);
    img.y = (img.y || 0) + (useBlockYOffset ? block.yOffset || 0 : ctx.y);

    page.items.push({
        type: "svg",
        item: img
    });
    break;
```

**Comment by kwkelly** [comment]
This also affects tables. I've submitted a PR. Thanks for finding where the issue was, I was racking my brain yesterday trying to follow.
