### ISSUE TITLE
Apply style for PDF Print View

### ISSUE THREAD

**Issue by dineshdedhia** [bpampuch/pdfmake#1799]
How do I apply styling in print view PDF like cellspacing (Th and Td spacing) specific font

**Comment by liborm85** [comment]
Cellspacing is not supported now.
Feature requests: https://github.com/bpampuch/pdfmake/issues/725, https://github.com/bpampuch/pdfmake/issues/724, https://github.com/bpampuch/pdfmake/issues/272
