### ISSUE TITLE
Cant print pdf with chrome

### ISSUE THREAD

**Issue by gwoplock** [bpampuch/pdfmake#1800]
When I try to print a pdf from chrome with `pdfMake.createPdf(docDefinition).print();` the new tab that opens stays blank and the console for the pdf viewer has this error message `blob:https://127.0.0.1/488588ca-387e-429d-abe4-25bd6c4e867e:1 Refused to load plugin data from 'blob:https://127.0.0.1/488588ca-387e-429d-abe4-25bd6c4e867e' because it violates the following Content Security Policy directive: "default-src 'self' 'unsafe-inline' 'unsafe-eval'". Note that 'object-src' was not explicitly set, so 'default-src' is used as a fallback.
`

Any thoughts as to why this is happening?

using:
chrome: 76.0.3809.100
angular: 7.2.15
pdfmake: 0.1.58

**Comment by liborm85** [comment]
It is not related with pdfmake.

Your application have too strict Content-Security-Policy settings, must be set correctly, see: https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Content-Security-Policy
