### ISSUE TITLE
How to create Horizontal WaterMark instead of Diagonial Default ?

### ISSUE THREAD

**Issue by goxr3plus** [bpampuch/pdfmake#1801]
Hi :) ? I am new user of this library and i saw how to create a simple water mark like :

``` JAVA
var docDefinition = {
    watermark: { text: "watermark", color: "gray", opacity: 0.3, bold: true, alignment: "right" },
	content: [
  
	]
}
```

![brave_2019-09-03_15-13-42](https://user-images.githubusercontent.com/20374208/64172349-70b98e80-ce5d-11e9-859b-12523224e2f2.png)

But how can i make the text of it be horizontal instead of diagonal ? 

@bmihelac  Thank you .

**Comment by liborm85** [comment]
Not now.
PR for improve watermark (eg. add rotation angle for text) is Draft and in development: https://github.com/bpampuch/pdfmake/pull/1780

**Comment by liborm85** [comment]
Use version 1.0.60 and see [documenation](https://pdfmake.github.io/docs/document-definition-object/watermark/).
