### ISSUE TITLE
How to add image to a table in header block

### ISSUE THREAD

**Issue by gotpewi2** [bpampuch/pdfmake#1802]
Hi,
I'm a new user of pdfmake and want's to use an image in the header block and place it in a table column but I don't fix it!!!

The block I'm trying to use is:

    generateBaseDocument(headerText: string, orientation: string, creationDate: string, pageBreakFunction?: (currentNode: any, followingNodesOnPage: any, nodesOnNextPage: any, previousNodesOnPage: any) => boolean) {
        var document = {
            header: 
            {
                table: {
                    widths: ["*", "50%", "*"],
                    body: 
                    [
                        [
                            {
                                stack: 
                                [
                                    {
                                        image: this.fragusLogo,
                                        fit: [150 * this.pointConversion, 80 * this.pointConversion],
                                        style: "logo", 
                                        margin: 10
                                    } 
                                ],
                                margin: 10,
                                layout: "noBorders"
                            },                            
                            { text: headerText ,
                              style: "header"
                            },
                            {
                                text: creationDate,
                                style:  "date"
                            }
                        ]
                    ]
                }
              },
            footer: 
                {
                    text: this.vehicleInfo,
                    style: "smallText",
                    alignement: "center"
                },       
            pageOrientation: orientation,
            content: [],
            pageBreakBefore: pageBreakFunction,
            styles: {
                header: {
                    fontSize: 18,
                    bold: true,
                    alignment: "center"
                },
                subheader: {
                    fontSize: 12,
                    bold: true
                },
                text: {
                    fontSize: 8
                },
                logo: {
                    alignment: "left"
                },
                date: {
                    fontSize: 8,
                    alignment: "right"
                },
                orgLogo: {
                    alignment: "center"
                },
                preamble: {
                    fontSize: 8,
                    bold: false
                },
                insuranceLogo: {
                    alignment: "right"
                },
                insuranceContactInfo: {
                    fontSize: 7,
                    bold: false,
                    alignment: "left"
                },
                totalcostheader: {
                    fontSize: 18,
                    bold: true,
                    alignment: "left"
                },
                totalcost: {
                    fontSize: 18,
                    bold: true,
                    alignment: "right"
                },
                totalcount: {
                    fontSize: 12,
                    bold: true,
                    alignment: "right"
                },
                sum: {
                    fontSize: 10,
                    bold: true
                },
                cost: {
                    fontSize: 8,
                    bold: true
                },
                smallText: {
                    fontSize: 6
                }
            }
        };
        return document;
    }

Everything but the image is working fine. Please advise me on how to fix this issue-

Best regareds Peter

**Comment by liborm85** [comment]
Like this:
```js
var dd = {
    header: function(currentPage, pageCount, pageSize) {
        return {image: 'sampleImage.jpg', fit:[50,50]};
    },
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
	
}
```

or like this:
```js
var dd = {
    header: function(currentPage, pageCount, pageSize) {
        return {
			table: {
			    widths: [200,100,200],
				body: [
					['Column 1', {image: 'sampleImage.jpg', fit:[50,50]}, 'Column 3'],
				]
			}
		};
    },    
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
	
}
```
