### ISSUE TITLE
 How big is the page size for printing on 80mm and 50mm printers?

### ISSUE THREAD

**Issue by diegoestacho999** [bpampuch/pdfmake#1803]
First, sorry for the bad English.

I currently have a A4 size pdf generation that works perfectly. But I will need to adapt this same generation today to 80mm and 50mm printers, similar to those of credit cards.

My question is, can I get this same pdf that is ready today, and make it responsive to these printer models?

Can I add multiple page sizes within this method that is ready to generate this print on multiple printers?

What is the way I should go to do this work?

**Comment by liborm85** [comment]
It depends on the printer driver whether it is able to reduce A4 to printer paper size.
In pdf one page can only have one page size.
