### ISSUE TITLE
Support watermark angles

### ISSUE THREAD

**Issue by goxr3plus** [bpampuch/pdfmake#1804]
As far as i see there is no option to rotate the watermark angle , i need it horizontal instead of diagonial :

https://github.com/bpampuch/pdfmake/blob/2c02af7d364782c3d9fa43babfd07ca04b08321d/src/Renderer.js#L277

Can we discuss on how can i implement it ?

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1801
