### ISSUE TITLE
Show pagenumber + number of pages

### ISSUE THREAD

**Issue by elymatos** [bpampuch/pdfmake#1805]
Hi, thanks for the work!
I'm generating a simple pdf report from database table records, using "table" in DocDefinition. I'm wondering how to add a footer in each page, with pageNumber + total of pages (something like "page x from y", where x is the currentPage and y is the total of pages of document).
In my data I already have the total of records, but as the cell content can wrap at some lines, it is difficult to calculate the total of pages based on it.
Is it possible in pdfmake?
Thanks,
Ely

**Comment by SergioFloresG** [comment]
Like this.  
```js
function footer (currentPage, pageCount, pageSize) {
    return [{
        margin: [31, 0, 31],
        layout: {
            hLineColor: (i) => (i === 0) ? 'lightgray' : '',
            vLineWidth: (i) => 0,
            hLineWidth: (i) => (i === 0) ? 1 : 0
        },
        table: {
            widths: ['*', 160, 160],
            body: [
                [
                    {text: '(c) 2019, ', fontSize: 8},
                    {text: '#', alignment: 'center'},
                    {text: `${currentPage}/${pageCount}`}
                ]
            ]
        }
    }];
};
```

and in object definition.

```js
{
    pageSize: 'A4',
    pageOrientation: 'landscape',

    footer: this.footer()
}
```

**Comment by elymatos** [comment]
Thanks for answer!
I've tried different ways to declare the function outside doc definition, but what works was

    footer: (currentPage, pageCount, pageSize) => {
        return [{
            margin: [31, 0, 31],
            layout: {
                hLineColor: (i) => (i === 0) ? 'lightgray' : '',
                vLineWidth: (i) => 0,
                hLineWidth: (i) => (i === 0) ? 1 : 0
            },
            table: {
                widths: ['*', 160, 160],
                body: [
                    [
                        {text: '(c) 2019, ', fontSize: 8},
                        {text: '#', alignment: 'center'},
                        {text: `${currentPage}/${pageCount}`}
                    ]
                ]
            }
        }];
    },

**Comment by SergioFloresG** [comment]
Sorry, if u need a function outside of dd. call your function like a callback. 
I correct my previous answer.

**Comment by elymatos** [comment]
Thanks again!
