### ISSUE TITLE
Dynamic page numbers in body of document

### ISSUE THREAD

**Issue by gdeichen** [bpampuch/pdfmake#1806]
Hey guys, 

Great library, thanks.

Is it possible to add a page number within the PDF document dynamically from content that's generated later?

Something like a function that returned the page number of a linkToDestination (specified by ID/name). Or some sort of hack of ToC?

**Comment by SergioFloresG** [comment]
See this  #1805

**Comment by gdeichen** [comment]
Hi,

Thanks for the reply; that seems to only allow me to do sequential page numbering and only in the footer(?)

What I'm hoping to be able to do is something along the lines of retrieving a page number from an id, so if I don't know which of my pages will wrap onto another page during generation I can still provide a page number (to make it easier to find the referenced item if the PDF is printed). Is that possible?

var dd = {
  content: [
    { text: 'Page 1' },
    { text: 'I can make a link to different things like this:', margin: [0, 20, 0, 0] },
    { text: 'Cool thing', linkToDestination: 'cool', margin: [0, 20, 0, 0] },
    { text: 'But what I want to be able to do is to also somehow get the page number from that id, so it looks like (for example) this:', margin: [0, 20, 0, 0] },
    { text: 'See: Cool thing (page 2)', linkToDestination: 'cool', margin: [0, 20, 0, 0] },
    { text: '', pageBreak: 'after' },
    { text: 'Page 2' },
    { text: 'An item of interest', id: 'interest', margin: [0, 20, 0, 0] },
    { text: 'Something cool', id: 'cool', margin: [0, 20, 0, 0] },
    { text: '', pageBreak: 'after' },
    { text: 'Page 3' },
    { text: 'Link to an interesting thing', linkToDestination: 'interest', margin: [0, 20, 0, 0] },
  ]
}

**Comment by liborm85** [comment]
You can use table of content (see [examples/toc.js](https://github.com/bpampuch/pdfmake/blob/0.1/examples/toc.js)) or own page referencing (see [examples/pageReference.js](https://github.com/bpampuch/pdfmake/blob/0.1/examples/pageReference.js)).

**Comment by gdeichen** [comment]
Perfect, thanks!
