### ISSUE TITLE
IE (11) download() error since v0.1.57

### ISSUE THREAD

**Issue by grovolis** [bpampuch/pdfmake#1811]
Hi all, 
I've been getting an error on IE 11 when trying to download a pdf, more specifically: 
`SCRIPT5005: String expected: pdfmake.min.js (37,413940)`
This error does not occur prior to 0.1.57 with exactly the same code and dependencies. You may reproduce this error with this simple example: 

`var dd = {
                content: [
                    'Test'
                ]
            }
            pdfMake.createPdf(dd).download("Report.pdf");`

It's working fine on the playground for me (v0.1.60) so not sure what really the problem here.

**Comment by liborm85** [comment]
Tested minified pdfmake with versions 0.1.57, 0.1.58, 0.1.59, 0.1.60 in IE 11 and all works correctly.
