### ISSUE TITLE
Multi language Support Issue

### ISSUE THREAD

**Issue by michelabikhalil** [bpampuch/pdfmake#1812]
Hello,

In our case we use the export in Arabic and English language depending on the results from the database(1 app with 2 languages at the same time). 
Currently based on the selected fonts, one of the language will work correctly while the other wont. 
Could you please advise how can we achieve this in datatables

**Comment by liborm85** [comment]
You can use setting font via `style`, see example:
```js
var dd = {
	content: [
		{ text: 'Text in language A', style: 'langA' },
		{ text: 'Text in language B', style: 'langB' }
	],
	styles: {
		langA: {
			font: 'Font1',
		},
		langB: {
			font: 'Font2',
		}
	}
};
```

**Comment by german-st** [comment]
Hello.

Please help. My[ issue](https://github.com/bpampuch/pdfmake/issues/2218) is defined mixed content in one pdf

**Comment by imPrashik** [comment]
try using "Arial_Unicode_MS", this font supports many languages.

[WikiPedia](https://en.wikipedia.org/wiki/Arial_Unicode_MS#:~:text=The%20code%20pages%20supported%20are,Devanagari)
