### ISSUE TITLE
 pdf for woocommerce variable product

### ISSUE THREAD

**Issue by tvalades** [bpampuch/pdfmake#1815]
Hello! 
I am using pdfmake as a technical data sheet on woocommerce.
In simple products it works perfectly but at the moment of variable products I always get the same error:
Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js) and I have all the images in base64 in the vsfonts file.

Thank you very much in advance

**Comment by liborm85** [comment]
You probably don't have images there or in invalid format.
