### ISSUE TITLE
Ipad and safari print issue

### ISSUE THREAD

**Issue by ashok234** [bpampuch/pdfmake#1816]
Hi I'm unable to print page in Ipad safari browser.

**Comment by liborm85** [comment]
Thanks for the information.
Any details?

**Comment by ashok234** [comment]
Please check this  in http://pdfmake.org/playground.html in ipad safari browser
nt able print the pdf

**Comment by liborm85** [comment]
see [Supported browsers](https://github.com/bpampuch/pdfmake/issues/800#issue-197996544)

On ipad is probably supported only download action.
