### ISSUE TITLE
Font 'Roboto' in style 'normal' is not defined in the font section of the document definition

### ISSUE THREAD

**Issue by snr-lab** [bpampuch/pdfmake#1818]
Hi,
I am trying to create an API which will accept JSON data and return a pdf file. I want to use build files pdfmake.js and vfs_fonts.js which I kept in the same directory. Unfortunately, I am getting the issue saying "Font 'Roboto' in style 'normal' is not defined in the font section of the document definition". I am attaching the server.js code for reference. It will be great if you help me to resolve the issue.

`
var http = require('http');
var express = require('express');
var path = require('path');
var bodyParser = require('body-parser');
var cors = require('cors');

var pdfMake = require('./pdfmake');
var pdfFonts = require('./vfs_fonts');

var app = express();

app.use(bodyParser.json({ limit: '50mb' }));
app.use(bodyParser.urlencoded({ extended: false }));
function createPdfBinary(docDefinition) {
	pdfMake.setFonts(pdfFonts);
	
	var pdf = pdfMake.createPdf(docDefinition);
	return pdf.getDataUrl();
}
app.use(cors());
app.post('/pdf', function (req, res) {
	var docDefinition = req.body.content;
	console.log(docDefinition);
	//For testing
	docDefinition = {content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]}
	createPdfBinary(docDefinition).then(function (binary) {
		res.contentType('application/pdf');
		res.send(binary);
	}, function (error) {
		res.send('ERROR:' + error);
	});

});

var server = http.createServer(app);
var port = process.env.PORT || 1234;
server.listen(port);

console.log('http server listening on port %d', port);
console.log('dev-playground is available at http://localhost:%d', port);
`

**Comment by snr-lab** [comment]
Finally, I resolved it. The following code helped me.

var pdfMake = require('./pdfmake');
var pdfFonts = require('./vfs_fonts');

pdfMake.addVirtualFileSystem(pdfFonts);

**Comment by vilmes21** [comment]
Since a few standard fonts are available already, and if you don't need Roboto, you can also resolve this issue by using another font. In docDefinition obj, set:
```
defaultStyle: {
    font: "Helvetica",
    lineHeight: 1.2
}
```

**Comment by Serbiaguy96** [comment]
Fonts should be imported before creating of pdf.

```javascript
import PdfMake from "pdfmake/build/pdfmake";
import PdfFonts from "pdfmake/build/vfs_fonts";

PdfMake.vfs = PdfFonts.pdfMake.vfs;
PdfMake.createPdf(pdfContent);
```

**Comment by dennisideaonce** [comment]
Although I am too late to this thread, please try:

```
pdfMake.createPdf({
      content: html,
      defaultStyle: {
          font: Object.keys(win.pdfMake.fonts)[0], // Any already loaded font
      },  
```

**Comment by vresetnikov** [comment]
> defaultStyle: {
>     font: "Helvetica",
> }

This will not work, not at least in Typescript as the class constructor requires at least 1 argument.

**Comment by PanArnaud** [comment]
Adding the default style, as mentionned by @vilmes21 resolves the issue for me

**Comment by Jendorski** [comment]
> Since a few standard fonts are available already, and if you don't need Roboto, you can also resolve this issue by using another font. In docDefinition obj, set:
> 
> ```
> defaultStyle: {
>     font: "Helvetica",
> }
> ```

I have added the `defaultStyle`, still throwing the same error.

I use `^0.2.7` and `"@types/pdfmake": "^0.2.2",`

**Comment by UKanishka** [comment]
```
const fonts = {
    'Roboto': {
        normal: path.join(__dirname, '..', '<your-dir>', '/fonts/Roboto-Regular.ttf'),
        bold: path.join(__dirname, '..', '<your-dir>', '/fonts/Roboto-Medium.ttf'),
        italics: path.join(__dirname, '..', '<your-dir>', '/fonts/Roboto-Italic.ttf'),
        bolditalics: path.join(__dirname, '..', '<your-dir>', '/fonts/Roboto-Italic.ttf'),
    },
}
```

This worked for me.

**Comment by alpborcek** [comment]
Sorry for waking up this past topic but I can not solve this. I am trying to build a pdfreport with pdfmake using firestore cloudfunctions but I could not solve this issue. I am using javascript and what ever I tried did not help. Can you please help me.

**Comment by Sithum-CTS** [comment]
Found an answer for this issue. 

just pass your fonts to the CreatePDF function when you call it. setting the global fonts might not work as expected. so here is what I have done. 

My font is "iskpota", you can use what ever the font you are using.

 pdfMake.fonts = {
      iskpota: {
        normal: 'Iskpota-Regular.ttf',
        bold: 'Iskpota-Bold.ttf',
        italics: 'Iskpota-Regular.ttf',
        bolditalics: 'Iskpota-Regular.ttf'
      }
    }

 var docDefinition = {
      defaultStyle: {
        font: 'iskpota'
      },
   contains : {......}
}

pdfMake.createPdf(docDefinition, null, pdfMake.fonts)
