### ISSUE TITLE
Infinite loop

### ISSUE THREAD

**Issue by quoininc-huudatran** [bpampuch/pdfmake#1819]
Hi,

I've tried the following DD on the playground, and it's not working either. On my laptop, it runs into an infinite loop somewhere in the library, so it's very difficult for me to know where to start the debugging.

[20190927-pdfmake-infinite-loop.txt](https://github.com/bpampuch/pdfmake/files/3663108/20190927-pdfmake-infinite-loop.txt)

I've removed all definition of fonts (so not related to #1751) and images (had same issue with interlaced PNG) from my original docDefinition for this to be smaller, but it still doesn't work. 

Any ideas how I can find where the issue is?

Thanks,

**Comment by liborm85** [comment]
I used your docDefinition, and PDF was render correctly:
[issue-1819.pdf](https://github.com/bpampuch/pdfmake/files/3665397/issue-1819.pdf)

I don't know how to reproduce.

**Comment by quoininc-huudatran** [comment]
Do you use the [playground](http://pdfmake.org/playground.html) to do that? I pasted the following, and it still hasn't generated after 5min.

I added the images to the document: 
[pdfmake-infinite-loop-20191001210426575.txt](https://github.com/bpampuch/pdfmake/files/3678532/pdfmake-infinite-loop-20191001210426575.txt)

Can you let me know if you successfully generate this one? On playground or on computer?

**Comment by liborm85** [comment]
Second example tested in node on computer, and works correctly:
[issue-1819-2.pdf](https://github.com/bpampuch/pdfmake/files/3686885/issue-1819-2.pdf)

**Comment by liborm85** [comment]
And tested both in script in browser (Chrome) and also correctly.

**Comment by quoininc-huudatran** [comment]
This really puzzles me. What version of node are you using? I'm using 8.12.0 on my local (MacOS  10.14.6).

And also it doesn't work for my on the browser playground with Google Chrome is version 77.0.3865.90 (Official Build) (64-bit).

<img width="1282" alt="20191003-playground" src="https://user-images.githubusercontent.com/52758369/66150519-5a7d2a80-e5e3-11e9-8d2b-46e375c321d3.png">

Do I need to click on something once I pasted the code in?

**Comment by liborm85** [comment]
I used Node 10.
In playground it not works, because is not ready for that big `dd` definition and is not defined Courier and Helvetica font. Can be tested in plain JS and HTML, works correctly.

**Comment by quoininc-huudatran** [comment]
Ok, then I'll stop reporting issues until I have time to move to a newer version of node. It's pretty involved so I can't do that overnight. Thanks.

**Comment by quoininc-huudatran** [comment]
Would it make sense for you to update `package.json` to indicate engine v10+. Thanks.

**Comment by liborm85** [comment]
Not related with Node version, works in Node 8 also.
