### ISSUE TITLE
Individual styling issues

### ISSUE THREAD

**Issue by Wabbala** [bpampuch/pdfmake#182]
I think the italics option is broken. Could you verify? (Check the last paragraph)

![image](https://cloud.githubusercontent.com/assets/10757863/5958624/d0a4cfde-a7c6-11e4-91e0-dd00026f1856.png)

**Comment by Wabbala** [comment]
To me it loks like that individual styling is not working properly. When a bold font is set it is used through the rest of the document ...

![image](https://cloud.githubusercontent.com/assets/10757863/5960454/c0d983d8-a7d5-11e4-96bb-8b562a9233a5.png)

**Comment by SteffiPeTaffy** [comment]
Duplicate of #162

**Comment by Wabbala** [comment]
@SteffiPeTaffy, Thank you!
