### ISSUE TITLE
Not support Japanese language

### ISSUE THREAD

**Issue by realvino** [bpampuch/pdfmake#1821]
Hello !

PDF maker does not support Japanese language, I have tested on the site (**http://pdfmake.org/playground.html**) that's also not working. Please let me know, is there anything i need to add in pdfContent object or modify the configuration of docDefinition. 

![Annotation (3)](https://user-images.githubusercontent.com/16932278/65874122-a2f9d580-e3a2-11e9-8b14-d6765361381b.png)

Thanks in advance !

**Comment by liborm85** [comment]
pdfmake support all unicode languages. But is required font with support with this special characters.
See how to use custom fonts: [documentation](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/).

**Comment by realvino** [comment]
Thanks for your response. I will check on that.
