### ISSUE TITLE
How can i take base64 string and save it to variable?

### ISSUE THREAD

**Issue by SStasL** [bpampuch/pdfmake#1824]
How can i take base64 string and save it to variable?
like this...
```javascript
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
        var b64; //in this variable must be data in base64 string format
	return b64;
});
```

_Originally posted by @SStasL in https://github.com/bpampuch/pdfmake/issues/1464#issuecomment-535423652_

**Comment by xalunda** [comment]
Hi there,

Simply declare your variable outside of the scope, assign it, and your good to go

```js
let b64;
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
  b64 = data
});
```

Keep in mind that `getBase64` returns a Promise. Make sure to execute relevant code when the promise is resolved.

**Comment by SStasL** [comment]
```javascript
let b64;
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getBase64((data) => {
  b64 = data
});
console.log(b64);
```
In this case i have undefined in console.log()
What i do wrong?
What should i do to get only string?

**Comment by xalunda** [comment]
Are you familiar with the concept of Promises?
Could you make a codepen with your code so I can see the whole thing?

**Comment by SStasL** [comment]
Unfortunately, at this time I am not familiar with the Promises concept.
https://codepen.io/SStasL/pen/rNNOeyj

**Comment by xalunda** [comment]
I checked your code:

I don't see where `createReport` is called, but I presume this would be the last function called in your lifecycle.

I would recommend this:
* Create a new function, like `function usePdf(base64Data)` or so
* Code whatever you need to do with your `base64Data` in there
* `getBase64` argument is actually a callback, use it like this:
```js
pdfDocGenerator.getBase64(usePdf);
```

Hope this helps

**Comment by SStasL** [comment]
I'm called `createReport` function from html.
Ok. I try the following example

```javascript
function usePdf(base64Data) {
    console.log(base64Data);
}
pdfDocGenerator.getBase64(usePdf);
```
But i have nothing in console output! :(

If i am right following code are equal previously code

```javascript
pdfDocGenerator.getBase64((base64Data) => {
    console.log(base64Data);
});
```

**Comment by xalunda** [comment]
Yes this is the same
I might be wrong about the callback, try this then
```js
pdfDocGenerator.getBase64((base64Data) => {
   usePdf(base64Data);
});
```

**Comment by SStasL** [comment]
I have same result.
Nothing in console output!

**Comment by liborm85** [comment]
You can use Promise and await, see https://alligator.io/js/async-functions/ or https://dev.to/afifsohaiii/dealing-with-promises-in-an-array-with-async-await-5d7g

**Comment by SStasL** [comment]
This code gave me a successful result
```javascript
let pdfDocGenerator = pdfMake.createPdf(docInfo);
let promiseObject = pdfDocGenerator.getBase64((base64Data) => {
 });
 promiseObject.then(function(result) {
    console.log(result);    //in this console log i have base 64 string
 });
```
Thanks for your help!
