### ISSUE TITLE
Allow setting of lineHeight for entire document so you don't have to set lineHeight for every piece of text.

### ISSUE THREAD

**Issue by MattyKirchh** [bpampuch/pdfmake#1825]
Just a small quality of life feature request.
Example:
`var dd={
    lineHeight: 2.0,
    content: [ ... ],
    styles: { ... }
}`

**Comment by rabraha3** [comment]
This should be covered in the `defaultStyles` property:
```
var dd = {
  content: [...],
  ...,
  defaultStyles: {
    ...,
    lineHeight: 2
  }
};
```

**Comment by MattyKirchh** [comment]
Indeed it is. Thank you.
