### ISSUE TITLE
Can't position SVG images vertically.

### ISSUE THREAD

**Issue by pandersen-uncharted** [bpampuch/pdfmake#1828]
If I have
```javascript
    var svg = `
      <svg height="100" width="100" xmlns="http://www.w3.org/2000/svg">
      <rect height="100" width="100" x="0" y="0" fill="red"></rect>
      <text x="0" y="50">Lorem ipsum</text>
    </svg>
`;
   var docDefinition = {
        pageSize: 'LETTER',
        pageOrientation: 'landscape',
        content: [
            {
                svg: svg,
                x: 200,
                y: 200      // <-- This appears to be ignored.
                , options: {
                    useCSS: false,
                    assumePt: false,
                }
            }
        ]
   };
   const pdfDocGenerator = pdfMake.createPdf(docDefinition);
   pdfDocGenerator.download();
```
The x position of 200 is used but the y position is ignored. 

The problem appears to be in addSVG() in src/ElementWriter.js which has:

```javascript
		if (image._x === undefined) {
			image._x = image.x || 0;
		}

		image.x = context.x + image._x;
		image.y = context.y;
```
Why is image.y thrown away (i.e. replaced by context.y)? Is this a coding error or am I completely misunderstanding how to position an SVG in a document?

**Comment by rabraha3** [comment]
I can't answer your question regarding the `x` and `y` style flags. I've always used either the `margin`, `relativePosition`, or `absolutePosition` style flags. The two 'position' flags allow you to specify the x and y coordinates. They work similar to the CSS versions.

```javascript
   ..., content: [
            {
                svg: svg,
                relativePosition: { x: 200, y: 200 }
            },
           {
                svg: svg,
               absolutePosition: { x: 200, y: 200 }
            }
        ]
```
I think for your example, the `relativePosition` property is appropriate. In addition, the `x` and `y` properties are not listed in the style context properties:

https://github.com/bpampuch/pdfmake/blob/98a2dac7eb808b42f6ab9c8c8669902c59f7b8c7/src/StyleContextStack.js#L82-L107
