### ISSUE TITLE
What limitation am I hitting?

### ISSUE THREAD

**Issue by cyrixmorten** [bpampuch/pdfmake#1830]
Working on generating a somewhat large pdf, have uploaded the definition as a fiddle here: https://jsfiddle.net/cyrixmorten/r26kcnzf/

Adding the definition to the playground will show a blank pdf.

If I remove any random one of the stack entries in the definition, the pdf will get generated and shown in the preview.

This leaves me wondering what limitation I am hitting, are there a limit on amount of pages, time to render, memory consumption?

Not seeing any errors or getting a warning indicating why there are no preview shown.

Looks like it may be related to the size of the definition object, cutting the amount of images in half (1 instead of 2 per row) allows more pages to be rendered: https://jsfiddle.net/cyrixmorten/kvbdwx7L/

**Comment by rabraha3** [comment]
There are probably two things going on here. 
1. We need to set a larger page size. It seems the standard page size is too small, and the table is unable to wrap. I've seen that when something is too tall to render on a page, it simply disappears. In my local pdfmake playground, I set in the document definition: `var dd = { "pageSize: [1500, 1500], ... };`. I tried different page heights/widths and standard page sizes (e.g., "A2"). And the PDF was (barely) able to render.
2. There may be some network troubles; I was unable to get the PDF to render on the JSFiddles you posted, nor on the pdfmake playground at [http://pdfmake.org/playground.html](http://pdfmake.org/playground.html). Finally, there were a few times I had to inspect the response from my local pdfmake playground, and drop the response body (base64 encoded PDF) into a decoder. The downloaded, decoded PDF rendered.

Your document definition is 4.9 MB in size, the returned PDF is 1.6MB.
[application.pdf](https://github.com/bpampuch/pdfmake/files/3752106/application.pdf)

**Comment by cyrixmorten** [comment]
Thank you for taking time to look at it @rabraha3 

First off sorry for perhaps not having been clear enough, the fiddles contain definition JSON only, no logic to perform rendering. I was relying on the playground as well.

I doubt the issue is related to available space on the page as each entry is roughly the same height, and it does not matter which stack I remove for the playground to be able to render the preview. At some point I had the same suspicion so I removed the 'unbreakable' part of the stacks to rule that out.

It does sound promising that you were able to retrieve the pdf from the network response, honestly did not think of that. Makes me more confident that it will work if I move forward and do the pdf generation on my server.

**Comment by cyrixmorten** [comment]
Moved on generating the pdf on my machine locally and it works as expected 👍
