### ISSUE TITLE
Low image resolution

### ISSUE THREAD

**Issue by abtx** [bpampuch/pdfmake#1831]
Hi. I've looked up other GH issues addressing this, but the solutions proposed don't work. I've got an image generated by Highcharts exporting server with PhantomJS. If I render the chart on a page and download it using exporting.js I'm getting a nice an crisp image. I'm using same setting for PDF make, but passing a base64 string for the image, and it always renders blurry on the PDF. Any ideas how I can get this fixed?

**Comment by liborm85** [comment]
Attach example for reproduce issue.
