### ISSUE TITLE
gulp buildWithStandardFonts fails with error

### ISSUE THREAD

**Issue by hepaestus** [bpampuch/pdfmake#1833]
Not a gulp guy. How should I proceed? 

pdfmake (master) $ gulp buildWithStandardFonts
[10:13:59] Using gulpfile ~/git/offerLetterJhipster/offer-letter/node_modules/pdfmake/gulpfile.js
/usr/lib/nodejs/gulp/bin/gulp.js:132
    gulpInst.start.apply(gulpInst, toRun);
                   ^

TypeError: Cannot read property 'apply' of undefined
    at /usr/lib/nodejs/gulp/bin/gulp.js:132:20
    at process._tickCallback (internal/process/next_tick.js:61:11)

**Comment by liborm85** [comment]
Probably need to install this: [article](https://stackoverflow.com/questions/43000660/cannot-gulp-install-results-in-cannot-read-property-apply-of-undefined/55255878#55255878)
