### ISSUE TITLE
get error for DataUrl "Failed to load resource: net::ERR_INVALID_URL"

### ISSUE THREAD

**Issue by csps** [bpampuch/pdfmake#1835]
Hi, I get the error when I use the dataurl generated by getDataUrl.
The ts code is:
`
const dd = {
    content: content
};
pdfMake.createPdf(dd).getDataUrl( x=>{
     this.reportUrl = this.sanitizer.bypassSecurityTrustResourceUrl(x) as string;
}); `
The html is: 
`<object class="h-100 w-100" type="application/pdf" [data]="reportUrl"></object>`
Here is the content I generate. 
[pdf-content (38).txt](https://github.com/bpampuch/pdfmake/files/3792523/pdf-content.38.txt)
By the way I also tried in  http://pdfmake.org/playground.html. It doesn't work.
Could you anyone help have a look? Thanks.

The angular: 
"@angular/core": "^6.1.10",
"pdfmake": "0.1.57"

**Comment by liborm85** [comment]
What error text is throwed?

Tested your docDefinition on [playground](http://pdfmake.org/playground.html) with download/open/print and works correctly.

**Comment by csps** [comment]
Hi @liborm85 , thanks for your reply. There is an error when embeding the dataurl into <object class="h-100 w-100" type="application/pdf" [data]="reportUrl"></object>
The error is Failed to load resource: net::ERR_INVALID_URL

I also found that using download/open/print in playground. But it can't preview immediately in rhe right side either.

![image](https://user-images.githubusercontent.com/56900325/68101425-881e0200-ff08-11e9-9ed6-90342e80218b.png)

**Comment by liborm85** [comment]
Then your browser does not support this pdf data uri. What is your browser?

**Comment by csps** [comment]
It's chrome.   Version 72.0.3626.121

Libor M. <notifications@github.com> 于2019年11月4日周一 下午3:05写道：

**Comment by liborm85** [comment]
You probably have it disabled in chrome browser. It is out of pdfmake scope.
