### ISSUE TITLE
"Download" function doesn't work in IE11 after PDFmake v0.1.56.

### ISSUE THREAD

**Issue by Angelhost** [bpampuch/pdfmake#1837]
Internet Explorer 11.805.17763.0

Version v0.1.56 and lower works OK, later - not. (Edge and Chrome - works OK.)

My code:
window.pdfMake.createPdf(JSON.parse(docDefinition)).download('123.pdf');

Error:
![2019-10-31_1116_001](https://user-images.githubusercontent.com/6372230/68062937-b0b8b880-fcca-11e9-938a-b0285ee7cf1b.png)
![2019-10-31_1116](https://user-images.githubusercontent.com/6372230/68062938-b1e9e580-fcca-11e9-923c-e3f8e6a5d4de.png)
![2019-10-31_1117](https://user-images.githubusercontent.com/6372230/68062940-b3b3a900-fcca-11e9-8329-d3a32f455f3c.png)

**Comment by liborm85** [comment]
Download action tested on IE 11 on [playground](http://pdfmake.org/playground.html) and works correctly

**Comment by Diffendbecker** [comment]
> Download action tested on IE 11 on [playground](http://pdfmake.org/playground.html) and works correctly

Yes. In playground it is working. In our project was client library, version 59 and IE 11 didn’t work. I’ve tried to increase it to latest 61 - no result, then I’ve decreased it to 56 and IE 11 started to work.

**Comment by liborm85** [comment]
Create example on [jsfiddle](https://jsfiddle.net/) for reproduce issue.

**Comment by Angelhost** [comment]
> Create example on [jsfiddle](https://jsfiddle.net/) for reproduce issue.

JS Fiddle is no longer supporting IE.

**Comment by liborm85** [comment]
Then some similar service. Because I don't know how to simulate this issue.
