### ISSUE TITLE
Shadow, text Underline and text Opacity Issue when Export Fabric Canvas as PDF.

### ISSUE THREAD

**Issue by sagarvibrant** [bpampuch/pdfmake#1838]
I am using fabric js and Shadow, text Underline and text Opacity Not display in generated pdf file.

**Comment by liborm85** [comment]
Add example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html)  or [jsfiddle](https://jsfiddle.net/).

**Comment by sagarvibrant** [comment]
https://jsfiddle.net/50atsvyp/3/

**Comment by liborm85** [comment]
pdfmake uses for transformation from svg [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit) library, you can create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).

**Comment by blikblum** [comment]
> https://jsfiddle.net/50atsvyp/3/

Getting Uncaught TypeError: Cannot read property 'encode' of null

So i cannot look at it
