### ISSUE TITLE
Composer TransportException

### ISSUE THREAD

**Issue by p2made** [bpampuch/pdfmake#1839]
In migrating a few dependancies in Yii2 project from bower to npm, I started getting this error from Composer...

```
  [Composer\Downloader\TransportException]                                                                                                                                                    
  The "https://asset-packagist.org/p/npm-asset/merge-source-map/7ef2b7a41a2389a9dcc5ce98a86cecdbcea1b5eb508e22a47d8d6129b59d7d7c.json" file could not be downloaded (HTTP/1.1 404 Not Found)  
```

Going through all of my dependancies one by one, `"npm-asset/pdfmake": "~0.1"` proves to be the only one that produces the error.

Fortunately I can continue to use `"bower-asset/pdfmake": "~0.1"`, however I would like to be able to migrate it to use npm.

**Comment by liborm85** [comment]
If you want use npm package, is available here: https://www.npmjs.com/package/pdfmake

If you want use composer via packagist package, is available here: https://packagist.org/packages/bpampuch/pdfmake
