### ISSUE TITLE
How know if it is the last row?

### ISSUE THREAD

**Issue by loxy** [bpampuch/pdfmake#1841]
Is there a possibility to check if it is the last row on tables?  For all the layout functions, like hLineWidth, paddingLeft ...

**Comment by liborm85** [comment]
like this:

```
hLineWidth: function (i, node) {
    if (i === node.table.body.length) { // last
        return 5;
    }
				    
    return 1;
},
```

See [playground](http://pdfmake.org/playground.html) > tab _TABLES_

**Comment by loxy** [comment]
Ok. Thank you!
