### ISSUE TITLE
SVG draw in document error

### ISSUE THREAD

**Issue by zezo93** [bpampuch/pdfmake#1842]
i tried to add svg of chart but i got this error :

```
TypeError: Cannot read property 0 of null
   at SvgElemPath.SvgElemBasicShape.drawInDocument (source.js:1791)
    at SvgElemGroup.SvgElemHasChildren.drawChildren (source.js:1386)
    at SvgElemGroup.SvgElemContainer.drawContent (source.js:1403)
    at SvgElemGroup.drawInDocument (source.js:1462)
    at SvgElemGroup.SvgElemHasChildren.drawChildren (source.js:1386)
    at SvgElemGroup.SvgElemContainer.drawContent (source.js:1403)
    at SvgElemGroup.drawInDocument (source.js:1462)
    at SvgElemSvg.SvgElemHasChildren.drawChildren (source.js:1386)
    at SvgElemSvg.SvgElemContainer.drawContent (source.js:1403)
    at SvgElemSvg.drawInDocument (source.js:1518)
```
my svg was one line and single qouted, and i generated other chart svgs and worked fine, but sometimes the generated svg couldn't be read by pdfmake,
here is my svg :
```<svg xmlns:xlink="http://www.w3.org/1999/xlink" version="1.1" class="highcharts-root" style="font-family:&quot;Lucida Grande&quot;, &quot;Lucida Sans Unicode&quot;, Arial, Helvetica, sans-serif;font-size:12px;" xmlns="http://www.w3.org/2000/svg" width="620" height="160" viewBox="0 0 620 160"><desc>Created with Highcharts 7.1.3</desc><defs><clipPath id="highcharts-pnyaumr-71-"><rect x="0" y="0" width="408" height="92" fill="none"></rect></clipPath></defs><rect fill="#ffffff" class="highcharts-background" x="0" y="0" width="620" height="160" rx="0" ry="0"></rect><rect fill="none" class="highcharts-plot-background" x="44" y="30" width="408" height="92"></rect><g class="highcharts-grid highcharts-xaxis-grid" data-z-index="1"><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 47.5 30 L 47.5 122" opacity="1"></path><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 247.5 30 L 247.5 122" opacity="1"></path><path fill="none" data-z-index="1" class="highcharts-grid-line" d="M 447.5 30 L 447.5 122" opacity="1"></path></g><g class="highcharts-grid highcharts-yaxis-grid" data-z-index="1"><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 122.5 L 452 122.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 109.5 L 452 109.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 96.5 L 452 96.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 83.5 L 452 83.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 69.5 L 452 69.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 56.5 L 452 56.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 43.5 L 452 43.5" opacity="1"></path><path fill="none" stroke="#e6e6e6" stroke-width="1" data-z-index="1" class="highcharts-grid-line" d="M 44 29.5 L 452 29.5" opacity="1"></path></g><rect fill="none" class="highcharts-plot-border" data-z-index="1" x="44" y="30" width="408" height="92"></rect><g class="highcharts-axis highcharts-xaxis" data-z-index="2"><path fill="none" class="highcharts-tick" stroke="#ccd6eb" stroke-width="1" d="M 47.5 122 L 47.5 132" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#ccd6eb" stroke-width="1" d="M 247.5 122 L 247.5 132" opacity="1"></path><path fill="none" class="highcharts-tick" stroke="#ccd6eb" stroke-width="1" d="M 447.5 122 L 447.5 132" opacity="1"></path><path fill="none" class="highcharts-axis-line" stroke="#ccd6eb" stroke-width="1" data-z-index="7" d="M 44 122.5 L 452 122.5"></path></g><g class="highcharts-axis highcharts-yaxis" data-z-index="2"><path fill="none" class="highcharts-axis-line" data-z-index="7" d="M 44 30 L 44 122"></path></g><g class="highcharts-series-group" data-z-index="3"><g data-z-index="0.1" class="highcharts-series highcharts-series-0 highcharts-line-series " transform="translate(44,30) scale(1 1)" clip-path="url(#highcharts-pnyaumr-71-)"><path fill="none" d="M 3.9999999999964 92 L 204 92 L 404 87.88190674900216" class="highcharts-graph" data-z-index="1" stroke="#ff9800" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path></g><g data-z-index="0.1" class="highcharts-markers highcharts-series-0 highcharts-line-series " transform="translate(44,30) scale(1 1)" clip-path="none"><path fill="#ff9800" d="M 3.0000000000000004 96 A 4 4 0 1 1 3.003999999333336 95.99999800000016 Z" stroke="#ff9800" stroke-width="1" opacity="1" class="highcharts-point"></path><path fill="#ff9800" d="M 204 96 A 4 4 0 1 1 204.00399999933333 95.99999800000016 Z" stroke="#ff9800" stroke-width="1" opacity="1" class="highcharts-point"></path><path fill="#ff9800" d="M 404 92 A 4 4 0 1 1 404.00399999933336 91.99999800000016 Z" stroke="#ff9800" stroke-width="1" opacity="1" class="highcharts-point"></path></g><g data-z-index="0.1" class="highcharts-series highcharts-series-1 highcharts-line-series highcharts-color-0 " transform="translate(44,30) scale(1 1)" clip-path="url(#highcharts-pnyaumr-71-)"><path fill="none" d="M 404 16.29593159204812" class="highcharts-graph" data-z-index="1" stroke="#2C313F" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path></g><g data-z-index="0.1" class="highcharts-markers highcharts-series-1 highcharts-line-series highcharts-color-0 " transform="translate(44,30) scale(1 1)" clip-path="none"><path fill="#FFFFFF" d="M 404 20 A 4 4 0 1 1 404.00399999933336 19.99999800000017 Z" stroke="#2C313F" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-0"></path></g><g data-z-index="0.1" class="highcharts-series highcharts-series-2 highcharts-line-series highcharts-color-1 " transform="translate(44,30) scale(1 1)" clip-path="url(#highcharts-pnyaumr-71-)"><path fill="none" d="M 404 91.93066774945555" class="highcharts-graph" data-z-index="1" stroke="#6F7B8B" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path></g><g data-z-index="0.1" class="highcharts-markers highcharts-series-2 highcharts-line-series highcharts-color-1 " transform="translate(44,30) scale(1 1)" clip-path="none"><path fill="#FFFFFF" d="M 404 96 A 4 4 0 1 1 404.00399999933336 95.99999800000016 Z" stroke="#6F7B8B" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-1"></path></g><g data-z-index="0.1" class="highcharts-series highcharts-series-3 highcharts-line-series highcharts-color-2 " transform="translate(44,30) scale(1 1)" clip-path="url(#highcharts-pnyaumr-71-)"><path fill="none" d="M 404 70.53380439707017" class="highcharts-graph" data-z-index="1" stroke="#c7c9d6" stroke-width="2" stroke-linejoin="round" stroke-linecap="round"></path></g><g data-z-index="0.1" class="highcharts-markers highcharts-series-3 highcharts-line-series highcharts-color-2 " transform="translate(44,30) scale(1 1)" clip-path="none"><path fill="#FFFFFF" d="M 404 75 A 4 4 0 1 1 404.00399999933336 74.99999800000016 Z" stroke="#c7c9d6" stroke-width="1" opacity="1" class="highcharts-point highcharts-color-2"></path></g></g><text x="310" text-anchor="middle" class="highcharts-title" data-z-index="4" style="color:#333333;font-size:18px;display:none;fill:#333333;" y="24"></text><text x="310" text-anchor="middle" class="highcharts-subtitle" data-z-index="4" style="color:#666666;display:none;fill:#666666;" y="24"></text><g data-z-index="6" class="highcharts-data-labels highcharts-series-0 highcharts-line-series " transform="translate(44,30) scale(1 1)"><g class="highcharts-label highcharts-data-label highcharts-data-label-color-undefined" data-z-index="1" transform="translate(-18,67)"><text x="5" data-z-index="1" style="font-size:11px;font-weight:bold;color:#ff9800;fill:#ff9800;" y="16"><tspan>0.0 GJ</tspan></text></g><g class="highcharts-label highcharts-data-label highcharts-data-label-color-undefined" data-z-index="1" transform="translate(182,67)"><text x="5" data-z-index="1" style="font-size:11px;font-weight:bold;color:#ff9800;fill:#ff9800;" y="16"><tspan>0.0 GJ</tspan></text></g><g class="highcharts-label highcharts-data-label highcharts-data-label-color-undefined" data-z-index="1" transform="translate(382,63)"><text x="5" data-z-index="1" style="font-size:11px;font-weight:bold;color:#ff9800;fill:#ff9800;" y="16"><tspan>6.3 GJ</tspan></text></g></g><g class="highcharts-legend" data-z-index="7" transform="translate(464,52)"><rect fill="none" class="highcharts-legend-box" rx="0" ry="0" x="0" y="0" width="146" height="51" visibility="visible"></rect><g data-z-index="1"><g><g class="highcharts-legend-item highcharts-line-series highcharts-color-undefined highcharts-series-0" data-z-index="1" transform="translate(8,3)"><path fill="none" d="M 0 8 L 16 8" class="highcharts-graph" stroke="#ff9800" stroke-width="2"></path><path fill="#ff9800" d="M 8 12 A 4 4 0 1 1 8.003999999333336 11.999998000000167 Z" class="highcharts-point" stroke="#ff9800" stroke-width="1" opacity="1"></path><text x="21" style="color:#333333;cursor:pointer;font-size:8px;font-weight:normal;fill:#333333;" text-anchor="start" data-z-index="2" y="11"><tspan>Total Energy Consumption</tspan></text></g><g class="highcharts-legend-item highcharts-line-series highcharts-color-0 highcharts-series-1" data-z-index="1" transform="translate(8,13)"><path fill="none" d="M 0 8 L 16 8" class="highcharts-graph" stroke="#2C313F" stroke-width="2"></path><path fill="#2C313F" d="M 8 12 A 4 4 0 1 1 8.003999999333336 11.999998000000167 Z" class="highcharts-point" stroke="#2C313F" stroke-width="1" opacity="1"></path><text x="21" y="11" style="color:#333333;cursor:pointer;font-size:8px;font-weight:normal;fill:#333333;" text-anchor="start" data-z-index="2"><tspan>Diesel</tspan></text></g><g class="highcharts-legend-item highcharts-line-series highcharts-color-1 highcharts-series-2" data-z-index="1" transform="translate(8,23)"><path fill="none" d="M 0 8 L 16 8" class="highcharts-graph" stroke="#6F7B8B" stroke-width="2"></path><path fill="#6F7B8B" d="M 8 12 A 4 4 0 1 1 8.003999999333336 11.999998000000167 Z" class="highcharts-point" stroke="#6F7B8B" stroke-width="1" opacity="1"></path><text x="21" y="11" style="color:#333333;cursor:pointer;font-size:8px;font-weight:normal;fill:#333333;" text-anchor="start" data-z-index="2"><tspan>Natural gas</tspan></text></g><g class="highcharts-legend-item highcharts-line-series highcharts-color-2 highcharts-series-3" data-z-index="1" transform="translate(8,33)"><path fill="none" d="M 0 8 L 16 8" class="highcharts-graph" stroke="#c7c9d6" stroke-width="2"></path><path fill="#c7c9d6" d="M 8 12 A 4 4 0 1 1 8.003999999333336 11.999998000000167 Z" class="highcharts-point" stroke="#c7c9d6" stroke-width="1" opacity="1"></path><text x="21" y="11" style="color:#333333;cursor:pointer;font-size:8px;font-weight:normal;fill:#333333;" text-anchor="start" data-z-index="2"><tspan>Fuel oil</tspan></text></g></g></g></g><g class="highcharts-axis-labels highcharts-xaxis-labels" data-z-index="7"><text x="47.999999999996" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="141" opacity="1">2017</text><text x="248" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="141" opacity="1">2018</text><text x="448" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="middle" transform="translate(0,0)" y="141" opacity="1">2019</text></g><g class="highcharts-axis-labels highcharts-yaxis-labels" data-z-index="7"><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="126" opacity="1">0</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="112" opacity="1">20</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="99" opacity="1">40</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="86" opacity="1">60</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="73" opacity="1">80</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="60" opacity="1">100</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="47" opacity="1">120</text><text x="29" style="color:#666666;cursor:default;font-size:11px;fill:#666666;" text-anchor="end" transform="translate(0,0)" y="34" opacity="1">140</text></g></svg>```

**Comment by liborm85** [comment]
pdfmake uses for transformation from svg [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit) library, you can create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).

**Comment by liborm85** [comment]
(related with: https://github.com/alafr/SVG-to-PDFKit/issues/107)
