### ISSUE TITLE
Rotated Text using Canvas is not working in Header/Footer

### ISSUE THREAD

**Issue by Rupali-Mehta** [bpampuch/pdfmake#1845]
I have to show vertically placed text in my header/footer. When i am only using the canvas image in header/footer it works fine. However, on adding any additional text the vertically placed text disappears. Please suggest how to achieve the same.

```js
writeRotatedText = function(text) {
  var ctx, canvas = document.createElement('canvas');
  canvas.width = 15;
  canvas.height = 800;
  ctx = canvas.getContext('2d');
  ctx.font = '8pt Akkurat Pro';
  ctx.save();
  ctx.textAlign = 'left';
  ctx.translate(15,800);
  ctx.rotate(-0.5*Math.PI);
  ctx.fillStyle = '#e8eae';
  ctx.fillText(text , 0, 0);
  ctx.restore();
  return canvas.toDataURL();
};

var dd = {
                 header: function(){
		  return[
		   // {text: 'Sample Header Text', fontSize: 11.5 }, 
		    { image: writeRotatedText('Licensed to abc@spglobal.com'), alignment: 'left',margin:[5,0,24,0]},
		
		]
	},
      footer: function(currentPage, pageCount) { 
       return [{
           
      stack: [{
        canvas: [{
          type: 'line',
          x1: 48,
          y1: 0,
          x2: 560,
          y2: 0,
          lineWidth: 1.5,
          color:'#000000',
          margin:[48,0,48,24]
        
        }]
      },
       
      {      
        text: [ 
                {text:'© '+(new Date().getFullYear()).toString()+', Powered by ABC | Page ' + currentPage.toString() +'\n', fontSize:8, alignment:'center',fontStyle:'Akkurat Pro',color:'#e8eae'}],

        margin: [48,0,48,0]
      }
      ]
    }];
  },

	content: [
	    
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
]
} 
```

**Comment by liborm85** [comment]
canvas image is in pdf rendered:
![pdfscreen](https://user-images.githubusercontent.com/1298652/68278915-a6a00c80-0072-11ea-9ee0-312c97284042.PNG)

Where is the problem?

**Comment by Rupali-Mehta** [comment]
Please uncomment the below text in header and re-run the script.

  // {text: 'Sample Header Text', fontSize: 11.5 },

**Comment by liborm85** [comment]
Header content can be only in header area (dimensions are defined by `pageMargins`), not in page content area. Only image, if is as first element, is rendered whole.

If you need render content in page, can be used `background` [(documentation)](https://pdfmake.github.io/docs/document-definition-object/background-layer/). Example:
```js
    background: function(){
		  return[
		    { image: writeRotatedText('Licensed to abc@spglobal.com'), alignment: 'left',margin:[5,0,24,0]},
		
		]        
    },
```

**Comment by Rupali-Mehta** [comment]
Thanks. When i am using a longer text some of it is getting trimmed.
writeRotatedText = function(text) {
  var ctx, canvas = document.createElement('canvas');
  canvas.width = 15;
  canvas.height = 800;
  ctx = canvas.getContext('2d');
  ctx.font = '8pt Akkurat Pro';
  ctx.textBaseline = "bottom";
  ctx.save();
  ctx.textAlign = 'left';
  ctx.translate(15,800);
  ctx.rotate(-0.5*Math.PI);
  ctx.fillStyle = '#e8eae';
  ctx.fillText(text , 0, 0);
  ctx.restore();
  return canvas.toDataURL();
};

var dd = {
    
      background: function(){
		  return[
		    { image: writeRotatedText('Licensed to rupalitalwar@myportal.com'), alignment: 'left',margin:[5,0,24,0]},
		
		]        
    },
![Capture](https://user-images.githubusercontent.com/50446028/68294642-a88bbf00-00b6-11ea-801e-b7ec8e44c8fe.JPG)
