### ISSUE TITLE
Webpack useBuiltIns warning

### ISSUE THREAD

**Issue by deguich** [bpampuch/pdfmake#1846]
With last version of pdfmake 0.1.62, webpack print this warning when compiling: 
```
WARNING: We noticed you're using the `useBuiltIns` option without declaring a core-js version. Currently, we assume version 2.x when no version is passed. Since this default version will likely change in future versions of Babel, we recommend explicitly setting the core-js version you are using via the `corejs` option.
```

I found useBuiltIns option in webpack.config.js.

Not sure but it seems webpack need a core-js module version fixed in the dependencies ...

**Comment by liborm85** [comment]
Fixed... I hope it will be solved in Babel soon...
