### ISSUE TITLE
Hyperlink not adding to PDF

### ISSUE THREAD

**Issue by chris-chalmers** [bpampuch/pdfmake#1847]
First, thank you for developing this wonderful FREE library for making PDFs. I hope you can help with my problem: 
I'm trying to add a link to my PDF using the following code:
```
docDefinition.content.push({ 
	text: "Go to " + button_link,
	link: button_link,
	style: "link",
	alignment: "center",
	margin: [0,0,0,5],
});
```

where the variable "button_link" is "https://www.getcontrol.net/tq-black-belt-certificate/"
What I get in my PDF looks like this:
<img width="712" alt="Screen Shot 2019-11-13 at 9 35 31 AM" src="https://user-images.githubusercontent.com/10425052/68783986-137a5000-05f9-11ea-978d-aea1f8957a25.png">

But when I click on the link it doesn't work. When I click on it in the PDF I get the following:
<img width="712" alt="Screen Shot 2019-11-13 at 9 37 25 AM" src="https://user-images.githubusercontent.com/10425052/68784121-52a8a100-05f9-11ea-872b-6df29146f165.png">

I'm using Chrome on a Mac

**Comment by liborm85** [comment]
Runnable example on [playground](http://pdfmake.org/playground.html):
```
var button_link = "https://www.getcontrol.net/tq-black-belt-certificate/";

var dd = {
	content: [
    ]
};

dd.content.push({ 
	text: "Go to " + button_link,
	link: button_link,
	style: "link",
	alignment: "center",
	margin: [0,0,0,5],
});
```

**Comment by liborm85** [comment]
Tested on Chrome on Windows and works ok.
I don't have an Mac.

**Comment by chris-chalmers** [comment]
I think I found the problem. My client was using an outdated version of
jQuery.
