### ISSUE TITLE
add a picture from a local folder when generating pdf

### ISSUE THREAD

**Issue by DmitryMas** [bpampuch/pdfmake#1848]
Hello!
How can I add a picture from a local folder when generating pdf?

**Comment by liborm85** [comment]
See [documentation](https://pdfmake.github.io/docs/document-definition-object/images/).
Quote:
> ```
>     {
>       // under NodeJS (or in case you use virtual file system provided by pdfmake)
>       // you can also pass file names here
>       image: 'myImageDictionary/image1.jpg'
>     }
> ```
