### ISSUE TITLE
Table inside tables do not respect border on multiple pages 

### ISSUE THREAD

**Issue by atomzerolee** [bpampuch/pdfmake#1849]
I have a case with the following structure:

title1 | title2
------------ | -------------
table1 | table2

![image](https://user-images.githubusercontent.com/21033360/68993156-c8d62d80-08af-11ea-9e9c-78b71148c933.png)

On the first page, it works just fine, as you can see from the above image. Once the table span more than one page and we have to repeat the headers of all tables, The borders of the outer table are not applied on the repeated headers:

![image](https://user-images.githubusercontent.com/21033360/68993182-25d1e380-08b0-11ea-9242-5d5ffe5461a6.png)

When I did not set the header for the outer table, it was shown below:

![image](https://user-images.githubusercontent.com/21033360/68993242-bb6d7300-08b0-11ea-9427-514caa4d5309.png)

The problem is similar to [issue#1122](https://github.com/bpampuch/pdfmake/issues/1122)

**Comment by liborm85** [comment]
duplicate with https://github.com/bpampuch/pdfmake/issues/1122
