### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by akshaymagapu** [bpampuch/pdfmake#1851]
![image](https://user-images.githubusercontent.com/13298615/69048242-4d829200-09fd-11ea-8917-b494db8554b4.png)
Build fails.
We are using this library and as we build pdf make in post-install, our project build fails.

**Comment by liborm85** [comment]
Fixed in master and 0.1 branch.

**Comment by akshaymagapu** [comment]
@liborm85 do you know when will be the next release?
