### ISSUE TITLE
Download callback missing

### ISSUE THREAD

**Issue by netAction** [bpampuch/pdfmake#1852]
I am using PDFMake on client side (Chrome) without webpack. Everything works fine except the last step.

The function download() does not call any callback:
https://github.com/bpampuch/pdfmake/blob/master/build/pdfmake.js
Am I using the wrong script file?

**Comment by liborm85** [comment]
Pdfmake you can download from [Github releases page](https://github.com/bpampuch/pdfmake/releases/latest) or cdnjs/npm see [documentation](https://pdfmake.github.io/docs/getting-started/client-side/#library-sources).

**Comment by netAction** [comment]
OK thanks this fixes the issue. Thanks. I did not expect the alpha version in master branch.
