### ISSUE TITLE
Vertical layout

### ISSUE THREAD

**Issue by alasili** [bpampuch/pdfmake#1853]
[http://www.nmmgyw.com/newsMore/78.html](url)
![微信图片_20191119111310](https://user-images.githubusercontent.com/43257060/69113316-a0238300-0abd-11ea-9a0d-4a69426b9fcb.png)
How to create this kind of page change
Mongolian website
What should I do?

**Comment by liborm85** [comment]
Page can be rotated to landscape, see example:
```js
var dd = {
    pageOrientation: 'landscape',
	content: [
		'text'
	]
}
```

and see [documentation](https://pdfmake.github.io/docs/document-definition-object/page/)

**Comment by alasili** [comment]
It's not like that
Mongolian is typesetting from top to bottom, left to right

Just like adding CSS  writing-mode: vertical-lr;

**Comment by liborm85** [comment]
Not supported, feature request is here: https://github.com/bpampuch/pdfmake/issues/324
