### ISSUE TITLE
Issue exporting svg

### ISSUE THREAD

**Issue by pedrocleto** [bpampuch/pdfmake#1854]
Exporting Svg has a problem caused by svg-to-pdfkit lib version in the current one we have 
  if ((lineCap === 'square' || lineCap === 'round') && lineWidth > 0) {
                    let x = subPaths[j].startPoint[0],
                        y = subPaths[j].startPoint[1];

but if we go to the project source code here https://github.com/alafr/SVG-to-PDFKit/blob/master/source.js#L1812 this line is already protected and it doesn't break the document like the version used by pdfmake.

Can we build in the svg-to-pdfkit inside the pdfmake since the npm hasn't been update in 2 years but the source keeps up to date? 

Thank you this lib is amazing if you could solve this it would be great.

**Comment by liborm85** [comment]
No, for official build is used only packages released on npm.
