### ISSUE TITLE
node.js and browser .. different output pdf

### ISSUE THREAD

**Issue by k3341095** [bpampuch/pdfmake#1858]
![image](https://user-images.githubusercontent.com/17330375/69351015-f8c16e80-0cbd-11ea-9e7e-5c040d39c8e4.png)

I use node.js and browser
Have the same font and the same code
I made it .. but I got another pdf like the picture.

Left side output of node.js
On the right is the output of web javascript.

The two heights are wrong
The output of node.js fits well in the middle of the height.
But
The web javascript output has a higher height
The text's alignment is not centered
It is aligned downwards.

Why is this happening and how can I solve it?
The same thing happens if you change to a ttf file with a different font.

**Comment by liborm85** [comment]
Attach runnable examples for reproduce issue in nodejs and browser.

**Comment by liborm85** [comment]
No reaction.
