### ISSUE TITLE
line break in texts

### ISSUE THREAD

**Issue by tvalades** [bpampuch/pdfmake#1859]
Good afternoon, 
I am using pdfmake to create pdf for technical data sheets of woocommerce products with dynamic content. I load the content using PHP and an error appears when the text contains a line break. Is there any option to solve that problem? The texts are in an excel 
sheet

Thanks!

**Comment by liborm85** [comment]
Not related with pdfmake but with javascript knowledges. New lines are created in javascript using `\n`. Be careful not to interpret php as a new line, use `$variable = '\n';`.
