### ISSUE TITLE
Featrure: html content support

### ISSUE THREAD

**Issue by YidingW** [bpampuch/pdfmake#186]
Is it possible to insert html content into the pdf? 

For example: "\<p class="style">some test text\</p>" which will generate a paragraph with specific style.

**Comment by gnibeda** [comment]
you can write simple html parser yourself. traverse all nodes in hierarchy and generate appropriate description objects for pdfmake.

**Comment by YidingW** [comment]
@gnibeda  Thanks for replying. But furthermore I want to generate some HTML Unicode symbol in the pdf. Like a checkbox. http://www.w3schools.com/charsets/ref_utf_misc_symbols.asp 
A simple html parser cannot do that I think.

**Comment by gnibeda** [comment]
I'm not sure for 100%, but pdfmake doesn't support unicode right now(may be via custom fonts?).
We should hear answer from bpampuch, to know it for sure.

**Comment by jthoenes** [comment]
If you want to use unicode with pdfmake, your font has to support this unicode symbol.

Just specify a font which has this symbol, it should be ok. See: https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
