### ISSUE TITLE
Question about ColSpan and inline cell styles?

### ISSUE THREAD

**Issue by GregLarden** [bpampuch/pdfmake#1860]
First let me say this library is AWESOME and Thank you! 

I do have a question regarding setting colspan on a table column.
It works fine when the is formatted like this:
`[{ text: 'COMPANY LOGO, NAME AND CONTACT INFO GO HERE', colSpan: 4, fontSize: 8 }, {}, {}, {}]`

But when I use inline formatting the colspan is ignored but the other settings like FontSize are detected and applied properly. Do I just have colspan in the wrong location?
 Oh this is a nested table as well.

`[[{ text: [{ text: 'Name:', bold: true }, 'Test_FirstName Test_MiddleName Test_LastName'],colSpan: 3 , fontSize: 6, alignment: 'left'}], {}, {}, { text: 'Date: Febuary 22, 2017', fontSize: 6 }]`

**Comment by liborm85** [comment]
Example of how to use inline formatting in table:
```js
var dd = {
  content: [
    {
      table: {
        body: [
          [
            {
              text: [
                'First ',
                { text: 'column', bold: true },
                '.'
              ],
              colSpan: 2 
            },
            '',
            'Column 3'
          ],
          [
            'One value goes here',
            'Another one here',
            'OK?'
          ]
        ]
      }
    }
  ]
}
```

**Comment by GregLarden** [comment]
Thank you so much!!! Works perfect!
