### ISSUE TITLE
moving table or any text from top

### ISSUE THREAD

**Issue by varun-vivek** [bpampuch/pdfmake#1861]
is there any property to move the table or content to move from top, similar to margin-top css for div (which will move div from top)

**Comment by liborm85** [comment]
Can be used `margin`, example:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					[{text: 'Header 1', margin: [10, 20, 30, 40]}, {text: 'Header 2'}, {text: 'Header 3'}],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
				]
			},
		},
	]
}
```

For more info see [documenation](https://pdfmake.github.io/docs/document-definition-object/margins/).
