### ISSUE TITLE
Cannot read property '_calcWidth' of undefined

### ISSUE THREAD

**Issue by davidwebster48** [bpampuch/pdfmake#1863]
I am trying to create a table where the first row has a cell with colSpan=2. I'm using version 0.1.62.

Here is my code...
```
var dd = {
  content: [
    {
      table: {
        body: [
          [
            { text: 'row one label', colSpan: 2 },
            { text: '0' },
          ],
          [
            { text: 'row two' },
            { text: '0' },
            { text: '1' },
          ],
        ],
      }
    },
  ]
}
```

Here is my error...
`TypeError: Cannot read property '_calcWidth' of undefined at layoutBuilder.js:509 `

Am I doing something wrong?

**Comment by liborm85** [comment]
This is correct definition:
```js
var dd = {
  content: [
    {
      table: {
        body: [
          [
            { text: 'row one label', colSpan: 2 },
            '',
            { text: '0' },
          ],
          [
            { text: 'row two' },
            { text: '0' },
            { text: '1' },
          ],
        ],
      }
    },
  ]
}
```

see [playground](http://pdfmake.org/playground.html) > TABLES for more information.

**Comment by erasmuswill** [comment]
Hi @liborm85 , this solves the issue, but why is the blank cell needed? Is there not a way to add these based on `colSpan` from the library's side? I didn't see anything in the docs regarding this.

**Comment by liborm85** [comment]
This behavior cannot be changed because it would BC break. Maybe changed in 0.2 version, issue: https://github.com/bpampuch/pdfmake/issues/1814

**Comment by sandeepjadhav** [comment]
Hi I'm using 0.2.8 , but still not able to handle the error app is getting crashed if I pass invalid table. Tried using try catch but still no use.
