### ISSUE TITLE
"Unexpected svg viewbox format" pdfmake edge

### ISSUE THREAD

**Issue by tedbakers** [bpampuch/pdfmake#1868]
This line in SVGMeasure.js
var viewboxMatches = svgNode.match(/viewBox="(.*)"/);

should  be updated  to

var viewboxMatches = svgNode.match(/viewBox="(.*?)"/);

to avoid this error.

**Comment by liborm85** [comment]
What problem does it solve?

**Comment by tedbakers** [comment]
"Unexpected svg viewbox format" pdfmake  in Edge only. It worked as is in Chrome, Firefox but for some reason Edge decided to take the width="x" and height="x" properties with it in the match so you end up with too many entries for the viewbox generating the above error, updating the regular expression as my example resolved the issue.

**Comment by tedbakers** [comment]
It's worth noting I use svg.js to generate my svg outputs and they are perfectly formed.

**Comment by liborm85** [comment]
You probably using old version. Update pdfmake to latest version.

**Comment by tedbakers** [comment]
This has been changed to  var viewboxMatches = svgNode.match(/viewBox="([0-9\s]*)"/); in the latest version

**Comment by tedbakers** [comment]
will update later and report back if I still have an issue, thanks
