### ISSUE TITLE
The contents of the form are overflowed

### ISSUE THREAD

**Issue by jiahui1522** [bpampuch/pdfmake#1869]
![image](https://user-images.githubusercontent.com/42529020/70294339-17774780-181e-11ea-81b2-679af7a321f9.png)
**When the content has small letters such as l or i repeated multiple times**

![image](https://user-images.githubusercontent.com/42529020/70294419-60c79700-181e-11ea-85c3-cc21bedfa4d6.png)
**When the content does not have a smaller letter like l or i**

When the content contains small letters such as l or i repeated many times, overflow will occur, but other letters will not.

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html) or [jsfiddle.net](https://jsfiddle.net/).
