### ISSUE TITLE
Can you add opacity to text?

### ISSUE THREAD

**Issue by CJStokes** [bpampuch/pdfmake#187]
Hi, I was wondering if it is possible to adjust the opacity of text and/or images. For example, having a watermark on each page in the background layer.

Thanks for the great tool!

**Comment by jthoenes** [comment]
Hi, 

it is possible to set a watermark by using 

    watermark: 'Water mark text'

in you document definition. There is no way to specify the formatting for it at the moment.

**Comment by Procaseycash** [comment]
[info.kdevs@gmail.com Invoice (4523390836670464) (16).pdf](https://github.com/bpampuch/pdfmake/files/544231/info.kdevs.gmail.com.Invoice.4523390836670464.16.pdf)

How can i make the background image transparent?

**Comment by liborm85** [comment]
Implemented in https://github.com/bpampuch/pdfmake/pull/492

**Comment by dina1610** [comment]
How can i make image watermark instead on text.  Can u give small example.
