### ISSUE TITLE
Request: Table border line style "double"

### ISSUE THREAD

**Issue by estani** [bpampuch/pdfmake#1870]
I only found information regarding how to create dash line, afaict it's not possible to create a double line.

This will be great and I presume not very hard to implement (not sure though).
```
hLineStyle: function (i, node) {
 if (i === 0 || i === node.table.body.length) {
  return null;
 }
  return {double: true };
},
```

or much more general and flexible:
```
return { multi: {sizes: [1, 2, 1], spaces: [2, 1]}
```

Something like:
```
-----


=====

-----
```

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/724
