### ISSUE TITLE
Multiple Table

### ISSUE THREAD

**Issue by AaaRUnnN** [bpampuch/pdfmake#1872]
Hi  I want to generate PDF like this below images 
Thanks in Advance

![Table](https://user-images.githubusercontent.com/20571583/70412724-7d143f80-1a7b-11ea-9263-f570ad2e0acf.png)

**Comment by adonismendozaperez** [comment]
Hello, 

You can Create multiple Columns, 
in your case three columns, and into this column create a table

**Comment by adonismendozaperez** [comment]
> Hello,
> 
> You can Create multiple Columns,
> in your case three columns, and into this column create a table

This a Example:

https://pastebin.com/V8axu6ZF
