### ISSUE TITLE
Dynamically create multiple tables with single data source

### ISSUE THREAD

**Issue by lprivette** [bpampuch/pdfmake#1874]
Hi,

I have an array that includes data on an item and its location. I'd like to display a separate table for each location. Depending on the page that the user is printing to pdf on, there could be any number of locations.

I'm currently using a function to generate a single table off that data, but I'd like to be generate separate tables with that data. Is this possible? In the doc definition I'm only ever defining a single table and I can't figure out how I would make multiple based on then number of locations my data has.

Thank you for any time and help!

**Comment by lprivette** [comment]
In case anyone else is having this issue. I ended up writing a function to create the tables outside the doc definition, and am pushing the tables into the doc definition before the download.

e.g: 
`dd.content.push(table);`
`pdfMake.createPdf(dd).download();`

**Comment by liborm85** [comment]
You can prepare table rows into variables from a single source:
```
var tableBody1 = [...];
var tableBody2 = [...];
```
and then only use in docDefinition:
```
var dd = {
	content: [
	    'Table 1:',
		{
			style: 'tableExample',
			table: {
				body: tableBody1
			}
		},
	    'Table 2:',
		{
			style: 'tableExample',
			table: {
				body: tableBody2
			}
		},		
	]
}
```

**Comment by lprivette** [comment]
Thanks for your response! That actually wouldn't solve my issue though because I don't know who many tables for each 'event' the user is downloading. The data is changing often. 

To solve it, I did still define my tables outside the doc definition and then made a function to output a table for each, and then push it to the doc definition.

```
for (const loc of this.eventLocs) {
        docDefinition.content.push(this.makeLocationTable(loc));
      }
```

**Comment by liborm85** [comment]
You can build the definition dynamically in javascript.

Example:
```js
var dd = {
	content: [
	]	
}

for (...) {
  var table = ...;
  dd.content.push(table);
}
```

**Comment by HegerValesin** [comment]
I'm using htmlToText.fromStringr to convert this text "'<p style="max-width: 650px !important; display: inline-block; position: relative; overflow: hidden; top: 0; bottom: 0; left: 0; right: 0;\r\t\t\t\t\tmargin: auto;"><p><img alt="" src="https://example/moodle/webservice/pluginfile.php/1/question /questiontext/391457/4/116086/CVOZ069C.jpg" style="height: 100%; height2:338px; width: 100%; width2:600px"></p> \n' +
       '<p>Shortly after their removal from the body, cells or tissue fragments
and organs must undergo a process called fixation, which has several purposes. Fixation can be done by chemical methods or, less frequently, by physical methods. In chemical fixation, tissues are immersed ...</p> \n' +
       '<p><br> Based on the text above, tick the box that describes an important purpose of fasteners.</p> \n' +
       '<p>&nbsp;</p></p>'"

 but the image comes with [ ] and doesn't open in pdfmake.
Is there any way to resolve it?
