### ISSUE TITLE
Warning: Invalid absolute docBaseUrl

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#1878]
Hello. I have looked everywhere for a solution to this potential error.

pdfmake displays document correctly in chrome and firefox but in console you get...

`Warning: Invalid absolute docBaseUrl: "data:application/pdf;base64,JVBERi0xLjcKJf`

Any ideas on how to solve this?

```
const pdfDocGenerator = pdfMake.createPdf(docDefinition);

pdfDocGenerator.getDataUrl((dataUrl) => {
  const targetElement = document.getElementById('embedContainer');
  targetElement.src = dataUrl;
  // console.info("PDF base64 output: ", dataUrl)

});
```

**Comment by suchislife801** [comment]
Ok. I have identified this line as the cause of the error.

`link: 'mailto:client@email.address?subject=Question%20about%20subcontract',`

**Comment by liborm85** [comment]
This is not related with pdfmake, with this warning is in firefox pdf viewer (https://mozilla.github.io/pdf.js/)

**Comment by suchislife801** [comment]
It also happens in Chrome and Edge as well.
