### ISSUE TITLE
Different  headers | header:function (currentPage) Cannot read property ' property ' of undefined

### ISSUE THREAD

**Issue by reworx-ux** [bpampuch/pdfmake#1879]
I've been struggling for weeks to get property read when in a docDefinition {header: function (currentPage) { if (currentPage != 1)  return [ ... (the table comes here) ...

**Ex.** this.offer.place.address.street -or- `${this.offer.place.address.street }` works as well in header: [], footer:[] and content:[]

My idea: I try to use defferent _header_ in the PDF, actually to remove/hide the _header_ on the first page. But when trying to use it as in the code below, I aways get Type Error: Cannot read property ' offer ' of undefined. 

**My code:**

```
 header: function(page, currentPage, pageCount) {
          if (currentPage != 1)  return [ 
            {
              margin:[50, 10, 40, 0],
              table: { 
                heights:3, widths:['20%','20%','20%','20%','20%'], body: [
                [
                  {rowSpan:2,style: 'h3',bold:true, text:'ANGEBOT'}, 
                  {style: 'tableRow',text:'Angebotsnummer'}, 
                  {style: 'tableRow',text:'Datum'},
                  {style: 'tableRow',text:'Leistungszeitraum'},
                  {rowSpan:3,style: 'h3',bold:true, text:'IMAGE/LOGO'},
                ],
                [
                  {}, 
                  {style:'h6',text:'Angebotsnummer'}, 
                  {style:'h6',text:'Datum'},
                  {style:'h6',text:'Leistungszeitraum'},
                  {},
                ],
                [
                  {colSpan:4,style:'h3',bold:true, text: '{{offer.place.address.street}}'}, 
                  {}, 
                  {},
                  {},
                  {},
                ],
                
               
              ]}
            },
                     
                ]
              
               },
```

<img width="788" alt="issue" src="https://user-images.githubusercontent.com/57011508/70860779-598f4000-1f26-11ea-925a-b86ecdc125e8.png">

**Comment by liborm85** [comment]
`offer` variable is not defined is in your code, is out of scope pdfmake. This is about javascript or some framework knowledges. For help with javascript use [stackoverflow](https://stackoverflow.com/) or other forum.

**Comment by rgenchev** [comment]
Hey @liborm85, thanks for the quick answer. I also have this problem. I can't use dynamic data in the `header` function. The variables I use are already defined and have values. I tried logging them in the browser console and everything was in order. Do you think that it is possible to use not only dynamic data in a `header` function? Thanks in advance! :)

**Comment by liborm85** [comment]
Simple example of usage:
```js
var someVariable = 'Outside variable';

var dd = {
    footer: function(currentPage, pageCount) { 
        return { text: someVariable }
    },
    header: function(currentPage, pageCount, pageSize) {
        return { text: someVariable }
    },    
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```
