### ISSUE TITLE
Can we have export in common image formats?

### ISSUE THREAD

**Issue by den-t** [bpampuch/pdfmake#188]
Something similar to PDF.js - pdfCanvas.toDataURL().

**Comment by jthoenes** [comment]
Could you elaborate what you mean?

**Comment by den-t** [comment]
The use case is rather simple. I'm already creating a PDF document using pdfmake, and it works like a charm. But some of my end-users need the final document to be in JPG or PNG format. Of course they can convert one to another, but that is nowhere near of straight forward solution.
So if there will be a possibility to save generated PDF as a JPG file or a bytestring that would be a perfect solution for my use case.
I do understand that it could be out of scope of this library. So it's more of a question than a feature request.

**Comment by jthoenes** [comment]
I think this would be out of scope. pdfmake uses PDFkit to actually do the PDF creation. As this library does not support creating images, I'll be very hard to introduce it to pdfmake.

I'm not the maintainer, however ...
