### ISSUE TITLE
How to use startPostion: with pageNumber:

### ISSUE THREAD

**Issue by reworx-ux** [bpampuch/pdfmake#1880]
No matter what I tried I couldn't get **startPostion:** with **pageNumber: 2** working.

How exactly should I use it?

**Comment by liborm85** [comment]
`startPostion` is not used in pdfmake.
`pageNumber` is used only as return value.

What do you want to do?

**Comment by reworx-ux** [comment]
I thought, I could use it to push a content starting at other page.... this would be a great feature

**Comment by liborm85** [comment]
Such properties do not exist.
