### ISSUE TITLE
Default font not set

### ISSUE THREAD

**Issue by sagarvibrant** [bpampuch/pdfmake#1882]
I load SVG with any Fonts and set Abel font as Default. But when i Generate PDF its throw error `Cannot read property 'normal' of undefined` or if font has Bold style then throw `Cannot read property 'Bold' of undefined` 
![Screenshot from 2019-12-17 15-40-26](https://user-images.githubusercontent.com/36664189/70987280-8fc6ee00-20e5-11ea-9dbf-bae10db20217.png)
 CODE:
pdfMake.fonts = {
          Courier: {            normal: 'Courier',            bold: 'Courier-Bold',            italics: 'Courier-Oblique',
            bolditalics: 'Courier-BoldOblique'          },
          Helvetica: {            normal: 'Helvetica',            bold: 'Helvetica-Bold',            italics: 'Helvetica-Oblique',            bolditalics: 'Helvetica-BoldOblique'          },
          Times: {            normal: 'Times-Roman',            bold: 'Times-Bold',            italics: 'Times-Italic',            bolditalics: 'Times-BoldItalic'          },
          Symbol: {            normal: 'Symbol'          },
          ZapfDingbats: {            normal: 'ZapfDingbats'          },
          Abel: {            normal: 'Abel-Regular.ttf',          }
        };
        var docDefinition = {
          pageSize: {            width: this.newEditorWidth / 4.16,            height: 'auto'          },
          pageMargins: [0, 0, 0, 0],
          content: [{            width: this.newEditorWidth / 4.16,            svg: s,          }],
          defaultStyle: {            font: 'Abel'          }
        };
        pdfMake.createPdf(docDefinition).download("Score_Details.pdf");

**Comment by liborm85** [comment]
What version of pdfmake are you using?

**Comment by sagarvibrant** [comment]
> What version number of pdfmake are you using?

version : 0.1.61

**Comment by liborm85** [comment]
Then update to latest version (0.1.63).

**Comment by sagarvibrant** [comment]
Thanks @liborm85.  It's Working Great : )

**Comment by sagarvibrant** [comment]
@liborm85 , One more question . There is no **Underline** and **Shadow** diplay while Generating PDF.
