### ISSUE TITLE
pdfMake rends une page blanche sur IE et EDGE, mais fonctionne sur Chrome et Firefox

### ISSUE THREAD

**Issue by FlorianDubois1** [bpampuch/pdfmake#1883]
Bonjour,

J'utilise pdfMake afin de générer un pdf à partir de texte contenu dans une base de données. Je souhaite générer le pdf à chaque fois qu'on en a besoin (ne pas l'enregistrer) de manière à ce qu'il soit toujours à jour avec la Base de données.

Tout fonctionne très bien sous firefox et chrome, mais IE et EDGE me retournent tous deux une page blanche à la fin du chargement de la page.

Voici le code javascript qui a l'air de poser problème : 
`
if (method == "open") {
    // pdfMake.createPdf(docDefinition).open({}, window);
    const pdfDocGenerator = pdfMake.createPdf(docDefinition);
    pdfDocGenerator.getDataUrl((dataUrl) => {
        const targetElement = document.querySelector('#iframeContainer');
        const iframe = document.createElement('iframe');
        iframe.src = dataUrl;
        targetElement.appendChild(iframe);
    });
}
else if (method == "print") {
    pdfMake.createPdf(docDefinition).print({}, window);
}
else if (method == "download") {
    pdfMake.createPdf(docDefinition).download(reference);
}
else {
    const pdfDocGenerator = pdfMake.createPdf(docDefinition);
    pdfDocGenerator.getDataUrl(function(dataUrl) {
        const targetElement = document.querySelector('#iframeContainer');
        const iframe = document.createElement('iframe');
        iframe.src = dataUrl;
        targetElement.appendChild(iframe);
    });
}
`

J'utilise précisément ce fichier : 
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.62/pdfmake.min.js
Je n'ai aucune erreur dans la console donc je ne comprends pas d'où viens le problème.

Merci de votre réponse

**Comment by liborm85** [comment]
Mělo by to fungovat ve všech prohlížečích podobně. Záleží jaká je struktura dokumentu, žádnou ukázku neuvádíš ani jaký operační systém používáš, potom je těžko radit. Bez ukázky která by způsobovala toto chování nelze nic odhalit.
