### ISSUE TITLE
Playground JQuery, NOT ANGULAR example. How?

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#1885]
Hello. I have created 10 functional templates that work ONLY if the page is entirely refreshed.

This means that if I click on the PREVIEW pdf button more than once, the document begins to add pages and it looks terrible. 

How do I prevent this? Tell me I don't need to use local storage for this to work as intended...

**Comment by liborm85** [comment]
Depends how you did it... May need to overwrite entire variable.
For questions about javascript is better to use [stackoverflow.com](https://stackoverflow.com/).
