### ISSUE TITLE
iOS Safari pdfmake methods. Behavior report.

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#1886]
Hello. I had the chance to test pdfmake methods in iOS Safari and here is what I've found:

`pdfMake.createPdf(docDefinition).download();`

- In desktop FireFox it does exactly what is says; triggers download box.
- In iOS Safari it opens a new tab and loads the PDF perfectly.

`pdfMake.createPdf(docDefinition).open();`

- In desktop FireFox it triggers the built-in popup blocker. You must allow it manually.
- In iOS Safari it does nothing because iOS Safari comes has default popup blocker setting turned on. You must disable it manually.

`pdfMake.createPdf(docDefinition).print();`

- In desktop FireFox it triggers the built-in popup blocker. You must allow it manually.
- In iOS Safari it does nothing because iOS Safari comes has default popup blocker setting turned on. You must disable it manually.

```
const pdfDocGenerator = pdfMake.createPdf(docDefinition);
pdfDocGenerator.getDataUrl((dataUrl) => {
	const targetElement = document.querySelector('#iframeContainer');
	const iframe = document.createElement('iframe');
	iframe.src = dataUrl;
	targetElement.appendChild(iframe);
});
```

- In desktop FireFox it works perfectly.
- In iOS Safari it seems to only show the first page of PDF document. It appears IOS Safari does not yet support this?

[See Stackoverflow post](https://stackoverflow.com/a/23663784)

**Conclusion so far**

If you wish to write a Javascript app that works in both Safari and FireFox, the following method is your best bet so far.

`pdfMake.createPdf(docDefinition).download();`

- In desktop FireFox it does exactly what is says; triggers download box.
- In iOS Safari it opens a new tab and loads the PDF perfectly.

**Comment by liborm85** [comment]
Thanks. Updated table in https://github.com/bpampuch/pdfmake/issues/800.

**Comment by adam-acosta** [comment]
Mobile browsers: I don't think download() "loads the PDF perfectly". It's just creates and opens a blob. I'd like an actual download to occur. Is it possible to actually generate a .pdf file and trigger an actual download in mobile browsers (chrome/safari)?

**Comment by suchislife801** [comment]
It is. The difference is, on iOS tablet or phone, you must have a Cloud service to safe the file to installed on your device. It can be DropBox, Google Drive, etc. It seems that for security reasons, Apple doesn't allow saving public web content to the Local File System as that would invite all kinds of security issues on their side.
