### ISSUE TITLE
Page breaks to next odd page.

### ISSUE THREAD

**Issue by lech206** [bpampuch/pdfmake#1889]
I generate documents witch have many parts. Each part have to start at odd page. How can I realize this?
Now I added two times pageBreak:'after'. But simtime part have more than one page and than document mismashes and I cant print on printer with duplex on.

I tryed use pageBeakBefore but document generate slowly. Example document have more than 500 pages.

**Comment by lech206** [comment]
Now I worked around this problem by modifiing pdfmake.js - added 'after2' option

`
function applyMargins(callback) { 
		var margin = node._margin;

		if (node.pageBreak === 'before') {
			self.writer.moveToNextPage(node.pageOrientation);
		}

		if (margin) {
			self.writer.context().moveDown(margin[1]);
			self.writer.context().addMargin(margin[0], margin[2]);
		}

		callback();

		if (margin) {
			self.writer.context().addMargin(-margin[0], -margin[2]);
			self.writer.context().moveDown(margin[3]);
		}

		if (node.pageBreak === 'after') {
			self.writer.moveToNextPage(node.pageOrientation);
		}
		
		if (node.pageBreak === 'after2') {
			self.writer.moveToNextPage(node.pageOrientation);
			if ((node.positions[0].pageNumber) % 2) {
				self.writer.moveToNextPage(node.pageOrientation);
			}
		}
	}`

in my code I use

`{ text: ' ', pageBreak: 'after2' }`
this work but no when text is empty string { text: '', pageBreak: 'after2' }
then I have error

`
{"text":"","pageBreak":"after2","_margin":null,"_inlines":[],"_minWidth":0,"_maxWidth":0,"positions":[]}
core.js:4002 ERROR TypeError: Cannot read property 'pageNumber' of undefined
    at applyMargins (pdfmake.js:61224)
    at LayoutBuilder.processNode (pdfmake.js:61145)
    at pdfmake.js:61235
    at Array.forEach (<anonymous>)
    at LayoutBuilder.processVerticalContainer (pdfmake.js:61234)
    at pdfmake.js:61164
    at applyMargins (pdfmake.js:61210)
    at LayoutBuilder.processNode (pdfmake.js:61145)
    at LayoutBuilder.tryLayoutDocument (pdfmake.js:60931)
    at LayoutBuilder.layoutDocument (pdfmake.js:60907)
`

**Comment by liborm85** [comment]
Implemented by commit 942accae2ff0f96729f91de420029e8fdaf50956 (in 0.1 branch) and 753c1b1145f61412d462ac3d75b336e8089da89a (in master branch).

New values for `pageBreak`:
`beforeOdd`
`beforeEven`
`afterOdd`
`afterEven`

You can test it.

**Comment by lech206** [comment]
Thanks a lot for fast solution. I've tested all 4 variants. It's works.
