### ISSUE TITLE
Table with 1 column only and max width

### ISSUE THREAD

**Issue by matey1116** [bpampuch/pdfmake#1891]
Hi there,

My use case requires that one of the tables only have 1 column which is full width. I have the following code:

```
var dd = {
	content: [
		{
			style: 'tableExample',
			width: ['99%'],
			table: {
				body: [
					['Column 1'],
					['One value goes here']
				]
			}
		}]
	
}
```
However, the table is not 100% width. I tried setting it `100%` as well but same result - table is not modified.

Is there a way to make 1 columned table full page width?

**Comment by liborm85** [comment]
Example with full page table width:
```
var dd = {
	content: [
		{
			table: {
				widths: ['*'],
				body: [
					['Column 1'],
					['One value goes here']
				]
			}
		}
	]
}
```
