### ISSUE TITLE
Font issue - Uncaught File

### ISSUE THREAD

**Issue by Mikeez** [bpampuch/pdfmake#1894]
Hello

I am unsure if it is a Windows related bug or Chrome... I am using Chrome and Windows 10.

`pdfmake.js:7442 Uncaught File 'Roboto-Regular.ttf' not found in virtual file system`

I have 

```
require( 'jszip' );
require('pdfmake/build/pdfmake.js');
require('pdfmake/build/vfs_fonts.js');
```

I am using React and JQuery

**Comment by liborm85** [comment]
With React is usually used:
```
var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```
or
```
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

Details in [documenation](https://pdfmake.github.io/docs/getting-started/client-side/).
