### ISSUE TITLE
side by side images don't show.

### ISSUE THREAD

**Issue by jmuffat** [bpampuch/pdfmake#1895]
With the code below, images do not show at all. I'm not sure I have the right expectations about how text type nodes should work... 

If I make the 'text' node a 'stack', the  images do appear. They end up on top of each other, but they do show.

Is there a best practice for drawing side by side images with pdfmake ?

```
var dd = {
  content: [{
    text: [
      'spacing ',
      {
        image: 'sampleImage.jpg',
        fit: [50, 50],
      },
      ' spacing ',
      {
        image: 'sampleImage.jpg',
        fit: [50, 50],
      },
      ' spacing'
    ],
    style: ["test"]
  }],
  styles: {
    test: {
      color: 'red'
    }
  }
}
```

**Comment by liborm85** [comment]
You can use `table`:

```js
var dd = {
  content: [
    {
      table: {
        body: [
          ['spacing ',
            {
              image: 'sampleImage.jpg',
              fit: [50, 50],
            },
            ' spacing ',
            {
              image: 'sampleImage.jpg',
              fit: [50, 50],
            },
            ' spacing'],
        ]
      },
      layout: 'noBorders'
    },
  ]
}
```

**Comment by jmuffat** [comment]
Sure, I actually am going for columns, which is even simpler :
```
var dd = {
  content: [
    {
      columns: [
          'spacing ',
          {
            image: 'sampleImage.jpg',
            fit: [50, 50]
          },
          ' spacing ',
          {
            image: 'sampleImage.jpg',
            fit: [50, 50],
          },
        ' spacing'
        ]
    }
  ]
}
```

I'll give a little more context : I'm working on a tool that starts from markdown content and generates both html pages and a pdf document. From time to time, authors will insert images as part of a paragraph in the makdown, which translates straighforwardly to html. This made me realize that pdfmake doesn't even show an image if it sits at the <span> level, which feels wrong. Now, having thought about it quite a bit more, I kind of see it is a whole giant can of worms because as soon as you start embedding an image inside a paragraph, you have to decide how it flows with it... 

So, yes, turns out that it's easier that I just detect that images are embedded, extract them and work out some columns logic and keep things simple. 




Who decides whether images not showing in this context is a bug or not ? 
(ie should I close this issue ?)

**Comment by liborm85** [comment]
Horizontal stack is not supported now (feature request: https://github.com/bpampuch/pdfmake/issues/358), workaround is via `table` (or `columns`).
