### ISSUE TITLE
Bold text in SVG is too thick

### ISSUE THREAD

**Issue by Rufflet** [bpampuch/pdfmake#1899]
Bold text in SVG is too thick and looks fuzzy (like it's stroked additionally).

eg, this svg `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 760 800" preserveAspectRatio="xMinYMin meet"><text class="title" x="380" y="20" text-anchor="middle" font-weight="bold" style="font-size: 16px;">Bold text sample</text></svg>`

generated with pdfmake:
![image](https://user-images.githubusercontent.com/15361093/72683697-8c5ec200-3aea-11ea-8b9e-9d72cdd133b4.png)

and pdfkit:
![image](https://user-images.githubusercontent.com/15361093/72683699-91237600-3aea-11ea-8a14-e09af5f1750a.png)

and it the playground:
![image](https://user-images.githubusercontent.com/15361093/72683706-a13b5580-3aea-11ea-972b-2b0cdacb2035.png)

I also noticed that it was good in version 0.1.61, but then something's happened.

generated with 0.1.61:
![image](https://user-images.githubusercontent.com/15361093/72683748-0000cf00-3aeb-11ea-82d7-36adfaeaf023.png)

and current:
![image](https://user-images.githubusercontent.com/15361093/72683750-0a22cd80-3aeb-11ea-9774-e8008db817c2.png)

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/31a505f26beea5ee6606debbca78816ce4216226 (in 0.1 branch) and https://github.com/bpampuch/pdfmake/commit/1bb014f0e8ed9902520e227f2f7f13aa06017878 (in master).
