### ISSUE TITLE
Save pdf document in the filesystem

### ISSUE THREAD

**Issue by almoraleslopez** [bpampuch/pdfmake#19]
Hello.

I'm working on a solution for getting the pdf generated to be saved on the server.

I have pdmake working on client side with angularjs. On the backend I hava nodejs and express.

My intention is to send an email with the pdf attached to it.

Any ideas for having this working?

Thanks...  and really good work with pdfmake!

**Comment by flaurian** [comment]
Hi,
Is it possible to get the pdf file result encoded in a base64 string? How would that work?
Thanks!

**Comment by flaurian** [comment]
Gonna answer this myself. I used a npm module called base64-stream and here is the code :

```
var base64 = require('base64-stream');
var base64stream = pdfDoc.pipe(base64.encode());
pdfDoc.end();

var tempFileBase64 = ''

base64stream.on('data',function(buffer){
var part = buffer.toString();
    tempFileBase64 += part;
    console.log('process data ' + part);
});

base64streamEvaluations.on('end',function(){
  console.log('final output ' + tempFileBase64);
});
```

Thank you myself! ;)

**Comment by juppwerner** [comment]
Thanks for letting us know!

Regards
--
Joachim Werner

Am 9. Juni 2016 08:53:03 MESZ, schrieb flaurian <notifications@github.com>:

**Comment by SaidMarar** [comment]
i can't use require('pdfmake') v0.1.24 in NODEJS so i used createPdfKitDocument , and i don't know how to get the arrayBuffer ... anyone here can help please
