### ISSUE TITLE
Page numeration on multi part reports

### ISSUE THREAD

**Issue by mk2fly1999** [bpampuch/pdfmake#1900]
I generate documents which have many parts. Each part should have its own page numeration .How can I do this?

**Comment by rabraha3** [comment]
I'm not sure! Apparently PDFKit does not support merging PDFs, so we cannot easily create a separate PDF for each report and put them together.

https://github.com/foliojs/pdfkit/issues/417

But there is an npm package which can merge PDFs -- `pdf-merge`.

https://www.npmjs.com/package/pdf-merge

It isn't a really satisfactory answer, but the `footer` callback function only gives you access to the

1. current page,
2. total number of pages, and
3. page size/orientation information.

**Comment by mk2fly1999** [comment]
Thanks for your answer, but i don't want to merge PDF's. Using PDFMAKE i generate one pdf document.  It consists  of several logical parts, which should have separate numeration.

**Comment by lech206** [comment]
http://pdfmake.org/playground.html

`var tableData = dataGenerator(3);

var dd = {
  content: tableData,
  footer: function(current, count) {
    const content = dd.content;

    let stackPages = 0;
    let stackPage = 0;
    for (let index = 0; index < content.length; index++) {
      var stack = content[index];
      let stackFirstpage = stack.positions[0].pageNumber;
      let stackLastPage =
        stack.positions[stack.positions.length - 1].pageNumber;
      if (current >= stackFirstpage && current <= stackLastPage) {
        stackPages = stackLastPage - stackFirstpage + 1;
        stackPage = current - stackFirstpage + 1;
        if (current > stackLastPage) {
          break;
        }
      }
    }
    if (stackPages) {
      return {
        text: "page " + stackPage + " from " + stackPages,
        margin: [55, 0, 0, 0]
      };
    }
    return { text: "", margin: [40, 0, 0, 0] };
  }
};

function dataGenerator(totalStacks) {
  let docDefinition = [];

  for (let i = 0; i < totalStacks; i++) {
    const r = Math.round(Math.random() * 90);
    console.log(r);
    let stack = [];
    for (let p = 0; p < r; p++) {
      stack = stack.concat([
        {
          text: `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.`,
          fontSize: 10,
          bold: true,
          margin: [15, 5, 0, 10]
        }
      ]);
    }
    if (i < totalStacks - 1) {
      stack = stack.concat([
        { text: ``, pageBreak: "after" },
        { text: ``, pageBreak: "after" }
      ]);
    }
    console.log(`stack ${stack.length}`);

    docDefinition.push({ stack: stack });
  }

  return docDefinition;
}
`

**Comment by liborm85** [comment]
It is not simply supported now, only according to the previous.

Feature request: https://github.com/bpampuch/pdfmake/issues/1270

**Comment by mbintex** [comment]
![image](https://user-images.githubusercontent.com/48861124/96371939-b706a580-1164-11eb-9b1a-955363ea3848.png)

**Comment by MyQuestion123** [comment]
@lech206 Brilliant and thank you for that stack code. I have been searching for this for years...
