### ISSUE TITLE
Problems with QR code

### ISSUE THREAD

**Issue by Tonym79** [bpampuch/pdfmake#1902]
Hi!
when I add many qr, none appears in the document.
I have tried to put its inside tables and with columns, but I have se same problem.
 Any suggestions?
(sorry for my english)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by Tonym79** [comment]
This code is inside a function:
   let ejemplo = '{"IdCentros": "14", "Nombre": "Construcciones Saavedra, SL"}'
        let ejemplonombre = 'Construciones Saavedra, SL'

        let arris = {columns: [
          [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
          [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
          [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
          [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
          ]};
        let arris2 = [{text:'   '}]

        var paso;
        for (paso = 0; paso < 5; paso++){
          modelopdf2.content.push(arris);
          modelopdf2.content.push(arris2)
        }    
        pdfMake.createPdf(modelopdf2).open({}, window);

**Comment by liborm85** [comment]
Do it this way:
```js
var dd = {
    content: [],
    pageMargins: [ 36, 36, 15, 15 ],
};

let ejemplo = '{"IdCentros": "14", "Nombre": "Construcciones Saavedra, SL"}'
let ejemplonombre = 'Construciones Saavedra, SL'        
let arris = function() { 
    return {columns: [
      [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
      [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
      [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
      [{qr: ejemplo, fit: '100', alignment: 'center'},{text : ejemplonombre, alignment: 'center', fontSize: 10}],
      ]}
      };
let arris2 = function() {
    return [{text:'   '}];
}

var paso;
for (paso = 0; paso < 5; paso++){
  dd.content.push(arris());
  dd.content.push(arris2())
}
```

**Comment by Tonym79** [comment]
Thank you! It is a perfect solution!
