### ISSUE TITLE
Adding 'cover' option for images 

### ISSUE THREAD

**Issue by KaiHuebner** [bpampuch/pdfmake#1906]
Thanks for this great library. I just switch from jsPDF and I love it.

One functionality I'm missing from pdfKit is the 'cover' option for images.
My images a mostly from canvas which can be any size due to the responsive design of my website.

I tried to change your code to include this functionality (pdfmake.js - line 19996):

```
function renderImage(image, x, y, pdfKitDoc) {
  pdfKitDoc.opacity(image.opacity || 1);
  if (image.cover) {
    pdfKitDoc.save()
    pdfKitDoc.rect(image.x, image.y, image.cover[0], image.cover[1]).clip()
    pdfKitDoc.image(image.image, image.x, image.y, {cover: [image.cover[0], image.cover[1]], align: 'center', valign: 'center'});
    pdfKitDoc.restore()
  } else {
    pdfKitDoc.image(image.image, image.x, image.y, { width: image._width, height: image._height });
  }
	if (image.link) {
		pdfKitDoc.link(image.x, image.y, image._width, image._height, image.link);
	}
}
```
So you can use it like this:
```
{
      image: 'data:image/jpeg;base64,...encodedContent...',
      cover: [100, 100]
}
```

Sorry for this crude implementation.
Can you include something similar?

Thanks

**Comment by liborm85** [comment]
Implemented by https://github.com/bpampuch/pdfmake/pull/2148
