### ISSUE TITLE
Extend bold, italics and bolditalics to allow for addtional types.

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#1907]
I would like to know if you are able to add support for more than just normal, **bold, italics and bolditalics**.

Below is the list of fonts I have added to my custom **vfs_fonts.js** file.

<img width="300" alt="vfs_fonts" src="https://user-images.githubusercontent.com/6699482/73153738-382b8300-4092-11ea-879e-711e6dfafa9a.PNG">

The limitation is that i can only bind 4 different designations to a font type like so:

```
// Document Fonts
pdfMake.fonts = {
  // Font 1
  HelveticaRoman: {
    normal: 'Neue Helvetica® Std 55 Roman.otf',
    bold: 'Neue Helvetica® Std 65 Medium.otf',
    italics: 'Neue Helvetica® Std 75 Bold.otf',
    bolditalics: 'Neue Helvetica® Std 85 Heavy.otf'
  },
  // Font 2
  HelveticaCondensed: {
    normal: 'Neue Helvetica® Std 57 Condensed.otf',
    bold: 'Neue Helvetica® Std 67 Condensed Medium.otf',
    italics: 'Neue Helvetica® Std 77 Condensed Bold.otf',
    bolditalics: 'Neue Helvetica® Std 87 Condensed Heavy.otf'
  }
};
```

As you can see, **the actual font name** _does not match_ its pdfmake designation. 

This is a work around to allow for the use of the many variations of a professional font family such as this one.

It would be greatly appreciated if you could add support for more designations than **bold, italics and bolditalics** as we could use professional font families available out there.

**Comment by liborm85** [comment]
No, it is not possible.  Multiple fonts must be used and splitted by subspecies.
