### ISSUE TITLE
How to reduce size vfs_fonts.js size

### ISSUE THREAD

**Issue by kvsssrk** [bpampuch/pdfmake#1908]
Greetings.

1)To support chinese,japanese,korean languages have added fonts kaiu.ttf, yugothic.ttf,malgun.ttf in examples/fonts folder .

2) On performing gulp buildFonts task, the vfs_fonts.js size has increased drastically. It become nearly 35mb.

Can you please provide the way to optimise the size of vfs_fonts.js ?

Can you suggest some font which will be smaller in size similar like roboto for another languages ?

Thanks!!!!

**Comment by lucianojs** [comment]
take a look here:

https://github.com/bpampuch/pdfmake/issues/1374
