### ISSUE TITLE
Would it be possible to generate a PDF/A compliant document?

### ISSUE THREAD

**Issue by sanderboom** [bpampuch/pdfmake#191]
Thanks for the great tool. As PDF/A is requested for the current project I'm involved in, I hope this is reachable.

For info on PDF/A: http://en.wikipedia.org/wiki/PDF/A

Thanks.

**Comment by jthoenes** [comment]
What does PDF/A imply for us?

**Comment by bpampuch** [comment]
I'm closing this now, feel free @sanderboom to reopen this issue as soon as you have the requirements
