### ISSUE TITLE
pageReference - right margin and disable linking

### ISSUE THREAD

**Issue by bandizsolt** [bpampuch/pdfmake#1910]
Hi!

Using this example in playground you can see that the pageReference have a right margin. This how can be removed, overwrited or something similar? Another question, the linking on that number can be disabled? Like: { pageReference: 'header1', linkToDestination: false}

         `var dd = {
				content: [

					{
						text: '\nAnd all can be in inline texts:\n'
					},
					{
						text: [
							'Chapter "',
							{ textReference: 'header1' },
							'" is on page number ',
							{ pageReference: 'header1' },"dsfsdf"
						]
					},
					{
						text: [
							'Chapter "',
							{ textReference: 'subheader1' },
							'" is on page number ',
							{ pageReference: 'subheader1' }
						]
					},
					{
						text: [
							'Chapter "',
							{ textReference: 'subheader2' },
							'" is on page number ',
							{ pageReference: 'subheader2' }
						]
					},
					{
						text: [
							'Chapter "',
							{ textReference: 'subheader3' },
							'" is on page number ',
							{ pageReference: 'subheader3' }
						]
					},
					{
						text: 'This is a header, using header style',
						style: 'header',
						id: 'header1',
						pageBreak: 'before'
					},
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam.\n\n',
					{
						text: 'Subheader 1 - using subheader style',
						style: 'subheader',
						id: 'subheader1',
						pageBreak: 'before'
					},
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
					{
						text: 'Subheader 2 - using subheader style',
						style: 'subheader',
						id: 'subheader2',
						pageBreak: 'before'
					},
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
					{
						text: 'It is possible to apply multiple styles, by passing an array. This paragraph uses two styles: quote and small. When multiple styles are provided, they are evaluated in the specified order which is important in case they define the same properties',
						style: ['quote', 'small']
					},
					{
						text: [
							{
								text: 'iji',
								style: 'subheader',
								id: 'subheader3',
								tocItem: false
							},
							{
								text: '; and this text not be displayed in ToC',
								italics: true
							}
						],
						pageBreak: 'before'
					},
					'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.'
				],
				styles: {
					header: {
						fontSize: 18,
						bold: true
					},
					subheader: {
						fontSize: 15,
						bold: true
					},
					quote: {
						italics: true
					},
					small: {
						fontSize: 8
					}
				}
			};`

![Capture2](https://user-images.githubusercontent.com/52448147/73384086-3a305480-42d3-11ea-9b08-a3249ab56a46.PNG)

**Comment by bandizsolt** [comment]
I see that in DocPreprocessor.js there is a '00000' on node.text and if I change that to '0' then it's ok. For what is that '00000' ?
![Capture](https://user-images.githubusercontent.com/52448147/73438137-372a7800-4356-11ea-840e-ac6664a00773.PNG)

**Comment by liborm85** [comment]
'00000' is used because page number does not have to be only single digit number.

**Comment by bandizsolt** [comment]
Ok, thank you, so to remove the unnecessary space can can we update the text like below?

```
node.text = '';
      if (node._pageRef) {
      	const pageCount = node._pageRef._nodeRef.nodeInfo.pageNumbers[0].toString().length;
      	if (pageCount > 0) {

      		 node.text = node.text.padStart(pageCount, '0');
      	}
      }
````
There was my another question, the linking on that number can be disabled? Like: { pageReference: 'header1', linkToDestination: false}
If there no function for this, something in this direction can be added?

```
if (node.linkToDestination !== false) {
      	node.linkToDestination = node.pageReference;
      }
```
Sorry I am not an expert, these are only ideas, I tested but maybe there are better solutions.

**Comment by liborm85** [comment]
If is prepared node for page reference, [here](https://github.com/bpampuch/pdfmake/blob/9b7e5e8b7ebeb13d9863c19fbe7d310257fc0029/src/docPreprocessor.js#L171-L173), total count of pages not known, we do not know what width for number will be needed. I haven't figured out how to solve it yet.

**Comment by bandizsolt** [comment]
Yeah, you are right, my workaround to get the total count of pages was to create a text element in the end of content, then with pageReference I can get the number of total pages.
```
//define on last page, last element
{
  text: " ",
  id: "totalpagecounter"
}
```
```
//get the total page number in the body
{
  text: [
    "Total page number: ",
    {
      pageReference: "totalpagecounter"
    },
  ]
}
```
If I am right only with footer and header I can get this number. 

But there is no need to know the total count of pages to determine the width for number what will be needed for pageReference. In my previous comment that function will calculate dinamically the width, like if is on page 23 then node.text will be updated to '00', if is on page 6 then will be '0' the node.text.
I tested this with multiple id, pageReference, and it is working. Every pageReference have a pageNumber right, so we only need this to calculate. This resolution is correct, what do you think?

**Comment by liborm85** [comment]
If you know way to solve problem with page number "reservation width" in text, you can create Pull request. Thanks.

**Comment by bandizsolt** [comment]
My "resolution" was based on "pageBreakBefore" function. So you have to use that function in docDefinition, but without that is not working. If I use pageBreakBefore then the document is rendered 2x?

**Comment by bigNeoneo** [comment]
> I see that in DocPreprocessor.js there is a '00000' on node.text and if I change that to '0' then it's ok. For what is that '00000' ?
> ![Capture](https://user-images.githubusercontent.com/52448147/73438137-372a7800-4356-11ea-840e-ac6664a00773.PNG)

bro, I tried your code but not work, and got this error:"TypeError: Cannot read property 'pageNumbers' of undefined",can you tell me the specific code you use, appreciate！

**Comment by bandizsolt** [comment]
Hi, I mentioned in tha last comment, that works only if you use the pageBreakBefore() function, because  that function, the document is "rendered" 2x. You will know the required pagebreaks after first render. So if you dont want to use this function, define it, to make pageReference work using the code you mentioned.
```
const docDefinition = {
... //other code
,
pageBreakBefore: function(
          currentNode,
          followingNodesOnPage,
          nodesOnNextPage,
          previousNodesOnPage
        ) {
          //do nothing
        },
... //other code
```
Then you can modify the pdfmake source code, the javascript, or the minified javascript, whichever you want.
