### ISSUE TITLE
Cloned repo, unable to use it after importing

### ISSUE THREAD

**Issue by zahrafali** [bpampuch/pdfmake#1911]
Hi,
I cloned this repo and published it under npm under a different name
When I install this, it gives an error when I try to use it by importing it.

It looks like a build issue because I compared the gulpfile.js in the node_modules folder after importing it, and they are different (compared the gulpfile.js pdfmake vs my_package)

I also compared the files inside the build folder, those files are also different.

Is there a specific way to build the project before publishing to npm or am I doing it wrong?
I would really appreciate some guidance on this.
Thanks

**Comment by liborm85** [comment]
I guess you did something wrong, the solution depends on what error are throws. Nothing special to publish is needed.

**Comment by zahrafali** [comment]
`stack:"/Users/zahraali/Code/wisedoc/wisedoc-api/lib/functions/exportToPdf/createPDF/createPdfKitDocument.js:2\nimport abc from "./abc";\n       ^^^\n\nSyntaxError: Unexpected identifier\n    at Module._compile (internal/modules/cjs/loader.js:721:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/Users/zahraali/Code/wisedoc/wisedoc-api/lib/functions/exportToPdf/createPDF/generateDocument.js:7:5)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Functio...`

This is the error that I get

**Comment by zahrafali** [comment]
`stack:"/Users/zahraali/Code/wisedoc/wisedoc-api/node_modules/@wisedocnpm/wisepdf/src/base.js:1\nimport Printer from './Printer';\n       ^^^^^^^\n\nSyntaxError: Unexpected identifier\n    at Module._compile (internal/modules/cjs/loader.js:721:23)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._load (internal/modules/cjs/loader.js:585:3)\n    at Module.require (internal/modules/cjs/loader.js:690:17)\n    at require (internal/modules/cjs/helpers.js:25:18)\n    at Object.<anonymous> (/Users/zahraali/Code/wisedoc/wisedoc-api/node_modules/@wisedocnpm/wisepdf/src/index.js:1:21)\n    at Module._compile (internal/modules/cjs/loader.js:776:30)\n    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)\n    at Module.load (internal/modules/cjs/loader.js:653:32)\n    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)\n    at Function.Module._lo...
`
This is the error message that I get

**Comment by liborm85** [comment]
Fixed loading ES5 as main by commit: https://github.com/bpampuch/pdfmake/commit/acb7ff5862a9162f38da4f26f34aeae7458bcf78

Before publishing is needed run build: https://github.com/bpampuch/pdfmake#building-from-sources

Thanks for testing master branch.

**Comment by zahrafali** [comment]
Thanks a ton :)
