### ISSUE TITLE
Questions about playground examples

### ISSUE THREAD

**Issue by vpo-dev** [bpampuch/pdfmake#1913]
Hi,

I've made some changes in the pdfmake source code to support the fill opacity attribute in tables.

To test my patch, I also added a new example. I thought the right place was in `examples/tables.js`.

However, files present in the `examples` folder are not those used when running the playground through `npm run playground`.  Instead files in `dev-playground/public/samples` are used. But those sample files are not in line with the last pdfmake releases (e.g. the protoype of `fillColor()` with 2 arguments, whereas it has now 3). In addition, as those sample files only contain the `content` var, it is required to manually copy the corresponding code from  `examples/*.js` files, which is error prone.

The other solution to test the playground is to checkout the `gh-pages` branch and to have a web server running the branch contents. In this case, files present in the `samples` folder seem up to date, but it is also required to manually edit them.

**Question 1:** Does a script exist to automatically update `dev-playground/public/samples` files from `examples` js files?
**Question 2:** In case of a pull request, do you also welcome new examples? Or do you only want changes in the core source code?
**Question 3:** And if you are happy with new examples in pull requests, shall I also provide examples for the `gh-pages` branch?

Cheers

Vincent

**Comment by liborm85** [comment]
> **Question 1:** Does a script exist to automatically update `dev-playground/public/samples` files from `examples` js files?

No, it is not automatically.

> **Question 2:** In case of a pull request, do you also welcome new examples? Or do you only want changes in the core source code?

Yes, pull requests with improvements examples are welcome.

> **Question 3:** And if you are happy with new examples in pull requests, shall I also provide examples for the `gh-pages` branch?

Yes, great.

**Comment by vpo-dev** [comment]
Ok thanks for the information.
Last question  : is there a way to test from the command line the js files stored in the `example` folder? Or is it for reference only?

**Comment by vpo-dev** [comment]
Ok thanks for the answers.
