### ISSUE TITLE
pageMargins 0 is not work

### ISSUE THREAD

**Issue by teerawat2606** [bpampuch/pdfmake#1914]
Hi,

I think this is an issue.

I have tried to set pageMargins to 0, It's not working as expected behavior.

In case of PDFkit is working as expected

I think the root cause is from 0 JS are converted to boolean and it's false then in library source on line 136 from printer.js https://github.com/bpampuch/pdfmake/blob/0.1/src/printer.js#L136 set deafult as 40 then it's true
```
var builder = new LayoutBuilder(pageSize, fixPageMargins(docDefinition.pageMargins || 40), new ImageMeasure(this.pdfKitDoc, docDefinition.images), new SVGMeasure());
```
 
## Steps to Reproduce the Problem
```js
const docDefinition = {
  pageSize: "A4",
  pageMargins: 0,
  pageOrientation: "portrait",
  content: [
    {
      text: "Hello this is PDFmake"
    }
  ]
};
```

## Expected Behavior 
Page margin should set to 0 
<img width="750" alt="Screen Shot 2563-01-31 at 11 58 06" src="https://user-images.githubusercontent.com/54131024/73513918-28a99280-4422-11ea-87b7-185e5ae13175.png">

## Actual Behavior
Page margin is set to 40 
![Screen Shot 2020-01-31 at 11 57 31](https://user-images.githubusercontent.com/54131024/73513906-1b8ca380-4422-11ea-95cc-73598a01339e.png)

## Specifications

  - Node Version: 12.14.1 (LTS)

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/3bd0e8753fb79ed3c884d65aa090423ab4c27625 (in master branch) and https://github.com/bpampuch/pdfmake/commit/568f6546a9a82696d0c0fff49e309e1ed65bb3f2 (in 0.1 branch).
