### ISSUE TITLE
Uncaught ReferenceError: require is not defined

### ISSUE THREAD

**Issue by rohitjadhav999** [bpampuch/pdfmake#1915]
Hi,

I'm getting error as "_Uncaught ReferenceError: require is not defined_" on below line:
var PdfPrinter = require('../src/printer');

**Comment by liborm85** [comment]
add more informations...

**Comment by rohitjadhav999** [comment]
I'm trying to generate pdf with watermark using below example:
https://github.com/bpampuch/pdfmake/blob/0.1/examples/watermark.js

But I'm getting error in this step "_var PdfPrinter = require('../src/printer');_"
Am I missing any libraries?

**Comment by vpo-dev** [comment]
Such error messages are displayed when you try to run in a Web browser a JS file intended for a server with Node.js. It is the case for all the examples, of which `watermark.js`.

If you want to run the example, you need to install Node.js on your computer and run the example by invoking `node watermark.js` from a command shell.

**Comment by liborm85** [comment]
Answered.
