### ISSUE TITLE
trying to generate multiple pdf reports each with different headers appended together into 1 report.

### ISSUE THREAD

**Issue by sishengz** [bpampuch/pdfmake#1919]
I am currently able to generate 1 report in base64 format. However, I am now trying to generate multiple reports and have them append into 1 report. Each pdf report will have different headers and data. 
Is this possible with this library?

```
  const pdf = printer.createPdfKitDocument(docDefinition);
  const chunks = [];
  let result;

  return new Promise((resolve) => {
    pdf.on('data', (chunk) => {
      chunks.push(chunk);
    });
    pdf.on('end', () => {
      result = Buffer.concat(chunks);
      resolve(`data:application/pdf;base64, ${result.toString('base64')}`);
    });
    pdf.end();
  });
```
The above is what i have working with only 1 docDefinition. is there a way to pass in an array of it and generate combined pdfs?

**Comment by liborm85** [comment]
Only one PDF file can be created via pdfmake. Merging is not supported.
