### ISSUE TITLE
Infinite loop when table row missing a cell

### ISSUE THREAD

**Issue by sophistifunk** [bpampuch/pdfmake#1922]
This breaks in the playground as well as locally for me.

Works:

```
var dd = {
    content: [
        {
            table: {
                body: [
                    ['xxx', 'yyy', 'zzz'],
                    ['xxx', 'yyy', 'zzz'],
                    ['xxx', 'yyy', 'zzz'],
                ]
            }
        },
    ]
}
```

Hangs:

```
var dd = {
    content: [
        {
            table: {
                body: [
                    ['xxx', 'yyy', 'zzz'],
                    ['xxx', 'yyy'],
                    ['xxx', 'yyy', 'zzz'],
                ]
            }
        },
    ]
}
```

**Comment by sophistifunk** [comment]
More diagnosis cases - this works:

```
var dd = {
    content: [
        'Works as expected',
        {
            table: {
                body: [
                    ['aaa', 'yyy', 'zzz'],
                    [
                        'single', 
                        {text:'double', colSpan:2},
                    ],
                    ['xxx', 'yyy', 'zzz'],
                ],
                headerRows:1,
            }
        },
    ]
}
```

But simply swapping the middle two cells around blows out:

```
var dd = {
    content: [
        'Hangs for ages then eventually throws',
        {
            table: {
                body: [
                    ['aaa', 'yyy', 'zzz'],
                    [
                        {text:'double', colSpan:2},
                        'single', 
                    ],
                    ['xxx', 'yyy', 'zzz'],
                ],
                headerRows:1,
            }
        },
    ]
}
```

**Comment by sophistifunk** [comment]
Adding a `widths:['*','*','*']` doesn't fix it, either.

**Comment by liborm85** [comment]
> Hangs:
> 
> ```js
> var dd = {
>     content: [
>         {
>             table: {
>                 body: [
>                     ['xxx', 'yyy', 'zzz'],
>                     ['xxx', 'yyy'],
>                     ['xxx', 'yyy', 'zzz'],
>                 ]
>             }
>         },
>     ]
> }
> ```

This does not cause infinite loops, but is thrown exception "Malformed table row, a cell is undefined.".
Because you have wrongly defined second row in table - missing last column.

**Comment by sophistifunk** [comment]
Yes I noticed this eventually. But I still think there's issues here:

1. It takes s tens of seconds for this to happen.
2. the error message itself is vague, and includes massive amounts of information and a huge tree dump.
3. It's unexpected versus the way colspan and rowspan work in all other systems I can think of, where you skip cells that don't exist rather than include placeholders. 
4. It doesn't appear to be documented.

**Comment by liborm85** [comment]
> 1. It takes s tens of seconds for this to happen.

If this example takes tens of seconds, there will be no problem in pdfmake, but on your computer.

> 2. the error message itself is vague, and includes massive amounts of information and a huge tree dump.

Only this error is displayed "Uncaught Malformed table row, a cell is undefined.". Displayed stack trace for errors is a general property of javascript, not related to pdfmake.

> 3. It's unexpected versus the way colspan and rowspan work in all other systems I can think of, where you skip cells that don't exist rather than include placeholders.

pdfmake uses a different definition format, that's why it's different. Any change now is BC. Maybe changed in 0.2.

> 4. It doesn't appear to be documented.

Documentation is not perfect, issue for improve is here https://github.com/bpampuch/pdfmake/issues/1238 , but tables are documented [here](https://pdfmake.github.io/docs/document-definition-object/tables/) good.
