### ISSUE TITLE
OTF fonts for NotoSansCJK show bad characters, unlike ttf files

### ISSUE THREAD

**Issue by fireflower19** [bpampuch/pdfmake#1930]
I've been trying to use pdfmake to generate reports, and while TTF fonts build just fine, I can't get any of the otf versions to build without displaying entirely incorrect characters.  Specifically, I'm trying to use NotoSansCJKsc.otf and NotoSansCJKjp.otf; Right now I'm using version 0.1.57, which is after the version that says to have added the ability to build otf fonts. (https://github.com/bpampuch/pdfmake/issues/365)

I've additionally tried other smaller fonts like GreatVibes-Regular.otf to make sure it wasn't just this particular font. They all produced the same results.

The fonts work correctly on Microsoft word / any software on my computer

Is there a known issue that only impacts this particular font? Or is there some possible functionality regression?

Help would be greatly appreciated.

**Comment by fireflower19** [comment]
I've additionally tried other smaller fonts like GreatVibes-Regular.otf
Which produce the same results.

**Comment by liborm85** [comment]
Add example for reproduce issue e.g. on https://jsfiddle.net/.

**Comment by liborm85** [comment]
No reaction.
