### ISSUE TITLE
Characters missing when using NotoSansCJKjp TTF for bold and regular in the same pdf

### ISSUE THREAD

**Issue by fireflower19** [bpampuch/pdfmake#1931]
Because of another issue (https://github.com/bpampuch/pdfmake/issues/1930) where I'm unable to use OTF fonts, I've been trying to use the only TTF version of NotoSansCJKjp I could find.

For some reason the font is missing characters in the pdf, even though the font works on my computer in Microsoft Word just fine.

What's most odd, is that the font that is marked as the "defaultStyle" font (either regular or bold) shows all characters, while whichever is marked for indvidual sections as overrides are missing the characters.  So it's clear that each of the fonts have the characters available, but for some reason how they're being interpreted in pdfmake causes additional issues.

Any help would be greatly appreciated.

Currently on version 1.57

[NotoSansCJKjp-TTF-fonts.zip](https://github.com/bpampuch/pdfmake/files/4216512/NotoSansCJKjp-TTF-fonts.zip)

**Comment by liborm85** [comment]
Add example for reproduce issue e.g. on https://jsfiddle.net/.

**Comment by eljenso** [comment]
Came across this issue while adding support Japanese support to PDF reports.
I solved this by using another font ([M PLUS 1p](https://fonts.google.com/specimen/M+PLUS+1p)), which works fine.

@fireflower19 I hope this helps you.

**Comment by liborm85** [comment]
No reaction.
