### ISSUE TITLE
Generate multiple tables using array of arrays in pdfmake

### ISSUE THREAD

**Issue by Ramarjunan** [bpampuch/pdfmake#1932]
I'm trying to generate multiple tables of pdfmake content in a function using this procedure and here is my code. In this code error not came but tables are not rendering. 

```
getExpenseObject(data1) {
    console.log('come', JSON.stringify(data1), 'new');
    var rows = [];
    this.data1.forEach(element => {
      this.tableData = element.claimExpenseList;
      rows.push({
        table: {
          widths: ['*','*','*','*','*','*','*','*'],
          body: [
            [{
              text: 'Date',
              style: 'tableHeader'
            },
            {
              text: 'Merchant',
              style: 'tableHeader'
            },
            {
              text: 'Category',
              style: 'tableHeader'
            },
            {
              text: 'Notes',
              style: 'tableHeader'
            },
            {
              text: 'Amount USD',
              style: 'tableHeader',
            },
            {
              text: 'Exchange Rate',
              style: 'tableHeader'
            },
            {
              text: 'Amount INR',
              style: 'tableHeader',
            },
            {
              text: 'Receipt',
              style: 'tableHeader'
            }
            ],
            this.tableData.map(ed => {
              console.log('table', this.tableData);
              return [   
                console.log('cool', ed.expDate),
                { text :ed.expDate, alignment: 'left', style: 'tablebody' },
                { text :ed.merchantName, alignment: 'left', style: 'tablebody' },
                { text :ed.category, alignment: 'left', style: 'tablebody', },
                { text :ed.comments, alignment: 'left', style: 'tablebody' },
                { text :ed.totalAmount, alignment: 'right', style: 'tablebody' },
                { text :ed.requestCurrencyExchangeRate, alignment: 'right', style: 'tablebody' },
                { text :ed.requestCurrencyApprovedAmount, alignment: 'right', style: 'tablebody' },
                { text: ed.requestCurrencyApprovedAmount, alignment: 'left', style: 'tablebody', decoration:"underline", color: '#0077CC', linkToDestination: ed.id}
              ]})
          ]
        },
        layout: {
          hLineColor: function(i, node) {
              return (i === 0 || i === node.table.body.length) ? '#a8cbe4' : '#a8cbe4';
          },
          vLineColor: function(i, node) {
              return (i === 0 || i === node.table.widths.length) ? '#a8cbe4' : '#a8cbe4';
          },
          fillColor: function (rowIndex, node, columnIndex) {
            node.table.body.forEach(item => {
              if (item.text === 'Total Taxi') {
                console.log('Success');
              }
            });
            return (rowIndex  === 3 ||  rowIndex === 6) ? '#a8cbe4' : 'white';
          },
          paddingLeft: function(i, node) { return 3; },
          paddingRight: function(i, node) { return 3; },
          paddingTop: function(i, node) { return 3; },
          paddingBottom: function(i, node) { return 3; }
        }
      })
      console.log(rows, 'rows');
      return rows
    });
    
  }
```

**Comment by liborm85** [comment]
I don't know what is in variable `data1` or `this.data1`.   `data1` and `this.data1` should contain the same values?
Need to be added to reproduce.

**Comment by Ramarjunan** [comment]
{attachments:[
	{id:"237", url:"https://xpensa.azurewebsites.net/bills/02/bill.jpg"},
	{id:"238", url:"https://xpensa.azurewebsites.net/bills/02/bill.jpg"},
	{id:"239", url:"https://xpensa.azurewebsites.net/bills/02/bill.jpg"},
]
}


data1 = [
[
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'}
],
[
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'}
],
[
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'}
],
[
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'},
{expDate: '30-12-2020', merchantName: 'Taxi', category: 'bus', comments: '', totAmount: 123, reqAmount: 123, reqCurrencyAmt: 456, receipt: 'BillNo1'}
]
]


 data1 should be like this

**Comment by Ramarjunan** [comment]
ya contains same values

**Comment by liborm85** [comment]
Nothing is rendered, because  this line `this.tableData = element.claimExpenseList;` set to tableData `undefined`, because property claimExpenseList is not defined in data1.

**Comment by Ramarjunan** [comment]
Hi acutally i fixed this issue. Sorry i didn't gave correct data structure. Thanks for ur help.
