### ISSUE TITLE
linkToPage function with images

### ISSUE THREAD

**Issue by BorisBosnar** [bpampuch/pdfmake#1934]
I need the "linkToPage" function for images or is there a workaround?

Works without problems:
{ image: 'pin.png', width: 30, height: 45, link: 'https://www.google.com/' }

Doesn't work:
{ image: 'pin.png', width: 30, height: 45, linkToPage: 2 }

P.S. Thanks for this awesome PDF generator

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/48907711ca3a9f8cf958cc1e5201e5a05b709ae2 (in 0.1 branch) and https://github.com/bpampuch/pdfmake/commit/b914c7e1143cadbf1ea3910baf1a03e4c6a073e7 (in master branch).
