### ISSUE TITLE
Support PWA

### ISSUE THREAD

**Issue by rusliabdulgani** [bpampuch/pdfmake#1935]
Hi All,

I Have web apps using react js (create-react-app) and enabling PWA, after install/add app to home screen, then i cannot open or just download pdf. apps just force close. 

Any solution about it? is pdfmake support PWA ?

**Comment by liborm85** [comment]
PWA support has not been tested.

**Comment by liborm85** [comment]
If anyone comes up with a solution, PR is welcome.

**Comment by Lxstr** [comment]
Checkout FileSharer from '@byteowls/capacitor-filesharer'
