### ISSUE TITLE
QR code has a variable size depending on how much data

### ISSUE THREAD

**Issue by markhbucknell** [bpampuch/pdfmake#1938]
Hello,

In my testing, I've noticed that the size of the QR string changes the size of the QR Code.
Is it possible to set a static height for the QR code so then both small strings and large strings result in the same size QR code?

Thank you!

**Comment by liborm85** [comment]
This is the general behavior of QR codes. You can use `fit` property for resize QR code, see [documentation](https://pdfmake.github.io/docs/document-definition-object/qr/).
