### ISSUE TITLE
Complex table is malformed

### ISSUE THREAD

**Issue by CodingJun** [bpampuch/pdfmake#1939]
When I user pdfmake to create table, the code like this
`
var dd = {
	content: [
	    ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
	    ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
	    ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ', ' ',
	    {
		"table": {
			"widths": [
				13,
				15,
				26,
				26,
				27,
				33,
				98,
				92,
				26,
				85
			],
			"body": [
                          [
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#f6f6f6"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 5,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 5,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 3,
						"fillColor": "#ffedeb"
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#ffedeb"
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 3,
						"fillColor": "#ffedeb"
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 8,
						"fillColor": "#ffedeb"
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 2,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 2,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 1
					},
					{
						"text": " "
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 2,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 3,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 3,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 2,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "123456789012",
						"colSpan": 1,
						"rowSpan": 1
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": " "
					}
				],
				[
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 1,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 1,
						"fillColor": "#ffedeb"
					},
					{
						"text": " "
					},
					{
						"text": " "
					},
					{
						"text": "",
						"colSpan": 1,
						"rowSpan": 1
					},
					{
						"text": " "
					}
				]
			]
		}
	}]
}
`
Table border lines and background colors are out of range
<img width="552" alt="截屏2020-03-07下午2 08 16" src="https://user-images.githubusercontent.com/12445745/76137951-79de1f00-607d-11ea-81fa-c49e592f7d05.png">
For example, The content in the red box should not appear

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/928
