### ISSUE TITLE
NPM Audit reports

### ISSUE THREAD

**Issue by goxr3plus** [bpampuch/pdfmake#1940]
Hi i am having the below warnings about pdfmake :

```JAVA
                                 Manual Review                                  
             Some vulnerabilities require your attention to resolve             
                                                                                
          Visit https://go.npm.me/audit-guide for additional guidance           


  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   pdfmake                                                       

  Path            pdfmake > pdfkit > fontkit > brfs > static-module > falafel   
                  > acorn                                                       

  More info       https://npmjs.com/advisories/1488                             


  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   pdfmake                                                       

  Path            pdfmake > svg-to-pdfkit > pdfkit > fontkit > brfs >           
                  static-module > falafel > acorn                               

  More info       https://npmjs.com/advisories/1488                             


  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   eslint-config-rallycoding [dev]                               

  Path            eslint-config-rallycoding > eslint > espree > acorn           

  More info       https://npmjs.com/advisories/1488                             


  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   eslint-config-rallycoding [dev]                               

  Path            eslint-config-rallycoding > eslint-plugin-class-property >    
                  eslint > espree > acorn                                       

  More info       https://npmjs.com/advisories/1488                             


  Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   webpack [dev]                                                 

  Path            webpack > acorn                                               

  More info       https://npmjs.com/advisories/1488        
```

**Comment by liborm85** [comment]
> ```java
>   Moderate        Regular Expression Denial of Service                          
> 
>   Package         acorn                                                         
> 
>   Patched in      >=7.1.1                                                       
> 
>   Dependency of   pdfmake                                                       
> 
>   Path            pdfmake > pdfkit > fontkit > brfs > static-module > falafel   
>                   > acorn                                                       
> 
>   More info       https://npmjs.com/advisories/1488                             
> ```

Not related with pdfmake, it is fontkit issue.

> ```java
>   Moderate        Regular Expression Denial of Service                          
> 
>   Package         acorn                                                         
> 
>   Patched in      >=7.1.1                                                       
> 
>   Dependency of   pdfmake                                                       
> 
>   Path            pdfmake > svg-to-pdfkit > pdfkit > fontkit > brfs >           
>                   static-module > falafel > acorn                               
> 
>   More info       https://npmjs.com/advisories/1488   
> ```

Not related with pdfmake, it is fontkit issue.
                    
> ```java
>   Moderate        Regular Expression Denial of Service                          
> 
>   Package         acorn                                                         
> 
>   Patched in      >=7.1.1                                                       
> 
>   Dependency of   eslint-config-rallycoding [dev]                               
> 
>   Path            eslint-config-rallycoding > eslint > espree > acorn           
> 
>   More info       https://npmjs.com/advisories/1488   
> ```

Not related with pdfmake, it is eslint/plugin issue.
                          
> ```java
>   Moderate        Regular Expression Denial of Service                          
> 
>   Package         acorn                                                         
> 
>   Patched in      >=7.1.1                                                       
> 
>   Dependency of   eslint-config-rallycoding [dev]                               
> 
>   Path            eslint-config-rallycoding > eslint-plugin-class-property >    
>                   eslint > espree > acorn                                       
> 
>   More info       https://npmjs.com/advisories/1488    
> ```

Not related with pdfmake, it is eslint/plugin issue.
                          
> ```java                         
>   Moderate        Regular Expression Denial of Service                          
> 
>   Package         acorn                                                         
> 
>   Patched in      >=7.1.1                                                       
> 
>   Dependency of   webpack [dev]                                                 
> 
>   Path            webpack > acorn                                               
> 
>   More info       https://npmjs.com/advisories/1488        
> ```

Not related with pdfmake, it is webpack issue.


Why did you create issue in pdfmake library?

**Comment by goxr3plus** [comment]
This is webpack issue ? 

```
 Moderate        Regular Expression Denial of Service                          

  Package         acorn                                                         

  Patched in      >=7.1.1                                                       

  Dependency of   pdfmake                                                       

  Path            pdfmake > pdfkit > fontkit > brfs > static-module > falafel   
                  > acorn                                                       

  More info       https://npmjs.com/advisories/1488
```

**Comment by goxr3plus** [comment]
Okay i understood :)

**Comment by goxr3plus** [comment]
I though some of them had to do with pdfmake internally code :)

**Comment by liborm85** [comment]
Yes these libraries uses pdfmake, but must be fixed in these libraries. pdfmake has no way to fix it.

**Comment by goxr3plus** [comment]
I understand now :)
