### ISSUE TITLE
Join table together in the next page..

### ISSUE THREAD

**Issue by jasonhoo95** [bpampuch/pdfmake#1941]
![Screen Shot 2020-03-10 at 8 36 04 PM](https://user-images.githubusercontent.com/13375280/76312863-dd32b000-630e-11ea-9a2d-be80b9eaa7ca.png)
Hi is there any way i can use the pdfmake table to do this effect..?

**Comment by liborm85** [comment]
Can be used `unbreakable: true`, example:
```js
var dd = {
	content: [
		{
			unbreakable: true,
			table: {
				body: [
					...
				]
			}
		},
	]
}
```
