### ISSUE TITLE
Dependency Vulnerability acorn 

### ISSUE THREAD

**Issue by sdmiller7** [bpampuch/pdfmake#1942]
Vulnerability found in the acorn  in Pdfkit dependency
https://www.npmjs.com/advisories/1488

+-- pdfmake@0.1.65
| +-- linebreak@1.0.2
| | `-- brfs@2.0.2
| |   `-- static-module@3.0.3
| |     `-- acorn-node@1.8.2
| |       `-- acorn@7.1.0
| `-- pdfkit@0.11.0
|   `-- fontkit@1.8.0
|     `-- brfs@1.6.1
|       `-- static-module@2.2.5
|         `-- falafel@2.1.0
|           **`-- acorn@5.7.3**

**Comment by liborm85** [comment]
Not related with pdfmake library, duplicate: https://github.com/bpampuch/pdfmake/issues/1940

**Comment by sdmiller7** [comment]
Sorry but how is this not "related" to your plugin since you use a specific version of a dependency that has a dependency with this vulnerability.  At the very least you have a responsibility to update this dependency when a fix has been issued. Does that mean with pdfkit fixes their font

**Comment by liborm85** [comment]
pdfmake contains latest version of pdfkit and fontkit library. Vulnerability is in fontkit library where no new version was released.
pdfmake has no way to fix vulnerability in used 3rd-part library. Therefore issue is not related with pdfmake.
