### ISSUE TITLE
http://pdfmake.org/ is down 

### ISSUE THREAD

**Issue by goxr3plus** [bpampuch/pdfmake#1947]
Hi :) 

I am trying to access  http://pdfmake.org/ but its down ...

**Comment by diepmyduong** [comment]
me too

**Comment by josiah1888** [comment]
If you're trying to load the playground like I was, it is pretty easy to clone the playground repo and run it locally from https://github.com/blikblum/pdfmake-playground

Looks like just 
```
git clone https://github.com/blikblum/pdfmake-playground
cd pdfmake-playground
npm install
npm run dev
# nav browser to localhost:8080
```

**Comment by aaale83** [comment]
Is there a way to access the code i was testing in the playground from my browser before the website went down?

**Comment by liborm85** [comment]
## temporary mirror: http://liborm85.github.io/pdfmake

**Comment by goxr3plus** [comment]
Thank you :) , you can also use https://www.netlify.com/ .

**Comment by superlbr** [comment]
@liborm85 down too

**Comment by liborm85** [comment]
Site is back.
