### ISSUE TITLE
Can not export symbols available microsoft word to pdf

### ISSUE THREAD

**Issue by mmalay** [bpampuch/pdfmake#1948]
![Screenshot (470)](https://user-images.githubusercontent.com/26890207/77503746-66f08a80-6e84-11ea-9137-ea6f93d35612.png)
When I tried to generate pdf with symbols available in Microsoft word, it's showing some random characters.

**Comment by Tilogorn** [comment]
You have to embed a font that resembles these "symbols" either as normal characters (e.g `Windings`) or as unicode representation.

See the font in your browser: it can display several unicode characters: `✓ β ε`

**Comment by zahrafali** [comment]
In the 14 fonts supported by pdfmake, there is one font **_Symbol_** 
But that font wont support the Symbols in Microsoft word.

It'd be of great help if you can show me a sample code using the Symbol font

**Comment by liborm85** [comment]
The font you use in MS Word, you must also use it in pdfmake.
