### ISSUE TITLE
Page Number / Count in the content

### ISSUE THREAD

**Issue by matthew2564** [bpampuch/pdfmake#1949]
Hi, I know this is possible in the header/footer to get the pageNumber, but I am looking to access this info in the content itself, is there any simple way to do this?

**Comment by jackwshepherd** [comment]
I would love to know this too. I tried a hacky workaround by mutating a variable in one of the functions (pagebreakbefore etc.), but it doesn't seem to work

**Comment by whahoo** [comment]
Came here looking for the same and found this: https://github.com/bpampuch/pdfmake/blob/master/examples/pageReference.js
