### ISSUE TITLE
Nested List now working

### ISSUE THREAD

**Issue by MaxiSantos** [bpampuch/pdfmake#195]
You can see in "List" section in http://bpampuch.github.io/pdfmake/playground.html that "item
3" should be the third one, but instead it's the fourth. I gues the previous argument (a nested list) is also modifing the index of the previos list.

**Comment by jthoenes** [comment]
To be precise: 

````javascript
{
  ol: [
    'item 1',
    'item 2',
    {
      ol: [
        'subitem 1',
        'subitem 2'
      ]
    },
    'item 3',
  ]
},
````

Is causing this

![screen shot 2015-02-17 at 13 48 37](https://cloud.githubusercontent.com/assets/15578/6228407/d8cbf2ca-b6ab-11e4-9a57-2bf6c9d15db1.png)


Actually - looking at this, ``'item 3'`` is the fourth item. To make sense out of this, it would be necessary to combine the text 'item 4'. Something like this:

```javascript
{   text: 'item 2',
  ol: [
    'subitem 1',
    subitem 2'
  ]
}
````

**Comment by jthoenes** [comment]
You can make item 2 an array to fix this:

````javascript
{
     ol: [
       'item 1',
       [
           'item 2',
            ['subitem 2.1', 'subitem 2.2']
       ],
       'item 3',
   ]
}
````

Will update the playground to default to this.
