### ISSUE TITLE
Trying to make a table on pdfmake 

### ISSUE THREAD

**Issue by caem1420** [bpampuch/pdfmake#1950]
Hello i'm trying to make a table like this 
![1](https://user-images.githubusercontent.com/28551270/77440303-288c9a00-6db6-11ea-844d-4359c7a52c1a.png)

my code is this 
`{
          table: {
            widths: ["auto", "auto", 'auto', 'auto'],

            body: [
              [
                {text: "MECANISMOS DE VINCULACION", bold: true, alignment: "center", colSpan: 2}, 
                {text: "CLASIFICACION DE LA PRACTICA PROFESIONAL", bold: true, alignment: "center", colSpan: 3},
                {},
                {}
              ],
              ['Contrato de Aprendizaje ' ,{text:"X", bold:true, alignment: "center"}, 'Investigación', {}],

            ]
          }
        },`

but end up looking like this 

![2](https://user-images.githubusercontent.com/28551270/77440467-570a7500-6db6-11ea-8b26-0c0d4ce21cdd.png)

**Comment by Tilogorn** [comment]
You misunderstood the concept of `colSpan`. Maybe you should read some documentation about the HTML `<table>` attributes `rowspan` and `colspan` to get the concept.

This should help you:

```js
{
    table: {
        widths: ["auto", "auto", 'auto', 'auto'],
        body: [
            [
                {text: "MECANISMOS DE VINCULACION", bold: true, alignment: "center", colSpan: 2}, 
                {},
                {text: "CLASIFICACION DE LA PRACTICA PROFESIONAL", bold: true, alignment: "center", colSpan: 2},
                {},
            ],
            [
                'Contrato de Aprendizaje ' ,
                {text:"X", bold:true, alignment: "center"}, 
                'Investigación', 
                {}
            ],
        
        ]
    }
}
```
![Bildschirmfoto vom 2020-03-25 09-23-55](https://user-images.githubusercontent.com/7524854/77516405-a5814780-6e7a-11ea-9fa2-5b4d82f83fb0.png)
