### ISSUE TITLE
Can the document definition be generated from a PDF

### ISSUE THREAD

**Issue by bartonhammond** [bpampuch/pdfmake#1952]
Given a PDF, is it possible to generate the doc definition?

**Comment by liborm85** [comment]
No, this is out of scope pdfmake.

**Comment by nafberger** [comment]
Hi, I also have this question. maybe I am trying to use this library for something which it was not designed. let's say we get back a base 64 string as a label from ups or FedEx and we want to print it for the user. can it be done with pdf-make? I mean to say we have no document definition and no need for it just the base 64 string. please reply. big thanks

**Comment by liborm85** [comment]
Yes, pdfmake is used to generate pdf documents from definition see [documentation](https://pdfmake.github.io/docs/) and [playground](http://pdfmake.org/playground.html).
