### ISSUE TITLE
Trying to make a simple box with columns inside.

### ISSUE THREAD

**Issue by nafberger** [bpampuch/pdfmake#1953]
Sorry for asking. I am trying to make a simple box with 3 columns inside. like in this picture

![Screenshot_5](https://user-images.githubusercontent.com/26122027/77604581-427ac980-6ee9-11ea-91bd-f9bde03e3aff.png)

it's not a table. I tried with the examples but it didn't work. huge thanks

**Comment by liborm85** [comment]
Attach example of docDefinition.
