### ISSUE TITLE
Rotated image inside <g> tag becomes blurry

### ISSUE THREAD

**Issue by ilbrigz** [bpampuch/pdfmake#1958]
```
<g transform="matrix(0.2 -0.34 0.34 0.2 240.02 110.09)"  >
//<image style="stroke: none; stroke-width: 0; stroke-dasharray: none; stroke-linecap: butt; stroke-dashoffset: 0; stroke-linejoin: miter; stroke-miterlimit: 4; fill: rgb(0,0,0); fill-rule: nonzero; opacity: 1;"  xlink:href="data:image/png;base64,iVBORw0KGgoAAAANSUhEUg...
</g>
```

The above pseudo code produces a blurry image. This one is causing the problem **transform="matrix(0.2 -0.34 0.34 0.2 240.02 110.09)"**. After changing it to **transform="matrix(0.2 0 0 0.2 240.02 110.09)"** the image quality improved. How can I fix this but still keep the rotation?

**Comment by liborm85** [comment]
For rendering svg in pdfmake is used [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit), please create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).
