### ISSUE TITLE
The download option freezes firefox

### ISSUE THREAD

**Issue by Wabbala** [bpampuch/pdfmake#196]
Hi guys,

I have got the following issue. When I render a pdf and I would like to save it using
`pdfMake.createPdf(docDefinition).download(filename)`
It results in firefox not responding and it alerts with: a script on this page is causing your web browser to run slowly.

Any ideas?

Cheers!

**Comment by jthoenes** [comment]
Is this a duplicate of #122?

**Comment by Wabbala** [comment]
Actually this freeze up is caused by firefox versions < 25. For firefox versions 25+ this is no longer an issue.
