### ISSUE TITLE
vfs propriety issue

### ISSUE THREAD

**Issue by stingers** [bpampuch/pdfmake#1960]
Hello ! I'm farcing the following error on compilation on Angular 9.1.0(ps: I follow the documentation) But no way.
`error TS2540: Cannot assign to 'vfs' because it is a read-only property. 5 pdfMake.vfs = pdfFonts.pdfMake.vfs; `

Someone have an idea ?!!

**Comment by liborm85** [comment]
Attach simple example of your script.

**Comment by stingers** [comment]
Hello, sorry after some updates in angular the error seems gone.
