### ISSUE TITLE
Gulpfile is not generated

### ISSUE THREAD

**Issue by neil89** [bpampuch/pdfmake#1967]
I'm using pdfmake in my Angular project. I'm very happy with it, it's working great! But I'm having a problem following this article [to add custom icons](https://pdfmake.github.io/docs/fonts/icons/).

I can't find my pdfmake directory, or any automatically created gulpfile anywhere. Did I miss something? 

Thank you in advance.

**Comment by liborm85** [comment]
Gulpfile is in pdfmake repo, download and install it.

The whole procedure for generate custom file is described [here](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/).

**Comment by camslice** [comment]
FYI @liborm85 & @neil89 , there doesn't actually seem to be a Gulpfile in the current master branch. You have to download a tagged branch to see it. Not sure if this is intentional or not.

**Comment by liborm85** [comment]
Yes, it's intentional.
