### ISSUE TITLE
how to use pdfmake with ES6?

### ISSUE THREAD

**Issue by stanley85** [bpampuch/pdfmake#1969]
Hi there I am running in circles by now, I've searched the web for examples on this but noone is using this by now with ES6 i guess. When i follow the documentation it should work with require syntax but thats not the case in ES6. So i am stuck on the imports.

This works for me, but the vfs is missing the Roboto font
```import pdfMake from 'pdfmake/build/pdfmake.js';```

I tried adding:
```
import pdfFonts from 'pdfmake/build/vfs_fonts.js';
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

but that is not working stating that 
```'default' is not exported by node_modules\pdfmake\build\vfs_fonts.js```

Please help me on this. I am having quiet a headache after 1 hour on 3 lines ... 
I am using Ionic/stencil webcomponent compiler 1.9.1 if one may ask.

**Comment by stanley85** [comment]
I ended up copying the declaration of the vfs from the vfs_fonts.js to my service ... this works fine -.-
Not the way it should be done but - hey it will never change I guess ...
```
import pdfMake from 'pdfmake/build/pdfmake.js';
pdfMake.vfs = {
    "Roboto-Italic.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAA....",
    "Roboto-Medium.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAA....",
    "Roboto-MediumItalic.ttf": "AAEAAAASAQAABAAgR0RFRrR....",
    "Roboto-Regular.ttf": "AAEAAAASAQAABAAgR0RFRrRCsIIAA...."
};
```

**Comment by meirroth** [comment]
For anyone stumbling upon this issue, here's what worked for me:
```
import pdfMake from 'pdfmake/build/pdfmake'
import * as pdfFonts from 'pdfmake/build/vfs_fonts'
pdfMake.vfs = pdfFonts.pdfMake.vfs
```
