### ISSUE TITLE
white space printed in pdf has half space with the words.

### ISSUE THREAD

**Issue by XiaodongCoding** [bpampuch/pdfmake#1973]
Hi, 
I am converting the string to the pdf format. But looks like the white space only has half of the width of the other characters. 
For example, if I print "a  b", there are 2 white spaces between "a" and "b". However, in the generated pdf, there is only 1 white space in between. This can be reproduced in http://pdfmake.org/playground.html.

Do I miss any configuration? Is there a way to make the white space have the same length with other charachters?
Thanks!

**Comment by liborm85** [comment]
> For example, if I print "a b", there are 2 white spaces between "a" and "b".

I see only one space. Add correct docdefinition example.
