### ISSUE TITLE
Header with table columns?

### ISSUE THREAD

**Issue by naknode** [bpampuch/pdfmake#1974]
Hi, I am using `pdfmake` to _only_ display a `table` for results. I would like to have a the `header` to display the columns on every page using the `header`. Is there a pre-done way to do this or do I have to figure it out on my own?

**Comment by liborm85** [comment]
Table in the header can be used simply:
```js
var dd = {
    header: function(currentPage, pageCount, pageSize) {
        return {
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		};
    },
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```

**Comment by naknode** [comment]
@liborm85 Will that line up with the columns in the body of the table?

**Comment by liborm85** [comment]
No, it is necessary to define tables of ame size in both places.

**Comment by naknode** [comment]
@liborm85 so you can define a table in the header too? And if both headers are the same size... they will line up... no?

**Comment by liborm85** [comment]
If tables are are same size, they will be the same in header and content.

**Comment by naknode** [comment]
@liborm85 Thank you. ONE last thing... it seems like the `border` and `margin` do not apply to header tables? I am trying... but even setting all `border` false and still.. all borders still there.

**Comment by naknode** [comment]
@liborm85 I see. But the columns are not lining up.. it seems the headers and body content are on a different margin/padding? how do I fix this so they line up?

![Screen Shot 2020-05-07 at 12 00 48 PM](https://user-images.githubusercontent.com/616320/81323167-90432f80-905a-11ea-95ae-66fdd7cff63f.png)

**Comment by liborm85** [comment]
Header is all content above the top of the page, use `margin` to move table.

**Comment by naknode** [comment]
Thank you.
