### ISSUE TITLE
Unable to display Image from server URL after PDF creation. 

### ISSUE THREAD

**Issue by vnanaware** [bpampuch/pdfmake#1975]
I am Using live server url of Image in my React Js code when I click download PDF button. PDF downloaded but unable to display image. Any Help, 

Thanks in advance.

**Comment by liborm85** [comment]
Add runnable example for reproduce issue.

**Comment by vnanaware** [comment]
import React, { Component } from 'react';


import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';
import AdmitCardLogo from '../images/AdmitCardLogo.png';
import ProfilePhoto from '../images/Student-Profile.png';
import Typography from '@material-ui/core/Typography';

class AdmitCard extends Component {
    state={
        basicDetail:[{
                key:'Roll Number :',
                value:'194738782',
                Photo: ProfilePhoto,
            },
        ],
            basicDetailName:[{
                key: 'Name',
                value: 'Jonsan Robart Mankin',
            },
        ],
        SubjectObted:[{
            key: 'Subject Opted',
            value: 'PH',
            value1: 'CH',
            value2: 'MH',
        },
    ],
    SubjectDetails:[{
        key: 'SUBJECT',
        key1: 'DATE & TIME',
        key2: 'SIGNATURE OF CANDIDATE',
    },],
    CandidateDetails:[{

    },],
    subTime:[{
        key: 'PHYSICS (PY)',
        value: '17-06-2020 1PM to 2PM',
        sign: '',
    },],
    subTime1:[{
        key: 'CHEMESTRY (CH)',
        value: '18-06-2020 1PM to 2PM',
        sign: '',

        key1: 'MATHEMATICS (MA)',
        value1: '19-06-2020 1PM to 2PM',
        sign1: '',
    },],
    subTime2:[{
        
    },],
    }


    render() {
        return (
            <div>
                

                <div style={{padding:10}}>
                    <TableContainer component={Paper} style={{width: '100%', maxWidth: 1160, margin: 'auto', overflow: 'Hidden',}}>
                        <Table className={AdmitCard.table} aria-label="simple table">
                            
                            <TableRow>
                                <TableCell className="tableHead" colSpan="2">
                                    <img src={AdmitCardLogo} style={{width: 160,}} alt="Logo"/>
                                </TableCell>
                                <TableCell className="tableHead" colSpan="4">
                                    <span style={{fontSize: 20, color: '#000000',}}> GOVERNMENT OF GOA </span> <br /> 
                                    <span style={{color: '#414141'}}>DIRECTORATE OF TECHNICAL EDUCATION, GOA STATE </span><br />
                                    <span style={{fontSize: 16, color: '#414141'}}>DTE BUILDING, ALTO-PORVORIM, BARDEZ, GOA, PIN 403521. </span> <br />
                                    <span style={{fontSize: 20, color: '#414141'}}> CENTER: 15 Goa Board of Secondary and Higher Secondary Education <br /> MAPUSA</span> <br /> 
                                </TableCell>
                            </TableRow>

                            <TableBody>

                                {/*////////// Photo ///////////*/}
                                {
                                    this.state.basicDetail.map((item,index)=>{

                                        if (index === 0)
                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2" align="center"><img style={{width: 180,}} src="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"/></TableCell>
                                                    
                                                    <TableRow >
                                                        <TableCell component="th" colSpan="2"><strong>{item.key}</strong></TableCell>
                                                        <TableCell align="left" colSpan="5">{item.value}</TableCell>
                                                        
                                                    </TableRow>
                                                    
                                                    
                                                    {
                                                        this.state.basicDetailName.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{height: 40,}}><strong>{item.key}</strong></TableCell>
                                                                    <TableCell align="left" colSpan="5">{item.value}</TableCell>
                                                                </TableRow>
                                                                
                                                            </>)
                                                        })
                                                    }

{
                                                        this.state.SubjectObted.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "13%"}}><strong>{item.key}</strong></TableCell>
                                                                    <TableCell align="left" colSpan="2" style={{width: "13%"}}>{item.value}</TableCell>
                                                                    <TableCell align="left" style={{width: "14%"}} colSpan="2" >{item.value1}</TableCell>
                                                                    <TableCell align="left" style={{width: "14%"}} colSpan="2">{item.value2}</TableCell>
                                                                </TableRow>
                                                                
                                                                <TableRow align="center" style={{width: "100%",}}>
                                                                    
                                                                    <TableCell component="th" align="center"  colSpan="7" rowSpan="2" style={{fontSize: 22}}>Attendance</TableCell>
                                                                   
                                                                </TableRow>
                                                            </>)
                                                        })
                                                    }


                                                </TableRow></>)
                                        }
                                         
                                    })   
                                }


                                {/*////////// Seal ///////////*/}
                                {
                                    this.state.SubjectDetails.map((item,index)=>{

                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2" align="center">Seal</TableCell>
                                                    
                                                    <TableRow align="center">
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key}</strong></TableCell>
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key1}</strong></TableCell>
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key2}</strong></TableCell>
                                                    </TableRow>
                                                    
                                                    
                                                    {
                                                        this.state.subTime.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.key}</TableCell>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.value}</TableCell>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.sign}</TableCell>
                                                                </TableRow>
                                                                
                                                            </>)
                                                        })
                                                    }

                                                    

                                                </TableRow></>)
                                        }
                                         
                                    })   
                                }   



                                {/*////////// cANDIDATE sIGNATURE ///////////*/}
                                {
                                    this.state.CandidateDetails.map((item,index)=>{

                                        if (index === 0)
                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2"  align="center">Candidate Signature</TableCell>
                                                    
                                                    {
                                                        this.state.subTime1.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "20%",textAlign: "center"}}>{item.key}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.value}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.sign}</TableCell>
                                                                </TableRow>

                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.key1}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.value1}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.sign1}</TableCell>
                                                                </TableRow> 
                                                                
                                                            </>)
                                                        })
                                                    }

                                                    
                                                </TableRow></>)
                                        }
                                         
                                    })    
                                }

                                

                                <TableRow>
                                    <TableCell colSpan="7">
                                        THIS CARD WITH BE REQUIRED
                                    </TableCell>
                                </TableRow>

                                

                            </TableBody>
                        </Table>
                    </TableContainer>
                </div>
            </div>
        );
    }
}

export default AdmitCard;

**Comment by liborm85** [comment]
I don't see any use of pdfmake there. How is it related to pdfmake?

**Comment by vnanaware** [comment]
Ohh sorry that was wrong 


import React, { Component } from 'react';


import Table from '@material-ui/core/Table';
import TableBody from '@material-ui/core/TableBody';
import TableCell from '@material-ui/core/TableCell';
import TableContainer from '@material-ui/core/TableContainer';
import TableHead from '@material-ui/core/TableHead';
import TableRow from '@material-ui/core/TableRow';
import Paper from '@material-ui/core/Paper';
import AdmitCardLogo from '../images/AdmitCardLogo.png';
import ProfilePhoto from '../images/Student-Profile.png';
import Typography from '@material-ui/core/Typography';
import Sign from '../images/sign.png';

import { Button } from '@material-ui/core';
import html2canvas from "html2canvas";
import pdfMake from "pdfmake";

class AdmitCard extends Component {

    // Generate the pdf based on a component
    printToPdf = () => {
        html2canvas(document.getElementById("print_to_pdf")).then(canvas => {
            var data = canvas.toDataURL();
            var pdfExportSetting = {
            content: [
                {
                    image: data,
                    width: 500,
                    style: { fontSize: 20 }
                }
            ]
        };

        pdfMake.createPdf(pdfExportSetting).download("AdmitCard.pdf");
    });
  };


    state={
        basicDetail:[{
                key:'Roll Number :',
                value:'194738782',
                Photo: ProfilePhoto,
            },
        ],
            basicDetailName:[{
                key: 'Name',
                value: 'Jonsan Robart Mankin',
            },
        ],
        SubjectObted:[{
            key: 'Subject Opted',
            value: 'PH',
            value1: 'CH',
            value2: 'MH',
        },
    ],
    SubjectDetails:[{
        key: 'SUBJECT',
        key1: 'DATE & TIME',
        key2: 'SIGNATURE OF CANDIDATE',
    },],
    CandidateDetails:[{

    },],
    subTime:[{
        key: 'PHYSICS (PY)',
        value: '17-06-2020 1PM to 2PM',
        sign: '',
    },],
    subTime1:[{
        key: 'CHEMESTRY (CH)',
        value: '18-06-2020 1PM to 2PM',
        sign: '',

        key1: 'MATHEMATICS (MA)',
        value1: '19-06-2020 1PM to 2PM',
        sign1: '',
    },],
    subTime2:[{
        
    },],
    }


    render() {
        return (
            <div>

                <div align="center" style={{margin: 10}}>
                    <Button
                        onClick={this.printToPdf}
                        style={{ backgroundColor: "green",color: "#ffffff", borderRadius: 4, fontSize: 14 }}
                    >
                    Print It
                    </Button>
                </div>

                <span id="print_to_pdf">

                <div style={{ paddingTop: 20, paddingBottom: 70 }}>
                    <TableContainer component={Paper} style={{width: '100%', maxWidth: 1160, margin: 'auto', overflow: 'Hidden',}}>
                        <Table className={AdmitCard.table} aria-label="simple table">
                            
                            <TableRow>
                                <TableCell className="tableHead" colSpan="2">
                                    <img src={AdmitCardLogo} style={{width: 160,}} alt="Logo"/>
                                </TableCell>
                                <TableCell className="tableHead" colSpan="4">
                                    <span style={{fontSize: 16, color: '#414141', textAlign: "center"}}> GOVERNMENT OF GOA </span> <br /> 
                                    <span style={{color: '#000000', textAlign: "center", fontSize: 22}}>DIRECTORATE OF TECHNICAL EDUCATION, GOA STATE </span><br />
                                    <span style={{fontSize: 14, color: '#414141', textAlign: "center"}}>DTE BUILDING, ALTO-PORVORIM, BARDEZ, GOA, PIN 403521. </span> <br />
                                    <span style={{fontSize: 20, color: '#000000', textAlign: "center"}}> <strong>CENTER:</strong> 15 Goa Board of Secondary and Higher Secondary Education <br /> MAPUSA</span> <br /> 
                                </TableCell>
                            </TableRow>

                            <TableBody>

                                {/*////////// Photo ///////////*/}
                                {
                                    this.state.basicDetail.map((item,index)=>{

                                        if (index === 0)
                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2" align="center"><img style={{width: 180,}} src="https://www.gravatar.com/avatar/205e460b479e2e5b48aec07710c08d50"/></TableCell>
                                                    
                                                    <TableRow >
                                                        <TableCell component="th" colSpan="2"><strong>{item.key}</strong></TableCell>
                                                        <TableCell align="left" colSpan="5">{item.value}</TableCell>
                                                        
                                                    </TableRow>
                                                    
                                                    
                                                    {
                                                        this.state.basicDetailName.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{height: 40,}}><strong>{item.key}</strong></TableCell>
                                                                    <TableCell align="left" colSpan="5">{item.value}</TableCell>
                                                                </TableRow>
                                                                
                                                            </>)
                                                        })
                                                    }

{
                                                        this.state.SubjectObted.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "13%"}}><strong>{item.key}</strong></TableCell>
                                                                    <TableCell align="left" colSpan="2" style={{width: "13%"}}>{item.value}</TableCell>
                                                                    <TableCell align="left" style={{width: "14%"}} colSpan="2" >{item.value1}</TableCell>
                                                                    <TableCell align="left" style={{width: "14%"}} colSpan="2">{item.value2}</TableCell>
                                                                </TableRow>
                                                                
                                                                <TableRow align="center" style={{width: "100%",}}>
                                                                    
                                                                    <TableCell component="th" align="center"  colSpan="7" rowSpan="2" style={{fontSize: 22}}>Attendance</TableCell>
                                                                   
                                                                </TableRow>
                                                            </>)
                                                        })
                                                    }


                                                </TableRow></>)
                                        }
                                         
                                    })   
                                }


                                {/*////////// Seal ///////////*/}
                                {
                                    this.state.SubjectDetails.map((item,index)=>{

                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2" align="center">Seal</TableCell>
                                                    
                                                    <TableRow align="center">
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key}</strong></TableCell>
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key1}</strong></TableCell>
                                                        <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}><strong>{item.key2}</strong></TableCell>
                                                    </TableRow>
                                                    
                                                    
                                                    {
                                                        this.state.subTime.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.key}</TableCell>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.value}</TableCell>
                                                                    <TableCell component="th" colSpan="2" style={{width: "9%", textAlign: "center"}}>{item.sign}</TableCell>
                                                                </TableRow>
                                                                
                                                            </>)
                                                        })
                                                    }

                                                    

                                                </TableRow></>)
                                        }
                                         
                                    })   
                                }   



                                {/*////////// cANDIDATE sIGNATURE ///////////*/}
                                {
                                    this.state.CandidateDetails.map((item,index)=>{

                                        if (index === 0)
                                        {
                                            return(<> 
                                                <TableRow>
                                                    <TableCell component="th" colSpan="2"  align="center" style={{verticalAlign: "bottom"}}><img src={Sign} style={{width: 150, height: 25,}} alt="Logo"/><br />Candidate Signature</TableCell>
                                                    
                                                    {
                                                        this.state.subTime1.map((item,index)=>{   
                                                            return(<>                                                                             
                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "20%",textAlign: "center"}}>{item.key}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.value}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.sign}</TableCell>
                                                                </TableRow>

                                                                <TableRow>
                                                                    <TableCell component="th" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.key1}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.value1}</TableCell>
                                                                    <TableCell component="th" align="left" colSpan="2" style={{width: "20%", textAlign: "center"}}>{item.sign1}</TableCell>
                                                                </TableRow> 
                                                                
                                                            </>)
                                                        })
                                                    }

                                                    
                                                </TableRow></>)
                                        }
                                         
                                    })    
                                }

                                

                                <TableRow>
                                    <TableCell colSpan="7">
                                        THIS CARD WITH BE REQUIRED
                                    </TableCell>
                                </TableRow>

                                

                            </TableBody>
                        </Table>
                    </TableContainer>
                </div>
                </span>
            </div>
        );
    }
}

export default AdmitCard;

**Comment by liborm85** [comment]
From html2canvas is created image after is permision resolved. And before that a pdf is generated.

**Comment by vnanaware** [comment]
Is there any code example?

**Comment by liborm85** [comment]
It's based on your example. You have to do everything pdfmake code in html2canvas success promise.
