### ISSUE TITLE
PDF doesn't open when too many images

### ISSUE THREAD

**Issue by fraeez** [bpampuch/pdfmake#1980]
The PDF doesn't display when there is too many images. I've created a fiddle, juste copy paste it into the playground: https://jsfiddle.net/fraeez/7eL8josg/latest/

If you delete 2 or 3 images randomly, the PDF shows up. 

I didn't find any created bug related to that issues. Does anyone know how to fix this?

Thanks,

Tell me if you need more information

**Comment by liborm85** [comment]
I do not see any problem. I normally opened the generated pdf file in Acrobat Reader and Google Chrome.

**Comment by fraeez** [comment]
That's might be related to my Chrome version. The preview doesn't show on my screen, but others operations (print, open, download) are working. I'm on Chrome 81.0.4044.138 

![image](https://user-images.githubusercontent.com/17552332/82429625-84109680-9a8c-11ea-9a7f-61e386e561b1.png)

So it's not related to the framework but it's something with the Chrome viewer I guess. Well, in my app I w'ont use the viewer anymore and direclty download the file.

**Comment by liborm85** [comment]
This is only a preview, the browser probably can't display it; after download it can open properly.

**Comment by fraeez** [comment]
OK I'm closing this as it related to the browser. Thanks liborm
