### ISSUE TITLE
content too long then PdfPrinter.createPdfKitDocument error

### ISSUE THREAD

**Issue by pangshunlong** [bpampuch/pdfmake#1985]
docDefinition  content too long then PdfPrinter.createPdfKitDocument error

---
printer.createPdfKitDocument(docDefinition)
---

You have triggered an unhandledRejection, you may have forgotten to catch a Promise rejection:
TypeError: Cannot read property 'length' of undefined

**Comment by liborm85** [comment]
Attach example for reproduce issue.

**Comment by pangshunlong** [comment]
Sorry, the problem lies in the body format of the table. It can't be an empty array, but an array set corresponding to the column vertical.

**Comment by pangshunlong** [comment]
> Attach example for reproduce issue.

The problem has been solved.Thank you very much.
