### ISSUE TITLE
Problems with a Google Font

### ISSUE THREAD

**Issue by JesusVoltage** [bpampuch/pdfmake#1986]
Hi mates, we have some troubles using this google font since client side
https://fonts.google.com/specimen/Noto+Sans+HK?query=noto+sans+HK.

we miss some letters in our document, this is ramdon.

i add a capture of the problem

https://drive.google.com/file/d/1QakvSaYeCNOcnU4s-kiJBrvUPUrogaOf/view?usp=sharing

**Comment by liborm85** [comment]
Attach example of doc definition for reproduce issue.

**Comment by rafolmo** [comment]
Same problem by there.
