### ISSUE TITLE
pageBreakBefore performance for bigger documents

### ISSUE THREAD

**Issue by Kissema** [bpampuch/pdfmake#1989]
I'm using `"pdfmake": "^0.1.65"` and when i'm trying to generate a bigger pdf with **`pageBreakbefore` function its takes more than 2 hours** but when i use the similar logic with **`pageBreak` (`after`, `before` or null) its takes less then 5 minutes**. 

So, i think that the [#11718](https://github.com/bpampuch/pdfmake/pull/1718) don´t solves all performances problems. Cause the parameters of this function `pageBreakBefore` can receive bigger arrays elements. 

I think that for solve this must be changed the concept logic.
I recomend for the bigger documents to use `pageBreak` until solved this issue

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1410
