### ISSUE TITLE
pageReference doesn't seem to be working

### ISSUE THREAD

**Issue by linduff** [bpampuch/pdfmake#1991]
Hello,
I am trying to use pageReference to reference a paragraph on another page in my pdf. I ran it in the pdfMake playground, and it seems to be working fine, but on my local machine with the same setup, nothing gets returned in the text block. 

Is there something I need to import to make it work?

I am running version 0.1.37.

Thanks!

**Comment by liborm85** [comment]
Update to the latest version.
