### ISSUE TITLE
Header disappears when pageMargin is set to 0

### ISSUE THREAD

**Issue by 0xC0DEBA5E** [bpampuch/pdfmake#1992]
When I set pageMargins to `pageMargins: [0, 0, 0, 0]`, the header in the generated PDF disappears.
I found no way to make it visible again. I need to set margins to zero, because I want to create an "pixel perfect" PDF.

I created a jsfiddle for testing: [https://jsfiddle.net/y3s7btna/3/](https://jsfiddle.net/y3s7btna/3/)

Alternatively, here's the code from the fiddle:
```javascript
const documentDefinition = {
    pageSize: 'A4',
    pageOrientation: 'landscape',
    // uncomment the following line to see the header disappear
    // pageMargins: [0, 0, 0, 0], // [left, top, right, bottom]
    pageMargins: 20,
    header: [{
        text: 'This is a header',
        margin: 5
      }
    ],
    content: [{
      text: 'Content',
      margin: 10
    }]
  };

  pdfMake.createPdf(documentDefinition).download('testdoc.pdf');
```

**Comment by liborm85** [comment]
Header area size is defined by `pageMargins`. If you have `pageMargins` 0, then header is not visible. Increase pageMargins.
