### ISSUE TITLE
Table missing borders

### ISSUE THREAD

**Issue by marcelmu** [bpampuch/pdfmake#1993]
My goal is to render a table with borders just around a specifc cell.

On the pdfmake playground, my definition works as expected:
![image](https://user-images.githubusercontent.com/19172755/83632458-9831b900-a59f-11ea-97ff-07b535b3a7b1.png)

However, the same definition is breaking in my application:
![image](https://user-images.githubusercontent.com/19172755/83632573-ce6f3880-a59f-11ea-9825-b33ba4eb7aa4.png)

The part of the definition:
```
[
            {
              text: 'Summe in USD:',
              border: [
                false,
                false,
                false,
                false
              ],
              style: 'tableContent',
              alignment: 'right'
            },
            {
              text: '2500 USD',
              style: 'tableContent',
              alignment: 'right',
              border: [
                true,
                true,
                true,
                true
              ]
            },
            {
              text: '',
              border: [
                false,
                false,
                false,
                false
              ]
            }
          ],
```
The style 'tableContent' is just setting the fontSize

**Comment by liborm85** [comment]
Update to latest pdfmake.

**Comment by marcelmu** [comment]
Sorry, but I have already updated to the latest 0.1.65. 
Still having the issue

**Comment by liborm85** [comment]
When it works on playground and not in your code, then you can't have latest 0.1.65 version
