### ISSUE TITLE
Inline Style for Textcolors

### ISSUE THREAD

**Issue by stanley85** [bpampuch/pdfmake#1994]
I have a single line of text that is in one color styled by now. If I split up the text with different styles for each segment I end up with a new line for each segment. Is it possible to get inline styles of some sort? Maybe {display: inline} to avoid linebreaks? I have several names seperated by komma and need to highlight one or two of these without having a vertical list of names ... any help appreciated.

**Comment by liborm85** [comment]
Yes, it is possible. Described in [documentation](https://pdfmake.github.io/docs/document-definition-object/styling/).

Simple example:
```js
var dd = {
  content: [
    {
      text: [
        'Text ',
        {text: 'Text ', color: 'red'},
        {text: 'Text ', color: 'green'},
        {text: 'Text ', color: 'blue'},
      ]
    }
  ]
};
```
