### ISSUE TITLE
Cross Table or intelligente table

### ISSUE THREAD

**Issue by alexjesjimalex** [bpampuch/pdfmake#1996]
hi @bpampuch, i have a question about your library, can i create a crosstab like Crystal Report o do you have any advice about how i do it?

**Comment by liborm85** [comment]
I don't know what exactly should be in table Crystal Report, but in pdfmake table is supported. All documentation is available [here](https://pdfmake.github.io/docs/), examples [here](http://pdfmake.org/playground.html) and [here](https://github.com/bpampuch/pdfmake/tree/0.1/examples).

**Comment by alexjesjimalex** [comment]
@liborm85 sorry about time, but what i mean is about your library can make pivot table o some kind of intelligent table to manage 
to handle columns that grow automatically for the right depending on the information injected by  API, here you have and example:

https://ej2.syncfusion.com/angular/documentation/pivotview/grouping-bar/

I honestly like to work more with your library and easy and agile, but I have that question if you can do something similar to the link using your library, I appreciate your time and support.

regards

**Comment by liborm85** [comment]
pdfmake  only allows creation of tables. No calculations, grouping, etc. over table data does not support. You can perform calculations and groupings outside and and to pdfmake pass table with result
