### ISSUE TITLE
How do I create a bottom border on each page's last row

### ISSUE THREAD

**Issue by bjmfransen** [bpampuch/pdfmake#1997]
I am creating invoices with pdfmake (client side), showing individual expense lines in a table. Horizontal borders for this table are at the top and bottom of the single header row, and at the bottom of the table. However, if the table stretches to a second page, there is no bottom border on the first page. Which makes sense but doesn't look great.

How do I go about creating a bottom border on the table's last row for each page?

**Comment by CanadaViet** [comment]
I have the same problem that need to be resolve

**Comment by liborm85** [comment]
Feature request here: https://github.com/bpampuch/pdfmake/issues/620
