### ISSUE TITLE
Line separator

### ISSUE THREAD

**Issue by przemyslaw** [bpampuch/pdfmake#2]
A good feature would be the ability to insert a horizontal line as a separator on this content from the rest of the document. This line can be modife. 
This line could be modified by specifying the width(i.e. in %) of the page in the document.
:)

**Comment by credli** [comment]
+1

**Comment by jthoenes** [comment]
Please use vectors for this:

````
{canvas: [{ type: 'line', x1: 0, y1: 5, x2: 595-2*40, y2: 5, lineWidth: 3 }]}
````

**Comment by rebelholic** [comment]
@jthoenes I guess you should add documentation about this feature.

**Comment by infacq** [comment]
1+

**Comment by brianmgray** [comment]
@jthoenes if I want to use vectors for an horizontal rule effect, can you provide guidance on how I would incorporate this as an element if I don't know exactly where it will be on the page? Say for example I have this:

```
"content": [
    {
      "text": [
        {
          "text": "COMPLETE: ",
          "style": "strong"
        },
        "Some text"
      ]
    },
    {
        canvas: [ {
             type: 'line', 
             x1: [in line with the page/column margins], y1: beneath that text], 
             x2: [in line with the page/column margins], y2: beneath that text],
             lineWidth: 0.5
        } ]
    }
    {
      "text": [
        {
          "text": "COMPLETE: ",
          "style": "strong"
        },
        "Some more text"
      ],
    {
        canvas: [ {
             type: 'line', 
             x1: [in line with the page/column margins], y1: beneath that text], 
             x2: [in line with the page/column margins], y2: beneath that text],
             lineWidth: 0.5
        } ]
    }
  ]
```

**Comment by jthoenes** [comment]
The canvas element should be place relative to the text. Doesn't it? What are you trying to achieve?

**Comment by brianmgray** [comment]
@jthoenes 

Below is a sample to run in the playground.

I am using pdf-make in a larger application where we generate many PDFs. So I have code that builds the pdf-make document object. Some of our PDFs use horizontal rules to space out elements. But there might be one across the whole page, and another between two elements in a single column. 

I cannot find a way in pdf-make to build a horizontal line that says "take up 100% of the available space." i.e. If I am in the root of content, take up the page width minus margins. If I am in a column, take up the column width, and so forth.

````
var dd = {
  "pageOrientation": "portrait",
  "pageSize": "LETTER",
  "content": [
    {
      "text": [
        {
          "text": "Some Text: ",
          "style": "strong"
        },
        "The line below will be full width"
      ]
    },
    {
        canvas: [
            {
                type: 'line',
                x1: 0,
                y1: 5,
                x2: 535,
                y2: 5,
                lineWidth: 0.5
            }
        ]
    },
    {
        columns: [
            'But what if there is a column?',
            {
                stack: [
                    'Ideally this line would be below just the text',
                    {
                         canvas: [
                            {
                                type: 'line',
                                x1: 0,
                                y1: 5,
                                x2: 250,
                                y2: 5,
                                lineWidth: 0.5
                            }
                        ]
                    }
                ]
            }
        ]
    }
  ]
}
````

**Comment by jthoenes** [comment]
I don't see a way to do this without hacking it into the document context inside pdfmake itself. It's currently the only place you could find out how much space is available horizontally.

**Comment by brianmgray** [comment]
Ok gotcha.

For now, I am working out a way given that I have experimentally figured out how long the full width is. So I am passing in the number of columns and dividing that width. We'll see how it looks.

Not sure how much work it would be to add a line / separator type that has maybe a thickness and a width. Then a '100%' width would work how the tables do (which themselves can be nested in all the other elements).

Thanks!

**Comment by brianmgray** [comment]
@jthoenes FYI works pretty well actually just dividing by the number of columns, and you are correct it does display relative to its position.

**Comment by ottigerb** [comment]
I have created the following function: `514` seems to fit for `A4`.

```JS
d.horizontalLine = function(width_percent) {
        width_percent = width_percent === undefined ? 100 : width_percent;

        var length = 514 / 100 * width_percent;

        var return_obj = {
            "margin": [0, 12, 0, 0],
            "canvas": [{
                "type": "line",
                "x1": 0,
                "y1": 0,
                "x2": length,
                "y2": 0,
                "lineWidth": 0.5,
                "lineColor": "#BDBDBD"
            }]
        };

        return return_obj;
    };
```

Maybe this is helpful for someone.  :-)

**Comment by selmo47** [comment]
For the <hr>, you can do it with canvas.
take a look on : 
[https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js](url)

**Comment by asadullakkh** [comment]
> +1 for this. Great library.
> 
> Also, I am creating the horizontal lines by creating a table with a custom layout. Here is the code:
> 
> ```
> {
>     table: {
>             widths: ['*'],
>             body: [[" "], [" "]]
>     },
>     layout: {
>         hLineWidth: function(i, node) {
>             return (i === 0 || i === node.table.body.length) ? 0 : 2;
>         },
>         vLineWidth: function(i, node) {
>             return 0;
>         },
>     }
> },
> ```

thank you, it works for me)

**Comment by testerez** [comment]
Here is the simple function I use, in case it helps:
```ts
export const hr = ({
  color,
  lineWidth,
}: {
  color?: string
  lineWidth: number
}): ContentCanvas => ({
  canvas: [
    {
      type: 'line',
      x1: 0,
      y1: 0,
      x2: 595 - 2 * 40,
      y2: 0,
      lineWidth,
      lineColor: color,
    },
  ],
})

```

**Comment by vivek-andani** [comment]
if want to add after header in pdfMake than can add by this method 
 header : [ 
          {
          columns: [
            { 
              stack:[
                [ {image: 'this.logoUrl', fit: [80, 80], alignment: 'center',width: '25%' ,margin: [0, 0, 0, 0]},
            ]
              ]
          },
            {
              stack: [
                [`Name: ${ this.profiledata.displayName}`],
                [`Address: ${ this.profiledata.address}`],
                {
                  canvas: [
                     {
                         type: 'line',
                         x1: -110,
                         y1: 5,
                         x2: 250,
                         y2: 5,
                         lineWidth: 0.5
                     }
                 ]
                }
              ],
              
              alignment: 'center',
              width: '40%' ,
              style: 'tableText',
              margin: [0, 5, 0, 0],
              
            },
            {
              stack: [
                [`Email: ${ this.profiledata.email}`],
                [`Phone: ${ this.profiledata.phone_number}`],
                {
                  canvas: [
                     {
                         type: 'line',
                         x1: 0,
                         y1: 5,
                         x2: 180,
                         y2: 5,
                         lineWidth: 0.5
                     }
                 ]
                }
              ],
              alignment: 'left',
              width: '35%' ,
              style: 'tableText',
              margin: [0, 5, 0, 0],
            },
          ], 
        }         
        ],

**Comment by vivek-andani** [comment]
Add line above the footer



footer : function (currentPage, pageCount) {
          return {
            columns: [
              {
                stack:[
                  {
                    canvas: [
                      {
                          type: 'line',
                          x1: 0,
                          y1: 5,
                          x2: 520,
                          y2: 5,
                          lineWidth: 0.5
                      }
                  ]
                  },
                  [ 
                    {
                        columns:[
                        [
                          {text:`Date:${currentDate}`,alignment:'left'}
                        ],
                        [
                          {text:`Page ${currentPage.toString()} of ${pageCount}`,alignment:'right'}
                        ]
                      ]
                    }
                  ], 
                ],
               
            },
         
            ],
            margin: [40, 0],
            alignment : 'center'
          };
        },

**Comment by bgmort** [comment]
@guzmonne's solution worked great for me. Here it is encapsulated into a Typescript function:

```ts
import { Content, TDocumentDefinitions } from 'pdfmake/interfaces'

const hr = (width = 1, lineHeight = 0.25): Content => (
  {
    table: {
      widths: ['*'],
      body: [[' '], [' ']]
    },
    lineHeight,
    layout: {
      hLineWidth: (i, node) => (i === 0 || i === node.table.body.length) ? 0 : width,
      vLineWidth: () => 0
    }
  }
)
```
or, plain Javascript:
```js
const hr = (width = 1, lineHeight = 0.25) => (
  {
    table: {
      widths: ['*'],
      body: [[' '], [' ']]
    },
    lineHeight,
    layout: {
      hLineWidth: (i, node) => (i === 0 || i === node.table.body.length) ? 0 : width,
      vLineWidth: () => 0
    }
  }
)
```
