### ISSUE TITLE
Custom File name

### ISSUE THREAD

**Issue by YidingW** [bpampuch/pdfmake#200]
I am wondering where can I specify the default file name for the user when download a pdf file?

**Comment by jthoenes** [comment]
Hi, I'm not sure in which situation you want to specify the name. Could you be more precise?

**Comment by YidingW** [comment]
Hi jthoenes, 

My question was how to specify the file name when download the pdf. For example, 
                ```pdfMake.createPdf(docDefinition).download(); ```
Where should I specify the file name? 

I should read the source code a little bit before asking this question. Turns out I can define the name like:                `` `pdfMake.createPdf(docDefinition).download(FILENAME);```

And the downloaded pdf should named as FILENAME.pdf

**Comment by YidingW** [comment]
This issue can be closed but I suggest to add it to the document.
