### ISSUE TITLE
Gulp build for fonts needs to be updated

### ISSUE THREAD

**Issue by rachelleahr** [bpampuch/pdfmake#2000]
I used the current gulp file to build a vfs_fonts.js file and it would not work with the current version of pdfmake. The vfsBefore and vfsAfter just needs to be updated to match what the expected file should look like.
Should be pretty simple and I can create a pr if needed.

Additionally it added an extra "77u/" (byte code for utf-8) in front of the fonts that were built that caused them to be read wrong - for anyone else that has an issue adding custom fonts this might be helpful.

**Comment by rachelleahr** [comment]
Never mind I see that it's updated in the latest release but I had downloaded master and it wasn't updated there. Maybe add that to the documentation that you need to download from the latest releases and not master?

**Comment by liborm85** [comment]
In readme is this text:

![image](https://user-images.githubusercontent.com/1298652/84569167-b4dea580-ad84-11ea-8d21-03dd70820b7a.png)
