### ISSUE TITLE
Dynamic data in nested table using pdfmake. It shold print in PDF as shown in screen shot

### ISSUE THREAD

**Issue by jclindia** [bpampuch/pdfmake#2002]
I have this strcturure 
![image](https://user-images.githubusercontent.com/26209751/84569313-32191300-ada3-11ea-816d-8132b53f3762.png)
data :{ 
class_name:
section_name:
day_lines:  [
{day_name: Monday,
period_line: [
{period_name,subject_name}
]}]}
ANy help is higly appreciable. Thanking you

**Comment by liborm85** [comment]
Yes, tables can be created using pdfmake.
Pdfmake documentation is available [here](https://pdfmake.github.io/docs/), examples are [here](http://pdfmake.org/playground.html) and [here](https://github.com/bpampuch/pdfmake/tree/0.1/examples).

**Comment by jclindia** [comment]
That i seen but those example are for static data. I am unable to assign data dynamically using some loop etc..share some light would be great.

**Comment by liborm85** [comment]
pdfmake `docDefinition` is standard [JavaScript JSON](https://www.w3schools.com/js/js_json.asp), specifically for tables cells (row/column) is array and therefore for dynamic generation you can use [array `push()` method](https://www.w3schools.com/jsref/jsref_push.asp) or anything else from javascript. Code for dynamic generation depends on data structure.

**Comment by jclindia** [comment]
Thanks for prompt response. Issue Is with nesting table.. Since each have different  set header and data...let me try. Mean while can you guide to see some sample code it will be easy to understand. For simple tabular format i dont hv issue. Only nesting one facing issue

**Comment by liborm85** [comment]
I don't know what the table should look like. I don't see the need for nested tables in the screenshot (although the use is exactly the same).
Attach your code for prepare PDF docDefinition.

**Comment by jclindia** [comment]
pdfmakereport1() {
  pdfMake.vfs = pdfFonts.pdfMake.vfs;
  const ddate =  new Date();
  const dddate = ddate.toLocaleDateString('en-US');
  const rn =this.storageService.getResourceNumber();
  const cn = this.storageService.getCompanyName();
  const ln = this.storageService.getLocationName();
  const academic_session = this.clientAddForm.value.academic_session;
  let servicerows = [];
  const theader = [];
  let tbody=[];
  const headerFillColor='#00BFFF';
  const bodyFillColor='#FFFFFF';
    theader.push({width:'auto',text:'Day Name',fontSize:14,fillColor:headerFillColor});
  let sess='';
    this.clientService.getFlatData(this.tablename, academic_session,1).then(respflatdata => {
      this.flatdata = respflatdata;
      console.log('serv data',this.flatdata);
      this.flatdata[0]['data'].schedule_lines[0]['section_lines'].forEach(ssl => {
        theader.push({width:'auto',text:ssl.period_name,fontSize:14,fillColor:headerFillColor});
      });

      for(let i=0; i< this.flatdata.length; i++)  {
        let sh =0;
        sess=this.flatdata[i]['data'].academic_session;
        this.flatdata[i]['data'].schedule_lines.forEach(sch => {
          const rarr=[];
          rarr.push({width:'auto',text:sch.day_name,fontSize:12,fillColor:bodyFillColor});
          // rarr.push(sch.day_name,);
          this.flatdata[i]['data'].schedule_lines[sh]['section_lines'].forEach(ssl => {
            if (ssl.period_name !=='**') {
              rarr.push({width:'auto',text:ssl.subject_name,fontSize:12,fillColor:bodyFillColor});
          }
          });
          tbody.push(rarr);
          sh++;
      });
      }
  console.log('header=',theader);
  console.log('body=',tbody);
  setTimeout(function() { }, 1000);
  const dd = {
    // Here you put the page settings as your footer, for example:
              footer: function(currentPage, pageCount) {
                  return [
                    {
                      text:
                        currentPage.toString() +
                        ' of ' +
                        pageCount +
                        '\n' +
                        'Printed by:'+rn,
                      alignment: currentPage ? 'center' : 'center'
                    }
                  ];
                },
    // here you can have header
              header: function() {
                return [
                  {
                    text: cn,
                    fontSize: 14,
                    bold: true,
                    alignment: 'center'
                  },
                  {
                    text: ln,
                    fontSize: 12,
                    bold: true,
                    alignment: 'center'
                  },
                  {
                    text: 'Print Date:'+dddate,
                    fontSize: 12,
                    bold: true,
                    alignment: 'center'
                  },
                ];
              },
    // Here you can enter the page size and orientation:
              pageSize: 'A4',
              // pageOrientation: 'Portrait',
              pageOrientation: 'Landscape',
              pageMargins: [40, 80, 40, 40],
    // in pageOrientation you can put "Portrait" or "landscape"
    // start the body of your impression:
            content: [
                        {
                          text: 'Session:  '+ this.flatdata[0]['data'].academic_session
                          +'  Term:  '+this.flatdata[0]['data'].academic_term
                          +'  Class Name:  '+ this.flatdata[0]['data'].class_name
                          +'  Section Name:  '+this.flatdata[0]['data'].section_name,
                          fontSize: 14,
                          bold: true,
                          alignment: 'center'
                        },
                        {
                          table: {
                            header: theader,
                            body:tbody
                          }
                        }
            ],
          };
          const mytableLayouts = {
            exampleLayout: {
              hLineWidth: function (i, node) {
                if (i === 0 || i === node.table.body.length) {
                  return 0;
                }
                return (i === node.table.headerRows) ? 2 : 1;
              },
              vLineWidth: function (i) {
                return 0;
              },
              hLineColor: function (i) {
                return i === 1 ? 'black' : '#aaa';
              },
              paddingLeft: function (i) {
                return i === 0 ? 0 : 8;
              },
              paddingRight: function (i, node) {
                return (i === node.table.widths.length - 1) ? 0 : 8;
              }
            }
          };
          pdfMake.createPdf(dd,mytableLayouts.exampleLayout).download('NameofPrint');
        }); // this is data call API
}
Above cuurent code gives output like this
Its not showing tableheader
![image](https://user-images.githubusercontent.com/26209751/84585031-d7c29580-ae28-11ea-8b4a-8b79dd1cef77.png)

**Comment by jclindia** [comment]
![image](https://user-images.githubusercontent.com/26209751/84585404-207c4d80-ae2d-11ea-8247-151633e1b198.png)
 Now i can add the header. Now nested feature should work as one class have multiple sections multiple tables should be printed

**Comment by jclindia** [comment]
session:20-21:term:annual:Class-I:Section:B
<Class-1 section B table Here>
session:20-21:term:annual:Class-I:Section:C
<Class-2 Section C Table>
session:20-21:term:annual:Class-2:Section:A
<Class-2 Section-A Table here>
Each should print in seperate page
Pls advise

**Comment by liborm85** [comment]
ok, you already got one table. For more tables you can do something like this:
1. initialize docDefinition with empty contend
```js
var dd = {
	// and header, footer, etc..
	content: []
}
```

2. and add "session" tables to content:
```js
function addSessionTable(dd, dataForSession) {
  // before prepare data for `theader` and `tbody` as you already have

  dd.content.push({
                          pageBreak: 'before' // to start on new page
                          text: 'Session:  '+ this.flatdata[0]['data'].academic_session
                          +'  Term:  '+this.flatdata[0]['data'].academic_term
                          +'  Class Name:  '+ this.flatdata[0]['data'].class_name
                          +'  Section Name:  '+this.flatdata[0]['data'].section_name,
                          fontSize: 14,
                          bold: true,
                          alignment: 'center'
                        });
  dd.content.push({
                          table: {
                            header: theader,
                            body:tbody
                          }
                        });
}
```

```js
addSessionTable(dd, dataForSession1);
addSessionTable(dd, dataForSession2);
...
```

For break to new page use `pageBreak: 'before'` in node element.

**Comment by jclindia** [comment]
Thx i got the idea. Let me try...will update you accordingly...
