### ISSUE TITLE
Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined in a build bundle AND regeneratorRuntime is not defined.

### ISSUE THREAD

**Issue by MateuszKrazek** [bpampuch/pdfmake#2003]
I know there is a solution for this to add to the config in webpack
**exclude: [ /node_modules/, /pdfmake.js$/ ]**, but my problem is, that I need to use the .js version of the library - so the pdfmake.min.js file. I'm on the environment on which I need to import the end-javascript of PDFMake. I don't have the Webpack nor npm. Anyone knows how to workaround such problem?

What I'm doing atm is I cloned the pdfMake repository, did npm install and npm run build. Than I take the pdfmake(.min).js file and import in my current solution, where I want to use PDFMake. When the file is loading, I'm getting the 'TYPED_ARRAY_SUPPORT' problem.  
![image](https://user-images.githubusercontent.com/26872792/84764966-cc10d380-afce-11ea-8592-b7929a2f7640.png)

**Comment by MateuszKrazek** [comment]
After I managed to "solve" the problem with TYPED_ARRAY_SUPPORT - it turned out I do not have the "global" defined in the env I'm running the script on. Now I'm getting the following error: 
![image](https://user-images.githubusercontent.com/26872792/84825722-29824000-b022-11ea-9d26-f8cae558f973.png)

**Comment by MateuszKrazek** [comment]
ok, all my problems were related to the babel-loader preset-env configuration options:
```
	{
									targets: {
										"ie": "11"
									},
									modules: false,
									useBuiltIns: 'usage',
									loose: true
								}
```

**Comment by liborm85** [comment]
You write you don't use webpack and npm, but you have problem with webpack configuration.

Do not use git for production use, but released version. If you really don't use npm, you can download manually from here: https://libraries.io/npm/pdfmake
