### ISSUE TITLE
How to set pageSize for different printers (i.e. ello, thermal, brother)

### ISSUE THREAD

**Issue by ankitghanekar** [bpampuch/pdfmake#2004]

**Comment by liborm85** [comment]
One page of a pdf document can have only one page size.

**Comment by ankitghanekar** [comment]
@liborm85  But I don't know how to set dynamic page size. because we have multiple printers. so what should I do?

**Comment by liborm85** [comment]
PDF document does not allow dynamic page size. You must generate a separate pdf document for each printer  with the required page size.

**Comment by ankitghanekar** [comment]
ok, so e.g. I've 3 printer, so I need to write 3 diffrent code of pdf,
 right?

**Comment by liborm85** [comment]
You need 3 docDefinition with different `pageSize`, from which you generate 3 different pdf documents.

**Comment by ankitghanekar** [comment]
ok Thanks a lot. I'll do that.
