### ISSUE TITLE
Doubt

### ISSUE THREAD

**Issue by alexjesjimalex** [bpampuch/pdfmake#2007]
@liborm85 sorry about time, but what i mean is about your library can make pivot table o some kind of intelligent table to manage 
to handle columns that grow automatically for the right depending on the information injected by  API, here you have and example:

https://ej2.syncfusion.com/angular/documentation/pivotview/grouping-bar/

I honestly like to work more with your library and easy and agile, but I have that question if you can do something similar to the link using your library, I appreciate your time and support.

regards

**Comment by liborm85** [comment]
Do not create a duplicate issue.

duplicate: https://github.com/bpampuch/pdfmake/issues/1996
