### ISSUE TITLE
"export 'default' (imported as 'pdfMake') was not found in 'pdfmake/build/pdfmake' Angular 10.0.0

### ISSUE THREAD

**Issue by aharms24** [bpampuch/pdfmake#2009]
After updating from Angular version 9.1.11 to version 10.0.0, I am receiving this error:

"export 'default' (imported as 'pdfMake') was not found in 'pdfmake/build/pdfmake'

**Comment by Enngage** [comment]
Same here

**Comment by liborm85** [comment]
This
```
import pdfMake from "pdfmake/build/pdfmake";
```

or this
```
import * as pdfMake from 'pdfmake/build/pdfmake';
```

doesn't work?

**Comment by aharms24** [comment]
No, I tried everything I could think of, including your two suggestions.

**Comment by liborm85** [comment]
Try ask on angular support. Because these are standard imports, I don't know what the problem is in angular

**Comment by timdoes** [comment]
I am also seeing this issue. And this library is the only one that breaks on import after upgrading to Angular 10

**Comment by aharms24** [comment]
I will second that. None of my other imports broke either after upgrading to Angular 10.

**Comment by pascalklesse** [comment]
Same here with Angular 10

**Comment by liborm85** [comment]
Report it to angular support.

**Comment by timdoes** [comment]
The break happened when Angular updated the TypeScript version It uses. This TS update must include stricter standards for exporting.

Since Angular Support can’t update the pdfmake  code to be compliant with the TypeScript export standards, I guess we will have to look for a solution to replace pdfmake.

**Comment by liborm85** [comment]
pdfmake use  CommonJS standard with `module.exports` syntax: https://github.com/bpampuch/pdfmake/blob/1c6d6f529790d8fdb425fc09f36ebad4dbe883d7/src/browser-extensions/pdfMake.js#L262-L274

There must be some way in typescript to import such a library with commonjs syntax.

Angular support does not need to update anything in pdfmake library, only say how to import libraries with commonjs in new angular.

**Comment by liborm85** [comment]
According to [post in angular blog](https://blog.angular.io/version-10-of-angular-now-available-78960babd41) typescript is updated to 3.9 in Angular 10.

[Release announcement](https://devblogs.microsoft.com/typescript/announcing-typescript-3-9/) for typescript 3.9 say:

> **CommonJS Auto-Imports in JavaScript**
> One great new improvement is in auto-imports in JavaScript files using CommonJS modules.
> 
> In older versions, TypeScript always assumed that regardless of your file, you wanted an ECMAScript-style import like
> 
> import * as fs from "fs";
> However, not everyone is targeting ECMAScript-style modules when writing JavaScript files. Plenty of users still use CommonJS-style require(...) imports like so
>
> const fs = require("fs");
> TypeScript now automatically detects the types of imports you’re using to keep your file’s style clean and consistent.
>
>
> For more details on the change, see [the corresponding pull request](https://github.com/microsoft/TypeScript/pull/37027).


Which means it has to be imported somehow. I don't use typescript or angular, must try how to do it, someone else.

**Comment by wittibs** [comment]
I am not getting the typescript compilation error, but the imported pdfmake module was undefined after upgrading to angular v10.

I noticed in the pdfmake code that, as a last resort, the import will define the createPdf function on a "global" object (which is the window object in a web browser environment). so this worked for me:

```javascript
import "pdfmake/build/pdfmake";
const pdfMake = { createPdf: window["createPdf"] }
```

**Comment by weilies** [comment]
i also stuck as i need a PDF package for my project, deadly!
Why not they make pdfMake officially support and maintain for TS folks...?

**Comment by liborm85** [comment]
But according to the TS documentation it should work...

Can anyone prepare simple example with TypeScript 10 and pdfmake, where I just run npm install and something else and this will cause this error? Thanks.

**Comment by ashgrey91** [comment]
Hi everyone,
I needed to generate a html table into a pdf for a report in my angular project and wanted to use pdfMake because I didnt want to make it complex with axes and everything.I tried pdfmake, ng-pdf-make and import * as but nothing worked.So, I have given up on pdfMake.As I searched for a simple solution,I found the following link very useful.It took me only 10 minutes.It uses jsPDF and jspdf-autotable plugin.You just have to pass the table id and your table will be printed.No need to play with axes.

https://medium.com/@ramamity94/creating-customisable-beautiful-pdfs-using-jspdf-api-aem-and-angular-991dcc988bbd 

Here is JsPDF-AutoTable official gitHub page.

https://github.com/simonbengtsson/jsPDF-AutoTable#installation

Hope it helps someone.

**Comment by liborm85** [comment]
How is this related to this problem?

**Comment by ashgrey91** [comment]
I also faced this problem and I don't see a working solution for this problem anywhere.If someone like the user, weilies is willing to go for an alternative but dont want to, I quote "i buy the idea not using x,y, html position text and tables!",they can migrate from PDFMake to JsPDF easily.

**Comment by liborm85** [comment]
Tested with TypeScript 4.0.2, and this way is working:
```js
import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

(<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;
```


In TypeScript `* as` is required as already mentioned in my first post...

**Comment by hfilippi** [comment]
I'm facing the same problem with angular 10.2.0. I changed the imports in my TypeScript as @liborm85 suggest:

```
import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

(<any> pdfMake).vfs = pdfFonts.pdfMake.vfs;
```

but when I run **ng build --prod --aot** I get:

ERROR in ./src/app/components/shared/audit.ts 43:8-25
"export 'createPdf' (imported as 'pdfMake') was not found in 'pdfmake/build/pdfmake'
ERROR in ./src/app/components/shared/audit.ts 3:0-11
"export 'vfs' (imported as 'pdfMake') was not found in 'pdfmake/build/pdfmake'

Is there a solution for this problem? Please help! Thanks in advance.

**Comment by liborm85** [comment]
No reaction. I take the problem as solved as write above.

**Comment by aaronfrost** [comment]
Same issue. Anyone get a fix/workaround for this? I really am not looking forward to copying the source into my project and fixing a copy of the project.

**Comment by wittibs** [comment]
@aaronfrost try this

```javascript
import "pdfmake/build/pdfmake"
const pdfMake = window["pdfMake"];
```

**Comment by Joemarc** [comment]
@wittibs It worked for me but on ReactJs, thanks :) 

If it can help anyone, here is my imports 

`import "pdfmake/build/pdfmake"
import moment from 'moment';
import pdfFonts from 'pdfmake/build/vfs_fonts';

const pdfMake = window["pdfMake"];
pdfMake.vfs = pdfFonts.pdfMake.vfs;`

**Comment by pradeep199896** [comment]
> @wittibs This worked for me man!Thankss
> 
> ```js
> import "pdfmake/build/pdfmake"
> const pdfMake = window["pdfMake"];
> ```

**Comment by sanD9090** [comment]
var pdfMake = require('pdfmake/build/pdfmake');
var pdfFonts = require('pdfmake/build/vfs_fonts');
pdfMake.vfs = pdfFonts.pdfMake.vfs;

**Comment by 8483** [comment]
> @aaronfrost try this
> 
> ```js
> import "pdfmake/build/pdfmake"
> const pdfMake = window["pdfMake"];
> ```

THANK FUCK! This finally worked. What a piece of shit importing approach for such a good library... I hope they fix it...

**Comment by maxfortatacado** [comment]
> > @aaronfrost try this
> > ```js
> > import "pdfmake/build/pdfmake"
> > const pdfMake = window["pdfMake"];
> > ```
> 
> THANK FUCK! This finally worked. What a piece of shit importing approach for such a good library... I hope they fix it...
> 
> After wasting 3 fucking hours on this, here is the final working solution:
> 
> ```js
> import "pdfmake/build/pdfmake";
> const pdfMake = window["pdfMake"];
> 
> pdfMake.fonts = {
>     Roboto: {
>         normal: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
>         bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
>         italics: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
>         bolditalics: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
>     },
> };
> ```

Worked perfectly for me!

**Comment by fernandoscheffel** [comment]
> > @aaronfrost try this
> > ```js
> > import "pdfmake/build/pdfmake"
> > const pdfMake = window["pdfMake"];
> > ```
> 
> THANK FUCK! This finally worked. What a piece of shit importing approach for such a good library... I hope they fix it...
> 
> After wasting 3 fucking hours on this, here is the final working solution:
> 
> ```js
> import "pdfmake/build/pdfmake";
> const pdfMake = window["pdfMake"];
> 
> pdfMake.fonts = {
>     Roboto: {
>         normal: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
>         bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
>         italics: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
>         bolditalics: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
>     },
> };
> ```

Thank you!!

**Comment by rajeev1202** [comment]
> Tested with TypeScript 4.0.2, and this way is working:
> 
> ```js
> import * as pdfMake from "pdfmake/build/pdfmake";
> import * as pdfFonts from 'pdfmake/build/vfs_fonts';
> 
> (<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;
> ```
> 
> In TypeScript `* as` is required as already mentioned in my first post...

Thanks.It worked for me , i'm using Angular 16.2.0 and typescript 5.1.3 .

**Comment by eurival** [comment]
how make to use in pure javascript ?

**Comment by cromanauter** [comment]
This works in angular 17 :
`import * as pdfMake from 'pdfmake/build/pdfmake';`
