### ISSUE TITLE
When adblock is installed open() method doesn't work. New window is closed

### ISSUE THREAD

**Issue by geekypunk** [bpampuch/pdfmake#2014]
Using the latest pdfmake version, and Chrome 83.0.4103.116  with latest version of adblock addon.

When adblock is installed open() method doesn't work. New window when pdf is supposed to show, is closed automatically. It works fine when adblock is disabled

**Comment by liborm85** [comment]
see [documentation](https://pdfmake.github.io/docs/getting-started/client-side/supported-browsers/) and referenced [issue](https://github.com/bpampuch/pdfmake/issues/800) in documentation.
