### ISSUE TITLE
PDFMake How do I position a stamp/signature on the bottom of the page?

### ISSUE THREAD

**Issue by awei863** [bpampuch/pdfmake#2018]
Hi, so I'm creating an invoice using PDFMake and I have trouble positioning the stamp/signature section to the bottom of the page. If the invoice is bigger than a page then the stamp/signature should be on the bottom of the next page. Also, if the invoice is filled to the right amount, the table gets cut off between the first two pages, it does not bring the whole thing over to the next page.

If you go to pdfmake playground website, this is my current code:

```
var dd = {
    content: [
        {
            
            table: {
                widths:['*',"*"],
                heights:[100],
                body: [
                    [{text:'______________________________________________ \n Stamp', alignment:'left', margin: [0,90,0,0], border: [true, true, false, true],}, 
                    {text:'Authorized Agent ____________________________ \n\n Signature               ____________________________', margin:[0,50,0,0], border: [false, true, true, true],}, ],
                    
                ]
            }
        },
    ]
    
}
```
I tried using absolute positioning, but that only moves the text inside the table and not the table itself.

I made this using a table because I find it easy to make, if there are other ways to do this to make this stamp/section "stick" to the bottom of the last page please help me, thanks!

**Comment by liborm85** [comment]
Using `absolutePosition` does what you want, example:
```js
var dd = {
    content: [
        {
            absolutePosition: { x: 40, y: 650 },
            table: {
                widths:['*',"*"],
                heights:[100],
                body: [
                    [{text:'______________________________________________ \n Stamp', alignment:'left', margin: [0,90,0,0], border: [true, true, false, true],}, 
                    {text:'Authorized Agent ____________________________ \n\n Signature               ____________________________', margin:[0,50,0,0], border: [false, true, true, true],}, ],
                    
                ]
            }
        },
    ]
}
```

**Comment by awei863** [comment]
> Using `absolutePosition` does what you want, example:
> 
> ```js
> var dd = {
>     content: [
>         {
>             absolutePosition: { x: 40, y: 650 },
>             table: {
>                 widths:['*',"*"],
>                 heights:[100],
>                 body: [
>                     [{text:'______________________________________________ \n Stamp', alignment:'left', margin: [0,90,0,0], border: [true, true, false, true],}, 
>                     {text:'Authorized Agent ____________________________ \n\n Signature               ____________________________', margin:[0,50,0,0], border: [false, true, true, true],}, ],
>                     
>                 ]
>             }
>         },
>     ]
> }
> ```

**Comment by awei863** [comment]
@liborm85 I tried it with text and it goes into the table instead of skipping it.

```
var dd = {
    content: [
        {text:'hi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\nhihi\n'},
        {
            absolutePosition: { x: 40, y: 650 },
            table: {
                widths:['*',"*"],
                heights:[100],
                body: [
                    [{text:'______________________________________________ \n Stamp', alignment:'left', margin: [0,90,0,0], border: [true, true, false, true],}, 
                    {text:'Authorized Agent ____________________________ \n\n Signature               ____________________________', margin:[0,50,0,0], border: [false, true, true, true],}, ],
                    
                ]
            }
        },
    ]
}
```
