### ISSUE TITLE
Image URL support, please

### ISSUE THREAD

**Issue by stl1988** [bpampuch/pdfmake#2020]
After you added the possibility to use fonta directly from an URL, can you please do the same thing for images, too? Currently I have to pass each image through a data URI generator in order to use it. But that converter seems to have a size limit for images.

**Comment by suchislife801** [comment]
After encoding an image Signature.png with pdfmake_vfsmake.php into vfs_fonts.js, the following piece of code works for me.

```
{
  image: 'Signature.png',
  width: 180,
  height: 82
},
```

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/de3e5526ea86528f496707eae0a70d0949ef1950. Feature is supported in only in "images" dictionary and only in browser.
This is not supported: ~~```{ image: 'https://picsum.photos/seed/picsum/200/300' }```~~

Example of usage:
```js
var dd = {
	content: [
		{
			image: 'testImage'
		}
	],
	images: {
		testImage: 'https://picsum.photos/seed/picsum/200/300',
	}
};
```
