### ISSUE TITLE
SVG parsing is..... not great.

### ISSUE THREAD

**Issue by sophistifunk** [bpampuch/pdfmake#2021]
This file renders correctly, but at the wrong size (too big, ends up drawing over following content):

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="105pt" height="222pt" viewBox="0.00 0.00 105.43 222.00" xmlns="http://www.w3.org/2000/svg" 
    xmlns:xlink="http://www.w3.org/1999/xlink">
    <rect width="105" height="222" fill="none" stroke="black"/>
</svg>
```

Whereas if I make the sole change of deleting the line break on the `svg` element like so:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<svg width="105pt" height="222pt" viewBox="0.00 0.00 105.43 222.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <rect width="105" height="222" fill="none" stroke="black"/>
</svg>
```

Then it renders correctly. Adding a comment into the document like this:

```
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE svg PUBLIC "-//W3C//DTD SVG 1.1//EN" "http://www.w3.org/Graphics/SVG/1.1/DTD/svg11.dtd">
<!-- <svg -->
<svg width="105pt" height="222pt" viewBox="0.00 0.00 105.43 222.00" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink">
    <rect width="105" height="222" fill="none" stroke="black"/>
</svg>
```

Causes the image to be rendered at the larger incorrect size, and then silently throws somewhere, and stops processing any part of the document afterwards.

**Comment by sophistifunk** [comment]
Bad output (wrong size):
![image](https://user-images.githubusercontent.com/142591/87396603-6a0bb400-c5f6-11ea-830f-211dcd5b7beb.png)

Correct (expected) output:
![image](https://user-images.githubusercontent.com/142591/87396667-827bce80-c5f6-11ea-9453-4f8f81e55a3e.png)

Really bad (silent failure) output:
![image](https://user-images.githubusercontent.com/142591/87396772-accd8c00-c5f6-11ea-8430-aa2d281134f2.png)

**Comment by sophistifunk** [comment]
FWIW I'm looking into if I can fix this, so I'll add more info as I learn more.

**Comment by sophistifunk** [comment]
Ideally the way to fix this is by using a real XML parser lib, if I re-write `SVGMeasure` to use one, will my change be rejected because it introduces a new dependency?

Also: is there a gitter or mailing list or something for discussion about things like this, or just issues and PRs?

**Comment by liborm85** [comment]
In PR https://github.com/bpampuch/pdfmake/pull/1682 was originally used library for xml parsing, but was removed later https://github.com/bpampuch/pdfmake/pull/1682/commits/388286c2b349a47f34ab3b249cfddf0ea6c7c5f9, because it seemed that it would be possible to solve it manually without next library.

If this cannot be solved manually, new library will need to be used. PR is welcome.

Discussion takes place in issues or PRs.
