### ISSUE TITLE
Support for professional fonts.

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#2022]
Bellow is a sample of what I need to do in order to get professional fonts to display correctly.

**I have purchased** a set of Linotype Helvetica fonts. If you check this font family on their site, you will see they have MUCH more than just normal, bold, italics and bolditalics.

[https://www.linotype.com/1245395/neue-helvetica-family.html](https://www.linotype.com/1245395/neue-helvetica-family.html)

Notice how...

The Helvetica Roman has 4 variations & The Helvetica Condensed has 4 variations.

My question is, Is there a chance you can add more than normal, bold, italics and bolditalics **without being hacky like below**?

```
// Document Fonts
pdfMake.fonts = {
  // Font 1
  HelveticaRoman: {
    normal: 'Neue Helvetica® Std 55 Roman.otf',
    bold: 'Neue Helvetica® Std 65 Medium.otf',
    italics: 'Neue Helvetica® Std 75 Bold.otf',
    bolditalics: 'Neue Helvetica® Std 85 Heavy.otf'
  },
  // Font 2
  HelveticaCondensed: {
    normal: 'Neue Helvetica® Std 57 Condensed.otf',
    bold: 'Neue Helvetica® Std 67 Condensed Medium.otf',
    italics: 'Neue Helvetica® Std 77 Condensed Bold.otf',
    bolditalics: 'Neue Helvetica® Std 87 Condensed Heavy.otf'
  }
};
```

**Comment by liborm85** [comment]
Why do you create exactly same questions from you?
DUPLICATE: https://github.com/bpampuch/pdfmake/issues/1907
