### ISSUE TITLE
Trouble with a Table

### ISSUE THREAD

**Issue by alexjesjimalex** [bpampuch/pdfmake#2024]
I have this problem with my tables:
![Captura](https://user-images.githubusercontent.com/26495551/87581007-86aaf900-c695-11ea-8a1b-a8c86c04d90d.PNG)

the question is, does any one knows how to fit the table in one page o pass to another one??
thxs

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/441
