### ISSUE TITLE
pdfmake overrides window.Promise object

### ISSUE THREAD

**Issue by jonathanPoitz** [bpampuch/pdfmake#2026]
Hello,

we're embedding pdfmake.min.js into our js-webapp in which we also use the promise lib https://github.com/petkaantonov/bluebird. Unfortunately, pdfmake permanently overrides `window.Promise`. Can you fix this unwanted side effect?

Thanks,

Jonathan

**Comment by liborm85** [comment]
pdfmake uses a lot of polyfills for cross support in browsers. Promise polyfill is added via Babel from core-js (see core-js [Promise polyfill](https://github.com/zloirock/core-js/tree/v3/packages/core-js/features/promise)). I suppose is added only if is not available in browser. Therefore first load your polyfill and then pdfmake (pdfmake should add nothing).

**Comment by Skubakoob** [comment]
Hello, I have a similar problem in using pdfmake in an Angular project and Safari (Angular 5 to be specific). Angular runs along nicely until I create a document with pdfmake, at which point it replaces angulars promise object and then breaks the whole website. This doesn't happen in Chrome - not sure why core-js does this in Safari.

To get around this (for now) I've just rebuilt pdfmake with the  **require('core-js/features/promise');** line commented out in the UrlBrowserResolver.js file, and my site is working as expected again. (Working this out was a nightmare!)

I guess it's a problem with core-js, safari and angular in my case. Pretty annoying. Not sure if that helps in any way whatsoever. I suppose a solution would be to not include the polyfills in the pdfmake build and let people install it separately if they need it

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/e83f8530751d63d037c5b6ce3d117564fd9214b6.
I had no idea core-js is so stupid.
