### ISSUE TITLE
Extra padding

### ISSUE THREAD

**Issue by fscloudapp** [bpampuch/pdfmake#2028]
Hi, i created a tag generator and i use a table o organize them. Starting from second page the columns of first row are drawn with extra padding. The table doesn't have header. Any help welcome.
[download (6).pdf](https://github.com/bpampuch/pdfmake/files/4942028/download.6.pdf)

**Comment by liborm85** [comment]
Attach example of reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by fscloudapp** [comment]
liborm85, problem solved. "Added dontBreakRows: true" in table definition and everything works fine. Thanks!
