### ISSUE TITLE
Table pops outside page container 

### ISSUE THREAD

**Issue by NeevShah** [bpampuch/pdfmake#203]
I have following problem where I have a table with dynamic data for body and width is 'auto' or '*'. Still it pops out of page container where email id is too large. Can you please help me out?
"Status" pops outside the page container in following image.. Sorry for my bad English.. 

![screenshot from 2015-02-16 22 08 37](https://cloud.githubusercontent.com/assets/9209944/6215690/023c2bb2-b629-11e4-814f-1209f9c16f95.png)

**Comment by jthoenes** [comment]
Could you paste the document definition that creates it - so I can have a look?

**Comment by NeevShah** [comment]
var docDefinition = {
            pageSize: 'A4',
            footer: function (currentPage, pageCount) { return currentPage.toString() + ' of ' + pageCount; },
            content: content,
            pageMargins: [ 20, 40, 20, 40 ],
            styles: {
                tableHeader: {
                    bold: true,
                    fontSize: 13,
                    color: 'black',
                    fillColor: '#eaeaea'
                }
            },
            defaultStyle: {
                fontSize: 12,
            }
        };


*Where content contains widths and body part..

**Comment by cat0rgi0** [comment]
You should check the values of widths ?

**Comment by NeevShah** [comment]
I have.. Widths array contains ['*','*','auto','auto','auto','auto','auto'] .. I Have 7 columns..

**Comment by cat0rgi0** [comment]
Why the firsts two values are blank? 
Change them with auto or star fixed value

**Comment by NeevShah** [comment]
They are not blank, they are "*" (star)..

**Comment by cat0rgi0** [comment]
Change them with auto

**Comment by NeevShah** [comment]
I have tried it.. still did not solve my problem.
