### ISSUE TITLE
Support width setting on text elements; especially for absolute positioning

### ISSUE THREAD

**Issue by darksnake747** [bpampuch/pdfmake#2030]
While trying to layout a PDF, I needed to position some text to a specific x and y. I was able to do that with the `absolutePosition` setting, but the width setting does nothing. The text starts where it needs to, but it just continues to the right edge of the page. I would expect a setting like the code below to work, but the `width` does nothing.

```js
{
    text: 'This is some text...',
    absolutePosition: {x: 100, y: 100},
    width: 80
}
```

I would also think that just a `width` setting on a text element should work, but it does not.

```js
{
    text: 'This is some text...',
    width: 80
}
```

Am I doing something wrong; is there support for this already? Would this be a new feature request... or was it suppose to work and this is a bug? Thank you for developing such an awesome library!

**Comment by rondog** [comment]
you figure this out? I need the same solution

**Comment by darksnake747** [comment]
I did not. From what I could tell in the code (and docs), it's just not supported at the moment. Enough time passed from my initial post here that I decided to just go back to using jsPDF directly. The dev here seems busy and in high demand; and I have too many projects on hand and my clients' need things asap. 

I don't have time right now to get involved and try to figure it out for my use case. Some day I may get back to this. It is a great and powerful library! Excited for its future though! :)

Sorry; best of luck to you!

**Comment by rondog** [comment]
alright, thanks for letting me know!

**Comment by liborm85** [comment]
`table` node with 1 row and 1 column should be used for this.

**Comment by bengigone** [comment]
Adding on to this @liborm85 - I have three stacks in a single row, each with a canvas. I'm trying to put text in the middle column however the text also runs off the page. I've tried inserting a table with 1 row and 1 column but I can't seem to render it within the canvas (doesn't seem to respond to relative or absolute positioning).

Running this in the playground renders the second column incorrectly. Any thoughts on this? Have been battling with this one for a while!

`var dd = {
  pageMargins: [30, 20, 30, 10],

  background: function () {
    return {
      canvas: [
        {
          type: "rect",
          x: 0,
          y: 0,
          w: 595.28,
          h: 841.89,
          color: "#f2f4f6",
        },
      ],
    };
  },
  content: [
    // Header Column

    // Row 4 //

    {
      columns: [
        {
          stack: [
            {
              canvas: [
                {
                  type: "rect",
                  x: 1,
                  y: 1,
                  w: 168,
                  h: 185,
                  r: 20,
                  color: "#fff",
                },
              ],
            },
            {
              text: "References",
              relativePosition: { y: -165, x: 30 },
              fontSize: 13,
            },
            {
              text: "Mark Pompeo",
              bold: true,
              relativePosition: { y: -130, x: 30 },
              fontSize: 10,
            },
            {
              text: "CTO at Apple",
              relativePosition: { y: -115, x: 30 },
              fontSize: 9,
              color: "gray",
            },
            {
              text: "Phone: 986-854-3210",
              relativePosition: { y: -100, x: 30 },
              fontSize: 9,
              color: "gray",
            },
            {
              text: "Claire Loy",
              bold: true,
              relativePosition: { y: -70, x: 30 },
              fontSize: 10,
            },
            {
              text: "Landlord at Freed Condos",
              relativePosition: { y: -55, x: 30 },
              fontSize: 9,
              color: "gray",
            },
            {
              text: "Phone: 986-854-3210",
              relativePosition: { y: -40, x: 30 },
              fontSize: 9,
              color: "gray",
            },
          ],
        },

        {
            
          stack: [
            {
              canvas: [
                {
                  type: "rect",
                  x: 1,
                  y: 1,
                  w: 168,
                  h: 185,
                  r: 20,
                  color: "#fff",
                },
              ],
            },
            {
              text: "Additional Needs",
              relativePosition: { y: -165, x: 20 },
              fontSize: 13,
            },
            {
              text: "I have some additional needs that need",
              relativePosition: { y: -130, x: 20 },
              fontSize: 10,
            },
            
          ],
        },
        {
          stack: [
            {
              canvas: [
                {
                  type: "rect",
                  x: 1,
                  y: 1,
                  w: 168,
                  h: 185,
                  r: 20,
                  color: "#fff",
                },
              ],
            },
            {
              text: "Availability",
              relativePosition: { y: -165, x: 20 },
              fontSize: 13,
            },
            {
              text: "Weekends after 5",
              relativePosition: { y: -130, x: 20 },
              fontSize: 10,
            },
          ],
        },
      ],
      margin: [0, 15, 0, 15],
      columnGap: 0,
    },

    // End of Content - Page Styles
  ],
  defaultStyle: {
    color: "black",
    fontSize: 8,
    lineHeight: 1.25,
  },

};`

**Comment by Cauen** [comment]
> `table` node with 1 row and 1 column should be used for this.

Table doesnt have support for "absolutePosition". 

<details>
  <summary>Click to see an error ❌ example</summary>

```ts
var dd = {
	content: [
		{
			table: {
				widths: [10],
			    // absolutePosition: { x: 0, y: 0 },
				body: [
					[
						{
							text: "Lorem ipsum dolor amet",
							absolutePosition: { x: 0, y: 0 },
						},
					],
				],
			},
		}
	],
}
```

</details>

I've resolved this issue using columns, below an ok example ✅:
Check it here: http://pdfmake.org/playground.html

```ts
var dd = {
	content: [
		{
			absolutePosition: { x: 50, y: 100 },
			columns: [
				{
					width: 100,
					text: "Simple absolute text width width 100",
				},
			],
		},
		{
			// alignment: "justify",
			absolutePosition: { x: 5, y: 5 },
			columns: [
				{
					width: 400,
					text: [
						{
							text: " This is a sentence with a ",
							margin: [0, 5, 0, 10],
							style: ["html-p", "html-div"],
							alignment: "center",
						},
						{
							text: "bold word",
							// nodeName: "STRONG",
							alignment: "center",
							bold: true,
							style: ["html-strong", "html-p", "html-div"],
						},
						{
							text: ", ",
							margin: [0, 5, 0, 10],
							alignment: "center",
							style: ["html-p", "html-div"],
						},
						{
							text: "one in italic",
							// nodeName: "EM",
							alignment: "center",
							italics: true,
							style: ["html-em", "html-p", "html-div"],
						},
						{
							text: ", and ",
							margin: [0, 5, 0, 10],
							alignment: "center",
							style: ["html-p", "html-div"],
						},
						{
							text: "one with underline",
							// nodeName: "U",
							alignment: "center",
							decoration: ["underline"],
							style: ["html-u", "html-p", "html-div"],
						},
						{
							text: ". And finally ",
							margin: [0, 5, 0, 10],
							alignment: "center",
							style: ["html-p", "html-div"],
						},
						{
							text: "a link",
							alignment: "center",
							color: "blue",
							decoration: ["underline"],
							style: ["html-a", "html-p", "html-div"],
							link: "https://www.somewhere.com",
							// nodeName: "A",
						},
						{
							text: ". ",
							margin: [0, 5, 0, 10],
							alignment: "center",
							style: ["html-p", "html-div"],
						},
					],
				},
			],
		},
	],
};

```
