### ISSUE TITLE
Export  images with JsPDF or pdfMake

### ISSUE THREAD

**Issue by sylvain258** [bpampuch/pdfmake#2032]
Hello,

I am looking to export images, but I have this problem. The console says "Uncaught (in promise) Invalid image ....". I need to export images. I understood that the images should be encoded in Base64, but I have several thousand images and I cannot encode them one by one. URLs come from PHP database requests. I need the js method to encode in Base64. I tried btoa() method, but the message is returned.
I cannot work on the server side (node.js) because I am already in the PHP environment. 
Ideas to resolve this problem. A lot of messages about this problem exist but nothing resolve it.
Thank you very much
Sylvain

**Comment by liborm85** [comment]
If you do not want to use base64 conversion, you can use image loading via url (https or http protocol) in version 0.1.67, see [release info](https://github.com/bpampuch/pdfmake/releases/tag/0.1.67).
