### ISSUE TITLE
Is there any way to add outline to text with destinations, so that it can viewed in getOutline of ng2-pdf-viewer

### ISSUE THREAD

**Issue by Anand-Paul** [bpampuch/pdfmake#2033]
i have searched a lot to display the outlines using ng2-pdf-viewer in which the pdf is generated using the pdfmake library. Is there any options to put some text as outline text in pdfmake while definnig the document definition

**Comment by justinthomas0789** [comment]
Same here, wondering is there a way to get the PDF outlines to show in PDF viewers. Found linkToDestination and toc, but both are doing the job inside the PDF I guess, not by a PDF viewer.

**Comment by liborm85** [comment]
I don't know ng2-pdf-viewer. Support for outlines/bookmaks in PDF is here: https://github.com/bpampuch/pdfmake/issues/427
