### ISSUE TITLE
Vertical align a stack in pdfmake

### ISSUE THREAD

**Issue by Anand-Paul** [bpampuch/pdfmake#2034]
is there any way to align a stack of text vertically centered with respect to the page height of the page.
example code :
`stack: [
   {
     text: 'text 1'
   },
   {
     text: 'text 2'
   } 
 ]`

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/983 https://github.com/bpampuch/pdfmake/issues/74
