### ISSUE TITLE
How to export images in dynamic column image?

### ISSUE THREAD

**Issue by baynojunemark24** [bpampuch/pdfmake#2036]
I have a `datatable` with a column images. Now the situation is like this. My DataTable it has `responsive` and `colReorder` function, and I reOrder the columns using a div (image below) with jQuery `sortable()`.

![image](https://user-images.githubusercontent.com/26641237/88875386-c0fac580-d253-11ea-9d5e-c2acbaf76656.png)

Now when I export it to pdf I found that the image is empty as what I read in some solution is converting the image to 64 string, and insert the base64

I did this, putting the encoded URL
```
// HTML
<img class="img-circle img-thumbnail img-responsive convertTo64" src="{{ $path }}">
```

```
// JS
function toDataURL(src, callback, outputFormat) {
    var img = new Image();
        img.setAttribute("crossOrigin", "anonymous");
        img.onload = function() {
            var canvas = document.createElement('canvas');
                canvas.height = this.naturalHeight;
                canvas.width = this.naturalWidth;

            var ctx = canvas.getContext('2d');
                ctx.drawImage(this, 0, 0);
            var dataURL;
            dataURL = canvas.toDataURL(outputFormat);
            callback(dataURL);
        };
        img.src = src;
}
$.each($('.convertTo64'), function(index, val) {
    var that = $(this);
    var url = $(this).attr('src');

    toDataURL(url, function(dataUrl) {
        that.attr('src', dataUrl)
    });
});
```
// callback function in pdfMake
```
customize: function ( doc ) {
    doc.content[1].layout = 'lightHorizontalLines';
    var toImg64 = [];
    // Get the encoded url
    $.each( $('.convertTo64') , function(index, val) {
        var that = $(this);
        toImg64.push(that.attr('src'))
    });

    var base64Url;
    for (var i = 1; i < doc.content[1].table.body.length; i++ ) {
        base64Url = toImg64[i-1];
        doc.content[1].table.body[i][1] = {
            image: base64Url,
            fit: [70, 70]
        }
    }
},
```
In the example above, let's assume that the column image is in the `index 1`. Works great in here, but the problem is:

> **How can I detect the column image if the user re-ordered the columns?**

Any help would be appreciated.

Thanks

**Comment by liborm85** [comment]
This is not a pdfmake code... Ask a question in DataTable suppport.
