### ISSUE TITLE
Indent lines in tables

### ISSUE THREAD

**Issue by Tjossul** [bpampuch/pdfmake#2038]
Hello,

is it somehow possible to intend lines in tables?

I tried it using spaces:

        tableBody.push([
            { text: text1 + '\n   ' + text2, style: 'tableBodyLeft' },
            { text: text3, style: 'tableBodyRight' },
            { text: text4, style: 'tableBodyRight' },
            { text: text5, style: 'tableBodyRight' }]
        );

The forced line break works but the 3 spaces before "text2" is being ignored.

Any ideas?

Thanks and regards!
T.

**Comment by liborm85** [comment]
Use `preserveLeadingSpaces` property, example:
```js
{ text: 'text1' + '\n   ' + 'text2', preserveLeadingSpaces: true, style: 'tableBodyLeft' },
```

**Comment by Tjossul** [comment]
Wow! Thank you very much!

You're my savior! :-)

**Comment by wfy-ddup** [comment]
\t
