### ISSUE TITLE
import Google Font OpenSans but getting error advanceWidth

### ISSUE THREAD

**Issue by fauzanmasulili** [bpampuch/pdfmake#2039]
![image](https://user-images.githubusercontent.com/26572430/89255118-1c112b80-d64b-11ea-835c-8f0f6ff5210e.png)

**Comment by liborm85** [comment]
Probably an unsupported font format. Where is the font to download?

**Comment by fauzanmasulili** [comment]
i downloaded it from google fonts

**Comment by liborm85** [comment]
Open Sans font tested and works ok.

**Comment by fauzanmasulili** [comment]
I use vue js and convert that font to base64

**Comment by liborm85** [comment]
Yes, this is correct. Details are in [documentation](https://pdfmake.github.io/docs/fonts/).
