### ISSUE TITLE
Issue with custom font via URL protocol

### ISSUE THREAD

**Issue by manhtqb** [bpampuch/pdfmake#2040]
I want to use Noto Sans JP font to display Japanese, but I can't find an URL like that https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf

I tried some URLs but none of them work:
https://fonts.googleapis.com/css2?family=Noto+Sans+JP:wght@100&display=swap
https://fonts.gstatic.com/s/notosansjp/v25/-F6ofjtqLzI2JPCgQBnw7HFQoggPkENvl4B0ZLgOquiXidBa3qHiDcp2RQ.0.woff2

I use vuejs and my code like this:
```
<template>
  <div class="pdf-iframe">
    <iframe id='pdfV'></iframe>
  </div>
</template>
<script>
import pdfMake from 'pdfmake/build/pdfmake';
import pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake.vfs;
var dd = {
  defaultStyle: {
    font: 'NotoSan'
  },
 
  content: [
   // my content
  ]
};

export default {
  name: 'Demo',
  mounted () {
    const fonts = {
      NotoSan: {
        normal: 'https://fonts.gstatic.com/s/notosansjp/v25/-F6ofjtqLzI2JPCgQBnw7HFQoggPkENvl4B0ZLgOquiXidBa3qHiDcp2RQ.0.woff2',
      },
    };
    pdfMake.createPdf(dd, null, fonts).getDataUrl(function (outDoc) {
      document.getElementById('pdfV').src = outDoc;
    });
  }
}
</script>
```

**Comment by liborm85** [comment]
You can use url from your application where the font will be located. It doesn't have to be on cdn.

It must be a supported font. CSS is not supported.

**Comment by manhtqb** [comment]
> You can use url from your application where the font will be located. It doesn't have to be on cdn.
> 
> It must be a supported font. CSS is not supported.

Thank you for your reply, I tried to store fonts file in my application and it worked!
