### ISSUE TITLE
Javascript Heap Memory

### ISSUE THREAD

**Issue by dewaleolaoye** [bpampuch/pdfmake#2041]
I'm using `pdfmake` in a `create react app`, When I run `yarn build` on my machine, it builds successfully with no errors but on getting to production, It throws **FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory**  and failed to build. 

This is how I'm generating the PDF 

```javascript
const generatePdf = () => {
    const doc: IContent = {
      content: [],
      info: {
        title: 'Report Note',
        author: 'wale',
        subject: 'Report Note',
        producer: 'Wale',
      },
      pageSize: 'A4',
      pageOrientation: 'portrait',
      pageMargins: [40, 80, 40, 40],
      defaultStyle: {
        fontSize: 16,
        lineHeight: 1.2,
      },
      footer: {
        columns: [
          {
            text: 'Report Note ©2020',
            alignment: 'left',
            fontSize: 12,
            margin: [10, 10],
          },
        ],
      },   
    };

    doc.content.push({
      text: [{ text: 'Description: ', bold: true }, `${data?.getReport.description}`, '\n'],
    });

    pdfMake.createPdf(doc).download('report.pdf', undefined, { fontLayoutCache: false });
  }
  ```
And I pass the `generatePdf` function to the onClick
```javascript
<Button onClick={generatePdf}>Download Report</Button>
```

NB: `data?.getReport.description` is data string I'm getting from the server.
and the pdf is been generated fine and works fine on **local** but refuses to build in production. 
Please help

**Comment by liborm85** [comment]
Looking at code you generate only 1 text line, this cannot fail to memory due to pdfmake.
Problem will be somewhere else, not in pdfmake.

**Comment by dewaleolaoye** [comment]
Thanks @liborm85  but when I remove `pdfmake`, It builds fine

**Comment by liborm85** [comment]
Memory limit in production will probably be almost "zero". Increase memory limit in production.

**Comment by dewaleolaoye** [comment]
Okay, thanks. 
Will reach out to DevOps team and give feedback

**Comment by dewaleolaoye** [comment]
this fixed it for me 
```javascript
react-scripts --max_old_space_size=8000 start
```
