### ISSUE TITLE
pdfmake decimal numbering

### ISSUE THREAD

**Issue by srikanthgopu** [bpampuch/pdfmake#2044]

**Comment by liborm85** [comment]
Explain your question.

**Comment by srikanthgopu** [comment]
html data
```
    <ol class="orderedList">
          <li class="orderListItem">one</li>
        <li class="orderListItem">two
            <ol class="orderedList">
                <li class="orderListItem">two-one</li>
                <li class="orderListItem">two-two</li>
            </ol>
        </li>
        <li class="orderListItem">three</li>
       </ol>
```
css 

```
.orderedList { counter-reset: item }
.orderListItem { display: block }
.orderListItem:before { 
 content: counters(item, ".") " "; 
counter-increment: item 
}
```
<img width="109" alt="Capture" src="https://user-images.githubusercontent.com/69294217/89515797-3981f900-d7f5-11ea-9798-c4843761f68e.PNG">

iN PDFMAKE

pdfMake.createPdf({
 pageSize: "A4",
 pageOrientation: "portrait",
  styles:{
    'orderedList':{ 
      counter-reset: item 
     },
     'orderListItem':{
        display: "block"
      }
   }
})
But it is not working

**Comment by liborm85** [comment]
Pdfmake doesn't support CSS.

Multilevel number list is not supported now, feature request is here: https://github.com/bpampuch/pdfmake/issues/959
