### ISSUE TITLE
Feature Request: "Use VFS to search for images"

### ISSUE THREAD

**Issue by thefat32** [bpampuch/pdfmake#2045]
Is there any reason the lib needs images dictionary separated from VFS?
Could it be possible to lookup into the VFS for images?

**Comment by liborm85** [comment]
Images dictionary is only next way how to use image in pdf. Of course, images can also be in virtual file system. This is used, for example in [playground](http://pdfmake.org/playground.html) where is available sampleImage.jpg (eg.: `var dd = {content: [{ image: 'sampleImage.jpg' }]}`).

**Comment by thefat32** [comment]
Well now I know what is happening. Images Dictionary admits data url format and vfs admits only base64 string part. This should be mentioned anywhere.

**Comment by thefat32** [comment]
To clarify:

In Images Dictionary you need to use data url format:

`imagesDictionary['redDot'] ="data:image/png;base64, iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="`

In VFS you need to use only the base64 string (we add extension to image name not to loose any metadata):

`vfs['redDot.png'] = "iVBORw0KGgoAAAANSUhEUgAAAAUAAAAFCAYAAACNbyblAAAAHElEQVQI12P4//8/w38GIAXDIBKE0DHxgljNBAAO9TXL0Y4OHwAAAABJRU5ErkJggg=="`
