### ISSUE TITLE
TypeError : cannot read property 'content' of undefined

### ISSUE THREAD

**Issue by Anushapalem7** [bpampuch/pdfmake#2046]
for(var i=0; i<checklists.length; i++){
for(var j=0;j<checklists[i].checklistItems.length;j++){
tempArr.push(
{
description : checklists[i].checklistItems[j].description,
result : checklists[i].checklistItems[j].response.result
}
);
dd.content.push( this.createTable(tempArr, ['description','result']));
}
}

createTable(data, columns) {
return {

table: {
headerRows: 1,
body: this.buildTableBody(data, columns)
}
};
}

buildTableBody(data, columns) {
var body = [];
body.push(columns);
data.forEach(function(row) {
var dataRow = [];
columns.forEach(function(column) {
dataRow.push(row[column]);
})
body.push(dataRow);
});
return body;
}

var dd = {
    content: [ ]
  
}

**Comment by liborm85** [comment]
You call `content` on undefined variable. Not related with pdfmake.
For beginnings with javascript use [stackoverflow.com](https://stackoverflow.com/) or something similar.
