### ISSUE TITLE
how to add space   between dynamically created tables? tried using margin but it is not working.and also want to add title to each table before the table.

### ISSUE THREAD

**Issue by Anushapalem7** [bpampuch/pdfmake#2047]
createTable(data, columns,title) {
return {
text : title,
table: {
margin :{10,40,10,10},
headerRows: 1,
body: this.buildTableBody(data, columns)
}
};
}

buildTableBody(data, columns) {
var body = [];
body.push(columns);
data.forEach(function(row) {
var dataRow = [];
columns.forEach(function(column) {
dataRow.push(row[column]);
})
body.push(dataRow);
});
return body;
}

allTables(checklists)
{

  var tables = [];
  for(var i=0; i<checklists.length; i++){
    this.heading = checklists.title;
    var tempArr =[];
       for(var j=0;j<checklists[i].checklistItems.length;j++){
  tempArr.push(
  {
  description :checklists[i].checklistItems[j].description,
  result :checklists[i].checklistItems[j].response.result
  }
  );
 }
 tables.push( this.createTable(tempArr, ['description','result'],title));  
  }
  return tables;
}

var dd = {
content: [ this.allTables(checklists) ]

}

**Comment by Anushapalem7** [comment]
this is the output I m getting 3 tables, but I need space between every table.
![image](https://user-images.githubusercontent.com/69342414/89769142-83970300-dab1-11ea-9023-d79af28fb0ca.png)

**Comment by liborm85** [comment]
For spaces between tables `margin` can be used:
```js
var dd = {
	content: [
		{
			margin: [0, 20, 0, 0],
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		},
		{
			margin: [0, 20, 0, 0],
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		},		
	]
}
```

Documentation: [here](https://pdfmake.github.io/docs/document-definition-object/margins/)
