### ISSUE TITLE
Image url can't use another link

### ISSUE THREAD

**Issue by teerawat2606** [bpampuch/pdfmake#2048]
1. if i use url from [(https://picsum.photos/)](url)  images can use url example [https://i.picsum.photos/id/237/200/300.jpg?hmac=TmmQSbShHz9CdQm0NkEjx1Dyh_Y984R9LpNrpvH2D_U](url)
2. use another url [https://stg-avatar.dmpcdn.com/p320x320/14/21990014.png?v=3241&fbclid=IwAR2JsUUWb7LZDJfFo2eOS2p7YteyDIvJRHZsuLDqN7nXqSGrwYUwukwqts0](url) can't not use.

var dd = {
 content: [
 {
 image: 'test',
 width: 200
 },
 {
 image: 'test2',
 width: 200
 },
 {
 image: 'test3',
 width: 200
 },
 ],
images: {
 test3:'https://stg-avatar.dmpcdn.com/p320x320/14/21990014.png?v=3241&fbclid=IwAR2JsUUWb7LZDJfFo2eOS2p7YteyDIvJRHZsuLDqN7nXqSGrwYUwukwqts0',
 test:'https://i.picsum.photos/id/237/200/300.jpg?hmac=TmmQSbShHz9CdQm0NkEjx1Dyh_Y984R9LpNrpvH2D_U',
 test2:"https://i.picsum.photos/id/866/200/300.jpg?hmac=rcadCENKh4rD6MAp6V_ma-AyWv641M4iiOpe1RyFHeI"
 }
}

run in [http://pdfmake.org/playground.html](url)

**Comment by liborm85** [comment]
In browser error log:
`Access to XMLHttpRequest at 'https://stg-avatar.dmpcdn.com/p320x320/14/21990014.png?v=3241&fbclid=IwAR2JsUUWb7LZDJfFo2eOS2p7YteyDIvJRHZsuLDqN7nXqSGrwYUwukwqts0' from origin 'http://pdfmake.org' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.`

Website stg-avatar.dmpcdn.com block this request by CORS policy.
