### ISSUE TITLE
using rowspan getting a weird line border in header portion 

### ISSUE THREAD

**Issue by Anand-Paul** [bpampuch/pdfmake#2050]
used the rowspan with fillcolor, getting a weird narrow line in between the rows

like this :
![github2](https://user-images.githubusercontent.com/20293629/90007105-c0cce200-dcb7-11ea-8348-42c90d86c858.png)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by Anand-Paul** [comment]
But in your playground am getting it fine.

`var dd = {
	content: [
        {
            margin: [0, 10, 0, 10],
            table: {
              widths: ['50%', '50%'],
              body:
                  [
                    [
                        {
                          text: 'Objectives',
                          style: 'tableHeader',
                        
                        },
                        {
                          rowSpan: 2,
                          text: 'standards',
                          style: 'tableHeader',
                          margin: [0, 10],
                        },
                    ],
                    [
                       {
                          text: 'example',
                          style: 'tableHeaderSmall',
                        },
                        ''
                    ],
                    [
                        { text: 'an example '},
                        { text: 'an example '}
                    ],
                     [
                        { text: 'an example '},
                        { text: 'an example '}
                    ],
                     [
                        { text: 'an example '},
                        { text: 'an example '}
                    ],
                     [
                        { text: 'an example '},
                        { text: 'an example '}
                    ]
                ],
            },
            layout: {
            
            	hLineWidth: function (i, node) {
					return i === 0 || i === 1 ? 0 : 2;
				},
				vLineWidth: function (i, node) {
					return 2;
				},
				hLineColor: function (i, node) {
					return i === 0 || i === 1 || i === node.table.body.length
                    ? '#6400E4'
                    : '#FFFFFF';
				},
				vLineColor: function (i, node) {
					return i === 0 || i === node.table.widths.length ? '#6400E4' : '#FFFFFF'
				},
			
				paddingLeft: function(i, node) {
				    return 10 },
				paddingRight: function(i, node) {return 10 },
				paddingTop: function(i, node) { return i === 0 ? 5 : i === 1 ? 0 : 10 },
				paddingBottom: function(i, node) { return i === 0 ? 0 : i === 1 ? 2 : 10 },
				fillColor: function (rowIndex, node, columnIndex) { return rowIndex === 0 || rowIndex === 1 ? '#6400E4' : '#FAFBFB'}
            }
            
        }
	],
	 styles: {
	      tableHeader: {
          alignment: 'center',
          color: '#FFFFFF',
          fontSize: 12,
          bold: true,
          characterSpacing: 0.36,
          fillColor: '#6400E4',
        },
        tableHeaderSmall: {
          fontSize: 10,
          bold: false,
          alignment: 'center',
          color: '#FFFFFF',
          characterSpacing: 0.5,
          fillColor: '#6400E4',
        },
	 }
}`

**Comment by liborm85** [comment]
Then update to latest pdfmake version.

**Comment by Anand-Paul** [comment]
ok, one more doubt is there any way to call fonts from local without using vfs

**Comment by Anand-Paul** [comment]
Is there any way to not repeat the header in table without removing the headerRows property ?

**Comment by liborm85** [comment]
`headerRows` property is for repeating header row on each page.
