### ISSUE TITLE
Will there be a Deno.js port of pdfmake?

### ISSUE THREAD

**Issue by suchislife801** [bpampuch/pdfmake#2059]
Deno runtime is awesome and it would be great to use.

**Comment by liborm85** [comment]
Port is not planned.

**Comment by suchislife801** [comment]
Deno has a compatibility layer for node. Can you at least provide an example?

**Comment by liborm85** [comment]
Is this more of a question on deno.js support?

**Comment by suchislife801** [comment]
Well, I have noticed you have some examples on the site that use Type Script so I thought, since Deno is virtually the same as JS, pdfmake could be ported with little to no change in the code. 

pdfmake is literally the best PDF generator out there and Deno is the best Javascript/Typescript runtime out there.
