### ISSUE TITLE
Alignment Left and Right in same cell

### ISSUE THREAD

**Issue by Kraysh** [bpampuch/pdfmake#2060]
I'm trying to align the **$** to the left, and the **2.10** to the right, but it doesn't work.

Code:
``` 
{
  text: [
    { text: '$', alignment: "left", bold: true },
    { text: '2.10', alignment: "right", italics: true}
  ]
},
```

Result:
![image](https://user-images.githubusercontent.com/31409782/91613381-cb44d800-e955-11ea-8793-a0480d0f9605.png)

Expected (made in html): 
![image](https://user-images.githubusercontent.com/31409782/91613463-f2030e80-e955-11ea-9133-9cdffe87a099.png)

**Comment by DivGolakiya** [comment]
One thing you can do is giving colspan to header and create 2 cells on another lines and give them separate alignment

**Comment by marmik18** [comment]
@Kraysh you can do this by using `columns` inside a table value

example for [playground](http://pdfmake.org/playground.html):
```
var dd = {
	content: [
		{
			style: 'tableExample',
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					[
    				    {
                            columns:[
                                {
                                    text:"$",
                                    alignment:"left"
                                },
                                {
                                    text:"100",
                                    alignment:"right"
                                }
                            ]
                         }, 
    				    'Value 2', 
    				    'Value 3'
    				]
				]
			}
		},
	],
}
```
