### ISSUE TITLE
measure elements before using createPdf

### ISSUE THREAD

**Issue by askeyt** [bpampuch/pdfmake#2064]
Hi there,

I'm looking to redistribute content within my doc def based on certain conditions.. To do so I'd like to be able to calculate the height of certain elements before they are actually rendered using createPdf.

Can anyone point me in the right direction, perhaps with an example of how I could use some of the internal functions?

I've currently got a solution but it relies upon calling createPdf multiple times and hooking into the pageBeforeBreak - while it works - I assume something a little more elegant is possible.

Any help would be appreciated :)

**Comment by liborm85** [comment]
This pdfmake doesn't support.
