### ISSUE TITLE
pdfMake / html2canvas is way too big for PDF output, how to resize?

### ISSUE THREAD

**Issue by HennDev** [bpampuch/pdfmake#2065]
I'm trying to convert a section of my HTML page into a PDF file. I don't want the whole page because it contains buttons, etc. that aren't necessary.

So I created a div that has a height 0 and adding the content I need to print into the underlying div then removed elements and printed. All my code is below. It works well but the pdf is WAY too zoomed in and I can't fix it. I've attached my code and resulting pdf output below. I've tried so many different settings. Does anyone have tips?

```js
<div style="overflow: hidden; height: 0;">
  <div id="mainClone"></div>
</div>


function printPDF()
{


html2canvas($('#mainClone'), {
        onrendered: function (canvas) {
            var data = canvas.toDataURL();
            var docDefinition = {
                pageSize: {
                    width: 1000,
                    height: 'auto'
                },
                content: [{
                    image: data,
                    //width: width,
                    //height: height,
                }],
                pageSize: 'letter',
                pageOrientation: 'landscape',
                pageMargins: [ 5, 5, 5, 5 ],
            };
            pdfMake.createPdf(docDefinition).download("test.pdf");
        }
    });

}

$('#PrintPDF').click(function () {
    $('#mainClone').html($('#main').html());
    $('#mainClone').find(".calendar-prev").hide();
    //remove more html elemnent we don't need

    printPDF();
});
 ```

![Screen Shot 2020-09-08 at 3 22 44 PM](https://user-images.githubusercontent.com/47605421/92525214-0c0bdf00-f1e9-11ea-9288-33ad2d28d56d.png)

**Comment by liborm85** [comment]
Attach runnable example on [jsfiddle.net](https://jsfiddle.net/) or another.
