### ISSUE TITLE
Best way to use pageNumber in a body?

### ISSUE THREAD

**Issue by naknode** [bpampuch/pdfmake#2070]
I am trying to get the standard "Page 1 of XXX" in the body of the table because my header is longer than 1 line. 

(Can you have tables in headers?)

Is there a way to easily number pages in the content without use pageReference?

**Comment by liborm85** [comment]
Yes, you can use `header` or `footer` functions where are variables currentPage and pageCount, see [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/headers-footers/).
