### ISSUE TITLE
Authenticated URLs for images

### ISSUE THREAD

**Issue by humphreyja** [bpampuch/pdfmake#2071]
The current API for fetching images does not allow for passing headers with it, only the path. This is important for loading authenticated images, like a User's profile image for example. Additionally, we cannot pass the token via a get param because that defeats the purpose of encrypted SSL requests (the url is still visible). This is why we pass headers. 

I propose a slight change to the API that allows for passing in an object containing the URL and headers for the image.  Additionally, relative url paths should also be allowed. If I pass a path like `/path/to/image.jpg`, shouldn't these all be resolved into web requests?

I'll have a PR that adds this support in just a second.

Here's a summary of the images API change.
```
Images: {
    mystringimage: 'https://example.com/image.jpg',
   + myrelativeimage: '/image.jpg',
   + myauthimage: {
         url: '/user/profile.jpg'
         headers: {
            Token: '1234',
        }
     }
}
```

**Comment by liborm85** [comment]
Released in version 0.2.5.
