### ISSUE TITLE
Cannot download() or open() docDef that has 'text' fields

### ISSUE THREAD

**Issue by nforbus** [bpampuch/pdfmake#2073]
**EDIT:**  Turns out its not about the columns.  It's about specifying text fields..  I was able to use 2 columns that have 'image' types, but when I switched it to 'text' with some dummy text, thats when it broke.  I removed the 'text' type and just left a column with a string, but that also breaks it...

Chrome version:  85.0.4183.102

Code being used;

```              
                    var docDefinition = {
                        content: [
                            {
                                columns: [
                                    { text: 'Text1' },
                                    { text: 'Image1' },
                                ],
                            },
                            {
                                columns: [
                                    { text: 'Text2' },
                                    { text: 'Image2' },
                                ],
                            },
                        ],
                    };

                    pdfMake.createPdf(docDefinition).download('testFile.pdf');
```

It works fine when I do something simple that doesn't use columns.  The second I throw columns in the mix, it doesn't download anything.  It also does not open in a new window if I switch to using .open() instead of download.  No error message obviously.  It works just fine in playground.

**Comment by liborm85** [comment]
Are you using the latest version of pdfmake? Try update.
If that doesn't help attach example of reproduce issue runnable on [jsfiddle.net](https://jsfiddle.net/) (or another).

**Comment by nforbus** [comment]
I'm using the latest version.

Here's a jsfiddle where it doesn't work even with a simple implementation that just uses a string.  Tested it both on my work computer and my home computer.

https://jsfiddle.net/qa8wkmec/

**Comment by liborm85** [comment]
> No error message obviously.

In browser console is this error:
`Uncaught (in promise) File 'Roboto-Regular.ttf' not found in virtual file system`

Is necessary to follow [documentation](https://pdfmake.github.io/docs/0.1/getting-started/client-side/) where is described how to use pdfmake.

Font is not imported. Correct use: https://jsfiddle.net/w2nxtfjd/
