### ISSUE TITLE
Error while converting a span tag with text-decoration underline and line-through

### ISSUE THREAD

**Issue by vcomplyRahul** [bpampuch/pdfmake#2074]
While converting one of the html docs, the library fetched an error saying **Unkown decoration : underlinelineThrough**
`<span style="font-weight: bold;font-style: italic;text-decoration: underline line-through;background-color: #000000">rav</span>`

**Comment by liborm85** [comment]
I don't understand what you're doing, becouse pdfmake doesn't support HTML or CSS.
Possible values for `decoration` is `underline`, `overline` and `lineThrough`.
