### ISSUE TITLE
Dynamic page margins?

### ISSUE THREAD

**Issue by naknode** [bpampuch/pdfmake#2075]
I have a piece I want to  insert at the bottom into the footer and only show on the 1st page.

So I utilize the footer function and show it... and then adjust the `pageMargins` accordingly. However, these page margins only apply to 1st page only... 

Is there any way around this so I can only have this piece of table show on 1st page? Can I dynamically change the pageMargins for 1 page ...?

**Comment by liborm85** [comment]
Duplicate: https://github.com/bpampuch/pdfmake/issues/368

This feature is WIP in PR https://github.com/bpampuch/pdfmake/pull/1972.
