### ISSUE TITLE
core-js@2.6 deprecated

### ISSUE THREAD

**Issue by valentijnscholten** [bpampuch/pdfmake#2076]
during npm/yarn install:
``
warning pdfmake > pdfkit > fontkit > babel-runtime > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
``

**Comment by liborm85** [comment]
> warning pdfmake > pdfkit > [**fontkit**](https://github.com/foliojs/fontkit) > babel-runtime > core-js@2.6.11

https://github.com/foliojs/fontkit/issues

**Comment by valentijnscholten** [comment]
sorry, too fast...

**Comment by valentijnscholten** [comment]
https://github.com/foliojs/fontkit/issues/219
