### ISSUE TITLE
Please Update the documentation by removing gulp

### ISSUE THREAD

**Issue by AnmoldeepSinghGill** [bpampuch/pdfmake#2079]
As I was reading the documentation on how to the 14 standard fonts on the client-side, I came across an issue of gulpfile no longer present in the project repository that I cloned using the commands given, So I was not able to make a new "vfs_fonts.js" for these fonts and also same for the custom fonts. 

So could you please update the documentation as it is confusing for the visitor on how to use new fonts in pdfmake, as we can no longer make the custom fonts "vfs_fonts.js" file using the "gulp buildFonts" command as gulp and gulpfile.js are no longer present in the project repository. I had to run "gulp --gulpfile build-vfs.js" to make the "vfs_fonts.js" file containing my fonts.

This is the  documentation page I was following:

https://pdfmake.github.io/docs/0.1/fonts/standard-14-fonts/#use-in-pdfmake-on-client-side

**Comment by liborm85** [comment]
Fixed git clone command in documentation by commit https://github.com/pdfmake/docs/commit/5c771aee45716604649be698c398e3e77beafd62.
