### ISSUE TITLE
pdfmake not working with latest build files

### ISSUE THREAD

**Issue by OGsoundFX** [bpampuch/pdfmake#2081]
Hello,
I am having trouble making pdfmake work with the latest versions of the build files (pdfmake.js, and vfs_fonts.js)

```
var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

Error message:
```
pdfMake.vfs = vfsFonts.pdfMake.vfs
                               ^

TypeError: Cannot read property 'vfs' of undefined
```

It is working with 0.1.68 version and these 2 particular files:
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/pdfmake.min.js
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.68/vfs_fonts.js

But not with the latest source files.
It's OK I can use the older build files, but I feel it would be better to make my app work with the latest build files.
Thanks!

**Comment by liborm85** [comment]
Lastest pdfmake versions is 0.1.68 and with that it works. Explain your question.

**Comment by OGsoundFX** [comment]
The first line of the pdfmake.js file in the build (https://github.com/bpampuch/pdfmake/blob/master/build/pdfmake.js), the first line is:
`/*! pdfmake v0.2.0-alpha.0, @license MIT, @link http://pdfmake.org */`

Isn't that the pdfmake version?

So my question is: with this pdfmake.js file, my program doesn't work, but it works fine with the 0.1.68 version.
Sorry for the confusion.

**Comment by liborm85** [comment]
You download a version in development from https://github.com/bpampuch/pdfmake/tree/master, and README say:
> #### This is unstable master branch for version 0.2.x, for stable version 0.1.x see [branch 0.1](https://github.com/bpampuch/pdfmake/tree/0.1).


This version cannot be used in production, is under development and not available documentation. Use latest released version.

**Comment by OGsoundFX** [comment]
Got it!
Thanks a lot for your help!
