### ISSUE TITLE
Can't add header with image and text.

### ISSUE THREAD

**Issue by eestein** [bpampuch/pdfmake#2082]
Hi, I've read a lot of issues here asking how to add images on headers and even one where it was recommended to use a table, but I can't get it to work. If I add only the image centered, it works. If I add only the text, it works. When I try to add both, it stops working. It'll either show only the text or the image. Also, when the image is shown, even if I add margins, the content's text starts beneath the image. Here's my latest attempt:

```ts
function(currentPage, pageCount, pageSize): Content {
    if (currentPage <= 1) {
        return [];
    }

    return {
        table: {
            widths: ['*', 30],
            body: [
                [
                    { image: 'companyLogo', fit: [100, 60] },
                    { text: `${currentPage}/${pageCount}`, alignment: 'right', fontSize: 10 }
                ],
            ]
        },
        margin: [0, 15, 40, 0]
    };
}
```

This is the output:
![Screen Shot 2020-09-28 at 15 53 57](https://user-images.githubusercontent.com/2049255/94473995-5c041300-01a3-11eb-9ebf-1161072081a9.jpg)

I'm trying to have a header with a centered image and the page counter aligned to the right.

Could anyone please help me out?

**Comment by liborm85** [comment]
I don't see any problem:
```js
var dd = {
    pageMargins: [ 40, 100, 40, 60 ],
    header: function(currentPage, pageCount, pageSize) {
        //if (currentPage <= 1) {
        //    return [];
        //}
    
        return {
            table: {
                widths: ['*', 30],
                body: [
                    [
                        { image: 'sampleImage.jpg', fit: [100, 60] },
                        { text: `${currentPage}/${pageCount}`, alignment: 'right', fontSize: 10 }
                    ],
                ]
            },
            margin: [0, 15, 40, 0]
        };
    },
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]	
}
```

**Comment by eestein** [comment]
Well, you added `pageMargins`. I didn't have that. If you remove that, the output is the same as shown on my issue description. Is that a requirement?

**Comment by liborm85** [comment]
Yes, for header show margin must be set to a sufficient size, which is required by header.

**Comment by eestein** [comment]
oh ok, thank you!
