### ISSUE TITLE
Inline styling for template Literals

### ISSUE THREAD

**Issue by NathBabs** [bpampuch/pdfmake#2084]
Is there inline styling for template strings in **PDFmake**. I am trying to style some texts within the string but didn't find any support for it. So my question is, how do I make some texts within this template bold.

**Comment by liborm85** [comment]
Styling is described in [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/styling/).

If something is not clear, attach example of problem.

**Comment by NathBabs** [comment]
This is an ordered list, in template strings, how do i make bold **typesetting** in the first, **roots** in the second and **majority** in the third.

```
{
                ol: [
                    `Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's   standard dummy text ever since the 1500s, when an **unknown** printer took a galley`,
                    `"Contrary" to popular belief, Lorem Ipsum is not simply random text. It has "roots" in a piece of classical Latin literature from 45 BC, making it over 2000 years old.`,
                   `There are many variations of passages of Lorem "**Ipsum**" available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable.`
                        ]
}
 
```

**Comment by liborm85** [comment]
As already mentioned this is in [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/styling/).

Simple example:
```js
var dd = {
     content: [
        {
            text: [
                'Normal text ',
                { text: 'bold text ', bold: true },
                'normal text.'
            ]
        }		
     ]
}
```
