### ISSUE TITLE
draw line

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2085]
How to draw line after table in body part?

**Comment by liborm85** [comment]
Simple example:
```js
var dd = {
	content: [
		{
			style: 'tableExample',
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		},
		{canvas: [{ type: 'line', x1: 0, y1: 5, x2: 595-2*40, y2: 5, lineWidth: 3 }]}
	]
	
}
```

**Comment by DivGolakiya** [comment]
while creating line by this, when i generate PDF it creates auto pagebreak and alignment gets scattered.

this is part of my code:
content: [
                {
                    // pageBreak: 'before',
                    style: 'table',
                    margin: [ 0, 10, 0, 0 ],
                    layout: {
                              defaultBorder: false,
                              paddingLeft(i: any, node: any) { return 0.1; },
                              paddingRight(i: any, node: any) { return 0.1; },
                              paddingTop(i: any, node: any) { return 2; },
                              paddingBottom(i: any, node: any) { return 0.5; },
                            },
                    table:
                    {
                      headerRows: 0,
                      widths: [ '15%', '4%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '6%', '5%' ],

                    body: Tbody1,
                    },
                },
                {
                  canvas: [
                    {
                      type: 'line',
                      x1: 0, y1: 15,
                      x2: 790, y2: 15,
                      lineWidth: 1,
                    },
                  ]
                },
                {
                    // pageBreak: 'before',
                    style: 'table',
                    layout: {
                              defaultBorder: false,
                              paddingLeft(i: any, node: any) { return 0.5; },
                              paddingRight(i: any, node: any) { return 0.5; },
                              paddingTop(i: any, node: any) { return 2; },
                              paddingBottom(i: any, node: any) { return 0.5; },
                            },
                    table:
                    {
                      headerRows: 0,
                      widths: [ '15%', '4%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '5%', '6%', '5%' ],

                    body: Tbody2,
                    },
                },
                {
                  canvas: [
                    {
                      type: 'line',
                      x1: 0, y1: 15,
                      x2: 790, y2: 15,
                      lineWidth: 1,
                    },
                  ]
                },
                {
                    // pageBreak: 'before',
                    style: 'table',
                    margin: [ 0, 10, 0, 0 ],
                    layout: {
                              defaultBorder: false,
                              paddingLeft(i: any, node: any) { return 2; },
                              paddingRight(i: any, node: any) { return 2; },
                              paddingTop(i: any, node: any) { return 2; },
                              paddingBottom(i: any, node: any) { return 0.5; },
                            },
                    table:
                    {
                      headerRows: 0,
                      widths: [ '*' ],

                    body: Tbody3,
                    },
                },
               ],

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by DivGolakiya** [comment]
While i use canvas in header or footer section, it does not give me auto page break but when i use it in content area it creates auto page break on PDF which pdfmake has generated.
p.s.: while using buttons from navbar it gives me same output as pdfmake shows but while generating PDF from custom button which i generate by angular it gives me PDF with auto page break on canvas.
