### ISSUE TITLE
How do i install times new roman?

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2086]

**Comment by liborm85** [comment]
see [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/)

**Comment by DivGolakiya** [comment]
i have tried as same as documentation but not working.

**Comment by liborm85** [comment]
No information. No answer.

**Comment by DivGolakiya** [comment]
i have tried putting all 4 .ttf files in examples/fonts folder and declaring .ts file with style font but not working.
