### ISSUE TITLE
Can't apply proportie alignment in styles

### ISSUE THREAD

**Issue by desintrinski** [bpampuch/pdfmake#2087]
When I add alignment in styles I got an error in createPdf function.

![image](https://user-images.githubusercontent.com/17813183/94676805-d18ef100-0313-11eb-93fd-006fadc99654.png)

![image](https://user-images.githubusercontent.com/17813183/94676450-3f86e880-0313-11eb-8ca2-d778f7c4a02e.png)

I'm using Angular 9.1.12 and previous I need to change import to this:
`import * as pdfMake from "pdfmake/build/pdfmake";`
`import * as pdfFonts from 'pdfmake/build/vfs_fonts';`
`(<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;`

**Comment by liborm85** [comment]
Feature request for definition file d.ts is here: https://github.com/bpampuch/pdfmake/issues/525. Not supported now.

Your d.ts definition you have from another source, ask him.
