### ISSUE TITLE
Define width of column as auto don't work

### ISSUE THREAD

**Issue by desintrinski** [bpampuch/pdfmake#2088]
I'm trying to write two lines of text, in wich line has half of text bold and other normal, like this:

**Bold Text 1:** Normal text 1
**Bold Text 2:** Normal text 2

I'm doing this:

![image](https://user-images.githubusercontent.com/17813183/94716551-ecc72400-0346-11eb-9b01-cce53711ac39.png)

But I got this:

![image](https://user-images.githubusercontent.com/17813183/94716620-09fbf280-0347-11eb-8552-196a2c40f3d3.png)

Is there any way to reduce the space between bold text and normal text? I thought that bold text width = 'auto' works, but it didn't take any effect.

**Comment by liborm85** [comment]
Example:
![image](https://user-images.githubusercontent.com/1298652/94820133-640cbe80-0400-11eb-84ff-d6d4ac453b7a.png)

Output:
![image](https://user-images.githubusercontent.com/1298652/94820220-7edf3300-0400-11eb-9685-9fc3149b99bb.png)
