### ISSUE TITLE
browserify fails with "Cannot find module 'brfs'"

### ISSUE THREAD

**Issue by gr2m** [bpampuch/pdfmake#209]
```
$ node -v && npm -v && browserify -v
v0.10.32
2.1.18
9.0.3
$ npm install pdfmake
$ browserify ./node_modules/pdfmake/src/printer.js -o bundle.js
Error: Cannot find module 'brfs' from '/private/tmp/node_modules/pdfmake/node_modules/pdfkit'
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:46:17
    at process (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:173:43)
    at ondir (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:188:17)
    at load (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:69:43)
    at onex (/usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:92:31)
    at /usr/local/lib/node_modules/browserify/node_modules/resolve/lib/async.js:22:47
    at Object.oncomplete (fs.js:107:15)
```

any idea?

**Comment by gr2m** [comment]
when I install `brfs`

```
$ npm install brfs
```

I get another error

```
$ browserify ./node_modules/pdfmake/src/printer.js -o bundle.js
SyntaxError: Line 63: Unexpected token ILLEGAL while parsing /private/tmp/node_modules/pdfmake/node_modules/pdfkit/js/font.js while parsing file: /private/tmp/node_modules/pdfmake/node_modules/pdfkit/js/font.js
    at Stream.end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/index.js:73:21)
    at _end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:65:9)
    at Stream.stream.end (/usr/local/lib/node_modules/browserify/node_modules/insert-module-globals/node_modules/through/index.js:74:5)
    at Transform.onend (/usr/local/lib/node_modules/browserify/node_modules/module-deps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523:10)
    at Transform.g (events.js:180:16)
    at Transform.emit (events.js:117:20)
    at /usr/local/lib/node_modules/browserify/node_modules/module-deps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:965:16
    at process._tickCallback (node.js:419:13)
```

**Comment by jthoenes** [comment]
Currently browserify is not supported by pdfmake. I have no experience with it, so I don't know what to do.

Happy to get a pull request.

**Comment by janl** [comment]
These issues are relevant:

https://github.com/devongovett/pdfkit/issues/248
https://github.com/substack/brfs/issues/23

**Comment by janl** [comment]
@gr2m the command you pasted works, when you `npm install bras@1.0.2` instead of the latest version.

**Comment by bpampuch** [comment]
Gregor - we don't use brfs, have you changed anything ?

**Comment by igregson** [comment]
Trying to get pdfmake to work with Browserify... @janl, thanks for the pointer on installing drfs at the specific version. That did the installation trick for me. 

Now I'm getting `undefined is not a function` error when trying to call `createPdf`. 

@bpampuch, your instructing to require `./src/browser-extensions/virtual-fs.js:fs`... the `browser-extensions` is excluded from the NPM package, which of course means it's not possible to require it when installed from NPM. Thoughts?

**Comment by igregson** [comment]
Alright... regard all of the above. Simply adding the two client-side scripts via script tags did the trick. Somehow my Browserified scripts are still able to see the global variables. Seems I was making it a bit too complicated :)

**Comment by igregson** [comment]
PS: Why does this work? How are my calls to `pdfMake` not returning undefined, as they usually seem to with scripts attached to the global name space? 

Is it simply due to attaching pdfMake to the window object? (as below from `vfs_fonts.js`)?

```
window.pdfMake = window.pdfMake || {}; window.pdfMake.vfs
```

**Comment by bpampuch** [comment]
we're using webpack now, to build pdfmake you can run ```gulp build```

**Comment by dudunato** [comment]
I'm having the same issue trying to use pdfmake with npm. How can I make it works?

**Comment by gr2m** [comment]
@dudunato when you say `npm`, do try to use it in the browser using browserify? Because that’s not supported, as stated above: https://github.com/bpampuch/pdfmake/issues/209#issuecomment-75707166
