### ISSUE TITLE
Newspaper Style Columns

### ISSUE THREAD

**Issue by nikolnikov** [bpampuch/pdfmake#2093]
I’ve been researching for a while and trying to “hack” PDFMake to do “snaking” newspaper style columns. PDFKit seems to do this correctly, and given PDFMake is based off PDFKit, I’m curious if this is something that is doable?

Also, an example of what I’m referring to is two columns, fixed heights, the content of the first column extends to the bottom of the first column, and then snakes (or wraps) to the top of the second column.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/604

**Comment by liborm85** [comment]
Snaking columns is not supported by pdfmake now. Issue https://github.com/bpampuch/pdfmake/issues/604 is feature request.

**Comment by nikolnikov** [comment]
Thank you for your response. I understand snaking columns isn't supported by PDFMake now, which is why I made the request. My question was: is there any plan to eventually support it? Is it something being considered or can we expect it to never be an option in PDFMake? Your response is very much appreciated.
