### ISSUE TITLE
Question: colorful emoji

### ISSUE THREAD

**Issue by aosyatnik** [bpampuch/pdfmake#2095]
Hi, I've seen this question: https://github.com/bpampuch/pdfmake/issues/1214.

I have almost a similar question. I want to display emoji in pdf, but this time colorful images. In the question, that I mentioned above it's suggested to use OpenSansEmoji font, which is a great solution but it lacks colors.

I've tried with Noto font from here: https://github.com/googlefonts/noto-emoji
and with apple font from here: https://github.com/samuelngs/apple-emoji-linux
But they both have the same issue, which is this:
```
Exception: TypeError: Cannot read property 'advanceWidth' of null
Stack: TypeError: Cannot read property 'advanceWidth' of null
    at new EmbeddedFont (C:\Projects\HFP\HFP.Backend.Pdf\node_modules\pdfkit\js\pdfkit.js:2974:41)
    at Function.open (C:\Projects\HFP\HFP.Backend.Pdf\node_modules\pdfkit\js\pdfkit.js:3251:12)
    at PDFDocument.font (C:\Projects\HFP\HFP.Backend.Pdf\node_modules\pdfkit\js\pdfkit.js:3306:33)
    at FontProvider.provideFont (C:\Projects\HFP\HFP.Backend.Pdf\node_modules\pdfmake\src\fontProvider.js:62:58)
```

That's how I've set up font:
```ts
   const fontDescriptors = { 
        Roboto: {
            normal: 'fonts/Roboto-Regular.ttf',
            bold: 'fonts/Roboto-Medium.ttf',
            italics: 'fonts/Roboto-Italic.ttf',
            bolditalics: 'fonts/Roboto-MediumItalic.ttf'
        },
        colorEmoji: {
            normal: 'fonts/AppleColorEmoji.ttf'
        }
    };
    const printer = new pdfMakePrinter(fontDescriptors);
    const doc = printer.createPdfKitDocument(docDefinition);
```

docDefinition is something like this:
```json
...
{
    "text": "❤ 😀 😇 emoji test message",
    "fontSize": 12,
    "style": "page",
    "font": "colorEmoji"
}
...
```

Anything I'm doing wrong here?

**Comment by liborm85** [comment]
Pdfmake use for rendering PDF document [pdfkit library](https://github.com/foliojs/pdfkit). Pdfkit doesn't support colored fonts see https://github.com/foliojs/pdfkit/issues/575 and https://github.com/foliojs/pdfkit/issues/314.

**Comment by aosyatnik** [comment]
I see, thanks.
