### ISSUE TITLE
Repeat content on pages

### ISSUE THREAD

**Issue by mujgancihan** [bpampuch/pdfmake#2096]
Hi,

I have an application in Angular and I try to create a pdf file using pdfMake.
This file has 2 main columns. Left column includes static data; an image and 2 tables and it has enough space in only 1 page. The right column is getting created dynamically depending on data.
So file can have multiple pages because of the right column.
I need to repeat the left the column content on all pages if right column is splitting in multiple pages.
How can i do that?

Thanks in advance

Basic template is something like that;

var dd = {
	content: [
{
          table: {
            widths: [170, '*'],
            body: [
              [{text: '', style: ''}, {}],
              [
              {
                table: {
                  body: [['left column; images and tables']]
                },
                layout : 'noBorders'
              },
              {
                table: {
                  dontBreakRows: true,
                  body: [
                      ['aa'],
                  ['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],
                  ['aa'],['aa'],['aa'],
                  ['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],
                  ['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],
                  ['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],
                  ['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],['aa'],
                  
                  ]
                }
              }
            ]
            ],
          },
        }]
	
}

**Comment by liborm85** [comment]
No, that's not possible.
