### ISSUE TITLE
variable with table definition not rendered as part of document

### ISSUE THREAD

**Issue by mbintex** [bpampuch/pdfmake#2099]
Hi,

I have a variable passed from PHP to Javascript containing this

`{layout: 'lightHorizontalLines',
table: {widths: ['*', '*', 100],
headerRows: 1,
body: [
['Umlageart', 'Berechnung', {text: 'Anteil', alignment: 'right'}],
['Quadratmeter',{text:'(71,00 QM * 365 Tage) / (314,00 Gesamt-QM * 365 Gesamt-Tage)'},
{text: '22,61%', alignment: 'right'}],
['Einheiten',{text:'(1 Einheit * 365 Tage) / (5 Gesamt-Einheiten * 365 Gesamt-Tage)'},{text:
'20,00%', alignment: 'right'}],
['Personen',{text:'(1,00 Personen * 365 Tage) / (7,00 Gesamt-Personen * 365 GesamtTage)'},{text: '14,29%', alignment: 'right'}],]
}}
`

I am adding this to the document definition with

`dd.content.push(mytablevariable)`

Rendering takes place and I get a PDF with no errors on the way.

But the PDF contains no table, the above code is rendered as plain text.

What do I have to change to get a table rendering?

**Comment by liborm85** [comment]
I tested your example:
```js
var dd = {
	content: [
	]
}

var mytablevariable = {layout: 'lightHorizontalLines',
table: {widths: ['*', '*', 100],
headerRows: 1,
body: [
['Umlageart', 'Berechnung', {text: 'Anteil', alignment: 'right'}],
['Quadratmeter',{text:'(71,00 QM * 365 Tage) / (314,00 Gesamt-QM * 365 Gesamt-Tage)'},
{text: '22,61%', alignment: 'right'}],
['Einheiten',{text:'(1 Einheit * 365 Tage) / (5 Gesamt-Einheiten * 365 Gesamt-Tage)'},{text:
'20,00%', alignment: 'right'}],
['Personen',{text:'(1,00 Personen * 365 Tage) / (7,00 Gesamt-Personen * 365 GesamtTage)'},{text: '14,29%', alignment: 'right'}],]
}}

dd.content.push(mytablevariable);
```

And output is correct:
![image](https://user-images.githubusercontent.com/1298652/96009719-4b10fe00-0e41-11eb-8937-63011c8890dd.png)

**Comment by mbintex** [comment]
Yes, the table code is correct.

But I get no rendering, only the code as text inside my document.

I guess the variable is not recognized as an object.

If I write

`var mytablevariable="{layout: 'lightHorizontalLines', table: {widths: ['*', '*', 100], headerRows: 1, body: [['Umlageart', 'Berechnung', {text: 'Anteil', alignment: 'right'}],['Quadratmeter',{text:'(71,00 QM * 365 Tage) / (314,00 Gesamt-QM * 365 Gesamt-Tage)'},{text: '22,61%', alignment: 'right'}],['Einheiten',{text:'(1 Einheit * 365 Tage) / (5 Gesamt-Einheiten * 365 Gesamt-Tage)'},{text:'20,00%', alignment: 'right'}],['Personen',{text:'(1,00 Personen * 365 Tage) / (7,00 Gesamt-Personen * 365 GesamtTage)'},{text: '14,29%', alignment: 'right'}],]}}";

`

and push it to the content, I get no rendering, I get the code in the PDF.

I am a Javascript newbie :-)

**Comment by mbintex** [comment]
following this [https://stackoverflow.com/questions/1086404/string-to-object-in-js](url)

and rushing my string through an "eval" with

`eval('var umlagefaktoren='+string);`

I get the table rendered

**Comment by liborm85** [comment]
Variable `mytablevariable` cannot be a string but JSON, see https://www.w3schools.com/js/js_json_intro.asp
