### ISSUE TITLE
documentation: "text" literally has to be "text"

### ISSUE THREAD

**Issue by mg1075** [bpampuch/pdfmake#21]
Perhaps it would be worth noting in the documentation how the "text" value has to be converted to a a string if the value is not a string? 

The reason I raise the issue is because I had a variable whose value was an integer. When I had the variable in the output as `text: myVar`, where `myVar` was a number, no output was generated. But when I had `text: myVar.toString()`, the integer was converted to a string, and then was generated as output in the pdf.

**Comment by hujhax** [comment]
Yup, I stubbed my toe on this one too

**Comment by liborm85** [comment]
Fixed by https://github.com/bpampuch/pdfmake/commit/f2dea15b22c7bfa9ad7d612351e178b853ea7678 and https://github.com/bpampuch/pdfmake/commit/f73e3221a4e12a0b2892c659e833e67ec9b5eb06.
