### ISSUE TITLE
Base64 dataURL with custom fonts

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#2100]
We are trying to get base64 string using,

```
var data;
pdfMake.createPdf(docDefinition).getDataUrl(function(dataURL) {
    data = dataURL;
console.log(data);
});
```

The above code perfectly working for default font. When we using custom fonts or the standard fonts which are available by changing vfs-fonts.js file as explained, the data url is not returning with the above code. What is missing here?

**Comment by liborm85** [comment]
Look to error console. There will probably be some exception.

**Comment by mpsbhat** [comment]
> Look to error console. There will probably be some exception.

No error or exception at all found in console. But not getting into the getDataURL function.
Btw, we are using Helvetica font which is available in standard fonts as explained in documentation. Print / Download functions are working correctly.

**Comment by liborm85** [comment]
Create example for reproduce issue on [jsfiddle.net](https://jsfiddle.net/).

**Comment by mpsbhat** [comment]
> Create example for reproduce issue on [jsfiddle.net](https://jsfiddle.net/).

There is error with [jsfiddle](https://jsfiddle.net/mpsbhat/hopfmuve/), so created test files as follows.

1. [Test - new](https://test.saraghsoft.com/testnew.html) - pdfmake v0.2.x
2. [Test - standard fonts](https://test.saraghsoft.com/teststd.html) - pdfmake v0.2.x with standard fonts build
3. [Test - old](https://test.saraghsoft.com/testold.html) - pdfmake v0.1.29

In above tests, the old library gives the dataurl output (see console) whereas the other two didn't.

**Comment by liborm85** [comment]
Version 0.2 has different interface and not released stable version now.

**Comment by mpsbhat** [comment]
> Version 0.2 has different interface and not released stable version now.

So, is the function `getDataUrl()` won't work with v0.2 as of now or any other ways to make it work for v0.2?

**Comment by liborm85** [comment]
0.2 interface: https://github.com/bpampuch/pdfmake/issues/866#issuecomment-487855258

standard ansi fonts in 0.1: https://pdfmake.github.io/docs/0.1/fonts/standard-14-fonts/
