### ISSUE TITLE
Unable to print CMYK svg 

### ISSUE THREAD

**Issue by Wewill** [bpampuch/pdfmake#2101]
Hey team, thank you for your excellent work here. 

**About CMYK in SVG, I tried :**

` ...<style>.a{fill:device-cmyk(1.00, 0.90, 0.25, 0.00) #654e9a;"}</style></defs><title>logo</title><path class="a" d=....`
Not working

`...<style>.a{fill:#654e9a device-cmyk(1.00, 0.90, 0.25, 0.00) ;"}</style></defs><title>logo</title><path class="a" d=...`
Not working

`...</defs><title>logo</title><path fill="#654e9a device-cmyk(1.00, 0.90, 0.25, 0.00)" class="a" d=...`
Not working

`...
{
              svg: ccppm_global.logo_fifam,
              width: dimension,
              fill:'#FF0000',
              color:[100,90,25,0],
              fillColor:[100,90,25,0],
},`
Not working

Do you have an idea ? 

Best regards, Wilhem

**Comment by liborm85** [comment]
Transformation from svg to pdf in pdfmake is via [svg-to-pdfkit library](https://github.com/alafr/SVG-to-PDFKit). Create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).

**Comment by Wewill** [comment]
Hello @liborm85, 

I reopen this ticket : 
Fill CMYK colors in PDFMake is rendering as it should without a #Hex color.

Here you can see an example of `<svg>` with `fill="cmyk(...)"` colors working on via svg-to-pdfkit library.
https://github.com/alafr/SVG-to-PDFKit/issues/129

Best regards, Wilhem

**Comment by Wewill** [comment]
I just tried in playground to be certain : 

```
var svg = '<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 480 360"><title>CMYK BOXES</title><style>.red_cmyk {fill:cmyk(0, 85, 65, 0)} .blue_cmyk {fill:cmyk(90, 55, 0, 0)}</style><rect x="10" y="10" width="460" height="340" fill="none" stroke="grey"/><text x="40" y="40" font-size="30" fill="cmyk(0, 85, 65, 0)">THESE SHOULD BE RED:</text><rect x="40" y="50" width="120" height="120" fill="cmyk(0, 85, 65, 0)"/><rect x="180" y="50" width="120" height="120" style="fill:cmyk(0, 85, 65, 0)"/><rect x="320" y="50" width="120" height="120" class="red_cmyk"/><text x="40" y="210" font-size="30" fill="cmyk(90, 55, 0, 0)">THESE SHOULD BE BLUE:</text><rect x="40" y="220" width="120" height="120" fill="cmyk(90, 55, 0, 0)"/><rect x="180" y="220" width="120" height="120" style="fill:cmyk(90, 55, 0, 0)"/><rect x="320" y="220" width="120" height="120" class="blue_cmyk"/></svg>';

var dd = {
    content: [
        {
            svg: svg
        },
    ],
};
```

![Capture d’écran 2020-11-18 à 09 28 51](https://user-images.githubusercontent.com/3178443/99505127-b5591900-2980-11eb-86d0-de3406c2ee8f.png)

**Comment by liborm85** [comment]
On https://alafr.github.io/SVG-to-PDFKit/examples/demo.htm is output same:
![image](https://user-images.githubusercontent.com/1298652/99817928-d58a0300-2b4d-11eb-85a6-c887fdf6175a.png)

**Comment by Wewill** [comment]
Right, @naeem-brikl wants to merge a commit to svg-to-pdfkit. We have to wait.
