### ISSUE TITLE
Format number with 2 decimals

### ISSUE THREAD

**Issue by FrancoFasano** [bpampuch/pdfmake#2104]
Hi team,

I try to show number with 2 decimals.
The DB data are decimal with 2 digits.

PDFmake show numbers as following:

Exemple 1 :
data = 1786.00
pdfmake = 1786

Exemple 2 :
data = 89.30
pdfmake = 89.3

Is there a way to format numbers with always 2 decimals?

**Comment by liborm85** [comment]
javascript formatting can be used:
``js
var x = 89.30;
x.toFixed(2); 
```

Or pass numbers to pdfmake as string.

**Comment by FrancoFasano** [comment]
Thanks for answer,
I pass number as string:
{
"text": "$invoice.subtotal_amount",
}
I don't understand you javascript formatting suggestion, based on my code exemple what will be the right code?
Sorry I'm not a developper, just a PDF rooky ;-)

**Comment by liborm85** [comment]
Example how to format number in javascript for pdfmake:
```js
var x = 123.40

var dd = {
	content: [
		{
			"text":  x.toFixed(2),
		}
	]
	
}
```

**Comment by FrancoFasano** [comment]
many thanks

**Comment by FrancoFasano** [comment]
Hi,
I confused because the amount isn't persisted in DB, it is calculated and automaticly rounded by the application.
What I want to do is to show in PDFMake the amount not rounded, just add decimals.
Is it possible to do that ?

**Comment by liborm85** [comment]
This is not related with pdfmake. For questions about javascript use [stackoverflow.com](https://stackoverflow.com/).
