### ISSUE TITLE
pdfMake cannot see ttf fonts

### ISSUE THREAD

**Issue by wolffle** [bpampuch/pdfmake#2105]
I've got a file structure as follows:

parent/
- fonts/
-- Roboto-Regular.ttf
-- Roboto-Medium.ttf
-- Roboto-Italic.ttf
-- Roboto-MediumItalic.ttf
- pdfMaker.js

So pdfMaker where all the JS code resides is in the same directory as the fonts directory.

I'm pulling in the fonts from the fonts directory as follows:
`const fonts = {
    Roboto: {
      normal: './fonts/Roboto-Regular.ttf',
      bold: './fonts/Roboto-Medium.ttf',
      italics: './fonts/Roboto-Italic.ttf',
      bolditalics: './fonts/Roboto-MediumItalic.ttf',
    },
  };`

But I'm getting "Error: ENOENT: no such file or directory, open './fonts/Roboto-Medium.ttf'" when bold is called.

**Comment by karthikSirsikar** [comment]
What was the problem here ?
