### ISSUE TITLE
Gutter or inside page margins?

### ISSUE THREAD

**Issue by lieuzhenghong** [bpampuch/pdfmake#2106]
I'm looking at 
[Page Dimensions, Orientation and Margins](https://pdfmake.github.io/docs/0.1/document-definition-object/page/)
and it looks like gutter margins (margins on the "inside" of the pages ---right margin for odd-numbered pages, left margin for even-numbered pages) are not yet supported.

Is there any workaround for this?

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/368

**Comment by big-scorpio** [comment]
I am also looking above feature @lieuzhenghong
