### ISSUE TITLE
PDF render new data in stale template 

### ISSUE THREAD

**Issue by Studira** [bpampuch/pdfmake#2107]
The scenario:
I have an Angular 10 application running on a Node 12 instance. I have 4 components that get swapped with an ng-if statement and each one receives data via an RXJS observable. In each component I have an independent Typescript pdf template class that generates a PDF document dynamically and attaches it to a dynamically generated iframe. I use PDFMake as my browser pdf generator.

The problem:
If I render any one of these the first time it renders 100% correct BUT after I rendered the first one, without reloading the page, I then switch to another, all the consecutive templates are based on the first template.

Tested:
Data correctly land in the component. Yes
Component correctly swapped. Yes
Iframe correctly generated and attached. Yes.
Issue exist across browsers. Yes

Correct template
![Screenshot 2020-10-25 at 19 40 34](https://user-images.githubusercontent.com/3531847/97114594-1f6ffc80-16fa-11eb-8e11-34a7a13212ff.png)
Incorrect template
![Screenshot 2020-10-25 at 19 41 07](https://user-images.githubusercontent.com/3531847/97114596-23038380-16fa-11eb-8244-a9a934a12e57.png)

**Comment by liborm85** [comment]
Probably second time you won't regenerate the docDefinition.

**Comment by Studira** [comment]
@liborm85 The docDefinition is generated dynamically:

`private generatePdf(data: any, settings: any) {
        const invoice = new Invoice(data, settings);
        const pdfDocGenerator = pdfMake.createPdf(invoice.template);
        const iframe = this._renderer.createElement('iframe');
        pdfDocGenerator.getDataUrl((dataUrl) => {
            this._renderer.setProperty(iframe, 'src', dataUrl);
            this._renderer.appendChild(this.pdfElement.nativeElement, iframe);
        });
    }`

This line does that:

` new Invoice(data, settings);`

**Comment by liborm85** [comment]
Then there is no problem in pdfmake, but in your code around.

**Comment by Studira** [comment]
@liborm85 Is there a way to clear buffers etc. in pdfmake, I have had another person that used another pdf creator say that the buffer needs to be cleared. I am not sure how Pdfmake library is cached in Node when it is imported. Maybe there is some issue there.

**Comment by liborm85** [comment]
If you use a new docDefinition for each PDF generation, there is no need clear buffers or something else.
