### ISSUE TITLE
Margin is not working

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2110]
Margin is not working in header section. This is my part of code:

header( currentPage: { toString: () => string; }, pageCount: string, pageSize: any ) {
        return [
          [

            { text: [{ text: 'Name of the Unit: ', bold: false, fontSize: 10}, { text: 'Chambal Fertilisers and Chemicals Ltd. (Gadepan II)' }], absolutePosition: { x: 10, y: 18 }, bold: true, fontSize: 10 },
            { text: 'Financial Year: ' + finyear, absolutePosition: { x: 10, y: 32 }, fontSize: 10 },
            { text: 'Period: ' + DBData.Table7[0].cf_qtr, absolutePosition: { x: 10, y: 48 }, fontSize: 10 },
            { text: 'Claim form - XII ( B )', absolutePosition: { x: -10, y: 18 }, fontSize: 10, alignment: 'right', margin: [ 0, 0, 20, 0 ] },
            { text: '( Enclosure to the Payment Claim )', absolutePosition: { x: -10, y: 32 }, fontSize: 10, alignment: 'right', margin: [ 0, 0, 20, 0 ] },
            { text: ' PAGE ' + currentPage.toString() + ' of ' + pageCount, absolutePosition: { x: -10, y: 48 }, fontSize: 10, alignment: 'right', margin: [ 0, 0, 20, 0 ] },

          ],
        ];
      },

**Comment by the-architect** [comment]
@DivGolakiya  can you please fix the formatting of your code? :)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1770
