### ISSUE TITLE
sub and sup

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2112]
i can't use margin in nested text. this is part of my code:

styles: {

        body_r: {
          fontSize: 7,
          alignment: 'right',
          bold: false,
        },
        fontsize: {
          fontSize: 6,
          margin: [ 0, 0, 0, 15 ]
        }
}

{ text: [ { text: this.tofixed(this.DBData.Table2[0].GDF_CAP_POWER, 3) }, { text: '+', style: 'fontsize' } ], style: 'body_r', border: [ true, false, true, false ], rowSpan: 2 },

**Comment by liborm85** [comment]
This is not supported. Feature request is here: https://github.com/bpampuch/pdfmake/issues/1740
