### ISSUE TITLE
Hide empty and/or value=0 table rows

### ISSUE THREAD

**Issue by FrancoFasano** [bpampuch/pdfmake#2113]
Hi team,
I try to hide empty and/or values=0 table rows and :

![Capture du 2020-11-06 14-37-10](https://user-images.githubusercontent.com/32268027/98372409-03dfec80-203e-11eb-9d24-a588c1e6a528.png)

In this case the "Rabais" and "Arrété" line must be hidden as follow:

![Sans titre](https://user-images.githubusercontent.com/32268027/98373067-00993080-203f-11eb-8c53-d18a2680790a.png)
An idea to how do this ?

**Comment by liborm85** [comment]
Simply using pure javascript:
```js
var tableBody = [];
tableBody.push(['Row 1', 'XYZ']);
tableBody.push(['Row 2', 'XYZ']);

if ( condition for row show ) {
    tableBody.push(['Row 3', 'XYZ']);
}

tableBody.push(['Row 4', 'XYZ']);


var dd = {
	content: [
		{
			table: {
				body: tableBody
			}
		},
	]
	
}
```

**Comment by FrancoFasano** [comment]
Many thanks
