### ISSUE TITLE
Canvas element causes incorrect rendering when used more than once or in a loop

### ISSUE THREAD

**Issue by simeon9696** [bpampuch/pdfmake#2123]
I'm trying to generate multiple PDFs **server side**. Each PDF has a certain section that's constant across all PDFs to be generated, `general`. That general section is then separated by a line and then the information specific to that document is loaded in beneath it. 

However, this works great on the first PDF. On the second one the layout breaks completely. 

![image](https://user-images.githubusercontent.com/31748055/98835995-863e2700-2417-11eb-9f96-695b31898844.png)

![image](https://user-images.githubusercontent.com/31748055/98836012-8c340800-2417-11eb-8466-77da746573c0.png)

Here's the MVP:
```
"use strict";
const fs = require("fs");
const PdfPrinter = require("pdfmake");

const fonts = {
  Helvetica: {
    normal: "Helvetica",
    bold: "Helvetica-Bold",
    italics: "Helvetica-Oblique",
    bolditalics: "Helvetica-BoldOblique",
  },
};

const printer = new PdfPrinter(fonts);

const general = [{ text: "This is general text" }];

const first = [{ text: "This is the text for the first pdf" }];

const second = [{ text: "This is the text for the second pdf" }];

const line = [{canvas: [{ type: 'line', x1: 0, y1: 5, x2: 595-2*40, y2: 5, lineWidth: 2 }],margin: [ 0, 10, 0, 10 ]},];


let docDefinition = {
  pageSize: "letter",
  defaultStyle: {
    font: "Helvetica"
  }
};

docDefinition.content = [general,line,first];
let pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('one.pdf'));
pdfDoc.end();


docDefinition.content = [general,line,second];
pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('two.pdf'));
pdfDoc.end();
```

**Comment by liborm85** [comment]
One `docDefinition` variable can be used only once to generate PDF.

**Comment by simeon9696** [comment]
I posted a workaround here: 
https://stackoverflow.com/questions/64790193/canvas-element-causes-incorrect-rendering-when-used-more-than-once-or-in-a-loop/65612433#65612433
