### ISSUE TITLE
load svg in base64 format

### ISSUE THREAD

**Issue by mortenko** [bpampuch/pdfmake#2125]
Hi, 
I'm trying to load svg in base64 but it seems to be not possible ...

Has anyone experience with it ? 

Thanks

**Comment by liborm85** [comment]
Attach example for reproduce issue.

**Comment by mortenko** [comment]
@liborm85 
I serialize DOM svg node into a string using XMLSerializer. I want to insert this svg base64 into pdf document as normal image (based on this example https://pdfmake.github.io/docs/0.1/document-definition-object/images/.)

```js
{
content: [{
  svg:`data:image/svg+xml;base64,${svg}`,  --> svg is  base64 encoded svg node element
  width: 150,
 height: 150 
}]
}
```
Im getting following error: 

pdfmake.js:68678 Uncaught (in promise) Error: SVGMeasure: Error: Non-whitespace before first tag.
Line: 0  in function **parseSVG**.

**Comment by liborm85** [comment]
SVG is not image and is not inserted to document as image. For image is base64 required because images are binary data. For SVG is not required base64 encoding, because it is standard XML.

Use SVG is decribed in documentation https://pdfmake.github.io/docs/0.1/document-definition-object/svgs/
