### ISSUE TITLE
Style function to only bold first line of dynamic data not working

### ISSUE THREAD

**Issue by SutleB** [bpampuch/pdfmake#2127]
I am trying to always have the header be bold, but the 'tables' section of the playground hardcodes the text as {text: 'stuff', style: 'header'}.

```js
var dd = {
	content: [
		{text: 'zebra style', margin: [0, 20, 0, 8]},
		{
			table: {
				body: [
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
					['Sample value 1', 'Sample value 2', 'Sample value 3'],
				]
			},
			style: {
				bold: function (rowIndex, node, columnIndex) {
					return (rowIndex === 0) ? true : false;
				}
			}
		}
	]
}
```

When running this block in the playground, for example, I get every cell in the table as bold instead of only the first row as I'd expect..
Is there a better way to handle this?

**Comment by liborm85** [comment]
No, only `style` in table cell is supported.

**Comment by albertoLGDev** [comment]
still not any way of style the table header working with dynamic data?
