### ISSUE TITLE
Those evil x,y calculations

### ISSUE THREAD

**Issue by kondulak10** [bpampuch/pdfmake#213]
Hello,
I found this library and will use it because of ěščřžýáí supportability. But I think it is much easier to use x, y calculations for automatic converting from html to pdf (I design complex forms in html). I can loop through all elements on page, get their properties and place them immediately to pdf using offset.top and offset.left.

Is it possible to avoid using undeniable good and complex structure you created and use instead of floating, those relative positions, because I dont do that manually. Jquery loops, computes and assings.

So alternative to jsPDF: doc.rect(60, 20, 10, 10); TOP, LEFT Positions?

**Comment by jthoenes** [comment]
Can you explain more? I think I don't get your point.

Can you show some examples?

**Comment by kondulak10** [comment]
Thank you for your response,

Yes. You state that we should "forget about manual x,y calculations and declare document structure". But would it be possible to create whole pdf withtout that structure, and use only x,y calculations? 

The examples are on: https://parall.ax/products/jspdf . This library only place desired element on exact positions x and y. Can I do something similar here?

**Comment by jthoenes** [comment]
Ah, now I understand what you are asking for.

pdfmake is a library which is all about not having to calculate positions. So its probably not the library you are looking for. Maybe take a look at https://github.com/devongovett/pdfkit/ - this is what pdfmake uses internally to get stuff onto the PDF.

**Comment by kondulak10** [comment]
Ah, Ok thank you. I admire the job you made - it is really good!, but I would like to have this feature as well. This tool could still have the structure as it has and then there could be extra elements out of the structure, just positioned directlly to a spot (for others it could serve for fast and minor modifications in document).

It is just my suggestion :)

But I understand your desire, and I will try to create my forms using this.
