### ISSUE TITLE
[Question] delete specific page on generated pdf file

### ISSUE THREAD

**Issue by ifndefdeadmau5** [bpampuch/pdfmake#2134]
Let's say I've created a pdf file contains about 100 pages.
and I want to remove arbitrary page out of those pages (maybe by page number or query the page index by string search, I dunno)
Is it possible? any advices would be appreciated

**Comment by liborm85** [comment]
No, that is not possible. Library is not for editing pdf documents. If you do not want the document to contain specific page do not put its contents to docDefinition.
