### ISSUE TITLE
Swiss QR code with Swiss cross in the middle

### ISSUE THREAD

**Issue by FrancoFasano** [bpampuch/pdfmake#2137]
Hi team,
I'm trying to add the swiss cross in the middle of the QR code as below:
Is it possible to do this with PDFMake ?

![Capture du 2020-11-23 19-16-31](https://user-images.githubusercontent.com/32268027/99999456-797ae500-2dc0-11eb-9127-34792f59cdf5.png)

**Comment by liborm85** [comment]
QR codes with logo is not supported. You can generate own QR using another library and then add it as a PNG image.

**Comment by FrancoFasano** [comment]
Many thanks
