### ISSUE TITLE
Make input valid json

### ISSUE THREAD

**Issue by rogerfar** [bpampuch/pdfmake#2138]
I'm investigating in using PDFMake on the browser and on the server, but I need to be able to store the input "document" as something in the database.

If I have something like this:
```
var dd = {
    "footer": function(currentPage, pageCount) { 
        return { text: 'Invoice #231584 Page ' + currentPage.toString() + '/' + pageCount }
    },
	"content": [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```

I cannot serialize this because of the function, same as using table layouts.

Is there an easy way to make the input document portable?

**Comment by liborm85** [comment]
It depends on your programming language. In javascript you can insert it directly into the code or use [eval](https://www.w3schools.com/jsref/jsref_eval.asp).

**Comment by rogerfar** [comment]
I'm using JS (TS) to create the input "file" but if you use serialization out of the box it will ignore everything that is a function (as functions aren't a part of the JSON standard). 

You can do some trickery with troStringing functions when serializing but it's not optimal.

For now I wrote a wrapper that evals some of the functions (like table layout), but for example the Header and Footer are more difficult as it can return different things.

**Comment by liborm85** [comment]
Yes, this is not simply allowed in javascript for security reasons.
