### ISSUE TITLE
Remove line if value is NULL

### ISSUE THREAD

**Issue by FrancoFasano** [bpampuch/pdfmake#2139]
Hi team,
I'm trying to remove "text" line if value is NULL.
In the exemple below the label and the variables are concatenated.
If variable is NULL or = 0, the expected result is to remove ligne.

Any idea to help me ?

`  {
    "text": "Order N° $po_number",
  },`

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/2113

Here is pdfmake support, not javascript beginner support. Use for example https://stackoverflow.com/
