### ISSUE TITLE
Do italics work ?

### ISSUE THREAD

**Issue by djehring** [bpampuch/pdfmake#214]
I see that your available styles include italics but although you are setting some text in the playground examples in this style they don't render as italics in the pdf. I have tried this on Chrome and Safari  on both OS-X Yosemite and Windows 8.

**Comment by jthoenes** [comment]
Dublicate of #162

**Comment by djehring** [comment]
Hi,

Forgive me for troubling you but I am puzzled why you have marked this 
issue as closed when it still affects your production code. Had the 
issue still been marked as open I would not have filed a duplicate as I 
always take the trouble to look at all open issues before filing a new 
one. You live web site still fails to render italics as does your latest 
source (0.1.15) when pulled using bower so I would have classed the 
issue as unresolved.

Have you fixed the issue in a yet unreleased version, if so when do you 
plan to release it ?

It is a great piece of code but I just need to get my head around your 
fix/release policy.

Kind regards

David

-- 
Dr David Jehring
CEO Black Pear Software Ltd

Tel. +44 1905 621227
Mob. +44 7884 433959

/This E-mail is confidential and may also be privileged. It must not be 
disclosed to any other person or party without the prior authority of 
Black Pear Software Limited. To do so may be unlawful. If you are not 
the intended recipient of this, please notify us immediately and delete 
the e-mail received./

/This e-mail and any attached files have been checked for viruses.  
Although we employ virus protection software, we cannot accept any 
responsibility for any loss or damage to your systems due to viruses or 
malicious code not detected. /

/Any views or opinions contained within this message are solely those of 
the author and do not necessarily represent those of Black Pear Software 
Limited./

Johannes Thönes wrote:

**Comment by jthoenes** [comment]
Hi David,

the issue has been fixed with commit https://github.com/bpampuch/pdfmake/commit/9829f02794fcbd35e50591ead7693b425ed872b6. It has not yet been bundled to a release yet. This has to be done by @bpampuch, the maintainer of pdfmake. He is very busy unfortunately and doing this project in his free time. 

For more information, look at #202.

Best regards
Johannes
