### ISSUE TITLE
Can we view/download the pdf in browser on server end

### ISSUE THREAD

**Issue by sandeshgb** [bpampuch/pdfmake#2140]
As per documentation regarding server side implementation .download() method isn't available. As of now I'm just able to dump it to a specific path.

`
const filename = 'batch-' + batch.id + '.pdf';
                const filepath = '/var/www/tmp/';
                const pdfDoc = printer.createPdfKitDocument(docDefinition);
                pdfDoc.pipe(fs.createWriteStream(filepath + filename));
                pdfDoc.end();
`
Kindly assist...thanks!!

**Comment by liborm85** [comment]
NodeJS on server is not a browser, therefore there can be no `download` method. View is out of scope pdfmake.
You can save PDF document to file on server and then do whatever you want with it.

**Comment by Tilogorn** [comment]
@sandeshgb Are you talking of [this doc page](https://pdfmake.github.io/docs/0.1/getting-started/server-side/)? I cannot find any use of `.download()` there.

What you _probably_ meant, is the `download()` method of Express.js, see [its docs](http://expressjs.com/en/api.html#res.download).

As @liborm85 stated, just use `fs.createWriteStream('myfile.pdf')` to save it locally, then you can call `req.download('myfile.pdf')` to send it to the client.

Pseudo code:
```js
app.get('/', function(req, res) {
    var pdfDoc = printer.createPdfKitDocument(docDefinition);
    var ws = fs.createWriteStream('myfile.pdf');
    ws.on('finish', function() {
        res.download('myfile.pdf');
    });
    pdfDoc.pipe(ws);
    pdfDoc.end();
});

```
