### ISSUE TITLE
auto pagebreak

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2143]
I am generating columns dynamically. while doing this page is not breaking automatically and content goes out of page. so i want to break page automatically after certain columns are generated. may i know how to do this?

**Comment by liborm85** [comment]
You can use `pageBreak: 'after'` or pageBreak: 'before' in node element. Example: https://github.com/bpampuch/pdfmake/blob/0.1/examples/toc.js
