### ISSUE TITLE
Newspaper style two column text?

### ISSUE THREAD

**Issue by rscotten** [bpampuch/pdfmake#2145]
Hello,

I have a multi-page contract.  I want to display it in two columns over multiple pages instead of one column, like this:

![two-col](https://user-images.githubusercontent.com/8073294/100961048-6a89e600-34d6-11eb-89ab-4617d04e9bc9.jpg)

Is there an easy way to do that without having to hack together some dirty character counter to break up the text into two separate columns per page?  

Like a two-column page layout setting?

**Comment by liborm85** [comment]
Not supported now. Feature request: https://github.com/bpampuch/pdfmake/issues/604
