### ISSUE TITLE
Issue with rounded table borders not fixed

### ISSUE THREAD

**Issue by AZchVVT** [bpampuch/pdfmake#2153]
Issue https://github.com/bpampuch/pdfmake/issues/1196 not fixed
the canvas implementation doesn't work for me because I need the title and lines to be different colors
for example:
<img width="717" alt="Screenshot 2020-12-17 at 11 08 43" src="https://user-images.githubusercontent.com/55236206/102442990-4262c100-4058-11eb-94c6-1d067e197191.png">

**Comment by liborm85** [comment]
Text styling is described in [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/styling/).

**Comment by AZchVVT** [comment]
@liborm85 and what i should write for made my table with rounded corners? maybe I don't see something in the documentation?

**Comment by liborm85** [comment]
As written in you referenced issue https://github.com/bpampuch/pdfmake/issues/1196, not supported now and feature request is here:  https://github.com/bpampuch/pdfmake/issues/724

**Comment by AZchVVT** [comment]
@liborm85 do you plan to deliver it in the near future?
