### ISSUE TITLE
Single image doesnt cover multiple pages

### ISSUE THREAD

**Issue by mrigankg** [bpampuch/pdfmake#2154]
I am using pdfmake to convert the html content into imaaage by html2canvas. When the conent is more and resultant. images doesnt fit in single page, then it ssimply print blank pdf. Do we have option to split the paage and roll it over to next page?

**Comment by liborm85** [comment]
You can split to more images (use 3rd library for this) or use automatic page height, see [documentation](https://pdfmake.github.io/docs/document-definition-object/page/).
