### ISSUE TITLE
^0.1.57 => 0.1.59 build failed

### ISSUE THREAD

**Issue by wslp12** [bpampuch/pdfmake#2158]
I was using 0.1.57 without any problem.
However, the error shown below appears at 0.1.59.

![image](https://user-images.githubusercontent.com/26638889/103331992-b1ee9c80-4aab-11eb-9462-795943e085bf.png)

Of course, erasing ^ from package.json will solve it, and changing the minipaing setting will solve it, but I wonder why this problem occurred in bug patches that support sub-compatibility.

**Comment by liborm85** [comment]
I don't see any relation with pdfmake in screenshot.
Add information and attach runnable example.

**Comment by liborm85** [comment]
No reaction.

**Comment by wslp12** [comment]
@liborm85 
I'm sorry for my late reply.
We were looking for the cause of the problem.
This is all the data I can provide...
I'd like to provide a minimum of operational storage, but the situation is not so good.
Tell me if you still don't have enough information.


![image](https://user-images.githubusercontent.com/26638889/103720437-af8dc480-500e-11eb-98cb-dc50f1174189.png)

![image](https://user-images.githubusercontent.com/26638889/103720466-bddbe080-500e-11eb-88c9-dab59b74234c.png)

What we've seen so far is...

0.1.57 is normally built.
0.1.59 indicates that the error is printed as shown in the picture.

The error is based on the version of pdfmake.

The webpack version of our project is 2.2.1
The ugly used is webpack-parallel-ugly-plugin and version 0.4.2.

**Comment by liborm85** [comment]
No example. Non-reproducible.
