### ISSUE TITLE
link to the keywords

### ISSUE THREAD

**Issue by julieagaze** [bpampuch/pdfmake#216]
Is there a link to the documentation of this project. I would like to know the keywords to be used and the patterns of nesting, while generating data dynamically
I was basically trying to create a table from HTML and it overflows the page.
Can we specify the width of the table as a whole in percentage?

**Comment by jthoenes** [comment]
We have some documentation up on http://pdfmake.org/#/gettingstarted, unfortunately it is incomplete. Not all features are documented.

You can specify the percentage in a table by:

````javascript
    widths: ['70%', '10%', '10%', '10%'],
````

Also, if you work on HTML to pdfmake transformation, maybe you can find some valuable information here: #186 

We are desperately in need for someone who helps us extend the documentation. So if you want to extend it, sende pull request for the https://github.com/bpampuch/pdfmake/tree/gh-pages branch.

**Comment by julieagaze** [comment]
Thanks..
few more clarifications: 1.Cant we have the image and text together.I tried adding them to colums..
But the text does not appear close to the image on the right though.. 
columns:[
{image : dataURL format},
  {text:'some text'}

]
The above works. However there is a lot of gap between the image and text,
2. Can we have footer with text (align left ) and page number(align right)?
3. Does the library support valign?
Any leads would really help

**Comment by jthoenes** [comment]
1. I guess you have to adapt the image size or column size.
  2. Yes, use align='left' and align='right' in composition with columns.
  3. No, that's currently not supported.

**Comment by Wabbala** [comment]
Hi @julieagaze,

You can solve the gap issue by defining the padding of the table cells. See the following definition for a two column table containing text in one column and an image in the other:

```javascript
{
    style: 'tableExample', // see pdfmake playground
    table: {
        widths: [250, 255.28],
        body: [
               [{ text: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.'}, [{
                   style: 'noMargins', // I defined this style as margin: [0, 0, 0, 0] in the docDefinition
                   table: {
                       body: [
                              [{
                                  image: 'sampleImage.jpg',
                                  width: 255.28,
                                  alignment: 'right'
                              }]]
                   },
                   layout: {
                        paddingLeft: function(i) { return 0; }, 
                        paddingRight: function(i, node) { return 0; },
                        paddingTop: function(i, node) { return 0; },
                        paddingBottom: function(i, node) { return 0; }
                    }
               }]],
               ]
    },
    layout: 'noBorders'
}
```

Goodluck!

**Comment by Wabbala** [comment]
Hi @julieagaze,

You can solve the gap issue by defining the padding of the table cells. See
the following definition for a two column table containing text in one
column and an image in the other:

```javascript
{
    style: 'tableExample', // see pdfmake playground
    table: {
        widths: [250, 255.28],
        body: [
               [{ text: 'Lorem ipsum dolor sit amet, consectetur
adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore
magna aliqua.'}, [{
                   style: 'noMargins', // I defined this style as margin:
[0, 0, 0, 0] in the docDefinition
                   table: {
                       body: [
                              [{
                                  image: 'sampleImage.jpg',
                                  width: 255.28,
                                  alignment: 'right'
                              }]]
                   },
                   layout: {
                        paddingLeft: function(i) { return 0; },
                        paddingRight: function(i, node) { return 0; },
                        paddingTop: function(i, node) { return 0; },
                        paddingBottom: function(i, node) { return 0; }
                    }
               }]],
               ]
    },
    layout: 'noBorders'
}
```

Goodluck!

**Comment by bpampuch** [comment]
It seems we have a bug - two auto-sized columns should work fine in the above case and they do... unless alignment is set to right.

**Comment by julieagaze** [comment]
Thanks a lot .....
I just had to add the width to the columns as in the comment above..
Really great library!!!!

**Comment by liborm85** [comment]
Documentation is in [readme file](https://github.com/bpampuch/pdfmake/blob/master/README.md). Yes, it would like to a lot of improve it and move it to pdfmake.org site, but so far I have not figured out how.
