### ISSUE TITLE
Add content position before executing background function

### ISSUE THREAD

**Issue by Bramikke** [bpampuch/pdfmake#2160]
Is it possible to add the position of the content before executing the background function just like the header function?

I would like to add a canvas with rounded corners behind a table. Therefor I need the position of the table on the page and the height. Since the height can be different because of text wrapping, the height needs to be calculated after the table is drawn.

When calling pdf.content inside the header function (header: (currentPage) => {...}), the **positions** attribute is already added to each element. Like in the example below
```
1:{text: 'test', margin: Array(4), _margin: Array(4), …}
  _inlines:(0) []
  _margin:(4) [5, 0, 5, 0]
  _maxWidth:172.6337890625
  _minWidth:94.1708984375
  margin:(4) [5, 0, 5, 0]
  positions:(1) [{…}]
      0:{pageNumber: 1, pageOrientation: 'portrait', pageInnerHeight: 701.89, pageInnerWidth: 555.28, left: 25, …}
      length:1
  text:'test'
```

But when calling pdf.content inside the background function (background: () => {...}), the **positions** attribute is not yet added to the elements.

Can you please change this, so the background function is executed after the content positions are set?
Or is there a possible workaround for this issue?

**Comment by liborm85** [comment]
To `header`  is passed only page number. The same goes for `background`.

**Comment by Bramikke** [comment]
I understand. But in the `header`, it is possible to access the positions of each `content` item. This is missing in the `background` function. 

I must have the positions of the tables in the content, so I can draw a background behind each table.

**Comment by liborm85** [comment]
It is not possible, because background is rendered before page content.

**Comment by Bramikke** [comment]
Thank you @liborm85 for the quick answer.

Is there another way to show a variable-height table with a rounded border around it?
I was not able find a solution for this problem yet.

**Comment by liborm85** [comment]
It is not supported now. Feature request: https://github.com/bpampuch/pdfmake/issues/724
