### ISSUE TITLE
Uncaught Unrecognized document structure error, can't find any solution to fix it

### ISSUE THREAD

**Issue by pibubear** [bpampuch/pdfmake#2161]
Hey there!
I would like to have some feedback on what's really going wrong.
I'm creating pdfmake objects of my inner tables and then trying to assign these to the main Doc object of customize function as I'm using this library alongwith datatables. 
**_Uncaught Unrecognized document structure: {"body":[[{"style":"normal","margin":[0,1,0,0],"text":"Total Assets"},{"style":"normal","margin":[0,1,0,0],"text":"Dr 1,342.70"}],[{"style":"normal","margin":[0,1,0,0],"text":""},{"style":"normal","margin":[0,1,0,0],"text":""}],[{"style":"normal","margin":[0,1,0,0],"text":""},{"style":"normal","margin":[0,1,0,0],"text":""}],[{"style":"normal","margin":[0,1,0,0],"text":"Total"},{"style":"normal","margin":[0,1,0,0],"text":"Dr 1,342.70"}],{"cellStylingMap":[null,[{},{}],[{},{}],[{},{}],[{},{}]],"rowStylingMap":[null,[],[],[],[]],"columnStylingMap":[[],[]]}]}_** 

here is the docDefinition:
  // create new pdfmake object for inner node 
          var docDefinition = {
            content: {
              table: {
                body: body
              },
            }
          };
           var pdf = pdfMake.createPdf(docDefinition);
           // tried assigning object (**table** here has the pdfmake table's body structure)
          table[1][0] = pdf.docDefinition.content.table; 
   // that is how my newly created objects looks like
 **docDefinition:
content:
table:
body: Array(5)
0: Array(2)
0: {style: "normal", margin: Array(4), text: "Total Assets"}
1: {style: "normal", margin: Array(4), text: "Dr 1,342.70"}
length: 2
__proto__: Array(0)
1: (2) [{…}, {…}]** 

Any help is appreciated. I want my inner tables to render properly when they are being exported to pdf.
Thank you.

**Comment by liborm85** [comment]
Attach example for reproduce ssiue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by pibubear** [comment]
Somewhat fixed. removed my styling object from table body. 
table:
body: Array(5)
0: (2) [{…}, {…}]
1: (2) [{…}, {…}]
2: (2) [{…}, {…}]
3: (2) [{…}, {…}]
**4: {cellStylingMap: Array(5), rowStylingMap: Array(5), columnStylingMap: Array(2)}**
![oie_JGcKFL6FxCj2](https://user-images.githubusercontent.com/76561836/103452499-5532f200-4cf6-11eb-91b8-bd1bf1a09297.png)
I still need to figure out how to style this table. Thank you for reaching out.
