### ISSUE TITLE
Load image via external url

### ISSUE THREAD

**Issue by sandeshgb** [bpampuch/pdfmake#2162]
I need to load an image from an external url.
(ex: url: https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUcUCuXMald5MexzWYz8GwZAu-vqSr0JZOFw&usqp=CAU)

How can I do it??

**Comment by liborm85** [comment]
see [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/images/)

**Comment by sandeshgb** [comment]
> see [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/images/)

I had seen the documentation, but there also its asking base-64 encoded url, where as I just wanted to pass http url.

`
images: {
    mySuperImage: 'data:image/jpeg;base64,...content...',
    snow: 'https://picsum.photos/seed/picsum/200/300'
  }
`
The above code is from documentation, and i tried it in playground as well.
I don't get what is **mySuperImage** **snow** (or should it be show)

It would be very helpful if you could just share a snippet which I can execute on playground.

**Comment by r0the** [comment]
Here's an example how to download images for pdfmake: 

https://gist.github.com/r0the/3fd5cbc15ab07940c59eb519fa5cbf3e

**Comment by liborm85** [comment]
quite simply:
```js
var dd = {
  content: [
    {
      image: 'snow'
    }
  ],
  images: {
    snow: 'https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUcUCuXMald5MexzWYz8GwZAu-vqSr0JZOFw&usqp=CAU'
  }
};
```

snow (or mySuperImage) is only custom image name.

**Comment by Jackyyans** [comment]
Convert an Image URL to base64:

```export const imageUrlToBase64 = async (imageUrl = '') => {
  const response = await axios.get(imageUrl, {
    responseType: 'arraybuffer',
  });
  const contentType = response.headers['content-type'];
  const base64String = `data:${contentType};base64,${Buffer.from(
    response.data
  ).toString('base64')}`;
  return base64String;
};```
