### ISSUE TITLE
Arabic and English Combined pdf

### ISSUE THREAD

**Issue by MFarooqAbdullah** [bpampuch/pdfmake#2163]
is it possible to make pdf document with both arabic and english?

**Comment by liborm85** [comment]
Fonts for multiple languages are supported via [custom fonts](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/).
For Arabic language is not supported RTL (feature request: https://github.com/bpampuch/pdfmake/issues/184).

**Comment by german-st** [comment]
@liborm85 Please see my[ issue ](https://github.com/bpampuch/pdfmake/issues/2218)

**Comment by imPrashik** [comment]
try using "Arial_Unicode_MS"

[WikiPedia](https://en.wikipedia.org/wiki/Arial_Unicode_MS#:~:text=The%20code%20pages%20supported%20are,Devanagari)
