### ISSUE TITLE
image produced incorrect pdf

### ISSUE THREAD

**Issue by tw1t611** [bpampuch/pdfmake#2164]
### problem
When inserting a png file, the pdf is not generated properly on nodejs v14.15.3.
It works fine without the image.
The image path is correct, otherwise there would be an other error.
Inserting the image as base64 caused the same error.
Strapi is running in a docker container.

### code
```js
module.exports = {
  offer: async (ctx, next) => {
    try {
      const accessories = await strapi.services.accessories.findOne({
        id: "5ff5b246760b42004dc77be1",
      });
      var docDefinition = {
        content: [
          accessories.name,
          "First paragraph",
          "Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines",
          {
            text: "This is a header, using header style",
            style: "header",
          },
          {
            image: "public/uploads/logo.png",
            width: 150,
            height: 150,
          },
        ],
        defaultStyle: {
          font: "Helvetica",
        },
        styles: {
          header: {
            fontSize: 18,
            bold: true,
          },
        },
      };

      var pdfDoc = printer.createPdfKitDocument(docDefinition);

      pdfDoc.pipe(fs.createWriteStream("test.pdf"));
      pdfDoc.end();

      ctx.body = "ok";
    } catch (err) {
      ctx.body = err;
    }
  },
};
```

### pdf
```pdf
%PDF-1.3
%\FF\FF\FF\FF
9 0 obj
<<
/Type /ExtGState
/ca 1
/CA 1
>>
endobj
8 0 obj
<<
/Type /Page
/Parent 1 0 R
/MediaBox [0 0 595.28 841.89]
/Contents 6 0 R
/Resources 7 0 R
>>
endobj
7 0 obj
<<
/ProcSet [/PDF /Text /ImageB /ImageC /ImageI]
/ExtGState <<
/Gs1 9 0 R
>>
/Font <<
/F1 10 0 R
/F2 11 0 R
>>
/XObject <<
/I1 5 0 R
>>
>>
endobj
6 0 obj
<<
/Length 526
/Filter /FlateDecode
>>
stream
x\9Cŗώ\D3@\C6\EFy\8Ayf\C7\FF\99\91\AAV+\B8\81rC\\C86\88 T\89\E7\C7n\8B@"qXUj\A34\C9o\FC\D9\FEƁT\EC\F3\EC\AB\E4\D6\D3\F2e\BA{<C\FAt\9E\EEN?>/\A7w\8F\F7i9O\E5r\E9y\F9:\AD\D3\F7	\B6n\BC\9Fo\E7!QI\DAkF\A54\DB_AL\F3:\BD?(	kU:\A6\F2!\CDo\A6\97\F3\F4\F6ِ
3\FC\8D$\91\AE\E8P,ώ\C9"4BkP<&(\E9  z=\FA}\C6\FEo!J(䲡\C8IVKA\B3$`\80\8Ds\95\FD_\C4\C0%`U@b\CBj\C3u\B9]kYZ\AE:V\84\A4˓p\B9S\AEÐ\90X9f.&2Y\C8KH\C0\88=\97\A1҂\8F\C0v/\E8\D5zN\83\FA
deܩ\AF5\82\DA-\E6>\D6\FAɺ\FB\E3\D1\EA\C1\BA:"\D55sG]\D5\D46_\E1tq\94\CAj\8EB\FF\C1Q\AAvs\94a\EC\DEdVo\AAS\81GQ5\F0"b\C2n\C8nm\B9\8C[K̺\D5\FBe\890\B2DS\96\98\A79\A8\BD\B9`.mL\86#e\E0L\B8g\A4l\E4\98!\CE'&\EE\B9ou\B2\DE\E6\94\A9\C5\CE\F9\8E\B9
\FF\D5\CCZC"&\CA,r\85b\82v\85r\9Cwٌ\,\B68j\F3j\F6\BAP#&!\00\CD޺d\F3Rv\E3\F0\D9W\8A\EFQG\CF\C8!b)\8D\EC5l\B4\DB(\EB\A5\C64bL\A8\9Aw\84\FFC\85\88}\D2w+\9F\81\9B\91\A8oX\BCI\B6\E7s\B9\EC\C0r\83l\B6ė\F7\E3א\BE\D9\C5?\9C\C4X\A9
endstream
endobj
13 0 obj
(pdfmake)
endobj
14 0 obj
(pdfmake)
endobj
15 0 obj
(D:20210106154233Z)
endobj
12 0 obj
<<
/Producer 13 0 R
/Creator 14 0 R
/CreationDate 15 0 R
>>
endobj
10 0 obj
<<
/Type /Font
/BaseFont /Helvetica
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
11 0 obj
<<
/Type /Font
/BaseFont /Helvetica-Bold
/Subtype /Type1
/Encoding /WinAnsiEncoding
>>
endobj
4 0 obj
<<
>>
endobj
3 0 obj
<<
/Type /Catalog
/Pages 1 0 R
/Names 2 0 R
>>
endobj
1 0 obj
<<
/Type /Pages
/Count 1
/Kids [8 0 R]
>>
endobj
2 0 obj
<<
/Dests <<
  /Names [
]
>>
>>
endobj
```

**Comment by liborm85** [comment]
Tested a works ok.
Attach runnable example for reproduce issue.

**Comment by tw1t611** [comment]
Sadly, I am not able to provide a not working script, but I was able to narrow down the problem.
First of all the script works, if executed synchronous. `node test.js`
I tested the script above with a jpg file and base64 jpg file. That works, too.
Therefore I believe the problem occures on using png files in an asynchronous execution.

Sorry for I can't give you more information to find the bug. Simply using a jpg solves it for now.

**Comment by liborm85** [comment]
No example. Non-reproducible.

**Comment by antonfire** [comment]
Did you resolve this? I'm having the same problem. I can't swap to jpeg as the images are user supplied and so either can be provided.

**Comment by ari-motors-team** [comment]
nope sorry, we switched to
https://github.com/Hopding/pdf-lib

**Comment by blikblum** [comment]
> Did you resolve this? I'm having the same problem. I can't swap to jpeg as the images are user supplied and so either can be provided.

Its because png runs async. You have to wait for the stream complete before returning the response.

Here's a function that wraps the doc in an async function and returns base64:

```js
async function generatePdfDataUrl(doc) {
  return new Promise((resolve, reject) => {
    const chunks = []

    doc.on('data', (chunk) => {
      chunks.push(chunk)
    })

    doc.on('end', () => {
      const result = Buffer.concat(chunks)
      resolve('data:application/pdf;base64,' + result.toString('base64'))
    })

    doc.on('error', (error) => {
      reject(error)
    })

    doc.end()
  })
}

async createPdf() {
  const  docDefinition = {}
  const pdfDoc = printer.createPdfKitDocument(docDefinition);
  const base64 = await generatePdfDataUrl(pdfDoc)
}
```

**Comment by antonfire** [comment]
> > Did you resolve this? I'm having the same problem. I can't swap to jpeg as the images are user supplied and so either can be provided.
> 
> Its because png runs async. You have to wait for the stream complete before returning the response.
> 
> Here's a function that wraps the doc in an async function and returns base64:
> 
> ```js
> async function generatePdfDataUrl(doc) {
>   return new Promise((resolve, reject) => {
>     const chunks = []
> 
>     doc.on('data', (chunk) => {
>       chunks.push(chunk)
>     })
> 
>     doc.on('end', () => {
>       const result = Buffer.concat(chunks)
>       resolve('data:application/pdf;base64,' + result.toString('base64'))
>     })
> 
>     doc.on('error', (error) => {
>       reject(error)
>     })
> 
>     doc.end()
>   })
> }
> 
> async createPdf() {
>   const  docDefinition = {}
>   const pdfDoc = printer.createPdfKitDocument(docDefinition);
>   const base64 = await generatePdfDataUrl(pdfDoc)
> }
> ```

How are you using this in conjunction with pdf make?

**Comment by blikblum** [comment]
> ```js
>   const  docDefinition = {}
>   const pdfDoc = printer.createPdfKitDocument(docDefinition);
> ```

This is pdfmake api

**Comment by antonfire** [comment]
My code uses the following, can you see any reason why mine would still produce errors with pngs, it seems to achieve the same as yours.
`function createPdfBinary(docDef, optionsObj) {
          return new Promise((resolve, reject) => {

            const doc = printer.createPdfKitDocument(docDef, optionsObj);

            const chunks = [];
            let result;

            doc.on('data', function(chunk) {
              chunks.push(chunk);
            });
            doc.on('end', function() {
              result = Buffer.concat(chunks);
              resolve(result);
            });
            doc.end();
          });
        }; `

**Comment by blikblum** [comment]
should work. For further investigation needs a minimal reproducible example. 

what error are you getting ?

**Comment by antonfire** [comment]
My mistake sorry it is working, another library was messing up the final result. Thanks for your help

**Comment by wendy121418** [comment]
@antonfire how you resolve this issue?

**Comment by antonfire** [comment]
@wendy121418 You need to download the pdf file and save to file system like this or similar:

```
                  const fileBuffer = Buffer.from(file)
                  fs.writeFileSync(os.tmpdir() + "/image.png", fileBuffer)
```

then call it for inclusion like this:

```
                        .image(os.tmpdir() + "/imagepng", 10, 10, {
                          width: 20,
                          keepAspectRatio: true
                        })
```
