### ISSUE TITLE
Mobile browsers don't actually download() a pdf file?

### ISSUE THREAD

**Issue by adam-acosta** [bpampuch/pdfmake#2165]
Mobile browsers: I don't think download() "loads the PDF perfectly". It just creates and opens a blob. I'd like an actual download to occur. Is it possible to actually generate a .pdf file and trigger an actual download in mobile browsers (chrome/safari)?

**Comment by liborm85** [comment]
Document file cannot be "real" downloaded because no exist real file on server. Document is generated in browser in client-side.
For download action is used [FileSaver.js library](https://github.com/eligrey/FileSaver.js/) with the functions that the device allows.
