### ISSUE TITLE
stamp existing pdf

### ISSUE THREAD

**Issue by gernotstarke** [bpampuch/pdfmake#217]
add e.g. headline, page-numbers or other info to existing pdf's.

similar to https://bitbucket.org/arc42/pdfstamper, but without 
the dependeny on the Java ecosystem :-)

feasible with pdfmake?

thx,
Gernot

**Comment by mikend** [comment]
Being able to add new content to an existing pdf would be a very useful feature, though in my case it would rather be the opposite way than above, i.e. adding body content to an existing pdf with header and footer. So I think the feature, should it be implemented, should be about adding content i general, not headers and footers specifically.

**Comment by gernotstarke** [comment]
yep - right. The "mother of all pdf libraries" (iTextPdf) calls that "stamping" - and allows
arbitrary content to be stamped anywhere on a page (more specific, canvas, if I remember correctly).

It'd be allright to calculate some coordinates based upon the current pages' dimensions...

For stamping it would be useful to:

   1. open an existing pdf  file
   2. get a specific page within this file
   3. add text to this page at specified coords

**Comment by jthoenes** [comment]
Hi @gernotstarke, Hi @mikend,

thanks for the suggestion. If I understand the documentation of https://github.com/devongovett/pdfkit (the underlying rendering engine of pdfmake) correct, it cannot support stamping yet. Therefore it will be hard to provide it in pdfmake.

Best regards

**Comment by gernotstarke** [comment]
opened an issued with pdfkit:
https://github.com/devongovett/pdfkit/issues/373

@jthoenes  - you're right - should have started there...

will close this one here!
