### ISSUE TITLE
[IE11 - 0.1 branch] Syntax Error - SCRIPT1003: Expected ':'

### ISSUE THREAD

**Issue by Janooba** [bpampuch/pdfmake#2170]
I'm trying to use the latest pdfmake.js from the 0.1 branch in IE11 and I'm getting a "Syntax error"

![image](https://user-images.githubusercontent.com/17034238/104528111-9dd68f00-55c3-11eb-85f1-73f60b693dc3.png)

![image](https://user-images.githubusercontent.com/17034238/104528134-aaf37e00-55c3-11eb-8652-d2304addd582.png)

I'm at a loss here considering this seems to work fine for everyone else.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/1fb9759c9e9b3963a8f705ff01def9bfd84977f7

**Comment by liborm85** [comment]
Bugfix version 0.1.70 released.
