### ISSUE TITLE
if else statement in content

### ISSUE THREAD

**Issue by DivGolakiya** [bpampuch/pdfmake#2171]
I am generating a report in which sometimes there is 2 pages and sometimes there is 3 pages. so for each page I am declaring a new object. for eg., I am generating 3 objects Tbody1, Tbody2, Tbody3 and using them in content as 

content: [

      {
        table: {
          body: Tbody1,
        }
      },
      {
        table: {
          body: Tbody2,
        }
      },
      {
        table: {
           body: Tbody3,
        }
      }
      ],

when report has generated 3 pages, everything works fine but when report has generated only 2 pages, it gives error. how can i encounter that as if..else.. statements is not working in content tag?

**Comment by liborm85** [comment]
Explain your quest and attach runnable example.

**Comment by NDalvise** [comment]
Move you if-else logic outside on the _content_ array and you will be good.

I can imagine something like
```
let data = {
  pageSize: 'A4',
  content: myContent,
  styles: myStyles
}

let myContent = [
  {
    table: {
      body: Tbody1,
    }
  },
  {
    table: {
      body: Tbody2,
    }
  }
];

if (TBody3 != null) {
  content.push({ table: { body: TBody3 } });
}

let myStyles = ...and so on...
```

As you can see, the trick is to play with javascript. You shouldn't have logic in a data model.

**Comment by liborm85** [comment]
This is standard JSON use google or stackoverflow for help with this. This is not related with pdfmka. This site is not support for javascript beginners.

**Comment by matthew-valenti** [comment]
Or with standard javascript, we can use a conditional statement inside the content array e.g.
```
content: [
    { table: { body: Tbody1 } },
    ...(myCondition) ? [{ table: { body: Tbody2 } }] : [],
    { table: { body: Tbody3 } }
]
```
