### ISSUE TITLE
Only add Background-layer on last page of PDF

### ISSUE THREAD

**Issue by kobrien24** [bpampuch/pdfmake#2172]
Background-layer callback passes currentPage & pageSize. Is there a way to know if it's a specific page other than the currentPage number? 

I have possible data that could extend to another page, so I can't hard code a number because at times it would not work properly. 

In my case, this background-layer would only be added to the last page of the PDF, but I still don't know how to do that with the current variables being supplied.

Thank you for the help!

**Comment by suchislife801** [comment]
At the moment there is no way to add watermark layer to just one page. It is a watermark after all.
