### ISSUE TITLE
Make a PDF with one page of an other PDF

### ISSUE THREAD

**Issue by samthib** [bpampuch/pdfmake#2178]
Hi,

I want to select the first page of a PDF and make an other PDF with it, how can I achieve this ?

For instance, is there a way to use the _getPages() methods like this :

```
pdfDocGenerator._getPages({}, function(pages){
      const pdfGeneratorPage = pdfMake.createPdf(pages[0]);
    pdfGeneratorPage.getDataUrl((dataUrl) => {

        ...

    });
  });
```
Thank you

**Comment by suchislife801** [comment]
You cannot. Currently there is no support to load an existing PDF and, edit it and save it.

PDFMake is a PDF Creation library. Not a PDF Editing library.

**Comment by imhaeussler** [comment]
pdf-lib can be used for this https://github.com/Hopding/pdf-lib

**Comment by linh236** [comment]
Hey, I have a question that when i upload file (docx) and how to get text in docx file ?. After that, I call makePdf with params: docxContent.
makePdf(docxContent):Promise<any> {
    let docDefinition =  { 
      content: [docxContent]
    }
    return new Promise(resolve => {
      const pdfDocGenerator = pdfMake.createPdf(docDefinition);
      pdfDocGenerator.getBlob((blob) => {
        resolve(blob)
      });
    });
