### ISSUE TITLE
Any option to change color of table border ?

### ISSUE THREAD

**Issue by athimannil** [bpampuch/pdfmake#218]
Is there any solution available to change table cell border color ?

**Comment by jthoenes** [comment]
Example from http://pdfmake.org/playground.html

````javascript
layout: {
														hLineWidth: function(i, node) {
																return (i === 0 || i === node.table.body.length) ? 2 : 1;
														},
														vLineWidth: function(i, node) {
																return (i === 0 || i === node.table.widths.length) ? 2 : 1;
														},
														hLineColor: function(i, node) {
																return (i === 0 || i === node.table.body.length) ? 'black' : 'gray';
														},
														vLineColor: function(i, node) {
																return (i === 0 || i === node.table.widths.length) ? 'black' : 'gray';
														},
														// paddingLeft: function(i, node) { return 4; },
														// paddingRight: function(i, node) { return 4; },
														// paddingTop: function(i, node) { return 2; },
														// paddingBottom: function(i, node) { return 2; }
						}
````

**Comment by douglasg14b** [comment]
@jthoenes  can this not be controlled on a cell by cell basis?

**Comment by jthoenes** [comment]
exactly like in the code above. Make your function react on the ``i`` param and you're there.

**Comment by douglasg14b** [comment]
@jthoenes That's for the table as a whole, not controllable for each individual cell is it? 

Say I have a single cell somewhere in the table and I need the right vertical border to be 2 pixels. How can I achieve that with the above example.

**Comment by imamdev** [comment]
@jthoenes @douglasg14b: I'm interested how this can be done too? I tried to loop though the nodes, rows and cells but this doesn't make sense or?

**Comment by hamzachaouch** [comment]
Hi, Did anyone face the same problem? 
![CaptureDash](https://user-images.githubusercontent.com/22745729/73259837-ef2a1a80-41c8-11ea-9c75-6c97e7ff1876.PNG)

**Comment by ykessler** [comment]
It's [now possible](https://github.com/bpampuch/pdfmake/commit/9e25e22e5cd0b66d9179aca6269ddc3a0bbdb557) to set border colors on individual cells.

**EXAMPLE:**
```
table: {
  body: [
    [{
        text: 'Cell 1',
        borderColor: ['#ff00ff', '#00ffff', '#ff00ff', '#00ffff'],
      },
      {
        image: 'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAAEAAAABCAQAAAC1HAwCAAAAC0lEQVR42mNk+A8AAQUBAScY42YAAAAASUVORK5CYII=',
        borderColor: ['#ff00ff', '#00ffff', '#ff00ff', '#00ffff']
      },
      'Cell 3'
    ]
  ]
}
```

See also https://github.com/bpampuch/pdfmake/issues/1189#issuecomment-529971357

**Comment by nicolacardi** [comment]
what about setting individual cells borders width?

**Comment by nerdess** [comment]
> 



> what about setting individual cells borders width?

This is already possible, see [playground](http://pdfmake.org/playground.html) > tables
