### ISSUE TITLE
Header Not Working with Page Margins

### ISSUE THREAD

**Issue by MarkWhite1961** [bpampuch/pdfmake#2181]
Adding pageMargins stops the header working.

{
            header: 'HEADER',
            content: 'CONTENT',
            pageMargins: 0
}

Only CONTENT is displayed.

Remove it the header is shown.

Great project BTW!

**Comment by liborm85** [comment]
Your page margin is `0`, therefore there is no place to header. Increase page margin.

**Comment by fernando-s97** [comment]
I have 

{
header: 'HEADER',
content: 'CONTENT',
pageMargins: [ 40, 60, 40, 60 ]
}

But horizontal margins are not working in the header. Any solution?
