### ISSUE TITLE
Footer params 

### ISSUE THREAD

**Issue by DiegoCampaneroNegrete** [bpampuch/pdfmake#2183]
Hi i tried to add a url in the footer of every single page in my PDF, but i don´t undertand how can i pass a single param (my URL) to the footer and print.

This is my code how i tried to pass the param

`
var docDefinition = {
      pageOrientation: 'landscape',
      pageSize: {width: 1320, height: 1460},
      content: [
          {
              text: ''
          }
      ],
      footer: (currentPage, pageCount, urlToShow) => {
          console.log('footer: (urlToShow)', urlToShow);
          return [{ text: 'urlToShow' + urlToShow, alignment: 'left' }];
      },
  };
`

`
return contentArray[`${index}`] = [{
        image: imgData, width: canvas.width, height: canvas.height-40, margin: [-40, 0],
        footer: (currentPage, pageCount)  => footerFunction(currentPage, pageCount, urlTemp) ,
    }];
`

thanks for the help.

**Comment by suchislife801** [comment]
You do it by coding the footer object like this:

```
// PDF Document Footer (Dynamic Page Numbers)
footer: function(currentPage, pageCount) {

  return {

    columns: [
      {
        stack: [
          {
            text: 'Form F-1 © 2020 - Example1 LLC',
            // left, top, right, bottom
            margin: [41, 21, 0, 0],
            font: 'Helvetica',
            fontSize: 7.5,
            color: '#404040',
            normal: true,
            bold: true,
            italics: false,
            bolditalics: false
          }
        ],
        width: '*',
        style: 'text-left'
      },
      {
        stack: [
          {
            text: ' ',
            // left, top, right, bottom
            margin: [0, 21, 0, 0],
            font: 'Helvetica',
            fontSize: 7.5,
            color: '#404040',
            normal: true,
            bold: true,
            italics: false,
            bolditalics: false
          }
        ],
        width: '*',
        style: 'text-center'
      },
      {
        stack: [
          {
            text: 'PAGE ' + currentPage.toString() + ' of ' + pageCount.toString(),
            // left, top, right, bottom
            margin: [0, 21, 41, 0],
            font: 'Helvetica',
            fontSize: 7.5,
            color: '#404040',
            normal: true,
            bold: true,
            italics: false,
            bolditalics: false
          }
        ],
        width: '*',
        style: 'text-right'
      }
    ]

  }

}
```
