### ISSUE TITLE
Lists don't render unless they are top level

### ISSUE THREAD

**Issue by adam-vaultplatform** [bpampuch/pdfmake#2184]
I've been doing some experimentation with a parser and pagination. I've found that Unordered/Ordered Lists won't render unless they are top level

For example this following example will not render the list but will happily render further nested text:
```
var dd = {
  content:  {
      "text": [
          "Test\n",
          { "ol": ["List Item 1"] },
          { "text": { "text": "hello world" } },
      ]
  }
}
```
This happily renders the text but not the ordered list itself:
```
var dd = {
  content:  [
          "Test",
          { "ol": ["List Item 1"] },
          { "text": { "text": "hello world" } },
      ]
}
```

**Comment by liborm85** [comment]
In `text` can only contain text or `text` node. This is for inline styling only.
