### ISSUE TITLE
PDF viewer not working in Safari - 

### ISSUE THREAD

**Issue by dankushrao** [bpampuch/pdfmake#2185]
Under Safari 14.0.2 running on macOS Catalina, when opening a pdf file it does not open. Instead, it freezes the whole tab's controls. The safari development tools cannot be activated after this bug is triggered, and in some cases the page cannot close. Sometimes if the session in opened long enough to save the state then it happens again after reopening the page.

**Comment by suchislife801** [comment]
Please see this list of supported browser on issue [#800](https://github.com/bpampuch/pdfmake/issues/800)
