### ISSUE TITLE
Can't save PDF file in the Angular app in production because of the Content Security Policy directive

### ISSUE THREAD

**Issue by ArturGudiev** [bpampuch/pdfmake#2187]
I have the Angular app. And there is a function that saves a pdf file.

```
import * as pdfMake from 'pdfmake';
...

  createPdf(): void {

    let docDefinition = {  
      header: 'C#Corner PDF Header',  
      content: 'Simple pdf file'  
    };  
   
    pdfMake.createPdf(docDefinition).download('a.pdf'); 
  }
```

It worked well both locally and in production in the past. But from some point, it started to fail in production while locally everything remained the same.

This is the error I receive in the production

> ERROR EvalError: Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "script-src 'self'".

**Comment by SouengKimmeng** [comment]
I got this problems as well. Pls help

**Comment by liborm85** [comment]
Problem is in [foliojs/restructure](https://github.com/foliojs/restructure) library. We pending to release new version.
