### ISSUE TITLE
When I use NotoSansJP font, a specific character is not displayd on PDF under certain conditions

### ISSUE THREAD

**Issue by sks-ysk** [bpampuch/pdfmake#2191]
Hello.

This is the font I'm using.
https://fonts.google.com/specimen/Noto+Sans+JP?preview.text_type=custom

I tried the code below.
```
// OK----------------------------------------
pdfMake.fonts = {
    TestFont: {
        normal: 'NotoSansJP-Regular.otf',
        bold: 'NotoSansJP-Regular.otf',
        italics: 'NotoSansJP-Regular.otf',
        bolditalics: 'NotoSansJP-Regular.otf'
    }
};
let docDefinition = {
    content: [
        { text: "描画", fontSize: 20 },
        { text: "指定なしで描画", fontSize: 20 },
    ],
    defaultStyle: {
        font: 'TestFont'
    },
};
pdfMake.createPdf(docDefinition).open();

// NG----------------------------------------
pdfMake.fonts = {
    TestFont: {
        normal: 'NotoSansJP-Regular.otf',
        bold: 'NotoSansJP-Regular.otf',
        italics: 'NotoSansJP-Regular.otf',
        bolditalics: 'NotoSansJP-Regular.otf'
    }
};
let docDefinition = {
    content: [
        { text: "指定なしで描画", fontSize: 20 },
        { text: "描画", fontSize: 20 },
    ],
    defaultStyle: {
        font: 'TestFont'
    },
};
pdfMake.createPdf(docDefinition).open();
```
![result](https://user-images.githubusercontent.com/79124112/108024961-ebce2f00-7068-11eb-8e91-1460d8e9e228.png)

(I just changed the order of the text.)

Is this a bug?

Please excuse my poor English.

**Comment by hand-dot** [comment]
@sks-ysk 
It's not pdfmake's problem.(it is caused by otf font)

Alternatively you can use this font.
repo: https://github.com/3846masa/sauce-han-fonts
blog(japanase): https://3846masa.hatenablog.jp/entry/2017/10/25/183205

sauce-han-fonts(源ノ角ゴシック / 源ノ明朝) are TrueType Font.

**Comment by sks-ysk** [comment]
@hand-dot 
Thank you for the information.
It was helpful.

**Comment by GustavPS** [comment]
> @sks-ysk It's not pdfmake's problem.(it is caused by otf font)
> 
> Alternatively you can use this font. repo: https://github.com/3846masa/sauce-han-fonts blog(japanase): https://3846masa.hatenablog.jp/entry/2017/10/25/183205
> 
> sauce-han-fonts(源ノ角ゴシック / 源ノ明朝) are TrueType Font.

Is this a known issue with all otf fonts when using pdfmake? I'm seeing this exact issue on Arabic, Korean and Chinese otf fonts. But not when using ttf fonts
