### ISSUE TITLE
Opacity not working for svg's

### ISSUE THREAD

**Issue by HypergeneticSpacekid** [bpampuch/pdfmake#2193]
Hi, 

I would like to translate my canvas to pdf, with all features (opacity...). Since rotation is not enabled for canvas elements, I resorted to svgs. However, I noticed that opacity is not properly rendered in the pdf. 

Here the canvas version: 

![image](https://user-images.githubusercontent.com/57860800/108589152-5d55f800-735d-11eb-9bc7-a328cfdb76e4.png)

and the same in the pdf: 

![image](https://user-images.githubusercontent.com/57860800/108589173-72cb2200-735d-11eb-9b9c-68cdee6ce1de.png)

In the SVG, opacity was introduced via style="opacity:${opacity_value};". The expected outcome is that the overall opacity would change without overlapping fill and borders. 

(see here for the expected behavior:
![image](https://user-images.githubusercontent.com/57860800/108589261-e705c580-735d-11eb-80bf-0cc8c41f48e8.png)
 )

Also, noticed that when introducing opacity to the content description as a style, as in: 

 const  sampleDocDefinitionSVG = {
      content: [
        {
          // If no width/height/fit is used, then dimensions from the svg element is used.
          svg: '<svg width="300" height="200" viewBox="0 0 300 200"><rect x="3" y="3" width="80" height="60"/></svg>',
          absolutePosition: {x:100, y:50},
          opacity:0.5,
        },
      ]
    };

... the opacity is not applied and the rect remains solid black. 

Cheers,
Alex

**Comment by HypergeneticSpacekid** [comment]
I found out that this actually works in the preview. After some more testing it turns out that this depends on the pdf viewer chosen. E.g. react-pdf does not display this properly. Acrobat however does. Thus, it might a bug a the viewer rather than this library.

**Comment by liborm85** [comment]
PDF viewer issue. Not related with pdfmake.
