### ISSUE TITLE
TypeError: Cannot read property '_minWidth' of undefined with the right number of columns ?

### ISSUE THREAD

**Issue by YoannBuzenet** [bpampuch/pdfmake#2194]
Hello, I have this error while compiling my pdf  : 
`TypeError: Cannot read property '_minWidth' of undefined`

However, when I check in debug mode each table, each rows has the right number of elements : same array length as the table width.

I don't understand why it is happening. Can other thing trigger that error ?

**Comment by YoannBuzenet** [comment]
Is there a way to know which table has an error ?

**Comment by YoannBuzenet** [comment]
Ok, finally found how which table it was. The number of columns was right, it was the colspan that was indicating a wrong number.

If anyone has the same problem, to find out I did just put a console.log in the lib, in docMeasure.js, line 712, to find out.

**Comment by liborm85** [comment]
Attach example for reproduce issue.
