### ISSUE TITLE
SVG inline styles are overridden with class styles in the PDF generated

### ISSUE THREAD

**Issue by IndraRed1** [bpampuch/pdfmake#2198]
Hi, In the browser, SVG class styles are overridden by inline styles, but the generated pdf is taking class styles over inline styles. Please provide a way to override the class styles with inline styles.

To replicate, copy the code in the attached file to
[playground-code.txt](https://github.com/bpampuch/pdfmake/files/6044897/playground-code.txt)
 [http://pdfmake.org/playground.html](http://pdfmake.org/playground.html)

**Comment by liborm85** [comment]
Pdfmake use [svg-to-pdfkit library](https://github.com/alafr/SVG-to-PDFKit) for svg transformation to pdf. Create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).
Not related with pdfmake.
