### ISSUE TITLE
Cannot assign to 'fonts' because it is a read-only property.ts(2540)

### ISSUE THREAD

**Issue by oleroling** [bpampuch/pdfmake#2200]
![app component ts - demo-pdfmake - Visual Studio Code 2_3_2564 15_28_02 (2)](https://user-images.githubusercontent.com/58808126/109620744-cf53eb80-7b6c-11eb-967a-c982b9c8bb05.png)

Hey man!! I tried to follow your guide but why i stuck to this error ? Can u explain this bug for me ?

**Comment by liborm85** [comment]
Typescript is not officialy supported, see https://github.com/bpampuch/pdfmake/issues/525. Probably you have wrong d.ts definition.
