### ISSUE TITLE
Ability to add a Progress Bar

### ISSUE THREAD

**Issue by Sun3** [bpampuch/pdfmake#2201]
Is there a way to add a Progress Bar inside of a table cell and have the width expand to the width of the cell?

Thank you

**Comment by djungowski** [comment]
If you use the master branch instead of the version provided by `npm install` you can use the following:
```
const progressCallback = (progress) => {
  console.log(progress);
};

pdfMake.setProgressCallback(progressCallback);
```

progress is a float value. To use the master version, update your package.json to the following:
```
"pdfmake": "github:bpampuch/pdfmake#master",
```

**Comment by liborm85** [comment]
You can use canvas node with vectors, see example in [/examples/vectors.js](https://github.com/bpampuch/pdfmake/blob/0.1/examples/vectors.js).
