### ISSUE TITLE
Importing in Svelte Sapper gives Assigning to rvalue (5090:0) error

### ISSUE THREAD

**Issue by 1140251** [bpampuch/pdfmake#2204]
I tried to import in Svelte using sapper

```
import pdfMake from 'pdfmake/build/pdfmake';
  import pdfFonts from 'pdfmake/build/vfs_fonts';
```
but gives error in build
```
Assigning to rvalue (5090:0) in C:\project\node_modules\pdfmake\build\pdfmake.js
5088: };
5089: process.title = 'browser';
5090: process.browser = true;
```

**Comment by liborm85** [comment]
I don't see `rvalue` variable on line 5090.
I don't know Sapper. Ask on Sapper support.

**Comment by 1140251** [comment]
It is just the error that shows. If you searched a bit  of what it means you would see that is trying to access a variable that does not exist. 
Probably is a sapper configuration but if you don't provide support for the use of the package in the frameworks, how can I know if the problem is not with your package? One less person that wanted to use this package.

**Comment by liborm85** [comment]
As I've already written, I don't know Sapper and its error messages.
Problem is not in pdfmake package, becouse line with this error is from library https://www.npmjs.com/package/process.
