### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by tcsaddul** [bpampuch/pdfmake#2205]
@liborm85 @bpampuch  I would like to donate/sponsor ???? USD as a way to thank you for this library.  Can you setup a "Donate" or "Sponsor" button?

**Comment by jordankkk** [comment]
+1

**Comment by vini-brito** [comment]
Since there's no central organization to this, it seems that what you could do is donate developer time. Either yours or pay someone to spend some time working on the library.

**Comment by tcsaddul** [comment]
Rignt now we cannot donate developer time so we decided to donate money instead. Since I have observed that @liborm85 is the one working hard for this library for past few years. I would donate the amount to him if he wants.  Though 1k USD maybe small to many, it's like buying a coffee to someone who's working hard for something of great value to us.

**Comment by tcsaddul** [comment]
I'm closing this now since nobody is interested in our offer of donation. So what I can offer now is say --- THANK YOU for this awesome project.
