### ISSUE TITLE
Cannot get page number when create pdf from server-side

### ISSUE THREAD

**Issue by spinater** [bpampuch/pdfmake#2210]
my server-side code 

module.exports = function (pdfDoc, callback) {

    var fontDescriptors = {
        DB_HelvethaicaX: {
            normal: path.join('./assets/fonts/', 'DB Helvethaica X Cond v3.2.ttf'),
            bold: path.join('./assets/fonts/', 'DB Helvethaica X Blk Cond v3.2.ttf'),
            italics: path.join('./assets/fonts/', 'DB Helvethaica X Med Cond It v3.2.ttf'),
            bolditalics: path.join('./assets/fonts/', 'DB Helvethaica X Blk Cond It v3.2.ttf')
        }
    };

    var printer = new pdfMakePrinter(fontDescriptors);

    var doc = printer.createPdfKitDocument(pdfDoc);

    var chunks = [];
    var result;

    try {

        console.log('doc on')

        doc.on('data', function (chunk) {
            chunks.push(chunk);
        });

        doc.on('end', function () {
            result = Buffer.concat(chunks);
            callback(result);
            //callback('data:application/pdf;base64,' + result.toString('base64'));
        });
        doc.end();

    } catch (error) {

    }

}

my client-side code 

    pdfContent = {

        pageSize: 'A4',
        pageMargins: [20, 80, 0, 80],

       footer: function(currentPage, pageCount) { return currentPage.toString() + ' of ' + pageCount; },
       
       defaultStyle: {
            font: 'DB_HelvethaicaX'

        },
        styles: {

            checkboxMargin: {
                margin: [5, 0, 0, 0],
            },
            header: {
                fontSize: 18,
                bold: true
            },
            tableHeader: {
                fontSize: 18,
                bold: true
            },
            subheader: {
                fontSize: 12,
                bold: true
            },
            subheaderMoney: {
                fontSize: 12,
                alignment: 'right',
                bold: true
            },
            subheaderMoneyTitle: {
                fontSize: 12,
                alignment: 'right',
                bold: true
            },
            contentCenter: {
                alignment: 'center',
            },
            subheaderMoneySpell: {
                fontSize: 15,
                alignment: 'center',
                bold: true
            },
            quote: {
                italics: true
            },
            small: {
                fontSize: 8
            },
            tableDetail: {
                alignment: 'center', absolutePosition: { y: 150 },
            },
            checkBoxText: {
                alignment: 'left', paddingLeft: -10,
            },

            background1: {
                background: '#5190a5'
            },
            header: {
                fontSize: 22,
                alignment: 'center',
                color: 'white',
            },

        },
    }
    
    

anything working on PDF but page number doesn't show at all

I sent a whole pdfContent from client-side and let server-side generate pdf and return to client as blob

**Comment by liborm85** [comment]
How you send JSON from client to server? Probably footer function is not interpreted.
