### ISSUE TITLE
Unbreakable, but large - what happens (other than is not being printed)

### ISSUE THREAD

**Issue by skiv71** [bpampuch/pdfmake#2219]
As per the subject, printing a dynamic table, in the last case, it was large... and I'd prefer unbreakable.... but in the produced document, I ended up with a blank page. What should I do? I "could" split the tables apart when I exceed a 'guessed' number of entries... but am hoping there's some feature of the lib I've not seen?

**Comment by liborm85** [comment]
Known issue. Duplicate: https://github.com/bpampuch/pdfmake/issues/207
