### ISSUE TITLE
errors loading images / feature request: read svg from file

### ISSUE THREAD

**Issue by thebirdman7** [bpampuch/pdfmake#2221]
When you setup image paths in the image dictionary to be loaded for you by PDFMake, it appears that any error in retrieving the image may not be handled properly. The only way I was able to trap that type of error was to setup an unhandled promise rejection event listener. I have noticed that it is suggested to use a try catch block around the pdf make creation process, but this does not work in this particular case due to the nature of the async get. It would be nice if it were possible to trap this error normally either by having PDFMake return a promise or by perhaps by adding a catch block at the end of your async request and throwing the error normally. 

Related to this, I would like to request a feature. We have color themes on our site and users may also upload a logo. Some of these images are SVGs. It is not ideal to check this data for SVGs and then do alternate handling of these images, dynamically setting "image" or "svg" and then removing them from the dictionary so as not to cause an error. It would be ideal if PDFMake supported reading SVGs from a file as our reportsinvariably include logos and static SVG charts. The other choice is to handle all image handling myself, which I may end up doing, because then I can trap an error and decide if the image is a deal breaker (which in most cases it is not) and perhaps use a placeholder SVG or something so that report creation can continue (this would be another great feature, if we could provide a placeholder SVG or image to be used in the event an image cannot be found).

Thanks for your consideration!

**Comment by liborm85** [comment]
Catching errors with loading images/fonts/etc. will be supported in version 0.2, where everything will return Promise. See https://github.com/bpampuch/pdfmake/issues/866, https://github.com/bpampuch/pdfmake/issues/2066

**Comment by thebirdman7** [comment]
That is awesome!
