### ISSUE TITLE
exception on exporting multiple times, with image in header()

### ISSUE THREAD

**Issue by nehawawalkar** [bpampuch/pdfmake#2223]
Hello,
I have an app, where I'm using datatable for my reporting area. I have put image in header function of pdfmke customize(), as I want company logo in header of every exported file. When I export on first load, it gets exported with the image in header as expected but when I'm trying to re generate the pdf it throws error (Uncaught invalid image, images dictionary should contain dataURL entries (or local file paths in node.js)). I tried to debug this, which leads to image in ImageMeasure.prototype.measureImage (), comes as null on re generating, and the src argument of this same function holds value $$pdfmake$$1 which was DataURI(base64 encoded) on first load or when I first generated the pdf.

Please help if you could understand whats wrong.

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.

**Comment by nehawawalkar** [comment]
I have tried it here in this fiddle [https://jsfiddle.net/hakuna_matata/xw7jaqyn/20/](https://jsfiddle.net/hakuna_matata/xw7jaqyn/20/) but I'm not able to reproduce same error. my issue is similar to#54, I wonder how he fixed it.
