### ISSUE TITLE
Errors are not thrown leading to my code not catching error

### ISSUE THREAD

**Issue by Nitheeshskumar** [bpampuch/pdfmake#2224]
I am having a use case where I am creating the data url to display it inside an iframe. I am triggering a loader during generation and the loader stops and displays the pdf within iframe upon successful generation. But when there are any error during pdf generation, it is not exposed outside pdfmake and hence its not getting caught in my tru catch. Hence the loader stills runs after an error occured. Errors are simply logged in the console.
Expected behaviour : throw error so the developers can handle it

**Comment by liborm85** [comment]
Catching errors will be improved in version 0.2. See https://github.com/bpampuch/pdfmake/issues/866, https://github.com/bpampuch/pdfmake/issues/2066
