### ISSUE TITLE
Please Help: Image Page Break

### ISSUE THREAD

**Issue by lartheon** [bpampuch/pdfmake#2230]
Hello, I hope someone could advise me. 

I am converting a html page into a PDF (I'm not fetching images individually). I have several large images which are dynamically generated and embedded into html page that I have fetched, when I view the PDF the images exceed the page height and does not continue onto the next page. 

BTW I've also noticed that large images will overlap the footer, I'm not sure if this is intended (I hope there is a setting to change this) or a bug.

I did search for closed issues but the solution found here does not fit my case since my html content is dynamically created by several different vue components https://github.com/bpampuch/pdfmake/issues/1602 

Thank you

**Comment by liborm85** [comment]
If image is larger than page, split to multiple images is required (use 3rd part tool/library).
