### ISSUE TITLE
How to use Roboto font server-side?

### ISSUE THREAD

**Issue by fs1995** [bpampuch/pdfmake#2232]
Hello,

I see in the changelog for version 0.1.71, Roboto font was updated... but how do I use this font (server-side)? The documentation does not list it.

https://pdfmake.github.io/docs/0.1/fonts/standard-14-fonts/

**Comment by liborm85** [comment]
On server-side you are not limited by choice of fonts, you can download from anywhere. Roboto font you can download [here](https://github.com/bpampuch/pdfmake/tree/0.1/examples/fonts) or [here](https://cdnjs.com/libraries/pdfmake).

**Comment by filnko** [comment]
Roboto is the default font, see here: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/
