### ISSUE TITLE
Define Paper Tray per Page?

### ISSUE THREAD

**Issue by TimCarloPPI** [bpampuch/pdfmake#2233]
By chance is there undocumented capability to define the tray the paper will draw from when the page is printed?   For example, page 1 = draw from tray 2, page 2 = tray3, page 3 = tray 2, page 4 = tray 1.

**Comment by liborm85** [comment]
Cannot be defined in PDF document. This depends on printer or printer drivers.

**Comment by TimCarloPPI** [comment]
I disagree with "Cannot be defined in PDF document" because I am a user of 10-15 year old forms merge software that produces a PDF with the feature I am asking about.  Maybe, should have been written, "Cannot be defined in PDF document with this library"?
Anyway, my colleagues are enthusiastic with what pdfmake has facilitated, and are hopeful for additional capabilities.

**Comment by liborm85** [comment]
Merging documents with different page sizes and using different trays makes a difference.
Any link to pdf standard that this is possible?

**Comment by TimCarloPPI** [comment]
Realize that there will be a full spectrum of people who may want to use this library to solve their problem, from "I don't care how it works, just so it works" to "Of course I know that function is not defined in the standard for this technology, why even ask that question?".  I am somewhere in the middle.  So what I know is that I have a licensed PDF creator that can set a paper tray for a page that will be printed.  This works for me because I know where that PDF will be printed, and the PDF is not for any other use,  The pdf I create is indeed less "portable" than what the standard defines, but again fulfills my need.  So as I try to figure out how I might be able to make things happen similarly within the context of NodeJS, I start reading more and there it is, the pdf standard does not TECHNICALLY have my requested feature available.  In the pdf v1.5 reference, however , there is discussion of certain places where other/non-native application code can be stashed, that will be ignored by pdf page rendering processes?  Like I said, I am one of those users of this library who is somewhere in the middle of the spectrum.  A search on the tray selection topic turns up results on how it can generally be accomplished and something about Adobe themselves having this JDF Ticket ride along file that does some of this tray selection capability also.  That's about how far I have time and energy for. 

So in the short term, I will continue to use pdfmake to accomplish whatever I can do with it.  And search for other solutions for my per page tray selection needs.
