### ISSUE TITLE
pdfhtml5 custom font

### ISSUE THREAD

**Issue by phyuphyuthaw** [bpampuch/pdfmake#2235]
Hello Author,
Thank you for your distribution. I would like to ask some questions. I am doing a function to export datatable pdf using Datatable-pdfHtml5. There are some Japanese words in my table and I would like to change custom fonts. I have read your documentation and have done adding custom fonts into vfs_fonts.js file. What should I do as a next step to be able to appear/export datatable?
Please kindly reply to me. Thank you.

**Comment by liborm85** [comment]
Example for use multiple fonts in pdfmake:
```js
var dd = {
	content: [
		{ text: 'Text in language A', style: 'langA' },
		{ text: 'Text in language B', style: 'langB' }
	],
	styles: {
		langA: {
			font: 'Font1',
		},
		langB: {
			font: 'Font2',
		}
	}
};
```
