### ISSUE TITLE
Alignment issue

### ISSUE THREAD

**Issue by tmatheas2000** [bpampuch/pdfmake#2236]
I am using pdfmake in my web application for generating question paper as pdf. In the image the first page, mark alignment in the right is working fine whereas in the second page, mark alignment in the right is little off from alignment.

![pdfmake alignment](https://user-images.githubusercontent.com/54699140/114710380-44f5ce80-9d4b-11eb-859e-f84d604442ce.png)

            l={};
            l.columns=[];
            column={};
            column.text = i+')\t';
            column.style='top';
            column.width='5%';
            l.columns.push(column);
            column={};
            column.text = htmlToPdfmake(question.questionText);
            column.style='top';
            column.width='80%';
            l.columns.push(column);
            column={};
            column.text = '['+question.actualMarks+' marks]';
            column.width='15%';
            column.style="markText";
            l.columns.push(column);
            l.style='textMargin';
            this.contentObj.push(l);

**Comment by liborm85** [comment]
Attach full example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).
