### ISSUE TITLE
LineBreak Algorithm does not support numbers as text (word wrap)

### ISSUE THREAD

**Issue by jwallet** [bpampuch/pdfmake#2242]
Hi,

I found out that the library pdfmake uses to detect and wrap lines based on the available width [linebreak](https://github.com/foliojs/linebreak) does not handle text with numbers, it can't wrap in a cell set with a width "*" (fill)

uncomment the line to test it out.

believe it or not there is a use case for that; 

```
var textAsText = "sadsadsadasdsada/sds/adsa/da/dsad/as/da/dsa/sa/sada/sds/sa/dsa/dsa/das/dsa/sadasadasd";
var numberAsText = "1123213/123/123/1232/112/312/12/321/12/123/312/213/123/12/312/321/2/3123/123/12/313";

var dd = {
	content: [
		{text: 'Tables', style: 'header'},
		'The following table has nothing more than a body array',
		{
			table: {
    			widths: ['*', 150, 150],
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					[textAsText, 'Another one here', 'OK?'], // letters does wrap
				// 	[numberAsText, 'Another one here', 'OK?'] // numbers does not wrap
				]
			}
		},
	],
}
```

![image](https://user-images.githubusercontent.com/23088305/117087206-c7efc080-ad1c-11eb-9f49-04e9b247aafc.png)

![image](https://user-images.githubusercontent.com/23088305/117087238-d3db8280-ad1c-11eb-8d19-bb9ffdb75baa.png)

search engine keywords:
> pdfmake does not wrap text without spaces (no space) when it only contains numbers in a table cell.
> npm linebreak, linebreaker cannot evaluates nextBreak if text contains only numbers.

using:
- PdfMake 0.1.71
- Node 14.16

related to:
- [linebreak](https://github.com/foliojs/linebreak)

**Comment by jwallet** [comment]
also if I use `textAsText` and add a number after every `/` then I get the same behavior
`abc/1def/2ghi/3jkl/4mno/5pqr/6stu/7vxyz`
it can also be separate with another unicode like `-`

**Comment by liborm85** [comment]
This is expected behaviour. Unicode line breaking algorithm is used, see http://www.unicode.org/reports/tr14/.

**Comment by robbytx** [comment]
I've run across this also, and it looks like https://github.com/foliojs/linebreak/issues/7 provides further explanation on the issue.
