### ISSUE TITLE
Cell with multiple lines line break issue

### ISSUE THREAD

**Issue by mamosingh** [bpampuch/pdfmake#2245]
When the last row on a page has a cell with multi lined text it renders part of the text on the last row of first page and the rest of the text is displayed on the first row of next page but with all other cells blank. See screenshot - https://www.dropbox.com/s/fag0mey15ydeff7/file__45__pdf.png?dl=0.

The expectation is if last row has text that spills over then it should force a line break.

Any suggestions to fix this issue?

**Comment by liborm85** [comment]
Attach simple runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
