### ISSUE TITLE
HU003 - Modelo de datos, usuarios

### ISSUE THREAD

**Issue by FUTTO86** [bpampuch/pdfmake#2248]
Una vez se registren los usuarios, se debe alimentar la BD en el modelo con la información que se reciba vía: método de registro manual / registro vía redes sociales 
El sistema debe guardar la información que se capture de las APIs de autenticación de estas redes: nombre, teléfono, email, perfil de usuario
El sistema debe asignar un ID único a cada usuario
El sistema debe realizar validaciones como:
No permitir 2 usuarios con el mismo profile de redes
Validar el ingreso de contraseñas con las políticas definidas (longitud, caracteres, etc)

**Comment by liborm85** [comment]
STOP SPAMMIG!
