### ISSUE TITLE
Not able to make use of download or open function in windows 8 app.

### ISSUE THREAD

**Issue by AADVIKGUPTA** [bpampuch/pdfmake#225]
Not able to make use of download or open function in windows 8 app. pdfMake.createPdf() is working fine in windows 8 app but download or open functions are coming undefined.

**Comment by bpampuch** [comment]
pdfMake contains only ```createPdf```, the others can be called on the returned object:

```
// open the PDF in a new window
 pdfMake.createPdf(docDefinition).open();

 // print the PDF (temporarily Chrome-only)
 pdfMake.createPdf(docDefinition).print();

 // download the PDF (temporarily Chrome-only)
 pdfMake.createPdf(docDefinition).download('optionalName.pdf');
```

**Comment by AADVIKGUPTA** [comment]
Yes . I do understand that and infact in chrome browser  pdfMake.createPdf(docDefinition).download('optionalName.pdf') is working fine, but issue lies in Windows 8 Application. It ( pdfMake.createPdf(docDefinition).download('optionalName.pdf')) just say undefined.

**Comment by AADVIKGUPTA** [comment]
Any update on same ?

**Comment by ethanova** [comment]
In my Win8 app, I just get the base64 from pdfmake and then use Windows API to actually open the file; I'd recommend you do the same.

var localFolder = Windows.Storage.ApplicationData.current.localFolder;
            localFolder.createFileAsync(fileName, Windows.Storage.CreationCollisionOption.replaceExisting).then(function (file) {
                Windows.Storage.CachedFileManager.deferUpdates(file);
                var buffer = Windows.Security.Cryptography.CryptographicBuffer.decodeFromBase64String(fileBase64);
                Windows.Storage.FileIO.writeBufferAsync(file, buffer).done(function () {
                    Windows.Storage.CachedFileManager.completeUpdatesAsync(file).done(function (updateStatus) {
                        console.log(updateStatus);
                        var options = new Windows.System.LauncherOptions();
                        Windows.System.Launcher.launchFileAsync(file, options);
                    });
                });
            });

**Comment by liborm85** [comment]
Windows 8 app is not browser window then not supported `download()`, `open()`, `print()`. You can use the code above.
