### ISSUE TITLE
HU005 - Recuperación de contraseña

### ISSUE THREAD

**Issue by FUTTO86** [bpampuch/pdfmake#2250]
El sistema habilitará la recuperación de la contraseña bajo el siguiente flujo
Usuario hace clic en “recuperar contraseña”
FUTTO app da la opción de enviar el link de recuperación al email o a un sms
El usuario visita el link enviado
El sistema le presenta al usuario la opción de crear una nueva contraseña

**Comment by liborm85** [comment]
STOP SPAMMIG!
