### ISSUE TITLE
HU007 - Notificar videos a usuarios

### ISSUE THREAD

**Issue by FUTTO86** [bpampuch/pdfmake#2252]
Una vez que sea asociado un video a un partido, el sistema deberá enviar un SMS/email a los usuarios con el código para que el video sea visible en “Mis partidos”
Este código será numérico de 6 dígitos
El sistema hará un recorrido por la base de datos de usuarios y enviará la notificación a los usuarios que quedaron confirmados / asociados al partido correspondiente
El sistema tiene una asociación vídeo (recurso multimedia) - partido
El sistema tiene una asociación 1-n (partido - usuarios)
Detalles del contenido del mensaje
Asunto: xxx
Cuerpo: xxx
Detalle del formato:

**Comment by liborm85** [comment]
STOP SPAMMIG!
