### ISSUE TITLE
HU008 - Subir videos

### ISSUE THREAD

**Issue by FUTTO86** [bpampuch/pdfmake#2253]
el sistema mostrará una pantalla para permitir el upload de un video de un partido
este recurso multimedia se subirá a Amazon S3
En el momento del upload, el sistema solicitará al usuario la metadata correspondiente al video en cuestión:
Partido: lista desplegable (debe tener capacidad de búsqueda por: Nombre del partido, cancha, fecha)
datos adicionales?

**Comment by liborm85** [comment]
STOP SPAMMIG!
