### ISSUE TITLE
HU010 - Visualizar videos completos

### ISSUE THREAD

**Issue by FUTTO86** [bpampuch/pdfmake#2255]
El usuario podrá visualizar el listado de videos para los cuales le ha sido enviado un código
En otras palabras, el usuario solo podrá visualizar los videos para los partidos que cumplan las siguientes condiciones:
Fue invitado
El capitán aprobó su participación
Este listado tendrá filtros de búsqueda con el fin de que el usuario pueda encontrar rápidamente el video que desea hallar. 
El sistema presentará un search con un único TextBox, el cual internamente buscará en los campos:
Nombre del partido
Ciudad

**Comment by liborm85** [comment]
STOP SPAMMIG!
