### ISSUE TITLE
Feature Request: Make property preserveLeadingSpaces default to true instead of false

### ISSUE THREAD

**Issue by bradws** [bpampuch/pdfmake#2257]
May I suggest the property `preserveLeadingSpaces` to be have the default set as `true`.
It is currently set to false.

I would submit that the common case scenario is for people wanting white spaces to be incorporated by default, with the less-common approach for them NOT to be preserved.

By doing this, it makes adding the additional code `{ ...preserveLeadingSpaces : true; }` unnecessary resulting in less clutter in the application.

If there is agreeance, I would be happy to assist with this change (only if people agree)

As an addendum: Are there any other defaults that others have considered?

**Comment by liborm85** [comment]
Value for `preserveLeadingSpaces` can be changed via `defaultStyle`, see example:

```js
var dd = {
	content: [
		'  First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines',
		'    Next another paragraph'
	],
	defaultStyle: {
		 preserveLeadingSpaces: true
	}
}
```

**Comment by bradws** [comment]
Thanks :)  Yep, I get that ;)  My suggestion was for the system to default to true, thus not needing to manually specify a value for preserveLeadingSpace. This is a great suggestion, but in my use case there are many named styles, and all currently require the `preserveLeadingSpaces: true` code. Would be great if I didn't have to do that, and I'm assuming most people would to? It would probably break some existing users' code though. I mention this here for a discussion.   :)

**Comment by liborm85** [comment]
Current default behavior is expected behavior.
