### ISSUE TITLE
How to add the generated PDF file to jsZip

### ISSUE THREAD

**Issue by julieagaze** [bpampuch/pdfmake#226]
Hi,
  My utility uses pdfMake on client and generates around 500 files. 
We cannot directly create a folder and put the files into the same using JavaScript.
Can you share examples where we can put the generated out put into a zip file so that we have just one download?(using JSZip)

TIA

**Comment by jthoenes** [comment]
Hi, I don't have an example. You'll have to look into the JSZip documentation for that.
