### ISSUE TITLE
stream unidentified

### ISSUE THREAD

**Issue by KKamaa** [bpampuch/pdfmake#2260]
Hello, I am trying to insert a logo to my pdf using datatables. Funny enough if i use the datatables logo encoded in Base64 it works
but any other image produces an error "stream unidentified"
`doc['header'] = (function(){
                                             return {
                                                 margin: 10,
                                                 columns: [
                                                     {
                                                         alignment: 'left',
                                                         image: 'uri of base64 for datatables logo'
                                                         width:50,
                                                         height:50
                                                     },
                                                     {
                                                         margin: [10, 0, 0, 0],
                                                         text: 'Here goes the rest'
                                                     }
                                                     ],
                                                 content: [
                                                     'Here goes your content',
                                                 ],
                                             };
                                         });`
above works well
but if i trying any other image it fails with error "stream unidentified" error log below
`

TypeError: stream is undefined

http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:11733
Traceback:
flow@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:11733:19
zlibBuffer@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:11729:3
exports.inflate@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:11690:10
PNG</PNG.prototype.decodePixels@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:58542:19
splitAlphaChannel@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:23287:25
embed@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:23253:21
ImageMeasure.prototype.measureImage@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:62347:9
DocMeasure.prototype.measureImage@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59915:36
DocMeasure.prototype.measureNode/<@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59813:30
StyleContextStack.prototype.auto@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:17366:15
DocMeasure.prototype.measureNode@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59794:25
DocMeasure.prototype.measureColumns@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:60262:21
DocMeasure.prototype.measureNode/<@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59799:30
StyleContextStack.prototype.auto@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:17366:15
DocMeasure.prototype.measureNode@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59794:25
DocMeasure.prototype.measureDocument@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:59787:14
LayoutBuilder.prototype.addDynamicRepeatable@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:58963:37
LayoutBuilder.prototype.addHeadersAndFooters@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:58989:8
LayoutBuilder.prototype.tryLayoutDocument@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:58917:7
LayoutBuilder.prototype.layoutDocument@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:58892:20
PdfPrinter.prototype.createPdfKitDocument@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:18407:22
Document.prototype._createDoc@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:17867:20
Document.prototype.getBuffer@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:18011:17
Document.prototype.getBlob@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:18001:7
Document.prototype.download@http://localhost:9708/report_generator/static/src/js/lib/pdfmake.js:17969:7
action@http://localhost:9708/report_generator/static/src/js/lib/buttons.html5.js:509:46
g@http://localhost:9708/report_generator/static/src/js/lib/dataTables.buttons.js:204:26
_buildButton/k<@http://localhost:9708/report_generator/static/src/js/lib/dataTables.buttons.js:215:64
dispatch@http://localhost:9708/web/static/lib/jquery/jquery.js:4641:58
add/elemData.handle@http://localhost:9708/web/static/lib/jquery/jquery.js:4309:63
`

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.

**Comment by KKamaa** [comment]
So am using it on Odoo so it's js structure is different but the issue is image format. Funny enough a screenshot works well but if I pick an image say a logo I get an error stream unidentified. So not sure why it's selective on image.
