### ISSUE TITLE
How to prevent string breaks on two separate lines

### ISSUE THREAD

**Issue by AntonNazarenko** [bpampuch/pdfmake#2261]
Hello! I have a table and a string, the string looks like this **10,000.00 $**. When the value in the string either more or equals 10 000 or less than 1 000 000 the string breaks into two separate lines ( the dollar sign occurs on the second line ) but if the value is bigger than 1 000 000 or less than 10k everything goes fine, how I can prevent the row splitting? ( Also, if I'm replacing spaces between the dollar sign and the amount with other signs (for instance, underscore everything also goes okay).

**Comment by Cowraider** [comment]
Try using `unbreakable: true`

For example like this 

```
{ 
  text: '10 000, 00$',
  unbreakable: true
}
```

**Comment by sepsol** [comment]
> Maybe using `unbreakable: true` could help here?
> 
> For example like this
> 
> ```
> { 
>   text: '10 000, 00$',
>   unbreakable: true
> }
> ```

This doesn't work
