### ISSUE TITLE
Callback function after download

### ISSUE THREAD

**Issue by damcompany** [bpampuch/pdfmake#2264]
Hello, I'm trying to use the callback function as a parameter of the download() method, but it seems it doesn't work.
The download starts properly, but no alert appears when download is finished.

pdfMake.createPdf(docDefinition, null, fonts).download("test.pdf", function(){ alert("test"); });

**Comment by liborm85** [comment]
Tested and callback parameter works. Create example for reproduce issue on [jsfiddle.net](https://jsfiddle.net/) or similar.

**Comment by damcompany** [comment]
This is the fiddle, we are using 0.2 version of pdfmake
https://jsfiddle.net/zpLt0d78/1/

**Comment by liborm85** [comment]
0.2 use promises, see https://github.com/bpampuch/pdfmake/issues/866

Version 0.2 is unstable and is not for production use.
