### ISSUE TITLE
Fonts don't renders correctly in Chrome on v0.2.0-alpha.0 and v0.1.71 versions

### ISSUE THREAD

**Issue by javier-dominguez** [bpampuch/pdfmake#2265]
I have problems with fonts on v0.2.0-alpha.0 and v0.1.71 versions in **Chrome**

I'm using default font (ROBOTO) and custom fonts and in both case I've the same result.

The font is renders correctly when the PDF is generated in Firefox, but not in Chrome.

_**avión año**_ (**Firefox**)
_**aviÃ³n aÃ±o**_ (**Chrome**)

It's not working when I create a pdf in local using (**Chrome**) but if I run the code in **Firefox** or in http://pdfmake.org/playground.html it's working perfectly.

I'm working on MacOS.
what Am I supposed to do?
I suspect it's a pdfmake issue.

**Comment by liborm85** [comment]
Probably your script file is saved in wrong code page. Re-save script file in UTF-8.

**Comment by javier-dominguez** [comment]
> Probably your script file is saved in wrong code page. Re-save script file in UTF-8.

@liborm85 you saved the day, thank you very much. I appreciate your quick response. 

I was working with **UTF-8** but I tried to switch to **UTF with BOM** and It worked, thanks to you.

I don't really know what the main difference between the two formats is, but I will look into it.
