### ISSUE TITLE
header and footer function not working since last file updates

### ISSUE THREAD

**Issue by bschumi** [bpampuch/pdfmake#227]
since the last file updates the function for header and footer are not working anymore.
i test it on my code and in the playground, but dosent work. I've used the example code: 

footer: {
    columns: [
      'Left part',
      { text: 'Right part', alignment: 'right' }
    ]
  },

There is no error in the console, but the pdf show nothing.

**Comment by jthoenes** [comment]
Hi, 

I'll try to look into that soon. For now, you can use a function as workaround to make it work:

````javascript
footer: function() {
  return {
    columns: [
      'Left part',
      { text: 'Right part', alignment: 'right' }
    ]
  };
},
````

**Comment by jthoenes** [comment]
Fix will be in next release.
