### ISSUE TITLE
Table with rowSpan is rendered incorrectly if broken by pageBreak

### ISSUE THREAD

**Issue by miroslavvojtus** [bpampuch/pdfmake#2274]
We have several several tables with row-spanning cells in our project and they could be broken anytime as the content is build dynamically. It often happens that it breaks in middle of row-spanning cell what almost overtime breaks the table as shown on next image.
![image](https://user-images.githubusercontent.com/208306/122570731-52318100-d04c-11eb-83cc-1534963012a4.png)

In the example above I deliberately shifted default table in playground in a way that it is broken in middle of row-span.
https://pastebin.com/hmXakSUa

I attempted to fix it in our code with the `dontBreakRows: true` flag but it seems to be also buggy (see #1159).
Some rows were lost some had improperly calculated heights etc.

Is there a reliable way to prevent breaking rows with row spanning cells?

If there would be some initial guidance where to try to fix I would volunteer.

**Comment by liborm85** [comment]
Known issue. Help is welcome.

duplicate: https://github.com/bpampuch/pdfmake/issues/928
