### ISSUE TITLE
Link is not clickable if text is wrap first in strong tag and after that added link on that bold text <a href='https://www.google.com'><strong>Google</strong></a> (And same for underline too)

### ISSUE THREAD

**Issue by Prakash-karena** [bpampuch/pdfmake#2276]
Link not clickable if first added any style on text and after that added link.

Steps to reproduce
I have used html-to-pdfmake to convert html to pdf and used that value inside pdfmake and after that once pdf generated i have used that pdf here. into that pdf link is not clickable.

Expected behavior
link should be clickable even if strong added first and after that link is added

Additional information

![Screenshot from 2021-06-22 19-09-18](https://user-images.githubusercontent.com/63772512/122935895-57653780-d38e-11eb-9201-6463787329a9.png)

Here on above supermart first added bold after that added link so that is not clickable and on below supermart first added link and after that added bold so that is clickable.

Environment : any

Browser (if applicable) [e.g. Chrome 57, Firefox 59]: any
React-PDF version [ 4.2.0]:
React version [16.13.1]:
pdfmake [^0.1.66]

**Comment by liborm85** [comment]
Attach runnable example on http://pdfmake.org/playground.html for reproduce issue.

**Comment by Prakash-karena** [comment]
Hi Libor,
  I have added example in comment please verify and let me know if anything
required.
https://github.com/bpampuch/pdfmake/issues/2276#issuecomment-866642740.

Thanks & Regards,
Prakash Karena

**Comment by liborm85** [comment]
This is wrong definition, because `link` must be in `text` node:
```js
{
  "text": [
    {
      "text": "Google",
      "nodeName": "STRONG",
      "color": "blue",
      "decoration": ["underline"],
      "bold": true,
      "style": ["html-strong", "html-a", "html-p"],
    }
  ],
  "nodeName": "A",
  "color": "blue",
  "decoration": ["underline"],
  "style": ["html-a", "html-p"],
  "link": "https://www.google.com/"
},
```

This is correct definition:
```js
{
  "text": [
    {
      "text": "Google",
      "nodeName": "STRONG",
      "color": "blue",
      "decoration": ["underline"],
      "bold": true,
      "style": ["html-strong", "html-a", "html-p"],
      "link": "https://www.google.com/"
    }
  ],
  "nodeName": "A",
  "color": "blue",
  "decoration": ["underline"],
  "style": ["html-a", "html-p"]
},
```

**Comment by Prakash-karena** [comment]
My requirement is to generate pdf from RTE content. So what i am doing is i'm using react-to-pdfmake to conver my RTE content to html to pdf and after that i am using that content here. 

From RTE if user added link first and after that if then added bold then at that time it is working fine.but if user added bold on text first and after that if added link then this issue occur. So is there any possible solution for this.

**Comment by liborm85** [comment]
This is not related with pdfmake library. Problem is in html-to-pdfmake library.
