### ISSUE TITLE
problems with lists when using httml-to-pdfmake

### ISSUE THREAD

**Issue by rbarbeito** [bpampuch/pdfmake#2280]
I am trying to generate a pdf from a query to a database, where the information has HTML code, like lists. `<p><strong>DDDDD</strong></p><ol><li>jkdbkjdf</li><li>bjdbfkjadsf</li><li>kjdnfkadf</li></ol><ul><li>kjdfkajdsfnla</li></ul><p><br></p><p>ljasdbfjads ajdhfpija sdifhapisd iasdpfj pOSDJF POIASJDF</p>`

after installing pdfmake and html-to-pdfmake, i import them into my component.ts

```
const pdfMake = require('node_modules/pdfmake/build/pdfmake')
const pdfFonts = require('node_modules/pdfmake/build/vfs_fonts')
pdfMake.vfs = pdfFonts.pdfMake.vfs
const htmlToPdfmake = require('html-to-pdfmake')
at some point I send to call the method where it is generated creates my pdf

savePDF() {
    console.log(this.reConsulta)

    const documentDefinition = {
      pageSize: 'A5',
      // by default we use portrait, you can change it to landscape if you wish
      pageOrientation: 'landscape',
      // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
      pageMargins: [5, 100, 5, 10],

      content: [
        { text: htmlToPdfmake(this.reConsulta.medicamentos) },
        { text: htmlToPdfmake(this.reConsulta.metodo), absolutePosition: { x: 320, y: 100 } },
      ],
    }

    pdfMake.createPdf(documentDefinition).open()
  }
```
at this moment `this.reConsulta.medicamentos` has the value of the previous list `<p><strong>DDDDD</strong></p><ol><li>jkdbkjdf</li><li>bjdbfkjadsf</li><li>kjdnfkadf</li></ol><ul><li>kjdfkajdsfnla</li></ul><p><br></p><p>ljasdbfjads ajdhfpija sdifhapisd iasdpfj pOSDJF POIASJDF</p>`

but cdo creates the pdf the list is not displayed, however other html tags like <b> </b> <i> </i> are formatted without problems.

![image](https://user-images.githubusercontent.com/14133027/124135259-43ce6680-da49-11eb-9790-a3de25f6fa56.png)

I tried other options until I noticed something peculiar. if I use this code directly.

```
let htmlMedicamentos = htmlToPdfmake('<ol><li>dd</li><li>d</li></ol>')
const documentDefinition={content:htmlMedicamentos}
pdfMake.createPdf(documentDefinition).open()
```

everything works wonders

![image](https://user-images.githubusercontent.com/14133027/124135435-6ceef700-da49-11eb-84d3-b57fa46592a9.png)

but if I try to format the document with pdfmake it is where what is expected does not happen.

`var htmlMedicamentos = htmlToPdfmake( '<ol><li>dd</li><li>d</li></ol>' );`

```
const documentDefinition = {
      pageSize: 'A5',
      // by default we use portrait, you can change it to landscape if you wish
      pageOrientation: 'landscape',
      // [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
      pageMargins: [20, 100, 20, 10],

      content: [
        {
          columns: [
            { width: '48%', text: htmlMedicamentos },
            { width: '45%', text: this.reConsulta.metodo, absolutePosition: { x: 320, y: 100 } },
          ],
          columnGap: 5,
        },
      ],
    }


    pdfMake.createPdf(documentDefinition).open()
```

**Comment by liborm85** [comment]
Not related with pdfmake.
html-to-pdfmake is not part of pdfmake.

**Comment by bisnukundu** [comment]
> 

Did you solve this problem? I am getting the same problem. If you solve this problem then please share it with me.
