### ISSUE TITLE
Version 0.2.0 released!

### ISSUE THREAD

**Issue by liborm85** [bpampuch/pdfmake#2282]
# Version 0.2.0 released!

## Changelog:
- Move to [@foliojs-fork](https://github.com/foliojs-fork) packages with up-to-date dependecies and security bug fixes and others. These are the libraries [@foliojs-fork/fontkit](https://github.com/foliojs-fork/fontkit), [@foliojs-fork/restructure](https://github.com/foliojs-fork/restructure), [@foliojs-fork/linebreak](https://github.com/foliojs-fork/linebreak) which are used in [@foliojs-fork/pdfkit](https://github.com/foliojs-fork/pdfkit).
- Upgrade Unicode Line Breaking Algorithm (UAX `#14`) to Unicode 12.0.0
- Introduced new `build-vfs.js` script to build virtual file system for fonts (see [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/)).
- Removed support Node.js 8 and 10. Minimum required version is 12 LTS.
- Removed support Internet Explorer 10. Supported only Internet Explorer 11.
- Removed gulp.

**Comment by sophistifunk** [comment]
What's the reason / difference with the `foliojs-fork` packages? I can't seem to find any details in their docs that say *why* they're forked? And is there a better place to ask this, like a gitter or some other chat room?

**Comment by liborm85** [comment]
I added "Why fork?" to packages readme with reasons and differences:
- https://github.com/foliojs-fork/pdfkit#why-fork
- https://github.com/foliojs-fork/fontkit#why-fork
- https://github.com/foliojs-fork/linebreak#why-fork
- https://github.com/foliojs-fork/restructure#why-fork

**Comment by naknode** [comment]
@liborm85 Grats. Are there any breaking changes from 0.1 to 0.2?

**Comment by mzl-md** [comment]
We had some errors with this release because we used .trie files from node_modules/fontkit and node_modules/linebreak, now you need to use those from node_modules/@foliojs-fork/fontkit and node_modules/@foliojs-fork/linebreak.

**Comment by VivienneB** [comment]
Hi! After upgrading from `v0.1.x` version to `v0.2.0` the next error appears when the `getBase64` is called:

```
[Error] Unhandled promise rejection
RangeError: Maximum call stack size exceeded. — index.bundle:229341
	error
	reactConsoleErrorHandler (index.bundle:22209)
	registerError (index.bundle:71704)
	errorImpl (index.bundle:71611)
	(anonymous function) (index.bundle:71588)
	n (index.bundle:39564)
	(anonymous function) (index.bundle:228996)
	dispatchEvent (index.bundle:233128:148)
	(anonymous function) (index.bundle:233142)
```

There are no useful logs to locate the source of error. From the logs shown in *Developer Tools - React Native* seems like it's an infinite recursive call, promise related (see below). The weird thing is, that the error doesn't crash the app and only appears at the first **getBase64** call. 

```
RangeError: Maximum call stack size exceeded.
call
call
(anonymous function) — index.bundle:227179
Promise — index.bundle:233189
safeThen — index.bundle:28127
call
(anonymous function) — index.bundle:233253
Promise — index.bundle:233195
then — index.bundle:233252
(anonymous function) — index.bundle:28129
Promise — index.bundle:233195
safeThen — index.bundle:28127
call
```

Also tried version `0.2.5` and with other functions like `getDataUrl` and `getBuffer` - same.
