### ISSUE TITLE
SVG images with elements having fill attribute do not work with PascalCased color names

### ISSUE THREAD

**Issue by akarshpandey217** [bpampuch/pdfmake#2286]
Encountered this issue while creating a PDF out of an SVG image. 
the fill attribute with PascalCased names will output a black element. whereas all lowercase colors and hexcodes work fine.
```
<svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="Red" />
</svg>
```
-- Shows a black circle
```
<svg height="100" width="100">
  <circle cx="50" cy="50" r="40" stroke="black" stroke-width="3" fill="red" />
</svg>
```
-- works just fine

**Comment by liborm85** [comment]
Pdfmake use for transformation from svg to pdf [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit) library. Create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).
