### ISSUE TITLE
Security vulnerability with crypto-js & path-parse

### ISSUE THREAD

**Issue by kthomas182** [bpampuch/pdfmake#2287]
Request to bump 3rd party dependencies:

- https://app.snyk.io/vuln/SNYK-JS-CRYPTOJS-548472
- https://app.snyk.io/vuln/SNYK-JS-PATHPARSE-1077067

**Comment by liborm85** [comment]
- crypto-js - upgrade is required in pdfkit, see: [foliojs/pdfkit#1273](https://github.com/foliojs/pdfkit/issues/1273)
- path-parse - pdfmake use latest version 1.0.7 and that is according to snyk safe version.

**Comment by liborm85** [comment]
pdfmake version 0.2.1 released with updated pdfkit version 0.12.3 containing cryptojs security fix.

**Comment by zdm** [comment]
`pdfkit` is the dead project and will not be updated.
It is possible to use fork: https://github.com/foliojs-fork/pdfkit.

**Comment by liborm85** [comment]
@zdm pdfmake is already using library fork https://github.com/foliojs-fork/pdfkit in 0.2.x version.
