### ISSUE TITLE
pdfmake with uigrid 

### ISSUE THREAD

**Issue by mathewbeno** [bpampuch/pdfmake#229]
The pdf export is not working in IE, and I am using Internet explorer version 11.

Appreciate any comments on this.

Thank you

**Comment by jthoenes** [comment]
Hi @mathewbeno - we know that pdfmake currently seems to have issues with IE. I don't have windows, so I don't even know how to reproduce it. But if somebody does, a pull request would be great.

Please look into the grouping issue for this: #16
