### ISSUE TITLE
Any ideas ?

### ISSUE THREAD

**Issue by cognition66** [bpampuch/pdfmake#2294]
Hi all

I have a Storyline 360 project with a Download button with following code in to launch the index file through a WebObject to launch a pdf file.

var iframeElements = document.getElementsByTagName("iframe");
iframeElements[0].contentWindow.generatePDF();

Issue I have is with the attached code....any ideas why it is not launching a pdf ?  Errors in Visual Studio Code show up for the Define Styles section at the end.

Any help gratefully received.

**Comment by cognition66** [comment]
[index.docx](https://github.com/bpampuch/pdfmake/files/6868853/index.docx)

**Comment by cognition66** [comment]
Script is in attached docx

**Comment by liborm85** [comment]
I have no idea.
