### ISSUE TITLE
ES Module import: Error: 'default' is not exported by printer.js

### ISSUE THREAD

**Issue by btakita** [bpampuch/pdfmake#2295]
```ts
import pdfmake from 'pdfmake'
```

results with an error `ES Module import: Error: 'default' is not exported by node_modules/pdfmake/src/printer.js`

The package that is importing `pdfmake` has `"type": "module"` in `package.json`, making the importing module an ESM.

**Comment by liborm85** [comment]
Please read [documentation](https://pdfmake.github.io/docs/0.1/getting-started/client-side/). Thanks.
