### ISSUE TITLE
Image exif orientation tag

### ISSUE THREAD

**Issue by tarrant17** [bpampuch/pdfmake#2297]
Hi everybody,

It seems that PdfMake is ignoring the exif metadata tag "orientation". I dont know if its a bug or a feature not implemented.

I tested with two image with the same width and height but with different "orientation" tag. One set to "Horizontal normal" and other with "90° CW". Both images are displayed the same way in the pdf.

Thanks for your reply and sorry for my english

**Comment by liborm85** [comment]
Attach example for reproduce issue.
