### ISSUE TITLE
Columns with margins: after page break, first column is aligned wrong

### ISSUE THREAD

**Issue by elinake** [bpampuch/pdfmake#2298]
I need to print multiple rows, two columns each row.  Rows must have a margin on the left.
```
{
	fontSize:10,
	margin: [20, 0, 0, 0],
		columns: [
			{
				text: 'first column'
			},
			{
				text: 'second column'
			},
		]
},
```
After page break the first row's second column is misaligned.

Code example: https://codepen.io/elinakeranen/pen/YzVaPeg

Pdfmake version: 0.2.0

**Comment by jkruuth** [comment]
What is the status on this issue? I am still facing this problem.

**Comment by jo-rooke** [comment]
I am also experiencing this problem, only when setting a page break with `pageBreak: "after"` in the node- using `pageBreakBefore` in the document definitions doesn't cause the problem. If others are having this bug, maybe try changing your logic to use the DD, but it doesn't help in my use case.
