### ISSUE TITLE
Indian rupee symbol displayed as square bullet symbol while using custom Arial Font

### ISSUE THREAD

**Issue by nehawawalkar** [bpampuch/pdfmake#2300]
I have added custom fonts to vfs_fonts.js and then assigned these fonts to my js as below
 pdfMake.fonts = {
          Roboto: {
            normal: 'Roboto-Regular.ttf',
            bold: 'Roboto-Medium.ttf',
            italics: 'Roboto-Italic.ttf',
            bolditalics: 'Roboto-MediumItalic.ttf'
          },
          Arial: {
                  normal: 'Arial.ttf',
                  bold: 'Arial-bold.ttf',
                  italics: 'Arial-italic.ttf',
                  bolditalics: 'Arial-bold-italics.ttf',
          },
Now, when I'm trying to print Invoice, Indian Rupee Symbol is displayed wrongly. I really don't know how to make it work using Arial font. It'll be a great help if someone suggest any solution.
Here's a screenshot of what's displayed currently
![rupeeSymbolIssue (1) (1)](https://user-images.githubusercontent.com/30154454/127447330-c51d1953-5e41-4941-9de7-29f5832e8062.png)

@bpampuch @liborm85 Could you please look into it and suggest what else I need to do to make it work.
Thanks In Advance!

**Comment by liborm85** [comment]
Probably your Arial font not support this character.

Tested on playground with Roboto font and works ok:
```js
var dd = {
	content: [
		'₹'
	]
}
``` 

![image](https://user-images.githubusercontent.com/1298652/127478522-69eb47fa-2ed6-486d-84c9-817f7a58e892.png)

**Comment by nehawawalkar** [comment]
Thanks for responding this early, found that out later that Arial does not support this symbol, trying to go for other alternatives. Thanks again. This is really a excellent library.
