### ISSUE TITLE
Playground crashes my browser

### ISSUE THREAD

**Issue by Shawnfoto** [bpampuch/pdfmake#2301]
I often write some demo code on playground, but once I have some error, playground will let my browser crash.
Can you add an exception handling function?

![Screen Shot 2021-07-29 at 4 34 21 PM](https://user-images.githubusercontent.com/18244561/127578596-138afa88-1a8c-4152-aea1-57b8770a11dc.png)

**Comment by liborm85** [comment]
If demo code is too big (meant difficult to perform) browser show dialog Page Unresponsive. This is standard feature of browsers, there is no way to solve it.
