### ISSUE TITLE
ES6 in v0.2.1

### ISSUE THREAD

**Issue by bytestream** [bpampuch/pdfmake#2302]
ES6 has been introduced in v0.2.1 [build/pdfmake.js](https://github.com/bpampuch/pdfmake/compare/0.2.0...0.2.1#diff-0eb2b75a9058702508c9647c645e94dbf8b0d058f99381096089bb183b822140R39070):
```js
stringify: function (wordArray, urlSafe=true) {
```

Supported browsers - https://pdfmake.github.io/docs/0.1/getting-started/client-side/supported-browsers/

Default argument values is only supported in ES2015 (not IE 11) - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters

**Comment by liborm85** [comment]
Thanks. Fixed by commit https://github.com/bpampuch/pdfmake/commit/f1513106d6dbe7f67c8d94b4c87d857b807a14e0.

Version 0.2.2 released.

**Comment by bytestream** [comment]
Thanks! Looks good :+1:
