### ISSUE TITLE
How to signify table rows thats are goes to next page?

### ISSUE THREAD

**Issue by davinder-ficode** [bpampuch/pdfmake#2303]
I have requirement to add indication text to bottom of table (...,continue) to indicate that part of table rows also goes to next page. How can i achieve that?
Requirement screenshot link: [ScreenShot](https://pasteboard.co/Ket7WQL.png)
Thanks

**Comment by liborm85** [comment]
Is not possible now.
Feature request: https://github.com/bpampuch/pdfmake/issues/620
