### ISSUE TITLE
How to build vfs with standard fonts in v0.2.2

### ISSUE THREAD

**Issue by blalan05** [bpampuch/pdfmake#2304]
Since gulp has been removed, the documentation seems like it hasn't been updated. <https://pdfmake.github.io/docs/0.1/fonts/standard-14-fonts/#use-in-pdfmake-on-client-side> 
The issue I'm having its that I get the PDF to build and preview as expected in vue-pdf, but trying to print, the font file seems to be missing and I can't figure out why. The only thing I changed was updating this library and building the new vfs as per the docs... I'm using Times New Romans which should be standard.

**Comment by liborm85** [comment]
Documentation fixed by commit: https://github.com/pdfmake/docs/commit/2434e178604ef85314cb533f7febd3c0e941520f
