### ISSUE TITLE
Text outside of page container

### ISSUE THREAD

**Issue by ethanova** [bpampuch/pdfmake#231]
Hello - for some reason some text, randomly, is getting pushed off the screen. You can see an example on page 9 here: https://parivedasolutions.box.com/s/e7tv5yc6crck6tu1f3czbla6dvixrtp0

The document definition object is here: https://parivedasolutions.box.com/s/naw4d2fabjxf9vronk1u646kxi58037j

I've tried adding a page margin which didn't work, and I've tried adding margins to the actual text but that doesn't work either. After each of those paragraphs though, I do include an empty text line after some of the paragraph sections and when given a large enough height margin on those empty lines, the paragraphs do sort themselves out. In this DD, there are some of these as an example (content[91]), but they didn't help in this case because it's different text than I am actually working with. 

Any ideas?

**Comment by bpampuch** [comment]
I can't access parivedasolutions without logging in, could you share the examples somewhere else?

**Comment by ethanova** [comment]
Sorry about that, could you try again? I believe I opened up the access to anyone with the link. Thank you!

**Comment by bpampuch** [comment]
OK, I'm able to download it now. We're talking about page 9, right?

**Comment by ethanova** [comment]
Yessir, page 9 is where it's going out of bounds with this text. With the text I'm actually working with, it does it in a couple places. I'm trying to step through the code now and see if it's not setting margin correctly. My uneducated line of thinking right now is that maybe splitWords may not be finding the right lineEnd or my text isn't letting it do so. Wondering if that's it because I saw maxWidth in buildInLines getting over 1k

**Comment by ethanova** [comment]
As extra info, we're using the Freesans typeface. Looking at the resulting pdfKitDoc that comes out, it looks like the lines are just not breaking in the right place. Any idea why it would do this or where to look for it doing this incorrectly?

**Comment by ethanova** [comment]
So the problem seems to be related to line.prototype.hasEnoughSpaceForInline... the maxWidth in this case is just a bad number, it's too high. So how is it getting set incorrectly high? Hmm...

**Comment by ethanova** [comment]
How would the writer context's available width be changed in between instantiating the writer and using it to create a new Line()??

**Comment by ethanova** [comment]
So I've discovered that the ElementWriter's available width somehow changes in between when it is instantiated and when it is used to create a new Line(). It's created with pageWidth (595) minus page margins (40x2=80) to be ~515. However, when the offending lines are created, the context().availableWidth is equal to ~588. Any ideas?

**Comment by liborm85** [comment]
Version 0.1.23 works well.
