### ISSUE TITLE
how to make downloadable pdf name dynamic ? e.g If I am in dashboard page, name should be dashboard view. if I am in report page, name should be report view and so on.

### ISSUE THREAD

**Issue by swadhinranjan** [bpampuch/pdfmake#2310]

**Comment by liborm85** [comment]
File name you can set as parameter in `download()` method. See [documentation](https://pdfmake.github.io/docs/0.1/getting-started/client-side/methods/).

**Comment by swadhinranjan** [comment]
Thanks for your quick reply.

yes , as per the documentation, download("myFileName.pdf") --- it will download pdf named as myFileName.pdf .

But here I am using a variable , download(myvarFileName.pdf) --- because file name can be any name what I am assigning before,  but here that name is getting "undefined" . Any solution?

**Comment by liborm85** [comment]
Solution through the variable must work, these are the basics of javascript. Attach example of your code.

**Comment by wolsk1** [comment]
I agree. I use variable-based naming and everything is working. If you attach the code to the issue it might be solved

**Comment by swadhinranjan** [comment]
Hi,
Thank you all.
variable-based naming was getting undefined before (inside function getting the name in console, but inside the block of pdfmake it was getting ''undefined''), but now through id (given in html), I am able to get the name dynamically.

**Comment by swadhinranjan** [comment]
Hi,
 pdf is taking around 7-8 sec to download the whole page, is there any way to reduce the time ?
TIA.

**Comment by liborm85** [comment]
Depends on the content of the page.
