### ISSUE TITLE
[AOT optimized issue] Second page onwards in default orientation ('Portrait')

### ISSUE THREAD

**Issue by wolsk1** [bpampuch/pdfmake#2311]
Good day! 
Last week I decided to use your package and everything went smoothly until I ran webpack optimizations against my code.
All pages of rendered document are in landscape and it contains a table of data, second page onwards page is set to portrait mode. After investigation I found that for some reason method `pageOrientation` in `getPageSize` is not setting orientation for next page.

Code from: https://github.com/bpampuch/pdfmake/blob/master/src/DocumentContext.js
```
function pageOrientation(pageOrientationString, currentPageOrientation) {
	if (pageOrientationString === undefined) {
		return currentPageOrientation;
	} else if (isString(pageOrientationString) && (pageOrientationString.toLowerCase() === 'landscape')) {
		return 'landscape';
	} else {
		return 'portrait';
	}
}
```
A deeper investigation showed that in webpack optimizations that we use this method is not available anymore.

Our optimization config
```
new TerserPlugin({
    terserOptions: {
        compress: {
            pure_getters: true,
            passes: 3
        }
    }
})
```
I found if we refactor `pageOrientation` from named function to function statement, then these optimizations picks up this function and functionality works as expected. I am making a PR for this solution, as soon as it is ready, I will attach it to this issue.
```
const pageOrientation = (pageOrientationString, currentPageOrientation) => {  //code }
```

PR for fix: #2312 

P.S. Cool library, but some docs and explanations are missing which makes it harder to use :)

**Comment by wolsk1** [comment]
@liborm85 What I need to do for this to be accepted?

**Comment by liborm85** [comment]
It looks more like a bug in terser plugin?

**Comment by wolsk1** [comment]
Well, once I do this refactor it is included in the optimized package. Do you have any other options for how to solve this?
We are using this package in our application, and I did this patch locally while trying to patch this issue at the package level if it is possible.

**Comment by liborm85** [comment]
Must be fixed in terser plugin.
