### ISSUE TITLE
the "widths: []" is not doing anything

### ISSUE THREAD

**Issue by codysmallmak** [bpampuch/pdfmake#2317]
same as title in this portion of the code the "widths" property isn't doing anything and the table widths are defaulting to auto.  
my best guess is that it is because the function "collectTableInArray" dynamically grabs a table fromt he web page and fromats it to work with pdf make, but I have no idea how to fix it if that is the issue. 
```
      style: "small",
        widths: [25, 70, 50, 200, 50],
        table: {
          body: [
            [
              { text: "QTY", fontSize: 12, bold: true, alignment: `center` },
              {
                text: "Description",
                fontSize: 12,
                bold: true,
                alignment: `center`,
              },
              {
                text: "Price",
                fontSize: 12,
                bold: true,
                alignment: `center`,
              },
              {
                text: "Discount",
                fontSize: 12,
                bold: true,
                alignment: `center`,
              },
              {
                text: "Total",
                fontSize: 12,
                bold: true,
                alignment: `center`,
              },
            ],
            ...collectTableInArray(),
          ],
        },
      },

```

**Comment by Sveagruva** [comment]
you need to put widths for table in table like that:

    style: "small",
    table: {
      widths: [25, 70, 50, 200, 50],
      body: [
        [
          { text: "QTY", fontSize: 12, bold: true, alignment: `center` },
          {
            text: "Description",
            fontSize: 12,
            bold: true,
            alignment: `center`,
          },
          {
            text: "Price",
            fontSize: 12,
            bold: true,
            alignment: `center`,
          },
          {
            text: "Discount",
            fontSize: 12,
            bold: true,
            alignment: `center`,
          },
          {
            text: "Total",
            fontSize: 12,
            bold: true,
            alignment: `center`,
          },
        ],
        ...collectTableInArray(),
      ],
    },
  },
