### ISSUE TITLE
I have some issues with khmer unicode missing some characters ? how to solve this solution ?

### ISSUE THREAD

**Issue by kaoben** [bpampuch/pdfmake#2319]

**Comment by liborm85** [comment]
Use font with support required characters.

**Comment by kaoben** [comment]
yes Does It support with font unicode for pdfmake?

**Comment by liborm85** [comment]
Yes, use custom font.

**Comment by kaoben** [comment]
I use custom font but it still not work

**Comment by kaoben** [comment]
can you give me example for that?

**Comment by liborm85** [comment]
see documentatio: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/
and use custom font with support required characters.

**Comment by huonsokly** [comment]
Please try with Hanuman font.

**Comment by Kokleng-Dev** [comment]
> Please try with Hanuman font.

Hello bong, with Hanuman font still not work.
<img width="529" alt="Image" src="https://github.com/user-attachments/assets/502835dc-f5bc-495e-b9f0-96810e856925" />

**Comment by huonsokly** [comment]
You may install this font on your server as well.
