### ISSUE TITLE
Not displaying date values from jqGrid properly

### ISSUE THREAD

**Issue by ConaxLiu** [bpampuch/pdfmake#2324]
I am very new to jqGrid and pdfmake, and I've googled about this for more than an hour but could not find any solution, so I'm logging an issue here.

I am testing pdfmake with a very simple jqGrid that contains a date column.
`    <script>

        var birthDay = new Date(1970, 0, 10);

        var dataArray = [
            { name: 'Bob', phone: '232-532-6268', birthday: '' },
            { name: 'Jeff', phone: '365-267-8325', birthday: birthDay }
        ];

        $("#grid").jqGrid({
            datatype: 'local',
            data: dataArray,
            colModel: [
                { name: 'name', label: 'Name' },
                { name: 'phone', label: 'Phone Number' },
                { name: 'birthday', formatter: 'date', formatoptions: { newformat: 'd/m/Y', defaultValue: null } }
            ]
        });

        function ExportToPDF() {
            $("#grid").jqGrid('exportToPdf', {
                title: 'PDF Export',
                orientation: 'portrait',
                pageSize: 'A4',
                description: '',
                customSettings: null,
                download: 'download',
                includeLabels: true,
                includeGroupHeader: true,
                includeFooter: true,
                fileName: "Test.pdf"
            });
        }

    </script>`

The data displays in the browser OK.

![jqGridTest](https://user-images.githubusercontent.com/38426847/131248245-5e732c3d-be4f-41e9-baf5-e09956430052.PNG)

However, when exported to PDF, the first row where the date should just be blank, shows up as &#160;, and the second row shows up as NaN/NaN/NaN.

[Test.pdf](https://github.com/bpampuch/pdfmake/files/7072340/Test.pdf)

Honestly I am not sure if this is a bug or is just I have not configured the grid or the export function properly. I wish someone can help, please?

Thank you.

**Comment by liborm85** [comment]
jqGrid is not related with pdfmake. Ask on jqGrid support.
