### ISSUE TITLE
How can pages in pdfmake be collated

### ISSUE THREAD

**Issue by ALaubscher** [bpampuch/pdfmake#2325]
I want to collate pages but I don't now where to start. I am unsure if this can be done. 

Lets say we have our pages:  1 - 2 - 3
How can I "duplicate" these to give me: 111 - 222 - 333

I have tried expanding the header to fit the entire page as you can get the node and the page number from that. But the content will be overflowing as the body of the document contains a table of unknown size.

On a side note: I told the person who will be making use of the pdf that they can just hit print button 3 times or set the collate option in the "printing" section but they rejected that idea.

**Comment by liborm85** [comment]
Pages cannot be duplicated, but you can define in docDefinition the same elements in multiple pages.

**Comment by Zamalekies** [comment]
@liborm85 What if the nodes are added to a static class from the pageBreakBefore function. These nodes can be added to a static object and then be manipulated as we know what the page numbers are in this function?

Example

- The static class

`export class Collate {

  public static nodes: Node[] = [];

  public static GetAllNodes(): Node[] {
    return Collate.nodes;
  }

  public static AddNode(node: Node) {
    Collate.nodes.push(node)
  }

  public static ClearNodes() {
    Collate.nodes = [];
  }
  
    public static DoSomethingWithTheNodes() {
   
  }
}
`

- And for our document
`    
    const pdfDocGenerator = pdfMake.createPdf(this.getDocDef());
    Collate.ClearNodes();

     pdfDocGenerator.getDataUrl((dataUrl) => {
     
      /* Collate the nodes over here and generate a new document */
      Collate.DoSomethingWithTheNodes()

    });`
    
    `  private getDocDef(): TDocumentDefinitions
  {
    return {
     //Rest of the doc over here
      pageBreakBefore: (currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) =>
      {
        Collate.AddNode(currentNode);
        return false;
      },
      `

**Comment by Zamalekies** [comment]
@liborm85 What if the nodes are added to a static class from the pageBreakBefore function. These nodes can be added to a static object and then be manipulated as we know what the page numbers are in this function?

Example

- The static class

```export class Collate {

  public static nodes: Node[] = [];

  public static GetAllNodes(): Node[] {
    return Collate.nodes;
  }

  public static AddNode(node: Node) {
    Collate.nodes.push(node)
  }

  public static ClearNodes() {
    Collate.nodes = [];
  }
  
    public static DoSomethingWithTheNodes() {
   
  }
}
```

- And for our document
``` 
    const pdfDocGenerator = pdfMake.createPdf(this.getDocDef());
    Collate.ClearNodes();

     pdfDocGenerator.getDataUrl((dataUrl) => {
     
      /* Collate the nodes over here and generate a new document */
      Collate.DoSomethingWithTheNodes()

    });
    ```
 ```   
  private getDocDef(): TDocumentDefinitions
  {
    return {
     //Rest of the doc over here
      pageBreakBefore: (currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) =>
      {
        Collate.AddNode(currentNode);
        return false;
      },
   ```
