### ISSUE TITLE
Absolute position not working beyond first page

### ISSUE THREAD

**Issue by LucGranato** [bpampuch/pdfmake#2327]
Hello there,

I would like to place something at a specific position on the second page but it seems to not handle correctly the `y` param from the `absolutePosition` for the element place outside the first page.

The example is very basic:

```javascript
var dd = {
  pageSize: {
    width: 500,
    height: 400
  },
  pageMargins: [0, 0, 0, 0],
  content: [
    {
      text: 'PAGE 1',
      absolutePosition: {
        x: 200,
        y: 200
      }
    },
    {
      text: 'PAGE 2',
      absolutePosition: {
        x: 200,
        y: 600
      }
    }
  ]
}
```

Even increasing the `y` value for the text "PAGE 2", the text stays on the top of the second page.

Can anyone help me, please?

Thank you very much.

**Comment by Zamalekies** [comment]
`    {
      text: 'PAGE 1',
      absolutePosition: {
        x: 200,
        y: 200
      }
    },
    {
        text: '',
        pageBreak: 'before'
    },
    {
      text: 'PAGE 2',
      absolutePosition: {
        x: 200,
        y: 200
      }
    }`
    
 Why not just add a page break and set the position the same? I am relatively sure that in the example you provided the text should not overflow to the next page. I think this needs to be logged as a bug.
