### ISSUE TITLE
Small squares appear when using custom fonts      

### ISSUE THREAD

**Issue by lang1427** [bpampuch/pdfmake#2329]
When I use a custom font, it is used to support Chinese, but the English content of the generated pdf will appear inexplicable if there are spaces in the English content □
![image](https://user-images.githubusercontent.com/46393473/132439410-69937db2-3398-4864-88e0-5fb553edea4d.png)

Doesn’t appear when I use the default font □

I don’t know if it’s because of custom fonts or how to solve it. Please help me to see this problem, thanks!

` 
  
        var docDefinition = {
          content: [],
         defaultStyle: {
            font: 'simhei'
        }
     };

        docDefinition.content.push("蓝芯检测引擎: Win.Worm.Brontok-88\n复合文档检测引擎: \n启发式检测引擎: \n压缩包检测引擎: \n脚本检测引擎: 无\n可执行文件\n可执行文件检测引擎: PE32 EXE\n壳检测引擎: UPX\n数字签名检测引擎: 无签名\n文件资源检测引擎: 有资源\n编译器检测引擎: \n导入表检测引擎\nKERNEL32.DLL.LoadLibraryA\nKERNEL32.DLL.GetProcAddress\nKERNEL32.DLL.ExitProcess\n输出表检测引擎\n字符串检测引擎\n!This program cannot be run in DOS mode.\nRich\n.rsrc\ndvvehzv\n1.25\nVXV^Y\nVHVF\nWU)EaS\nUZY3\nFVNE\n5xVB ! \n;QcU\nZ0K0\nA<J?\n8]U<9A$\n{&D'I\n' aJ\nCQ](\nZysad\nVBQL\nBD\"G\n*quuv\nGpsjF6\nfNzG\nGpE*\n[+6F\n;-?...")

        pdfMake.fonts = {
            simhei: {
                normal: 'simhei.ttf',
            }
        };

        pdfMake.createPdf(docDefinition).download();
`

 custom font
[vfs_fonts.js](https://raw.githubusercontent.com/lang1427/lang1427.github.io/main/vfs_fonts.js)

**Comment by liborm85** [comment]
Is required custom font which support both characters
