### ISSUE TITLE
Can we print to PDF in loop using pdfmake

### ISSUE THREAD

**Issue by prabhu-nishant** [bpampuch/pdfmake#233]
Hi ,

I have a scenario where in I need to create the doc definition inside loop . The problem is once the doc definition is created there is no way you can append it. How can this be achieved ? Every time I loop I am getting a json object which needs to be added to the PDF file. 

Regards,
Nishant

**Comment by prabhu-nishant** [comment]
Please find the code snippet.

for (var i = 0; i < checkedValues.length; i++) {
			
			{{#questionList}}
			if((checkedValues[i]).localeCompare({{questionId}}) == 0 ){
				
				var docDefinition = {
					content: [
						{ 
							text: 'Problem statement', 
							style: 'header' 
						},
						'{{questionString}}',
						{
							text: 'Detailed description',
							style: 'header'
						},
						'{{detailedDescription}}',
						{
							text: 'Community',
							style: 'header'	
						},
						'{{community}}',
						{ 
							text: 'Category',
							style: 'header'	
						},
						'{{category}}',
						{ 
							text: 'Comments',
							style: 'header'	
						},
						{
							ol: [	
								{{#commentList}}
									'{{commentString}}',
								{{/commentList}}
							]
						}
					],
					styles: {
						header: {
							fontSize: 12,
							bold: true
						}
					}
				}
			}
			{{/questionList}}
		}
		pdfMake.createPdf(docDefinition).download();

**Comment by jthoenes** [comment]
Why don't you just add to the content afterwards?

**Comment by prabhu-nishant** [comment]
I have an if condition which needs to hold true before I add it to the content . I cannot have the condition executed in between the content.

Von meinem iPhone gesendet

**Comment by Wabbala** [comment]
Uhm, why don't you create a ``content = []`` and push your content everytime your condition is true ... 
(note: use strict comparisons `===` instead of `==`)
```javascript
if (true) {
content.push({text: "hello world"});
}
```
Then you end-up something like:
```javascript
content = [{text: "hello world"},{"more text"}];
```
Then finally you can add content to docDefinition like:
```javascript
var docDefinition = {
                    content: content,
                    styles: {
                        header: {
                            fontSize: 12,
                            bold: true
                        }
                    }
                }
pdfMake.createPdf(docDefinition).download();
```

**Comment by Allansantosdefreitas** [comment]
@Wabbala WOW!! **IT WORKS!**
