### ISSUE TITLE
Repeat Header on each page

### ISSUE THREAD

**Issue by johnwick1986** [bpampuch/pdfmake#2330]
Hello. I just discovered this library and I would like to print out 2 div's and repeat the content of one as the header in all pages. The code is really simple, as you can see below:

` <div id="RoadmapHeader" style={{ height: "100px", width:"2000px", backgroundColor: "green"}}>
       
      </div>

      <div id="RoadmapBody" style={{height: "3000px", width:"2000px", backgroundColor: "blue" }}> 

      </div>`

In this case I want to print out the entire content, but I would like that the div with the id "RoadmapHeader" would appear on the beginning of each page. 

If someone could help I would really appreciate it

**Comment by liborm85** [comment]
pdfmake is not support html, use json format. For headers/footers see [documenatation](https://pdfmake.github.io/docs/0.1/document-definition-object/headers-footers/).
