### ISSUE TITLE
import in webpack/babel build fails

### ISSUE THREAD

**Issue by ftes** [bpampuch/pdfmake#2337]
In my rails app (@rails/webpacker 5, webpack@4) I cannot

```js
import pdfMake from "pdfmake/build/pdfmake"
// or
import * as pdfMake from "pdfmake/build/pdfmake"
```

In both cases, `pdfMake.createPdf` is not defined.

What works:

```js
import "pdfmake/build/pdfmake
```

`pdfMake` is then registered as a global variable.
It seems that the built module (`pdfmake/build/pdfmake.js`) is not correct, at least for my setup.

**Comment by liborm85** [comment]
```import "pdfmake/build/pdfmake``` is standard import described in [documentation](https://pdfmake.github.io/docs/0.1/getting-started/client-side/).

**Comment by ftes** [comment]
I see the documentation mentioning something different:

![Screenshot 2021-09-30 at 18 05 53](https://user-images.githubusercontent.com/2614732/135491357-e42c4e44-ed71-4f5f-bd73-84064f7237a6.png)

It suggests named imports.

**Comment by liborm85** [comment]
Use the variant that works in your case/framework.
