### ISSUE TITLE
Cannot find module 'has-tostringtag/shams'

### ISSUE THREAD

**Issue by 1nstinct** [bpampuch/pdfmake#2339]
Dependencies for the latest release 0.2.2 are not on their places.
![image](https://user-images.githubusercontent.com/1754655/135354527-4d02251b-7c91-4446-9158-40485ad316de.png)

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.

**Comment by 1nstinct** [comment]
Removing package-lock.json
Removing node_modules
npm i
Did the trick
