### ISSUE TITLE
Withdrawn: Arbitrary Code Execution in static-eval

### ISSUE THREAD

**Issue by Vinod-Telang1** [bpampuch/pdfmake#2342]
pdfmake module having vulnerabilities with following error
Withdrawn: Arbitrary Code Execution in static-eval

<img width="394" alt="pdf-make" src="https://user-images.githubusercontent.com/91894179/135861810-29983117-7b6d-4792-90fb-472bbf43cef5.png">

Team, can you please provide the solution for this?

**Comment by liborm85** [comment]
Version of pdfmake is?

**Comment by Vinod-Telang1** [comment]
@liborm85 
its occurring for all from 0.1.70 to latest one 0.2.2

**Comment by liborm85** [comment]
Vulnerability is only in version 0.1.x.
Version 0.2.x does not contain any vulnerability. Package svg-to-pdfkit install own pdfkit library, but this library is not used by svg-to-pdfkit or pdfmake.

**Comment by AxelRothe** [comment]
The maintainers need to escalate this to svg-to-pdfkit as one of their dependents. If a package is installed but not used it should be removed by the dependencies maintainers.

**Comment by liborm85** [comment]
You can create issue [here](https://github.com/alafr/SVG-to-PDFKit/issues).

**Comment by liborm85** [comment]
svg-to-pdfkit is in version pdfmake 0.2.3 build-in (without pdfkit dependency) https://github.com/bpampuch/pdfmake/commit/ce50aeb512dda94652711e2dffb2fd568aed60e1.
