### ISSUE TITLE
Two PDFs created with the same content and infos are never equal

### ISSUE THREAD

**Issue by peterberweiler** [bpampuch/pdfmake#2346]
# Problem
Two PDFs created with the same content and infos are never equal. This can be undesired if you want to compare PDFs by hashing them.

# Example
Here is an example doccument definition:
```js
var dd = {
	info: {
		creationDate: new Date("2000-01-01T00:00:00.000Z")
	},
	content: ['Test']
}
```
If you generate two PDFs with this they always differ in this line
```
...
/ID [<2fa220dbc6bd46e5b8fec2eaf5119503> <2fa220dbc6bd46e5b8fec2eaf5119503>]
...
```
# Cause
This happens because pdfmake sets the infos after pdfkit already generated this ID.

So pdfkit always uses the default info and the ID is never the same because of the creation date:
```js
// pdfkit default info
this.info = { Producer: 'PDFKit', Creator: 'PDFKit', CreationDate: new Date() };
```

# Solution
This is easily fixable by passing the infos to PDFDocument as options instead of setting them manually.

**Comment by liborm85** [comment]
New version released.
