### ISSUE TITLE
Tiling pattern support

### ISSUE THREAD

**Issue by jlogar** [bpampuch/pdfmake#2348]
I've implemented the tiling pattern support for pdfkit (foliojs/pdfkit#526). The PR foliojs/pdfkit#1311 is awaiting review/merge.

I'm currently developing support for that on our fork pdfmake (using the forked pdfkit). **If** the mentioned PR gets merged I would also like to add support for patterns to pdfmake.

Patterns need to be defined as resources in PDF so a `patterns` field would need to be added to the document definition. Something along the lines of:
```
var docDefinition = {
// ..
content: [
  // ..
],
patterns: {
  stripe45d: {
    boundingBox: [1, 1, 4, 4],
    xStep: 3,
    yStep: 3,
    pattern: '1 w 0 1 m 4 5 l s 2 0 m 5 3 l s'
  }
}};
```

I was wondering how I should go about implementing pattern usage in the content though. Looking at gradients implementation ([in 0.2 branch](https://github.com/bpampuch/pdfmake/blob/7f5412468e532226671483d62a2b4cc06b65f97c/src/printer.js#L561)) i see that a separate `linearGradient` field has been added. I was considering adding a `pattern` field (let's say for text and table cells/layouts). But I have second thoughts on that. The `pattern` and `fillColor` for table cells are more or less mutually exclusive. And pdfkit itself (and PDF spec itself) more or less treats patterns as just another color. So I am more inclined to just make the `color`/`fillColor`/`background` field accept a pattern tuple.
So that is:
```
{text: 'Some ipsum', pattern: ['stripe45d', 'yellow']}
```
vs.:
```
{text: 'Some ipsum', background: ['stripe45d', 'yellow']}
```

I would like to hear your thoughts on that. And whether such a PR would be needed/accepted.

**Comment by liborm85** [comment]
PR is welcome.

**Comment by jlogar** [comment]
Thanks for the merge!

Anything I can do to get this into master too?

**Comment by liborm85** [comment]
Ported to master by commit https://github.com/bpampuch/pdfmake/commit/1a0611481ef1299f989bf46628edb033cd9dfbc3.

**Comment by liborm85** [comment]
New version released.

**Comment by liborm85** [comment]
@jlogar Would be good add to documentation  https://github.com/pdfmake/docs
