### ISSUE TITLE
installing from git does not work

### ISSUE THREAD

**Issue by adamwong246** [bpampuch/pdfmake#2349]
As I understand it, you ought to be able to install an npm package from a git ref  in your package.json dependencies a la `"pdfmake": "bpampuch/pdfmake#master",`

We found that this method fails when we attempted to install our own fork into our project with `"pdfmake": "ChromaPDX/pdfmake#hardmodeTables",`

The error message
`Uncaught TypeError: Cannot read properties of undefined (reading 'vfs')`

The code 
```
import * as pdfMake from 'pdfmake/build/pdfmake.js';
import * as pdfFonts from 'pdfmake/build/vfs_fonts.js';
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

**Comment by liborm85** [comment]
The installation from github  of course works normally. Master branch is unstable branch for next 0.3 version with some BC, not intended for production. This version works with fonts differently, so it doesn't work for you.

**Comment by adamwong246** [comment]
My bad for assuming the master branch to be stable/up-to-date. Since we are forking this repo and have already submitted a PR, should we continue our work on the master branch, or re-base that work on an older release? Whats the ETA on v0.3?
