### ISSUE TITLE
Table inside a Table does not align to the right side of the parent table

### ISSUE THREAD

**Issue by Sun3** [bpampuch/pdfmake#2350]
Table inside a Table does not align to the right side of the parent table. The main objective it to be able to add additional tables to the main layout.

Sample code:
```
var tableLeft = {
	style: 'tableExample',
	widths: ['*', '*'],
	table: {
		headerRows: 1,
		body: [
			[{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}],
			['Left value 1', 'Sample value 2'],
			['Left value 1', 'Sample value 2'],
			['Left value 1', 'Sample value 2'],
			['Left value 1', 'Sample value 2'],
			['Left value 1', 'Sample value 2'],
		]
	},
}

var tableRight = {
	style: 'tableExample',
	widths: ['*', '*'],
	alignment: 'left',
	table: {
		headerRows: 1,
		body: [
			[{text: 'Header 1', style: 'tableHeader'}, {text: 'Header 2', style: 'tableHeader'}],
			['Right value 1', {text:'100,000,000,000'}],
			['Right value 1', {text:'25,000'}],
			['Right value 1', 'Sample value 2'],
			['Right value 1', 'Sample value 2'],
			['Right value 1', 'Sample value 2'],
		]
	},
}

var dd = {
  content: [
      {
      table: {
        headerRows: 1,
        widths: [ '*', 'auto', '*' ],
        body: [
          [tableLeft, '', { alignment: 'right', stack: [tableRight, 'Hello is on right']}],
        ],
      }
    },
  ]
};
```

Result is:

![table-wrong-result](https://user-images.githubusercontent.com/4562374/137567427-49b27e4a-a361-4b7a-8afa-6dc494c42f2d.png)

Correct result should be:

![table-right-result](https://user-images.githubusercontent.com/4562374/137567428-72a96616-cbfd-4149-b413-b1641d8f189c.png)

Any ideas on how to make this work is greatly appreciated.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/72

**Comment by Sun3** [comment]
I looked at that ticket before opening this one, but I do not see how it applies here. If you can show me what changes to make I would greatly appreciate it. 

Please remember that my sample has tables with only two columns, but they could have one or three in the subsequent tables.

In the body, more tables will be added
```
body: [
          [tableLeft, '', tableRight],
          [tableLeft2, '', tableRight2],
          [tableLeft3, '', tableRight3],
          // ... more
        ],
```

Thank you.
