### ISSUE TITLE
How does pfmake work in the table when there are multiple elements in the same column(Images, QR code, text) when data comes dynamically from backend? Also the column name should be translatable i18n Below is the ref image

### ISSUE THREAD

**Issue by akhil709** [bpampuch/pdfmake#2351]
![image](https://user-images.githubusercontent.com/73927905/137851372-0546b668-2368-4681-90b7-bc2581740fe4.png)

There is also some icon listed horizontally next to each row,

The solution of How does pdfmake work with dynamic data? #24 worked for ne give by @bpampuch But just that images and QR and text should be in same column also the column name table(externalDataRetrievedFromServer, ['name', 'age']) here in example name and age it should translated text, cant i add the object [{text: 'getTraslated text, style: 'Own style'] ?

**Comment by liborm85** [comment]
> How does pfmake work in the table when there are multiple elements in the same column(Images, QR code, text) when data comes dynamically from backend?

It depends on how you define it in docDefinition. Attach example docDefinition with your problem. Or see examples on [playground](http://pdfmake.org/playground.html).

> Also the column name should be translatable i18n Below is the ref image

You can pass text in what language you need.

> The solution of How does pdfmake work with dynamic data?

It's javascript and docDefinition is JSON. You can build it as you need it.
