### ISSUE TITLE
QR Code does not display with a text in column 

### ISSUE THREAD

**Issue by cmouze** [bpampuch/pdfmake#2356]
I would like to display QR Code with text above in columns then I define doc like this:
```
{
      alignment: 'center',
			columns: [
				{
					width: '50%',
					qr: 'https://www.test.frDSKFKDFGHOISHI',
          text: 'A000001',
          fit: 75,
          margins: [0, 0, 0, 8]
				},
				{
					width: '50%',
          fit: 75,
					qr: 'https://www.test.fr/VJVKFUYTDFRRYD',
          margins: [0, 0, 0, 8]
				}
			]
		},
...
```
with this the qr Code does not appear. What is wrong ?

**Comment by liborm85** [comment]
Your definition is wrong. Node text with QR doesn't exists. Exists only node text and node QR. Use this definition:
		{
      alignment: 'center',
			columns: [
			    {
			        stack: [
			     				{
					width: '50%',
          text: 'A000001',
          margins: [0, 0, 0, 8]
				},
								{
					width: '50%',
					qr: 'https://www.test.frDSKFKDFGHOISHI',
          fit: 75,
          margins: [0, 0, 0, 8]
				}
			        ]
			    },
				{
					width: '50%',
          fit: 75,
					qr: 'https://www.test.fr/VJVKFUYTDFRRYD',
          margins: [0, 0, 0, 8]
				}
			]
		},

**Comment by cmouze** [comment]
great, it works !!!
![image](https://user-images.githubusercontent.com/4621822/139819836-04ab6f75-7ef2-4d91-84ac-e43ebdf90949.png)
