### ISSUE TITLE
Is there an image file size limit?

### ISSUE THREAD

**Issue by MiksLatvis** [bpampuch/pdfmake#236]
I'm testing full size background images for A4 size prints, and resulting pdf only contains text. Images I used where 3500px by 2500px, jpg file size around 1.5 MB.

After that I tried using smaller images and they worked. What is the limit for base64 files? Is there another way I could use full sized images?

**Comment by jthoenes** [comment]
Hm, there is no limit imposed by pdfmake. But I can imagine that a image cannot be displayed when it is to big for the page. Have you considered using the ``fit`` attribute? Does it change something?

**Comment by MiksLatvis** [comment]
Thank you very much! It didn't occur to me that I need to use fit attribute, because I just used standard 300dpi pixel size for A4. I'm now using fit: [595, 842] which seems to fill the page perfectly.

**Comment by MiksLatvis** [comment]
Thank you very much! It didn't occur to me that I need to use fit attribute, because I just used standard 300dpi pixel size for A4. I'm now using fit: [595, 842] which seems to fill the page perfectly.

**Comment by robbannn** [comment]
Hi! I'm trying to fit images on a page using `fit` and I have also tried setting `width` and `height` properties. Works great for image sizes under 1MB. A new tab is opened but its left blank. What can be the issue here?

**Comment by sorb999** [comment]
hi @robbannn  can you please post your code so I will get more idea about the issue.

**Comment by Chris--A** [comment]
@robbannn try downloading the PDF instead of opening it.

I think you'll find the data URL produced for the PDF is too large for the browser. The latest version of Chrome only supports 2MB and FireFox is presumably lower (1MB).

**Comment by sorb999** [comment]
Hi @robbannn as @Chris--A said if the issue is with pdf size then you can download different version of pdfmake that will help you to generate a url something like this "blob:48b9b320-a204-11e6-8521-8ca2dcaf83ce" and it will not pass your entire binary data to new window.
