### ISSUE TITLE
how to stretch table height to fill remaining space on page

### ISSUE THREAD

**Issue by nehawawalkar** [bpampuch/pdfmake#2360]
The `pdfmake` module internally maintains a variable which contains all the meta-data such as total page height, current horizontal/vertical position and so on. We are able to achieve this functionality by using that variable.

Following is the code that calculates the padding for the last element using the currentPosition and totalPageHeight which will be equal to the height of the rest of the page.

Set the below created layout to the table.

```
const TABLE_LAYOUT: CustomTableLayout = {
    paddingBottom: (rowIndex: number, node: any, colIndex: number) => {
        const DEFAULT_PADDING = 2;

        // Calculate padding for the last element of the table.
        if (rowIndex === node.table.body.length - 1) {
            const currentPosition = node.positions[node.positions.length - 1];
            const totalPageHeight = currentPosition.pageInnerHeight;
            const currentHeight = currentPosition.top;
            const paddingBottom = totalPageHeight - currentHeight;
            return paddingBottom;
        } else {
            return DEFAULT_PADDING;
        }
    },
};
```

FYI, @Wyzix33

_Originally posted by @LogeswaranAnandan in https://github.com/bpampuch/pdfmake/issues/1427#issuecomment-814211639_

**Comment by nehawawalkar** [comment]
@LogeswaranAnandan I assume the solution you posted works if the calculated remaining height is directly applied to the last element. what if we assign this calculated height to an inner element whos position is already been assigned in positions array? 
 
 Thanks.

**Comment by Wyzix33** [comment]
Thank you so much !  It's exactly what i needed! Works like a charm

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1427
