### ISSUE TITLE
Table of contents - Skip first few pages

### ISSUE THREAD

**Issue by syedabdhalim** [bpampuch/pdfmake#2363]
Hi, I just wondering if there any way we can offset page number in table of contents?

For example
`var dd = {
  content: [
    {
      toc: {
        title: {text: 'INDEX', style: 'header'}
      }
    },
    {
      text: 'This is a header',
      style: 'header',
      tocItem: true,
      pageBreak: 'before'
    }
  ]
}`

Will give this result.
![image](https://user-images.githubusercontent.com/30526309/141247357-949607bd-01ea-4d4d-9ad5-9e7674a18ec1.png)

If there any way, instead of page number 2, i want to make the page number become 1?

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1270
