### ISSUE TITLE
Exceptions continually printed on the console after calling the "download" method

### ISSUE THREAD

**Issue by Asghwor** [bpampuch/pdfmake#2364]
When executing the following code:

```js
pdfMake.createPdf(documentDefinition).download()
```

exceptions start to be printed continually on the console, even though it does indeed download. It's usually a variation of the message below:

![image](https://user-images.githubusercontent.com/30949004/141337197-e1c929cc-8d53-43b6-9fab-e5742ccb21f1.png)

I'm using Angular 7.2.16 and Node 12.16.0.

I tried using versions 0.2.4 and 0.2.2 with no success.

**Comment by liborm85** [comment]
Create runnable example for reproduce issue, eg. on https://jsfiddle.net/ or other.

**Comment by Asghwor** [comment]
I apologize, but I haven't been able to have either JSFiddle or Stackblitz install the version of Angular I'm currently using.

Is there anything else I can provide?

**Comment by liborm85** [comment]
Error is on line 37356, where is:
![image](https://user-images.githubusercontent.com/1298652/141646388-140fbf28-6832-4ae7-a4e1-9d2940338941.png)

`arguments` is standard javascript variable. I don't know why is throw error here in Angular.

You can create simple runnable example in github repo.

**Comment by Asghwor** [comment]
Pardon for the delay, but I wasn't able to reproduce the error on a new project.

I'm honestly puzzled by this error.

**Comment by liborm85** [comment]
Non-reproducible.

**Comment by Asghwor** [comment]
Update on the issue: I found out the problem was caused by a mismatch between the Webpack versions of the project (4.x) and PDFMake's (5.x).

Downgrading PDFMake to version **0.1.72** fixed the problem.
