### ISSUE TITLE
[Question] Planned release data for 0.3.x (async version) of the lib?

### ISSUE THREAD

**Issue by jloleysens** [bpampuch/pdfmake#2367]
Hello!

Hopefully this is the correct way to ask about 0.3.x.

We use this library on a NodeJS server that is responsible for serving requests and compiling PDF reports. We are currently using version `0.1.15` which generates a PDF synchronously as one chunk of work on the event loop, stalling the ability to handle requests or other work. It looks like 0.3.x contains changes that move this to happen asynchronously, yielding control back to other code. I tested this out with master and it looks like it provides the functionality we are after.

Would it be possible to get an idea of when 0.3.x is being released?

Cheers!

[UPDATE]

Or any other kind of work-around.

**Comment by liborm85** [comment]
Beta version of 0.3 is [available](https://github.com/bpampuch/pdfmake/issues/2375).
