### ISSUE TITLE
Exclude certain HTML-Elements by docDefinition styles

### ISSUE THREAD

**Issue by nku-bsw** [bpampuch/pdfmake#2372]
Hi i have only some questions. Im trying to achive that i can set `display: none` for a certain HTML-Element by it's class selectors. 
So i have an button wich looks like this:
`<button class="print-not">Button</button>`

How can i now make it not be shown in the generated PDF ?

`var docDefinition = {
  content: [
button.innerHTML...
 ],
styles: {
"print-not": {
"display": "none"
}
}
};`

**Comment by liborm85** [comment]
pdfmake does not support HTML.
If you don't want to display something in document, just don't put it in doc definition.
