### ISSUE TITLE
Duplicate element not appearing

### ISSUE THREAD

**Issue by focexop** [bpampuch/pdfmake#2374]
Hello, I have a problem with pdfmake. Basically I have a pdf that contains 4 elements: header, body, table and footer. They are stored in a variable.
When I compose the pdfContent as [head. body, table, footer] it's fine with all the elements rendering but if I build the pdfContent as [head, body, table, footer, head]  the second head does not render on the pdf.

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by focexop** [comment]
Here's the example to reproduce the behavior -> [Gist](https://gist.github.com/focexop/0df98a41126c37d96b70964a33ef0c0c)
In the rows variable there is generated content for the table, in the header variable there's the dynamic data for the header of the page.
When I compose the "dd" as [header object, table, table, another element] the first table is generated but the second one is empty.
The same happens if I

**Comment by liborm85** [comment]
Reusing objects is not allowed (issue https://github.com/bpampuch/pdfmake/issues/465).
Can be solved, for example, by using functions, see https://github.com/bpampuch/pdfmake/issues/847#issuecomment-277526384
