### ISSUE TITLE
line-height error thrown by pdfmake

### ISSUE THREAD

**Issue by qasimmehdi** [bpampuch/pdfmake#2378]
I am converting this html:
```html
<a href="https://en.wikipedia.org/wiki/Poison" title="Poison">
    <span
        style="
        font-size: 10.5pt;
        line-height: 107%;
        font-family: Arial, 'sans-serif';
        color: windowtext;
        background-image: initial;
        background-position: initial;
        background-size: initial;
        background-repeat: initial;
        background-attachment: initial;
        background-origin: initial;
        background-clip: initial;
        text-decoration-line: none;
        "
    >
        poisonous gases
    </span>
</a>
```

html-to-pdfmake returns this:
```js
{
    "text": "poisonous gases",
    "nodeName": "A",
    "color": "windowtext",
    "decoration": ["underline"],
    "fontSize": 10.5,
    "lineHeight": "107%", //causing error
    "backgroundImage": "initial",
    "backgroundPosition": "initial",
    "backgroundSize": "initial",
    "backgroundRepeat": "initial",
    "backgroundAttachment": "initial",
    "backgroundOrigin": "initial",
    "backgroundClip": "initial",
    "textDecorationLine": "none",
    "link": "https://en.wikipedia.org/wiki/Poison"
}
```

pdfmake throws error:
object.js:128 Uncaught (in promise) Error: unsupported number: NaN
    at number (object.js:128)
    at PDFDocument.rect (vector.js:111)
    at drawDecoration (textDecorator.js:123)
    at Object.drawDecorations (textDecorator.js:132)
    at renderLine (printer.js:526)
    at renderPages (printer.js:394)
    at PdfPrinter.createPdfKitDocument (printer.js:164)
    at pdfMake.js:86

If I remove `"lineHeight": "107%"` the error goes away.

**Question:**
What's the best way to fix this since the html is dynamic I can't check for every css property. If can I remove a specific css property from being parsed that would also be a good solution.

**Comment by liborm85** [comment]
Not related with pdfmake. html-to-pdfmake is not part of pdfmake.
