### ISSUE TITLE
2 columns dynamic layout

### ISSUE THREAD

**Issue by giulioprovasi** [bpampuch/pdfmake#238]
I need to generate a pdf with an automatic 2 columns layout, is this possible with pdfmake ? 

The text (or table in my case) should be able to overflow to second columng when the bottom of the page is reached and then go back to left column on page 2 etc.

**Comment by jthoenes** [comment]
Hi @kitensei, this is unfortunately not supported yet.

**Comment by kitensei** [comment]
is it planned for a next release or not yet ?

**Comment by jthoenes** [comment]
We have no plans yet. Happy to accept pull request, if you want to do it yourself. 

Let me know, when I can help you with that.

**Comment by pankgeorg** [comment]
Any news on that front?

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/604

**Comment by MussaCharles** [comment]
@giulioprovasi  Did you manage to solve this issue back then?
