### ISSUE TITLE
Want to set whole Table height  

### ISSUE THREAD

**Issue by nayan-moontech** [bpampuch/pdfmake#2380]
I want to set height of whole table not rows means like in html we can set height of table same that way i want to set height of table in pdfmake.

Also i want that my terms box will stay at bottom if pdf has only one page content, and have blank space between product table and terms & condition box. 

as right now product and terms bot stick together i only want them to stick if pdf have more than one page content. 

![image](https://user-images.githubusercontent.com/97596591/149115098-5b279ad4-bd14-437e-89aa-8cac995a4fb3.png)

**Comment by nikhil-jaunjal** [comment]
```
 content: [
                {
                    layout: 'lightHorizontalLines',
                    table: {
                        widths: ['30%', '70%'],
                        heights: 900,                                  <=// make sure that this number is more than your page size i.e. if 'A4' paper is used your height should be '>= 294'
                        body: [
                            [
                                {  
                                    stack: []                               <=//add your content here
                                },
                                { 
                                    stack: []                               <=//add your content here
                                }
                            ]
                        ]
                    }
                }
            ],
```

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1427
