### ISSUE TITLE
Digital signatures are not visible in pdf

### ISSUE THREAD

**Issue by HomsiHamude** [bpampuch/pdfmake#2389]
I need the pdf viewer to display the digital signatures present in the pdf.
I know there are some security concerns with displaying the e-signatures (the signatures can't be verified for authenticity, it may be a fraud).
The need is to just display the signatures, without validating them.

Is this possible to implement? Or is there a workaround until a more robust solution is available?

Thank you!

**Comment by liborm85** [comment]
pdfmake is not pdf viewer.
