### ISSUE TITLE
r.toLowerCase is not a function

### ISSUE THREAD

**Issue by afilp** [bpampuch/pdfmake#2390]
Hello,

This code used to work, but not now that I upgraded to the latest PDFMake (not sure if this is the reason though):

`pdfMake.createPdf(docDefinition).download('QR Codes.pdf')`

I get this in my console:

```Uncaught (in promise) TypeError: r.toLowerCase is not a function
    at URLBrowserResolver.js:60:1
```

It appears that a `url` is considered `undefined`

![image](https://user-images.githubusercontent.com/7850073/152721602-dd6501fe-cc02-4853-8b8e-0f4e1c2fb565.png)

But I do not need any url, before it was working without problems. I just want to create a PDF and download it from memory.

Thanks a lot!

**Comment by naknode** [comment]
I would also try to make your file string names friendly so no spaces

**Comment by afilp** [comment]
@liborm85 I was unable to create a runnable example fast, the code is very large.

However, I found this: https://discourse.nodered.org/t/solved-contrib-pdfmake-node-help-please-getting-node-to-work/30867

I am also in Windows 10, if this is related.

So, I downgraded to `    "pdfmake": "0.1.65",` (just before the `URLBrowserResolver` was introduced in v0.1.66) and it works with exactly the same code.

So, maybe you know better what causes this, as everything else is OK (docdefinition, etc.).

**Comment by liborm85** [comment]
> 
> However, I found this: https://discourse.nodered.org/t/solved-contrib-pdfmake-node-help-please-getting-node-to-work/30867

This issue is not related with your problem.


Without reproduce code cannot be your issue solved.

**Comment by LiquidMagical** [comment]
I've had the same Problem. The Problem was that i've attached a undefined String inside the images Object of the document definition.

`{
    "info": {
        "title": "Test",
        "author": "Test",
        "subject": "",
        "keywords": ""
    },
    "header": {},
    "footer": {},
    "content": {},
    "images": {
      "image01": "undefined"
    },
    "pageSize": "A4",
    "pageOrientation": "portrait",
    "version": "1.3",
    "compress": true,
    "pageMargins": 40
}`

**Comment by shubhendusaurabh** [comment]
I was getting same error due to my custom font urls being relative path i.e. not starting http protocol
