### ISSUE TITLE
pdfmake 0.2.4: issue with custom fonts using URL protocol

### ISSUE THREAD

**Issue by therealgilles** [bpampuch/pdfmake#2391]
I am trying to define custom fonts with the URL protocol as explained [here](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/). I am using dataTables so I am defining defaultStyle.font on the doc object of dataTables (which will be passed to docDefinition):

```JS
						pdfMake.fonts = {
							Roboto: {
								normal: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Regular.ttf',
								bold: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Medium.ttf',
								italics:
									'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Italic.ttf',
								bolditalics:
									'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-MediumItalic.ttf',
							},
						}
						doc.defaultStyle.font = 'Roboto'
```

I am including the following two scripts:
```JS
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/pdfmake.min.js
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/vfs_fonts.js
```

Yet I am getting this error at runtime:
```JS
uncaught exception: File 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Regular.ttf' not found in virtual file system
```

I am not sure why pdfmake is looking for the font files in the virtual file system. What am I doing wrong?

**Comment by therealgilles** [comment]
Does the playground use 0.2.4? By the way, the playground was working a few minutes ago and seems unresponsive right now.

**Comment by therealgilles** [comment]
Trying to run the playground locally, I get this error:
```
ReferenceError: pdfMake is not defined
```

**Comment by therealgilles** [comment]
If I locally change server.js as follows:
```JS
  var fontDescriptors = {
    /*Roboto: {
      normal: path.join(__dirname, '..', 'examples', '/fonts/Roboto-Regular.ttf'),
      bold: path.join(__dirname, '..', 'examples', '/fonts/Roboto-Medium.ttf'),
      italics: path.join(__dirname, '..', 'examples', '/fonts/Roboto-Italic.ttf'),
      bolditalics: path.join(__dirname, '..', 'examples', '/fonts/Roboto-MediumItalic.ttf')
    }*/
    Roboto: {
      normal: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Regular.ttf',
      bold: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Medium.ttf',
      italics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Italic.ttf',
      bolditalics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-MediumItalic.ttf',
    },
  };
```

I get the following error:
```
Error: ENOENT: no such file or directory, open 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.2.4/fonts/Roboto/Roboto-Regular.ttf'
```

Is that enough of an example to debug on your side?

**Comment by therealgilles** [comment]
I was able to run a change similar to the one above on 0.3.0-beta.1, but does not work on 0.2.4.

**Comment by liborm85** [comment]
See [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/): "This feature is available only in client-side (in browser)."

Support on server-side is added in version 0.3.0-beta.1.

**Comment by therealgilles** [comment]
@liborm85: I'm a bit confused as to why you close this issue. My test case is on the client side.
You told me it worked on the playground in 0.2.4 but I tried and it did not work. What's your rationale for closing this issue?
I understand I needs to give you a test case. Give me a bit of time and I will prepare one.

**Comment by therealgilles** [comment]
@liborm85: I understand.

It turns out my problem comes from trying to use getStream() synchronously. I missed the note on this [page](https://pdfmake.github.io/docs/0.1/getting-started/client-side/methods/):
```
Unable to download real font files from url (https:// or http://). Asynchronous call required.
```

It would be great if you also added the note on the documentation page [here](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/).

**Comment by therealgilles** [comment]
I am a bit confused as to how the call to getStream() is qualified as a 'Synchronous call' as it returns a promise. This is in the 0.2.* documentation.

**Comment by liborm85** [comment]
Version 0.2 does not know promises, using callbacks. Promises are added in version 0.3.
