### ISSUE TITLE
pdfmake takes too long to generate PDFs

### ISSUE THREAD

**Issue by Yeshwanth2411** [bpampuch/pdfmake#2394]
We are using pdfmake with NodeJS(Backend) to generate PDFs. We have templates for all the PDFs and on each request from the user the API will generate the corresponding PDF and send a response. The size of the PDFs varies based on the template and the request body. Now, for PDF of size 2.36MB pdfmake is taking 15.27 secs which is too long and sometime the request times out before the response is sent. Please help us to generate the PDFs faster so that it will resolve our issue.
![MicrosoftTeams-image (3)](https://user-images.githubusercontent.com/61352443/154422410-421750de-9481-454f-862b-091047157ebe.png)

**Comment by liborm85** [comment]
Time to generate depends on size and complexity of document. For larger documents is 15 sec good value.
