### ISSUE TITLE
Issue with .open() and .print() in mobile device.

### ISSUE THREAD

**Issue by Srk15** [bpampuch/pdfmake#2399]
<img width="488" alt="image" src="https://user-images.githubusercontent.com/41322670/155278129-a6d67215-3c30-4f94-a808-c51391d0576b.png">

While using pdfmake's print() or open() methods, facing an issue in chrome in mobile devices where instead of opening pdf in new tab, it just shows blank page as above, and automatically downloads pdf in background. 

For desktop it is working as expected(opening in new tab, and pdf is displayed correctly)

Kindly advise on this issue.

**Comment by liborm85** [comment]
Browsers in mobile devices mostly do not support opening blobs (documents) in new window.
