### ISSUE TITLE
Adding header and footer from from my html table

### ISSUE THREAD

**Issue by Shubham9t** [bpampuch/pdfmake#2401]
I have to create a PDF of more than 10 templates, every template consists of a different header, footer , HTML table.
I wrote HTML and CSS for templates I don't want to write for PDF, Already tried html2pdf but it did not repeat the header and footer and pdfmake want me to write code for every template .So please help what to do

**Comment by liborm85** [comment]
pdfmake is not html to pdf converter.

**Comment by Shubham9t** [comment]
yes i know just need some help to achieve this
