### ISSUE TITLE
_pdfmake.default is not a constructor

### ISSUE THREAD

**Issue by revathiVinoth** [bpampuch/pdfmake#2402]
i upgraded the pdfmake version from 1.x to 3.0 (beta version) and run my code and i am getting "_pdfmake.default is not a constructor"

**Comment by liborm85** [comment]
Add informations about your environment and attach runnable example for reproduce issue.

**Comment by vijaykerure** [comment]
@liborm85  Please find below example, through which we can reproduce the mentioned error:

This is simple typescript node backend project

`
import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import PdfPrinter from 'pdfmake';

import { TDocumentDefinitions, TFontDictionary } from 'pdfmake/interfaces';

const app = express();

const docDefinition: TDocumentDefinitions = {
  pageSize: 'A4',

  pageOrientation: 'portrait',

  pageMargins: [30, 30, 30, 30],

  content: [{ text: 'test' }],
};

const fonts: TFontDictionary = {
  Roboto: {
    normal: path.join(__dirname, '..', '/fonts', '/Roboto-Regular.ttf'),
    bold: path.join(__dirname, '..', '/fonts', '/Roboto-Medium.ttf'),
    italics: path.join(__dirname, '..', '/fonts', '/Roboto-Italic.ttf'),
    bolditalics: path.join(
      __dirname,
      '..',
      '/fonts',
      '/Roboto-MediumItalic.ttf'
    ),
  },
};

app.post('/', async (req: Request, res: Response) => {
  try {
    const pdfPrinter = new PdfPrinter(fonts);

    const pdfDoc = pdfPrinter.createPdfKitDocument(docDefinition);

    let writeStream = fs.createWriteStream('document.pdf');

    pdfDoc.pipe(writeStream);
    pdfDoc.end();

    // res.setHeader('Content-Type', 'application/pdf');
    // res.send({});
    res.send();
  } catch (error: any) {
    console.log(error);
    res.send(error.message);
  }
});

app.listen(3000, () => {
  console.log('Service is listing on PORT 3000.');
});

`

**Comment by vijaykerure** [comment]
@liborm85  Please find the runnable example: https://replit.com/join/afqvppgymq-vijaykerure

**Comment by marcschroeder** [comment]
For me setting
		"esModuleInterop": true
in my tsconfig solved this issue.

**Comment by SS-Runen** [comment]
> "esModuleInterop": true

It doesn't always work. I got an error on importing `import * as moment from 'moment-timezone';`

**Comment by marcschroeder** [comment]
> > "esModuleInterop": true
> 
> It doesn't always work. I got an error on importing `import * as moment from 'moment-timezone';`

You might be able to change the import to something like `import { XXXX } from 'moment-timezone';` and only import the methods you actually need - this depends how on how the package is structured.
