### ISSUE TITLE
On Downloading pdf, it is showing following ERROR Error: Uncaught (in promise): Error: Font 'Helvetica' in style 'normal' is not defined in the font section of the document definition.

### ISSUE THREAD

**Issue by srnsh07** [bpampuch/pdfmake#2403]
Showing error on download pdf in Angular but if resize the window then it's started downloading.
Please help me to resolve it ASAP
Thanks

ERROR Error: Uncaught (in promise): Error: Font 'Helvetica' in style 'normal' is not defined in the font section of the document definition.
Error: Font 'Helvetica' in style 'normal' is not defined in the font section of the document definition.
    at n.provideFont (270.de570c02152990d85ea6.js:1:1237625)
    at 270.de570c02152990d85ea6.js:1:1289522
    at Array.forEach (<anonymous>)
    at C (270.de570c02152990d85ea6.js:1:1288880)
    at g.buildInlines (270.de570c02152990d85ea6.js:1:1290143)
    at E.measureLeaf (270.de570c02152990d85ea6.js:1:1216311)
    at 270.de570c02152990d85ea6.js:1:1214345
    at l.auto (270.de570c02152990d85ea6.js:1:1275307)
    at E.measureNode (270.de570c02152990d85ea6.js:1:1213404)
    at E.measureVerticalContainer (270.de570c02152990d85ea6.js:1:1217252)
    at Ct (polyfills.fb2d774b9c433f15305f.js:1:43602)
    at polyfills.fb2d774b9c433f15305f.js:1:44510
    at nt.invokeTask (polyfills.fb2d774b9c433f15305f.js:1:34706)
    at Object.onInvokeTask (main.11400acb0d2e881b5b98.js:1:297865)
    at nt.invokeTask (polyfills.fb2d774b9c433f15305f.js:1:34626)
    at kt.runTask (polyfills.fb2d774b9c433f15305f.js:1:30003)
    at Rt (polyfills.fb2d774b9c433f15305f.js:1:36759)
    at tt.invokeTask [as invoke] (polyfills.fb2d774b9c433f15305f.js:1:35806)
    at vt (polyfills.fb2d774b9c433f15305f.js:1:48000)
    at XMLHttpRequest.Tt (polyfills.fb2d774b9c433f15305f.js:1:48354)

**Comment by liborm85** [comment]
You probably don't have a defined font Helvetica.

**Comment by srnsh07** [comment]
Ok, then what should i do?

My issue is not fixed yet.

**Comment by srnsh07** [comment]
Please help

![Screenshot 2022-03-16 at 1 57 10 PM](https://user-images.githubusercontent.com/85245137/158549114-0fd42202-6f2d-4d60-8708-5c838e34d3cb.png)

**Comment by liborm85** [comment]
I don't know exactly what and how you do. Attach runnable example for reproduce issue.

**Comment by srnsh07** [comment]
This is my code for angular

import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';
const htmlToPdfmake = require('html-to-pdfmake');
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;


@ViewChild('my_html_id')
  my_html_id!: ElementRef;


 downloadPdf(): void {
    const pdfTable = this.my_html_id.nativeElement;
    var html = htmlToPdfmake(pdfTable.innerHTML);
    const documentDefinition = { content: html,
    
  };
    pdfMake.createPdf(documentDefinition).download();

  }

**Comment by liborm85** [comment]
I don't see the font added anywhere in the example. See documentation how to add custom font: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/

**Comment by srnsh07** [comment]
Thanks @liborm85  for 
your quick response. I tried this but sometimes this problem is coming sometimes not.


downloadPdf(): void {
    // pdfFonts
    pdfMake.fonts = {
      Roboto: {
    normal: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf',
    bold: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf',
    italics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf',
    bolditalics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf'
  },
     
    }
    
    const pdfTable = this. my_html_id.nativeElement;
    var html = htmlToPdfmake(pdfTable.innerHTML);
    const documentDefinition = { content: html,
    defaultStyle: {
      font: 'Roboto'
    } 
  };
    pdfMake.createPdf(documentDefinition).download();

  }

![Screenshot 2022-03-16 at 1 57 10 PM](https://user-images.githubusercontent.com/85245137/158582826-43db9417-376b-4d94-bc0b-b860f25ec0fa.png)

**Comment by srnsh07** [comment]
Even I have no such need to add custom font, standard font is also fine for me.

**Comment by FelipeDaros** [comment]
Hello

generatePDF = () => {
        var promotoria = `PROMOTORIA: ${this.props.promotoria.Promotoria.zy7_codsol}`
        var data = `DATA: ${this.props.promotoria.Promotoria.zy7_dtiniv}`
        
        const docDefinition = {
            pageMargins: [10, 10, 10, 10],
            font: 'Averta-Black',
            content: [
                {
                    text: promotoria, // Center-aligned text
                    alignment: 'center', // Center alignment
                    fontSize: 20, // Set the desired font size
                    margin: [0, 0, 0, 20]
                },
                {
                    text: data, // Center-aligned text
                    alignment: 'center', // Center alignment
                    fontSize: 16, // Set the desired font size
                    margin: [0, 0, 0, 20]
                },
                { qr: promotoria, alignment: 'center', fit: 400, },
            ]
        }

        const pdfDoc = pdfMake.createPdf(docDefinition)

        return pdfDoc;
    }
