### ISSUE TITLE
Force the table to the next page

### ISSUE THREAD

**Issue by bcgov-brwang** [bpampuch/pdfmake#2405]
Hi,
We are running into an issue with pdfmake. The attached image shows that a row of a table we created was split into two parts on two different pages. Can the spacing between pages force the answers highlighted and the beginning of the title boxes to the next page?
Or are there any ways to avoid this issue? Thanks.

[image-2021-12-09-09-18-33-037.zip](https://github.com/bpampuch/pdfmake/files/8217008/image-2021-12-09-09-18-33-037.zip)

**Comment by liborm85** [comment]
You can use property `unbreakable`, see example: https://github.com/bpampuch/pdfmake/issues/2321#issuecomment-907222842
