### ISSUE TITLE
force new page (if content is going to span 2 pages)

### ISSUE THREAD

**Issue by pjebs** [bpampuch/pdfmake#2406]
Is it for possible for us to set that if some content will end up spanning between 2 pages, then force that text to start in a new page?

i.e. a predictive version of: https://github.com/bpampuch/pdfmake/issues/25#issuecomment-43151912

**Comment by liborm85** [comment]
You can use property `unbreakable`, see example: https://github.com/bpampuch/pdfmake/issues/2321#issuecomment-907222842
