### ISSUE TITLE
Issue with multiple simultaneous requests for createPDF

### ISSUE THREAD

**Issue by Srk15** [bpampuch/pdfmake#2411]
We are using pdfMake to generate pdfs in our project. However, we have observed that when multiple simultaneous requests(multiple pdfs being generated, simultaneously) occur for the "createPDF" method, some of them do not execute. Currently, we have found that the limit is 7 simultaneous requests that execute successfully. Has anyone else faced something similar?

Kindly help with this issue.

**Comment by liborm85** [comment]
pdfmake has no such restrictions. Maybe some problem in layer above it that calls pdfmake?

**Comment by Srk15** [comment]
Thanks for the confirmation @liborm85 . Must be some other issue then, as you suggested, with the layer calling pdfmake.

Thank you.
