### ISSUE TITLE
Table layout "noBorders" is not working

### ISSUE THREAD

**Issue by Lycoon** [bpampuch/pdfmake#2413]
### Issue
I'm using pdfmake for client-side rendering. I just can't make the noBorders standard layout to work, borders still appear.
I strictly followed [this guide](https://pdfmake.github.io/docs/0.1/document-definition-object/tables/) from the docs.

### Code
```ts
import { TDocumentDefinitions } from "pdfmake/interfaces";
import * as pdfMake from "pdfmake/build/pdfmake";

let pdfData: TDocumentDefinitions = {
  content: [
    {
      table: {
        layout: "noBorders",
        body: [
          [{ text: "sample text" }],
        ],
      },
    },
  ],
};

pdfMake.createPdf(pdfData).open();
 ```

### Versions
- pdfmake `^0.2.4`
- npm `8.1.2`
- node `16.13.1 `

**Comment by liborm85** [comment]
Property `layout` must be at `table` node level (no inside table node). Example:
```js
var dd = {
  content: [
    {
      layout: "noBorders",
      table: {
        body: [
          [{ text: "sample text" }],
        ],
      },
    },
  ],
};
```

**Comment by Lycoon** [comment]
It appears that I indeed did not _strictly_ followed the guide, now it works!

Thank you!
