### ISSUE TITLE
Units

### ISSUE THREAD

**Issue by pjebs** [bpampuch/pdfmake#2418]
The documentation says the page size units are in points.
What is the units for the margins? The margins docs doesn't say.

**Comment by liborm85** [comment]
Points.

**Comment by pjebs** [comment]
Where does it say?

**Comment by liborm85** [comment]
Documentation https://pdfmake.github.io/docs/0.1/document-definition-object/ say:
> All numbers are in points (pt) unit (sometimes labeled as PDF/PostScript points).
