### ISSUE TITLE
Pagebreak in a column should affect entire "row" 

### ISSUE THREAD

**Issue by orestis** [bpampuch/pdfmake#242]
Hello, thanks for this awesome library.

I have an issue where if I have something like (runnable in the playground):

    var dd = {
	content: [
		
		
		'a','a','a','a','a','a','a','a','a','a','a','a','a','a',
		'a','a','a','a','a','a','a','a','a','a','a','a','a','a',
		'a','a','a','a','a','a','a','a','a','a','a','a','a','a',
		'a','a','a','a','a','a','a','a','a','a', // push down the page
		{
		  columns: [
		  {
			image: 'sampleImage.jpg',
			width: 350
		   },
		   { text: "should follow image" }
		   ],
		   
		}
		
		
	   ],
	defaultStyle: {
	    columnGap: 20
	}
	
    }

The layout will (correctly) insert a page break before the image, but the text on the second column will ignore it and appear on the previous page. I've also tried with tables and it seems it's doing the same thing.

I would expect (or would like to specify) that if an auto page break in the column group should affect equally all columns, and push the text down with the image. Let me know if I can help on this in any way.

**Comment by orestis** [comment]
To make this a bit more generic, I'd like to specify an "unbreakable" block - that is, if the whole "block" can't fit in the space left, move it to the next page. Again, if you could point me to the code responsible for this, I could have a go at hacking something together.

**Comment by jthoenes** [comment]
Hi @orestis,

The easiest step would be to just add a ``pageBreak: before`` to the columns. 

If your application is more dynamic, have a look at the example for the ``pageBreakBefore`` function in #202 - this should do the job. 
It gives you more control as a user of pdfmake (but also more possibility to shoot you in the foot with it). 

Let me know if that works for you.

**Comment by orestis** [comment]
Just a clarification on my use case:

I have a stack of columns. There's an image on the left, some text info on the right. I'm relying on the automatic page breaks to ensure everything fits all right. All the content is dynamic therefore I cannot anticipate the height of the images when I create the document definition.

I'll have a look at the pageBreakBefore function, it seems promising but needs testing.

**Comment by orestis** [comment]
Thanks, this did exactly what I wanted. For future reference:

I made the content block I wanted to ensure isn't divided by a page break an explicit stack and gave all of them the same id, e.g. 'mediaRow'. Then the pageBreakBefore function looks like so:

     var  pageBreakBefore = function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
        return currentNode.id === 'mediaRow' && currentNode.pageNumbers.length > 1;
    };

**Comment by csbatista** [comment]
@orestis, can you share how you did it in your content array? I'm trying to group together an image and its title so the page break occurs before the title or after the image, and not between, but the content is dynamic. Would your approach work in this case?

**Comment by 185driver** [comment]
How can this principle be applied to an entire table row as a group? I have table rows with three columns and one of the columns is multi-line. Placing an `id` on each column only page breaks before the column spanning two pages. The other column's data is left on the previous page because it fails the test.
