### ISSUE TITLE
Read file after writing

### ISSUE THREAD

**Issue by brno32** [bpampuch/pdfmake#2420]
After generating the pdf on a server, I'd like to read the file and upload it to AWS S3

```javascript
    const filename = "example.pdf"

    const pdfDoc = printer.createPdfKitDocument(docDefinition);
    pdfDoc.pipe(fs.createWriteStream(filename));
    pdfDoc.end();

    const fileContent = fs.readFileSync(filename)
```

however this gives me `ENOENT: no such file or directory, open 'example.pdf'`. Can someone provide a code example of how to get the file content after generation?

**Comment by liborm85** [comment]
Method `pipe` is async, you need to wait for document to be created, see: https://github.com/bpampuch/pdfmake/blob/4f12968b0a9be8f3d46326d5b2094dc7fa8aa3b5/src/OutputDocumentServer.js#L13-L17

In example on line 15 is document fully available to read or anything else.

**Comment by brno32** [comment]
Thanks. Makes sense!
