### ISSUE TITLE
Uncaught SyntaxError: Unexpected token ':' (at vfs_fonts.js:2:12)

### ISSUE THREAD

**Issue by alexvrv** [bpampuch/pdfmake#2422]
Uncaught SyntaxError: Unexpected token ':' (at vfs_fonts.js:2:12)

Using 0.3 v2 beta. I have builded the vfs_fonts.js with the shell script on Windows. Am I doing something wrong?
Worked perfectly with 0.2.4 but i need promise

UPDATE: shell script has a small mistake - in (echo "var vfs = ") should be (echo "var vfs = {")  '{' was missing

#!/bin/sh

if [ -t 1 ]; then
	target="vfs_fonts.js"
else
	target="/dev/stdout"
fi

(
	echo "var vfs = "
	for file in "$@"; do
		file=$1
		filename=$(basename $file)
		filecontent=$(base64 -w 0 $file)
		shift
		echo "\"${filename}\":\"${filecontent}\""
		if [ "$#" -gt 0 ]; then
			echo ","
		fi
	done
	echo "}"
	echo "; var _global = typeof window === 'object' ? window : typeof global === 'object' ? global : typeof self === 'object' ? self : this; if (typeof _global.pdfMake !== 'undefined' && typeof _global.pdfMake.addVirtualFileSystem !== 'undefined') { _global.pdfMake.addVirtualFileSystem(vfs); } if (typeof module !== 'undefined') { module.exports = vfs; }"
) > "$target"

**Comment by liborm85** [comment]
Thanks. Fixed by commit https://github.com/pdfmake/docs/commit/8800d7bdee1e02ef5cbbcc5c4f85abb8f594962f.
