### ISSUE TITLE
italics not working

### ISSUE THREAD

**Issue by igregson** [bpampuch/pdfmake#243]
Greetings,

I can't seem to get any italics working... not even in the playground. The docs say they're supported, are they? 

Many thanks.

**Comment by jthoenes** [comment]
Hi igregson,

two ideas come to my mind:
* you did not define a font that supports italics (or bold together with italics)
* your using version 0.1.16 which still has #162

If that's not the case, please post your document definition.

Best regards
Johannes

**Comment by igregson** [comment]
Thanks @jthoenes. 

Found the problem:
the readme says `italic: true` but should say `italics: true`

I've submitted PR https://github.com/bpampuch/pdfmake/pull/245 with the fix.
