### ISSUE TITLE
'Unhandled Promise Rejection' error in Angular

### ISSUE THREAD

**Issue by db-69** [bpampuch/pdfmake#2430]
I started to use pdfmake in Angular app. It works fine on my machine.

But when the app runs on our server, the pdf is generated okay, but I got the following error when the pdfMake.createPdf().download() function is called and then the app is stuck:

Unhandled promise rejection TypeError: null is not a function

![image](https://user-images.githubusercontent.com/104134992/164423841-81a81570-d3a6-4294-a69b-dd11e8ecaaa7.png)

**Comment by liborm85** [comment]
I don't known what is on line 30.

**Comment by db-69** [comment]
Thank you for your reply.

adrum is the AppDynamics js library:
https://cdn.appdynamics.com/adrum/adrum-21.6.0.3448.js

In the browser console, the line 30 looks like this:

h,n,f,m){a.assert(b.support(c),"M11");c=c||function(){};return function(){if(a.isDebug)try{a.log("M12",f,k(arguments).join(", "))}catch(b){a.log("M13",e(b.stack)||b.toString())}var u=k(arguments),r,s=null;try{if(h&&(r=h.apply(this,u))){var g=a.utils.Qk(r),s=r[g];-1!==g&&r.splice(g,1)}}catch(y){a.exception(y,"M14",f,y)}a.assert(!r||a.utils.isArray(r));g=void 0;try{g=c.apply(this,r||u)}catch(q){throw a.log(q,"M15",f,q),m?m(q):a.monitor.ErrorMonitor.n(q),q;}finally{try{n&&(s?(s.adrumArgs.origFuncResult=

**Comment by liborm85** [comment]
I don't see any connection with pdfmake. Try to ask on adrum support.

**Comment by srivastavaanurag79** [comment]
"pdfmake": "^0.2.4"

This is the error:

<img width="328" alt="image" src="https://user-images.githubusercontent.com/24560090/182357769-e92349bc-a7be-4270-9639-a1354f598d96.png">


Unhandled promise rejection TypeError: null is not a function
    at __webpack_modules__.9662.module.exports (pdfmake.js:35668:1)
    at new Promise (pdfmake.js:42290:1)
    at ZoneAwarePromise.then (zone-evergreen.js:961:1)
    at pdfmake.js:42355:1
    at new Promise (pdfmake.js:42294:1)
    at ZoneAwarePromise.then (pdfmake.js:42354:1)
    at AnimationRendererFactory._scheduleCountTask (animations.js:338:1)
    at animations.js:393:1
    at ZoneDelegate.invoke (zone-evergreen.js:365:1)
    at Zone.run (zone-evergreen.js:124:1)
