### ISSUE TITLE
doest not Repeat table header on each page Using html-to-pdfmake

### ISSUE THREAD

**Issue by vstar001** [bpampuch/pdfmake#2439]
https://github.com/Aymkdn/html-to-pdfmake/issues/133#issuecomment-1042727716

**Comment by vstar001** [comment]
hi 
import { Component, ElementRef, ViewChild } from '@angular/core';

declare var require: any;

import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from "pdfmake/build/vfs_fonts";
const htmlToPdfmake = require("html-to-pdfmake");
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css']
})
export class AppComponent {
  title = 'angular-html-to-pdf-app';
  @ViewChild('pdfTable')
  pdfTable!: ElementRef;
  
  public downloadAsPDF() {
    const pdfTable = this.pdfTable.nativeElement;
    var html = htmlToPdfmake(pdfTable.innerHTML);
    const documentDefinition = { content: [html],table:{headerRows: 1} };
    pdfMake.createPdf(documentDefinition).open(); 
    // pdfMake.createPdf(documentDefinition).download(); 
  }
}

this my coding but its not working

**Comment by vstar001** [comment]
> Use `headerRows: 1` in `table` definition.

hi
import { Component, ElementRef, ViewChild } from '@angular/core';

declare var require: any;

import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from "pdfmake/build/vfs_fonts";
const htmlToPdfmake = require("html-to-pdfmake");
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;

https://github.com/component({
selector: 'app-root',
templateUrl: './app.component.html',
styleUrls: ['./app.component.css']
})
export class AppComponent {
title = 'angular-html-to-pdf-app';
@ViewChild('pdfTable')
pdfTable!: ElementRef;

public downloadAsPDF() {
const pdfTable = this.pdfTable.nativeElement;
var html = htmlToPdfmake(pdfTable.innerHTML);
const documentDefinition = { content: [html],table:{headerRows: 1} };
pdfMake.createPdf(documentDefinition).open();
// pdfMake.createPdf(documentDefinition).download();
}
}

this my coding but its not working

**Comment by liborm85** [comment]
A don't see any table definition with rows in your example.

**Comment by vstar001** [comment]
iam adding this in my coding
 const documentDefinition = { content: [html],table:{headerRows: 1} };

**Comment by liborm85** [comment]
Property `headerRows` must be added to table which should have a header, see example: https://github.com/bpampuch/pdfmake/blob/0.2.5/examples/tables.js#L173
