### ISSUE TITLE
Hiding row if value is false

### ISSUE THREAD

**Issue by chatay** [bpampuch/pdfmake#2441]
Do we have a option to hide any element in the table if some value is false?

       const hasGstValue = pricing.cgst > 0;
           hasGstValue && 
            [
              {
                text: test,
                fontSize: test,
                margin: [0, 10, 0, 0],
                bold: true
              },
              
              {
                text: formatCurrency({
                  price: 10,
                  currencyLabel: "test "
                }),
                headlineLevel: headlineLevel.subtotal,
                alignment: "right",
                fontSize: test,
                margin: [0, 10, 0, 0]
              }
            ] : 
            
            
 if it is true, it works perfectly. if false, it gives the below error.
pdfmake.js:87940 Malformed table row  false in node 

     if (data === undefined) {
                console.error(
                  "Malformed table row ",
                  rowData,
                  "in node ",
                  node
                );
                throw "Malformed table row, a cell is undefined.";

**Comment by liborm85** [comment]
This is correct, table row cannot be null.
You can create table dynamically by [Array.push](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/push) to variable with table rows.
