### ISSUE TITLE
Typescript cast to TableCell

### ISSUE THREAD

**Issue by Sliffcak** [bpampuch/pdfmake#2444]
I do not see a way to use TableCell as an interface in client code. Or was there a different interface intended for this purpose? 

Example: If I have a 

`var test : Table =  ....`

how do I use typescript and create a `TableCell[][]`

For instance;

`var tableCells : TableCell[][] = test.body;` is not possible since TableCell defines a type and not an interface. Maybe I am misunderstanding

I could create my own generic type to mock a table cell property with any `Content` but I do not think its best practice. For example I can define:

```
export interface TableCellExtraProps {
  rowSpan?: number | undefined;
  colSpan?: number | undefined;
  border?: [boolean, boolean, boolean, boolean] | undefined;
  borderColor?: [string, string, string, string] | undefined;
  fillOpacity?: number | undefined;
}
export type TableCellMocked<T> = T & TableCellExtraProps;
```

then in code I can cast any `Content` to a `TableCellMocked` if needed in order to access the `TableCellExtraProps`

**Comment by liborm85** [comment]
Not related with pdfmake. TypeScript definition is not part of pdfmake.
