### ISSUE TITLE
The responsiveness of table is cut.

### ISSUE THREAD

**Issue by muath-ye** [bpampuch/pdfmake#2445]
How to display the table to be responsive like datatables.

Here is my table
![image](https://user-images.githubusercontent.com/34031333/172575077-2b6f7642-4fe3-4426-8548-b9217065eee2.png)

Here is what I need to do
![image](https://user-images.githubusercontent.com/34031333/172576350-d26f9de5-69d1-46c5-83e7-170c2a0e0e67.png)

**Comment by liborm85** [comment]
It is easy, simple example:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					['First name', 'Last name', 'Position', 'Office', 'Age', 'Start date'],
					['Airi', 'Satou', 'Acoutant', 'Tokyo', '33', '2018-11-28'],
					[{
					    colSpan:6, 
					    text: 'Some multiline text\nSecond multiline row\netc.'
					    
					 },'','','','',''],
					['Angelica', 'Ramos', 'Acoutant', 'Tokyo', '33', '2018-11-28'],
					[{
					    colSpan:6, 
					    text: 'Some multiline text\nSecond multiline row\netc.'
					    
					 },'','','','',''],					 
				]
			}
		},
	]
}
```

**Comment by muath-ye** [comment]
> It is easy, simple example:
> 
> ```js
> var dd = {
> 	content: [
> 		{
> 			table: {
> 				body: [
> 					['First name', 'Last name', 'Position', 'Office', 'Age', 'Start date'],
> 					['Airi', 'Satou', 'Acoutant', 'Tokyo', '33', '2018-11-28'],
> 					[{
> 					    colSpan:6, 
> 					    text: 'Some multiline text\nSecond multiline row\netc.'
> 					    
> 					 },'','','','',''],
> 					['Angelica', 'Ramos', 'Acoutant', 'Tokyo', '33', '2018-11-28'],
> 					[{
> 					    colSpan:6, 
> 					    text: 'Some multiline text\nSecond multiline row\netc.'
> 					    
> 					 },'','','','',''],					 
> 				]
> 			}
> 		},
> 	]
> }
> ```

This is okay , but I need to make it dynamically depending on the values of columns.
