### ISSUE TITLE
Uncaught Unrecognized document structure: {"alignment":"center"}  in Table

### ISSUE THREAD

**Issue by ABSOD** [bpampuch/pdfmake#2447]
This may have been answered, but I am having issues with a table structure.  
The error is Uncaught Unrecognized document structure: {"alignment":"center"}

My code:
```
 data.forEach( dd => {
  var indTab =  {
   table: {
   headerRows: hdrRows,
   dontBreakRows: true, 
            body: dd},
   pageBreak: "after" }
  outarr.push(indTab);
 })
```
This is a multiple panel table with the same number of rows in each panel.  The dimensions of the table are the same for each panel.

Here is an example of a data row within a panel:
```
0: Array(5)
0: {text: ' ', alignment: 'center'}
1: {text: 'Colorado', alignment: 'center'}
2: {text: ' ', alignment: 'center'}
3: {text: 'Central Mountains', alignment: 'center'}
4: {text: ' ', alignment: 'center'}
```

This is a row within a 5-column table (in this example, there are 11 rows in each panel).
My reading of the doc suggests that this structure shouldwork.  But pdfmake throws an error at line 14462 (pdfmake.js, called by
https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.36/pdfmake.min.js )

Any suggestions?
TIA

**Comment by liborm85** [comment]
Attach example runnable on [playground](http://pdfmake.org/playground.html).
