### ISSUE TITLE
Is it possible to remove header and footer from certain pages in content array?

### ISSUE THREAD

**Issue by Saad1379** [bpampuch/pdfmake#2448]
Is it possible to remove header and footer from certain pages in conten array? I have section title pages inside document on which I do not want to show header and footer.  But the content inside of those sections pages in generated dynamically so I do not know on which page number the section title page will be rendered. That is why I cannot use `currentPage` variable in this case. Is there any solution?

**Comment by Saad1379** [comment]
@bpampuch Any idea how this can be done?

**Comment by liborm85** [comment]
Feature request here: https://github.com/bpampuch/pdfmake/issues/283
