### ISSUE TITLE
How to add a link of local file as external link in pdf

### ISSUE THREAD

**Issue by revathiVinoth** [bpampuch/pdfmake#2451]
I used file:///C:/Users/****/Desktop/****/****/public/uploads/santest3/Requirements/Attachments but its not working. Is it possible to provide a local file as external link

replaced ** for privacy purpose

**Comment by timothyerwin** [comment]
if I understand correctly, it doesn't make sense to do this

**Comment by liborm85** [comment]
I tested it in Adobe Reader and this works correctly:
```js
var dd = {
	content: [
		{
		    text: 'link',
		    link: 'file:///c:/testFile.txt'
		}
	]
}
```

**Comment by timothyerwin** [comment]
even if it worked it doesn't make sense. why link to a local file?

it seems like a bad design.

**Comment by liborm85** [comment]
Documentation updated: https://github.com/pdfmake/docs/commit/45fa587bb9c97ff06c055fa653295cda19a355ff
