### ISSUE TITLE
pdfmake 0.1.70 compiled error

### ISSUE THREAD

**Issue by fengnian7** [bpampuch/pdfmake#2454]
Hello, there is an error in compiling pdfmake 0.1.7, as shown below.  Could you please help to check it? Thank you very much and LOOK forward to your reply！The error was reported in May 2022 after being used for half a year.

![image](https://user-images.githubusercontent.com/35560697/177927582-4e2e05be-cac5-4c86-a922-3c50fdee2523.png)

**Comment by liborm85** [comment]
Update to latest version.
