### ISSUE TITLE
Custom Font Collection Via URL Protocol Does Not Seem To Work

### ISSUE THREAD

**Issue by fearghalom** [bpampuch/pdfmake#2456]
I'm trying to add a custom font using a TrueType Collection (.ttc) with a URL address. I've followed the [example ](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/) in the documentation but I get an error: 

> ERROR
> Error: Uncaught (in promise): TypeError: url.toLowerCase is not a function
> TypeError: url.toLowerCase is not a function

It looks like the library is treating the font type definition as a string when the examples show that an array of strings should be specified to identify the .ttc file and font name.  

Specifying a .ttf file via the URL protocol method works fine, it's only with the usage of a .ttc file and the specification of the font name that the issue seems to occur.

I've reproduced the issue on StackBlitz: https://stackblitz.com/edit/angular-pdfmake-example-5prbnt?file=src/app/app.component.ts

**Comment by liborm85** [comment]
Loading TTC from URL fixed by commit https://github.com/bpampuch/pdfmake/commit/eebdf143ca9e6e6bdec0b51d3e516f0806e2348c.
