### ISSUE TITLE
Greek Font is shown like unicode.

### ISSUE THREAD

**Issue by parthsavaliya1** [bpampuch/pdfmake#2457]
Greek font is shown like this.
https://prnt.sc/mOB_vCy3ktMo

**Comment by liborm85** [comment]
Font probably does not support characters you require. Use font which support required characters.

**Comment by parthsavaliya1** [comment]
Hii liborm can you please help here which font i need to use. currently i am using 
![Screenshot from 2022-08-08 12-41-17](https://user-images.githubusercontent.com/49479934/183360874-81e99de5-bdbe-486a-9e57-a9008491e321.png)

**Comment by parthsavaliya1** [comment]
Hi Any update here. This is the example for issue i am facing https://d3dqeg6cnh5mh9.cloudfront.net/carnival-public/pdf-guides/cunardguides.com/Corfu.pdf
