### ISSUE TITLE
Image on repeated header gets duplicated

### ISSUE THREAD

**Issue by albertoLGDev** [bpampuch/pdfmake#2459]
My Problem is that I upload two different images with the same height and width and one gets duplicated and the other prints well.
The problem appears both uploading by url and with base64.
I upload the image by this object:
`  var logo = {
                    image: 'data:image/image/png;base64,' + jsondata.company.logo,
                    width: 140,
                    maxHeight: 100,
                    margin: [10, 0, 0, 0]
                }`
![image](https://user-images.githubusercontent.com/101418432/181459614-bb802d1e-f70f-4e23-ac5c-8098c0a15b6b.png)
![image](https://user-images.githubusercontent.com/101418432/181460109-db894bfe-adad-4814-882d-46ee410740d1.png)

By the way: I can`t manage to get both maxWidth and maxHeight work together like this:
                    maxWidth: 140,
                    maxHeight: 100,

Edit: if i change the duplicated image to a jpg image, it stops duplicating it

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).
