### ISSUE TITLE
pdfMake and two (maybe) specific pdf files -> preview shows blank page when both added to preview

### ISSUE THREAD

**Issue by PiotrSwedrowski** [bpampuch/pdfmake#2461]
[oncotarget-08-3237-s001.pdf](https://github.com/bpampuch/pdfmake/files/9245446/oncotarget-08-3237-s001.pdf)
[oncotarget-08-3237.pdf](https://github.com/bpampuch/pdfmake/files/9245448/oncotarget-08-3237.pdf)

Hello, 
recently I have encountered an issue with pdfMake while trying to show(print) using pdfMake thumbnails of the attached two pdf files, First I did thumbnails of both  pdf files, then I have used some online image to base64 encoder to encode pdf files to create base64 images as an inputs for pdfMake and then something very strange appears....on pdfMake playground when I tried to add both files then pdfMake in preview shows blank page....when I will remove one file from code, then pdfMake preview works fine and one file is showed properly.

I have a question is there any limitation for pdfMake for file size of base64 image to show or something like this? In my code attachments which are attached to report which then later we are getting the base64 images from attachments which are then printed in report, whenever I have added both of these pdf files which I have provided, then pdfMake preview shows blak page, if I will add only one of the pdf files which I have provided you to try, then pdfMake preview worked fine. 

Or maybe these two pdf files are somehow very specific and pdfMake has issues when they are both rendered/preview...this is also possible, if someone knows how to check these pdf files if maybe one of them is somehow corrupted, I would appreciate. 

I have ask/favour to people who knows pdfMake or people who developed it or participate in development, can you check the attached files and try to preview both n pdfMake as { image: ....... } and check it, then let me know about some outcomes .... or maybe someone already knows the answer that maybe pdfMake has some limitations. 

I can add that when opening preview from pdfMake in new browser tab or download pdf file, then everything is rendering just fine and both images are on pdf....only preview in iframe is not working properly and when both images are included then pdfMake is rendering blank page.

Thank you all very much for any help or advice or tips. 
Best regards

**Comment by liborm85** [comment]
pdfmake has no hard limit for base64. If there are problems with the pdf preview in browser, it is usually caused by a problem with browser (viewer plugin).

**Comment by PiotrSwedrowski** [comment]
ok, the ticket is closed, but if someone with more expirience in pdfmake could check these two attachment and try to display  thumbnails of them in base64, it would be nice to try and give some thoughts....if anyone would give a try, please write your comments/conclusions here and thank you.
