### ISSUE TITLE
linkToDestination by default points to second page in case of page-break

### ISSUE THREAD

**Issue by htambekar** [bpampuch/pdfmake#2463]
In case of page-break (condition when contents of the page uses next page), when linkToDestination points to title of the page, by default, link points to second page instead of first page.
Ideally linkToDestination should point to first page (start)

I am generating a PDF, in which sometimes when there are extra-rows, contents gets displayed in second page (next page). Title of the first page and second page is exactly similar. I am pointing linkToDestination to title of the page. Since title is same on both pages, after clicking hyperlink directly second page gets displayed instead of first page.
Expectation :- Hyperlink should redirect user to first page.

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).
