### ISSUE TITLE
GetBase64 function break the design 

### ISSUE THREAD

**Issue by albertoLGDev** [bpampuch/pdfmake#2465]
Hello.
I have an issue when I try to get the base64 of my document.
I have two lines that I have created with canvas type rect.
The error does`t happen every time, but when it happen it mess up those lines, and then it creates a couple of new pages in my document with this lines.
The error doesn`t appear when downloading, only when converting to base64.

**Comment by albertoLGDev** [comment]
the same happens when I use getDataUrl

**Comment by albertoLGDev** [comment]
A code example for the playground.
everything works well until i use the getBase64 function, then it mess up.

`var hrFinalTasas = 200; //I use this because in the real code, this number will depend on some conditionals.
var dd = {
	content: [
		{
			text: 'This is a header, using header style',
			style: 'header'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam.\n\n',
		{
			text: 'Subheader 1 - using subheader style',
			style: 'subheader'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
		
			{
                                        canvas: [
                                            {
                                                type: 'rect',
                                                x: 296,
                                                y: hrFinalTasas,
                                                w: 260,
                                                h: 1,
                                                lineColor: '#dedede'
                                            },
                                        ]
                                    },
		{
			text: 'Subheader 2 - using subheader style',
			style: 'subheader'
		},
	
	
	],

	
}
var mypdf =  pdfMake.createPdf(dd);
mypdf.getBase64((data) => {
 
        });`

**Comment by backciro** [comment]
same here, still open 0.2.10. 
Did you find some workaround?

**Comment by liborm85** [comment]
`docDefinition` can be used only once. If you need to generate multiple times is need clone/copy original `docDefinition` and it pass into pdfmake. See https://github.com/bpampuch/pdfmake/issues/1576
