### ISSUE TITLE
Wrong downloading format

### ISSUE THREAD

**Issue by SivachenkoYegor** [bpampuch/pdfmake#2468]
Hello.
I'm using the typical downloading method to download created pdf.
Everything is working fine on local env as well as on dev/prod env Chrome, Mozilla, etc browsers. But on Safari in dev/prod env I have some troubles with the downloading format. It always returns with `example.com` name and resolution.

How it can be fixed from my side or is it a library issue? I recheck everything several times and found nothing from my side.

**Comment by liborm85** [comment]
pdfmake use for download method library [FileSaver.js](https://github.com/eligrey/FileSaver.js/). If is any problem create issue [here](https://github.com/eligrey/FileSaver.js/issues).
