### ISSUE TITLE
backgroundColor and blocks

### ISSUE THREAD

**Issue by terragady** [bpampuch/pdfmake#2470]
![image](https://user-images.githubusercontent.com/19210041/186717563-76c60f03-f408-4863-9822-421881d69612.png)

Is it possible to achieve something like this in pdfmake? Partial background color not for the full page? And the block with corner radius? I am only able to add text, tables and images but not fancy styling. Thanks!

**Comment by liborm85** [comment]
Not supported now.
Feature request here: https://github.com/bpampuch/pdfmake/issues/2470
