### ISSUE TITLE
I need to populate another column in same page once after the first column content is overflowed

### ISSUE THREAD

**Issue by revathiVinoth** [bpampuch/pdfmake#2475]

**Comment by revathiVinoth** [comment]
Please provide any methods that could be available that could wrap a new column once the column is filled. 
I am using the dynamic content which might populate on the run time

**Comment by fuzail-afsar** [comment]
I am also facing the same problem

**Comment by liborm85** [comment]
Not supported now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/604
