### ISSUE TITLE
Table cell with Image and text

### ISSUE THREAD

**Issue by Sreejithga** [bpampuch/pdfmake#2476]
Hi Team,

Can someone please guide me on how to create table cells with image and text content inside it. I know this is the method to be used in order to create a table cell - createTableCell(cellValue, colId), please guide further to achieve the below

![image](https://user-images.githubusercontent.com/53110553/189827330-1e599681-b4d0-4e02-8acc-af90eac4755b.png)

Above is what needs to be achieved in the PDF, Please guide.

Thanks

**Comment by liborm85** [comment]
docdefinition example:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					[{image: 'sampleImage.jpg', width: 50},'123 %'],
					[{image: 'sampleImage.jpg', width: 50},'456 %'],
					[{image: 'sampleImage.jpg', width: 50},'789 %'],
				]
			}
		},
	]
}
```
