### ISSUE TITLE
Prefetching custom fonts

### ISSUE THREAD

**Issue by mgesbert** [bpampuch/pdfmake#2477]
Hello,

we use pdfmake with a collection of custom fonts that we load via URLs (as described here https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/). Every time we call `pdfMake.createPdf()`, pdfmake downloads all the custom font files, even when we use it several times in a row. Is there any way to avoid refetching all the fonts for each doc definition, or even better, to prefetch these font files?

Thanks 🙂

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/a6a7668e7ab15d7995623f91594c2a663ce781ff.
