### ISSUE TITLE
Possible date of release of the stable version 0.3. ?

### ISSUE THREAD

**Issue by cb66** [bpampuch/pdfmake#2478]
I have been following up with the changes that are coming with the 0.3 version. They are really great, I am looking forward mainly to Attachments and Promises.

**Comment by TanushreeB2611** [comment]
Any update on the possible release date for stable version 0.3 ?

**Comment by liborm85** [comment]
Date of release final 0.3 version is unknown. Watch issue https://github.com/bpampuch/pdfmake/issues/2375.
