### ISSUE TITLE
Header and footer are not shown

### ISSUE THREAD

**Issue by dbautistav** [bpampuch/pdfmake#248]
Header and footer content are not shown when building the PDF document (even playing with the margins in order to have enough space for them).

```javascript
var docDefinition = {
  footer: "Bottom", 
  header: "Top",
  content: (...)
}
```

Both are attached to docDefinition Object after this call:
```javascript
pdfMake.createPdf(docDefinition).open()
```
but are not shown in final pdf file.

**Comment by jthoenes** [comment]
This is a duplicate of #227 - will be fixed in the next release. For now, wrap them in a function.

**Comment by dbautistav** [comment]
Ok, thank you.
