### ISSUE TITLE
Weird padding when using rowSpan on a specific column.

### ISSUE THREAD

**Issue by vixalien** [bpampuch/pdfmake#2484]
The title says it all.

![image](https://user-images.githubusercontent.com/37999241/194317088-d5cc8ce1-80eb-4c9a-8efc-474c5ff089cf.png)

When there is no `rowSpan` on the third (Quantity) column, it all works well.

![image](https://user-images.githubusercontent.com/37999241/194317332-4ce74820-685d-405a-a414-a18ddbefc52c.png)

**Comment by liborm85** [comment]
Attach example for reproduce issue runnable on [playground](http://pdfmake.org/playground.html).

**Comment by vixalien** [comment]
my bad. it was caused by the fact that the first row continued. i fixed it by adding part of the data to the first row, then adding separate rows for consequent data.
