### ISSUE TITLE
Cannot read properties of undefined (reading 'bits')

### ISSUE THREAD

**Issue by nonam4** [bpampuch/pdfmake#2486]
I'm trying to use PdfMake in my NextJS project.
Everything works fine in development but it's not working in the production build.

Here is a screenshot of the error I'm getting
![Captura de Tela 2022-10-10 às 11 18 38](https://user-images.githubusercontent.com/60632638/194888073-1187fdfc-48f2-4483-be71-61e4264981b0.png)

I've created a [repository](https://github.com/nonam4/pdfmake_netxjs) with a simple project and all the instructions to reproduce the error.

**Comment by vlohar08** [comment]
Disable swcMinify and everything will work!
![image](https://user-images.githubusercontent.com/89565983/198813253-562a01bc-9ea3-4704-8eab-f1df0cd70024.png)

**Comment by imchivaa** [comment]
facing same issue, deployed to vercel, locally doesn't hit this.

**Comment by maxtheaxe** [comment]
For future searchers: in Firefox, the error is `TypeError: t[e] is undefined`. I didn't find my way to this issue until I tried looking for the Chrome version of the error, which is already listed above.

![image](https://github.com/bpampuch/pdfmake/assets/20795292/880253ce-e6ec-4cf1-87c3-95df4881bb97)

**Comment by maxtheaxe** [comment]
Was this ever resolved? I keep getting warnings that disabling SWC Minifer will not be an option in the next major version.

**Comment by luicfrr** [comment]
I’m using next 14 and without disabling swc and it seems to be working

**Comment by maxtheaxe** [comment]
Interesting, thanks. I'll report back once I've tried the same (since I'm in the process of upgrading to next 14 myself).
