### ISSUE TITLE
Not able to use rowSpan >2

### ISSUE THREAD

**Issue by julieagaze** [bpampuch/pdfmake#249]
Hi,
  On using colSpan and rowSpan together and if the rowSpan>2, I get the divider line between the columns  In the below example, the line is displayed on row 3 . we can replace the following in the first table of the playground.
	table: {
		body: [
			[{"text":'Column 11'}, {"rowSpan":3,"colSpan":2,"text":'Column 12'}, ''],
			[{"text":'Column 21'},{"text":''}, ''],
		        [{"text":'Column 31'}, 'Column 2', 'Column 3'],
			[{"text":'Column 41'}, 'Another one here', 'OK?'],
		]
						}

**Comment by jthoenes** [comment]
Looks like this is fixed with #239. 
It's not released yet and we have unfortunately problems with grunt-browserify.

Might take some time to get released. Sorry!
