### ISSUE TITLE
Move away from `@foliojs-fork` and back to the now up to date `@foliojs`, fixing a critical vulnerability on `minimist`

### ISSUE THREAD

**Issue by AnthonyLenglet** [bpampuch/pdfmake#2492]
pdfmake > @foliojs-fork/linebreak > brfs > quote-stream > minimist@1.1.3

This version of minimist has a critical vulnerability related to prototype pollution
https://github.com/advisories/GHSA-xvch-5gv4-984h

it looks like this fork was originally made to remediate the lack of updated version on npm, which has since been fixed
https://github.com/foliojs/linebreak/issues/24#issuecomment-875319448

the updated version in the official, non-forked version, includes this commit that removes the brfs dependency completely, hence fixing the vulnerability
https://github.com/foliojs/linebreak/commit/ac397ca18f94334a3a935d2988d8cbbbb051346a#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519

**Comment by liborm85** [comment]
Fixed in version 0.2.10.
