### ISSUE TITLE
fontFeatures property of styling is not availabe for svg

### ISSUE THREAD

**Issue by gdfeeling** [bpampuch/pdfmake#2499]
In pdf we are using SVG images which contains text. We want to apply fonFeatures property in SVG just like we are using text.
Is there any way to do so in pdfmake?

**Comment by liborm85** [comment]
pdfmake for converting svg using [svg-to-pdfkit library](https://github.com/alafr/SVG-to-PDFKit), probably doesn't support it. You can create an issue [there](https://github.com/alafr/SVG-to-PDFKit).
