### ISSUE TITLE
Module parse failed on Angular 14

### ISSUE THREAD

**Issue by obrador** [bpampuch/pdfmake#2502]
Hi, I've just updated my project from Angular 11 to 14 and Pdfmake started to give next error, on Angular 11 or less it worked very well for several years, I can't tell on which version of Angular this error appears.

```
ERROR in ./node_modules/pdfmake/build/pdfmake.js 43324:116

Module parse failed: Unexpected token (43324:116)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/source-map-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
|            *     not null.
|            */
>           function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|             var tree = desc.dyn_tree;
|             var max_code = desc.max_code;
```

Have anyone found this issue before? Is there any workarround or solution?

Many thanks in advance.
Jaume.

**Comment by subratbhola** [comment]
Getting the same error with below mentioned configuration:
1. Angular 11
2. pdfMake: 0.1.71 and 0.2.4
3. node 10.21.0

Error: Module parse failed: Unexpected token (43456:116)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|            *     not null.
|            */
>           function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|             var tree = desc.dyn_tree;
|             var max_code = desc.max_code;
Error: Module parse failed: Unexpected token (71044:112)
File was processed with these loaders:
 * ./node_modules/@angular-devkit/build-angular/src/babel/webpack-loader.js
 * ./node_modules/@ngtools/webpack/src/ivy/index.js
You may need an additional loader to handle the result of these loaders.
|        */
| 
>       function gen_bitlen(s, desc) /*    deflate_state *s;*/ /*    tree_desc *desc;    /* the tree descriptor */*/{
|         var tree = desc.dyn_tree;
|         var max_code = desc.max_code;


Team pdfMake , requesting you to share the feedback ASAP.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/2502
