### ISSUE TITLE
Barcode Generation Support

### ISSUE THREAD

**Issue by heldergoncalvesneptunesoftware** [bpampuch/pdfmake#2509]
We found some description on how to achieve this https://github.com/bpampuch/pdfmake/issues/929 using 3rd party. Is there any plans or someone working on it to add it as standard?

**Comment by liborm85** [comment]
No plan to add it. It is better to use an external library to create barcode.

**Comment by hfgoncalves** [comment]
Could you suggest one?

**Comment by liborm85** [comment]
For example barcode-generator is mentioned here https://github.com/bpampuch/pdfmake/issues/929#issuecomment-289996885 and jsbarcode here https://github.com/bpampuch/pdfmake/issues/929#issuecomment-455571103
