### ISSUE TITLE
Get the document generated blob

### ISSUE THREAD

**Issue by dbautistav** [bpampuch/pdfmake#251]
Get the document generated blob in order to do whatever other task with.

```javascript
var document = pdfMake.createPdf(docDefinition);
document.open();
document.download("myDoc.pdf");

// Like this:
var docBlob = document.getBlob();
(...)
```

**Comment by dbautistav** [comment]
Now I am taking advantage of `getDataUrl()` callback:

```javascript
var document = pdfMake.createPdf(docDefinition);
var docBlob = null;

document.getDataUrl( function (result) {
  docBlob = result;
});

(...)
```

Maybe a more straight way?

**Comment by jthoenes** [comment]
You can also use

````javascript
document.getBuffer( function (buffer) {
  blob = new Blob([buffer]);
});
````

What do you mean by straight way? No asynchronous callback? 

That is not possible, since the pdfkit library which pdfmake uses is event based.

**Comment by dbautistav** [comment]
No, the asynchronous callback is really cool. I meant one function like `getBuffer()` as you suggested, but since it does not appear in the documentation nor the examples, I thought a function like this was missing.

Thanks one more time @jthoenes.
