### ISSUE TITLE
tocItems from dynamically generated list 

### ISSUE THREAD

**Issue by bastifix** [bpampuch/pdfmake#2511]
Hey, thanks for this great tool for creating amazing PDFs!
I now want additionally a table of contents from a dynamically generated list of tables. I started with:
```
  content: [
        {
          toc: {
            title: { text: "Table of contents", style: 'header' },
            numberStyle: { bold: true }
          }
        },
```
For normal entries like
`  { text: "Header" , style: 'heading2', tocItem: true },`
it's providing a table of contents as to be expected.

But the tocItems in a for loop are missing:

```
  for (var i = 0; i < this.list.length; i++) {

          docDefinition.content.push(
                      { text: "Process" + this.list[i].name, style: 'header', tocItem: true },
      ...
```

Is there a way to get them also in the table of contents?
Thanks!

**Comment by liborm85** [comment]
Tested on [playgroud](http://pdfmake.org/playground.html) this example and works ok:
```js
var dd = {
	content: [
        {
          toc: {
            title: { text: "Table of contents", style: 'header' },
            numberStyle: { bold: true }
          }
        }
	]
}

var list = [{name: 'Item A'}, {name: 'Item B'}, {name: 'Item C'}];


for (var i = 0; i < list.length; i++) {
    dd.content.push({ text: "Process" + list[i].name, style: 'header', tocItem: true });
}
```

Output:
![image](https://user-images.githubusercontent.com/1298652/203958766-623fef1c-3b74-4f54-b842-680ba975a56e.png)

**Comment by bastifix** [comment]
Oh, I'm so sorry: Triple checked it now, stupid mistake on my site....
Thanks for your help!
