### ISSUE TITLE
pdfmake.js:55549 Uncaught TypeError: Cannot read properties of undefined (reading 'signature')

### ISSUE THREAD

**Issue by kdRanaa** [bpampuch/pdfmake#2512]
while downloading the PDF in local environment PDF make is showing the error as " pdfmake.js:55549 Uncaught TypeError: Cannot read properties of undefined (reading 'signature')" but it is working fine in Dev environment.

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue on [playgroud](http://pdfmake.org/playground.html) or other js service.
