### ISSUE TITLE
Add lines to table of contents

### ISSUE THREAD

**Issue by jopfre** [bpampuch/pdfmake#2513]
I am trying to recreate the design shown below.
![Screenshot 2022-12-09 at 09 39 27](https://user-images.githubusercontent.com/9122228/206738429-262a7a77-9aaf-4127-9259-25285b333310.jpg)
Is it possible to add lines to the TOC?

I can see two references to `lineStyle` in the code

```
184 | let lineStyle = item._textNodeRef.tocStyle \|\| textStyle;
185 | { text: item._textNodeRef.text, linkToDestination: destination, alignment: 'left', style: lineStyle, margin: lineMargin },
```

I'm wondering if there is someway to use this as I don't see any references in the docs/examples.

**Comment by liborm85** [comment]
Not supported now, feature request: https://github.com/bpampuch/pdfmake/issues/2226
