### ISSUE TITLE
can use linkToDestination within SVG text?

### ISSUE THREAD

**Issue by dreamakeryang** [bpampuch/pdfmake#2514]
I have searched and tried different ways, but seems there isn't any solution to have linkToDestination within a SVG text. Can anyone point me to the direct direction? thank you so much!

**Comment by liborm85** [comment]
pdfmake use library [SVG-to-PDFKit](https://github.com/alafr/SVG-to-PDFKit) to transform svg to pdf, open issue [there](https://github.com/alafr/SVG-to-PDFKit/issues).
