### ISSUE TITLE
Get the number of lines of a text server side

### ISSUE THREAD

**Issue by albertoLGDev** [bpampuch/pdfmake#2517]
First of all thank you for such a good library :)
I was using the library on client side and I needed to get the number of lines in a text.
I managed to do it in a slightly strange way (Here is the code of playground example)

`function getTextMaxWidth(content) {
      const temp = [];
      temp.push(content);
      const pdf = pdfMake.createPdf({ content: temp });
      pdf.getStream({});
      return pdf.docDefinition.content[0].positions.length;
         
   }
        
   
      
    let numLineas =getTextMaxWidth({
            absolutePosition: { x: 3, y: 5 },
            
            columns: [
              {
                text: "this is the text \n second line\n other line",
                fontSize: 8
              }
            ]
          });`

notice that pdf.docDefinition.content[0].positions.length was the number of lines in the text.
We have been working with this function for a long time and had no problems, but now we are developing a server side version , and I am not able to find that data inside the object that generates  createPdfKitDocument function.

**Comment by liborm85** [comment]
Exactly the same. But beware, it is an asynchronous and createPdfKitDocument return stream then you can wait to finish process, example:
```js
var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('pdfs/basics.pdf'));
pdfDoc.end();

pdfDoc.on('end', () => {
  console.log(docDefinition);
});
```
