### ISSUE TITLE
dynamically create nested tables inside table

### ISSUE THREAD

**Issue by inceptivetech** [bpampuch/pdfmake#252]
Hello,
I must admit its good tool. I want to add nested table dynamically (depending on value of my variable), could you please let me know how can I achieve this inside content.

Regards,
Suhas

**Comment by jthoenes** [comment]
Hi @inceptivetech, could you be a bit more specific what your problem is?

**Comment by inceptivetech** [comment]
Hi,
I have a requirement where I want to have a table, having 3 rows and 1 column. Now in the third row I want to have multiple tables (based on some count) having 3 columns and 1 row.

I have created static table in content, now for dynamic tables, how should I add that in content, should I generate a string in for loop and then place this string inside content.

Please let me know.

Regards,

Suhas Chitade
CTO, Inceptive Technologies
Web: www.inceptivetechnologies.com
Skype: suhas.chitade
Mobile: +91 9850131578

**Comment by gnibeda** [comment]
you can traverse you doc definition, and add nested tables in required places based on obj props

**Comment by inceptivetech** [comment]
@gnibeda , thanks for your response. I will try that out today.

Regards,
Suhas
