### ISSUE TITLE
Error: _pdfmake.default is not a constructor for Typescript

### ISSUE THREAD

**Issue by vijaykerure** [bpampuch/pdfmake#2522]
I am using 3.0 (beta version) with typescript node backend project and getting an error "_pdfmake.default is not a constructor"

Please find the runnable example: https://replit.com/join/afqvppgymq-vijaykerure

**Comment by liborm85** [comment]
replit requires login, set example as public

**Comment by vijaykerure** [comment]
Example:


import express, { Request, Response } from 'express';
import path from 'path';
import fs from 'fs';
import PdfPrinter from 'pdfmake';

import { TDocumentDefinitions, TFontDictionary } from 'pdfmake/interfaces';

const app = express();

const docDefinition: TDocumentDefinitions = {
    pageSize: 'A4',

    pageOrientation: 'portrait',

    pageMargins: [30, 30, 30, 30],

    content: [{ text: 'test' }],
};

const fonts: TFontDictionary = {
    Roboto: {
        normal: 'fonts/Roboto-Regular.ttf',
        bold: 'fonts/Roboto-Medium.ttf',
        italics: 'fonts/Roboto-Italic.ttf',
        bolditalics: '/fonts/Roboto-MediumItalic.ttf'
    },
};

app.get('/', async (req: Request, res: Response) => {
    console.log('Request received');
    try {
        const pdfPrinter = new PdfPrinter(fonts);

        const pdfDoc = pdfPrinter.createPdfKitDocument(docDefinition);

        let writeStream = fs.createWriteStream('document.pdf');

        pdfDoc.pipe(writeStream);
        pdfDoc.end();

        // res.setHeader('Content-Type', 'application/pdf');
        // res.send({});
        res.send();
    } catch (error: any) {
        console.log(error);
        res.send(error.message);
    }
});

app.listen(3000, () => {
    console.log('Service is listing on PORT 3000.');
});

**Comment by vijaykerure** [comment]
@liborm85  Please let me know, if you need more details.

**Comment by vijaykerure** [comment]
@liborm85 Did you get a chance to work on this?

**Comment by liborm85** [comment]
Used typescript definition file (d.ts) is compatibile with pdfmake 0.3.0-beta.4?

**Comment by vijaykerure** [comment]
It might be, but not sure.

**Comment by vijaykerure** [comment]
Used typescript definition file is latest one

**Comment by liborm85** [comment]
Yes, but is compatibile with 0.3 beta? Because pdfmake d.ts is not officially supported, features request is here: https://github.com/bpampuch/pdfmake/issues/525

**Comment by vijaykerure** [comment]
Thanks for the information, until pdfmake d.ts supports to 0.3 beta, I have to downgrade my current version.
