### ISSUE TITLE
Invalid image: Error: Incomplete or corrupt PNG file Images dictionary should contain dataURL entries (or local file paths in node.js) on next js production only

### ISSUE THREAD

**Issue by mdShakilHossainNsu2018** [bpampuch/pdfmake#2525]
I am getting Invalid image: Error: Incomplete or corrupt PNG file Images dictionary should contain dataURL entries (or local file paths in node.js) on next js production only

**Comment by liborm85** [comment]
[CONTRIBUTING.md](https://github.com/bpampuch/pdfmake/blob/master/.github/CONTRIBUTING.md)
