### ISSUE TITLE
Links are not reported correctly in the PDF

### ISSUE THREAD

**Issue by andreaproietti** [bpampuch/pdfmake#2526]
Links are not reported correctly in the PDF, although the syntax is correct. For instance, inserting

`{ text: 'google', link: 'http://www.google.com' }`

results in a text "google" which is not clickable, either in the browser or in Adobe Reader. Links to other pages or destinations also do not work.

How can I solve it?

Note that, if I try to add "www.google.com", it is transformed in a link automatically.

**Comment by liborm85** [comment]
Tested in browser viewer and Adobe Reader. It works corect in both. Explain how to simulate.
