### ISSUE TITLE
Repeat element outside header and footer

### ISSUE THREAD

**Issue by lysirius** [bpampuch/pdfmake#253]
Hello,

First thank you for this great library !

I would like to know if it is possible to repeat some element outside header and footer section.
For example if i have a paragraph on 3 pages, is it possible to repeat the paragraph title ?

thanks for your answer.

**Comment by jthoenes** [comment]
Hi @lysirius, unfortunately that is not possible at the moment. There is already a feature request #178 which asks for this - so I close this issue.

Happy to accept pull requests of course ;-)
