### ISSUE TITLE
blob URL link not opening on mouse click from generated pdf using pdfmake

### ISSUE THREAD

**Issue by 2052021** [bpampuch/pdfmake#2532]
Hi Team,

link inside pdf not opening on mouse click but open while right click **open link in new tab**.
we are generating report as pdf from angular application, inside this pdf we have table , one column is for links (images\pdf).
I am setting link as blob URL that is generated from base64.

if i am giving link as **http://www.google.com** it is opening on mouse click as well but problem with blob URL.

Anyone could you help?

Thanks in Advance!

**Comment by liborm85** [comment]
pdfmake generate it correctly. The problem will be in pdf viewer.
