### ISSUE TITLE
wrap table column to next row in pdfMake

### ISSUE THREAD

**Issue by maxleon52** [bpampuch/pdfmake#2534]
Hey guys!

Is possible broke colunm for other line?

![image](https://user-images.githubusercontent.com/42389997/213758574-7468314f-7846-462a-924c-f482acce0fa1.png)

**Comment by liborm85** [comment]
Not supported now. Feature request here: https://github.com/bpampuch/pdfmake/issues/441

**Comment by del-inderjeetvadhera** [comment]
Is this issue resolved?
