### ISSUE TITLE
How to provide page-break explicitly

### ISSUE THREAD

**Issue by inceptivetech** [bpampuch/pdfmake#254]
Hi,
I want to explicit have page break, along with header and footer, could you please let me know how to achieve this.

Regards,
Suhas

**Comment by Wabbala** [comment]
Try something like this:

```javascript
{
	text: 'Lorem Ipsum',
	pageBreak: "before" // or after
}
```

**Comment by inceptivetech** [comment]
@Wabbala  thanks, could you please let me know regarding headers and footers too.

thanks in advance

**Comment by Wabbala** [comment]
@inceptivetech how do you want to break a header/footer?

**Comment by inceptivetech** [comment]
I have two subheaders as mentioned below

{ text:$scope.ProcedureName  , style: 'subheader',fontSize: 8,  alignment: 'left'},
{ text: 'Revision:  '+ $scope.ProcedureRvs, style: 'subheader',fontSize: 8,  alignment: 'right’}

on left side I have procedure name and revision number on right side. Now I have to write 2 subheader for aligning to left and right, this disturbs my horizontal alignment 


Regards,
Suhas Chitade
Skype: suhas.chitade
Mobile: +91 9850131578

**Comment by Wabbala** [comment]
The key in a different header/footer is using a function in the footer definition (within the docDeficition).
Does this help?
```javascript
docDefinition : {
    footer: function(currentPage, pageCount) {
        var columnText = [];
        columnText.push((currentPage % 2) ? "" : currentPage + "/" + pageCount);
        columnText.push((currentPage % 2) ? currentPage + "/" + pageCount : "");
        return {columns: [
                          { text: columnText[0], alignment: 'left', margin: 30,  style: 'pageHeader'},
                          { text: columnText[1], alignment: 'right', margin: 30,  style: 'pageHeader'}]}; 
    },
    content : {
        {
            text: 'Lorem Ipsum',
            pageBreak: "after" // or before
        },
        {
            text: 'Lorem Ipsum',
            pageBreak: "after" // or before
        },
        {
            text: 'Lorem Ipsum',
            pageBreak: "after" // or before
        },
    },
    styles: {
        pageHeader: {
            fontSize: 10	
        }
    }
}
```

**Comment by inceptivetech** [comment]
@Wabbala  thanks, could you please tell me about inserting image in column
i tried this:
[ {image:'mlbc-logo.png', width: 150, height: 150,}, ' 1', '2'],
but it give in result an error 'Uncaught TypeError: Cannot read property 'embed' of undefined'

Thanks in advance

**Comment by inceptivetech** [comment]
@Wabbala, tried your suggestion, however no footer or header is rendered while creating pdf.
does the function written above needs to be explicitly called? if yes how?

**Comment by Wabbala** [comment]
@inceptivetech could you post your docDefinition?

**Comment by inceptivetech** [comment]
@Wabbala 

{"content":[[{"text":"\n\n\n\n\n\n\n\n\n\n\n\n\n  Document Name: 2","fontSize":10,"alignment":"center"},{"text":"Document ID: undefined","fontSize":10,"alignment":"center"},{"text":"Revision: undefined","fontSize":10,"alignment":"center"},{"text":"Author: undefined","fontSize":10,"alignment":"center"},{"text":"Approved By: undefined","fontSize":10,"alignment":"center"},{"text":"Release Date: undefined","fontSize":10,"pageBreak":"after","alignment":"center"},{"table":{"widths":[500],"body":[["Instruction:undefined"],["Safety: undefined"],["StepInstrct:undefined"],[["Photographs",{"table":{"widths":[100,100,100],"body":[["","",""]]}}]]]}},{"text":"\n\n\n"},{"table":{"widths":[500],"body":[["Instruction:undefined"],["Safety: undefined"],["StepInstrct:undefined"],[["Photographs",{"table":{"widths":[100,100,100],"body":[["","",""]]}}]]]}},{"text":"\n\n\n"}]]}
The above is logged in console and result of mydoc, however in mydoc I have mentioned footer function which should return 1/2. please let me know if am doing wrong

  var myDoc = {
            footer: function(currentPage, pageCount) {
        var columnText = [];
        columnText.push("1");
        columnText.push("2");
        return {columns: [
                          { text: columnText[0], alignment: 'left', margin: 30,  style: 'pageHeader'},
                          { text: columnText[1], alignment: 'right', margin: 30,  style: 'pageHeader'}]}; 
            },
             content:[ ArrOrig[0]
             ]
         }

**Comment by Wabbala** [comment]
You should add the pageMargins to the doc definition.
>`pageMargins: [40,40,40,60]`

**Comment by inceptivetech** [comment]
@Wabbala 
 now it's working. thanks!

**Comment by Wabbala** [comment]
:smile: Cheers!
