### ISSUE TITLE
A PDF generated with PDFmake is fine on the computer but messy when printed

### ISSUE THREAD

**Issue by djcaesar9114** [bpampuch/pdfmake#2541]
Hello,
When I display the PDF on my computer, everything is fine. My PDF has several pages, the tables and paragraphs are fine, the colors are fine, etc. But when I print it (even in a file), look at what I have, everything is on a unique page and all the letters seem crushed, the tables have disappeared, etc:

[![enter image description here][1]][1]

What could possibly go wrong? I precise I download the file on my computer and open it with my usual PDF viewer.

  [1]: https://i.stack.imgur.com/0sUn7.png

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.
