### ISSUE TITLE
Custom font in Nodered

### ISSUE THREAD

**Issue by VesaliaBricks** [bpampuch/pdfmake#2544]
As I understand it, Node-RED only allows for a document definition to be processed, not a separate fonts-section.

Is it possible to use custom fonts (system-installed or TTF) with the Node-RED pdfmake-node out of the box?

Thanks

**Comment by liborm85** [comment]
pdfmake supports fonts in TTF files or in virtual file system (javascript file).
Questions about Node Red ask on node red support.
