### ISSUE TITLE
Can't show image url to pdf

### ISSUE THREAD

**Issue by Ben-Mananya** [bpampuch/pdfmake#2545]
I have a image url = http://203.159.92.57:1660/getqrcode/qrcode_dev/2023-2-7/BllotBox_152812023.png

Issue is when I getBase64 pdf is not show image

![Screenshot 2023-02-08 001409](https://user-images.githubusercontent.com/105309506/217316158-6d1dd167-188e-4995-9b2e-d1b450d92f3a.png)

**Comment by liborm85** [comment]
Tested on [playground](http://pdfmake.org/playground.html) and works correct:
```js
var dd = {
    content: [
        { image: 'testimage' }
    ],
    images: {
        testimage: 'http://203.159.92.57:1660/getqrcode/qrcode_dev/2023-2-7/BllotBox_152812023.png',
    }
}
```

**Comment by Ben-Mananya** [comment]
Thank you for your advice.
