### ISSUE TITLE
Getting TypeError: Cannot read properties of undefined (reading 'bottomMost')

### ISSUE THREAD

**Issue by Nevetha-Manoharan** [bpampuch/pdfmake#2549]
Hi @bpampuch , 
I was trying to generate dynamic pdf with multiple tables.  In some scenarios, I was getting an error of **TypeError: Cannot read properties of undefined (reading 'bottomMost')**

Here is my docDefinition

'{"pageSize":"A4","pageOrientation":"portrait","pageMargins":[10,270,10,110],"header":{"margin":[10,40,10,30],"stack":[{"columns":[{"alignment":"center","text":"Interventional Procedures RN Skills Checklist","style":"heading"},{}]},{"margin":[1,35,1,1],"columns":[{"table":{"heights":[10,125],"headerRows":1,"widths":[265],"body":[[{"text":"Instructions","style":"tableHeader","borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"],"fillColor":"#545B67","alignment":"center"}],[{"margin":[1,2],"text":"Please select a value for each question to provide us, you will have to re-do.","style":"headerData","borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"]}]]}},{"table":{"heights":[10,125],"headerRows":1,"widths":[265],"body":[[{"text":"Provided Key","style":"tableHeader","borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"],"fillColor":"#545B67","alignment":"center"}],[{"margin":[1,8],"type":"none","ol":["0 Zero","1 One","2 Two","3 Three","4 Four","5 Five"],"style":"headerData","borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"]}]]}}]}]},"content":[{"widths":["auto","auto"],"columns":[{"stack":[{"style":"tableExample","color":"#444","margin":[1,3],"table":{"widths":[150,10,10,10,10,10,10],"heights":20,"headerRows":2,"body":[[{"text":"group 1","style":"tableHeader","borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"],"fillColor":"#545B67","margin":[1,3]},{"text":"Provided","style":"tableHeader","colSpan":6,"borderColor":["#9EA4B0","#9EA4B0","#9EA4B0","#9EA4B0"],"fillColor":"#545B67","margin":[1,3]},"","","","",""]]}}]},{"stack":[]}]}],"styles":{"heading":{"color":"#444F8B","bold":true,"fontSize":12},"userDetails":{"fontWeight":400,"fontSize":10,"fontFamily":"Arial","fontStyle":"normal","color":"#444F8B"},"bgColor":{"fillColor":"#545B67","color":"#FFFFFF"},"tableExample":{"margin":[60,60,60,60]},"tableRating":{"fontWeight":400,"fontSize":12,"fontFamily":"Arial","fontStyle":"normal","color":"#000000","alignment":"center","valign":"middle"},"tableData":{"fontWeight":400,"fontSize":10,"fontFamily":"Arial","fontStyle":"normal","color":"#30333A"},"tableHeader":{"bold":true,"fontSize":12,"fontFamily":"Arial","fontStyle":"normal","color":"#FFFFFF"},"headerData":{"color":"#545B67","fontWeight":400,"fontSize":10,"fontFamily":"Arial","fontStyle":"normal"},"footerRightTitle":{"bold":true,"fontSize":10,"fontFamily":"Arial","fontStyle":"normal","color":"#30333A"}},"defaultStyle":{"columnGap":20}}'

Error screenshot:
![image](https://user-images.githubusercontent.com/98396204/221654063-3f6eff9c-0424-4157-9553-3bc863419a6a.png)

Please help me ASAP.

**Comment by liborm85** [comment]
Property `"headerRows":2` is defined but only one row is in table.

**Comment by liborm85** [comment]
Fixed exception text by commit https://github.com/bpampuch/pdfmake/commit/5f8b345654ac6dc46018380a34d614a1b05a2cb1 (in master by https://github.com/bpampuch/pdfmake/commit/f514a11e6ae2dc7477d25e69de1de079ff59e78d).
