### ISSUE TITLE
how to insert image

### ISSUE THREAD

**Issue by inceptivetech** [bpampuch/pdfmake#255]
could you  please tell me about inserting image?
also for inserting image in column
i tried this:
[ {image:'mlbc-logo.png', width: 150, height: 150,}, ' 1', '2'],
but it give in result an error 'Uncaught TypeError: Cannot read property 'embed' of undefined'

Thanks in advance

**Comment by jthoenes** [comment]
are you in the browser? You need to turn your image into a data url.

**Comment by Wabbala** [comment]
A data url (mentioned by @jthoenes) can be created by turning a image to a base64 encoded string. Check out this question on [Stackoverflow](http://stackoverflow.com/questions/6150289/how-to-convert-image-into-base64-string-using-javascript)
