### ISSUE TITLE
Can't import new costum fonts in angular

### ISSUE THREAD

**Issue by hathemi** [bpampuch/pdfmake#2550]
i have generated new costum fonts using this commande 
`$ pdfmakefg ./my-fonts ./pdf/fonts/custom-fonts.js`. then i have added it in assets/fonts/
When i try to import ne costum fonts in angular component, i get this error
`import pdfFonts from '../../../assets/fonts/custom-fonts';`

> add-student.component.ts:27:22 - error TS7016: Could not find a declaration file for module '../../../assets/fonts/custom-fonts'. 'C:/Users/Asus/Desktop/students-prjt/prjct/src/assets/fonts/custom-fonts.js' implicitly has an 'any' type.

path of new costume fonts is correct.
i can't get over this error! any help please?

**Comment by liborm85** [comment]
pdfmakefg is not part of pdfmake. I don't know what is in custom-fonts.js. But `import` is standard key, file probably is not found.

**Comment by hathemi** [comment]
@liborm85  i have nothing wrong with custom-fonts.js file 

> this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = 
> {"OpenSans-Bold.ttf":"AAEAAAATAQAABAAwRFNJR5IYdDoAA1fcAAAVdEdERUYAJgOvAANTvAAAAB5HUE9TCzcPNwADU9wAAAA4R1NVQg4rPbcAA1QUAAADxk9TLzKidaEYAAABuAAAAGBjbWFwKasvaAAAELQAAAQaY3Z0IBMtGpQAAB2oAAAAqmZwZ227c6R1AAAU0AAAB+BnYXNwAAgAGwADU7AAAAAMZ2x5Zh1/yvQAACWsAAFLxGhlYWT34ccOA ................ ,"OpenSans-BoldItalic.ttf":".......+IGRqDMAkGBSsOAwIaBQCgcDAQBgorBgEEAYI3AgEMMQIwADAZBgkqhkiG9w0BCQMxDAYKKwYBBAGCNwIBBDAcBgorBgEEAYI3AgELMQ4wDAYKKwYBBAGCNwIBFTAjBgkqhkiG9w0BCQQxFgQU3eeHLMJonnPQWY+U5UK5lqHvkeswDQYJKoZIhvcNAQEBBQAEgYBxF4D8LCRUdAx8DslFo7v+elz9jXZtHmZMtQ+f8qUM28UMYlKJrV1HYipoui4xErEwkU+IM22mO7w21h7MBByEfg6qgOKMyIfr9XjxBGh8I+uus+LDGuo50t/TZM2+vANUlLF531Hqa2wkGvYOjcWJhNuhbGgUzS1FVkj6jrev4qGCAX8wggF7BgkqhkiG9w0BCQYxggFsMIIBaAIBATBnMFMxCzAJBgNVBAYTAlVTMRcwFQYDVQQKEw5WZXJpU2lnbiwgSW5jLjErMCkGA1UEAxMiVmVyaVNpZ24gVGltZSBTdGFtcGluZyBTZXJ2aWNlcyBDQQIQOCXX+vhhr570kOcmtdZa1TAJBgUrDgMCGgUAoF0wGAYJKoZIhvcNAQkDMQsGCSqGSIb3DQEHATAcBgkqhkiG9w0BCQUxDxcNMTEwNTA1MTY1NTExWjAjBgkqhkiG9w0BCQQxFgQU8YO3S7p5I8ZGkjSspXu6az77sqIwDQYJKoZIhvcNAQEBBQAEgYBQargDPDHrd71Q4uZkASVpOZ1/sFrhvQBwmyYzohcd4VpGDkqz2MbbxazxPsHx6FBPJ/ovk7bTgUGaWtSvlmTfYtE6BPU4xhf42JtwLpFA8KxhbeGqxAtKwy4AdzFvexXGtdGsgJtkicHufqkOTcUj7+OELNMNLX56CsnJ3yhQgwAA"};

**Comment by liborm85** [comment]
I tried google and found https://pjausovec.medium.com/how-to-fix-error-ts7016-could-not-find-a-declaration-file-for-module-xyz-has-an-any-type-ecab588800a8
If you use TypeScript is required .d.ts file with declaration for custom-fonts.js.

**Comment by hathemi** [comment]
i solve it by doing these steps; 
1- add allowJs: true inside tsconfig.json file

> "compilerOptions": { "allowJs": true, ...}

2- add module.export at the end of costume-font.js file

> module.exports = this.pdfMake.vfs;
