### ISSUE TITLE
How to add Thai font from google font

### ISSUE THREAD

**Issue by Ben-Mananya** [bpampuch/pdfmake#2554]
pdfMake.fonts = {
  Sarabun: {
     normal: 'https://fonts.googleapis.com/css2?family=Sarabun&display=swap',
     bold: 'https://fonts.googleapis.com/css2?family=Sarabun:wght@500&display=swap',
     italics: 'https://fonts.googleapis.com/css2?family=Sarabun:ital@1&display=swap',
     bolditalics: 'https://fonts.googleapis.com/css2?family=Sarabun:ital,wght@1,500&display=swap'
   },
   Roboto: {
     normal: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf',
     bold: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf',
     italics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf',
     bolditalics: 'https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf'
   },
  }
  
  I can't add font from google font

**Comment by liborm85** [comment]
CSS is only for style for website. Pdfmake require font file. Pdfmake supports TrueType (.ttf), OpenType (.otf), WOFF, WOFF2, TrueType Collection (.ttc), and Datafork TrueType (.dfont) font files.

**Comment by Ben-Mananya** [comment]
How I get cdnjs.cloudflare.com vfs_fonts.js for Thai font?

> CSS is only for style for website. Pdfmake require font file. Pdfmake supports TrueType (.ttf), OpenType (.otf), WOFF, WOFF2, TrueType Collection (.ttc), and Datafork TrueType (.dfont) font files.

**Comment by liborm85** [comment]
How to create vfs for custom files is described in [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/).
