### ISSUE TITLE
Table cell with barcode image breaks 

### ISSUE THREAD

**Issue by nemoeric** [bpampuch/pdfmake#2555]
I am using PDFMAKE a lot, and using table constantly 

In this project, I am trying to create a PDF layout to print labels with barcodes. 
To make sure label are fixed width, I want to use table. 

I generate a label stack : 
```javascript
let label = [
  { text: 'EAN 3701424935004' },
  {
    image: <Buffer 89 50 4e 47 0d 0a 1a 0a 00 00 00 0d 49 48 44 52 00 00 00 be 00 00 00 4b 08 06 00 00 00 ce 2b 3d 37 00 00 00 1e 74 45 58 74 53 6f 66 74 77 61 72 65 00 ... 594 more bytes>,
    fit: [ 90, 90 ]
  },
  { text: 'Ontario Grey checks' },
  { text: 'Coton upcyclé' },
  { text: 'Size L' }
]
```

And I am testing an insert into a table cell, using "stack"
```javascript 
{
  table: {
	  headerRows: 0,
	  widths: [ "*", "*", "*", "*" ],
	  body: [
		  [ 'First', 'Second', 'Third', 'The last one' ],
		  [ 
			  { 
				  stack: label,  
				  bold: true 
			  }, 
			  "Second",
			  'Third', 
			  'The last one' 
		  ],	
		  [ 
			  { 
				  stack: label,  
				  bold: true 
			  }, 
			  "Second",
			  'Third', 
			  'The last one' 
		  ],							
	  ]
  }
  }
```

For some reason, with one use of "Label", it is showing up correctly, but as soon as I use a second "label" inside any other table cell in another row, the table layout breaks.

## With one "label" object inside table 
<img width="831" alt="Capture d’écran 2023-03-20 à 18 19 48" src="https://user-images.githubusercontent.com/16577228/226418572-d79c1198-b6cb-4d00-9c9c-924c7c2d65ae.png">
## With 2  "label" objects inside table 
The layout breaks, the first barcode image is a bottom left 
<img width="831" alt="Capture d’écran 2023-03-20 à 18 23 04" src="https://user-images.githubusercontent.com/16577228/226418999-312b1981-708a-4697-a339-acfcbc765395.png">

Any one has an idea on what could be the cause of this ? 

ps: I am using `bwip-js` package for barcode generation, as mentioned by @real050280 in ticket #300

**Comment by ammulder** [comment]
I am guessing it's because you use literally the same `label` variable for both rows?  If you make a second copy of the stack for the second row then does it work?

**Comment by nemoeric** [comment]
Hey @ammulder 

Good guess but unfortunately not the issue. 
I used the same variable in my example for the sake of simplifiying my request. 

Actually I am generating different labels stored in an array 
```javascript
let labels = []
for(let prodVariant of prodVariants){
  let oneLabel = await productionParts.variants.generateLabel(prodVariant)
  labels.push(oneLabel)
}
....
content: [
{
table: {
  heights: 	[150, 10, 150],
  widths: 	[150, 10, 150, 10, 150, 10, 150],			    
  body: [
    [
      labels[0],
      {text: '', border: [false, false, false, false]},
      labels[1],
      {text: '', border: [false, false, false, false]},
      labels[2],
    ],
    [
      {text: '', colSpan: 5, border: [false, false, false, false]},
    ],
    [
      labels[2],
      {text: '', border: [false, false, false, false]},
      labels[4],
      {text: '', border: [false, false, false, false]},
      labels[5],
    ],					
  ]
}
}
```

A label item is structured this way 
```javascript
let label = {
  stack: [
    {text: `EAN ${EAN[0]}`},
    { image: barImg, fit: [90, 90] },
    { text: SP_TITLE[0] },
    { text: SP_COMPO_SHORT_NAME[0] },
    {text: `SIZE ${SIZE[0]}`},
  ]
}
```

Still showing up like this
<img width="845" alt="Capture d’écran 2023-03-23 à 10 11 45" src="https://user-images.githubusercontent.com/16577228/227156134-d5faad47-3e6a-43fa-96d7-d19fc51de286.png">


Let me know if you see anything that might explain this weird result!

**Comment by ammulder** [comment]
Now I'm really just guessing... (I was able to print 10 labels per page in a table with a barcode in each cell and it worked fine, so I know it's not that the library always fails for this -- though in my case I used a nested table inside each cell rather than a stack).  Is it possible that whatever generates the barcodes gives you a promise that for some entries hasn't resolved yet when the document is rendered?

**Comment by liborm85** [comment]
Using the function should work, example:

```js
let label = function() { return [
  { text: 'EAN 3701424935004' },
  {
    image: 'sampleImage.jpg', // sample image instead of buffer
    fit: [ 90, 90 ]
  },
  { text: 'Ontario Grey checks' },
  { text: 'Coton upcyclé' },
  { text: 'Size L' }
];
};


var dd = {
	content: [
{
  table: {
	  headerRows: 0,
	  widths: [ "*", "*", "*", "*" ],
	  body: [
		  [ 'First', 'Second', 'Third', 'The last one' ],
		  [ 
			  { 
				  stack: label(),  
				  bold: true 
			  }, 
			  "Second",
			  'Third', 
			  'The last one' 
		  ],	
		  [ 
			  { 
				  stack: label(),  
				  bold: true 
			  }, 
			  "Second",
			  'Third', 
			  'The last one' 
		  ],							
	  ]
  }
  }
	]
	
}
```
