### ISSUE TITLE
Clip to fixed size table cells

### ISSUE THREAD

**Issue by ammulder** [bpampuch/pdfmake#2556]
I am using a table to create a PDF to print to labels...  My table cells are fixed size:
```
    const tableData:ContentTable = {
      layout: 'table',
      table: {
        headerRows: 0,
        widths: [277,277],
        heights: [72*2,72*2,72*2,72*2,72*2],
        body: ...
      },
    };
...
    const tableFormat:CustomTableLayout = {
      paddingBottom: () => 0,
      paddingTop: () => 0,
      paddingLeft: column => column > 0 ? 11 : 0,
      paddingRight: column => column < 1 ? 11 : 0,
      defaultBorder: false
    };
    const pdfDocGenerator = pdfMake.createPdf(docDefinition, {table: tableFormat});
```

Sometimes the provided text for the table cell is too large, and it just overflows and overwrites the cell beneath or causes an unwanted page break.  For example, I can fit 10 lines of text the width of the cell onto the label, but there are 20 lines provided.  I want to just cut it off at the bottom border of the cell.

I know PDF has the ability to set and clear a clip rect.  Can we add a boolean flag for a table with fixed-size cells (or on the fixed-size cells themselves) to crop to the cell size, which if enabled would make the cell rendering process:
1. save the graphics state
2. set the clip rect to the rectangle of the cell
3. render the cell content
4. restore the graphics state
5. when calculating whether to add a page break, do it based on the fixed cell dimensions _not_ the dimensions of the provided text (so a lot of overflowing text in a cell near the bottom of the page won't cause a page break unless the actual fixed size cell boundaries extend past the bottom of the page)

If given some pointers on where this layout is happening, I could work on a PR for this.

**Comment by liborm85** [comment]
Not supported now, feature request here: https://github.com/bpampuch/pdfmake/issues/264
