### ISSUE TITLE
Unable to nest/ stack columns

### ISSUE THREAD

**Issue by vresetnikov** [bpampuch/pdfmake#2558]
Hello, I am trying to populate an A4 paper with stickers. Each sticker is generated as follows:

```ts
function generateLabelSticker({productId, recipient, address}: ILabelSticker): Column {
    return {
        width: 200,
        columnGap: 5,
        alignment: "justify",
        columns: [
            { qr: productId, fit: 50, version: 2, width: 50},
            {width: 150,stack: [
                    { text: recipient, fontSize: 15 },
                    { text: address, fontSize: 15 },
                ]}

        ]
    }
}
```

This produces the following:

![image](https://user-images.githubusercontent.com/54367758/226784950-7e92ab62-27d2-4785-ab78-58a8b60e3bf2.png)

In order to get more stickers I then do the following:

```ts
    const testLabelSticker = generateLabelSticker({productId: "343r3rf3rf", recipient: "Name Surname", address: "Test Street, 17, 35r35"}) //todo might need to multine address too
    const docDefinition = {
        content: [
            {
                columnGap: 10,
                columns: [
                    testLabelSticker,
                    testLabelSticker,
                    testLabelSticker
                ]
            }

        ] as Content,
        defaultStyle: {
            font: "Helvetica"
        },
        pageSize: "A4" as PageSize,
        pageMargins: [ 40, 20, 40, 60 ] as Margins,
    };
  ```

The expectation here is 3 columns, each containing the previously illustrated sticker, however all I am getting is this:

![image](https://user-images.githubusercontent.com/54367758/226785476-c90400de-3657-4054-ba97-309c2a1ca28c.png)

What is happening?

**Comment by vresetnikov** [comment]
My bad, introducing different variable names fixed the issue. 

What is the best way to populate the whole A4 paper with stickers (horizontally - vertically) ?

**Comment by ammulder** [comment]
I did it with a table instead of columns.  With a table you can specify a fixed width and height for each cell, so it's deterministic how many cells fit on the page.  I had to create and use a table format with no padding or borders, and experiment a little with the page margins, but I got my content to line up correctly with the labels on a page of labels.

(The only problem, noted in issue #2556 is that if you put too much content in the table cell, it flows into other cells or pages or etc., so you have to be careful not to overfill the cell.)

**Comment by vresetnikov** [comment]
> I did it with a table instead of columns. With a table you can specify a fixed width and height for each cell, so it's deterministic how many cells fit on the page. I had to create and use a table format with no padding or borders, and experiment a little with the page margins, but I got my content to line up correctly with the labels on a page of labels.
> 
> (The only problem, noted in issue #2556 is that if you put too much content in the table cell, it flows into other cells or pages or etc., so you have to be careful not to overfill the cell.)

Thank you for your reply. In the end I managed to get it done with columns. Since I knew how many items I wanted to have horizontally per row, I simply used a `stack[]` and I pushed into it a `Column` object with the array of needed columns / row. For every new row I pushed a new `Column` object into the `stack[]`
