### ISSUE TITLE
Generated QR codes losing resolution at certain zoom segments

### ISSUE THREAD

**Issue by vresetnikov** [bpampuch/pdfmake#2559]
Have the following in a table:

```ts
{ qr: product.productId, fit: 44, version: 2, alignment: "center", marginBottom: 5, marginTop: 5},
```

Adobe acrobat zoom level 100%:
![image](https://user-images.githubusercontent.com/54367758/226789853-6f92a020-e817-499f-9aaf-8dd7d2b486d1.png)

Chrome browser zoom level 100%:
![image](https://user-images.githubusercontent.com/54367758/226789953-9be826d4-895c-4f1e-bbdc-917ba003d3bc.png)

Firefox browser zoom level 100% (looks way better and more readable):

![image](https://user-images.githubusercontent.com/54367758/226790167-7b81cf38-16b9-47a6-958d-e75f4b30822d.png)

**_Now, what is particularly odd is that at certain zoom levels the code becomes mangled:_**

75%:
![image](https://user-images.githubusercontent.com/54367758/226790809-7a7724df-a83b-4265-96f9-5581082c79e8.png)

But then going below that it regains its quality:

58%:

![image](https://user-images.githubusercontent.com/54367758/226790709-42a5068f-a30c-4f1d-97ae-eb8274710113.png)

**Comment by liborm85** [comment]
What is wrong with it? If is zoom to small is qr mangled. This is happening on all objects in pdf documents.

**Comment by vresetnikov** [comment]
> What is wrong with it? If is zoom to small is qr mangled. This is happening on all objects in pdf documents.

The problem is not with the zoom being too small, but with it changing in resolution in different segments of the resolution. 

You can see that 58% zoom renders QR codes unmangled, whereas the higher zoom level - 75% is unreadable

**Comment by liborm85** [comment]
But how does this relate to pdf creation? I think rendering method is rather on pdf viewer.
