### ISSUE TITLE
TypeError: Cannot assign to read only property '_margin' of 22

### ISSUE THREAD

**Issue by silverwings** [bpampuch/pdfmake#256]
Hello,
in my local web server i have no problem with my script in pdfmake, but in my online server the same script return this error.

**Comment by jthoenes** [comment]
For me that sounds like a deployment issue. Please provide more details, why this should be a problem in pdfmake.

**Comment by nschleder** [comment]
I started getting this issue after updating Google Chrome to 42.0.2311.90. Here's the complete error:

```
TypeError: Cannot assign to read only property '_margin' of 846846543
    at pdfmake.min.js:28884
    at StyleContextStack.auto (pdfmake.min.js:32094)
    at DocMeasure.measureNode (pdfmake.min.js:28882)
    at DocMeasure.measureVerticalContainer (pdfmake.min.js:29033)
    at pdfmake.min.js:28889
    at StyleContextStack.auto (pdfmake.min.js:32094)
    at DocMeasure.measureNode (pdfmake.min.js:28882)
    at pdfmake.min.js:29169
    at StyleContextStack.auto (pdfmake.min.js:32094)
    at DocMeasure.measureTable (pdfmake.min.js:29138)
```

**Comment by jthoenes** [comment]
This is the same error message, but seems like a different issue to me. Could you open a separate issue and also add you document definition to it?

**Comment by mikehstrauss** [comment]
I am seeing the same issue.  I am using v0.1.17.  Its interesting because it is definitely document definition dependent as I can get other document of the same form to generate.  I am trying to isolate the delta.  I would add the definition here, but it is not small and the data must be scrubbed.

**Comment by mikehstrauss** [comment]
Interesting... I resolved the issue when I realized we were passing some numeric values (non-string) as table data.

**Comment by funkyremi** [comment]
Thanks @mikehstrauss solved the same issue by formating my numeric values to strings.

**Comment by emilioriosvz** [comment]
I have also solved the issue by formating my numeric values to strings
