### ISSUE TITLE
[feature] rewrite in typescript

### ISSUE THREAD

**Issue by StarHosea** [bpampuch/pdfmake#2561]
I love pdfmake so much, I am trying to add some feature for my , but i find some it's not easy to understand and modify the code without typescript , do we have any plan for typescirpt ?

**Comment by xDivisionByZerox** [comment]
I think some bugs could be found during the migration process as well. Unhandled edge cases on object properties for example.
While I'm a big TypeScript enthusiast as well I still have to ask.

What would be the benefit over simply extending the documentation (JSDocs)?
A lot of code already uses type declarations via JSDocs. This is enough for most IDEs/editors to complain about mismatching types and still gives the maintainer/contributer a clear enough image of what to expect. 
So why go all the way to TypeScript, require an additional build step, get frustrated over the Transpiler (in strict mode) and throw a lot of resources at something that could be achieved with an easier way?

While I think this step would benefit the project in the long run, I simply want to point out that it's not that easy to migrate an existing project as big as pdfmake without decent knowledge in both JS and TS.

**Comment by liborm85** [comment]
Version [0.3](https://github.com/bpampuch/pdfmake/issues/2375) is rewrited to ES6+.
Rewriting to typescript is not planned.
