### ISSUE TITLE
Error on empty image content

### ISSUE THREAD

**Issue by xDivisionByZerox** [bpampuch/pdfmake#2562]
## Description

When creating an image content with an "empty" value the error `Unrecognized document structure: {"image":""}` is thrown.

Is this by design?

## Expected result

I would expect pdfmake to handle "empty" image elements and default them to an empty paragraph instead.

## Alternative solution

Let the client handle the error.

## Additional information

I can provide a PR if it is desired that this error is handled in pdfmake and not on the client.

**Comment by xDivisionByZerox** [comment]
This can be reproduced by pasting the following content into the playground (pdf will not generate new):

```js
var dd = {
	content: [
		{ image: '' },
	],
}
```

**Comment by xDivisionByZerox** [comment]
Potentially related to #1772 since both are empty elements.

**Comment by liborm85** [comment]
"Empty" image doesn't exists in pdfmake. If don't want image in document do not create image node.

**Comment by liborm85** [comment]
Yes. If you define `{ image: "" }` it means image with invalid path/data of image. It would be unfortunate to silent convert it to text, because developer needs to know where have bug in creating doc definition.

**Comment by xDivisionByZerox** [comment]
May I suggest in that case extending the documentation to mention this behavior? I can propose a PR with suggestions for the documentation if that helps.

**Comment by liborm85** [comment]
Of course

**Comment by abhatta2020** [comment]
When you don't have data in your table, please try this to avoid getting an error while creating the PDF.
function buildTableBody(data) {
                 debugger;
                 var body = [];

                 if (data != null) {
                     var columns = ['writeInText', 'totalVote'];
                     body.push(columns);
                     data.forEach(function (row) {
                         var dataRow = [];

                         columns.forEach(function (column) {
                             debugger;
                             dataRow.push(row[column].toString());
                         })
                         // for (var j = 0; j < 3; j++) {
                         //   debugger;
                         //    dataRow.push(row.toString());
                         //  }
                         body.push(dataRow);
                     });
                   
                 }
                 else {
                     body.push("");
                 }
                 return body;

             }

And here is the code where I call this function:
var  data = 
                                             [
                                               { text: msg.d["Name"], fontSize: 14, margin: [0, 0, 0, 8] },
                                                         
                                               {
                                                    table:
                                                        {
                                                        widths: ["60%", "20%", "20%"],
                                                        body: buildTableBody(msg.d["StatusArrary"])
                                                    },
                                                    layout:
                                                    {
                                                        defaultBorder: false,
                                                        fillColor: function (rowIndex, node, columnIndex)
                                                        {
                                                            return (rowIndex % 2 === 0) ? '#dfe0e0' : null;
                                                        }
                                                    }
                                               },
                                               {
                                                   canvas: [
                                                       { type: 'line', x1: 0, y1: 5, x2: 595 - 2 * 40, y2: 5, lineWidth: 3 }
                                                   ]
                                               },
                                               {
                                                     table:
                                                     {
                                                         widths: ["60%", "20%", "20%"],
                                                         body: buildTableBody(msg.d["SomeArray"])
                                                     },
                                                     layout:
                                                     {
                                                         defaultBorder: false,
                                                         fillColor: function (rowIndex, node, columnIndex) {
                                                             return (rowIndex % 2 === 0) ? '#dfe0e0' : null;
                                                         }
                                                     }
                                               }
                                             ]
