### ISSUE TITLE
Maybe there is something wrong to draw the table border line when the stack content separate into two pages.

### ISSUE THREAD

**Issue by OukaWang** [bpampuch/pdfmake#2565]
I used pdfmake to draw the table at the server side. The table format likes below:
![pdfmake_issue_1](https://user-images.githubusercontent.com/8477153/229663450-9fde5278-f066-4dbd-9088-4ba6cc5a14cf.jpg)

Unfortunately, there is something wrong to draw the table horizontal line and the table vertical line when the second stack value separate into two pages.

See the attachment image above, there are two line of content in the page 20, the others of content are in the page 21. The content calculates the 'pageNumber' like below:
![pdfmake_issue_2](https://user-images.githubusercontent.com/8477153/229663607-7a77cf2c-4a2f-4821-9528-f1a7a13c8899.jpg)

Because of the second stack content separate into different page, there are two records need to generate in the page 21. But the below columns also need to generate in the page 20.

If a table has this case, the border of the table will draw abnormal.

Could you tell me how fix this issue or avoid this one?

**Comment by ana-jovanovic** [comment]
Hi,

I'm sorry I'm bumping in with another subject, but I've noticed something in your PDF example that doesn't work in mine. I see you have a rowSpan for the first column which is also filled with color. May I ask you how did you manage for the split column's border not to be seen? I get a tiny white line after doing a rowSpan and adding a fillingColor property to the same cell (there's an image here: **https://github.com/bpampuch/pdfmake/issues/2567**)

Thanks,
Ana

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/371 https://github.com/bpampuch/pdfmake/issues/2270
