### ISSUE TITLE
border affects table cell width even when defaultBorder: false 

### ISSUE THREAD

**Issue by calioptrix** [bpampuch/pdfmake#2566]
I have two tables - one in the header function to act as column headings, and the other in the document content. Both are passed the same array of column widths. 

The heading table has

` layout: {defaultBorder: false}
`
the body table has 
```
layout:
{
  vLineWidth: function (i, node)
  {
    return 0;
  }
}

```

The columns in the heading table are slightly wider than the body table. Setting a fillColor for the cells make the difference more obvious.

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
