### ISSUE TITLE
Filling row with fillColor option and adding a rowSpan still shows me white lines in the table row

### ISSUE THREAD

**Issue by ana-jovanovic** [bpampuch/pdfmake#2567]
Hi,

I have the following issue: I add a table that has, let's say, 9 rows, and this is what my first column in the first row looks like:
{
  svg: `some svg here`,
  rowSpan: 9,
  fillColor: 'gray',
}
In the next 9 rows, the first column looks like this: {} (just an empty column)

The problem I encounter is that after every row I can see a tiny white border which I want to remove. I tried removing width of the horizontal lines, tried changing the border color so it's the same as fillColor mentioned above, etc. but nothing helped.

Does anyone has an idea how to solve this issue?

P.S. SVG doesn't take the whole height of the first column, only 3/9 of it.

![Screenshot 2023-04-05 at 11 33 44](https://user-images.githubusercontent.com/24357190/230042103-1433c374-1a0d-4fd1-a24a-5f3b6aa009a8.png)

**Comment by ana-jovanovic** [comment]
Hi @OukaWang,

No problem at all! Thank you for answering me, I just have to ask you to explain me what the "stack" schema is.

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
