### ISSUE TITLE
How to add other language (Hindi) ?

### ISSUE THREAD

**Issue by its-ratikant** [bpampuch/pdfmake#2568]
Hi, thanks for the great library!
I am looking to add Hindi words in my PDF, but it does not render properly. Do I have to add any font for that specific Hindi words? If so how? can you please give me an example?

**Comment by liborm85** [comment]
Adding custom fonts is described in [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/).
pdfmake use [pdfkit](https://github.com/foliojs/pdfkit) library for creating pdf documents, according to issue https://github.com/foliojs/pdfkit/issues/1140#issuecomment-665281117 it works.

**Comment by its-ratikant** [comment]
How to do this in server side?

**Comment by liborm85** [comment]
That's even easier, only define local font files, see example: [basics.js](https://github.com/bpampuch/pdfmake/blob/0.2.7/examples/basics.js#L2-L7)
