### ISSUE TITLE
Pdf is not generating images 

### ISSUE THREAD

**Issue by mca-binita** [bpampuch/pdfmake#2569]
Hello,
PFA content object in the file.
I have generated this content object with the help of htmlToPdfmake.
I cannot find out why the image in the question part is not generating.  Project code has not been changed for awhile and the very same code was working correctly till before some time.
Please help me to figure out the issue.

[no-image-printing.txt](https://github.com/bpampuch/pdfmake/files/11198753/no-image-printing.txt)

Please note,
Project framework: Angular 9.0
"dependencies": {
    "@angular/animations": "~9.1.0",
    "@angular/cdk": "^9.2.0",
    "@angular/common": "~9.1.0",
    "@angular/compiler": "~9.1.0",
    "@angular/core": "~9.1.0",
    "@angular/flex-layout": "^9.0.0-beta.29",
    "@angular/forms": "~9.1.0",
    "@angular/material": "^9.2.0",
    "@angular/material-moment-adapter": "^11.0.2",
    "@angular/platform-browser": "~9.1.0",
    "@angular/platform-browser-dynamic": "~9.1.0",
    "@angular/router": "~9.1.0",
    "@angular/service-worker": "^9.1.13",
    "@auth0/angular-jwt": "^5.0.2",  
    "html-to-pdfmake": "^2.1.5",
    "jsonpath": "^1.1.1",
    "jszip": "^3.5.0",
    "jwt-decode": "^3.1.2",
    "moment": "^2.29.1",
    "ng-connection-service": "^1.0.4",
    "ngx-countdown": "^10.0.1",
    "ngx-image-compress": "^8.0.4",
    "ngx-image-cropper": "^3.2.1",
    "ngx-lightbox": "^2.2.2",
    "pdfmake": "^0.1.70",
    "rxjs": "~6.5.4",
    "tslib": "^1.10.0",
    "xlsx": "^0.17.0",
    "zone.js": "~0.10.2"
  },
  "devDependencies": {
    "@angular-devkit/build-angular": "~0.901.0",
    "@angular/cli": "^9.1.0",
    "@angular/compiler-cli": "~9.1.0",
    "@angular/language-service": "~9.1.0",
    "@types/jasmine": "~3.5.0",
    "@types/jasminewd2": "~2.0.3",
    "@types/jsonpath": "^0.2.0",
    "@types/node": "^12.11.1",
    "codelyzer": "^5.1.2",
    "jasmine-core": "~3.5.0",
    "jasmine-spec-reporter": "~4.2.1",
    "karma": "~4.4.1",
    "karma-chrome-launcher": "~3.1.0",
    "karma-coverage-istanbul-reporter": "~2.1.0",
    "karma-jasmine": "~3.0.1",
    "karma-jasmine-html-reporter": "^1.4.2",
    "protractor": "~5.4.3",
    "ts-node": "~8.3.0",
    "tslint": "~6.1.0",
    "typescript": "~3.8.3"
  }
I am hoping for quick help as we are looking at the production deadline and this issue is creating a major impact.

regards,
Binita

**Comment by liborm85** [comment]
Image node is in text node and that's wrong. Image must be outside text node.
