### ISSUE TITLE
Problem with custom font

### ISSUE THREAD

**Issue by nicolacardi** [bpampuch/pdfmake#2576]
I have an angular project
I have installed pdfMake
It generates my pdf. Everything seems ok.
Now I want to install a new font and use it. Then I followed instructions: I placed my font (TitilliumWeb) in its different aspects (Regular, bold, italics, bolditalics) in example/fonts folder and launched 

node build-vfs.js "./examples/fonts"
OK, it creates a vfs_fonts.js file like:

```
this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {
  "TitilliumWeb-Black.ttf": "AAEAAAAPAIAAAwBwR0RFRgARAZoAAAEMAAAAFkdQT1NDfEofAAAcQAAAGZpHU1VCJ8AW5wAAAgAAAAGOT1MvMmvJguUAAAGgAAAAYGNtYXAorzP2AAADkAAAAaRnYXNwAAAAEAAAAQQAAAAIZ2x5Zms0XgkAADXcAAB0smhlYWQEdslgAAABaAAAAD...etc...
```
Now it was time to import it  then I included 
```
const pdfFonts = require("pdfmake/build/vfs_fonts");
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```
Now I got the problem.
First of all if I console.log
`    console.log("pdfFonts.pdfMake.vfs:", pdfFonts.pdfMake.vfs); `
it shows me Roboto and not Titillium (where the hell takes it from is a mistery for me)
But the main point is that when I write

```
    pdfMake.fonts = {
      TitilliumWeb: {
        normal: 'TitilliumWeb-Regular.ttf',
        bold: 'TitilliumWeb-Bold.ttf',
        italics: 'TitilliumWeb-Italic.ttf',
        bolditalics: 'TitilliumWeb-BoldItalic.ttf'
      }
    };
```

this stops the pdf generation.

Infact it arrives to
`    pdfMake.createPdf(docDefinition).download();
`
but there it doesn't do anything and does not throw any error
I have spent ONE WEEK so far on this without finding out any answer or doing any progress.
Any help to try to figure out what is wrong with my procedure is appreciated

**Comment by Deibi12** [comment]
same here, any solution?

**Comment by Jackyyans** [comment]
For reference:
![image](https://user-images.githubusercontent.com/37462017/236780817-95f2f567-448f-45a0-b383-70b59185a628.png)
![image](https://user-images.githubusercontent.com/37462017/236781242-03a38a06-cbb1-4566-b53f-d785426ff745.png)

**Comment by Kimser** [comment]
Worship the boss

**Comment by Kimser** [comment]
> 以供参考： ![图像](https://user-images.githubusercontent.com/37462017/236780817-95f2f567-448f-45a0-b383-70b59185a628.png) ![图像](https://user-images.githubusercontent.com/37462017/236781242-03a38a06-cbb1-4566-b53f-d785426ff745.png)
How do you define multiple fonts that are used in different languages

**Comment by 12michel34** [comment]
same problem here, any solution? I use Angular V17

**Comment by liborm85** [comment]
Frameworks use cache for `node_modules` and these changes will not be reflected. Use custom folder is recommended. 
Information added to documentation [here](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/).
