### ISSUE TITLE
word-wrap module used indirectly by pdfmake has a security vulnerability, and no fix is available

### ISSUE THREAD

**Issue by andreidiaconescu** [bpampuch/pdfmake#2579]
- word-wrap module used indirectly by pdfmake has a security vulnerability, and no fix is available according to: https://security.snyk.io/vuln/SNYK-JS-WORDWRAP-3149973
 - how pdfmake references work-wrap:

> npm ls word-wrap
> someapp@0.0.1 /home/andrei/client
> └─┬ pdfmake@0.2.7
>   └─┬ @foliojs-fork/linebreak@1.1.1
>     └─┬ brfs@2.0.2
>       └─┬ static-module@3.0.4
>         └─┬ escodegen@1.14.3
>           └─┬ optionator@0.8.3
>             └── word-wrap@1.2.3
> 

 - what could we do to avoid this problem ?

**Comment by andreidiaconescu** [comment]
i found a fix here: https://github.com/jonschlinkert/word-wrap/issues/32

**Comment by TanushreeB2611** [comment]
[andreidiaconescu](https://github.com/andreidiaconescu): Can you help me with the fix ? I am blocked due to the same issue

**Comment by liborm85** [comment]
Fixed in version 0.2.10.
