### ISSUE TITLE
where document will be stored when using download on device or simulator

### ISSUE THREAD

**Issue by inceptivetech** [bpampuch/pdfmake#258]
Hello,
Could you please let me know where pdf will be downloaded on device or emulator, can we configure path inside app, if yes how. If no which plugin to use for downloading file inside app.

Regards,
Suhas

**Comment by jthoenes** [comment]
I don't know. Depends on your device or emulator - I would google for default pdf locations. We don't set one in pdfmake.

**Comment by inceptivetech** [comment]
sorry, however I want donwload generated pdf in my app's file system on iPad. please let me know if this is possible if yes how

Regards,
Suhas

**Comment by jthoenes** [comment]
Can you describe your usage scenario more concrete?

**Comment by inceptivetech** [comment]
I want to create pdf file dynamically and then store this in filesystem for future usuage.
Using pdfmake I was able to create pdf perfectly, however I really dont know how to save this file in filesystem. I am using phonegap cordova.

Regards,
Suhas

**Comment by jthoenes** [comment]
There is a ``download`` method available on pdfmake. If that doesn't work, please open an issue with details what is wrong.

**Comment by inceptivetech** [comment]
thank you for this, however this is really my question I have used download however on simulator it is opening pdf rather than downloading. Can I specify parameters for download location like 
download('/documents')

Regards,
Suhas

**Comment by jthoenes** [comment]
Unfortunately you cannot. FileSaver.js does not support this - and I'm even unsure we can provide this functionality in a browser at all. You can specify a default file name if you want.
