### ISSUE TITLE
Subsequent table instances show empty header rows

### ISSUE THREAD

**Issue by RBJRBJ** [bpampuch/pdfmake#2581]
In a large document a set of tables does not show the header content except for the first instance of the same table.
The same pdf table content in a small document does not suffer from the problem.
See the screenshot. The red squares hilite the header rows without data.
![pdfmake-table-header-problem](https://user-images.githubusercontent.com/32237919/236163303-bbd987a1-4a87-42de-922f-49e1b8b74f55.png)

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
