### ISSUE TITLE
Table/Column Layout

### ISSUE THREAD

**Issue by gopaljangid123** [bpampuch/pdfmake#2583]
Hi,

I want print particular data in the attached format.
I want to divide the page in half, and the use the first half to start printing the content. When the page comes to an end, the next nodes(data) should be printed in the second half of the first page itself. 
Is it possible? If yes, can anyone guide me?

![image](https://user-images.githubusercontent.com/38186980/237045219-026c10b5-f53e-46ee-86bb-894b336fe2b0.png)

**Comment by liborm85** [comment]
Not supported now. Feature request is here: https://github.com/bpampuch/pdfmake/issues/604
