### ISSUE TITLE
rowspan and pagination issues

### ISSUE THREAD

**Issue by zmlu** [bpampuch/pdfmake#2584]
When using rowspan to merge cells, if the table spans pages, the merged cells on the second page do not display content. Is there a way to display the content? 

![image](https://github.com/bpampuch/pdfmake/assets/16974046/cdb803a8-3fd2-4c4a-8ce1-224e892274fe)

Displaying red words is the effect I want.

![image](https://github.com/bpampuch/pdfmake/assets/16974046/6608685e-df59-4ff6-8c82-78bcd0f3845e)

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.

**Comment by htwins019** [comment]
Whether the overflow content of the previous page appears on the second row of the next page after pagination occurs

**Comment by htwins019** [comment]
译文：

I have such a problem do not know how to solve

**Comment by htwins019** [comment]
I have such a problem do not know how to solve

**Comment by liborm85** [comment]
This is expected behavior. rowSpan = 2 cause that cell is on 2 rows with content from this row.

**Comment by rifaldi34** [comment]
can this still be fixed please ?
![image](https://github.com/user-attachments/assets/fba65600-a58e-4227-8d82-53b5a843de42)
https://pastebin.com/raw/uyvbpkpf

**Comment by Vimalraj777** [comment]
@liborm85 will this issue be resolved?
