### ISSUE TITLE
Cannot assign to 'vfs' because it is a read-only property

### ISSUE THREAD

**Issue by muhammadahmad5149** [bpampuch/pdfmake#2588]
I am using this library with nest js. It works fine with node js but when want to use it with type script or nest js it shows this error. 
pdfMake.vfs = pdfFonts.pdfMake.vfs;

**Comment by dgtllion** [comment]
Nest.js is server side. Server side has another way of implementing fonts. You are trying the frontend way

**Comment by muhammadahmad5149** [comment]
> 

It is working fine with Node JS. Node JS is also also a server-side framework. This issue is not due to server-side this is due to typescript.

**Comment by davidstackio** [comment]
I'm running into this too with Typescript and Nuxt 3 (with `ssr: false`).

Related issue: https://github.com/bpampuch/pdfmake/issues/1877

**Comment by shaheedac** [comment]
(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;

**Comment by liborm85** [comment]
Resolved see https://github.com/bpampuch/pdfmake/issues/2654#issuecomment-2452944236.
