### ISSUE TITLE
Uncaught (in promise) File 'msyh.ttc' not found in virtual file system

### ISSUE THREAD

**Issue by skiinaurora** [bpampuch/pdfmake#2589]
this error happend when I use a new font file. my project is React and my codes is:
```js
import React from "react";
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from 'pdfmake/build/vfs_fonts';

pdfMake.vfs = pdfFonts.pdfMake.vfs;
pdfMake.fonts = {
  Msyh: {
    normal: "msyh.ttc",
    bold: "msyhbd.ttc",
    italics: "msyhl.ttc",
  },
};
type PdfPropsType = {};
const PdfMake: React.FC<PdfPropsType> = (props) => {
  const docDefinition = {
    content: ['hello world! pdf测试'],
    defaultStyle: { font: 'Msyh' }
  };
  function downLoadPdf() {
    pdfMake.createPdf(docDefinition).download("文件名", () => {
      console.log("complete");
    });
  }
  return (
    <div onClick={() => downLoadPdf()} style={{ color: '#fff' }}>
      下载pdf
    </div>
  )
}
```

export default PdfMake;`
and my font file in node_modules is:
![1](https://github.com/bpampuch/pdfmake/assets/105364939/d637e41d-5b8e-435e-b7b1-258a6bd83420)

I make sure i have run 'node build-vfs.js "./examples/fonts"' in pdfmake folder.

Thanks for answer my question

**Comment by liborm85** [comment]
Frameworks use cache for `node_modules` and these changes will not be reflected. Use custom folder is recommended. 
Information added to documentation [here](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/).
