### ISSUE TITLE
Problem with german capital ß (ẞ)

### ISSUE THREAD

**Issue by K4ugummi** [bpampuch/pdfmake#2593]
There is a problem with the pdf generation when a german capital "ß" is used.

Zeichen | UnicodePosition | UnicodeBezeichnung | Bezeichnung | HTMLdezimal
-- | -- | -- | -- | --
ẞ | U+1E9E | LATIN CAPITAL LETTER SHARP S | Lateinischer Großbuchstabe scharfes S | &#7838;

Steps to reproduce:

1. Open the pdfmake playground on 
http://pdfmake.org/playground.html

2. Copy and paste the below content to the playground.

3. Check the capital `ß` -> `ẞ`, those are different characters.
The ẞ is displayed as a rectangle. 

```
var dd = {
    content: [
            'ASCII-1:  A B C D E F G H I J K L M N O P Q R S T U V W X Y Z',
            'ASCII-2:  a b c d e f g h i j k l m n o p q r s t u v w x y z',
            'ASCII-3:  0 1 2 3 4 5 6 7 8 9',
            'ASCII-4:  . , : ; - _ ! ? / " \' ` ^ ~ * + = \\ | # $ @ % & ( ) < > [ ] { }',
            'German:  Ä Ö Ü ä ö ü ß ẞ',
            'Czech-1:  Á Č Ď É Ě Í Ň Ó Ř Š Ť Ú Ů Ý Ž',
            'Czech-2:  á č ď é ě í ň ó ř š ť ú ů ý ž',
            'Romanian-1:  Ă Â Î Ş Ţ',
            'Romanian-2:  ă â î ş ţ',
            'Slovenian-1:  Č Š Ž',
            'Slovenian-1:  č š ž',
            'Slowak-1:  Á Ä Č Ď É Í Ľ Ĺ Ň Ó Ô Ŕ Š Ť Ú Ý Ž',
            'Slowak-2:  á ä č ď é í ľ ĺ ň ó ô ŕ š ť ú ý ž',
            'Special:  § ´ ² ³ ° µ €',
            'Greek: Α α, Β β, Γ γ, Δ δ, Ε ε, Ζ ζ, Η η, Θ θ, Ι ι, Κ κ, Λ λ, Μ μ, Ν ν, Ξ ξ, Ο ο, Π π, Ρ ρ, Σ σ/ς, Τ τ, Υ υ, Φ φ, Χ χ, Ψ ψ, Ω ω.',
    ]
}
```

![image](https://github.com/bpampuch/pdfmake/assets/16589843/52cd2d29-ea88-40b8-8d8f-54c7fb9a835e)

**Comment by liborm85** [comment]
On playground is used Roboto font. How it looks this font doesn't suport this character, use a different font (described in [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/)).
