### ISSUE TITLE
Font thin style is not supported

### ISSUE THREAD

**Issue by EranKT** [bpampuch/pdfmake#2597]
I am trying to find a way to use Roboto thin in the pdfMake but couldn't find any way to do it except of drawing it on a canvas and adding to the pdf as an image.

In the documentations I see support only for 
normal,
bold,
italics,
bolditalics,

Is there an easier way to do it?

**Comment by liborm85** [comment]
You can use any font, how to use custom fonts is described in [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/vfs/).
