### ISSUE TITLE
 WARN  deprecated sourcemap-codec@1.4.8: Please use @jridgewell/sourcemap-codec instead

### ISSUE THREAD

**Issue by boldurean** [bpampuch/pdfmake#2598]
<img width="341" alt="Screenshot 2023-07-02 at 13 09 41" src="https://github.com/bpampuch/pdfmake/assets/64642760/dd3d2835-9674-4f6e-9b00-b2d3d3216180">

magic-string is already using @jridgewell's source map

Can we update this deps?

**Comment by liborm85** [comment]
No, it is part of brfs package.
