### ISSUE TITLE
how to reduce file size especially on many images in content?

### ISSUE THREAD

**Issue by AsasinCree** [bpampuch/pdfmake#2599]
version 0.2.7

I have around 400 images and 1~4M size per image in content. That leads to large file size, how can I reduce file size **on the whole** or **compress** the image by some **settings**?

I can't compress the image as these images are load from **url**

**Comment by liborm85** [comment]
You can download images from urls a convert using some other library to a smaller size and then use in pdfmake.

**Comment by boustanihani** [comment]
@AsasinCree did you find a suitable library for solving this?

@liborm85 this would be a nice to have built in feature, maybe when version 3.0 is released?

**Comment by liborm85** [comment]
pdfmake is not a library that should handle image format conversion, it is out of scope. Use other library that allows this according to your needs.

**Comment by AsasinCree** [comment]
> @AsasinCree did you find a suitable library for solving this?
> 
> @liborm85 this would be a nice to have built in feature, maybe when version 3.0 is released?

What liborm85 said is right but it"ll be nice to have the feature inside it.

@boustanihani Btw, you can try to use [jsPDF](https://raw.githack.com/MrRio/jsPDF/master/docs/jsPDF.html)  instead. 
It has a global compress config option `var doc = new jsPDF({compress: true});` or use lower quality like `var doc = new jsPDF('p', 'mm', 'a4', true);`.
And you can also have the compress option in its image [api](https://raw.githack.com/MrRio/jsPDF/master/docs/module-addImage.html) while you adding an image like `pdf.addImage(png, 'PNG', leftmargin, 120, 485, 270,'','FAST');`(The last param "FAST" is the compress value)

But, jsPDF doesn't support url image. If you're in my situation. You need to convert it to base64 first(You could easily find it on stackoverflow) or use [html2canvas](https://html2canvas.hertzen.com/) to achive it.

**Comment by boustanihani** [comment]
@AsasinCree Thank you!

I ended up using this code for resizing my images:

```
function resizeImage(img) { // HTMLImageElement
    
    // Source: https://imagekit.io/blog/how-to-resize-image-in-javascript/

    var maxSize = 600; // Width or Height

    var width = img.naturalWidth;
    var height = img.naturalHeight;

    if (width > height) {
        if (width > maxSize) {
            height = height * (maxSize / width);
            width = maxSize;
        }
    } else {
        if (height > maxSize) {
            width = width * (maxSize / height);
            height = maxSize;
        }
    }

    var canvas = document.createElement("canvas");
    canvas.width = width;
    canvas.height = height;
    var ctx = canvas.getContext("2d");
    ctx.drawImage(img, 0, 0, width, height);

    return canvas.toDataURL('image/jpeg', 0.85);
}
```

**Comment by AsasinCree** [comment]
> @AsasinCree Thank you!
> 
> I ended up using this code for resizing my images:
> 
> ```
> function resizeImage(img) { // HTMLImageElement
>     
>     // Source: https://imagekit.io/blog/how-to-resize-image-in-javascript/
> 
>     var maxSize = 600; // Width or Height
> 
>     var width = img.naturalWidth;
>     var height = img.naturalHeight;
> 
>     if (width > height) {
>         if (width > maxSize) {
>             height = height * (maxSize / width);
>             width = maxSize;
>         }
>     } else {
>         if (height > maxSize) {
>             width = width * (maxSize / height);
>             height = maxSize;
>         }
>     }
> 
>     var canvas = document.createElement("canvas");
>     canvas.width = width;
>     canvas.height = height;
>     var ctx = canvas.getContext("2d");
>     ctx.drawImage(img, 0, 0, width, height);
> 
>     return canvas.toDataURL('image/jpeg', 0.85);
> }
> ```

Good for you! It's a nice solution. And I found your solution is similar to [html2canvas](https://html2canvas.hertzen.com/) that key point is the second param in `toDataURL` which indicate the image quality.
