### ISSUE TITLE
Float image a side text

### ISSUE THREAD

**Issue by mawi5** [bpampuch/pdfmake#26]
Hello bpampuch, I'm using pdfmake and it's terrific, but I have a trouble, how could I put an image a side a text? (like in the image attached).

Thank you for your help.

![g3107](https://cloud.githubusercontent.com/assets/1425361/2992197/d3e5e93c-dc8b-11e3-8371-59eb92dcde37.png)

**Comment by Shakeel77** [comment]
good one

**Comment by niklsss** [comment]
@bpampuch If you put this in the header block, then the styles do not work, how do I fix it?
