### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'text')     at htmlToPdfMake

### ISSUE THREAD

**Issue by sanahabibi00** [bpampuch/pdfmake#2600]
I HAVE  HTML , WHEN I TRY TO USE
 HTMLTOPDFMAKE   ---var  htmlContent= htmlToPdfmake(html)
 THIS THROWS ERROR as connot read properties of undefined reading text null

**Comment by liborm85** [comment]
Ask on htmlToPdfmake package support.
