### ISSUE TITLE
Cannot create property 'version' for the string error

### ISSUE THREAD

**Issue by vedamtamssp** [bpampuch/pdfmake#2601]
The error below is when calling createPdfKitDocument inside a Lambda function. 
When I use the same string in the pdfmake playground, it renders the page correctly. 
May I know how to fix the syntax (?) error ?

pdfmake version, 0.2.7
nodejs 18

TypeError: Cannot create property 'version' on string '{ content: [ { text: 'Heading For test', style: 'header', alignment: 'center' }, { text: 'Second heading for test', style: 'header', alignment: 'center'  } ],  style: { header: { bold: true, font: 'Helvetica' } } };'

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.
