### ISSUE TITLE
Right-hand side of 'instanceof' is not callable

### ISSUE THREAD

**Issue by Pavel064** [bpampuch/pdfmake#2607]
Good afternoon
In my application, I use the pdfMake library to create a PDF document and the epub-gen-memory library.

I am getting error: "pdfmake.js:5332 Uncaught (in promise) TypeError: Right-hand side of 'instanceof' is not callable"

Apparently, this is due to the fact that both libraries use browser memory and there are conflicts that break pdfMake.

here is the link to the app:
https://github.com/texttree/obs-format-convert-rcl/tree/develop

**Comment by liborm85** [comment]
Description how to simulate problem is not available.
