### ISSUE TITLE
make PDF with 58mm paper receipt roll width

### ISSUE THREAD

**Issue by 22fey** [bpampuch/pdfmake#2609]
Is it possible to set paper width to 58mm with auto height for receipt roll paper to make pdf with **pdfmake**  ? somehow im trying to set the width to **2.28346** and height to **auto** and it work, but the letter is truncate, and if im trying to resize the letter to 1pt the letter fit the paper BUT the letter goes something like this :
L
E
T
T
E
R

**Comment by liborm85** [comment]
It works as expected, example:
```js
var dd = {
    pageSize: {
        width: 164,
        height: 'auto'
    },
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```
