### ISSUE TITLE
Highlighted incorrect text in search function in  iOS 17 beta 4

### ISSUE THREAD

**Issue by violetchow2023** [bpampuch/pdfmake#2611]
In iOS 17 beta 4,  the search highlighter highlighted incorrect text in the PDF which generated by pdfMake 

Steps to reproduce
Step 1: Download the pdf from pdfmake playground > tables > download (attached in the post 'sample.pdf')
Step 2: Open the downloaded pdf in iPad OS 17 beta 4 device using [Files] app
Step 3:  Search "rowSpan"

Expected result: Highlighted all "rowSpan" 
Actual result: In some of the result, highlighted non "rowSpan" 

![IMG_0692](https://github.com/bpampuch/pdfmake/assets/141154888/1e1a3d38-5f59-49b2-b12a-d5614cded1a9)
[sample.pdf](https://github.com/bpampuch/pdfmake/files/12230149/sample.pdf)

**Comment by liborm85** [comment]
Pdfmake is not pdf viewer. Bug is probably in iOS pdf viewer.
