### ISSUE TITLE
Text alignment inside a table cell

### ISSUE THREAD

**Issue by vresetnikov** [bpampuch/pdfmake#2620]
Hello, what is the correct way of aligning 2 text elements inside a table cell? 

I have the following code:

```ts
     table: {
            widths: ["*", "*"],
            body: [
                [{
                    text: [
                        { text: 'DATA ', fontSize: 7, alignment: "left" },
                        { text: `${creationDate}`, fontSize: 12, alignment: "right"}
                    ]
                }
            ]
        }
```

And the following comes out:

![image](https://github.com/bpampuch/pdfmake/assets/54367758/fd9eb1ba-b30d-4025-ad34-63e5cf69e250)

The desired outcome is to have the actual date to move to the far right side of the cell. Is this possible?

**Comment by biggs50** [comment]
You can use columns to get the desired outcome

```
table: {
          widths: ['*'],
          body: [
		         [
		              {
                                   columns: [
                                         { text: 'DATA ', fontSize: 7, alignment: "left"},
                                         { text: '2023-08-28', fontSize: 12, alignment: "right"}
                                   ]
                             }
                         ],
                          [
		              {
                                   columns: [
                                         { text: 'DATA ', fontSize: 7, alignment: "left"},
                                         { text: '2023-08-29', fontSize: 12, alignment: "right"}
                                   ]
                             }
                         ]
                   ]
 }

```

**Comment by vresetnikov** [comment]
> You can use columns to get the desired outcome
> 
> ```
> table: {
>           widths: ['*'],
>           body: [
> 		         [
> 		              {
>                                    columns: [
>                                          { text: 'DATA ', fontSize: 7, alignment: "left"},
>                                          { text: '2023-08-28', fontSize: 12, alignment: "right"}
>                                    ]
>                              }
>                          ],
>                           [
> 		              {
>                                    columns: [
>                                          { text: 'DATA ', fontSize: 7, alignment: "left"},
>                                          { text: '2023-08-29', fontSize: 12, alignment: "right"}
>                                    ]
>                              }
>                          ]
>                    ]
>  }
> ```

Thank you very much!
