### ISSUE TITLE
Security vulnerability noticed in word-wrap 1.2.3 

### ISSUE THREAD

**Issue by Ganeshdr** [bpampuch/pdfmake#2623]
word-wrap 1.2.3 package which is used in the path brfs/2.0.2 -> static-module/3.0.4 -> escodegen/1.14.3 -> optionator/0.8.3. In npm, I can latest word-wrap package version available is 1.2.5 which has no security vulnerabilities reported. request you to upgrade the version for this package.

**Comment by TanushreeB2611** [comment]
[vadimka123](https://github.com/vadimka123):  We are blocked due to the same security vulnerability issue. The word-wrap 1.2.3, is not a direct dependency of our app, it is indirectly imported by pdf-make. We are already on the latest version of pdf-make: 0.2.7. Can you advise what needs to be done to resolve this?

**Comment by vadimka123** [comment]
@TanushreeB2611 , original foliojs packages looks like didn’t affected and not using brfs

**Comment by TanushreeB2611** [comment]
[vadimka123](https://github.com/vadimka123): Did not get you ? What is brfs ? And what step can I take to resolve this issue ?

**Comment by vadimka123** [comment]
@TanushreeB2611 Just wait steps to solve from pdf-kit side 
Switching from forks back in this package looks like should help, but this should be done by pdf-kit devs

**Comment by TanushreeB2611** [comment]
@vadimka123: I tried creating a fork and merging the open PR to it and referring it in our package.json. It still did not fix the issue as brfs is till present as a devDependency.

**Comment by learntolive2** [comment]
Any ETA when this issue will be addressed?

**Comment by vadimka123** [comment]
I think it's already fixed 
Yesterday I updated node modules and noticed that line-break (fork) was updated and no any brfs dependency 
pdfmake already pointing to this version of line-break fork 
So looks good for me

**Comment by liborm85** [comment]
Fixed in version 0.2.10.

**Comment by learntolive2** [comment]
Thank you @vadimka123 and @liborm85 for quick response.
