### ISSUE TITLE
Issue with displaying the Icon and the Heading side by side

### ISSUE THREAD

**Issue by harithaped** [bpampuch/pdfmake#2626]
``
<div className="main">
<> 
<h1>
<SomeIcon />//Icon
<span>HeadingText </span>
</h1>
<ol> 
<li>
 <p >Text</p>
 <p>value</p>
</li>
</ol>
</>

<> 
<h1>
<SomeIcon />//SecondIcon
<span>Second block </span>
</h1>
<ol> 
<li>
 <p >Second Text</p>
 <p>Second Value</p>
</li>
</ol>
</>
</div>
``
I need to display the icon and heading text side by side in the header.  For converting the html code to pdf I'm using html-to-pdf and then that code I'm passing as a content to in the docDefinition of the pdfMake. I tired applying many styles but I'm unable to display the icon and the heading side by side. Can any one provide me any inputs on how to achieve this?(The html code is dynamic. ) @darrinholst @bmihelac @jthoenes

**Comment by liborm85** [comment]
Not supported now, as workaround you can use table:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					['//Icon', 'HeadingText'],
				]
			},
			layout: 'noBorders'
		}
	]
}
```

Feature request: https://github.com/bpampuch/pdfmake/issues/358
