### ISSUE TITLE
set vfs of pdfMake in esbuils angular 16

### ISSUE THREAD

**Issue by ahmed-a-ibrahim** [bpampuch/pdfmake#2628]
import * as pdfMake from 'pdfmake/build/pdfmake';
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

(pdfMake as any).vfs = pdfFonts.pdfMake.vfs;

 [ERROR] Cannot assign to import "vfs"

    libs/table/src/lib/table/pdfExport/printDoc.ts:3:8:
      3 │ pdfMake.vfs = pdfFonts.pdfMake.vfs;
        ╵         ~~~

  Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function in the imported file (e.g. "setVfs") and then import and call that function here instead.

**Comment by liborm85** [comment]
Resolved see https://github.com/bpampuch/pdfmake/issues/2654#issuecomment-2452944236.
