### ISSUE TITLE
require('pdfmake') gives errors

### ISSUE THREAD

**Issue by achatha** [bpampuch/pdfmake#263]
Hi. After installing pdfmake 0.1.17, i tried to use it by doing:

var pdf = require('pdfmake');

but that results in following errors:

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'base64-js' in /vagrant/sims/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 8:13-33

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'ieee754' in /vagrant/sims/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 9:14-32

ERROR in (webpack)/~/node-libs-browser/~/buffer/index.js
Module not found: Error: Cannot resolve module 'is-array' in /vagrant/sims/lib/node_modules/webpack/node_modules/node-libs-browser/node_modules/buffer
 @ (webpack)/~/node-libs-browser/~/buffer/index.js 10:14-33
Child extract-text-webpack-plugin:

Do i have to install those three packages? Shouldn't these be included as dependencies for pdfmake?
Any help is appreciated.

**Comment by achatha** [comment]
These are standard node library modules. Had to resolve them manually in webpack.

**Comment by mattrei** [comment]
hi, achatha. Can you give an example how to do it. cant get it running. Thanks

**Comment by achatha** [comment]
In your webpack (assuming you are using webpack) config file, resolve the modules manually:
resolve: {
    alias: {
      'is-array': require.resolve('webpack/node_modules/node-libs-browser/node_modules/buffer/node_modules/is-array'),
      'ieee754': require.resolve('webpack/node_modules/node-libs-browser/node_modules/buffer/node_modules/ieee754'),
      'base64-js': require.resolve('webpack/node_modules/node-libs-browser/node_modules/buffer/node_modules/base64-js')
    }
  }
This is basically telling webpack where to find those modules. Your specific paths may be different!
