### ISSUE TITLE
How to handle Uncaught (in promise)?

### ISSUE THREAD

**Issue by qvazi** [bpampuch/pdfmake#2630]
How to handle an error when, for example, an image Failed to fetch
`Uncaught (in promise) TypeError: Failed to fetch` 
Example code:
```js
const dd: TDocumentDefinitions = {
          content: [{ text: 'pdfmake' }, { image: 'cat', width: 150 }],
          images: {
            cat: catImageSrc
          },
        };
        const pdf = pdfMake.createPdf(dd);
        pdf.open();
```
I want to display the PDF creation process and display the creation error
I would also like to handle other Uncaught (in promise)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/2066

Will be fixed in version 0.3.0
