### ISSUE TITLE
Font characters rendered differently 

### ISSUE THREAD

**Issue by ghost** [bpampuch/pdfmake#2631]
Hi, 

I have extracted a font from a PDF and then imported it into to PDFMake.  How ever PDFMake renders the font differently to the original PDF.

Is there any way I can get the font rendered the same?

As you can see, in the PSDMake version(second image) the F's are slightly different.

![orignal](https://github.com/bpampuch/pdfmake/assets/126609761/0b882a5b-2f49-40ac-86ee-c491de6d34c4)
![pdfmake](https://github.com/bpampuch/pdfmake/assets/126609761/47ffa4e2-a270-4297-a8b1-169a0cd555f5)

**Comment by liborm85** [comment]
Attach pdf, font and example for reproduce issue.
