### ISSUE TITLE
How should I do to repeat elements in a document?

### ISSUE THREAD

**Issue by reinaldo-alves** [bpampuch/pdfmake#2632]
Hi, I created a const divider = {text: 'something'} to separate document sections. In do definitions, I set the property content as an array like [section1, divider, section2, divider, section3]. When the document is generated, only the first divider shows up. I also notice that if I created variables divider1, divider2, divider3, ... with the same content and insert them in the content array, like section1, divider1, section2, divider2, section3], all dividers are rendered.

The question is: Is there any way to repeat a variable in the content array, without having to create many variables?

**Comment by liborm85** [comment]
Multiple variable references is not supported, you can creatate `divider` as function, example:
```js
const divider = function() { return {text: 'something'} };

var dd = {
	content: [
		divider(),
		'Text A',
		divider(),
		'Text B',
		divider(),
	]
	
}
```

Issue: https://github.com/bpampuch/pdfmake/issues/465
