### ISSUE TITLE
Question: How do I recreate a codeblock?

### ISSUE THREAD

**Issue by jpobley** [bpampuch/pdfmake#2634]
I'd like to recreate an HTML code-block like the one in the image I've pasted below. I'm not so concerned with syntax highlighting; I just need the rectangle and mono-width font. I understand how to change fonts, but I don't know how to get the rectangle around the text--especially if the content would go across a page break.

Does anyone have experience with drawing this type of content?

<img width="948" alt="Screenshot 2023-10-03 at 9 08 25 AM" src="https://github.com/bpampuch/pdfmake/assets/2583256/65e9d617-c50b-4666-ac7d-b3f250c6f8ed">

**_pdfmake version: 0.2.7
environment: browser_**

**Comment by liborm85** [comment]
Simple example:
```js
var dd = {
	content: [
	    {
			table: {
			    widths: [500],
				body: [
					[
						{
							text: '\ndasdadasdasd\ndsadsdasdas\nfeffwe',
							fillColor: 'black',
							color: 'white'
						},
					]
				]
			}
	    }
	]
	
}
```
