### ISSUE TITLE
html to img and to pdf

### ISSUE THREAD

**Issue by mshakhriyorov** [bpampuch/pdfmake#2643]
Is it possible to render html component into image and turn it into pdf along with pdfMake? I mean, let's say, I have a chart and I will provide it with data from backend. And I need to generate pdf from this chart in my html code. 

One possible solution I am guessing is creating canvas from chart html and generating pdf from that url. But I am not sure how to do that with pdfMake

**Comment by lpicchi** [comment]
I don't think this is a feature related with pdfmake. You can solve this on your side. Just take a chart library that supports svg or png rendering echarts and add the rendered image to your PDF. echarte also support rendering in server. https://echarts.apache.org/handbook/en/how-to/cross-platform/server/
