### ISSUE TITLE
yarn/npm audit critical vulnerability for dependency crypto-js

### ISSUE THREAD

**Issue by atefth** [bpampuch/pdfmake#2645]
The dependency of **@foliojs-fork/pdfkit**  `crypto-js` has a critical vulnerability as of https://github.com/advisories/GHSA-xwcq-pm8m-c4vf but is patched in a subsequent patch. Can this dependency be updated please?

**Comment by Ganeshdr** [comment]
We are also currently blocked due to vulnerability introduced by old version of `crypto-js`. Can some one please address this issue ASAP?

**Comment by mathiasKaiser** [comment]
same here. my external code analyses tool checkmarx is setting alarm. love to see an security update here!

**Comment by NagendraKumar0505** [comment]
we are also facing same issue with cryptojs flagged by Sonatype. Request urgent attention to fix this issue for 0.2.7 version. Thanks

**Comment by liborm85** [comment]
Fixed in version 0.2.8.
