### ISSUE TITLE
When creating and comparing the pdf in tests sometimes it matches sometimes it doesn't

### ISSUE THREAD

**Issue by gonzalovilaseca** [bpampuch/pdfmake#2646]
Despite passing through `info`, sometimes the files match sometimes they don't.

There seems to be a counter? could it be the time it takes to render the pdf?

![Screenshot 2023-10-26 at 11 15 19](https://github.com/bpampuch/pdfmake/assets/4030438/999cb3d4-2728-44b6-8cfd-4d02ca12c6be)

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.
