### ISSUE TITLE
Possibility to access pdfkit context

### ISSUE THREAD

**Issue by BitInByte** [bpampuch/pdfmake#2650]
Hello and first of all, thanks for the amazing work on this plugin, simplifying something that was rather complex without this library and using all other libraries.

I wanted to use bookmarks/outlines but it seems that is not supported yet by this library. However, I was having a look to this repo to maybe implement this solution and possibly open a pull request and I saw that, since you're using pdfkit under the hood, you have kind of a context of the pdfkit. 

My question is, is it possible to get the context of the pdfkit so that we can also use the pdfkit features mixed together with pdfmake? With that way, even if a feature like for example the outlines is not implemented yet, we could use the pdfkit anyways to use until it got's completely implemented on pdfmake layer. 

Thanks one more time for the amazing work with this library :)

**Comment by liborm85** [comment]
Is possible to get the pdfkit document object after generate in browser via [getStream](https://pdfmake.github.io/docs/0.1/getting-started/client-side/methods/#get-pdfkit-document-object-as-stream) method or on server method [createPdfKitDocument](https://pdfmake.github.io/docs/0.1/getting-started/server-side/) returns this object. I don't know if it will be applicable for your purposes.

(related with https://github.com/bpampuch/pdfmake/issues/20)
