### ISSUE TITLE
Vite Packing error  vfs_fonts

### ISSUE THREAD

**Issue by Kimser** [bpampuch/pdfmake#2654]
<img width="663" alt="image" src="https://github.com/bpampuch/pdfmake/assets/54876002/2512c3ba-6c8b-46b1-b926-8bb46a23d750">
 ERROR  'default' is not exported by node_modules/pdfmake/build/vfs_fonts.js, imported by ......

**Comment by izidorio** [comment]
I'm having the same error when building

my code
```typescript
import * as pdfFonts from "pdfmake/build/vfs_fonts";
import * as pdfMake from "pdfmake/build/pdfmake";
(<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;
```

versios
```json
"pdfmake": "^0.2.8",
"react": "^18.2.0",
"typescript": "^5.0.2",
"vite": "^4.4.5"
```

**Comment by izidorio** [comment]
### Interim Solution
I created the file `./vfs_fontes.ts` in my project with the content `node_modules/pdfmake/build/vfs_fonts.js` leaving it as follows
 
original code `node_modules/pdfmake/build/vfs_fonts.js`
 ```javascript
this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {"Roboto-Italic.ttf":"AAEAAAARA ... AA0AA1AAA="};
```
 sample my code `./vfs_fontes.ts` 
```typescript
export default { "Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbz ... 0AjQAwAJgAmwAxANAA0AA1AAA="};
```
sample my code `./index.ts`
```typescript
import * as pdfFonts from "./vfs_fontes"; // 👈 local import
import * as pdfMake from "pdfmake/build/pdfmake";
(<any>pdfMake).vfs = pdfFonts.default;
```

@Kimser this is what worked for me, for now I will use it this way and monitor this problem until a definitive solution is found.

**Comment by ivanbtrujillo** [comment]
@izidorio approach works, but it gives me an error as we're trying to mutate the import:

`Imports are immutable in JavaScript. To modify the value of this import, you must export a setter function in the imported file (e.g. “setFonts”) and then import and call that function here instead.`

The safe way I found to do it is by passing down our vfs fonts as an argument to createPdf (you can see it is supported, based on @types/pdfmake):

<img width="813" alt="image" src="https://github.com/bpampuch/pdfmake/assets/6088653/7a4eb351-150c-417e-9648-4e36f96e37d0">

So the change is the following, instead of this:
```typescript
import { vfs_fonts } from './vfs_fonts';
(<any>pdfMake).vfs = pdfFonts.default;
```

do this:


```typescript
import * as pdfMake from 'pdfmake/build/pdfmake.js';
import { vfs_fonts } from './vfs_fonts';

....

 pdfMake.createPdf(docDefinition, undefined, undefined, vfs_fonts).download();
 ```

Now the app works as expected in dev mode, but also after building it.

**Comment by JDPedroza** [comment]
import pdfMake from "pdfmake/build/pdfmake";

export const generatePDFClient = (data) => {
  const {
    figures,
    totales,
    nidQuoter,
    name,
    phone,
    typeDocument,
    numberDocument,
  } = data;
  const date = new Date();

  return new Promise((resolve, reject) => {
    pdfMake.fonts = {
      Roboto: {
        normal:
          "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
        bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
        italics:
          "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
        bolditalics:
          "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
      },
    };

    var dd = {...}
    
    const pdfDocGenerator = pdfMake.createPdf(dd);

**Comment by panch8** [comment]
> ### Interim Solution
> I created the file `./vfs_fontes.ts` in my project with the content `node_modules/pdfmake/build/vfs_fonts.js` leaving it as follows
> 
> original code `node_modules/pdfmake/build/vfs_fonts.js`
> 
> ```js
> this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {"Roboto-Italic.ttf":"AAEAAAARA ... AA0AA1AAA="};
> ```
> 
> sample my code `./vfs_fontes.ts`
> 
> ```ts
> export default { "Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbz ... 0AjQAwAJgAmwAxANAA0AA1AAA="};
> ```
> 
> sample my code `./index.ts`
> 
> ```ts
> import * as pdfFonts from "./vfs_fontes"; // 👈 local import
> import  pdfMake from "pdfmake/build/pdfmake";
> (<any>pdfMake).vfs = pdfFonts.default;
> ```
> 
it worked for me also like this!  just thet fact to create a vfs_fotns.ts file with this structure: 
```
export default {"Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbzo4gAAddgAAACWEdQT1N/jK....AAAAAAAAAA"}
```
 and import it directly in  my code base.  where:
```import pdfFonts from "../../../../../utils/vfs_fonts";
import pdfMake from "pdfmake/build/pdfmake";
 pdfMake.vfs = pdfFonts
```

**Comment by GevinHasmitha** [comment]
> ### Interim Solution
> I created the file `./vfs_fontes.ts` in my project with the content `node_modules/pdfmake/build/vfs_fonts.js` leaving it as follows
> 
> original code `node_modules/pdfmake/build/vfs_fonts.js`
> 
> ```js
> this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {"Roboto-Italic.ttf":"AAEAAAARA ... AA0AA1AAA="};
> ```
> 
> sample my code `./vfs_fontes.ts`
> 
> ```ts
> export default { "Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbz ... 0AjQAwAJgAmwAxANAA0AA1AAA="};
> ```
> 
> sample my code `./index.ts`
> 
> ```ts
> import * as pdfFonts from "./vfs_fontes"; // 👈 local import
> import  pdfMake from "pdfmake/build/pdfmake";
> (<any>pdfMake).vfs = pdfFonts.default;
> ```
> 
> Another simpler solution is to download the source from the CDN sample my code `./index.ts`
> 
> ```ts
> import pdfMake from "pdfmake/build/pdfmake";
> (<any>pdfMake).fonts = {
>   Roboto: {
>     normal:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
>     bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
>     italics:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
>     bolditalics:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
>   },
> };
> ```
> 
> @Kimser this is what worked for me, for now I will use it this way and monitor this problem until a definitive solution is found.

export default {"Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbzo4gAAddgAAACWEdQT1N/jK....AAAAAAAAAA"}

How did you get the data urls for the fonts? Did you generate them?

**Comment by habeebijaba** [comment]
### Interim Solution  for Vite+React+JS
```

// import statement
 import pdfMake from "pdfmake/build/pdfmake";

// Defining and Using Custom Fonts
const pdfMakeFonts = {
  Roboto: {
    normal:
      "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
    bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
    italics:
      "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
    bolditalics:
      "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
  },
};

// Assign the custom fonts to pdfMake
  pdfMake.fonts = pdfMakeFonts;

```

**Comment by Joecey** [comment]
@habeebijaba works for me ;))

**Comment by Youssif-Salama** [comment]
> ### Interim Solution
> 
> I created the file `./vfs_fontes.ts` in my project with the content `node_modules/pdfmake/build/vfs_fonts.js` leaving it as follows
> 
> original code `node_modules/pdfmake/build/vfs_fonts.js`
> 
> ```js
> this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {"Roboto-Italic.ttf":"AAEAAAARA ... AA0AA1AAA="};
> ```
> 
> sample my code `./vfs_fontes.ts`
> 
> ```ts
> export default { "Roboto-Italic.ttf": "AAEAAAARAQAABAAQR0RFRqbz ... 0AjQAwAJgAmwAxANAA0AA1AAA="};
> ```
> 
> sample my code `./index.ts`
> 
> ```ts
> import * as pdfFonts from "./vfs_fontes"; // 👈 local import
> import  pdfMake from "pdfmake/build/pdfmake";
> (<any>pdfMake).vfs = pdfFonts.default;
> ```
> 
> Another simpler solution is to download the source from the CDN sample my code `./index.ts`
> 
> ```ts
> import pdfMake from "pdfmake/build/pdfmake";
> (<any>pdfMake).fonts = {
>   Roboto: {
>     normal:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Regular.ttf",
>     bold: "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Medium.ttf",
>     italics:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-Italic.ttf",
>     bolditalics:
>       "https://cdnjs.cloudflare.com/ajax/libs/pdfmake/0.1.66/fonts/Roboto/Roboto-MediumItalic.ttf",
>   },
> };
> ```
> 
> @Kimser this is what worked for me, for now I will use it this way and monitor this problem until a definitive solution is found.

thank  you bro it worked for me

**Comment by liborm85** [comment]
In version [0.2.15](https://github.com/bpampuch/pdfmake/releases/tag/0.2.15) changed VFS format. (**Custom VFS files require rebuild.**)

Now works this simple import:
```js
import pdfMake from "pdfmake/build/pdfmake";
import "pdfmake/build/vfs_fonts";
```
(Tested on vite + react jsx.)


Other way for frameworks where not available global can be used:
```js
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.addVirtualFileSystem(pdfFonts);
```
