### ISSUE TITLE
Table Layout is not Assignable to readonly property 'tableLayouts'

### ISSUE THREAD

**Issue by Melakeselam** [bpampuch/pdfmake#2657]
First of all, I would like to express my appreciation to the pdfMake team for creating and making available such a resource filled tool for us to use. Thank you and God bless you.

Coming to the point, I am using version 0.2.8, trying to create custom table layout and assign it to pdfMake as per the explanation I saw on the reference document:

```
pdfMake.tableLayouts = {
  exampleLayout: {
    ...
  }
};
```
However, I am getting an error on the tableLayouts property:

`Cannot assign to 'tableLayouts' because it is a read-only property.ts(2540)`

Is this a bug in this version?

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/5c8f788633228235a3d8820acb33d782d42717d7 in version 0.2.15.

You can use method `setTableLayouts(...)`.
