### ISSUE TITLE
Most efficient way save pdf with images in Phonegap/Cordova.

### ISSUE THREAD

**Issue by wootwoot1234** [bpampuch/pdfmake#266]
I'm trying to create a pdf that contains a few images in a Phonegap/Cordova app.  When I call `getDataUrl()` on a pdf document that has images the app freezes for a little while then crashes.  It only crashes when there are images so I'm guessing it's having a hard time generating the base64 string with all the image data.  Is there another way to save/export the pdf that might be more efficient?

**Comment by jthoenes** [comment]
I don't know the cordova details, but there are some people using it with pdfmake (search the other issues).

We had issues with Chrome when the data url got to big, the browser simply crashed. So we used ``getBuffer`` to create a file and store it in Chrome temporary file system. But that's only working in Chrome ...

**Comment by wootwoot1234** [comment]
@jthoenes Thanks.  That was very helpful.  Using ```getBuffer``` fixed the crashing issue and #144 has a nice example of how to use ```getBuffer``` to save it to the local file system.  My issue now is, it's taking a long time to get the buffer.  It seems to be caused by the images I'm adding.  I've already reduced the image sizes to as small as possible, is there anything I can do to speed up the PDF creation?  I'm currently getting the base64 url of each image and adding them that way.  Is there a more efficient way to add them?

Maybe I should create a new issue for this question (let me know).  Thanks again.

**Comment by Wabbala** [comment]
@wootwoot1234 I had the same issue as you, I had to incorporate images (1 to many) in a report I was generating. This caused many browsers to freeze up and end-up being unresponsive. 

What I had to do was to switch my whole back-end to nodejs, to actually do the rendering of the pdf server-sided (content generation did take place client side). Doing it this way gave me the control over the hardware requirements. I do not know if this is possible for you, but if it is, do it. It is totally worth it! If you need help setting it up, just me let me know :smile: !

**Comment by liborm85** [comment]
New versions contains fix for perfomance, see details: https://github.com/bpampuch/pdfmake/issues/280#issuecomment-267255835. You can test whether you solved the problem?

**Comment by liborm85** [comment]
Fixed. Details: https://github.com/bpampuch/pdfmake/issues/280#issuecomment-275910108
