### ISSUE TITLE
Function mm to point and px to point 

### ISSUE THREAD

**Issue by jiangdefu** [bpampuch/pdfmake#2662]
Can the conversion method or specific conversion rules of the lower millimeter (mm) and point be provided?

Can the conversion method or specific conversion rule of lower pixels (px) and points be provided?

**Comment by white1crow** [comment]
/**
 * 获取当前显示器1毫米对应的像素值
 */
function getOneMmsPx() {
  // 创建一个1mm宽的元素插入到页面，然后坐等出结果
  let id = `mm_${new Date().getTime().toString()}`
  let div = document.createElement('div')
  div.id = id
  div.style.width = '1mm'
  div.style.position = 'absolute'
  document.querySelector('body')!.appendChild(div)
  // 原生方法获取浏览器对元素的计算值
  let mm1 = document.getElementById(id)!.getBoundingClientRect()
  const mmPx = mm1.width
  div.parentElement?.removeChild(div)
  return mmPx
}

**Comment by white1crow** [comment]
/**
 * 获取当前显示器1毫米对应的像素值
 */
function getOneMmsPx() {
  // 创建一个1mm宽的元素插入到页面，然后坐等出结果
  let id = `mm_${new Date().getTime().toString()}`
  let div = document.createElement('div')
  div.id = id
  div.style.width = '1mm'
  div.style.position = 'absolute'
  document.querySelector('body')!.appendChild(div)
  // 原生方法获取浏览器对元素的计算值
  let mm1 = document.getElementById(id)!.getBoundingClientRect()
  const mmPx = mm1.width
  div.parentElement?.removeChild(div)
  return mmPx
}

**Comment by liborm85** [comment]
mm to pt: https://www.unitconverters.net/length/millimeter-to-point.htm
px to pt: https://www.ninjaunits.com/converters/pixels/pixels-points/
