### ISSUE TITLE
This works in PDFmake playgroud. But not in NodeJs code level.

### ISSUE THREAD

**Issue by Ananyakokala** [bpampuch/pdfmake#2664]
```ts
var dd = {
  content: [
    {
      image: 'snow'
    }
  ],
  images: {
    snow: 'https://<url>/image.png'
  }
};
```

Receiving the below error: 
```ts
Invalid image: Error: ENOENT: no such file or directory, open 'https://<url>/image.png'
Images dictionary should contain dataURL entries (or local file paths in node.js)
```
The same documetDefination works fine in [PlayGround](http://pdfmake.org/playground.html) But it wont work in my application. The same docDefination what my code dynamically generates will work in playground but from the npm package _createPdfKitDocument_ function gives the above metioned error.
Node Version: >= 16.4
PDFMake Version: 0.2.7

Can any one please help?

**Comment by liborm85** [comment]
Loading images from https/http is supported only in browser.

**Comment by Ananyakokala** [comment]
@liborm85 
Do you mean from pdfMake npm package we will not be able to handle images with http/https URLs? 

Here I am using pdfMake to create any PDF and send it as a REST API response to the web application.  I am not able to handle it with the above-provided syntax. I need to handle the images in the PDF.

**Comment by liborm85** [comment]
See [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/images/), only in browser:
![image](https://github.com/bpampuch/pdfmake/assets/1298652/a5921048-de4d-48be-af65-0f9a9b8f4fd2)

Loading from https/http will be supported in the upcoming 0.3.0 version, https://github.com/bpampuch/pdfmake/issues/2375.
