### ISSUE TITLE
font loading issue with pdfmake in ionic/ios

### ISSUE THREAD

**Issue by pareshgami** [bpampuch/pdfmake#2666]
I'm using pdfMake for generating PDF in ionic/angular. It's working fine with android but getting error in iOS when loading font dynamically.

I'm loading font in this way

```
generatePDF(pdfInstant: any, content: any) {
  pdfInstant.fonts = {
    common: {
       normal: window.location.origin + " /assets/fonts/pdf/FreeSerif.ttf",
       bold: window.location.origin + " /assets/fonts/pdf/FreeSerif.ttf",
       italics: window.location.origin + " /assets/fonts/pdf/FreeSerif.ttf",
       bolditalics: window.location.origin + "/assets/fonts/pdf/FreeSerif.ttf",
     },
   };

   content['defaultStyle'] = {
     font: 'common'
   };
   pdfInstant.createPdf(content).getBase64((r: any) => {
      this.utilService.sharePDF(new Date().getTime() / 1000 + '.pdf', r);
   });
}
```

Error I'm getting is:

`⚡️  [error] - ERROR Error: Uncaught (in promise): File 'capacitor://localhost/assets/fonts/pdf/FreeSerif.ttf' not found in virtual file system `

**Comment by liborm85** [comment]
Only https or http protocol is supported, see [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/url/).

**Comment by pareshgami** [comment]
In ionic/capacitor, specifically URL is not localhost or http or https but somehow I manage to do it using base64 of font.
