### ISSUE TITLE
Memory Leak issue observed while docDefinition is huge

### ISSUE THREAD

**Issue by revathiVinoth** [bpampuch/pdfmake#2667]
We are using create Pdf kit document for printing the pdf doc . (refer the snippet)
//
 import PdfPrinter from "pdfmake";
  let printer = new PdfPrinter(fonts);
  let pdfDoc = printer.createPdfKitDocument(docDefinition, options);
//
When the docdefinition content is huge we are facing "what(): std::bad_alloc" / Java heap memory allocation issue"

Please feedback.

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.
