### ISSUE TITLE
Underline and strike text

### ISSUE THREAD

**Issue by natcohen** [bpampuch/pdfmake#267]
Is it possible to underline or strike text?

**Comment by jthoenes** [comment]
Have a look at Text Decorations: https://github.com/bpampuch/pdfmake/blob/master/examples/textDecorations.js

**Comment by natcohen** [comment]
Thanks! Would be good to add those in the playground... In addition, it would be more consistent to be able to underline, overline and strike at the same time (very rare but more consistent with what an editor can do...)

**Comment by jthoenes** [comment]
Happy to accept a pull request for either ;-)

**Comment by natcohen** [comment]
:) I'm not very familiar with github...

**Comment by 12smc120** [comment]
Hi @jthoenes ,
 How to give a space between decocation:'overline' and text.

var dd = {
        content: [{
            text: 'Test',
            style: 'signature',
         }],
        styles: {
            signature: {
                fontSize: 20,
                bold: true,
                decoration: 'overline',
                decorationStyle: 'solid', 
                decorationColor: 'black'
            },
        }
    }

**Comment by ackvf** [comment]
I had to do a google search to find this. It would look great in documentation....

**Comment by daniel-rau** [comment]
Agreed.  It would be extremely helpful to have all of the styling options laid out in the documentation so that we don't have to do a google search every time we want to make a styling change.
