### ISSUE TITLE
Why image in footer has replaced from image in content only first page

### ISSUE THREAD

**Issue by qwerty2042** [bpampuch/pdfmake#2672]
<img width="560" alt="ภาพถ่ายหน้าจอ 2567-01-10 เวลา 19 15 49" src="https://github.com/bpampuch/pdfmake/assets/107826719/d6ba96eb-b7dc-4fbe-b359-3e9ffc65e156">

After pdf file has generated, i found this issue only first page

**Comment by TDDEL** [comment]
I also stumbled upon this problem as well.  

It occurs for me whenever I pass content in through a function. For example, my footer has a image in it which should be the same for all pages, but instead the image of the footer is replaced with the first image that occurs on that specific page.

I also encountered this same problem when passing in the content for **background** with a function.  That is, the first image in the background is replaced with the first image that occurs on the page content.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1278
