### ISSUE TITLE
How to create pdf file with math symbols? 

### ISSUE THREAD

**Issue by tiepntt** [bpampuch/pdfmake#2673]
I have a document struct base on katex. 
```
{
  "json": '\sqrt{a^2 + b^2}'
}
```
I want render in pdf look like: 
![image](https://github.com/bpampuch/pdfmake/assets/44738396/0c895d7f-28ef-40ee-aeac-66493469e38c).

Help me.

**Comment by michaelpantelios** [comment]
Hi, I have combined katex and html2canvas with pdfmake, it's quite tricky because you have to let katex render the maths into html, and html2canvas to create canvas that will be used as image in pdfmake. I can send you sample code in javascript if you like.

**Comment by rubickecho** [comment]
> Hi, I have combined katex and html2canvas with pdfmake, it's quite tricky because you have to let katex render the maths into html, and html2canvas to create canvas that will be used as image in pdfmake. I can send you sample code in javascript if you like.

i also want to know

**Comment by liborm85** [comment]
It is not supported directly by pdfmake. Use other library to convert this code to svg or image and this output use in pdfmake doc definition.

**Comment by wendleypf** [comment]
How to render `text + svg + text` in these formula scenarios?
