### ISSUE TITLE
SERVER GOT HACKED TO MAKE GAMBLING ONLINE AND SPAM

### ISSUE THREAD

**Issue by OLIV853** [bpampuch/pdfmake#2675]
![maxwin pdfmake](https://github.com/bpampuch/pdfmake/assets/153894964/04a1a7b8-9acb-4273-b7be-96e9b52d0f2f)

Hello Sir,

I want to inform that  Your Server site already got hacked to make so many sub domain for gambling online site that's ilegal to do.

You can check in google use this keyword :
site:http://maxwin.pdfmake.org/

it will display so many this is serveral of the links:
http://maxwin.pdfmake.org/surat4d.html
http://maxwin.pdfmake.org/sis4d.html
http://maxwin.pdfmake.org/timnas4d.html

The button link is direct to gambling online site and only can access use indonesia IP address :
https://ght.mrusco.com/hohocolang/
https://ops.mrusco.com/hohocolang
https://66kbet3m.top/

Please Remove,Banned also Track the Hacker and make the Hacker go to Jail.

As an Indonesian citizen, I want to emphasize that online gambling is clearly prohibited by Indonesian law. In accordance with Article 27 paragraph (2) of the ITE Law, this act is a prohibited act. Therefore, individuals are prohibited from distributing, transmitting or making accessible gambling content online.

I have attached clear photographic evidence related to this case. My request is that you immediately take the necessary action to delete this sub-domain and online gambling page, or at least suspend access immediately so that online gambling content cannot be accessed. I hope that firm steps will be taken to ensure the integrity of the father's name is maintained and to avoid potential legal problems in the future.

I am grateful for the attention and action taken regarding this matter. I am sure that you will uphold ethics and legal compliance in carrying out your services.

Yours faithfully,

**Comment by liborm85** [comment]
Your links returns 404.
