### ISSUE TITLE
Thai letter not rendering correctly 

### ISSUE THREAD

**Issue by naveena1111** [bpampuch/pdfmake#2677]
Hi ,

while rendering Thai word in PDFMake one specific letter is not render correctly we used many Thai fonts but while render its different.kindly help for fix.

![Capture](https://github.com/bpampuch/pdfmake/assets/57196548/e886cdc8-a958-49d5-9539-6e68dc282127) need to change to น้ำ

**Comment by liborm85** [comment]
pdfmake use fontkit library for rendering fonts, create issue [here](https://github.com/foliojs/fontkit).
