### ISSUE TITLE
Error when using with vite production build

### ISSUE THREAD

**Issue by smitbhalodiya** [bpampuch/pdfmake#2678]
When using in a Laravel with Vite.

- Laravel: v10.39.0
- Vite: v5.0.11
- pdfmake : v0.2.9

I am importing the library like this:
```
import pdfFonts from 'pdfmake/build/vfs_fonts';
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

![image](https://github.com/bpampuch/pdfmake/assets/61959920/25bda17e-d97b-4d94-ac85-cba3a2fad276)

This code works fine when running with vite watch

I am importing the library like this:
`import * as pdfFonts from 'pdfmake/build/vfs_fonts';`

It successfully ran the `Yarn Build` command without encountering any build errors, but see errors in the console.
![image](https://github.com/bpampuch/pdfmake/assets/61959920/6ef91d93-3dd8-4ff6-aa02-4f4425095c3e)

**Comment by SamirMishra27** [comment]
Hi, have you found a solution to this? I'm also facing same exact issue in production deployment of site, using react and vite as build tool.

**Comment by smitbhalodiya** [comment]
Hi @SamirMishra27,
Everything worked out!, thank you very much!

**Comment by du-disk** [comment]
> Hi @SamirMishra27, Everything worked out!, thank you very much!

How?
