### ISSUE TITLE
How to custom Pagebreak ?

### ISSUE THREAD

**Issue by yourlowkey** [bpampuch/pdfmake#2680]
I have to remove the line of table break and add the Line like the below pictures. Can someone help me where in the Pdfmake package code I can interrupt with?

![e5f3595306cdad93f4dc1](https://github.com/bpampuch/pdfmake/assets/89309285/0310bffc-8375-433d-8f58-873f3f55e696)
![e560ecc7b359180741482](https://github.com/bpampuch/pdfmake/assets/89309285/2d8c009c-db91-47a1-9d39-49b7cd1c8e38)

**Comment by liborm85** [comment]
You can use `pageBreak: 'before'` or `pageBreak: 'after'` or dynamically `pageBreakBefore` function see [documentation](https://pdfmake.github.io/docs/0.1/document-definition-object/page/).
