### ISSUE TITLE
Please add feature contentPageSize 

### ISSUE THREAD

**Issue by yourlowkey** [bpampuch/pdfmake#2681]
It would be perfect to have the size of content of every page. I love something like this from the heading : 
export type DynamicContent = (
    currentPage: number,
    pageCount: number,
    pageSize: ContextPageSize,
    **contentSize : ContentPageSize,**
) => Content | null | undefined;
![image](https://github.com/bpampuch/pdfmake/assets/89309285/8761f4df-edba-43d0-a07a-872f59c257dc)

**Comment by liborm85** [comment]
Duplicate. Feature request here: https://github.com/bpampuch/pdfmake/issues/325
