### ISSUE TITLE
pageBreakBefore increases the output size of my PDF x15 fold

### ISSUE THREAD

**Issue by ruzqat** [bpampuch/pdfmake#2685]
Hi everyone. 

I'm using pageBreakBefore to control table rows breaks. It works excellent, but bloats my file size from ~1 mb to ~17mb. Using foxit pdf Optimizer the size shrinks to about 300kb with no losses. Space Usage Audit of the original document shows >95% of the space is taken by Document Overhead. After shrinking the the new 300kb file shows <2% of space is taken by Document Overhead. 

Judging by the fact that quality isn't degraded I think all that data in document overhead is not needed. 
Any suggestions where to look further? 

    pageBreakBefore: function (
      currentNode,
      followingNodesOnPage,
      nodesOnNextPage,
      previousNodesOnPage,
    ) {
      if (
        currentNode.headlineLevel < 10 &&
        currentNode.id !== 1 &&
        followingNodesOnPage.every(node => node.headlineLevel !== 1)
      ) {
        return true;
      }
    },

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.

**Comment by ruzqat** [comment]
FOR ANYONE FACING SIMILAR ISSUES:

What solved my case was changing the way image is being used and referenced in the background.

From this:
...
import { base64image } from '@assets/img/imageBase64';
 const document = {
    background: function (currentPage) {
      return {
        image: base64image,
      };
    },
...


To this:
...
import { base64image } from '@assets/img/imageBase64';
 const document = {
     images: {
      imageB64 : base64image
    },
    background: function (currentPage) {
      return {
        image: 'imageB64', 
      };
    },


I'm not sure why that makes such a difference, but this was able to bring my pdf size down to about 400-500kb. 
I'm curious to know why if anyone has an explanation.

**Comment by liborm85** [comment]
First mean add image from base64.
Second mean add image from image dictionary.
First generate multiple images to document. Second generate only one image to document.
