### ISSUE TITLE
Custom font problem

### ISSUE THREAD

**Issue by Tiru150837** [bpampuch/pdfmake#2687]
I am trying to include custom font other than the inbuilt one. Actually I am using pdfmake.min.js file to generate pdf. Now I am trying to insert my custom font in vfs_fonts . And I try to use it my application and I follow the procedure given in document. Then I  got the error like 
ERROR Error: Uncaught (in promise): Error: Font 'Lora' in style 'normal' is not defined in the font section of the document definition.
FontProvider.prototype.provideFont@webpack-internal:///./src/assets/build/pdfMake.min.js:2:1013114
measure/<@webpack-internal:///./src/assets/build/pdfMake.min.js:2:153457
measure@webpack-internal:///./src/assets/build/pdfMake.min.js:2:152516
TextTools.prototype.buildInlines@webpack-internal:///./src/assets/build/pdfMake.min.js:2:154011
DocMeasure.prototype.measureLeaf@webpack-internal:///./src/assets/build/pdfMake.min.js:2:1033499..where it is located...

Please , help me to resolve this issue..

Thanks in Advance

**Comment by liborm85** [comment]
How to use custom fonts is described in [documentation](https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/).

**Comment by Tiru150837** [comment]
I tried that way but it is not working to me. 
And I tried to build as well to get new pdfmake.min.js file..when I run the command npm run build , I am getting the error like this..

ERROR in ./node_modules/fontkit/dist/module.mjs 7463:26
Module parse failed: Unexpected token (7463:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| class $5340de7a86f3ae85$export$2e2bcd8739ae039 {
>     static zeroMarkWidths = 'AFTER_GPOS';
|     static plan(plan, glyphs, features) {
|         // Plan the features we want to apply
 @ ./node_modules/pdfkit/js/pdfkit.es5.js 75:38-56
 @ ./src/pdfKitEngine.js
 @ ./src/printer.js
 @ ./src/browser-extensions/pdfMake.js
 @ ./src/browser-extensions/pdfMake-exposed.js
[23:24:30] 'build' errored after 12 s
[23:24:30] ModuleParseError: Module parse failed: Unexpected token (7463:26)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| };
| class $5340de7a86f3ae85$export$2e2bcd8739ae039 {
>     static zeroMarkWidths = 'AFTER_GPOS';
|     static plan(plan, glyphs, features) {
|         // Plan the features we want to apply
    at handleParseError (D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\webpack\lib\NormalModule.js:469:19) 
    at D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\webpack\lib\NormalModule.js:503:5
    at D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\webpack\lib\NormalModule.js:358:12
    at D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\loader-runner\lib\LoaderRunner.js:373:3
    at iterateNormalLoaders (D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\loader-runner\lib\LoaderRunner.js:214:10)
    at Array.<anonymous> (D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\loader-runner\lib\LoaderRunner.js:205:4)
    at Storage.finished (D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:55:16)
    at D:\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\enhanced-resolve\lib\CachedInputFileSystem.js:91:9    
    at D\v9-notification\pdfmake0.1.72\node_modules\pdfmake\node_modules\graceful-fs\graceful-fs.js:123:16
    at FSReqCallback.readFileAfterClose [as oncomplete] (node:internal/fs/read_file_context:68:3)
    at FSReqCallback.callbackTrampoline (node:internal/async_hooks:130:17)..


How to resolve this issue?


Thanks in advance!!

**Comment by liborm85** [comment]
Not related with your first post. Step rebuild pdfmake with npm run build not part of building custom fonts.
