### ISSUE TITLE
Not able to find values with custom page size

### ISSUE THREAD

**Issue by mrsreejeshsreekumar** [bpampuch/pdfmake#2688]
generatePDF(): void {
    const customPageSize = { width: 89, height: 28 };

    const docDefinition = {
      pageSize: customPageSize,
      content: [
        {
          text: 'Hello, this is a custom-sized document!',
          fontSize: 12,
          bold: true,
          alignment: 'center',
        },
      ],
    };

    const pdfDocGenerator = pdfMake.createPdf(docDefinition);

    pdfDocGenerator.getBlob((blob: any) => {
      const blobURL = URL.createObjectURL(blob);
      console.log("blobURL", blobURL);
      // Open the PDF in a new tab for testing
      window.open(blobURL, '_blank');
    });
  `}```

**Comment by mrsreejeshsreekumar** [comment]
existing behaviour is no text found inside the page.

**Comment by liborm85** [comment]
Page size is too small and page margins is too big. This definition is correct:
```js
var dd = {
  pageMargins: [ 0, 0, 0, 0 ],
  pageSize: { width: 89, height: 28 },
  content: [
    {
      text: 'Hello, this is a custom-sized document!',
      fontSize: 12,
      bold: true,
      alignment: 'center',
    },
  ],
};
```

**Comment by mrsreejeshsreekumar** [comment]
oh, okey, let me see if this solved the issue.

Many thanks!!!!!

**Comment by mrsreejeshsreekumar** [comment]
Issue is fixed, thanks again...
