### ISSUE TITLE
Issue with styles when generating tables

### ISSUE THREAD

**Issue by jm-delgado** [bpampuch/pdfmake#2694]
Good morning, 

I'm having some trouble when I use the method createPdf. It's very strange, because I couldn't determine what causes it. 

Sometimes, a table within the document would be created ignoring the styles that I'm providing in the variable dd and it looks like this: 

![image](https://github.com/bpampuch/pdfmake/assets/160005686/6f710722-4511-43b4-aa84-18400404a320)

When it should look like this::

![image](https://github.com/bpampuch/pdfmake/assets/160005686/2019ca02-17eb-4904-bd9d-a01469254817)

Also, when some cells in the table are empty, it throws this error, but we manage to place a blank space to avoid not creating the document: 
![image](https://github.com/bpampuch/pdfmake/assets/160005686/2be3c3ef-f5e9-427d-b98a-521ec843f38f)

This was working in our production environment until January 15th more or less. I'm using the last version of the library and I've verify that the information that is passed to the function is the same when it works and when it doesn't. Also, changing the version of the library won't fix the issue. 

We are working in SN and we tried with different browsers, OS, cleaning cache and cookies and the issue seems to be random. 
Did anyone have the same issue? 

Best regards, 

José

**Comment by liborm85** [comment]
Malformed table row exception is caused by table row with not enough columns. If the rows have the correct number of columns including those colSpan, rowSpan the exception should not occur.
Before January 15th probably your code generate different table contents.

**Comment by jm-delgado** [comment]
We got that under control adding information to every field, but we still have the issue with the styles on the tables.  We are trying to identify if the issue is coming from the method "htmlToPdfmake" or when creating the PDF with createPdf.
