### ISSUE TITLE
show table do not across page

### ISSUE THREAD

**Issue by timfei** [bpampuch/pdfmake#2699]
The table show in two page , is there any possible display the tables on same page?
In this image,the table (orange line ) show in two page, and row two content display is not OK， is any possible let the table do not acoss pages, just show in one page. (my doc table is short , it's ok let table show in one page). 
![image](https://github.com/bpampuch/pdfmake/assets/10008489/85ef62a0-1366-431e-9a6f-9a9d6c15c68b)
I would appreciate it if you could help me :)

**Comment by timfei** [comment]
there are many tables in my document. have any way to let table recognize itself will across page then let table show in same page.

**Comment by MrSimmmons** [comment]
You would have to include the tables in a stack, then use `pageBreakBefore` with some custom logic to achieve this
https://pdfmake.github.io/docs/0.1/document-definition-object/page/#dynamically-control-page-breaks-for-instance-to-avoid-orphan-children
