### ISSUE TITLE
Problems on some printers on pdfmake generated docs

### ISSUE THREAD

**Issue by gpor1989** [bpampuch/pdfmake#270]
Hi.

Im having issue with printer here. Some of the printers (minolta) cannot print the generated documents. I Don't know why. They just reboot themselves.

Also, please check generated pdf validity with PDF validity check tools:

http://www.pdf-tools.com/pdf/validate-pdfa-online.aspx with sample generated doc. says:

sample.pdf does not conform to PDF/A.

Validating file "sample.pdf" for conformance level pdfa-1b
The file trailer dictionary must have an id key.
The key Metadata is required but missing.
A device-specific color space (DeviceRGB) without an appropriate output intent is used.
The document does not conform to the requested standard.
The document contains device-specific color spaces.
The document's meta data is either missing or inconsistent or corrupt.
Done.

If this is a bug, please fix it.

**Comment by jthoenes** [comment]
Hi @gpor1989,

pdfmake is not aiming to PDF/A compliant at the moment. So it's not a bug.

For the printing, check if you font has an issue. You might have this issue: https://github.com/devongovett/pdfkit/issues/218

Let me know if that fixes the issue please.
