### ISSUE TITLE
Vulnerability SNYK-JS-ES5EXT-6095076 in es5-ext

### ISSUE THREAD

**Issue by corzelito** [bpampuch/pdfmake#2701]
Link in snyk: https://security.snyk.io/vuln/SNYK-JS-ES5EXT-6095076

**Comment by liborm85** [comment]
es5-ext is part of brfs. brfs package is unused in pdfmake (only installed).

Removed brfs dependency in version 0.2.10.

**Comment by corzelito** [comment]
The vulnerability is still in Synk, and if it apparently depends on the dev playground, why isn't it changed or removed from this project? This causes the library to be marked as vulnerable, and will no longer be used as much...

**Comment by corzelito** [comment]
> es5-ext is part of brfs. brfs package is unused in pdfmake (only installed).
> 
> Removed brfs dependency in version 0.2.10.

Thanks mate!

**Comment by keithernet** [comment]
Hello! It looks like the brfs dependency is still in the package.json file which is causing my SCA to pick up the vulnerability still. Can it be removed? Happy to add the PR if there's not some reason it still needs to be in the devDeps.

Thanks!
