### ISSUE TITLE
How to display Chinese traditional language in PDF using angular version 15

### ISSUE THREAD

**Issue by raviKrishnaNaidu** [bpampuch/pdfmake#2704]

**Comment by raviKrishnaNaidu** [comment]
I have followed the steps mentioned, but I couldn’t get it resolved. I m getting an error like ‘ file not found in virtual file system’

Any examples or suggestions will be helpful

Thank you in advance

**Comment by liborm85** [comment]
Maybe similar problem with angular and solution described here: https://github.com/bpampuch/pdfmake/issues/2723#issuecomment-2117740730
