### ISSUE TITLE
SVG is not displayed correctly

### ISSUE THREAD

**Issue by EdoardoCroci** [bpampuch/pdfmake#2706]
I have a react project with pdfmake added by yarn, a component draws a chart (svg) using d3, I use an id to get the svg. 
This is how I get the svg and add it to an empty document:

`const svgElement = document.getElementById('svgConcrete');
    const svgString = svgElement.outerHTML;

    const docDefinition = {
      content: [           
        {
          columns: [
            { width: '*', text: '' },
            {
              svg: svgString,
              width: 175,
              height: 175
            },
            { width: '*', text: '' },
          ]
        }
      ],
    }` 

The image that should be displayed is this: 
![WhatsApp Image 2024-03-11 at 12 03 04](https://github.com/bpampuch/pdfmake/assets/50620392/c21f5fff-1f96-41ba-a89e-50266f0516c1)

The image that I get is:
![WhatsApp Image 2024-03-11 at 12 05 03](https://github.com/bpampuch/pdfmake/assets/50620392/1975b408-70db-44bc-9227-a4d06de93277)

Why does this happen? How can I fix it?

**Comment by liborm85** [comment]
pdfmake use for rendering svg library [svg-to-pdfkit](https://github.com/alafr/SVG-to-PDFKit) you can report there.
