### ISSUE TITLE
Table - Long 'star' cell with no space takes to much space 

### ISSUE THREAD

**Issue by natcohen** [bpampuch/pdfmake#271]
When I fill a cell with a very long string (without space), it doesn't break the string in order keep the right size for the cell and pushes the rest of the table outside the page...

table: {
                                widths: ['_', '_', '_', '_'],
                                body: [
                                        [ 'width=100000000000000000000000000000000000000000000000000000000000000', 'star-sized', 'width=200', 'star-sized'],
                                        [ 'fixed-width cells have exactly the specified width', { text: 'nothing interesting here', italics: true, color: 'gray' }, { text: 'nothing interesting here', italics: true, color: 'gray' }, { text: 'nothing interesting here', italics: true, color: 'gray' }]
                                ]
                        }

**Comment by jthoenes** [comment]
Hi @natcohen, that's a know issue/bug. As we break words only when there is breakable white-space between, this goes bad in tables. I don't know what a good strategy for solving it would be. 

Suggestions are welcome, pull request even more.

**Comment by natcohen** [comment]
Well, IMHO the best solution is to cut the word to fit the table and add '-'...

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/204
