### ISSUE TITLE
encountered an error "javascript heap out of memory" while attempting to generate a PDF using pdf-make

### ISSUE THREAD

**Issue by kmr-pawan** [bpampuch/pdfmake#2713]
Details:
When attempting to generate a PDF with a large amount of data using pdf-make, the process fails with a "JavaScript heap out of memory" error. This issue was encountered while testing with a dataset containing 1 million user records. The PDF generation succeeds with a dataset of 100k user records but fails with the larger dataset.

Steps to reproduce:

- Use pdf-make to generate a PDF document.

- Pass a large dataset, such as 1 million user records, to pdf-make for rendering.

- Observe the "JavaScript heap out of memory" error during PDF generation.

- Testing json: https://jsoneditoronline.org/indepth/datasets/json-file-example/#

<--- Last few GCs --->
[22796:000001B44B921450]   130275 ms: Mark-Compact 4045.1 (4130.9) -> 4029.8 (4131.4) MB, 1417.58 / 0.00 ms  (average mu = 0.100, current mu = 0.012) allocation failure; scavenge might not succeed
[22796:000001B44B921450]   131689 ms: Mark-Compact 4045.7 (4131.7) -> 4030.3 (4131.7) MB, 1393.16 / 0.00 ms  (average mu = 0.059, current mu = 0.015) allocation failure; scavenge might not succeed
<--- JS stacktrace --->
FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
----- Native stack trace -----
 1: 00007FF7ED0D65BB node::SetCppgcReference+15595
 2: 00007FF7ED041074 v8::base::CPU::num_virtual_address_bits+88020
 3: 00007FF7EDB11101 v8::Isolate::ReportExternalAllocationLimitReached+65
 4: 00007FF7EDAFAAB8 v8::Function::Experimental_IsNopFunction+1192
 5: 00007FF7ED94B970 v8::StackTrace::GetFrameCount+426608
 6: 00007FF7ED957AF1 v8::StackTrace::GetFrameCount+476145
 7: 00007FF7ED954FF0 v8::StackTrace::GetFrameCount+465136
 8: 00007FF7ED945622 v8::StackTrace::GetFrameCount+401186
 9: 00007FF7ED941095 v8::StackTrace::GetFrameCount+383381
10: 00007FF7ED36812D BIO_ssl_shutdown+189

My server.js file:
const fs = require('fs');
const pdfMake = require('pdfmake');
const axios = require('axios');

let fonts = {
    Roboto: {
        normal: 'roboto/Roboto-Regular.ttf',
        bold: 'roboto/Roboto-Bold.ttf',
        italics: 'roboto/Roboto-Italic.ttf',
        bolditalics: 'roboto/Roboto-BoldItalic.ttf'
    }
};
let printer = new pdfMake(fonts);

const jsonData = fs.readFileSync('users_100K.json', 'utf8');
const data = JSON.parse(jsonData);

console.log("dummyData", data.length);

const getRowColor = rowIndex => rowIndex % 2 === 0 ? '#CCCCCC' : null;
console.time("pdfTime");

const documentDefinition = {
  content: [
    { text: 'User Data', style: 'header' },
    {
      table: {
        headerRows: 1,
        widths: ['auto', 30, 40, 50, 40, '*'],
        body: [
          [
            { text: 'Name', style: 'tableHeader' },
            { text: 'Age', style: 'tableHeader' },
            { text: 'City', style: 'tableHeader' },
            { text: 'Friends', style: 'tableHeader' },
            { text: 'Hobbies', style: 'tableHeader' },
            { text: 'Friend Hobbies', style: 'tableHeader' }
          ],
          // flattened data
          ...data.map((user, index) => [
            { text: user.name, style: 'tableRow',  fillColor: getRowColor(index) },
            { text: user.age.toString(), style: 'tableRow', fillColor: getRowColor(index) },
            { text: user.city, style: 'tableRow', fillColor: getRowColor(index) },
            { text: user.friends.map(friend => friend.name).join(', '), style: 'tableRow', fillColor: getRowColor(index) },
            { text: user.friends.map(friend => friend.hobbies.join(', ')).join(', '), style: 'tableRow', fillColor: getRowColor(index) },
            { text: user.friends.flatMap(friend => friend.hobbies).join(', '), style: 'tableRow', fillColor: getRowColor(index) }
          ])
        ]
      }
    }
  ],
  styles: {
    header: {
      fontSize: 10,
      bold: true,
      alignment: 'center',
      margin: [0, 0, 0, 20]
    },
    tableHeader: {
      fontSize: 8,
      bold: true
    },
    tableRow: {
      fontSize: 6,
      bold: true
    }
  }
};

const pdfDoc = printer.createPdfKitDocument(documentDefinition);
pdfDoc.pipe(fs.createWriteStream('user_data7.pdf'));
pdfDoc.end();

console.timeEnd("pdfTime");
console.log('PDF generated successfully!');

**Comment by liborm85** [comment]
For big tables is require increase memory limit.
