### ISSUE TITLE
UI Interface for drag n drop PDF Editor

### ISSUE THREAD

**Issue by serikuly** [bpampuch/pdfmake#2714]
"The concept of the task is to accelerate the creation of pdf structure with the ability to drag and drop pre-made components."

![image](https://github.com/bpampuch/pdfmake/assets/38244167/bbe58905-8c7f-46f5-9e29-ea0bd7223b6a)

**Comment by mikkelking** [comment]
@serikuly Can you provide more detail on what you are thinking please?

**Comment by liborm85** [comment]
@serikuly Nice. Where can see?
