### ISSUE TITLE
TypeError: Cannot redefine property: vfs

### ISSUE THREAD

**Issue by vinch** [bpampuch/pdfmake#2716]
Hello. I'm using pdfmake in a SvelteKit (1.20) project in TypeScript and simply doing the imports via the method presented in the documentation gives me an error.

I'm doing this :

```
import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from 'pdfmake/build/vfs_fonts';

(<any>pdfMake).vfs = pdfFonts.pdfMake.vfs;
```

And I get the following error :

```
TypeError: Cannot redefine property: vfs
```

What am I doing wrong?

**Comment by YTDev** [comment]
Did you try using this to rollup config:

build: {
      rollupOptions: {
        // Add moduleContext to change 'this' context for vfs_fonts.js
        context: "window",
        moduleContext: (id) => {
          if (id.includes('pdfmake/build/vfs_fonts.js')) {
            return 'window';
          }
        },
      },
    },

**Comment by liborm85** [comment]
Resolved see https://github.com/bpampuch/pdfmake/issues/2654#issuecomment-2452944236.
