### ISSUE TITLE
page size is not set apart from default printer page size while print

### ISSUE THREAD

**Issue by jaganmeenakshi** [bpampuch/pdfmake#2719]
i have set the pagesize to A5 and while calling print method, 
print options screen opens and  shows only last assigned pagesize A4, need to change it manually

tested in chrome and firefox same scenario

my printer is : HP LaserJet Professional P1106

how to fix it

**Comment by liborm85** [comment]
Not related with pdfmake. It depends on operating system and printer drivers.
