### ISSUE TITLE
how to use css for tables ?

### ISSUE THREAD

**Issue by balajireddykasu** [bpampuch/pdfmake#272]
hi 

I am unable to find a solution for applying CSS for tables (th/td ) in particular. Lets say i want to background-color for TH, how can i do that ?

**Comment by jthoenes** [comment]
Hey,

that's not possible at the moment. Sorry.

Best regards
Johannes

**Comment by jthoenes** [comment]
Hey,

that's not possible at the moment. Sorry.

Best regards
Johannes

**Comment by jeremyml** [comment]
`fillColor` can be applied to an individual cell.

**Comment by liborm85** [comment]
CSS is not supported by pdfmake.
