### ISSUE TITLE
Items in the table are not colored with the color I indicated

### ISSUE THREAD

**Issue by Sebasapk** [bpampuch/pdfmake#2720]
Hi, as the title says some table items don't color the color I want, this problem only happens in this part, in other parts of the document with the same information doesn't happen.

So this is how the color should look:
<img width="394" alt="image" src="https://github.com/bpampuch/pdfmake/assets/50756524/b7a2c19f-5192-4cff-aab3-228e94cab676">

But instead It's coloring the rest of the column with green, so what I discover is that any color you paint in the item table "¿Quiénes?" in that part of the table, that color will cover the rest of the column so no matter what colors your paint below that item "¿Quiénes?", it won't appear.
![image](https://github.com/bpampuch/pdfmake/assets/50756524/c68da4b2-57e7-4291-b4db-32694bda438d)

This can be replicated in the PDF Make playground, here's the content:
https://pastecode.io/s/92omympc

**Comment by liborm85** [comment]
Fix released in version 0.2.15.
