### ISSUE TITLE
Vertical alignment of text in a cell / specific cell border line width / underline a word or words in a cell

### ISSUE THREAD

**Issue by awyaawya** [bpampuch/pdfmake#2721]
is there a way to center a text vertically in a cell, custom linewidth for specific cell and is there a way to underline a word or words in a cell or in a column? tnx.

**Comment by liborm85** [comment]
- Not supported now, see https://github.com/bpampuch/pdfmake/issues/74
- [examples/pdfs/tables.pdf](https://github.com/bpampuch/pdfmake/blob/0.2/examples/pdfs/tables.pdf) (source: [examples/tables.js](https://github.com/bpampuch/pdfmake/blob/0.2/examples/tables.js))
- [examples/pdfs/textDecorations.pdf](https://github.com/bpampuch/pdfmake/blob/0.2/examples/pdfs/textDecorations.pdf) (source: [examples/textDecorations.js](https://github.com/bpampuch/pdfmake/blob/0.2/examples/textDecorations.js))
