### ISSUE TITLE
On downloading the pdf in Kannada Language in my angular application. i'm getting the following error core.js:15724 ERROR Error: Uncaught (in promise): File 'NotoSansKannada.ttf' not found in virtual file system

### ISSUE THREAD

**Issue by nagashreehr** [bpampuch/pdfmake#2723]

**Comment by nagashreehr** [comment]
your help in this issue is much appreciated.

**Comment by liborm85** [comment]
See documentation, how to use custom fonts: https://pdfmake.github.io/docs/0.1/fonts/custom-fonts-client-side/

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.

**Comment by nagashreehr** [comment]
[kannada-pdf-generator.zip](https://github.com/bpampuch/pdfmake/files/15251466/kannada-pdf-generator.zip)

**Comment by nagashreehr** [comment]
@liborm85, please take a look at code attached and provide some guidance on how to fix the issue? Your expertise would be greatly appreciated!

**Comment by liborm85** [comment]
Example is not complete, package.json is not available then it cannot be installed dependencies and there is no way to run it.

I think you don't have NotoSansKannada font in vfs_fonts.js file.

**Comment by nagashreehr** [comment]
![image](https://github.com/bpampuch/pdfmake/assets/57983015/0661a3d9-a25b-4d2a-962e-a3771629e7ae)
I have attached the screenshot of the vfs_fonts.js
While uploding the whole example I found that I cant upload more than 25MB.
and I have attached the package.json file for you reference and I have mailed you the entire example project
[package.json](https://github.com/bpampuch/pdfmake/files/15329736/package.json)

**Comment by liborm85** [comment]
I don't know how angular does it, but if is pdfmake/build/vfs_fonts.js file is generated with NotoSansKannada font angular still sees file with default Roboto font.

I changed this [line](https://github.com/nagashreehr/pdfmake_Example/blob/d76d2ed4f9d63da42248c0e5d96727cdccd4633b/src/app/app.component.ts#L3) from `import * as pdfFonts from 'pdfmake/build/vfs_fonts.js';` to `import * as pdfFonts from './vfs_fonts.js';` and copy `vfs_fonts.js` file to app folder (and copy vfs_fonts.d.ts from node_modules\@types\pdfmake\build\ to app folder). Now it works without errors.

**Comment by nagashreehr** [comment]
@liborm85  I tried changing the import statement and also I copy the vfs_fonts.js and copy the vfs_fonts.d.ts and I encountered with the error as
![image](https://github.com/bpampuch/pdfmake/assets/57983015/f3cd8197-ca9f-4e17-a754-90a4c9aeae9f)

**Comment by liborm85** [comment]
Here is fixed working repo: https://github.com/liborm85/nagashreehr-pdfmake_Example and link to commit with changes: https://github.com/liborm85/nagashreehr-pdfmake_Example/commit/515e012f03314e621f77253e0445683b5231d409

**Comment by nagashreehr** [comment]
@liborm85 Can I add two different fonts in vfs_fonts.js with the above changes in app folder

**Comment by liborm85** [comment]
yes, you can add all fonts you need.

**Comment by nagashreehr** [comment]
Thank you for your assistance with this issue and for taking the time to help resolve it.
