### ISSUE TITLE
Page breaks automatically and the background get over the rest of the information;

### ISSUE THREAD

**Issue by JesusAdson** [bpampuch/pdfmake#2727]
First Page
![Captura de Tela 2024-05-15 às 12 38 29](https://github.com/bpampuch/pdfmake/assets/57694787/9b911ec2-8dc5-4850-b452-81b4b7dd8c57)

Second Page
![Captura de Tela 2024-05-15 às 12 39 17](https://github.com/bpampuch/pdfmake/assets/57694787/7972746e-5d21-46ae-b62c-08d36caeab5b)

I have a table to list the data and it gets in a point that it breaks the page, however the background break the page; 

I can't know when the page is breaking so I can't use the pageBreak: "after"

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
