### ISSUE TITLE
Problem setting the paper size when trying to print

### ISSUE THREAD

**Issue by RobertMercieca** [bpampuch/pdfmake#2729]
I have some documents which are `A4` and `A5`. I set the `pageSize` appropriately but the paper size when trying to print in chrome remains as `Letter` and I have to manually set it each time. 

Anyone has a solution to this?

**Comment by liborm85** [comment]
It is out of scope pdfmake. It depend on printer and printer drivers. If I look in properties of pdf document sizes are correct.

**Comment by RobertMercieca** [comment]
Makes sense, will be closing the issue, thanks!
