### ISSUE TITLE
document with variable height (no paging)

### ISSUE THREAD

**Issue by credli** [bpampuch/pdfmake#273]
Hi,

I am trying to build a receipt-like document using this library and I wonder if I can specify a custom pageSize with width defined, but without a height so it can grow as much as the content needs.

Is there a way to accomplish this with the current API?

Thanks for this awesome library btw!

**Comment by jthoenes** [comment]
Hmm, interesting. That is currently not supported, but could be, I think.

Unfortunately I don't have the time, to work on it. But I'm happy to help out giving guidance when you want to work on a pull request.

**Comment by credli** [comment]
Thanks Johannes, I did fork the repo, can you guide me to which js class is responsible for adapting the page size?

**Comment by jthoenes** [comment]
The engine uses ``DocumentContext.availableHeight`` to determine when to do a page break. It gets initialised here: https://github.com/bpampuch/pdfmake/blob/master/src/documentContext.js#L116

I was thinking along the line of setting the pageHeight to ``Infinity`` for the layoutProcess (``LayoutBuilder``), and than calculating & setting the real page height just before returning the pdfkit document.

**Comment by credli** [comment]
Without understanding who LayoutBuilder works it would be impossible for me to do it :) But thanks anyway for keeping this open.

**Comment by liborm85** [comment]
Implemented. https://github.com/bpampuch/pdfmake/commit/9fae1d8e92f38ad0297a4828fba78880a09d3892
