### ISSUE TITLE
Slow StyleContextStack.autopush() for large table

### ISSUE THREAD

**Issue by estanglerbm** [bpampuch/pdfmake#2732]
The `styleProperties.forEach()` in `StyleContextStack.autopush()` takes significant time for a large table of rows (i.e. 1,000 to 5,000 pages).

It's much faster (i.e. 14%) to skip creating the `styleOverrideObject` and just use the item itself.

This change would break three existing tests, however, that check for the number returned rather than for specific names (or lack thereof).

**Comment by liborm85** [comment]
Fixed by PR https://github.com/bpampuch/pdfmake/pull/2733.
Released in version 0.2.11.
