### ISSUE TITLE
Differents problem with differents browsers

### ISSUE THREAD

**Issue by trapero** [bpampuch/pdfmake#274]
Hello once again :-),

 First I have to say I´m adapting a Web to a mobile version, I thought It was ready but I tried only in Chrome. I use pdfmake only for the transofrmation of HTML-tables in PDF. Now I try it in some anothers browsers and I discover some issues. I´m having troubles with:

  - Chrome:
         It makes most of documents good but with one exception there are a few documents which he is able to dowload but not to open. I was searching the problem but i can´t identify. The difference with another document is a big number of columns, but I set the width with percentages.
        Note: Safari makes it. I can show you in the next two images:

Chrome PDF fail to open, but good downloading an show after the download, only fails to open, the next image represent the document:

![chrome-table](https://cloud.githubusercontent.com/assets/9141232/7368076/00c4fc60-eda5-11e4-919d-1a8f2d6c973d.jpg)

Safari Image of the same table:

![safari-table](https://cloud.githubusercontent.com/assets/9141232/7368169/d30134dc-eda5-11e4-97cb-6394920e3d4d.jpg)

  - Firefox, I use the last version of Firefox, It makes no reaction to open() or download() in all documents (all work fine on Chrome and Safari), but rarely the examples of pdfmake.org/playground.html are working fine.

  - Safari, works 100%

  - Opera works 100%

 I want to say that the tool works very fine, and I accomplished a big amount of HTML-tables to transform, I have only troubles with open() in Chrome and with open() and download() in Firefox, nowdays we can install in our Handys, Chrome and Firefox (I have self an iPhone with Chrome), and I would like to make it work on both.

I´m very thanks for your work.

With best regards

**Comment by gnibeda** [comment]
I have the same issue

**Comment by jthoenes** [comment]
This is a problem with data urls. I created an issue for that, because other people also have experienced to it.

If you have any information on how to fix it, please add it to #275
