### ISSUE TITLE
Displaying footer on everypage when generating PDF through HTML

### ISSUE THREAD

**Issue by imad-haq** [bpampuch/pdfmake#2744]
Hi,

I cannot display footer on everypage when generating PDF through HTML.
here is what I'm doing for displaying footer on every page:

`
#footer {
        position: running(footer);
        color: #003B5C;
        font-size: 10px;
        font-family: Mulish;
    }
    @media print {
        @page {
            size: A4;
            margin-top: 40px;
            margin-bottom: 40px;
            @bottom-left {
                content: element(footer);
            }
        }
    }
`
"<div id="footer">testing footer</div>"
Is it evern possible to display footer when generating PDF through HTML? If yes what is the solution?

**Comment by liborm85** [comment]
pdfmake doesn't support HTML source. Ask author of library you are using for conversion.
