### ISSUE TITLE
Query regarding use of polyfill.js in pdfmake

### ISSUE THREAD

**Issue by SrujanKeskar** [bpampuch/pdfmake#2746]
This is regarding the current controversy with the polyfill.io server being compromised and inject malware in sites using the library.

https://sansec.io/research/polyfill-supply-chain-attack

Since pdfmake also uses some polyfill.js code, just wanted to understand if it would be of any concern for applications using pdfmake.

**Comment by liborm85** [comment]
pdfmake does not use polyfill.io
