### ISSUE TITLE
Uncaught (in promise) File 'Roboto-Regular.ttf' not found in virtual file system

### ISSUE THREAD

**Issue by maheshcodes12** [bpampuch/pdfmake#2747]
Font file is not found in the package. Code is working well on localhost but not when hosted.

**Comment by liborm85** [comment]
Roboto fonts are available in package in path /build/vfs_fonts.js.

**Comment by Aymkdn** [comment]
I had the same problem. I found the answer [there](https://pdfmake.github.io/docs/0.1/getting-started/client-side/#npm), and I had to do `pdfMake.addVirtualFileSystem(pdfFonts);`
