### ISSUE TITLE
Some DataUrls don't work since Chrome 42.0.2311.60

### ISSUE THREAD

**Issue by jthoenes** [bpampuch/pdfmake#275]
The ``open()`` function does not work anymore for a lot of PDFs that worked previously to Chrome ``42.0.2311.60``.

My assumption is, that the data urls are getting to large. Don't know if we can fix it.

**Comment by compact** [comment]
This issue appears to only happen with Chrome PDF Viewer, which has replaced the Adobe Reader plugin in Chrome 42.

I just tried the following:

In Chrome 42.0.2311.135 in Windows, with the default Chrome PDF Viewer, the playground PDFs `columns`, `lists`, and `images` don't render (grey screen). When I enable Adobe Reader plugin via `chrome://flags/#enable-npapi` and `chrome://plugins/`, they all work.

In Chrome 42.0.2311.90 in Linux, these playground PDFs don't render with Chrome PDF Viewer: `columns`, `tables`, `lists`, `margin`, `images`.

**Comment by djehring** [comment]
I am experiencing problems with the OS-X version of Chrome (Version 42.0.2311.135 (64-bit)):
1. print() causes an error:
Resource interpreted as Document but transferred with MIME type application/pdf: 

2. open() displays an empty document.

The latest windows version (Version 42.0.2311.135 m) seems to work fine

**Comment by gnibeda** [comment]
@compact As I know npapi will be removed soon, so this is temporary solution. If this is chrome bug, the only way is pdf.js to display pdf files.

**Comment by gnibeda** [comment]
Seems that in 43.0.2357.65 m this issue was fixed. In my case all pdf now displayed correctly with internal chrome pdf viewer. Anyone have this issue on new chrome?

**Comment by kmather** [comment]
It appears fine in the new version of Chrome. In the older versions it would not open large PDFs (for me this was ~100 rows)

**Comment by djehring** [comment]
Just checked in 43.0.2357.81 and now all is working fine

**Comment by jthoenes** [comment]
Alright - apparently some bugs resolve themselves just by waiting :-)

Please feel free to comment on this issue, should you experience it again.

**Comment by ragefuljoe** [comment]
On osx chrome 45.0.2454.37 beta (64-bit), open and print aren't working for me :(

**Comment by the86freak** [comment]
on win chrome 45.0.2454.85 m open doesn't work

**Comment by limenet** [comment]
I was just about to comment and complaining this bug is still present in Chrome 47.0.2522.0 dev-m (64-bit) when I opened the Chrome settings to get the version number and was presented with an update. And guess what? It now works in the most recent dev-channel build of Chrome: 47.0.2526.5 dev-m (64-bit)!

(The reason I post this is for others to see a) it's a Chrome bug and b) it's (at least for the time being) fixed :smiley:)

**Comment by DavidYCZhou** [comment]
Version 47.0.2526.106
Latest Chrome so far, still have problem exporting large amount data.
Is it possible to provide a download method instead of opening it?

**Comment by james-bell** [comment]
Why is this issue closed when it clearly is still happening?  Using Chrome 48.0.2564.82 m and it works perfectly if the dataset is small (less than about 200-300 rows with about 10-12 columns).  Anything larger than that fails silently with a blank open window in Chrome.

**Comment by gwen0504** [comment]
still failing? no workaround?

**Comment by creaturerigger** [comment]
.print() isn't working with Chrome 50.0.2661.102 (64-bit) on Mac OS X 10.10.5. Any suggestion?

**Comment by DevQueen** [comment]
I'm having the same issue.  Failing in Chrome with large dataset with the latest version of Chrome Version 53.0.2785.116 m.  It succeeds in IE but takes a very long time.  No work around yet?

**Comment by ramaseshulukka** [comment]
@jthoenes  I am facing issue with having more than 300 records with data uris images as header and footer . please reopen this bug as its not yet fixed.
chrome version : 53.0.2785.143

**Comment by kristofvanwoensel** [comment]
I have the same issue...when I use print() function it sais: Resource interpreted as Document but transferred with MIME type application/pdf:

**Comment by prtome** [comment]
Same issue, Chrome 55.0.2883.95 (64-bit) on OSX 10.12.2

Any idea of how to force it ?

**Comment by bhagyamaheshi** [comment]
Same issue with Chrome Version 56.0.2924.87 on Windows 7 (64-bit).
Seems working fine in Firefox

**Comment by janainaemilia** [comment]
I have seen a comment with some solution that works for me!
Follow:

"If anyone else is experiencing this on the current v0.1.27, first check you have whatever flavour of ad blocker you may have turned off. That's coming from a guy who definitely didn't accidentally turn on uBlock Origin in his dev environment..." - jmcgrory-plx

**Comment by kevinkleine** [comment]
This seems to work for me: 

```
const iframe = document.createElement( 'iframe' )

document.body.appendChild( iframe )  // don't forget to append your iframe to the DOM

const doc = {[ ... ]}

pdfMake
    .createPdf( doc )
    .open( {}, iframe.contentWindow )
```
