### ISSUE TITLE
Table border extends outside the table when table spans across multiple pages

### ISSUE THREAD

**Issue by shoh1129kr** [bpampuch/pdfmake#2750]
Hello,

I am using PDFMake to generate PDF documents. I have encountered an issue where the border of a table extends outside the table when the table spans across multiple pages due to its length.

![화면 캡처 2024-07-08 171245](https://github.com/bpampuch/pdfmake/assets/175002370/3142de88-48b7-46c4-8ab7-c0fea291127f)

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
