### ISSUE TITLE
Line issue while table starts in new page

### ISSUE THREAD

**Issue by Tiru150837** [bpampuch/pdfmake#2753]
While I generate a PDF, If there is a table which can starts in new page...that time the line is coming with respective spaces given. I don't understand how should I resolve that issue. That is overlapped the footer as well even I given page margins properly.

Can you please give me the solution to it?

Thanks In advance

**Comment by liborm85** [comment]
[CONTRIBUTING.md](https://github.com/bpampuch/pdfmake/blob/master/.github/CONTRIBUTING.md)
