### ISSUE TITLE
Pdf layout breaks when table has headerRows = 0 and keepWithHeaderRows > 0

### ISSUE THREAD

**Issue by fe-cj** [bpampuch/pdfmake#2754]
In the example below, there is just one table but if there are more elements it also affects them. So for example:
```
var dd = {
	content: [
	{
            table: {
                body: [
                    [ 'A', 'B' ],
                    [ 'C', 'D']
                ],
                keepWithHeaderRows: 1,
                headerRows: 0
            }
        },
	]
	
}
```
![image](https://github.com/user-attachments/assets/cae2ed4a-17b5-4271-a9bc-44c742425312)

When headerRows is set to 1, it does it correctly:
```
var dd = {
	content: [
	{
            table: {
                body: [
                    [ 'A', 'B' ],
                    [ 'C', 'D']
                ],
                keepWithHeaderRows: 1,
                headerRows: 1
            }
        },
	]
	
}
```
![image](https://github.com/user-attachments/assets/71da6435-da48-4f5e-867d-8188363706b0)

**Comment by liborm85** [comment]
Fixed by PR https://github.com/bpampuch/pdfmake/pull/2759.
Released in version 0.2.11.
