### ISSUE TITLE
How should we hide the header and footer sections for some of the pages

### ISSUE THREAD

**Issue by Tiru150837** [bpampuch/pdfmake#2755]
I have a dynamic content with several sections. I don't want header and footer for some of the sections. Then how should we achieve this without knowing the page numbers of those sections. Because they are dynamically adding to the pdf.

Is there any way to achieve it?

Thanks in Advance
G Lakshmi

**Comment by liborm85** [comment]
Without knowing page numbers actually is not possible. Feature request is here: https://github.com/bpampuch/pdfmake/issues/283
