### ISSUE TITLE
Bower installed version of the library overrides global scope lodash

### ISSUE THREAD

**Issue by moberemk** [bpampuch/pdfmake#276]
When updating to `pdfmake#0.1.18` from `pdfmake#0.1.15` my team ran in to trouble with this file overriding the global lodash variable from our included lodash 3.7.x version to the 3.1.0 version included by `build/pdfmake.js`. The issue seems to exist since at least 0.1.17 and means we're reverting to 0.1.15 until it's addressed since we need features available since lodash 3.5.

**Comment by jthoenes** [comment]
I think the appropriate solution would be, to not include lodash in pdfmake when already present. Do you have an idea how to configure that in bower?

**Comment by moberemk** [comment]
To my knowledge that's not really possible; lodash is being included in the built JS file which is distributed by the package. Two potential solutions I can think of here are to wrap pdfmake in a closure and only expose the necessary portions of the library on the global scope or provide a lodash-less alternative build in the `build/` directory for people working in environments where lodash is available.

**Comment by colorfulgrayscale** [comment]
+1

0.1.18 crashes my app. I've been using lodash 3.8.0, and now several of the _ functions are not found.

**Comment by trentvb** [comment]
+1, really like the library. Would be nice if it didn't clober lodash in the process.

**Comment by nthnmldr** [comment]
+1

This threw me for a loop when I thought I was using lodash 3.9.3 but it kept showing as 3.1.0.  temp solution is to move lodash after pdfmake in my BundleConfig so the version I want loads last and takes priority, although I am loading two lodash libraries now...

**Comment by ollwenjones** [comment]
+1 We just ran into this today. I understand bundling dependencies with webpack for a deployed product, but is it common practice for a library that developers will use in their product to bundle its dependencies in the same way? It seems like common libraries would multi-embedded constantly if this were the case.

**Comment by tiengtinh** [comment]
+ I also had this today. It was a hard time for me to finally figuring out this. I was trying to use _.mapKeys but got error method undefined. I checked lodash source code and see the function there. I tried upgrade lodash from 3.10.0 to 3.10.1 with hope this will help, but notthing happen. Finally, from dev debug tool, I managed to trace out that all lodash call this currently call to pdfmake.js, not lodash.js. That was a really confusing time for me. Hope that this will be resolved soon.

**Comment by azakharo** [comment]
+1

**Comment by SergioMacGyver** [comment]
+1

**Comment by lobo-tuerto** [comment]
+1

**Comment by prostoandrei** [comment]
+1

**Comment by FinnStutzenstein** [comment]
+1

**Comment by jpammerlaan** [comment]
+1

**Comment by csvan** [comment]
+100, this is a HUGE issue. There was a PR to fix it but I am not certain it did: https://github.com/bpampuch/pdfmake/pull/443

**Comment by liborm85** [comment]
Fixed by https://github.com/bpampuch/pdfmake/pull/443.
