### ISSUE TITLE
Error when building the project using pdfMake in my React Vite project

### ISSUE THREAD

**Issue by YashBaldotaDS** [bpampuch/pdfmake#2765]
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts"; // Use wildcard import to get all exported members

pdfMake.vfs = pdfFonts.pdfMake.vfs;

Here are the imports I am using. I am getting the following error during build
"default" is not exported by "node_modules/pdfmake/build/vfs_fonts.js", imported by ".....".

**Comment by liborm85** [comment]
Resolved see https://github.com/bpampuch/pdfmake/issues/2654#issuecomment-2452944236.
