### ISSUE TITLE
Canvas location changing on every call

### ISSUE THREAD

**Issue by andrewhamili** [bpampuch/pdfmake#2768]
https://github.com/user-attachments/assets/4d5bdcc8-16b4-4b9c-a4c3-7edd6abdb1a3

**Comment by andrewhamili** [comment]
Refer to latest code for replication [https://github.com/andrewhamili/nestjs-pdfmake](url)

**Comment by andrewhamili** [comment]
Any updates here?

**Comment by liborm85** [comment]
`docDefinition` can be used only once. If you need to generate multiple times is need clone/copy original `docDefinition` and it pass into pdfmake. See https://github.com/bpampuch/pdfmake/issues/1576
