### ISSUE TITLE
Font problems after upgrading to pdfmake v0.1.18 from v0.1.17

### ISSUE THREAD

**Issue by renatoargh** [bpampuch/pdfmake#277]
I don't know what the problem is exactly, but running **the same code** with `v0.1.18` gives me a broken pdf, and if I roll back to `v0.1.17` everything becomes correct again.

Here you can see what happens;

## v0.1.18
![screen shot 2015-05-01 at 2 28 20 pm](https://cloud.githubusercontent.com/assets/522043/7434133/6a5fc75c-f00e-11e4-8986-f5fd7099d4a0.png)

## v0.1.17
![screen shot 2015-05-01 at 2 29 14 pm](https://cloud.githubusercontent.com/assets/522043/7434138/7934f89c-f00e-11e4-9fb1-8f8d3e401fbf.png)

How can I solve this problem?
Thank you very much for you great work!

**Comment by jthoenes** [comment]
Can you provide both pdfs?

This might be an issue with #221.
How did you create the pdfs?

**Comment by renatoargh** [comment]
Sure I can! Will upload it and send you later today!

**Comment by renatoargh** [comment]
@jthoenes here are both files

- [v0.1.17 - The good one](https://s3-sa-east-1.amazonaws.com/gammasoft/PDF+-+v0.1.17.pdf)
- [v0.1.18 - The broken one](https://s3-sa-east-1.amazonaws.com/gammasoft/PDF+-+v0.1.18.pdf)

**Comment by jthoenes** [comment]
Ok, seems like ````undefined```` ends up in the PDF to often. Can you share the document definition for it? (sorry ... should have asked for it from the start)

**Comment by renatoargh** [comment]
Of course I can, but its mostly in portuguese, so I'm afraid it doesn't help. Also, I have a generic thing to create tableish reports.

https://gist.github.com/renatoargh/2ea8d7c60df1a78e135f and https://gist.github.com/renatoargh/8d9fa5c385021d0b2760

**Comment by jthoenes** [comment]
The first one (https://gist.github.com/renatoargh/2ea8d7c60df1a78e135f) would help, if you could give me some simple sample data to call the module.exports function.

There seems to be something wrong with the encoding of the font, turning encodedText and fontId into ``undefined``.

**Comment by renatoargh** [comment]
The second gist is actually the call to this module.exports function. If you call its exports function with this data: https://gist.github.com/renatoargh/944432bfa728c8a10b91 (array with two records) instead of `vendas.rows` you will be able to reproduce the problem! Do you want me to send the font files as well?

**Comment by jthoenes** [comment]
This fixes the issue: https://gist.github.com/jthoenes/4668e810f233d6fd101f/revisions.

You did not specify a default font, therefore no font was defined. The old fallback worked by accident (it fell back to the only existing font - which was times). Now it's no longer working.

I'm thinking how pdfmake should handle that. Probably throw an error when the font is not defined?

It's visible here: https://github.com/bpampuch/pdfmake/blob/master/src/fontProvider.js#L35
