### ISSUE TITLE
How to pipe in 0.3.0

### ISSUE THREAD

**Issue by benquan** [bpampuch/pdfmake#2777]
I am trying to stream the answer directly to an endpoint using 0.3.0

In version 0.2.0 I used to do it lke this:
```
var pdfDoc = printer.createPdfKitDocument(docDefinition, options);
pdfDoc.end();
```

and then pdfDoc could be directly piped to an endpoint without turning it to a file.

in version 0.3.0 the doc example is as following:

```
var pdf = pdfmake.createPdf(docDefinition);
pdf.write('document.pdf').then(() => {
  // success event
}, err => {
  // error event
  console.error(err);
});
```

but there is no **pipe()** method or **end()** method, I can only find **write** (which does actually output the pdf to th filesystem).

How can I stream directly to the endpoint using the beta version?

**Comment by benquan** [comment]
Thanks!

Your code led me to the my final solution to stream directly by using getBuffer(). So the final replacement code was:

```
var pdf = pdfmake.createPdf(dd);
const pdfDoc = pdf.getBuffer();
```

Typescript is missing to accessing these methosds easier.

**Comment by elawad** [comment]
FYI for others running into this.
Using `getBuffer()` is not a true stream. Data will be read in memory.
Use `getStream()` to get a proper stream to pipe to response, S3, etc.
