### ISSUE TITLE
DEPLOY ERROR ON VERCEL

### ISSUE THREAD

**Issue by Yuta4u** [bpampuch/pdfmake#2780]
vercel error logs:
![image](https://github.com/user-attachments/assets/2a2fa79d-7731-4be2-b01f-ea1f86e1a5bd)

my code:
![image](https://github.com/user-attachments/assets/45b374fa-3520-4fd5-9dca-94ae9736a44a)

I have tried using both methods above, but the error logs are still there

**Comment by liborm85** [comment]
Resolved see https://github.com/bpampuch/pdfmake/issues/2654#issuecomment-2452944236.
