### ISSUE TITLE
PdfMake not working inside Redux Toolkit Provider

### ISSUE THREAD

**Issue by yasiraktunc** [bpampuch/pdfmake#2784]
Hello,

I'm encountering an issue with the pdfMake package when using it inside a project that is wrapped with a Redux Toolkit provider. When the provider is present, pdfMake fails to work as expected. However, when the Redux Toolkit provider is removed, everything functions correctly.

 For example

import React, {useEffect, useState} from 'react';
import {Provider} from 'react-redux';
import MakePdf from '@/components/MakePdf';

function App(): JSX.Element {
   return (
    <>
// Its not working 
     ` <MakePdf></MakePdf>
      <Provider ></Provider>`

//ıts working
      `<MakePdf></MakePdf>`
    </>
  );
}
export default App;

**Comment by mhmtyasr** [comment]
if ı use this version 0.1.72. Its working true with provider

**Comment by liborm85** [comment]
MakePdf component is not part of pdfmake. Try ask author of this component.
