### ISSUE TITLE
table border issue

### ISSUE THREAD

**Issue by Tiru150837** [bpampuch/pdfmake#2788]
the content which my pdf has dynamic one. There is a table format for some of the portion. Whenever a table starts in a new page, the border of the table is also coming to the previous page. 

How should I resolve it?

Thanks in advance,
G Lakshmi

**Comment by fe-cj** [comment]
It is not possible to understand what your problem is. You should share a doc definition so people can reproduce your issue in the [playground](http://pdfmake.org/playground.html)
