### ISSUE TITLE
percentage character with DecodeURIComponent

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#2793]
Namaste,

We can simply print the % character as, ` var dd = {content: ['%' ] }` but with decodeURIComponent `var dd = {	content: [decodeURIComponent('%')]}` it gives error.  At the same time, decodeURIComponent of other charecters like &, $, #, @ etc are just working fine.

Why it is so? Can anyone suggest the work around for the above issue.

**Comment by liborm85** [comment]
How does this relate to pdfmake?

**Comment by mpsbhat** [comment]
My case is, there is a dynamic string getting printed and the string is using decodeURIComponent to decode the ncoded parts in the string  before printing. But in between there maybe % charecter too which causing the error in printing. So, I just wanted to know the exact reason for why it is giving such error?

**Comment by liborm85** [comment]
`%` is invalid encoded URI therefore cannot be decoded by function decodeURIComponent. pdfmake won't help you with that.
You must correctly encode the text before transmission:
`encodeURIComponent('%')` return right encoded string `'%25'`, then this example works:
```js
var dd = {content: [decodeURIComponent('%25') ] }
```
