### ISSUE TITLE
How to add standalone pageBreak?

### ISSUE THREAD

**Issue by yurakhomitsky** [bpampuch/pdfmake#2794]
In my application, I'm dynamically building PDF content sections and I want after each section add a page break because the content itself doesn't know if it's the last to add a page break so a section needs to add a page break after all content is gathered. 

But I add a page break with an empty text. I feel like it's a hack maybe I should modify the last element of the content to add a pageBreak there? What is the best way to add a pageBreak to signify a new page without providing empty content?

```
public getContent(): Content[] {
    if (!this.config.includedInPrint) {
      return [];
    }
    const content = this.pdfContent.map((content) => content.getContent());

    if (this.config.pageBreak) {
      content.push({ text: '', pageBreak: 'after' });
    }

    return [{ text: this.title, style: ['header', 'primaryColor'] }, ...content];
  }
```

**Comment by liborm85** [comment]
You can use `pageBreak: 'before'` in first node in section. But don't put in first section, it shouldn't be hard to figure out that this is first section.
