### ISSUE TITLE
pageBreak before drops column text

### ISSUE THREAD

**Issue by OS4** [bpampuch/pdfmake#2807]
Adding a pageBreak: 'before' on the cells in the first column of a table results in the column text being dropped. My structure is:

{
    stack: [{
        text: orderId.replace(/<br>/g, "\n"),
        bold: true
    }],
    id: 'col1-' + colId,
    pageBreak: 'before'
},

**Comment by liborm85** [comment]
Attach runnable example for reproduce issue.
