### ISSUE TITLE
Is there a way to prevent orphan/widow objects?

### ISSUE THREAD

**Issue by hujhax** [bpampuch/pdfmake#281]
(Sorry to keep bothering you guys -- hopefully this one is pretty straightforward...)

Say I have a heading "table 1" and then a table, and I won't ever want a page break between those two.  

Is there a way to tell pdfmake never to put a page break between the heading and the table? or between any given pair of items?

**Comment by jthoenes** [comment]
Use the ``pageBreakBefore`` function as described in #202.

**Comment by hujhax** [comment]
Thanks!  However, I discovered a pretty heavy performance penalty for `pageBreakBefore`, as per https://github.com/bpampuch/pdfmake/commit/b31c3811262127abfc41ac029c62f9082a1a2c4a.

I was hoping it would be easy to, in this case, add something like "forbidPageBreakAfter: true" to the heading, and then have the initial layout pass glom the heading together with the table, for purposes of pagination, without incurring a performance problem.  And it seems like that would handle the most common widow/orphan use case, right?  I'll keep plugging through the code to see if there's an easy way to implement this...

**Comment by jthoenes** [comment]
A ``forbitPageBreakAfter`` functionality is exactly what we cannot do, the way pdfMake is working. If a line (e.g. headline) is set on a page, it is assumed to be placed. A logic like this would be very complex - and much less flexible than ``pageBreakBefore``. 

I would rather try to understand why ``pageBreakBefore`` is taking so much time and try to improve its speed (probably by reducing memory footprint).

**Comment by hujhax** [comment]
Point taken -- thanks for the further info about how the code works.  I, too, wonder what's hitting performance so hard with `pageBreakBefore`...
