### ISSUE TITLE
NaN error when creating a multi page table with v.0.2.15

### ISSUE THREAD

**Issue by JMBHaufe** [bpampuch/pdfmake#2815]
Hi there,

We faced a new error when updating from 0.2.14 to 0.2.15. (node: 18.20.5),
We got a landscape table with 7 columns and normal text data (string) in each row. In the past we were able to render tables up to 10 pages long. Now, whenever we reach a certain value of rows (+- 4 pages of table), we run into an error during pdf creation. When the rows are empty, the table can be longer.
This is the error message:

![image](https://github.com/user-attachments/assets/01475f69-d534-4ef6-97a3-9a81754efc50)

**Comment by liborm85** [comment]
Attach runnable example on [playground](http://pdfmake.org/playground.html) for reproduce issue.
