### ISSUE TITLE
Link from text broken

### ISSUE THREAD

**Issue by tinohager** [bpampuch/pdfmake#2821]
When a link is automatically generated from text, the combination fl causes a letter to be omitted in the resulting link. This issue appears to affect the proper rendering of such links.

`www.flow.com` -> `www.low.com` missing `l`

```
{
    text: 'www.flow.com'
}
```

[Download.pdf](https://github.com/user-attachments/files/18079916/Download.pdf)

**Comment by liborm85** [comment]
`text` node in pdfmake is not automatically a link.
To define a link, pdfmake requires the link property:
```js
var dd = {
	content: [
		{
			text: 'www.flow.com',
			link: 'www.flow.com'
		}
	]
}
```

In your case, the PDF viewer is attempting to interpret the text as a link. This behavior is not part of pdfmake, but rather a feature of the PDF viewer you're using.

**Comment by tinohager** [comment]
i don't necessarily want a link. i just put the url in. I can prevent “www.flow.com” from being converted into a link. It is still very strange that a character gets lost and then I get a link that points somewhere else.

**Comment by liborm85** [comment]
This is Pdf viewers "feature", it is not related with pdfmake, can't influence it. You can try ask on Chrome support.
