### ISSUE TITLE
Text does not wrap when word contains "/"

### ISSUE THREAD

**Issue by Glenn271** [bpampuch/pdfmake#2822]
In the PDF, there is a linebreak in the middle of the word with a slash.

Would expect this (whole word to go to new line):
![image](https://github.com/user-attachments/assets/2bae3ac6-6d31-477b-bec6-f5cc9edc412e)

But in the PDF it appears like this:
![image](https://github.com/user-attachments/assets/ca4c8f59-12eb-4394-8426-d9ead3e23fa4)

Another example of how it should appear vs how it looks:
![{EB0E0BC8-5C86-40BF-BE2B-253B37A93EFE}](https://github.com/user-attachments/assets/4fadf8bf-157e-47ad-a904-75eca164f16d)
![{721052C9-CF62-44D1-B5F8-658018E83773}](https://github.com/user-attachments/assets/f1d8ba34-e0cc-405f-bd82-d0b319c46454)

**Comment by liborm85** [comment]
pdfmake using Unicode Line Breaking Algorithm (`UAX #14`) for splitting words via [linebreak](https://github.com/foliojs/linebreak) library. By `UAX #14` is `/` character to split word and break line.

If you don't want to wrap some texts, you can use `noWrap` property, example:
```js
var dd = {
	content: [
	    {
	        text: [
	           'One of the select is at line 136 of method ',
	           {text: '/VWK/IF_GFT_BC203_SUBST_BSEG—PROCESS ', noWrap: true},
	           'of class ',
	           {text: '/VWK/CL_GFTKK299_RID_BSEG_S001', noWrap: true},
	           ':'
	        ]
	    },
	]
}
```

**Comment by Glenn271** [comment]
> pdfmake using Unicode Line Breaking Algorithm (`UAX #14`) for splitting words via [linebreak](https://github.com/foliojs/linebreak) library. By `UAX #14` is `/` character to split word and break line.
> 
> If you don't want to wrap some texts, you can use `noWrap` property, example:
> 
> ```js
> var dd = {
> 	content: [
> 	    {
> 	        text: [
> 	           'One of the select is at line 136 of method ',
> 	           {text: '/VWK/IF_GFT_BC203_SUBST_BSEG—PROCESS ', noWrap: true},
> 	           'of class ',
> 	           {text: '/VWK/CL_GFTKK299_RID_BSEG_S001', noWrap: true},
> 	           ':'
> 	        ]
> 	    },
> 	]
> }
> ```

only trouble is when we're generating a PDF, the text is getting pulled straight from a textbox on the page. So would we have to manually extract these slashes words and break up the docDefinition ourselves? might not be feasible for large PDFs

**Comment by liborm85** [comment]
Yes, that's right.
