### ISSUE TITLE
possible one-line optimization to renderLine

### ISSUE THREAD

**Issue by hujhax** [bpampuch/pdfmake#284]
I was working on optimizing pdfMake, and AFAICT, this transform in `renderLine`:

```
pdfKitDoc.transform(1, 0, 0, -1, 0, pdfKitDoc.page.height);
```

... ٭always٭ evaluates to this code:

```
pdfKitDoc.addContent("1 0 0 -1 0 " + pdfKitDoc.page.height + " cm");
```

`renderLine` gets called so often (at least on my PDFs) that this minor change gave me a noticeable speedup.

Worth a pull request? or does this introduce a bug I'm not seeing?

**Comment by jthoenes** [comment]
Hm, I'm not sure what this line is for. @bpampuch What do you think?

**Comment by bpampuch** [comment]
I'm not aware of any negative consequences if we remove this, but I don't remember why I've decided to use this ;//. 

If all tests pass without this line, let's get rid of it ;)

**Comment by devongovett** [comment]
That flips the PDF coordinate system, which has the origin in the bottom left corner of the page instead of the top left. Without that line, text that is supposed to be at the top of the page will render upside down at the bottom of the page.

**Comment by liborm85** [comment]
Now in the renderLine are used methods from pdfkit.
