### ISSUE TITLE
Fix table sizes

### ISSUE THREAD

**Issue by Urr4** [bpampuch/pdfmake#285]
Is it possible, to fix the size of a table?
I want for example a table that has 3 columns, where the whole table has a height of 100 and every row in the first two columns has a width of 20 and the rows in the third column have a width of 30, no matter the number of rows.
This should be used, to ensure a common size for every table on a page.
I can not seem to find a solution to this and would be happy, if you could help.

Regards
Urr.4

**Comment by jthoenes** [comment]
You can only define the size of a column in pdfmake.
