### ISSUE TITLE
Remove Lodash From build

### ISSUE THREAD

**Issue by holmankb** [bpampuch/pdfmake#287]
Is is possible to remove lodash from the bower build and have it as a dependency instead?  We are using a newer version (3.8.0) than what is included and is requiring us to ensure our version is loaded after pdfmake and have the lib duplicated.

Thanks...

**Comment by jthoenes** [comment]
Good suggestion. How would I do that?

Please make a pull request or comment on #276

**Comment by coffy** [comment]
+1

**Comment by lobo-tuerto** [comment]
+1
