### ISSUE TITLE
Linespacing in pdfMake

### ISSUE THREAD

**Issue by tomconneely** [bpampuch/pdfmake#288]
I'm looking to add some space between lines of text in a paragraph. I haven't seen an option to add linespacing in pdfMake. I was looking at pdfkit and it has [the 'lineGap' option](http://pdfkit.org/docs/text.html). I've tried adding lineGap when creating my document in pdfMake but it doesn't work. Is there a way to add space between lines of text?

**Comment by jthoenes** [comment]
There is a lineHeight style available. See #202

Tom Conneely <notifications@github.com> schrieb am Do., 14. Mai 2015 12:54:
