### ISSUE TITLE
Error when bundling pdfMake in ASP.NET

### ISSUE THREAD

**Issue by tomconneely** [bpampuch/pdfmake#289]
I've run into a problem when trying to bundle pdfMake with other JavaScript files using [ASP.NET Bundling and Minification](http://www.asp.net/mvc/overview/performance/bundling-and-minification). When I include pdfMake in the bundle and I try t create the PDF document using

```
pdfMake.createPdf(dd).getDataUrl(function (outDoc) { ... });
```

I get this error "Uncaught TypeError: Cannot read property 'call' of undefined" in my browser console. If I remove pdfMake and vfs_fonts from the bundle and attach them to the page in normal script tags it works fine.

I'd like to continue bundling the JS files as much as possible to cut down on network traffic. Is this possible?

**Comment by bpampuch** [comment]
Have you tried using the minified pdfmake version instead?

**Comment by tomconneely** [comment]
Yes. It still happens with the minified version.

**Comment by liborm85** [comment]
Can you try it with latest version?
