### ISSUE TITLE
Is it possible to assign background color to a table cell?

### ISSUE THREAD

**Issue by ynfiesta** [bpampuch/pdfmake#29]
Is it possible to assign background color to a table cell?

thanks, library is awesome

**Comment by JulianHidalgo** [comment]
Hi
I'd like to create a table with alternating background colors for each row. yelouafi's original approach with the table layout would have worked for me, but I see the fillColor property is now a part of the cell's style itself, which is also practical, but not so handy for what I want. Is there any way to do this without setting a style for each row on my code? Thanks!
