### ISSUE TITLE
"No unicode cmap for font" happened when i using client version.

### ISSUE THREAD

**Issue by darkautism** [bpampuch/pdfmake#290]
I use chinese fonts in my project.
When i using server version, it work perfectly.
But when i using client version, it always alert me "No unicode cmap for font".
This is font i used : 
https://mega.co.nz/#!WddCwIjR!XVwz3BH8brUc0znBSNQ_vb_NG9iHXtW0ghlkEWz9lo8
This is vfs_fonts.js i builed :
https://mega.co.nz/#!DN9DmSYD!Nd10rPBBfTZ9OFpw7MEQm5A_wrqcQhpECH0z3RLHy-k
This is code i used :

			var fontDescriptors = { 
				times: {
					normal: 'times.ttf',
					bold: 'timesbd.ttf',
					italics: 'timesi.ttf',
					bolditalics: 'timesbi.ttf'
				} , 
				wqy: {
					normal: 'wqy.ttf',
					bold: 'wqy.ttf',
					italics: 'wqy.ttf',
					bolditalics: 'wqy.ttf'
				}
				
			};
			pdfMake.fonts = fontDescriptors;
			var docDefinition = { content: 'wqy中文wqy',
			defaultStyle: {
				font: 'wqy'
			}};

                   pdfMake.createPdf(docDefinition).open('test.pdf');

G3548817

**Comment by jthoenes** [comment]
Your font needs to have a Unicode CMAP - can you verify that is has one?

See https://github.com/devongovett/pdfkit/issues/121#issuecomment-53655273

**Comment by darkautism** [comment]
If this font do not have a Unicode CMAP, why can this run in server mode perfectly?

**Comment by jthoenes** [comment]
I don't know your setup, so I cannot answer the question. 

Assuming the CMap is present in the vfs_fonts, there might be space issue inside your browsers. Have you checked (with Chrome debugger) if it gets loaded correctly?

**Comment by darkautism** [comment]
This is server version:
http://i.imgur.com/BTJWzTv.png

It work correctly.

Because this font work correctly so i assume this font have a Unicode CMAP, but it cannot work on client version.

This is client version:
http://i.imgur.com/cVZpMRm.png

Uncaught Error: No unicode cmap for font                 

pdfmake.js:22153 Uncaught Error: No unicode cmap for fontPDFFont.registerTTF @ pdfmake.js:22153PDFFont @ pdfmake.js:22026module.exports.font @ pdfmake.js:19762FontWrapper.getFont @ pdfmake.js:14190FontWrapper.widthOfString @ pdfmake.js:14201(anonymous function) @ pdfmake.js:16133measure @ pdfmake.js:16118TextTools.buildInlines @ pdfmake.js:15941DocMeasure.measureLeaf @ pdfmake.js:14557(anonymous function) @ pdfmake.js:14437StyleContextStack.auto @ pdfmake.js:16306DocMeasure.measureNode @ pdfmake.js:14422DocMeasure.measureDocument @ pdfmake.js:14409LayoutBuilder.tryLayoutDocument @ pdfmake.js:2425LayoutBuilder.layoutDocument @ pdfmake.js:2413PdfPrinter.createPdfKitDocument @ pdfmake.js:285Document._createDoc @ pdfmake.js:81Document.getDataUrl @ pdfmake.js:160Document.open @ pdfmake.js:108onclick @ Test.html:32

**Comment by jthoenes** [comment]
Your font (one of the two) does not have a unicode cmap when it gets loaded by pdfkit - the underlying pdf engine of pdfmake.

I cannot tell why this is the case - and I don't have time to look deeper into it myself at the moment.

If you want to investigate yourself, try to use the Chrome debugger to see, what is going wrong. This might or might not be a pdfkit bug, rather than a pdfmake bug.

**Comment by hillelcoren** [comment]
+1

I believe I'm running into the same problem. I'm using the Google Noto CJK font (https://www.google.com/get/noto/#/) and I'm seeing the same error.

**Comment by darkautism** [comment]
I solved this problem.
I remove other english font (e.g. Times New Roman) and only use one Unicode CMAP fonts.
It's work.
So all of the fonts should have Unicode CMAP in client version, but sever version shouldn't.

**Comment by hillelcoren** [comment]
@darkautism 

Can you share the updated vfs_fonts.js file you're using?

Thanks

**Comment by darkautism** [comment]
https://mega.co.nz/#!zdVH3bSJ!6lN1vO5_Ty0i0rOljyJrZMConTklVjDiL_Egw6vps5I
This file only have wqy.ttf


var fontDescriptors = { 
            wqy: {
                normal: 'wqy.ttf',
                bold: 'wqy.ttf',
                italics: 'wqy.ttf',
                bolditalics: 'wqy.ttf'
            }
        };
        pdfMake.fonts = fontDescriptors;
        var docDefinition = { content: 'wqy中文wqy',
        defaultStyle: {
            font: 'wqy'
        }};

**Comment by hillelcoren** [comment]
Amazing, thanks!

**Comment by hillelcoren** [comment]
@darkautism 

I haven't been able to get it to work. Any chance you could put together a mini-sample project of Chinese working. It'd be a great help.

**Comment by marcojauregui** [comment]
Hi,

I am getting: Uncaught Error: No unicode cmap for font, I have tried with several fonts and getting same error with all fonts. Can you please help?

var fontDescriptors = {
	arial: {
		normal: 'fonts/arial.ttf',
		bold: 'fonts/arialbd.ttf',
		italics: 'fonts/ariali.ttf',
		bolditalics: 'fonts/arialbi.ttf'
	}
};

var genpdf = function() {
	pdfMake.fonts = fontDescriptors;
	var docDefinition = { content: 'wqy中文wqy',
			defaultStyle: {
	            font: 'arial'
	        }};
	 
	 pdfMake.createPdf(docDefinition).download('pdfmake.pdf');
}

**Comment by Joeper214** [comment]
+1 
I also tried the above codes. But it seems not to be working for me. Any workaround on this guys?

**Comment by hillelcoren** [comment]
We were able to get Chinese working in our project: https://github.com/invoiceninja/invoiceninja

It took us a while to find an open-source font which worked, we ended up using Ukai:

http://www.freedesktop.org/wiki/Software/CJKUnifonts/Download/

**Comment by Joeper214** [comment]
@hillelcoren 

Thanks for the information. But I got confused on the implementation on your project. is it the `ukai.js` file needed for the font mapping or there are a bunch of ways?

**Comment by hillelcoren** [comment]
Yes, that's the correct font file.

**Comment by Joeper214** [comment]
Thanks A lot. I got it working now. @hillelcoren

**Comment by outprog** [comment]
@hillelcoren  @Joeper214 i download ttc file, Uncaught Error: Font ukai(normal)0 not found in TTC file. how u woking?

**Comment by hillelcoren** [comment]
I believe this is the file you need to use

https://github.com/invoiceninja/invoiceninja/blob/master/public/js/vfs_fonts/ukai.js

**Comment by outprog** [comment]
@hillelcoren i download this file and use this config:
                    
                    var fontDescriptors = {
                    ukai: {
                        normal: 'UKai.ttf',
                        bold: 'UKai.ttf',
                        italics: 'UKai.ttf',
                        bolditalics: 'UKai.ttf'
                    }
                };
                pdfMake.fonts = fontDescriptors;
                var docDefinition = { content: 'wqy中文wqy',
                    defaultStyle: {
                        font: 'ukai'
                    }
                };
                pdfMake.createPdf(docDefinition).open('test.pdf');

but not working.  console log is 'Uncaught TypeError: Cannot read property 'UKai.ttf' of undefined'

**Comment by Joeper214** [comment]
I think `Ukai.ttf` is also not working on me. I tried another way and wrote this blog.

Please check it out: http://www.skyarch.net/blog/?p=5673

**Comment by askie** [comment]
@hillelcoren 
`pdfmake.js:21668 Uncaught TypeError: Cannot read property 'UKai.ttf' of undefined`

**Comment by hillelcoren** [comment]
@askie did you mean to create the issue with this project or our app?

**Comment by 88kbbq** [comment]
> We were able to get Chinese working in our project: https://github.com/invoiceninja/invoiceninja
> 
> It took us a while to find an open-source font which worked, we ended up using Ukai:
> 
> http://www.freedesktop.org/wiki/Software/CJKUnifonts/Download/

I just installed the NotoSansCJKtc-Light font successfully, but Chinese appears normal while English in this font is spaced one letter per line, vertically, and the document is dozens of pages. Why did you choose Ukai and are there any other Chinese fonts that will display both Chinese and English properly?

**Comment by hillelcoren** [comment]
We chose Ukai because it worked and was open source. This was a few years ago, it's certainly possible there are better fonts to use.

**Comment by blikblum** [comment]
A bug with NotoSansCJK fonts where fixed in https://github.com/foliojs/fontkit/pull/207 but not released yet. In the mean time you can try https://www.npmjs.com/package/pdfkit-next

**Comment by 88kbbq** [comment]
Too bad the NotoSansCJK fix hasn’t been released yet. Great clear font for Chinese, but without English it won’t work. I used Transtype 4 to export local Chinese fonts .ttf and they all work in Invoice Ninja. Loving my PDF invoices now
