### ISSUE TITLE
Printing Problem - Replacing white spaces with squares - Firefox

### ISSUE THREAD

**Issue by BernardoLima** [bpampuch/pdfmake#292]
Had this problem on Firefox, print preview was perfect.
When printed it, it had replaced white spaces with squares.
Could you tell me if there's a solution?
![image](https://cloud.githubusercontent.com/assets/5435164/7694842/91ee3ce8-fdbc-11e4-8ea1-60fdc31d03d6.png)

**Comment by jthoenes** [comment]
Can you provide a more detail?

What are the fonts and the document definition you are using? Do you have the same issue in the playground?

**Comment by BernardoLima** [comment]
@jthoenes, I didn't set a font, and my document settings are:
[code]
		// a string or { width: number, height: number }
		pageSize: 'A4',

		// by default we use portrait, you can change it to landscape if you wish
		pageOrientation: 'portrait',

		// [left, top, right, bottom] or [horizontal, vertical] or just a number for equal margins
		pageMargins: [ 40, 60, 40, 70 ],
[/code]
The rest of the code is only simple text ''.

**Comment by jthoenes** [comment]
Can you provide the full document definition?

**Comment by shuklaalok7** [comment]
@BernardoLima I think you are using characters which are not in `Roboto`, which is the default font used. You may want to use font-families which cover more characters. I needed to print `₹` symbol, so I used Ubuntu font family.
Please visit google fonts to cater your needs.

**Comment by ridgarou** [comment]
Hi @jthoenes ,

I have the same problem than @BernardoLima but I don't know how to fix it. Any idea?

I'm using pdfmake integrated at "https://github.com/invoiceninja/invoiceninja/" project and I'm not sure how get information about it :worried:  Could you help me?  :smile: 

thanks a lot
