### ISSUE TITLE
Internet Explorer 10 Error

### ISSUE THREAD

**Issue by brettjthom** [bpampuch/pdfmake#295]
Getting the following error when trying to use the library in IE 10.
	  this.__defineGetter__('ascender', function(){
	    var font = this.getFont(0);
	    return font.ascender;
	  });
	  this.__defineGetter__('decender', function(){
	    var font = this.getFont(0);
	    return font.decender;
	  });

_definegetter_ isn't supported in IE 10, can we move this to a defineProperty?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/defineProperty

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/__defineGetter__

**Comment by jthoenes** [comment]
Already in with a recent pull request (but not released yet): #293

**Comment by brettjthom** [comment]
Just noticed that, thanks!
