### ISSUE TITLE
restrict 30 rows per page in a table

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#299]
How can I restrict only 30 rows of html table per page in pdf? ie, Pagebreak after every 30 rows.

**Comment by gnibeda** [comment]
When you generate doc definition from html, you can break your table in multiple tables with 30 rows in each.

**Comment by mpsbhat** [comment]
But the table rows are generating dynamically from backend code. So is it
possible to set row height?

**Comment by mpsbhat** [comment]
But the table rows are generating dynamically from backend code. So is it possible to set row height?

**Comment by jthoenes** [comment]
Hi, can you describe more concrete what you want to achieve?

As @gnibeda pointed out, you can easily create a new table by counting the rows yourself in JavaScript.

**Comment by mpsbhat** [comment]
Myself creating a pdf file from html table using pdfmake where there are 25+ columns. So I given A2 pagesize otherwise all the columns not fit inside the document. When I given A2 size, automatically the rows per page will becoming 60+ which is not visible after printing in a hard copy of papersize A4. Attached the screen shot of the report. The code is here: http://jsfiddle.net/mpsbhat/845mkg9h/50/
![screenshot from 2015-05-19 14_55_00](https://cloud.githubusercontent.com/assets/9914694/7841230/ca465d98-04b8-11e5-93b6-8286972fb000.png)

**Comment by jthoenes** [comment]
I'm still not sure what you want
You want to split by 30 rows? Split your ``reportGrid`` into chunks of 30 for instance using lodash.

You want to split by 30 columns? That's not supported by pdfmake.
