### ISSUE TITLE
generate barcode

### ISSUE THREAD

**Issue by wsugiri** [bpampuch/pdfmake#300]
Is this posible to generate barcode in with this library?
For QR Code already available and work well.

**Comment by jthoenes** [comment]
Not yet. If you (or someone else) wants to implement it and create a pull request, I'm happy to help.

**Comment by skylize** [comment]
Just get the datauri of your barcode and add it as an image. [-images example-](https://github.com/bpampuch/pdfmake/blob/master/examples/images.js)
```javascript
var canv = document.createElement('canvas')
drawBarcodeOnCanvasUsingSomeLibrary(canv)

var imgdata = canv.toDataURL('image/png')

docDefinition.content.push({ img: imgdata })
```
For best image quality, make your canvas about 4 times the size you really need and downscale when defining the document.

There is also a "canvas" property in pdfmake that exposes pdfkit vector drawing. [-vectors example-](https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js) If your library generates SVG, you could probably convert it to match the API.

**Comment by wsugiri** [comment]
oh great, thanks for the idea..

**Comment by svlungade** [comment]
WSUGIRI the QR code generated in my PDF is mirror image and is 90 degree rotated, have you tried scanning the QR code generated? is it working fine?

**Comment by NitinAK** [comment]
I am using the PDFmake, and my requirement is to print the QR code in pdf. Please help me. my email is nitinak511@gmail.com

**Comment by real050280** [comment]
@natinAK you can use bwip-js library for that.

example (nodejs):
```
'use strict';
const Promise = require('bluebird');
const bwipjs = require('bwip-js');
const pdfPrinter = require('pdfmake/src/printer');

//IMPORTANT: Make sure these fonts are existing and in the correct location as stated below.
const fonts = { 
  Roboto: {
      normal: 'assets/arial.ttf',
      bold: 'assets/arialbd.ttf',
      // italics: 'assets/ariali.ttf',
  }
};
const printer = new pdfPrinter(fonts);

const createBarcodeImage = (text, opt) => {
  opt = opt || {};
  const format = opt.format || 'gs1-128'; //default barcode type
  const height = opt.height || 13;        //default barcode height
  return new Promise((resolve, reject) => {
     try {
         bwipjs.toBuffer({
            bcid: format,
            text: text,
            height: height,
            parsefnc: true
        }, (err, img) => {
           if(err) { return reject err; }
           return resolve(img);
        });
     } catch(errMessage) {
        return reject(errMessage);
     }
  });
}

const createBarcode = (barImg, barcodeNumber) => {
  return {
    content: [
      {image: barImg}, //you could control the height and width here as well
      {text: barcodeNumber}
    ]
  }
}

const test = Promise.coroutine(function*() {
  const barcodeNumber = '1234567890';
  const barImg = yield createImage('^FNC100' + barcodeNumber, {format:'code128', height:22});
  var pdfDoc = printer.createPdfKitDocument(createBarcode(barImg, barcodeNumber));
  pdfDoc.pipe(fs.createWriteStream('./barcode.pdf')).on('finish',function(){
  //success
  });
  pdfDoc.end();
});
```

test();

**Comment by sKY02644** [comment]
I have been able to generate a barcode as an SVG and inserted into the pdf.

the problem is after printing the barcode shows all black

anybody here to assist me 

I am attaching a sample pdf file to it for reference

[Receipt-1652536084993.pdf](https://github.com/bpampuch/pdfmake/files/8693027/Receipt-1652536084993.pdf)
.

Please assist
