### ISSUE TITLE
Named printers freez if using more than 1 font and adobe reader

### ISSUE THREAD

**Issue by entcs** [bpampuch/pdfmake#301]
Some printers freez when printing with adobe reader.
When using only one font on pdf(no bold and no italic) the document prints fine.
If using bold or a second font the named printers freez and dont print.
When printing with foxit reader everything is fine.
When resaving pdf with photoshop the printers also print fine.

Any idea on what exactly might cause this?fontmaps conflict? or any pointers what could i change in pdfmake to try to solve this?

list of printers:
Konica Minolta,
Xerox,
HP Laserjet 2430,
HP laserjet M1530 MFP Series

**Comment by jthoenes** [comment]
Have you checked your bold and italic fonts. Maybe you have the same issue as these: https://github.com/devongovett/pdfkit/issues/218 or https://github.com/devongovett/pdfkit/issues/69

We an issue with crashing printers with a version of Arial back in the day, but fixing the font solved the issue.

**Comment by entcs** [comment]
thank you, converting font files from ttf and back to ttf solved the printing issue
