### ISSUE TITLE
What is proper build process for standalone browser script?

### ISSUE THREAD

**Issue by skylize** [bpampuch/pdfmake#304]
I ran ```gulp build``` and ```grunt build```. Both reported success. From looking at the build files I would expect server ready scripts from the gulp build (except for missing font_vfs) and then browser ready files from running grunt afterward. 

In the build folder on github, I see several browser-friendly injections and alterations in pdfmake.js, such as ```... module.exports = global["pdfMake"] = ...``` on line 47. These are missing from the copy  I built locally. Code that works fine with the master build throws ```pdfMake is not defined``` with my build.

**Comment by bpampuch** [comment]
We're using gulp now so simply run ```gulp build``` 

Don't use grunt unless you need to bundle your own vfs_font - this step is not included in gulp build yet

**Comment by skylize** [comment]
Okay, thanks. I kind of thought that might be the case. It doesn't seem to answer the question though. If I only run ``gulp build``, I'm still missing the browser-friendly injections into ``pdfmake.js`` that I see if I just download the ``pdfmake.js`` from master on github. Loading into the browser with a simple ``<script>`` tag fails when I build it myself. I have to assume I'm missing a step or a configuration.

**Comment by jthoenes** [comment]
Hm, I cannot reproduce your problem at all. Have you double-checked npm packages? What's your environement?

**Comment by skylize** [comment]
Hmm. I guess you must be right about a problem w/ the packages. I deleted the node_modules folder and reinstalled so I could report the warnings to you. Decided to try building again before posting this message and it worked fine. Maybe a dependency regression that got fixed upstream? Anyway, thanks for looking.
