### ISSUE TITLE
Ability to add colors to text?

### ISSUE THREAD

**Issue by sankalpsingha** [bpampuch/pdfmake#305]
I tried doing something like :
`fontColor: 'red'`

Nothing really happened. Am I doing it wrong or this does not exist yet?

**Comment by coinpusha** [comment]
Hey, try using    
`color:'red'`

**Comment by bpampuch** [comment]
@sankalpsingha - you'll find all styling properties here: https://github.com/bpampuch/pdfmake/blob/master/src/styleContextStack.js#L85

**Comment by Flynnp25** [comment]
> @sankalpsingha - you'll find all available styling properties here: https://github.com/bpampuch/pdfmake/blob/master/src/styleContextStack.js#L85

Link isn't working anymore

**Comment by rexsuecia** [comment]
> > @sankalpsingha - you'll find all available styling properties here: https://github.com/bpampuch/pdfmake/blob/master/src/styleContextStack.js#L85
> 
> Link isn't working anymore

https://github.com/bpampuch/pdfmake/blob/0.1/src/styleContextStack.js
 Love this digging in sources to make stuff work :-p

**Comment by nmummau** [comment]
https://pdfmake.github.io/docs/document-definition-object/styling/
