### ISSUE TITLE
Alias "fit" keyword to "auto" for column/table width

### ISSUE THREAD

**Issue by Zopieux** [bpampuch/pdfmake#306]
I was quite confused about `star` and `auto` sizing until I read the column examples. In my humble opinion, the `auto` keyword should have a more explicit name; I suggest `fit`, because that's what it actually does: _fit the content_. `auto` carries no real meaning: automatic about what? Other columns? No! Page width? No! Content maybe? Yes indeed.

My suggestion is to add an alias `fit` → `auto`. Thanks for your consideration.

**Comment by zukilover** [comment]
Auto is actually self explanatory and closest to the CSS standards on size unit.

**Comment by liborm85** [comment]
`auto` is correct and sufficient.
