### ISSUE TITLE
Playground Missing example loading of PDF

### ISSUE THREAD

**Issue by jHoyne** [bpampuch/pdfmake#308]
Google Chrome	42.0.2311.153 (Official Build) (64-bit)
ChromeOS

Issue
Collums, Lists, Tables, Margin, and images to not have the PDFs render properly.

Collums:
![screenshot 2015-06-02 at 14 24 34](https://cloud.githubusercontent.com/assets/6077549/7944971/8af6c734-0933-11e5-85ab-10647b2f12c3.png)

Table:
![screenshot 2015-06-02 at 14 25 26](https://cloud.githubusercontent.com/assets/6077549/7945002/a8c798a6-0933-11e5-97be-781dbf1accd3.png)

Lists:
![screenshot 2015-06-02 at 14 25 37](https://cloud.githubusercontent.com/assets/6077549/7945011/bbac713a-0933-11e5-907a-1225ea048e63.png)

Margin:
![screenshot 2015-06-02 at 14 25 44](https://cloud.githubusercontent.com/assets/6077549/7945024/cc300a76-0933-11e5-8825-0de06b6e830e.png)

Images:
![screenshot 2015-06-02 at 14 25 50](https://cloud.githubusercontent.com/assets/6077549/7945035/d738a5cc-0933-11e5-9537-95e30ff01475.png)

**Comment by bpampuch** [comment]
There's a bug with handling long data URIs in Chrome 42, upgrade your browser to 43 or 44
