### ISSUE TITLE
Arabic support

### ISSUE THREAD

**Issue by devmondo** [bpampuch/pdfmake#315]
hi, 

i have tried the playground, but it seems that it does not support right to left languages like Arabic and Hebrew , is it possible?

thanks in advanced.

**Comment by jthoenes** [comment]
No, its not possible currently.

**Comment by devmondo** [comment]
thank you, i hope it would soon

**Comment by moravcik** [comment]
+1 for this feature, actually this is a showstopper for our current project

**Comment by jthoenes** [comment]
@moravcik we're happy to accept pull request if you want to work on it.

**Comment by moravcik** [comment]
@jthoenes I think it should definitely be somebody with Arabic background, which is not my case

**Comment by itsmohdabrar** [comment]
It would be a great feature, if its support for arabic characters.

**Comment by mahmouddev** [comment]
any news hear for rtl language support ??

**Comment by moravcik** [comment]
just linking with corresponding pdfkit issue: https://github.com/devongovett/pdfkit/issues/219

**Comment by liborm85** [comment]
Connected with https://github.com/bpampuch/pdfmake/issues/184

**Comment by StigP1337** [comment]
As a workaround this [Arabic reshaper](https://github.com/louy/Javascript-Arabic-Reshaper) could be used

**Comment by saurabhgis** [comment]
RTL(Right to Left) , for arabic fonts supported or not? Pls provide some solution..

**Comment by Hodor9898** [comment]
3 years and still no support for rtl languages? shitty support to be honest

**Comment by liborm85** [comment]
Arabic characters are supported. Only RTL is required, feature request: https://github.com/bpampuch/pdfmake/issues/184

Closed.

**Comment by Elshaden** [comment]
Nothing seems to work out of the box for Arabic in PDF Export

**Comment by liborm85** [comment]
I don't know what is PDF Export, but as described above in pdfmake arabic characters are supported (of course it must support the font). Only RTL is not supported now.

**Comment by abdalla-ayman** [comment]
i mean what is the point of supporting arabic is word is all messed up
