### ISSUE TITLE
Nodejs documentation

### ISSUE THREAD

**Issue by btmdave** [bpampuch/pdfmake#317]
Is there any documentation specific for using this in node?

**Comment by Wabbala** [comment]
Hi Dave,

I am running pdfmake on nodejs, what do you need to know?

**Comment by xErik** [comment]
@Wabbala I have only this workaround.

Calling require('pdfmake') is no problem, but how to you initialise the resulting Printer with fonts in the browser?

**Workaround**

_HTML_ (order of script tags is important, otherwise I get an error)

    <script src='assets/libs/pdfmake.min.js'></script>
    <script src='assets/fonts/vfs_fonts.js'></script>
    <button type="button" ng-click="getPdf()">Get PDF</button>

_Angular_


    module.exports = angular.module('myApp')
	.controller('MyController',

	function ($scope, $window) {
		$scope.pdfMake = $window.pdfMake;

		$scope.getPdf = function () {
			var pdfMake = $scope.pdfMake;
			var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
			pdfMake.createPdf(docDefinition).open();
		};
	});

**Comment by xErik** [comment]
* `pdfmake-browserified-0.1.18` solved my problem.
* Works via `require('pdfmake-browserified-0.1.18')`
* Works via `<script src="bundle.js" type="text/javascript"></script>`, too
* Includes the Roboto font as the default font
* It's a big file
* Status is *works for me*

### Console
```console
npm install pdfmake-browserified-0.1.18
```

### Javascript
```javascript
var content = { content: 'This is a sample PDF printed with pdfMake' };

var createPdf = require('pdfmake-browserified-0.1.18');
createPdf(content).open(); // immediately opens new tab with PDF in browser
createPdf(content).download(); // immediately downloads PDF in browser
```

**Comment by moisesramalho** [comment]
Hello. I've looked around but haven't found any examples for how to use pdfmake on a Node.js controller.
Also, pdfmake-browserified include returns [TypeError: Cannot read property 'document' of undefined].
I'm trying to use it with in a Sails.js framework.

Could you post a small example of pdfmake use on a node.js controller for reference @Wabbala ? 
Would be much appreciated, thank you.

**Comment by Wabbala** [comment]
@Psyclops,

I will have a look at it when i am back at work :) will keep you posted!

**Comment by moisesramalho** [comment]
Ok, thanx @Wabbala .

**Comment by sirodoht** [comment]
Any news on this?

**Comment by moisesramalho** [comment]
Nope.

Currently doing the reports with PDFkit.

**Comment by jpang01** [comment]
Here is server side example:

```javascript
var fonts = { ... };

var PdfPrinter = require('pdfmake');
var printer = new PdfPrinter(fonts);
var fs = require('fs');

var docDefinition = { .... };

var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('sample.pdf');
pdfDoc.end();
```

---------------------------
Change the line in example absolute.js
```javascript
var PdfPrinter = require('../src/printer');
```
to
```javascript
var PdfPrinter = require('pdfmake');
```

**Comment by liborm85** [comment]
Will be included in the new documentation. Issue: https://github.com/bpampuch/pdfmake/issues/1238
