### ISSUE TITLE
getBase64 and missing images

### ISSUE THREAD

**Issue by cgundacker** [bpampuch/pdfmake#318]
Hi!

I want to generate a pdf using ".getBase64()" and transfer the string to my backendserver to save it.
When i open the file later the images are missing.

I created a demo where you can see my code - in this demo i call ".open()" and ".getBase64()", in the opened file there is an image in the header in the base64 string not.

link to demo -> https://www.epoconsulting.com/_ema/test/ema.html
app to decode the string and save it as pdf: http://www.motobit.com/util/base64-decoder-encoder.asp

thanks for your help

Christopher

**Comment by jthoenes** [comment]
You cannot call ``getBase64()`` (or any other method) after you called ``open()``. pdfmake is stateful - which means you cannot call it twice with the same data. 

Would be probably good to work on it ...
