### ISSUE TITLE
Put a text o any element in the bottom of the document

### ISSUE THREAD

**Issue by RigobertoFelix** [bpampuch/pdfmake#319]
I try to put a sing part in the bottom of the document an fail there is a way to do that automatically

**Comment by jthoenes** [comment]
Could you please provide the document definition or source code for your problem? When you have, also the error message / stack trace.

I don't understand what your issue is.

**Comment by RigobertoFelix** [comment]
I use a footer with a function that in the last page put a line and a text but my question is there is no other way to make that?

**Comment by jthoenes** [comment]
You can use ``{text: 'my text', absolutePosition: {x: 12, y: 18}}`` for that. Use inch values to specify them.

**Comment by RigobertoFelix** [comment]
Done. Thanks
