### ISSUE TITLE
Table don't split

### ISSUE THREAD

**Issue by RigobertoFelix** [bpampuch/pdfmake#321]
I have table inside on another table and don´t split when it is in the end

![issue](https://cloud.githubusercontent.com/assets/11526005/8116988/5a830cb4-1042-11e5-9963-99690cca70ca.png)

**Comment by jthoenes** [comment]
Can you provide the full document definition of the example?

**Comment by RigobertoFelix** [comment]
{
                table: {                    
                    
                    widths: ['*'],
                    body: [
                        [
                            {
                                columns: [
				            {

				                table: {
				                    widths: ['auto', '*'],
				                    body: [
                                        [{ text: 'Nombre del Prospecto:', style: 'titulo_fondo_azul' }, { text: contenido.prospecto, style: 'normal_fondo_azul' }],
                                        [{ text: 'Poblacion:', style: 'titulo_fondo_azul' }, { text: contenido.poblacion, style: 'normal_fondo_azul' }],
                                        [{ text: 'Domicilio:', style: 'titulo_fondo_azul' }, { text: contenido.domicilio, style: 'normal_fondo_azul' }],
                                        [{ text: 'Telefono:', style: 'titulo_fondo_azul' }, { text: contenido.telefono, style: 'normal_fondo_azul' }],
                                        [{ text: 'Correo Electronico:', style: 'titulo_fondo_azul' }, { text: contenido.correo_electronico, style: 'normal_fondo_azul' }],
                                        [{ text: 'Fecha de Alata:', style: 'titulo_fondo_azul' }, { text: contenido.fecha_alta, style: 'normal_fondo_azul' }],
                                        [{ text: 'Zona de Operacion:', style: 'titulo_fondo_azul' }, { text: contenido.zona_operacion, style: 'normal_fondo_azul' }],
                                        [{ text: 'Necesidad:', style: 'titulo_fondo_azul' }, { text: contenido.necesidad, style: 'normal_fondo_azul' }],
                                        [{ text: 'Sugerencias del Vendedor:', style: 'titulo_fondo_azul' }, { text: contenido.sugerencias_vendedor, style: 'normal_fondo_azul' }],
                                        [{ text: 'Atenderse antes del:', style: 'titulo_fondo_azul' }, { text: contenido.atenderse_antes_del, style: 'normal_fondo_azul' }]
				                    ]
				                }, layout: {
				                    hLineWidth: function (i, node) {
				                        return (i === 0 || i === node.table.body.length) ? 0 : 0;
				                    },
				                    vLineWidth: function (i, node) {
				                        return 0;
				                    },
				                }
				            },
				            {
				                width: 100,
				                table: {
				                    widths: ['auto', 10],
				                    body: [
                                        [{ text: 'Estado del Prospecto', colSpan: 2, style: 'titulo_fondo_negro' }, {}],
                                        [{ text: 'Alta' }, { image: contenido.img_alta, width: 10 }],
                                        [{ text: 'Analisis' }, { image: contenido.img_analisis, width: 10 }],
                                        [{ text: 'Canalizacion' }, { image: contenido.img_canalizacion, width: 1 }],
                                        [{ text: 'Aun en proceso de captura', colSpan: 2, rowSpan: 23 }, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}],
                                        [{}, {}]
				                    ]
				                }
                                    , style: 'normal_fondo_azul'
				            }
                                ],
                                //text: contenido, fillColor: '#DCF8FA'
                            }],
                        [

													{
													    table: {
													        widths: ['*'],
													        body: [
																[{ text: 'Proveedores', fillColor: '#89858A' }],
                                                                [{ text: contenido.proveedores, fillColor: '#F1DCFA' }]
													        ]
													    },
													},
                        ], [

													{
													    table: {
													        widths: ['*'],
													        body: [
																[{ text: 'Cultivos', fillColor: '#89858A' }],
                                                                [{ text: contenido.cultivos, fillColor: '#F1DCFA' }]
													        ]
													    },
													},
                        ],
                        [{
                            table: {
                                widths: ['*'],
                                body: [                                    
                                    [{ text: 'Observaciones:' + contenido.observaciones_aceptacion, style: 'titulo_fondo_azul' }]
                                ]
                            }, layout: {
                                hLineWidth: function (i, node) {
                                    return (i === 0 || i === node.table.body.length) ? 0 : 0;
                                },
                                vLineWidth: function (i, node) {
                                    return (i === 0 || i === node.table.body.length) ? 0 : 0;
                                },
                            }
                        }]

                    ]
                }
            }

**Comment by RigobertoFelix** [comment]
when contenido.observaciones_aceptacion is very long dont split

**Comment by jthoenes** [comment]
Can you also provide ``contenido`` with some content? So I can actually see the issue?

(To double check, paste your document definition & date in the http://pdfmake.org/playground.html and see if they work)

**Comment by RigobertoFelix** [comment]
Got it, the problem appear when i put a table inside of elements columns

**Comment by liborm85** [comment]
Not available functional sample. I tried to edit the above sample, and it works well.
Maybe some of the variables are as numbers (this issue fixed version 0.1.23) or is used reference to same object (see https://github.com/bpampuch/pdfmake/issues/465).
