### ISSUE TITLE
Background color and justification

### ISSUE THREAD

**Issue by cphyc** [bpampuch/pdfmake#326]
Hi,
when I try to add a background color and at the same time justify the text, the generated PDF has only background color on the letters, not on the white space. See the attached image. The document I used is:

```
{content: [ 
  {
    alignment: 'justify',
    background: 'black',
    text: ' … '
  }
]}
```

and I'm exporting with the command `pdfMake.createPdf(document).download()`
![303](https://cloud.githubusercontent.com/assets/5411875/8204462/17bfee8c-14e9-11e5-8373-445455bdb5a9.png)

**Comment by smeijer** [comment]
Is there a better workaround available than placing the thing in a 1x1 table with `fillColor`?

**Comment by liborm85** [comment]
Sample for reproduce:
```
var dd = {
    content: [ 
        {
            alignment: 'justify',
            background: 'black',
            color: 'white',
            text: 'Lorem ipsum dolor sit amet, consectetur adipiscing elit. Phasellus pulvinar lobortis purus in iaculis. In ultrices nulla elit, sit amet lobortis eros porttitor in. Quisque auctor risus id blandit consequat. Sed quis vehicula sapien. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Mauris non tempor quam. Quisque eget elementum arcu. Fusce ac mattis leo, quis placerat eros. Nam ac libero a ante facilisis vulputate eu eget tortor.'
        }
    ]
}
```

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/86db261d8ba1be2788f5b466ca1ad0ca46bdc889.
