### ISSUE TITLE
Images are up-scaled by pdfmake and look blurry

### ISSUE THREAD

**Issue by Bangybug** [bpampuch/pdfmake#328]
I'm trying to use pdfmake to render math formulas into pdf. Formulas are generated by a php script "phpmathpublisher.php"

The formulas are always up-scaled by pdfmake (or pdfkit - I don't know).

The playground of pdfmake http://pdfmake.org/playground.html illustrates this problem well. The original size of the image in the playground is 695 x 310, but it is rendered at a larger scale in the pdf.

I think that the DPI of the Pdf is affecting the images that way. I'm not sure what units are used when specifying fit/width/height of an image in Pdfmake. Looks like Pdfmake is using pixels, but PDF kit is using points. PDF make does not properly transform pixels to points. That's my wild guess.

I found similar issues: https://github.com/bpampuch/pdfmake/issues/67

**Comment by snarkitect** [comment]
I'm seeing the same issue.  If I pass a 900x600 pixel image, the image is scaled by 4/3 in the resulting pdf.

**Comment by stephenanders** [comment]
It appears this up-scaling is happening b/c the default unit for pdfmake is points.  When no size is passed for the image, it gets the dimensions from the parsed image's header information.  However, the image's dimensions in the header are in pixels "[PNG - Width and height give the image dimensions in pixels.](https://www.w3.org/TR/PNG-Chunks.html)".  So, when pdfmake determines the size of the image, that value is in pixels, but it assumes the value is in points - resulting in the 4/3 scaling which we see in the pdf.

I've been trying to modify pdfmake.js to convert the pixel values to points before inserting the image onto the page, but so far, am not having any luck. 

Has anyone else encountered this and have a working fix or workaround?  I will continue working on this, but if someone else has already accomplished what I'm trying to do, I'd love to get that code!!

**Comment by Bangybug** [comment]
As a temporary workaround I premultiply the width of my image with 0.7487922705314 (the height is adjusted by pdfmake automatically)

**Comment by christomitov** [comment]
@Bangybug at what point did you do this premultiplication? I tried it at the JSON level with something like:
```
{
    image: options.productBarChart,
    width: 515 * 0.7487922705314
}
```

However it's still blurry.. just with less width as expected.

**Comment by s7726** [comment]
I'd also like to get a fix for this figured out.

**Comment by christomitov** [comment]
@s7726 I forgot to mention, this was actually a problem with the image and not PDFmake. What I was doing was rendering an image from Google charts using PhantomJS. By default this image was low DPI but I was able to hack around that by doing `page.zoomFactor = 300.0/72.0;` . Not sure this will help your specific case but maybe if someone else stumbles on this and is doing something similar it'll save them some time.

**Comment by s7726** [comment]
My case is an 816x108px png that is supposed to be like letter head on a US Letter size document. It fits and renders nicely in MS Word and in a normal image viewer. It turns out fuzzy and low resolution in the PDF output.

**Comment by csvan** [comment]
+1

**Comment by nettiopsu** [comment]
@Bangybug where does this 0.7487922705314 come from?

**Comment by 12smc120** [comment]
How to fit different size images over the pdf?

**Comment by Phero49** [comment]
guys its 2023 and am stuck on this problem  if anyone solved it please share
