### ISSUE TITLE
Custom font: must always define Roboto

### ISSUE THREAD

**Issue by diegito** [bpampuch/pdfmake#329]
I tried to insert a new font and I was getting an error like I was referring the wrong header. Eventually I realized I had to define also `Roboto` in my `pdfMake.fonts` dictionary. 

I think saying it's mandatory to define Roboto in the dictionary it's a nice addition to the [docs](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side). (or change the code in a way that does not make Roboto necessary or default).

Thanks

**Comment by jthoenes** [comment]
Did you define your font as default font? In this case you should not get an error. And the default font part is written in the documentation.

Suggestions on how to make it clearer are welcome!

**Comment by diegito** [comment]
Yes I tried to set a default font as suggested but nothing...

Perfect! I was not sure if it was something for documentation or it was a bug or something else. It just was not clear why I was keeping to get an error while trying to import new fonts :)

**Comment by liborm85** [comment]
Will be included in the new documentation. Issue: https://github.com/bpampuch/pdfmake/issues/1238
