### ISSUE TITLE
Custom Fonts not render as expected. 

### ISSUE THREAD

**Issue by liratanak** [bpampuch/pdfmake#332]
I tried to make custom fonts in my own language, Khmer.

*Expected*
![selection_024](https://cloud.githubusercontent.com/assets/1790248/8268385/516f22a2-17ae-11e5-8fd6-69c7db7c4b85.png)

*Rendered*
![selection_023](https://cloud.githubusercontent.com/assets/1790248/8268374/e5f8d25c-17ad-11e5-935a-927659c4299a.png)

I don't really know what I missed.
Really appreciate for any suggestion and idea. Thanks

**Comment by jthoenes** [comment]
Can you provide all the information to regenerate the pdf file including font and document definition to be pasted into the playground?

**Comment by devongovett** [comment]
Khmer and other complex scripts require additional processing prior to rendering that PDFKit and pdfmake do not currently do. This includes unicode syllable analysis and reordering, and correct OpenType shaping. See the [Khmer OpenType spec](https://www.microsoft.com/typography/OpenTypeDev/khmer/intro.htm) from Microsoft for more details.

I'm working on a [new font engine](http://github.com/devongovett/fontkit) for PDFKit that aims to eventually support complex script shaping. It is a big job, however, so it will take some time. Currently, fontkit supports OpenType shaping, but does not automatically select the right features for you based on the script analysis.

**Comment by liratanak** [comment]
Even, I did not fully understand @devongovett said but mostly it is the root problem.
I did tried others way to work around. I use canvas image of the text then put it in back in the pdf.
( I know that not a solution, but that just a way to fix that )

Thanks for supports :)
