### ISSUE TITLE
Table text spilling over footer

### ISSUE THREAD

**Issue by SummerSonnet** [bpampuch/pdfmake#333]
The table rows are spilling over the footer. The header gets generated fine on the second page, but the content and the footer data overlap. What am I doing wrong here? Is it the page margins?

**Comment by hugo-ruivo-dw** [comment]
Hi,

We are having the same issue you are reporting.

Did you manage to correct this?

Thanks,

**Comment by SummerSonnet** [comment]
Hi,

You need to set the margins right. That way the text won't spill over to
the footer. Increase the height of the footer. That should help.

**Comment by manuelph** [comment]
+1
