### ISSUE TITLE
Units of margins

### ISSUE THREAD

**Issue by SummerSonnet** [bpampuch/pdfmake#334]
What units are the margins in- inches pixels or cms? And is there a way to convert them?

**Comment by jthoenes** [comment]
The margins are in inches.

To convert from centimeters to inches multiply by 0.393700787

Conversion to pixel don't make sense, as pixel are in relation to your
screen resolution.

SummerSonnet <notifications@github.com> schrieb am Di., 23. Juni 2015 01:37:

**Comment by SummerSonnet** [comment]
Thank you! Also, is there a way to change individual table row properties. I want the first header row's width to be more than the other rows.

**Comment by DerekDomino** [comment]
It looks like units are in points (https://en.wikipedia.org/wiki/Point_(typography).

There are 72 points in an inch (72 dpi):
````
var marginInPoints = marginInCentimeter / 2.54 * 72
````
