### ISSUE TITLE
Line Breaks being added after text line on header, before a canvas line

### ISSUE THREAD

**Issue by regexti** [bpampuch/pdfmake#337]
![pages](https://cloud.githubusercontent.com/assets/12944215/8319640/7230efda-19e7-11e5-8f72-ff979fb7199b.png)

``` javascript
var teste = function() {

    var array = [];

    for ( var i = 0; i < 300; i++) {

        var x = { 
            fontSize: 8,
            columns: [ 

                {
                    text: '' + i,
                    width : 50
                },
                {
                    text: 'xxx' + i,
                    alignment : 'right',
                    bold : i%2 == 0 ? true : false,
                    margin : [ i%2 == 0 ? 0 : 10, 0,0,0],
                    width : 150
                }
            ]};

        array.push(x);

    }

    return array;

};


var dd = {

    pageMargins: [ 10, 70, 10, 20 ],
    pageSize: 'A4',

    header: [

        { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 0.5 }] },

        {
           fontSize: 8,
           columns : [
               {
                   text : 'YYYYYYY', margin : [ 10, 0, 0, 0 ], width : 100 
               }     
           ]

        },

        {
           fontSize: 8,
           columns : [
               {
                   text : 'XXXXXXXXXXX', margin : [ 10,0,0,0 ], width : 100
               }     
           ]

        },

        { 
            canvas: [
                { type: 'line', x1: 10, y1: 0, x2: 595-10, y2: 0, lineWidth: 0.5 }
            ] 

        }

    ],

    content: [ 
        teste()
    ]
};
```

Thank's! For this amazing work! ;)
Marco Polo

**Comment by Mario-Eis** [comment]
+1 Same problem here!

**Comment by robertknecht** [comment]
Try defining the header with a function. That seems to fix the problem; don't know why.
`    header: function() {
        return [
            {
                "text": [
                    {
                        "text": "Some Text: ",
                        "style": "rightme"
                    },
                    {
                        "text": "Hello ",
                        "alignment": "right"
                    }
                ]
            },
            { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 0.5 }] }
        ];
    }`

**Comment by liborm85** [comment]
Converting static header/footer to dynamic is improved by commit https://github.com/bpampuch/pdfmake/commit/ecab1d69f4b068b417c4c8db2e7e136fe2c0e50e.
