### ISSUE TITLE
Is it possible to stream the creation of the pdf?

### ISSUE THREAD

**Issue by jangu** [bpampuch/pdfmake#338]
In pdfkit, you're able to create a stream and gradually create the PDF document.

<pre>
var PDFDocument = require('pdfkit');
var doc = new PDFDocument();
doc.pipe(fs.createWriteStream('/path/to/file.pdf');

//Grab data and add to the PDF document.
doc.text(data)
  .moveDown();

// Grab more data.
doc.text(moreData);

// End the document generation later.
doc.end();
</pre>

In pdfmake, the document definition directs the generation of the PDF all at once. It looks like createPDFDocument in printer.js returns a reference to the pdfkit instance.

**Comment by jthoenes** [comment]
Yes. Se for example: https://github.com/bpampuch/pdfmake/blob/master/examples/background.js

**Comment by jangu** [comment]
Thanks @jthoenes. To better explain, I'm trying to use the pdfmake table API. My problem is that I'm retrieving data asynchronously and want to print it to the PDF progressively without having a document definition object maintaining this data structure.

In the example:

<pre>
var async = require('async');
var fs = require('fs');
var printer = require('../src/printer');

var docDefinition = { content: [ ... ] };
var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('pdfs/background.pdf'));

async.series([
  function (makeTitle) {
     pdfDoc.text('Title')
       .moveDown();
     return makeTitle();
  },
  function (makeTable) {
     // HERE!! - Add table?
     pdfDoc.add(content: [ table: ... ]);
     // OR
     docDefinition.content.push({ table: ... });

     return makeTable();
  }
], function (err) {
  pdfDoc.end();
});
</pre>

pdfDoc will be a reference to the PdfKitDocument with methods exposed such as text, moveDown, etc. Would it be possible to add a table through pdfmake's API after this point or modify the document definition? The document I'm generating will be at least 1MB.

**Comment by jthoenes** [comment]
Ah understood. That's not possible with the current structure of pdfmake - and will probably never be possible.

pdfmake is a layout engine, that needs to look ahead from time to time, to decide if something will be put somewhere on a page. So it needs to know, what content will be coming.

**Comment by jangu** [comment]
Gotcha, thanks!

**Comment by simplynutty** [comment]
@jthoenes Is it expected that calls to ```pdfMake.createPdf(documentDefinition)``` lock up the browser?  I'd like to show the user a loading screen when they click to export as PDF but that call seems to lock up the browser.  I tried using `download()`, `getBuffer()`, and `getDataUrl()` but they all require calling createPdf first.  Any thoughts?

**Comment by jthoenes** [comment]
Why don't you show the loader before the screen?
Am 01.07.2015 18:17 schrieb "Jon West" <notifications@github.com>:

**Comment by jthoenes** [comment]
Sorry I mean, before calling createPdf?
Am 01.07.2015 21:24 schrieb "Johannes Thönes" <johannes.thoenes@gmail.com>:

**Comment by simplynutty** [comment]
I can but neither `createPdf()` or `download()` lets me know when the download is complete.  I saw that `getBuffer()`, and `getDataUrl()` have callbacks but then I have to find a cross-browser solution to name the file via Blob download etc.  I might be doing something wrong within angular but `createPdf` was locking the browser and my load screen didn't appear until sometime after calling createPdf even though I triggered it 1st.  Might need an $apply somewhere.

**Comment by jmorrisIII** [comment]
@jthoenes If I run the above example https://github.com/bpampuch/pdfmake/blob/master/examples/background.js
I get an Unrecognized document structure error if my content is an array ex. content:[...]  but if its an object ex.content:{ text: 'FOO', style: 'BAR' } it works fine. Any Ideas?
