### ISSUE TITLE
table padding 

### ISSUE THREAD

**Issue by loverdrive** [bpampuch/pdfmake#345]
Hi, is there a way to add padding in text into table?
I want to set a space between the border of the table and the text into the table.

**Comment by Wabbala** [comment]
Hi Loverdrive,

I did it by "hacking" the different table styles in pdfMake.

You can do it by specifying certain types of table layouts. Check out the
documentation on tables with the corresponding style: noBorders.

Find noBorders in the source code of pdfMake, and you'll see the padding
parameters there. If you need any help just let me know :).

Cheers!

**Comment by loverdrive** [comment]
Now i solved adding margin to the text in the table:

{ text: 'some text here', style: 'tableStyle',  margin: [0, 15, 0, 0]}

Thank you :)

**Comment by Wabbala** [comment]
Ahh good to know! I will incorporate this, thnx!

**Comment by bpampuch** [comment]
You can define custom paddings, please refer to the "tables" example in Playground, custom layout has paddings commented out, but you can uncomment them

```
paddingLeft: function(i, node) { return 4; },
paddingRight: function(i, node) { return 4; },
paddingTop: function(i, node) { return 2; },
paddingBottom: function(i, node) { return 2; }
```

**Comment by loverdrive** [comment]
Thank you very much for the answer! :)

**Comment by jafar-rezaei** [comment]
@bpampuch is that padding and margins added to whole table or on every cells ?
