### ISSUE TITLE
Property title, subject ...

### ISSUE THREAD

**Issue by ami44** [bpampuch/pdfmake#346]
Hello
How set property title, author, subject, keyword of pdf with pdfmake ?
Thank
Ami44

**Comment by jthoenes** [comment]
Currently this is not supported by pdfmake.

**Comment by ami44** [comment]
Thanks

**Comment by EddyBorja** [comment]
What kind of work would be involved in implementing this feature?

**Comment by liborm85** [comment]
Use is described in the readme.
