### ISSUE TITLE
UTF-8 Encoding

### ISSUE THREAD

**Issue by Ranth67** [bpampuch/pdfmake#348]
I seem to have a problem with the danish letters æøå, where I can't write these to my pdf file.

I have seen the Issue: 
https://github.com/bpampuch/pdfmake/issues/165
where it seems that you solve the problem, but i can't get it to work for myself.

My code looks like the following, but all I get in the PDF file is black questionmarks, where ø is supposed to be.

```
bodyDef.push([{text: 'Mandag', alignment: 'center'},{text: 'Tirsdag', alignment: 'center'},{text: 'Onsdag', alignment: 'center'},{text: 'Torsdag', alignment: 'center'},{text: 'Fredag', alignment: 'center'},{text: 'Lørdag', alignment: 'center'},{text: 'Søndag', alignment: 'center'}]);


        function pushBody(timeOfDay,timeOfDayArr){

            bodyDef.push([{text: timeOfDay, colSpan: 7, alignment: 'center'},{},{},{},{},{},{}]);
            max = Math.max.apply(null, timeOfDayArr.map(function(day) {return day.length;}));
            max && bodyDef.push(mapBinnedActivities(timeOfDayArr, max));

        }

        pushBody('Morgen',mornings);
        pushBody('Middag',noons);
        pushBody('Aften',evenings);


        docDefinition.content.push(
            {
                style: 'tableHeader',
                table: {
                    widths: ['*','*','*','*','*','*','*'],
                    headerRows: 1,
                    dontBreakRows: 1,
                    keepWithHeaderRows: 1,
                    body: bodyDef
                }
            }

        );
```

The PDF is generated from input messages from a website, so I need to resolve the problem for the overall document, and not just for the single characters that you see above.

**Comment by liborm85** [comment]
On http://pdfmake.org/playground.html this works:
```
var dd = {
	content: [
		'æøå'
	]
};
```

**Comment by kabirbaidhya** [comment]
Hi, I'm having issue with printing this character `℉` it is not being printed right now. I've tried other unicode characters they're working pretty fine.

**Comment by kabirbaidhya** [comment]
Okay, I found a workaround for this. If you use two different characters `°` & `F` together instead of single `℉`  it works. So, I'm using `°F` instead of `℉` now. Not sure why the latter on isn't working.
