### ISSUE TITLE
Generator pdf on server side and download, got unexpected result.

### ISSUE THREAD

**Issue by dktan** [bpampuch/pdfmake#351]
my code
```
app.get('/download', function(req, res){
res.setHeader('Content-disposition', 'attachment; filename=test.pdf');
    res.setHeader('Content-type', 'application/pdf');
    var PdfPrinter = require('pdfmake');
    var printer = new PdfPrinter();
    var docDefinition = {
        content: [
            'First paragraph',
            'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
        ]
    };

      var pdfDoc = printer.createPdfKitDocument(docDefinition);
      pdfDoc.pipe(res);
      pdfDoc.end();
  });
```

result: 
![qq20150706-1 2x](https://cloud.githubusercontent.com/assets/12505414/8535457/cf195e5e-23fa-11e5-84cf-a7c27540fcd4.png)

**Comment by dktan** [comment]
I figured out that the fonts name has to be Roboto. But is this a bug?

**Comment by svlungade** [comment]
Hi dktan, I have written same code, which works, however if the PDF size is big, then it takes time to generate the pdf file, and the code tries to render it even before the pdf file is created, is there a way I can avoid creating the pdf on file system and directly render it?
