### ISSUE TITLE
How to make a large image scroll onto the second or third page?

### ISSUE THREAD

**Issue by tanzid203** [bpampuch/pdfmake#357]
I am using html2canvas to create dataURL of a html table.
This table is quite long. 
PDFmake take the image, scales it, and tries to make the image fit into a single page. 
I would like my image to scroll to as much pages as it would like to.

![capture](https://cloud.githubusercontent.com/assets/13332775/8673840/76612c70-2a57-11e5-956e-e6359bc78d1e.JPG)

Can this be done?

**Comment by arsinawaz** [comment]
any updates on this issue? i also need this behavior...
+1

**Comment by Balkoth** [comment]
I'm interested as well… Will update this when I'll find a solution.

**Comment by Balkoth** [comment]
I managed to make it work by splitting the image before feeding it to pdfMake. 
Here is the relevant code:
https://gist.github.com/Balkoth/d79a520ca2a3377c15e902ec68790aff

**Comment by liborm85** [comment]
Answered.
