### ISSUE TITLE
IE 11 crash on images: "The data area passed to a system call is too small"

### ISSUE THREAD

**Issue by joepal1976** [bpampuch/pdfmake#362]
Visiting playground / images (on pdfmake.org) with chrome, the PDF renders as expected.

Visiting the same page with IE11 (11.0.9600.17842, in win 8.1), I just get a blank area where the PDF is supposed to render.

Debugging this further locally, I see that I get the error "The data area passed to a system call is too small", in pdfmake.js line 109 when I try to add a data-url image to a PDF.

(the version of pdfmake is what got pulled via bower this morning)

**Comment by joepal1976** [comment]
Actually, on further testing, this only seems to happen on open() and not on download(). Maybe the URL gets too long?

**Comment by liborm85** [comment]
Can you try it with lastest pdfmake version (0.1.22) ?

**Comment by liborm85** [comment]
known problem: https://github.com/bpampuch/pdfmake/issues/173
