### ISSUE TITLE
Adding Two Custom Fonts without Grunt

### ISSUE THREAD

**Issue by donatsu** [bpampuch/pdfmake#363]
Hello, is there anyway to add the custom fonts without using Grunt. Reason is we're building an application that can't have any server-side at all. We're running on a mongoose server and thus needs to make the application portable.

**Comment by mikehstrauss** [comment]
You only need to run the grunt task once in a development environment to build the vfs_fonts.js, then use the artifact as you need.

**Comment by liborm85** [comment]
Answered.
