### ISSUE TITLE
add support for otf fonts

### ISSUE THREAD

**Issue by Pczek** [bpampuch/pdfmake#365]
I just created a new vfs_fonts.js with the libre-baskerville otf files, it worked fine, but I was not able to use them in my pdf.  

```
Error: Not a supported font format or standard PDF font.    pdfmake.js:132
```

Seems like otf are not supported yet, couldn't find simliar issues in this tracker. In issue #51 pcpuser suggests to convert it to ttf. This worked fine but is not very elegant. Not sure if this support can be added in pdfmake or should be implemented in the underlying pdfkit library?

**Comment by devongovett** [comment]
This is coming very soon to pdfkit, via [fontkit](http://github.com/devongovett/fontkit).

**Comment by loverdrive** [comment]
@devongovett is possible to use fontkit now?
I have a problem of performance with japanese/chinese/korean fonts. On tablet, it may take minutes to generate pdf, using japanese fonts.
I hope to improve performance with new fontkit, so i'd like to try it.

Another noob question: how can i use fontkit into pdfmaker?

Thank you very much!

**Comment by liborm85** [comment]
Supported by actual release (0.1.22).
