### ISSUE TITLE
Create a link

### ISSUE THREAD

**Issue by diogoAntunes** [bpampuch/pdfmake#37]
Is it possible to in the same paragraph put a link to some url, for example:

'Lorem ipsum http://www.google.com some more text'

and google be a link to the page in some other colour?

**Comment by WishMaster2310** [comment]
where is the link code in you solution?

**Comment by jthoenes** [comment]
There is no support for clickable links in pdfmake yet, sorry.

**Comment by sc-03** [comment]
Hello first of all: Thanks 1000xtimes for this great library. It is fun to work with and clearly structured and many examples - thanks!

Regarding the links: How much effort would it be to integrate links in pdfmake? Links could be done automatically, as soon as the parser detects an URL or an E-Mailaddress, e.g. http://www.google.com - as far as I understand, the underlying pdfKit-Library supports linking, i.e. annotations: http://pdfkit.org/docs/annotations.html, e.g. link(20, 0, width, height, 'http://google.com/') - in which source file of the library the links should go in?
Thanks again!

**Comment by jthoenes** [comment]
Hi @sc-03,

you need to extend the ``layoutBuilder.js`` - best to extend the ``processLeaf`` method to handle dd like this:

````javascript
var dd = {content: [{text: 'Google', link: 'http://google.com/'}]};
````

To actually write the link to the pdf, you need to also extend the ``renderLine`` in ``printer.js``. Unfortunately we are not using pdfkit for writing the text - but you should be able to use the mentioned link function.

Let me know if you need more.

**Comment by sc-03** [comment]
Hi back

Thanks a lot for your fast reply! This makes sense and I will give it a try as soon as I have time (I hope that I do not have to make too much research on this topic, it doesn't seem straightforward to annotate a pdf) - at the moment, there is no pressure for us on this feature but I wanted to be prepared if customers wants to have it (and they will, I am sure ...). Thanks again!

**Comment by bpampuch** [comment]
merged :)

**Comment by arieljake** [comment]
@bpampuch are links working? I tried to add link: '...' to a text node in the playground and it didn't work.

**Comment by exequeryphil** [comment]
@bpampuch Hi, are links currently working?  Can you add a usage note in the docs?  I can't get them to work either.

**Comment by uanthwal** [comment]
Hello,
Is the hyperlink feature supported? If yes, please tell me how and if no, then any other alternate.

**Comment by marwenlandoulsi** [comment]
hello,
I can't add a link in my pdf document. Can you please show us how you can add a link?

@jthoenes : can you please explain how we can extend the renderLine in printer.js

**Comment by uanthwal** [comment]
Just update the js file manually and you will be able to add it. The latest js file does not include this change. :)

**Comment by marwenlandoulsi** [comment]
@uanthwal can you please show me how i can update it ?

**Comment by uanthwal** [comment]
tell me your email id, i will send updated file

**Comment by marwenlandoulsi** [comment]
landoulsi_marwen@hotmail.com 

thinks ! :) 👍

**Comment by marwenlandoulsi** [comment]
@uanthwal the problem not resolved :( .
In my case i use the printer.js 

what i should make to resolve this problem :(

**Comment by byjusbikashrajkhowa** [comment]
hey *diogoAntunes* Thankyou so muchhhhhhhhh for this. It is helpful!

**Comment by jackysupit** [comment]
> For anyone who had the same question, this is the answer:
> 
> text: [ 'This ', { text: 'is', color: 'green' }, ' the first ', { text: 'paragraph', color: 'red' } ] },

this works on mine, thank you so much

**Comment by LuizCTJ** [comment]
is there any way to create an svg with link ? i know what images is possible to do that
`{svg: svg, link: 'www.google.com'}`

**Comment by Pavithralak** [comment]
Link not open in a newtab..is there any option to set the link open in newtab?
