### ISSUE TITLE
currency symbol not available

### ISSUE THREAD

**Issue by kkarayat** [bpampuch/pdfmake#370]
Hi I am trying to create a sample invoice using pdfMake, where i have currency symbol with the amount, the standard currency symbols like (dollar, pound) etc seems to render correctly, whereas when i am trying to render (indian rupee) sign, it is not showing in the pdf. Can you please help.

**Comment by olsn** [comment]
We're having the same issue, did you find any solution for this @kkarayat ?

**Comment by kkarayat** [comment]
Hi, I have not found any solution till now, will let you know if found, also requested you to please let me know if you found some solution

**Comment by liborm85** [comment]
see https://github.com/bpampuch/pdfmake/issues/593
