### ISSUE TITLE
Table row does not start from new page 

### ISSUE THREAD

**Issue by Tawsif** [bpampuch/pdfmake#371]
Hello,

We are trying to generate a PDF using PDFMAKE.
For PDF generation, we are utilizing Table, Text and Images.

But it seems that Table is not able to understand the Text alignment along with the Image.
If the Cell is not able to contain the Image on the same page, it automatically applies Page Break for it. So that the Image is not sliced and it appears properly on the next page. That is fine.

But the text remains on the same page. And hence it looks very weird. Text on same page and Image on another.
Please find the attached Image where we have showed the issue. Its a screenshot of the PDF generated by us.

Do we have any work around for the same. We also want the text to appear along with the Image so that the alignment looks fine.
Please help us out for the same.
Thanks in Advance.

Have a look at below screenshot for reference-

![table_spacing-error](https://cloud.githubusercontent.com/assets/6791620/9195217/bce6c16c-403e-11e5-820e-69f8fd30a824.png)

**Comment by surjikal** [comment]
This is a problem for me as well.

**Comment by no-more** [comment]
Same for me

**Comment by playingwithbandits** [comment]
Was there a fix for this? :)

**Comment by vytautassugintas** [comment]
```
table: {
    headerRows: 1,
    widths: ['auto', 'auto', 'auto', 'auto']
    dontBreakRows:true,
    body: [ someBody ]
}
```
setting **dontBreakRows:true** in table declaration helped me

**Comment by playingwithbandits** [comment]
Thanks!

**Comment by liborm85** [comment]
Code for reproduce issue:
```js
var dd = {
    pageSize: 'A7',
    pageOrientation: 'landscape',
	content: [
		{
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['Column 1', 'Column 2', 'Column 3'],
					['Column 1', 'Column 2', {image: 'sampleImage.jpg', width: 130}],
				]
			}
		},
	]	
}
```
