### ISSUE TITLE
Status of non-webpack (0.1.17) branch and bug fixes?

### ISSUE THREAD

**Issue by mikehstrauss** [bpampuch/pdfmake#373]
It looks like the support for non-webpack usage is going away.  We are using AMD and would like to use the latest build with all the fixes and enhancements added since 0.1.18. Is it possible to use the latest build with requirejs?  We have it working with 0.1.17, but since 0.1.18 support for AMD looks to be removed. We are seeing some bugs with 0.1.17 that appear to be resolved in the latest code base (as tested in the playground).

**Comment by liborm85** [comment]
In the final version (0.1.22), everything should work correctly.
