### ISSUE TITLE
Some Images though part of the docdef object don't show on the PDF

### ISSUE THREAD

**Issue by RonCan** [bpampuch/pdfmake#374]
Here's my manipulation of the docdef
                                var certificates=[];
                            for (var certificate in forms[form].data.photos){
                                certificates.push({
                                    image:  $scope.getImage(forms[form].data.photos[certificate]),
                                    width:500
                                });
                            }
                            docdef.content.push({
                                text: 'INSPECTION/TEST CERTIFICATES',
                                style: 'header'
                            },
                                {
                                    columns: [
                                        {
                                            width: '_',
                                            table: {
                                                widths:['auto','_'],
                                                body: [
                                                    [ 'Date', $scope.get(forms[form].data.date,'date') ],
                                                    [ 'Type of test/inspection', $scope.get(forms[form].data.type)],
                                                    [ 'System', $scope.get(forms[form].data.system) ]
                                                ]
                                            }
                                        }
                                    ]
                                },
                                {
                                    table: {
                                        widths:['auto','*'],
                                        body: [

```
                                        [
                                            'Certificate Image',
                                            {
                                                stack: [
                                                    {
                                                        ul: certificates
                                                    }
                                                ]
                                            }
                                        ]
                                    ]
                                }
                            }
                        );
```

This docdef works fine in most cases but in some cases(when the image resolution is quite big e.g. picture taken from a smartphone) the image does not show up but if I change the `width:500` to `width:300` then the other image shows up too. I'm guessing it's the automatic width calculation that's not working fine in the library. Can you verify?

**Comment by liborm85** [comment]
You must correctly define the size of the images. If the image is too large will not be displayed.
