### ISSUE TITLE
Firefox 37.0.2 still cannot download pdfs

### ISSUE THREAD

**Issue by Meaglin** [bpampuch/pdfmake#378]
See #122 , issue still exists.

**Comment by robboerman** [comment]
Confirmed on Firefox 40.0.2 still a problem, cannot download. Can open in a new tab though

**Comment by ximex** [comment]
I have the same problem with FF 40.0.3 on Ubuntu Gnome.
No error messages in console.
![pdfmake](https://cloud.githubusercontent.com/assets/1078640/9783730/dcd9eb46-57a6-11e5-9074-2f623a06c071.png)

**Comment by NikitaNO** [comment]
Confirmed on Firefox 43. Using open() instead.

**Comment by liborm85** [comment]
I tested lastest Pdfmake (0.1.22) with Firefox 50 and download works well.
