### ISSUE TITLE
Server-side rendering

### ISSUE THREAD

**Issue by Kuzmin** [bpampuch/pdfmake#381]
Would it be possible to have this export as a standard module so that we could also have server side PDF rendering in the cases where that is needed?

**Comment by rajesh0188** [comment]
I am also trying to find options for server side PDF download option, is there any examples for server side PDF generation?

**Comment by psuhas** [comment]
I have done it following way, 
pdfmake is installed in node-modules folders with following command

npm install pdfmake

The code to generate the doc as :

    var PdfPrinter = require('pdfmake/src/printer');
    var printer = new PdfPrinter(fonts);

    var dd = {
	content: [
		'First paragraph',
		'Another paragraph'
	]
    }
    var pdfDoc = printer.createPdfKitDocument(dd);
    pdfDoc.pipe(fs.createWriteStream('basics.pdf')).on('finish',function(){
		//success
    });
    pdfDoc.end();

**Comment by sangecz** [comment]
I have a problem to get this working because of fonts object. pdfmake installed with npm.
I followed examples/basic but I don't know how to refer to fonts or how to bipass it using common fonts. I get this error:
`Error: ENOENT, no such file or directory 'fonts/Roboto-Regular.ttf'`

**Comment by psuhas** [comment]
Check the path for .ttf file, it should be from root of the node js app.

**Comment by sudib** [comment]
I am having the same font path problem in a meteor app on the server side. Using the simple example given above. The javascript file is under server directory. Can't find the font files. I have placed a fonts directory under my app root (same level as server and node_modules), I have placed a font directory under server, under node_modules...!! No luck. Any help is much appreciated!!

**Comment by stemfinity** [comment]
I am not familiar with meteor app but in NodeJS when I placed the fonts folder in root, it works

`

		fonts = {
			Roboto: {
				normal: './fonts/Roboto-Regular.ttf',
				bold: './fonts/Roboto-Medium.ttf',
				italics: './fonts/Roboto-Italic.ttf',
				bolditalics: './fonts/Roboto-Italic.ttf'
			}
		};

	var PdfPrinter = require('pdfmake/src/printer');
        var printer = new PdfPrinter(fonts);
`

**Comment by daupawar** [comment]
I have created small example for Server side async pdf generation in meteor
https://github.com/daupawar/MeteorAsyncPdfmake

**Comment by mzvast** [comment]
@stemfinity It works!Thanks a lot!

**Comment by emotilla** [comment]
pdfmake has a wonderful server example using express and node under 
pdfmake/dev-playground/server.js

**Comment by thincmedia** [comment]
Hi, fellow developers. Thanks for all the great inputs shared above.

I'm trying to implement this code:

var PdfPrinter = require('pdfmake/src/printer');
var printer = new PdfPrinter(fonts);

var dd = {
content: [
    'First paragraph',
    'Another paragraph'
]
}
var pdfDoc = printer.createPdfKitDocument(dd);
pdfDoc.pipe(fs.createWriteStream('basics.pdf')).on('finish',function(){
    //success
});
pdfDoc.end();


But there is no src/print  directories inside my pdfmake directory

What I'm trying to achieve is simply saving the generated PDF into my filesystem. Any help would be much appreciated.

**Comment by acomito** [comment]
@daupawar was putting fonts in private (rather than public) the key for getting at fonts server-side? I'm using html-pdf in a meteor to make a PDF server-side but can't get it to work... so may switch to this package if you got custom fonts working with meteor.

**Comment by kasztof** [comment]
In my case rebuilding docker container after adding `fonts` directory to root folder solved the issue

**Comment by tiveor** [comment]
@daupawar it works!! thanks.
