### ISSUE TITLE
Where can I get more info on editing existing PDFS

### ISSUE THREAD

**Issue by tdhz77** [bpampuch/pdfmake#382]
I found this issue here, but it leaves more questions than answers.
https://github.com/bpampuch/pdfmake/issues/105

Is it possible to create background images per page? eg) background#1 on page1 background#2 on page2.
One background image per page? If so, how could I use this?

Our PDF's are made in the HR department and I have no control over them. But I need to be able to fill the data with our backend. Trying to hack it together using the background image and absolute text. 

Any advice on this would be great!
So far, I have a background image and perfectly placed text, but I'm starting to fear that a second page would not be possible.

**Comment by liborm85** [comment]
This library does not edit PDF files.
