### ISSUE TITLE
how to fit too long words to fit into multi-line column. 

### ISSUE THREAD

**Issue by yogi4yu** [bpampuch/pdfmake#383]
Hi,
         I am using pdfmake through ui-grid. If there is more data in a column more than it's width, it justifies it so that it moves to next line provided that there's space between characters. But if it's a very long continuous word, it overlaps into next column content.
           How can tell pdfmake to break the word & move to next row , instead of writing it on to next column's data, on occurrence of characters like underscore(_) or hyphen (-) along with space.

```
        I would also like to know how to pass column widths dynamically to pdfmake? For example, if a user adjusts the column width in ui grid through web interface, can I capture & send the same column width to pdfmake if he clicks on "export as pdf" ?
```

Regards,

**Comment by yogi4yu** [comment]
I have also observed that coumns containing large numerical values break it on '-' , but alphanumeric strings don't

**Comment by csvan** [comment]
+1

**Comment by holly-weisser** [comment]
+1

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/204
