### ISSUE TITLE
Auto page break

### ISSUE THREAD

**Issue by vusan** [bpampuch/pdfmake#387]
There is a code for the page break after or before element. 
In my case content is dynamic and just exporting only one page. So requesting for automatically page break after the content reached to the bottom most.

**Comment by s7726** [comment]
there is a `pageBreak: 'after'` element you can apply to the table. You could also apply `pageBreak: 'before'` to the heading for the next section.

**Comment by vusan** [comment]
Yeah. We have those feature. But In my case content is dynamic and didn't know where should page break. So page should break automatically after the content reached to the bottom most.

**Comment by franklindias** [comment]
Hi @vusan, you could solve the problem?

**Comment by gshchaudhari** [comment]
I am having same problem please help me out.

**Comment by JulianKingman** [comment]
Ditto! For some reason I thought it did this automatically and I was the only one with this problem.

**Comment by gshchaudhari** [comment]
I got Solutions on this see my below code
var docDefinition = { 
                    content: DynamicContent,
                    footer: function(currentPage, pageCount) { return { text: currentPage.toString(), alignment:'center'} },
                   pageBreakBefore: function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
                     return currentNode.startPosition.top >= 650;
                    }
                               
                };

**Comment by liborm85** [comment]
Answered.

**Comment by ashishsober** [comment]
Anyone got the solution , i have the same issue .
Please help me out.

Thanks

**Comment by LorsK** [comment]
Me too, table rolling over to next page but the formatting is messing up
here is how it looks, it is a table in a table. 
![image](https://cloud.githubusercontent.com/assets/17942432/25454068/3a581998-2a99-11e7-807b-45959f0c1396.png)

**Comment by NikhilRadadiya** [comment]
I'm having same issue, Can anyone please help?

Thanks

**Comment by DivGolakiya** [comment]
did you find solution?

**Comment by javier-dominguez** [comment]
> I got Solution on this, see my below code
> var docDefinition = {
> content: DynamicContent,
> pageBreakBefore: function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
> return currentNode.startPosition.top >= 650;
> }
> };

This solution work for me, thanks @gshchaudhari. With this function automatically the content break to other page, you only need to move the value in this condition _return currentNode.startPosition.top >= **650**;_. 

For dynamic table generation work perfectly.
