### ISSUE TITLE
Set image inside of column and fit the space

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#388]
Hi guys,

I would like to fit an image into a column width, as long as the image is big enough. Otherwise just only as wide as the maximum width is possible. 

Are there any easy steps to do so? Is it possible setting maxWidth or maxHeight to images, for preventing completely unexpected behaviour?

Thanks!

**Comment by vishwajeets7** [comment]
I know this is a very old post, still you can use "fit:[width, height]"

**Comment by liborm85** [comment]
Answered.
