### ISSUE TITLE
Example with requirejs

### ISSUE THREAD

**Issue by infacq** [bpampuch/pdfmake#39]
Is there any?

**Comment by AntiAsko** [comment]
Is there a way to make it work with backbone and require js?

**Comment by Legends** [comment]
Don't specify vfs_fonts as a dependency for pdfmake, as this will give you the following error:
**Cannot read property 'Roboto-Regular.ttf' of undefined** 

Make sure pdfmake loads before vfs_fonts

This works in my case:
```
 shim: { 
       vfsfonts: { deps: ["datatables.net", "pdfmake"] }
       pdfmake: { deps: ["datatables.net"] } 
    },
 .....
 ..
```

**Comment by liborm85** [comment]
Will be included in the new documentation. Issue: https://github.com/bpampuch/pdfmake/issues/1238
