### ISSUE TITLE
Hide element / output element based

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#390]
Hello,

would like to know how you guys think about an option to hide a row through a boolean, somethink like:

```
{
text: 'Some text to dynamically hide',
hide:true
}
{
image: 'datauri...',
hide:false
},
{
text: 'This will be always visible'
}
```

It would be helpful to programatically hide some parts of the output. Cheers

**Comment by liborm85** [comment]
No. Create definition dynamic with or without texts/images

**Comment by mtin79** [comment]
Pitty :-( Would love to have a possibility to hide an element, too.
