### ISSUE TITLE
Table Height

### ISSUE THREAD

**Issue by tadija-lazarevic** [bpampuch/pdfmake#391]
Hello ya all,

just wondering is it possible to set height of specific row in table? Thanks.

**Comment by gregoralbrecht** [comment]
Would love to know this too!
How did you end up doing it @tadija-lazarevic ?

**Comment by tadija-lazarevic** [comment]
@gregoralbrecht Well I didn't found solution so I left it as it is. Height has dynamic size so it was not big deal.. 

Good luck :)

**Comment by gregoralbrecht** [comment]
Alright thanks! I got something now but it's really hacky...

**Comment by gabsoftware** [comment]
Please add this feature as well.
And/or make it possible for a nested table to take all the available vertical space of a table cell.

For example consider the following example:

`var dd = {
    content: [

        { text: 'A simple table with nested elements', style: 'subheader' },
        'It is of course possible to nest any other type of nodes available in pdfmake inside table cells',
        {
            style: 'tableExample',
        table: {
                headerRows: 1,
                body: [
                    ['Column 1', 'Column 2'],
                    [
                        {
                            table: {
                                body: [
                                    [ 'Col1', 'Col2', 'Col3'],
                                    [ '1', '2', '3'],
                                    [ '4', '5', '6']
                                ]
                            }
                        },
                        {
                            table: {
                                body: [
                                    [ 'Col1', 'Col2', 'Col3'],
                                    [ '1', '2', '3'],
                                    [ '4', '5', '6'],
                                    [ '7', '8', '9']
                                ]
                            }
                        }
                    ]
                ]
            }
        }
    ]
}`
It would be nice if in the first column, the table took all the available space to be the same size of the table on the second column.

**Comment by Tonio31** [comment]
Will this be avilable soon, it seems a shame not to have something basic like this (or a workaround)

**Comment by strokovnjaka** [comment]
This is available (with at least basic functionality) in the forks above.

**Comment by majid701** [comment]
I really need this!

**Comment by renoken** [comment]
+1

**Comment by rodcope1** [comment]
+1

**Comment by WisdomSky** [comment]
still not implemented?

**Comment by liborm85** [comment]
Feature implemented by commit https://github.com/bpampuch/pdfmake/commit/6577e79325f580f81c7b046cd068c8b78b1bf43a.

**Comment by lattam** [comment]
Great work! When can we expect this feature to be released ?

**Comment by liborm85** [comment]
New version released.
