### ISSUE TITLE
 this.baseSystem error with firefox

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#397]
Hello,

with Firefox 41.0.1 I receive 

```
this.baseSystem is undefined
r.prototype.readFileSync

```

With Chrome I don't have any problem. I'm calling pdfmake with following function:

```
pdfMake.createPdf(docDefinition).download()
```

Any ideas about this issue? I use the newest bower version. Thanks

**Comment by tcsaddul** [comment]
I encountered that before when I used async download of both pdfmake.min.js and vfs_fonts.js when vfs_fonts.js is downloaded first.  To avoid this, make sure that you download pdfmake.min.js first before vfs_fonts.js



     On Thursday, October 1, 2015 8:39 PM, Dominic Garms <notifications@github.com> wrote:
   

 Hello,with Firefox 41.0.1 I receive this.baseSystem is undefined
r.prototype.readFileSync

With Chrome I don't have any problem. I'm calling pdfmake with following function:pdfMake.createPdf(docDefinition).download()
Any ideas about this issue? I use the newest bower version. Thanks—

**Comment by vijay1675** [comment]
Hi,
TypeError: this.baseSystem is undefined issue in  firebox 45.0b10 while pdfmake. but  Chrome browser working well. How to solve this issue..

Thanks...

**Comment by liborm85** [comment]
Use lastest version of pdfmake (0.1.22).

**Comment by vijay1675** [comment]
Thanks for your supports..
