### ISSUE TITLE
Cannot read property '_minWidth' of undefined 

### ISSUE THREAD

**Issue by infacq** [bpampuch/pdfmake#40]
I stumbled upon this error when trying to include the `colSpan`. 

```
[{ text: 'header ', colSpan: 3, style: 'header', alignment: 'center' }],
```

**Comment by kumar612** [comment]
i am new to pdfMake ... so i have this doubt ? i want to have a table like this.
![untitled](https://cloud.githubusercontent.com/assets/17428279/13249702/c85c8ebc-da4b-11e5-9d3b-c7662fb477cd.png)

but when i use colspan=4 .. it gives me an error saying "Cannot read property '_minWidth' of undefined".

code:

	body: [
		      [{ text: '', style: 'tableHeader', colSpan: 4, alignment: 'center' },{},{},{},{ text: 'Accepted', style: 'tableHeader', colSpan: 2, alignment: 'center' }, {},{ text: 'Rejected', style: 'tableHeader', colSpan: 5, alignment: 'center' },{},{},{},{},{ text: 'total', style: 'tableHeader', alignment: 'center' }],

                      [{ text: 'Authenticator', style: 'tableHeader', alignment: 'center' },{ text: 'Name', style: 'tableHeader', alignment: 'center' },{ text: 'Types', style: 'tableHeader', alignment: 'center' },{ text: 'Container', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text: '%', style: 'tableHeader', alignment: 'center' }, { text: 'ProcError', style: 'tableHeader', alignment: 'center' }, { text: 'AuthError', style: 'tableHeader', alignment: 'center' },{ text: 'lookupError', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text: 
alignment: 'center' }, { text: 'AuthError', style: 'tableHeader', alignment: 'center' },{ text: 'lookupError', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text:'%', style: 'tableHeader', alignment: 'center' }, { text: 'total', style: 'tableHeader', alignment: 'center' }],

		     [ 'Sample value 1', 'Sample value 2', 'Sample value 3','Sample value 4', 'Sample value 5', 'Sample value 3','Sample value 6', 'Sample value 7', 'Sample value 8','Sample value 9', 'Sample value 10', 'Sample value 11','Sample value 12'],		
]

thanks in advance.

**Comment by jayeshsheta** [comment]
@bpampuch i did same as per ur comment still got same error can u please review below snippet

`{"pageSize":"A6","pageOrientation":"landscape","content":[[{"style":"tableExample","table":{"headerRows":1,"widths":["auto","auto"],"body":[[{"text":"jayesh S","style":"tableHeader","colSpan":2,"alignment":"center"},{},{"text":"MAR-2021 PAY SLIP","style":"tableHeader","colSpan":2,"alignment":"left"},{}]]}},{"style":"tableExample","table":{"headerRows":1,"widths":["auto","auto"],"body":[[{"text":"paresh S","style":"tableHeader","colSpan":2,"alignment":"center"},{},{"text":"MAR-2021 PAY SLIP","style":"tableHeader","colSpan":2,"alignment":"left"},{}]]}}]],"styles":{"tableHeader":{"bold":true}}}`
