### ISSUE TITLE
Page break not always working

### ISSUE THREAD

**Issue by no-more** [bpampuch/pdfmake#405]
Hello,

I have a multi page table with sub tables that breaks well with some data and not with other. I think this depends on how the data fit on the page and sometime it broke the page break process.

Thanks

**Comment by no-more** [comment]
Hi,

I have created a codepen here : http://codepen.io/anon/pen/EVwEeo

Please note in Firefox pdf.download(); does not work too (this is another issue already posted)

Thanks a lot

**Comment by no-more** [comment]
Hello,

Is any one at least reproducing this bug ?

Thanks.

**Comment by DavidYCZhou** [comment]
+ 1

**Comment by peterbartos** [comment]
+1

**Comment by paulosborne** [comment]
+1

**Comment by liborm85** [comment]
@no-more pdfmake requires text in format string, but you also used the format number. I added support for cast number to string. https://github.com/bpampuch/pdfmake/commit/b34dde51f0173bbe6b82143176e079da0de6885a
