### ISSUE TITLE
Tables with images breaking between pages

### ISSUE THREAD

**Issue by juliekirwin** [bpampuch/pdfmake#406]
Hello, besides the issues I found with #399, I noticed that the cell text in between rows breaks out of the table when there is a image and the image goes onto the next page like it should. Is there a workaround for this?  

![image](https://cloud.githubusercontent.com/assets/3643156/10337536/4ae3152c-6cce-11e5-903e-c936721e16e1.png)

**Comment by liborm85** [comment]
Same as https://github.com/bpampuch/pdfmake/issues/371.
