### ISSUE TITLE
Prevent page break

### ISSUE THREAD

**Issue by no-more** [bpampuch/pdfmake#407]
Hello,

This one might not be possible, but I prefer to ask. Is there anyway to prevent pagebreak on some elements ? I have a big table with small tables inside. those table should always be quite small and it would be great to be able to prevent pagebreak inside them.

Thanks a lot.

Great tool !!!

**Comment by khaivngo** [comment]
Anyone got a clue?

**Comment by liborm85** [comment]
Use `dontBreakRows: true` in table definition
