### ISSUE TITLE
How to sent file into the printer using .print()

### ISSUE THREAD

**Issue by venhels** [bpampuch/pdfmake#408]
How can I send the print file into the printer using .print() function on pdfmake?

my code is

pdfMake.createPdf(docDefinition).print();

when I watch console I can see

Resource interpreted as Document but transferred with MIME type application/pdf: "data:application/pdf;base64,JVBERi0xLjMKJf////8KNiAwIG9iago8PAovVHlwZSAvRXh…AxNQovUm9vdCAyIDAgUgovSW5mbyAxMSAwIFIKPj4Kc3RhcnR4cmVmCjQyNzA3CiUlRU9GCg==".

but I cant see the file being queued on the printer..

I can also successfully generate a pdf file on other window using pdfMake.createPdf(docDefinition).open(); and automatically download the pdf using pdfMake.createPdf(docDefinition).download('file.pdf');

even I am trying the print button on their site http://pdfmake.org/playground.html its still not working.

I am using Google Chrome Version 45.0.2454.101 m any suggestions are greatly appreciated.. Thanks.!

**Comment by liborm85** [comment]
Use latest version, it works.
