### ISSUE TITLE
Not a supported font format or standard PDF font. for hebrew font TTF

### ISSUE THREAD

**Issue by RonCan** [bpampuch/pdfmake#409]
Hello I'm trying to use http://www.pement.org/heb_fonts/david.zip this and others from the same site. But I get the above error, I'm not sure why. What can I do to render Hebrew fonts now? I followed the Use Custom Font guide and did everything correctly(to my knowledge) but I think there's something wrong with these font files. I'm using

```
                pdfMake.fonts = {
                Hebrew: {
                    normal: 'HEBREW.TTF'
                }
            }

                     defaultStyle: {
                    columnGap: 15,
                    font: 'Hebrew'
                }
```

This code to render. Please guide

**Comment by RonCan** [comment]
I was able to resolve the above by adding other parts e.g. bold,italic like this

                    pdfMake.fonts = {
                    Hebrew: {
                        normal: 'HEBREW.TTF',
                        bold: 'HEBREW.TTF',
                        italics: 'HEBREW.TTF',
                        bolditalics: 'HEBREW.TTF'
                    }
                }

But now I'm facing another problem, the Hebrew text is in the next column to CUSTNAME. It's still blank and all the other english text has malformed too. What am I doing wrong?

![screenshot from 2015-10-10 19 15 43](https://cloud.githubusercontent.com/assets/4863594/10411568/c9f397bc-6f83-11e5-83c5-3742fb29ae50.png)

**Comment by liborm85** [comment]
Can you try latest version?

**Comment by liborm85** [comment]
Is needed RTL support. RTL issue: https://github.com/bpampuch/pdfmake/issues/184
