### ISSUE TITLE
trying to open more than one pdf document 

### ISSUE THREAD

**Issue by mgrivera** [bpampuch/pdfmake#410]
Hi, 

I'm trying to create several documents at on once. If I use: 

``` javascript
var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).open();
```

it opens a window and shows my document. Now, If I use: 

``` javascript
var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).open();
docDefinition = {}; 
docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).open();
```

It opens _just one_ window with the first document. For the second, it shows this error in the developers tools console (and, of course, stops and does not build the second document): 

> Uncaught TypeError: Cannot read property 'location' of undefined

Am I missing something here? 

Many thanks and bye ...

**Comment by mgrivera** [comment]
Hi, 

I think I know what is happening here, although I still don´t know how to solve the issue. 
When my code tries to build two documents, one after another, *pdfMake.createPdf(docDefinition).open()*, effectively opens and focus in the new window *before* is has built the second one. When the second document is built and *pdfMake.createPdf(docDefinition).open()* executes again, it happens in the new opened window; I mean, not in the original window, and the error occurs because of that. 

If you build and open one document; return to the original window and build the second one, everything executes perfect. 

So, I think, the error occurs when building the second document and using that just opened window as a context. Does this reasoning makes sense? ... 

So, I think the question should be: how to build several documents at once and opened the new windows just at the end, when all the code has already executed?? 

Thanks and bye ...

**Comment by timkrins** [comment]
I can't replicate your error with Chrome 45.0.2454.101
Which browser are you using, and which pdfmake library version?

**Comment by mgrivera** [comment]
Hi Tim and thanks for ansewring ... 

Google Chrome just updated itself when I went to "help and about" to see which version I was on. Now, my version is (I suppose the latest): **46.0.2490.71m**

Regarding the pdfMake version, I'm using Meteor, so I picked up the pdfMake that comes with the *nilsdannemann:pdfmake* package. In the docs, it says the pdfMake version the package uses is **0.1.17** and I think it is the latest. 

I tried again this issue and got the same error message, I'm just doing: 

```javascript
var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).open();

docDefinition = {};
docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).open();
```

I get just one pdf document and this is the error in chrome console: 

> Uncaught TypeError: Cannot read property 'location' of undefined 

The focus passes to the pdf document in the *new* chrome window, and I think this may be the problem, because if I create one document go to the original window and create another, everything works as expected. 

Any help is very welcomed ... Thanks and bye ...

**Comment by juliovivanco** [comment]
This error occurs when google blocks pop-ups. I get same problem today.

**Comment by mgrivera** [comment]
Haven't got this issue anymore. I'm using version 0.1.20 of pdfMake. I just checked this out today and everything was fine. Maybe, before, the issue was because Chrome was blocking pop-ups ...

**Comment by liborm85** [comment]
stackoverflow:
http://stackoverflow.com/questions/41220342/download-multiple-files-using-pdfmake/41235131#41235131
