### ISSUE TITLE
Images on footer don't display properly after Page 1

### ISSUE THREAD

**Issue by gmonterroso** [bpampuch/pdfmake#411]
I have the following on my footer

footer: {
    columns: [
        { image: image1, fit: [150, 15] },
        { image: image2, fit: [150, 15] },
        { text: 'text1' },
        { text: 'text2' }
    ]
},

In Page1 the footer is displayed properly but not in the next pages.

image1, text1 and text2 always displays properly but not image2.

In Page2: image2 is drawn over text1
In Page3: image2 is drawn over text2
In Page4 until last Page: image2 is missing.

**Comment by javo01** [comment]
have you found out a solution?

**Comment by liborm85** [comment]
Use `footer` as function.
