### ISSUE TITLE
Creating borders around images

### ISSUE THREAD

**Issue by IbrahimAmin** [bpampuch/pdfmake#413]
I love your project, it really helped me with what am trying to achieve but i only got one obstacle that i can't get around which is creating borders around images or at least a hack that would provide the same feeling perhaps borders around columns and image inside of it with 0 padding, i don't know what do you suggest :)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/385

**Comment by Diferno** [comment]
Hi @IbrahimAmin , my workaround your issue was to use ( [graphicsMagick](https://www.npmjs.com/package/gm) and modify the image before adding it to the PDF. 

In my use case, I fetch the image from a url so I use request module to:
```
        var request = require('request').defaults({ encoding: null });
        gm(request(url))
        .borderColor('#000')
        .border(1,1)
        .resize(500,500)
        .toBuffer('PNG', function(err, buffer){
            if (err) return callback(err)
            else {
                let dataPrefix = `data:image/png;base64,`
                data = dataPrefix + buffer.toString('base64')
                // console.log(data);
                return callback(null, data)
            }
        })
```
Hope it helps :)
