### ISSUE TITLE
iOS issue on print with images

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#414]
Hello,

my PDF creation works fine on standard Safari, Firefox and Chrome and Android. 

But on iOS it fails, a new tab is getting opened but without any content. I am using `.download()`method so I thought it will get downloaded immediately? Anything I could do about it? The size is ~800kb so I guess it happens because of the size of the PDF.
Thanks Dominic

**Comment by dohomi** [comment]
This is the error message:
```
TypeError: undefined is not an object (evaluating 'e.location')
(anonymous function)pdfmake.min.js:1:1043
(anonymous function)pdfmake.min.js:1:2094
(anonymous function)pdfmake.min.js:1:771
emitpdfmake.min.js:9:26386
(anonymous function)pdfmake.min.js:10:1127
runpdfmake.min.js:10:6798
rpdfmake.min.js:10:6430
```

**Comment by mikehuebner** [comment]
If you can, try an unminified version, helps with debugging.
Besides that, according to the documentation the `.download()` only works in Chrome. It crashes every other browser for me. `.open()` seems to have its limits, IE is a definite case as anything over 5k doesn't seem to work. Regardless, there is no where to download it on iOS, you can't really download a file on iOS easily. Does `.open()` do anything?
Thanks!

**Comment by dohomi** [comment]
@mikehuebner I narrowed it down with following approach and now it works on almost all platforms with all browsers. Importantly I don't use the ```.download()```nor```.open()``` any more because for iOS there must be the ultimate click event which calls the download of the generated blob - the click event is getting lost. Here a snippet from my approach.
function
```
function createPdfBuffer(){
(... creation of docDefinition)
var defered = $q.defer();
pdfMake.createPdf(docDefinition).getBuffer(function(result) {
  defered.resolve(result);
});
return defered.promise;
}

// call the function
var objectURL; 
createPdfBuffer().then(function(result){
  currentBlob = new Blob([result], {type: 'application/pdf'});
  objectURL = URL.createObjectURL(currentBlob);
}

// this is a click on any HTML link or click event
function clickDownloadPdf(){
  // making use of FileSaver project to save it
  FileSaver.saveAs({
    data:currentBlob
   filename:'Some title'
  });
}
```
Most importantly after all my excursion there is ```FileSaver```included in the build of ```pdfmake```but its not available for public. Is it possible having a build without ```FileSaver```and the public ```download open print```functions?

**Comment by balilaszlo** [comment]
@dohomi 
Ok, but what if the data-s come from the server as JSON pls.
I have the same issues like yours, IOS always goes on different ways :-)

**Comment by mikehuebner** [comment]
@balilaszlo 
If the JSON data is coming from the server you have to massage that data to fit the format of the PDF. So as it comes in just read the specifications of what everything needs (I did a loop through the data in JS and then just ran PDF make once I felt it was ready). It's a ton of mutation of the JSON to get it to work, but it does. Honestly I found myself dropping this plugin not because its bad but because I needed massive generation support. Which this plugin just crawls with sadly... So I just did it in PHP using FPDF, so this became a sort of irrelevant issue for me. The work around was just too annoying as I couldn't find a solution that actually met the needs of what I was doing.

**Comment by balilaszlo** [comment]
Creating proper JSON on server side and sending back to client is working well in my project. I did it according the documentation.

2015. dec. 27. dátummal, 6:25 időpontban Mike <notifications@github.com> írta:

**Comment by sganeshkumar** [comment]
I also face same problem like Dohomi. Any solution plz help me.

**Comment by liborm85** [comment]
reference: https://github.com/bpampuch/pdfmake/issues/800

**Comment by liborm85** [comment]
Was previously fixed in files-saver, see https://github.com/eligrey/FileSaver.js/issues/12
