### ISSUE TITLE
Don´t show table images ...

### ISSUE THREAD

**Issue by 4inn** [bpampuch/pdfmake#415]
Hi, I use pdfmake and datatables ... I have a table with images in a single column , but when I export PDF, do not show me the pictures in this column ... use the standard `<img>` statement to show images

It has a solution ?
Thanks...
(Sorry for my english)

**Comment by mikehuebner** [comment]
We would need to see your document definition you are sending!
Just `JSON.stringify(docDef)` it and post it in a gist or post it directly here!

**Comment by DataTables** [comment]
This is a question that comes up fairly frequently in the DataTables forums. My understanding is that pdfmake needs the images in base64 format (happy to be corrected there) - and simply padding an HTML `<img>` tag is not enough.

Therefore some kind of formatter would be needed to transform the `img` tag to base64 for the pdf creation.

**Comment by mikehuebner** [comment]
@DataTables This actually makes sense, I just tried to render an image using the HTML tag and it gave me an error (didn't even render anything to the page). So I assume we should probably look into a better solution for image management? I'll end up taking a look sometime soon.

**Comment by liborm85** [comment]
No reaction.
