### ISSUE TITLE
update npm to current 0.1.20

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#417]
Hello,

is there a plan to upload current 0.1.20 to npm?

Currently the 0.1.18 is available.

Cheers

**Comment by oles-io** [comment]
I'd love to see 0.1.20 live on NPM as well.

Really could use the https://github.com/bpampuch/pdfmake/pull/349/commits

**Comment by chulkilee** [comment]
Although I can use it directly from github, it would be nice to have it in npm repo.

**Comment by liborm85** [comment]
New version released and published in npm.
