### ISSUE TITLE
ul bullet-point colour always black

### ISSUE THREAD

**Issue by zerebruin** [bpampuch/pdfmake#418]
Bullet point colour cannot be influenced and are always black. 
Expected behaviour (equivalent to css) would be that the bullet point have the same colour as the text.

Example code:
<code>
  {
          ul: [
            'one',
            'two',
            'three',
          ],
          fontSize: 18,
          alignment: 'left',
          margin: [0, 0, 0, 4],
          color: '#fffffff',
}
</code>

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/1e65d438e98bc729ef7f4987a1ddabfa6cf9aa48
