### ISSUE TITLE
using unminified version of pdfmake

### ISSUE THREAD

**Issue by dohomi** [bpampuch/pdfmake#419]
Hello,

in my current project the creation of pdfmake fails inside of the library. So I would like to use the unminified version, but this one seems not to work:
``` 
TypeError: pdfMake.createPdf is not a function
```
Any idea how to solve this?

Thanks!

**Comment by mikehuebner** [comment]
I would need to see where you're including this in your scripts to see what is going on. If your using gulp or grunt, make sure you're not wrapping this in its own `(function(){}();` tags.

**Comment by dohomi** [comment]
@mikehuebner sorry this was just an integration mistake. Thanks for your feedback
