### ISSUE TITLE
Unrecognized document structure error, not sure how to fix...

### ISSUE THREAD

**Issue by mikehuebner** [bpampuch/pdfmake#420]
Hello everyone!
This product is awesome but I'm beating my head against a wall with an issue, I would love to have some feedback on what is wrong!

```
Unrecognized document structure: {"value":"","_margin":null}
```

Here is a link to my data structure.
https://gist.github.com/mikehuebner/96f9af6e6aea68f28b95

I'm generating data behind the scenes before I show it and I'm trying to create multiple tables, then I break the page after that, then generate the PDF. So basically each table will have 2 rows (a header and a user row), then page break. Repeat until data is done type of thing. But I'm having an issue where this error popped up and now real error message showed. This is all I have.
![image](https://cloud.githubusercontent.com/assets/6125123/10657830/98ad7a86-7845-11e5-852b-bd8c4cc6a193.png)

Any help is appreciated. There is a lot of data there but I can't find why I'm getting this error upon generation... Thanks!

**Comment by mikehuebner** [comment]
Somewhat fixed, changed value: to text: and what seemed to work. But now dealing with headers not showing up on the tables if I push the values to gether.

**Comment by mikehuebner** [comment]
Headers show in the playground when I copy and paste it directly in, but otherwise the headers are blank
![image](https://cloud.githubusercontent.com/assets/6125123/10682699/bbf99ada-78ed-11e5-836f-766681515c98.png)

**Comment by mikehuebner** [comment]
Check reference for semi-fix for performance of large tables.

**Comment by surajkhanal** [comment]
I think  issue with the spacing of content.

**Comment by yanickrochon** [comment]
A JSON object that works at http://pdfmake.org/playground.html fails in my code with 

> Uncaught (in promise) Unrecognized document structure: {"_margin":null}

Not sure where the error is... the definition is quite large.

**Comment by yanickrochon** [comment]
The problem was a dynamic part of the definition, generated by the app, appended a `undefined` values under certain use cases. Setting an empty string resolve the problem for me.

**Comment by sivakrishna551** [comment]
I used the following parsing it worked for me.
         docDefinition.dom=JSON.stringify(docDefinition);
            docDefinition.dom=JSON.parse(docDefinition.dom);
 pdfMake.createPdf( docDefinition.dom).download("SampleDom.pdf");
Finally i was given docDefinition.dom as my latest docDefinition.

**Comment by sivakrishna551** [comment]
instead of
pdfMake.createPdf( docDefinition).download("SampleDom.pdf");

the above line use the below lines of code,

docDefinition.dom=JSON.stringify(docDefinition);
docDefinition.dom=JSON.parse(docDefinition.dom);
pdfMake.createPdf( docDefinition.dom).download("SampleDom.pdf");

**Comment by liborm85** [comment]
The rows are empty, because you're not defined any text in any cell.

**Comment by syedhaffiz7** [comment]
Do not have any undefined variables or empty variables in your input data to pdfMake. This solves the issue.

**Comment by lohiyaabhishek** [comment]
I am facing performance issue while exporting pdf through pdfmake.min.js .
I am not able find below function in pdfmake.js file.

function flow(stream) {
var state = stream._readableState;
debug('flow', state.flowing);
if (state.flowing) {
do {
var chunk = stream.read(Number.MAX_SAFE_INTEGER); // grab MAX_SAFE_INTEGER bytes
} while (null !== chunk && state.flowing);
}
}
Is there any change in the name of above function?

**Comment by syedhaffiz7** [comment]
Line 1:  var flow = function (stream) {

this is the change

**Comment by olafur-palsson** [comment]
Would be great to have the path to the faulty part of the document in this one

**Comment by yanickrochon** [comment]
> how you able to solve it? this JSON rendering file on pdfMake playground, but giving error on code. could you help me to find the solution?
> 

Ow, that was over 7 years ago! You might have better luck on StackOverflow for this?
