### ISSUE TITLE
Open PDF blocked as popup

### ISSUE THREAD

**Issue by depiction** [bpampuch/pdfmake#424]
I'm just starting to use pdfmake. When I call pdfMake.createPdf(docDefinition).open(); it creates a popup that is blocked in most browsers by default. I don't want users to have to allow popups on my site.

Is there an alternative?

**Comment by zhulduz** [comment]
I guess you should check next solutions:
http://stackoverflow.com/questions/9514698/bypass-popup-blocker-on-window-open-when-jquery-event-preventdefault-is-set
http://stackoverflow.com/questions/2587677/avoid-browser-popup-blockers

**Comment by liborm85** [comment]
Answered.

**Comment by moffsugita** [comment]
https://github.com/bpampuch/pdfmake/issues/587
I used "liborm85 commented on 2 Apr 2017"

```
    const pdfDocGenerator = pdfMake.createPdf(docDefinition);
    var win = window.open('', '_blank');
    (pdfDocGenerator as any).open({}, win);
```

did you work?
