### ISSUE TITLE
Is it possible to lazyload vfs_fonts.js?

### ISSUE THREAD

**Issue by seiyata** [bpampuch/pdfmake#425]
I'm using pdfmake in an angular web app. 

As I needed to use Japanese characters in PDF, I created vfs_fonts.js with Japanese font according to
https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
and the size of the file became more than 8M byte.

PDF output function is used only by admin user, so I'd like to avoid the big file load from the top page. Are there any ways to load vfs_fonts.js lazily with Angular?

**Comment by depiction** [comment]
You could use requirejs to only load the necessary files for pdfmake when needed (ex: user clicks a  download PDF button).

**Comment by liborm85** [comment]
Answered.
