### ISSUE TITLE
Support for External Fonts (Google Fonts and Typekit)

### ISSUE THREAD

**Issue by depiction** [bpampuch/pdfmake#426]
I'm using Adobe Typekit fonts on my site, but it appears that I can only use open source fonts stored on my server with pdfmake. Please add support for using external fonts from services like Google Font Library and Typekit.

**Comment by gabboman** [comment]
You should download the fonts you want to use and then recompile vfs_fonts.js, as I understood

**Comment by seansimonanimation** [comment]
You can also convert the font into base64, write them into the end of vfs_fonts.js under the correct font's name, then declare them in your app.

**Comment by depiction** [comment]
I wrote this as a feature request. With Typekit and Google Fonts one doesn't actually have the font files; they are in the cloud. It would be nice for pdfmake to pull fonts from these services. For now I'm using local fonts and compiling them into vfs_fonts.js.

**Comment by hks2002** [comment]
I recompile my font to vfs_fons.js, my font is chinese simun.ttf. my chinese text doesn't show in pdf, i try to copy it from the generated pdf, then past it into text edit grogram, i can see chinese text in the text edit program again. what's it the problem?

**Comment by waynelouflz** [comment]
hks2002:

I am having exactly the same problem, have you found out a solution yet?

**Comment by hks2002** [comment]
the other font arial.ttf and simfang.ttf works, you can try it.

**Comment by liborm85** [comment]
In version 0.1.66 can be used external fonts via url (https or http), see [documentation](https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/url/).
