### ISSUE TITLE
Client-side version on npm

### ISSUE THREAD

**Issue by AaronBuxbaum** [bpampuch/pdfmake#429]
I work in an environment where bower is blocked by the firewall (I know...), so we need to use npm instead. Unfortunately, the npm version of `pdfmake` is the server side version, which isn't the one I want in this case. Is the only solution to just pull in the raw files and keep an eye on updates, or is there a way to do this with npm (or really any version tracker but bower)?

**Comment by JLLeitschuh** [comment]
Same problem. These should be published as two different packages to npm

**Comment by ghislainf** [comment]
+1000

**Comment by ghislainf** [comment]
Can you create repository & npm package `pdfmake-client` with the client build ?

**Comment by AaronBuxbaum** [comment]
I created a wrapper repo until it's done by OP: `https://www.npmjs.com/package/pdfmake-client`

**Comment by ghislainf** [comment]
My bad, the solution is on the package `pdfmake-browserified`

**Comment by SirHenry** [comment]
> I created a wrapper repo until it's done by OP: https://www.npmjs.com/package/pdfmake-client
Which pdfmake version is used inside pdfmake-client?

**Comment by AaronBuxbaum** [comment]
@SirHenry: v0.1.20

**Comment by liborm85** [comment]
New version 0.1.22 released. Through npm is available.
