### ISSUE TITLE
Specify alignment for table, not just cells

### ISSUE THREAD

**Issue by depiction** [bpampuch/pdfmake#432]
I'm building a large table with all cell content centered within each cell except for two of the columns. I know I can add alignment: 'center' to individual cells, but it would be nice set that at the table level as well to be more efficient. I tried specifying the alignment at the table level, but it didn't work. Setting the alignment on individual cells should still work and override what is set at the table level.

**Comment by liborm85** [comment]
Yes, it is possible.
Example:
```
var dd = {
	content: [
		{
		    'alignment': 'center',
			table: {
				body: [
					['Column 1', 'Column 2', 'Column 3'],
					['One value goes here', 'Another one here', 'OK?']
				]
			}
		}
	]
}
```

**Comment by aruprakshit** [comment]
@liborm85 It doesn't center the table.

<img width="1434" alt="Screenshot 2019-06-03 at 5 12 55 PM" src="https://user-images.githubusercontent.com/3428463/58799402-e590e880-8622-11e9-998d-58761e4b0779.png">
