### ISSUE TITLE
Text wrapping breaks after the pagebreak.

### ISSUE THREAD

**Issue by seansimonanimation** [bpampuch/pdfmake#433]
![Visual example of the bug](http://s14.postimg.org/9lxli2q41/pdfmake_bug.png)

On the left is the input as done by the user, and on the right is how PDFMake handles that input.

Here is the source for my project: https://github.com/seansimonanimation/Screentastic/

**Comment by seansimonanimation** [comment]
I've done some playing around. A workaround (at least for my project) is to force a pageBreak: "before" or pageBreak: "after" on every line that activates the autogenerating code. It's icky, and a proper fix would be preferable, but it's something for now.

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/287362a1b4763ee99fc0bb04061e12af9ee9e6d9
