### ISSUE TITLE
How to use on the browser with webpack?

### ISSUE THREAD

**Issue by Agamennon** [bpampuch/pdfmake#436]
I want to use this lib on the browser,  how do i configure webpack to bring in the bower version?  the standard procedures are flailing me!  i am using 

```
resolve:{
  alias:{
     'pdfmake':path.join(__dirname,'bower_components/pdfmake/build/pdfmake.js")
  }
}
```

and `var pdfMake = require('pdfmake')` but pdfMake is an empty object! , i also tried using externals and inserting the `<script>`  tags with the same results!

**Comment by circy** [comment]
[check out this ;)](https://github.com/bpampuch/pdfmake/issues/150#issuecomment-156143062)
