### ISSUE TITLE
Background image overwrite 'fillColor' on table

### ISSUE THREAD

**Issue by shadowRR** [bpampuch/pdfmake#437]
Hey guys,

If i add an image as a background layer, the `fillColor` property on table gets overwritten and disappear...

Is that the normal behavior ?

And example, to c/c in the playground :

```
var dd = {
    background: [{
        image: 'sampleImage.jpg'
    }],
    content: [{
        table: {
            body: [
                [{
                        text: 'Column 1',
                        fillColor: 'grey'
                    },
                    'Column 2',
                    'Column 3'
                ],
            ]
        }
    }]
}
```

You just have to comment the image on the background to see the difference.

**Comment by labe-me** [comment]
+1

**Comment by csbatista** [comment]
Any fix on this yet?

**Comment by peter6006** [comment]
put "headerRows: 1," inside your table, before the body.

**Comment by gabrielenosso** [comment]
headerRows solves the problem, but only for the number of rows that you specify.

so if you use headerRows: 1, but you have a background colored cell in the 3rd row, it won't appear colored.

**Comment by Procaseycash** [comment]
how can i make the background image look faded?

**Comment by liborm85** [comment]
Fixed by PR https://github.com/bpampuch/pdfmake/pull/1201.

**Comment by Mourdraug** [comment]
It seems to still be the case if you use vectors for background image. Only first shape on canvas is hidden under fill, every other shape will be rendered over table fill.
