### ISSUE TITLE
Understanding content.splice()

### ISSUE THREAD

**Issue by cce1911** [bpampuch/pdfmake#438]
I'm using jQuery dataTables.net and they reference the ability to customize the document object using a callback function. In their example (https://datatables.net/reference/button/pdfHtml5) they insert an image. 

```
function ( doc ) {
                // Splice the image in after the header, but before the table
                doc.content.splice( 1, 0, {
                    margin: [ 0, 0, 0, 12 ],
                    alignment: 'center',
                    image: 'data:image/png;base64...'
                } );
```

I'm trying to insert a footer containing a URL, but I can't find any documentation on content.splice(). Is this a datatables function or a pdfmake function? Nothing I've tried so far works. How do I add a page footer on every page?

**Comment by cce1911** [comment]
So I determined that content.splice() is the way that dataTables accesses the content array. splice() is just the Jquery splice() method for inserting and deleting data from this array. So, I did figure out how to add the footer using the playground, but the same code doesn't work with the datatables plugin. Bottom line is that this appears to be a datatables issue, not a pdfmake issue.

**Comment by liborm85** [comment]
Is not related to pdfmake.
