### ISSUE TITLE
Unicode Font Display Error in Myanmar (Burma) fonts

### ISSUE THREAD

**Issue by kaunghtetaung** [bpampuch/pdfmake#439]
Hello, 

I changed default font to Myanmar (Burmese) Unicode Font. It is working but Unicode char display is not show correctly. 
Please see this error link --> http://prntscr.com/93nxfm.
This is correct link.  -->   http://prntscr.com/93nxvn

Help me please!

**Comment by liborm85** [comment]
Please, can you try it with latest version?
