### ISSUE TITLE
How to make table width 100% of page size

### ISSUE THREAD

**Issue by infacq** [bpampuch/pdfmake#44]

**Comment by hisuwh** [comment]
When you're dynamically generating tables this isn't helpful because you're not necessarily setting the right column to `*` and you can end up with a wonky looking table.

I want all my columns as `auto` but taking up the full width of the page.  Is this not possible?

**Comment by sinaf97** [comment]
> When you're dynamically generating tables this isn't helpful because you're not necessarily setting the right column to `*` and you can end up with a wonky looking table.
> 
> I want all my columns as `auto` but taking up the full width of the page. Is this not possible?

You can set `widths` property to `['*', '*', '*', ..., '*', '*', 'auto']`. This way your last cell will remain automatic(to avoid page overflow) while other cells are filling the page width. You can use `...[Array(headers,length-2).fill('*'), 'auto']` to create it dynamically.
