### ISSUE TITLE
How to rename column names with dynamic data?

### ISSUE THREAD

**Issue by aditeswarreddy** [bpampuch/pdfmake#440]
I'm unable to rename the column names while working with the dynamic data?
Ex: rt_nm = Route Name #24

**Comment by naqib83** [comment]
Any solution yet?

**Comment by liborm85** [comment]
Comment https://github.com/bpampuch/pdfmake/issues/24#issuecomment-42662042 is only as example, you can customize in any way according to your requirements. For example, you can add the parameter with titles
