### ISSUE TITLE
linktopage - jumping to a particular page

### ISSUE THREAD

**Issue by athavanraja** [bpampuch/pdfmake#442]
I looked around for a feature to link to a page (by page number - jumping from one page to another) within the document , couldn't find anything and then I found this (https://github.com/devongovett/pdfkit/issues/421) in pdfkit and was able to incorporate this into pdfmake. 

Here is how I have done it .
1.  { text: 'Go to page  5', targetpage: 4}
2. added the function "linktopage" to pdfmake.js (refer the above link)
3. created another annotate function similar to issue 421 in pdfkit
4. and then added functions similar to how "link" is enabled
   if (inline.targetpage) {
               pdfKitDoc.linkToPage(x + inline.x, pdfKitDoc.page.height - y - lineHeight, inline.width, lineHeight,inline.targetpage);
           }

Its working fine, however I am not happy with the approach of another annotate function , should have adjusted the exiting one.

If someone could kindly add this feature to pdfmake that will be great.

Thanks in advance.

Regards
Raja

**Comment by gigglegirl** [comment]
Hi Raja , 

   I am still not clear how can i link text to a particular page 
   Do i have to just mention the 'targetpage' property or do i have write 'linkToPage ' and 'annotate' 
   function .
   I am not much clear with it .Please help .

   Thanks
   Laxmi

**Comment by gigglegirl** [comment]
Hi Raja , 

   It Would be great if you could give me some example and i can check it playground to understand 
   clearly.

  Thanks
  Laxmi

**Comment by liborm85** [comment]
This is only feature request, not yet implemented in pdfmake.

**Comment by gigglegirl** [comment]
Ok Thanks 

Laxmi

**Comment by cricri** [comment]
#970

**Comment by liborm85** [comment]
Implemented by PR #970.

**Comment by cricri** [comment]
could you bump the version please?

**Comment by liborm85** [comment]
New version will be tomorrow.
