### ISSUE TITLE
The image's margin is not right

### ISSUE THREAD

**Issue by LeoLPF** [bpampuch/pdfmake#446]
When I use padfmake.js to generate a pdf document,I find a problem that when the static header or static footer contains a image ,the image's x margin would be not right in the next page.
From the source I found a line code "image.x = context.x + (image.x || 0);" in the function named "addImage" of "ElementWriter" . Can you explain why the image.x should be added to context.x?

**Comment by rpocklin** [comment]
I have the same problem.  I have a small logo on the top left header for each page and on progressive pages it increase the left position by the amount of it's margin.

**Comment by vipex** [comment]
+1

**Comment by vipex** [comment]
Duplicate issue, take a look at #376

**Comment by antoinepairet** [comment]
https://github.com/bpampuch/pdfmake/issues/376
The solution is to use a function to return a new object each time the header needs to be rendered.

**Comment by LeoLPF** [comment]
Thank you very much! I tried,and it works right.But just a moment ago, I have read #376.I noticed psuhas  suggested to change  "image.x = context.x + (image.x || 0);" to "image.x = context.x;". I solved this problem in this way four months ago. So I wandered whether it would be proper to change  "image.x = context.x + (image.x || 0);" to "image.x = context.x;".

**Comment by LeoLPF** [comment]
@vipex and @antoinepairet , Thank you very much! I tried,and it works right.But just a moment ago, I have read #376.I noticed psuhas suggested to change "image.x = context.x + (image.x || 0);" to "image.x = context.x;". I solved this problem in this way four months ago. So I wandered whether it would be proper to change "image.x = context.x + (image.x || 0);" to "image.x = context.x;".

**Comment by LeoLPF** [comment]
@vipex and @antoinepairet ,Thank you very much! I tried,and it works right.But just a moment ago, I have read #376 .I noticed @psuhas suggested to change "image.x = context.x + (image.x || 0);" to "image.x = context.x;". I solved this problem in this way four months ago. So I wandered whether it would be proper to change "image.x = context.x + (image.x || 0);" to "image.x = context.x;".

**Comment by liborm85** [comment]
Fix is included in the new version (0.1.22).
