### ISSUE TITLE
Array of Images

### ISSUE THREAD

**Issue by rschramm** [bpampuch/pdfmake#447]
It is possible to have an array of text items in a column text: [{text...].  However, applying the same format to image:[{image...] blows up.  Is there a way around this or can it be fixed?

**Comment by liborm85** [comment]
This is not supported.

Need to be implemented horizontal stack: https://github.com/bpampuch/pdfmake/issues/358

**Comment by MussaCharles** [comment]
@rschramm  did you find any workaround for this issue? I have the same problem as I get a dynamic array of images from server and I have to create a grid layout pdf document.

**Comment by MikeAmezcua22** [comment]
Could you find something, about a grid layout?
