### ISSUE TITLE
table with many rows

### ISSUE THREAD

**Issue by droshi** [bpampuch/pdfmake#45]
I have a requirement for a PDF builder that can handle many rows (several thousand hopefully). pdfmake looks great, but seems to crash Chrome after about ~1500 rows maximum. Any chance that this is something the library could handle in the future?

I've tried a different server side utility that has similar problems after 3-4000 rows, but I like the idea of a javascript utility that relies on local resources rather than server resources.

**Comment by edenchen123** [comment]
any update on this, sorry to bring this up...

**Comment by liborm85** [comment]
According to post https://github.com/bpampuch/pdfmake/issues/947#issuecomment-293494738 10000 rows is not a problem.
