### ISSUE TITLE
dontBreakRows results in strange border styling bug

### ISSUE THREAD

**Issue by AaronBuxbaum** [bpampuch/pdfmake#450]
I'm finding that using `dontBreakRows` results in strange border styling.

With `dontBreakRows: true`:
<img width="225" alt="screen shot 2015-12-01 at 9 50 45 am" src="https://cloud.githubusercontent.com/assets/5578581/11503989/1d57faa0-9811-11e5-8dd7-ebe3b4547a28.png">

With `dontBreakRows: false`:
<img width="174" alt="screen shot 2015-12-01 at 9 51 15 am" src="https://cloud.githubusercontent.com/assets/5578581/11503994/21027ebe-9811-11e5-9742-db11c148acb0.png">

Here's what my layout styling looks like:

```
table: {
    dontBreakRows: true,
    headerRows: 1,
    keepWithHeaderRows: 1,
    ...
},
layout: {
    hLineColor: '#ddd',
    vLineWidth: function () { return 0; },
    hLineWidth: function (i, node) {
        switch (i) {
            case 0:
            case node.table.body.length:
                return 0;
           case 1:
                return 2;
           default:
                return 1;
        }
    },
    paddingTop: function () { return padding; },
    paddingBottom: function () { return padding; }
}
```

In this example, `padding` is set to `8`.

**Comment by JcBernack** [comment]
I'm using the predefined "lightHorizontalLines" layout and have exactly the same issue. The first row after the header is not styled correctly.

**Comment by no-more** [comment]
Same here, I have strange border result. But this fix some renders issues.

**Comment by KthProg** [comment]
I seem to be having a similar issue. In my case the line thicknesses are incorrect, and the top border is missing.

**Comment by khaivngo** [comment]
Same here.

**Comment by rjmasikome** [comment]
I fixed this issue by changing the snippet (line 18564-18574) to the following 
```js
if(this.dontBreakRows) {
	writer.tracker.auto('pageChanged',
	function() {
		//self.drawHorizontalLine(rowIndex, writer);
	},
	function() {
		writer.commitUnbreakableBlock();
		//self.drawHorizontalLine(rowIndex, writer);
	}
	);
}
```

**Comment by deanmikel** [comment]
This issue appears to be fixed in the newer project [pdfmake/pdfmake](https://github.com/pdfmake/pdfmake). Apparently this project bpampuch/pdfmake is deprecated and the pdfmake.org link still points here instead of pdfmake/pdfmake. So it's easy to get the old build by mistake.

**Comment by liborm85** [comment]
fixed by https://github.com/bpampuch/pdfmake/pull/494
