### ISSUE TITLE
Blob to PDF

### ISSUE THREAD

**Issue by DevQueen** [bpampuch/pdfmake#451]
I am using Angularjs in an Asp.net MVC project.  I am trying to save a blob of my HTML as a pdf.  The weird thing is that when I first tried the code below:

```
            var blob = new Blob([document.getElementById('exportable').innerHTML])
            var docDefinition = {
                content: [blob]
            }
            pdfMake.createPdf(docDefinition).open();
```

 the pdf opened and looked good, but when I tried to change open() to download() it began throwing an error that reads: "Unrecognized document structure: {"_margin":null}".  So then I tried:

```
            var blob = new Blob([document.getElementById('exportable').innerHTML])
            var docDefinition = {
                content: [blob,
                    {margin: 5}
            ]
            }
            pdfMake.createPdf(docDefinition).download();
```

but that didn't work either, and now even changing download() back to open() gives me the same "margin: null" error.  Please help.

**Comment by liborm85** [comment]
Do not do it as a blob, but as string/text.
