### ISSUE TITLE
Extra blank page at the end

### ISSUE THREAD

**Issue by PiyushRamuka** [bpampuch/pdfmake#452]
This may not be an issue; may be something i am missing. The script works and generates a PDF consisting of one page. However, when printed, it prints an extra blank page. Not sure why but it does it consistently. Is it normal or am i doing something wrong.

I even tried the playground pdf and it does the same thing. Is there any way to disable this extra page?

Thanks for your help in advance.

**Comment by daupawar** [comment]
add blank object with break so you can see blank page 

var dd = {
	content: [
				{ text: '', style: 'header' , pageBreak:'before'}
                   ]
             };

**Comment by liborm85** [comment]
Answered.
