### ISSUE TITLE
Can't Insert Image

### ISSUE THREAD

**Issue by DevQueen** [bpampuch/pdfmake#455]
I receive the error Cannot get property 'embed' of undefined or null reference.  I changed it to base64.  See code below:'

```
            var blob = new Blob([document.getElementById('exportable').innerHTML]);
            var reader = new window.FileReader();
            reader.readAsDataURL(blob);
            var base64data = reader.result;

            var docDefinition = {
                content: [{

                    image: base64data,
                    width: 500
                }]
            };
            pdfMake.createPdf(docDefinition).download();
```

After execution the contents of base64data are:

data:;base64,CiAgICAgICAgICAgICAKICAgICAgICAgICAgICAgICAgICA8dGFibGUgaWQ9Im15VGFibGUiIHN0eWxlPSJ3aWR0aDogMTAwJTsiPgogICAgICAgICAgICAgICAgICAgICAgICA8dGhlYWQ...etc.

I feel like I'm missing something small here.  PLEASE help!

**Comment by DevQueen** [comment]
I thought maybe the problem was the data:;base64 so I did this:

var blob = new Blob([document.getElementById('exportable').innerHTML]);
                var reader = new window.FileReader();
                reader.readAsDataURL(blob);
                var base64data = reader.result;
                base64data = base64data.replace('data:;base64,', 'data:image/jpeg;base64,/9j/')
                var docDefinition = {
                    content: [{
                        
                        image: base64data,
                        width: 500
                    }]
                };
                pdfMake.createPdf(docDefinition).download();

**Comment by DevQueen** [comment]
I thought that maybe the problem was the data:;base64 so I changed it to this:

              var blob = new Blob([document.getElementById('exportable').innerHTML]);
                var reader = new window.FileReader();
                reader.readAsDataURL(blob);
                var base64data = reader.result;
                base64data = base64data.replace('data:;base64,', 'data:image/jpeg;base64,/9j/')
                var docDefinition = {
                    content: [{
                        
                        image: base64data,
                        width: 500
                    }]
                };
                pdfMake.createPdf(docDefinition).download();

Now I get the error "invalid JPEG".

**Comment by liborm85** [comment]
base64 image works, see http://pdfmake.org/playground.html
