### ISSUE TITLE
Pipelining ?

### ISSUE THREAD

**Issue by odungern** [bpampuch/pdfmake#456]
Dear pdfmake-team,
first of all we would like to express our great appreciation for your work.  Our team has taken a close look to your interface design and considers it very useful and easy-to-use. The hierarchical document structure is just neat _(still in the active vocabulary of the younger generations ?)_ or awesome _(also getting outdated by now)_ - it makes it easy to transform JSON/XML/XHTML and other structures to yours.
However we would like to let you know the results of our investigations and why we had to decide to look for other approaches to generate pdf-documents. Probably, we must do it on server-side using XSL-FO, DocBook or something similar.
### 1. memory:

A small to medium sized project has about 400 data elements (paragraphs) and a data volume of about 100kB; no images, yet. The result has 34 pages. (In our case, usual projects would have about ten times the volume).  The stated volume was eventually processed, but the browser froze for quite a while and some Firefox-monitor asked us whether he should stop the script.
Perhaps the memory usage can be reduced by adopting a streaming or pipeline processing. Rather than compiling the whole data structure before handing it over to pdfmake, this would allow to feed it in chunks (anyways we push to the content list while walking through our data structure, so we could 'push' the chunks to pdfmake, directly.) Whenever pdfmake has enough to fill a page, it generates it, adds it to the output pile and clears up the memory internally.
### 2. stability:

While your playground runs perfecty stable with data we paste into it from the clipboard (windows with Firefox or Chrome), we had some problems when integrating your libraries with our app.  It is ok, as long we use a separate html and again paste the data manually into the code.  If we feed the pdfmake library directly from our app, we had to suppress all but alphanumeric charaters [^a-zA-Z0-9], otherwise pdfmake would silently die in the background. We assume this is some codepage issue - we are using utf-8 throughout - at least we think we do ;-). Perhaps there is some under-the-cover transformation when using the clipboard, because the 'same' data is perfectly processed in your playground. We haven't further investigated the issue, as the memory issue described above is already prohibitive for our case.

If you have some idea how to use pdfmake more cleverly than we did, we would love to give it another try. Or perhaps we have overlooked something basic .... anyways we have learned a lot from your approach ...

**Comment by liborm85** [comment]
Performance is optimized in version 0.1.29, and memory usage is optimized in version 0.1.50.
Pipelining is available because document is Node readable stream (on browser use `getStream()`).
UTF-8 characters are supported.
