### ISSUE TITLE
How to display pdf object in canvas container? 

### ISSUE THREAD

**Issue by hok89** [bpampuch/pdfmake#461]
Hi All,

I have to put pdfmake object: 

[ var doc = pdfMake.createPdf(docDefinition) ]

into a canvas object. Basically, I want to display pdf preview before I will print it. 
I have tried to use drawImage method from Canvas API but I get message that input stream is invalid.

Is Pdfmake support such operation or do you know suitable alternative?

Thanks

**Comment by daupawar** [comment]
Try this

in html
<iframe id='pdfV' style="width:100%; height: 500px" ></iframe>

in js
pdfMake.createPdf(docDefinition).getDataUrl(function (outDoc) {
            document.getElementById('pdfV').src = outDoc;
        });

**Comment by hok89** [comment]
Hi Daupawar

Thank you. It is working brilliantly.

**Comment by Queen-esther01** [comment]
> Try this
> 
> in html < iframe id='pdfV' style="width:100%; height: 500px" > </ iframe>
> 
> in js pdfMake.createPdf(docDefinition).getDataUrl(function (outDoc) { document.getElementById('pdfV').src = outDoc; });

Please what does your docDefinitions look like?
