### ISSUE TITLE
Chinese can not  line wrap

### ISSUE THREAD

**Issue by yiniesta** [bpampuch/pdfmake#462]
In my project, I need to print Chinese,and I found that Chinese can not automatically line wrap.
![screenshot](https://cloud.githubusercontent.com/assets/6304413/11800886/9c11f534-a31b-11e5-93dd-4cbd53a90edd.jpg)

Can you tell me how can I fixed this problem, or tell me which code I need to change?
Thanks a lot.

**Comment by lizepeng** [comment]
It seems like the default [Lexer](https://github.com/bpampuch/pdfmake/blob/master/src/textTools.js#L4) in only for English, so it treats continuous Chinese characters like one word. A simple work around could be just insert a space between every two Chinese characters, or you may have to change the Lexer on your own.

**Comment by hks2002** [comment]
you should change the WORD_RE regurlar
var WORD_RE = /\(?[\u4e00-\u9fa5]\)?|[\d]+|([^ ,\/!.?:;\-\n，。：]*|[^\u4e00-\u9fa5])[ ,\/!.?:;)\-，。：]?|\n/g;
I tested it today.

**Comment by hks2002** [comment]
it is in the textTools.js file, but you can also change the makdpdf.js derectly.

**Comment by hks2002** [comment]
do you know how to use bold if the chinese font file is only one file? such as simfang.ttf.

**Comment by yiniesta** [comment]
@hks2002 you should find bold ttf file and generate vfs_fons.js by yourself
https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
![Uploading ttf.png…]()

**Comment by devongovett** [comment]
pdfmake should use https://github.com/devongovett/linebreak for linebreaking, as PDFKit does. It implements the unicode line breaking algorithm, and supports chinese and many other languages correctly.

**Comment by yiniesta** [comment]
@devongovett thanks for your help.But I am sorry that I can't really understand what I need to do,can you give me some steps or example?

**Comment by waynelouflz** [comment]
Hi 

I made a vfs_font.js file from simsun.ttf. But I still can't display Chinese character in my pdf. Would you suggest what is the problem? Do I miss somthing?

**Comment by yiniesta** [comment]
@waynelouflz  We have encountered situations like yours before, and I do not know the specific reasons.Now the size of vfs_font.js file what I used is more than 12M.

**Comment by waynelouflz** [comment]
@yiniesta My vfs_font.js is 14M. I not sure if my ttf file is correct. The problem is bothering me for a week now. Would you share your ttf file or vfs_font.js file? My email address is weiwei.lou@outlook.com. Thank you very much!

**Comment by hks2002** [comment]
@waynelouflz, I have the same issue with you, you can try another font, such as simfang.ttf or aril(unicode).ttf. then you can see the chinese character.

**Comment by liborm85** [comment]
By commit https://github.com/bpampuch/pdfmake/commit/d661618cf1afc89c0ddfb8a5cf7c6eedf8a7f07f implemented new split words algorithm -  Unicode Line Breaking Algorithm (UAX #14). This supports also Chinese characters.
