### ISSUE TITLE
Trouble getting the watermark to work

### ISSUE THREAD

**Issue by hillelcoren** [bpampuch/pdfmake#466]
When trying to add the watermark property, for example:

```
var dd = {
    content: [
        'First paragraph',
    ],
    watermark: 'test'
}
```

I get the following error:

```
Uncaught Error: Font 'undefined' in style 'normal' is not defined in the font section of the document definition.
```

This is both in my dev environment and when trying it in the playground.

**Comment by liborm85** [comment]
Fixed by https://github.com/bpampuch/pdfmake/pull/492
