### ISSUE TITLE
No unicode cmap for font

### ISSUE THREAD

**Issue by hks2002** [bpampuch/pdfmake#467]
how to fix this issue? these error comes out with some font.

**Comment by askie** [comment]
+1

**Comment by askie** [comment]
![image](https://cloud.githubusercontent.com/assets/1140973/15545482/0764a7c2-22cf-11e6-8b9a-3a5bf7b19006.png)

**Comment by liborm85** [comment]
Can you try latest version?

**Comment by liborm85** [comment]
No reaction. No specific information.
