### ISSUE TITLE
tableOfContent

### ISSUE THREAD

**Issue by Fadilah** [bpampuch/pdfmake#469]
Greetings, 

I'm trying to add page of content in my generated pdf file, Is there any way to do that. I need to know the page number for each page in addition to the header title.

**Comment by Fadilah** [comment]
i'm using pdfMake library to generate the pdf file.

**Comment by jorgebo10** [comment]
Hi , i need to do the same . Did you find any way to do it ?

**Comment by liborm85** [comment]
Duplicate https://github.com/bpampuch/pdfmake/issues/126
