### ISSUE TITLE
Table -> Header with colspan and rowspan not rendered well on new pages, and pagebreak also an issue

### ISSUE THREAD

**Issue by balilaszlo** [bpampuch/pdfmake#470]
Hi, i just started using pdfmake, and think, that is the tool i need for my work.

I got JSON from server for generating table on client side -> works very good, fix header rows are generated OK.
But if the header has colspan, and rowwspan, than the automatically generated header on the next pages are rendered on bad way, the colspans and rowspans ignored.
In the first page everything is ok, but for the next pages no colspans and rowspans are aplied.

And if the first row of the "permanent header" has colspan , than the pageBreak does not work well, some cells are left in previous/next page depending the location of the pageBreak inside the table row.

Thnx in advance.

**Comment by mgrivera** [comment]
Hi, I'm also experiencing this issue. Table header in first page looks perfect. On 2nd. page, colspans are not respected. Haven't tried page breaks. 

Many thanks for this fantastic library. I use it a lot and can easily recommend to anyone ...

**Comment by Rodrigojorge** [comment]
Hi, I'm also experiencing this issue. My 2ns pages header looks like this (colspans are not respected):

![image](https://cloud.githubusercontent.com/assets/2468366/12954993/2cfd512e-d008-11e5-829b-4cd25af61790.png)

**Comment by jorgebo10** [comment]
Hi, i'm experiencing this issue too

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/247
