### ISSUE TITLE
Location error

### ISSUE THREAD

**Issue by balilaszlo** [bpampuch/pdfmake#471]
Hi

A get back the data from the server as JSON.
A try to: 
pdfMake.createPdf(data).open();
and got an error ( firefox ):
"
TypeError: e is null
...lank");try{this.getDataUrl(function(t){e.location.href=t})}catch(n){throw e.clos...
"
If i try on local maschine ( localhost ), than no problem occurs.

BR: L. Bali.

**Comment by yohanology** [comment]
same here! on Local no problem, and in production I got this error or `UncaughtTypeError: Cannot set property 'href' of undefined`

**Comment by liborm85** [comment]
Can you try it in lastest version (0.1.22)?

**Comment by hugoblanc** [comment]
Same in client side 
![image](https://cloud.githubusercontent.com/assets/15015179/21803846/441d12c8-d72c-11e6-9fb6-a30710da09c6.png)

**Comment by hugoblanc** [comment]
In addition when I execute de methode which return null in "win", A popup ask me to choose which programme use to open the page "about"

![image](https://cloud.githubusercontent.com/assets/15015179/21807293/4c007996-d73e-11e6-9d2c-e693ec8da22e.png)

**Comment by liborm85** [comment]
Added check for windows blocked - https://github.com/bpampuch/pdfmake/commit/4452de84c7a4684970b11c9b389607ee455f5a23
