### ISSUE TITLE
Dynamically built rows in a table using dontBreakRows doesn't work as I expect

### ISSUE THREAD

**Issue by adamkjones** [bpampuch/pdfmake#473]
Hello,

I have attached a screen shot.  Notice the Bond Fund section.  I am building rows dynamically in a loop.  The Bond Fund section first row is a max colspan fillcolor row that says Bond Fund.  The next two rows are data for that bond fund category.  Notice the data rows are broken across two pages.  I need those to stay together.  I don't care which page they are on just can't break across pages like that.  I thought using dontBreakRows on the table (which I am using) would solve this however it has not.  Can someone assist?  I can post whatever code is necessary.

Thanks.
![table_screenshot](https://cloud.githubusercontent.com/assets/5125199/12024375/65295b56-ad71-11e5-82f4-fec797df0553.png)

**Comment by adamkjones** [comment]
Hey nevermind I fixed this using headerRows and keepWithHeaderRows properties.  Thanks.

**Comment by jamesriady** [comment]
@liborm85 do you only use headerRows and keepWithHeaderRows?
