### ISSUE TITLE
Chinese Fonts don't display, custom vfs_fonts.js has added new font

### ISSUE THREAD

**Issue by waynelouflz** [bpampuch/pdfmake#474]
Hi all,

I am working with printing form,  and I have read through this forum about fonts issues. There are others successfully displaying Chinese character. I do have added my font TTF file to vfs_fonts.js as the the guide. The code is as following:

```
        defaultStyle: {
            font: 'SimSun'
          }
    // open the PDF in a new window
    window.pdfMake.fonts = {
       SimSun: {
         normal: 'simsun.ttf'
        //  bold: 'simsun.ttf',
        //  italics: 'simsun.ttf',
        //  bolditalics: 'simsun.ttf'
       }
```

What do I miss? Looking forward to have your posts here. Thank you!

**Comment by LeoLPF** [comment]
The font file SimSun.ttf may not support Chinese,"Microsoft YaHei" will be a better choice.

**Comment by waynelouflz** [comment]
Thank you!

My problem is solved, One of the guru sent me a simfang.ttf file, and works fine!

**Comment by bbj** [comment]
I confirm that "Microsoft YaHei" is working very well, especially when mixing English and Chinese. I have tried a lot of font, and this is the only one which really work for me.

**Comment by liborm85** [comment]
Answered.
