### ISSUE TITLE
LineWidth doesnt work when setting line color into other color.

### ISSUE THREAD

**Issue by venhels** [bpampuch/pdfmake#477]
Hello Sir, How can I properly set line color using color property.

I copied the code from https://github.com/bpampuch/pdfmake/issues/2 but when I tried adding `color` property to the canvas the `lineWidth` is set to default which is .5 I think.

my code was 

<pre>
var dd = {
    content: [{canvas: [
            {
                type: 'line',
                color:'red',
                x1: 0,
                y1: -10,
                x2: 520,
                y2: -10,
                lineWidth:3,
            }
        ]}
        ]
    
}
</pre>

if you remove the `color:'red'`, `lineWidt:3` doesnt work.

**Comment by liborm85** [comment]
Hello. If you use a `lineColor` it works.

```javascript
var dd = {
    content: [
        {
            canvas: [
                {
                    type: 'line',
                    lineColor: 'red',
                    x1: 0,
                    y1: -10,
                    x2: 520,
                    y2: -10,
                    lineWidth: 5,
                }
            ]
        }
    ]
}
```

**Comment by martinschilliger** [comment]
Oh, cool, thank you very much!
