### ISSUE TITLE
Different footer heights per page

### ISSUE THREAD

**Issue by lifeisfoo** [bpampuch/pdfmake#479]
I've a document with different headers and footers for every page, generally the first header and the last  footer are bigger that the others. 

I've used a function for the `header` and the `footer` properties in order to have different content per page, but seems that their height is statically defined in the object `pageMargins`.

Is it possible to create a pdf with _fluid_ header and footer height using pdfmake?

**Comment by lifeisfoo** [comment]
Looking at the [source code](https://github.com/bpampuch/pdfmake/blob/af47c2757d6775c61dea48a9c0923e52231408e3/src/layoutBuilder.js#L175) seems that with a small tweak, this could be possible:

Change the LayoutBuilder.prototype.**addDynamicRepeatable** function in this way:
```
if (node) {
     var currentMargins = this.pageMargins.slice();
     if (node.height) {
          currentMargins[3] = node.height;       
     }
      var sizes = sizeFunction(this.writer.context().getCurrentPage().pageSize, currentMargins);
      //...
    }
```

Then, create the document object:

```
var myDoc = {
    footer: footer: function(currentPage, pageCount) {
        if(currentPage == pageCount) {
            return {
                text: "Last page\nWith nice ending text :)",
                alignment: 'center',
                height: 100
            }
      } else {
        return currentPage.toString() + ' of ' + pageCount; 
      }
    },
//...
}
```

Am I right?

**Comment by dcrystalj** [comment]
Try to make pull request?

**Comment by max-yu** [comment]
seems this change is not enough.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/368
