### ISSUE TITLE
Define page-unity of elements

### ISSUE THREAD

**Issue by Urr4** [bpampuch/pdfmake#480]
I'm trying to have a document which contains (amongst other stuff) a table with a headline over it.
The headline and the table should belong together, so it should never happen, that the headline ist the last thing on one page and the table is the first thing on the next page.
In this case the headline should be put on the next page too.

Is this possible?
If so how?

Thank you.
Regards
Urr4

**Comment by athavanraja** [comment]
you can do it with headerrows
in your case you could have 2 header rows and the first row with colspan can be used for headline.
check the table sample at http://pdfmake.org/playground.html

**Comment by liborm85** [comment]
Answered.
