### ISSUE TITLE
The error throwed meaningless

### ISSUE THREAD

**Issue by gentlecolder** [bpampuch/pdfmake#483]
Cannot read property '_span' of undefined in file  pdfmake.js 114

```
try {
        this.getDataUrl(function(result) {
            win.location.href = result;
        });
    } catch(e) {
        win.close();
        throw e;
    }
};
```

and i want to know how to denfine the pagesize through length and width not the predefined Item. Thanks in advance.

**Comment by jbjorge** [comment]
To know more about the error you're getting, try to reproduce it with as small document definition as you can make and post it here.
Regarding pagesize, the predefined items actually translate to a width/height within the library. This means that you can define the width/height yourself if you want.
```javascript
var dd = {
    pageSize: {width: 500, height: 400},
    content: ['hello there']
}
```

**Comment by philippjbauer** [comment]
I ran into the same error and for me it was an undefined object attribute within a table.body definition.

Maybe it'll help someone running into the same problem...

**Comment by Nayigiziki** [comment]
I am running into this same error, and I have confirmed that all of the values in table.body are defined...Has anyone else resolved this issue?

**Comment by liborm85** [comment]
Without docDefinition is nothing to solve.
