### ISSUE TITLE
Could not open pdf after sending it to the browser

### ISSUE THREAD

**Issue by jorgebo10** [bpampuch/pdfmake#484]
Hi guys, 

I have a pdf generated with the following code, however the generated pdf file does not open.
Am i missing something?

Thanks,
Jorge
var fs = require('fs');
var PdfPrinter = require('pdfmake');

// Get a single informe
exports.reporte = function (req, res) {
    function createPdfBinary(pdfDoc, callback) {

```
    var printer = new PdfPrinter();

    var doc = printer.createPdfKitDocument(pdfDoc);

    var chunks = [];
    var result;

    doc.on('data', function (chunk) {
        chunks.push(chunk);
    });

    doc.on('end', function () {
        result = Buffer.concat(chunks);
        callback('data:application/pdf;base64,' + result.toString('base64'));
    });
    doc.end();
}

var dd = {
    content: [
        'test paragraph'
    ]
};

createPdfBinary(dd, function (binary) {
    res.contentType('application/pdf');
    res.send(binary);
}, function (error) {
    res.send(500, error);
});
```

};

**Comment by gabboman** [comment]
This is how I make it:
html:
```
<div>
<iframe  id="preview" type="application/pdf"></iframe>
</div>
```
javascript:
```
var dd=.....
pdfMake.createPdf( dd ).getDataUrl(function( result ) {
  //var pdfBase64 = JSON.stringify( result.split( ',' ).splice( 1, 1 ) );
  preview.src=result;
});
```

I hope this could help you

**Comment by svlungade** [comment]
please check if the PDF is getting generated on server properly, if yes, that means your browser is trying to fetch the PDF even before it is generated.
1. Use async.series function to generated pdf in first function and sending to browser in second function
2. Add  a settimeout of around 3 seconds in the first function callback, so that client gets the file only after it is completely generated.

**Comment by gabboman** [comment]
Please, note that my code is for client side PDF generation. I've updated my comment to reflect it

**Comment by svlungade** [comment]
ohh sorry then, I am using the server side version of it. Someone else may help you I guess.
