### ISSUE TITLE
send the pdf to client without downloading

### ISSUE THREAD

**Issue by svlungade** [bpampuch/pdfmake#489]
I am creating the PDF file and then sending it to browser, how can i send it directly to browser without saving it on server.
Please note i am using the server side implementation of node.js

app.get('/', function(req, res) {

```
var pdfDoc = printer.createPdfKitDocument(docDefinition);
pdfDoc.pipe(fs.createWriteStream('pdfs/new8.pdf'));
pdfDoc.end();

var file = 'pdfs/new8.pdf';
var filename = path.basename(file);
var mimetype = mime.lookup(file);
res.setHeader('Content-disposition', 'attachment; filename=' + filename);
res.setHeader('Content-type', mimetype);

var filestream = fs.createReadStream(file);
filestream.pipe(res);   
```

});
app.listen(3000);

**Comment by jybleau** [comment]
Almost one year, here's a start:

Using express with a GET path:

```
   //...

    var printer = new pdfMakePrinter(fontDescriptors)
    var doc = printer.createPdfKitDocument(definition)

    var chunks = []
    var result

    doc.on('data', function (chunk) {
      chunks.push(chunk)
    });
    doc.on('end', function () {
      result = Buffer.concat(chunks)

      response.contentType('application/pdf')
      response.send(result)
    });
    doc.end()
   //...
```

NB: If your request is AJAX, make sure the `responseType` (on the client side) is an `arraybuffer`. 

Explanation here:
* [https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data](https://developer.mozilla.org/en-US/docs/Web/API/XMLHttpRequest/Sending_and_Receiving_Binary_Data)

Example using Angular, jquery like: 
* [http://stackoverflow.com/questions/21628378/angularjs-display-blob-pdf-in-an-angular-app](http://stackoverflow.com/questions/21628378/angularjs-display-blob-pdf-in-an-angular-app)

**Comment by liborm85** [comment]
Answered.

**Comment by angelzarazua** [comment]
You really saved me, super thanks

**Comment by angelzarazua** [comment]
Thanks, you really saved me!

**Comment by receding-gravity-forms-p** [comment]
> You really saved me, super thanks





https://cavan3.github.io/arbitrary/
