### ISSUE TITLE
Image displays in Base64 but not in browser.

### ISSUE THREAD

**Issue by davefeucht** [bpampuch/pdfmake#490]
I'm having an issue with an image in a document definition where I'm creating a Base64 string using getBase64, and saving it to a database in a blob, and the image appears correctly in the PDF that gets saved to the database, but then immediately after doing this, I also open the PDF in the web browser using the open() function, and the image is not appearing in the PDF that is opened in the web browser. 

They are using the exact same document definition, which is stored in a variable. The image in question is actually a choice between two images that is conditionally displayed based on a ternary operator (if blah ? image1 : image2) that is wrapping the {image:} object in the document definition like so (this is in an Angular app):

$scope.name == 'Some Name' ? {image: $scope.image1, width: 150, style: 'sigImage'} : {image: $scope.image2, width: 150, style: 'sigImage'}

So, in any case, it should display one of the images - but no image is displayed in the browser, only in the Base64-encoded version that is saved to the database.

Any thoughts as to what might cause this?

**Comment by liborm85** [comment]
Please add some simple example works on http://pdfmake.org/playground.html.

**Comment by moffsugita** [comment]
there aren't image sample
