### ISSUE TITLE
Document to PDF conversion

### ISSUE THREAD

**Issue by natcohen** [bpampuch/pdfmake#50]
First of all, thank you for this great tool!

It's not an issue but a request (I don't know where to put it so sorry if it's not the right place).
It would be amazing to have an odt or docx to PDF conversion! Do you think it's possible and realistic in the 'not too' long term?

**Comment by softboy99** [comment]
Hi,
cannot create PR, please check

**Comment by saiprasad9467** [comment]
Hey is this done
