### ISSUE TITLE
QRCode generated is mirror image and rotated 90 degrees

### ISSUE THREAD

**Issue by svlungade** [bpampuch/pdfmake#500]
I am using the qr method to generate QRCode in the PDF, but the QR code generated is mirror image of the actual QR code and is 90 degree rotated, hence QR code when scanned is not working. any remedy to this?

**Comment by zbysekmartoch** [comment]
Hi, I think that somewere in the code is swaped X and Y coordinates. So I stepped docMeasure.js and in the function DocMeasure.prototype.measureQr I made this hot fix. It's on line 492.

```
DocMeasure.prototype.measureQr = function(node) {
	node = qrEncoder.measure(node);
	node._alignment = this.styleStack.getProperty('alignment');

	// begin of mirrored and rotated bug fix - just swap X and Y of all elements
	var p;
	for (var i=0;i<node._canvas.length;i++) {
		p=node._canvas[i].x;
		node._canvas[i].x=node._canvas[i].y;
		node._canvas[i].y=p;
	}
	// end of fix

	return node;
};
```

**Comment by bswiswa** [comment]
I had this problem too and @zbysekmartoch's solution works. Thanks!

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/fdf8be15d8e6f3a2546a18199a30b39a169cef31
