### ISSUE TITLE
pdf filename on open

### ISSUE THREAD

**Issue by Gsuz** [bpampuch/pdfmake#501]
is it possible to give a custom default name to the pdf while the user opens the document in a new tab with the
pdfMake.createPdf(doc).open() method and then uses the save as option?

**Comment by Adhara3** [comment]
You can give a title in the infos, but that will not be used when saving.

**Comment by nrjmr432** [comment]
I am able to give title in case of download(), but the same is not working for open()

**Comment by liborm85** [comment]
Name can be defined only by using metadata `title` property (see [Document metadata](https://github.com/bpampuch/pdfmake#document-metadata)).
