### ISSUE TITLE
Fixed Table Row Height

### ISSUE THREAD

**Issue by ryanlin1986** [bpampuch/pdfmake#505]
Is it possible to fix a table row height?  If not, are you going to support this? If so, is it possible to set vertical-alignment?

I'm trying to export pdf from my report engine, which has a report designer that use can set fixed row height, it's very important to have row size fixed and vertical-align supported as well.

**Comment by spazhead** [comment]
Im also looking for this feature!

**Comment by burggraf** [comment]
@strokovnjaka can you post an example of how to create a table with fixed-height rows?  I can't seem to get it to work.

**Comment by strokovnjaka** [comment]
@burggraf find it here https://github.com/strokovnjaka/pdfmake2/commit/98b13a6a18dbba1e42476573f4bd7e3c0757e279#commitcomment-17696054

**Comment by rcouto** [comment]
+1

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/391

**Comment by Tonio31** [comment]
I'm sorry, I must misunderstand something but is this available, I can't see it on the main branch ?
