### ISSUE TITLE
Table Cell Border

### ISSUE THREAD

**Issue by ryanlin1986** [bpampuch/pdfmake#506]
Is it possible to customize cell border instead of entire row or entire column border?

**Comment by liborm85** [comment]
Maybe, it depends what you want. Simple border support is here http://pdfmake.org/playground.html (section Table, down on page).
If you need more customizable, now is not supported (but PR for this is available  #493 ...).

**Comment by liborm85** [comment]
PR https://github.com/bpampuch/pdfmake/pull/493 merged.

**Comment by mstruensee** [comment]
This only works for the entire table?  The documents show it can work for each cell but I cannot seem to get it working ... using v0.1.31.
