### ISSUE TITLE
Is there any option to fill the table in entire page ?  

### ISSUE THREAD

**Issue by athimannil** [bpampuch/pdfmake#509]
Demo: [https://jsfiddle.net/t2dbcb4t/](url)

![screen shot 2016-02-07 at 6 17 25 pm](https://cloud.githubusercontent.com/assets/4364227/12872872/6630b00e-cdc8-11e5-97f7-f0814e871255.png)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/561
