### ISSUE TITLE
Image within SVG - doesn't load the first time

### ISSUE THREAD

**Issue by taylorchance** [bpampuch/pdfmake#510]
Has anyone else ran into this issue? I am currently working with pdfMake and a series of d3 graphs. They are all working fine except one doesn't load at all on the first try, only works after creating the pdf twice. I have narrowed down the problem to this one graph having an images included within it.

**Comment by magbeat** [comment]
@taylorchance did you solve your problem? How did you include the d3 graphs into a pdfmake document? I am trying to convert the graphs from svg to canvas and then use the image property on the pdfmake document. Is this the right direction?

**Comment by taylorchance** [comment]
@magbeat yes you are absolutely on the right path. I did solve my problem, the issue was that since that one graph had images as well as svg's, it was taking longer to convert. The pdfmake was initializing before everything had been converted to canvas. This was months ago and I don't have access to the code anymore, but I used a promise type of function, to make sure the first conversion was finished before moving to the next step. Good luck!

**Comment by magbeat** [comment]
@taylorchance thanks a lot for your quick feedback! Really appreciate it. I'll have another try then.

**Comment by liborm85** [comment]
duplicate: #121

**Comment by ajayep** [comment]
@taylorchance @magbeat - Can you tell me how to convert  svg to canvas ?
