### ISSUE TITLE
Can't open() dataurls longer than smallint in Chrome

### ISSUE THREAD

**Issue by formido** [bpampuch/pdfmake#513]
My users can't open my application's PDF reports in Chrome if they have more than 300-400 rows. Since each row is around 200 bytes, it appears that dataurls longer than an unsigned smallint integer representation result in a blank tab.

They all have recent versions of Chrome, e.g., 47.0.2526.111 m.

**Comment by liborm85** [comment]
@formido You can insert some sample of definitions?

**Comment by Chris--A** [comment]
In Chrome it has a max dataURL string of 2MB, anything longer and it'll just open a blank tab.
