### ISSUE TITLE
a, b, c as numeration for ordered lists

### ISSUE THREAD

**Issue by MangaRed** [bpampuch/pdfmake#515]
Can it be an option to choose the type of enumeration for ordered lists?
I could include the letter in the paragraph but the next line won't be correctly aligned. i.e.:

a)   paragraph 1....
more lines
b)   paragraph 2....
c)   paragraph 3....

Or is there a way to emulate the next line alignment? maybe a negative first line indent?

**Comment by liborm85** [comment]
Implemented, see https://github.com/bpampuch/pdfmake/issues/559#issuecomment-277520036.
