### ISSUE TITLE
Arabic characters in reverse and detached

### ISSUE THREAD

**Issue by IbrahimAmin** [bpampuch/pdfmake#517]
Hi first of all your tool is just awesome it helped me a lot, One problem i faced was not being able to show Arabic characters  but that was fixed using a font that support Arabic now my problem is that characters are actually showing in reverse and they should be joined instead they are detached.

like: وتسيرك تنوم يد تنوكلا should be الكونت دي مونت كريستو

I attached the generated file i hope you are able to help me on this, I really need this :100: 
[document (36).pdf](https://github.com/bpampuch/pdfmake/files/133019/document.36.pdf)

**Comment by asonni** [comment]
Hello @IbrahimAmin  How are you?
you hint about the font supported Arabic characters what's the name or type of the font was used !

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/315

**Comment by saurabhgis** [comment]
@IbrahimAmin **As I checked you are also faced problem in that arabic characters are actually showing in reverse. Pls suggest me how you we can resolve this issue.**
