### ISSUE TITLE
pdfmake - minWidth undefined for colspan 4

### ISSUE THREAD

**Issue by kumar612** [bpampuch/pdfmake#527]
i am new to pdfMake ... so i have this doubt ? i want to have a table like this.
untitled
![untitled](https://cloud.githubusercontent.com/assets/17428279/13252485/01a12a46-da5d-11e5-8ae4-d6093ff69c2f.png)

but when i use colspan=4 .. it gives me an error saying "Cannot read property '_minWidth' of undefined".

code:

body: [
          [{ text: '', style: 'tableHeader', colSpan: 4, alignment: 'center' },{},{},{},{ text: 'Accepted', style: 'tableHeader', colSpan: 2, alignment: 'center' }, {},{ text: 'Rejected', style: 'tableHeader', colSpan: 5, alignment: 'center' },{},{},{},{},{ text: 'total', style: 'tableHeader', alignment: 'center' }],

```
              [{ text: 'Authenticator', style: 'tableHeader', alignment: 'center' },{ text: 'Name', style: 'tableHeader', alignment: 'center' },{ text: 'Types', style: 'tableHeader', alignment: 'center' },{ text: 'Container', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text: '%', style: 'tableHeader', alignment: 'center' }, { text: 'ProcError', style: 'tableHeader', alignment: 'center' }, { text: 'AuthError', style: 'tableHeader', alignment: 'center' },{ text: 'lookupError', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text: 
```

alignment: 'center' }, { text: 'AuthError', style: 'tableHeader', alignment: 'center' },{ text: 'lookupError', style: 'tableHeader', alignment: 'center' },{ text: '#', style: 'tableHeader', alignment: 'center' },{ text:'%', style: 'tableHeader', alignment: 'center' }, { text: 'total', style: 'tableHeader', alignment: 'center' }],

```
     [ 'Sample value 1', 'Sample value 2', 'Sample value 3','Sample value 4', 'Sample value 5', 'Sample value 3','Sample value 6', 'Sample value 7', 'Sample value 8','Sample value 9', 'Sample value 10', 'Sample value 11','Sample value 12'],        
```

]

thanks in advance.

**Comment by liborm85** [comment]
Must be defined all cells of table.
