### ISSUE TITLE
How can I create grid in pdf make ?

### ISSUE THREAD

**Issue by sagarwasule** [bpampuch/pdfmake#534]
I want to create grid in pdf using pdf make.
Should I use table in order to implement the same ? or is there any other option available ?
Also if I use table, can it support json object ? Currently referring to the demo available I can see the table expects array of data, but I want to assign a json array to it for example,

[    {"firstName":"John", "lastName":"Doe"}, 
    {"firstName":"Anna",    "lastName":"Smith"},
    {"firstName":"Peter", "lastName":"Jones"}]

Could you provide any pointers regarding the same ?

**Comment by liborm85** [comment]
data for table you can create with any object/json, create converter.
