### ISSUE TITLE
PDFMake slow with images

### ISSUE THREAD

**Issue by HMubaireek** [bpampuch/pdfmake#538]
I'm trying to create a single page report that consists of some images. The performance I'm getting is not good. Here is a sample of one images only:

http://codepen.io/HMubaireek/pen/zqoZoG

Can't add more than one image as the size is restricted to 1Mb at codepen but [here is the doc var with two images. ](https://www.dropbox.com/s/evvzze0hllm7tgd/doc.js?dl=0)
Any help would be appreciated.

**Comment by HMubaireek** [comment]
Was using too high res image, reducing the quality a bit solves it for now..

**Comment by liborm85** [comment]
Version 0.1.23 solved problems with performance.
