### ISSUE TITLE
Q: Align to bottom?

### ISSUE THREAD

**Issue by ZepAviator** [bpampuch/pdfmake#540]
I'm sorry to leave a question as an issue. 

Can anyone point me to the docs on how to align text in a column to the bottom of the column? I'd love to specify an x, y, width, height and then align to the bottom of that box.

Thanks!

**Comment by fguillen** [comment]
👍

**Comment by fguillen** [comment]
I think duplicated: https://github.com/bpampuch/pdfmake/issues/74
