### ISSUE TITLE
Uncaught Error: No unicode cmap for font

### ISSUE THREAD

**Issue by wmalevski** [bpampuch/pdfmake#542]
Hello,

I have tried with few fonts, 

one from this demo:
http://www.rudeprogrammer.com/2016/01/changing-your-datatablepdfmake-font-in-pdf-print-button-for-right-to-left/

one directly from here:
https://www.google.com/fonts/earlyaccess (Open Sans Hebrew)

But still I got the following error.

How I can validate that a font is supporting unicode CMap?
Can someone give me an example of font who is supporting hebrew characters, because currently I'm having the issue that or I can't see the hebrew characters or I got the following error.

I'm trying to mix this all with DataTables Buttons.

Thanks in advance!

**Comment by liborm85** [comment]
Can you try it with new version pdfmake (0.1.24) ?

**Comment by wmalevski** [comment]
9 months later? Seriously? I have forgotten about this project already..

**Comment by Wabbala** [comment]
@wmalevski Wow somehow your comment seems to be pretty rude. Hopefully you have found something that works for you!

**Comment by wmalevski** [comment]
@Wabbala I didn't want to sound rude, sorry about this. But it's logical to go forward after 9 months if you are stuck on such a major issue. I have generated the PDF in PHP based backend, thanks for the answer anyway.
