### ISSUE TITLE
UTF-8 support ?

### ISSUE THREAD

**Issue by LeoAbu-Saa** [bpampuch/pdfmake#543]
Hi, I'm trying to generate a pdf using Swedish/Finnish language but the special chars are not displayed

This is the code:

``` javascript
<script>
$(document).ready(function () {
var text = "Med avtalet säkerställer man att skogsägaren får den överenskomna servicen..."
            var docDefinition = {
                content: text,
                //font: 'Verdana'
            };
            $("#generatePdf").click(function () {           
                pdfMake.createPdf(docDefinition).open();
            });            
        });        
</script>
```

This is the result: 
"Med avtalet s�kerst�ller man att skogs�garen f�r den �verenskomna servicen.."
Have any of you had this issue? 
Thanks,
Leo

**Comment by liborm85** [comment]
In http://pdfmake.org/playground.html I tried this:

```javascript
var dd = {
    content: "Med avtalet säkerställer man att skogsägaren får den överenskomna servicen..."
}
```

And UTF-8 is ok.

Script file is in UTF-8?
Used font (Verdana?) supported this characters? Try the default font.

**Comment by LeoAbu-Saa** [comment]
Hi guys what I'm doing wrong here ?

I've configured the pdf to use Verdana (which btw supports utf-8 chars) but the result is incorrect.
I have exported the vsf_fonts.js file without any errors and during debug all Verdana fonts (bold, italic, etc) are in the vsf object.

```javascript

var text = "säkerställer";
var docDefinition = {
  content: [{ text: text, style: 'header' }],
  styles: {
        header: {
            fontSize: 10,
            bold: false
        }
   },
   defaultStyle: {
         font: 'Verdana'
         }
   };
   pdfMake.fonts = {
         Verdana: {
               normal: 'Verdana.ttf',
               bold: 'Verdana Bold.ttf',
               italics: 'Verdana Italic.ttf',
               bolditalics: 'Verdana Bold Italic.ttf'
         },
};
pdfMake.createPdf(docDefinition).open();
```

The result should be this one "säkerställer", but instead is the one in the picture:
[https://postimg.org/image/gct0ezzt1/](url)

Any help is very much appreciated.
Thanks,Leo

**Comment by doyouknowme** [comment]
var text = "säkerställer";
pdfMake.fonts = {
         Verdana: {
               normal: 'Verdana.ttf',
               bold: 'Verdana Bold.ttf',
               italics: 'Verdana Italic.ttf',
               bolditalics: 'Verdana Bold Italic.ttf'
         };
var docDefinition = {
  content: [{ text: text, style: 'header' }],
  styles: {
        header: {
            fontSize: 10,
            bold: false
        }
   },
   defaultStyle: {
         font: 'Verdana'
         }
   };
};
pdfMake.createPdf(docDefinition).open();
---------------------------
try this, i think it may be work.

**Comment by LeoAbu-Saa** [comment]
Thank you @doyouknowme but still doesn't work. From what I see you just moved the fonts declaration before the doc def. Anyway I have tried that and doesn't work ..
Thanks, Leo

**Comment by doyouknowme** [comment]
@LeoAbu-Saa  ,i had change the commention up there,you can just have a try. BTW i am Chinese,i had use this pdfmake to print Chinese word.

**Comment by LeoAbu-Saa** [comment]
@doyouknowme, I still get the same result :(
Thanks anyway.

**Comment by ZEALi** [comment]
@doyouknowme which font did you use to print chinese words? I've tried the default vfs_font , but all chinese words being converted into blank.

**Comment by gdibble** [comment]
@LeoAbu-Saa your utf-8 chars look like they're getting converted to ansi. That's odd.

For me, the problem wasn't in the pdf output.  I was getting an error because I was trying to set a `Content-Disposition` header on hapi reply but the filename I passed had special chars.  Although slightly unrelated, I thought this bit might help someone along:
`reply(pdf).type('application/pdf').header('Content-Disposition', 'attachment; filename="' + encodeURI(fileName) + '"')`

**Comment by dehghani-mehdi** [comment]
Have you any plan to support non-English languages? (for example your library doesn't support  this: `این یک جمله به زبان فارسی است` .

**Comment by liborm85** [comment]
@dehghani-mehdi The library supports a lot of non-English languages. Can you tell me what language is that?

**Comment by dehghani-mehdi** [comment]
@liborm85 `Persian aka Farsi`

As I mentioned this is a sample of Persian language: `این یک جمله به زبان فارسی است`.

**Comment by liborm85** [comment]
@liborm85 In playground is only Roboto font and it does not support Farsi. Is need find font that supports Farsi.

I try download from https://github.com/behnam/fonts-farsiweb/tree/master/ttf font for Farsi, and build to virtual file system (instruction: https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side).

Result:
![farsi](https://cloud.githubusercontent.com/assets/1298652/21499129/4a5d3c84-cc33-11e6-89c8-4fdded3df4f7.png)

I do not know if it's totally correctly, but probably not because is needed RTL support, which is not in pdfmake (https://github.com/bpampuch/pdfmake/issues/184).

**Comment by wolfbomb** [comment]
anyone can help me disGD&T Symbols in pdfmake? my web app using chrome is displaying fine but not when printing with pdfmake.

**Comment by arbabi2010** [comment]
@liborm85 Hi . Could you please upload your persian vs-font.js somewhere for download? Tank you

**Comment by ShinodasCodes** [comment]
better you consider of providing encoding flexibility rather than using tricks implicitly such as importing fonts to resolve character encodes.
