### ISSUE TITLE
Can't we set password protection?

### ISSUE THREAD

**Issue by ghost** [bpampuch/pdfmake#544]
Hey, I am searching here for generating pdf's then with password protection. can we do that using pdfmake?

**Comment by liborm85** [comment]
Related with: https://github.com/bpampuch/pdfmake/issues/1262

**Comment by MobileAppVault** [comment]
Hi, can you give an ETA when this feature will be available in pdfmake?

**Comment by liborm85** [comment]
duplicate with: https://github.com/bpampuch/pdfmake/issues/1262
