### ISSUE TITLE
force N page

### ISSUE THREAD

**Issue by gine** [bpampuch/pdfmake#546]
I create a pdf with only a table. I can't know how much a row is long and I want fill all my page with the same row repeated. But i want that pdfmake create only the first N page.

Is there something that i can use?

**Comment by mahmoudHosny** [comment]
If you mean repeating the header for each page you can play with the following property
headerRows: 1,//repaeat the first row as a header for each page
 keepWithHeaderRows: 1,//if the row is high and will split into 2 pages it will keep it will not break the row and keep the header with it 
 dontBreakRows: true,

**Comment by gine** [comment]
Thanks, but i know this options and it doesn't help me.

I try to explain to you the context. I have a form that i use to get few datas. But in some field you can put more than 1 email separated by comma. Then i need to print this datas in a simple table with 3 columns and repeated for all the row to fill the page. 

But i can't know how much row can stay in a page. Is it possible?

**Comment by mahmoudHosny** [comment]
Do you mean that you want to know how many rows the page will take before the next break?

**Comment by gine** [comment]
Yes, i'm writing a form where the user can write his gpg uid/fingeprint etc.. and then clicking on send button can create his visiting card. So i want to force, better with a params, the pdf page max number.

**Comment by mahmoudHosny** [comment]
I didn't find option to set pages number
However
you can do it by edit the src code
at printer.js there is a renderPages function which take the pages as the first argument and loop so I think that you can edit the code to set the page limit

**Comment by gine** [comment]
thanks, when i have a bit of time i will try.

**Comment by liborm85** [comment]
Implemented by https://github.com/bpampuch/pdfmake/pull/797
