### ISSUE TITLE
Add certificate or set read-only 

### ISSUE THREAD

**Issue by sagg629** [bpampuch/pdfmake#548]
Hi, how can I attach a certificate to all created documents?? ... or make them read-only ???
It's for security issues, in our company we want to make sure documents generated from our website are ours, validated from a certificate, not just from metadata.

Thanks in advance (Y)

**Comment by liborm85** [comment]
Feature request for digital signature is here: https://github.com/bpampuch/pdfmake/issues/1015
Feature request for security/read-only/etc is available here: https://github.com/bpampuch/pdfmake/issues/1262
