### ISSUE TITLE
simple report generation is very slow

### ISSUE THREAD

**Issue by philjoseph** [bpampuch/pdfmake#55]
Hello - 

We are considering using pdfmake in our application to generate one page reports and we are concerned with performance. We are generating simple one page PDF that is 50Kbyte that mostly contain one PNG generated by Google chart that is 20Kbyte. The generation of such a report can take up to 30 second!! We tried to profile that but with no success for now. Any hint about how to profile PDFmake doc generation? 

I will be glad to attach the doc-definition-object that expose this performance concern.

If we cannot optimize, we will consider using web worker and at least unfreeze the UI

Thanks - Philippe Cohen

**Comment by liborm85** [comment]
This should be fixed in the lastest version (0.1.22).

**Comment by viebel** [comment]
Wow!!!! After 2 years!!!
