### ISSUE TITLE
Images displacement on cordova app on Android

### ISSUE THREAD

**Issue by graduss** [bpampuch/pdfmake#552]
All images shifted to the right on platform Android, but on PC and IOS it worked good.
Android version 5.1.1
Please see in attachments
[onAndroid.pdf](https://github.com/bpampuch/pdfmake/files/206665/onAndroid.pdf)
[onPC.pdf](https://github.com/bpampuch/pdfmake/files/206667/onPC.pdf)

**Comment by liborm85** [comment]
You can insert docDefinition for reproduce this problem?

**Comment by liborm85** [comment]
Can not be reproduced.
