### ISSUE TITLE
PdfMake appending of fonts url using javascript is not working…

### ISSUE THREAD

**Issue by abhibly** [bpampuch/pdfmake#553]
Hi i am trying to generate client side pdf using pdfmake.When user clicks on download button i am appending the source link of fonts in head of html that user wants.When he clicks on open button i want to open the pdf. I can see the links has been added successfully in head section but when i click on open button it is showing error saying "Cannot convert undefined or null to object".If i save those files locally it works fine.But if i give the http links of those fonts it doesn't.Why is that so? I have made a plunker demo here https://plnkr.co/edit/KVxjOokQR6x1ftJL6Nl5?p=preview where i am appending links to head section on button click. This is my code to include link files in head
` function download(){

```
  var mainjs=document.createElement('script');
  mainjs.setAttribute('src','https://rawgit.com/xErik/pdfmake-fonts-google/master/build/script/ofl/ledger.js');
  document.head.appendChild(mainjs);


  var mapjs=document.createElement('script');
  mapjs.setAttribute('src','https://rawgit.com/xErik/pdfmake-fonts-google/master/build/script/ofl/ledger.map.js');
  document.head.appendChild(mapjs);
```

 }`

And this is my code to generate and open the pdf

`function openPdf() {
            var docDefinition = {
            content: 'Lorem ipsum dolor sit ametasdddddddddddddddddddddddddddd...',
            defaultStyle: {
                font: Object.keys(pdfMake.fonts)[0]
            }
        };
        pdfMake.createPdf(docDefinition).open();
    }
`
In the plunker demo i have locally saved the font files and included in head section (commented them).If you un-comment them and generate the pdf means it works fine...Somebody please help me how to give the https links of fonts and generate pdf?

**Comment by liborm85** [comment]
It works ok.
Test script: [test_533.zip](https://github.com/bpampuch/pdfmake/files/919865/test_533.zip)
