### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by bmanic** [bpampuch/pdfmake#555]
Hi,

Greate job,

Is there any detailed documentation, with all valid elements in docDefinition object?
Your examples are fine, but i'm looking for something with all valid elemens.

Thank you

bmanic

**Comment by Adhara3** [comment]
I was looking for the same, I had to dig in the code. Not very friendly.

**Comment by j8** [comment]
+1

**Comment by liborm85** [comment]
Will be included in the new documentation. Issue: https://github.com/bpampuch/pdfmake/issues/1238
