### ISSUE TITLE
su-items in an ordered list

### ISSUE THREAD

**Issue by Darbiol** [bpampuch/pdfmake#559]
is there any configuration or property available for the ordered list to show 'lower-alphabets', 'roman numerals' or etc.?

**Comment by liborm85** [comment]
Implemented by commits https://github.com/bpampuch/pdfmake/commit/f1a657fe450a43cfd7fb7facdc653f8b40387caa, https://github.com/bpampuch/pdfmake/commit/83de2beeb7ca1cbbe6b524bc122043e75f730d38

example of usage:
```
{
	type: 'upper-roman',
	ol: [
		'item 1',
		'item 2',
		'item 3',
		'item 4',
		'item 5'
	]
}
```

Supported types: `decimal` (default), `upper-alpha`, `lower-alpha`, `upper-roman`, `lower-roman`, `none`
