### ISSUE TITLE
Feature Request: Support for bidirectional text

### ISSUE THREAD

**Issue by rodnolan** [bpampuch/pdfmake#56]
This feature would make the library usable for generating PDFs in right-to-left languages such as Hebrew

**Comment by jthoenes** [comment]
Duplicate of #184 

@paviad You probably need to adapt docMeasure.js and layoutBuilder and build a similar methods to ``DocMeasure.measureLeaf`` and ``LayoutBuilder.processLeaf`` (e.g. ``processLeaf right``).
