### ISSUE TITLE
Open Windows Asynchronous

### ISSUE THREAD

**Issue by raky291** [bpampuch/pdfmake#560]
Chrome is blocking the popup I am creating. After some tests it appears to be an issue with window.open in asynchronous callback.

for example:

```
$scope.generatePdf = function () {
    $http.post('/someUrl', data).then( function (response) {
    pdfMake.createPdf(docDefinition).open();
  });
};
```

![win](https://cloud.githubusercontent.com/assets/12045722/14580664/12ac6a04-0392-11e6-9820-e406c9ce6c16.jpg)

My solution was to add a new parameter called **win** and add an **if** (look at the picture).

Now it works...

```
$scope.generatePdf = function () {
    var win = window.open('', '_blank');
    $http.post('/someUrl', data).then( function (response) {
    pdfMake.createPdf(docDefinition).open(win);
  });
};
```

If I place the open.window outside of the callback that it works, but inside it is blocked.

Sorry for my English.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/587
