### ISSUE TITLE
Table header new page does not work fine

### ISSUE THREAD

**Issue by tobiashuebnermhp** [bpampuch/pdfmake#563]
Hello,

I hope you have already fixed this issue in another repo, or you can help me to find a quick solution for that:

When I create a table that has too much rows to be displayed at one page, a new page will be created. Also there will be printed the header again. However, pdfmake prints some weird rectangles at the new page. It seems to be an issue with the position of the new row.

![bug-pdfmake](https://cloud.githubusercontent.com/assets/18554776/14642472/d6006130-064a-11e6-824a-6d8c3a1d08bd.png)

Code:

Unfortunately I cannot provide my whole code because it is more than 100 lines long. 

The styles and other configurations are as following:

`styles: {
            header: {
                fontSize: 10,
                bold: true
            },
            tableExample: {
                margin: [0, 5, 0, 5],
                fontSize: 9
            },
            greyBackground: {
                fillColor: '#EBEBEB'
            }
        },pageOrientation: config.orientation,
        pageSize: config.format,
        pageMargins: {
            left: 20,
            top: 20,
            right: 20,
            bottom: 20
        }`
The table:
`var tmpContent = {
            style: 'tableExample',
            table: {
                headerRows: 1,
                widths: widths,
                body: body
            }`
Thanks for your help.

Kind regards,
Tobias

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/247
