### ISSUE TITLE
Problem with font embedding

### ISSUE THREAD

**Issue by frustrateddeveloper** [bpampuch/pdfmake#564]
When I run,

pdfMake.createPdf(docDefinition).download();

my browser displays my PDF as expected.

When I instead run,

pdfMake.createPdf(docDefinition).getDataUrl(function(dataURL) {
$scope.myFileString = dataURL;
// remove header
// data:application/pdf;base64,
$scope.myFileString = $scope.myFileString.replace("data:application\/pdf;base64,",'');
// convert
$scope.myFileString = window.atob($scope.myFileString);

and pass $scope.myFileString to a file creation function (it just gives me access to a database, but only accepts decrypted strings without the header as an argument) my file is saved to the database just fine.  I can download and open the PDF, which has a lot of tables that display correctly.  However, none of the plaintext entries in these tables display properly.  I can copy & paste a table entry somewhere else and see the correct display.

When opening with Adobe reader, I get this error:

Cannot extract the embedded font 'AAAAAA+Roboto-Medium'. Some characters may not display or print correctly.

Any idea what is going on here?  I am completely lost.

Update:
I have managed to get around this problem by using .getBuffer() and constructing a blob instead.

**Comment by dTuteja** [comment]
HI , 
I am facing the same issue , Can you please explain how you get through this or how you used getBuffer()

**Comment by liborm85** [comment]
Solved.

**Comment by vinaynb** [comment]
@liborm85 any help on how did you solve this ?

**Comment by liborm85** [comment]
@vinaynb Solution is in first note:

> Update:
> I have managed to get around this problem by using .getBuffer() and constructing a blob instead.

**Comment by vinaynb** [comment]
@liborm85 i missed that. Thanks !
