### ISSUE TITLE
How to display array of string in pdf?

### ISSUE THREAD

**Issue by rashmiPatil10** [bpampuch/pdfmake#565]
I already have ,

var docDefinition = {
                content: [

```
              { text: '\nMy App Idea', alignment: 'center', bold: true, fontSize: 18 }
      { text: ‘list of data', alignment: 'center', bold: true, fontSize: 18 }
            ],

            styles: {
                header: {
                    fontSize: 22,
                    bold: true
                },
            }
        }
```

now with this i want to add an array of string which should be display below tittle list of data.
$scope.featuresArr = [‘value1’,’value2' ]; 
the values in array are not static they may change.
please help.

**Comment by liborm85** [comment]
I suppose that you need http://www.w3schools.com/jsref/jsref_join.asp or http://www.w3schools.com/jsref/jsref_push.asp
