### ISSUE TITLE
How actively maintained?

### ISSUE THREAD

**Issue by atdiff** [bpampuch/pdfmake#566]
Just curious how actively maintained this code-base is and if I should consider a different project to use in my app.

**Comment by lobo-tuerto** [comment]
Still waiting for a year old issue to be solved: https://github.com/bpampuch/pdfmake/issues/276

`pdfmake.js` clobbers your `lodash` with it's own outdated internal copy.

**Comment by liborm85** [comment]
Now we will work on the project intensively. PRs are welcome.
