### ISSUE TITLE
Server side unicode font embedding.

### ISSUE THREAD

**Issue by ataurrahim** [bpampuch/pdfmake#567]
I am trying to embed bengali font to generate pdf in server side. 

following this article (https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side), I can add fonts in the following way:

```
{
   yourFontName: {
     normal: 'fontFile.ttf',
     bold: 'fontFile2.ttf',
     italics: 'fontFile3.ttf',
     bolditalics: 'fontFile4.ttf'
   },
   anotherFontName: {
     (...)
   }
}
```

And in definition:

```
var docDefinition = {
  content: (...),
  defaultStyle: {
    font: 'yourFontName'
  }
}
```

Font gets desplayed, but the font seem to be broken (complex characters). In the client side article suggested that to build and add `vfs_fonts.js`. But, don't know how add this in server side.

**Comment by daupawar** [comment]
Check this example https://github.com/daupawar/MeteorAsyncPdfmake

**Comment by ycpatel813** [comment]
@ataurrahim is your problem is solved?? I am still facing same issue.
@daupawar  can you check this issue ? #643 will it solved by your repo??

**Comment by liborm85** [comment]
Answered. No reaction.
