### ISSUE TITLE
What is the page width ?

### ISSUE THREAD

**Issue by JanBN** [bpampuch/pdfmake#568]
I want to fit image into rectangle of 1/3 of page width. How to do this ?

**Comment by DeadcatDev** [comment]
Good question. Image width dont work with ex. width='33%' just with width=100. My current solution is do columns like:
```
columns: [{
    width: '66%'
    text: 'some text'
},{
    width: 170
    image : base64
}]
```

It's this way because (for my case) A4 page is always the same but ya know, its not the 'right way' to do so.

**Comment by liborm85** [comment]
https://github.com/bpampuch/pdfmake/issues/1238
