### ISSUE TITLE
Very slow images generation 

### ISSUE THREAD

**Issue by JanBN** [bpampuch/pdfmake#569]
Hello,

I need to create a pdf full of pictures (qr-codes) in table, so it can be easily cut. However pdfmake is very slow. So slow that chrome suggests me to kill page. When I get rid of images it is in a second. I have also tried jspdf and it generates images fast, but I don't want to deal with positioning so I would prefer this libraby. Please help

**Comment by mplussit** [comment]
Hi.

**Comment by liborm85** [comment]
Can you try it with lastest pdfmake version (0.1.22) ?
