### ISSUE TITLE
insert backer image on page 2

### ISSUE THREAD

**Issue by baddhamsster** [bpampuch/pdfmake#571]
Hey guys, 
I am trying to insert a backer image on page 2 for duplexing, but I have a repeating stack just before the image and causes the image to move. Is there a way to have the stack page break around the image or insert a page 2 with the backer after the stack is ran?

here is the code:

function getStack(){
                              var column = [];
                              angular.forEach(array, function(val, index) {
column.push([
                                          {
                                              stack: [
                                                  {
                                                      columns: [
                                                          {text: 'stuff', alignment: 'center', fontSize: 8,},
                                                      ]
                                                  }, 
                                              ],
                                              id: index,
                                          }
                                      ]);
                                  }
                              });
                              return column;
}
var dd = {
  content: [{
                                 stack: [
                                              getStack(),
                                          ]
                                  },
                                  {
                                      image: backer,
                                      margin: [-20, 0, 0, 0],
                                      fit: [550, 1200]
               }],
                              pageBreakBefore: function(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
                                      angular.forEach(array, function(val, index) {
                                      if (currentNode.id === ( index) && currentNode.startPosition.pageNumber === 2) {
                                          return true;
                                      }
                                      return false;
                                      });
                              },
 }

**Comment by liborm85** [comment]
Can you put the code that will work on http://pdfmake.org/playground.html?
