### ISSUE TITLE
Django selenium, mutating prototype

### ISSUE THREAD

**Issue by wuahi** [bpampuch/pdfmake#573]
Im running Django 1.8.9, using selenium for testing and i'm getting this error when pdfmake.js is included on page.

`{u'sourceName': u'http://localhost:8081/static/js/pdfmake.js', u'errorMessage': u'mutating the [[Prototype]] of an object will cause your code to run very slowly; instead create the object with the correct initial [[Prototype]] value using Object.create', u'console': None, u'lineNumber': 421}`

Any ideas?

**Comment by liborm85** [comment]
I can not work with Django, try their support.
