### ISSUE TITLE
Browser Compatibility List

### ISSUE THREAD

**Issue by JohannesKuehnel** [bpampuch/pdfmake#575]
I plan on using this library for an upcoming project, but I need to know which browsers actually work with it.

Is there such a compatibility list?

**Comment by nigel-dewar** [comment]
it doesnt work on IE I can tell you that!

**Comment by gsc89** [comment]
The face when I spent 2 hours developing in chrome but the client insists on using IE .... 

![spongar](https://cloud.githubusercontent.com/assets/1032459/17522879/90044292-5e50-11e6-88f6-444989bf4cfd.gif)

**Comment by liborm85** [comment]
here: https://github.com/bpampuch/pdfmake/issues/800

**Comment by nigel-dewar** [comment]
God i love the face bro, its good. Hahah
