### ISSUE TITLE
Chrome, Firefox block popups when first time used

### ISSUE THREAD

**Issue by MangaRed** [bpampuch/pdfmake#578]
The first time a user clicks the button "view pdf", there is no way to notify the user about the blocked popup although in firefox it shows a wide yellow message, in chrome it's not so wide, and can be unnoticed so the user can say the button doesn't work. 
So I checked the source and added this code in the `open` method

```
Document.prototype.open = function(message) {
    // we have to open the window immediately and store the reference
    // otherwise popup blockers will stop us
    var win = window.open('', '_blank');
    if (!win) {console.warn('enable popups'); return false;} // HERE NEW CODE
    try {
        this.getDataUrl(function(result) { ...
```

so when It runs
`var result = pdfMake.createPdf(dd).open();`
I notify the user if the popup was blocked
`if (result === false) {toastr.warning('The popup was blocked by the browser. Please allow popups from this domain');}`

**Comment by marcioaguiar** [comment]
I think the open function should return the _**win**_ reference, so the client can check if the window was opened and also do whatever he wants.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/424

**Comment by moffsugita** [comment]
@MangaRed did you resolve it?
