### ISSUE TITLE
How to do zebra background color in tables

### ISSUE THREAD

**Issue by bartosh44** [bpampuch/pdfmake#579]
Hi,
I would like to do zebra background-color on table (generated pdf). Is it possible with pdfmake?

**Comment by padre629** [comment]
You just need to set a "global" variable (to control row background) in true or false depending row of your table. 
For example, you may to set "true" on even rows (2, 4, 6... table index 1, 3, 5) and "false" on odd rows (1, 3, 5... table index 0, 2, 4).
Odd rows won't be background-colored, so in some indexes the variable controlling background will be false; by other hand, even rows will be background-colored, var will be true. Depending on your logic you can achieve something like this.

If current index (while looping array to print the table) representing a row, will be background-colored, you may to do something like this:
`
columns: [
   {width: 'auto', text: $filter('nameFilter')(sector.name), style: 'tableContent'},
   {
      width: 'auto', text: ' ' + sector.cont, style: ['tableContent', 'red', 'boldText', 'superscript']
   }
], columnGap: 2, fillColor: rowBackground ? cellBackgroundColor : ""
`
cellBackgroundColor is a variable containing color in HEX format ("#EAEAEA" for example).
Look at **fillColor** statement: print this section if rowBackground is true / else don't set a color.

Easy, like this, hope this helps.

**Comment by gabrielenosso** [comment]
you could also use something like this
`export function addRowsDifferentBackground(tableBody) {
  // Iterate all rows
  return tableBody.map((row, index) => {
    if (Array.isArray(row) && index % 2 === 0) {
      // Iterate all cells of the row and add the properties
      return row.map(cell => {
        const c = { ...cell };
        if (!c.fillColor) c.fillColor = theme.tableDifferentRowColor;
        console.log(c);
        return c;
      });
    }
    return row;
  });
}`

**Comment by liborm85** [comment]
Implemented "zebra style" for tables in layout, by commit https://github.com/bpampuch/pdfmake/commit/e0fd55d5193cc4e2e167d2d39ab0fc7113f27b24.
`fillColor` in table cell has a higher priority.

Example of usage:
```js
var dd = {
	content: [
		{
			table: {
				body: [
					[{text:'Row 1'}, {text:'Column 2A'}],
					[{text: 'Row 2'}, {text: 'Column 2B'}],
					[{text: 'Row 3'}, {text: 'Column 2C'}],
					[{text: 'Row 4'}, {text: 'Column 2D - own fill color', fillColor: 'red'}]
				]
			},
			layout: {
				fillColor: function (i, node) {
					return (i % 2 === 0) ?  '#CCCCCC' : null;
				}
			}
		}
	]
};
```
