### ISSUE TITLE
Does anyone know how to set the pageSize properly for a thermal printer?

### ISSUE THREAD

**Issue by qgliu** [bpampuch/pdfmake#582]
The printer size has width of 3 1/2''

**Comment by fdoddridge** [comment]
I'm printing to a TPG A799.  I set the width to 300, and the height to something large enough that it won't page wrap... like 3000.  Just experiment a bit, you'll find the right size.

**Comment by qgliu** [comment]
Thanks a lot. In the Wiki or demo page, it might be worth including the unit of these numbers. I was experimenting to find if they are inch, cm, mm, or pixel based.

**Comment by techana** [comment]
The formula for calculating width and height values for a page is:
 value in inch * 72
or
 value in mm / 0.35277

See here: https://en.wikipedia.org/wiki/Point_(typography)
