### ISSUE TITLE
datatables table formating

### ISSUE THREAD

**Issue by AmitKannaujiya** [bpampuch/pdfmake#583]
Hi ,
I am using datatable library to generate tables in my project and there lib have option to generate pdf doc of table through pdfmake . Now the tables are generated but it i not well formatted (alignment,margin,padding) .can any one help regarding columns/cell formatting .
[pdf (7).pdf](https://github.com/bpampuch/pdfmake/files/274015/pdf.7.pdf)

i am using it like 
extend: 'pdfHtml5',
                            text: 'PDF',
                            title: '',
                            //message: headerView,
                            customize: function (doc) {
doc.content.splice(0, 0,
                                        cont);
}
can i change styling for table ? 
layout:"noBorder"
cell=>  style:"tableBodyOdd"/"tableBodyEven" 
can i change alignment/marging /pading of table as well as cells of table in pdf ?

**Comment by liborm85** [comment]
You can use this: https://github.com/bpampuch/pdfmake/blob/e0fd55d5193cc4e2e167d2d39ab0fc7113f27b24/src/docMeasure.js#L363-L392
you can try here: http://pdfmake.org/playground.html
