### ISSUE TITLE
Identify if to use gulp or Gruntfile and go for one

### ISSUE THREAD

**Issue by evilaliv3** [bpampuch/pdfmake#585]
Gulp and Grunt are two alternatives and generally every plugin has been implemented by their users.

To ease creating a community around pdfmake it would be valuable to simplify the development process and clearly define what is be used and what not and avoid duplication.

first activity would be probably to choose if to use gulp or Grunt for the build and test, because one is simply an alternative of the other.

**Comment by evilaliv3** [comment]
From my undestunding @bmihelac, i think that you decided in https://github.com/bpampuch/pdfmake/commit/02a859b90b262921bb1a00409c7f548332dce33b to go for Gulp;

Probably you forgot to simply remove the Gruntfile and i do not know why it has been accepted the commit https://github.com/bpampuch/pdfmake/commit/d5d0cc1b8ca5c868acc5be89d0b8406259632781

i will proceed providing a patch for simply removing both.

**Comment by bmihelac** [comment]
@evilaliv3 you meant to mention @bpampuch and not me, right?

**Comment by danawoodman** [comment]
@evilaliv3 I'm holding off on merging this right now as I'm going to refactor things to just use WebPack, but thanks for the PR!
