### ISSUE TITLE
open function won't work in a callback

### ISSUE THREAD

**Issue by krewx** [bpampuch/pdfmake#587]
I can't seem to use the open function after any callback. I tried to use the function after an ajax call and after using SVG.toDataURL, in both cases i get "undefined is not an object (evaluating 'e.location')"

**Comment by daupawar** [comment]
please post some line of code

**Comment by zilzurna** [comment]
Same issue here.
This code does not work. Gives; 

> pdfmake.min.js:110  Uncaught TypeError: Cannot read property 'location' of undefined

```javascript
           $.post(site_url, form_data, function(json) {

				var pdfContent = {
					content:[
						"First paragraph",
						"Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines"
					]
				};
				pdfMake.createPdf(pdfContent).open();

			}, "json");
```
 But it is working outside of the ajax callback function.

**Comment by liborm85** [comment]
Works only `download()` method.

**Comment by raky291** [comment]
This is a temporary solution:
I solved this issue modified the build code ("open" method).
```
// add the "win" argument
Document.prototype.open = function(win) {
  // if don't exist a window, create one
  if (!win) {
    win = this._openWindow();
  }
  try {
    [...]
  } catch (e) {
    win.close();
    throw e;
  }
};
```
Usage

```
$scope.generatePdf = function() {
  // create the window before the callback
  var win = window.open('', '_blank');
  $http.post('/someUrl', data).then(function(response) {
    // pass the "win" argument
    pdfMake.createPdf(docDefinition).open(win);
  });
};
```

**Comment by clemf** [comment]
@raky291 Did you submit a pull request? I would love to have this in the official release.

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/5f4076ff0e4738134664f75108e34b980993452f.

`open()` example:
```js
$scope.generatePdf = function() {
  // create the window before the callback
  var win = window.open('', '_blank');
  $http.post('/someUrl', data).then(function(response) {
    // pass the "win" argument
    pdfMake.createPdf(docDefinition).open({}, win);
  });
};
```


`print()` example:
```js
$scope.generatePdf = function() {
  // create the window before the callback
  var win = window.open('', '_blank');
  $http.post('/someUrl', data).then(function(response) {
    // pass the "win" argument
    pdfMake.createPdf(docDefinition).print({}, win);
  });
};
```

**Comment by cJayyy** [comment]
**Is it true that this solution can not be used unless application runs AngularJS?**
If not, how could I implement it in pure JS? 

This is the only solution to this issue i've found yet.

**Comment by liborm85** [comment]
No., Used framework/technology for async process is not related to pdfmake and `open()`. 

It is important at begin of action create/open new window and then pass this parameter to pdfmake `open()`. See [readme](https://github.com/bpampuch/pdfmake#open-the-pdf-in-a-new-window).

**Comment by moffsugita** [comment]
not work

I used new version. I read `node_modules/pdfmake/build/pdfmake.js` and same to https://github.com/bpampuch/pdfmake/commit/5f4076ff0e4738134664f75108e34b980993452f
