### ISSUE TITLE
Watermark styling is not working

### ISSUE THREAD

**Issue by johnnycorleone** [bpampuch/pdfmake#590]
Hello, i'm trying to create watermark on my pdf exported from datatables. I received an error like this:
![error watermark](https://cloud.githubusercontent.com/assets/8342957/15489362/4f1f2e6c-2189-11e6-8bff-d1c7488483cf.PNG)

And here's code i write in my script
![code](https://cloud.githubusercontent.com/assets/8342957/15489431/e9357524-2189-11e6-96c5-b74d3a924b00.PNG)

Anyone know what problem i'm getting into?

**Comment by liborm85** [comment]
Fixed by #492
