### ISSUE TITLE
Indian Rupee Symbol

### ISSUE THREAD

**Issue by mzmmohideen** [bpampuch/pdfmake#593]
I want to use Indian Rupee Symbol either from HTML HEx code or from FONT ... Roboto Font supports Indian Rupee Symbol but pdfmake wont showing that.. kindly help me to get solution for this issue .

**Comment by AmitKannaujiya** [comment]
use ubuntu font , as it has support for ruppes symbol .
https://github.com/Nishi-Inc/billing/issues/1

**Comment by liborm85** [comment]
Answered.
