### ISSUE TITLE
Predefined page sizes

### ISSUE THREAD

**Issue by kamilkp** [bpampuch/pdfmake#6]
It would be nice if one could declaratively define a desired page size. The docuement definition object now supports this syntax:

```
var dd = {
    content: someContentObject,
    pageSize: {
        width: pageWidth,
        height: pageHeight
    }
};
```

I'd like to be able to define it like that:

```
var dd = {
    content: someContentObject,
    pageSize: 'A4' // A3, A5 or other standard page sizes
};
```

**Comment by jayiconcmo** [comment]
Trying to make labels. What is the measurement in for me to set the width and hieght? Is is inches, CM, MM, and so on

**Comment by varundbest** [comment]
@jayiconcmo Taking this file as reference :- https://github.com/bpampuch/pdfmake/blob/7b5675d5b9d5d7b815bd721e00504b16560a6382/src/standardPageSizes.js

I'd say width and height are in pixels as per 72 DPI.
