### ISSUE TITLE
.open() immediately closes when using pdfmake.min.js

### ISSUE THREAD

**Issue by binoche9** [bpampuch/pdfmake#60]
The title pretty much says it all. When I try .open() when I include pdfmake.min.js, a tab opens then immediately closes. However, when I use pdfmake.js, it works as I expect it to.

I have no idea why this is happening but I thought I'd let you know.
I'm using Mac OSX 10.9.4 and Chrome 36.0.1985.125
I can recreate this issue in Safari 7.0.5 and Firefox 30.0

The pdfmake.js and pdfmake.min.js files were downloaded a few minutes ago.

Hope this can be resolved!

**Comment by jmcgrory-plx** [comment]
If anyone else is experiencing this on the current v0.1.27, first check you have whatever flavour of ad blocker you may have turned off. That's coming from a guy who definitely didn't accidentally turn on uBlock Origin in his dev environment...

**Comment by fsauter** [comment]
Do you guys know a way that we don't have to force the user to disable his ad blocker?

**Comment by jmcgrory-plx** [comment]
Not that I know of, if there's an option to open in the current window then it should work however.

**Comment by BennyHinrichs** [comment]
Just wanted to say that I encountered this issue January 2019, being blocked by uBlock. However, if I breakpoint the `this.getBlob` function call inside of `Document.prototype._openPdf` and wait ~15 or more seconds then hit run, it loads. Something about the adblocker stops caring if you wait awhile.
