### ISSUE TITLE
Is it possible to use web worker with makepdf using angularjs?

### ISSUE THREAD

**Issue by Damore** [bpampuch/pdfmake#602]
I have read how to better performance with makepdf [here](https://github.com/bpampuch/pdfmake/issues/280#issuecomment-98944706). However, this does not solve my problem, since I have more than a 100 pages to export to pdf. I saw a solution on stackoverflow on how to use web worker work with javascript, the solution is on this [link](http://stackoverflow.com/questions/32689932/how-to-apply-web-worker-to-rendering-of-a-pdf-using-makepdf/33206568#). But I want to know if it is possible to have this solution with AngularJs

**Comment by daupawar** [comment]
yes this is possible with angularjs
check [this](https://developer.mozilla.org/en-US/docs/Web/API/Worker/onmessage) for web worker

**Comment by liborm85** [comment]
Answered.
