### ISSUE TITLE
table borders

### ISSUE THREAD

**Issue by solisoft** [bpampuch/pdfmake#607]
There is a way to add a bottom border at the end of the page when a table is split on two pages ? 
I use a specific layout which don't display horizontal lines ... except for the last one... 
How can I specify the latest row of a page (before page break) ?

**Comment by liborm85** [comment]
See the documentation http://pdfmake.org/index.html#/gettingstarted , chapter "Headers and footers"

**Comment by CanadaViet** [comment]
The footer is clearly not an answer to that question

**Comment by RedFish** [comment]
I'm still looking for this feature, is there a way (or workaround) to do it today?
