### ISSUE TITLE
Large file size

### ISSUE THREAD

**Issue by mkey** [bpampuch/pdfmake#609]
Hello good people.

I'm experiencing an issue (or is it maybe a feature?) where generated pdf files are rather large. Files I'm creating are rather simple, some text and tables, one small overlay image and the included roboto font.

If I print said pdfs into pdf (via Cute PDF) the file size is reduced about 6-10 times. I'm attaching an example below. The printed pdf looks very similar to the original to me, only page orienation isn't preserved.

Thanks for your time and all of your hard work.

[gb_cup_2016_19_06_original.pdf](https://github.com/bpampuch/pdfmake/files/318624/gb_cup_2016_19_06_original.pdf)
[gb_cup_2016_19_06.pdf](https://github.com/bpampuch/pdfmake/files/318625/gb_cup_2016_19_06.pdf)

**Comment by padre629** [comment]
You can override default pdfmake settings to achieve PDF file compression, by editing directly the unminified version of library. 
More explained in this issue, https://github.com/bpampuch/pdfmake/issues/622.

PS: I've edited file directly and, currently, it's  working as expected: 
before, a file with data (6 pages), ~600KB
after, a file with the same data, ~135KB

**Comment by mkey** [comment]
Thanks, will look into it.

**Comment by liborm85** [comment]
Compression was enabled by default. More info: https://github.com/bpampuch/pdfmake/issues/622#issuecomment-267807661

**Comment by mkey** [comment]
Hello good people. That time of the year again :D

I have updated to 0.1.30 since 0.1.20 kept throwing me an error along these lines https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Invalid_array_length

Anyhow, whether I set the compression option to false or true, I still get a fairly large PDF file, about 1.3 MB instead of some 50KB after optimization via various online PDF optimization services. I'm not getting any errors nor warnings in the console.

Tried it in Firefox 53.0.3 64 bit, Maxthon 4.4.8.1000 32 bit, Google Chrome 59.0.3071.86 32 bit (produces even a bit larger file than the other two.)

I'm adding two examples.

[gb_cup_2017_17_06-formalni.pdf](https://github.com/bpampuch/pdfmake/files/1064980/gb_cup_2017_17_06-formalni.pdf)
[gb_cup_2017_17_06-formalni-ilovepdf-compressed.pdf](https://github.com/bpampuch/pdfmake/files/1064981/gb_cup_2017_17_06-formalni-ilovepdf-compressed.pdf)

**Comment by liborm85** [comment]
Attach a sample script that causes `invalid array length` error for reproduce your problem.

**Comment by mkey** [comment]
Well, that was for the old version of pdfmake on the newer firefox version.
A year ago there wasn't any such error with the same code, so something
must have changed in the browser.

If you really need it, I can work on pinpointing the part of the code that
generates the problem, but I have quite a lot of loops there and data so it
will take some time.

Exactly why I chose to upgrade instead of delving in older code versions.

Again, if you stand to benefit from that, I'll do it, just want to be sure
we're on the same page.



On 10 Jun 2017 09:38, "Libor M." <notifications@github.com> wrote:

Attach a sample script that causes invalid array length error for reproduce
your problem.

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/bpampuch/pdfmake/issues/609#issuecomment-307549123>,
or mute
the thread

**Comment by mkey** [comment]
I have found a simple PDF analyzer demo program on codeproject
https://www.codeproject.com/Articles/450254/PDF-File-Analyzer-With-Csharp-Parsing-Classes-Vers

The most interesting part of it would be these objects, which are basically quite large uncompressed bitmaps of the logo I'm using in the pdf.

> 3 0 obj
> %% File Position: 7099 Hex: 1BBB
> %% Object Type: /XObject
> %% Object Subtype: /Image
> <</BitsPerComponent 8/ColorSpace/DeviceRGB/Filter/FlateDecode/Height 458
> /Length 263443/SMask 31 0 R/Subtype/Image/Type/XObject/Width 450>>
> stream
> Stream data file position: 7.267 Hex: 1C63
> endstream
> endobj
> 4 0 obj
> %% File Position: 271135 Hex: 4231F
> %% Object Type: /XObject
> %% Object Subtype: /Image
> <</BitsPerComponent 8/ColorSpace/DeviceRGB/Filter/FlateDecode/Height 458
> /Length 263443/SMask 32 0 R/Subtype/Image/Type/XObject/Width 450>>
> stream
> Stream data file position: 271.303 Hex: 423C7
> endstream
> endobj
> 5 0 obj
> %% File Position: 535171 Hex: 82A83
> %% Object Type: /XObject
> %% Object Subtype: /Image
> <</BitsPerComponent 8/ColorSpace/DeviceRGB/Filter/FlateDecode/Height 458
> /Length 263443/SMask 33 0 R/Subtype/Image/Type/XObject/Width 450>>
> stream
> Stream data file position: 535.339 Hex: 82B2B
> endstream
> endobj
> 6 0 obj
> %% File Position: 799207 Hex: C31E7
> %% Object Type: /XObject
> %% Object Subtype: /Image
> <</BitsPerComponent 8/ColorSpace/DeviceRGB/Filter/FlateDecode/Height 458
> /Length 263443/SMask 34 0 R/Subtype/Image/Type/XObject/Width 450>>
> stream
> Stream data file position: 799.375 Hex: C328F
> endstream
> endobj

![screenshot_2](https://user-images.githubusercontent.com/672581/27282451-4b692610-54f0-11e7-8158-8e733e9076ff.png)
[1.pdf](https://github.com/bpampuch/pdfmake/files/1084665/1.pdf)
[2.pdf](https://github.com/bpampuch/pdfmake/files/1084666/2.pdf)

**Comment by mkey** [comment]
I have been doing some thinking yesterday so I went ahead and checked it out now.

```
var img = new Image();

img.setAttribute('crossOrigin', 'anonymous');
img.src = 'images/logo.jpg';

img.onload = function ()
{
	var canvas = document.createElement('canvas');
	canvas.width = this.width;
	canvas.height = this.height;
	
	var ctx = canvas.getContext('2d');
	ctx.drawImage(this, 0, 0);
	
	var dataURL = canvas.toDataURL('image/jpg');
	
	pdfMake.createPdf(_prep_object(dataURL)).download(__site_data.db + '_list.pdf');
};
```

This is the function I'm using to load the image into a canvas. Image is of a jpg type and while `canvas.toDataURL('image/jpg')` should supposedly output a jpf file type, it does not. I get a rather large png type image, over 290KB in size. When I convert the jpg file to a base64 string and feed that to the pdfMake.createPDF function, I get a smaller pdf, about 90 KB, down from over 1 MB.

Giant pdf size is due to the image size (I'm not sure what's up with canvas) but also caused by the problem of same image object not being reused inside the pdf.

[01.pdf](https://github.com/bpampuch/pdfmake/files/1097763/01.pdf)
[02.pdf](https://github.com/bpampuch/pdfmake/files/1097765/02.pdf)
