### ISSUE TITLE
How to use font awesome

### ISSUE THREAD

**Issue by fabiosantos87** [bpampuch/pdfmake#610]
How I use font awesome with pdfmake?
Thanks in advance

**Comment by h3kt0r** [comment]
https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side

1- Get proyect from Github
2- Add your font into examples/fonts
3- in the root path exec grunt dump_dir (It recreate the build/vfs_fonts.js file with the files in examples/fonts)
4- In html import pdfmake.min.js and the updated vfs_fonts.js file
5- Add the fonts we are going to use 
 ```
pdfMake.fonts = {
    Roboto: {
            normal: 'Roboto-Regular.ttf',
            bold: 'Roboto-Medium.ttf',
            italics: 'Roboto-Italic.ttf',
            bolditalics: 'Roboto-Italic.ttf'
        },
        FontAwesome: {
            normal: 'fontawesome-webfont.ttf',
            bold: 'fontawesome-webfont.ttf',
            italics: 'fontawesome-webfont.ttf',
            bolditalics: 'fontawesome-webfont.ttf'
        }
}
```
6- Append this functions to your proyect
```
var findSymbolForClass = function (selector) {
        var result = '';
        var sheets = document.styleSheets;

        for (var sheetNr = 0; sheetNr < sheets.length; sheetNr++) {
            var content = findCSSRuleContent(sheets[sheetNr], selector);

            if (content) {
                result = stripQuotes(content);
                break;
            }
        }
        return result;
    };

    function findCSSRuleContent(mySheet, selector) {
        var ruleContent = '';
        var rules = mySheet.cssRules ? mySheet.cssRules : mySheet.rules;

        for (var i = 0; i < rules.length; i++) {
            var text = rules[i].selectorText;
            if (text && text.indexOf(selector) >= 0) {
                ruleContent = rules[i].style.content;
                break;
            }
        }

        return ruleContent;
    }

    function stripQuotes(string) {
        var len = string.length;
        return string.slice(1, len - 1);
    }
```
7- Add a icon to your content
```
var content = ...
  contenido.push({
    text: findSymbolForClass('fa-plus', ''),
    style: 'symbol'
});
```
8- Create the pdf with the full docDefinition (requires the content and the style)
```
var docDefinition = {
            content: content,
            styles : styles
 };
```
9 Append this entry to docDefinition
` docDefinition.styles.symbol = {font: 'FontAwesome'};`
10- Create the PDF
 `pdfMake.createPdf(docDefinition).open();`

It works for me :D

**Comment by fabiosantos87** [comment]
can you poost a project wu«it the font working I tried but witout sussec

**Comment by fabiosantos87** [comment]
can you post a project with this work? i try and with no success

**Comment by fabiosantos87** [comment]
now i get this error:
Error: Font 'FontAwesome' in style 'normal' is not defined in the font section of the document definition.

**Comment by fabiosantos87** [comment]
Error: No unicode cmap for font

**Comment by fabiosantos87** [comment]
The probles is he doesn't create de base64 in vfs_fonts i add that to the file and work's perfectelly thanks a lot

**Comment by h3kt0r** [comment]
:))

**Comment by filipejoe** [comment]
I try but the simbols appear one square. How i incorporate this font in pdf make? thanks in advanced.

**Comment by stevebelt** [comment]
Are these instruction compatible with the dev-playground? I have followed these steps, adding the functions in step-6 just above the createPdfBinary() function already defined in the dev-playground/server.js. When I use the following source in the web-ui:

```
var dd = {
	content: [
		'First paragraph',
		{ text: findSymbolForClass('fa-plus', ''),
        style: 'symbol'	}
    ],
    styles: {
        symbol: { font: 'FontAwesome' }
    }	
}
```

I get the following error:
```
ReferenceError: document is not defined
    at findSymbolForClass (C:\temp\pdfmake\dev-playground\server.js:19:22)
    at eval (eval at <anonymous> (C:\temp\pdfmake\dev-playground\server.js:89:3), <anonymous>:6:11)
    at C:\temp\pdfmake\dev-playground\server.js:89:3
    at Layer.handle [as handle_request] (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\layer.js:95:5)
    at next (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\route.js:137:13)
    at Route.dispatch (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\route.js:112:3)
    at Layer.handle [as handle_request] (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\layer.js:95:5)
    at C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\index.js:281:22
    at Function.process_params (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\index.js:335:12)
    at next (C:\temp\pdfmake\dev-playground\node_modules\express\lib\router\index.js:275:10)
```
What is 'document' suppose to be. Or, more helpful, has anyone got this setup? Is there a project anywhere that has already put these steps together?

Thanks!

**Comment by suryarsp** [comment]
How to create the  base64 in vfs_fonts. You said that you added that file and it works perfectly fine @fabiosantos87 . Please reply aspa

**Comment by markhbucknell** [comment]
@suryarsp follow these instructions https://pdfmake.github.io/docs/fonts/custom-fonts-client-side/ 
(that will give you the base64 image file but I still have other issues with the instructions above)
