### ISSUE TITLE
How to customize generated pdf's file name

### ISSUE THREAD

**Issue by arjunchakkalakunnel** [bpampuch/pdfmake#611]
I am generating pdf with following code, and send it to browser, when i click pdfviewer download button, filename shows like "c89d9d51-9bfa-4955-84d1-ac6e330e5875.pdf", how can i change it?
![screenshot from 2016-06-17 17 13 08](https://cloud.githubusercontent.com/assets/6231867/16149538/174c20f6-34af-11e6-8c2d-6565fe3eabc0.png)

> createPdf(function(req,res){
> 
> var pdfDoc = printer.createPdfKitDocument(docDefinition);
> 
>   //pdfDoc.pipe(fs.createWriteStream('./output.pdf'));
>   var chunks = [];
>   var result;
> 
>   pdfDoc.on('data', function(chunk) {
>       chunks.push(chunk);
>   });
>   pdfDoc.on('end', function() {
>       result = Buffer.concat(chunks);
>       callback(result);
> 
>   });
> 
>   pdfDoc.end();
> });

**Comment by padre629** [comment]
From docs (http://pdfmake.org/#/gettingstarted) to specify a custom name of PDF file you want to download, you may to achieve this:
```

// download the PDF (temporarily Chrome-only)
pdfMake.createPdf(docDefinition).download('optionalName.pdf');
```

**Comment by liborm85** [comment]
Aswered.

**Comment by moffsugita** [comment]
How about `open()`?

**Comment by moffsugita** [comment]
https://github.com/bpampuch/pdfmake/issues/680

**Comment by moffsugita** [comment]
https://github.com/bpampuch/pdfmake/issues/1304

**Comment by atomdaf** [comment]
and open()?

**Comment by scrivereleonardo** [comment]
> and open()?

Try to change the Metadata of the document,

Documentation:
https://pdfmake.github.io/docs/0.1/document-definition-object/document-medatadata/
