### ISSUE TITLE
Is it possible to add html into pdf?

### ISSUE THREAD

**Issue by ryanlin1986** [bpampuch/pdfmake#613]
I need to generate a contract pdf, the agreement part is html content(edited by html editor), how can I embed a the agreement html into pdf? Should I manually parse the html, and loop through it to generate?

**Comment by tiagoargolo** [comment]
Check this out: https://github.com/ymkins/html2pdfmake

**Comment by ryanlin1986** [comment]
Thanks for the hint

**Comment by chrillewoodz** [comment]
Will this automatically create pages if content becomes too long?
