### ISSUE TITLE
Multi column text support?

### ISSUE THREAD

**Issue by ryanlin1986** [bpampuch/pdfmake#614]
For more information, please see the following article:
http://www.mikesdotnetting.com/article/89/itextsharp-page-layout-with-columns

**Comment by robertknecht** [comment]
We need this functionality as well. Is there a way to create this using the existing pdfMake framework? Is there a way to dynamically track the height of the content as the report is being built?

**Comment by RobertPrediger** [comment]
+1

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/604
