### ISSUE TITLE
PDFMake Unicode Font issue

### ISSUE THREAD

**Issue by sujithramani** [bpampuch/pdfmake#615]
Hi Namaskaram, 
                    I am suji i m new to pdfmake.I tried custom font in pdfmake like explained in issue 33,it is having 3 steps for custom font rendering in PDF, but i got swap in that pdf for that particular word, i attached the PDF

![screenshot from 2016-06-21 17 22 18](https://cloud.githubusercontent.com/assets/20064735/16228357/267fa8c2-37d4-11e6-80a5-6821c67596f6.png)

for your reference and my code.Please check and tell what i did wrong.Please guide how to use custom font in pdfmake.

This is my code,

var fonts = {
Roboto:{
normal: 'examples/fonts/Roboto-Regular.ttf',
bold: 'examples/fonts/Roboto-Medium.ttf',
italics: 'examples/fonts/Roboto-Italic.ttf',
bolditalics: 'examples/fonts/Roboto-Italic.ttf'
},
UniIlaSundaram : {
normal: 'examples/fonts/UniIla.Sundaram-05.ttf',
bold: 'examples/fonts/UniIla.Sundaram-05.ttf',
italics: 'examples/fonts/UniIla.Sundaram-05.ttf',
bolditalics: 'examples/fonts/UniIla.Sundaram-05.ttf'
  }
}
var docDefinition = { content: ("Test Tamil  தமிழ்  Word"),
Style: {
font: 'UniIlaSundaram'
}
};
pdfMake.createPdf(docDefinition).open();

thankyou,
SujithraMani

**Comment by liborm85** [comment]
On screen looks all alright. I don't know what language is it. Maybe require RTL (https://github.com/bpampuch/pdfmake/issues/184).

**Comment by senthilksp** [comment]
same issue any solution

**Comment by arunrajdpm** [comment]
any solution regarding this one

**Comment by imPrashik** [comment]
try using "Arial_Unicode_MS", this font supports many languages.

[WikiPedia](https://en.wikipedia.org/wiki/Arial_Unicode_MS#:~:text=The%20code%20pages%20supported%20are,Devanagari)
