### ISSUE TITLE
Draw line in footer

### ISSUE THREAD

**Issue by fabiosantos87** [bpampuch/pdfmake#616]
How I draw a line in the footer and appears in all pages? Thanks in advance

**Comment by sunduoze** [comment]
Sorry, I'm a novice in this, I do not understand because i used this only a few times。

**Comment by tneil** [comment]
Have you tried the **canvas** object that allows you to draw different vectors? https://github.com/bpampuch/pdfmake/blob/master/examples/vectors.js

**Comment by fabiosantos87** [comment]
I already tried, just draw a line in the content and i need on the footer

**Comment by robertknecht** [comment]
The canvas object seems to increment off the page. Defining headers and footers with a function seems to fix this bug. I tried this in the playground and it gave me a repeating header with a line:
    header: function() {
        return [
            {
                "text": [
                    {
                        "text": "Some Text: ",
                        "style": "rightme"
                    },
                    {
                        "text": "Hello ",
                        "alignment": "right"
                    }
                ]
            },
            { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 0.5 }] }
        ];
    }

**Comment by liborm85** [comment]
Converting static header/footer to dynamic is improved by commit https://github.com/bpampuch/pdfmake/commit/ecab1d69f4b068b417c4c8db2e7e136fe2c0e50e.

**Comment by Sadi-1992** [comment]
Im using this with columns in the header and the line is getting lost on the second page. .___.

```
header: function() {
return [{
  columns: [
    {text: 'test', fontSize: 14, bold: true, color:'black'},
    {text: 'test:', fontSize: 12, bold: true, alignment:'right'}
  ], margin: [30, 10, 30, 0]
}, {
  columns: [
    {text: 'test', fontSize: 10, margin: [0, 5, 0, 0]},
    {text: 'test', fontSize: 10, alignment: 'right', margin: [0, 5, 0, 0]}
  ], margin: [30, 0, 30, 0]
}, {
  columns: [
    {text: 'test', fontSize: 10, margin: [0, 0]},
    {text: 'test', fontSize: 10, alignment: 'right', margin: [0, 0]}
  ], margin: [30, 0, 30, 0]
},{
  canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 1 }]
}]
}
```

**Comment by DivGolakiya** [comment]
i want to add line in body section
