### ISSUE TITLE
bold not work with italic

### ISSUE THREAD

**Issue by neylsongularte** [bpampuch/pdfmake#619]
``` javascript
var dd = {
    content: [
        {
            text:'Another paragraph',
            bold: true,
            italics: true
        }
    ]
}

```

**Comment by oscardz10** [comment]
I think it doesn't work because the default font doesn't come with a '**_boldItalics_**' file,
I used another font, but first I had to define it as:

`
var pdfContent= {};

pdfMake.fonts = {
            myFont: {
                normal:     'myFont.ttf',
                bold:       'myFont.ttf',
                italics:    'myFont.ttf',
                bolditalics:'myFont.ttf'
            }
}

pdfContent {
content: [ ],
defaultStyle: {
                      font: 'myFont',
                 },
......
}
`

**Comment by liborm85** [comment]
Answered.
