### ISSUE TITLE
pdf is not maked.

### ISSUE THREAD

**Issue by Matovidlo** [bpampuch/pdfmake#621]
Hello I have issue with a pdfmake on ftp server 
I have there a simple code which is written in your readme file

```
> <!doctype html>
> <html lang='en'>
> <head>
>   <meta charset='utf-8'>
>   <title>my first pdfmake example</title>
>   <script src='build/pdfmake.min.js'></script>
>   <script src='build/vfs_fonts.js'></script>
> </head>
> <body>
> <script>
> var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
> </script>
> </body>
> </html>
```

I tried both pdfMake.createPdf(docDefinition).open();
or download form but both of them are not working I had it inside the pdfmake folder so i used this script src above and also when i had it in folder outside i just simply use pdfmake/ extention in src for JS.

I am not sure how it is working just tried it on your website it worked nicely but on my website no way.

I downloaded pdfmake build it as you write in Readme file for client side and i am using it on my website is that a problem or how could i solve it .

I have whole directory uploaded on ftp server. Thanks for help

**Comment by liborm85** [comment]
You do not write what it returns an error. But it should work.
