### ISSUE TITLE
Turn on Compression by default

### ISSUE THREAD

**Issue by tneil** [bpampuch/pdfmake#622]
We have been using pdfmake on our report server using node.js.  In some scenarios we are running fairly large reports and found that changing the following line to have **compress: true** makes a major difference in the performance of our reports.

https://github.com/bpampuch/pdfmake/blob/master/src/printer.js#L93

Is there any chance this code could be updated to have compression turned on by default so that we don't need to modify the pdfmake source files as we continue to keep up with the latest versions?

Or if there is another way/configuration/property we can use to pass in the ability to override the **false** with **true** that would be great.

**Comment by padre629** [comment]
I've made this change (sadly/by now by editing unminified lib directly) and results are amazing, it's working as expected by now. 
Thanks :+1:

**Comment by patrickdet** [comment]
that would be really awesome to have

**Comment by liborm85** [comment]
Now compression is enabled by default (https://github.com/bpampuch/pdfmake/commit/d5c4eefb8b73519067ca89ec3d01d96eae254391). And can be disabled by option (https://github.com/bpampuch/pdfmake/commit/1cc6ea780e502da4543e7dc21dcbd54306edb1fe).

**Comment by liborm85** [comment]
New version released.

**Comment by vinitdholakia** [comment]
@liborm85 , this commit (d5c4eef) will always keep compression as 'true', even if option is 'false'.

false || true = true
true || true = true

**Comment by liborm85** [comment]
It was fixed in 0.1.34 by this commit https://github.com/bpampuch/pdfmake/commit/b5a86ddf57a0ada502c78b7e86b949854184b595.
