### ISSUE TITLE
Cannot read property 'TYPED_ARRAY_SUPPORT' of undefined

### ISSUE THREAD

**Issue by ghost** [bpampuch/pdfmake#624]
when I try to run my application I have only this issue

in line 248 of pdfmake.js

![captura de pantalla 2016-06-30 a las 13 37 22](https://cloud.githubusercontent.com/assets/17413476/16499886/d16198dc-3ec7-11e6-87f1-c25099bcffc7.png)

**Comment by codedge** [comment]
I am facing the same problem. Somebody found out what this is?

**Comment by alexandre-roitman** [comment]
Me too, will be glad if someone could assist..

**Comment by wesley100002001** [comment]
I'm facing this as well, so far I think it's related to webpack.
pdfmake.js is build by webpack and I'm building my webapp with webpack
I'm afraid that webpack has compiled pdfmake.js again to cause this error, I saw ppl discussing the 'TYPED_ARRAY_SUPPORT'
But still, trying to figure it out...

**Comment by wesley100002001** [comment]
I found this working using script-loader
https://github.com/bpampuch/pdfmake/issues/150#issuecomment-156143062

**Comment by liborm85** [comment]
Fixed in new release.

**Comment by omkadiri** [comment]
I just migrate to webpack and am using pdfmake v0.1.25. Am still can seeing this error, is there anything else i need to do beside importing 
import "pdfmake/build/pdfmake.js";
import "pdfmake/build/vfs_fonts.js"; or
import "pdfmake/build/pdfmake.min.js";
import "pdfmake/build/vfs_fonts.js";
