### ISSUE TITLE
On android device in chrome pdf not opening in a tab.

### ISSUE THREAD

**Issue by ciprianJijie** [bpampuch/pdfmake#626]
Hi, I use this library to export some data to pdf, on pc works great but on android devices in chrome when make  > pdfMake.createPdf(doc).open();
no opening in chrome in the same tab he offer me to save document but I no want to save current file.
Any solution?
Thanks!

**Comment by liborm85** [comment]
continue here: https://github.com/bpampuch/pdfmake/issues/679
