### ISSUE TITLE
qrCode

### ISSUE THREAD

**Issue by fabiosantos87** [bpampuch/pdfmake#627]
How i create a qrcode in my pdfmake?thanks in advance

**Comment by SEGEEK** [comment]
Have you tried putting the qrcode in an image and then inserting the image element?

**Comment by fabiosantos87** [comment]
Give me errors about the requires


2016-07-28 19:41 GMT+01:00 SEGEEK <notifications@github.com>:

**Comment by SEGEEK** [comment]
I am afraid without more information I can't give you any useful advise.  Is your website accessible through a particular URL where I can see the error messages?

If you get an error about require, I am assuming you are using the server code on the front end, or are not using browserify or something similar.

**Comment by fabiosantos87** [comment]
I am using the pdfmake in my local pc.


2016-07-29 19:33 GMT+01:00 SEGEEK <notifications@github.com>:

**Comment by SEGEEK** [comment]
Unfortunately there isn't much I can do to help without more information.  I would suggest trying to get an example of the problem up on something like https://plnkr.co/, I would be happy to look at it if you can get me a link to it so that I can see it.

**Comment by liborm85** [comment]
Simple example:
```js
var dd = {
  content: [
    { qr: 'test text' },
  ]
};
```

You can try here: http://pdfmake.org/playground.html
