### ISSUE TITLE
Custom fonts in client side

### ISSUE THREAD

**Issue by mpsbhat** [bpampuch/pdfmake#629]
Here is the wiki page explains about custom fonts. : https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side

But I didn't understand how to configure the same. I tried `grunt dump_dir` after installing grunt in ubuntu but it shows error command 'grunt' not found. BTW, i wanted to print Kannada fonts.

**Comment by mpsbhat** [comment]
Its working for few fonts after installing the grunt again. But `Lohith-kannada.ttf` font not working and gives blank spaces.

**Comment by liborm85** [comment]
Now you can use gulp on the same wiki link https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side
