### ISSUE TITLE
Server Side Styling Issue

### ISSUE THREAD

**Issue by PiyushRamuka** [bpampuch/pdfmake#632]
Hi - 

I am able to use pdfMake successfully without any styling on server side. However as soon as i add styling, it give me following error:

throw new Error('Not a supported font format or standard PDF font.');

I have included the "roboto" font and am using example code. No matter what I do, as soon as style bold or italics is added, it gives me the error message.

Any body else having this issue on server side? Any guidance what can be done here?

Regards,
Piyush

**Comment by Kuzmin** [comment]
Have you tried adding the bold and italic fonts, as in this comment: https://github.com/bpampuch/pdfmake/issues/381#issuecomment-189803814 ? 

I have server side rendering working properly with a configuration similar to that, with bold text. Let me know if it works!

**Comment by PiyushRamuka** [comment]
I tried that. Moved the fonts folder to the root of the nodejs application. The font & app.js have same location. However, I continue to see the issue. Is it possible you could provide sample (zipped) files which i can run on my side? That will be very helpful.

**Comment by Kuzmin** [comment]
It sounds like your paths are wrong in some way. Could you upload an example of your code in a repo on Github that I could look at to troubleshoot? Sorry but right now I don't really have enough time to produce my own minimal sample due to other projects that need finishing.. If you upload yours I'll be happy to help though!

**Comment by PiyushRamuka** [comment]
Finally it worked. My filed name was wrong. Instead ".tff" it was ".ttf". Sorry about the stupid typo error. Thank you all for help. Thanks Kuzmin :)

**Comment by Kuzmin** [comment]
Great to hear that it worked out!
