### ISSUE TITLE
colSpan in first row causes error or display problems

### ISSUE THREAD

**Issue by dgrice** [bpampuch/pdfmake#633]
This definition causes error:

{ content:[
        {
            table:{
                widths:['auto','auto'],
                body:[
                    [ {text:'header', colSpan:2} ],
                    ['abc','def']
                ]
            }
        }
    ]}

but, moving the first row with colSpan to second row, displays correctly;
{ content:[
        {
            table:{
                widths:['auto','auto'],
                body:[
                    ['abc','def'],
                    [ {text:'header', colSpan:2} ]
                ]
            }
        }
    ]}

**Comment by SEGEEK** [comment]
I ran into a similar issue, I believe you need an empty element in your first example try this instead 

```
{ 
  content:[
    {
      table:{
        widths:['auto','auto'],
        body:[
          [ {text:'header', colSpan:2}, {text:''} ], //note the second object with empty string for 'text'
          ['abc','def']
        ]
      }
    }
  ]
}
```

**Comment by liborm85** [comment]
They must be defined all cells of table. This is a feature (probably poor, but it is so.).

**Comment by giovanni-orciuolo** [comment]
I just wasted 2 hours of my time into this issue!!! Please refer back to this issue in the Playground so people don't lose their minds over this weird behaviour.

**Comment by NuteIla** [comment]
I just wasted 2 hours of my time into this issue as well! To elaborate a bit more on this, 
If say there are 5 columns and you want to span across 3 columns

**expected**: 
[
{text:"some random long text", colSpan:3},
"some other text",
"some other text2",
]
**what actually works:** 
[
{text:"some random long text", colSpan:3},
{text:""},
{text:""},
"some other text",
"some other text2",
]
