### ISSUE TITLE
Image on Header isn't repeating on every page

### ISSUE THREAD

**Issue by enr1c091** [bpampuch/pdfmake#635]
Hi all.

I am facing a small problem with my PDF header. I have an image logo in this header, but when my PDF is generated with multiple pages, the image only appears in the first page instead of spanning across all the pages, but if I place only a text node on my header instead of this image, it works just as it should.

I don't know if I'm missing something in my JSON, it also doesn't work on the Playground.

```
var dd = {
            header: {
                margin: 10,
                columns: [
                    {},
                    {
                        image: imagemLogo,
                        width: 40
                    }
                ]
            },
            content: [....]
}
```

Has anyone ever faced the same situation?

Thanks in advance.

Regards,
Enrico Bergamo

**Comment by cundiz** [comment]
Try to put your image at the first element of columns.

**Comment by enr1c091** [comment]
Thank you for your answer! It does work, but now I can't align the image at the right corner of the document, not even using the alignment property for the image. That was the reason I was using 2 columns and placing the image on the second one.

Have you ever gone through this issue?

**Comment by cundiz** [comment]
no. i think it was a bug in the framework.

**Comment by enr1c091** [comment]
Oh, well.. it's alright then. 

Thank you for your attention. I really appreciate it. :)
