### ISSUE TITLE
Update deprecated lodash-node@3.1.0:

### ISSUE THREAD

**Issue by codeuniquely** [bpampuch/pdfmake#637]
When using the package in a solution this warning is issued at build.

npm WARN deprecated lodash-node@3.1.0: 
This package has been discontinued in favor of lodash@^4.0.0.

pdfmake@0.1.18 
│ ├── lodash@3.1.0 
│ └── lodash-node@3.1.0   ******

**Comment by liborm85** [comment]
Dependencies updated by #759
