### ISSUE TITLE
Do not bundle lodash in built file, but add it as a bower dependency

### ISSUE THREAD

**Issue by thomaux** [bpampuch/pdfmake#638]
I can't state it anymore simpler than this, please do not bundle a lodash version in the build file. List it as a bower dependency in stead.

**Comment by prashantpawar** [comment]
@anzeo I recreated this issue at the new pdfmake repo.

**Comment by mbarakaja** [comment]
@prashantpawar, Where is located the new pdfmake repository?

**Comment by prashantpawar** [comment]
@mbarakaja It seems that the newer repository got merged into this one and then deleted. So this is the canonical repository.

**Comment by liborm85** [comment]
Lodash is no longer necessary, removed dependency by commit https://github.com/bpampuch/pdfmake/commit/211f4c83e86ec2b5097c919f1d60a877aa575a4b.
