### ISSUE TITLE
full example of pdfmake-basics example incl. filesaver-object to save a pdf on filesystem

### ISSUE THREAD

**Issue by rschaar** [bpampuch/pdfmake#639]
Hello,

i had tried to execute the project basics of example folder. at first, the project was sucessful executed with the three basic function open, print and download. now the problem is, how can i save a created pdf into a filesystem? my browser brings a error "require is undefinied". it is possible that a person can somehow demonstrate a working example with respect to the storage of a PDF in a filesystem?

best regards, robert

**Comment by liborm85** [comment]
Do you have any simple example of what you do?

**Comment by liborm85** [comment]
No reaction. No specific information.
