### ISSUE TITLE
Problem PDfmake server side

### ISSUE THREAD

**Issue by gladenko** [bpampuch/pdfmake#642]
If i creare a pdf with

doc = pdf.createPdfKitDocument(JSON.parse(jsonString))
  doc.pipe(pdf.fs.createWriteStream('s1.pdf'))
doc.end()

the pdf created is corret,

if i send pipe directly to response like this

doc.pipe(response)

i have a problem , a pdf is correctly formatted but is icomprensible 

Thank You in advance

[nnnnn.pdf](https://github.com/bpampuch/pdfmake/files/375283/nnnnn.pdf)

**Comment by kaivi** [comment]
I've had exactly the same problem, solved it by passing font paths to pdfPrinter:

```
const fonts = {
            Roboto: {
                normal: './src/server/helpers/fonts/Roboto-Regular.ttf',
                bold: './src/server/helpers/fonts/Roboto-Medium.ttf',
                italics: './src/server/helpers/fonts/Roboto-Italic.ttf',
                bolditalics: './src/server/helpers/fonts/Roboto-Italic.ttf'
            }
        }
const printer = new pdfPrinter(fonts)
```

**Comment by liborm85** [comment]
Answered.
