### ISSUE TITLE
Google Nato gujarati font 

### ISSUE THREAD

**Issue by ycpatel813** [bpampuch/pdfmake#643]
Hi I have small issue for custom fonts.
I am using Noto Sans Gujarati font to create pdf.
I am passing 'દૈનિક પત્રક' but it will convert into something differ which is displayed under image.

![pdfbug](https://cloud.githubusercontent.com/assets/8921044/17032082/18ddeb24-4f95-11e6-90d3-aee562a15840.png)

any one has idea about it?

Thanks

**Comment by daupawar** [comment]
@ycpatel813 i have tried for Marathi font and it works perfectly.
https://github.com/daupawar/MeteorAsyncPdfmake fork this and just replace font or send me your font i will check, also send your json

**Comment by liborm85** [comment]
Answered. No reaction.

**Comment by magheshbabu** [comment]
i tried to include malayalam 'Karthika' font...but it is not at all working.

Seems that this library does not support any font..even if it is embedded as said in the instructions. (https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side)

**Comment by magheshbabu** [comment]
It perfectly works fine with malayalam fonts
