### ISSUE TITLE
Rowspan gives "pdfmake.js: 15914 Uncaught TypeError: Cannot read property '_span' of undefined"

### ISSUE THREAD

**Issue by tiagoargolo** [bpampuch/pdfmake#644]
When I use rowspan at the first td, this error occurs: pdfmake.js:15914 Uncaught TypeError: Cannot read property '_span' of undefined

I could reproduce this error on playground:

	
```
table: {
								headerRows: 1,
								body: [
										[{ text: 'Header 1', style: 'tableHeader' }, { text: 'Header 2', style: 'tableHeader'}, { text: 'Header 3', style: 'tableHeader' }],
										[ 'Sample value 1', 'Sample value 2', 'Sample value 3' ],
										[ 'Sample value 1', 'Sample value 2', 'Sample value 3' ],
										[ {rowSpan: 2, text: 'Sample value 1'}, 'Sample value 2', 'Sample value 3' ],
										[ 'Sample value 2', 'Sample value 3' ],
										[ 'Sample value 1', 'Sample value 2', 'Sample value 3' ],
								]
						}
```

Looks like the same problem of #633 
Thank you in advance.

**Comment by SEGEEK** [comment]
You a missing an empty cell in the row after the rowSpan..

Try changing `[ 'Sample value 2', 'Sample value 3' ],` to `[ '', 'Sample value 2', 'Sample value 3' ],`

**Comment by tiagoargolo** [comment]
Thank you!

**Comment by thomaspatricksteven** [comment]
Thinks comment has helped me many times. Thank you!
