### ISSUE TITLE
How to display image inline ?

### ISSUE THREAD

**Issue by jbg77** [bpampuch/pdfmake#646]
Hello,

I'm making a html to pdfmake parser, I add a support for katex/mathjax, I render it in a canvas and I display it as an image in pdfmake.
But i want that the image doesn't jump line, I thought about table but i think it exists a more simple solution.

Thank in advance.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/358

**Comment by xuananpham93** [comment]
@jbg77 , did you have any solution? How do you render canvas?
