### ISSUE TITLE
Table auto page break not working if it contains an empty row

### ISSUE THREAD

**Issue by charobnjak32** [bpampuch/pdfmake#647]
I found that if a table has a row that has no content like  [ "", "", "" ] `( possible on tables with dynamic content) auto page break will not work. 

This will work: 

```
var body = [];
for(var i = 0; i < 100; i++) body.push(["1", "2"]);

var dd = {content: [{table: {body: body}}]}
```

But for example this will not work: 

```
var body = [["", ""]];
for(var i = 0; i < 100; i++) body.push(["1", "2"]);

var dd = {content: [{table: {body: body}}]}
```

The workaround that I found is replacing empty strings with  spaces `" "`

so this works just fine:

```
var body = [[" ", " "]];
for(var i = 0; i < 100; i++) body.push(["1", "2"]);

var dd = {content: [{table: {body: body}}]}
```

**Comment by igor-pomogai** [comment]
thank you! you saved me hours of work!

**Comment by Focushift** [comment]
+1
have same problem

**Comment by seanmurrin** [comment]
thank you!

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/176
