### ISSUE TITLE
italics and bold cannot be combined

### ISSUE THREAD

**Issue by tsiegleauq** [bpampuch/pdfmake#651]
when combining "italics: true, bold: true" the resulting text is italic only.

Sample code:

```
var dd = {
    content: [
        { 
            text: 'This is a header, using header style',
            italics: true,
            bold: true
        },
    ],
}
```

(add in playground for example)

**Comment by greyskymedia** [comment]
I would think that that is expected. When you're using a custom font you registered regular, italic and bold font files. If you wanted bold-italic, you'd simply registered a bold-italic font file and reference that one. 

I'm just stopping by to see if this would be better for my app than pdfkit though, hope I've been helpful.

**Comment by liborm85** [comment]
Probably this was a feature.
I updated Roboto font to latest and added bold+italic type. https://github.com/bpampuch/pdfmake/commit/3b940a8de78a1413d789848f30854a884dea07e1
