### ISSUE TITLE
Error 110 in Acrobat Reader

### ISSUE THREAD

**Issue by exequeryphil** [bpampuch/pdfmake#654]
I can successfully generate and download PDFs from localhost, and they open just fine in Acrobat Reader.  However, when I deploy to a remote server, download, and try to open the PDF in Acrobat, I get an "Error 110", though other PDF viewers seem to open the file just fine.  Anyone know why this might be happening?

**Comment by liborm85** [comment]
@exequeryphil You can try it in the latest version (0.1.22)?
