### ISSUE TITLE
Nesting margins in stacks fails to wrap on 2nd page

### ISSUE THREAD

**Issue by stangel** [bpampuch/pdfmake#655]
I've got some code that generates the document definition from HTML elements and styles, which produces some pretty complicated nested text.  I noticed that on the second page of my PDF output, the lines are running past the right-hand edge instead of wrapping properly.  I managed to boil it down to the following example:

```
<html>
  <head>
    <script src='build/pdfmake.min.js'></script>
    <script src='build/vfs_fonts.js'></script>
  </head>
  <body>
    <script>
      var docDefinition = {
        content: [
          { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
          { margin: [15,100,0,0],
            stack:  [
              { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
              { margin: [15,100,0,0],
                stack:  [
                  { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
                  { margin: [15,100,0,0],
                    stack:  [
                      { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
                      { margin: [15,100,0,0],
                        stack:  [
                          { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
                          { margin: [15,100,0,0],
                            stack:  [
                              { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
                              { margin: [15,100,0,0],
                                stack:  [
                                  { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins'},
                                  { margin: [15,100,0,0],
                                    stack:  [
                                      { text: 'This line is longer than the page width but will wrap automatically so nothing is lost unless there is nested stacks of margins' }
                                    ]
                                  }
                                ]
                              }
                            ]
                          }
                        ]
                      }
                    ]
                  }
                ]
              }
            ]
          }
        ]
      };

      pdfMake.createPdf(docDefinition).open();
    </script>
  </body>
</html>
```

Here's what the output looks like on my system:
[pdfmake_margin_test.pdf](https://github.com/bpampuch/pdfmake/files/389447/pdfmake_margin_test.pdf)

**Comment by KendallSpackman** [comment]
I'm having a similar problem. Here's my example:
```
var dd = {
    content: [
		[
			[
				{
					text: "Section 1",
					style: "sectionLabel",
					margin: [0,0,0,0]
				},
				{
					text: [
						{text: "Filler: ", style: "questionLabel" },
						{text: "filler", style: "response"}
					],
					margin: [20, 100, 0, 0]
				},
				{
					text: [
						{text: "Filler: ", style: "questionLabel" },
						{text: "filler", style: "response"}
					],
					margin: [20, 100, 0, 0]
				},
				{
					text: [
						{text: "Filler: ", style: "questionLabel" },
						{text: "filler", style: "response"}
					],
					margin: [20, 100, 0, 0]
				}
			],
			[
				{
					text: "Section 2",
					style: "sectionLabel",
					margin: [0,100,0,0]
				},
				{
					text: [
						{text: "Filler: ", style: "questionLabel" },
						{text: "filler", style: "response"}
					],
					margin: [20, 100, 0, 0]
				},
				{
					text: [
						{text: "Filler: ", style: "questionLabel" },
						{text: "filler", style: "response"}
					],
					margin: [20, 100, 0, 0]
				},
				{
					text: [
						{text: "A much longer section of text which shows that the text wrapping does not: ", style: "questionLabel"},
						{text: "work", style: "response"}
					],
					margin: [40, 0, 0, 0]
				},
				{
					text: [
						{text: "A much longer section of text which shows that the text wrapping does not: ", style: "questionLabel"},
						{text: "work", style: "response"}
					],
					margin: [40, 0, 0, 0]
				},
				{
					text: [
						{text: "A much longer section of text which shows that the text wrapping does not: ", style: "questionLabel"},
						{text: "work", style: "response"}
					],
					margin: [40, 0, 0, 0]
				}
			]
		]
	],
	styles: {
		sectionLabel: {
			fontSize: 15,
			bold: true
		},
		questionLabel: {
			fontSize: 15,
			bold: true
		},
		response: {
			fontSize: 15
		}
	}
}
```

And the generated document
[sample.pdf](https://github.com/bpampuch/pdfmake/files/443334/sample.pdf)

It seemed to have something to do with the margin property of the first element on the second page, but I wasn't sure what the connection was. This document is being generated dynamically, so I don't know when there will be a new page necessarily, and I'm indenting lines in a hierarchy, so every element has a margin property with some kind of left indent.

**Comment by tomph** [comment]
Did you guys figure out a solution to this?  I have something similar where a dynamically generated PDF does not wrap on the second (or more) pages.

**Comment by tomph** [comment]
It seems to have some relation to fontSize.  (try toggling the bottom fontSize from 10 to 20)

see http://pdfmake.org/playground.html

with following data:

// playground requires you to assign document definition to a variable called dd

var dd = {
	content: [
		{ 
			text: 'This is a header, using header style', 
			style: 'header' 
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam.\n\n',
		{
			text: 'Subheader 1 - using subheader style',
			style: 'subheader'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
		{
			text: 'Subheader 2 - using subheader style',
			style: 'subheader'
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.',
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
		{ 
			text: 'It is possible to apply multiple styles, by passing an array. This paragraph uses two styles: quote and small. When multiple styles are provided, they are evaluated in the specified order which is important in case they define the same properties', 
			style: ['quote', 'small'] 
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
		{ 
			text: 'It is possible to apply multiple styles, by passing an array. This paragraph uses two styles: quote and small. When multiple styles are provided, they are evaluated in the specified order which is important in case they define the same properties', 
			style: ['quote', 'small'] 
		},
		'Lorem ipsum dolor sit amet, consectetur adipisicing elit. Confectum ponit legam, perferendis nomine miserum, animi. Moveat nesciunt triari naturam posset, eveniunt specie deorsus efficiat sermone instituendarum fuisse veniat, eademque mutat debeo. Delectet plerique protervi diogenem dixerit logikh levius probabo adipiscuntur afficitur, factis magistra inprobitatem aliquo andriam obiecta, religionis, imitarentur studiis quam, clamat intereant vulgo admonitionem operis iudex stabilitas vacillare scriptum nixam, reperiri inveniri maestitiam istius eaque dissentias idcirco gravis, refert suscipiet recte sapiens oportet ipsam terentianus, perpauca sedatio aliena video.\n\n',
		{ 
			text: 'It is possible to apply multiple styles, by passing an array. This paragraph uses two styles: quote and small. When multiple styles are provided, they are evaluated in the specified order which is important in case they define the same properties', 
			style: ['quote', 'small'] 
		}
		
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true
		},
		subheader: {
			fontSize: 15,
			bold: true
		},
		quote: {
			italics: true,
			margin:[180,0,0,0]
		},
		small: {
			fontSize: 10
		}
	}
}

**Comment by liborm85** [comment]
Fixed by commit https://github.com/bpampuch/pdfmake/commit/287362a1b4763ee99fc0bb04061e12af9ee9e6d9
