### ISSUE TITLE
Get X,Y position in Pdfmake?

### ISSUE THREAD

**Issue by f4th4n** [bpampuch/pdfmake#657]
How to get the abscissa and ordinate of the current position?

**Comment by manuelph** [comment]
+1

**Comment by v3yr0n** [comment]
+1

**Comment by v3yr0n** [comment]
Any idea on how this can be done? I need to position a canvas type path on the document, relative to another element. @bpampuch is it possible?

**Comment by liborm85** [comment]
Can not be get X, Y of current positon.

Relative positioning can be used, see example - [relative.js](https://github.com/bpampuch/pdfmake/blob/master/examples/relative.js).
