### ISSUE TITLE
PDF not generating for huge array size

### ISSUE THREAD

**Issue by shailesh9** [bpampuch/pdfmake#658]
Pdf is not generating for 

 **docDefinition**

 content size more than **600**

**Comment by daniel-gwilt** [comment]
Hello Shailesh,

I have the exact same issue.  I'm currently working around it by splitting up the array into chunks of 500 items and then sending each chunk to a web worker to be converted into a PDF.  Although, I currently have the problem of recombining the chunks into a single PDF file again.  If anyone has a better solution please let us know.

Regards,
Dan

**Comment by mevillep** [comment]
Hi, How do i interpolate array of objects to  get multiple pdfs printed.. I have a pdf structure made, and want to generate multiple pdfs on multiple objects coming in.

**Comment by daniel-gwilt** [comment]
Hi Mevillep,

I did it by splitting up a table array into blocks or chunks of 500, wrapping each chunk with the PDF make JSON object and calling PDF make on each one.  You could do something similar.  Just call "createPdf()" for each chunk.  Hope this helps.

Good Luck,
Dan

**Comment by liborm85** [comment]
Here https://github.com/bpampuch/pdfmake/issues/947#issuecomment-293494738 I created table with 10 000 rows without problems.

Where is the problem?
Any sample?

**Comment by liborm85** [comment]
Can not be simulated.
