### ISSUE TITLE
on IOS (ipad or iphone), cannot create PDF with more than 30-40 pages (safari/chrome/firefox crashes) 

### ISSUE THREAD

**Issue by bbj** [bpampuch/pdfmake#661]
Hi,

on IOS (ipad or iphone), cannot create PDF with more than 30-40 pages (safari/chrome/firefox crashes and page is reloaded).
I can open the same report on windows or android without any problems.
It is also crashing when opening a 20 pages report several times (2 or 3 times).
Did anyone tried more than 40 pages on IOS?

The code I am calling to generate the PDF file is:
THE CRASH is occuring into pdf.getBuffer, before calling the callback.

var pdf = pdfMake.createPdf(pdfmakeData);
pdf.getBuffer(function(buffer) {
         var blob;
         try {
            blob = new Blob([buffer], {type: 'application/pdf'});
         } catch (e) {
            // Old browser which can't handle it without making it an byte array (ie10)
            if (e.name == "InvalidStateError") {
               var byteArray = new Uint8Array(buffer);
               blob = new Blob([byteArray.buffer], { type: 'application/pdf' });
            }
         }
         if (blob) {
            var windowURL = window.URL || window.webkitURL;
            var blobUrl = windowURL.createObjectURL(blob);
         }
}

Thanks,
Bruno

**Comment by liborm85** [comment]
Fixed in new release (0.1.22).
