### ISSUE TITLE
Any support for Arabic characters ?

### ISSUE THREAD

**Issue by amrdruid** [bpampuch/pdfmake#662]
After downloading a pdf with arabic characters they seem to be just invisible, any solution or support for Arabic characters ?

**Comment by marc-rutkowski** [comment]
Never try it by myself but maybe do you need to include some custom font?
See explanations here: https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side

Font that support arabic chars can be found here : https://fonts.google.com/?subset=arabic

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/315
