### ISSUE TITLE
PDFs are very large in Firefox

### ISSUE THREAD

**Issue by EpicWolverine** [bpampuch/pdfmake#666]
I have an application that exports PDFs. I've noticed that when these are generated in Firefox, they are much larger in file size than they are when exported in Chrome or IE. This is so bad that it can slow down the browser when opened with the built in PDF.js (see the size of test1).
![pdf_testing_2016-08-09_16-11-41](https://cloud.githubusercontent.com/assets/2897970/17534702/755b5c16-5e58-11e6-8761-a9704f8ab2d1.png)
Turning on compression (#609 and #622) actually made the file sizes worse so I left that off. I've poked around with comparing the resulting base64 data and it looks like a lot of junk data is being written for some reason. There are lots of long sections of repeated "AA" which [converts to ](https://duckduckgo.com/?q=base64+decode+AA&t=ffab&ia=answer) `&#0;`. Another section I decoded was full of [`&#xFFFD;` characters](http://www.fileformat.info/info/unicode/char/fffd/index.htm) with data mixed in between. While you can't just grab sections of base64 and expect a PDF out of it, a similar section of base64 from Chrome decodes to actual numbers and other data.

I'm not sure how to go about tackling this issue or what other details you may need to help me with this. Let me know if you need to know more. I do have another (possibly related) issue (#665) in the same application so that may be worth looking at.

**Comment by EpicWolverine** [comment]
It seems this problem is limited to Firefox 48, as Firefox 47 works as expected.
![pdf_testing_2016-08-10_11-41-26](https://cloud.githubusercontent.com/assets/2897970/17560235/4a127570-5eef-11e6-8bc3-f0de91052409.png)

**Comment by liborm85** [comment]
Can you try it with new version pdfmake (0.1.22) and with lastest Firefox?

**Comment by EpicWolverine** [comment]
Sorry for not responding. Long story short, the job this was for is seasonal and I was unable to test this until now. However, I can confirm that it does work as expected with the latest version of pdfmake (0.1.29) and Firefox (53.0.3).

Thank you for looking at my issue and working on this awesome project.
