### ISSUE TITLE
Content goes to second column and then to next page

### ISSUE THREAD

**Issue by robertknecht** [bpampuch/pdfmake#669]
We're running into a major roadblock with this. We need a two-column directory where text goes down to the bottom of the first column, then down the second column, and then on to the next page.

This is functionality that we really need.

Is there a way to use hooks or something to track how far down the page the content has gone and create a function to break to the next column when at the bottom of the first.

We could count lines, but that would be hard to maintain and adjust appearance for, and there's not way of telling when an item will take more than one line.

The addition of column breaks or any ideas how we could implement this on our own using the pdfMake framework would be greatly appreciated.
#614 #604

Otherwise, I'm wondering if there is a way to track how many pages the content has taken before actually generating the PDF, so that we could create two pages of content, then manipulate the array of content into two columns for one page.

**Comment by robertknecht** [comment]
Since there doesn't seem to be a way to make a block of text automatically overflow from one column to the next, it would be useful to be able to use functions to dynamically control the content of the PDF the same we can with the Header and Footer. That way I could put in place a system to track pages and correctly rearrange the data into columns.

**Comment by RobertPrediger** [comment]
+1

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/604
