### ISSUE TITLE
Header text increment margins on every page.

### ISSUE THREAD

**Issue by samavedulark** [bpampuch/pdfmake#671]
Header is incrementing on every page.
var dd = {
    content: [
        'Here goes your content',
        {text: 'More content', pageBreak:'after'},
        'Other content',
        {text: 'More Content', pageBreak:'after'},
        'Other content'],
header: [
    {
      "text": [
        {
          "text": "Some Text: ",
          "style": "rightme"
        },
        {
          "text": "Hello ",
          "alignment": "right"
        }
      ]
    },
    { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 0.5 }] }
  ]
}

**Comment by robertknecht** [comment]
When you set the header with a function that defines it's data structure, it seems to fix this problem.
For example:
    header: function() {
        return [
            {
                "text": [
                    {
                        "text": "Some Text: ",
                        "style": "rightme"
                    },
                    {
                        "text": "Hello ",
                        "alignment": "right"
                    }
                ]
            },
            { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 595-10, y2: 10, lineWidth: 0.5 }] }
        ];
    }

**Comment by samavedulark** [comment]
Thanks, that did work. But will it be fixed.

**Comment by liborm85** [comment]
Header must be defined as function.

**Comment by liborm85** [comment]
Converting static header/footer to dynamic is improved by commit https://github.com/bpampuch/pdfmake/commit/ecab1d69f4b068b417c4c8db2e7e136fe2c0e50e.
