### ISSUE TITLE
multiple fonts in a PDF

### ISSUE THREAD

**Issue by Darbiol** [bpampuch/pdfmake#673]
is there a way to apply different fonts in a single PDF creation?
sample:

```
{
   stack : [
      { 
         text : this is a test text
         fontStyle  : 'roboto',
         italic : true
      }, { 
         text : this is another test text
         fontStyle : 'open-sans',
         bold : true
      }  
  ]
}
```

or something close to that?

**Comment by Darbiol** [comment]
[Closing this issue]
sorry just figured out how to do this. just incase anyone is looking for this i'll just leave an example on how to do this.

as it is shown in [setting up custom fonts](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side) we add any new font here with a corresponding key

```
pdfmake.fonts = {
   'Roboto' : {
      normal: 'Roboto-Regular.ttf',
      bold: 'Roboto-Medium.ttf',
      italics: 'Roboto-Italic.ttf',
      bolditalics: 'Roboto-Italic.ttf'
   },

   'OpenSans' : {
      normal: 'OpenSans-Regular.ttf',
      bold: 'OpenSans-Medium.ttf',
      italics: 'OpenSans-Italic.ttf',
      bolditalics: 'OpenSans-Italic.ttf'
   }
   
}
```

So now it can be used as

```
{
   stack : [
      { 
         text : this is a test text
         font  : 'OpenSans',
         italic : true
      }, { 
         text : this is another test text
         font : 'Roboto',
         bold : true
      }  
  ]
}
```

**Comment by solidet** [comment]
so , we include two vfs_fonts.js or what ??? or we create one vfs_fonts.js  containing two fonts?

**Comment by liborm85** [comment]
1. copy all font files to folder `examples/fonts/` ( + remove unnecessary files )
2. run `gulp buildFonts`
3. it creates a new file `build/vfs_fonts.js`

**Comment by rosiejaneenomar** [comment]
@Darbiol hi, where did you put the font files in your project? by the way, im using angular 6,

my code is this

const docDefinition = this.createDocumentDefinition(new Date(), headers, tblData);
    pdfMake.vfs = pdfFonts.pdfMake.vfs;
    pdfMake.fonts = {
      noto: {
        normal: 'NotoSansKannada-Regular.ttf',
        bold: 'NotoSansKannada-Bold.ttf',
        italics: 'NotoSansKannada-Black.ttf',
      }
    };

the fonts are located under assets folder:

assets/fonts/NotoSansKannada-Regular.ttf

but i got an error:

ERROR Error: Uncaught (in promise): File 'NotoSansKannada-Regular.ttf' not found in virtual file system
    at resolvePromise (zone.js:831)

is there something that i need to change?

**Comment by quantumcat1** [comment]
> 
> 
> @Darbiol hi, where did you put the font files in your project? by the way, im using angular 6,
> 
> my code is this
> 
> const docDefinition = this.createDocumentDefinition(new Date(), headers, tblData);
> pdfMake.vfs = pdfFonts.pdfMake.vfs;
> pdfMake.fonts = {
> noto: {
> normal: 'NotoSansKannada-Regular.ttf',
> bold: 'NotoSansKannada-Bold.ttf',
> italics: 'NotoSansKannada-Black.ttf',
> }
> };
> 
> the fonts are located under assets folder:
> 
> assets/fonts/NotoSansKannada-Regular.ttf
> 
> but i got an error:
> 
> ERROR Error: Uncaught (in promise): File 'NotoSansKannada-Regular.ttf' not found in virtual file system
> at resolvePromise (zone.js:831)
> 
> is there something that i need to change?

Try this https://github.com/bpampuch/pdfmake/issues/864#issuecomment-298341323

**Comment by NithMario** [comment]
@quantumcat1 I have this problem too if you are already done with this share me please

**Comment by Gefyaqiilah** [comment]
in my case i just create some object like in pdfmake/build/vfs_fonts.js, example:

const base64fonts = {
'Montserrat-Light': 'import your spesific.ttf file to base64',
'Montserrat-LightItalic': 'import your spesific.ttf file to base64',
etc...
};

***important the keys on base64fonts will be use on code below:**

<img width="432" alt="Screen Shot 2021-11-14 at 9 55 53 AM" src="https://user-images.githubusercontent.com/54069791/141665678-e3ffe8a3-431c-46d9-95f8-3faacea3722f.png">

 assign to pdf.vfs and pdf.fonts
<img width="280" alt="Screen Shot 2021-11-14 at 9 58 13 AM" src="https://user-images.githubusercontent.com/54069791/141665739-a2400277-6bac-45f7-b972-fdff3b0b00d8.png">

and use the value that is in the pdf.fonts keys (on the first image):
<img width="253" alt="Screen Shot 2021-11-14 at 10 01 09 AM" src="https://user-images.githubusercontent.com/54069791/141665771-a7327a9b-ee0b-4db4-9ab8-e513ec6afc52.png">

that's it, sorry for my broken english :)
