### ISSUE TITLE
Text inside canvas

### ISSUE THREAD

**Issue by Purush0th** [bpampuch/pdfmake#674]
I want to print text with in a rectangular box. I am seeing canvas option (type: 'rect') which lets us to draw rectangles.

``` javascript
        {
            canvas: [
                {
                    type: 'rect',
                    x: 1,
                    y: 10,
                    w: 250,
                    h: 100,
                    r: 4,
                    lineColor: '#000',
                }
                               ]
              }
```

How to write text inside it? Or is the anyway to specify coordinates for text?

**Comment by pemaxim** [comment]
+1

**Comment by Focushift** [comment]
try this custom function from reply №5 https://github.com/bpampuch/pdfmake/issues/74

**Comment by ottigerb** [comment]
# +1

Something like this - inside `"canvas": []` - would be great!

```
                   {
                        type: "text",
                        x: 0,
                        y: 0,
                        font: '36pt Arial',
                        fillStyle: '#3F51B5',
                        text: 'My TEXT'
                    }
```

Any idea for a "workaround"? custom function from reply №5 #74 does not help.  Just have to print some Numbers & Text inside a canvas. Basically to create some "charts".

**Comment by franbueno** [comment]
+1

**Comment by liborm85** [comment]
Use `absolutePosition`, see example: https://github.com/bpampuch/pdfmake/blob/master/examples/absolute.js
