### ISSUE TITLE
Dynamic data - own names of the columns

### ISSUE THREAD

**Issue by samurai-jack** [bpampuch/pdfmake#675]
Hi I have a question to the code that you put at this link
https://github.com/bpampuch/pdfmake/issues/24#issuecomment-42662042

In this code, the name of table columns must have the name of the same name as the "key " object ( [ 'name' , ' age '] ) . Is it possible to give your own ( other ) names of the columns in the generated PDF -ie table

**Comment by liborm85** [comment]
Yes.
Comment #24 (comment) is only as example, you can customize in any way according to your requirements. For example, you can add the parameter with titles.
