### ISSUE TITLE
Print not working in safari

### ISSUE THREAD

**Issue by BalachanderJ** [bpampuch/pdfmake#678]
Hi, 
Am trying to create a PDF and directly print it instead of opening it. This seems to be working fine in Chrome and Mozilla Firefox. But in Safari, I don't see it working. Am using safari version 9.1.2 (10601.7.7). PdfMake playground too doesn't seem to be working.

Please help.

**Comment by saormart** [comment]
I'm using this library to build a PDF file locally with Intel XDK (cordova based) hybrid app for iOS (iPhone / iPad).
It was working fine before the new release of iOS 10 ! Is there any way to fix it ?

**Comment by liborm85** [comment]
reference: https://github.com/bpampuch/pdfmake/issues/800

**Comment by liborm85** [comment]
duplicate https://github.com/bpampuch/pdfmake/issues/414
