### ISSUE TITLE
How can i set filename to a "open" Option?

### ISSUE THREAD

**Issue by jc2** [bpampuch/pdfmake#680]
When i try to download a file opened, the browser set a default name (download.pdf).
Is posible to change that?

**Comment by aswitahidayat** [comment]
try this:
`pdfMake.createPdf(docDefinition).download('download.pdf');`

**Comment by jc2** [comment]
yea, with the option "download" i can set a filename, but i need to do the same with the option "open".

**Comment by aswitahidayat** [comment]
You can add title to the document definition

`var docDefinition = {
  info: {
    title: 'awesome Document',
    author: 'john doe',
    subject: 'subject of document',
    keywords: 'keywords for document',
  },
  content:  'This is an sample PDF printed with pdfMake' 
}`

**Comment by daniel-van-niekerk** [comment]
Setting the title worked for me, thanks.

**Comment by miltador** [comment]
I will close this issue cause the question is answered.

**Comment by moffsugita** [comment]
It can't set download file name....

![2019-01-24 18 05 14](https://user-images.githubusercontent.com/35673132/51667122-a31b2780-2002-11e9-9a3b-bcd185ee6a30.png)
I pushed the download button of it.

**Comment by moffsugita** [comment]
https://stackoverflow.com/questions/37894898/issue-on-generate-pdf-with-custom-name-using-pdfmake-and-nodejs

**Comment by moffsugita** [comment]
https://stackoverflow.com/questions/44349001/open-pdf-in-default-app-using-pdfmake

**Comment by moffsugita** [comment]
https://stackoverflow.com/questions/41947735/custom-name-for-blob-url

**Comment by prabhugochild14** [comment]
@moffsugita Hi.
did you get any solution for changing name in pdf make while pdfmake.open();

**Comment by Kvarkas** [comment]
hello, also looking for a solution about how to open('filename')

**Comment by Yaroslav-Zaika** [comment]
> hello, also looking for a solution about how to pdfmake.open('filename')
You have found?

**Comment by diegodario88** [comment]
me too

**Comment by Gil-Epshtain** [comment]
This issue isn't solved, and it's need to be reopened. Currently we can:
1. Use the download method and pass it a file name `pdfMake.createPdf(docDefinition).download('download.pdf');`
2. Set in the docDefinition the `info.title` option and the open the document, `let docDefinition = {  info: {  title: 'MY_TITLE' }  ... }`. This will set the title in the browser title, but when clicking download via the browser interface a default name will be used.

Please reopen this issue, and add an option to set the file name via the open method.

**Comment by liborm85** [comment]
Browsers do not support it...

**Comment by Lexiebkm** [comment]
@liborm85 I think you are right; browsers do not support providing a custom file name when opening pdf using blob in the browser. So, either we are forced to use download method to provide custom filename, or just tell our user to rename the file when they click the browser interface to download the opened pdf output.

**Comment by marvinero1** [comment]
La respuesta de @Gil-Epshtain funciona para el open().
