### ISSUE TITLE
Underlined Text?

### ISSUE THREAD

**Issue by Tanshaydar** [bpampuch/pdfmake#69]
Hi,
Is it possible to have an underlined text?
I tried underline:true, underlines:true and so on, but I couldn't get anything to work.
I can think of a workaround, having a lower border of a table drawn, but that would not work on a paragraph of a text.

Regards, Tansel.

**Comment by MikeAski** [comment]
See https://github.com/bpampuch/pdfmake/issues/1061#issuecomment-314357279
