### ISSUE TITLE
Drawing the line relative to the table

### ISSUE THREAD

**Issue by sanpraka** [bpampuch/pdfmake#691]
I have one custom requirement.Would like to know whether it is possible or not?

I have a dynamic table getting printed. It can have 1,2,3 ,4 ........rows..I am able to print this table correctly.

I am adding disclaimer section below this table by drawing the line.Text will be below the line.
I have set the line and text when the rows are 3 with margin:[0,200,0,0]

Problem is when the table rows are 1, line and text moves up.
when the table rows are 2, line and text moves up little.
when the table rows are 3, line and text is correct according to margin.
when the table rows are 4, line and text moves down to second page.

Question is How can i set the line relative to the table?any suggestions?I do not know how many rows does the table has?

Appreciate your help in this regard?

**Comment by liborm85** [comment]
Please add simple example runnable on http://pdfmake.org/playground.html .
