### ISSUE TITLE
Add fillColor to cell with nested table

### ISSUE THREAD

**Issue by bfailing** [bpampuch/pdfmake#694]
Looking at the Playground tables example "A simple table with nested elements," I would like to change the color of the cell which contains the text "or a nested table" and the 3x3 nested table.  The new color (e.g., green instead of white) should be displayed behind the text "or a nested table" and also behind the nested table.  Is this possible?

**Comment by liborm85** [comment]
Example with fillColor:
```
var dd = {
	content: [
		{
			table: {
				body: [
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}],
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}],					
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}],
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}]
				]
			}
		}
	]
	
}
```
