### ISSUE TITLE
Style enumeration?

### ISSUE THREAD

**Issue by pvencill** [bpampuch/pdfmake#697]
I really like this project, and I think you've done a great job.  It'd be very helpful if you could include some reference of what style declarations are supported in the documentation, as it's not completely intuitive as to which CSS-style attributes you allow (e.g. bold) and which you don't (e.g. backgroundColor).

**Comment by DaveSanders** [comment]
As I explore this project this morning, I'm wondering if there is a doc written somewhere that outlines the entire DDL?  There should be some SDK docs basically that go beyond the examples.

Unless I'm just not seeing them.

**Comment by liborm85** [comment]
Will be included in the new documentation. Issue: https://github.com/bpampuch/pdfmake/issues/1238
