### ISSUE TITLE
open in same window

### ISSUE THREAD

**Issue by rwu2359** [bpampuch/pdfmake#70]
I have an interesting use case (a web viewer inside FileMaker) in which I need to show the pdf in the same browser window and the current method using .open() to trigger the creation is not working at all.

Is it possible to just write the application/pdf:base64 direct into the same window??

btw this a great tool, but some standalone documentation and examples focussed on standalone browser use is a real must...

**Comment by Balaraju1** [comment]
pdf file open same browser that file will be open small size with scroll bar.
what can i do?
