### ISSUE TITLE
Problems with FontAwesome

### ISSUE THREAD

**Issue by hsunami21** [bpampuch/pdfmake#701]
Hello,

I'm having trouble getting FontAwesome fonts to show up on the PDF. I have followed the steps listed [here](http://stackoverflow.com/questions/32837042/use-glyphicons-or-font-awesome-in-pdfmake-prints) as well as [here](https://github.com/bpampuch/pdfmake/issues/610) but to no avail. I have created the vfs_fonts.js using Grunt and have changed the base64 for FontAwesome. I have also created the new font using `pdfMake.font`.

The issue I'm stuck at is when I run my generatePDF method, it says that it `"Cannot read property 'length' of null"` at `for (var i = 0; i < rules.length; i++) {`. So, I logged the stylesheet object and it shows that the `cssRules` and `rules` properties are both `null`.

Any help would be appreciated!

**Comment by filipejoe** [comment]
i have the same issue

Any Ideas, or solutions? I would really appreciate it :)

**Comment by liborm85** [comment]
see https://github.com/bpampuch/pdfmake/issues/948
