### ISSUE TITLE
Cell Borders being displayed after page break when using colSpan/rowSpan in repeating header

### ISSUE THREAD

**Issue by mandtcampos** [bpampuch/pdfmake#705]
First of all, great library!!!

My issue is: cell borders are being displayed after page break when using colSpan/rowSpan in repeating header

First Page:
![image](https://cloud.githubusercontent.com/assets/20407706/18690533/0d72d058-7f54-11e6-9add-e8c588babe67.png)

Second Page:
![image](https://cloud.githubusercontent.com/assets/20407706/18690515/0253fa3a-7f54-11e6-907e-599ee42a4c29.png)

Not sure if this is an issue in the library or an issue with my code, has anyone else had an issue like this? Do you know what to look for?

**Comment by gerickson808** [comment]
This is an issue in the library, I have the same problem.

**Comment by Focushift** [comment]
+1

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/247
