### ISSUE TITLE
Table row element for null and boolean values breaks

### ISSUE THREAD

**Issue by zam6ak** [bpampuch/pdfmake#706]
I have noticed that table rows must be pretty much only text.
Often, I get values from DB and they are JSON "array of arrays" that are valid JSON elements containing text, numbers, boolean values and sometimes nulls...

For example:

```
[
 ["row with null", null, "2016-07-01T09:30:00-04:00"],                   
 ["row with number", 12345, "2016-07-01T09:30:00-04:00"],                 
 ["row with boolean", true, "Sample value 2-3"]                          
]
```

However, using these directly as table body does not work..
Here are some errors I am getting

```
"body": [
  [{"text": "Header 1", "style": "tableHeader" },{"text": "Header 2", "style": "tableHeader"}, {"text": "Header 3", "style": "tableHeader"}],
  ["Sample value 1-1", "Sample value 1-2", "Sample value 1-3"],
  ["Sample value 2-1", "Sample value 2-2", "Sample value 2-3"],
  //["row with boolean", true, "Sample value 2-3"],                          // "Cannot create property '_margin' on boolean 'true'"
  ["row with boolean", {"text":true}, "Sample value 2-3"],
  //["row with null", null, "2016-07-01T09:30:00-04:00"],                    // "Cannot read property '_span' of null"
  //["row with null", {"text":null}, "2016-07-01T09:30:00-04:00"],           // "Cannot read property 'length' of null"
  //["row with number", 12345, "2016-07-01T09:30:00-04:00"],                 // "Cannot create property '_margin' on number '12345'"
  ["row with number", {"text":12345}, "2016-07-01T09:30:00-04:00"]
]
```

I tried wrapping each into `{"text": val}` but that did not work...
Is my only option to take the DB data and run it through some transformation function that will 
- replace all numbers with their text equivalents
- replace all booleans with some custom string (e.g. "true", "yes", "false", "no")
- replace all nulls with some custom text string (e.g "", "n/a")

Is there a way to just feed the data to table definition and have it work?

**Comment by liborm85** [comment]
This added https://github.com/bpampuch/pdfmake/commit/d10f4bba6740a1cfbe727abe35bda381a39fd61a cast value to text, if is used `{"text": value}` syntax.

**Comment by liborm85** [comment]
Casting to string improved by https://github.com/bpampuch/pdfmake/commit/93f106e14bee5f3d7c9332fc6799c30d4b34f982 for values without text element.
