### ISSUE TITLE
Slow generation for large PDFs (server side)

### ISSUE THREAD

**Issue by zam6ak** [bpampuch/pdfmake#707]
I am experiencing same slowness factors as described in #280 ...
Is there a way to fix or apply the patch to speed up the PDF generation on server side (Node.js + Express)...

My use case is a PDF with with a table ( 6 columns) which I am piping directly to response.
I timed the DB query, PDF generation and response output.
The only variable that increases as the number of rows increase is PDF generation.
And speed increases in non linear fashion. 
100 rows - 635 ms
500 rows - almost 5 seconds
1000 rows - 1.2 minutes !!!

Any help would be appreciated!

Thanks

**Comment by mayurtanna** [comment]
Hi,

Any update on this ? Any alternate solutions ?

Thanks.

**Comment by jchabot86** [comment]
Any update on this?

Thanks,

**Comment by liborm85** [comment]
@jchabot86 @mayurtanna @zam6ak
Hi. I tried to fix performance, details in comment https://github.com/bpampuch/pdfmake/issues/280#issuecomment-267255835
Can you try it?

**Comment by NikitaBonachev** [comment]
For me your solution works very good (56 pages in less than 40 seconds).

**Comment by jchabot86** [comment]
Please excuse my inexperience with this, but how do I try your fix?  I typically just do npm installs, but do I need to tell npm to pull from a specific git commit?

Also, fyi, the guilty party in my situation seemed to be the while loop calling addPageBreaksIfNecessary in the layoutBuilder.js.  If I comment out that line, I still get the same PDF at a MUCH faster rate.  I get a 150 page pdf in seconds.   (I know manually editing node modules is not a good approach but wanted to test)

**Comment by liborm85** [comment]
@jchabot86 New version 0.1.22 released, you try to install by npm.
