### ISSUE TITLE
Doesn't work on Windows 10 Mobile

### ISSUE THREAD

**Issue by ckincincy** [bpampuch/pdfmake#708]
Yes... I know, who is dumb enough to use Windows Phone... apparently me.  Working on moving away from the platform, but even then.. it doesn't work on Edge.  Not even the playground.

If somebody who has contributed well to this project wants to tackle this I could probably send an old W10 phone to you (have been moving my family off of the platform).  But I've not even explored how to trouble shoot this issue.

**Comment by liborm85** [comment]
reference: https://github.com/bpampuch/pdfmake/issues/800

**Comment by vytautas-pranskunas-** [comment]
Any update on this?

**Comment by Rotzbua** [comment]
Still does not work.

**Comment by liborm85** [comment]
Microsoft has discontinued support for Windows 10 Mobile.
