### ISSUE TITLE
pdf doesn't generate in iOS 10 , pdf made using pdfmake 0.1.20

### ISSUE THREAD

**Issue by rssandy1991** [bpampuch/pdfmake#709]
Hi,
I have made an application using IONIC in this I generate a report in PDF format, but since iOS 10 update the app freezes while generating PDF I have used the latest version of pdfmake i.e, 0.1.20 to generate PDF.
If there is any solution for this issue please let me know where should I make changes in my app?

Thank you.

**Comment by drosenvall** [comment]
I am having a similar problem using pdfmake in iOS 10 and Sierra 10. I'm getting the following error when I add an image to the document using base64 data url's:

RangeError: Range consisting of offset and length are out of bounds

Here is the dataURL:
data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAggAAACCCAYAAAAjSDD0AAAAAXNSR0IArs4c6QAACtxJREFUeAHt3W2IHdUZAOBbE12sFKvpx8agRvzCNhhKIfhVCi1t8IdQ/6iICiL6Q0tBaPujoiGlPxS0xfqB/rFQWlsstgqCilgKtiKBVUFBVFBRSEgixJJKm9XVvm+8R2Zvsru5uzv3zsx9DryZmTsf57zPBM65s3Nnej2FAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAgQIECAAAECBAg0RWCqKQ3RDgIECBAgQKAZArdHMz5tRlO0ggABAgQIEGiKQA4ODBCacja0gwCBTgqs7WRWklpNgfw/8s2IL0cc1481Mf044qNKlOWcfhIxFzFYcr8sOa1G1lGOORvzGf+NeL0/jcnn5Yr+3PWff2KGAAECBAgQqE3g+Dhydr6PR5Rv6E2b5uCjtOlbMa8QIECAQE0CX6jpuA7bXIE85xdEXBZxZcRXIpYq/4sN8hv9fyJy/qiIoyPym39OS5TlXH+4kp17XlkokR1+mc91x/SjHCcWlyxvxhaZy8tLbmkDAgQIECBA4KDA1+Pfn0TsiCjfvBebPhnbXR2R+zWtnBAN2huR7X+jPx3M5f74PAcZCgECBAgQINAXyKsC2UF+GDHYcQ4u59/2b404I6ItJa9SZB55JaOU02PmpYjB/HL5krKRKQECBAgQmASBvPz+7Yj7Ig7XMVY/m41tHor4fkTeBNjmMhONz9xOWyCJa/rrq/nnfF51yPwVAgQIECDQOYGLIqO/Rwx2ftXl12L9TyOmI7pWzouEMte3jiCx/FPEU/3tqz45/37E1giFAAECBAi0ViBv9LslYrCTy+WdET+P+GpE10teMSkGw95Ue0rsu9Bg4Z+x7uSu48mPAAECBLojkAODOyNKp5jTvMnwOxFt/zNBpDB0mYs90uDUofecv8NJsfhsRNW1zP9o/qaWCBAgQIBAswRui+aUTiun2yOG/dbcrIxW1poXYvd0uGllhzlk7/Pjk7w/o2qdP+H0C4hDqHxAgAABAuMUuD4qr3ZW+eeDSR4Y5Lm4sW/yYi7UVHJA8GhE1f7smupyWAIECBAgcMQCV8eW1c7pV7E86QODxDuz75IPUhpF2RyVVM/DZaOoVB0ECBAgQGBQ4Nr4oNohPRjLBgafKeV9FsVmlCZfrNSb9f/6s+b4lwABAgQI1CuQNx/eGlE6v5z+LWKhxxLHqoks5X0Lp40p+/x1QzlHfx1TG1RLgAABAhMgkAOA2yNKp5PTByJG+e04qmtFeSZamT55/8E4y71ReTlfT4yzIeomQIAAgW4K3BBplY4mp9sjDAwOf67z5sA0eu/wq0f+6c/67ck2uZIwcn4VEiBAoLsC70RqZXDwi5g3MFj8XBerxbca7drqIOGR0VatNgIECBDoosAHkVR2eP+IMDAIhCXKH2N9el26xHbjWF19muXD42iAOgkQIECgGwLllcR3dSOd2rOYjhpycLCv9pqWX8Hd/TZmOw0Slu9oTwIECEyswJuReXYiv5lYgeETT6+MfOdCk8u2aFxpq0FCk8+UthEgQKBhAq9Ee7ID+UPD2tXk5rzaN7u8yY2stM0goYJhlgABAgQWF8h7DPI5/jk4eGzxTa2tCKRVmuULlNpUyiDhwzY1WlsJECBAYLQCZ0V12cll/Gm0Vbe6tnJTYl5BaGPJKx5ntLHh2kyAAAEC9Qv8Mqoog4Ot9VfXmRrK4ODdzmQkEQIECBAg0Bf4V0zL4OA4KkcskA8cSremPAzpiBtuQwIECBAgsJTAHbFBdnIvLrWh9fMEyqAqf+mhECBAgACBzgmUKwedS6ymhI6N4xaz52uqw2EJECBAgMBYBb4WtWdn9/5YW9Geyq/pe6XZ79rTbC0lQIAAAQLDCVwSm2dnd89wu03c1nnVIH8GmFYZ50QoBAgQIECgswI5MMgO74edzXDlif24b5ROz0V4F8XKTR2BAAECBBouUB6lPNXwdo6jecdHpeWKQU7PHUcj1EmAAAECBMYhUDrAcdTd5Dq3R+OKzV+a3FBtI0CAAAECdQiUTrCOY7fxmHkl5ZOI4nJyG5PQZgIECBAgsFKB0hGu9Dhd2P97kUTxeLQLCcmBAAECBAgsV6B0iMvdvyv7PRGJFItvdCUpeRAgQIAAgeUKlE6xLa8nXm6eC+13YqwoBvti/qiFNvQ5AQIECBCYJIG7ItnSQa6bpMQj1+qNiLdNWO7SJUCAAAECiwrkb/rLACGnXf6N/wWR35MD+WbOGyIUAgQIECBAYEAgO8gySHhlYF0XFrdU8it55vS3XUhODgQIECBAoE6BH8TBS+f5cJ0VjfDY+drq/ZW8ZmL+4oguXyWJ9BQCBAgQILC6AnfE4boySLi3ksvbMe9Jkav7f8XRCBAgQGDCBLZFvmWQ8OcW5n5dpf2Zh5cqtfAkajIBAgTqEGjs5eMtW7acNTc393odSa/mMXft2tXbuXPnwUNOTU31Nm3atJqHX9Vjzc7O9nbv3t3bs2fPvONu2LChNz09Pe8zCwQIECBQv8CaNWvO3rFjxxv11zR8DWuH38UeVYH169f3YiBzsOM9cOBAb2Zmprd58+be2rXjp92/f39v7969vX378pEFh5Z169b1Nm7ceOgKnxAgQIDAxAs09gpCC89MvgL66Uq7b475RyrL+VChL0XkzYB5OX+w5Pp8r8Fgyc9nI+YiPq5EjkDyXoF8HsN3I7ZGXBixWMmRwraI30f8e7ENrSNAgAABAgRWTyBfVpSdf1PipWjLlRHHRigECBAgQIDAGAXyG3/1iYt1Dxbeifoeirgq4tSIrF8hQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIECBAgQIAAAQIEWifwfzv/FPA2d3K+AAAAAElFTkSuQmCC

**Comment by drosenvall** [comment]
Finally got it to work again. I had to use a different pdfmake.min.js file. I downloaded one from Armcharts.com

https://github.com/amcharts/amcharts3/tree/master/amcharts/plugins/export/libs/pdfmake

Hope this helps others.

**Comment by saormart** [comment]
For me the pdfmake in this link doesn't work ! Now I can't even open the application on iOS 10!

**Comment by drosenvall** [comment]
I used the pdfmake.min.js from the armchart.com site and it works perfectly. What error are you getting on your application? I had an issue where I had an empty node in the content of the pdf and it threw an error ({_margin:null}). All I had to do is make sure I didn't have any empty nodes and the data url images worked perfectly.

**Comment by trailjob** [comment]
I am getting error as Error: TypeError: pdfMake.createPdf is not a function. (In 'pdfMake.createPdf( docDefinition )', 'pdfMake.createPdf' is undefined) after updating pdfmake.min.js from amcharts

**Comment by saormart** [comment]
I don't get any error by using the pdfmake.min.js from the armchart.com, the app just can't even open by using this pdf library from the website you posted in here...  that's really strange...

**Comment by saormart** [comment]
By the way, I just found another link that's works for me with iOS 10! Looks like they just build the update 5 days ago! Follow the link: [https://github.com/pdfmake/pdfmake](url)

**Comment by contacturmila** [comment]
Still getting Error: TypeError: pdfMake.createPdf is not a function. (In 'pdfMake.createPdf( docDefinition )', 'pdfMake.createPdf' is undefined)

**Comment by contacturmila** [comment]
saormart https://github.com/pdfmake/pdfmake is a broken link

**Comment by saormart** [comment]
It's not ! try by click on your copy of the link I have posted ! by the way you can get direct to: [http://pdfmake.github.io](http://pdfmake.github.io)

**Comment by jimothyhalpert7** [comment]
Can someone explain the relationship between this repository and https://github.com/pdfmake/pdfmake? Seems like this is the one that the bower package is pointing to, but the other is the npm one. However, the bower tag on this one says `0.1.20`, but on _pdfmake_ it's `0.1.31`. `bower info pdfmake` says `0.1.20` is the latest one.

**Comment by bhericher** [comment]
https://github.com/pdfmake/pdfmake is a fork that is more alive than this repository.

**Comment by Akta3d** [comment]
solution found in #710

**Comment by jimothyhalpert7** [comment]
Now that https://github.com/pdfmake/pdfmake is inexplicably shut down, we're back to looking for a better solution.

**Comment by liborm85** [comment]
@jimothyhalpert7  All changes from pdfmake/pdfmake are merged back here and there will continue active development. :)

**Comment by jimothyhalpert7** [comment]
@liborm85 thanks. Are you considering a tag-worthy release any time soon?

**Comment by liborm85** [comment]
@jimothyhalpert7  Date of release is not set. But because a lot of fixes is in master, it should be as soon as possible.

**Comment by liborm85** [comment]
Solve this problem, the latest released version (0.1.22) ?

**Comment by tcsaddul** [comment]
Thanks so much!  Been awaiting for this release.
 

    On Friday, December 23, 2016 4:30 PM, Libor M. <notifications@github.com> wrote:
 

 Solve this problem, the latest released version (0.1.22) ?—
