### ISSUE TITLE
Chinese can not automatically wrap

### ISSUE THREAD

**Issue by LuoMo92** [bpampuch/pdfmake#716]
Use pdfmake generated pdf file, custom Chinese fonts, but the Chinese can not automatically wrap, the English can. refer to the issue:
https://github.com/bpampuch/pdfmake/issues/462
but the regular expression will be given the error, the regular expression is not too understanding, please help me!

**Comment by bbj** [comment]
Just found one which work!!!! after hours of fighting!

var WORD_RE = /([\u4e00-\u9fa5][ ,\/!.?:;\-，。：]*)|([^ \u4e00-\u9fa5,\/!.?:;\-\n，。：]*[ ,\/!.?:;\-，。：]*)|\n/g;

**Comment by solidet** [comment]
@bbj i am sorry. could you just make the way you use it a bit clearer?

**Comment by liborm85** [comment]
By commit https://github.com/bpampuch/pdfmake/commit/d661618cf1afc89c0ddfb8a5cf7c6eedf8a7f07f implemented new split words algorithm -  Unicode Line Breaking Algorithm (UAX #14). This supports also Chinese characters.

**Comment by liborm85** [comment]
New version released.
