### ISSUE TITLE
How to load a svg image

### ISSUE THREAD

**Issue by ivanwagner** [bpampuch/pdfmake#717]
Dear all,

I'm attempting to load a svg image by using the following piece of code:
`...`
`var img = require('fs').readFileSync('images/image.svg', "utf8");`
`...`
`// The image object is part of the pdf content object which is then fed to createPdfKitDocument`
`image: 'data:image/svg+xml;utf8,' + img,`
`...`

I get an error which states that the file name is too long... Are there any ideas? Thank you.

**Comment by liborm85** [comment]
Relevant pdfkit issue: https://github.com/devongovett/pdfkit/issues/270. Will not be included in pdfkit.

You can use the library to converting: https://github.com/devongovett/svgkit

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/121
