### ISSUE TITLE
Tables cut off rather than breaking for the next page

### ISSUE THREAD

**Issue by gerickson808** [bpampuch/pdfmake#722]
I have tables with dynamic content, and sometimes rather than breaking in the appropriate place and continuing on the next page they just run off the end of the page, losing the rest of the content. Previously with this issue I was able to "fix" it by putting 'pageBreak: before' on the table, starting it on a new page after which it would break in the appropriate place, but that messes with the flow of the document and is no longer working reliably to fix the issue. Has anyone had this experience, and if so had any success?

**Comment by franklindias** [comment]
Hi @gerickson808, you could solve the problem?

**Comment by gerickson808** [comment]
No. My solution of pageBreak:before before the first dynamic table does reliably fix it now that I'm also explicitly setting page size, however this is not ideal as it leaves the page before the tables mostly blank.

**Comment by aconran** [comment]
@gerickson808 did you try dontBreakRows: true, in your table configuration? Are you expecting it to break on individual rows or on the table as a whole?

**Comment by liborm85** [comment]
Can be used `unbreakable` attribute, see PR https://github.com/bpampuch/pdfmake/pull/1073

**Comment by Focushift** [comment]
Solution - table cells must contain at least 1 space, not empty string.
When cell with empty string, then correct height cannot be calculated and in this case pageBreak is not inserted.
