### ISSUE TITLE
Footer shows on generated document but does not print

### ISSUE THREAD

**Issue by gerickson808** [bpampuch/pdfmake#723]
When a pdf is generated, the footer shows as it is supposed to, however when the document is physically printed out it is gone. Any ideas?

**Comment by alikaraki** [comment]
Is it possible that you have the wrong page size when printing?

**Comment by gerickson808** [comment]
Yes, it was the wrong page size. I'm not certain it's fixed, but I haven't heard otherwise from those actually doing the printing, so I'll go ahead and close this. Thanks
