### ISSUE TITLE
Very slow the creation of large pdf files & very large size of large pdf files

### ISSUE THREAD

**Issue by FireIvan** [bpampuch/pdfmake#727]
Greetings

When working with the library faced with the following (often critical) problems:

I create a table that is located on multiple pages (50 pages, 20000 rows) in Chrome.

**problem #1:**
PDF document is created for a long time (about 5-10 minutes), despite the fact that the formation of pdf and save of pdf takes 0.5sec and 5.0sec respectively. Rest of the time the browser is not responding (more 4:55min, more than 95% of the time the creation of pdf).

What could be the problem? And how to deal with it?

**problem #2** 
Created a pdf file has a size of 8MB, if resave this file using Adobe Reader, you get just 1MB. When viewing the contents of files, it was found that 7MB occupy fonts. It seems that the fonts (400 kb) are set for each page separately.

Is it so? And how can izbazhat such a negative effect

**Comment by eos87** [comment]
Hi, I have more or less the same issue. PDF generation is really slow for me with about 5000 rows (~ 100 pages). Any ideas on how to improve this? Thanks!

**Comment by Chris--A** [comment]
For the speed issue, see here:
https://github.com/bpampuch/pdfmake/issues/280#issuecomment-148335977

Generating my 100 page document went from 9 mins to about 10 seconds in chrome.

**Comment by liborm85** [comment]
Can you test with lastest version (0.1.22) ?
