### ISSUE TITLE
vertically rotated text in table

### ISSUE THREAD

**Issue by angularnewbee** [bpampuch/pdfmake#728]
Hello,

I have searched both playground and docs to find out how to achieve vertical text in table columns, failed to do that.

Is it possible to write text 90 degrees vertical?

If not, are you planning to add this feature?

Keep up the good work.

Best regards

edit:typos

**Comment by Focushift** [comment]
Use canvas to insert rotated text.
here code from @serkandurusoy https://github.com/bpampuch/pdfmake/issues/74

**Comment by liborm85** [comment]
Feature request: https://github.com/bpampuch/pdfmake/issues/324
