### ISSUE TITLE
Is it possible to rotate the content of certain pages in pdf document?

### ISSUE THREAD

**Issue by arsinawaz** [bpampuch/pdfmake#729]
i generate pdf documents dynamically and i wanted to know is there a way to rotate the content of certain pdf pages in the document based on the content width and not changing the page orientation?

just as in image below which has portrait page with rotated content

![image](https://cloud.githubusercontent.com/assets/6444617/19430851/99ad4c82-945e-11e6-88a3-e4cbef6b1230.png)

**Comment by aconran** [comment]
Copy/paste from the README.md Page Dimensions, Orientation and Margins
https://github.com/bpampuch/pdfmake/blob/master/README.md#page-dimensions-orientation-and-margins

> To change page orientation within a document, add a page break with the new page orientation.
> 
> {
>   pageOrientation: 'portrait',
>   content: [
>     {text: 'Text on Portrait'},
>     {text: 'Text on Landscape', pageOrientation: 'landscape', pageBreak: 'before'},
>     {text: 'Text on Landscape 2', pageOrientation: 'portrait', pageBreak: 'after'},
>     {text: 'Text on Portrait 2'},
>   ]
> }

**Comment by liborm85** [comment]
Answered.
