### ISSUE TITLE
is it possible to remove certain pages from pdf docuement after generation or during generation?

### ISSUE THREAD

**Issue by arsinawaz** [bpampuch/pdfmake#730]
Is it possible to remove certain pages from pdf document after the document has been generated or during generation?

The use case is that i have a **wide** table on first page of the pdf and i want to make that page to landscape mode. On second page i have another table which i want to make it to portrait mode.

The issue here is that if i want change the orientation of first page then there is unnecessary blank page (added by pageBreak, required to change the pageOrientation). I want to remove that initial blank page.

Any help is highly appreciated..

Thanks in advance.

**Comment by liborm85** [comment]
Do you have any simple sample that would reproduce this problem?

**Comment by liborm85** [comment]
No reaction.
