### ISSUE TITLE
Text not wrapped on invisible space

### ISSUE THREAD

**Issue by myleftsock** [bpampuch/pdfmake#733]
The invisible space (character 0x200b) has no width but should cause the line to be wrapped like a space or hyphen (-) character. Currently it renders correctly within a single line but does not cause wrapping.

**Comment by liborm85** [comment]
I implemented in commit https://github.com/bpampuch/pdfmake/commit/d661618cf1afc89c0ddfb8a5cf7c6eedf8a7f07f new split words algorithm -  Unicode Line Breaking Algorithm (UAX #14). This supports also wrapping per invisible space.

**Comment by liborm85** [comment]
New version released.
