### ISSUE TITLE
release of pdfmake 0.1.18 differs between bower and npm

### ISSUE THREAD

**Issue by hohwille** [bpampuch/pdfmake#735]
When I request pdfmake 0.1.18 via bower I get a working result. However the same version resolved via npm or yarn ends in a different result what seems to be broken. Is it possible that the npm release was somehow broken? E.g. it does not contain a `build` folder and the file `vfs_fonts.js` is missing. Instead of including `build/pdfmake.min.js` I tried to include `src/printer.js`. This itself is including both `pdfkit` and `pdfkit/js/reference`. As I am using SystemJS this is causing other problems as I have to map `pdfkit` and can not find a mapping for both references.
So if the npm release is just broken, It would be great to just have a new fixed release as e.g. `0.1.19` that fixes the problem. Otherwise it would be great if I you could update your docs or provide some other way to give me feedback in order to fix my problem.

**Comment by hohwille** [comment]
https://github.com/bpampuch/pdfmake/tree/0.1.18/build
any ideas why both npm and yarn does not result in this build folder be present in node_modules/pdfmake? Even if I put this into `package.json`:
```
    "pdfmake": "git+https://github.com/bpampuch/pdfmake.git#0.1.18",
```
I do not understand what is going on here...

**Comment by hohwille** [comment]
It is working with
```
    "pdfmake": "git+https://github.com/bpampuch/pdfmake.git#0.1.20",
```
do not ask me why.
If I use
```
    "pdfmake": "0.1.20",
```
It fails as 0.1.20 is not published in npm registry.

**Comment by Pczek** [comment]
still don't get the build folder. Btw the folder is ignored in the .npmignore 
https://github.com/bpampuch/pdfmake/blob/master/.npmignore#L6

However, can't we just somehow get this fantastic lib working with webpack somehow?

**Comment by gastongr** [comment]
For me it worked the first time with
`pdfmake": "git+https://github.com/bpampuch/pdfmake.git#0.1.20",`
Now it doesn't pull the build folder anymore..

It would be nice if the author takes it out from .npmignore

**Comment by gastongr** [comment]
If someone is interested, this package is a wrapper for the build folder. Version 0.1.20
https://preview.npmjs.com/package/pdfmake-client

**Comment by liborm85** [comment]
New version 0.1.22 released. Through npm is available.
