### ISSUE TITLE
Absolutely positioned images disappear when they get too close to the page bottom

### ISSUE THREAD

**Issue by va-andrew** [bpampuch/pdfmake#737]
This came when I was trying to add an image as a background (using AbsolutePosition). E.g. from the playground:

```
var HEIGHT = 10*72;
var dd = {
    pageSize: {width: 8.5*72, height: 11*72},
    content: [
        {
            image: 'sampleImage.jpg',
            absolutePosition: {x: 0, y: 0},
            width: 8.5*72,
            height: HEIGHT
        },
    ]
}
```

The above definition works, but setting `HEIGHT = 11*72` no longer works. Instead, the PDF becomes two blank pages. I think absolute positioning might be trying to wrap the image to the next page, even though it's absolutely positioned?

**Comment by va-andrew** [comment]
(Setting the bottom page margin to a negative value works, but seems like a hacky solution.)

**Comment by prokilogrammer** [comment]
I had this issue too. I set `pageMargin: [0.0]` to remove the margin that was causing images to wrap.

**Comment by liborm85** [comment]
Fixed by PR https://github.com/bpampuch/pdfmake/pull/1031.
