### ISSUE TITLE
Header and Footer not showing up

### ISSUE THREAD

**Issue by m0ngr31** [bpampuch/pdfmake#739]
Here's my config:
```
var dd = {
  footer: function(currentPage, pageCount) {
    return {
      columns: [
        {
          width: '*',
          text: ' '
        },
        {
          width: '*',
          text: '%copy; ' + moment().format('YYYY') + ' My Swift Quotes.'
        },
        {
          width: '*',
          text: currentPage.toString() + ' of ' + pageCount 
        }
      ]
    };
  },
  content: []
};
```

Nothing my content shows up (I'm pushing stufff to it later), but the footer doesn't show at all. If I try to do the header the same way, it doesn't show either. Is there something I'm doing wrong?

**Comment by Chris--A** [comment]
I found that if the top or bottom page margins are not big enough to contain the header or footer, they do not show.

Might not be your issue but worth a try to temporarily increase them.

**Comment by m0ngr31** [comment]
Looks like I needed to crank up my margin on the bottom. Works great now. Thanks.
