### ISSUE TITLE
pdfMake.createPdf does not working on device (Saleforce1 on Ipad)

### ISSUE THREAD

**Issue by ttkhai93** [bpampuch/pdfmake#740]
The code working find on browser, but when I run my page on Ipad, the second alert is not displayed. Does pdfMake not support on device?
```
alert('start createPDF'); //1
pdfMake.createPdf(dd).getDataUrl(function(dataURL) {
       alert('start pdfMake.createPdf'); //2
});
alert('end createPDF'); //3
```

**Comment by liborm85** [comment]
reference: https://github.com/bpampuch/pdfmake/issues/800

**Comment by liborm85** [comment]
Is there displayed an error? What version of pdfmake you use?

**Comment by liborm85** [comment]
No reaction.
