### ISSUE TITLE
DeprecationWarning: Using Buffer without `new` will soon stop working. Use `new Buffer()`, or preferably `Buffer.from()`, `Buffer.allocUnsafe()` or `Buffer.alloc()` instead.

### ISSUE THREAD

**Issue by thomasdola** [bpampuch/pdfmake#741]
getting this warning, any idea on how to solve it?
am using node v7

**Comment by jakubkratina** [comment]
+1

**Comment by samikarak** [comment]
same for me

**Comment by thomasgroch** [comment]
+1

**Comment by richellin** [comment]
+1

**Comment by simonguo** [comment]
+1

**Comment by andreipanov** [comment]
+1

**Comment by liaoyuming** [comment]
+1

**Comment by danawoodman** [comment]
I'm looking into it but I'm a new collaborator so no guarantees yet

**Comment by danawoodman** [comment]
It looks like a deprecation warning in newer Node versions for one of the project dependencies. Shouldn't be a major issue at this point

**Comment by liborm85** [comment]
Tested with node 8.9.3, warning is not displayed, probably solved some updates.
