### ISSUE TITLE
What are the supported style properties?

### ISSUE THREAD

**Issue by parky128** [bpampuch/pdfmake#742]
Hi,

Firstly, I just want to say what a fantastic library this is - great job!

I am looking at the styling capabilities and have struggled to find anything in the docs that details the supported properties, so my apologies if I have missed this.

I would like to know what are the supported style properties that can be applied. Would I be correct its the ones listed [here](https://github.com/bpampuch/pdfmake/blob/master/src/styleContextStack.js#L85)?

Thanks

**Comment by liborm85** [comment]
Documentation might not be complete. It depends what you want to create. Look into `examples` folder and on http://pdfmake.org/playground.html.

**Comment by dennisat** [comment]
This might help https://stackoverflow.com/questions/32291112/pdfmake-api-is-there-a-list-of-styles-fonts-capabilities
