### ISSUE TITLE
New versions take longer to load files?

### ISSUE THREAD

**Issue by diegito** [bpampuch/pdfmake#743]
I am using an older version of pdfMake and the pdf I am building consists of a big JPG file plus 3 rows of text.

I wanted to switch to the latest version but I noticed that the load times for this image is ~4 times bigger than with the older version. 

I'd be glad to provide with the version number of pdfMake if anybody can tell me how to get it. In the source code I have found a version for `lodash` and this is 3.1.0, not sure if that can help..

The images I am loading range from 4-10MB in size. With the old version of pdfmake the load times were around 4-10 seconds, with the new version I have times of 15-35 seconds.

Did anything change in the way images are loaded?

**Comment by liborm85** [comment]
@diegito Can you try it in latest version (0.1.22)?

**Comment by hillelcoren** [comment]
In our tests performance degraded significantly from version 0.1.20 to 0.1.22.

Note: we're using a custom font. With Roboto it's less noticeable.

**Comment by liborm85** [comment]
@hillelcoren Yes. Version 0.1.22 using newest version of pdfkit package and it will be a problem. I did same performance test (see https://github.com/bpampuch/pdfmake/issues/798#issuecomment-275899461). I do not know how to find the cause of the performance problem in pdfkit.

**Comment by liborm85** [comment]
New version 0.1.27 includes partial performance fix. Next performace solution we will continue in issue https://github.com/bpampuch/pdfmake/issues/798.
