### ISSUE TITLE
Uncaught TypeError: Cannot assign to read only property '0' of string

### ISSUE THREAD

**Issue by brettywhite** [bpampuch/pdfmake#744]
Hi, I am having sort of a brain fart. I am dynamically generating table rows for use with pdfmake for use in the browser, and inserting the rows into the table. However, when I put the lines in with a variable, I get the error: Uncaught TypeError: Cannot assign to read only property '0' of string. If i copy the variable's contents and paste it in its place (the same thing), it works. Hopefully someone can see something wrong here, as I am pulling my hair out.

#### row generation:
``` javascript
function createPdfLineItems(tabledata){

          var lines="";

          for (i = 0; i < tabledata.length; i++) {
            lines += "[ '"+tabledata[i].Item+"','"+tabledata[i].Description+"',{ text: '"+tabledata[i].Quantity+"', alignment: 'center' },{ text: '"+tabledata[i].Cost+"', alignment: 'center' },{ text: '"+tabledata[i].Total+"', alignment: 'center' }],";
          }

          return lines;
        }
```
#### template 
``` javascript
var docDefinition = { 
  
                    content: [
                        { 
                        text: 'ESTIMATE', 
                        style: 'header' , 
                        alignment: 'center',
                        color: 'gray'
                      },
                    {
                      columns: [
                      
                      {
                        
                        text: 'Estimate #'+estimateNum+' \n PO# '+PONumber+' \n '+date,
                        margin: [0, 10],
                      }
                      ],columnGap: 270
                    },
                    {
                      columns: [
                      {
                        
                        text: client+'\n '+clientCompany+'\n '+clientAddress+'\n '+clientCity+', '+clientState+' '+clientZip,
                        margin: [0, 25],
                      },
                      {
                        
                        text: username+'\n '+usercompany+'\n '+useraddress+'\n '+usercity+', '+userstate+' '+userzip,
                        margin: [0, 25],
                      }
                      ],columnGap: 310
                    },
                    {
                      style: 'tableExample',
                      table: {
                        widths: ['23%', '50%', '*', '*','*'],
                        body: [
                        [ { text: 'Item', style: 'tableHeader', alignment: 'center' }, { text: 'Description', style: 'tableHeader', alignment: 'center' }, { text: 'Quantity', style: 'tableHeader', alignment: 'center' }, { text: 'Cost', style: 'tableHeader', alignment: 'center' },{ text: 'Total', style: 'tableHeader', alignment: 'center' }],
                        createPdfLineItems(lineItems),
                        ]
                      },layout: 'lightHorizontalLines'
                    },
                      {
                      columns: [
                      {

                      },
                      {
                        text: 'Subtotal: '+total,
                      }
                      ],columnGap: 300
                    },
                    {
                      columns: [
                      {

                      },
                      {
                        text: 'Total: '+total,
                        style: 'subheader'
                      }
                      ],columnGap: 300
                    },
                    {
                        text: 'Notes:',
                        style: 'subheader'
                      },
                      notes,
                    ],
                    styles: {
                      header: {
                        fontSize: 18,
                        bold: true,
                        margin: [0, 0, 0, 10]
                      },
                      subheader: {
                        fontSize: 16,
                        bold: true,
                        margin: [0, 10, 0, 5]
                      },
                      tableExample: {
                        margin: [0, 5, 0, 15]
                      },
                      tableHeader: {
                        bold: true,
                        fontSize: 13,
                        color: 'black'
                      }
                    },
                    defaultStyle: {
                      // alignment: 'justify'
                    }
                    
                  };
                pdfMake.createPdf(docDefinition).open();  
        }
```
As you can see around the middle, it is calling the function ```createPdfLineItems(lineItems)```.

An example response of createPdfLineItems(lineItems):
```
[ 'tools','chainsaw',{ text: '1', alignment: 'center' },{ text: '300', alignment: 'center' },{ text: '300', alignment: 'center' }],
```

The interesting part comes because when I call the function with the ```createPdfLineItems(lineItems)```, it fails with the error mentioned, however if i log the output like i copied just above, and replace ```createPdfLineItems(lineItems)``` with the logged output, it works.

Any help is greatly appreciated. I am testing this in chrome. 

Many Thanks!

Edit: here is the screenshot of the console error:

<img width="400" alt="screen shot 2016-11-09 at 10 11 54" src="https://cloud.githubusercontent.com/assets/3911458/20143030/3bd71fde-a665-11e6-87b9-edf5632290cd.png">

**Comment by g6025** [comment]
Hi

Did you solve this? I'm having same problem, is driving me mad!

**Comment by katiazanotti** [comment]
same issue here: TypeError: Cannot assign to read only property '0' of string '

**Comment by brettywhite** [comment]
Hey, ya i got it working:

      function createPdfLineItems(tabledata){
        var headers = {

            top:{
                col_1:{ text: 'Item', style: 'tableHeader', alignment: 'center' },
                col_2:{ text: 'Description', style: 'tableHeader', alignment: 'center' }, 
                col_3:{ text: 'Quantity', style: 'tableHeader', alignment: 'center' },
                col_4:{ text: 'Cost', style: 'tableHeader', alignment: 'center' },
                col_5:{ text: 'Total', style: 'tableHeader', alignment: 'center'}
            }
        }
        var rows = tabledata;

        var body = [];
        for (var key in headers){
            if (headers.hasOwnProperty(key)){
                var header = headers[key];
                var row = new Array();
                row.push( header.col_1 );
                row.push( header.col_2 );
                row.push( header.col_3 );
                row.push( header.col_4 );
                row.push( header.col_5 );
                body.push(row);
            }
        }
        for (var key in rows) 
        {
            if (rows.hasOwnProperty(key))
            {
                var data = rows[key];
                var row = new Array();
                row.push( { text: data.Item.toString(), alignment: 'center' } );
                row.push( { text: data.Description.toString(), alignment: 'center' } );
                row.push( { text: data.Quantity.toString(), alignment: 'center' });
                row.push( { text: data.Cost.toString(), alignment: 'center' });
                row.push( { text: data.Total.toString(), alignment: 'center' });
                body.push(row);
            }
        }
        return body;
      } 

And thats inserted in like this:

                    {
                      style: 'tableExample',
                      writable: true,
                      table: {
                        widths: ['20%', '50%', '*', '*','20%'],
                        body: body
                      },layout: 'lightHorizontalLines'
                    },
