### ISSUE TITLE
Project abandoned?

### ISSUE THREAD

**Issue by danawoodman** [bpampuch/pdfmake#745]
Is this project abandoned? Does it need contributors to pickup the slack on the Pull Request queue? 

The API for this library is great and it would be a shame for it to die off.

**Comment by danawoodman** [comment]
@bpampuch if you need contributors, I could lend a hand

**Comment by tqwhite** [comment]
There is another repo with more recent code. 
[https://github.com/pdfmake/pdfmake](https://github.com/pdfmake/pdfmake)

It would be great if @bpampuch would let us know a little more about his intentions.

**Comment by danawoodman** [comment]
@tqwhite seems like that repo is equally abandoned to me

**Comment by Sjonnie2nd** [comment]
I heard bpampuch stepped over to ISIS.

**Comment by bpampuch** [comment]
Sorry guys, I literally have no time now to contribute. @danawoodman - would be great to have somebody who could test and merge pull requests and commits from pdfmake/pdfmake as well.

**Comment by Sjonnie2nd** [comment]
Sorry @bpampuch, I already regretted my post when I pushed the Comment button!

**Comment by bpampuch** [comment]
@Sjonnie2nd that's ok

**Comment by danawoodman** [comment]
Thanks @bpampuch I will jump into things tomorrow and see if I can help triage some things 👍

**Comment by miltador** [comment]
@bpampuch hi there! Glad to hear from you. I can spend some of my free time on this project, already created a PR with my changes, more to come. I'll remove my fork to not to confuse anyone, would be glad to contribute as I see it is needed by a lot of people and I also use pdfmake in my projects.
