### ISSUE TITLE
dynamic image table

### ISSUE THREAD

**Issue by fpena06** [bpampuch/pdfmake#746]
Hello I'm trying to generate an image table dynamically. I'm using lodash.chunk to split an image array into arrays of three in order to get three images per row (array). This works fine as expected, the problem I'm facing for example if I had 7 images I would end up with three arrays, two with three images each and one with the remaining image, this is where I have a problem. Seems like pdfmake wont generate the report because the last image array which only contains one image. Once I remove the last image image, report is generated fine.

**Comment by liborm85** [comment]
Do you have an example of the problem?
