### ISSUE TITLE
How to make Chinese character auto break line in table layout 

### ISSUE THREAD

**Issue by JennerChen** [bpampuch/pdfmake#748]
I am trying to make user can download table in pdf format, the table may contain long text Chinese, each row column has fixed width. The number and English words can be auto break line when text too long, but for Chinese , it can't. 
Please tel me how to make Chinese word auto break line in table
note: I am using SIMHEI font for Chinese.

**Comment by liborm85** [comment]
By commit https://github.com/bpampuch/pdfmake/commit/d661618cf1afc89c0ddfb8a5cf7c6eedf8a7f07f implemented new split words algorithm -  Unicode Line Breaking Algorithm (UAX #14). This supports also Chinese characters.

**Comment by liborm85** [comment]
New version released.

**Comment by JennerChen** [comment]
thanks a lot, it works for me!
