### ISSUE TITLE
Instead downloading 2 generated PDF, same pdf downloaded twice

### ISSUE THREAD

**Issue by peterbartos** [bpampuch/pdfmake#754]
I'm generating 2 PDFs at the same time and want to download both. I'm calling:
```
pdfMake.createPdf(printDef1).download();
pdfMake.createPdf(printDef2).download();
```
And I get 2 downloads, with the same document which is defined in printDef1.

PS: If I'm calling only 1 download, proper pdf gets downloaded. Also when I replace download() with open(), the browser properly opens 2 different documents, so the problem appears only with download().

**Comment by Loki-432** [comment]
same issue here !

**Comment by solidet** [comment]
I also come across this, but the different is I have an array containing many docs. I tried with loop and download but it doesn't work well. 

However, I decided to set the time interval instead. you can check my Question and answer here 
[http://stackoverflow.com/questions/41220342/download-multiple-files-using-pdfmake/41235131#41235131](url)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/410
