### ISSUE TITLE
Margin Keeps Changing, Header Image Moves to the right 

### ISSUE THREAD

**Issue by romarioscott** [bpampuch/pdfmake#757]
`<script type="text/javascript" src="js/pdfmake.min.js"></script> `

I am using that to generate PDF however, when the PDF is generated there are right margin issues when the text overflow on the next page. The right margin does not obey the settings. 

Also in the header where there is a image, the image keeps on increment in margin to the right.

**Comment by aconran** [comment]
@romarioscott Try implementing the header as a function rather than just assigning an object to it.
```
header: function() {
    var object = {};
    return object;
}
```

**Comment by romarioscott** [comment]
Fixes the image moving but it does not fix the right margin not obeying the boundary settings. The words that overflow from page 1 to page 2 do not obey the right margin boundary.

**Comment by aconran** [comment]
@romarioscott I do not. I know there were several fixes from the fork https://github.com/pdfmake/pdfmake/ that have recently made it back to the repo

**Comment by liborm85** [comment]
Fixed. https://github.com/bpampuch/pdfmake/commit/287362a1b4763ee99fc0bb04061e12af9ee9e6d9
