### ISSUE TITLE
Create multipage poster pdfs

### ISSUE THREAD

**Issue by matthiasg** [bpampuch/pdfmake#760]
It would be nice to have an option, to have it automatically split a large SVG/PNG/JPG across multiple pages (with guiding lines) which could be printed and glued together as one large poster.

is something like this possible or planned ?

**Comment by Chris--A** [comment]
As pdfmake is designed to generate a PDF based on a layout or document definition, you will need to create the document how you would like it. It is not an image manipulation tool.

- You can create your image in a canvas object
- Split the canvas into logical sections (page sized chunks)
- Create a data URI for each section
- Add each data URI as an image to a document with a page break after each.
- Generate PDF
- Profit

**Comment by matthiasg** [comment]
@Chris--A  sure thing. I just hoped that this is something of general use. But i do see the point, maybe something to be built on top as a nice little module
