### ISSUE TITLE
can we hide border in table content or do zebra style?

### ISSUE THREAD

**Issue by piggyman007** [bpampuch/pdfmake#763]
hi all,

I am using pdfmake with table content but  I cannot see the way to hide border of the table or do zebra style.

are these features above supported or just missing the document?

**Comment by miltador** [comment]
@piggyman007 checkout the [tables section in playground](http://pdfmake.org/playground.html) or [this example](https://github.com/bpampuch/pdfmake/blob/master/examples/tables.js#L138) for no boder table. As for zebra tables - they are not currently supported, however you can manually set styles for each row.
