### ISSUE TITLE
Using really large images

### ISSUE THREAD

**Issue by SpringsTea** [bpampuch/pdfmake#764]
I'm using html2canvas to try and save an info dump to pdf. Heres my code

    function PrintInfoPanel(){
		var panelhtml = $('.error-dump .upload-info');
	    html2canvas(panelhtml, {
          onrendered: function (canvas) {
              var data = canvas.toDataURL();
              var docDefinition = {
                  content: [{
                      image: data
                  }]
              };
              console.log(data);
              pdfMake.createPdf(docDefinition).download("UPD_UploadPrint.pdf", function(){
                //$('.label-wrapper').html('');
              });
          }
      });
    }

The encoded image turns out fine from html2canvas, [heres an example](http://pastebin.com/WC6M8rj4)
which becomes the value of `image: data`.

As you can see if you decode the image, it is pretty long, longer than a normal sized page. So if the image coming in is as long as this one, all I'm getting back is a 2 page pdf that appears blank. If the image happens to be shorter than a page, it prints out fine. How is pdfmake supposed to handle tall images? I would like it to just flow over into the second page, and I have seen examples around that look like people have done this before. I don't want to set the content height, I want it to keep the source dimensions.

**Comment by Chris--A** [comment]
I have had issues with the image dimensions.

To be sure the image data is actually correct, do a test with a `fit` command to shrink it to dimensions that fit inside the document.

If the image shows up, then your image is too large for the page. I have had this issue and the images simply do not show when too big.

Oops, just read more of your post, and yes it definitely is the issue if you wish it to flow onto a second page.

Before creating the document definition, use JS/canvas element and cut the picture up, then create data URLs for the pieces.

**Comment by SpringsTea** [comment]
Fair enough, but it just seems wrong that the image just dosnt show up. This is only if it's too tall, if it's too wide it just overflows, which is way more reasonable.

**Comment by AswarthaA** [comment]
SpringsTea, why did u close the thread? did u solve this issue by spliting the data to urls or got some other fix??

I am also facing same issue, can you post your solution..

**Comment by SpringsTea** [comment]
Yes, I just split the image into pieces vertically. My image was data arranged in a grid, so it wasn't a big deal for me, but this behavior still seems like a bug to me.

**Comment by nikokolev** [comment]
@SpringsTea Sorry to bother you but, how did you do the splitting? I mean, how you can calculate at what height actually to split? I have a document that flows into pages and the image (which obviously is too tall to fit the document) that I need to place can be once on the top of the page, once in the middle or so, and once on the bottom of a page. I have other stuff before that section that is dynamic so I don't know how long it can be! Any help would be much appreciated! Thank you!
