### ISSUE TITLE
Table does not break into pages with Dynamic creation

### ISSUE THREAD

**Issue by Tanshaydar** [bpampuch/pdfmake#77]
Hi;
I'm creating my tables on the runtime with specific information. Unfortunately my table which should have been 8 pages long keeps being rendered under the same page into the oblivious.

How can I solve this?

![screenshot from 2014-08-26 13 46 25](https://cloud.githubusercontent.com/assets/1215477/4043837/15b258dc-2d18-11e4-9973-014b5f10391d.png)

**Comment by mackadir** [comment]
How to add dynamic picture of PDFMaker

**Comment by nahueld** [comment]
can you please fix this ?????
