### ISSUE TITLE
文本未正确换行

### ISSUE THREAD

**Issue by smart-dream** [bpampuch/pdfmake#770]
当一句话没有空格或换行符的时候，文本会超出pagesize区域.
eg:aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa,像这种一直输入进去的就有问题。

**Comment by liborm85** [comment]
In English, please.
