### ISSUE TITLE
pdfmake配置中文微软雅黑字体后，部分英文会乱码

### ISSUE THREAD

**Issue by smart-dream** [bpampuch/pdfmake#771]
通过grunt dump_dir 打包成新的vfs_fonts.js，在项目中使用：
        pdfMake.fonts = {
            Roboto: {
                normal: 'Roboto-Regular.ttf',
                bold: 'Roboto-Medium.ttf',
                italics: 'Roboto-Italic.ttf',
                bolditalics: 'Roboto-Italic.ttf'
            },
            微软雅黑: {
                normal: '微软雅黑.ttf',
                bold: '微软雅黑.ttf',
                italics: '微软雅黑.ttf',
                bolditalics: '微软雅黑.ttf',
            }
        };
        var dd = {
            content: [            
             '中英文测试',
             'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines asdfasdf asdfasdf documentation is in prog'
             ],
             defaultStyle: {
                 font: '微软雅黑'
             }
        };
 配置中文微软雅黑字体后，中文显示正确，但是英文内容有一些部分会变成中文。有谁遇到过这个问题，有什么办法让它同时支持中文 和 英文么，求帮助。

**Comment by liborm85** [comment]
I do not understand Chinese language, but I used google translate for jsou issue and probably you have a problem in that what font to use for Chinese text. Issue https://github.com/bpampuch/pdfmake/issues/533 it would not help in this?

**Comment by gongph** [comment]
关键是，换成中文后，vfs_fonts.js 特别大。导出 pdf 时很慢。怎么破？

**Comment by xuchao996** [comment]
@gongph 嗨兄台，这个问题解决了嘛？即导出时间过长的问题。
