### ISSUE TITLE
Header adding margin value in each page!

### ISSUE THREAD

**Issue by mariogalvez17** [bpampuch/pdfmake#772]
[playgroundDesc.pdf](https://github.com/bpampuch/pdfmake/files/631204/playgroundDesc.pdf)

Hi .... I'm not sure if this is a mistake or it's a misunderstanding on my part (most likely), so ... I need a logo in the header of each page, header has a margin, the body Of reports is dynamically built, a playground example:
var externalDataRetrievedFromServer = [
    { name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },
    { name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },{ name: 'Bartek', age: 34 },
    { name: 'John', age: 27 },
    { name: 'Elizabeth', age: 30 },
];

function buildTableBody(data, columns) {
    var body = [];

    body.push(columns);

    data.forEach(function(row) {
        var dataRow = [];

        columns.forEach(function(column) {
            dataRow.push(row[column].toString());
        })

        body.push(dataRow);
    });
        //body.push({image: 'sampleImage.jpg'});
    return body;
}

function table(data, columns) {
    return {
        table: {
            headerRows: 1,
            body: buildTableBody(data, columns)
        }
    };
}

var dd = {
                            pageSize: 'A4',
                            pageMargins: [40, 100, 40, 60],
                            header: {
                                margin: 20,
                                columns: [
                                {
                                    table: {
                                        widths: [ '20%','60%','20%'],

                                        body: [
                                            [
                                                { 
                                                    image: 'sampleImage.jpg',
                                                    width: 100,

                                                },
                                                [
                                                    {
                                                        text: 'Reporte ',
                                                        style: 'surveyReportTitle',
                                                    },
                                                    {
                                                        text:'Area:', 
                                                        style: 'surveyReportSubTitle',
                                                    }
                                                ],

                                                { text: '55',

                                                    heigth:150,
                                                    alignment:'right',
                                                    bold:true,
                                                    size:8,
                                                    
                                                }
                                            ]
                                        ]
                                    },
                                    layout: 'noBorders'
                                }

                                ]
                            },
    content: [
        { text: 'Dynamic parts', style: 'header' },
        table(externalDataRetrievedFromServer, ['name', 'age']),
        {image: 'sampleImage.jpg',fit:[200,200],},
    ]
}`

In page 2, 3 .... the image logo at header section is "rolling"  the margin. 

related with Issue #757, #376,#472,... ?
This should be marked as duplicated.

**Comment by mariogalvez17** [comment]
I guess this should be labeled as a question.

**Comment by mariogalvez17** [comment]
wrapp header section in a function as suggested by Elyahou at #376  fix this

**Comment by JJanz** [comment]
I guess you meant to open this issue for https://github.com/pdfmake/pdfmake/ , right? Because this specifically is fixed in this guy's fork ( https://github.com/bpampuch/pdfmake/blob/master/src/elementWriter.js#L96 vs https://github.com/pdfmake/pdfmake/blob/master/src/elementWriter.js#L96 ), which unfortunately he never pulled back.

**Comment by liborm85** [comment]
Fix is included in the new version (0.1.22).
