### ISSUE TITLE
Stream du to performance issue

### ISSUE THREAD

**Issue by romainkoenig** [bpampuch/pdfmake#773]
Hello guys, 
I am using this packages and it works well for small PDF, I can render them client side.
However for a large PDF ( around 100 pages ). It takes very long time. So I decided to construct it server-side with a stream, so the user can see the file downloading like he is used to.
However I cannot find on the docs how to construct a stream to pass ( to a res express response for example ). Do you know where to find it or how to construct it ( the stream ? ).
This is what I want to do : 
````js
function exportStuff(params, res, res) {
     res.writeHead(200, { 'Content-Type': 'application/pdf' });
     mongo.fetchData(...); // ok
     const docDefinition = {...}; // ok
     pdfMake.createPdf(docDefinition) //.??? pipe(res); ???
}
````
Client side it is ok for the method open and download, but I cannot find how to use it server side : (

**Comment by romainkoenig** [comment]
Find how do to the stream server side, sadly it does not resolve the performance problems. Worse it blocks everything coming from the server for minutes...
But very useful package for small PDF

**Comment by liborm85** [comment]
@romainkoenig I tried to fix performance, details in comment https://github.com/bpampuch/pdfmake/issues/280#issuecomment-267255835. You can try it.
