### ISSUE TITLE
Looking for Help on Fixing Issues

### ISSUE THREAD

**Issue by cjustice** [bpampuch/pdfmake#774]
I'm running into issues #278 and #655 but I have both the time and resources to (hopefully) fix the PDFMake codebase. That being said, my job would be made significantly easier if I could get some help from more experienced contributors. Do @bpampuch, @jthoenes or others have any inkling as to what parts of the codebase may be causing these problems? I.e. where should a new contributor such as myself start? 

I'd also love to hear about any tips you have for development with this plugin. What does your setup look like? 

Please let me know if I can provide more information. Sorry if this isn't the right place for my question!

**Comment by liborm85** [comment]
How build sources is says here https://github.com/bpampuch/pdfmake#building-from-sources .
It's just about learning the npm and gulp and have some knowledge of javascript.

Pull requests are welcome. :)

(and https://github.com/bpampuch/pdfmake/issues/655 is fixed in master)
