### ISSUE TITLE
[Question] Set filname

### ISSUE THREAD

**Issue by ottigerb** [bpampuch/pdfmake#780]
### Set filname
Is there a way to control the filename of the current PDF?  
Currently all my files are named just: `file.pdf`.  Sorry if I have 'overlooked' something.

Thanks for any helpful comment.

**Comment by miltador** [comment]
Hi!
The possible options (for both `open` and `download` methods) are mentioned in #680.

**Comment by ottigerb** [comment]
Oh yes - that did the trick:

```JS
var filename = ' Whatever you want ';
filename = filename.replace(/[^a-z0-9]/gi, '_').toLowerCase();
filename = filename + '.pdf';

pdfMake.createPdf(docDefinition).download(filename);
```

This was also helpful:

```JS
var docDefinition = {
  info: {
    title: 'awesome Document',
    author: 'john doe',
    subject: 'subject of document',
    keywords: 'keywords for document',
  },
  content:  'This is an sample PDF printed with pdfMake' 
}
```
