### ISSUE TITLE
[internal] npm permissions

### ISSUE THREAD

**Issue by liborm85** [bpampuch/pdfmake#783]
@bpampuch We will need release new version  in future over https://www.npmjs.com/package/pdfmake, you can add permissions for these accounts?
https://www.npmjs.com/~liborm85
https://www.npmjs.com/~miltador
https://www.npmjs.com/~danawoodman

I hope you can "hear" me @bpampuch.

Thanks.

// cc @miltador, @danawoodman

**Comment by bpampuch** [comment]
Sure, I'm off right now, I'll do it tomorrow, late evening. Thanks a lot
for you work and amazing pace :)

**Comment by bpampuch** [comment]
done
