### ISSUE TITLE
Multiple Language Support in Same PDF

### ISSUE THREAD

**Issue by barani2824** [bpampuch/pdfmake#787]
I am using PDFMake for generating the PDF.I have to Support four languages and successfully i am able to do this.but one small problem i am facing Some of the values I dont want to translate to other language it has to continue as English.For Example I am generating PDF in thai language .in pdf I dont want to convert a header text .if i use thai font header text also getting converted into thai language.If I get any help regarding this issue it would be very great for me.
Thanks in Advance.
With Regards,
Baranitharan.k

**Comment by liborm85** [comment]
I do not understand your question. What you translate? If the header of a text is the same everywhere, it will never translate.

**Comment by liborm85** [comment]
No reaction. No specific information.
