### ISSUE TITLE
Pdfkit is now compatible with otf and woff font !

### ISSUE THREAD

**Issue by jbinard** [bpampuch/pdfmake#788]
Pdfkit now allows to use otf and woff fonts.

If you build pdfmake from source, it works out of the box !

Can you tag a new version on bower to provide these new features ?

**Comment by liborm85** [comment]
Release of new version will probably on Friday.

**Comment by jbinard** [comment]
After a new test, it seems that woff2 doesn't work. My previous test was with otf.

I will try to find what is wrong with woff2.

**Comment by liborm85** [comment]
New version released.
