### ISSUE TITLE
Problem when page break on colspan and rowspan

### ISSUE THREAD

**Issue by solidet** [bpampuch/pdfmake#790]
I create pdf doc, and the content is not fixed. It is according to the item that loop inside the doc. so the height is not fixed, too. Actually, when i have many items (row), the height increases. when it comes to page break on the colspan, I get something strange like the image attached. Could you help me with that?
Thanks in advanced for any answers.

![pdfmake-colspan](https://cloud.githubusercontent.com/assets/13518075/21374946/d52c64ba-c75c-11e6-9194-6ea0a07311de.png)

**Comment by rUI-Bullet** [comment]
Hello,
I'm having the same. 
If a column with rowspan passes to another page, the table layout breaks.
Any news of when this issue will be fixed?
![screen shot 2017-02-20 at 17 08 20](https://cloud.githubusercontent.com/assets/20336574/23135120/3d794544-f78f-11e6-876a-3873ecd8c5e2.png)

Thanx

**Comment by vmontal** [comment]
Hi,
I'm having the same, too.
It's very annoying!!!!

**Comment by vmontal** [comment]
CLOSED:
dontBreakRows: true,
it's working!

**Comment by rUI-Bullet** [comment]
In my case dontBreakRows doesn´t work because it changes the cell height. 
I need that all cells have the exact same height.

**Comment by rUI-Bullet** [comment]
Hi,
Any news on this issue?
Thanx

**Comment by liborm85** [comment]
@solidet Table is rendered correctly. I tried create similar table in Microsft Word and the result is exactly the same. The current table can have only header. Footer not.

**Comment by rUI-Bullet** [comment]
Try this example:

var dd = {
    pageSize: 'A5',
    pageOrientation: 'landscape',
    pageMargins: [ 40, 60, 40, 60 ],
	content: [
		{text: 'Title', style: 'header'},
		{
			table: {
				widths: ['auto', 'auto'],
				headerRows: 1,
				body: [
				    [{text: '#', style: 'tableHeader'}, {text: 'Lorem Ipsum', style: 'tableHeader'}],
				    ['1', 'Lorem Ipsum Dolor Sit Amet'],
				    ['2', 'Lorem Ipsum Dolor Sit Amet'],
				    ['3', 'Lorem Ipsum Dolor Sit Amet'],
				    ['4', 'Lorem Ipsum Dolor Sit Amet'],
				    ['5', 'Lorem Ipsum Dolor Sit Amet'],
				    ['6', 'Lorem Ipsum Dolor Sit Amet'],
				    ['7', 'Lorem Ipsum Dolor Sit Amet'],
				    ['8', 'Lorem Ipsum Dolor Sit Amet'],
				    ['9', 'Lorem Ipsum Dolor Sit Amet'],
				    ['10', 'Lorem Ipsum Dolor Sit Amet'],
				    ['12', 'Lorem Ipsum Dolor Sit Amet'],
				    ['13', {rowSpan: 5, text : 'Lorem Ipsum Dolor Sit Amet \n Lorem Ipsum Dolor Sit Amet \n Lorem Ipsum Dolor Sit Amet. \n Lorem Ipsum Dolor Sit Amet \n Lorem Ipsum Dolor Sit Amet' }],
				    ['14', ''],
				    ['15', ''],
				    ['16', ''],
				    ['17', ''],
				    ['18', 'Lorem Ipsum Dolor Sit Amet'],
				    ['19', 'Lorem Ipsum Dolor Sit Amet'],
				    ['20', 'Lorem Ipsum Dolor Sit Amet']
				]
			}
		}
	],
	styles: {
		header: {
			fontSize: 18,
			bold: true,
			margin: [0, 0, 0, 10]
		},
		tableHeader: {
			bold: true,
			fontSize: 13
		}
	}
}

**Comment by rUI-Bullet** [comment]
![e01](https://cloud.githubusercontent.com/assets/20336574/24359565/a5742cf8-12fc-11e7-88b6-226c030c127e.png)
![e02](https://cloud.githubusercontent.com/assets/20336574/24359576/a90c54d0-12fc-11e7-8926-e27871e9dd8b.png)

**Comment by rUI-Bullet** [comment]
If the text in a rowspan cell doesn't pass to the other page, theres's no problem at all.
But when that happens, the vertical borderers of the table extend to the end of the page. After cell #20, there's no more information on the table, but the vertical borders continue to extend.

**Comment by rUI-Bullet** [comment]
![e03](https://cloud.githubusercontent.com/assets/20336574/24359897/a0f210ea-12fd-11e7-9619-2d44b878f3a6.png)

**Comment by rUI-Bullet** [comment]
And if you add a fillColor to that cell with rowspan (from 13 to 17), the background (has it happens with the vertical border) extends to the other cells, and to the end of the page.

**Comment by Balaraju1** [comment]
![pdf](https://cloud.githubusercontent.com/assets/20854774/24497845/6061dc72-155a-11e7-8651-a2e3bb46cb35.png)
how to solve this issue..?

**Comment by vmontal** [comment]
dontBreakRows: true,
it's working!

**Comment by rUI-Bullet** [comment]
dontBreakRows: true doesn´t work.
It fixes the vertical borderers and background expanded, but screws the cell text.

![screen shot 2017-03-31 at 09 28 28](https://cloud.githubusercontent.com/assets/20336574/24542714/99e3a8dc-15f4-11e7-8a05-4a65dbbbdc2f.png)

**Comment by vmontal** [comment]
if the colSpan / rowSpan option is only in the table header, so "dontBreakRows: true" it'sworking. Try it!

**Comment by rUI-Bullet** [comment]
In my case, the rowspan is not in the table header, but in rows 13 to 17.

**Comment by liborm85** [comment]
Problem width "red rows" have issue https://github.com/bpampuch/pdfmake/issues/928. This issue orginal have something else topic.

Closed.
