### ISSUE TITLE
Whats happened to pdfmake-dist?

### ISSUE THREAD

**Issue by chris5287** [bpampuch/pdfmake#791]
The pdfmake-dist repo has disappeared, and now my CI builds are failing :(

I also noticed that pdfmake-dist was at v0.1.31, but this repo is only at v0.1.20. 

Can anyone explain what is happening?

**Comment by miltador** [comment]
pdfmake-dist, which is a fork of this repo, has been merged back. New version will be out on Friday. Before that you can just use current master.

**Comment by chris5287** [comment]
Thanks for the update. It might have been best to leave the fork until the new version was out, and even then leave a note in the README of that repo that the changes had been merged back here.

I'll wait for the new version of Friday

**Comment by liborm85** [comment]
New version released.
