### ISSUE TITLE
Grunt

### ISSUE THREAD

**Issue by liborm85** [bpampuch/pdfmake#794]
Gruntfile.js file is not updated over 2 years, everything can be done through webpack and gulp (with version 0.1.22).

Someone uses a grunt?
I propose to remove Gruntfile.js and all its dependencies.

What do you think?

**Comment by liborm85** [comment]
No reaction. Probably no one would have a problem when I delete a grunt. :)

**Comment by Chris--A** [comment]
I'm happy with gulp. It is what I use in my projects. Have never used grunt.
Its still in the history, so if it turns out we need it, its simple to dig out of the trash.

**Comment by liborm85** [comment]
Grunt removed. https://github.com/bpampuch/pdfmake/commit/a6e1ee23641b5bdaec0049dec1c8a3ad37ce64cb
