### ISSUE TITLE
transform into a File?

### ISSUE THREAD

**Issue by ptitdje45** [bpampuch/pdfmake#795]
Hello, 

i'm trying unsuccessfull to transform the .pdf into File to download it with ng-file-upload ( i use the Upload.upload(file) -- file is a File. 

I want to do that because my Upload.upload is already configured.

Is there a way to do it properly ?

Thx

**Comment by liborm85** [comment]
If you want to download the file, but to work with its content can be used `getBase64` or `getBuffer`.
see https://github.com/bpampuch/pdfmake#document-definition-object
