### ISSUE TITLE
link issue

### ISSUE THREAD

**Issue by marwenlandoulsi** [bpampuch/pdfmake#796]
Hi
when we npm install we got old version building.that was without link to

PS: without that below
{
text:"google",
link:"http://google.com"
}

Can you guys update npm with newest building version

**Comment by liborm85** [comment]
link does not work again...

**Comment by liborm85** [comment]
Fixed by commit: https://github.com/bpampuch/pdfmake/commit/af014e2bd18bd32113c3712a5c73fbbe56232df8
