### ISSUE TITLE
Image and text on same line 

### ISSUE THREAD

**Issue by gshchaudhari** [bpampuch/pdfmake#802]
I am unable to add images and text on same line. I have 5 images and text that i need to print on same line, instead of every image on next line. I found some tricks to add using column and table but its not relevant. My content is dynamic.
I hope next version will come up with proper solution to it.

**Comment by liborm85** [comment]
Do you have any simple example to reproduce problem?
You can use http://pdfmake.org/playground.html.

**Comment by gshchaudhari** [comment]
Here is my example 

'This is my testing text to show images and text should be on same line',
		{
			image: 'sampleImage.jpg',
			fit: [50, 50],
		},
		'It should also work for multiple images',
	       {
			image: 'sampleImage.jpg',
			fit: [50, 50],
	       },
		'Images can be also provided in dataURL format...'

**Comment by liborm85** [comment]
Continued here: https://github.com/bpampuch/pdfmake/issues/358

**Comment by JRivasS** [comment]
Aquí un ejemplo :D 

customize: function ( doc ) {
                                doc.content.splice( 1, 0, {
                                    margin: [ 0, 0, 0, 12 ],
                                    alignment: 'center',
                                    imagen: 'tu imagen en b64'
                                }, {
                                    margin: [10, 15],
                                    padding: [10, 20],
                                    text: 'Programación Naves: Datos Históricos',
                                    fontSize: 15
                                } );
                            }

**Comment by JRivasS** [comment]
> customize: function ( doc ) {
                                doc.content.splice( 1, 0, {
                                    margin: [ 0, 0, 0, 12 ],
                                    alignment: 'center',
                                    imagen: 'tu imagen en b64'
                                }, {
                                    margin: [10, 15],
                                    padding: [10, 20],
                                    {#margin_left: [30],#}
                                    text: 'Programación Naves: Datos Históricos',
                                    {#color: red,#}
                                    fontSize: 15
                                } );
                            }

**Comment by suraw** [comment]
i think better c heck this link. https://pdfmake.github.io/docs/document-definition-object/stack/
