### ISSUE TITLE
Warning: Unable to read "/bower_components/pdfmake/build/index.js.map" file (Error code: ENOENT).

### ISSUE THREAD

**Issue by jamesvanleuven** [bpampuch/pdfmake#804]
So this file doesn't exist...

at all.. so what is the point of referencing it in the pdfMake.js if it doesn't exist? which brings up the second question - why do you have a pdfmake.min.js.map when it's not referenced?

**Comment by liborm85** [comment]
File `pdfmake.min.js` contains reference to `map` file. At the end of the file is:
```
//# sourceMappingURL=pdfmake.min.js.map
```

**Comment by liborm85** [comment]
New version released.
