### ISSUE TITLE
Using Rotate, Translate and Path from pdfMake.js

### ISSUE THREAD

**Issue by Makrel** [bpampuch/pdfmake#807]
Is there an example where the canvas items use the transform, translate or rotate on items in a pdfMake canvas? Can't seem to nail this one down...this is for client side JS.

ex:
`canvas: [
	{
		type: 'rect',
		x: 150,
		y: 200,
		w: 150,
		h: 50,
		rotate:45
	}
]`

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/502 and https://github.com/bpampuch/pdfmake/issues/375
