### ISSUE TITLE
Dynamic headers and footers

### ISSUE THREAD

**Issue by mevillep** [bpampuch/pdfmake#808]
I am passing an array of multiple objects to my docDefinition Object. I am wanting to put dynamic data for the headers and footers from these multiple objects.

Footer code:

  docDefinition.footer = function (page, pages) {
                            return {
                               style: 'fRepeat',
                            table: {
                                widths: [250, 300, 250, 302],
                                body: [
                                    [Send Correspondence to Buyer,key.buyerName, Buyer Email, key.buyerEmailAddress],
                                    [Sourcing Signature/Date, some text1, Supplier Signature/Date, some text 2]
  ]
                                   }
                                  }

     }                  

Above, the key.buyerName and key.buyerEmailAddress are present in every object that I pass to docDefinition. Hence, I want the footer to be unique per object passed.
Example, If I pass 3 objects to the docDefinition, I am expecting to get 3 pdf's with unique footer data on each one of them.
Instead what I observe is that the footer data on the third object is repeated on all the three pdf's.

P.s.: I got rid of quotes around the text in the code above.
Kindly help. @bpampuch

**Comment by liborm85** [comment]
I can not simulate your problem, can you do some example executable on http://pdfmake.org/playground.html ?

**Comment by mevillep** [comment]
`var pdfObjects = [{
    "foot":"0",
    "poRevisionType": "NON-CORE",
    "poRevisionNumber": 0,
    "poRevisionDate": null,
    "poNumber": "111111",  //THIS IS TH DATA IN THE HEADERS 
    "poReleaseNumber": 0,
    "creationDate": '1473638400000',
    "poTypeCode": "STANDARD",
    "buyerId": '11127493',
    "buyerName": "AAAAAA" , //THIS IS TH DATA IN THE FOOTER 
    "vendorId": '436706',
    "vendorName": "LEMAC PACKAGING",
    "vendorGslId": "023047",
    "poLineTypeCode": null,
    "billToLocationId": '0',
    "billToLocDescription": null,
    "billToLocAddrLine1": null,
    "billToLocAddrLine2": null,
    "billToLocAddrLine3": null,
    "billToLocAddrLine4": null,
    "billToLocAddrCityName": null,
    "billToLocAddrStateCode": null,
    "billToLocAddrProvinceCode": null,
    "billToLocAddrPostalCode": null,
    "billToLocAddrCountryCode": null,
    "shipToLocationId": '2226000',
    "shipToLocDescription": null,
    "shipToLocAddrLine1": "1503 W. MAIN ST. EXT.",
    "shipToLocAddrLine2": " ",
    "shipToLocAddrLine3": " ",
    "shipToLocAddrLine4": " ",
    "shipToLocAddrCityName": "GROVE CITY",
    "shipToLocAddrStateCode": "PA",
    "shipToLocAddrProvinceCode": null,
    "shipToLocAddrPostalCode": "16127",
    "shipToLocAddrCountryCode": "US",
    "shipFromLocId": '473358',
    "shipFromLocAddrLine1": "P.O. BOX 10788",
    "shipFromLocAddrLine2": " ",
    "shipFromLocAddrLine3": " ",
    "shipFromLocAddrLine4": " ",
    "shipFromLocAddrCityName": "ERIE",
    "shipFromLocAddrStateCode": "PA",
    "shipFromLocAddrProvinceCode": null,
    "shipFromLocAddrPostalCode": "16514",
    "shipFromLocAddrCountryCode": "US",
    "approvedById": "11127493",
    "mailInvoiceToLocId": '2226000',
    "vatNumber": null,
    "vatAmount": null,
    "netTotalAmount": '204',
    "currencyCode": "USD",
    "incotermsCode": null,
    "poHeaderNote": null,
    "dd": null,
    "tncTxt": "SOME TEXT THERE" ,
    "fobLookupCode": null,
    "approvedByName": "Magaly Escamilla",
    "approverPositionDescription": "Sr. Buyer",
    "shipmentPriorityDescription": null,
    "shippingInstructionDescription": null,
    "packingInstructionDescription": null,
    "buyerEmailAddress": "magaly.escamilla1@ge.com",
    "poLine": [{
        "poLineNumber": '32',
        "itemDescription": "LABEL          CAUTION",
        "itemRevisionCode": "0",
        "itemPartNumber": "84A233484P4",
        "approvedMfgName": null,
        "mfgPartNumber": null,
        "lineQuantity": '140',
        "lineNoteToVendorTxt": null,
        "drawingRevisionNumber": "0",
        "poLineNote": null,
        "unitPriceAmount": '23',
        "totalPrice": '204',
        "lineTypeCode": "Goods",
        "shipment": [{
            "poShipmentNumber": '1',
            "poShipmentNote": null,
            "needByDate": '1479859200000',
            "promiseDate": null,
            "shipQuantity": '140',
            "uomCode": "PC",
            "shipToLocationId": 0,
            "shipToLocDescription": null,
            "shipToLocAddrLine1": "1503 W. MAIN ST. EXT.",
            "shipToLocAddrLine2": null,
            "shipToLocAddrLine3": null,
            "shipToLocAddrLine4": null,
            "shipToLocAddrCityName": "GROVE CITY",
            "shipToLocAddrStateCode": "PA",
            "shipToLocAddrProvinceCode": null,
            "shipToLocAddrPostalCode": "16127",
            "shipToLocAddrCountryCode": "US",
            "workOrderNumber": null
        }
        ]
    }]
},
{
    "foot":"1",
    "poRevisionType": "NON-CORE",
    "poRevisionNumber": 0,
    "poRevisionDate": null,
    "poNumber": "222222",  //THIS IS TH DATA IN THE HEADERS 
    "poReleaseNumber": 0,
    "creationDate": '1473638400000',
    "poTypeCode": "STANDARD",
    "buyerId": '11127493',
    "buyerName": "BBBBBB", //THIS IS TH DATA IN THE FOOTER 
    "vendorId": '436706',
    "vendorName": "LEMAC PACKAGING",
    "vendorGslId": "023047",
    "poLineTypeCode": null,
    "billToLocationId": '0',
    "billToLocDescription": null,
    "billToLocAddrLine1": null,
    "billToLocAddrLine2": null,
    "billToLocAddrLine3": null,
    "billToLocAddrLine4": null,
    "billToLocAddrCityName": null,
    "billToLocAddrStateCode": null,
    "billToLocAddrProvinceCode": null,
    "billToLocAddrPostalCode": null,
    "billToLocAddrCountryCode": null,
    "shipToLocationId": '2226000',
    "shipToLocDescription": null,
    "shipToLocAddrLine1": "1503 W. MAIN ST. EXT.",
    "shipToLocAddrLine2": " ",
    "shipToLocAddrLine3": " ",
    "shipToLocAddrLine4": " ",
    "shipToLocAddrCityName": "GROVE CITY",
    "shipToLocAddrStateCode": "PA",
    "shipToLocAddrProvinceCode": null,
    "shipToLocAddrPostalCode": "16127",
    "shipToLocAddrCountryCode": "US",
    "shipFromLocId": '473358',
    "shipFromLocAddrLine1": "P.O. BOX 10788",
    "shipFromLocAddrLine2": " ",
    "shipFromLocAddrLine3": " ",
    "shipFromLocAddrLine4": " ",
    "shipFromLocAddrCityName": "ERIE",
    "shipFromLocAddrStateCode": "PA",
    "shipFromLocAddrProvinceCode": null,
    "shipFromLocAddrPostalCode": "16514",
    "shipFromLocAddrCountryCode": "US",
    "approvedById": "11127493",
    "mailInvoiceToLocId": '2226000',
    "vatNumber": null,
    "vatAmount": null,
    "netTotalAmount": '204',
    "currencyCode": "USD",
    "incotermsCode": null,
    "poHeaderNote": null,
    "dd": null,
   "tncTxt": "SOME TEXT THERE" ,
    "fobLookupCode": null,
    "approvedByName": "Magaly Escamilla",
    "approverPositionDescription": "Sr. Buyer",
    "shipmentPriorityDescription": null,
    "shippingInstructionDescription": null,
    "packingInstructionDescription": null,
    "buyerEmailAddress": "magaly.escamilla1@ge.com",
    "poLine": [{
        "poLineNumber": '32',
        "itemDescription": "LABEL          CAUTION",
        "itemRevisionCode": "0",
        "itemPartNumber": "84A233484P4",
        "approvedMfgName": null,
        "mfgPartNumber": null,
        "lineQuantity": '140',
        "lineNoteToVendorTxt": null,
        "drawingRevisionNumber": "0",
        "poLineNote": null,
        "unitPriceAmount": '23',
        "totalPrice": '204',
        "lineTypeCode": "Goods",
        "shipment": [{
            "poShipmentNumber": '1',
            "poShipmentNote": null,
            "needByDate": '1479859200000',
            "promiseDate": null,
            "shipQuantity": '140',
            "uomCode": "PC",
            "shipToLocationId": 0,
            "shipToLocDescription": null,
            "shipToLocAddrLine1": "1503 W. MAIN ST. EXT.",
            "shipToLocAddrLine2": null,
            "shipToLocAddrLine3": null,
            "shipToLocAddrLine4": null,
            "shipToLocAddrCityName": "GROVE CITY",
            "shipToLocAddrStateCode": "PA",
            "shipToLocAddrProvinceCode": null,
            "shipToLocAddrPostalCode": "16127",
            "shipToLocAddrCountryCode": "US",
            "workOrderNumber": null
        }]
    }]
}]

                var dd = {
                    pageOrientation: 'landscape',
                    pageSize: 'A3',
                     pageMargins: [150, 170, 0, 40]
                    }


                dd.content = [];

                dd.styles = {
                    small: {
                        fontSize: 8
                    },
                    sellerHeader: {
                        fontSize: 12,
                        bold: true,
                        margin: [-120, -10, 0, 5]  //change
                    },
                    hRepeat: {
                        margin: [30, 30, 30, 40],
                        bold: true 
                    },
                    fRepeat: {
                        margin: [30, -5, 30, 40],
                         bold: true
                    },  
                    shipmentHeader: {
                        fontSize: 12,
                        bold: true,
                        margin: [-120, 5, 0, 5]

                    },
                    supplierNote: {
                        fontSize: 12,
                        bold: true,
                        margin: [-120, 5, 0, 5]
                    },
                    invoiceNotes: {
                        fontSize: 12,
                        bold: true,
                        margin: [-120, 5, 0, 5]
                    },
                    headerLine: {
                        fontSize: 14,
                        bold: true,
                        margin: [-120, 10, 10, 5]
                    },
                    shipHeader: {
                        fontSize: 12,
                        bold: true,
                        margin: [-70, 5, 30, 5]

                    },
                    lineNotesHeader: {
                        fontSize: 14,
                        bold: true,
                        margin: [-10, 5, 0, 30]
                    },
                    totalHeader: {
                        margin: [-120, 5, 0, 5],
                        fontSize: 14
                    },
                    tncHeader: {
                        fontSize: 14,
                        bold: true,
                        margin: [-120, 5, 0, 5],
                    },
                    buyerHeader: {
                        fontSize: 14,
                        bold: true,
                        margin: [-120, 5, 0, 25],
                    },


                    subheader: {
                        fontSize: 14,
                        bold: true,
                        margin: [0, 10, 0, 5]
                    },
                    tableExample: {
                        margin: [0, 5, 0, 15],
                        fontSize: 14
                    },

                    tableHeader: {
                        bold: true,
                        color: 'black',
                        fillColor: '#ceebfd'

                    }, tableHeader1: {
                        bold: true,
                        color: 'black',
                        fillColor: '#ceebfd'

                    },

                    greyArea: {
                        fillColor: '#d9d9d9'
                    },
                    greyAreaHead: {
                        fillColor: '#d9d9d9',
                        fontSize: 22
                    }
                };

                /**
                 *
                 *
                 *
                 *
                 *
                 *
                 * */
                var convertToStringDate = function (date) {
                    if (date) {
                        var today = new Date(date);

                    } else {
                        return null;
                    }
                    var dd = today.getUTCDate(),
                        mm = today.getUTCMonth() + 1, //January is 0!
                        yyyy = today.getUTCFullYear(),
                        dateString;

                    if (dd < 10) {
                        dd = '0' + dd;
                    }
                    if (mm < 10) {
                        mm = '0' + mm;
                    }

                    dateString = mm + '-' + dd + '-' + yyyy;


                    return dateString;
                };


                var replaceNull = function (data) {
                    if (data != null && data) {
                        return data.toString();
                    }
                    else {
                        return '';
                    }
                }

                if (!pdfObjects) {

                    dd.content.push(
                        {
                            text: 'Sorry, no data is available right now!',
                            style: 'header'
                        }
                    );
                }
                $scope.footArray = []
                angular.forEach(pdfObjects, function (key, value) {    // footer loop
                    $scope.footArray.push( { 
                            
                              style: 'fRepeat',
                            table: {
                                widths: [250, 300, 250, 302],
                                body: [
                                    ['Send Correspondence to Buyer', replaceNull(key.buyerName), 'Buyer Email', replaceNull(key.buyerEmailAddress)],
                                    ['GE Sourcing Signature/Date', '', 'Supplier Signature/Date', '']

                                      ]
                                  } 
                            

                        })
                })
                var index = 0;
                angular.forEach(pdfObjects, function (key, value) {   // main loop
                   
                    var k = key.vatAmount + key.netTotalAmount;


                  if(key.foot == 0) {   
                        dd.footer = function(page,pages){ return $scope.footArray[0]  }  //////
                            }
                            else if(key.foot == 1)
                             {   
                      //  dd.footer = function(page,pages){ return $scope.footArray[1]  }  //////
                            }
                    dd.header =
                        function (page, pages) {
                            return {

                                style: 'hRepeat',
                                color: '#444',
                                table: {
                                    widths: [120, 250, 370, 178, 180],

                                    body: [
                                        [{
                                            rowSpan: 8,
                                            margin: [0, 20, 0, 15],
                                            text: 'APP',
                                            width: 80,
                                            height: 80,
                                            alignment: 'center'
                                        },
                                            {
                                                rowSpan: 8,
                                                text: 'Bill To : \n' + replaceNull(key.billToLocDescription) + '\n' + replaceNull(key.billToLocAddrLine1) + '\n' + replaceNull(key.billToLocAddrLine2) + '\n' + replaceNull(key.billToLocAddrCityName) + ', ' + replaceNull(key.billToLocAddrStateCode) + ',' + replaceNull(key.billToLocAddrPostalCode) + '\n' + replaceNull(key.billToLocAddrCountryCode)
                                            }, {
                                            rowSpan: 8,
                                            alignment: 'center',
                                            style: 'greyAreaHead',
                                            text: '\nPurchase Order\n' + replaceNull(key.poTypeCode) + ' Order Release \n'
                                        }, {rowSpan: 1, text: 'Order Number'}, {
                                            rowSpan: 1,
                                            text: replaceNull(key.poNumber)
                                        }],
                                        [{}, {}, {}, {rowSpan: 1, text: 'Order Date'}, {
                                            rowSpan: 1,
                                            text: replaceNull(convertToStringDate(key.creationDate))
                                        }],
                                        [{}, {}, {}, {rowSpan: 1, text: 'Release Number'}, {
                                            rowSpan: 1,
                                            text: key.foot
                                        }],
                                        [{}, {}, {}, {rowSpan: 1, text: 'Revision'}, {
                                            rowSpan: 1,
                                            text: replaceNull(key.poRevisionNumber)
                                        }],
                                        [{}, {}, {}, {rowSpan: 1, text: 'Revision Date'}, {
                                            rowSpan: 1,
                                            text: replaceNull(convertToStringDate(key.poRevisionDate))
                                        }],
                                        [{}, {}, {}, {rowSpan: 3, colspan: 2, text: 'Page'}, {
                                            rowSpan: 3,
                                            text: page.toString() + ' of ' + pages.toString()
                                        }],
                                        [{}, {}, {}, {}, {}],
                                        [{}, {}, {}, {}, {}]
                                    ]
                                }
                            }
                        }, 
                            
                        //     if(key.foot == 0) {   
                        // dd.footer = function(page,pages){ return $scope.footArray[key.foot]  }  //////
                        //     }
                        // dd.content.push($scope.footArray[1])
                        index ++;
                    dd.content.push(
                        {

                            style: 'sellerHeader',
                            table: {
                                headerRows: 1,
                                widths: [375, 370, 370],

                                body: [
                                    [{text: 'Seller', style: 'tableHeader'}, {
                                        text: 'Ship To:',
                                        style: 'tableHeader'
                                    }, {text: 'Invoice To', style: 'tableHeader'}],
                                    [{text: key.foot+'<<<<<<<<<<<' + replaceNull(key.vendorName) + '\n' + replaceNull(key.shipFromLocAddrLine1) + '\n' + replaceNull(key.shipFromLocAddrLine2) + '\n' + replaceNull(key.shipFromLocAddrLine3) + replaceNull(key.shipFromLocAddrCityName) + ', ' + replaceNull(key.shipFromLocAddrStateCode) + ', ' + replaceNull(key.shipFromLocAddrPostalCode) + '\n' + replaceNull(key.shipFromLocAddrCountryCode)},
                                        {text: replaceNull(key.shipToLocDescription) + '\n' + replaceNull(key.shipToLocAddrLine1) + '\n' + replaceNull(key.shipToLocAddrLine2) + '\n' + replaceNull(key.shipToLocAddrLine3) + replaceNull(key.shipToLocAddrCityName) + ', ' + replaceNull(key.shipToLocAddrStateCode) + ', ' + replaceNull(key.shipToLocAddrPostalCode) + '\n' + replaceNull(key.shipToLocAddrCountryCode)},
                                        {text: replaceNull(key.mailInvoiceToLocId) + '\n'}]

                                ]
                            }
                        },

                        {
                            style: 'shipmentHeader',
                            color: '#444',
                            table: {
                                headerRows: 1,
                                widths: [180, 185, 180, 185, 180, 175],

                                body: [[{text: 'Ship Via', style: 'tableHeader'}, {
                                    colSpan: 5,
                                    text: replaceNull(key.shipToLocDescription) + '\n' + replaceNull(key.shipToLocAddrLine1) + '\n' + replaceNull(key.shipToLocAddrLine2) + '\n' + replaceNull(key.shipToLocAddrLine3) + replaceNull(key.shipToLocAddrCityName) + ', ' + replaceNull(key.shipToLocAddrStateCode) + ', ' + replaceNull(key.shipToLocAddrPostalCode) + '\n' + replaceNull(key.shipToLocAddrCountryCode)
                                }, {}, {}, {}, {}],
                                    [{
                                        text: 'Approved By ',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.approvedByName)}, {
                                        text: 'Approver Position',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.approverPositionDescription)}, {
                                        text: 'GE Supplier Code',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.vendorGslId)}],
                                    [{
                                        text: 'Currency ',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.currencyCode)}, {
                                        text: 'Incoterms',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.incotermsCode)}, {
                                        text: 'Payment Terms',
                                        style: 'tableHeader'
                                    }, {text: 'PAYMENT_TERMS'}],


                                ]
                            }
                        },

                        {
                            style: 'supplierNote',
                            color: '#444',
                            table: {
                                headerRows: 1,
                                widths: [1130],

                                body: [[{text: 'Special Note to Supplier:', style: 'tableHeader'}],
                                    [

                                        {
                                            style: 'tableExample',
                                            text: replaceNull(key.poHeaderNote) + ' \n' + 'Shipping Instructions :' + replaceNull(key.shippingInstructionDescription) + ' \n' + 'Shipping Priorities :' + replaceNull(key.shipmentPriorityDescription) + ' \n' + 'Packing Instructions :' + replaceNull(key.packingInstructionDescription) + ' \n' + 'Customer PO :' + replaceNull(key.poNumber) + ' \n' + 'FOB :' + replaceNull(key.fobLookupCode) + ' \n' + 'Fright Terms :' + replaceNull(key.billToLocDescription)
                                        }
                                    ]
                                ]
                            }
                        },


                        {
                            style: 'invoiceNotes',
                            color: '#444',
                            table: {
                                headerRows: 1,
                                widths: [1130],

                                body: [[{text: 'Shipment / Invoice Notes ', style: 'tableHeader'}],
                                    [
                                        {
                                            style: 'tableExample', stack: [
                                            {
                                                ul: [
                                                    'Our Order and Release Numbers must appear on all correspondence, invoices, packages and shipping memoranda.',
                                                    'Foreign Suppliers must send Certificate of Origin with each shipment',
                                                    'Packing List and Commercial Invoice must accompany each shipment',
                                                    'Two original (blue ink) signed invoices should be prepared.  One sent together with the cargo and the other sent by courier to the indicated address', 'Seller will not invoice until after Products and Services delivery'

                                                ]
                                            }
                                        ]
                                        }
                                    ]
                                ]
                            }
                        },
                        {text: '', pageBreak: 'before'}
                    )
                    angular.forEach(key, function (innerkey, innervalue) {
                        // console.log(innerkey);
                        // console.log(innervalue);
                        if (innervalue == 'poLine') {

                            angular.forEach(innerkey, function (ininnerkey, ininnervalue) {


                                dd.content.push(
                                    {
                                        style: 'headerLine',
                                        color: '#444',
                                        id: 'signature',
                                        table: {
                                             headerRows: 1,
                                            widths: [70, '*', '*', '*', 100, '*', 50, '*', '*'],

                                            body: [[{text: 'Line MEville', style: 'tableHeader'}, {
                                                text: 'Line Type',
                                                style: 'tableHeader'
                                            }, {text: 'Part Number', style: 'tableHeader'}, {
                                                text: 'Description',
                                                style: 'tableHeader'
                                            }, {text: 'Rev', style: 'tableHeader'}, {
                                                text: 'Manufacturer Part Number',
                                                style: 'tableHeader'
                                            }, {text: 'Total Quantity', style: 'tableHeader'}, {
                                                text: 'Unit Price',
                                                style: 'tableHeader'
                                            }, {text: 'Total Price', style: 'tableHeader'}],
                                                [{
                                                    text: replaceNull(ininnerkey.poLineNumber),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.lineTypeCode),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.itemPartNumber),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.itemDescription),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.itemRevisionCode),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.mfgPartNumber),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.lineQuantity),
                                                    style: 'subheader'
                                                }, {
                                                    text: replaceNull(ininnerkey.unitPriceAmount),
                                                    style: 'subheader'
                                                }, {text: replaceNull(ininnerkey.totalPrice), style: 'subheader'}]
                                                // [{text: 'shipment', style: 'tableHeader1',colSpan:2 },{},{ text: 'Due Date',style: 'tableHeader1' ,colSpan:2 },{},{text: 'Shipment Quantity',style: 'tableHeader1',colSpan:2 },{},{text: 'UOM',style: 'tableHeader1',colSpan:2 },{},{text: 'Shipto',style: 'tableHeader1',colSpan:2 },{}]


                                            ]
                                        }

                                    }
                                ); //pushing the line


                                angular.forEach(ininnerkey, function (inininnerkey, inininnervalue) {

                                    if (inininnervalue === 'shipment') {
                                        angular.forEach(inininnerkey, function (ininininnerkey, ininininnervalue) {
                                            dd.content.push(
                                                {
                                                     pageBreak: 'after', 
                                                    //  pageOrientation: 'portrait'    ,
                                                    style: 'shipHeader',
                                                    color: '#444',
                                                    table: {
                                                        headerRows: 1,
                                                        widths: [120, 120, 120, 120, 120, 240, 100],
                                                        height: [200],
                                                        body: [[{
                                                            text: 'Shipment ',
                                                            style: 'tableHeader'
                                                        }, {
                                                            text: 'Due Date',
                                                            style: 'tableHeader'
                                                        }, {
                                                            text: 'Promise Date',
                                                            style: 'tableHeader'
                                                        }, {
                                                            text: 'Shipment Quantity',
                                                            style: 'tableHeader'
                                                        }, {text: 'UOM', style: 'tableHeader'}, {
                                                            text: 'ShipTo',
                                                            style: 'tableHeader'
                                                        }, {text: 'Work Order No', style: 'tableHeader'}],
                                                            [{
                                                                text: replaceNull(ininininnerkey.poShipmentNumber),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(convertToStringDate(ininininnerkey.needByDate)),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(convertToStringDate(ininininnerkey.promiseDate)),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(ininininnerkey.shipQuantity),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(ininininnerkey.uomCode),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(ininininnerkey.shipToLocDescription) + '\n' + replaceNull(ininininnerkey.shipToLocAddrLine1) + '\n' + replaceNull(ininininnerkey.shipToLocAddrLine2) + '\n' + replaceNull(ininininnerkey.shipToLocAddrCityName) + ', ' + replaceNull(ininininnerkey.shipToLocAddrStateCode) + ', ' + replaceNull(ininininnerkey.shipToLocAddrPostalCode) + ', ' + replaceNull(ininininnerkey.shipToLocAddrCountryCode),
                                                                style: 'subheader'
                                                            }, {
                                                                text: replaceNull(ininininnerkey.workOrderNumber),
                                                                style: 'subheader'
                                                            }]

                                                        ]
                                                    }
                                                }
                                            );

                                        }); // for inner shipment

                                    }

                                });    // for outer shipment


                                dd.content.push(
                                    {
                                        style: 'lineNotesHeader',
                                        color: '#444',
                                        table: {
                                            headerRows: 1,
                                            widths: [1130],
                                            body: [[{text: 'Line Level Supplier Notes:', style: 'tableHeader'}],
                                                [
                                                    {
                                                        style: 'tableExample',
                                                        text: replaceNull(ininnerkey.lineNoteToVendorTxt) + '\n '
                                                    }
                                                ]
                                            ]
                                        }
                                    }
                                )
                                if (!ininnerkey.lineNoteToVendorTxt) {
                                    dd.content.pop()
                                }
                                //

                            });// for inner line


                        }


                    }); //for outer line


                    dd.content.push({
                            style: 'totalHeader',
                            color: '#444',
                            table: {
                                widths: [660, 230, 220],

                                body: [
                                    [{rowSpan: 3, text: '', style: 'greyArea'}, {
                                        text: 'Net Total:',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.netTotalAmount)}],
                                    [{rowSpan: 3, text: '', style: 'greyArea'}, {
                                        text: 'Tax/VAT (if applicable)',
                                        style: 'tableHeader'
                                    }, {text: replaceNull(key.vatAmount)}],
                                    [{rowSpan: 3, text: '', style: 'greyArea'}, {
                                        text: 'Grand Total',
                                        style: 'tableHeader',
                                        fontSize: '20'
                                    }, {text: replaceNull(k)}]
                                ]
                            }
                        },
                        {text: '', pageBreak: 'before'},

                        {
                            
                            style: 'tncHeader',
                            color: '#444',
                            table: {
                                headerRows: 1,
                                widths: [1130],

                                body: [[{text: 'Terms and Contitions Information:', style: 'tableHeader'}],
                                    [
                                        {style: 'tableExample', text: replaceNull(key.tncTxt)}
                                    ]
                                ]
                            }
                        }
                        // ,
                        // {
                        //     style: 'buyerHeader',
                        //     table: {
                        //         widths: [250, 300, 250, 302],
                        //         body: [
                        //             ['Send Correspondence to Buyer', replaceNull(key.buyerName), 'Buyer Email', replaceNull(key.buyerEmailAddress)],
                        //             ['GE Sourcing Signature/Date', '', 'Supplier Signature/Date', ''],

                        //         ]
                        //     }
                        // }
                        ,
                        {text: '', pageBreak: 'before'}
                    )

                });
                dd.content.pop();
                pdfMake.createPdf(dd);
               
         


            `

**Comment by mevillep** [comment]
https://plnkr.co/edit/v1jSWfulweS3vMflg2j1?p=catalogue


This is the link to the plunker. I am not sure if playground could persist the changes. 
Anyway, Look at the data in my headers and footers. The footer takes the data from the first Object, and the headers take data from the last object. All the other data that is consumed ex. tables , text etc is rendered perfectly.
@bpampuch 
@liborm85

**Comment by arjenzwerver** [comment]
I was also facing this problem and solved it with something like this:
```javascript
docDefinition.content.push({
                            text: aText,
                            fontSize: 18,
                            bold: true,
                            italics: true,
                            pageHeaderText: yourHeaderText
                        });
```
Next, the header function should look something like this:

```javascript
docDefinition.header = function(currentPage){
                        var rightText = "";
                        for(var l = 0; l < docDefinition.content.length; l++){
                            if(docDefinition.content[l].pageHeaderText && currentPage >= docDefinition.content[l].positions[0].pageNumber){
                                rightText = docDefinition.content[l].pageHeaderText;
                            }
                        }
                        var headerObj = {
                            columns: [
                                {
                                    stack: [
                                        {
                                            image: 'Logo',
                                            width: 100
                                        }
                                    ],
                                    alignment: 'left',
                                    width: 200
                                },
                                {
                                    text: rightText,
                                    color: '#666666',
                                    alignment: 'right',
                                    width: '*',
                                    margin: [0, 12]
                                }
                            ],
                            margin: [40, 20]
                        };
                        return headerObj;
                    }
```
@mevillep

**Comment by mevillep** [comment]
@arjenzwerver Thanks for the answer. It didn't help though. the header repeats itself whatsoever.

**Comment by jfaquinojr** [comment]
@arjenzwerver: docDefinition.content[l].positions doesnt seem to exist. did you add it manually yourself?

**Comment by arjenzwerver** [comment]
@jfaquinojr: No, but it is only available during/after pdfMake.createPdf(docDefinition) is called. Maybe you could check if the function is running before createPdf is called or not. For example through console.log.

**Comment by liborm85** [comment]
Feature request: https://github.com/bpampuch/pdfmake/issues/283

**Comment by dhyey35** [comment]
@arjenzwerver Thanks !! Works Great :)

**Comment by tedbakers** [comment]
This is a good answer, I used that pageHeaderText (renamed to pageHeader) and stored a stringified json object in it then in the header function JSON.parse that and replaced in any page numbers and returned the object, works well!

**Comment by adityavartak91** [comment]
Is it possible in PDFMake to display a small content first and then start with Page Header which will repeat in every page

**Comment by tedbakers** [comment]
> Is it possible in PDFMake to display a small content first and then start with Page Header which will repeat in every page

You should be able to do this using the method described by arjenzwerver above to get different headers, you'd just put that small content in the header for the page you want, you will probably need to increase the margins to get this to display correctly though, you'll just have to experiment.

**Comment by MildTomato** [comment]
I've just implemented this today, using what @arjenzwerver suggested.

You can also use this to build up an object of page numbers for each unique header you use, so you can calculate the length of pages for each section.

**Comment by wayneathomas** [comment]
I used @arjenzwerver method and it worked perfectly.

**Comment by boldham31** [comment]
Thanks @arjenzwerver and all for your responses. Very helpful for me in solving this. I wanted to also show my solution for how I got this working. I just needed to make two things dynamic - the page number in the footer, and the page title in the header. And then style header and footer uniquely. Here is what my header and footer look like within the docDefinition object.

`  header: function(currentPage, pageCount, pageSize) {
    var headers = ['SUMMARY', 'PAGE TITLE 1', 'PAGE TITLE 2', 'PAGE TITLE 3'];
    return [
      { 
        margin: [ 30, 30, 0, 30 ],
        table: {
          widths: ['50%', '50%'],
          heights: [ 30 ],
          body: [[{ text: headers[currentPage-1], style: 'leftHeader' }, { text: "", style: 'filledHeader' }]]
        },
        layout: 'noBorders',
      }
    ]
  },
  footer: function(currentPage, pageCount) { 
    return [
      {
        table: {
          widths: ['10%', '90%'],
          heights: [ 30 ],
          body: [[{ text: currentPage.toString(), style: 'leftFooter' }, { text: "", style: 'filledHeader' }]]
        },
        layout: 'noBorders',
      }
    ]
   },`

And then the aforementioned leftHeader, leftFooter, and filledHeader styles are defined later on in my docDefinition object. Hope this helps someone!
