### ISSUE TITLE
pageMargins not applied to header and footer

### ISSUE THREAD

**Issue by iceboxx89** [bpampuch/pdfmake#81]
Hi,

the page margins are not applied to the header and footer., did someone come across this issue.?
a simple playground test will replicate the issue..

``` javascript
var dd = {
    header: {
        stack: [
            {text: 'hello-header'}
        ]
    },
    footer: {
        stack: [
            {text: 'hello-footer'}
        ]
    },
    content: [
        {
            table: {
                widths: ['*', '*'],
                body: [
                    ['', '']
                ]
            }
        }
    ],
    pageSize: 'LETTER'
}
```

and any pageMargins given are applied only to the `content`

**Comment by nilakshibhosale** [comment]
Hi,
How can i add line above footer

**Comment by MyKindfu** [comment]
> Hi, How can i add line above footer

  private pageFooter(currentPage, pageCount) {
    return [
      { text: `Page ${currentPage} of ${pageCount}`, alignment: 'right' },
      { canvas: [{ type: 'line', x1: 10, y1: 3, x2: 595 - 10, y2: 3, lineWidth: 0.5 }] },
    ];
    margin: [72, 40];
  }
