### ISSUE TITLE
Open a pdf made with pdfmake using InAppBrowser

### ISSUE THREAD

**Issue by karinepires6** [bpampuch/pdfmake#810]
It is possible to open a pdf made with pdfmake using cordova.InAppBrowser.open()?

**Comment by karinepires6** [comment]
@miltador thanks, I'll try

**Comment by karinepires6** [comment]
In function cordova.InAppBrowser.open(url, target, options), the first parameter is url, but how I can transform for example:
`var pdf = pdfMake.createPdf(docDefinition)`
My pdf var in a url?

**Comment by liborm85** [comment]
Maybe so:
```
pdfMake.createPdf(docDefinition).getDataUrl((dataUrl) => {    
 // in variable dataUrl is PDF in data URL
});
```
Check cordova documentation, or cordova support.
