### ISSUE TITLE
Page constantly reloading

### ISSUE THREAD

**Issue by joshstrange** [bpampuch/pdfmake#812]
FInally tracked this down to this library getting updated (last time I use a "X.X.*" in a bower config). This was causing our webpage to be reloaded as soon as our DataTable Ajax feed came back (That may or may not be related). I have taken us back down to 0.1.20 and that is working but a higher version may still work.

**Comment by joshstrange** [comment]
I've narrowed it down to 0.1.20 -> 0.1.22 change that causes the reload

**Comment by liborm85** [comment]
Do you have an example of how to simulate this?

**Comment by joshstrange** [comment]
@liborm85, Currently I do not. I just ran into this as I was building code for our staging environment and I have been busy with other things since. I do plan on getting an example up for better examination but it won't be for a few weeks at best I'd guess. More than anything I wanted to throw this out as a possible issue people might see (I was using this in conjunction with DataTables).

**Comment by liborm85** [comment]
To me it did not simulate. Maybe someone else will create issue with this problem.
