### ISSUE TITLE
Edge browser

### ISSUE THREAD

**Issue by mudupalli** [bpampuch/pdfmake#813]
In my edge browser,   pdfMake.createPdf(docDefn).download(filename) takes twice the time compared to IE11 and Firefox. Do you know why?

**Comment by liborm85** [comment]
I tried it Edge, Firefox, Chrome and all it takes approximately the same.

**Comment by mudupalli** [comment]
Hi,
I have added additional information.
Please let me know whether you need anything else from me.

For 300 rows of data,

Browser

Version

Elapsed Time

Edge

25.10586.672.0

Microsoft Edge HTML 13.10586

1 minute 20 seconds

IE

11.713.10586

36 seconds

Firefox

50.1.0

36 seconds

Chrome

55.0.2883.87 m

16 seconds

Thanks,
RS

**Comment by liborm85** [comment]
The problem is connected with https://github.com/bpampuch/pdfmake/issues/798

**Comment by mudupalli** [comment]
ok, thanks for letting me know. I will track it to see whether you are
publishing a fix.

**Comment by liborm85** [comment]
New version 0.1.27 includes partial performance fix. Next performace solution we will continue in issue https://github.com/bpampuch/pdfmake/issues/798.
