### ISSUE TITLE
Background image combined with fillColor on table does not work.

### ISSUE THREAD

**Issue by khaivngo** [bpampuch/pdfmake#817]
It should be possible to use background image in conjuction with fillColor on a table cell.
Without background image fillColor is set: http://puu.sh/tgk1f/64b20c0995.png
With background image fillColor is not set: http://puu.sh/tgk3x/c21c4b5042.png

Can this be solved or is it a feature request?

**Comment by khaivngo** [comment]
Little update, the fillColor turns out to be behind the background image. So removing the image after export reveals the fillColor.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/437
