### ISSUE TITLE
TypeError with v0.1.24: Cannot read property 'version' of null

### ISSUE THREAD

**Issue by emanuelschuetze** [bpampuch/pdfmake#818]
If you create a pdf with pdfmake 0.1.24 and custom ttf fonts (using custom vfs_fonts.js as descripted in [wiki](https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side)) you get a TypeError:

`TypeError: Cannot read property 'version' of null`

pdfmake 0.1.23 works without problems (with same fonts).

**Comment by liborm85** [comment]
Problem explained here: https://github.com/bpampuch/pdfmake/issues/821#issuecomment-271506292
Can you provide a link to font you used?

**Comment by emanuelschuetze** [comment]
It fails in OTProcessor.getClassID of fontkit (as reported in https://github.com/devongovett/fontkit/issues/65)

```
TypeError: Cannot read property 'version' of null
    at OTProcessor.getClassID
    at GlyphInfo.set
    at new GlyphInfo
    at Array.map
    at OTLayoutEngine.setup
    at LayoutEngine.layout
    at TTFFont.layout
    at EmbeddedFont.widthOfString
```
@liborm85 I can't provide a public link of my vfs_fonts.js file because it contains a ttf file with licensing restrictions. But I'll sent it to you via email for testing.

**Comment by liborm85** [comment]
Thanks, I tried it. And create new issue: https://github.com/devongovett/fontkit/issues/66

**Comment by emanuelschuetze** [comment]
Thank you!

**Comment by liborm85** [comment]
Temporary fixed in pdfmake webpack by commit https://github.com/bpampuch/pdfmake/commit/b43f46b4043656f1e5b63af793b1837b54b7215d will be in new version. For complete fix must be fixed in fontkit by @devongovett 

This issue here I closed.
