### ISSUE TITLE
.open() working on localhost, but not on https webpage.

### ISSUE THREAD

**Issue by CrackerakiUA** [bpampuch/pdfmake#819]
This error happens when i use new tab as export pdf. When i am using download, everything is working.
i have below error in console
`Uncaught TypeError: Cannot read property 'location' of null`
`at getBuffer.autoPrint`

I have this issue in chrome, but not in firefox.

**Comment by liborm85** [comment]
I'm tried pdfmake on https page and `open()` works correctly in Chrome and Firefox.
