### ISSUE TITLE
Uninformative error message when vfs_fonts.js not loaded

### ISSUE THREAD

**Issue by rumkin** [bpampuch/pdfmake#820]
Library produce TypeError on `open` call if there is no `vfs_fonts.js` file loaded:

```
TypeError: undefined is not an object (evaluating 'filename')
```

Maybe it should be captured in code or specified in documentation?

**Comment by liborm85** [comment]
Added throw exception when file not found in virtual file system - https://github.com/bpampuch/pdfmake/commit/f4906ad10384fa894b378caa052f893ee695734b
