### ISSUE TITLE
PDF creation fails with custom fonts using new version of pdfmake

### ISSUE THREAD

**Issue by sklinga** [bpampuch/pdfmake#821]
We have a working code base to create PDF using custom fonts(Univers) with pdfmake-0.1.17.
We want to use pdfmake-0.1.23 or later for the custom links fix but we are seeing the below error with the custom fonts, is there anything changed with fonts in latest release?

TypeError: Cannot read property 'records' of undefined
    at TTFFont.get (pdfmake.js:50606:28)
    at new EmbeddedFont (pdfmake.js:70666:29)
    at Function.PDFFont.open (pdfmake.js:37654:15)
    at PDFDocument.font (pdfmake.js:37593:29)
    at FontProvider.provideFont (pdfmake.js:19881:56)
    at pdfmake.js:21351:28
    at Array.forEach (native)
    at measure (pdfmake.js:21338:14)
    at TextTools.buildInlines (pdfmake.js:21145:18)
    at DocMeasure.measureLeaf (pdfmake.js:20768:29)

Appreciate any help with this issue.

Regards,
Sunil

**Comment by devongovett** [comment]
@sklinga sounds like maybe the font has no `name` table. can you please send the file to me? devongovett@gmail.com

**Comment by sklinga** [comment]
@devongovett I can not share Univers font file due to licensing restrictions, but, I tried with the below font and I got the same issue
http://www.webpagepublicity.com/free-fonts/x/Xeranthemum.ttf

Thanks again for you help!

**Comment by sklinga** [comment]
On further debugging, looks like it is failing decoding the name table. I see below error

Uncaught Error: Encoding '_sbcs' has incorrect 'chars' (must be of len 128 or 256)(…)
	SBCSCodec @ pdfmake.js:52920
	getCodec @ pdfmake.js:52096
	getDecoder @ pdfmake.js:52118
	decode @ pdfmake.js:52036
	DecodeStream.readString @ pdfmake.js:51961

Strangely, when I run the code to create PDF with the same custom fonts as standalone outside our big app code base, it works fine.
The problem seems to be only when running the PDF creation within the entire app code base. Not sure if some thing else we have in our app code may have been causing the font decoding failed!!? 

Any help/pointers on this issue is greatly appreciated!

**Comment by liborm85** [comment]
Pdfmake v0.1.24 using the newer fontkit library, that are probably some bugs. :(
https://github.com/devongovett/fontkit/issues/65
https://github.com/bpampuch/pdfmake/issues/818

We must wait until it fix @devongovett.

**Comment by liborm85** [comment]
@devongovett Please also see this bug https://github.com/bpampuch/pdfmake/issues/818

**Comment by liborm85** [comment]
@sklinga The same or similar error is in issue https://github.com/bpampuch/pdfmake/issues/828. Do you have `<meta charset="utf-8">` in the `<header>`?

**Comment by liborm85** [comment]
No reaction.

**Comment by tdolphin** [comment]
I had exactly the same problem (old version <0.1.20 works but not new one) and adding 
`<meta charset="utf-8">`
to the header solved it.

**Comment by sklinga** [comment]
Sorry for the very long delay in responding. 

Adding meta tag to the header did not solve the issue in my case. I had to add the charset attribute to the script tag that is loading the pdfmake.js

`<script type="text/javascript" src="/js/dependencies.js" charset="utf-8"></script>`

pdfmake.js and few other libraries are concatenated in to dependencies.js file.
