### ISSUE TITLE
get Array Buffer from createPdfKitDocument

### ISSUE THREAD

**Issue by SaidMarar** [bpampuch/pdfmake#824]
i can't use pdfMake.createPdfv0.1.24 in NODEJS so i used createPdfKitDocument, and i don't know how to get the arrayBuffer ... anyone here can help please

**Comment by liborm85** [comment]
You can be inspired here https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js

**Comment by thefat32** [comment]
This does not answer the question, as that example is using browser version

**Comment by yanickrochon** [comment]
Came here, and saw nothing helpful. Thank you!

**Comment by relves** [comment]
This is actually helpful: https://github.com/bpampuch/pdfmake/issues/198#issuecomment-532005570

**Comment by picchi-lucas** [comment]
```ts
  return await new Promise<Buffer>((resolve) => {
    const pdfDoc = printer.createPdfKitDocument(docDefinition);
    const buffs: unknown[] = [];
    pdfDoc.on('data', function (d) {
      buffs.push(d as readonly Uint8Array[]);
    });
    pdfDoc.on('end', function () {
      resolve(Buffer.concat(buffs as readonly Uint8Array[]));
    });
    pdfDoc.end();
  });
  ```
