### ISSUE TITLE
How to catch error ?

### ISSUE THREAD

**Issue by nitinsinghit** [bpampuch/pdfmake#826]
How to catch error if pdfmake fails  while createPdf or during download? I know during download we can pass callback to check if pdf if downloaded but not sure how to differ it from sucess and error.

Thanks

**Comment by liborm85** [comment]
use try catch - http://www.w3schools.com/js/js_errors.asp

**Comment by thebirdman7** [comment]
For instance, when an image doesn't load I have found that try/catch does not work. In this case the only way to get the error (in my experience) has been to trap the unhandled promise rejection that most browsers send. Please let me know if you know another way.

**Comment by VikramRajai** [comment]
@Alfredleo7 @thebirdman7 guys, did you find any solution to handle exception if pdf is not generated?
