### ISSUE TITLE
SCRIPT70: Permission denied File: pdfmake.min.js IE 11

### ISSUE THREAD

**Issue by pr-dev-repo** [bpampuch/pdfmake#827]
Having problems rendering in Internet Explorer/ edge with latest version

File: pdfmake.min.js, Line: 1, Column: 1675

works fine on other browsers.

thanks in advance!!!

**Comment by liborm85** [comment]
`open()` doesn't work in IE https://github.com/bpampuch/pdfmake/issues/230.  Here is table with supported browsers: https://github.com/bpampuch/pdfmake/issues/800. Use `download()`, it works everywhere.

**Comment by pr-dev-repo** [comment]
thank you.
