### ISSUE TITLE
var docDefinition is being edited but changes are not reflected on PDF final printout.

### ISSUE THREAD

**Issue by norvaweb** [bpampuch/pdfmake#829]
After this file was edited and uploaded to the server, the changes are not shown and shows the original version. For instance:
table: {
                        widths: ['*'],
                        body: [
                                [ {text:'QUOTE', alignment: 'center',bold:true, fillColor: '#4F84C0'}],
                            ]
                    },
The alignment section was changed to "left" from "center" but the final PDF file does not show it.
table: {
                        widths: ['*'],
                        body: [
                                [ {text:'QUOTE', alignment: 'left',bold:true, fillColor: '#4F84C0'}],
                            ]
                    }, 
Thanks so much for your wisdom.
R@N

**Comment by liborm85** [comment]
What are you doing?
docDefinition array give to pdfmake is rendered as PDF.

**Comment by norvaweb** [comment]
HI liborm85,
This app was built with Angular 1.4, Express, Gulp, Jade. pdfkit and pdfmake mostly.  I need to make some changes on the printout but when I edit the changes, they are not reflected when the user is going to print as PDF.
On Thursday I got the suggestion that probably I was not compiling the new file with Gulp before uploading to the server. and thus it was not being read.
I still have not being able to solve this issue.

**Comment by liborm85** [comment]
If you change docDefinition before passing into pdfmake, it'll certainly be reflected. Check whether you pass the correct docDefinition.
