### ISSUE TITLE
Use of "new Function" break chrome apps compatibility

### ISSUE THREAD

**Issue by FbN** [bpampuch/pdfmake#831]
In Chrome installed Apps is prohibitet to use "new Function" for security reasons.

PDFMAKE started using new Function() from  0.1.23

Would be great to be able to use pdfmake in chrome installed apps

**Comment by liborm85** [comment]
pdfmake does not use this structure.
pdfmake 0.1.23 started using new version of library fontkit (version 1.5.2) and this has dependency with https://github.com/devongovett/restructure, where is `new Function` used.

**Comment by liborm85** [comment]
Issue fixed in version 0.2.0 - https://github.com/bpampuch/pdfmake/issues/2282.
