### ISSUE TITLE
Alternate fillColor Rows

### ISSUE THREAD

**Issue by vmontal** [bpampuch/pdfmake#836]
Hi,
how can I render a table with alternated (odd / even) fillColor rows?;
I already tried this:

fillColor: function(i){
return (i % 2 === 0 ? "red":"green");
};

but what I get is a black fillColor for all rows!

**Comment by liborm85** [comment]
`fillColor` should not be a function, must be a string.

**Comment by vmontal** [comment]
Ok! .... and so?

**Comment by liborm85** [comment]
Currently, only this :
```
var dd = {
	content: [
		{
			table: {
				body: [
					[{text:'Column 1', fillColor:'red'}, {text:'Column 2', fillColor:'red'}],
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}],
					[{text:'Column 1', fillColor:'red'}, {text:'Column 2', fillColor:'red'}],
					[{text:'Column 1', fillColor:'green'}, {text:'Column 2', fillColor:'green'}]					
				]
			}
		}
	]
	
}
```

**Comment by vmontal** [comment]
Ok, I realized that pdfmake can't manage alternated fillColor rows... so far!

**Comment by vmontal** [comment]
However, thank you !!!

**Comment by liborm85** [comment]
reference with feature request - https://github.com/bpampuch/pdfmake/issues/579

**Comment by liborm85** [comment]
I'm implemented it, see https://github.com/bpampuch/pdfmake/issues/579#issuecomment-274332716
