### ISSUE TITLE
How can align an entire column?

### ISSUE THREAD

**Issue by anguswild** [bpampuch/pdfmake#839]
Hi, i am using pdfmake via datatables.js i have a simple problem but i can't solved it

i need to right align an entire column and a im sending via the customize: function of datatables the folowing code to pdfmake

```javascript
doc.content[1].table.body[0][5].alignment = 'right';
```

but it only aligns the header, how can i align the entire column

thanks in advance

**Comment by anguswild** [comment]
```javascript
I came up with a workaround

var rowCount = document.getElementById("cheques").rows.length;
					for (i = 0; i < rowCount; i++) { 
						doc.content[1].table.body[i][5].alignment = 'right';
					};	
```

Sorry for any inconvenience

**Comment by k4neda74** [comment]
This solution only aligns the first 25 rows when using pagination (showing 25 rows on screen)
