### ISSUE TITLE
[node] PDF generation 3x slower than vanilla pdfkit

### ISSUE THREAD

**Issue by mhagmajer** [bpampuch/pdfmake#841]
Concerned about the speed of PdfMake on our server, I made a simplistic 12-page text-only example and measured times of both pdfmake and vanilla pdfkit. Please see details below including generated files and code. I also checked master but didn't see any improvement there.

### pdfmake 0.1.24
```
$ python -m timeit -n 10 "(__import__('os').system('node index.js'))"
10 loops, best of 3: 9.77 sec per loop
```
```javascript
const fs = require('fs');
const PdfPrinter = require('pdfmake');

const printer = new PdfPrinter({
  Roboto: {
    normal: 'fonts/Roboto-Regular.ttf',
  }
});

const content = [];

const linesPerPage = 84;
for (let i = 0; i < 1000; i += 1) {
  const line = `This is line nr ${i} on page nr ${Math.floor(i / linesPerPage) + 1}. `;
  content.push(line);
}

var doc = printer.createPdfKitDocument({
  content,
  defaultStyle: {
    font: 'Roboto',
    fontSize: 6,
  },
  pageMargins: [0, 0, 0, 0],
  pageOrientation: 'landscape',
});
doc.pipe(fs.createWriteStream('output.pdf'));
doc.end();
```
[output.pdf](https://github.com/bpampuch/pdfmake/files/732308/output.pdf)

### vanilla pdfkit 0.8.0
```
$ python -m timeit -n 10 "(__import__('os').system('node raw.js'))"
10 loops, best of 3: 3.03 sec per loop
```
```javascript
const fs = require('fs');
const PDFDocument = require('pdfkit');

const doc = new PDFDocument({
  layout: 'landscape',
  margin: 0,
  size: 'A4',
});

doc.registerFont('Roboto', 'fonts/Roboto-Regular.ttf');
doc.font('Roboto').fontSize(6);

const linesPerPage = 84;
for (let i = 0; i < 1000; i += 1) {
  const line = `This is line nr ${i} on page nr ${Math.floor(i / linesPerPage) + 1}. `;
  doc.text(`${line}`, 0, (i % linesPerPage) * 7.03);

  if ((i + 1) % linesPerPage === 0 && i < 999) {
    doc.addPage();
  }
}

doc.pipe(fs.createWriteStream('raw.pdf'));
doc.end();
```
[raw.pdf](https://github.com/bpampuch/pdfmake/files/732317/raw.pdf)

**Comment by mhagmajer** [comment]
After applying `noWrap` (with pending fix for https://github.com/bpampuch/pdfmake/issues/842) I was able to drive the pdfmake time down to:

```
$ python -m timeit -n 10 "(__import__('os').system('node index.js'))"
10 loops, best of 3: 5.47 sec per loop
```

I also found out that using the builtin `Helvetica` font gives the biggest performance boost:

```
$ python -m timeit -n 10 "(__import__('os').system('node index.js'))"
10 loops, best of 3: 897 msec per loop
```

**Comment by DerTieran** [comment]
@mhagmajer Are you able to share your test `index.js` files?
Thanks in advance.

**Comment by mhagmajer** [comment]
@DerTieran I copy pasted those files into description of this issue :)

**Comment by DerTieran** [comment]
Oh okay thought the ones from the [last update](https://github.com/bpampuch/pdfmake/issues/841#issuecomment-275482063) where different.
Thanks.

**Comment by DerTieran** [comment]
Hey just wanted to leave this here if it is needed.
I created a timeline profile using [iron-node](https://github.com/s-a/iron-node) for your code examples.

### pdfmake@0.1.26 
| Total Time | Activity                     |
|------------|------------------------------|
| 13.0 ms    | PDFDocument                  |
| 0.1 ms     | registerDefaultTableLayouts  |
| 1145.8 ms  | LayoutBuilder.layoutDocument |
| 1314.0 ms  | renderPages                  |

### pdfkit@0.8.0 
*The `renderPages` function here is just the loop wrapped into a function to make profiling easier*

| Total Time | Activity    |
|------------|-------------|
| 13.5 ms    | PDFDocument |
| 7.0 ms     | font        |
| 1076.3 ms  | renderPages |

**Comment by liborm85** [comment]
Performance problem solved in issue https://github.com/bpampuch/pdfmake/issues/798.
