### ISSUE TITLE
dynamically inserting pages

### ISSUE THREAD

**Issue by Vadi** [bpampuch/pdfmake#846]
We want to insert a page for every even numbered page, for example, "This is page is intentionally left blank". How it is possible? Is there any event or something we can listen into to alter the document context.

**Comment by cougarten** [comment]
you have to build the pages yourself and than do some if.

I for example do not do a pageBreak before the first page here:

`  var docDefinition ={
     content: [],
     styles: styles
  };

  for(var i = 0; i < pages.length; i++){
      var wrappedPage;
      //page wrapping for page breaks, exept for the first page
      if (i == 0) {
        wrappedPage = {
              stack: [makePage(pages[i])]
        };
      }else{
        wrappedPage = {
              stack: [makePage(pages[i])],
              pageBreak: 'before'
        };
      }
      docDefinition.content.push(wrappedPage);
  }`

**Comment by Vadi** [comment]
Thanks. It helped.
