### ISSUE TITLE
Base 64 image not displayed at device

### ISSUE THREAD

**Issue by favancini** [bpampuch/pdfmake#849]
This is part of Document Definition. At playground it works fine, but at the device isn't displayed. If I link it to a IMG tag, it works. Any tip?

var dd = {
       pageSize: 'A4',
        pageOrientation: 'portrait',
        pageMargins: [ 40, 60, 40, 60 ],

        header: [{ image: 'data:image/jpeg;base64,/9j/4Q............', width: 550 }],
        .......
}

**Comment by MehdiAR** [comment]
the same here

**Comment by alexxmde** [comment]
Same here too. In my case, all the content of the header and/or footer disapear when I add the image.

**Comment by liborm85** [comment]
In latest version header must be defined as function.

Improved by commit https://github.com/bpampuch/pdfmake/commit/ecab1d69f4b068b417c4c8db2e7e136fe2c0e50e.
