### ISSUE TITLE
pdf cuts some colums

### ISSUE THREAD

**Issue by mrwhite1** [bpampuch/pdfmake#850]
hi, we have fixed sized page so if i have lets say 10 or 15 colums it will cut out some colums and its content. is there a way i can do something about that? like by default all the columns should show on page?

**Comment by liborm85** [comment]
I don't understand your question, what you want to do?

**Comment by mrwhite1** [comment]
what will happen if i want to show a table which has a 15 columns per row. as width is fixed it would not show some content. i mean it will write the rows that fits and it will cut the extra part.

**Comment by liborm85** [comment]
Occurs this (executables on http://pdfmake.org/playground.html):
```js
var dd = {
	content: [
		{
			style: 'tableExample',
			table: {
				widths: [200, 200, 200, 200],
				body: [
					['1', '2', '3', '4']
				]
			}
		}
	]
}
```

You must define witds columns and number of columns the table so that it is not outside.
