### ISSUE TITLE
Array Iterator breaks Google Analytics

### ISSUE THREAD

**Issue by stangel** [bpampuch/pdfmake#852]
After updating our code from the version last May 2016 to Jan 2017, our Google Analytics fell off the map.  We traced it to the pdfmake library redefining the Array prototype to "Array Iterator" which, when we pass and empty array to Google Analytics, fails this test:

```
var a = [];
"[object Array]" == Object.prototype.toString.call(Object( a ))
```

...resulting in no Analytics call being made.  

Redefining the prototype of a core data type is evil.

**Comment by liborm85** [comment]
I'm try run your test together pdfmake, and condition returns `true`. Probably this means that the test passes. Is really the problem is pdfmake?

**Comment by stangel** [comment]
Hi @liborm85, turns out this was an interaction between pdfmake and Prototype prior to 1.7.3 [what can I say, our site's been around awhile!] -- it's fixed in newer versions of Prototype and also not a problem for anyone not running Prototype, so I'm going to close this issue.  Thanks for looking into it with us!
