### ISSUE TITLE
[Virus] Not able to clone or download

### ISSUE THREAD

**Issue by bhupal4all** [bpampuch/pdfmake#853]
I have been trying to download or clone the repository, but unfortunately system's Anti-Virus is deleting the files and says virus/trojan hourse identified and quarantined (as js files, mainly at pdfmake.js and pdfmake.min.js).
I am able to access the [Playground](http://pdfmake.org/playground.html) without any issue.

It would be great if you ensure the repository as virus free.

**Comment by liborm85** [comment]
Try to check your computer using antivirus. Or try it on other clean computer.

**Comment by bhupal4all** [comment]
I have tried another machine as well.  I got the same error and has been removed by Anti Virus.

**Comment by liborm85** [comment]
If it's not top secret information, what is the name of the antivirus? And name of the virus?

**Comment by bhupal4all** [comment]
Here is the snapshot of the anti virus report.

![image](https://cloud.githubusercontent.com/assets/11767178/22674347/8c646cb8-ed05-11e6-8633-f36ec6790f33.png)

**Comment by liborm85** [comment]
It si false positive detection, as mentioned in the previous post virustotal say it's clean.
