### ISSUE TITLE
item.item.getHeight is not a function

### ISSUE THREAD

**Issue by Klemen1337** [bpampuch/pdfmake#854]
Hi,
I tried to switch to `pageSize { height: 'auto' }` and now I am getting warn: `TypeError: item.item.getHeight is not a function at ../node_modules/pdfmake/src/printer.js:159:24`. Any ideas why?

Cheers,
K

**Comment by liborm85** [comment]
I suppose that is image image in PDF?
Fixed by commit https://github.com/bpampuch/pdfmake/commit/10e4b215190b482e90baf1949ce8ecdbf5afba0f.

**Comment by Klemen1337** [comment]
@liborm85 I applied the fix and the error is gone. But now I get a white PDF...

**Comment by liborm85** [comment]
For example, this works:
```
var dd = {
	pageSize: {
		width: 500,
		height: 'auto'
	},    
	content: [
		'First paragraph',
		'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
	]
}
```

Can you give some example of your code?

**Comment by Klemen1337** [comment]
Well I have it a bit more complicated :smile:, I dont know how to show/debug it

**Comment by liborm85** [comment]
Next fix for auto height - https://github.com/bpampuch/pdfmake/commit/62ad031a81688cb345c9c7c041606a4aa45bc796
