### ISSUE TITLE
 pdfMake.createPdf(dd).open fail Uncaught Open PDF in new window blocked by browser

### ISSUE THREAD

**Issue by lbottoni** [bpampuch/pdfmake#857]
i have this issue on Chrome
i have tried use timeout or ajac call async but never unlock this block.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/587

**Comment by ankitc1010** [comment]
Actually that is because the browser blocking the pop up, since it is not generated by user interaction but is internally.

**Comment by moffsugita** [comment]
So it can't resolve?

```
    let pdfDocGenerator = pdfMake.createPdf(docDefinition);
    try {
      pdfDocGenerator.open();
    } catch (err) {
      alert(err);
    }
```
