### ISSUE TITLE
is it possible to have different fonts in a paragraph

### ISSUE THREAD

**Issue by prtome** [bpampuch/pdfmake#859]
Hello
I have 2 columns in my page, with text. The texts have a title (in bold) then text on the next line. Some of this text also will be in bold.
 this is my example from the playground that shows what I am trying to do . 
My question is - is this possible ? thanks

    var dd = {
	  content: [
		{
			alignment: 'justify',
			columns: [
				{
					text: 'This should be the title in bold\n this a simple text\nblabla in bold, but this again normal.'
				},
				{
					text: 'This is a text \nthat goes to the next line\nall with same font\n how do I put text in bold ?'
				}
			]
		},
	 ],
	 styles: {
		header: {
			fontSize: 18,
			bold: true
		},
		bigger: {
			fontSize: 15,
			italics: true,
		}
	  },
	   defaultStyle: {
		columnGap: 20,
	    }
      }

**Comment by liborm85** [comment]
Example:
```js
var dd = {
  content: [
	{
		alignment: 'justify',
		columns: [
			{
			    stack: [
			            {text: 'Title for column 1', bold: true},
				    {text: 'This should be the title in bold\n this a simple text\nblabla in bold, but this again normal.'},
				    {
				        text: [
				            'Normal text ',
				            {text: 'Bold text', bold: true}
				        ]
				        
				    }
				]
			},
			{
			    stack: [
			            {text: 'Title for column 2', bold: true},
				    {text: 'This is a text \nthat goes to the next line\nall with same font\n how do I put text in bold ?'}
				]
			}
		]
	},
 ],
 styles: {
	header: {
		fontSize: 18,
		bold: true
	},
	bigger: {
		fontSize: 15,
		italics: true,
	}
  },
   defaultStyle: {
	columnGap: 20,
    }
  }
```

**Comment by prtome** [comment]
Thanks a lot  ! I was completely missing the stack part, don't know why I stopped at the first example  of paragraphs in the getstarted doc... Now I understand how to do it. And I should be more careful reading the docs.
