### ISSUE TITLE
How to set pagetitle for .open() like in .download('pagetitle.pdf')

### ISSUE THREAD

**Issue by nrjmr432** [bpampuch/pdfmake#860]
We can add page title for .download() similarly, is there any provision to add page title for open(). 

pdfMake.createPdf(dd).download('pagetitle.pdf');
pdfMake.createPdf(dd).open(); --> passing pagetile as parameter here is not working.

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/501
