### ISSUE TITLE
Text locking/padding/Filling

### ISSUE THREAD

**Issue by pdfCS2012** [bpampuch/pdfmake#863]
-  Hello,
- 
- I would like to be able to fill white space sin between texts with "-----"
- for Example
- -------------------------------------------------------------------------------------------------------
- ----Today I went to the shop and got food.--------------------------------------------------------
- ----I saw Timmy there. He was diferent, somethign had changed.--------------------------------
- -------------------------------------------------------------------------------------------------------
- ----No one knew what had happend... But he had a million miles stare on his eyes... I got the
- food and has I was paying... Timmy said:-----------------------------------------------------------
- ----"Hello There"------------------------------------------------------------------------------------
- 
- Is this possible? and if so, how?
- 
- Best Regards,
- Hugo Lopes

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/1730
