### ISSUE TITLE
Pdfmake  has huge performance issue when downloading 100 pages

### ISSUE THREAD

**Issue by vijender1256** [bpampuch/pdfmake#865]
I am having issues downloading pdf which had more than 100 pages. The browser just hangs and waits for more than a minute for PDF to show up(in IE) , whereas in chrome it constantly asks to wait or kill process as it took a lot of time to download.

How to fix the performance with huge dataset ? any help is appreciated.

**Comment by liborm85** [comment]
Perfomance problem is in the issue https://github.com/bpampuch/pdfmake/issues/798.
The problem is in pdfkit library.  It is reported in issue https://github.com/devongovett/pdfkit/issues/615. Now we are waiting for a statement from author @devongovett.

**Comment by vishwajeets7** [comment]
Facing the similar issue when working with large number of pages. Do we have any updates?

**Comment by vijender1256** [comment]
@Vishwajeets7  For large number of pages I think pdkmake.js is not recommended , it better we go with sever side PDF libraries . I used a different approach saving parameter values in databases and then used jobs to pick it up and generate pdfs using iTextsharp library and I have a UI page to view those generated reports in that shared location where pdfs are generated gl

**Comment by vishwajeets7** [comment]
@vijender1256 based on the scenario, the data images are generated on the client side, as they are very heavy i would not recommend transferring those images to server and then process for PDF. Looking for some client side solution. 

One of the contributor has worked on for creating pdf for large number of pages example 500+.
