### ISSUE TITLE
vfs_fonts.js importing problem in web worker

### ISSUE THREAD

**Issue by Sasha0430** [bpampuch/pdfmake#867]
Hi everyone.

I solved pdfmake.js importing problem in web worker with Sheep-y's solution(https://github.com/bpampuch/pdfmake/issues/38) but cannot resolve vfs_fonts.js importing problem he mentioned in the issue.
Please let me know how to solve this problem.
The pdf data created by pdfmake is returned correctly but font error occurs when downloading the data.

**Comment by liborm85** [comment]
duplicate post and issue: https://github.com/bpampuch/pdfmake/issues/38
