### ISSUE TITLE
different dependencies for bower and npm?

### ISSUE THREAD

**Issue by needforspeed** [bpampuch/pdfmake#868]
I notice there is no dependencies for bower, but there are three dependencies for npm. What are the differences?

If I'm using webpack to package the front end code and installing pdfmake via npm, do I really need the three dependencies?

TIA

**Comment by liborm85** [comment]
bower is for client-side (browser) usage and all is packed to pdfmake.js file (no next dependencies needed).
npm is for server-side usage from source codes and all dependencies are needed.
