### ISSUE TITLE
Letter Spacing

### ISSUE THREAD

**Issue by anthonmanix** [bpampuch/pdfmake#869]
Is it possible to set the letter spacing. I saw that pdfkit has characterSpacing property, but I can't find a way to set it in pdfmake.

Thank you.

**Comment by ardean** [comment]
Is there currently a way to add letter spacing? I really need that feature now...

**Comment by digitalgoodsprovider** [comment]
me to!!

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/86f34d35c2e15db8a1c17a7a7dd3fb810be22558.

**Comment by Nomia** [comment]
this commit is not merged to the newest version (v0.1.27)
when will the characterSpacing feature be merged into the npm package?

**Comment by darrenst** [comment]
Its not in the docs but the feature is in the latest version. Its takes negative values too.

`characterSpacing: -0.5,`
