### ISSUE TITLE
dynamic access on table data?

### ISSUE THREAD

**Issue by greyhole** [bpampuch/pdfmake#870]
Hi, I realy like your library.
The dynamic table and column is awesome!
But i miss one thing.

Is there any way to create a node in relation on the table data written on a page?
I need a table-footer which accumulate values of the table, written on the page and all pages before...

One way, i can imagine, is prebuild the hole pages and rebuild the specific nodes.
Like a Priority or depth system in multiple steps...

Off course with a performance overhead. But for me this did not matter.

For me, i only need to accumulate and print one column of a  table in a table footer...
Is there a functionality to accomplish this? 

Thanks for all.

**Comment by liborm85** [comment]
Pdfmake library is not MS Excel (or similar).
Definition for table you can build dynamically in javascript, and there can create any calculation.
