### ISSUE TITLE
Dot Matrix Printer

### ISSUE THREAD

**Issue by s-nadesh** [bpampuch/pdfmake#872]
Hi,

How to use Dot Matrix Printer ? 

My print paper size is width 23cm height 10cm. Please help how to use pdfmake. 

Thank you

**Comment by liborm85** [comment]
What is the problem?

**Comment by s-nadesh** [comment]
Hi, 

I am using dot matrix printer Tvs msp-250.

I attached sample sales bill format with old print content. How to use pdfMake to print my content exactly in the predefined location. 

For example:

Pt. Name : ###MYNAME###           No. : ###BILLNO###
Address : ###MYADDRESS##        Date : ###DATE###

Then table rows should display in the particular box. 

Paper size is 23cm width and 10cm height. 

![img_20170218_171039](https://cloud.githubusercontent.com/assets/8857848/23093029/54ed5860-f5fe-11e6-816f-a7a650faaa7f.jpg)

Please help me with some sample code. 

Thank you.

**Comment by liborm85** [comment]
Example with absolute positioned text:
```js
var dd = {
   content: [
        {
            text: 'text 1',
            absolutePosition: {x:123, y:200}
        },
        {
            text: 'text 2',
            absolutePosition: {x:400, y:250}
        },
        {
            text: 'text 3',
            absolutePosition: {x:300, y:270}
        },
    ]
}
```

**Comment by s-nadesh** [comment]
Thank you for your reply.

But my printing paper is not a A4 sheet, it is a label with 23cm x 10cm. So When I take a print out in the dot matrix printer the content is not displayed correctly.

Even I used 
pageSize: {width: 4 * 72, height: 8 * 72},
pageOrientation: 'landscape',

Thank you

**Comment by s-nadesh** [comment]
How to display below attached section ? 

![rsz_1rsz_img_20170218_171039](https://cloud.githubusercontent.com/assets/8857848/23093341/6c95d4f8-f606-11e6-92f4-d89e59920da3.jpg)

If More than 5 sales items means, print should go to next page. 

Better to understand If you give some static table array.

Please help me.

**Comment by liborm85** [comment]
example for one page:
```js
var dd = {
    pageSize: {
        width: 4 * 72,
        height: 8 * 72
    },
    pageOrientation: 'landscape',
	content: [
		{
			table: {
			    widths: ["5%", "45%", "9%", "9%", "9%", "9%", "9%", "9%"],
				body: [
					['1', 'ITEM 1', 'SUN', 'ABC123', '02/19', '70', '6.123', '370.02'],
					['2', 'ITEM 2', 'SUN', 'ABC123', '02/19', '70', '6.123', '370.02'],
					['3', 'ITEM 3', 'SUN', 'ABC123', '02/19', '70', '6.123', '370.02'],
					['4', 'ITEM 4', 'SUN', 'ABC123', '02/19', '70', '6.123', '370.02'],
					['5', 'ITEM 5', 'SUN', 'ABC123', '02/19', '70', '6.123', '370.02'],
					[' ', '', '', '', '', '', '', ''],
					[' ', '', '', '', '', '', '', ''],
					['', '', '', {text: 'Cash received', colSpan: 2}, '', '', '', '2012.0'],
					['', '', '', 'Balance', '', '', '', '1001.1'],
					['', '', '', '', '', '', {text: '1001.1', colSpan: 2, fontSize: 20, alignment: 'right'}, ''],
				]
			},
			layout: 'noBorders'
		},
		
	]
}
```

This way you can dynamically generate next pages by javascript.

There are good examples: http://pdfmake.org/playground.html

**Comment by s-nadesh** [comment]
Thank you for your reply. I will check it and let you know..

**Comment by s-nadesh** [comment]
Hi, 

I tried your static coding with two different browsers. Below is the result for different browsers.

**Chrome:** 
![chrome_browser](https://cloud.githubusercontent.com/assets/8857848/23538839/7066289e-fffc-11e6-9c2c-0c066ad31167.jpeg)

**Firefox:**
![firefox_browser](https://cloud.githubusercontent.com/assets/8857848/23538850/82857926-fffc-11e6-99cf-1d009f6f64af.jpeg)

1) In Firefox, page contents are printed in the correct directions but in the chrome, page contents are printed in the wrong direction.

2) In Firefox, May I know why the print takes more than 2 sheets for printing.

Once I fixed static code correctly, I will change to dynamic. 

Kindly help me.  

Thank you

**Comment by liborm85** [comment]
Maybe Chrome (or software/driver) concluded that page is too wide and turned orientation.

**Comment by s-nadesh** [comment]
Hi,

Yes, Do you have any idea to solve the above two issues. ?

Kindly help me.

Thank you

**Comment by liborm85** [comment]
Here are outputs from browsers:
[sample_firefox.pdf](https://github.com/bpampuch/pdfmake/files/820492/sample_firefox.pdf)
[sample_chrome.pdf](https://github.com/bpampuch/pdfmake/files/820491/sample_chrome.pdf)

Both PDF files are generated correctly.
In the print dialog can be document adapte, but it depends on printer software, that is probably problem.

**Comment by s-nadesh** [comment]
yes, you are right, when I save the pint as a PDF file means, It is correct.

But 
Do you have any idea ? What should I do now ? 

Kindly give your valuable points.

Thank you.

**Comment by liborm85** [comment]
I do not know. Try to check print settings dialog in both browsers, whether is set all equally.

**Comment by s-nadesh** [comment]
Okay. Thank you for your response. I will try and let you know.
