### ISSUE TITLE
Manual Positioning

### ISSUE THREAD

**Issue by RafeSafari** [bpampuch/pdfmake#874]
I wonder if we can put contents in any given position individually, despite their order in the content array, like absolute position in HTML.
I know that there is a trick using `textAlign: 'right'` and `margin`.
for example: `margin: [100, 30, 0, -15-30]`, will put the content in `right: 100` and `top: 30`. (`-15` removes `fontSize: 15` and extra `30` for `top` value)

**Comment by liborm85** [comment]
Example with absolute positioning:
```js
var dd = {
   content: [
        {
            text: 'text 1',
            absolutePosition: {x:123, y:200}
        },
        {
            text: 'text 2',
            absolutePosition: {x:400, y:250}
        },
        {
            text: 'text 3',
            absolutePosition: {x:300, y:270}
        },
    ]
}
```

**Comment by RafeSafari** [comment]
thanks a lot >:D<

**Comment by cougarten** [comment]
would be nice to have this added to the docs

**Comment by liborm85** [comment]
Example is available in `examples` folder: https://github.com/bpampuch/pdfmake/tree/master/examples

**Comment by chris-chalmers** [comment]
Is there an easy way to get the current position of text so I can absolutely position _relative_ to it?

**Comment by cougarten** [comment]
@chis: a variable+/-X?

**Comment by chris-chalmers** [comment]
I found the answer (silly me) there's a relativePosition parameter. That's awesome! exactly what I needed!

**Comment by adamczi** [comment]
Necroing, but would be nice to see it added to the docs anyway, or see some comments in code at least about positions (relative to what? or can I do absolute from bottom of page? etc)

**Comment by holtolee** [comment]
This just saved me centering a QR code on multiple pages, margin wasn't working well, please add this to the documentation it will be helpfull for other people.

**Comment by HeihoffJ** [comment]
This is working very well with text and images. My problem is, it is not working correctly (or at all) with a drawn canvas. Is there any workaround available ?

**Comment by rickyzhangca** [comment]
> Example with absolute positioning:
> 
> ```js
> var dd = {
>    content: [
>         {
>             text: 'text 1',
>             absolutePosition: {x:123, y:200}
>         },
>         {
>             text: 'text 2',
>             absolutePosition: {x:400, y:250}
>         },
>         {
>             text: 'text 3',
>             absolutePosition: {x:300, y:270}
>         },
>     ]
> }
> ```

Are we able to set "current position" like moving the cursor in a text editor? A workaround seems to be using margins. Thanks.
