### ISSUE TITLE
How to render an array of complex objects with pdf make?

### ISSUE THREAD

**Issue by corbetmw** [bpampuch/pdfmake#877]
Hi All,

Here's a stackoverflow question I asked. I was able to figure it out last night, but I just wanted it to be here to make it easier to find for anyone else that might have trouble with this.

[How to render an array of complex objects with pdf make?](http://stackoverflow.com/questions/42356990/how-to-render-an-array-of-complex-objects-with-pdf-make)

**Comment by liborm85** [comment]
Continued on stackoverflow.

**Comment by lylest** [comment]
facing the same issue
