### ISSUE TITLE
The playground stopped working

### ISSUE THREAD

**Issue by rfarko** [bpampuch/pdfmake#878]
the Playground on http://pdfmake.org has stopped working since a few days ago. It's a great tool and would appreciate if you can fix it.

**Comment by liborm85** [comment]
The site is working.

**Comment by mnewmedia** [comment]
Right know i'm getting:
```
DNS_PROBE_FINISHED_NXDOMAIN
```
and in devtools: 
```
Failed to load resource: net::ERR_NAME_NOT_RESOLVED
```
yesterday it worked..

**Comment by liborm85** [comment]
I tried it, and site working. Maybe a problem with your internet service provider

**Comment by mnewmedia** [comment]
Still not working! I also tried it on another place and on my cellphone. So I tried it with 3 different Internet providers. So maybe it's a problem with Switzerland :P

**Comment by justinthomas-syncbak** [comment]
Doesn't work for me either.  Receiving _ERR_NAME_RESOLUTION_FAILED_ message.

**Comment by liborm85** [comment]
Even for me, it stopped working. :(

**Comment by liborm85** [comment]
@bpampuch Site http://pdfmake.org/ doesn't work, receiving ERR_NAME_NOT_RESOLVED message. Can you solve it?

**Comment by bpampuch** [comment]
Yeah, I'll do it. I forgot to renew the domain

**Comment by jperocho** [comment]
the is still down

**Comment by sandeeppbajaj** [comment]
There is a alternative to run the playground on local, try these steps
```
git clone https://github.com/bpampuch/pdfmake.git
cd pdfmake
npm install
cd dev-playground
npm install # or: yarn
npm install -g nodemon
cd ..
nodemon ./dev-playground/server.js
```
Once up and running access playground on [`http://localhost:1234`](http://localhost:1234)

**Comment by liborm85** [comment]
@bpampuch When will be site available?

**Comment by bpampuch** [comment]
should be working now
