### ISSUE TITLE
Invalid filter algorithm: 197

### ISSUE THREAD

**Issue by CodingGorilla** [bpampuch/pdfmake#879]
I recently ran into an issue where pdfmake would generate the error:

> Invalid filter algorithm: 197

When attempting to generate a PDF with a specific PNG image embedded.  I was able to load the PNG into just about every other program I had with no issues, and opening it with an editor and re-saving the image resolved the issue.  But I'm curious what might have been the cause of the issue so I can try to avoid it in the future.

**Comment by liborm85** [comment]
By specification https://www.w3.org/TR/PNG-Filters.html, chapter 6.1, filter algorithms are only `0`, `1`, `2`, `3`, `4`.
Your PNG using algorithm `197`, this is not by specification. Perhaps you generated incorrect PNG.

**Comment by CodingGorilla** [comment]
@liborm85 Thanks for the response; these are customer generated images, is there any way to know what that filter algorithm is or how it was used in the PNG (if it's non-standard) so that we can advise our customers what _not_ to do when making these images?

**Comment by liborm85** [comment]
With PNG file I will not help much. Pdfmake using library [pdfkit](https://github.com/devongovett/pdfkit) for create PDF file (in which PNG file reads). You can try asking there https://github.com/devongovett/pdfkit/issues.
