### ISSUE TITLE
sticktogether: text on same page

### ISSUE THREAD

**Issue by anilgulecha** [bpampuch/pdfmake#88]
Hi, when setting out the layout, I'd like the underlying engine to take care of text reflow across pages. However I'd like to mark certain blocks of text as 'sticktogether' or something, which will make sure the engine will move to the next page if the block will not fit into this current page.

(Of course if the block is larger than a page, then this option will be ignored.)

Can something like this be done right now? I did not seem to find such a feature, and thus this issue. If it can be done, please provide a pointer, and close the issue.

**Comment by liborm85** [comment]
Implemented by PR https://github.com/bpampuch/pdfmake/pull/1073.
