### ISSUE TITLE
UL listStyle?

### ISSUE THREAD

**Issue by korenanzo** [bpampuch/pdfmake#881]
Hi,
Is it possible to change the bullet style in Unordered lists?

it should be something like:

`
 { ul: [ 'one', 'two', 'three', ], listStyle:'square' } 
`

Thanks, RIc

**Comment by korenanzo** [comment]
I've just seen the  #559 request, it could be ok for me but in the current distribution (and current playground) it doesnt work: do I need to fork and compile it by myself?

**Comment by liborm85** [comment]
Version with UL styling is not released yet, you can build, use this instructions: https://github.com/bpampuch/pdfmake#building-from-sources

**Comment by korenanzo** [comment]
thanks  :)

**Comment by Benibur** [comment]
hello, do you know when this feature will be merged in the the current release ?
being able to add styles inside a LI will be great ! ! 
for instance : 
`{ ol: [
  'item 1', 
  ['item2', {text:'in bold', style:{bold:true}}], 
  'item3'
]}
`

**Comment by lazymesh** [comment]
yes now you can use type: 'square' in ul for pdfmake

**Comment by lnvglr** [comment]
it would be nice if it were possible to add you own character to use as a bullet, e.g. a mid dot (·) or a dash (-). is there any perspective for that?
