### ISSUE TITLE
pdfMake.createPdf is not a function

### ISSUE THREAD

**Issue by vvumm** [bpampuch/pdfmake#882]
Hi,

I have used pdfmake to generate a report page in my project. We are using ftl files for rendering the UI.

Imported the required JS libraries as below:
FTL File :- 
```
<script type="text/javascript" src="${genericJsPath}/pdfmake.min.js"></script>
<script type="text/javascript" src="${genericJsPath}/vfs_fonts.js"></script>
<script type="text/javascript" src="${genericJsPath}/pdfdocgenerator.js"></script>
```

JS File :- 
Below is the usage of pdfMake in my js file.

```
function generatePDF(){
	var docDefinition = {
			pageMargins: [70, 100, 80, 80],
			pageSize: 'A4',
			header: {
				margin: [50, 50, 0, 0],
				columns: [
				          {
				        	  table: {
				        		  body: [
				        		         [
				        		          {
				        		        	  image: myImage,
				    			        	  width: 150,
				        		        	  alignment: 'center'
				        		          }
				        		          ]
				        		         ]
				        	  },
				        	  layout: 'noBorders'
				          }
				          ]
			},
			footer: {
				columns: [
				          {
				        	  width:'15%',
				        	  table: {
				        		  body: [
				        		         [
				        		          {
				        		        	  margin: [14, 0, 0, 0],
				        		        	  image: myImage,
				    			        	  width: 80,
				        		        	  alignment: 'left'
				        		          }
				        		          ]
				        		         ]
				        	  },
				        	  layout: 'noBorders'
				          }
				]
			},
			content: [
				    	  table(externalDataRetrievedFromServer, ['id', 'date', 'name', 'type']),
			        ],
	};
	pdfMake.createPdf(docDefinition).download('MyReport.pdf');
}

```
Everything works fine in my local, but when integrated in my project it fails with error saying pdfMake.createPdf is not a function.

Regards,
VinayKumar.

**Comment by liborm85** [comment]
Probably you do not correctly initialized pdfmake in you project as the local.

**Comment by vvumm** [comment]
Hi Libo,

I tried to debug this issue many times and somehow lost around. But, finally i was able to fix the issue in my local.

In the source code of pdfmake.js we have the following lines in the beginning of file :

```
if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		_define([], _factory);_
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
```

In my application we have the react.js alredy loaded, and when i try to use this pdfmake the object pdfmake is not getting initalized properly as the factory method is not invoked during pdfmake initialization and so the object construction is not successful.

I have done the following change to the code and was successful in initialization of the object and then my application is running fine. Below is the exact change i did for the js to work : 

```
if(typeof exports === 'object' && typeof module === 'object')
		module.exports = factory();
	else if(typeof define === 'function' && define.amd)
		_define([], factory());_
	else {
		var a = factory();
		for(var i in a) (typeof exports === 'object' ? exports : root)[i] = a[i];
	}
```

So, can you please check and let me know if the above change is correct or it is written for a specific purpose. If you feel the change is correct kindly update the library so that no one else should face such difficulties.

Regards,
VinayKumar.

**Comment by ramsaylanier** [comment]
👍 for this - having the same problem

**Comment by liborm85** [comment]
This code generate webpack automatically, it can not be changed. The code will sure correctly.
