### ISSUE TITLE
pageMargins , header and footer

### ISSUE THREAD

**Issue by korenanzo** [bpampuch/pdfmake#883]
The margins set up by pageMargins do not affact the position of header and footer.

Even if margins are not inherited , the PageMargins should be considered apart: it isn't text feature  but rather a space definition.

to test, add this to the  margins example 

` 
  pageMargins: [ 30, 30, 30, 30 ],
      footer: {
    columns: [
      'Left part',
      { text: 'Right part', alignment: 'right' }
    ]
  }, header: {
    columns: [
      'Left part',
      { text: 'Right part', alignment: 'right' }
    ]
  },

` 

Thanks,
Riccardo

**Comment by liborm85** [comment]
Yes, it is right. `pageMargins` is no effect on header and footer.
Header/footer have position "before" margins.
