### ISSUE TITLE
Are there default fontDescriptors that can be used when using the pdf printer?

### ISSUE THREAD

**Issue by parky128** [bpampuch/pdfmake#885]
I have some node express middleware for serving generating and serving back documents based on the example [here](https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js)

In the example the fontDescriptors get passed into the pdf printer constructor, so using that example, I have to have a fonts folder with those font files located under the root of my server application directory.

Doesn't pdfmake ship with some fonts already bundled in? Looking in the vfs_fonts.js file I see there are some Roboto ones already defined inline. How\when do these get used?

Is there a way to optionally supply fonts and if not provided, pdfmake\pdf printer will use these inline defined ones?

**Comment by liborm85** [comment]
Pdfmake has no built-in fonts.
Package includes TTF files for Roboto font: https://github.com/bpampuch/pdfmake/tree/master/examples/fonts. You can use any font (for example, downloaded from internet) and you just define the correct path to file.
