### ISSUE TITLE
how to print pdf view directly to printer device?

### ISSUE THREAD

**Issue by phonsay** [bpampuch/pdfmake#887]
Help me please, I would like to print out pdf view that generate by pdfmake to printer if I click button print.
How to do that.
I use InvoiceService.createPdf(dd).print(); but not working.

**Comment by liborm85** [comment]
You use a supported browser? See https://github.com/bpampuch/pdfmake/issues/800.

**Comment by phonsay** [comment]
It work on android device?

**Comment by liborm85** [comment]
See https://github.com/bpampuch/pdfmake/issues/800
