### ISSUE TITLE
ipaddress or uuid string can not wrap correct

### ISSUE THREAD

**Issue by lerit** [bpampuch/pdfmake#890]
in table,some text are ip address or uuid string,such as:
67e404e5-d4fb-2732-be14-2f60cf8b3cc2
::ffff:61.50.102.18

version:0.1.26

**Comment by liborm85** [comment]
Any example?

**Comment by lerit** [comment]
![00](https://cloud.githubusercontent.com/assets/4743467/23585136/ae536bf2-01b0-11e7-9880-dae213795efa.png)

**Comment by liborm85** [comment]
Here it wraps correctly:

```js
var dd = {
	content: [
		{
			table: {
				body: [
					['Text text [67e404e5-d4fb-2732-be14-2f60cf8b3cc2] text text', 'loongtextabcdefghijklmnopqrstuvwxyzabcdefghijklmnopqrstuvwxyz'],
					['Text Text [67e404e5-d4fb-2732-be14-2f60cf8b3cc2] text', 'text']
				]
			}
		}
	]
}
```

It is strange that in your table with some wraps correctly and some do not.

**Comment by lerit** [comment]
@liborm85  yes, some wraps correctly and some do not
i will copy my json data here ,then you can test it.

**Comment by lerit** [comment]
@liborm85 
my json data:
var dd =  {
     content: [{
         "table": {
             "headerRows": 1,
             "widths": [90, 90, 90, 90, 90],
             "body": [
                 [{
                     "text": "account",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "opertype",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "source",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "comment",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "datetime",
                     "bold": true,
                     "fontSize": 12
                 }],
                 ["j", "modify data", "web", "update plan:[9847b959-135a-7014-3ad5-5223f4d2eaf5]", "2017/03/06 09:28"]
             ]
         }
     }]
 }

**Comment by lerit** [comment]
@liborm85 
this is my json data:(i just find that remove widths settings will work fine,but why)
var dd =  {
     content: [{
         "table": {
             "headerRows": 1,
             "widths": [90, 90, 90, 90, 90],
             "body": [
                 [{
                     "text": "account",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "opertype",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "source",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "comment",
                     "bold": true,
                     "fontSize": 12
                 }, {
                     "text": "datetime",
                     "bold": true,
                     "fontSize": 12
                 }],
                 ["j", "modify data", "web", "update plan:[9847b959-135a-7014-3ad5-5223f4d2eaf5]", "2017/03/06 09:28"]
             ]
         }
     }]
 }

**Comment by liborm85** [comment]
@lerit Pdfmake using the Unicode Line Breaking Algorithm (UAX #14) for splitting words, it is implemented by https://github.com/devongovett/linebreak package. Maybe is linebreak dependecy is some bug.

**Comment by liborm85** [comment]
Wrapping is correct for Unicode. How to create a break is described here https://github.com/devongovett/linebreak/issues/7

**Comment by liborm85** [comment]
I'm implemented "hard" wrapping if is word too long. See https://github.com/bpampuch/pdfmake/issues/204#issuecomment-302877081
