### ISSUE TITLE
Text above each other

### ISSUE THREAD

**Issue by umarmughal824** [bpampuch/pdfmake#891]
Hi, I am using datatables to PDF export option but when I export it with too much it overwrites the data. The data comes above each other and look very akward and distorted.
Here is the example image with the related issue. The overflowing text is highlighted in red.

http://imgur.com/a/Gp1aq

I have contacted the dataTables export about the issue but they responded that its the error in pdfmake.
You can see that link as well.
https://datatables.net/forums/discussion/comment/106477/#Comment_106477

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/204
