### ISSUE TITLE
Conditional PageBreak

### ISSUE THREAD

**Issue by mico88** [bpampuch/pdfmake#892]
I would need to add page break in case of a paragraph (table, table row) is split between two pages. I mean avoid automatic page brake inside unwanted place. And is it possible to align part of a page vertically? To bottom for example, but only if fits all the content. Footer is not a solution in this case assume.

**Comment by mico88** [comment]
I just discovered pageBreakBefore function :). But still looking for possibility to align node vertically to the bottom.

**Comment by liborm85** [comment]
Vertical alignment to bottom is not supported. So how do you write, you can use `pageBreakBefore`.

**Comment by mazak** [comment]
I'm also looking for a way to mark a paragraph to avoid page breaks inside it. In case there would be a page break inside - use a page break before.

So, an equivalent of CSS:
`page-break-inside: avoid;`

**Comment by pedrohql** [comment]
@ujtordai I know I'm late, but to leave your question answered there's a property of currentNode called pageNumbers. It's an array containing the numbers of the pages which the current node is split between.

Example:
```
pageBreakBefore: function (currentNode, followingNodesOnPage,
    nodesOnNextPage, previousNodesOnPage) {
    return currentNode.pageNumbers.length > 1;
}
```

**Comment by coyotte508** [comment]
I know I'm even later, but here's my trick.

In the document definition, I have this:

```
pdfMake.createPdf({
    content: [...],
    pageBreakBefore(currentNode, followingNodesOnPage, nodesOnNextPage, previousNodesOnPage) {
      return currentNode.pageNumbers.length > 1 && currentNode.unbreakable;
    }
  })
```
And when I want to make a node "unbreakable", I just do this:

```
{
   stack: ["a stack", "of", "unbreakable", "paragraphs"]
   unbreakable: true
}
```

That way the 4 lines of the stacks are not broken. Of course if your unbreakable object takes the whole page you'll have the same issue described by @pedrohql, in which case you would want to change the `pageBreakBefore` function to add a `previousNodesOnPage.length > 0`.

**Comment by DeepakKapiswe** [comment]
Thanks a lot @coyotte508 , It helped me a lot, I was wondering how to implement page breaking rule for long. Maybe this should be published in the documentation page.
