### ISSUE TITLE
pdf is cutting off table

### ISSUE THREAD

**Issue by bautistaaa** [bpampuch/pdfmake#893]
My pdf seems to be cutting off my table and the rest of the pdf. Has anyone seen this before?

https://imgur.com/a/Ziy1s

You can plug this into the playground as well and see

`var dd = {
	"content": [
		{
			"text": [
				{
					"text": "xxxxxxxxxxxxxxx",
					"style": "title"
				}
			]
		},
		{
			"text": [
				{
					"text": "Created on 03/02/2017, 2:52:29 pm",
					"style": "subTitle"
				}
			],
			"margin": [
				0,
				0,
				0,
				10
			]
		},
		{
			"text": [
				{
					"text": "PEO: ",
					"style": "field"
				},
				{
					"text": "xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "Division: ",
					"style": "field"
				},
				{
					"text": "xxxxxxxxxxxxxxxxxxxxxx",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "System Program Manager: ",
					"style": "field"
				},
				{
					"text": "xxxxxxxxxxxxxxxx.",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "Program Manager: ",
					"style": "field"
				},
				{
					"text": "N/A",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "ACAT: ",
					"style": "field"
				},
				{
					"text": "N/A",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "Active Phase: ",
					"style": "field"
				},
				{
					"text": "N/A",
					"style": "value"
				}
			]
		},
		{
			"text": [
				{
					"text": "Prime Contractor(s): ",
					"style": "field"
				},
				{
					"text": "N/A",
					"style": "value"
				}
			]
		},
		{
			"text": "",
			"margin": [
				0,
				0,
				0,
				10
			]
		},
		{
			"text": "Program Performance",
			"style": "title"
		},
		{
			"table": {
				"body": [
					[
						{
							"text": "Name",
							"style": "tableHeader"
						},
						{
							"text": "Manually Set",
							"style": "tableHeader"
						},
						{
							"text": "Rating",
							"style": "tableHeader"
						},
						{
							"text": "Comments",
							"style": "tableHeader"
						}
					],
					[
						"Overall",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					],
					[
						"Cost",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					],
					[
						"Schedule",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					],
					[
						"Performance",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					],
					[
						"Funding",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					],
					[
						"Logistics",
						"No",
						{
							"text": "None",
							"color": "grey"
						},
						[]
					]
				],
				"widths": [
					"auto",
					"auto",
					"auto",
					"*"
				]
			},
			"margin": [
				0,
				20
			]
		},
		{
			"text": "Program Summary",
			"style": "title"
		},
		{
			"table": {
				"body": [
					[
						"Accomplishments",
						{
							"table": {
								"body": [
									[
										[],
										[
											""
										]
									],
									[
										[
											{
												"ul": [
													{
														"text": [
															{
																"text": "NSTR"
															}
														]
													}
												]
											}
										],
										[
											""
										]
									]
								],
								"widths": [
									"auto",
									"*"
								]
							},
							"layout": "noBorders"
						}
					],
					[
						"Key Issues/Risks/Opportunities",
						{
							"table": {
								"body": [
									[
										[
											{
												"stack": [
													{
														"text": [
															{
																"text": "XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"
															}
														]
													}
												]
											},
											{
												"ul": [
													{
														"text": [
															{
																"text": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY"
															}
														]
													}
												]
											},
											{
												"ul": [
													{
														"text": [
															{
																"text": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY)"
															}
														]
													},
													{
														"text": [
															{
																"text": "YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYSDFASDFASDFASDFASDFASDFASDFL"
															}
														]
													}
												]
											},
											{
												"ul": [
													{
														"text": [
															{
																"text": "111111111111111111111111111111111111111111111111111111111111111111111111111111111111222222"
															}
														]
													},
													{
														"text": [
															{
																"text": "TO val/ver halted at BLE; will delay BLE DT/OT start"
															}
														]
													},
													{
														"text": []
													},
													{
														"text": [
															{
																"text": "ASDFASDFASDFASDFASDF resulted in dSADFand ASDFASDF"
															}
														]
													},
													{
														"text": []
													}
												]
											}
										],
										[
											""
										]
									]
								],
								"widths": [
									"auto",
									"*"
								]
							},
							"layout": "noBorders"
						}
					],
					[
						"Significant Activities over Next 90 days",
						{
							"table": {
								"body": [
									[
										[
											{
												"ul": [
													{
														"text": [
															{
																"text": "AAAAAAA XX ASDASDASDASD"
															}
														]
													}
												]
											}
										],
										[
											[
												{
													"stack": [
														{
															"text": [
																{
																	"text": "May-Jun 17"
																}
															]
														}
													]
												}
											]
										]
									]
								],
								"widths": [
									"auto",
									"*"
								]
							},
							"layout": "noBorders"
						}
					],
					[
						"PEO/BM Assistance Requested",
						[
							{
								"stack": [
									{
										"text": [
											{
												"text": "None"
											}
										]
									}
								]
							}
						]
					]
				],
				"widths": [
					"auto",
					"*"
				]
			},
			"margin": [
				0,
				20
			]
		},
		{
			"text": "Financial Execution",
			"style": "title"
		},
		{
			"table": {
				"body": [
					[
						{
							"text": "Appn",
							"style": "tableHeader"
						},
						{
							"text": "FY",
							"style": "tableHeader"
						},
						{
							"text": "APPV $M",
							"style": "tableHeader"
						},
						{
							"text": "BA $M",
							"style": "tableHeader"
						},
						{
							"text": "$M",
							"style": "tableHeader"
						},
						{
							"text": "%",
							"style": "tableHeader"
						},
						{
							"text": "Rating",
							"style": "tableHeader"
						},
						{
							"text": "OSD EOM GOAL",
							"style": "tableHeader"
						},
						{
							"text": "$M",
							"style": "tableHeader"
						},
						{
							"text": "%",
							"style": "tableHeader"
						},
						{
							"text": "Rating",
							"style": "tableHeader"
						},
						{
							"text": "OSD EOM GOAL",
							"style": "tableHeader"
						}
					],
					[
						"3080",
						2015,
						28.4,
						27.4,
						26.5,
						93.2,
						{
							"text": "Yellow",
							"color": "#ffe34c"
						},
						93.3,
						"",
						"",
						"",
						""
					],
					[
						"3080",
						2016,
						17.4,
						16.9,
						16.9,
						96.8,
						{
							"text": "Green",
							"color": "#329933"
						},
						83.3,
						"",
						"",
						"",
						""
					],
					[
						"3080",
						2017,
						28.6,
						29.7,
						23.7,
						82.8,
						{
							"text": "Green",
							"color": "#329933"
						},
						26.7,
						"",
						"",
						"",
						""
					]
				]
			},
			"margin": [
				0,
				20
			]
		},
		{
			"text": "Critical Events",
			"style": "title"
		},
		{
			"table": {
				"body": [
					[
						{
							"text": "Name",
							"style": "tableHeader"
						},
						{
							"text": "Threshold Date",
							"style": "tableHeader"
						},
						{
							"text": "Actual/Projected Date",
							"style": "tableHeader"
						}
					],
					[
						"Name\tThreshold Date\tActual/Projected DateContract Award for THL DP/SP Suite Update",
						"12/30/2016",
						{
							"text": "12/30/2016",
							"color": "black",
							"fillColor": "green"
						}
					],
					[
						"Beale OT&E Certification",
						"03/31/2017",
						{
							"text": "06/30/2017",
							"color": "red",
							"fillColor": "white"
						}
					],
					[
						"FYL Facilities Ready for PME Install",
						"09/30/2017",
						""
					]
				],
				"widths": [
					"*",
					"*",
					"*"
				]
			},
			"margin": [
				0,
				20
			]
		}
	],
	"styles": {
		"title": {
			"fontSize": 18,
			"bold": true,
			"alignment": "center"
		},
		"subTitle": {
			"fontSize": 14,
			"alignment": "center"
		},
		"field": {
			"fontSize": 15,
			"alignment": "left",
			"bold": true
		},
		"value": {
			"fontSize": 14
		},
		"alignRight": {
			"alignment": "center"
		},
		"tableHeader": {
			"bold": true,
			"fontSize": 13,
			"color": "black",
			"fillColor": "#dddddd"
		}
	}
}`

**Comment by liborm85** [comment]
Table must have defined all cells in row; and row must contain some text.
See: https://github.com/bpampuch/pdfmake/issues/176

**Comment by bautistaaa** [comment]
ah perfect thanks!
