### ISSUE TITLE
Issues on embedded font

### ISSUE THREAD

**Issue by lkachun9129** [bpampuch/pdfmake#894]
I am trying the generate a PDF with Chinese character in it. I use NotoSansCJK TC as the font. However, it seems that the embedded font was not in complete set, some characters were missing. (I am sure that the missing characters are supported by NotoSansCJK TC.)

From #564 , someone suggested using pdfmake.createPdf(dd).getBuffer() will solve the problem. I tried with no luck.

The missing characters are highlighted in yellow.
![](https://github.com/lkachun9129/myfiles/raw/master/github.bpampuch.pdfmake.issues.894.001.PNG)

Here is a fiddle for my case.
[https://jsfiddle.net/agw73nxf/5/](https://jsfiddle.net/agw73nxf/5/)

Remarks: it takes some time to load the 20MB vfs_fonts.js

**Comment by ramsaylanier** [comment]
👍 having same issue

**Comment by liborm85** [comment]
Pdfmake use for rendering PDF file library pdfkit. Is not able to fix in pdfmake. Please create issue in https://github.com/devongovett/pdfkit. Thanks.

**Comment by lkachun9129** [comment]
[Issue opened](https://github.com/devongovett/fontkit/issues/92)

**Comment by lkachun9129** [comment]
Just notice that the latest version 0.1.34 fixed the issue!!!!

https://jsfiddle.net/agw73nxf/7/

![image](https://user-images.githubusercontent.com/6640910/33436996-9777f52e-d621-11e7-96f4-3479f0a1f625.png)
