### ISSUE TITLE
Anchor to section

### ISSUE THREAD

**Issue by frikeldon** [bpampuch/pdfmake#897]
Hi

Exist some way to create an internal anchor to pdf section? In example

```javascript
{
  text: 'Some awesome title',
  name: 'title1'
},
{
  text: 'Anchor to title',
  link: '#title1'
}
```

**Comment by clemenskroell** [comment]
Any ETA on this?

**Comment by henrique2601** [comment]
I need this too.

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/ba8c004252de915db1214113f83a37199cc26005 (in master) and https://github.com/bpampuch/pdfmake/commit/eca07d35ebf930b2768d0299a962b6af765a9cd8 (in branch 0.1).

Pending to release pdfkit with this PR: https://github.com/foliojs/pdfkit/pull/947
