### ISSUE TITLE
Bangla font not working properly(joint letters).

### ISSUE THREAD

**Issue by bulucseku** [bpampuch/pdfmake#898]
Hi,
Thank you for this great tool, It is working fine. I can show bangla fonts also, but have some issue with joint letters. In bangla we have complex fonts, we called them joint letter. For example z-phola is combined with two different letter and form another letter as shown bellow:

(ত +  ্ + য) = ত্য 

pdfmake is showing as the left part, but it should be as right part.

I am not sure how can I fix this. Any idea please.

**I am using pdfmake at browser**

Regards,
Bulbul

**Comment by liborm85** [comment]
Pdfmake use for rendering PDF file library pdfkit. Is not able to fix in pdfmake. Please create issue in https://github.com/devongovett/pdfkit. Thanks.

**Comment by liborm85** [comment]
https://rawgit.com/devongovett/text-rendering-tests/fontkit/reports/fontkit.html
According to this report currently fontkit (this is part of pdfkit) doesn't have full support for this font.
