### ISSUE TITLE
Can't use image other than sampleImage.jpg

### ISSUE THREAD

**Issue by robertstrz** [bpampuch/pdfmake#90]
Hello. Whenever I try to add image to my pdf, the scripts generate the following error:

> ##### Uncaught TypeError: Cannot read property 'embed' of undefined

However when I add sampleImage.img as a source everything seems to be working fine.

`{
                    image: 'sampleImage.jpg',
                    width: 100,
                    height: 100,
                }
`

Is there some special requirements which need to be met?
Thanks

**Comment by arunsahni** [comment]
Does it mean, images need to be converted into base 64 before passing?

**Comment by Wabbala** [comment]
yup!

**Comment by fercreek** [comment]
@Wabbala im trying to convert into base64, but doesnt works. 
is possible get the image without convert?

**Comment by SergioMacGyver** [comment]
Look at this pdfmake documentation snippet:

```
{
  // under NodeJS (or in case you use virtual file system provided by pdfmake)
  // you can also pass file names here
  image: 'myImageDictionary/image1.jpg'
}
```

What do you mean by "virtual file system provided by pdfmake" ? How do I use it?

**Comment by spsaucier** [comment]
@SergioMacGyver That would be data-uri-encoding images with gulp into the vfs_fonts.js file, as specified in step 1 of https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side.

**Comment by atefBB** [comment]
https://github.com/bpampuch/pdfmake#images
What do they mean by `myImageDictionary` ? 
help plz ! 
Thanks !

**Comment by sorb999** [comment]
hi @atefBB it means when client side you will load your website then it can be something like 'content/img/image1.jpg'

**Comment by atefBB** [comment]
@sorb999 Thanks.
