### ISSUE TITLE
Small thing, noticed page orientation is case sensitive...

### ISSUE THREAD

**Issue by vishwajeets7** [bpampuch/pdfmake#901]
while working with the dynamic pdf output, noticed the "Landscape" page orientation does not work, but "landscape".

Submitting it as it may require negligible efforts to cover the same, adding a step toward perfection.

**Comment by vishwajeets7** [comment]
Thank you for adding FR.

Thanks to the entire team, for such awesome product.

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/e92dc06f7a5e988f8dd3724a9a3b97cd58b2f6f5.
