### ISSUE TITLE
Image rendering issue

### ISSUE THREAD

**Issue by TheOff** [bpampuch/pdfmake#902]
Hi! I have a special image, its url [here](http://pastebin.com/7GBmgyFD). But when in rendered pdf document I've got this 
[download.pdf](https://github.com/bpampuch/pdfmake/files/825016/download.pdf). So, could you please check this out?

![upload](https://cloud.githubusercontent.com/assets/9024674/23665857/5516aff0-0362-11e7-8378-3945c9bfda6c.png)

**Comment by liborm85** [comment]
pdfmake creating pdf files using the pdfkit library.

I'm created issue in pdfkit - https://github.com/devongovett/pdfkit/issues/648

**Comment by liborm85** [comment]
Citation from https://github.com/devongovett/pdfkit/issues/648:
> I think it's because the image is encoded with a wide gamut color space, where each color-value is more than 8 bits. Try converting the image to sRGB prior to embedding the image in the PDF.

I try it and after re-save image works.
