### ISSUE TITLE
Big delay generating pdf on ionic app

### ISSUE THREAD

**Issue by elmismopancho** [bpampuch/pdfmake#903]
I'm developing an app using ionic framework. The app generates reports and saves them to the filesystem. The main code for this proccess is in this fiddle [https://jsfiddle.net/ery5o8sz/](https://jsfiddle.net/ery5o8sz/)
The biggest delay is here `pdf.getDataUrl(function(t) {`
On iOS (ipad mini 1st gen), a doc with no photos takes 60 seconds before the callback is called.
A doc with 40 photos takes 100 seconds. Android devices seems to perform a lot better, giving times between 10 and 20 seconds. I've also tried with pdf.getBuffer getting similar performance.
I just wanted to let you know about the performance of the library on mobile devices, maybe there is a way to improve this.

**Comment by liborm85** [comment]
See https://github.com/bpampuch/pdfmake/issues/798, performance problems are in new version pdfkit (this library is used to generate pdf file).
