### ISSUE TITLE
Watermark - background text - rotate text

### ISSUE THREAD

**Issue by myakout** [bpampuch/pdfmake#906]
I need to add watermark text for each page. I used the following: 

`              var docDefinition = {
    			content: [], 
    			background: {
    				text: 'Dental Marketing', 
    				color: '#d0d0d0', 
    				fontSize: 100, 
    				width: 500, 
    				height: 1000, 
    				zIndex: -1, 
    				webkitTransform: "rotate(-45deg)",
    				webkitTransform: -45,
    				mozTransform: -45,
    				mozTransform: "rotate(-45deg)",
    				margin: [0]
    			}
    		};`

But `webkitTransform` & `mozTransform` not working with me .. How can I rotate text to be as watermark?

**Comment by liborm85** [comment]
What is `webkitTransform` and `mozTransform`? This is not CSS, but pdfmake library.
Example with watermark is here: https://github.com/bpampuch/pdfmake/blob/master/examples/watermark.js

**Comment by myakout** [comment]
@liborm85 Yeah, I know .. I'm trying to add watermark in PDF.
For example in HTML: http://stackoverflow.com/a/40853561 

How can I add style to rotate text in PdfMake Library ?

**Comment by liborm85** [comment]
This is not yet in pdfmake. Watermark can be only one line...
