### ISSUE TITLE
How to calculate absolute positions with respect to a column cell

### ISSUE THREAD

**Issue by gigglegirl** [bpampuch/pdfmake#908]
Hi , 
In my code i am drawing a circle , and trying to put text on it, but as soon as change length of the    content text values , my text values '1' and '2' , shifts from there place , currently i am using absolutPosition to put the values over the circle .

My data is dynamic what can i do so that values are always on the circles .
and i want to know how to calculate the x and y coordinate values , which point is taken as the reference point for calculating coordinates .

Currently if i increase the value of 'y' coordinates text goes down as per my understanding if i am increasing the value of 'y' , it should go up the axis .

What i think is if we know how to fix the coordinates of text with respect to cell , the problem could be resolved .Still not sure if this will work .

    var dd = {
	content: [
     {
	 table: {
		 body: [
			[{
			text: 'Column1',
                        noWrap:true,
                        bold:true,
                        fontSize:16
		    },
                    {
                        text: 'Column2',
                        alignment: 'left'
                    }
                    ],
		    [{ text:'Developing',
                     noWrap:false,
                     lineHeight:2,
                     fontSize:12,
		   },
		[{table: {
                       body: [
                          [
                           {  canvas: [
            		    {
                    	type: 'ellipse',
                    	x:10 , y: 10, r1:10,
                    	color: '#1ba4dd'
                         }]
                          },
                         {  canvas: [
            		    {
                    	type: 'ellipse',
                    	x:10 , y: 10, r1:10,
                    	color: '#1ba4dd'
                         }]}
                         ],	[ {
                                                        absolutePosition: {x: 130, y: 73},
						        text:'4'
    						    },
    						    {   absolutePosition: {x: 160, y: 73},
    						        text:'5'
    						    }
    						    ]]},
							}]]],}},] }

**Comment by liborm85** [comment]
If you use `relativePosition`, it should do what you want.

Example:
```js
var dd = {
  content: [
    {
      table: {
        body: [
          [
            {
              text: 'Column1',
              noWrap:true,
              bold:true,
              fontSize:16
            },
            {
              text: 'Column2',
              alignment: 'left'
            }
          ],
          [
            {
              text: 'Column1',
              noWrap:true,
              bold:true,
              fontSize:16
            },
            {
              text: 'Column2',
              alignment: 'left'
            }
          ],
          [
            {
              text:'Developing',
              noWrap:false,
              lineHeight:2,
              fontSize:12,
            },
            [
              {
                table: {
                  body: [
                    [
                      {
                        canvas: [
                          {
                            type: 'ellipse',
                            x:10 , y: 10, r1:10,
                            color: '#1ba4dd'
                          }
                        ]
                      },
                      {
                        canvas: [
                          {
                            type: 'ellipse',
                            x:10 , y: 10, r1:10,
                            color: '#1ba4dd'
                          }
                        ]
                      }
                    ],
                    [
                      {
                        relativePosition: {x: 5, y: 0},
                        text:'4'
                      },
                      {
                        relativePosition: {x: 5, y: 0},
                        text:'5'
                      }
                    ]
                  ]
                }
              }
            ]
          ]
        ]
      }
    }
  ]
};
```

**Comment by gigglegirl** [comment]
Thanks a lot for your help .It worked . :-)

**Comment by MastersonLienus** [comment]
Excuse me, how do I make the color of a cell in the table look over the canvas?
Thanks in advance.
