### ISSUE TITLE
Uncaught File 'Roboto-Medium.ttf' not found in virtual file system

### ISSUE THREAD

**Issue by RodrigoInosh** [bpampuch/pdfmake#910]
Hi, i'm having an issue with pdfmake. I import pdfmake.min.js and vfs_fonts.js but i can't create a pdf file in my page cause it throws that error:

Uncaught File 'Roboto-Medium.ttf' not found in virtual file system

I dont understand how can i solve it. Please i need help with this.

I forgot, im using windows 7

**Comment by Seh83** [comment]
Hi RodrigoInosh,

I had the same issue. Please include the vfs_fonts.js file as well. That would resolve the issue. 

--
SV

**Comment by djgupta** [comment]
Hi,
I have been facing the same issue as @RodrigoInosh .

**Comment by XeniaSiskaki** [comment]
We have the same problem in 0.1.28 (0.1.27 works ok)

We do:
```
require('pdfmake/build/pdfmake.js');
require('pdfmake/build/vfs_fonts.js');
```

**Comment by djgupta** [comment]
Hi @XeniaSiskaki,

The vfs_fonts is dependent on pdfmake. You have to add the dependency. 
#302 should help.

**Comment by XeniaSiskaki** [comment]
@djgupta was it added as a dependency as of 0.1.28?

**Comment by djgupta** [comment]
@XeniaSiskaki I am not sure.
I am using 0.1.26 and I had to do this.

**Comment by XeniaSiskaki** [comment]
I believe for us the problem is that `window` was replaced by `this` in vfs_fonts.js in 0.1.28

However, I don't know why this is happening

**Comment by liborm85** [comment]
This has been changed for compatibility with the web worker (see changelog https://github.com/bpampuch/pdfmake/releases/tag/0.1.28). It should never cause problems because it is in the browser `window` same as `this`.

**Comment by XeniaSiskaki** [comment]
Doesn't seem like `this` is bound to `window`. Adding a brakepoint in `vfs_fonts.js`, `this` is just an empty object.

**Comment by liborm85** [comment]
Strange that `this` is empty. Which framework do you use?

**Comment by XeniaSiskaki** [comment]
Sorry, I removed my comment cause I thought it was stupid. We are using `webpack` and managed to fix this by shimming `this` to `window` with the `webpack` `imports-loader` like this:
```
require('pdfmake/build/pdfmake.js');
require('imports?this=>window!pdfmake/build/vfs_fonts.js');
```

Hope this can be helpful for others!

**Comment by marcusbertram** [comment]
Your solution worked for me, thanks @XeniaSiskaki!

**Comment by alexxmde** [comment]
I downgraded to version 0.1.26 and it got back to work

**Comment by itditp** [comment]
"Amazing" library. I tried it during 3days. f## fonts destroy  the whole library! Great!

**Comment by Pragmateek** [comment]
Same issue with **Browserify**.
@ammulder has found a fix: https://github.com/bpampuch/pdfmake/issues/864#issuecomment-298341323
I simply do:

    import pdfMake from "pdfmake/build/pdfmake";
    import pdfFonts from "pdfmake/build/vfs_fonts";
    pdfMake.vfs = pdfFonts.pdfMake.vfs;

**Comment by ShehramTahir** [comment]
declare var require: any;
 var pdfMake = require('pdfmake/build/pdfmake.js');
 var pdfFonts = require('pdfmake/build/vfs_fonts.js');
 pdfMake.vfs = pdfFonts.pdfMake.vfs;

I am doing like this 
but it is giving me error that "File 'Roboto-Regular.ttf' not found in virtual file system"

Upper solutions not working on my side

**Comment by alexxmde** [comment]
@ShehramTahir none of these solutions worked for me, I downgraded to a version from months ago and it continued to work smoothly on my project

**Comment by Tonio31** [comment]
@XeniaSiskaki! You saved me. Thanks. it works like a charm

**Comment by rstoenescu** [comment]
> var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;

I think @ShehramTahir 's solution needs to be added to the documentation.

**Comment by davidyeiser** [comment]
Agree with @rstoenescu. The Getting Started section is not clear on this.

**Comment by legreco** [comment]
@XeniaSiskaki  thanhs
require('imports-loader?this=>window!pdfmake/build/vfs_fonts.js');
works fine!

**Comment by devqazi** [comment]
@shehramtahir solution fixed it for me when using it in electron

**Comment by chess92** [comment]
if you are linking it thru HTML tags, make sure you link the pdfmake file first and the font file below it

**Comment by pevargasg** [comment]
Anyone knows why I'm getting this error?
**error TS2304: Cannot find name 'require'.**

This happened after I added the solution: 
```
var pdfMake = require('pdfmake/build/pdfmake.js');
var pdfFonts = require('pdfmake/build/vfs_fonts.js');
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

**Comment by jamesond** [comment]
Anyone using Aurelia and requireJS? 
Still trying to get my fonts to load properly.
 import * as pdfmake from 'pdfmake';
import pdfFonts from "pdfmake/build/vfs_fonts";
I get the File 'Roboto-Medium.ttf' not found in virtual file system
Thanks for any help, I feel like I have tried all combinations to get this to work.

**Comment by RizkiDPrast** [comment]
i use requirejs and in my case i edited vfs_fonts.js 
from
/// ```this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {```

to
///    ```pdfMake = pdfMake || {}; pdfMake.vfs = {```
then it works

**Comment by KamayaniT** [comment]
I am trying to use this plugin in my Ionic 4 project. 
When I try to enter :

`pdfMake.vfs = pdfFonts.pdfMake.vfs;`

it gives me error for vfs saying "`Cannot assign to 'vfs' because it is a constant or a read-only property`". Is it not compatible with ionic4 ? 
Any idea?

**Comment by ghenry22** [comment]
@KamayaniT remove the @types/pdfMake to resolve that problem. I think the types file may need to be updated.

But I still see the error about the font not being found

**Comment by naveed-ahmad** [comment]
Was facing same issue, rails + webpacker. 

And solution for me was:

```
require('pdfmake/build/pdfmake');
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;
```

**Comment by atulmith** [comment]
I was facing the same issue in reactjs project.
Just added this line 
import pdfMake from "pdfmake/build/pdfmake";
import vfsFonts from "pdfmake/build/vfs_fonts";

pdfMake.vfs = vfsFonts.pdfMake ? vfsFonts.pdfMake.vfs : pdfMake.vfs;


And now it works like wonder

**Comment by alexeybryk** [comment]
File `vfs_fonts.js` contains `this.pdfMake = pdfMake || {}; this.pdfMake.vfs = {...}`.
Solution for me was :
```
constructor() {
	super();

	this.pdfMake = {};
}
```
async functions:
```
this.pdfMake = await import(/* webpackChunkName: "pdfMake" */ 'pdfmake/build/pdfmake.js');

if (this.pdfMake) {
	await import(/* webpackChunkName: "pdfFonts" */ 'pdfmake/build/vfs_fonts.js');

	const pdfDocGenerator = await this.pdfMake.createPdf(pdfDoc);

	pdfDocGenerator.getDataUrl((dataUrl) => {
		this.setState({...});
	});
}
```

**Comment by scottyh527** [comment]
I'm using react and having the below issue, 

Unhandled rejection File 'data/Helvetica.afm' not found in virtual file system

I tried importing it this way 

import pdfMake from "pdfmake/build/pdfmake";
import vfsFonts from "pdfmake/build/vfs_fonts";

pdfMake.vfs = vfsFonts.pdfMake ? vfsFonts.pdfMake.vfs : pdfMake.vfs; 

pdfMake.fonts = {
      Courier: {
        normal: 'Courier',
        bold: 'Courier-Bold',
        italics: 'Courier-Oblique',
        bolditalics: 'Courier-BoldOblique'
      },
      Helvetica: {
        normal: 'Helvetica',
        bold: 'Helvetica-Bold',
        italics: 'Helvetica-Oblique',
        bolditalics: 'Helvetica-BoldOblique'
      },
      Times: {
        normal: 'Times-Roman',
        bold: 'Times-Bold',
        italics: 'Times-Italic',
        bolditalics: 'Times-BoldItalic'
      },
      Symbol: {
        normal: 'Symbol'
      },
      ZapfDingbats: {
        normal: 'ZapfDingbats'
      }
    };

    var docDefinition = {
      pageOrientation: 'landscape',
      info: {
        title: this.formatTitle(filename, territory, 'pdf')
      },
      header: territory ? {text: territory, alignment: 'center' }: {text: filename, alignment:'center'},
      defaultStyle:{
        font:'Helvetica',
        fontSize:6,
        alignment:'center'
      },
      content: [
        {
          layout: 'lightHorizontalLines', // optional

          table: {
            // headers are automatically repeated if the table spans over multiple pages
            // you can declare how many rows should be treated as headers
            headerRows: 1,
            widths: [ ],
            body: [columns]
          }
        }
      ],
      footer: function(currentPage, pageCount) {
        if(pageCount < 2) {
          return {text: currentPage.toString() + ' of ' + pageCount , alignment:'center'}; }
        }
    };

But it is still giving me an error. Any idea how I can import the helvetica that comes with it?

**Comment by ArbestNew** [comment]
For client-side use with webpack, I  suggest go to this page https://pdfmake.github.io/docs/getting-started/client-side/

You can import pdfMake by:

```
import pdfMake from "pdfmake/build/pdfmake";
import pdfFonts from "pdfmake/build/vfs_fonts";
pdfMake.vfs = pdfFonts.pdfMake.vfs;

let doc = {
    content: [
      'First paragraph',
      'Another paragraph, this time a little bit longer to make sure, this line will be divided into at least two lines'
    ]
  }
  pdfMake.createPdf(doc).download('test.pdf')
```

**Comment by ariunbatb** [comment]
my solution was edit vfs_fonts.js
from 
`this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = {`
to 
`pdfMake = pdfMake || {}; pdfMake.vfs = {`

and removed this line

`pdfMake.vfs = pdfFonts.vfs;`

**Comment by kirykr** [comment]
create a new field in the project where you keep your custom JS file for example `packs/vfs_fontsjs`
replace `this.pdfMake = this.pdfMake || {}; this.pdfMake.vfs = `
whith `window.pdfMake = window.pdfMake || {}; window.pdfMake.vfs = `
and require the file from the new file instead.

**Comment by Anuragck** [comment]
> Same issue with **Browserify**. @ammulder has found a fix: [#864 (comment)](https://github.com/bpampuch/pdfmake/issues/864#issuecomment-298341323) I simply do:
> 
> ```
> import pdfMake from "pdfmake/build/pdfmake";
> import pdfFonts from "pdfmake/build/vfs_fonts";
> pdfMake.vfs = pdfFonts.pdfMake.vfs;
> ```

Thank You..

**Comment by WelltonQ** [comment]
how i solved:

npm remove pdfmake
npm remove @types/pdfmake

npm i pdfmake
npm i @types/pdfmake -D

**Comment by testerez** [comment]
Here is my solution to dynamically import `pdfMake` (tested with `next@13.0.7` and `pdfmake@0.2.7`)

```ts
// pdfMake.ts
import _pdfMake from 'pdfmake/build/pdfmake'
import pdfFonts from 'pdfmake/build/vfs_fonts'
_pdfMake.vfs = pdfFonts.pdfMake.vfs

export const pdfMake = _pdfMake
```

```ts
// createPdf.ts
import type { createPdf as _createPdf } from 'pdfmake/build/pdfmake'

export const createPdf = async (...args: Parameters<typeof _createPdf>) => {
  // pdfmake is a heavy library. We use dynamic imports so that it's loaded only when needed.
  const { pdfMake } = await import('./pdfMake')
  return pdfMake.createPdf(...args)
}
```

now I can just import `createPdf` from `createPdf.ts` and don't have to worry about bundle size.

**Comment by gabrielbranch** [comment]
I use yarn and bower and load in my .lib folder by including it in the vendor section of webpack both the pdfMake.js and the vfs_fonts.js


`const vendor = [
  // js libraries
    './src/.lib/bower_components/pdfmake/build/pdfmake.min.js',
    './src/.lib/bower_components/pdfmake/build/vfs_fonts.js',
]`

I was able to solve this by importing the vfs js at the top level of my angular1 controller

`import pdfFonts from "../../../.lib/bower_components/pdfmake/build/vfs_fonts.js"; `

then in my function for generating a pdf

`$scope.makeThePdfBruh = function(){
 var docDefinition={...} // your def goes here
 pdfMake.vfs = pdfFonts.pdfMake ? pdfFonts.pdfMake.vfs : pdfMake.vfs;
 pdfMake.createPdf(docDefinition).download();
 }`

No need to import pdf make twice since its already loaded via webpack.  Maybe web pack is loading everything in some goofy order that we can't control. 

So I worked around it by just forcing the vfs js to import on the controller then assign it to the pdfMake. 
 Then wow it works.

**Comment by jabrij93** [comment]
> Anyone using Aurelia and requireJS? Still trying to get my fonts to load properly. import * as pdfmake from 'pdfmake'; import pdfFonts from "pdfmake/build/vfs_fonts"; I get the File 'Roboto-Medium.ttf' not found in virtual file system Thanks for any help, I feel like I have tried all combinations to get this to work.

Have you found the solution ? I am currently facing the same issue, I've tried the best answer solution but it failed when I ran yarn build. So I had no choice other than to use : 

import * as pdfMake from "pdfmake/build/pdfmake";
import * as pdfFonts from "pdfmake/build/vfs_fonts";

**Comment by jabrij93** [comment]
> I was facing the same issue in reactjs project. Just added this line import pdfMake from "pdfmake/build/pdfmake"; import vfsFonts from "pdfmake/build/vfs_fonts";
> 
> pdfMake.vfs = vfsFonts.pdfMake ? vfsFonts.pdfMake.vfs : pdfMake.vfs;
> 
> And now it works like wonder

Thanks ! after around 10 hours of trial and error various solutions, this works for me ! thankss !

**Comment by amiraiman** [comment]
Faced this problem while building for production with vite & laravel 10.

Solved by the solution provided by @atulmith with a slight tweak.

`
import * as pdfMake from "pdfmake/build/pdfmake";
import * as vfsFonts from "pdfmake/build/vfs_fonts";

pdfMake.vfs = vfsFonts.pdfMake ? vfsFonts.pdfMake.vfs : pdfMake.vfs;
`

**Comment by andidev** [comment]
Another solution for lazy loading with vite, works both when running vite, esm modules, in development with `vite dev` and with `vite build`

```ts
export async function lazyLoadPdfMake() {
    try {
        const pdfMake = (await import('pdfmake/build/pdfmake')).default;
        const pdfFonts = (await import('pdfmake/build/vfs_fonts')).default;
        if (pdfFonts?.pdfMake?.vfs) {
            pdfMake.vfs = pdfFonts.pdfMake.vfs; // needed to work when running admin localhost only, in release build pdfFonts is undefined
        }
        return pdfMake;
    } catch (e) {
        console.log(`Failed to lazy load pdfmake`, e);
        throw e;
    }
}
```

then use it like this
```ts
    const pdfMake = await lazyLoadPdfMake();
    pdfMake.createPdf(doc).download(`mypdf.pdf`);
```
