### ISSUE TITLE
1 pixel margin from right

### ISSUE THREAD

**Issue by istrion** [bpampuch/pdfmake#912]
On my pdf generated on android i got a blank line at right 
![capture d ecran 2017-03-17 a 16 51 00](https://cloud.githubusercontent.com/assets/2270645/24051345/132f1e10-0b32-11e7-9318-848a07bfb7d6.png)

my config : 

`var dd = {
    pageSize: 'A5',
    pageMargins: [0, 0],
    content: [

      {
        table: {
          widths: ['*'],` ...

**Comment by liborm85** [comment]
Please, add simple example runnable on pdfmake.org/playground.html.

**Comment by liborm85** [comment]
unreproducible
