### ISSUE TITLE
Blank first page when using landscape mode

### ISSUE THREAD

**Issue by r0fls** [bpampuch/pdfmake#913]
I can't get the first page to be landscape, it inserts a blank page before the first page of content when I try. Also I don't see how to copy from the playground or share the page. So, to reproduce you can use the images example from the playground and add this header as the first piece of content:

```javascript
{ 
             text: '\n\nUnordered list with longer lines', 
             style: 'header', 
             pageBreak: 'before', 
             pageOrientation: 'landscape' 
},
```

I would expect the first page to be landscape mode and show the full picture. However I get a blank portrait page followed by the content. What is the correct way to do this?

**Comment by liborm85** [comment]
See readme how to set page orientation: https://github.com/bpampuch/pdfmake#page-dimensions-orientation-and-margins

**Comment by r0fls** [comment]
ok fiddled some more and got it working, thank you.

**Comment by r0fls** [comment]
I didn't notice this quote, which was helpful:
>To change page orientation within a document, add a page break with the new page orientation.

**Comment by rickbolton** [comment]
@pankaj4197 you just need to define the `pageOrientation: 'landscape'` on the document definition e.g.

```
pdfMake.createPdf({
    pageOrientation: 'landscape',
    content: [
        // content here
   ]
})
```

**Comment by abdallah304** [comment]
@rickbolton 
Thanks man, it's working.
