### ISSUE TITLE
Fixed Column Height

### ISSUE THREAD

**Issue by ricky2k7** [bpampuch/pdfmake#914]
Hi,

I want to add text to a column and i would like that column to have a fixed height and width. I've managed to add a fixed width but i'm unable to add a fixed height.

Here's my code:
```
{
	columns:
	[
		{
			width: 200,
			height: 300, //doesn't work...
			text: someText
		}
	],
	absolutePosition:
	{
		x: 150,
		y: 75
	}
},
```

How can i accomplish this?

**Comment by liborm85** [comment]
Column has height required by the text. Smaller height would mean not displaying text.

**Comment by jonasao** [comment]
Please reopen this issue. Allowing the user to set a fixed column height is a feature. If the user sets the height too small, resulting in text being cut, its his/hers problem. I would really see this feature realized!
