### ISSUE TITLE
pdfmake.org down

### ISSUE THREAD

**Issue by bulucseku** [bpampuch/pdfmake#915]
Hi, the site pdfmake.org is down

Regards

**Comment by liborm85** [comment]
Yes, see: https://github.com/bpampuch/pdfmake/issues/878#issuecomment-287692825

**Comment by Henry23** [comment]
when is pdfmake.org going up?

**Comment by bpampuch** [comment]
should be working now

**Comment by AishS** [comment]
The website seems to be down again.

**Comment by nkarmi** [comment]
@bpampuch Yeah the site is down again 3 days in a row.
