### ISSUE TITLE
Exception when width defined as string

### ISSUE THREAD

**Issue by EricSch** [bpampuch/pdfmake#918]
There are 2 places in the lib, where `+v.toFixed(5)` is used.

should be `(+v).toFixed(5)`, if not, a string isn't converted.

Thanks

**Comment by liborm85** [comment]
`width` is numeric field, must be defined as number. String is not allowed.

**Comment by EricSch** [comment]
Doesn't make sense. Then why converting `v`?

**Comment by liborm85** [comment]
This code is not from pdfmake, but from other dependent library.
