### ISSUE TITLE
Cannot read property 'Roboto-Regular.ttf' of undefined 

### ISSUE THREAD

**Issue by M3enjamin** [bpampuch/pdfmake#92]
Hi,

I've got that wierd error when I try to create a pdf from the client side. 
Apparently the "baseSystem" object is undefined which causes the error when trying this: 
"var base64content = this.baseSystem[filename];" (line 17012)

when I try commenting out the lines, I got that "no unicode cmap for font" error that other users have with the .min file. Except I have it with the pdfMake.js too.

Does anybody have an idea of what I could be doing wrong here? I read other users could make it work with the non minified js file.

thx

**Comment by uncamoe** [comment]
When I do an install via bower, I am having this issue. 
On  Oct 11, 2014 bpampuch commented that it was fixed. 
When I run bower install do i need to add a version number? 
I still do not seem to have these font files and when I try to add other fonts they seem to be ignored. Can someone verify that the bower default download is the correct file? 
ps: I am using this through Angular, uiGrid export
