### ISSUE TITLE
Table with rowSpan breaks incorrectly at end of page even with dontBreakRows: true

### ISSUE THREAD

**Issue by geniass** [bpampuch/pdfmake#921]
I'm trying to make a table where a particular cell in each row contains 2 separate rows. To do this, I'm using  `rowSpan: 2` for all the other cells that are not split.

This works fine in most cases:
[pdfmake-issue-expected.pdf](https://github.com/bpampuch/pdfmake/files/867444/pdfmake-issue-expected.pdf)

But when there is slightly too much data on a page and it needs to continue to the next page:
[pdfmake-issue-actual.pdf](https://github.com/bpampuch/pdfmake/files/867443/pdfmake-issue-actual.pdf)

Here's a JSFiddle that demonstrates the problem:
https://jsfiddle.net/484py07u/

**Comment by berendvervelde** [comment]
Hi,
I solved this bug for my project, but only for tables with dontbreakrows = true. You could try my solution. You will have to build pdfmake yourself from source but there's a link on the pdfmake homepage how to do that. Create a local copy of pdfmake and unzip the archive in the src folder (overwrite the files), then build and use the /build/pdfmake.min js.
[rowspanfix.zip](https://github.com/bpampuch/pdfmake/files/1057543/rowspanfix.zip)

**Comment by liborm85** [comment]
Connected with https://github.com/bpampuch/pdfmake/issues/1042.

**Comment by liborm85** [comment]
Fix released in version 0.2.15.
