### ISSUE TITLE
Custom font Not Work, With An Error：No unicode cmap for font

### ISSUE THREAD

**Issue by GuanQiuQiao** [bpampuch/pdfmake#923]
I just started to use pdfmake,When I follow the step as this article advice  (https://github.com/bpampuch/pdfmake/issues/33),a new vfs_fonts.js is created,but it can't work,the error As is shown in the screenshots:
![Uploading B2LHML_DR8FYJ}C_YEL)L}I.jpg…]()

I really need help,Thanks in advance.

**Comment by liborm85** [comment]
Screenshot not uploaded, you can upload it again?

**Comment by GuanQiuQiao** [comment]
It since that I can't upload the screenshot,So I type it as the follow:

  Uncaught Error:No unicode cmap for font
          at t.registerTTF(http://localhost:8025/js/pdfmake.min.js:14:6016)
          at new t (http://localhost:8025/js/pdfmake.min.js:14:3106)
          at r.font (http://localhost:8025/js/pdfmake.min.js:14:1957)
          at r.getFont (http://localhost:8025/js/pdfmake.min.js:9:7442)
          at r.widthOfString (http://localhost:8025/js/pdfmake.min.js:9:7604)
          at http://localhost:8025/js/pdfmake.min.js:9:25981
          at Array.forEach(native)
          at h (http://localhost:8025/js/pdfmake.min.js:9:25668)     
          at n.buildInlines (http://localhost:8025/js/pdfmake.min.js:9:26514)
          at r.measureLeaf (http://localhost:8025/js/pdfmake.min.js:9:19814)

  Looking forward to your reply，Thank you

**Comment by liborm85** [comment]
This error throw version 0.1.20 (or older). Update to the latest version - https://github.com/bpampuch/pdfmake/releases/latest.

**Comment by GuanQiuQiao** [comment]
Update to the latest version,The problem has been solved,Thank you very much.But another error appeard,
      Uncaught File '../../fonts/msyh.ttf' not found in virtual file system
      Document._openPdf @ pdfmake.js:172
      Document.open @ pdfmake.js:180
      test @ (index):797
      (anonymous) @ VM157:1

My project structure is as follows:
    PdfMakeTest(My project Name)
    ------fonts
               -----msyh.ttf
    ------js
               -----pdfmake.js
               -----vfs_fonts.js
    ------View
               -----Test
                       -----pdfmake.cshtml(this view require pdfmake.js and vfs_fonts.js ,var dd = {...})

My code:
var dd={
defaultStyle: {
                font: 'msyh'
            },
content: (...)
}   

 pdfMake.fonts = {
            msyh: {
                normal: '../../fonts/msyh.ttf',
                bold: '../../fonts/msyh.ttf',
                italics: '../../fonts/msyh.ttf',
                bolditalics: '../../fonts/msyh.ttf',
            }
}    
   
I confused that why it can't find the msyh.ttf

**Comment by GuanQiuQiao** [comment]
My project structure (MVC)is as follows:
PdfMakeTest(My project Name)
------fonts
--------msyh.ttf
------js
--------pdfmake.js
--------vfs_fonts.js
------View
--------Test
-----------pdfmake.cshtml(this view require pdfmake.js and vfs_fonts.js ,var dd = {...})

**Comment by liborm85** [comment]
Here it is described how to add custom fonts: https://github.com/bpampuch/pdfmake/wiki/Custom-Fonts---client-side

Fonts must be in vfs_fonts.js file. A definition font file names must be without path.

**Comment by GuanQiuQiao** [comment]
Thank you very much,The pdf has been successfully opened.Thank you for providing so powerful and convenient tool
