### ISSUE TITLE
Chrome  Browser  crash to generate PDF with 3000 record may be 200 page of PDF

### ISSUE THREAD

**Issue by harikant-kumar** [bpampuch/pdfmake#925]
I have UI-grid( angular) trying to export grid data in CSV and PDF , CSV is working OK but exporting in PDF in chrome browser crash it. In IE and FF some time works some  time this also crash.

I have debugged the pdfmak.js and found the Document.prototype._createDoc method taking time.
In side  PdfPrinter.prototype.createPdfKitDocument method  builder.layoutDocument and renderPages taking too much time to complete the execution.
And  in  chrome, it hanged at doc.on('data', function() {...}). keep running in this event and after some time browser crash. it never reach to doc.on('end', function() {}); ( see the Document.prototype._createDoc)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/798
