### ISSUE TITLE
Specify font weight

### ISSUE THREAD

**Issue by dmatesic** [bpampuch/pdfmake#926]
Is there a way to specify the font weight?

**Comment by liborm85** [comment]
Is supported bold weight (see [playground](http://pdfmake.org/playground.html)). Specific weight depends on the file with font.

**Comment by pavelccz** [comment]
Is there a way to specify font weight? Not just "bold / not bold".

**Comment by Rainbowlemon** [comment]
+1, working on a project where I need 3 different font weights (book, heavy, and black). In CSS I'd usually use 400, 600 and 700, but not sure if that'd work here?

**Comment by safik222** [comment]
use **'bold': true** from documentation 

`{ text: 'Hello World', margin: [0, 0, 4, 8], 'width': 'auto', 'bold': true },`

https://pdfmake.github.io/docs/0.1/document-definition-object/styling/

**Comment by Jeremias-Nater** [comment]
There is a solution, although i think this is not sufficient since it currently requires me to make weird functions to apply the same rules to css and PDF.

You can register multiple fonts with any name you want. Therefore you can register a light version seperately like so:
```typeScript
const fonts: TFontDictionary = {
    RalewayLight: {
        normal: hostUrl + '/assets/fonts/Raleway/static/Raleway-Light.ttf',
        italics: hostUrl + '/assets/fonts/Raleway/static/Raleway-LightItalic.ttf',
    },
    Raleway: {
        normal: hostUrl + '/assets/fonts/Raleway/static/Raleway-Regular.ttf',
        italics: hostUrl + '/assets/fonts/Raleway/static/Raleway-Italic.ttf',
        bold: hostUrl + '/assets/fonts/Raleway/static/Raleway-Bold.ttf',
        bolditalics: hostUrl + '/assets/fonts/Raleway/static/Raleway-BoldItalic.ttf',
    },
    Hind: {
        normal: hostUrl + '/assets/fonts/Hind/Hind-Regular.ttf',
        bold: hostUrl + '/assets/fonts/Hind/Hind-Bold.ttf',
    },
};
```
