### ISSUE TITLE
custom properties

### ISSUE THREAD

**Issue by gr2m** [bpampuch/pdfmake#927]
Is there a way to write & read custom properties in a PDF? I want to create a web-based document Editor that allows to save the current document as PDF. Then when dragging the PDF on the editor, the source of the document (JSON data) is read from the custom property and used to render the source for the editor again.

Is something like that possible?

**Comment by liborm85** [comment]
Adding custom properties implemented by commit https://github.com/bpampuch/pdfmake/commit/cb43b8537b7b0e8a6e1b9a4cb9357422af01f115.
