### ISSUE TITLE
save pdf on server and generate link

### ISSUE THREAD

**Issue by levensailor** [bpampuch/pdfmake#930]
The current client side methods: open/print/download do not suffice for what I am trying to do. I would like to generate a pdf, save on the server, and email a link to that file. 

Does anyone have any ideas on how to make this work? If not I'm leaving this as a feature request.

**Comment by liborm85** [comment]
Example how to generate PDF on server side si here: https://github.com/bpampuch/pdfmake/blob/master/dev-playground/server.js.
PDF output can be saved and then processed on the server as you need.
