### ISSUE TITLE
How to set dynamically number of pages.

### ISSUE THREAD

**Issue by dinesh0906** [bpampuch/pdfmake#931]
I want to export my html div to pdf using html2canvas and pdfmake(version: 0.1.27). How ever it works when it is in a single page. But i am facing issue with making multiple page when i have a huge div. Can anyone please help me on this. Below is my code: 

html2canvas($('#profile1'), {
                onrendered: function (canvas) {
                    console.log(canvas);
                    var data = canvas.toDataURL('image/png');
                    var docDefinition = {                        
                        content: [{
                            image: data,
                            width: 500}]
                    };
                    pdfMake.createPdf(docDefinition).download("file.pdf");
                }
            });

**Comment by Wabbala** [comment]
Hi @dinesh0906, what is the issue that you are facing. I am also using html2canvas in combination with pdfmake. In our application I export google maps layouts to images and include them in a docdefiniton for pdfmake. Perhaps you can combine a html-parser with your div.

**Comment by dinesh0906** [comment]
Hi @Wabbala, Thanks for your reply. In my above message, I need to export div content to pdf. Div $('#profile1') needs more pages. How do i export in pdf by making multiple pages dynamically. Code is works when in single page but not works in multiple pages. Please refer my code and suggest what i missed out.

**Comment by Wabbala** [comment]
@dinesh0906 is it otherwise possible to do the following:
- split your div in smaller chunks;
- use html2canvas to iterate over the divs and store them in a docDefinition
- when completed create pdf from docDefinition

**Comment by dinesh0906** [comment]
Okay!. How to store multiple divs in a docDefinition? This is my docDefinition:

var docDefinition = {
                        content: [{
                            image: data,
                            pageBreak: "after",
                            width: 500
                        }]

**Comment by liborm85** [comment]
You can store divs in array (see https://www.w3schools.com/js/js_arrays.asp) and add for example by `push` (see https://www.w3schools.com/jsref/jsref_push.asp). You create part of docDefinition dynamically.

**Comment by dinesh0906** [comment]
@liborm85 @Wabbala My div content are dynamically expanded based on the values. It may be small or huge. So in that case how do i handle based on image size split into more pages by dynamically.
It needs to fit A4 size paper.

**Comment by Wabbala** [comment]
@dinesh0906 can't you determine the div size that fits on one page and then split the div in smaller chunks in order to make it fit over more pages? I think your question is kind of related to #357. While yours is a canvas item.

**Comment by Balkoth** [comment]
Like I answered in #357, you can split your image like this:
https://gist.github.com/Balkoth/d79a520ca2a3377c15e902ec68790aff

**Comment by liborm85** [comment]
Answered.

**Comment by NikhilRadadiya** [comment]
@Wabbala I'm pushing content to array like @liborm85 suggested but when passing it to `content` in `docDefination`. it doesn't print in correct order, I mean it is generating pdf in random order

**Comment by Wabbala** [comment]
That is strange, can you paste some code snippets?

**Comment by NikhilRadadiya** [comment]
@Wabbala  Here it is,
https://gist.github.com/NikhilRadadiya/de5c16eeeb87b38e37c4c5c3e37c9699

This is a function `createPdf()` which I'm using to create pdf

**Comment by NikhilRadadiya** [comment]
@Wabbala Sorry its not an issue with pdfmake, its an issue in object I created

**Comment by Wabbala** [comment]
Haha, glad I could help :-)
