### ISSUE TITLE
Angularjs UI-Grid, Formatting numbers to two decimal places when exported as a pdf

### ISSUE THREAD

**Issue by AndrewPreciado** [bpampuch/pdfmake#932]
I have content in my table that is formatted to two decimal places using:

    cellFilter : 'number : 2',

However, when I go to export this content as a pdf, the numbers are pouring outside of the table cell.  I would also like this content to be limited to two decimal places as well.  I am exporting a ui-grid within angularjs.  Is there a way I can do this?

**Comment by liborm85** [comment]
Pdfmake library does not do any formatting, text that you want to view the pdf you must define in docDefinition.
