### ISSUE TITLE
not working properly pagebrakeing

### ISSUE THREAD

**Issue by Balaraju1** [bpampuch/pdfmake#933]
![pdf](https://cloud.githubusercontent.com/assets/20854774/24495715/ba1d6526-1553-11e7-98c7-802ea8912b63.png)
![pdf1](https://cloud.githubusercontent.com/assets/20854774/24495841/1001c356-1554-11e7-875b-0862ea5535e8.png)

 #387

**Comment by vmontal** [comment]
dontBreakRows: true,
it's working!

**Comment by liborm85** [comment]
Any simple example to reproduce the problem?

**Comment by Balaraju1** [comment]
dontBreakRows is not Working

**Comment by liborm85** [comment]
No reaction.
