### ISSUE TITLE
Canvas line does not render

### ISSUE THREAD

**Issue by yal100394** [bpampuch/pdfmake#936]
I created a function that returns this:
`return { canvas: [{ type: 'line', x1: 10, y1: 10, x2: 520, y2: 10, lineWidth: 0.5, lineColor:'#E8E8E8' }]};`

When I render one row with this canvas, the line shows. But when I place it inside a loop, or there are multiple rows i add before and after this line, the line does not show. What is the problem with this?

**Comment by Balkoth** [comment]
You need to create a new Object for each line.
First create the line object
```js
const line = { type: 'line', x1: 10, y1: 10, x2: 520, y2: 10, lineWidth: 0.5, lineColor:'#E8E8E8' };
```
Then clone it in the loop
```js
return { canvas: [ Object.assign({}, line) ] };
```

**Comment by Jagdeep-Sing** [comment]
@liborm85 
This breaks everything when try to print from browser
