### ISSUE TITLE
React+Webpack Configuration: Uncaught File 'Roboto-Regular.ttf' not found in virtual file system

### ISSUE THREAD

**Issue by cah-alexsukhodolsky** [bpampuch/pdfmake#939]
I'm using the react library and building using webpack. When I try to building a base64 version of a pdf using pdfmake within my react app I get the following error:

`Uncaught File 'Roboto-Regular.ttf' not found in virtual file system`

I've read that I need to include the vfs_fonts.js script but including a reference to that file in my index.html file makes no difference. 

Has anyone managed to get pdfmake (download/base64 operations) working with react + webpack?

Thanks!

**Comment by liborm85** [comment]
Is file `vfs_fonts.js` included **after** `pdfmake.js`?
i.e.:
```
  <script src='build/pdfmake.min.js'></script>
  <script src='build/vfs_fonts.js'></script>
```

**Comment by yokeshvaradhan** [comment]
Hi i tried with ionic 2 same error
`<body>
  
  <ion-app></ion-app>
  
  <script src="build/polyfills.js"></script>
  
  <script src="build/main.js"></script>
  <script src='pdfmake/build/pdfmake.min.js'></script>
  <script src='pdfmake/build/vfs_fonts.js'></script>
</body>`

could someone help me

**Comment by cah-alexsukhodolsky** [comment]
@liborm85 yes--I included both reference, in that order, in my index.html file.

The issue was less with pdfmake and more with webpack. Specifically, I needed to:

1. `npm install --save-dev copy-webpack-plugin`
2. import and used the `CopyWebpackPlugin` and add it to the `plugins` section with the following config:
`new CopyWebpackPlugin([{from: 'node_modules/pdfmake/build/pdfmake.min.js'},{from: 'node_modules/pdfmake/build/vfs_fonts.js'}])`
3. Added references to the js files in index.html:
`<script src='build/pdfmake.min.js'></script>`
`<script src='build/vfs_fonts.js'></script>`
4. Do NOT import pdfMake into my React/Angular component. Simply use the global instance.

**Comment by XeniaSiskaki** [comment]
@cah-alexsukhodolsky what's the difference between what you did with the `CopyWebpackPlugin` and doing:

```
require('pdfmake/build/pdfmake.js');
require('pdfmake/build/vfs_fonts.js');
```

It's not working for us with webpack as well. But the problem started when we installed 0.1.28 (0.1.27 worked fine)

**Comment by cah-alexsukhodolsky** [comment]
@XeniaSiskaki I found that importing the libraries in a React component with a require/import statement didn't properly run the vfs_fonts.js code. Specifically, all vfs_fonts.js does is add a `vfs` property to the `window.pdfmake` object (it creates a window.pdfmake object if one doesn't exist already).
It's possibly that using `require` doesn't properly run the `vfs_fonts.js` code. Or maybe it runs it out of order and the `pdfmake.js` ends up overriding the `window.pdfmake` object.
Either way, setting up webpack to copy the pdfmake/vfs_fonts files to the build directory and importing them directly in `index.html` got pdfmake working correctly (even with 0.1.28).

**Comment by ShehramTahir** [comment]
New to Ionic 2.

First I installed "npm install pdfmake --save"
Secondly I defined like this in the body of index.html file
```
<script src="build/main.js"></script>
 <script src='/pdfmake.min.js'></script>

```
Thirdly I defined  I amked used of this library
``` declare var require: any;
 var pdfMake = require('pdfmake/build/pdfmake.js');
 var pdfFonts = require('pdfmake/build/vfs_fonts.js');
 pdfMake.vfs = pdfFonts.pdfMake.vfs; 
```
In the last I am accessing the the pdfmake function like this
`pdfMake.createPdf(docDefinition).open();
`
Consoling both function
![image](https://user-images.githubusercontent.com/25816777/27834163-401db64e-60ef-11e7-84fd-52e453ed9af7.PNG)

Problem is that after doing all that it is not giving me success.
When pdfMake.createPdf(docDefinition).open(); is called it do nothing.

Console Tells me that libraries are included in my project.

How Can I solve my problem ??

**Comment by hoppy-kamper** [comment]
I was able to get the basic example working in React with Webpack by doing the following:

```
// PdfMakePrototype.js

import pdfMake from 'pdfmake/build/pdfmake';
import vfsFonts from 'pdfmake/build/vfs_fonts'

export default () => {

	const {vfs} = vfsFonts.pdfMake;
	pdfMake.vfs = vfs;
	
	pdfMake.createPdf({content: 'Hi. I am a PDF.'}).open();
}
```
and then you can call this somewhere in a way like:
```
import pdfMakePrototype from './PdfMakePrototype';
// ...
<Button onClick{() => PdfProto()} />
// ...
```

**Comment by gbluv** [comment]
We use typescript would be good to have support for it. 

Had to do something similar to make it work:

```
window.pdfMake = require('pdfmake/build/pdfmake.min');
var vfs = require('pdfmake/build/vfs_fonts');
window.pdfMake.vfs = vfs.pdfMake.vfs;

```

**Comment by vspedr** [comment]
@hoppy-kamper your solution works great! I took the time to create a sample app to demonstrate it, if anyone is interested:
https://github.com/vspedr/react-pdfmake-example

**Comment by zinge** [comment]
Example CreatePdf.vue

```
<template>
  <div id="create-pdf">
    <a class="button is-warning" @click="create">create pdf</a>
  </div>
</template>

<script>
import pdfMake from 'pdfmake/build/pdfmake.min.js'
import pdfFonts from 'pdfmake/build/vfs_fonts.js'

export default {
  name: 'CreatePdf',

  data () {
    return {
      pdfMake,
      pdfFonts,
      docDefinition: {
        content: 'This is an sample PDF printed with pdfMake, тест'
      }
    }
  },

  methods: {
    create () {
      this.pdfMake.vfs = this.pdfFonts.pdfMake.vfs
      this.pdfMake.createPdf(this.docDefinition).download('optionalName.pdf')
    }
  }
}
</script>
```

**Comment by joshuaalpuerto** [comment]
@hoppy-kamper Thanks! Got it working with your code sample 👍

**Comment by ershadahamed** [comment]
@gbluv ur solution works fine in laravel, using below in webpack.mix.js
window.pdfMake = require('pdfmake/build/pdfmake.js');
var vfs = require('pdfmake/build/vfs_fonts');
window.pdfMake.vfs = vfs.pdfMake.vfs;

**Comment by arivera12** [comment]
### Integration with vuejs as plugin

For anyone interested on how to integrate it as a **vuejs** plugin here its a working solution:

1. Create a vuejs plugin and name it like -> vue-pdfmake.js and drop this lines of code
```
import pdfmake from 'pdfmake/build/pdfmake.js'
import vfsFonts from 'pdfmake/build/vfs_fonts.js'
export default {
    install(Vue, options) {
        const { vfs } = vfsFonts.pdfMake;
        pdfmake.vfs = vfs;
        Vue.prototype.$pdfmake = pdfmake
    }
}
```

2. Install it in your main.js
```
import vuepdfmake from 'myplugins/vue-pdfmake.js'
Vue.use(vuepdfmake) 
```

3. Then in all your components instance  you can use it like:
`this.$pdfmake.createPdf(docDefinition).download('export.pdf');`

Hope this helps someone!

**Comment by break69** [comment]
I haven't found a solution before elsewhere and I found help here so sorry I'm digging up this post
Under Symfony 6 with webpack inspired by **@gbluv**'s post from Aug 30, 2017 (THANKS A LOT) it works

`import 'pdfmake'`
`const vfs = require('pdfmake/build/vfs_fonts')`
`window.pdfMake.vfs = vfs.pdfMake.vfs`
