### ISSUE TITLE
Not able to generate pdf report of huge data having more than 100 pages.

### ISSUE THREAD

**Issue by sunilkumarsingh** [bpampuch/pdfmake#940]
Hi All,

I am using pdfmake to download PDF of report on client side, in my report there are many tables that I am creating dynamically using object format.
My report PDF size my be 100-150 page but its creates only 38 pages.

I used the following solution given by you people and changed in pdfmake.js file **but issue remains same**.

function flow(stream) {
       var state = stream._readableState;
       debug('flow', state.flowing);
       if (state.flowing) {
         do {
           var chunk = stream.read(Number.MAX_SAFE_INTEGER); // grab MAX_SAFE_INTEGER bytes
         } while (null !== chunk && state.flowing);
       }
  }

**My docDefinition  is given below like where summary() and datailed() are two functions that i am using to  get huge data in multiple table format .**

    var docDefinition = {
        footer: function (currentPage, pageCount) {
            return currentPage.toString() + ' of ' + pageCount;
        },
        content: [
            {
                style: 'tableExample',
                table: summary(data)
            },
            datailed(data)
        ],
        // style of contest here.
        styles: {
            header: {
                fontSize: 18,
                bold: true,
                margin: [0, 0, 0, 10]
            },
            subheader: {
                fontSize: 16,
                bold: true,
                margin: [0, 10, 0, 5],
                alignment: 'center'
            },
            tableExample: {
                margin: [0, 5, 0, 15]
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black'
            }
        },
        defaultStyle: {
            // alignment: 'justify'
        }
    };

**Please provide any solution if you buddy have.**

**Comment by GuanQiuQiao** [comment]
If  have a problem of your  data，like the format...？check the date where it didn't show.

**Comment by liborm85** [comment]
As already mentioned probably got a mistake in docDefinition. You have complete sample, which could be run?

**Comment by sunilkumarsingh** [comment]
Hi,

Thanks !!!
Below is my sample doc Definition please check it.

    var docDefinition = {
        header: function() {
          return {
              columns: [
                 {
                      image: 'sampleImage.jpg',
                      width: 100,
                      margin: [50, 10, 0, 0],
                  },
                  {text:'http://www.mydomain.com',alignment:'left'}
              ]
          }
        },
        pageMargins: [50,70,50,0],
        footer: function (currentPage, pageCount) {
            return currentPage.toString() + ' of ' + pageCount;
        },
        content: [
            {
                style: 'tableExample',
                table: {
                      body: [
                      [{text: 'Machine Name', 'background-color':'#00ff00'}, 'test1'],
                      [{text: 'Machine Identifier', }, '968ca483d1543ce'],
                      [{text: 'Operating System', }, 'Windows Server '],
                      [{text: 'Profile', }, 'DISA-MissionCriticalClassified'],
                      [{text: 'Executed on', }, 'Fri Feb 10 2017 16:20:04'],
                      [{text: 'Mode', }, 'Automatic'],
                      [{text: 'Execution Results', alignment: 'center'},
                      {
                        // style: 'tableExample2',
                        table: {body: [[
                        {text: 'Severity', alignment: 'center'}, 
                        {text: 'Passed', alignment: 'center'},
                        {text: 'Failed', alignment: 'center'},
                        {text: 'Manual Intervention', alignment: 'center',valign:'center'},
                        {text: 'Total', alignment: 'center'}],

                        [{text: 'High', fillColor: '#ffcdd2'}, '19', '0', '0', '19'],
                        [{text: 'Medium', fillColor: '#fff9c4', style: 'tableHeader'}, '19', '0', '0', '19'],
                        [{text: 'Low', fillColor: '#C8E6C9', style: 'tableHeader'}, '19', '0', '0', '19'],
                        [{text: 'Total', style: 'tableHeader'}, '19', '0', '0', '19'],
                        ]
                      }}]
                ]}
            },
            {
            style: 'tableExample',
            table: {
                widths: [100, 100, '*'],
                body: [
                    [{text: 'Manual intervention', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                    [{
                        colSpan: 3,
                        table: {
                            widths: ['*', '*', 'auto'],
                            body: [[
                                {text: 'Rule No', style: 'tableHeader'},
                                {text: 'Severity', style: 'tableHeader'},
                                {text: 'Description', style: 'tableHeader'},
                                ],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                            ]
                        }
                    }, '', ''],
                ]
            },
                layout: 'noBorders'
            },
            {
            style: 'tableExample',
            table: {
                widths: [100, 100, '*'],
                body: [
                    [{text: 'Manual intervention', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                    [{
                        colSpan: 3,
                        table: {
                            widths: ['*', '*', 'auto'],
                            body: [[
                                {text: 'Rule No', style: 'tableHeader'},
                                {text: 'Severity', style: 'tableHeader'},
                                {text: 'Description', style: 'tableHeader'},
                                ],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                            ]
                        }
                    }, '', ''],
                ]
            },
                layout: 'noBorders'
            },
                                    {
            style: 'tableExample',
            table: {
                widths: [100, 100, '*'],
                body: [
                    [{text: 'Manual intervention', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                    [{
                        colSpan: 3,
                        table: {
                            widths: ['*', '*', 'auto'],
                            body: [[
                                {text: 'Rule No', style: 'tableHeader'},
                                {text: 'Severity', style: 'tableHeader'},
                                {text: 'Description', style: 'tableHeader'},
                                ],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                                [{text:'V-4587'},{text:'Low',background:'#C8E6C9'} ,{text:'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.'}],
                            ]
                        }
                    }, '', ''],
                ]
            },
                layout: 'noBorders'
            }
        ],
        // style of contest here.
        styles: {
            header: {
                fontSize: 18,
                bold: true,
                margin: [0, 0, 0, 10]
            },
            subheader: {
                fontSize: 16,
                bold: true,
                margin: [0, 10, 0, 5],
                alignment: 'center'
            },
            tableExample: {
                margin: [0, 5, 0, 15]
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black'
            }
        },
        defaultStyle: {
            font: 'OpenSans',
            // alignment: 'justify'
        }
    };

Attachment is my sample downloaded PDF.

[file.pdf](https://github.com/bpampuch/pdfmake/files/927449/file.pdf)

My final PDF having more than 200 pages but when I try to generate PDF my code breaks any where some time generates 28 page,105 pages and etc.

I want to generate full and all pages any body please suggest me that it is possible to generate 200+ pages using pdfmake is possible or not.

Please review my code is help for any further improvements.

**Comment by liborm85** [comment]
I'm content of you sample copied X times and I have 272 pages, everything was rendered ok.
Probably will be problem in next content which dynamically generate and not part of the sample.

**Comment by sunilkumarsingh** [comment]
Thanks for your update.
I will check my dynamic contents.

**Comment by GuanQiuQiao** [comment]
I test 401 pages,everything was rendered ok(use pdfmake v0.1.27).
here the test code:


    function helptest() {
        var cont = "[{style: 'tableExample',table: {body: [[{ text: 'Machine Name', 'background-color': '#00ff00' }, 'test1'],[{ text: 'Machine Identifier', }, '968ca483d1543ce'],[{ text: 'Operating System', }, 'Windows Server '],[{ text: 'Profile', }, 'DISA-MissionCriticalClassified'],[{ text: 'Executed on', }, 'Fri Feb 10 2017 16:20:04'],[{ text: 'Mode', }, 'Automatic'],[{ text: 'Execution Results', alignment: 'center' },{table: { body: [[{ text: 'Severity', alignment: 'center' }, { text: 'Passed', alignment: 'center' },{ text: 'Failed', alignment: 'center' },{ text: 'Manual Intervention', alignment: 'center', valign: 'center' },{ text: 'Total', alignment: 'center' }],[{ text: 'High', fillColor: '#ffcdd2' }, '19', '0', '0', '19'],[{ text: 'Medium', fillColor: '#fff9c4', style: 'tableHeader' }, '19', '0', '0', '19'],[{ text: 'Low', fillColor: '#C8E6C9', style: 'tableHeader' }, '19', '0', '0', '19'],[{ text: 'Total', style: 'tableHeader' }, '19', '0', '0', '19'],]}}]]}},";
        for (var i = 0; i <= 2000; i++)
        {
            cont+="{style: 'tableExample',table: {widths: [100, 100, '*'], body: [[{ text: 'Manual intervention', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color: '#FFFFFF' }, {}, {}],[{colSpan: 3,table: {widths: ['*', '*', 'auto'],body: [[{ text: 'Rule No', style: 'tableHeader' },{ text: 'Severity', style: 'tableHeader' },{ text: 'Description', style: 'tableHeader' },],[{ text: 'V-4587' }, { text: 'Low', background: '#C8E6C9' }, { text: 'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.' }],[{ text: 'V-4587' }, { text: 'Low', background: '#C8E6C9' }, { text: 'This is a star-sized column. The next column over, an auto-sized column, will wrap to accomodate all the text in this cell.' }], ]}}, '', ''],] },layout: 'noBorders'},";

        }
        cont = cont.substring(0, cont.length - 1);
        cont += "]";
        var data = eval('(' + cont + ')');
        var docDefinition = {
            //header: function () {
            //    return {
            //        columns: [
            //           {
            //               image: 'sampleImage.jpg',
            //               width: 100,
            //               margin: [50, 10, 0, 0],
            //           },
            //            { text: 'http://www.mydomain.com', alignment: 'left' }
            //        ]
            //    }
            //},
            pageMargins: [50, 70, 50, 0],
            footer: function (currentPage, pageCount) {
                return currentPage.toString() + ' of ' + pageCount;
            },
            content: data,
            // style of contest here.
            styles: {
                header: {
                    fontSize: 18,
                    bold: true,
                    margin: [0, 0, 0, 10]
                },
                subheader: {
                    fontSize: 16,
                    bold: true,
                    margin: [0, 10, 0, 5],
                    alignment: 'center'
                },
                tableExample: {
                    margin: [0, 5, 0, 15]
                },
                tableHeader: {
                    bold: true,
                    fontSize: 13,
                    color: 'black'
                }
            },
            defaultStyle: {
                font: 'msyh',
                // alignment: 'justify'
            }
        };

        pdfMake.fonts = {
            msyh: {
                normal: 'msyh.ttf',
                bold: 'msyhbd.ttf',
                italics: 'msyh.ttf',
                bolditalics: 'msyh.ttf',
            }
        };
        //导出PDF
        pdfMake.createPdf(docDefinition).download();
    }

**Comment by sunilkumarsingh** [comment]
Hi,

**Still i am facing same issues anyone can please see my complete code and suggest me for further solution .**

$scope.generatePdf = function () {
    $('#loaderbox').show();
    var data = $scope.pdfdata;

if (data.type == "Executive Summary") {
    var docDefinition = {       
        footer: function (currentPage, pageCount) {
            return currentPage.toString() + ' of ' + pageCount;
        },
        pageMargins: [50,70,50,0],
        content: [
            {
              style: 'tableExample',
              table: executive_summary(data)
            }
        ],
        // style of contest here.
        styles: {
            header: {
                fontSize: 18,
                bold: true,
                margin: [0, 0, 0, 10]
            },
            subheader: {
                fontSize: 16,
                bold: true,
                margin: [0, 10, 0, 5],
                alignment: 'center'
            },
            tableExample: {
                margin: [0, 5, 0, 15]
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black'
            }
        },
        defaultStyle: {
            font: 'OpenSans',
            // alignment: 'justify'
        }
    };
} else {
    var docDefinition = {
        pageMargins: [50,70,50,0],
        footer: function (currentPage, pageCount) {
            return currentPage.toString() + ' of ' + pageCount;
        },
        content: [
            {
                style: 'tableExample',
                table: executive_summary(data)
            },
            datailed(data)
        ],
        // style of contest here.
        styles: {
            header: {
                fontSize: 18,
                bold: true,
                margin: [0, 0, 0, 10]
            },
            subheader: {
                fontSize: 16,
                bold: true,
                margin: [0, 10, 0, 5],
                alignment: 'center'
            },
            tableExample: {
                margin: [0, 5, 0, 15]
            },
            tableHeader: {
                bold: true,
                fontSize: 13,
                color: 'black'
            }
        },
        defaultStyle: {
            font: 'OpenSans',
            // alignment: 'justify'
        }
    };
}

  var d = new Date();
  var pdfname = 'report-'+d.toISOString()+'.pdf';
    pdfMake.fonts = {
        'Roboto' : {
          normal: 'Roboto-Regular.ttf',
          bold: 'Roboto-Medium.ttf',
          italics: 'Roboto-Italic.ttf',
          bolditalics: 'Roboto-Italic.ttf'
        },

        'OpenSans' : {
          normal: 'OpenSans-Regular.ttf',
          bold: 'OpenSans-Medium.ttf',
          italics: 'OpenSans-Italic.ttf',
          bolditalics: 'OpenSans-Italic.ttf'
        }
    }
    pdfMake.createPdf(docDefinition).download(pdfname,function(){
    console.log('your pdf is done');
    $('#loaderbox').hide();
  });
}// end generatePdf

function executive_summary(data) {
    var message = '';
    var summary = data.summary[0];

    var total_high = summary.high_severity_success + summary.high_severity_failure + summary.high_severity_manual + summary.high_severity_skipped;
    var total_medium = summary.medium_severity_success + summary.medium_severity_failure + summary.medium_severity_manual + summary.medium_severity_skipped;
    var total_low = summary.low_severity_success + summary.low_severity_failure + summary.low_severity_manual + summary.low_severity_skipped;
    var success_per = summary.success_rules_count + '(' + parseInt(summary.success_rules_count / summary.total_rules * 100) + '%)';
    var failed_per = summary.failure_rules_count + '(' + parseInt(summary.failure_rules_count / summary.total_rules * 100) + '%)';
    var manual_per = summary.manual_rules_count + '(' + parseInt(summary.manual_rules_count / summary.total_rules * 100) + '%)';
    var skipped_per = summary.skipped_rules_count + '(' + parseInt(summary.skipped_rules_count / summary.total_rules * 100) + '%)';
    var tatal_per = summary.total_rules + '(100%)';
    
    switch (data.type){
        case 'Summary':
            message = 'Summary Report';
            break;
        case 'Executive Summary':
            message = 'Executive Summary Report';
            break;
        case 'Detailed Report':
            message = 'Summary Report';
            break;            
    }

    return {
        widths: ['*', 'auto'],
        body: [
            [{text: message, colSpan:2,alignment:'center', fillColor: '#6b6a6a',color:'#FFFFFF'},{}],
            [{text: 'Machine Name', }, summary.execution_status],
            [{text: 'Hostname', }, summary.server_name],
            [{text: 'Server Name', }, summary.server_name + ' (' + summary.username + '@' + summary.ip_addr + ')'],
            [{text: 'Operating System', }, summary.os_name + ' ' + summary.os_version],
            [{text: 'Profile', }, summary.profile_name + ' (Total Rules:' + summary.total_rules + ')'],
            [{text: 'Executed on', }, summary.actual_end_time],
            [{text: 'Execution Mode', }, summary.execution_mode],
            [{text: 'Execution Results'},
                {
                    table: {
                        body: [[
                                {text: 'Severity', alignment: 'center', style: 'tableHeader'},
                                {text: 'Passed', alignment: 'center', style: 'tableHeader'},
                                {text: 'Failed', alignment: 'center', style: 'tableHeader'},
                                {text: 'Manual Intervention', alignment: 'center', style: 'tableHeader'},
                                {text: 'Skipped', alignment: 'center', style: 'tableHeader'},
                                {text: 'Total', alignment: 'center', style: 'tableHeader'}],
                            [{text: 'High', fillColor: '#ffcdd2'}, {text:summary.high_severity_success, alignment: 'center'}, {text:summary.high_severity_failure, alignment: 'center'}, {text:summary.high_severity_manual, alignment: 'center'}, {text:summary.high_severity_skipped, alignment: 'center'}, {text:total_high, alignment: 'center'}],
                            [{text: 'Medium', fillColor: '#fff9c4'}, {text:summary.medium_severity_success, alignment: 'center'}, {text:summary.medium_severity_failure, alignment: 'center'}, {text:summary.medium_severity_manual, alignment: 'center'}, {text:summary.medium_severity_skipped, alignment: 'center'}, {text:total_medium, alignment: 'center'}],
                            [{text: 'Low', fillColor: '#C8E6C9'}, {text:summary.low_severity_success, alignment: 'center'}, {text:summary.low_severity_failure, alignment: 'center'}, {text:summary.low_severity_manual, alignment: 'center'}, {text:summary.low_severity_skipped, alignment: 'center'}, {text:total_low, alignment: 'center'}],
                            [{text: 'Total'}, {text:success_per, alignment: 'center'}, {text:failed_per, alignment: 'center'}, {text:manual_per, alignment: 'center'}, {text:skipped_per, alignment: 'center'}, {text:tatal_per, alignment: 'center'}],
                        ]
                    },
                }]
        ]}
} // end summary

function datailed(data) {
    if (data.rulelists.length > 0) {
        var bcolor = '';
        var success_list = [];
        var manual_list = [];
        var failed_list = [];
        var skipped_list = [];

        var success_tbl = {};
        var failed_tbl = {};
        var manual_tbl = {};
        var skipped_tbl = {};

        var rulelists = data.rulelists;
        var summary = data.summary[0];
        var success_cnt = summary.success_rules_count;
        var manual_cnt = summary.manual_rules_count;
        var failed_cnt = summary.failure_rules_count;
        var skipped_cnt = summary.skipped_rules_count;

        var header = [
            {text: 'Rule No', style: 'tableHeader'},
            {text: 'Severity', style: 'tableHeader'},
            {text: 'Description', style: 'tableHeader'}
        ];

        success_list.push(header);
        failed_list.push(header);
        manual_list.push(header);
        skipped_list.push(header);

        angular.forEach(rulelists, function (val, key) {
            if (data.type == 'Summary') {
                var consolelog = val.title;
            } else {
                var consolelog = val.title + '\n' + val.console;
            }

            switch(val.criticality){
                case 'Low' :
                    bcolor = '#C8E6C9';
                    break;
                case 'Medium' :
                    bcolor = '#fff9c4';
                    break;
                case 'High' :
                    bcolor = '#FFCDD2';
                    break;    
            }
            if (val.outcome.indexOf('manual') > -1) {
                manual_list.push([val.name, {text: val.criticality,background:bcolor}, {text: consolelog}]);
            } else if (val.outcome == 'failed') {
                failed_list.push([val.name, {text: val.criticality,background:bcolor}, {text: consolelog}]);
            } else if(val.outcome.indexOf('success') > -1){
                success_list.push([val.name, {text: val.criticality,background:bcolor}, {text: consolelog}]);
            }else {
                skipped_list.push([val.name, {text: val.criticality,background:bcolor}, {text: val.title}]);
            }
        });

        if (manual_cnt > 0) {
            var manual_tbl = {
                style: 'tableExample',
                table: {
                    widths: [100, 100, '*'],
                    body: [
                        [{text: 'Needs manual intervention', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                        [{
                                colSpan: 3,
                                table: {
                                    widths: ['*', '*', 'auto'],
                                    body: manual_list,
                                }
                            }, '', '']
                    ]
                },
                layout: 'noBorders'
            };
        }

        if (failed_cnt > 0) {
            var failed_tbl = {
                style: 'tableExample',
                table: {
                    widths: [100, 100, '*'],
                    body: [
                        [{text: 'Fialed', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a',color:'#FFFFFF'}, {}, {}],
                        [{
                                colSpan: 3,
                                table: {
                                    widths: ['*', '*', 'auto'],
                                    body: failed_list,
                                }
                            }, '', '']
                    ]
                },
                layout: 'noBorders'
            };
        }

        if (success_cnt > 0) {
            var success_tbl = {
                style: 'tableExample',
                table: {
                    widths: [100, 100, '*'],
                    body: [
                        [{text: 'Successful', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                        [{
                                colSpan: 3,
                                table: {
                                    widths: ['*', '*', 'auto'],
                                    body: success_list,
                                }
                            }, '', '']
                    ]
                },
                layout: 'noBorders'
            };
        }

        if (skipped_cnt > 0) {
            var skipped_tbl = {
                style: 'tableExample',
                table: {
                    widths: [100, 100, '*'],
                    body: [
                        [{text: 'Skipped', colSpan: 3, alignment: 'center', fillColor: '#6b6a6a', color:'#FFFFFF'}, {}, {}],
                        [
                            {
                                colSpan: 3,
                                table: {
                                    widths: ['*', '*', 'auto'],
                                    body: skipped_list,
                                }
                            }, '', '']
                    ]
                },
                layout: 'noBorders'
            };
        }

        var table = [
            manual_tbl,
            failed_tbl,
            success_tbl,
            skipped_tbl
        ]
        return table;
    }
} //end detaild

**Comment by GuanQiuQiao** [comment]
it is strange that when you use array，it will lost the pages，then I joint the data as json string and use eval function to change it as json object，it will be ok，I don‘t why’

**Comment by sunilkumarsingh** [comment]
Is there is need to convert data in JSON string and then convert in to object ?.

**Comment by GuanQiuQiao** [comment]
you can hava a  try

**Comment by liborm85** [comment]
@sunilkumarsingh Your sample can not run, because it does not show what is in the `data` variable.
