### ISSUE TITLE
pdf make with ionic2 falls in 

### ISSUE THREAD

**Issue by yokeshvaradhan** [bpampuch/pdfmake#945]
Hi i am trying to make a pdf file using ionic 2, and save it to my local file system using file plugin, I used [pdfmake ](http://pdfmake.org/#/gettingstarted)  to create a pdf file but when i run it i get **ERROR Error: File 'Roboto-Regular.ttf' not found in virtual file system** 

In my index file i added like this
<script src='pdfmake/build/pdfmake.min.js'></script>
<script src='pdfmake/build/vfs_fonts.js'></script>

could someone help me to fix this roboto-regular .ttf file issue

**Comment by liborm85** [comment]
might help you: https://github.com/bpampuch/pdfmake/issues/939#issuecomment-292993073

**Comment by yokeshvaradhan** [comment]
just added import  * as 'pdfmake/build/vfs_fonts.js'

**Comment by jjrchrds** [comment]
can you verify your script for the import, that fails for me.

**Comment by PrabuGovindan** [comment]
How To Group Items ?

**Comment by PrabuGovindan** [comment]
How To Group Items In pdfmake???????????????????????????
