### ISSUE TITLE
Unable to generate pdf report of 10000 records

### ISSUE THREAD

**Issue by kriskarthik** [bpampuch/pdfmake#947]
Hi,

I am also facing the same issue of downloading the 10k records from browser using the pdfmake.min.js.

Tried applying solution from issue #342.

Browser - Chrome - 57.0
Records - 10000
Number of Columns - 8

Query-1 -- I didn't get where the above method need to be added as am new to this js usage.
Query-2 -- Latest version of pdfmake.min.js is directing to different sites, can you share me the appropriate link.

Thanks
Kris

**Comment by liborm85** [comment]
I created this test code:
```js
var tableBody = [];
for (let i = 0; i < 10000; i += 1) {
  var row = [
    i + ' - Col 1',
    'Col 2',
    'Col 3',
    'Col 4',
    'Col 5',
    'Col 6',
    'Col 7',
    'Col 8'
  ];
  tableBody.push(row);
}

var docDefinition = {
  content: [
    {
      table: {
        body: tableBody
      }
    }
  ]
};

var progressCallback = function (progress) {
  console.log(progress);
};

var start = Date.now();

  pdfMake.createPdf(docDefinition).download('out.pdf', null, {progressCallback: progressCallback});

var stop = Date.now();
console.log((stop - start) / 1000, ' seconds');
```

And everything was done correctly. Yes, it took a long time (ca. 10 minutes, depends on computer performance), but the pdf file was returned.

Where is your problem?
