### ISSUE TITLE
How to place icons in pdfmake? Is there any Solution

### ISSUE THREAD

**Issue by Balaraju1** [bpampuch/pdfmake#948]
How to place icons in pdfmake? Is there any Solution

**Comment by cougarten** [comment]
I use an icon font. Complicated but possible. 

In short:
-  Make a font at fontello or something and download it
- convert to dataURL (e.g. via http://dataurl.net/#dataurlmaker )
- add to the fs_js example like the robot font already in there (you can replace or remove the roboto) (strip the "data:application/octet-stream;base64," part from the beginning)
- define font in js:

```
        pdfMake.fonts = {
            Fontello: {
                normal: 'fontello.ttf',
                bold: 'fontello.ttf',
                italics: 'fontello.ttf',
                bolditalics: 'fontello.ttf'
            }
        }
```

- add a style for icons:

`            icon: {
                font: 'Fontello'
            }`
- make a text paragraph:
`
            { text: '', style: 'icon' }, //icon wifi`
- as the text you copy from the fontello-codes.css from the comments (not the escaped value)
