### ISSUE TITLE
Create PDF/A document  

### ISSUE THREAD

**Issue by PDF-Maker** [bpampuch/pdfmake#950]
Is there a possibility to create PDF/A documents?

The best solution would be PDF/A-3 Version, but Version PDF/A-1 should be helpful.

best regards

**Comment by liborm85** [comment]
Not supported.
We need support in pdfkit library (which is used for pdf rendering).

Related pdfkit issue: https://github.com/devongovett/pdfkit/issues/369

**Comment by Akta3d** [comment]
No update on how generate PDF/A-3 ?

**Comment by Cauen** [comment]
@liborm85 PDFkit (v0.13.0) has support for PDF/A-3b
Example code: https://github.com/PadraigGalvin/pdfkit-pdfa-sample/blob/master/generate.js

For those that dont want to wait PDFMAKE implementation, i've created a fork: https://github.com/Cauen/pdfmake/tree/pdfa
NPM: https://www.npmjs.com/package/pdfmake-a

Its updated with latest version of pdfmake 0.2.14 and downgraded version of pdfkit from 0.14.0 to 0.13.0

In this fork, all generated PDFs are PDF/A-3b compliant

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/ca6f874dc1c9c66146f7ce56352291b76482e12b and example https://github.com/bpampuch/pdfmake/commit/4e87757a28ba78a6002b0ddf3aa8225acc703579.

**Comment by liborm85** [comment]
Released in version 0.2.15.
