### ISSUE TITLE
Text at the bottom of the page with no absolute position

### ISSUE THREAD

**Issue by PiotrekPaprocki** [bpampuch/pdfmake#951]
Hi

I've searched thorough docs and issues but I couldn't find an answer. 
Is there an option to add line of text at the bottom of the page that doesn't has `positionAbsolute`? 
I already have `footer` and I need a text line just above it which do not interfere with other page content. 

I could set bigger margin bottom + text with `positionAbsolute` but it's kinda hacky and dirty way.

Thanks

**Comment by liborm85** [comment]
No, this is not possible. Only with `absolutePosition` or `footer`.
