### ISSUE TITLE
Pdfmake on AWS linux, ReferenceError: window is not defined?

### ISSUE THREAD

**Issue by phongyewtong** [bpampuch/pdfmake#952]
Cant figure out whats wrong, i am hosting this on my server using aws linux.

```
const pdfMake = require("pdfmake/build/pdfmake.min.js");
var docDefinition = { content: 'This is an sample PDF printed with pdfMake' };
pdfMake.createPdf(docDefinition).download('haha.pdf');
```

> ReferenceError: window is not defined
>     at Object.createPdf (/home/ec2-user/trh/pattern/node_modules/pdfmake/build/pdfmake.min.js:2:3055)
>     at /home/ec2-user/trh/pattern/server.js:58:10
>     at Layer.handle [as handle_request] (/home/ec2-user/trh/pattern/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/home/ec2-user/trh/pattern/node_modules/express/lib/router/index.js:317:13)
>     at /home/ec2-user/trh/pattern/node_modules/express/lib/router/index.js:284:7
>     at Function.process_params (/home/ec2-user/trh/pattern/node_modules/express/lib/router/index.js:335:12)
>     at next (/home/ec2-user/trh/pattern/node_modules/express/lib/router/index.js:275:10)
>     at urlencodedParser (/home/ec2-user/trh/pattern/node_modules/body-parser/lib/types/urlencoded.js:91:7)
>     at Layer.handle [as handle_request] (/home/ec2-user/trh/pattern/node_modules/express/lib/router/layer.js:95:5)
>     at trim_prefix (/home/ec2-user/trh/pattern/node_modules/express/lib/router/index.js:317:13)

**Comment by Wabbala** [comment]
@Phong Yew Tong
What did you do to fix, just for others to find your solution if they run
into the same.
