### ISSUE TITLE
How To make Table of Content . 

### ISSUE THREAD

**Issue by ashishsober** [bpampuch/pdfmake#953]
Hi , 

I want to implement table of content which has page numbers displayed based on dynamic display of data .Can someone give me any idea how it can done.

         Example :  A-B chapter 1
                    C-D chapter 2 

A,B,C,D have to be dynamic based on page display of the data . 

Thanks

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/126
