### ISSUE TITLE
pdfmake unable to open pdf in chrome browser.

### ISSUE THREAD

**Issue by ninad-d** [bpampuch/pdfmake#954]
pdfmake is unable to open up pdf's in chrome browser. The call to open() just opens up a new tab for a second and then closes automatically, no error are displayed on console. The code I have used to work earlier looks like something went wrong on the browser end. The default example on playground.html also does not works and fails to open up pdf in new tab. This problem is only when I try to open the pdf in new tab.The code to download() pdf then it works fine on chrome.

The chrome version is 57.0.2987.133 (64-bit)

**Comment by Wabbala** [comment]
It sounds like that the pdf "pop-up" is blocked by your browser. Check that
and revert back :)

**Comment by ninad-d** [comment]
That was my first reaction but the pop-up opens up for a split second and then closes and no message related to blocking or errors is displayed. I have not made any changes to browser settings and it was working fine few days back. I tried "allow all pop-ups" and it still failed to open up. The i tried "open pdf files in default application." In this case the pdf file was downloaded by chrome and I was able to use open it using pdf reader. It still does not opens up it in new tab like ealier.

**Comment by ninad-d** [comment]
Update the same code is able to up the pdf in new tab for firefox.

**Comment by Wabbala** [comment]
I think I found the issue. I am also running the same chrome version as you do and the behaviour was indeed also on the playground! But then I saw that my ad-blocker (uorigin) was blocking it somehow ... after disabling it for a moment the playground example worked. So try disable ad-block :)

**Comment by ninad-d** [comment]
@wabbala you got me here, I thought on why not disable ad-block and see. It was not evident to me first since my ad-block was hidden in chrome. It clicked me when I was reviewing my extensions and i saw adblocker. Thanks for the help.

**Comment by brobertsaz** [comment]
I know that this is closed and for me the issue was ad-blocker. I did figure out that if I used .download() or open in same window `pdfMake.createPdf(docDefinition).open({}, window);` it will work with ad-blocker turned on.

**Comment by BAPopov** [comment]
@brobertsaz Thank you exactly what I needed.
