### ISSUE TITLE
Positioning a text box and silent printing

### ISSUE THREAD

**Issue by hamble** [bpampuch/pdfmake#957]
Please excuse me if there is somewhere else I should be asking support queries - I'm new to Github.

PdfMake looks extremely interesting for me, but I have a few questions:

1 - is it possible to specify size and positioning of a text box, so that a piece of text is constrained to a particular area on the page, and ideally to have the option to apply a border/background to that text box? Similarly the positioning of an image at a particular place on the page.

2 - is it possible to 'silent print', i.e. without the browser's print dialog box appearing?

Many thanks

**Comment by liborm85** [comment]
1 - Simple example with absolute position
```js
var dd = {
	content: [
		{
		    absolutePosition: {x: 100, y: 100},
			table: {
			    widths: [100],
				body: [
					['ABCDEFG'],
				]
			}
		},
	]
};
```

2 - No, this is not possible in the browser.
