### ISSUE TITLE
Content are not warping in side cells. 

### ISSUE THREAD

**Issue by sunilkumarsingh** [bpampuch/pdfmake#958]
Hi All,

I have very large content that are not fitted in cell width is there any solution please provide me solutions.

my code snippet is : 
 {
            style: 'tableExample',
               table: {
                       widths: ['*', '*', 'auto'],
                         body: data_list,
                        }
    }

![image](https://cloud.githubusercontent.com/assets/6112878/25230955/9fa8c676-25f3-11e7-83b3-1e528078aec6.png)

![image](https://cloud.githubusercontent.com/assets/6112878/25230970/ad51b95e-25f3-11e7-8e99-ba473db94890.png)

**Comment by Balaraju1** [comment]
giving to fixed width to cell

**Comment by liborm85** [comment]
Answered.
