### ISSUE TITLE
big size customized font load very slow

### ISSUE THREAD

**Issue by solidet** [bpampuch/pdfmake#962]
I come across one issue after I customized font in pdfMake. I already customized the font. I generated new vfs_fonts.js that contains Roboto and simfang (chinese font). The problem is the file is about 15MB and the system loads very slow for the first time because it takes much time loading that font (as I check in network tab). I have to wait for long (on production). Does anybody have solution for this ?

**Comment by liborm85** [comment]
PDF is rendered on the client side and a font file is required. Without download font is not possible. You can try to run as a web worker.
