### ISSUE TITLE
page "background" when changing from portrait to landscape

### ISSUE THREAD

**Issue by jampy** [bpampuch/pdfmake#965]
First of all, thank you for this wonderful project! :-)

I have a problem: My docDefinition uses the `background` property to add header/footers to each page. This works, but I can't find a way to get the dimensions/orientation of the *current* page, since only the page *number* is passed, AFAIK.

In my case I have a footer at a fixed position relative to the bottom of the page. I use ` absolutePosition: { x: 40, y: 800 }` (relative to the top), which works for portrait pages, but of course is wrong for lanscape pages.

In my document I change between portrait and landscape pages, but due to the dynamic content I can't tell  exactly if a certain page number is in portrait or landscape mode.

**Comment by liborm85** [comment]
`header` and `footer` functions have these parameters:
`header: function(currentPage, pageCount, pageSize)`
`footer: function(currentPage, pageCount, pageSize)`

Third parameter contains information about page size and orientation.
