### ISSUE TITLE
Add fonts with symbols

### ISSUE THREAD

**Issue by natcohen** [bpampuch/pdfmake#966]
I would like to add checkboxes (with and without crosses) symbol. I've found the Wingdings 2 font but it doesn't seem to have cmap. When I add this font to my vfs-fonts I get the following error: `Error: No unicode cmap for font`

Anyone has a solution to this problem? Should I use a different font (if yes, which one?) or can I solve this problem? FYI I took this font from Office 2016

**Comment by liborm85** [comment]
You are using an outdated version. Update to the latest version.

**Comment by natcohen** [comment]
@liborm85 what is the latest release? I can see the official repo has downgraded to 0.1.27...I had 0.1.31 somehow!

**Comment by liborm85** [comment]
@natcohen Latest version from official repo is 0.1.27. 
Version 0.1.31 was from probably from https://github.com/pdfmake/pdfmake fork which no longer exists. Active development has moved back here.

**Comment by natcohen** [comment]
Now I'm getting the following error:

```
ERROR TypeError: Cannot read property 'records' of undefined
    at TTFFont.get (http://localhost:8011/javascripts/pdfmake-0.1.27.js:49917:49)
    at new EmbeddedFont (http://localhost:8011/javascripts/pdfmake-0.1.27.js:69934:46)
    at Function.PDFFont.open (http://localhost:8011/javascripts/pdfmake-0.1.27.js:37854:36)
    at PDFDocument.font (http://localhost:8011/javascripts/pdfmake-0.1.27.js:37793:46)
    at FontProvider.provideFont (http://localhost:8011/javascripts/pdfmake-0.1.27.js:19900:76)
    at http://localhost:8011/javascripts/pdfmake-0.1.27.js:21538:45
```

**Comment by liborm85** [comment]
Pdfmake requires utf-8 encoding in html, see:  https://github.com/bpampuch/pdfmake/issues/821 (post https://github.com/bpampuch/pdfmake/issues/821#issuecomment-272920974).

**Comment by natcohen** [comment]
I already had this encoding in my header so I've tried to add it to the script (PUG):

`script(type='text/javascript' src='javascripts/pdfmake-0.1.27.js', charset="utf-8")`

without success... still getting the same error! Did you try my `vfs_fonts.js` file?

**Comment by liborm85** [comment]
I tried your `vfs_fonts.js` file and it works ok.

**Comment by natcohen** [comment]
Did you try to create a pdf with the font?

         pdfMake.fonts = {
                Wingdings2: {
                    normal: 'wingdings2.ttf',
                    bold: 'wingdings2.ttf',
                    italics: 'wingdings2.ttf',
                    bolditalics: 'wingdings2.ttf'
                }
            };

          pdfMake.createPdf({
                content: content,
                defaultStyle: {font: 'Wingdings2'}
           })

Otherwise, could you share your pdfmake.js? How can I try to reproduce this bug online? plunker/fiddle... don't work with such big files (>6MB)

BTW I use Angular 2 (not sure if it affects pdfmake)

**Comment by liborm85** [comment]
Your vfs_fonts.js file contains these font files:
calibri.ttf - works
calibrib.ttf  - works
calibribi.ttf - works
calibrii.ttf - works
wingdings2.ttf - don't work

Probably is related with this issue: https://github.com/devongovett/fontkit/issues/73

**Comment by liborm85** [comment]
Reported: https://github.com/devongovett/fontkit/issues/73#issuecomment-297253481

**Comment by natcohen** [comment]
@liborm85 Can you please implement the upgraded pdfkit so I can test the fix?

**Comment by liborm85** [comment]
@natcohen Implementate into pdfmake is not necessary, just only new build a library, see readme: https://github.com/bpampuch/pdfmake#building-from-sources.

**Comment by liborm85** [comment]
Solved in fontkit issue https://github.com/devongovett/fontkit/issues/73.
