### ISSUE TITLE
Table Formatting messes up on roll over to new page

### ISSUE THREAD

**Issue by LorsK** [bpampuch/pdfmake#969]
The table I have for some reason messes up when it rolls over to the next page.
It is a table in a table and the content is made dynamically so it can have many contacts in the list. 
What could be the issue? 
![image](https://cloud.githubusercontent.com/assets/17942432/25454273/de0f692e-2a99-11e7-96e0-096cbf4aa042.png)

**Comment by LorsK** [comment]
I believe the problem is that the table adds the margins to the top and bottom of the table, but it doesn't see the header on the next page as the 'top' so does not add the header there. 

Also think that is issue occurs because of my table in a table along with the custom layout

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/247
