### ISSUE TITLE
how to draw a frame with pdfmake?

### ISSUE THREAD

**Issue by imoum007** [bpampuch/pdfmake#973]
I'm using pdfmake and I need to put some data in a frame. I looked on internet but I think the injection does not support frame tag
any help plz !!

**Comment by liborm85** [comment]
What should a frame tag do?

**Comment by imoum007** [comment]
something like that. some information in a frame
![frame](https://cloud.githubusercontent.com/assets/5359306/25609120/1493b396-2f1e-11e7-81ee-355422115600.png)

**Comment by liborm85** [comment]
Tag frame is not supported, but can be done using `table`.

Simple example:
```
var dd = {
	content: [
		{
			table: {
			    widths: [200, 100],
				body: [
					[
					    {text: 'TEXT  1', border: [true, true, false, false]}, 
					    {text: 'TEXT  2', border: [false, true, true, false]}
					],    
					[
					    {text: 'TEXT  3', border: [true, false, false, true]}, 
					    {text: 'TEXT  4', border: [false, false, true, true]}
					]
				]
			}
		},
	]
}
```
