### ISSUE TITLE
Leading/hanging paragraph indent

### ISSUE THREAD

**Issue by sethb0** [bpampuch/pdfmake#974]
As far as I can tell it turns out to be really easy to add this feature. I'd send a pull request but I don't have unit tests yet. It's a three-line patch to src/textTools.js

If I send a pull request, will you help me figure out what scenarios I need to test? I'm not very good at working on other people's code yet.

**Comment by liborm85** [comment]
Help is welcome. 
Leading indent was implemented by PR https://github.com/bpampuch/pdfmake/pull/1054.

**Comment by enniosousa** [comment]
PDFmake trim whitespaces, becouse of that ```\t``` does not works.

I found a solution: using [Unicode white spaces](http://jkorpela.fi/chars/spaces.html) works using `\u200B` followed by `\t`

```
{text: '\u200B\t\t\tÉ um fato conhecido de todos que um leitor se distrairá com o conteúdo de texto legível de uma página quando estiver examinando sua diagramação.', alignment: 'justify'}
```

**Comment by mbilaldnc** [comment]
Thanks @enniosousa :) It took me long time to find a solution for that. And only your solution works. 

It's really impossible to make indent while using separate {text: "bla bla", style: 'bla bla'} objects inside of columns like:

```
content = [
  {
    columns: [
    {
        width: '50%',
        text: [
          {text: "bla bla", style: "indentLineWithMarginOrLeadingIndent"},
          ...
        ]
    },
    {
      width: '50%',
      text: [
        { text: "bla bla", style: "indentLineWithMarginOrLeadingIndent" },
        ...
      ]
    }
    ]
  }
];
```

All styles work for these separate text object, except "margin". Actually 'stack' object helps to solve that. It accepts all margin styles but brings other problems like, last stack object of the column object disappears when you insert a new line out of column (if your columns has different heights).

**Comment by onkanya** [comment]
{text: '        "json": "nested"', preserveLeadingSpaces: true},

**Comment by peterbartos** [comment]
No plan to support hangingIndent similarly as leadingIndent?

**Comment by benzhuo** [comment]
> PDFmake trim whitespaces, becouse of that `\t` does not works.
> 
> I found a solution: using [Unicode white spaces](http://jkorpela.fi/chars/spaces.html) works using `\u200B` followed by `\t`
> 
> ```
> {text: '\u200B\t\t\tÉ um fato conhecido de todos que um leitor se distrairá com o conteúdo de texto legível de uma página quando estiver examinando sua diagramação.', alignment: 'justify'}
> ```
'\u200B' will display as square in some font...

**Comment by djcaesar9114** [comment]
The problem of the `\t\t\t` solutions is that when your text is justified the indentation is uneven.
I wanted to make a pull request but I saw there are a lot of (good!) pull requests pending... I think the project is not maintained anymore (I haven't seen any information about it, at least).
