### ISSUE TITLE
Changes in style should not always be line break candidates

### ISSUE THREAD

**Issue by sethb0** [bpampuch/pdfmake#975]
If I write "re<i>mark</i>able" toward the end of a line, I probably don't want it to break as "re<i>mark</i><br>able." I have a test case which shows that pdfmake will do this. (Unfortunately, because tickling the bug is highly dependent on font metrics to get the line to break in the wrong place, you'll need the open-source PT Sans font to run the test case. Unzip the attached file and run "node wrap-test-case.js".)
[wrap-test-case.zip](https://github.com/bpampuch/pdfmake/files/967008/wrap-test-case.zip)

The key part of the test case is
```javascript
const TEXT = [
  { text: 'Celestial Circle—' },
  { text: 'The Faithful Ally', style: 'styled' },
  { text: ', ' },
  { text: 'Gift of Knowledge', style: 'styled' },
  { text: ', ' },
  { text: 'Servant of Infallible Location', style: 'styled' },
  { text: ', ' },
  { text: 'Swift Spirit of Winged Transportation', style: 'styled' },
  { text: ', ' },
  { text: 'Warding the Created Mind', style: 'styled' },
];
```
When this is output with the right margins and font metrics, the line breaks between "Transportation" and the following comma.

**Comment by sethb0** [comment]
My best theory on how to fix this is really, really ugly, btw—could join the contents of all inlines while recording what parts of the joined string have what styles in some kind of "spans" array, run the line-break algorithm over the joined string, then apply the styles back. I hope you can think of something more elegant and easier to implement without bugs.

**Comment by liborm85** [comment]
Sample with default Roboto font:
```js
var TEXT = [
  { text: 'Celestial Circle—' },
  { text: 'The Faithful Ally', style: 'styled' },
  { text: ', ' },
  { text: 'Gift of Knowledge', style: 'styled' },
  { text: ', ' },
  { text: 'Servant of Infallible Location', style: 'styled' },
  { text: ', ' },
  { text: 'Swift Spirit of Winged Transportation', style: 'styled' },
  { text: ', ' },
  { text: 'Warding the Created Mind', style: 'styled' },
];


var dd = {
  pageSize: 'LETTER',
  pageMargins: [30, 54, 27, 45],
  content: [{ text: TEXT }],
  styles: {
    styled: { color: 'dodgerblue' }
  },
  defaultStyle: {
    fontSize: 10.5,
  }
};
```

**Comment by liborm85** [comment]
Implemented by commit https://github.com/bpampuch/pdfmake/commit/551fd999679723a88f6a6e0d6445883320ac1e88.

**Comment by liborm85** [comment]
New version released.
