### ISSUE TITLE
Not working with Chrome

### ISSUE THREAD

**Issue by AndrewPreciado** [bpampuch/pdfmake#976]
I am getting a 404 error when I try to export reports as a pdf.  It works perfectly in Firefox.

I am getting this msg twice
`Failed to load resource: the server responded with a status of 404 (Not Found)`

and then it points to both
`ui-bootstrap-2.4.0.min.js`
and
`:7001/favicon.ico`

I am using a localhost to run the application.

My current version is 57.0.2987.133

Any ideas or help would be greatly appreciated!

**Comment by Wabbala** [comment]
Ad block by any chance?

**Comment by AndrewPreciado** [comment]
Yup!  That did it.  Thank you
