### ISSUE TITLE
Broken pagination for tables

### ISSUE THREAD

**Issue by ammulder** [bpampuch/pdfmake#977]
I have a table with two columns.  Each row has text in the left column and an image in the right column, and the image is taller than the text.  All the rows together are several pages long, though individual rows are smaller than a page.

My expectation is that any individual row is completely on one page or another.

The actual output is that when you get to a page break, the text in the left column appears on page N, and the image and the borders for both left and right columns are on page N+1.  In other words, there's no border around the text, and the border that was supposed to be around the text is around a blank space on the next page instead.

It would be great if this could be fixed to keep all the content for a row on the same page (in this page, I would expect the text to be moved to page N+1 if the image and cell borders are going to be on page N+1).

Sample PDF with the problem (ignore the first page; the table in question starts on the second page):
http://opentools.org/table-layout-error.pdf

I can't think of a workaround because columns behave the same way.  What I'd need I guess is a command to "page break if less than X vertical space remaining on the page" because I can figure the height of the row based on the height of the image.

Finally, of lesser importance, the image seems to have a lot of whitespace above it in its cell; I'm not sure why it's not aligning with the top of the cell and making the row shorter.  If that's not related to the pagination problem I can make a separate issue for it.

**Comment by ammulder** [comment]
Hmm, seems to be fixed by `{table: {..., dontBreakRows:true}}`

I didn't see that in the docs, and I'm not sure why it's not the default, but it does cure the page break problem.

**Comment by ammulder** [comment]
And, the mystery whitespace was actually part of the image I put in there.

So, user error, then.  :)

**Comment by liborm85** [comment]
duplicate with: https://github.com/bpampuch/pdfmake/issues/371
