### ISSUE TITLE
Not working with IE11

### ISSUE THREAD

**Issue by AndrewPreciado** [bpampuch/pdfmake#978]
I am exporting tables using pdfmake as well as exporting a ui-grid.
Using IE (ver. 11.1066.14393.0).

I am using 
`.open()`
because I want to the pdf to export to a new tab.

When I hit the button to export the report, it opens a blank page with a msg that says
"Do you want to allow this website to open an app on your computer?"

If I hit allow it opens another pop up that says
"You will need a new app to open this blob"

With an option that gives me a chance to look for an app in the Microsoft store.

I will click that link and it shows no results for "blob"

Any ideas would be greatly appreciated.  Thank you.

**Comment by liborm85** [comment]
In Internet Explorer 11 is supported only `download()` method.
Supported browsers are described here: https://github.com/bpampuch/pdfmake/issues/800

**Comment by AndrewPreciado** [comment]
Good to know.

Is there a way for me to use both open() and download() depending if they are using say firefox/chrome or IE11?

**Comment by liborm85** [comment]
Yes, use browser detection (http://stackoverflow.com/questions/2400935/browser-detection-in-javascript , or other link on google) and then according to call `open()` or `download()`.

**Comment by jeco123** [comment]
We need to use the open() method for the main browsers ie10 / ie11 / chrome etc...
When the open() method will be available?
