### ISSUE TITLE
TypeError: this.font.createSubset is not a function | pdfmake.min.js:27:18037

### ISSUE THREAD

**Issue by ProfessorChill** [bpampuch/pdfmake#979]
This occurs whenever the bLangChn is true on my website to change the text to a Chinese compatible text. I believe that this occurs at this area of my code, if you need more information please ask.

```JS
pdfMake.fonts = {
     Roboto: {
          normal: 'Roboto-Regular.ttf',
          bold: 'Roboto-Medium.ttf',
          italics: 'Roboto-Italic.ttf',
          bolditalics: 'Roboto-MediumItalic.ttf'
     },
     SimSun: {
          normal: 'simsun.ttc',
          bold: 'simsun.ttc'
     }
};

pdfMake.createPdf(docDefinition).open();
```

**Comment by liborm85** [comment]
TTC font format is TrueType Collection which contains a collection of fonts

You have to define which font you want to use.

Example:
```js
pdfMake.fonts = {
  
  PingFangSC: {
    normal: ['pingfang.ttc', 'PingFangSC-Regular'],
    bold: ['pingfang.ttc', 'PingFangSC-Semibold'],
  }

};
```

**Comment by ProfessorChill** [comment]
Ah, thank you very much @liborm85 I didn't know that.
I was a bit confused on why that wasn't working but down this makes a lot of sense.
