### ISSUE TITLE
Line numbers

### ISSUE THREAD

**Issue by JimSangwine** [bpampuch/pdfmake#982]
Possibly a feature request, but hopefully there's a way already.

I would like to be able to add line numbers, including in columns like this:

```
wibble     1   wibble    4    wibble    7
wibble     2   wibble    5    wibble    8
wibble     3   wibble    6    wibble    9
```
Is this currently possible?

Thanks for an excellent library - using JSON is sooooo much nicer than the usual approaches 👍

**Comment by liborm85** [comment]
In first column is `wibble     1` on line 1 and `wibble     2` on line 2  `wibble     3` on line 3, **but in second column is  `wibble    4` is on line 1** - So it probably will not line numbers.

This will probably be this feature request - https://github.com/bpampuch/pdfmake/issues/604 ("snaking columns"). And same ordered list (`ol`) to counting.

**Comment by JimSangwine** [comment]
Thanks for the reply @liborm85 - I understand the difficulty.

Making an OL would mean splitting text up into lines before rendering the PDF.
How about automatic line numbering of flowed / wrapped text without columns? Is that possible?

**Comment by liborm85** [comment]
I do not think anything to solve it.
