### ISSUE TITLE
Values not wrapping in table

### ISSUE THREAD

**Issue by holly-weisser** [bpampuch/pdfmake#984]
I've seen a few issues like this already submitted, but most have been closed with advice that does not help me.

I'm generating a PDF with a table with a lot of columns, with values that can be very long (like ID numbers, strings of text).  When the PDF is created, the columns themselves take up the expected amount of space, but the values within the columns (including column headers) are not wrapping appropriately.

I have tried setting the columns to all star, all auto, all a fixed number, and all a fixed percentage.  Again, the columns/cells within the table display as expected, but the values in those cells are not wrapping consistently.  Most values end up overlapping adjacent columns/cells.

![image](https://cloud.githubusercontent.com/assets/5940753/25678167/c9b2a16c-3016-11e7-9959-de5fe7d1c1df.png)

**Comment by liborm85** [comment]
duplicate: https://github.com/bpampuch/pdfmake/issues/204
