### ISSUE TITLE
Image in header is mixed up with the first image of the content on download or using the getBuffer

### ISSUE THREAD

**Issue by kovacs-tamas** [bpampuch/pdfmake#985]
I found a strange bug when i use an image in the header.

<img width="708" alt="export-problem" src="https://cloud.githubusercontent.com/assets/7418668/25697225/73f40730-30ba-11e7-9ea4-f3f532353b3f.png">

If i use the getBase64 method for preview, the pdf looks good, the images are on their proper place.

But using the getBuffer or download methods results a strange output. The image in the header will be overwritten with the first image in the content.

Tested with pdfmake v0.1.28 (90b9a69)

**Comment by liborm85** [comment]
Can you do a simple example of docDefinition executable on http://pdfmake.org/playground.html ?

**Comment by kovacs-tamas** [comment]
I made an example, please use the following js file: https://gist.github.com/kovacs-tamas/d7cbeb66f190be2cae20115cd79b0714

It worked well on the playground and this helped me to find out what can be the problem.

I tried to implement a mobile friendly solution which can work on weaker phones also. So i created the pdf object once and reused it for the preview and the download both.

You can easily reproduce it, with this example:

    var pdf = pdfMake.createPdf(contentDefinition);

    pdf.download('first-try.pdf'); // the images are fine

    pdf.download('second-try.pdf'); // the images will be mixed up

**As a workaround i solved the problem with cloning the original object before doing any exports or downloads.**

**Comment by liborm85** [comment]
It is not possible to run multiple generations over one definition. Because pdfmake does not internally clone of docDefinition, but uses this variable for internal use.

As you write, the solution is cloning original docDefinition object. Or generate only once by `getBase64` (or `getBlob`, `getBuffer`) and save it to variable. And use this variable for preview and than for download.

**Comment by kovacs-tamas** [comment]
Okay, thanks. I propose to mention this solution in the documentation

**Comment by robdcal** [comment]
Just want to say thanks to @kovacs-tamas and @liborm85 - this resolved the issue for me.

For any beginners (like me), I cloned the docDefintion object using the following code:

`var newObject = jQuery.extend(true, {}, oldObject);`

This was found in [this StackOverflow response](https://stackoverflow.com/a/122704/7813053).
