### ISSUE TITLE
QR node background/foreground point to data instead of options 

### ISSUE THREAD

**Issue by nikolaglumac** [bpampuch/pdfmake#986]
Hi there and thanks for an awesome plugin!

I've been trying to customize QR code node by adding "background" and "foreground" options but with no success. I've looked into the source and it seems like both of these options are wrongly extracted from data instead of options object here:
https://github.com/bpampuch/pdfmake/blob/master/src/qrEnc.js#L743-L744
I believe these lines should read:
```
var background = options.background || '#fff';
var foreground = options.foreground || '#000';
```

After I have locally done the same I was able to use the following node without issues:
```
{
        qr: 'Turn this text into QR code',
        alignment: 'center',
        background: '#000',
        fit: 90,
        foreground: '#fff',
},
```

Thanks for looking into this!

**Comment by liborm85** [comment]
Added support for colored QR codes by commit https://github.com/bpampuch/pdfmake/commit/561abdeb0da24ae928641b363e8ba75517dc9b47 and added example by commit https://github.com/bpampuch/pdfmake/commit/3815277fd860320c907731a70275b489968663b5.

**Comment by nikolaglumac** [comment]
Thanks @liborm85 - works great now ;)
