### ISSUE TITLE
Saving Generated pdfmake PDF or attaching to email

### ISSUE THREAD

**Issue by thincmedia** [bpampuch/pdfmake#989]
Hi, Thanks to bpampuch for such a great code work. 

 I have struggled for the past 3 days to get the generated pdf either saved in my local filesystem or emailed as an attachment to the user. I have considered various threads posted here on the issue but none seem to be working in scenario. 

I have followed these threads:

https://github.com/bpampuch/pdfmake/issues/489
https://github.com/bpampuch/pdfmake/issues/720

However I'm not winning.

I also suggest that guides on emailing the pdf as attachment be added to the playground repository.

Thanks again for the great code work hope someone can help.

**Comment by liborm85** [comment]
How to save generated pdf into file is shown here: https://github.com/bpampuch/pdfmake/blob/master/examples/basics.js (saving file is in line 22)
And then you can attach this file to the e-mail.

**Comment by thincmedia** [comment]
Thanks a mil liborm85 your response was lost in my gmail spam. Thanks a mil for the help. Great stuff.

**Comment by jasminder** [comment]
Thanks @marmeden

**Comment by miradario** [comment]
what is Buffer @marmeden ?

**Comment by MohammedHafiz** [comment]
how we can send the same pdf using sendgrid??
