### ISSUE TITLE
Text wrap rules changed?

### ISSUE THREAD

**Issue by iAmcDiddy** [bpampuch/pdfmake#999]
I just upgraded from 0.1.17  to  0.1 28

One data value that is going into (a fixed-width column of) a table looks like this:
43.0554700,-76.0633570,75.00 m,0.00 m,,Unknown,0,0

in version 17 the value wrapped like this in the PDF:
43.0554700,-76.
0633570,75.00 m,0.00
m,,Unknown,0,0

in version 28 the same value is being wrapped like this in the PDF:
43.0554700,-76.0633570,75.00
m,0.00 m,,Unknown,0,0

That change causes overlap as shown below.  Is this a known issue?
![image](https://cloud.githubusercontent.com/assets/6363477/26175542/0066d218-3b21-11e7-9499-76405644f89b.png)

**Comment by liborm85** [comment]
In version 0.1.23 was added the Unicode Line Breaking Algorithm (`UAX #14`) for splitting words. Some texts are now wrapped in different ways.
Problem with wrapping long words is known issue https://github.com/bpampuch/pdfmake/issues/204, it was fixed (see https://github.com/bpampuch/pdfmake/issues/204#issuecomment-302877081). The fix will be in a new version.

**Comment by scottyh527** [comment]
Can someone explain how text wrapping is handled currently, I'm looking to do a function if text starts to wrap to create a stack, any help would be great
